### PR TITLE
Loadout runtime fix

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Fix runtime when using the loadout vendor as a non-squad role (try to access a null list). Players won't notice this

## Changelog
:cl:
fix: Loadouts vendor will no longer runtime when equipping a loadout as a non squad role
/:cl:

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
It would be nice if you shared some technical details like at least the type of error if not part or all of the stack trace.

**Comment by BraveMole** [comment]
null list accessing yeah

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
Add a cl and add more descriptive pr bodies so people dont have to ask in future plsthanks

**Comment by SplinterGP** [comment]
> 
> 
> Add a cl and add more descriptive pr bodies so people dont have to ask in future plsthanks

^

**Pull request merged**
