### PR TITLE
runner/hunter move slower now

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
no longer are they mach 2

## Why It's Good For The Game
why does this t1 and t2 literally move at -2 with weeds+frenzy

## Changelog
:cl:
balance: runner and hunter nerfed minorly speedwise
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -135. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
freeze and froze

**Review by Hughgent — APPROVED** [review]
variable changes

**Comment by AdamElTablawy** [comment]
Nerfing xenos when they've already got basically zilch for unique mechanics and people straight up don't enjoy playing them isn't really a good idea. 

Give xenos some more content before you keep focusing on rebalancing them or they're going to stall out in terms of playerbase.

**Comment by MLGTASTICa** [comment]
> Nerfing xenos when they've already got basically zilch for unique mechanics and people straight up don't enjoy playing them isn't really a good idea.
> 
> Give xenos some more content before you keep focusing on rebalancing them or they're going to stall out in terms of playerbase.

This is a balance change based on the  fact that hunters are extremly tanky and can tank PBs while spinning around people. Rebalancing keeps the game fresh actually, and no one enjoys PB'ing hunters and seeing them run away at half-health either. Theres plenty of xeno features PR'ed such as 2 new castes and other abilities.

**Comment by Mannybrado** [comment]
bruh. hunter maybe but the only thing that keeps runners alive is their speed. 👎

**Comment by Texicos** [comment]
"why does this t1 and t2 literally move at -2 with weeds+frenzy"
Fastest Caste + Max speed buffs = Speed. Debuffing the castes themselves will just kill their usefulness. Go nerf weed speed back or something.

**Comment by spookydonut** [comment]
Non-maintainer requested balance PR during balance freeze

**Pull request closed without merging**
