### PR TITLE
Seasonal Galore

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request
Adds essentially the rest of the import guns to seasonals, shuffles some guns around for more coherent seasons
## Why It's Good For The Game
These guns are essentially side grades of what marines get (skorpion= MP19, FAMAS = AR18, Garand/SVD = DMR, 1911 = P45, Levergun = Repeater etc), and seasonals exist to cycle req hell import guns.
## Changelog
:cl:
add: added more seasonal guns
/:cl:

### CODE REVIEW

**Comment by Otterwatch** [comment]
Everything looks fine except for the FAMAS, there's a reason why it was removed from seasonals. The main limitation of the FAMAS is its limited mag capacity making the mags you do have important to use at the best time. It will probably be the best seasonal again if you add it.

**Comment by maikilangiolo** [comment]
The FAMAS is strikingly similar to the T18 marines already get. 35% smaller mag, 20% more damage, really fast ROF. Same underbarrel attachments, FAMAS has 0.5 faster auto but 0.5 slower burst and smaller burst size. Has 1 scatter vs 0.

They're the same gun, with only a magazine size difference.

**Comment by ivanmixo** [comment]
They are **not** the same gun. The famas has a 20% damage buff and a way higher rate of fire. It was in seasonals before and it wasn't okay.

**Comment by Naaanii** [comment]
FAMAS is an ERT gun yeah. Everything else seems fine.

**Comment by Losenis** [comment]
I've yet to see anyone complaining about the 1.2 dmg multiplier ever complain about M16 in its entirety of seasonal rotation history despite also having a 1.2 dmg multiplier on the exact same bullet

**Comment by ivanmixo** [comment]
It doesn't have an smg fire rate

**Comment by Losenis** [comment]
bfa t18 says hi

**Comment by maikilangiolo** [comment]
The T18 has SMG firerate without BFA. With BFA, it has the same DPS as the FAMAS. Without, it only has 30 less DPS but 200 more damage per magazine (bigger mag). FAMAS cope is just that



> FAMAS is an ERT gun yeah. Everything else seems fine.

Every other gun is ert gun too. Garand, Ak, M16, skorpion etc etc. FAMAS isn't special

**Comment by ivanmixo** [comment]
Yes, just ignore how innacurate the bfa t18 is compared to famas.

**Comment by Losenis** [comment]
If you're not running a recoil compensator on your bfa t18 it's 100% skill issue

**Comment by ivanmixo** [comment]
Even with bfa its atrocious while moving

**Comment by Al-1ce** [comment]
FAMAS mag size really kills its potential in longer engagements compared to the AR-18, I've witnessed this personally when it used to be a seasonal.

PR feels fine to me.

**Comment by Joe13413** [comment]
FAMAS is fucking insane bro. 400 RPM with a damage of 30 makes it's effective DPS... OVER TWO HUNDRED??
Famas will be the new PPSh bro

**Comment by Lumipharon** [comment]
I get the FAMAS opposition, although I would just like to point out the M16 is just a straight FAMAS+

**Comment by ivanmixo** [comment]
What's the point. Just don't put famas in. Keep it in req.

**Comment by Losenis** [comment]
coping about dps of a 24 round mag gun while akimbotards keep running around with MP19s

**Comment by ivanmixo** [comment]
Comparing melee guns to a famas which can be used at medium range+...

**Comment by Losenis** [comment]
i forgot ravs crushers hunters and bulls all have guns too that let them fight at not-melee ranges, my bad lmfao

**Comment by maikilangiolo** [comment]
> Good idea but as comment show the seasonal is X gun but better issue needs to be fixed first

You could have commented that and I'd have removed the FAMAS instead of closing the whole PR

**Pull request closed without merging**
