### PR TITLE
Sentry(especially mini) small rebalance

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
this makes sentries not get knocked out by punch and forward charge automatically and gives a durability buff for the mini sentry

## Why It's Good For The Game
write this later

## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more mechanics or gameplay changes
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
What makes you believe Sentries being knocked is bad for balance? It may be annoying but that is pretty intentional. With that said, as somebody who plays warrior often, I would support the mini-turret durability buff in a separate PR.

**Comment by SplinterGP** [comment]
> What makes you believe Sentries being knocked is bad for balance? It may be annoying but that is pretty intentional. With that said, as somebody who plays warrior often, I would support the mini-turret durability buff in a separate PR.

is it not ? how you think mini sentries would work at all if they always have to be behind barricades otherwise a xeno with a very low CD ability can just go and IMMEDIATELY knock it down, Warrior punch already does 4x damage to stuff, it doens't need to immediately knockdown stuff, for UAC ones, that should be behind cades of course, thats basically missing 20 damage from knocking it down, one punch and slash should do, Mini sentries is another whole story, those should be more resistant so that makes sense

**Comment by Lefunny** [comment]
> > What makes you believe Sentries being knocked is bad for balance? It may be annoying but that is pretty intentional. With that said, as somebody who plays warrior often, I would support the mini-turret durability buff in a separate PR.
> 
> is it not ? how you think mini sentries would work at all if they always have to be behind barricades otherwise a xeno with a very low CD ability can just go and IMMEDIATELY knock it down, Warrior punch already does 4x damage to stuff, it doens't need to immediately knockdown stuff, for UAC ones, that should be behind cades of course, thats basically missing 20 damage from knocking it down, one punch and slash should do, Mini sentries is another whole story, those should be more resistant so that makes sense

They are smaller and cheaper version of the normal sentrys supposed for supress or backup fire, behind marines if a xeno manage to get in there idk why it shouldt be knocked down

**Comment by SplinterGP** [comment]
they are not smaller and cheaper version of the normal sentries, theyre supposed to be sentries that are useable outside of just a spot you put them there, hence why its easily able to carry them around in engineer backpack and all, not having a barricade means a xeno will easily hit it with a punch or anything since instantly knocking down a sentry is better than just using it in a marine to give a bit of damage, even more if you consider youre NOT gonna make cades aroud mini sentries

**Comment by Lefunny** [comment]
> they are not smaller and cheaper version of the normal sentries, theyre supposed to be sentries that are useable outside of just a spot you put them there, hence why its easily able to carry them around in engineer backpack and all, not having a barricade means a xeno will easily hit it with a punch or anything since instantly knocking down a sentry is better than just using it in a marine to give a bit of damage, even more if you consider youre NOT gonna make cades aroud mini sentries

Thats exactly the point of the thing if it got no cades to defend itself then why should it be more resistant they are made to be placed mid fight and are supposed to be breaked if xenos managed to get throught unga balls or any sort of another situation

**Comment by SplinterGP** [comment]
> > they are not smaller and cheaper version of the normal sentries, theyre supposed to be sentries that are useable outside of just a spot you put them there, hence why its easily able to carry them around in engineer backpack and all, not having a barricade means a xeno will easily hit it with a punch or anything since instantly knocking down a sentry is better than just using it in a marine to give a bit of damage, even more if you consider youre NOT gonna make cades aroud mini sentries
> 
> Thats exactly the point of the thing if it got no cades to defend itself then why should it be more resistant they are made to be placed mid fight and are supposed to be breaked if xenos managed to get throught unga balls or any sort of another situation

Its exactly made more resistant since its made to be used outside of FOBHugging and all, if you want to break it just slash it ? its not like xenos can literally just pushpast through marines and all, Plus its not always you have 10 marines together to defend the turret, i still fail to see how a skill completely disabling them with 1 click and a Low CD is needed at all

**Pull request closed without merging**
