### PR TITLE
Derringer has instant suicide speed.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Creates a new gun var suicide_delay.
Default suicide_delay is 40.
Sets derringer to suicide_delay = 0.
## Why It's Good For The Game
Gives the Derringer a clear niche.
## Changelog
:cl:
add: Derringer can now instant suicide.
/:cl:

### CODE REVIEW

**Comment by Coastfront** [comment]
At last, fervidly reaching unto their pristine river, may the hands of the defiled at once pray for their sin to be swept away as silt.

For shall their arms never touch this cloud of grandeur, then may they grip this ending rain.

**Comment by Pariah919** [comment]
Just make it deal extra damage to mobs in crit, rather than.. whatever this is.

**Comment by FIXTHERADBOXPLEASE** [comment]
Keyed PR.

**Comment by Losenis** [comment]
Me on my way to accidentally suicide after leaving the derringer on active hand instead of gauze because I pixelhunted the mouth instead of head due to being on the move to use numpad

**Comment by maikilangiolo** [comment]
> Just make it deal extra damage to mobs in crit, rather than.. whatever this is.

If you're in crit, you can't shoot yourself

**Comment by Joe13413** [comment]
> Me on my way to accidentally suicide after leaving the derringer on active hand instead of gauze because I pixelhunted the mouth instead of head due to being on the move to use numpad

what is up with this lozenus guy talking about the most schizo situations that'd never happen in these github comments. I see it all the time where he makes like conspiracy theories as to why you shou;dnt merge something and at this point i cant even tell if he's fucking with us all

**Pull request closed without merging**
