### PR TITLE
You need to stay still to make acid wells.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
You need to stand still to make acid wells, 1 second.

## Why It's Good For The Game
The fact you can make acid wells anytime to extinguish yourself is funny but pretty unintentional

## Changelog
:cl:
balance: Acid wells take time to make, 1 second.
fix: Acid wells take time to be made.
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
It already takes plenty of plasma to make one. Let it be.

**Comment by KornFlaks** [comment]
I hate to say it, especially since this will massively buff flamers which is already incredibly suppressing, but yea this does need to be done.

Halve the creation plasma maybe as it now requires a standstill time to create?

**Comment by Lumipharon** [comment]
> I hate to say it, especially since this will massively buff flamers which is already incredibly suppressing, but yea this does need to be done.
> 
> Halve the creation plasma maybe as it now requires a standstill time to create?

Plasma well cost is to prevent the spammability of acid wells. If you halve the cost you make it exponentially easier to spam wells over huge areas, which makes it grossly slower to push for marines if they can't just OB the lot.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Feel like acid wells are in a perfect place rn, why that pr ?

**Comment by Pariah919** [comment]
>Feel like acid wells are in a perfect place rn, why that pr ?
>
The ability to make acid wells on the moves seems unintended to me, considering you can make it to instantly extingush while being chased by marines. If you want, I can make it take even less, something like half a second so you can't make it on the move and nothing more.

**Comment by ThelastArchiver** [comment]
> 

to be fair the amount of casts that can do that is soly limited to queen shrike and boiler and hivelord when hes primordial making it you have to stop to do this would make it easy for marines to run down burning shrikes and queens

**Comment by BraveMole** [comment]
no

**Pull request closed without merging**
