### PR TITLE
Remove Big Red's cave miners near LZ2

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

image

RipGrayson's approval.

image

Marines can make a very strong fortication that can easily ward off xenomorphs. There is a 1/5 chance that there will be two plat miners for marines to occupy and can have requisition supply marines with stronger fortications and weapons no matter what the xenomorphs throw at them.

## Changelog

:cl:
del: Remove Big Red's two plat miners and 1 normal miner near LZ2
balance: Prevent a 1/5 chance for marines to camp near LZ2 on two plat miners
/:cl:

### CODE REVIEW

**Comment by Breadeagle** [comment]
There's at least one other modular that has easy (relatively) plats in the zone. Its harder in some ways compared to other maps because its caves, but they're also probably the last remaining sets of relatively "free" miners which are easily taken enroute to other objectives, straight off fob.

**Comment by DemonOfHatred** [comment]
good change

**Comment by Aroliacue** [comment]
Req snowball bad, good PR

**Comment by SimplySmiley123** [comment]
God forbid marines actually do miners I guess.

**Comment by Isy232** [comment]
Miners are typically risky to take given they require stationing marines away from an objective point, those 2 plats + plasma were so close to LZ 2 and red disk that it made it too easy to take them all.

**Comment by SimplySmiley123** [comment]
> Miners are typically risky to take given they require stationing marines away from an objective point, those 2 plats + plasma were so close to LZ 2 and red disk that it made it too easy to take them all.

At the same time it's, the only time marines would consistently do the miners.

IMo that's also something to look into as to _why the hell are miners barely ever done in any other situation._

**Pull request merged**
