### PR TITLE
Removes neuraline from medic vendors

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title

## Why It's Good For The Game
tivi said to do it idk, merge this or the cost increase

## Changelog
:cl:
balance: removed neuralien from medic vendor
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
Do https://github.com/tgstation/TerraGov-Marine-Corps/pull/5192 instead.

If needed, we can up the price even MOAR, but I'd rather not full-remove it from the game.

**Review by Hughgent — APPROVED** [review]
Choose one or the other.

**Comment by Pariah919** [comment]
id rather have uhh the price increase but either goes

**Comment by Hughgent** [comment]
Choose one of the two PR's to keep, and close the other.
#5192

**Comment by spookydonut** [comment]
@Pariah919 please use proper PR names and give proper descriptions

**Pull request closed without merging**
