### PR TITLE
Fixes robots screams

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request

title

## Why It's Good For The Game

they werent playering before
fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10843

## Changelog
:cl:
fix: fixes robots screams
/:cl:

### CODE REVIEW

**Comment by Calyxman** [comment]
i was literally in the middle of doing this

**Comment by Calyxman** [comment]
What the fuck that's broken as hell

**Comment by hyper2snyper** [comment]
> i was literally in the middle of doing this

skill issue

**Comment by Calyxman** [comment]
does not fix plurals iirc, you only added neuter
i already made a PR that fixes this (we don't need two PRs for the same thing)

**Pull request closed without merging**
