### PR TITLE
Bull now gets all charges at Young instead of having them be time gated

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

Pretty self explanatory, Bull gets all charges at Young instead of Headbutt at Mature and Gore at Ancient. This is a "buff" but is really more of a QoL change, Gore is not so much stronger than Headbutt (in most cases it is not stronger at all) that it should be locked until Ancient. Gore and Headbutt are used in different situations and not getting your other form of charge until Ancient kind of sucks and makes Bull gameplay less interesting until you hit that point. 

## Why It's Good For The Game

Gore is not directly better than Headbutt, it is more of a side grade used in a different situation. Unlocking it at Elder makes more sense, Ancient lock sucks and makes Bull less interesting until you hit Ancient which takes a fair bit of time. This is barely a buff at all.

## Changelog
:cl:
balance: Bull gets all charges at Young instead of time gated to Mature and Ancient
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
Without even kidding, this is pretty whatever letting the bull skills being unlocked at age, this probally make most bulls dont die trying to crush a marine in young or elder.

**Comment by Sebbe9123** [comment]
Time gates dumb especially for things like this. Just give it to Bull from the getgo.

**Comment by Hekzder** [comment]
> Time gates dumb especially for things like this. Just give it to Bull from the getgo.

Not opposed. If maintainers say it's chill I'll give it to them at Mature. But anything is better than nothing.

**Review by BraveMole — COMMENTED** [review]
I've never really got the timegate abilities, i'd be up to give bull everything at young like every other castes

**Comment by Hekzder** [comment]
> I've never really got the timegate abilities, i'd be up to give bull everything at young like every other castes

Done. Very cool.

**Review by BraveMole — APPROVED** [review]
Fine by me, bull is still shit anyway

**Pull request merged**
