### PR TITLE
Shields slow you down heavily

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
shields slow you down heavily instead of being minor

## Why It's Good For The Game
shields are innanely tanky for how effectively unheavy they are, overall this should make them more bearable, that or I could reduce their hard armor to 0 for melee.

## Changelog
:cl:
balance: shields slow you down heavily
/:cl:

### CODE REVIEW

**Comment by JackTheJackhammer** [comment]
People only use shields for melee, which makes that particular marine basically null and void.

**Comment by Walarks** [comment]
What if huge slowdown (1+) and durability buff or make shield not qdel at 0 durability?

**Comment by AnCopper** [comment]
Shields are only used for Melee, so this would completely go against that, I'd rather an item be too powerful than useless.

**Comment by Pariah919** [comment]
i have a better form

**Pull request closed without merging**
