### PR TITLE
Add requirement to autodoc new procs and vars to Contributing.md

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

As per title

### CODE REVIEW

**Review by Hughgent — APPROVED** [review]
LGTM

**Review by spookydonut — CHANGES_REQUESTED** [review]
copy the tg code docs format pls

**Comment by TiviPlus** [comment]
Didnt you make our linter check for 
```
/**
  *
  */
```
only

**Comment by Hughgent** [comment]
```
\**thing1
  *thing2
  *thing3
  *\
```
This actually produces a bulleted list which I don't think is what is desired or expected.

**Comment by TiviPlus** [comment]
> Didnt you make our linter check for
> 
> ```
> /**
>   *
>   */
> ```
> 
> only

@spookydonut

**Comment by TiviPlus** [comment]
image

**Pull request merged**
