### PR TITLE
Adressing lava outpost feedback & fixing a few mistakes

### PR DESCRIPTION
**Pull request by mrhugo13**
## About The Pull Request
Adds guard railings to alot of the bridges around lava outpost to make gameplay less frustrating, still can be thrown off into the lava though if you are not careful.

Removed alot of outpost lights that weren't either there before at the old lava outpost or were infront of entrances as a piece of feedback i got was that Lava Outpost was too bright, even with the relatively lava-less areas.

Made bridges wider as this was another piece of feedback i got.

Moved the central silo point towards near the shack as a piece of feedback i got with survivors trying to reach security without getting blasted by every xeno.

Got rid of some walls that were inside of windows due to my own fault.

Fixes a directional button at the vault that for some reason wasn't linked with the shutters it was right next to.

Further covered LZ1 fully in shutters so you can't just cut in/out as said by tiviplus.

And finally from what i can recall i sweeped up what was hopefully the last piece of an area being far away from where it's originated from just for it to be used on the lava vault/nuke dome's opening shutters.

[Compare & Contrast](https://mdb.affectedarc07.co.uk/Files/158907057/1688380290/0/diff.png)
[Before](https://mdb.affectedarc07.co.uk/Files/158907057/1649450827/0/after.png)
[After](https://mdb.affectedarc07.co.uk/Files/158907057/1688380290/0/after.png)

## Why It's Good For The Game
Feedback that was warranted got adresses as above and fixed things which were entirely a result of mistake and my lack of noticing it.

Guard rails which will help with the frustration that i have heard come across as a result of shrikes/warriors and whatever making bridges and absolute nightmare to cross and as such less fun for marines, this will hopefully remedy some of that but still make bridges something which you shouldn't stand in the middle of just because.

Outpost lights were causing the map to be too bright from some feedback as mentioned before, the lava is allready enough i don't wanna make xenos completely miserable _and_ visible in every spot of the map.

Central silo made it too easy for the xenos to hold a very important chunk of the map on lockdown which was not my intention and as such has been remedied and put more towards near the shack, which is also nearby a crash location.

Walls inside of windows is bad and defeats the purpose of windows.

Bridges wider to also, once again, make bridges less of a misery towards both xenos & ~~talls~~ humans alike.

Directional button not linked with the shutters it is right next to is a bad thing.

The area thingy as mentioned before should also help if tivi, as they have mentioned in the discord, would wish to do any sound enviroment stuff, that and it also means bodies wouldn't be reported far away from where they actually were.

## Changelog
:cl: Vondiech
add: Adds guard railings to alot of the bridges around lava outpost to make gameplay less frustrating, still can be thrown off into the lava though if you are not careful.
del: Removed alot of outpost lights that weren't either there before at the old lava outpost or were infront of entrances as a piece of feedback i got was that Lava Outpost was too bright, even with the relatively lava-less areas.
tweak: Made bridges wider as this was another piece of feedback i got.
tweak: Moved the central silo point towards near the shack as a piece of feedback i got with survivors trying to reach security without getting blasted by every xeno.
fix: Got rid of some walls that were inside of windows due to my own fault.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by TiviPlus** [comment]
I dont see shutters all the way around the LZ, couldnt you just cut through a wall to leave?

**Review by TiviPlus — APPROVED** [review]

**Comment by mrhugo13** [comment]
> 
> 
> I dont see shutters all the way around the LZ, couldnt you just cut through a wall to leave?
dreammaker_2021-01-12_14-37-01

Now adressed as-per you mentioned

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-15). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
