### PR TITLE
Hot Foods and Drink vendors now have an infinite supply of foods and drinks.

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
Better consistency, medbay won't run out of food in the long run. Bartenders are more useful.
Shouldn't affect balance as Xenos can melt groundside vendor variants.
## Changelog
:cl:
balance: Hoot foods and drink vendors now have infinite contents.
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by Serxule** [comment]
INFINITE GLIZZY

**Comment by Al-1ce** [comment]
Would this fix the issue of certain foods not spawning in loadouts? I generally take a bicaridine bar or two with me, but it never saves.

**Comment by Naaanii** [comment]
> Would this fix the issue of certain foods not spawning in loadouts? I generally take a bicaridine bar or two with me, but it never saves.

I believe loadout code is different as it should spawn in loadouts unless depleted and I don't think bicardine bars deplete quickly if at all during most rounds.

**Comment by maikilangiolo** [comment]
secret marine buff powercreep...how can he keep getting away with it

**Pull request merged**
