### PR TITLE
Buffs the Repeater

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
Leicester Repeater damage multiplier increased to 2 from 1.5, resulting in 60 damage from 45.

## Why It's Good For The Game
Gun got gutted as a result of MJP's revolver ammo nerf. This fixes that. 

## Changelog
:cl:
balance: Leicester Repeater damage multiplier increased to 2x from 1.5x. 
/:cl:

### CODE REVIEW

**Comment by Mrrpip** [comment]
This is a really roundabout way of saying returning the repeater to how it was before the revolver nerfs.

**Comment by KrabSpider** [comment]
> This is a really roundabout way of saying returning the repeater to how it was before the revolver nerfs.

Shut up I was tired and forgot it used to be 60.

**Comment by AndroidMK2** [comment]
I used to play repeater some time ago, couldn't kill a drone without landing every single shot of a 14 bullet mag. Right now I see it rarely being used so I would really like to see this buff implemented.

**Review by BraveMole — APPROVED** [review]

**Comment by BraveMole** [comment]
Wouldn't it be better for it to have its own ammo though?

**Comment by KrabSpider** [comment]
> Wouldn't it be better for it to have its own ammo though?

Hahaha.....

**Comment by BraveMole** [comment]
> > Wouldn't it be better for it to have its own ammo though?
> 
> Hahaha.....

David is making another rebalance for revolvers and pistols, so this situation will arise again

**Pull request merged**
