### PR TITLE
Nerfs the AI combat droid movement speed

### PR DESCRIPTION
**Pull request by chizzy376**
## About The Pull Request
The AI combat droid has been reduced a speedy move_delay of 3 down to a 5, making it much less of a headache to fight against.
## Why It's Good For The Game
Having an entire hive get deleted by a machine that can outrun and outDPS them is unfun, especially since it's immune to any form of CC the xenos have at their disposal.
## Changelog
:cl:
balance: nerfed combat droid's speed
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
No, they are extremely fragile and get blocked by everything.

**Comment by srxtreme** [comment]
Droids additionally fire overcharge laser beams at thrice the firerate. Might wanna look into nerfing that preferably.

**Comment by KrabSpider** [comment]
> No, they are extremely fragile and get blocked by everything.

Bro. You can LITERALLY chase a xeno, and they cannot FIGHT you in any meaningful capacity no matter what caste they are, because all your projectiles with strip entire chunks of health regardless of armor. Can you not _agree_ that maybe droid speed is a little too fucking cranked, especially for how much DPS it has?

**Comment by Coastfront** [comment]
This pull request literally already exists #11980

**Comment by Lumipharon** [comment]
Duplicate pr, also droid needs stunnability, not a speed nerf (initially)

**Comment by chizzy376** [comment]
Understood

**Pull request closed without merging**
