### PR TITLE
Adds Tyramorphs as a new faction

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
New faction that can shoot but don't heal or use resources like conventional marines.
Looks cool.

More code soonᵀᴹ
## Changelog
:cl:
add: Adds tyramorphs as a new faction.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
BENO WITH THE GUN

**Comment by Aporhtonoma** [comment]
IT SMELLS LIKE COMBAT PATROL IN HERE

**Comment by docRoboRobert** [comment]
I desire pictures aaugh

**Comment by Lumipharon** [comment]
Sneak preview:
image

**Pull request closed without merging**
