### PR TITLE
The AI now has expanded skills

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
This PR expands the AI list of skills to include things like leadership and surgery.

## Why It's Good For The Game
The AI currently is only skilled in engineering matters. Given there are some factors which are affected by skills like autodocs and some orders, it seems like an oversight. 

## Changelog
:cl:
balance: Improved AI skills, they're now a master of all, for whatever the AI can use their skills for.
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Is this balance in balance freeze. Damn

**Comment by lbnesquik** [comment]
> 
> 
> Is this balance in balance freeze. Damn

It straddles the line of QoL/tweak but balance still fits

**Comment by GradusNL** [comment]
> 
> 
> > Is this balance in balance freeze. Damn
> 
> It straddles the line of QoL/tweak but balance still fits

So wait for the balance freeze to be over? Not that hard.

**Comment by TiviPlus** [comment]
Balance freeze

**Comment by SplinterGP** [comment]
opened upon request after balance frez

**Comment by SplinterGP** [comment]
i have no idea what this does but its funny.

**Pull request merged**
