### PR TITLE
Adds CORSAT, Lava Outpost V1 and Chigusa into the game files, outside of rotation.

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
What it says on the tin. Used for events.
## Why It's Good For The Game
These maps aren't in a playable state for normal rotation, but are fun to do time-to-time as an event. Not much of a reason to remove maps from the game files entirely rather than just blacklisting them.
## Changelog
:cl:
add: CORSAT, Lava Outpost V1 and Chigusa are in the game files again! Can be used for events, but not in rotation.
/:cl:

### CODE REVIEW

**Comment by mrhugo13** [comment]
the players yearn for the 1 hour cave chase sequence (although admittedly might be alot less of a problem now that nuke war is the primary gamemode instead of "finding last shrike hiding in one of Lava Outpost's many corners)

**Review by RipGrayson — CHANGES_REQUESTED** [review]
I'm not reviewing for map quality here obvious reasons

This is an odd area on Lava Outpost
stasharea9

Just because these maps are ~~awful~~ underappreciated is no reason to use flat turfs.
Please replace the basalt with the 3/4ths version.
stasharea10

I guarantee you somebody is going to escape out of this fob before shutters open because of the lack of shutter coverage behind the button
stasharea11

I can feel your pain noding this
stasharea12

**Comment by RipGrayson** [comment]
> Is it compatible with Combat Patrol and Sensor Capture? Peak maps like these might actually be reasonably playable on HvH

CORSAT and Chigusa should be compatible, not sure about Lava Outpost/

**Comment by Victor239** [comment]
Lava Outpost has virtually no tunnels on the map.

**Pull request merged**
