### PR TITLE
Remove some posters as ordered by Tivi

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

The posters that have been removed:
image

Remove pin up girl posters since even in military this is illegal. No porno.

Remove blurry posters that are obviously have been shunk down.

Remove lore irrelevant posters. I don't know why lore is relevant, but sure.

Increase probability of seeing quality posters.

Alternative to #9891

## Why It's Good For The Game

Better guideance on posters.

## Changelog
:cl:
del: Removed some posters; git will remember
imagedel: deleted some posters; git will remember
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
>>Remove pin up girl posters since even in military this is illegal. No porno.
>>Remove lore irrelevant posters. I don't know why lore is relevant, but sure.

**Review by Kuro020 — APPROVED** [review]

**Comment by Ragecrabbo** [comment]
Morteposter my beloved

**Comment by novaepee** [comment]
image

The only posters right now.

**Comment by Arctrooper8** [comment]
> image
> 
> The only posters right now.

I'd suggest cutting the got wood and no ERP posters, they don't thematically make sense for the TGMC.
Also give the moth poster a funny conspiracy theory description.

**Review by BraveMole — CHANGES_REQUESTED** [review]
"Remove lore irrelevant posters. I don't know why lore is relevant, but sure."

Not a fan of this

**Comment by novaepee** [comment]
> "Remove lore irrelevant posters. I don't know why lore is relevant, but sure."
> 
> Not a fan of this

I know, right?

**Comment by BraveMole** [comment]
> People

You mean fun police

**Comment by TiviPlus** [comment]
wee woo

**Review by TiviPlus — APPROVED** [review]

**Comment by BraveMole** [comment]
Society

**Pull request merged**
