### PR TITLE
Adds medscanner gloves.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Creates new gloves with built-in health analyzer.
NEW SPRITE THANKS @KillerOrcaCora 
image

## Why It's Good For The Game
Maintainer approval
medscan glove
## Changelog
:cl:
add: Healthscanner gloves, there are 8 available in the marine med, medics can purchase them for 2 points from their vendor.
imageadd: Healthscanner glove sprites.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
good choice and alternative choice with defib gloves

**Comment by XElectricX** [comment]
Powercreep.

**Comment by Losenis** [comment]
Have the healthscan also pop for the one on the receiving end of a harm intent with this

**Comment by zzurge** [comment]
Zased

**Review by Kuro020 — APPROVED** [review]

**Pull request merged**
