### PR TITLE
Increases medical skill for Squad Leaders, Corpsman, and CMOs by one.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Increased Squad Leader's medical skill.
Increased Corpsman's medical skill.
Increased CMO's medical skill.

Medical Skill Affects:
- Apply Splint Speed
- Injecting Syringe Speed
- Forcefeeding Pill Speed
- Defib "Heal" amount.

It does NOT affect surgery.

## Why It's Good For The Game

SLs should be able to heal people faster as their rank should indicate that they're good at keeping people alive. Corpsman should be slightly stronger in their speed of doing actions given that they're a corpsman, and should be better than an SL at medical. The speed buff to medical healing should be on par with an unga's desire to go back in and fight. CMOs should also be pretty fucking good at medical and be better than any doctor below them.

## Changelog
:cl: BurgerBB
balance: Increases the medical skil by 1 for Squad Leaders, Corpsman, and CMOs.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Rohesie** [comment]
CMO is an administrative rank. It was intentionally made the same as doctors because we want them managing stuff, not being forced into doing surgery because they are better at it.

What is the need of this powercreep, though?

**Comment by jroinc** [comment]
It's powercreep, and as much as I want it, we don't need it.

SL's already have better medical skill then ungas, and medics have perfectly decent skill as-is.

**Comment by Rohesie** [comment]
Sorry, this one isn't happening.

**Comment by BurgerLUA** [comment]
maybe don't close the pr before I could respond smh

It's needed because alpha SL is useless right now.

**Comment by Rohesie** [comment]
SLs are leaders and beacons. Features improving that are fine and very welcome. Them creeping into medical goes against their design.

**Comment by BurgerLUA** [comment]
That's fine. I'll work on other ways to make SL useful.

**Pull request closed without merging**
