### PR TITLE
dogtag new sprite

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
new sprite

## Why It's Good For The Game
looks more in style

## Changelog
:cl:
tweak: new dogtag sprite
/:cl:

### CODE REVIEW

**Comment by BeloneX** [comment]
image

**Review by SplinterGP — APPROVED** [review]
bimmer approve or deny this pls

**Comment by ilikesaying** [comment]
spooky
oh god oh fuck

**Review by Kuro-ai — APPROVED** [review]
The sprite looks better,bimmer is dead not epic

**Review by TheBimmer231 — APPROVED** [review]

**Pull request merged**
