### PR TITLE
Add TS-34 Scopes

### PR DESCRIPTION
**Pull request by wezsel11**
## About The Pull Request
Three lines of code are added to the Double Barrel shotgun, those three lines are adding the scopes to the TS-34. Mini-scope, marine-scope and scope. 

/obj/item/attachable/scope,
/obj/item/attachable/scope/marine,
/obj/item/attachable/scope/mini,

## Why It's Good For The Game
Give a wider range for usage for the TS-34 instead of only being the funny pointblank weapon to insta-crit runners and hunters. Adding these scopes to the TS-34 will make the double barrel shotgun far much viable in other situations than PB. It can be used as a defensive and a support weapon. Double Barrel shotguns were used for hunting and I wouldn't be suprised if hunters sometimes used scopes on them. Thank you

For footage on how the Double Barrel works and looks with a scope check: 
https://youtu.be/51a5YrTYUVc

## Changelog
:cl: Grandpa
expansion: Expands content of an existing thing
code: changed some code
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
Mini onlly

**Comment by wezsel11** [comment]
Dear SplinterGP,

"> Mini onlly"
you responded. Could you give me more information why it should be mini-only? 

I've seen more Double Barrel shotguns with long-ranged scopes than those small scopes. Since the Aim-mode removal of sniping, many people stopped combating long range and combating Boilers from afar has been quite difficult. I am convinced that a scoped double barrel can enrich the gameplay with new ways of playing marine. Snipers are slowly becoming more extinct.

**Comment by wezsel11** [comment]
Hello Tiviplus,
> Is this a joke pr or serious?

My pr is serious, I really wish to see scopes being added to TS-34's. I can't imagine adding these scopes will bring a lot of favor to the Marine side, it just makes new possibilities to play as a marine and enjoy it. If, after many matches start to complain that the Double barrel is overpowered then we could nerf it to being a Mini-scope only. I've already been told that you could use binoculars for guns like this but shooting with binos is a bit buggy when you shoot sideways. 

Thank you for your patience.

**Comment by wezsel11** [comment]
I'll be gone for a month, I'll try to answer the questions around the weekend of 21 and 22 august. Thank you for your patience. I remain a fervent supporter of a scoped double barrel.

**Comment by TiviPlus** [comment]
You know what yolo

**Pull request merged**
