### PR TITLE
chat style changes

### PR DESCRIPTION
**Pull request by Neocloudy**
## About The Pull Request
adds the better looking chat styles from TG/CM-SS13. also adds announcement blocks from TG. please leave feedback about these in the comments ***(pictures currently outdated)***
- New style for spawning in as a job and round-related styles (round start/end, etc)
- New announcement blocks with striped effects, designed to get your attention while still looking good
- Sending orders now looks and sounds like a command announcement if you're any command role (FC/Captain/etc), or looks like a minor announcement if you're a Squad Leader. Also, they show your character's `real_name` and job at the bottom
- In dark mode, red styles are darker
- Slight changes to radio channel colors, deadchat and OOC
- Info/notice recolored to the same as TG
- Added bruise, burn and clone examine text in chat
- Added death flavor text in chat, also tells if you're DNR or something

image
image
image
## Why It's Good For The Game
- Styles like info and warning are really ugly. For example, the raw meat warning on dark mode doesn't look very good.
- The brighter channels should be more readable and better looking(?) in dark mode, and this should help with that.
- The announcement blocks/dividers will grab people's attention pretty easily while still trying to look half decent.
- I don't think any maintainers would oppose this.
## Changelog
:cl:
add: chat styles from tgstation
add: brighter channel, ooc and deadchat colors on dark mode
add: announcement blocks/dividers with striped effects, used for priority/minor announcements and sending command orders
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
might need more example pictures to get a clearer picture on what exactly has changed beyond text descriptions, me thinks

**Comment by Neocloudy** [comment]
## spawning in
i'm probably gonna change or revert this part in the afternoon, it's very ugly
image

## breaking or destroying limbs
image

## dying
image

image

**Comment by Wirpy** [comment]
How does it look in light mode

**Comment by Neocloudy** [comment]
> How does it look in light mode

image
image
image
image

**Comment by Neocloudy** [comment]
> Yellow OOC is disgusting, soulless, and immoral.

what do you mean by this? like, how are they bad?

**Comment by Neocloudy** [comment]
image
image
image

basically ready

**Comment by Neocloudy** [comment]
image
image
image

**Review by ivanmixo — APPROVED** [review]

**Comment by Aroliacue** [comment]
This has been very well-made but the colour changes REALLY should be a separate theme in the options, not a replacement in darkmode.

**Comment by DeltaFire15** [comment]
Dislike the style for announcements, looks very jarring in the same way as things look when admins embed random images.
Prefer the previous state for that change in particular.

**Review by vvvv-vvvv — CHANGES_REQUESTED** [review]
use the span_* macros

**Comment by efzapa** [comment]
please change piss yellow OOC back, thanks

**Comment by Neocloudy** [comment]
look at commits, the server just needs to update

**Comment by Neocloudy** [comment]
> Dislike the style for announcements, looks very jarring in the same way as things look when admins embed random images. Prefer the previous state for that change in particular.

the new announcements are supposed to be better looking (light mode definitely needs to be touched up lmfao) and grab your attention easier. i may mess with things that spawn them, so that things like alamo auto cycle don't fill your screen with a random red block every few minutes.

**Comment by DerpiestBruh** [comment]
There's also this one thing where highlighted text messes up the chat when it comes to stuff like the alamo's departure box

**Comment by Neocloudy** [comment]
> use the span_* macros

> There's also this one thing where highlighted text messes up the chat when it comes to stuff like the alamo's departure box

both should be addressed

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
