### PR TITLE
Removes vending delay from marine vendors

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Removes vending delay from marine vendors
## Why It's Good For The Game

Bro this shit is painful. Why. All it does is slow shit down. Even CM doesn't have this
## Changelog
:cl:
qol: Removes vending delay from marine vendors
/:cl:

### CODE REVIEW

**Comment by FIXTHERADBOXPLEASE** [comment]
This is a balance change... marines will be able to vend grenades and spare ammo MUCH faster and with ZERO ability to punish them during hijack. A situation where infinite ammo and grenade spam is already at an all time high.

**Comment by yyzsong** [comment]
> This is a balance change... marines will be able to vend grenades and spare ammo MUCH faster and with ZERO ability to punish them during hijack. A situation where infinite ammo and grenade spam is already at an all time high.

The 0.1 second delay between clicking a button and having an item drop to the ground is not gonna effect hijacking, I can fucking promise you that. This is a deranged take.

Marines can already either just spamclick the button or hold spacebar to vend items at super fast rates; it's not like the vending machine makes you wait every time it vends an object before vending another, it's just the delay between hitting the button and getting the item

**Comment by ClosetedSkeletonGH** [comment]
> This is a balance change... marines will be able to vend grenades and spare ammo MUCH faster and with ZERO ability to punish them during hijack. A situation where infinite ammo and grenade spam is already at an all time high.

I can already vend ~330 grenades within 2 minutes before the click limit comes in and I am by no means the fastest clicker around. If you really care about that, cut the amount of HEDP's from 600

**Comment by FIXTHERADBOXPLEASE** [comment]
The delay gives a hijack xeno the chance to attack or interfere with the process before it's complete.. Removing the delay removes that chance. This is the same reason why turrets and cades take time to set up. Why should vending infinite grenades or ammo be any different?

**Comment by carlarctg** [comment]
impressively insane complaint that is not even directed towards the right target

go ahead and make vending machines break after 10 vends in hijack or something if you want but it is irrelevant to the pr

**Comment by Coastfront** [comment]
> The delay gives a hijack xeno the chance to attack or interfere with the process before it's complete.. Removing the delay removes that chance. This is the same reason why turrets and cades take time to set up. Why should vending infinite grenades or ammo be any different?

Except that its physically impossible to interrupt the process with or without a delay because the items are still going to spawn from the vendor.

If I click the vendor 30 times in one second, iirc even if im half dead on the ground stunned, said 30 items are infact still going to come out and anybody who see's this can now use these items.

**Comment by Lumipharon** [comment]
Yeah the delay is shitcode to begin with. As above you can walk away from a vendor/take a teleporter and the item still spawns in your hand.

That said, if you remove the delay from coffee machines I will beat you with an immersive cup of coffee.

**Comment by Barnet2** [comment]
> This is a balance change... marines will be able to vend grenades and spare ammo MUCH faster and with ZERO ability to punish them during hijack. A situation where infinite ammo and grenade spam is already at an all time high.

One has to wonder if this is bait; but for the record you can already essentially not care about the delay with spacebar

**Review by TiviPlus — APPROVED** [review]
>gitblame is baycode

classic

**Comment by chizzy376** [comment]
> This is a balance change... marines will be able to vend grenades and spare ammo MUCH faster and with ZERO ability to punish them during hijack. A situation where infinite ammo and grenade spam is already at an all time high.

Zased CM take

**Comment by Losenis** [comment]
Only now yall realize the guy will even straight up lie to shit up any PR he can find?

**Comment by Strayed-Raven** [comment]
> This is a balance change... marines will be able to vend grenades and spare ammo MUCH faster and with ZERO ability to punish them during hijack. A situation where infinite ammo and grenade spam is already at an all time high.

The prime example of xeno lobbying. right here. This mindset is why we cannot have nice things

**Comment by Naaanii** [comment]
> This is a balance change... marines will be able to vend grenades and spare ammo MUCH faster and with ZERO ability to punish them during hijack. A situation where infinite ammo and grenade spam is already at an all time high.

I can't even tell if this is a meme or blatant saltposting anymore.

**Comment by Redrover1760** [comment]
> This is a balance change... marines will be able to vend grenades and spare ammo MUCH faster and with ZERO ability to punish them during hijack. A situation where infinite ammo and grenade spam is already at an all time high.

Nades aren't scary anyways. Let em vend the nades so they can probably ff with them.

**Pull request merged**
