### PR TITLE
Defiler reagentslash change

### PR DESCRIPTION
**Pull request by Sebbe9123**
## About The Pull Request
This PR aims to remove more traces of capture gameplay.
Previously defiler reagent slash injected 4 of chosen chems + 4 larvae growth juice. 
This pr removes larvae growth juice and makes reagent slash instead inject 7 of chosen chem.

## Why It's Good For The Game
I think moving further away from the defunct capture gameplay is good, although larvae growth serum is a very strong marine chem purge. In theory the power level of defiler hasn't moved, although you can inject more chems of your own choosing, the removal of the chem purge should make it easier for corpsmen to save marines that got ambushed.

## Changelog
:cl:
del: Removes larvae injection from reagent slash.
balance: makes reagent slash inject 7 of chosen chems.
/:cl:

### CODE REVIEW

**Comment by davidchan13** [comment]
Larval Growth Toxin purges Medicines. What Defiler wouldn't want that in every slash? Just because it has 'Larva' in the name doesn't mean it's only for capture.

**Comment by Sebbe9123** [comment]
> Larval Growth Toxin purges Medicines. What Defiler wouldn't want that in every slash? Just because it has 'Larva' in the name doesn't mean it's only for capture.

Neurotoxin also purges chems, the "main" chem in the Defiler's repertoire.

**Comment by davidchan13** [comment]
> > Larval Growth Toxin purges Medicines. What Defiler wouldn't want that in every slash? Just because it has 'Larva' in the name doesn't mean it's only for capture.
> 
> Neurotoxin also purges chems, the "main" chem in the Defiler's repertoire.

And Larval Toxins purges 3x as much per tick, metabolizes at 1/4 the rate, and stacks with Neuro. Literally no reason you wouldn't want Larval.

**Comment by Surrealaser** [comment]
I think it's worth TMing.

Personally I would like to pair this with my Defile change: https://github.com/tgstation/TerraGov-Marine-Corps/pull/7189

**Comment by Pariah919** [comment]
seems ok

**Pull request merged**
