### PR TITLE
T-29 drums rework

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

MJP has been talking about this, and after him looking over the stats, T-29 is fine and it should have different types of drums for interesting gameplay.

The T-29 is known to be reliant on requisition, its drums take a while to reload, its ammo is 200, and its wall of lead demands MORE.

Introducing two more drums, the 100 ammo and 300 ammo drum. The 100 ammo drum takes less time to reload at the cost of holding a lot of ammo. Its weight class is small, so you can fit a lot (though the storage ratio is all wack despite carrying half of a regular drum).

The 300 ammo drum is a CHONK of a drum. It takes a while to reload, its weight class is bulky (yeah, there is no large yet), and it has a modifier that apply 1.5 wield delay and 1.2 aim slowdown. However, it can lay the LAW OF THE LAND for a long long time.

It is a big PR since I have changed the T-29 drum pathway.

This is reflected in requisition, though the points don't divide well.

Also, T-29 smartgunners have to fix their loadout for drums. I changed pathway, so you gotta fix your loadout.

Sprites are from CM SS13. The 300 ammo sprites are actually the sentry drum sprites with different color, the 200 ammo sprites are the M56 drum but smaller and recolored, and the 100 ammo sprites are the M56B sprites but recolored.

## HOW DOES THIS AFFECT T-29 SMARTGUNNER AMMO STORAGE!

If a smartgunner buys T-29, then they will have 16 points, total up to 1,000 ammo.

A small 100 ammo drum costs 2 SG points. With 16 points, a T-29 smartgunner can buy at least eight 100 ammo drums if they really want to go full out.
A normal 200 ammo drum costs 4 SG points. With 16 points, a T-29 smartgunner can purchase four 200 ammo drums.
A large 300 ammo drumm costs 6 SG points. With 16 points, a T-29 smartgunner can only buy two 300 ammo drums, leaving them with a remainer of 4 points to use to either buy one 200 ammo drum or two 100 ammo drums.

## Why It's Good For The Game

Variant in T-29! T-25 already has that with ammo box, so T-29 should get flexibility, too. This also let players choose whether to reload with the 100 as fast as possible in dire situations or really surpress fire with  the 300 and just don't stop. 200 is a good middle ground.

## Changelog
:cl:
add: New T-29 drums, with the 100 ammo drum and 300 ammo drum! 100 ammo drum is faster to reload at the expense of ammo whereby 300 ammo drum is BIG at the expense of taking longer to reload and can't run as fast
code: change 200 ammo drum's pathway, so T-29 smartgunners loadout will need to account for this; why they don't see their drums in loadout is because of this PR, so go fix it
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
image

The left drum is the 300 ammo drum, the middle is the 200 ammo drum, and the right drum is the 100 ammo drum.

**Comment by novaepee** [comment]
MJP's instructions: 
image

**Comment by UsernameIs-UnAvailable** [comment]
I don’t see the point for the 100 round drum when the smart rifle exists, which for 20 less rounds you get a instant reload and access to a wide range of  attachments ( at least compared to the T-29 ). Also the 300 round drum’s drawbacks seem a bit harsh for  a 100 round increase.

**Comment by Otterwatch** [comment]
I don’t understand this pr considering that the smart rifle exists as the more flexible little brother to the t29. If you want a HSG, then just get a HSG instead of buying more expensive drums that only add 100 extra rounds and more wield delay. If you want less rounds, then grab a smart rifle and slap some of those attachies on. This seems like a pr to just convolute a simple role further for the sake of “content.” It’s just going to confuse newer players and one of your new types, the light drum, is useless compared to smart rifle or more ammo. T29 is perfectly fine balance wise right now and still is a good time to play as a versatile weapon for what it is.

**Comment by turnop** [comment]
smartgunner main reporting

that 300 round magazine is fucking rancid and I would absolutely never use it, the T29's wield delay is already so absurdly long in basic that xenos will consistently get away before you can even start laying down fire if you wield when you actually see aliens

i don't know why you guys think that giving the t29 more ammo in various forms is somehow a buff or will make it good, it's still a subpar gun that's been powercreeped, with this PR it just gets two objectively worse ammo rounds (one that will take up more space for less ammo and one that will be more ammo efficient but literally ruin the gun with an insane wield and aim decrease if you use it)

**Comment by novaepee** [comment]
Not today, MJP.

**Pull request closed without merging**
