### PR TITLE
Miners give more points, reprices certain things.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Reprices the weapons tab around, ups miner production.
Most used guns in req are increased by 33% then rounded up.
B18/17 are increased by 33%.
Most used materials, and plasmacutter upped by 33% then rounded down in bias.

Things changed in price that aren't increased should be..

~~Thermo/Sledge/XRAY reduced in price to make more appealing, and to add stuff to the lower 30-50 point brakcet.~~
Going to change these to get the price increase as well for atomization sakes, might reduce them in the future.

## Why It's Good For The Game
Our weapons tab is too compressed in price, we need to decompress it, we can touch other tabs in a later in a case by case basis, as otherwise this PR will probably be insanely bloated. I think having 160 be our top compared to the old 120 will decompress it massively, considering req guns are the most game impactful.
Price changes on certain guns done to make them more attractive.

Eveyrthing is sorted in multiples of 5 for guns, I'm not sure if ammos hould be multiplies of 5.

## Changelog
:cl:
balance: Miners produce 33% more points.
balance: Most used req guns upped by 33% in cost, decompression of req point tier costs, shouldn't be felt overall.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
Nerf across the board due to no equal increase to point generation by selling xeno corpses

**Comment by Arctrooper8** [comment]
> Nerf across the board due to no equal increase to point generation by selling xeno corpses

Marines should have more incentive to mine instead of just slaughter. Quite honestly a rework of mining is needed, but the one person who planned to do so got slogged down in schoolwork.
They did make this amazing design doc though: https://hackmd.io/@YoCjPtFmRCm5La02TCXmIw/H1o61iSRY

**Comment by Losenis** [comment]
When mining is in direct competition with fighting xenos that aren't braindead enough to push a fortified miner, are you going to be surprised people skip one for the other?

**Comment by Naaanii** [comment]
> Nerf across the board due to no equal increase to point generation by selling xeno corpses

Corpse point generation was already buffed due to Researcher powercreep.

**Comment by Arctrooper8** [comment]
> When mining is in direct competition with fighting xenos that aren't braindead enough to push a fortified miner, are you going to be surprised people skip one for the other?

That's why mining needs a rework, and why the design doc is honestly so well made. Because if miners are already auto, and xenos can't sneak attack them. Then marines have an actual reason to repair them.

**Comment by Xerkie** [comment]
reducing the four-barelled instant wippy spewer and the hardstun-almost-every-single-caste-in-the-game-for-a-solid-second-fnuuy hammer to 50ish points just because "not used much" does not seem like a great idea to me

**Comment by private-tristan** [comment]
miners aren't used because, in the time it takes for you to 
> get to a miner
repair it
place in upgrade
add defenses around it 

a RSR can scan 2 T2 bodies and get like 50 credits while not needing to be babysat

**Comment by Losenis** [comment]
>a RSR can scan 2 T2 bodies and get like 50 credits while not needing to be babysat

More like by then either the marines got wiped and could've used those mats on the frontline or the xenos got wiped

**Comment by Pariah919** [comment]
>

Unreviewable. You either decompress the price of everything, or you change the price of certain items. Not both at once
>
I'll revert the price changes and move up the prices aswell, then.

**Comment by Pariah919** [comment]
tivi veto'ed

**Pull request closed without merging**
