### PR TITLE
Russian red,hyroalin and arithazine now react very poorly to neuraline.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Makes russian red, hyroalin and arithazine kill you if you take them with neuraline. Powergamer be gone. Adds injectors for them for debug purposes. it also fixes hyroalin

## Why It's Good For The Game
powergamer man bad. Makes it so you don't have to sit around doing chem for 2-3 minutes to debug stuff with the injectors.

## Changelog
:cl:
add:added hyroalin and arithazine debug injectors
fix:hyroalin now actually functions
tweak: Russian red, hyroalin and arithazine now kill you if you take neuraline
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -49. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
Second-to-last PR made unga medics able to use an invincibility strat.

Your last PR made perdiox+ injectors and russian red pills just kill people immediately.

Plz change metabolism rates on chems per the comment on the last PR.

Being able to heal 1.5 toxin damage for 40 minutes straight while tanking the 0.5 brute damage on bicard is eeh.

**Comment by Pariah919** [comment]
>Second-to-last PR made unga medics able to use an invincibility strat.

>Your last PR made perdiox+ injectors and russian red pills just kill people immediately.

>Plz change metabolism rates on chems per the comment on the last PR.

>Being able to heal 1.5 toxin damage for 40 minutes straight while tanking the 0.5 brute damage on bicard is eeh.

I'll change that in a separate pr

**Comment by Hughgent** [comment]
Don't do this in this manner.

The standard we've set for 'bad interactions' is just to convert the two drugs into toxin. Thus it also happens 'in the beaker' and not just in the body.

Do keep the `hyronalin` typepath fix though.

**Comment by Pariah919** [comment]
>Don't do this in this manner.

>The standard we've set for 'bad interactions' is just to convert the two drugs into toxin. Thus it also happens 'in the beaker' and not just in the body.

>Do keep the hyronalin typepath fix though

This is to stop microdosing. Though I can make it go into toxin instead.

**Comment by Hughgent** [comment]
Please do make it react into a toxin. Even making a new toxin that is very deadly.

I would just accept the 'microdosing' via cigarettes and cigars as fact. It takes a small amount of teamwork to make that happen.

**Pull request closed without merging**
