### PR TITLE
Minor accessory storage rework

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Makes webbing work off max storage rather than slots, nerfs it to 2 for normal magazines, same for pistol magazines (3)
Nerfs black webbing to 4
Medical webbing clarifies what it is rather than being just "corpsman webbing"
Adds a grenade bandolier that holds 6 grenades.

Adds all the webbing to the ghmme vendors, as they should've been there from the start.

## Why It's Good For The Game
Webbing is literally free storage and there's never a reason to not use it, so you shouldn't get 3 magazines per webbing in my opinion.
The rest of the changes are just lowering marine storage by a bit.
I need an actual sprite for the bandolier however

## Changelog
:cl:
add: Added grenade bandolier
balance: most webbing storage decreased by 1 by the board. Added grenade bandolier
tweak: webbing now functions off weight storage rather than slots
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -163. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by revelation-8468** [comment]
Nerfing the storage capacity of WEBBING? Please, no.

If i wanted a merely two extra slots i would have just worn PAS or got a General Storage module.

**Comment by TGCMbetcher** [comment]
Why not nerf backpacks next. Its literally free storage and there is never a reason not to use it so you shouldnt get 8 magazines inside one.
For real though the grenade one is just the black webbing but you like grenades so you made a reason for people to pick it over black webbing.

**Comment by David-Stormwell** [comment]
MJP is a cade hugging agent in disguise

**Comment by Losenis** [comment]
"Webbing is literally free storage and there's never a reason to not use it, so you shouldn't get 3 magazines per webbing in my opinion."

So let me see if I get this right. If I, as corpsman, decide to skip ammo rig and mag pouches to run lifesaver, medkit, and autoinjector pouches as well as medical jaeger which limits me to 3 magazines total... It's considered OP and I should only run with 2? Or if I go engineer with toolbelt, construction pouch, and electronics pouch expecting a ton of FUBAR APCs?

This is absolute nonsense "balance" that only thinks of ungas who go full ammo on everything over only wanting to shoot or have so little they want to carry that they can afford the luxury of just taking more ammo storage options due to not needing any other storage type.

**Comment by Knuff-les** [comment]
I'm in honest confusion on how this affects any sort of balance other than just making it more inconvenient to store stuff

**Comment by davidchan13** [comment]
> I'm in honest confusion on how this affects any sort of balance other than just making it more inconvenient to store stuff

Any time the words 'Balance' and 'Storage' are used in the same PR it just means fuck you, I don't care if it's been this way forever and never affected balance before, across the board nerfs and reverting QoL for everyone.

**Comment by SplinterGP** [comment]
don't think black webbing and webbing needs nerfed, you can keep webbing with size to fit more ammo, we don't want much marines needing to go to FOB often to refuel

**Comment by TiviPlus** [comment]
Grenade belt is fine rest is not

**Pull request closed without merging**
