### PR TITLE
Hunter stealth damage threshold

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Hunter stealth being broken is now by total damage received in stealth, instead of the damage from a single hit being over a threshold.

The number is now 45 damage (number pulled out of my ass). i.e. a full burst from a rifle will break stealth, but 1-2 shots probably won't.

The damage threshold recovers by 10 damage per sec (i.e. you get hit once or twice so you're 25/45 damage taken, but stay stealthed and wait around a corner for a bit, and that recovers back to 0/45.
## Why It's Good For The Game
Less fucking god awful, certain guns were previously hard locked out of ever breaking stealth.
This is only set to get worse with the new mechanic letting xenos buff their armour, locking out more guns from stealth break.
## Changelog
:cl:
balance: Hunter stealth break from incoming damage is now a total amount (45) instead of a single hit needing to be over 15
/:cl:

### CODE REVIEW

**Comment by FunkyMonke47** [comment]
blessed

**Comment by Mannybrado** [comment]
people already salt about hunter because its capable of winning 1v1s, but this? oh no... the salt will flow and it'll end up nerfed because of it...

**Comment by Lumipharon** [comment]
This is a nerf you ape, MANY guns are simply incapable of breaking stealth right now. This will no longer be the case.

**Comment by Barnet2** [comment]
image

**Review by QualityVan — APPROVED** [review]

**Pull request merged**
