### PR TITLE
Marine tickets respawn system

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Reduce respawn time for marines from 45 minutes to 15. Every time a new client joins the server, 4 new tickets are given to marines. Every time someone join the marine side, one ticket is removed from their shared pool. When ticket runs out, marines can no longer respawn

Admins and ghosts can see the ticket count

## Why It's Good For The Game

This has pros and cons

Pros:
- Make people play more. Seriously, where is the fun with having to wait 45 minutes (!!!) if you die? 15 minutes is already very long by all other games standard, while making it bearable and not to boring
- Give marines another chance to push if they fail the first one. Currently with pools, if you don't reach them in the first 20 minutes, you are dead. Marines should be given a more consistent pushing power throughout the game, so that if they killed some xenos during their initial push they still have all their chances to win the game. 
- Make the strengh of marines more consistent throughout the whole round. Currently it declines pretty fast with the first deaths, wich makes the experience of playing one painfull
- Make death a bit less punishing, which could lead in less cade huging as marines as less afraid of pushing, even if it's a risky-ish push
- Give the game a limit in time, this should not be too short (that's why you have 3 free lives or more), but this should make boring 5 hours rounds impossible

Cons:
- Make death less impactfull. I personnaly dislike the all permadeath idea, but this is something other peoples disagree with. If you can respawn easily, you lose a part of your self-preservation sense and this limit RP
- Some people also said it could diminish the tactical aspect of the game for a more COD/TF2 approach, though i disagree with them. I think faster respawn doesn't mean that you stop acting tacticaly. And marines are currently not playing tacticly at all, that was the case before pools as well

## Changelog
:cl:
add: Marine ticket system. Faster respawn (15 minutes), but at the cost of one ticket per respawn. Every new player gives 4 tickets to marines. When there is no longer any tickets, marines can't respawn anymore
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -24. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by BongoDongo2000** [comment]
Instead of reducing time why not just make it cost resource points to "wake up" more marines? Would make miners more important and encourage marines to not just cade hug the lz

**Comment by BraveMole** [comment]
> Instead of reducing time why not just make it cost resource points to "wake up" more marines? Would make miners more important and encourage marines to not just cade hug the lz

I'm thinking in the future of lowering the amount of free tickers, but making them buyable by req. I wanted to make the system simpler for a start

**Comment by Chaznoodles** [comment]
You are attempting to slowly pushing the game further and further away from being a MRP server into a constant TDM server where characters aren't worth anything, everyone gets everything, and death isn't punished. You're trying to balance the game around your Pools PR instead of noticing that there's something fundementally wrong about nigh-infinite respawns and fixing that problem. Stop.

**Comment by SplinterGP** [comment]
ided pls restart

**Comment by BraveMole** [comment]
> You are attempting to slowly pushing the game further and further away from being a MRP server into a constant TDM server where characters aren't worth anything, everyone gets everything, and death isn't punished. You're being stubborn trying to bluntly balance the game around your Pools PR instead of noticing that there's something fundementally wrong about nigh-infinite respawns and fixing that problem. Stop.
> 
> image

I have nothing against the server being mrp, you're taking a quote of me with zero context. I was just saying that a lot of things in the server right now, even pre-pools, are making the server totally not MRP IMO

**Comment by BeloneX** [comment]
> You are attempting to slowly pushing the game further and further away from being a MRP server into a constant TDM server where characters aren't worth anything, everyone gets everything, and death isn't punished. You're being stubborn trying to bluntly balance the game around your Pools PR instead of noticing that there's something fundementally wrong about nigh-infinite respawns and fixing that problem. Stop.
> 
> image

Have your catfights on discord, GitHub comments are for code reviews not this.

**Comment by Kuro-ai** [comment]
> ided pls restart

"every pr I disagree with is an "ided pls restart""

**Comment by Kuro-ai** [comment]
> You are attempting to slowly pushing the game further and further away from being a MRP server into a constant TDM server where characters aren't worth anything, everyone gets everything, and death isn't punished. You're being stubborn trying to bluntly balance the game around your Pools PR instead of noticing that there's something fundementally wrong about nigh-infinite respawns and fixing that problem. Stop.
> 

RP was never considered for balance changes in this game ever,might I point you to the survivor and MP removal PRs?

**Comment by SplinterGP** [comment]
> > ided pls restart
> 
> "every pr I disagree with is an "ided pls restart""

jebaited

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Like it or not the server is considered MRP @BraveMole 

if you want this PR to be merged you will do 4 Things:
1) Remove ticket basing on connections rather than actively playing players
2) Undo the respawn change
3)Move ticket handling to be a by-gamemode function with support for multiple factions rather than the current hardcode, with it not being implemented to distress 
4) Clarify the admin message so that admins are aware before overriding ticket limits

**Comment by mokulus** [comment]
If each marine adds 3 tickets in total (+4 -1) and each xeno adds 4 tickets, for a game with 40 marines and 10 xenos it gives you 120 + 40 = 160 tickets per round, which is 4 tickets per marine. Practically this means that respawns are unlimited.

I think the problem is that the chance of reviving is low, because xenos will pull your corpse and wall it. If you don't want the death to be as punishing I think you should look into making revivals possible.

**Comment by BraveMole** [comment]
> If each marine adds 3 tickets in total (+4 -1) and each xeno adds 4 tickets, for a game with 40 marines and 10 xenos it gives you 120 + 40 = 160 tickets per round, which is 4 tickets per marine. Practically this means that respawns are unlimited.

I probably over did the free tickets yes, could tweak this. 

> I think the problem is that the chance of reviving is low, because xenos will pull your corpse and wall it. If you don't want the death to be as punishing I think you should look into making revivals possible.

Yeah, that's why i did the cryobags buff, and remove body drags and nerfed crit dragging. But even if we add more stuff, marines WILL have to push to get bodies back but they won't be able to do so, because well, they lost a chunk of their forces with no way of getting that back

**Comment by Walarks** [comment]
> Yeah, that's why i did the cryobags buff, and remove body drags and nerfed crit dragging. But even if we add more stuff, marines WILL have to push to get bodies back but they won't be able to do so, because well, they lost a chunk of their forces with no way of getting that back

If you want to fix reviving, I would suggest looking into making more features that assist with pushing and holding a position outside of cades. There have hardly been any PRs that address this compared to ones that circle around the issue.

**Comment by Tennessee116** [comment]
This entire PR is pretty unsalvageable. From my perspective, the core feature of marine balance is that they are a nonrenewable resource.

> A non-renewable resource is a natural resource that cannot be readily replaced by natural means at a quick enough pace to keep up with consumption.  - Wikipedia

Because of this, there are _a lot_ of marines, along with medical personnel to keep them alive. If they fail, well, that's called losing.

**Comment by BraveMole** [comment]
> This entire PR is pretty unsalvageable. From my perspective, the core feature of marine balance is that they are a nonrenewable resource.
> 
> > A non-renewable resource is a natural resource that cannot be readily replaced by natural means at a quick enough pace to keep up with consumption.  - Wikipedia


Renewable when there's a limit to tickets? That kinda the anti-definition of renewable, but whatever.
We had 30 minutes free marine respawn for a while, and a lot of people agreed with that

> Because of this, there are _a lot_ of marines, along with medical personnel to keep them alive. If they die, well, that's called losing.

So people are so afraid to die they just cadehug.

**Comment by Tennessee116** [comment]
> Renewable when there's a limit to tickets? That kinda the anti-definition of renewable, but whatever.
> We had 30 minutes free marine respawn for a while, and a lot of people agreed with that

It isn't the _antonym_ of renewable. This gives marines the ability to resupply themselves at a quick-enough rate to keep what you call a "consistent pushing power".

> So people are so afraid to die they just cadehug.

So the logic here is that "I'm ded respawn or restart no cadehug delaymarine delaylien REEEEEEEEEEEEEEEEE". Yeah, people stick to barricades, eventually they either win or lose, it takes 5 hours, its boring, people complain in ghost chat. This isn't the solution to it though, as it only tries to barely push marines to do risky actions that most of them already do.

**Comment by BraveMole** [comment]
The logic between this PR is making the round longer, cause marines either push and fail and die, or they win and basta.

> Yeah, people stick to barricades, eventually they either win or lose, it takes 5 hours, its boring, people complain in ghost chat. > This isn't the solution to it though, as it only tries to barely push marines to do risky actions that most of them already do.

This is clearly A solution, if you don't like it, that's fine that's what PR discutions are for.

If you could stop going to the strawman argument "I'm ded respawn or restart no cadehug delaymarine delaylien REEEEEEEEEEEEEEEEE" and correcting my english just for the sake of marking a point of whatever, that would be nice.

**Comment by davidchan13** [comment]
I feel like a modified version this system would be a better replacement for cloning. 

Instead of server joins giving them tickets, it'd be entirely handled with Req points. Req could just order deep storage access and get more slots. A PFC is 5 req points, a Medic/Engineer be 8 to 12 points, SG and SL be 12 to 16 points. 

When ever req spends points to access 'deep storage' or what ever we want to call it, ghost players can ready up for it. Would probably want something like the tg spawner menu that updates every minute with a running tally of the deep storage slots open (and maybe move join as larva to that menu with a count of larva)

**Comment by BraveMole** [comment]
Need more works, for another day

**Pull request closed without merging**
