### PR TITLE
Brings back tx15 onehanded firing

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request
See title.

## Why It's Good For The Game

Frankly, TX15 onehanded was always a meme. It got nerfed into the ground because shield at the time was OP and because robust people used it.

We still have Lasgun spread, why can't we have TX15 onehanded? 
## Changelog
:cl:
balance: brings back TX15 onehanded firing.
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
all thats left now.... t35 one handed

**Comment by AnCopper** [comment]
Making TGMC into CM, one PR at a time.

**Comment by lovegreenstuff** [comment]
also t39 onehanded. because that's a thing that exists now

**Comment by TiviPlus** [comment]
It was removed for a reason

**Pull request closed without merging**
