### PR TITLE
deletes marine shields

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
deletes marines shields

## Why It's Good For The Game
Shields are an awful gameplay mechanic that only sounded cool in my head after then I realized that they kind of suck to play against and are generally only useful with innanely minmaxy loadouts which make you insanely tanky for nearly no cost or the shield is entirely useless
it's better to put it down

## Changelog
:cl:
del:marine shields are gone
/:cl:

### CODE REVIEW

**Comment by Walarks** [comment]
deployable shields instead when?

**Comment by KornFlaks** [comment]
#7010

You got some personal vendetta against shields.

**Comment by ZahaSanko** [comment]
MJP did it again

**Comment by DerrickChamberlain** [comment]
Big Yikes, "not fun for me", no one gets it type stuff again I see.

**Comment by David-Stormwell** [comment]
mjp yet again qdeling something he himself made

**Pull request closed without merging**
