### PR TITLE
Gives gorger passive blood regen

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Atomization: https://github.com/tgstation/TerraGov-Marine-Corps/pull/13317
Gives Gorger passive blood regen up to 10%
## Why It's Good For The Game
Copypaste: "Gorger is really uncomfortable to play in general, these are merely QoL considering what state he is in right now, Gorger cannot sustain effectively neither offensive nor support abilities, some abilities are very rarely used in general, this tries to correct that (very successfully, considering RU experience with it). Probably needs a testmerge to estimate how good/bad these changes are. These changes are present on RU for 3 months without any balance issues."

## Changelog
:cl:
balance: Gorger passively regens blood up to 10% blood
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Yea edit that in or this is getting closed. 


Also this directly hurts the caste since you want to be low on blood for carnage to stun but wharever

**Comment by Cerrik** [comment]
You only need to be below 50% for carnage to stun, no?  This PR only goes up to 10% blood.  At least, that's described how it works from the original PR this is atomizing.

**Comment by AlexCrimson** [comment]
Considering i almost never see a Gorger overhealing other Xenos, i do not see the issue. Blood is such a hard resource to gather, but overhealing is supposed to be one of the castes main gimmicks. Passive regen up to 10% isnt even a lot of blood.

**Comment by Cerrik** [comment]
Unironically, that is a skill issue argument.  The only situation I have trouble getting blood is FOB sieges.  If you can melee a marine, you can collect blood.

**Comment by AlexCrimson** [comment]
Maybe it is a skill issue argument. Sadly, the entire Xenos player population isnt as cool as you, so they need shit to be a bit easier. Gorger is probably the most unpopular T3 caste, because it sucks to play. If you are good enough to always have blood, then this change is not going to make you better. If you struggle to farm blood for whatever reason, this is a good little buff to get you started.

**Comment by Cerrik** [comment]
I'm not cool and I'm not that good, but I can get into melee range of marines (thus, I can collect blood), which is the bare minimum requirement to play xeno.

**Comment by AlexCrimson** [comment]
Gorger max blood is 400. Drain gives you 80 if you land both hits. 10% passive blood is such a minor thing. Its enough for 2 Transfusions, which would give one xeno max overheal, i think. This just gives Gorgers a way to use their healing without needing to have blood stored up, and even then its an incredibly small amount of healing.

Considering Gorger is a T3 healer of sorts, its woefully bad at the role.

**Comment by Cerrik** [comment]
I'm just going to point to my first comment: it all depends on the regen rate.  10% is only two transfusions... until it regens back up to 10% again.  It's infinite transfusions, only limited by the regen rate.

**Comment by AlexCrimson** [comment]
>These are bad gorgers that aren't using one of their most powerful tools

Isnt that the point though? Good Gorgers will not benefit from this. They will have more blood because they are attacking more. Bad Gorgers will just actually get to contribute something to the team and at least overheal some Xenos. 

The biggest issue i see with this is the fact that when Xenos hijack, if there is a Gorger, the downtime & big group of Xenos means everyone will be overhealed by the time the ship crashes. Thinking about that, i could see this being too much.

**Comment by Pariah919** [comment]
This just makes blood into plasma

**Comment by Arturlang** [comment]
Instead maybe make draining marines give more blood?

**Comment by chizzy376** [comment]
Isn't this a nerf to his stun which is the main part of his kit?

**Comment by Xander3359** [comment]
Yeah this is probably just not needed at all tbh,

**Pull request closed without merging**
