### PR TITLE
Removes food tad

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Removes food tadpole from the game/code
## Why It's Good For The Game
Food tadpole was funny for exactly 1 round and has never been funny after that, people will pick it to soft grief and I can't blame them because the concept is supposed *to be* funny, it doesn't lend itself to serious gameplay because of presentation and the layout is cursed to forever be linked to that presentation.
It also heavily negatively impacts the marine team heavily when people pick it to meme because tadpole has become incredibly important to round flow.
## Changelog
:cl:
del: Food tadpole has been entirely removed.
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
What about the incoming bar tadpole in: https://github.com/tgstation/TerraGov-Marine-Corps/pull/13515

Which is literally the same as the current food tadpole just with booze instead of food.

**Comment by Pariah919** [comment]
> What about the incoming bar tadpole in: https://github.com/tgstation/TerraGov-Marine-Corps/pull/13515
> 
> Which is literally the same as the current food tadpole just with booze instead of food.

Same goes for there, meme tads shouldn't be allowed in.

**Comment by Mrrpip** [comment]
A mama mia! A spaghetti and a pasta!

That said...Ehhh. It's an alright change I guess. POs will probably still...Suck/Grief/whatever it is. Food tad or no food tad.

Not to mention you only have a limited amount of flour so 5 minutes in and you're stuck making meatballs.

**Comment by RipGrayson** [comment]
> What about the incoming bar tadpole in: #13515
> 
> Which is literally the same as the current food tadpole just with booze instead of food.

If this PR goes through than the Bar tad will be removed

**Comment by lbnesquik** [comment]
Stuff it into the fun panel?

**Comment by Mannybrado** [comment]
> > What about the incoming bar tadpole in: #13515
> > Which is literally the same as the current food tadpole just with booze instead of food.
> 
> Same goes for there, meme tads shouldn't be allowed in.

god bless you mjp!

**Review by marivanwan — APPROVED** [review]

**Comment by XANAv2** [comment]
I may be slightly biased, but I think the food tad actually counters puppeteers directly. Also, if you are dead set on removing these make them admin spawns, please.

**Comment by mc-oofert** [comment]
OH NO THERE IS A MEME TAD IN MY SILLY TDM GAME WITH ABSOLUTELY ZERO ROLEPLAY WITH PEOPLE NAMING THEMSELVES JETSTREAM SAM OR ASTOLFO OH NO THIS IS BAD FOR THE GAAAAAAAAAAAAAME!!!!

**Comment by mc-oofert** [comment]
> It also heavily negatively impacts the marine team heavily when people pick it to meme because tadpole has become incredibly important to round flow.

mind you i saw marines win with the food tad

**Comment by iforgotmeword** [comment]
just make it admin only so you have to request it and admins can manage it

**Comment by lbnesquik** [comment]
Wait for the outcome of that other PR before acting on this PR imo

**Comment by Redrover1760** [comment]
It gives strong morale bonuses, so it actually does provide a strong buff and role to the marines, really.

**Comment by spookydonut** [comment]
!13752 merged instead

**Pull request closed without merging**
