### PR TITLE
Ports RUTGMC Drop pods.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Ports RUTGMC Drop pods.
I dont know russian, I think it's this PR? https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/24

image

https://user-images.githubusercontent.com/66163761/224718848-6c60e2d0-6e68-43a3-9c22-d4ac21170af5.mp4

## Why It's Good For The Game
Coords? Coords? COORDS? COORDS? I NEED COORDS WHERE COORDS!!!!!????
This improves upon the drop pod experience.
## Changelog
:cl:
refactor: ports RUTGMC drop pods.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
BAAAAAAALLLLLLLLERRRRRRRRRRRRRRRRRRRRRRRRRRR

DROP POD UI HAS ARRIVED BLESS YO XANDER

**Comment by Frinid1** [comment]
Just for heads up
That shit has broken full night vision which we would probably switch to CIC/CAS vision, maybe someday

**Comment by FIXTHERADBOXPLEASE** [comment]
Anyone got coords?

**Comment by novaepee** [comment]
If you can get coordinates from camera, that would make the brainlets who don't use webmap or StrongDMM for coordinates happy.

**Comment by Al-1ce** [comment]
I have had a .txt file with drop-pod locations and coordinates for every map. Truly we live in a society.

**Comment by Xander3359** [comment]
> I have had a .txt file with drop-pod locations and coordinates for every map. Truly we live in a society.

The fact that you had to resort to this is a failure on the end of the coders.
Current drop pods are tragic.

**Pull request closed without merging**
