### PR TITLE
Knife Attachments

### PR DESCRIPTION
**Pull request by Hughgent**
## About The Pull Request

Memes are no longer dreams.

## Why It's Good For The Game

for the admin on the go who wants to reward a player with the ultimate in unga technology. that BC knife. (or just if they want to give someone more attachments in a much clunkier way.)

## Changelog
:cl:
add: knife attachments
/:cl:

image

image

### CODE REVIEW

**Comment by KitKetKetrai** [comment]
Admin-spawn only imo.

**Comment by Rohesie** [comment]
Is it a knife, or a pistol? Will it accept magazines and shoot without a masterkey?

**Comment by KitKetKetrai** [comment]
Bayonet + knife = 60 damage. OWO??? BAYONET + KNIFE + STOCK = 63 DAMAGE

This might even outclass the energy axe, hillarious adminspawn.

**Comment by Hughgent** [comment]
> 
> 
> Bayonet + knife = 60 damage. OWO??? BAYONET + KNIFE + STOCK = 63 DAMAGE
> 
> This might even outclass the energy axe, hillarious adminspawn.

Unfortunately, it only gets up to 50 (the top picture). so for an admin spawn melee weapon, it could be slightly better than the machete.

**Comment by Hughgent** [comment]
> 
> 
> Is it a knife, or a pistol? Will it accept magazines and shoot without a masterkey?

technically it's a pistol (code wise). a "pistol" that can't take magazines, speedloaders, or bullets. It'll go click if you try to shoot it. you can "cock" it. And it's got the same attachment list as the rifle.

image

I uh, might be able to make it take throwing knives if I put it under the revolver style of pistol and create a blade ammo with the same type path as the throwing knife? But that might be going too far for memes.

**Comment by Hughgent** [comment]
and after messing around for 20 minutes, I have decided not to make it shoot anything.

**Pull request merged**
