### PR TITLE
Humans Can Sing Military Cadences

### PR DESCRIPTION
**Pull request by AquaDraco**
## About The Pull Request
Allows humans to sing songs if they take turns. By pressing a hotkey (currently defaulted to "P"), marines and survivors can sing one line of the song. Once someone tries to sing the song, they will not be allowed to sing another line until another 3 people sing the next lines.

- If the player is unconscious, they will receive a message telling them so.
- If it is not the player's turn, the player will be informed of how many more people need to sing until their turn.
- If the player can sing but someone else is already singing, the player will be informed that someone is still singing.

If no one continues the song within 5 seconds, the song will reset to the first line.

When a line from the song is sung, an ogg of that line will play and the person who sang that line will verbally say the lyrics as well. This means that the words to the song will appear both in chat and above the person's head.

The song is currently set to the EDF song. All lines are included except for the lines where the people are talking (i.e. "Stop with that depressing crap!" and "Okay, then how about this song?" are not included, because they're weird and might be out of character for the player performing the line)

Anyone within 10 tiles will hear the song (although dropoff will cause the song to sound much more quiet after a few tiles). Can be changed if needed.

This pull request is still in progress. Planned features:
- [ ] Mute for those players who really hate listening to this song
- [x] More oggs if needed
- [ ] Ideally we can record and replace the song used with a crowdsourced, TGMC version

## Why It's Good For The Game
This seems like a fun way for marines to spend idling time (for example, in-transit on the Alamo or while on guard). Ideally, this will also boost marine morale and camaraderie.

## Changelog
:cl: AquaDraco
add: Keybind added to sing a line of a military cadence. Default set to P. Taking turns is required, only one person can sing at a time, and song progress will reset if more than 5 seconds passes without anyone singing.
soundadd: Added 32 oggs of the EDF song.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
ohh this is gonna get abused within 5 minutes

**Comment by terranaut1** [comment]
very SOUL i like it

**Comment by AbsoluteJerry** [comment]
This is something I see forward to

**Comment by AquaDraco** [comment]
Added rest of EDF lines and now requires 4 people to sing the song. This value is set to a constant variable that can be changed if needed. In other words, if 4 people keep spamming the song and annoying everyone, we can change this value to like... 6 or 8 or whatever.

**Comment by kyrahabattoir** [comment]
Looks very legal lol

**Comment by AquaDraco** [comment]
> Looks very legal lol

@kyrahabattoir The EDF song is just a placeholder so I can make something that shows that this idea could work. Our goal is to get volunteers to sing the TGMC song and have *that* be in the game.

Would be weird if TGMC marines were singing about the EDF

**Comment by XSlayer300** [comment]
Problem is with the genders, the EDF song are all male based and it'd be weird if females try to sing it.

**Pull request closed without merging**
