### PR TITLE
TGMC skirts

### PR DESCRIPTION
**Pull request by SomrNetwork**
## About The Pull Request
Adds colorable TGMC skirts (skirtlenecks not included)
## Why It's Good For The Game
New clothing and a chance to make female character loadouts good 👍 
## Changelog
🆑 
add: TGMC jumpskirt
add: hyperscaled TGMC jumpskirt
add: TGMC skirtlenecks
imageadd: TGMC skirts
code: marine vendors and code for the skirts
/ 🆑 

https://github.com/tgstation/TerraGov-Marine-Corps/assets/114457130/ec2ad0ff-0187-4f9c-8ed1-5c99fff7a965

### CODE REVIEW

**Comment by aarrisu** [comment]
balls

**Comment by Pariah919** [comment]
this had been done bfore, this isn't even a good joke anymore so why should it be merged

**Comment by FosterGrime-Heymynameslouie** [comment]
skirts (overdone, unfeasible in combat, feminine, makes you look stinky) VS  kilts (a show of dominance, powerful symbol of pride culture and masculinity, tactically cool and practical, already in game)

**Comment by SzkieletorNutric** [comment]
Watch as lumi merges this

**Comment by Kuro020** [comment]
You didnt really think I was gonna let this happen did you

**Comment by TheUSSWatercooler** [comment]
Why not, eh?

**Comment by sa1tman** [comment]
tyrant

**Comment by DerFlammenwerfer** [comment]
In Kuro's defense, those skirts look like garbage.

**Comment by TheUSSWatercooler** [comment]
yeah

**Comment by EaglePhntm** [comment]
either way should include E8 gloves bro. they get overwritten.

**Pull request closed without merging**
