### PR TITLE
Lets the queen SLAP

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Adds the queen slap , a brand new way to counter SMG rushers and bodyblocking as the queen
It will deal 30 brute(accounting for armor) , 60 stamina , drowsiness , deafness and stagger on humans
it makes friendly xenos permit passing
it deals 80 brute to enemy xenos.

Slapping footage:
https://user-images.githubusercontent.com/61350382/191130797-2d2f6bd6-ba25-4e51-9a35-e70bbef943fb.mp4

Icon sprite : 
image

## Why It's Good For The Game
SMG's have crazy damage potential , so the queen should have a crazy slap to give when they get too close.
(Also queen desperately needs more abilities for fighting marines in CQC other than spit and scream)

## Changelog
:cl:
balance: Added a new queen ability , The SLAP.
/:cl:

### CODE REVIEW

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Icon sprite is super whack, you need to put in some actual effort there

**Comment by Lumipharon** [comment]
You need a slapped emote sound for humans.
https://youtu.be/IzukIA7qU9Y?t=46

**Review by Pariah919 — CHANGES_REQUESTED** [review]
Terrible balance.

**Comment by FosterGrime-Heymynameslouie** [comment]
I thought the queen was gonna use her tail to slap and maybe fling people away from her like defender tail but I guess straight up slapping them with her hands is also equally funny

**Comment by ivanmixo** [comment]
Funny but the balance is super wack. And I really don't think queen needs more abilities.

**Comment by novaepee** [comment]
> slap is for self-defense
> slep is then used for more than self-defense
> back to tail sweep

**Comment by Weedmaster77** [comment]
> I thought the queen was gonna use her tail to slap and maybe fling people away from her

I think this idea might be better make it kinda like the crushers crest toss but only in the away direction not behind like the crest toss since its made to get the rusher away from queen and not into a gank.

**Comment by MathiasOrtega** [comment]
Salt PR of a Queen caught out? Imagine not using screech then acid spit and slash to kill a marine. If a PR’s only leg to stand on is ‘I died to this’ why even humor it?

**Comment by Serxule** [comment]
queen shouldnt be alone nor frontlining unless they're going to screech, otherwise there should be other xenos to already stop said rushers, very unbalanced and also, skill issue.

**Comment by Losenis** [comment]
"queen shouldnt be alone nor frontlining"

More often than not, you don't get the luxury of choosing to not be either of those

**Comment by Naaanii** [comment]
- Xenos already have the ability to shuffle since help intent takes prio iirc.

- A stun dealing damage AND stunning with multiple debuffs is a bit much.

- This can be combined with screech to be way too oppressive for a single marine.

- Screech already cucks SMG users rushing.

All that being said, a new ability doesn't hurt, but it should be less powercreepy and have a good use other than 'fuck this type of player in particular' use. Even tail sweep is a better addition than this honestly.

**Comment by Losenis** [comment]
>This can be combined with screech to be way too oppressive for a single marine.

I'll do you one better, the stamina damage from screech and stamina damage from slap will stack into oxydamage once it depletes stamina. It's why when admins reduce cooldown of screech at roundend to spam it it literally kills you.

**Comment by TiviPlus** [comment]
Funny, but:
1) Queen already has too many buttons
2) Disagree that queen needs more melee abilities
3) "This ability is to counter X weapon"
4) You already have shuffle priorities forcing people to help is only useful to grief
5) Funny but mechanically uninspired since it's just deal damage with no feedback barring the slap sound

**Pull request closed without merging**
