### PR TITLE
Armor storage bugfix

### PR DESCRIPTION
**Pull request by Hughgent**
🆑 Hughgent
fix: Re-adds limits to armor storage, no more backpack flamer tanks and 100 shell shotgun boxes in there.
/🆑 

image
image

### CODE REVIEW

**Comment by Hughgent** [comment]
Might as well prepare for the lasguns getting in as well.

**Comment by Hughgent** [comment]
it would require a rethinking of slot based inventory, and the w_class of certain objects. something like max_w_per_slot.

at the moment, pure slot inventory is slated at size w_class 2 or less. most magazines are w_class 3. (pistol mags are 2)

the bypass_w_limit allows anything in the list to go past the 2 size, but it's still limited by the max_w_limit of 6 for the whole inventory.

problem was that shotgunbox is essentially a magazine that brought out hand fulls of shells at w_class of 5, so you could fit a single one in there. and that large incinerator tank and the rockets were also w_class 3.

**Comment by Ghommie** [comment]
We could always blacklist large incinerator tanks and rockets, but either ways it's good.

**Comment by Hughgent** [comment]
white listing is smaller and easier. before you could get in the sentry ammo drums if you so chose.

**Comment by Rohesie** [comment]
Why not make it `pockets.max_w_class = 3` and increase the size of the offending items you don't want to fit in backpacks?
Or diminish the weight of ammo while keeping the storage size?

**Comment by Hughgent** [comment]
Reworking the weight classes would require a lot of effort and a list of almost every item in the game. It's simpler and more "realistic" (in that the pockets are of a certain rifle magazine shape) to make things bypass the slot limitation. as my larger rifle magazine fits the pocket perfectly, but my smaller flashlight fits as well.

image

**Pull request merged**
