### PR TITLE
Adds an ozelomelyn hugger

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/dfe934b6-d739-4a66-a5e4-4575b3123b4f

dreamseeker_vFHXZyUSjG
I'd have made them white but the way the color shifting works it's not possible until the hugger sprites are remade to be hyperscale or such

## Why It's Good For The Game

More variety and it makes sense since it evolves into a defiler which has ozy.
## Changelog
:cl:
add: Adds an ozelomelyn hugger
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]

**Comment by Xander3359** [comment]
This is an insane buff considering oze is the strongest chem xenos have and is typically restricted to T4s and Defiler

**Comment by novaepee** [comment]
> This is an insane buff considering oze is the strongest chem xenos have and is typically restricted to T4s and Defiler

just shoot the huggers

**Comment by Helg2** [comment]
Just catch the huggers.

**Review by Lumipharon — APPROVED** [review]

**Comment by Lumipharon** [comment]
just turn the huggers into soup.

**Comment by GuyGuysonF19** [comment]
Very good PR, this will make carrier more threatening

**Pull request merged**
