### PR TITLE
TG colored plainchat

### PR DESCRIPTION
**Pull request by Neocloudy**
## About The Pull Request
***(darkmode only)***
tg-colored plain chat. instead of it just being white, it's slightly blue (update 25th february: pink dchat removed)
image
image
image

## Why It's Good For The Game
Plain white chat doesn't really pair well with our *new* colors or examine blocks. The one from basically every other TGchat codebase looks better with the new styles and examine blocks. I nearly did this in 14850 but didn't feel like figuring it out. 
Pink dchat with the plain colors in this PR should work better too.
## Changelog
:cl:
add: new plain chat style
/:cl:

### CODE REVIEW

**Review by Lumipharon — APPROVED** [review]

**Comment by Lumipharon** [comment]
I dislike the colours tbh, less contrast between normal and dchat makes it harder to read.

**Comment by Fawcksy** [comment]
The new pink color is incredibly close to alive-chat and hurts my eyes. I believe that the singular user who uses light mode also can't see it due to contrast. I beg of you bring back the purple

**Comment by Neocloudy** [comment]
doesn't affect lightmode, but i'll likely revert it back to the purple before this pr since players and maints don't like it

**Comment by Kapu1178** [comment]
My eyes are sensitive, and highly contrasting colors like bright pink on black are tiresome to look at.

**Comment by Lumipharon** [comment]
readable now

**Comment by lbnesquik** [comment]
The bravo color is still terrible.

**Pull request merged**
