### PR TITLE
remove TL-172 Defensive Shield from crash and nuclear war

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

You cannot get TL-172 Defensive Shield in Crash and Nuclear War anymore, but you can use shield in HvH and Vahalla.

This mean you cannot buy TL-172 Defensive Shield from req or get one from armament vendor.

## Why It's Good For The Game

Tanky marines in HvX bad, maintainers said.

## Changelog

:cl:
balance: remove TL-172 Defensive Shield from crash and nuclear war
/:cl:

### CODE REVIEW

**Comment by TellyLsc** [comment]
Don't shields slow marines down while worn already? I thought that's the point, more slow for more eHP. Plus the shield user would need to wear weld goggles/carry or use weldmodule+welders if they really want to keep it up, limiting their loadout even more.

**Comment by FosterGrime-Heymynameslouie** [comment]
> Don't shields slow marines down while worn already? I thought that's the point, more slow for more eHP. Plus the shield user would need to wear weld goggles/carry or use weldmodule+welders if they really want to keep it up, limiting their loadout even more.

literally this

with all the prs removing human choices for increasing survivability you are essentially recreating the conditions on how to make gameplay like CM

do you want every single marine to be a glass cannon paper mache meat puppets like CM?

**Comment by SimplySmiley123** [comment]
> Don't shields slow marines down while worn already? I thought that's the point, more slow for more eHP. Plus the shield user would need to wear weld goggles/carry or use weldmodule+welders if they really want to keep it up, limiting their loadout even more.

Plus if their shield takes _too much_ damage, they have to find metal somewhere to repair their shield, so they either have to be an engi, find an engi that isn't busy with anything or carry their own tools and metal somewhere or scavenge groundside for metal.

**Comment by chizzy376** [comment]
This got already nerfed 3 times, the item is in a good balance right now
Close this haha

**Comment by Yttriums** [comment]
Makes the game smaller and less interesting. Xenos have counters to defensive stacking

**Comment by 1kajowsmol** [comment]
Poor taste PR

**Comment by novaepee** [comment]
the gods have spoken

**Comment by ivanmixo** [comment]
Nuh uh

**Comment by lbnesquik** [comment]
Terrible move

**Comment by Ragecrabbo** [comment]
Why not just nerf it again if its an issue? Why remove something someone worked on for hours when you could just do a one line change to make it less effective.

**Comment by ivanmixo** [comment]
Because its core idea is "make marine tanky". If it got nerfed to a reasonable degree it'd just not be worth it at all

**Comment by chizzy376** [comment]
i'd like to know if the "do not merge before 24 hours" rule applies to reopened PR's that have been previously closed

**Comment by SimplySmiley123** [comment]
Wait this was a closed PR, how the fuck did it get merged?

**Pull request merged**
