### PR TITLE
makes resin holes 2 pixels wide

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image
image

## Why It's Good For The Game
he asked for it

## Changelog
:cl:
balance: resin holes are literally two pixels
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
image

**Comment by BraveMole** [comment]
they should be invisible ngl

**Comment by TiviPlus** [comment]
meme pr

**Comment by Ieteihowmee** [comment]
Dear lord could you imagine if this was a serious PR, the amount of marines that would get face fricked is beyond comprehension.

**Pull request closed without merging**
