### PR TITLE
Lower Jetpacks cost from 15 to 8

### PR DESCRIPTION
**Pull request by Lauwma**
## About The Pull Request
ReQ cost change to an item that doesn't really get any use due to its expensive cost.
Jetpack cost: 15 -> 5

## Why It's Good For The Game
Jetpacks aren't used by a lot of marines, not because of the drawbacks it has (Lack of backpack storage/second weapon) but because its price in req is way expensive for what it does.
The item doesn't need to be stronger in my opinion, it has already the ability to escape warriors/shrikes brazil abilities and give a nice leap when you need to keep shooting at a target to finish it. That's why lowering the price would maybe make it more usable. A lot of ROs thinks jetpacks are a waste of points.

At first I wanted to put the jetpack in the vendor to make it consistant but I was afraid it would become a powergaming strategy (we don't want that to happen).

10 points seems like a large cut because with 105 points you can equip 21 marines with a jetpack instead of 7 but valks/surts/hlin are common and makes that the RO is usually left with less than 20 points (who would use what's left on a single jetpack ?).
Still, after the changes, if jetpacks are becomming too common a raise to 10 would be more appropriate.

## Changelog
:cl:
balance: Lowers Jetpacks cost in requisition from 15 to 5.
/:cl:

### CODE REVIEW

**Comment by AgentMA1** [comment]
>5 points for Jetpack

What.

**Comment by RenGusta** [comment]
Hot.

**Comment by Wayland-Smithy** [comment]
I think a 2/3 cost reduction is a bit much, also don't forget to make your changelog more descriptive so players in-game know what you did.

**Comment by Lauwma** [comment]
After reviews I'm considering to lowering the jetpack to 8, roughtly halving the price and making that a module + a jetpack would cost 20. (I mean valkiries are supposed to fly no ?)

**Comment by Lauwma** [comment]
Well uh I did an oopsie with my fork, I can't make changes now but well I guess I'll make another PR if it's approved

**Pull request closed without merging**
