### PR TITLE
makes peridaxon OD worst. but also makes it heal cloneloss

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
simple as the title
at the regular OD
gives the player
        4 Brute damage (this hurts)
	0.5 healing of clone damage (this heals)
	and medium pain
	and drains 3 stamina
	
at critical OD
 	all the things regular OD have PLUS
 	
 	3 brute damage 3 burn damage
 	1 healing power for clone damage (summing up to 1.5 still lower than how much the RR causes and you are getting 5 brute per tick that also makes the RR null
 	a HEAVY pain. so to not be used in premed or mixes lightly
 	and drains +7 stamina (for a total of 10)
 	
 	

## Why It's Good For The Game

will hopefully give players less CBT when dealing with clone damage. so far RR is the only one that causes it. but just lke the QC plus and Peri plus exist this will hopefully get more chem in play while balanced

## Changelog
:cl:
tweak: makes peridaxon OD worst. but also makes it heal cloneloss
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -14. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by joookschad** [comment]
this is gonna make russian red even more stupid OP, please merge..

**Comment by davidchan13** [comment]
> this is gonna make russian red even more stupid OP, please merge..

>Russian Red
>OP

Pick one.

**Comment by joookschad** [comment]
> > this is gonna make russian red even more stupid OP, please merge..
> 
> > Russian Red
> > OP
> 
> Pick one.

>be medic
>take neuraline
>take russian red pill
>heal 13,5 brute and burn per tick

**Comment by fernandos13** [comment]
> > > this is gonna make russian red even more stupid OP, please merge..
> > 
> > 
> > > Russian Red
> > > OP
> > 
> > 
> > Pick one.
> 
> be a medic
> take neuraline
> take a russian red pill
> heal 13,5 brute and burn per tick

you can already do that.. as is.. i mean.. this doesn't change the RR..
plus this deals damage....

**Comment by joookschad** [comment]
Yes but the whole bad part of using russian red in your chem mixes is having to go shipside and get your clone damage fixed, not just standing in the FOB for 2 minutes waiting for your clone damage to heal

**Comment by SplinterGP** [comment]
i'd say add cloneloss surgery maybe ? fun thing for medics i guess.

**Comment by TiviPlus** [comment]
The POINT is to add a hard to heal damage so this PR counters the point of russian red

**Pull request closed without merging**
