### PR TITLE
Shotgun Shell Rebalance - Buck

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request
Buckshot has vastly reduced scatter and damage falloff, as well as increased stagger. In return, it no longer full stuns and has less knockback.
Basically, I took Ren's and MJP's suggestions and I turned it into a PR. 

I'm fully expecting this to be closed immediately, but it's not really my ideas anyways.
## Why It's Good For The Game
Currently, shotgun isn't really that good, especially buckshot. Buckshot is currently just a melee weapon and even then, it does less damage on PB than flech does in most cases.

Even like this, in-game testing shows that it gets outperformed by flech in terms of damage at any reasonable range and armor, with the sole exceptions of runner and drone at point blank range.
## Changelog
:cl:
balance: buckshot now has vastly improved ranged capabilities, as well as increased stagger in return for its hardstun and some knockback.
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
i don't think buck should be more range, if its worser than flech in pb then it should be buffed to counter that not making it more like flechette where you're shooting farther.

**Comment by RenGusta** [comment]
Having seen it comparatively tested reasonably thoroughly, I'm confident this will make Buck at least appear more in general instead of just in PB. Could always balance flech and buck off one another, but that's the topic of another PR after this one.

**Comment by OrbisAnima** [comment]
I like the change, but shouldnt the /datum/ammo/bullet/shotgun/spread also get the modification to the damage falloff to 2 instead of 4?

**Comment by lovegreenstuff** [comment]
> I like the change, but shouldnt the /datum/ammo/bullet/shotgun/spread also get the modification to the damage falloff to 2 instead of 4?

yes. i am stupid.

**Comment by lovegreenstuff** [comment]
closing for balance freeze

**Comment by lovegreenstuff** [comment]
didn't have to close this for balance freeze apparently.
am stoopid

**Comment by TiviPlus** [comment]
Making buckshot flechette lite is not buckshots intended role its supposed to be the close range option

**Pull request closed without merging**
