### PR TITLE
add ammoboxes to vendors

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
adds ammoboxes "that are already in code" to the marine vendors

## Why It's Good For The Game
better roundstart prep HOPEFULLY less magazines thrown away

## Changelog
:cl:
tweak: adds ammoboxes "that are already in code" to the marine vendors
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -7. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Add these to the OPs vendor the marine weapon vends are too bloated

**Comment by Chaznoodles** [comment]
These pre-loaded boxes are already available via Requisitions for some points per. The reason I didn't put these into the Ops Vendor was because you may as well remove the packable ammo boxes, and it means people are relying on one or two specific ammo boxes rather than being able to pack a few for their buddies.

**Comment by fernandos13** [comment]
`Add these to the OPs vendor the marine weapon vends are too bloated`
was the original idea but i pushed the wrong branch and thought i should wait for the discussion to come so we can discuss HOW many even should be there ((moving to ammo vendor though))

`These pre-loaded boxes are already available via Requisitions for some points per. The reason I didn't put these into the Ops Vendor was because you may as well remove the packable ammo boxes, and it means people are relying on one or two specific ammo boxes which might get hidden or lost, rather than being able to pack a few for their buddies that they know exist.

They also require a magazine as the contents are loose bullets.`

the 10x24 ammo  box indeed need magazines to be used
but the other boxes have magazines themselves like the big t19 box. comes with 40 t19 MAGAZINES

so i propose we make this changes

make 4 ammo boxes that just got BULLETS

- rifle bullets with 800 in them ((for rifles like T12 and T42 and T18))
- DMR bullets 400 ((for the battle rifle and the DMR))
- pistol bullets with 400 in them ((for TP14 and TP... 23?))
- smg bullets with 1600 in them ((for the T19 and T90))
- LMG/HMG with 1600 bullets in them ((for the T60 ammo kind))

**Comment by fernandos13** [comment]
should i make those changes ? ye no?

**Comment by TiviPlus** [comment]
Move it to Ops vendor the standard marine vendors are too bloated

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-9). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
