### PR TITLE
Fixes config settings related to organ health multiplier and healing rate

### LINKED ISSUE #328: You cannot break limbs because config file is wrong
organ_health_multiplier is equal to 100; delimb is calculated as
if(CONFIG_GET(flag/limbs_can_break) && brute_dam >= max_damage * CONFIG_GET(number/organ_health_multiplier))
This means you need to deal about 3000 damage to the legs for a chance to break it

### PR DESCRIPTION
**Pull request by ma44**
:cl: ma44
fix: A major bug that made limbs impossible to break or delimb
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
Cause this basically removes the ability to delimb or break bones, which is a major factor in bay med as well as a huge nerf to xeno melee castes

Fixes #328

This was a thing because previously the value was 100/75, but this number then got divided by 100 to determine the percentage, this wasn't included when the configs were redone.

Old code for divide by example
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/blob/master/code/controllers/settings/game_options.dm#L49

### CODE REVIEW

**Comment by DominikPanic** [comment]
`ORGAN_REGENERATION_MULTIPLIER 0.75` that is set as an integer in the config entry, you have to either set it to 1 or set the integer to false.

**Comment by Qustinnus** [comment]
that's dumb, modifiers should be scalars

**Comment by DominikPanic** [comment]
> 
> 
> that's dumb, modifiers should be scalars

Yeah, not arguing that but in it's current form it would give config errors and wouldn't work.

**Comment by Qustinnus** [comment]
I realize that dw, we should fix it in this PR though

**Comment by Rohesie** [comment]
Current value in the configs is `ORGAN_REGENERATION_MULTIPLIER 1`. Is that what we are after, @DominikPanic ?

**Comment by DominikPanic** [comment]
> 
> 
> Current value in the configs is `ORGAN_REGENERATION_MULTIPLIER 1`. Is that what we are after, @DominikPanic ?

I changed that so it wouldn't break things since to make it a non-integer requires code changes. It was a hotfix to not make it be 100.

**Comment by Rohesie** [comment]
Then this can be safely closed, though we'll want to port the game configs to the repo's.

**Pull request closed without merging**
