### PR TITLE
Yet more Sulaco QOL

### PR DESCRIPTION
**Pull request by Derrick2Electricboogaloo**
## About The Pull Request
Derrick here with reports from Drydock. What has been done? More Sulaco QOL, namely a much needed CIC overhaul and SD overhaul to make them both more viable for any potential holds should xenos decide hijacking is their purgative. I have also taken some time to clean up the Sulaco area file to cut down on no longer relevant or used areas.

CIC: Before:
cicbefore

CIC: After:
Sulacoafter-2CIC

I moved the FC's office to where the SOs unused rooms were. I think it works better this way.
Sulacoafter-2FCroom

Adjusted these to be in better positions:
InkedSulacoafter-2Req_LI

Here is the new SD, since updated from 6 months ago:
Sulacoafter-2SD

## Why It's Good For The Game
Sulaco needed more love I intended to give it. CIC needs an overhaul it is horribly dated and ugly. It now flows better now. SD is better to hold now. Shifts some crash sites in the Sulaco to prevent alamo from punching into space. (Will continue to monitor this for issues) Anyways QOL and map fixes good, old outdated stuff bad. I definitely want to see this atleast TM'd while so when I am active I can monitor it and adjust the map. The first TMs I was not here for but it took a week to find a fatal issue so apparently it did fine up until a long round.

## Changelog
:cl:
fix: SMESs in engineering updated with new SMESs no more cheeky aciding.
fix: Tcomms devices in CIC actually function and serve a purpose now.
fix: adjusted placement of two dropship crash locations. (Req and marine prep)
fix: fixed all the button sprite positions, and sprite icons
fix: added more engine room blast door buttons so it is harder to get locked in
qol: CIC overhaul, SD updated.
qol: CIC armory added (can only be access during hijack)
qol: Sulaco Area File Cleaned up.
qol: Moved PO bunks to Hangar
qol: Added more lights to req
qol: Overhauled Req area to help with flow
qol: A few more AI displays around ship
qol: Re-added a disposal system to Sulaco.
qol: Corrected the disturbing lack of cigars.
qol: Adjust CAS area to fix with Elsa's standardization
qol: Adjusted and fixed drop pod area
qol: Added more lighting all over the ship, it is not so dark anymore.
qol: Adjusted medbay a bit so it looks better
qol: Moved garden to medbay.
qol: Replaced all double 1x1 doors with newer 2x1 doors
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
Cool. Making PRs Works better when I am not flagged for BS.

**Comment by BraveMole** [comment]
Pics?

**Comment by Derrick2Electricboogaloo** [comment]
> Pics?

Yeah I forgot to add them, Give me a second.

**Comment by Derrick2Electricboogaloo** [comment]
Oh my god this linters check. I am not even sure where to add the return at. I just added a machine down the line of presets.

**Comment by Derrick2Electricboogaloo** [comment]
Wow. Was a stupid thing. All I had to do was go in and press ENTER. I am so >:| Thanks Brave.

**Comment by GradusNL** [comment]
Can you provide a more zoomed out picture of CIC after? From what I can see it looks like you reduced the amount of entrances/approaches to CIC, which isn't QoL but a significant balance change. A second fully functional tcomms at CIC isn't very balanced either.

Also, can you provide before/after pictures of SD? You haven't shown any pictures of SD.

**Comment by Derrick2Electricboogaloo** [comment]
> > > Can you provide a more zoomed out picture of CIC after? From what I can see it looks like you reduced the amount of entrances/approaches to CIC, which isn't QoL but a significant balance change. A second fully functional tcomms at CIC isn't very balanced either.
> > > Also, can you provide before/after pictures of SD? You haven't shown any pictures of SD.
> > 
> > 
> > The overhaul itself is QOL, the reduced entrance to the right is to help make CIC a more viable option for defense by reducing your fronts. Most of the space before was not even necessary for anything. That is about the size of CIC. Give or take a few tiles to the left.
> 
> Tag the PR with balance if you are balancing, don't disguise it with QoL. Claiming that making CIC "a more viable option for defence" is part of a QoL overhaul doesn't make it QoL. And based on what I can see (since you aren't providing a clear picture) you have reduced the amount of entrances to CIC to two chokepoints (main entrance and captain's office maint) while there used to be five (main entrance, captain's office maint, captain's office itself, FC's office and FC's office maint). I don't get it, since CIC was already viable.
> 
> You also haven't addressed adding a duplication tcomms nor shown any picture of the changes to SD. I don't get why you are trying to make shipside even more marine-sided. All in all, you not properly tagging the PR and refusing to give (clear) pictures of the changes to CIC/SD gives me a shady feeling about this whole PR. I wouldn't mind seeing a TM of this, but the current issue with shipside is NOT that it isn't viable for marines to hold. More like the opposite.

It is not a balance since it is entirely optional and can be safely avoided. It is QOL because Sulaco CIC is stale and outdated beyond belief. It is not a sweeping gameplay change out of the norm.

**Comment by GradusNL** [comment]
> It is not a balance since it is entirely optional and can be safely avoided. It is QOL because Sulaco CIC is stale and outdated beyond belief. It is not a sweeping gameplay change out of the norm.

Your definition of balance is very wacky. Changing the stats of a gun wouldn't be balance either since nobody has to use it, for example. I finally figured out that you can use the bot to look at the changes and I gotta say, your CIC and SD changes are absolutely horrible. You have basically surrounded them both entirely by space, leaving two ways in for each. You've also put free mats at both CIC and SD. Saying that something is stale and outdated isn't a valid reason to make them braindead easy to defend. Marines should have numbers and gear if they want to successfully defend shipside.

**Comment by BraveMole** [comment]
image

I want another maint entrance on the north

image

Just no for this, it's a nightmare for xenos. Old sd was fine

**Comment by TiviPlus** [comment]
You also need to update /obj/vehicle/powerloader to /obj/vehicle/riden/powerloader in your map

**Comment by Derrick2Electricboogaloo** [comment]
> You also need to update /obj/vehicle/powerloader to /obj/vehicle/riden/powerloader in your map

Alright. Give me a bit. I just now logged back on.

**Comment by Naaanii** [comment]
Finally getting an actual armoury in CIC is nice, I'd recommend placing a Weapons and Clothing Vendor like the POS CIC has for consistency.

I do also agree with Gradus that moving TComms to CIC, the fewer entrance to CIC, and the new SD design is a straight buff rather than QoL. Incentivising marines to hold SD over CIC might not be a bad idea overall however, with changes that might be better for marines but not too CBT for Xenos.

**Comment by Derrick2Electricboogaloo** [comment]
> 

Absolutely. I have changed SD a bit more, added more ways for beans to flank it by reworking maint all around it. I want it TM'd so I can see how it plays and make some changes acoording. Personally, Shipside should absolutely be marine sided and feel that way. The way that when marines get to the ground we have to deal with all the prep work of xenos.

**Comment by Derrick2Electricboogaloo** [comment]
> Finally getting an actual armoury in CIC is nice, I'd recommend placing a Weapons and Clothing Vendor like the POS CIC has for consistency.
> 
> I do also agree with Gradus that moving TComms to CIC, the fewer entrance to CIC, and the new SD design is a straight buff rather than QoL. Incentivising marines to hold SD over CIC might not be a bad idea overall however, with changes that might be better for marines but not too CBT for Xenos.

Secondly the armory in CIC here is locked until red, because it does have free mats (plasteel and metal) along with other gear. I think it feels better having it restricted until hijack.

**Comment by RipGrayson** [comment]
I'm unsure about whether basic t-comms staying intact after xeno crash is a good thing. Overall it does seem this PR makes Sulaco harder for xenos, and they already struggle(more) on Sulaco as it is.

But anyway, there's nothing functionally wrong with this PR and balance concerns like that are for actual maintainers. I have a few tiny nitpicks but nothing major.

Please fill the empty gaps between stairs here, preferably with /obj/structure/stairs/seamless
stair1

This PR seems to have reverted Elsa's change to landing pad markings is this intentional?
sullandin

The biggest thing are button errors, quite a few of them aren't set properly and will initialize through walls.
button3
button4
button5
While this mostly a cosmetic concern, it can also put a critical button completely out of reach.

**Comment by novaepee** [comment]
@RipGrayson has given me the power to check maps.

image

image

Need powerloaders.

image

Going to have to nick pick, pipes go through doors.

image

I recommend filling this out so that captain has more room. In my personal opinion, captain should get more room since he is O6 in rank.

image

Make a north maintenance hall to enter CIC. Theseus and PoS have three enterances to get into CIC (with the exception of Minerva, but that's another story). I know that marines like to dig their grave in Sulaco CIC, hence it is important to make it hard on them to do so.

image

Use 2x1 doors.

image

Keep the Req Overwatch close to the supply drop so that Req Overwatch can double check if marines get the supplies.

image

I do not see the operational vendor.

image
image

Use the 2x1 black doors for firing range for EXTRA EDGE and consistency.

image
image

When you REALLY WANT an extra challenge, my two suggestions:

- Make medbay and req closer to landing zone
- Change positions of hanger (Condor, surgery station, supply place, ladders)

I recommend making this radical change to hanger when you make staircases in your next Sulaco PR for additional QoL.

image

Aesthetics take, you can put bunkers here for some RP.

image

This shouldn't exist.

image

Port and starboard port shouldn't be next to each other, to be honest. Then again, this is hard since you can't make it horizontal. Maybe ERT shuttle remap can change that . . .

**Comment by Derrick2Electricboogaloo** [comment]
> 

Copy yeah I can add the extra guns. I was not sure if it was ONE each or two, all I knew is that the ammo was 4 each should have read that clearly. I was thinking of adding the extra maint to CIC, but I want to see it TM'd first without it. Shipside should 100% be marine sided and CIC is rarely if ever held now since hanger is just superior on Sulaco. I need to fix req and add the med vendors to medical for sure. Thanks for making sure. I thought I forgot something.

**Comment by Derrick2Electricboogaloo** [comment]
> 

Secondly, yeah I plan on killing hangar medbay, and turning it into CAS storage. Pushing medbay closer is an interesting one, never thought about it being 100% necessary, but eventually I want to rework the design more, especially in terms of moving the morgue to a more accessible area for medical staff if they are so inclined to use the room. On the topic of the ERTs. I can start brain storming ideas for that. They have been that way for a while now. Once I fix the req and med prep issues, I can move onto getting the doors. I have to update my master again since I was finishing up when they were added. Bunkers have been an interesting idea as well, but I would rather engineers take the initiative and use their brains to do it.

**Comment by Derrick2Electricboogaloo** [comment]
Gave it some thought I will rework some of my req rework and work on the OW console position. I just got some ideas. I appreciate the feedback, this is how I get better.

**Comment by Derrick2Electricboogaloo** [comment]
> 

The removal of the warning strip was unintentional, also the T-comms in CIC I want to start turned off, but for some reason they start on, you can even check the code and I have it state: on = 0 <--- which should make it off since in my testing on a local server that is the value for 'off'

**Comment by Derrick2Electricboogaloo** [comment]
> @RipGrayson has given me the power to check maps.
> 
> image image
> 
> Sulaco needs corpsman vendor. First picture is Sulaco, and second picture is PoS.
> 
> image
> 
> image
> 
> Need powerloaders.
> 
> image
> 
> Also, need two of the CAS armaments
> 
> image
> 
> Going to have to nick pick, pipes go through doors.
> 
> image
> 
> I recommend filling this out so that captain has more room. In my personal opinion, captain should get more room since he is O6 in rank.
> 
> image
> 
> Make a north maintenance hall to enter CIC. Theseus and PoS have three enterances to get into CIC (with the exception of Minerva, but that's another story). I know that marines like to dig their grave in Sulaco CIC, hence it is important to make it hard on them to do so.
> 
> image
> 
> Use 2x1 doors.
> 
> image
> 
> Keep the Req Overwatch close to the supply drop so that Req Overwatch can double check if marines get the supplies.
> 
> image
> 
> I do not see the operational vendor.
> 
> image image
> 
> Use the 2x1 black doors for firing range for EXTRA EDGE and consistency.
> 
> image image
> 
> When you REALLY WANT an extra challenge, my two suggestions:
> 
> * Make medbay and req closer to landing zone
> * Change positions of hanger (Condor, surgery station, supply place, ladders)
> 
> I recommend making this radical change to hanger when you make staircases in your next Sulaco PR for additional QoL.
> 
> image
> 
> Aesthetics take, you can put bunkers here for some RP.
> 
> image
> 
> This shouldn't exist.
> 
> image
> 
> Port and starboard port shouldn't be next to each other, to be honest. Then again, this is hard since you can't make it horizontal. Maybe ERT shuttle remap can change that . . .

Oh the pipes! Heh, they is where the door was before! I kind of agree with the captain room increase, I will do something about that.

**Comment by Derrick2Electricboogaloo** [comment]
Also I made sure to add the powerloaders back, no idea how I forgot that. Deleted that massive quote I made.

**Comment by RipGrayson** [comment]
Buttons still aren't all fixed, otherwise looks fine to me. Elsa is arguably more qualified than me to judge shipside balance, so please consider their suggestions.

**Comment by Derrick2Electricboogaloo** [comment]
> 

Which buttons? I fixed the ones in sec? And the ones in surgery are repositioned to not be in space.

**Comment by RipGrayson** [comment]
Please don't do this, nodes connect diagonally.
nod1

These nodes aren't connected, but should be.
nod2

Don't stack nodes like this please,
nod3
nod4

if you need to connect to another row please do something like this instead 
nod11

These AI nodes cannot be reached by anything
nod5
nod7

These nodes near req don't actually connect to req or anything else
nod6

The nodes here connect through dense objects, please don't do that.
nod9

I'm not sure if this is your fault, but the only way for minions to get south lower floor is through maint because this connection is broken
nod8

**Comment by Derrick2Electricboogaloo** [comment]
> 

Will do, some of these nodes were from before. I will make adjustments soon. Thanks!

**Comment by Derrick2Electricboogaloo** [comment]
Forgot to list it, but I also added the powerload back to OB room since I missed that in my edits.

**Comment by RipGrayson** [comment]
This set of nodes isn't connected, but it could be easily fixed by inserting a node in the circled area.
nod1

Stacked nodes
nod4

The clone tube is dense and will block the path between the two nodes here
nod5

The sleepers here will block the pathing between these two nodes
nod6

The disposal unit blocks pathing between these two points.
nod2

The circled nodes are completely disconnected from everything else, please fix them
nod3

**Comment by RipGrayson** [comment]
All AI nodes are fixed now, all that's needed is a new TM

**Pull request merged**
