### PR TITLE
Adds cave roof for Blue disk in Desparity

### PR DESCRIPTION
**Pull request by chizzy376**
## About The Pull Request
Can't land here anymore 
image
## Why It's Good For The Game
Being able to land in caves is bad, unintended thing being gone = good
## Changelog
:cl:
fix: can't land tad in blue disk on Desparity anymore
/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
ah shit

**Comment by chizzy376** [comment]
We are so back

**Comment by iforgotmeword** [comment]
You do know this also going to stop marines fire support too right?

**Comment by chizzy376** [comment]
Do I really need to open a new PR if the windows buuld check got cancelled? I quickly swapped the file for a correct one and don't know what to do

**Comment by chizzy376** [comment]
Oh nice

**Pull request merged**
