### PR TITLE
pride month special

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
the first ever gay roomba race
the sequel to roomba race now in hvh
race
## Why It's Good For The Game
for the occasion
## Changelog
:cl:
add: roomba race
/:cl:

### CODE REVIEW

**Comment by Ragecrabbo** [comment]
speedmerg

**Comment by FosterGrime-Heymynameslouie** [comment]
spemdergh

**Comment by iLikeMemes** [comment]
Truely one of the pride month classics

**Comment by lKiseki** [comment]
image
I relate to this on a spiritual level.

**Comment by Ragecrabbo** [comment]
> image I relate to this on a spiritual level.

the K is missing a tile at the bottom unforgivable gitban this guy

**Comment by Mrrpip** [comment]
...Do we get an ATM so we can bet money?

**Comment by Alexeivichi** [comment]
Relevant: https://www.youtube.com/watch?v=N1D4Xz-3YE4

**Comment by zzurge** [comment]
Fake and Gay

**Comment by tyeagg** [comment]
pride month is over

**Pull request closed without merging**
