### PR TITLE
Rename the sulaco to the tGS sulaco to better fit

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
All ship maps except the Sulaco are called TGS_Something. This PR changes that.

## Why It's Good For The Game
More consistent for mappers. 

## Changelog
:cl:
code: Renamed sulaco to TGS_sulaco
/:cl:

### CODE REVIEW

**Review by RipGrayson — APPROVED** [review]
Sure, might need config changes though.

**Comment by AzonStarfall** [comment]
Fairly certain that this will also break the shipside webmap. We'll need to get it updated ASAP once this is merged.

**Review by TiviPlus — APPROVED** [review]
I'll do config once geadmins un-break access to it

**Comment by TiviPlus** [comment]
Wait do I even need to change config for this, I dont see any of the TXTs being changed unless you forgot

**Comment by lbnesquik** [comment]
> Wait do I even need to change config for this, I dont see any of the TXTs being changed unless you forgot

I didn't touch config, and I'm not sure if I should have.

**Comment by lbnesquik** [comment]
Accidentally closed it

**Pull request merged**
