### PR TITLE
Synth Rebalance

### LINKED ISSUE #4701: Old synth uses your real name instead of synth name
## Testmerges:
#4680 #4673 #4652 #4658 #4664 #4587 #4663

## Reproduction:
1: Join or ready up as old synth
2. Your name will be your real name instead of the synth name in prefrences

### PR DESCRIPTION
**Pull request by Hathkar**
## About The Pull Request
Reduced synth melee damage
Synths can no longer wear heavy armor (Unless synth restrictions are off)
New clothing options in synth equipment vendor
Synths take less brute/burn to compensate for not being able to wear armor

## Why It's Good For The Game

Combat synth is against our rules, and these changes will make said combat synth unviable.
More clothing options in the vendors, to encourage dressing up and not just looking like a bog standard marine.

Naked synths take about 12 slashes/spits to go down, a bit more if they're wearing something like a bulletproof vest.

Fixes #4701 

## Changelog
:cl:
add: More synth clothing options
balance: Reduced synth melee damage
balance: Synths can no longer wear heavier armors (Unless synth restrictions are off)
balance: Synths have increased natural brute and burn resistance
balance: Reduced synth max HP from 150 to 125
balance: Old synths are now equally as skilled as regular synths
balance: Some suit's exosuit slots can now hold some more items like flashlights/knives
code: Synths and old synths are now identical stat-wise, the only difference is cosmetic
fix: Old Synths should now actually get their synthetic names
fix: Made synth blood description make a bit more sense
fix: Armors can now hold the attachable bayonet knives, just like the older knives
/:cl:

### CODE REVIEW

**Comment by Hathkar** [comment]
One current issue is that when you try and equip armor by pressing E, you get the message `Your programming restricts wearing heavy armor` about 6 or 7 times in chat.

**Comment by Pariah919** [comment]
make combat synth not worse than new synth in every way other than being able to take some more damage. The entire point of synethic is to be a do all man who can do everything in emergencies and old synths advantage is only useful during fob sieges or sd where you're being owned by acid.

**Comment by Hathkar** [comment]
> 
> 
> make combat synth not worse than new synth in every way other than being able to take some more damage. The entire point of synethic is to be a do all man who can do everything in emergencies and old synths advantage is only useful during fob sieges or sd where you're being owned by acid.

Old synths and new synths are now identical except for appearance.

**Comment by jroinc** [comment]
Personally, I'd give them high HP, but either minimal, or zero melee damage. Sometimes, you need to tank to get shit done as a synth.

**Comment by Hathkar** [comment]
Naked synths take about 12 ravager slashes to go down. Synths wearing something like a bulletproof vest or flak jacket take about 16. That should be plenty of chonk.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Can you change 
GUN_ALLOW_SYNTHETIC
to use SYNTH_RESTRICTED instead?

**Comment by Hathkar** [comment]
> 
> 
> Can you change
> GUN_ALLOW_SYNTHETIC
> to use SYNTH_RESTRICTED instead?

I don't think so, since GUN_ALLOW_SYNTHETIC is a gun bitflag, and SYNTH_RESTRICTED is an item flag. I could just change all instances of GUN_ALLOW_SYNTHETIC to SYNTH_RESTRICTED, but it's probably bad practice to have two flags with the same name.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
