### PR TITLE
Removes the TerraGovTech Corpsmen Vendor

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

Removes the TerraGovTech Corpsmen vendor, all instances of it have been replaced with the NT Med vendor.

## Why It's Good For The Game

The corpsmen vendor serves practically no use, giving out limited amounts of pouchs and other strange items corpsmen can more easily get elsewhere. Replacing it with the NT med allows corpsmen easier access to things they will actually use such as medicine. 

## Changelog
:cl:
del: TerraGovTech Corpsmen Vendor
qol: NT Med now in Corpsmen prep
imagedel: TerraGovTech Corpsmen Vendor
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
A relic of an old time that almost no one wants to maintain. Least it frees up a sprite.

**Comment by goose4429** [comment]
Good PR.

Maybe add the kits from it to the NTmed+?
/obj/item/storage/firstaid/regular = 4,
/obj/item/storage/firstaid/adv = 8,

Possibly replace the cpsman belt there with kits too.

**Comment by Al-1ce** [comment]
>nanotrasen

Was there nothing else you could've came up with?

**Comment by Arctrooper8** [comment]
> > nanotrasen
> 
> Was there nothing else you could've came up with?

Elaborate? NT med is the vendor that's generally in medbay.

**Comment by Al-1ce** [comment]
> Elaborate? NT med is the vendor that's generally in medbay.

I dunno. It's just generic is all. Disregard.

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
