### PR TITLE
Bridge Command Additions [In Progress]

### PR DESCRIPTION
**Pull request by Max-023**
## About The Pull Request

This pull request adds more love to the unloved bridge crew, adding a new Captain's beret and giving the Staff Officer gear a makeover. The SO now has blue gear and a new jacket for extra style and protection. I additionally add protection to the SO's hat, with the captain's beret also featuring protection. I also fix the tan beret because someone forgot about the map variant flags.

## Why It's Good For The Game

The Staff Officer's uniform has not been updated at all since the initial fork from CM, and while their sprites fit the look of CM, it's color schemes no longer stay up to date with the current style of TGMC. Hopefully these recolored sprites look more fresh and in line with the Naval focus. As for the Captain's beret, it always has bugged me that all they get is a generic loadout headgear while the FC gets an armored beret. As for the protection, this would only ever come into play if the SO deploys and the Captain has to repel boarders. Personally, I like the idea of the officers being able to be better signified with their headgear, as that is exactly why the FC's beret is the way it is. The SO's jacket also provides some protection for the purpose of having an officer option for mobility builds.], as their job when deployed shouldn't really be for being a pointman.

## Changelog
:cl:
add: Bridge Officer Jacket
add: Captain's Beret
add: Staff Officer's Beret
balance: Gives the SO cap armor
fix: Tan berets will now show on ALL maps
imageadd: Recolors the bridge officer uniform
/:cl:

### CODE REVIEW

**Comment by EvilMelonTheSecond** [comment]
Not being able to deploy with my beret as SO has been hell.
Thank you random fashion person.

**Comment by joookschad** [comment]
> Not being able to deploy with my beret as SO has been hell.
> Thank you random fashion person.
Hmmm yes today I will deploy without a helmet
*headless*

**Comment by Max-023** [comment]
> > Not being able to deploy with my beret as SO has been hell.
> > Thank you random fashion person.
> 
> Hmmm yes today I will deploy without a helmet
> _headless_

All joking aside, I do think with all the focus on customization, having nonhelmet headgear be armored is just overall better for freedom of choice. Like, we have all sorts of customization that you lose out on much more than just a decap flag by taking a flimsy hat, so why even try to argue why said hat can't offer protection?

**Comment by Pariah919** [comment]
we don't need more snowflake headgear options in this game, jaeger is enough
groundside crew shouldn't be encouraged to deploy anyhow, the issue is that with new CIC, SOs are just irrelevant these days

**Comment by Max-023** [comment]
> we don't need more snowflake headgear options in this game, jaeger is enough
> groundside crew shouldn't be encouraged to deploy anyhow, the issue is that with new CIC, SOs are just irrelevant these days

I wasn't aware people looking how they want was such a problem, but then again knowing you, faceless clones is how you imagine things. To which I reply with go love yourself and let people play how they want to play. We have every single weapon, every tool and attachment designed, and every type of modular piece of equipment imaginable for practical use and tweaking of loadouts, yet you get angry and stomp your feet when someone just wants to wear a cool hat or look just a little more individualized? Where were you when all the snowflake weapons like GPMGs and EBRs, which already go into a role filled by other weapons just with some slight tweaking? Or the ridiculous sword?  While I respect your subjective opinion, its very clear that it leaves nothing of value. Staff Officers aren't required, but neither are a lot of roles. It takes 1 guy with a knife to cute down every silo, but not everyone wants to just be a dude with a knife and they can still contribute to the round that way. SOs can provide valuable intelligence just like an AI, call down CAS strikes when deployed, call OBs either through setting targets or pressing a button on the ship above, as well as other jobs that can impact the round and help the Marines.

Necessity doesn't equal utility, nor should it be the major factor in SPRITE changes and number tweaking.

**Comment by SplinterGP** [comment]
Why does CIC berets need armor, FC one only has armor because it needs to deploy and is a thing that makes them stick out a bit more(which also may be bad due to xenos focusing you) and still also has no decap protect

**Comment by Max-023** [comment]
> Why does CIC berets need armor, FC one only has armor because it needs to deploy and is a thing that makes them stick out a bit more(which also may be bad due to xenos focusing you) and still also has no decap protect, the others dont need armor on beret as they dont even leave bridge that much

It is so that when they leave the bridge, they are still recognizable, as well as provide passive armor against xenos who get aboard the ship.

It is in my personal opinion that headgear Marines can wear that isn't helmet options should also have armor so people who use them aren't unnecessary penalized because "muh snowflake". And given that CIC is stylized for having its own, separate equipment such as its own armored vests and other clothing wear, might as well make it so wearing them doesn't fuck you over.

**Comment by TiviPlus** [comment]
is this ready for review

**Comment by Max-023** [comment]
Not quite yet. Currently the officer jacket is counted as Marine armor, which means it comes with the shoulder lamp. I am currently looking at ways for this to not be so.

**Pull request closed without merging**
