### PR TITLE
Anti-Material Rifle Buff

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
Fire delay buffed to 2 from 2.5. 

## Why It's Good For The Game
Sniper too slow. 80 damage bad. Not used enough. Gun deserve love. 

## Changelog
:cl:
balance: Antimaterial rifle delay 2.5 -> 2
/:cl:

### CODE REVIEW

**Comment by Luxyboo** [comment]
cool PR unfortunately you’re probably gonna get “powercreep”

**Comment by KrabSpider** [comment]
> cool PR unfortunately you’re probably gonna get “powercreep”

Is it really powercreep if the spec weapon in question is out DPS'd by several roundstart marksman rifles?

**Comment by vilereaver41** [comment]
The winrates are terrible right now, the last thing marines need is powercreep

**Comment by KrabSpider** [comment]
> The winrates are terrible right now, the last thing marines need is powercreep

Correlation does not equal causation.

**Comment by turnop** [comment]
fuck you and fuck snipers

**Comment by SilencedMP5A5** [comment]
if this gets approved, ping me in discord and i'll make the AM sniper sprite look better

**Review by BraveMole — CHANGES_REQUESTED** [review]
not against a buff but uh, will a fire rate change do anything anyway? It's not really usefull for snipers imo

**Comment by Georgeur** [comment]
Know it sounds retarded but we need a better "Why It's Good For The Game"

**Comment by KrabSpider** [comment]
> not against a buff but uh, will a fire rate change do anything anyway? It's not really usefull for snipers imo

Are you telling me to make it hitscan and call it a day? I'll do it. I will do it. Give the word. 
Also...no other sniper has this long of a delay (ignoring aim-mode). The only thing coming close to it is the anti-tank rifle by an entire **second** (1.5) and that itself is "???" **when you consider the fucking thing does 100 damage + 50 sunder**. 

_Then again that's a PMC exclusive weapon so what the fuck am I on?_ 🙂 

Going back to my main point; 2.5 seconds is **very** long, especially when in that time you could have dealt roughly twice the damage as a regular bolt action rifle.

**Comment by KrabSpider** [comment]
New plan
Make gun available to smartgunners and remove it from req.
**Elsa please fuck off**

**Pull request closed without merging**
