### PR TITLE
Skirmish Rifle buff, 30->40 mag cap

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Skirmisher now has 40 magazine capacity.
## Why It's Good For The Game
Makes the skirmirsher a more enticing choice, it currently suffers from terrible ammo economy overall as it has significantly worse magazine capacity compared to other weapons in the same overall class (BR, StormR, AK, etc) so this should help it stand out more.
## Changelog
:cl:
balance: Skirmish Rifle has been buffed to 40 magazine capacity instead of 30.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Why does this gun even exist?
Compared to a BR it has worse damage, worse AP, worse capacity and identical sunder.
Really the only thing that splits them apart is better accuracy and (slightly) better move speed). I guess you can strap more underbarrels to it though.

The gun is so redundant its not even funny.

**Comment by Pariah919** [comment]
> Why does this gun even exist? Compared to a BR it has worse damage, worse AP, worse capacity and identical sunder. Really the only thing that splits them apart is better accuracy and (slightly) better move speed). I guess you can strap more underbarrels to it though.
> 
> The gun is so redundant its not even funny.

Almost everything has worse damage and AP compared to the battle rifle, its incredibly overtuned (the buff to the bullet and extra delay that happened way back was a huge mistake) even you know that. I don't even think its compareable considering one is full auto focused and the other one is burst fire focused? If you want to say that I might as well delete everything that isn't a BR or a lascarbine in the current stats..

**Comment by Lumipharon** [comment]
Other guns are different enough in other ways. i.e. a t12 has notably faster move speed, where as skirm is almost identical.
Auto vs burst auto isn't really a difference either. You're still holding down m1 on someone with either.

Its not even that the skirm is bad, its just redundant.

**Comment by FIXTHERADBOXPLEASE** [comment]
Don't play marine but automatic fire vs. burst fire is already a huge difference. The delay between bursts gives xenos a lot more options.

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
