### PR TITLE
makes the minimum age of marines 18

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
17 is cringe and makes little to no sense.

## Why It's Good For The Game
something something underage marine makes no sense bad

## Changelog
:cl:
tweak: minimum marine age is 18
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -57. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
My memes!

**Comment by David-Stormwell** [comment]
Based

**Comment by Tennessee116** [comment]
I mean, even if you were 17 when you joined, you probably wouldn't be doing xenomorph tours that soon.

**Review by Hughgent — APPROVED** [review]

**Pull request merged**
