### PR TITLE
webbing is bulky

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
webbing is bulky

## Why It's Good For The Game
so you can't carry 3x the ammo in a backpack

## Changelog
:cl:
balance: webbing is bulky now
/:cl:

### CODE REVIEW

**Comment by davidchan13** [comment]
RIP engi loadouts.

**Comment by SpaceLoveSs13** [comment]
Does this apply to surgical vests?

**Comment by lovegreenstuff** [comment]
You fool. 
You utter buffoon.

I am already 17 parallel universes ahead of you. Your measly PR changes nothing.

**Comment by DerrickChamberlain** [comment]
> You fool.
> You utter buffoon.
> 
> I am already 17 parallel universes ahead of you. Your measly PR changes nothing.

True

**Comment by David-Stormwell** [comment]
fine, though check if g8 pouches can hold them still, don't remember.

**Comment by Losenis** [comment]
maybe if a t18 mag wasn't as big as a gpmg drum I'd be behind this

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
