### PR TITLE
Combat Shotgun

### PR DESCRIPTION
**Pull request by zerosexualpartners**
Now can mount a bayonet knife that goes with your boots, fire delay changes.

You can quickly equip your combat shotgun with a knife bayonet, shortening your preparing time.

### CODE REVIEW

**Comment by David-Stormwell** [comment]
You know the normal Marine knife is also a bayonet which you can attach to guns already correct?
Also shortening firing delay on guns is a pretty big balance change which should be talked about on our balance channel.

**Comment by jroinc** [comment]
> You know the normal Marine knife is also a bayonet which you can attach to guns already correct?
> Also shortening firing delay on guns is a pretty big balance change which should be talked about on our balance channel.

The normal marine knife is a NEW bayonet that's not defined for this gun, he's updating it. Should probably remove the old one too.

**Comment by jroinc** [comment]
Wait, did you try to stealth-buff the shottie?

**Comment by Hughgent** [comment]
This PR does not meet the descriptive standards we set out.

Please use the template provided when opening PRs.

Second reason is that this isn't `atomized` enough.

**Comment by zerosexualpartners** [comment]
It is just that all guns can have two types of bayonets, so, why shotgun couldn't have it? My first commit, understood.

**Pull request closed without merging**
