### PR TITLE
Major Prison Station change/fix

### PR DESCRIPTION
**Pull request by Alterist**
prison
Prison Station Is now Prison Platform

### CODE REVIEW

**Comment by Ghommie** [comment]
3/10, no water-flood mechanics.

**Comment by Alterist** [comment]
it's a platform, it's sitting just very slightly above water

**Comment by Alterist** [comment]
Now it's a fix for Prison Station in general

**Comment by Borisvanmemes** [comment]
I like it but i think it'd be even better if there was some sand here and there, maybe make LZ-1 outside.

**Pull request merged**
