### PR TITLE
Duffelbag tweaks

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
- You can now open the duffelbag after a 2 second channel
- Moving while having the bag open closes it
## Why It's Good For The Game
Makes duffelbag less ass
## Changelog
:cl:
balance: You can now open worn duffelbags with a 2 second channel
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
What? At this point remove them. They're basically just a backpack upgrade at this point.

**Comment by Xander3359** [comment]
> How long does the backpack take to open?

backpack opens instantly

**Comment by Andrewhedge** [comment]
I like duffel bags. Plus, more variation of bags is just good and fancy - especially it distinguishes it from other bags makes organizing things easier on field. but uh, currently its sprite is not really distinguished - meaning marines wont know who carries this duffelbag at all. Maybe we should colour spray it?

**Comment by ButterChugger** [comment]
As is the duffel bag has the exact same storage capacity as a IMP with the only benefit is if another marine can recognize your sprite (or dwindling pool of drip), they can right click you to use you as an inventory. Whatever happened to the duffel bag having more storage space than an IMP?

**Comment by jroinc** [comment]
> > How long does the backpack take to open?
> 
> backpack opens instantly

That's incorrect; *satchels* open instantly. Backpack has a channel, either 2-3 seconds. Do you know which one it is?

**Comment by SimplySmiley123** [comment]
> 
> That's incorrect; _satchels_ open instantly. Backpack has a channel, either 2-3 seconds. Do you know which one it is?

Both open instantly.
The backpack has delay on *_taking things out_* not opening it.

**Comment by Looking4bros** [comment]
W8, i'm confused, where's "/datum/storage/backpack/duffelbag" storage capacity listed? I'm not seeing it in "code/datums/storage/subtypes/backpack.dm"

**Comment by Xander3359** [comment]
> W8, i'm confused, where's "storage_type = /datum/storage/backpack/duffelbag" storage capacity listed? I'm not seeing it in "code/datums/storage/subtypes/backpack.dm"

It's a /backpack subtype.
I just put the storage datum right after the item in the same file after QV brought up a point where splitting up files makes it harder to read.

**Comment by TiviPlus** [comment]
@Kuro020 ???

**Review by Kuro020 — APPROVED** [review]

**Pull request merged**
