### PR TITLE
(most) Shotguns can now not be fired without being wielded.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Title. Only real exceptions are the mosin and lever action guns.

## Why It's Good For The Game
To stop this dumb meme, and balance shotguns better rather than being a gun you just pull out and run at something with no slowdown.

## Changelog
:cl:
balance: Most shotguns can no longer be fired with one hand.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -20. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by David-Stormwell** [comment]
Largest shottie nerf I've seen in all my days

**Comment by namjay1170** [comment]
2 shotgun nerfs back to back, lets see if its lost relevance again

**Comment by Chaznoodles** [comment]
As a close combat weapon, this would make them near-useless when most xenos abilities focus on knocking you down in close combat.

Instead, it might be worth having the shotgun only useable if the other hand is empty, or if the gun is wielded. This stops the whole "double shotgun pointblank" people, while not mechanically restricting those who run a single shotgun and are put in positions where they don't have time to wield it.

**Comment by TiviPlus** [comment]
> As a close combat weapon, this would make them near-useless when most xenos abilities focus on knocking you down in close combat.

agree with this, many people are also complaining about it ingame

**Comment by RaidarV** [comment]
After the test merge, I now see why this would make shotguns an undesirable choice even if you are running an angled grip with it. Not even being able to shoot the shotgun with one hand, makes it just useless when you are being tackled or stunned. I personally use the shotgun for this exact reason, a backup plan if I get stunned or tackled. One-handed PB's DO sound pretty strong, but not even being able to choose the trade-off between less accurate shots with no wait or more accurate shots with wait is just restricting. By nerfing shotguns in this way you are nerfing buckshot too, since you have to get close to a Xeno for it to be effective and if you get close enough for it to be effective with this merge, Xenos will just disarm you and/or use many stun skills they have at their claws. I am not saying a marine should be able to dive into the Xeno crowd and kill them all, but even when you have other marines covering you whilst you are trying to pick up your weapon and wield it, it isn't enough. Sometimes you just need more than your friends to get out of sticky situations. ''Shotguns aren't supposed to be secondaries'' argument doesn't sound good to me either, even if you are using the shotgun as their main weapon it would only be viable if the Xeno is alone and no Xeno get into an engagement alone at the first place, unless it is a runner or a shrike, in which case; 1- No runner would run-up to a group of 4+ marines, 2- Shrike's stun ability is AOE.

**Comment by JJtheGerman** [comment]
I really do not like this change. It has made shotguns entirely pointless for me and I now have to use some shitty revolver instead.
I agree completely with what Chaz and Raidar have said.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-24). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
