### PR TITLE
Alkysine removal, expands healing methods for brain damage

### PR DESCRIPTION
**Pull request by MisterGrimm**
## About The Pull Request
This changelog is a attempt at making head fractures more valid for xenomorphs to attempt to inflict, while still giving marines ways to heal brain damage.

- Removes Alkysine from the game.
- Gives Cryox and Clonex the ability to heal brain damage.
- A pill bottle of Peri+ has been given to corpsmen, to replace the removed Alkysine. Vending machines do not have these bottles on purpose, if you want more Peri+ you'll have to grab the autoinjectors.
## Why It's Good For The Game
Fractures are a integral part of both xenomorph and marine gameplay, but in the current state not all fractures are created equal. Chest fractures cause organ damage, which requires Peri+ to heal on the field. This causes cloneloss, and forces the marine to eventually go back to the ship to get it fixed. Arm and leg fracs do not inflict organ damage, but cause debilitating debuffs to the marine that also force them to go back up. But head fracs are different. While head fractures are the most difficult to inflict due to high armor in all helmets, they also so happen to be the weakest and least debilitating fracture. Head fracs specifically cause damage to the eyes and brain, both of which have chems readily on-hand that can quickly and effortlessly heal the damage with no downside on the field. While that is understandable with the eyes for welding accidents, it cannot be so well explained for the brain.

By removing alkysine, head fractures now become more worthwhile for xenomorphs to target, equalizing the validity of targeting the head compared to other body parts.

However, marines also deserve methods of still dealing with brain damage, with the removal of alkysine. Giving the corpsmen a pill bottle of peri+ is my chosen method of doing this, as it will be inevitable that head fracs will happen more often once they are a more valid target choice. This allows the corpsmen to still heal brain damage, with the downside being cloneloss. Ontop of this, giving cryox and clonex the ability to heal brain damage will also give doctors a quick and painless method of healing the marine's brain, without the field downsides of peri+.
## Changelog
:cl:
del: Removed Alkysine
balance: Cryoxadone and Clonexadone can now heal brain damage
balance: Corpsmen now have a pill bottle of Peridaxon Plus, to replace the Alkysine pill bottle.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
```due to high armor in all helmets```
Its literally the same as heavy what are you talking about? If I remember right heads even have a lower break threshold. Why is this necessary at all beyond trying to make head fraccs more "viable" when they already are?

**Comment by MisterGrimm** [comment]
> `due to high armor in all helmets` Its literally the same as heavy what are you talking about? If I remember right heads even have a lower break threshold. Why is this necessary at all beyond trying to make head fraccs more "viable" when they already are?

To my understanding the only calculation that determines a fracture is 
`if(CONFIG_GET(flag/bones_can_break) && brute_dam > min_broken_damage && !(limb_status & LIMB_ROBOT))`
`  fracture()`

**Comment by Lumipharon** [comment]
Bro brain damage means humans can't shoot straight, can't tac reload, struggle to do anything that requires skill, including not being able to issue orders.

Being unable to see is also uh, quite bad.

Both are significantly worse than any other organ damage (after they were severely nerfed).

Also pillbottles of peri+ is ???

**Comment by Joe13413** [comment]
> `due to high armor in all helmets` Its literally the same as heavy what are you talking about? If I remember right heads even have a lower break threshold. Why is this necessary at all beyond trying to make head fraccs more "viable" when they already are?
uhhhh all helmets have as much armor as heavy armor, which means if someone is wearing light armor, then their head is more armored than their other limbs are

**Comment by Joe13413** [comment]
should mention though that reworking brain damage to be harder to fix on the field would be cool. It's debilitating, but the hardest to apply. Maybe brain fixy chem could only work while sleeping? or fix brain damage at a slow rate? idk, just spitballin here

**Comment by MisterGrimm** [comment]
> should mention though that reworking brain damage to be harder to fix on the field would be cool. It's debilitating, but the hardest to apply. Maybe brain fixy chem could only work while sleeping? or fix brain damage at a slow rate? idk, just spitballin here

Unfortunately this is unlikely to happen, due to the very niche direction the head maints want to take this codebase. Apparently something as simple as making head fractures valid is too much for them.

**Pull request closed without merging**
