### PR TITLE
Makes SADAR rockets bulky, adds rocket backpack to sadar crate.

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
See title.

## Why It's Good For The Game
Sadar's a stupidly powerful weapon, and running around with, say, minigun + sadar because of explosive pouch, or sadar + combat backpack is pretty dumb.

## Changelog
:cl:
add: Adds a rocket backpack to the sadar req kit.
balance: Sadar rockets can no longer fit in backpacks or explosive pouches
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
I think this is a balance think considering RR is round start available and sadar is an expensive req item.

**Comment by yyzsong** [comment]
RR is roundstart, yeah, but it's also considerably less powerful than the sadar.

And for the sadar: it's super expensive because it's super powerful. It's a weapon that shoots one super strong burst damage and then has to reload. Letting it combo with some other gun is kinda cringe. While it can still do this now, it's more difficult and prone to melting weapons.

**Comment by Naaanii** [comment]
Would be better to make both use rocket backpacks only for consistency.

**Comment by yyzsong** [comment]
> Would be better to make both use rocket backpacks only for consistency.

yeah maybe

**Comment by Pariah919** [comment]
Disagree.

SADAR requiring you to put your entire kit to make it work seems ehhh to me. Maybe if you make it fit inside the rocket bag like RR should I could agree with this. Since it'd mean if you want the other gun, you'd need no MAGH SADAR memes.

**Comment by Arctrooper8** [comment]
> Disagree.
> 
> SADAR requiring you to put your entire kit to make it work seems ehhh to me. Costs quite a chunk of points to make it run. Maybe if you make it fit inside the rocket bag like RR should I could agree with this. Since it'd mean if you want the other gun, you'd need no MAGH SADAR memes.

RR doesn't actually itself fit in the rocket bag but that'd be really cool to see. I mean there's even an extra slot just for it.

**Comment by yyzsong** [comment]
> Disagree.
> 
> SADAR requiring you to put your entire kit to make it work seems ehhh to me. Costs quite a chunk of points to make it run. Maybe if you make it fit inside the rocket bag like RR should I could agree with this.

SADAR *should* require you to put your entire kit into it. It's a super-powerful, 120 point weapon.  It's like the minigun, which needs back slot for an ammo pack.

Also RR cant even fit in the rocket bag. That PR was closed

> Since it'd mean if you want the other gun, you'd need no MAGH SADAR memes.

not really sure what you mean by this tbh.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Let's follow mjp advive on this, if you allow the sadar in the bag then ok. And as such you should wait for rr holster pr, so you don't have to do code

**Comment by BraveMole** [comment]
RR pr was merged btw

**Pull request closed without merging**
