### PR TITLE
PR that adds NOTHING to the game

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

For my 500th PR i will add NOTHING to the game so you should DEFENITELY JUST MERGE THIS PR trust me

## Why It's Good For The Game

its NOTHING

## Changelog
:cl:
add: Added NOTHING to the game trust me
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
blessed

**Comment by Kuro020** [comment]
Mjp told me he was gonna buff laser pistols if I closed this, so I have no choice really

**Comment by Kuro020** [comment]
Oops I missed

**Comment by SplinterGP** [comment]
sacrilege

**Pull request merged**
