### PR TITLE
Kuro Gun Resprite pt1

### PR DESCRIPTION
**Pull request by Xsdew**
## About The Pull Request

This is the first part of Marine Standard Issue Weapon Re sprite. The sprites are provided by Kuro and affect the following weapons:

AR-18
AR-12
SMG-90
P-14
SH-35
MG-42 

The changes include replacement of the applicable sprites, and the deletion of old sprites.
As apart of this PR I introduced four new DMI files to accommodate larger Mob sprites. For the MG42 specifically.
These are:

items_back_64
Items_lefthand_64
items_righthand_64
items_suit_slot_64

## Why It's Good For The Game

Kuro would like to marines looks to be more uniform. To complete this goal he is going to respite the standard issue weapons.

## Changelog
:cl:
imageadd: Re sprites for the following: AR-18, AR-12, SMG-90, P-14, SH-35, MG-42.
imagedel: Unused sprites of those weapons were removed.
code: added code to allow for the new sprites to be used, with the MG-42 getting the first big mob icon sprite.
/:cl:

### CODE REVIEW

**Comment by Kuro020** [comment]
based

**Comment by novaepee** [comment]
image
For the people that don't use icon diff

**Comment by Xsdew** [comment]
I strongly recommend we fix the icon bot for this PR. Seems to be not showing and icon diff checks.

**Comment by Alexeivichi** [comment]
I like the idea, but these designs look ergonomically confusing. Some of the sprites as a little too boxy. That's just my take on it. Hope you can get the other weapons done in time Kuro. Good luck.

**Comment by FIXTHERADBOXPLEASE** [comment]
Swear to god the shotgun looks like one of the ones from Planetside 2.

**Comment by Al-1ce** [comment]
These are a bit boxy but honestly that might be fine. Can we see the inhands sprites?

**Comment by Xsdew** [comment]
The art channel has more videos with the mob sprites on the discord

**Comment by FosterGrime-Heymynameslouie** [comment]
goodbye iconic base weapon sprites
I hope to see you again in another life

also these look great, but they ought to sound different I think? 
also wishing on a falling star that we see a system where we can play with/see the old sprites for a good old nostalgia kick

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
