### PR TITLE
Removes moths

### PR DESCRIPTION
**Pull request by DominikPanic**
AIIA approved this.

### CODE REVIEW

**Comment by Rohesie** [comment]
We are not fully removing moths. Let them be where they are, please.

**Comment by spookydonut** [comment]
Purge them

**Comment by Ketrai** [comment]
If you remove moths I will resign >:C

**Comment by Menshin** [comment]
>Removes moths

Wow, who assumed direct control over *La* ?

**Comment by DominikPanic** [comment]
> 
> 
> > Removes moths
> 
> Wow, who assumed direct control over _La_ ?

I'm a felinid person :relieved:

**Comment by Menshin** [comment]
What about the he... err manga panel over Discord ? 😁 

While not opposed to the removal, aren't they locked behind admingate though ?

**Comment by Rohesie** [comment]
These are locked behind admin panel. We are not adding nor removing species without a good reason and prior discussion.

**Pull request closed without merging**
