### PR TITLE
Revert "King is unique, but not time locked"

### PR DESCRIPTION
**Pull request by BrandonSmith6**
Reverts tgstation/TerraGov-Marine-Corps#8639

SHIT IS FUCKED Xenos get round start king that can delete cades in 1 click. This is beyond my understanding of unbalanced.

### CODE REVIEW

**Comment by MiniMeatwad** [comment]
Honestly, #8639 is a good attempt at killing turtling. Goodbye Super FOBs, and goodbye cade gameplay. Nobody will miss you.

**Comment by BrandonSmith6** [comment]
> Honestly, #8639 is a good attempt at killing turtling. Goodbye Super FOBs, and goodbye cade gameplay. Nobody will miss you.

Pov: shutters open. 
Within 10 seconds all cades are gone and FOB is breached completely.

**Comment by EvilMelonTheSecond** [comment]
I was skeptical when #8639 said that xenos had other ways to spend points so the king timer was now obsolete. How didn't anybody foresee this happening? King is THE big bad xeno, of course xeno will rush to get it.

Return King to the tiebreaker role or it will always get rushed and undermine all other psy point options.

**Comment by David-Stormwell** [comment]
problem is if you kill marine's cades too quickly you can demolish them even faster then you could say fuck xeno mains.

**Comment by BraveMole** [comment]
- King is a gamble; it can lands into the hand of a bad player and be utterly useless. Compare that to all other Psy points upgrade that are useful for the whole hive.
- Since when marines need cades of the first 10 minutes? If you are back into the fob in that short amount of time, you already lost the game, king or not.
- What is king doing exactly to stop marine pushes early on? Nightmare can be rendered useless by one flare, or even a flamer. Gravity crush does peanuts to marines, and again, you don't need cades to push early on.
- Having a king mean you have NOTHING else. No maturity boost, no ais, no towers, and NO SILO. The latter means xeno have to gather 600 points in a short amount of time or they just die. Marine can win just by not getting drained ; that's all, winning just by sitting in fob and not dying. If marines keep rushing into the unknown despite no silo, that's just a skill issue

**Comment by BrandonSmith6** [comment]
> - King is a gamble; it can lands into the hand of a bad player and be utterly useless. Compare that to all other Psy points upgrade that are useful for the whole hive.
> 
> - Since when marines need cades of the first 10 minutes? If you are back into the fob in that short amount of time, you already lost the game, king or not.
> 
> - What is king doing exactly to stop marine pushes early on? Nightmare can be rendered useless by one flare, or even a flamer. Gravity crush does peanuts to marines, and again, you don't need cades to push early on.
> 
> - Having a king mean you have NOTHING else. No maturity boost, no ais, no towers, and NO SILO. The latter means xeno have to gather 600 points in a short amount of time or they just die. Marine can win just by not getting drained ; that's all, winning just by sitting in fob and not dying. If marines keep rushing into the unknown despite no silo, that's just a skill issue

So you are saying that fob defense has no use?

**Comment by BraveMole** [comment]
> > * King is a gamble; it can lands into the hand of a bad player and be utterly useless. Compare that to all other Psy points upgrade that are useful for the whole hive.
> > * Since when marines need cades of the first 10 minutes? If you are back into the fob in that short amount of time, you already lost the game, king or not.
> > * What is king doing exactly to stop marine pushes early on? Nightmare can be rendered useless by one flare, or even a flamer. Gravity crush does peanuts to marines, and again, you don't need cades to push early on.
> > * Having a king mean you have NOTHING else. No maturity boost, no ais, no towers, and NO SILO. The latter means xeno have to gather 600 points in a short amount of time or they just die. Marine can win just by not getting drained ; that's all, winning just by sitting in fob and not dying. If marines keep rushing into the unknown despite no silo, that's just a skill issue
> 
> So you are saying that fob defense has no use?

In the first ten-twenty minutes, yes

**Comment by S1tr3p** [comment]
I promise you, king is not that good. You can kill a roundstart king with an assault rifle and shotgun solo. (I have done this, experiencing an ancient king dying so fast because it has drone slash hurts.) Yes, it can and will fuck up your fobs but those can easily be replaced if you sell the kings body and get one miner up.

I like roundstart king, it makes marines play smart for once. Please don't revert this.

**Comment by SplinterGP** [comment]
> 
> 
>     * King is a gamble; it can lands into the hand of a bad player and be utterly useless. Compare that to all other Psy points upgrade that are useful for the whole hive.
> 
>     * Since when marines need cades of the first 10 minutes? If you are back into the fob in that short amount of time, you already lost the game, king or not.
> 
>     * What is king doing exactly to stop marine pushes early on? Nightmare can be rendered useless by one flare, or even a flamer. Gravity crush does peanuts to marines, and again, you don't need cades to push early on.
> 
>     * Having a king mean you have NOTHING else. No maturity boost, no ais, no towers, and NO SILO. The latter means xeno have to gather 600 points in a short amount of time or they just die. Marine can win just by not getting drained ; that's all, winning just by sitting in fob and not dying. If marines keep rushing into the unknown despite no silo, that's just a skill issue

Why woulndt marine need cades in the 10 minutes ? why would they ever need to go outside FOB instead of defend it forever against the king ? why would they not let the xenos sneak behind and kill their medics ? why woulndt they just go out of FOB and let a xeno go around and melt their supplies, why not

**Comment by BraveMole** [comment]
Closing this, king roundstart is not a balance problem at all.

**Pull request closed without merging**
