### PR TITLE
Destructible cell windows. 

### PR DESCRIPTION
**Pull request by InterroLouis**
## About The Pull Request

Cell windows will be destructible now, but not deconstructible. 

## Why It's Good For The Game

Indestructible windows that aren't blocking off space areas are unnecessary and bad. 

## Changelog
:cl:
balance: Prison Station cell windows are now destructible and acidable but still not deconstructible. 
/:cl:

### CODE REVIEW

**Comment by KornFlaks** [comment]
You should add integrity so these cell windows get destroyed in an OB rather than sitting there.

**Comment by InterroLouis** [comment]
They have integrity. It's called inheritance. Are you saying you want them to have more integrity than they already have or less?

**Comment by KornFlaks** [comment]
> They have integrity. It's called inheritance.

If you follow the inheritance, it goes all the way back to window. Prison does have integrity. Framed doesnt have integrity, Window does and it's 30. This is a plain window frame, easily destroyable with a single poke.

**Comment by SplinterGP** [comment]
Map edit and rebalance since it affects map layout and balance

**Review by SplinterGP — CHANGES_REQUESTED** [review]
Post pictures of places affected by this please.

**Comment by InterroLouis** [comment]
It's most of the cell blocks on the prison map. 
prison

prison again

The cells have these indestructible windows. Any windows to outside are hull windows.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
