### PR TITLE
remove satchel strap from mob

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

image

## Why It's Good For The Game

image

the people demands this from me. we will see if art director wants this or not.

## Changelog

:cl:
del: remove satchel strap from mob
/:cl:

### CODE REVIEW

**Comment by ClosetedSkeletonGH** [comment]
satchel strap is vital to the look of one of my builds. Id much rather this be a toggle versus straight removal

**Comment by Blundir** [comment]
Marine with satchel glued to their groin, doesn't really look good, at least make it toggle

**Comment by KM-Catman** [comment]
LETS FUCKING GOOOOOOOOOOOOOOOOOOOO

**Comment by KM-Catman** [comment]
but yeah I do agree with Blundir, it would probably be preferred to make it toggleable rather than remove it outright

**Comment by XElectricX** [comment]
A toggle or just make a new backpack type like a clip-on bag would make far more sense. I can't believe there are people who hate the straps.

**Comment by Strayed-Raven** [comment]
HATE STRAPS! HATE STRAPS! HATE STRAPS!
But yes a toggle for it would also be good.

**Comment by chizzy376** [comment]
Why not let us switch between the two states?
LMB the backpack while it's in your active hand, "You adjust the straps on the backpack."
and boom, both parties happy

**Pull request closed without merging**
