### PR TITLE
Replaces the M44 entirely with a new sprite

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Replaces the M44 to look like an actual SAA rather than whatever the heck it was before hand.

## Why It's Good For The Game
cool new sprites for cool people

## Changelog
:cl:
add: Added new M-44 sprite to the game
del:Old m-44 sprite has been deleted git will remember it, nobody else will
balance:m-44 now only holds 6 shots instead of 7
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -51. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
image

**Comment by AtlasRules** [comment]
SPEEDMERGE THAT SHIT

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Give me one good reason not to close this on basis of it being a bloat gun

**Comment by Chaznoodles** [comment]
Remove another gun if you want to implement this imo, we already have too many

**Comment by Pariah919** [comment]
i'll delete the m44 for this sure

**Comment by Pariah919** [comment]
ok this is basically done now I think

**Comment by XSlayer300** [comment]
>Single Action
>Fires in double action.

Wait, that is illegal!

**Comment by SilencedMP5A5** [comment]
based based based based

**Review by TiviPlus — APPROVED** [review]

**Review by Hughgent — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-49). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
