### PR TITLE
Distress burrowed larva and psypoints generation rework

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Lot of changes:

Marines spawning no longer give psypoints
Xeno are given 1000 free psy points at the beginning of the game

Xeno generation is now LINEAR with the amount of alive marine players
Xeno generation now follows a f(x) = (a+x)/a * (a)/(a+1) law, with a being a static number (here 2.5) and x the number of silos

Here is how it compares, with the x axis being the number of silos and the y axis something proportional to the burrowed output: 
image

Remove small silos from the game, no longer needed

Psy drain gives 60 points rather than 40
Cocoon give 120 points and 1.5 larva point, so it's really better than psy drain now if you protect the body
Generators produces a bit more psy points (nothing dramatic), but it is now function of the number of alive marines on the ground

Turrets are now 100 points, silo are now 800, king is now 1800. This is to account for xeno having way less psy points in general (marine spawning no longer give 80 points)

Revert the change i did to the number of larva points per marine spawning. There is far less xeno respawn, so they need the same numbers as in hunt. 

Move the number of required larva points for a larva out of config, because they were fucking wrong there (8 instead of 7 for hunt, 9 instead of 7(!!!!) in crash). 

## Why It's Good For The Game

This will make the xeno generation ramps up much more smoother, which should in theory prevent the whole "the game is decided in the first 15 minutes of the game" issue, as well with the "infinite xeno go BRRR".

This also makes the diminishing return on silo less of an issue, since the second silo is no longer doubling the burrowed larva output

## Changelog
:cl:
balance: Rework silo generation
del: remove small silos
balance: psy drain gives 60 points and 1/8th of a larva, cocoon give 120 points and at the end of its lifetime (5minutes), 1/6th of a larva. Generators are making more psy points, but it's linked with the number of alive alive marines ground side
balance: Turrets are now 100 points, silo are now 800, king is now 1800. This is to account for xeno having way less psy points in general (marine spawning no longer give 80 points)
/:cl:

### CODE REVIEW

**Comment by lovegreenstuff** [comment]
hey, real fast, braveman

why does psydrain give larva points but cocoon doesn't?

**Comment by ilikesaying** [comment]
> hey, real fast, braveman
> 
> why does psydrain give larva points but cocoon doesn't?

psydrain is a instant cash-in
cocoon is a long-term investment

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
This is apparently too much of a nerf

**Comment by BraveMole** [comment]
> This is apparently too much of a nerf

Yes, but with the Psy drain plus cocoon buff, this might be fair

**Pull request merged**
