### PR TITLE
Brings back xeno nibbling having an attack animation

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request
yea
## Why It's Good For The Game
I think its funny
## Changelog
:cl:
fix: Friendly xeno nibbles have the attack animation again
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
this was soul
bring back the soul

**Comment by Mannybrado** [comment]
SOUL!!!!!!!!!!

**Comment by DrAmazing343** [comment]
sovl . . .

**Comment by Mantlecrawler** [comment]
sovel...

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
