### PR TITLE
Replacing shotgun ammo and box sprites

### PR DESCRIPTION
**Pull request by Arachnidnexus**
Chipping away at the "convert to CC BY-SA sprites" task.

Replacement:
image

Current In-Game:
image

Earlier Versions:
image
image
image
image
image

### CODE REVIEW

**Comment by Alterist** [comment]
The contrast is a bit high in my opinion, looks almost like its candy coated

**Comment by Arachnidnexus** [comment]
@Alterist more like the very bottom ones but darker in terms of contrast then?

**Comment by Alterist** [comment]
seems good to merge

**Comment by Ghommie** [comment]
It's eye candy satisfying. 👌

**Pull request merged**
