### PR TITLE
New thunderdome

### PR DESCRIPTION
**Pull request by sunofang**
## Why It's Good For The Game
I feel that it's very important to have a pretty looking testing environment, Since the Thunderdome is used by admins to test things for often long periods of time, Therefore it is good to have a pretty environment. The Thunderdome has also been redesigned to make it more suited for combat/testing.

## Changelog
:cl:
add: Added a new, Prettier Thunderdome
add: Added two new podlock types. for the Thunderdome
del: Removed the old Thunderdome
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
use mapmerge

**Comment by sunofang** [comment]
I'm getting a lot of errors trying to use the map merge. Could someone do it for me?

**Comment by Rohesie** [comment]
Ask for help in the mapping channel.

**Comment by sunofang** [comment]
I lost the files due to my own incompetence. Will be closing this PR.

**Comment by spookydonut** [comment]
> 
> 
> I lost the files due to my own incompetence. Will be closing this PR.

the files are still on github

**Pull request closed without merging**
