### PR TITLE
Resprites the health analyzer, no more CM sprites

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About The Pull Request
resprites the health analyzer, plant analyzer untouched
image
image
image

## Why It's Good For The Game

no more CM sprites

## Changelog
:cl: JoeHammad
imageadd: The TGMC has redesigned the HF2 health analyzer to be more usable by children raised on mummy's ipad
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
CM health analyzer has soul

**Comment by JoeHammad1844** [comment]
> CM health analyzer has soul

here's some soul for you then
image

**Comment by FosterGrime-Heymynameslouie** [comment]
I think respirting it into a stehtescope and a hammer woud be a lot more  funeyr

**Comment by JoeHammad1844** [comment]
> I think respirting it into a stehtescope and a hammer woud be a lot more funeyr

now THAT is epic

**Comment by JoeHammad1844** [comment]
what about this?
image

**Comment by Helg2** [comment]
Some darker pixels in the corners would be nice, so its ain't so plain.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
needs a bit more details in the shading, as it is rn its very plain

**Comment by Loafin34** [comment]
if you want to take out CM sprites, you should change RO's revolver belt. the holstered sprite still uses CM revolver.

**Comment by JoeHammad1844** [comment]
> if you want to take out CM sprites, you should change RO's revolver belt. the holstered sprite still uses CM revolver.

off topic

**Comment by JoeHammad1844** [comment]
> needs a bit more details in the shading, as it is rn its very plain

is this any better?
image

**Comment by lbnesquik** [comment]
Honestly, this looks plain worse. It's not like we have the ORIGINAL health scanner either. New sprites aren't always better than CM ones, and I think this is one case for it.

**Comment by efzapa** [comment]
random suggestion but does this look better? 
just yoink the sprite from para tbh

**Comment by Kuro020** [comment]
I liked the paradise sprite better

**Pull request closed without merging**
