### PR TITLE
fixed acid spray dealing double damage to all objects

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

If an obj has already been hit by acid spray once in a tile check, it will not be hit again by the atom/moveable acid spray check below.

## Why It's Good For The Game

This bug has made praetorian acid spray 2x as effective on all defensive structures and objs that are also moveable, which is unintended. 

## Changelog

:cl:
fix: prae acid spray no longer deals double damage to all objects that are also atom/moveables
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
>carrier acid spray

did they chainsmoke lucky strikes and evolve or something

**Comment by MacBlaze1** [comment]
> > carrier acid spray
> 
> did they chainsmoke lucky strikes and evolve or something

oops, typo

**Comment by TiviPlus** [comment]
The fix with the list will be rather unperformant for what it is i dont like it

**Comment by MacBlaze1** [comment]
uhhh this is intended apparently

**Comment by MacBlaze1** [comment]
and we're back

**Comment by Lumipharon** [comment]
To clarify here in the pr: This is old funny CM code. Doing extra damage to razor is intended, but should be correctly handled by just editing the acid act proc for it.
multitile vehicles don't exist so we don't care about them.
Cades are the only other than that can get hit twice, and this ONLY happens if you spray them sideways (as if you spray them front on, it blocks the acid and the second hit doesn't occur).

**Pull request merged**
