### PR TITLE
burst fire tweaks

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

tunes some weapons burstfire, adds a bit of scatter

изображение

## Why It's Good For The Game

tweaks for meta guns 

## Changelog
:cl:
balance: tweaks to burst weapons burstfire
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
Lmao he added the BR65 and mod88 to the nerf

**Comment by Xsdew** [comment]
Why are you nerfing the BR64? It doesn't get used to burst down Xenos in 2 seconds.

**Comment by Waselon** [comment]
> Why are you nerfing the BR64? It doesn't get used to burst down Xenos in 2 seconds.

Where am i nerfing it?

**Comment by Strayed-Raven** [comment]
None of this takes into consideration ammo differences or gun identity. We already have the Sunder PR. It should run its course before this is considered necessary.

**Comment by FIXTHERADBOXPLEASE** [comment]
Guys... you realize the BR64 damage remains exactly the same between old and new?
It's there for comparison purposes.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
