### PR TITLE
Updated SADAR sprites

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Thanks to @SilencedMP5A5 for the new SADAR.

image

Rockets midflight now have actual unique sprites, so you can see what kind of rocket is about to hit you in 0.1 seconds. I've also applied this to the SOM RPG.
image

Plus some misc clean up of sprites and code.
## Why It's Good For The Game
Betterer art
## Changelog
:cl:
qol: SADAR and RPG rounds now have ammo specific projectile sprites
imageadd: Updated SADAR sprites
/:cl:

### CODE REVIEW

**Comment by iforgotmeword** [comment]
Looks great but feels a bit same as the SOM one

**Comment by XElectricX** [comment]
Yeah this looks more like a modernized RPG. Looks cool but for SADAR? Eh.

**Comment by Al-1ce** [comment]
I feel like making this the RR and the current RR sprite would be better.

**Comment by Al-1ce** [comment]
I think making this the sprite for the RR would be better, while using the old RR sprite for the SADAR.

**Comment by Lumipharon** [comment]
Local man surprised that rocket in tube looks like every other rocket in tube.

**Comment by SilencedMP5A5** [comment]
pzf44

it is basically a german RPG-7, so

yea of course its gonna be similar looking

its fine imo (spriter talk for i'm too lazy to do another german rocket launcher instead)

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
