### PR TITLE
Hivelord healing infusion nerf

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
This is just chazs pr without the windup change, which I personally disagree with but I can get that too if people want it.

## Why It's Good For The Game
Healing infusion is way too good in its current state, 25 base hp is pretty okay considering it stacks with recov

## Changelog
:cl:
balance: healing infusion heals a flat 25 hp instead of 10+5% and heals less sunder
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -189. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by BraveMole** [comment]
What's bothered me the most was the 30 seconds cooldown, with that change hivelord can heal on average 4 hp/s, while drone can go to 8hp/s. Maybe leave the 5 sec cooldown, but up the plasma cost of infusion?

**Review by TiviPlus — APPROVED** [review]

**Comment by Surrealaser** [comment]
This is an utterly terrible and atrocious change.

30 second cooldown? This is a fucking joke.

**Comment by Surrealaser** [comment]
[1:05 AM] Surrealistik (Kai-Jew): I'll break down the math again, just so we're clear what is actually at play when we're talking about the healing infusion
[1:05 AM] Surrealistik (Kai-Jew): as it currently exists
[1:06 AM] Surrealistik (Kai-Jew): 10 HP + 5% of max per tick, for 5 ticks as well as 3 Sunder per tick for 5 ticks; each rank of Recovery improves each of these by 5%
[1:06 AM] Surrealistik (Kai-Jew): using 300 HP as a reference
[1:07 AM] Surrealistik (Kai-Jew): that means we regain 25 HP and 3 Sunder per tick, 125 HP and 15 sunder over 10 seconds, or 12.5 HP and 1.5 Sunder per second
[1:08 AM] Surrealistik (Kai-Jew): if you factor in max pheros from an ancient empress, that goes to 15.625 HP and 1.875 Sunder / second
[1:09 AM] Surrealistik (Kai-Jew): Drone normally has a heal rate of 6.66 HP / sec and 0.4 Sunder / sec (including cooldown and wind up); this can go as high as 13.2 HP / sec if the target has both Burn and Brute damage
[1:10 AM] Surrealistik (Kai-Jew): before Recovery
[1:11 AM] Surrealistik (Kai-Jew): but it has the added advantage of not needing weeds, and not being stopped by fire
[1:11 AM] Surrealistik (Kai-Jew): and being a spike heal
[1:11 AM] Surrealistik (Kai-Jew): so more useful tactically and under pressure
[1:14 AM] Surrealistik (Kai-Jew): if you factor in the cooldown, as I did for the Acidic Salve, the healing per second for Healing Infusion goes down to a base of 8.33 HP / sec and 1 Sunder / sec
[1:14 AM] Surrealistik (Kai-Jew): now, with this insane, ridiculous nerf
[1:14 AM] Surrealistik (Kai-Jew): the baseline is this
[1:15 AM] Surrealistik (Kai-Jew): 3.125 HP / sec and 0.0375 Sunder / sec
[1:15 AM] Surrealistik (Kai-Jew): including the 30 second cooldown and the 10 second heal over time
[1:17 AM] Surrealistik (Kai-Jew): so not only is it worse than a Drone's heal over time (even assuming no burn damage to double dip), while costing more plasma, it also A: applies heal over time instead of as a spike which is much less valuable and B: is subject to weed restrictions and can be suppressed by fire
[1:17 AM] Surrealistik (Kai-Jew): this nerf is mathematically ludicrous

**Comment by TiviPlus** [comment]
As it is it is too high and I agree from when I played, you can open a PR to make it "Ok" if you feel that way

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
I'd take 20 - 15 seconds for sure for the record

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-212). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
