### PR TITLE
Adds the V-21 (Kriss) to req imports

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
title
## Why It's Good For The Game
KRISS MY BELOVED
## Changelog
:cl:
add: Adds the V-21 (Kriss) to req imports tab
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
how the fuck are checks failing. What.

**Comment by Jackal-boop** [comment]
Why is it so cheap

**Comment by XSlayer300** [comment]
> Why is it so cheap

i mean, you can say the same with the garand and all

and besides, we already have the smg-50/t-50 btw.

**Comment by Al-1ce** [comment]
> Why is it so cheap

Because nobody would buy guns from req otherwise.

**Comment by TiviPlus** [comment]
We do not mix HvH and XvH weapons

**Pull request closed without merging**
