### PR TITLE
New sprites for brute kit, burn kit, and surgery membrane

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

image

image

Kuro approves. Merge in 24 hours.

metal gear aesthetics

image

## Why It's Good For The Game

Crow dislikes current sprites, so he replaces it with better sprites. Easier to click, looks better.

## Changelog
:cl: nova_epee and crow
imageadd: new sprites for brute kit, burn kit, and surgery membrane
del: useless sprites that never been used for brute and burn kit
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
everything but the kit sprites look good

**Comment by mc-oofert** [comment]
i dunno it seems too big for what is essentially a tiny box of sci-fi bandages

**Comment by Losenis** [comment]
>i dunno it seems too big for what is essentially a tiny box of sci-fi bandages to fit in a lifesaver/other belt

Don't make me get the comically large tweezers

**Review by TiviPlus — APPROVED** [review]

**Comment by Weedmaster77** [comment]
At first glance I didn't like them but the more I look its seems fine kinda wish the new kits where a bit brighter in color and not so whiteish. Brighter make the edges easier to see IMO

**Comment by Al-1ce** [comment]
If you were to make them _marginally_ smaller I think this would be fine. Roughly the same size as the pill bottles would be a good idea.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Make them smaller so they fit in more with what they're supposed to be

**Pull request merged**
