### PR TITLE
adjust ui location

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
centers the ui
image
## Why It's Good For The Game
adjust the ui to be properly centered for widescreen
## Changelog
:cl:
qol: center the ui
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Maybe unpopular opinion, but I kinda prefer it towards the side.
In your screen shot, directly south is clogged with the hand slots and swap button.
Trying to shoot something south of you but swapping hands instead is guh.

At the moment I can shoot past the pocket slots, but the hands are a solid block I can't click on.

UI in general is pretty scuff though.

**Comment by tyeagg** [comment]
> Maybe unpopular opinion, but I kinda prefer it towards the side. In your screen shot, directly south is clogged with the hand slots and swap button. Trying to shoot something south of you but swapping hands instead is guh.
> 
> At the moment I can shoot past the pocket slots, but the hands are a solid block I can't click on. image
> 
> UI in general is pretty scuff though.

it goes both ways

**Comment by TiviPlus** [comment]
You still wanna merge this or incoroprate into the larger rework you're doing? @tyeagg

**Comment by tyeagg** [comment]
> You still wanna merge this or incoroprate into the larger rework you're doing? @tyeagg

just merge it the rework will come later

**Comment by TiviPlus** [comment]
Talked about it with lumi would you be Ok with putting this with your larger rework when you get to it?
It might not be a good idea to drop feed UIU changes and to instead just dump it all on players so they only need to adapt once

**Pull request closed without merging**
