### PR TITLE
Cowboy Boots + Leather Jackets

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request
Adds two new armors.
The Leather Jacket with Webbing and the plain Leather Jacket
The Leather Jacket with Webbing is a marine harness in all but looks.
The plain Leather Jacket is just that, a jacket. It does look cooler however.

Also adds combat boot alts, Western boots equipped with spurs.

All three are available in the surplus clothing vendors.
Sprites by Ocelot

## Why It's Good For The Game
image
Some good lookin cosmetics

## Changelog
:cl:
add: Cowboy boots + Leather Jacket and Leather Jacket with webbing.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Need a badmin version that can hold all the guns, matrix style.
image

**Review by Kuro020 — APPROVED** [review]
tgmc's destiny is corp mercs it seems, so be it

**Comment by Licherr** [comment]
I can hear the revolvers spinning

**Review by BraveMole — APPROVED** [review]
@Kuro020 Just merge, don't approve when it's 100% cosmetic like this

**Pull request merged**
