### PR TITLE
Adding multiple balance features in Gelida IV: Xenomorph Edition

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Alternative to https://github.com/tgstation/TerraGov-Marine-Corps/pull/14016 .

This dead end dies: 
image

Both landing zones have tunnels to increase breach head for xenomorphs. Marines will hate me after this PR!
image

Add two bypasses in Gelida's cave
image

## Why It's Good For The Game

I ask Grayson and Barnet the issue with Gelida. They told me that preweed and dead end were the two issues to fix, so I fixed them. I then realize that this PR can address further issues with Gelida. Marines will hate me after this PR!

## Changelog

:cl:
add: Annihilate dead end near Gelida LZ2
add: two bypasses in Gelida's cave to allow xenomorphs to move around better, but this also goes for marines as well!
add: Put resin walls in Gelida's caves
add: More weed in Gelida
add: cave enterances in both Gelida's LZ
balance: easier for xenomorphs to play in Gelida with more weed, walls, caves, and features
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Looks like you didn't adjust the area.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
You forgot to replace the area here
gel1

**Comment by Victor239** [comment]
Is the lack of preweed fixed? 
image

**Comment by novaepee** [comment]
> Is the lack of preweed fixed? image

yes

**Review by RipGrayson — CHANGES_REQUESTED** [review]
These AI nodes need fixed.
gel2
Also the interior of this cave section needs its own area, not the area used for cave walls.

**Comment by Victor239** [comment]
> > Is the lack of preweed fixed?
> yes

@novaepee the areas I marked in the previous comment still have huge empty spots

**Pull request closed without merging**
