### PR TITLE
TGS Theseus

### PR DESCRIPTION
**Pull request by Alterist**
cleaned up the instances
pipenet improvement
wiring improvement
simplifies research floor turfs
simplifies almayer turfs
simplifies windoors
adjustments to medbay, research and marine prep
changes to tank garage location/layout
adds pilot office

### CODE REVIEW

**Comment by ninjanomnom** [comment]
TGS is the acronym for our server utility

**Comment by Alterist** [comment]
that's totally intended

**Comment by ninjanomnom** [comment]
Just checking. Rename the files as well

**Comment by Alterist** [comment]
untitled-1

**Pull request merged**
