### PR TITLE
Gives pilots modern jumpsuit/flak/helmet sprites by j*ff

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Replaces the old pilot sprites with new ones, PO has 2 different helmet types (in their closets. One green one blue.)
Flak sprites replaced.
image

## Why It's Good For The Game
PO no longer looks like a knob.

## Changelog
:cl:
MJP, Jeff
add: Added new pilot sprites, new jumpsuit/2 helmets and a new flak sprite
del: Removed old pilot sprites, git will remember them, nobody else will.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -55. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Chaznoodles** [comment]
This looks

Dull

**Comment by Jeff-jefferson-jeffery** [comment]
MJP you genuine idiot you used the wrong image you subhuman jesus CHRIST

**Comment by Pariah919** [comment]
oof i'lls wap the helmet

**Review by TiviPlus — APPROVED** [review]
Nice one MJP very smooth

**Review by TheBimmer231 — APPROVED** [review]
already reviewed and helped with, approved

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-60). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
