### PR TITLE
cool explosions

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
cool explosions and explosions have lights now
static light so probably won't be laggy
fire support railgun has cool blue explosion scifi light

https://user-images.githubusercontent.com/98577688/195997954-3d0c21cb-9c73-4eed-aa0c-a089e3f2ea48.mp4

https://user-images.githubusercontent.com/98577688/195998078-9d7c8ccf-1d76-4e36-8b19-dd4d058db321.mp4

## Why It's Good For The Game
cool explosions

## Changelog
:cl:
add: light to explosions
imageadd:  new explosion sprites
/:cl:

### CODE REVIEW

**Comment by Kuro020** [comment]
show railgun explosion nerd

**Review by Kuro020 — APPROVED** [review]

**Comment by XSlayer300** [comment]
Reminds me of goonstation (nerd)

**Comment by DerpiestBruh** [comment]
literally unmergable fix it NOW

**Review by TiviPlus — APPROVED** [review]
Can you respond to ccomments about off center lights pls

**Comment by tyeagg** [comment]
some weird stuff with pixel offset that i need to find a way to fix since its either offcenter explosions or offcenter lights

**Pull request merged**
