### PR TITLE
Attempts to balance crash larba points

### PR DESCRIPTION
**Pull request by Ldip999**
## About The Pull Request

Increases required larva points to  12

## Why It's Good For The Game

This game is unbalanced as is heavily in favour of xenos, but crash is in an even more tragic state with marine winrates in the single digits, largely thanks to xenos lacking an economy and having free respawns. This increases the amount of larva points required for xenos, although it probably won't be enough and should be raised even higher, but let's see how this works out.

## Changelog

:cl:
balance: Crash now requires 12 larva points
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
This doesn't fix anything, the issue with crash is lowpop not the (higher pop relevant) scaling

**Comment by Ldip999** [comment]
Then what do you recommend?

**Comment by TiviPlus** [comment]
Thats the million dollar question, 5-10 marines is always a marine loss, and 50+ is always a marine win, but we never see that because people wanna play nuke

My fix imo would just be make a lowpop pve mode but yea effort

**Comment by Ldip999** [comment]
Lowpop pve would go so hard

**Pull request closed without merging**
