### PR TITLE
GPMG/MMG Buff

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Buffs GPMG Bullet to 27.5/10/.75  from 25/10/.5

GPMG aim mode stats changed .35 aimed fire speed and 7.2 total move delay (lol) to .3 aim fire speed and 6 total move delay.

Buffs MMG under attachies to include flashlight underrail so LS isn't a free acc buff, MMG now has .5 damage falloff like other rifle type guns.

PASS 1 
GPMG falloff change reverted. 
MMG now has rifle damage falloff to .5 rather than 1 per tile.
PASS 2
MMG/GPMG no longer have VGRIP.
PASS 3
Acc mult reduced from 1 to .85
Accuracy penalty on the move increased by x1.2 (rounded up to closest .25) from 6 to 7.25
Aim speed nerfed from 6 to 6.5
## Why It's Good For The Game
Makes GPMG less of a meme choice, considering I swore it had 1 sunder before, appreantly it had the same sunder as rifles so it currently kind of sucks. You can pick an SMG to have better overall gun handling with basically the same overall damage to anything that isn't a T3.
MMG stuff it to increase variety on the gun, I mean even with supp and vgrip you'd still have 15 sunder standing..
## Changelog
:cl:
balance: GPMG has been buffed. It now deals 27.5 damage and .75 sunder on its bullet, from 20 damage and .75 sunder. Its total damage profile is now 27.5 damage, 10 penetration (Unchanged) and .75 sunder.
balance: MMG now can attach underbarrel flashlight, and has halved damage falloff to .5 falloff per tile rather than 1.
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
> GPMG has VGRIP now as an avaliable attachment.

Thank you, thank you and thank you

**Comment by Lumipharon** [comment]
tbh I would just remove the under attachments for mmg entirely, since as you say it's just a free acc buff, and model wise it already has a bipod. Vgrip is wierd because you're making it better wielded, when its not really meant to be.

vgrip on t60 similarly is encouraging mobile play (it reduces wield movespeed AND the aimmode move speed penalty), when I would argue that's supposed to be the t42's niche

**Comment by Tupinambis** [comment]
MMG buff is fine and I'm okay with more attachment options but I think the damage buff is a bit excessive (and I thought it was 20 damage not 25 to begin with?)

**Comment by Waselon** [comment]
> Buffs GPMG Bullet to 27.5/10/.75 per tile from 25/10/.5

Guh?

изображение

**Comment by helper-2** [comment]
GPMG
MMG
What are those words even mean?

**Comment by Lumipharon** [comment]
> GPMG MMG What are those words even mean?

Gamer Pro MachineGun
Mega MachineGun

**Comment by FosterGrime-Heymynameslouie** [comment]
t60 finally touched after 1 quadrillion years bless yo

**Comment by sluttykitty** [comment]
mjp you`re GOD pls delete xeno from the game. My dream is for the Marines' weapons to become so strong that no one else would play on Xeno, then remove Xeno and play only patrol. And i think you can do it. MJP PLS DO IT PLS PLS PLS PLS

**Comment by Losenis** [comment]
GPMG would be balanced with vgrip because it already has absolutely nuts wield time which vgrip would make even worse, so even though it'd be more mobile it'd get fucked up just as hard if not harder by anything that causes knockdown, be it xenos or backlining shotgunners. It'd only be able to hit shit if the xeno is literally in front of you, but that's already true of even hipfired T27 of all things. Not to mention that having vgrip means you don't have bipod for the funny -50% aim mode firerate debuff which turns into -100% with RDS, so unless the GPMG is frontlining hard it's going to be worse off as support weapon.

**Comment by Lumipharon** [comment]
Nothing bad can come of this.

**Comment by maikilangiolo** [comment]
> MMG/GPMG no longer have VGRIP.

I will mail you a pipe bomb

**Comment by Lumipharon** [comment]
Its a big too strong right now IMO. Not a fan of the improvements to aim speed and fire rate, as that encourages its mobile use, which should be heavily discouraged considering it has fat dps now.

**Comment by Tupinambis** [comment]
Nerf the damage to 25 per shot, keep the aim mode fire rate buff. Remove the aim speed buff. Atm it is kinda squeezing its way into the MG42 and MMG roles too much. 

MMG Buffs are fine.

**Comment by Zoldorf** [comment]
The issue really comes in with all of the damage, now let me do all the math here so it's all very clear

Pre-patch DPS at pointblank: 133~
Pre-patch DPS at 10 tiles: 116~
Pre-patch DPS at pointblank aimed: 40
Pre-patch DPS at 10 tiles aimed: 35

Post-patch DPS at pointblank: 183~
Post-patch DPS at 10 tiles: 150~
Post-patch DPS at pointblank aimed: 61~
post-patch DPS at 10 tiles aimed: 50~

as you can see, the damage output of the GPMG with this update outdoes the old GPMG by such a margain, that even 10 tiles away, the new GPMG does more DPS than the old one does at point blank, a much better solution to making the weapon a viable, less meme pick would be as follows:

Reduce damage increase from 7.5 to 2
Reduce damage falloff from 0.5 to 0.3
Keep sunder as is
reduce aim rof further from 0.3 to 0.2
Revert all other stats to previous pre-patch stats

This all in all ends up with these stats

Suggested-patch DPS at pointblank: 146~
Suggested-patch DPS at 10 tiles: 126~
Suggested-patch DPS at pointblank aimed: 63~
Suggested-patch DPS at 10 tiles aimed: 54~

This would overall make the weapon a more long-range support oriented weapon, fulfilling the niche it was always meant to do without stepping all over the MMG or the smartgun as they all do have their own role, with the added bonus that the GPMG is not gonna be a complete meme weapon anymore, and also not horribly overpowered, good enough to use, not enough to abuse.

**Pull request merged**
