### PR TITLE
Fixes regress/evolve for xenos that use plasma_regen_limit

### LINKED ISSUE #7637: Hivelord cannot evolve because it lacks plasma
### Description

Cannot evolve as an hivelord because you need your battery full 

### Test Merges

@SplinterGP 

### Reproduction Steps

@SplinterGP 

### Screenshots

_No response_

### LINKED ISSUE #7638: Cannot regress as a Ravager because no plasma
### Description

Ravager need full plasma to regress, yet has rage

### Test Merges

@SplinterGP 

### Reproduction Steps

@SplinterGP 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
Fixes #7637 
Fixes #7638 

## Changelog
:cl:
fix: fixed evolving/regressing not working with xenos with different plasma mechanics, now they account for their plasma regen limit.
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
Did you test this

**Comment by SplinterGP** [comment]
> 
> 
> Did you test this

no

**Comment by TiviPlus** [comment]
test it lol

**Comment by SplinterGP** [comment]
Works (y)

**Pull request merged**
