### PR TITLE
Medbay Autodoc Balance & Medbay Visual Edition

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Add one more autodoc to all shipside maps.

Make it easier to get to APC when autodocs drain all of medbay.

Spawn one high cap cell in research lab in all shipside maps.

Put cryo decals in all shipside medbay for STYLE.

Change researcher's landmark sprite to make it easier for mappers to see where researchers will spawn.

POS
image

Sulaco
image

Minerva
image

Theseus
image

## Why It's Good For The Game

Adding an autodoc in all shipside maps makes it easier to process patients and being lazy at the cost of shorting power in the entire medbay, rendering MEDEVAC, body scanners, and vendors in medbay USELESS.

This is fine because if you use autodoc too much, then you should be aware of APC, and since players don't know how to use APC, it's time to refresh your SS13 skills on how to maintain an APC.

For researcher's landmark sprite, just QOL for mappers.

## Changelog
:cl:
add: one more autodoc to all shipside maps
qol: Make it easier to get to APC when autodocs drain all of medbay
qol: Change researcher's landmark sprite to make it easier for mappers to see where researchers will spawn.
qol: Spawn one high cap cell in research lab in all shipside maps.
balance: more autodoc means one can process patients faster at the risk of shorting medbay
fix: fixed a few things
add: cryo decals in all shipside medbay for STYLE
/:cl:

### CODE REVIEW

**Review by RipGrayson — APPROVED** [review]

**Comment by Naaanii** [comment]
The additional autodoc seems unnecessary.

**Comment by Al-1ce** [comment]
>Adding an autodoc in all shipside maps makes it easier to process patients and being lazy at the cost of shorting power in the entire medbay, rendering MEDEVAC, body scanners, and vendors in medbay USELESS.

This takes less than five minutes to completely solve if you'd actually bother going to engineering. CMO has the ability to set up power but never does.

The additional autodoc isn't a good thing. One already consumes enough power, another will very quickly drain the medbay APC.

As for the cryo-sprite change, there isn't a good reason either. The clone generator and the cryocells are intended to be distinct from eachother visually.

**Comment by BraveMole** [comment]
Seems completly unnecessary. The only point of autodoc is to be there in low pop when there is no meddoc. Adding another one doesn't do anything, and they should not replace meddoc

**Comment by Naaanii** [comment]
Removing skill check for operating autodoc and replacing cells for the gens might be a nice buff/qol, at least for low pop purposes.

**Pull request closed without merging**
