### PR TITLE
Icy cave's Expansion

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

Adds a lot of new things to icy caves from buildings to LZ changes.

## Why It's Good For The Game

Icy caves needed a change, I think marines are struggling to hold LZ2 most of the time so I made it better to defend while adding changes to LZ1 and north of LZ1.

## Changelog
:cl:
add: New building North caves Above LZ1.
balance: LZ1 Changed
balance: LZ2 Changed
balance: Miner Under Engi, Moved.
balance: North LZ1 & West LZ2 changed
/:cl:

**Images**

image

image

image

image

image

### CODE REVIEW

**Comment by TiviPlus** [comment]
Fix your PR body to use the template please

**Comment by vilereaver41** [comment]
> Fix your PR body to use the template please

Done

**Comment by Ragecrabbo** [comment]
Good changes to the map, Icy Caves really could use more stuff in the caves themselves and the LZ changes are neat too. Only complaint i have is that LZ2 might have too many holes for xenos to flank from but thats something that will have to be seen.

**Comment by TiviPlus** [comment]
remove req weapons

**Comment by vilereaver41** [comment]
> remove req weapons

done

**Pull request closed without merging**
