### PR TITLE
Removed aim mode slowdown from T12 and T18

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request
After smartgun removal was tested, it appears that marines need more IFF stuff to push and T12/T18 seem like their niche is mobility, so I removed their slowdown from aim mode.

## Why It's Good For The Game
It should help marines that choose to push by making them more mobile without increasing their damage upfront or reintroducing smartgunner, which is a luck-based limited role.

## Changelog
:cl:
balance: removed T12 and T18 aim mode slowdown
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Makes sense

**Comment by Swagile** [comment]
i want to see a round where everyone takes T12, puts on aimmode, and just walks in a huge blob, shooting any xeno that dares pops in their view

it will be hilarious

**Comment by SkeletalElite** [comment]
Buff gyro to -100% aim mode slowdown instead

**Comment by BraveMole** [comment]
> Buff gyro to -100% aim mode slowdown instead

This is good

**Comment by Walarks** [comment]
> Buff gyro to -100% aim mode slowdown instead

No slowdown aim mode sniper coming through

**Comment by BraveMole** [comment]
> > Buff gyro to -100% aim mode slowdown instead
> 
> No slowdown aim mode sniper coming through

Slowdown is not an issue with snipers

**Comment by TiviPlus** [comment]
Right so T12 doesnt need this buff, its doing fine
T18 is less so, but I believe the main complaint is ammo for it is a pain, so I think addressing that is what is already done in MJPs pr
The mobility niche is also T90 territory, so if you're looking at improving mobility i'd take a look as to why that gun isnt seeing so much use and addressing that

**Pull request closed without merging**
