### PR TITLE
pepperball gun now staggers

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
pepperball gun came back from the gym and now staggers on hit
underbarrel pepperball does not stagger
## Why It's Good For The Game
Gives pepperball gun a bigger niche of ability denying gun that also drains plasma.
## Changelog
:cl:
balance: Pepperball gun now staggers enemies.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
would pepper draining xeno reserveres of rav and gorger also be considered? 
I think they were made immune to gas because it was easy to spam but with the pepper ball you actually need to aim 

also cool pr pepper baller cabal (2 guys and a potted plant) supports
spedde mergh

**Comment by Losenis** [comment]
Oh christ permastagger and plasmadrain

**Comment by halitosisman** [comment]
Xeno gameplay is extremely reliant on their ability usage, as marines have the overwhelming health and DPS edge these days. Any sort of consistent ability denial is a terrible idea.

**Comment by Lumipharon** [comment]
perma stagger an a weapon with a huge mag and goodaim mode ability is uh, not ideal.

**Comment by MLGTASTICa** [comment]
its time for the ravager to get chain-staggered and instantly die because he cant use his abilities for a whopping 15 seconds

**Comment by Losenis** [comment]
I'm more frightened of marines wiping a push with stamcrit due to forgetting their aim mode tbh

**Comment by TiviPlus** [comment]
Locking xenos out of their abilities like this seems like a bad idea, especially given how stagger works with life ticks

**Pull request closed without merging**
