### PR TITLE
Removes FC SG (again(again)) and adds tazers to POS

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

FC should have no SG

Tazers are as reccomended by psy in whatever tazer PR it was again
## Changelog
:cl:
balance: Removes SG in the POS and adds tazers to POS armoury
/:cl:

### CODE REVIEW

**Comment by neohenry** [comment]
heh

**Comment by psykzz** [comment]
Would it be better to just have the taser spawned on the command roles that can use them

**Comment by Chaznoodles** [comment]
Can we stop handing out tasers before we end up with people acting like MPs 😢

**Comment by Sibg** [comment]
Command staff are just MP's now when the need arises

**Pull request merged**
