### PR TITLE
Increases Queen heal cooldown

### PR DESCRIPTION
**Pull request by Kuro-ai**
## About The Pull Request

Increases cooldown from 8 seconds to 16 seconds

## Why It's Good For The Game

Queen heal is causing immortal xenomorphs memes right now,this nerfs that

## Changelog
:cl:
balance:adjusted queen heal
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -4. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by BurgerLUA** [comment]
I wouldn't even make it 16 seconds. I'd straight up make it 30 seconds for a powerful heal.

**Comment by Kuro-ai** [comment]
well that would be too extreme of a nerf

**Comment by BurgerLUA** [comment]
But it would be 100% fair. If someone for some reason sets the revolver to 200 damage, and you make a PR to make it 100 damage, that's still pretty high and there and there shouldn't be anything wrong with me suggesting to set it to 40 damage.

**Comment by Kuro-ai** [comment]
agreed,however you know how things are done here

**Comment by Isy232** [comment]
All I got to say is, no, not really, the heal is for 100 and every 8 seconds (12.5/second), a normal rifle bullet is 40 damage (with 0 AP). As long as its not an elder crusher (47 ballistic armor) with elder queen's (very strong) warding pheromones and the marines have no AP weaponry, the marines should be able to heavily outdamage the 12.5 health per second healing.

Also on the subject of that round, even with the queens healing I (I was the crusher) nearly died twice, once due to blue flame, other due to 2 marines with AP ammunition, I had to run away the latter time in a state where my health bar wasn't even visible it was so low.

This is also the queen that does this, the supposed biggest, strongest xeno of them all. She was an S tier frontline fighter, people thought it was bullshit so she was reworked to a support caste that is still S tier. Also, if the queen is using her support abilities effectively, she cannot be fighting the marines, this is the only thing she can be doing other than giving orders.

To be honest, out of all the castes, queen does not need the nerf, take a look at crushers charge that pretty much hits a marine once and gives them a medical issues list 5 pages long. Besides crash marines are dominating the win rates and we should be aiming to make the game less deadly instead of more.

If you really want to nerf the queens heal, I suggest making it only 25% as effective on burning xenos.

Seriously, this ability is only capable of memes in rare situations where marines are completely unable to burst down a xeno.

**Comment by Kuro-ai** [comment]
this ability is capable of making armored castes outheal any kind of damage,it's very much oppresive with the current cooldown

**Comment by Rohesie** [comment]
Small, gradual changes. This is good.
However a proper fix would be to make the queen heal a child of the shrike heal.

**Comment by jroinc** [comment]
+1 to the heal nerf as stands. It was kinda bullshit seeing even a fortified ancient defender tank all 500 rounds from a sentry AND all the fire from the marine force.

**Comment by Isy232** [comment]
Fortified defender is meant to be near completely resistant to bullets, try grenades or incendiary. Better yet, it cant move so just run away or dont shoot it at all. If I remember fortified defender was meant to be a shield for the boiler mostly.

I think increasing it a bit is okay but 16 is a bit much. I think 12 would be better.

**Comment by Rohesie** [comment]
Queen heal needs a bigger rework. This is in a good direction anyway.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
