### PR TITLE
Hypospray can inject 60/120u at once

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Allows hyposprays to inject their full amount in 1 go
## Why It's Good For The Game
It is now possible to fully inject a chem mix entirely in 1 go.
## Changelog
:cl:
qol: Hyposprays can inject their entire storage at once.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
im going to directly inject people with 120u of oxy

cool pr spedmrghe

**Comment by Lauwma** [comment]
Finally a buff for loading inside vali.

Put hypospray in reagent pouch, load chem 60u, rejoice

**Comment by jroinc** [comment]
Classic powercreep

**Comment by Looking4bros** [comment]
Juicers rise up!

**Comment by Ephemeralis** [comment]
I cast level 3 120u soporific.

**Comment by Looking4bros** [comment]
> I cast level 3 120u soporific.

May i suggest using Inaprovaline instead? It instasleeps people on OD and does some lovely heart damage if you crit OD them. 60u OD, 100u Crit OD

**Review by TiviPlus — APPROVED** [review]
lol

**Pull request merged**
