### PR TITLE
Marine drugs vendor

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Marines get a new vendor in prep, with a huge supply of basic drugs (kelo, trama, bica, trico, dylo, some basic bruise and burn pack, and med scanner)

The vendor in medbay is now only accessible by medical personnel 

## Why It's Good For The Game

Give marines an easy access to heal, cause i don't see while the heal drugs should suffer from scarcity

## Changelog
:cl:
add: New marine med vendor in prep
tweak: Med vendor in medbay are now only accessible by medical jobs
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -41. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SplinterGP** [comment]
IMO prep is already bloated as hell, fitting more vendors in there would be veeery hbngnhngn

**Comment by BraveMole** [comment]
On sulaco
image

On POS
image

**Comment by mokulus** [comment]
Doesn't this make Corpsman pointless?

**Comment by BraveMole** [comment]
Marines always rush and take drugs from medbay. This just make prep smoother. Also, corps task is currently resurrecting bodies, removing shrap, splinting people, giving advanced drugs, etc. All ungas that have some experience are carrying med, and are always premed anyway

**Comment by Chaznoodles** [comment]
Powercreep

**Comment by SplinterGP** [comment]
why that has so many stuff in it seeing MEDICAL has less ? marine standard meds are combat injectors that can be refilled and they can get a pouch of it, not all 300 meds, if they wanna get more meds they either go to medbay or play corpsman

**Comment by SplinterGP** [comment]
> On sulaco
> image
> 
> On POS
> image

on sulaco it blocks basically an entire passage and on POS you had to move both clothing and armor vendors to prep exit.

**Comment by BraveMole** [comment]
> why that has so many stuff in it seeing MEDICAL has less ? marine standard meds are combat injectors that can be refilled and they can get a pouch of it, not all 300 meds, if they wanna get more meds they either go to medbay or play corpsman

Because marines are way more. I always pack a full load of basic pills when i play unga, and i'd say a lot of people are doing the same. This is just easing a process that already is here, since medbay vendors are accessible by everyone.

I never use combat injector, because it's way faster to self med with pills than injectors IMO. 

I'd be faborable to a small nerf of basic drugs, and making advanced chem more accessible for corps/mo's

**Comment by Sulaboy** [comment]
I’d rather you buff the first aid pouch or something. I think it would be better to make the marine vendor something that goes on the ground to refill basic first aid for grunts, like bandages, ointment, splints, and their basic injectors/pill packets. Kinda like the lasgun battery charger and how it’s supposed to be brought down.

 I don’t feel like marines should be walking around with 90 pills on them (Total for three pill bottles Bic/Kelo/Tram since the pill bottle capacity changes). Heck the vendor you proposed looks like an easier way for me to stock up as corpsman.

**Comment by SplinterGP** [comment]
> I’d rather you buff the first aid pouch or something. I think it would be better to make the marine vendor something that goes on the ground to refill basic first aid for grunts, like bandages, ointment, splints, and their basic injectors/pill packets. Kinda like the lasgun battery charger and how it’s supposed to be brought down.
> 
> I don’t feel like marines should be walking around with 90 pills on them (Total for three pill bottles Bic/Kelo/Tram since the pill bottle capacity changes). Heck the vendor you proposed looks like an easier way for me to stock up as corpsman.
> 
> I’m don’t like this but other changes need to be made before anyone is happy about medical prepping.

quite this^^

**Comment by TiviPlus** [comment]
See statement by Sulaboy
I also disagree with creeping like this, corpsman should have more tools available to start than marines to maintain usefulness

**Pull request closed without merging**
