### PR TITLE
Icy caves crash fixes & adjustments

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

removes some stuff and fixes some stuff

## Why It's Good For The Game

Red disk was more or less a free disk for marines, so added a silo and fog area west of it in the miner building behind the icy walls to prevent undefendable camping meaning xenos only got a few fog spots to shoot from giving marines a chance.

green disk had marines hard camping it so fixes that by extending the fog  upward rather then closer to the disk giving xenos a place to attack from two areas.

blue disk well a bit tricky i think its more or less an issue of skill and its already pretty far so i aint touching it

there was also that silo south of dorms which had no fog and stuff so i deleted that

## Changelog
:cl:
balance: fog and silo changes
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
@RipGrayson

**Comment by RipGrayson** [comment]
Most of this is alright, this is fine.
east1

The only minor nitpick I have is placing this silo so close to the disk when there's a clear firing line between the two.
east2
You could set a boiler inside the fog to continually bombard the disk location with no real counterplay.  Given the entrance(s) to the silo area are 2 tiles wide, the marines could also just do suppressive fire to keep xenos from leaving.

**Comment by vilereaver41** [comment]
> Most of this is alright, this is fine. east1
> 
> The only minor nitpick I have is placing this silo so close to the disk when there's a clear firing line between the two. east2 You could set a boiler inside the fog to continually bombard the disk location with no real counterplay. Given the entrance(s) to the silo area are 2 tiles wide, the marines could also just do suppressive fire to keep xenos from leaving.

Il see what I can do

**Comment by RipGrayson** [comment]
This looks fine now, I don't see any outstanding issues that need addressed.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
