### PR TITLE
Cat's cannot be picked up from range anymore

### LINKED ISSUE #14428: Martin is omnipotent
### Description

You can click-drag martin into your hands, other people's hands, as a ghost, through walls, through cameras.
I want this reworked and not obliterated because everyone will go to CM if this is fully removed. Make this so it takes an action time and seems more like a feature than a bug plz.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: 24221
BYOND Version: 515.1610
Server revision compiled on: 2023-11-10T21:01:14+00:00
Master commit: [92c47508033cf7042e05b7c930a5021326a7f92c](https://github.com/tgstation/TerraGov-Marine-Corps//commit/92c47508033cf7042e05b7c930a5021326a7f92c)
The following pull requests are currently test merged:
[#14258: 'Reverts Hyperscale 3' by lKiseki at commit f1eedc1e4a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14258)

Local commit: bc4e3299cdf866c8cbf63c8cc001e8f473cc5bdb
Server tools version: 5.17.1

### Reproduction Steps

Go to martin as a ghost, through a camera system, or normally in the same room as him.
Click drag him to yourself in any number of ways.
Only benos cant click-drag him to others which makes this less of a big bug or anything.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Notamaniac**
## About The Pull Request
Fixes #14428

## Why It's Good For The Game
What do you mean Martin is a cat IT LOOKS LIKE A DOG
Also this isn't good for the game but marines need nerfs badly
## Changelog
:cl:
fix: You can no longer pick up cats from a distance
/:cl:

### CODE REVIEW

**Review by Lumipharon — CHANGES_REQUESTED** [review]
The base proc should just return true or false, since it already checks adjacent and some other shit. This issue has cropped up for other stuff for the same reason.

**Comment by novaepee** [comment]
NOOOOOO PLEASE

**Comment by Barnet2** [comment]
Extremely unsoulful

**Comment by LohnRan** [comment]
The PR that kill TGMC.

**Review by Lumipharon — APPROVED** [review]

**Comment by chizzy376** [comment]
Yeah the game isn't playable anymore, idk if I should open a revert pr in protest..

**Pull request merged**
