### PR TITLE
Directional attacks 2, probably better implementation edition

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Directional attacks. It's https://github.com/tgstation/TerraGov-Marine-Corps/pull/14541 but implemented as an element with a proper preference instead of a verb.

You click any tile in the direction of the mob you want to click, and you click them provided they're next to you. Works with any type of special click, like right click, ctrl click for example. It targets only mobs since it targetting atoms as well would probably be more of a nuisance than helpful.

This is a preference you can opt out of and it will be off by default for any non new players unfortunately.

This PR is also a bounty from @novaepee.
## Why It's Good For The Game

This should help lessen the massive gap between skilled and non skilled players, mainly helping xenos due to them being melee focused. 
## Changelog
:cl:
add: Added directional attacks, you can enable them in the preference menu for all living mobs.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
lets go

**Comment by PibeCantina** [comment]
TM when

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
Apparently lagged server to death?

**Comment by Looking4bros** [comment]
A Vali buff after all this time? :O

**Pull request merged**
