### PR TITLE
Fixes AI eye layer to be above all the things

### LINKED ISSUE #2087: Overwatch eye icon appears below weeds
## Testmerges:

Round ID:  626 
BYOND Version:  512.1464 
Server revision compiled on:  
Master commit: cd265db711da1fb8063767ccb7a93107a58201eb 
The following pull requests are currently test merged: 
#1904: 'Implements classic and hotkey keybinds' by psykzz at commit ae180eb84e 
#1769: 'Xeno Shrike' by Rohesie at commit 7bb8d2384c 
#2048: 'Adds sounds for hud and binoculars, reduces volume of some very loud ones' by MoXuT0 at commit e2fa60dba7 
#2004: 'HUD improvements.' by Rohesie at commit 62306ab156 
#1860: 'Fixes vent and weed layer issues.' by DominikPanic at commit 8f6d7dc56a 
#1876: 'Adds debugging information for 2 of the most elusive runtimes.' by DominikPanic at commit 0ebe0ab57e 
#1905: 'Reduces body temp damage for humans' by psykzz at commit 3eb3cfac31 
#1829: 'Flares burn weeds' by psykzz at commit 9a8b40b19f 
#1931: 'Replaces eye blur effect with real one' by MoXuT0 at commit f7bf81be49 
#1965: 'Add extra attachments to the ERT shuttles.' by psykzz at commit 8f82aa7b85 
#1966: 'Balance changes to the GAL9' by psykzz at commit cfa2f58e5d 
#1964: 'Lighting controller port from /tg/' by DominikPanic at commit eb0ae3b90b 
#1987: 'Checks if /tg/ regression fixes elusive runtime' by DominikPanic at commit e9e7e2590b 
#2055: 'Jump to Area ugly hack' by Rohesie at commit cad0bfc89b 
#2074: 'Cooldown fix and cleanup' by Rohesie at commit 28011dfa6d 
#2079: 'Fixes legcuffs runtime' by psykzz at commit c2f943170c 
#2078: 'Increase weeds size' by psykzz at commit 4b800790ee 
#2077: 'Unwielded fire from attachments nerf' by Rohesie at commit b19dd7657e 
#2084: 'Fixes EORD being called twice' by psykzz at commit 1bee28566c 

## Reproduction:

изображение

### PR DESCRIPTION
**Pull request by psykzz**
Fixes #2087

### CODE REVIEW

**Comment by psykzz** [comment]
May fix 2087 but i wanted it to be above all the things but that didn't happen 🤷‍♂

**Comment by DominikPanic** [comment]
The better question is, why doesn't /tg/ do this? 
Also the core of this issue is fixed in #1860

**Comment by DominikPanic** [comment]
Since that's merged try to replicate it now. Anyway I'd suggest not implementing new layers/planes as there may be many more evil bugs with overlapping created that way, and we dont' want to be hunting those for the next few month.

**Comment by Rohesie** [comment]
Is this still a thing?

**Comment by psykzz** [comment]
Yes 
image

**Comment by Rohesie** [comment]
@DominikPanic ?

**Comment by DominikPanic** [comment]
https://puu.sh/DOeFn/c73031f03b.png 
Unable to reproduce

**Comment by DominikPanic** [comment]
The plane is the same as weeds, it is already ABOVE_ALL_MOB layer. Did you update your branch? Seems like you're doing something wrong.

**Pull request merged**
