### PR TITLE
Xeno can see the health of marines rather than their pain

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Change the pain hud for a health hud

## Why It's Good For The Game

Pain is a not a usefull information for xeno, it's even a trap at some times

## Changelog
:cl:
balance: xeno will see directly the health of marines, rather than their pain
/:cl:

### CODE REVIEW

**Comment by KornFlaks** [comment]
Obligatory: Buffing Xenos, on my TGMC?

**Comment by Losenis** [comment]
based

**Comment by Losenis** [comment]
Until one M15 deletes a quadrillion + weeds in 2 clicks

**Comment by Pariah919** [comment]
way too much information given to you at once
xenomorphs already get way too much information for effectively just existing, (the ability to see through walls, etc)
marines have to gauge the amount of health you have, based off your sprite
just remove painhud, it was only added because shrike was being a thing, and rohesie accidentally gave it to every xeno, it isn't good and is just misleading and giving everyone the ability to see health for free is dumb and stupid, unless you give it to marines aswell

**Comment by DerrickChamberlain** [comment]
So hard to tell when a marine is nearly dead or really fucked up. Surely the man falling over every second and dropping his shit and the trail of blood is not indicative enough.

But as a more serious note. Maybe have more blood on marine sprites or more visible blood dripping when the marine takes heaps of damage to show it off more. Could be cool and aesthetic.

**Comment by BraveMole** [comment]
> So hard to tell when a marine is nearly dead or really fucked up. Surely the man falling over every second and dropping his shit and the trail of blood is not indicative enough.
> 
> But as a more serious note. Maybe have more blood on marine sprites or more visible blood dripping when the marine takes heaps of damage to show it off more. Could be cool and aesthetic.

big wyci? 
and dude, you never play xeno, why the fuck are you commenting that?

**Comment by BraveMole** [comment]
> way too much information given to you at once
> xenomorphs already get way too much information for effectively just existing, (the ability to see through walls, etc)
> marines have to gauge the amount of health you have, based off your sprite
> just remove painhud, it was only added because shrike was being a thing, and rohesie accidentally gave it to every xeno, it isn't good and is just misleading and giving everyone the ability to see health for free is dumb and stupid, unless you give it to marines aswell

Well no pain hud is probably better than what we currently have, agreed.

I think xeno should still have some info on marines health, cause contrary to xeno marines do not have damage decal. Can you imagine playing marine without damage decal again? That would be shit as fuck

**Comment by SplinterGP** [comment]
i think painhud is actually usefull if you know how to use, if you slash a marine and his hud drops alot that means he doenst have a painkiller and probably no other chems, etc

**Comment by Losenis** [comment]
>unless you give it to marines aswell

Medhud says hi

>Surely the man falling over every second and dropping his shit and the trail of blood is not indicative enough.

Neurotox gives the marine a flashing red healthbar as if about to drop to crit any second even though he might well be at full health and ready to fuck your shit up. Blood trails are also so unreliable as to be ignorable given you need a marine to be alone in a clean area to even spot the blood, identify it as recent, and attribute it to a specific marine that could be running around. At that point it's redundant unless you're a young rouny that needs a marine to be dying on top of already being completely alone.

**Pull request closed without merging**
