### PR TITLE
Distress Victory Conditions 2: Nuclear Boogaloo [WIP]

### PR DESCRIPTION
**Pull request by Hathkar**
## Why It's Good For The Game

- [ ] Nuke blowing up on the planet with the Alamo off the planet is a marine major
- [ ] Nuke blowing up on the planet with the Alamo on the planet is a marine minor
- [x] Xenos hijacking the Alamo and dying shipside is a xeno minor
- [x] Xenos hijacking the Alamo and/or killing all marines is a xeno major
- [x] SD blowing is a draw
- [ ] Nuke does not function if xenos hijack
- [ ] Nuke cannot be anchored in the Alamo
- [ ] Nuke blowing up on the ship is a xeno major
- [ ] Xeno leader cannot hijack or call Alamo when nuke is active
- [ ] Xeno leader indicator points to active nuke
- [ ] Make that area that an active nuke is in into an underground area to prevent mortar/OB?

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
coolio

**Comment by ilikesaying** [comment]
the fact that you added the "Nuke blowing up on the ship is a xeno major" means we're stupid enough to set the nuke to explode while on the ship, which is true

**Comment by spookydonut** [comment]
Doesn't pass travis

**Comment by Hathkar** [comment]
```
code/modules/mob/living/carbon/xenomorph/abilities.dm, line 101, column 3:

error: possible unreachable code here

code/modules/shuttle/marine_dropship.dm, line 1079, column 2:

error: possible unreachable code here
```

This PR doesn't even touch ``code/modules/mob/living/carbon/xenomorph/abilities.dm``
As for ``marine_dropship.dm`` how do I make it reachable?

**Comment by TiviPlus** [comment]
Merge master branch into your PR it should fix it

**Comment by Hathkar** [comment]
``Analyzing proc bodies...

code/modules/shuttle/marine_dropship.dm, line 1079, column 2:

error: possible unreachable code here``

**Comment by TiviPlus** [comment]
Still WIP?

**Comment by Hathkar** [comment]
Yeah, still WIP. I'd appreciate a review, since I'd like to know if what I have right now works, before I move onto the next bits.

**Pull request closed without merging**
