### PR TITLE
Kill macros

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Kill macros

## Why It's Good For The Game

Macros are bad. Cheating is not allowed on this server

## Changelog
:cl:
del: Macros have been disabled to avoid server lag and abuse
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
image

Also add a proper pr body

**Comment by jroinc** [comment]
*SCREEEEEEEE*

~finally~

**Comment by SplinterGP** [comment]
add keybinds for some other stuff, like underslug attachment, last i checked it has no keybind

**Comment by Losenis** [comment]
[Cries in *warcry]

**Comment by TiviPlus** [comment]
> [Cries in *warcry]

You can already do that in keybinds though

**Comment by David-Stormwell** [comment]
Make the rest of the gun toggles such as safety, unloading your gun, and also other abilities such as thermal cloaks hot-keyable and I'll agree with this change.
Otherwise, it's semi-fine, as people are forgetting you can make custom *me via hotkey menu as well.

**Comment by SplinterGP** [comment]
Added do not merge flag until we have more stuff keybinded

**Comment by JackTheJackhammer** [comment]
Oh god please add unloading your gun and taking a weapon from a belt holster a keybinded thing

**Comment by SilencedMP5A5** [comment]
you just don't like my ocelot quotes :(

**Comment by BraveMole** [comment]
> you just don't like my ocelot quotes :(

You can do quotes with custom emote system without macros :)

**Comment by Georgeur** [comment]
if you could keybind a single item for a pick-up hotkey, it'd really help
I know that the pick-up verb being used with throwing knives is the biggest problem with them, but its a pain in the ass picking them back up once you've used some of them

**Comment by Georgeur** [comment]
actually I'm wondering what you're tryna fix here, like there are reasons but youve given none

**Comment by TiviPlus** [comment]
> actually I'm wondering what you're tryna fix here, like there are reasons but youve given none
> there no reason for a crude fix, if you want specific things changed I can either give you the code or tell you where the problem is
> discord handle is revy, pm me anytime

Fun macros I know exist include
Lag macros
Spam throw/pickup macros
A macro that husked anyone with one button press
A macro to stunlock people with paper
A macro to stunlock anyone standing next to you
Pickup macro spam
And thats just to name a few whether macros are going is not up for debate

**Comment by Georgeur** [comment]
> > actually I'm wondering what you're tryna fix here, like there are reasons but youve given none
> > there no reason for a crude fix, if you want specific things changed I can either give you the code or tell you where the problem is
> > discord handle is revy, pm me anytime
> 
> Fun macros I know exist include
> Lag macros
> Spam throw/pickup macros
> A macro that husked anyone with one button press
> A macro to stunlock people with paper
> A macro to stunlock anyone standing next to you
> Pickup macro spam
> And thats just to name a few
> whether macros are going is not up for debate

that's mostly associated with the pick-up verb, would removing the verb be an alternative

**Comment by TiviPlus** [comment]
No

**Comment by SplinterGP** [comment]
> that's mostly associated with the pick-up verb, would removing the verb be an alternative

No, this cripples people from picking up stuff legitely

**Comment by Dolth** [comment]
Please add eject-magazine in the keybindings. Thanks.

**Comment by InterroLouis** [comment]
Could you add a hotkey for toggle right click?

**Comment by SilencedMP5A5** [comment]
leave macros alone, lmao

**Comment by SplinterGP** [comment]
> Could you add a hotkey for toggle right click? 

Ill look into

**Comment by TiviPlus** [comment]
> Please add eject-magazine in the keybindings. Thanks.
> Also the medevac stretcher activation, cheers.

Former done latter you can just right click

**Comment by InterroLouis** [comment]
There's no keybind for load from attachment. There's one for underbarrels only but the pistol lace is a barrel attachment, so you need load from attachment regular.

**Comment by Wayland-Smithy** [comment]
The `PAUSE` key is bindable, but does not seem to be detected when pressed, and a Toggle Fire Mode keybind was requested.

**Comment by spookydonut** [comment]
atom verbs (what players call macros) cause lag and this is a good change that will never be reverted once merged no matter what.

**Comment by Wayland-Smithy** [comment]
An IC `Give` verb hotkey is requested.

**Comment by David-Stormwell** [comment]
firemode needs a hotkey

**Comment by TiviPlus** [comment]
@BraveMole Add a firemode toggle and a give key and I will merge after

**Comment by Dolth** [comment]
> > Please add eject-magazine in the keybindings. Thanks.
> > Also the medevac stretcher activation, cheers.
> 
> Former done latter you can just right click

Oh wow no shit sherlock. I had a macro for it, I'd like a keybind for it. That's the whole point of the discussion, not just right clicking at everything.

**Comment by SplinterGP** [comment]
> 
> 
> firemode needs a hotkey, same for open verb, how else am I supposed to open god dam crates that are under piles of items without killing my client.

Right click menu

**Comment by Dolth** [comment]
Also a verb/keybinding to use the vali suit would be neat.

**Pull request merged**
