### PR TITLE
Corps no longer see robot health, engineers can see robot health. Pfcs no longer see machine health

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Title

## Why It's Good For The Game

Corp cannot heal robots, it doesn't make sense to have them see their health. Engineer can heal robots, it makes sense for them to see their health.

Pfcs can no longer see health of sentries, that's a byproduct of this code but i think it doesn't matter much since they are not really suppose to repair them

## Changelog
:cl:
balance: Corps no longer see robot health
balance: Engineers can see robot health
balance: Pfcs no longer see machine health
/:cl:

### CODE REVIEW

**Comment by revelation-8468** [comment]
why not make it so mesons act as a robot medhud

**Comment by BraveMole** [comment]
> why not make it so mesons act as a robot medhud

Because engies can choose welding glasse

**Comment by revelation-8468** [comment]
> > why not make it so mesons act as a robot medhud
> 
> Because engies can choose welding glasse

they have welding goggle attachment for helmets, though

**Comment by private-tristan** [comment]
> > > why not make it so mesons act as a robot medhud
> > 
> > 
> > Because engies can choose welding glasse
> 
> they have welding goggle attachment for helmets, though

there's not many engis who will give up mimir/tyr helm system for WELDER GOGGLES

**Comment by Mechanelize** [comment]
synth too?

**Pull request closed without merging**
