### PR TITLE
Cowboy leather jacket suit slot fix

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

When Hyper made the cowboy PR, the /obj/item/clothing/suit/cowboy didn't inherit any suit slot, but /obj/item/clothing/suit/storage/marine/harness/cowboy did, or as we know it the reinforced REATHER jacket with webbing. This is because /obj/item/clothing/suit/storage/marine/harness/cowboy inherits from /obj/item/clothing/suit/storage/marine, and that has suit slot.

In other words, code fix.

## Why It's Good For The Game

Ocelot asks me to fix, I fix.

## Changelog
:cl:
fix: Cowboy's reinforced leather jacket has suit slot now
fix: spelling error on reinforced REATHER jacket with webbing
/:cl:

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
REATHER

**Comment by hyper2snyper** [comment]
This isnt a fix. It wasnt a bug before.

**Review by BraveMole — CHANGES_REQUESTED** [review]
it's not in vendors so don't talk about loadouts

**Comment by novaepee** [comment]
> it's not in vendors so don't talk about loadouts

It is in surplus vendor:

image

**Pull request merged**
