### PR TITLE
Mostly buffs xenos across the board, nerfs speed

### PR DESCRIPTION
**Pull request by Kuro020**
## About The Pull Request

Mostly buffs xenos stats across the board, while reducing speed, for a complete list of changes read the hackmd https://hackmd.io/@wlLEbadtQoCyE4iytTkonw/r1vSnLmBR

## Why It's Good For The Game

Xenos are really struggling right now, with the ammount of additions marines have gotten over time while xenos themselves have had almost no additions, these buffs should push them to have a better time on the game.

## Changelog

:cl:
balance: Makes xenos tankier and a little slower plus some other assorted xeno changes, read the hackmd linked on the pr
/:cl:

### CODE REVIEW

**Comment by Barnet2** [comment]
Not being able to one-pb a runner, soul is GONE.
Uh, now that it isn't a straight armor/hp/dmg/speed buff it'll be interesting to see, I suppose.

**Comment by lKiseki** [comment]
My honest to god feedback. This'll be a long one so bear with me...

### Behemoth
Probably fine as a band aid since the caste underperforms, but I doubt stat changes will help it out much.

### Boiler
Boiler does not need a health increase! It's tanky enough that it can survive incoming and distant shots, but fragile enough that it can be punished for being incorrectly positioned. I'd say it is in a very okay spot at the moment, especially since it cannot really be killed if it plays smart. I would be fine with the acid spray changes, though I'd say you might've buffed that a bit TOO much.

### Bull
Feeling iffy about these changes. It's a bit of a Behemoth case, where the caste underperforms not because of stats, but because its abilities don't really help it out much. I'd say Bull doesn't need them, either way, besides the slash damage increase maybe.

### Carrier
I'm actually fine with buffing Carrier. You should go back on the movement speed nerf, though, and maybe tone down the health buff a little.

### Crusher
This one is where I stare at you like you're crazy. Crusher is already VERY good, and the only thing it really needs is more movement speed, and maybe some help with sunder in general. Everything else you're doing here is highly questionable.

### Defender
This is also another caste whose stats you shouldn't touch at all. If you asked me, the only thing I'd do is make it so that you can attack during Fortify, and remove the weird yet intentional cooldown/delay during which Fortify won't let you use other abilities like charge. Otherwise, just don't change the stats.

### Defiler
Sssssure? I'm feeling a bit iffy about these but I'd be open to seeing how the caste performs after such changes.

### Drone
This caste doesn't need stat changes. Or anything at all, really. It's already in a perfect spot if you ask me.

### Gorger
I am very much fine with increasing the slash damage, and actually believe you should increase it more, but the speed and health changes are completely unneeded otherwise. Bear in mind Gorger is arguably one of the tankiest castes in the game if you factor in Overheal, even moreso with Feast active.

### Hivelord
These changes are completely unnecessary. Hivelords are not combat castes, and have a great escape tool in the form of Resin Walker. If they're caught out of place, that's on them.

### Hunter
These changes are also completely unneeded. Hunter can chain stun you into oblivion and I don't think it needs any of these. Maybe the armor buffs at most.

### King
King's super high stats are somewhat of a band aid and you're putting another on top of the old one. Never been a fan of stat sticks either way.

### Praetorian
Feeling iffy about these, willing to see how it goes though.

### Pyrogen
I'm skipping this one due to a lack of knowledge and/or experience with the caste.

### Queen
Okay, you are overdoing it here. That slash damage buff is huge, and also unneeded, Movement speed nerf is also unneeded, same for the health buff. I'm fine with the plasma gain changes, though.

### Ravager
I am a ravager main so I can actually offer some insightful feedback here. I wouldn't nerf their movement speed; the health change would otherwise be fine **IF** you nerf the stun duration on their charge.

### Runner
I will not deny this caste needs the help, though I still think the changes to Evasion were a mistake. Should've been made into a damage reduction ability instead of outright damage denial.

### Shrike
These changes are completely unnecessary. Shrike is already completely fine as is.

### Spitter
Eh... sure, why not? Caste could probably use a tad bit of help.

### Warrior
This might make the caste overpowered. Willing to see how it goes, though.

### Widow
Eh... I don't like Widow's abilities or how it plays out by design. More damage to the spider gang of multiple spiderlings and a Widow sounds bad, though.

### Wraith
Sure. I'm fine with these.

### Spit changes
You probably shouldn't buff autospitter damage since it already deletes people up close. The damage falloff change is otherwise fine, though if you really have an issue with spit damage I'd sooner look at Mimir than buff spits.

**Comment by chemistrymain3** [comment]
A major thing with the spitter is that unlike neurotoxin being hit with acid really isn't all that debilitating. Everyone carries kelotane.

The burns just don't hurt that much, and the acid doesn't travel through your friends, so it's not something you can blindfire, either. The slight damage increase isn't enough to make spitter worth it- you're generally doing more damage as a sentinel, because neurotoxin hits like a truck. Even the acid spray stun can be better executed by other castes.

**Comment by Woker2004** [comment]
> ### Ravager
> I am a ravager main so I can actually offer some insightful feedback here. I wouldn't nerf their movement speed; the health change would otherwise be fine **IF** you nerf the stun duration on their charge.

My thought is truthfully is to increase stagger resistance and maybe buff sunder by 5-10 to all armor except fire

**Comment by novaepee** [comment]
https://tgmc.statbus.space/rounds/page/1

image

for anyone that want to keep track

**Comment by coldironwarrior** [comment]
this also means structures are less durable as more damage is applied to cades, etc.

**Comment by Kuro020** [comment]
> this also means structures are less durable as more damage is applied to cades, etc.

yes, if I see structures are too weak I'll buff them in the future to compensate

**Comment by Araulius** [comment]
Light armor is the future

**Comment by coldironwarrior** [comment]
> yes, if I see structures are too weak I'll buff them in the future to compensate

as long as it's kept in mind. i think based off the doc, the only actual problem is the acid damages against cades, the slash damage increases are probably negligible against static defence stuff.

rest seems okay but not into the speed decreases; though i get why you added them

**Comment by Pariah919** [comment]
Kuro. You gave Carrier 100 more health and nerfed speed by .1.
I don't even need to read more. God help you.

**Comment by SimplySmiley123** [comment]
Oh boy can't wait for the stun-reliant and brazil castes to be uncontested with this and for the game to get even slower for both sides.

Honestly if you want to buth health and damage across the board, nerf the stuns as well so it's not pure bullshit to go against. Speed doesn't matter as much when xenos have the control over the map and ful lfreedom of movement with x-ray vision to boot.

**Comment by MiniMeatwad** [comment]
>Get slashed 3 times by xeno, 30 organ damage
Yep, balanced

**Comment by Arturlang** [comment]
> Oh boy can't wait for the stun-reliant and brazil castes to be uncontested with this and for the game to get even slower for both sides.
> 
> Honestly if you want to buth health and damage across the board, nerf the stuns as well so it's not pure bullshit to go against. Speed doesn't matter as much when xenos have the control over the map and ful lfreedom of movement with x-ray vision to boot.
> 
> Also worth noting is that if this affects Puppeteer, shit's gonna become the meta to delete marines in an instant.

Puppeteer isn't getting any buffs with this PR, atleast according to the doc

**Comment by Arturlang** [comment]
My main suggestion here is to improve behemoth's slash a bit so their abilities will do actual amounts of damage, and so they're not simply a big teddy bear that can't kill even a shuffled marine.

**Comment by MiniMeatwad** [comment]
Should reduce xeno speed a lot more if you want to do cmification, if they're gonna hit harder they might as well move slower.

**Comment by Notamaniac** [comment]
Though I was anticipating this to be a bandaid fix, I was surprised at how ineffective it felt in practice

[Example1.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17688334/ebff8d3c-ad5a-4e19-b6de-69500142d9ec)
[Example2.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17688334/5ce1eb52-14e0-46d8-a97d-8f602ab3e1c6)
[Example3.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17688334/4b7e32b8-ab32-4e79-896a-a4a5478c1743)

Now you could argue - Just don't push marine aimballs alone. Which is the problem, big aim balls need cohesion to take down, or more accurately specific castes to be competent. And worse those specfic castes all have counters/mitigations.

Defiler - Can be shotgunned/staggered to prevent gas. Antigas/tangle can be used to limit effectiveness of gas
Crusher - Razorwire/Cade traps, or outta nowhere AMR to provide a nasty slowdown
Boiler - AMR/Autosniper/SG-62 (yes it does enough damage) to deal enough damage to prevent globs being launched. Can have a xeno like a defender block for them, but their gas can still be neutralised with anti gas.
Queen - Hold order reduces stun duration on screech
King - Abilities have windup, which means that you're vulnerable to AMR or SADAR, or simply being staggered with a shotgun

On higher pops, it's much more likely to come across marines who know and possess the appropriate counters (and xenoes who have no idea how to use their abilities effectively), meaning that xeno can't effectively damage the aimball as well on lower pops. On Nuclear marines switch between being on the offensive and defensive, on the defensive they can aimball, and on the offensive they have OB's to clear away any mazes/turrets/xenoes in their path.

TL;DR, Marines have the counters, Xenoes don't.

I think there are much more systemic problems too, and isn't something that can simply be solved by buffing stats

Much more is expected from each individual xeno, and there's much more room for error as a marine. If one marine charges off alone and dies, at worst they give some psy and 1/6th of a larva. If a xeno dies, at worst they deny a T2/T3 slot, potentially deny a Queen/King, and if their corpse is secured they can be sold for req points, which can be used to buy req weapons, snowballing into more deaths and a decisive marine advantage. And if you die as a xeno, you die period, while a marine can be revived, and with some time brought back to full health.

This also extends into another issue, xenoes need to secure wipes to effectively hurt marines. If you kill one or two marines, and don't drain them, even if you managed to cause a frac/IB/organ damage, you've contributed very little. Those marines can easily be revived, treated with splints/QC+/Peri+, or medevaced. Asking xenoes to specifically play rav/runner/hunter to have a higher RNG chance of causing fracs/IB/organ damage A : Doesn't sit right with me B : Further contributes to skill issue by playing 'inefficent castes'. While attrition is a thing (i.e. causing enough marines to have injuries that the overall effectiveness of the marine force is diminished), with marines on the defence on nuclear most of the time, being able to create safe areas to stall with barricades, and being able to hold onto miners to gain an advantage while stalling, while also being able to seize on the mistakes of noob xenoes to buy req gear, long drawn out fights edge more towards marines.

As an aside, one round we managed to kill 3 people in admin on Big Red. Normally that would be a good thing, but 3 more marines and the APC arrived while we were resting. Two held us off, the other tossed the corpses into the APC, and that fight might as well as never happened. 

And even if you do cause a wipe, sometimes it just doesn't even matter
wipe
Two wipes happened on that op, and xenoes still couldn't win because the remaining marines had req weapons, and xenoes don't scale off mass fuckups. Situations reversed, xenoes had a mass wipe- marines instead can convert that lead into req weapons ect. so on.

There's also other issues like burrowed presenting a massive disadadvantage for xenoes when admins don't press the autobalance button, Marine respawns, the Tank and APC contributing to the big unassailable aimball, but ideasguying about solutions is useless without getting off your ass and actually coding them.

So welcome to my ted talk blah blah blah

**Comment by PibeCantina** [comment]
Yeah, even though i really like the buffs, this will not improve xenos a whole lot, it feels nice to not get oneshot by tank with no counter but this doesn´t solve any problems xenos have at all, and i still think marines are stronger but w/e. My point is that this is just another bandaid over xenos having near to no content

**Comment by Kuro020** [comment]
Of course, this is just one step, this pr mainly gets rid of the meme we have of a single marine being able to, without much effort, shit on xenos, this will not fix all problems, but there is more stuff to come

**Comment by SimplySmiley123** [comment]
> And if you die as a xeno, you die period, while a marine can be revived, and with some time brought back to full health.

If you die as a marine it's not guaranteed you'll be revived, xenos can and will camp your body, especially if you get brazil'd and/or there's a hivemind player. And even if you get recovered it highly depends on both how good the corpsmen are and how much pressure is being put on them.

Xenos have a 5 minute respawn.
Marines 30 minute long one.

**Comment by SimplySmiley123** [comment]
> Yeah, even though i really like the buffs, this will not improve xenos a whole lot, it feels nice to not get oneshot by tank with no counter but this doesn´t solve any problems xenos have at all, and i still think marines are stronger but w/e. My point is that this is just another bandaid over xenos having near to no content

Problem to me is that no matter what xenos have no variety in options.
Just buffing stats overall at the cost of barely noticeable speed reduction won't do much with that.

**Comment by Ephemeralis** [comment]
The health increases are excessive across the board. They should probably be reduced by half. They definitely need *something*, but I think this is too much as it stands.

**Comment by Lefunny** [comment]
Based pr, xenos winrate were sucking before and now things are back to order, everything is fine and anyone against it is moping hard, 'xenos' who didn't liked the change have 30% playtime as xeno cope cope cope cope

**Comment by Pariah919** [comment]
Someone yelled at me to give a more insightful opinion.
Either way, flat buffs across the board are pretty funny. removing minor amounts of speed per caste to give them more hp is a questionable change in general since this doesn't even really bandaid the issue at hand which is that engagement and disengagement options for benos suck ass in most scenarios while marines have terrible movement options that are aided by the existance of things like APC and Tad. 

If you want to make the game generally slower but make things more tanky you would probably need to be far more extreme in your number changes than this considering the most hilarious thing I've seen here is probably the ravager damage (which appears to be gone?)

In a vaccum this will have solid changes, in reality though if 100hp is what saves you from an engagement and not the -.1 speed the caste lost. Then honestly you've already fucked up in some way in your game plan and how you've dictated your engagement. The loss of speed is more impactful overtime in a game than the 100 health you've seem to applied universally.

**Comment by chizzy376** [comment]
While I enjoy shaking up the meta, this is not the way to do it. It hurts the xenos in the longrun now that a larmor synap user will outrun them guaranteed

**Comment by Lefunny** [comment]
> While I enjoy shaking up the meta, this is not the way to do it. It hurts the xenos in the longrun now that a larmor synap user will outrun them guaranteed

Learn to position yourself and play nearby corners where you cannot be outran

**Comment by Lefunny** [comment]
> The health increases are excessive across the board. They should probably be reduced by half. They definitely need _something_, but I think this is too much as it stands.

That's just silly, barely can form an argument to that, halving the health buff kills the objective of the change

**Comment by Lefunny** [comment]
> In a vaccum this will have solid changes, in reality though if 100hp is what saves you from an engagement and not the -.1 speed the caste lost. Then honestly you've already fucked up in some way in your game plan and how you've dictated your engagement. The loss of speed is more impactful overtime in a game than the 100 health you've seem to applied universally.

100 HP has more importance than speed as you cannot dodge a billion guns and their sprite clicking, and yes 100 HP is stronger than -.1 speed

**Comment by iforgotmeword** [comment]
I would personally prefer if the speed needs were removed but meh

-63% marine time 30% ghost time
(Give me harder battles)

**Comment by yyzsong** [comment]
While I like the idea of a xeno stat buff, I think that "slower but tankier" isn't really the way to do this. Marines have ready access to burst damage and slowdowns, and xenos will have to cross ground to get to them. Losing speed means you have to spend longer getting to and running from marines, and that might mean that they have another opportunity to hit you with a big burst of damage.

In addition, xenos are a melee faction, and losing movement speed means less efficient engagements as marines can back out of melee range repeatedly. 0.1 slowdown might not be a tremendous amount, but if this is indicative of the stat changes xenos are going to receive in the future, I can't say I'm a fan.

Not to mention that being slower just feels worse. Xenos need to move around the map a lot. While 0.1 slowdown isn't a lot, it adds up.

**Comment by Lefunny** [comment]
> While I like the idea of a xeno stat buff, I think that "slower but tankier" isn't really the way to do this. Marines have ready access to burst damage and slowdowns, and xenos will have to cross ground to get to them. Losing speed means you have to spend longer getting to and running from marines, and that might mean that they have another opportunity to hit you with a big burst of damage.
> 
> In addition, xenos are a melee faction, and losing movement speed means less efficient engagements as marines can back out of melee range repeatedly. 0.1 slowdown might not be a tremendous amount, but if this is indicative of the stat changes xenos are going to receive in the future, I can't say I'm a fan.
> 
> Not to mention that being slower just feels worse. Xenos need to move around the map a lot. While 0.1 slowdown isn't a lot, it adds up.

Most combat castes that are meele have gap closers, use them

**Comment by Kuro020** [comment]
> Someone yelled at me to give a more insightful opinion. Either way, flat buffs across the board are pretty funny. removing minor amounts of speed per caste to give them more hp is a questionable change in general since this doesn't even really bandaid the issue at hand which is that engagement and disengagement options for benos suck ass in most scenarios while marines have terrible movement options that are aided by the existance of things like APC and Tad.
> 

The "issue" at hand is actually that the ratios are so that marines will outnumber xenos, and yet xenos are barely, if at all, stronger than a individual marine with standard gear, overall engagement/disengagement/apc and tad is just unrelated stuff, xenos aren't strong enough.

> If you want to make the game generally slower but make things more tanky you would probably need to be far more extreme in your number changes than this considering the most hilarious thing I've seen here is probably the ravager damage (which appears to be gone?)
> 

I dont want it to be a drastic change, xenos still need speed to rotate on objectives, but they also need to be tankier to defend said objectives.

> In a vaccum this will have solid changes, in reality though if 100hp is what saves you from an engagement and not the -.1 speed the caste lost. Then honestly you've already fucked up in some way in your game plan and how you've dictated your engagement. The loss of speed is more impactful overtime in a game than the 100 health you've seem to applied universally.

I have not felt this to be true from seeing actual gameplay, xenos now can take way more engagements that were simply impossible for them to do and get out alive before.

**Comment by Kuro020** [comment]
> Should reduce xeno speed a lot more if you want to do cmification, if they're gonna hit harder and tank more they might as well move slower.
> 

Damage buffs were only drastic on the T4s, because they barely dealt damage to begin with (considering you know, that they're limited roles and are also the most important ones)

> Although if I am being honest, old damage values were more sane for various reasons like RNG organ damage, delimbing thresholds, etc. You could start with tankiness though, because the longer you can face tank, the more damage you can do.

Rng organ damage is its own issue, and at any rate, the rng chance iirc doesnt scale with damage, as soon as you deal 10 damage you start rolling for it, most of the xenos that received a damage buff were already rolling for that before said buff.

**Comment by Kuro020** [comment]
> > Yeah, even though i really like the buffs, this will not improve xenos a whole lot, it feels nice to not get oneshot by tank with no counter but this doesn´t solve any problems xenos have at all, and i still think marines are stronger but w/e. My point is that this is just another bandaid over xenos having near to no content
> 
> Problem to me is that no matter what xenos have no variety in options. Just buffing stats overall at the cost of barely noticeable speed reduction won't do much with that.

I can go and add 50 castes, 100 strains, 200 buildings, and none of that will change.
Everything that is added is balanced around things that already exist, xenos right now are simply put, weak, and anything that is added to them will be balanced around that and will in turn also be weak, we need to raise the baseline strenght of xenos before any additions make an actual effect, otherwise they'll just end up as another unnused xeno option.

**Comment by SimplySmiley123** [comment]
> > > Yeah, even though i really like the buffs, this will not improve xenos a whole lot, it feels nice to not get oneshot by tank with no counter but this doesn´t solve any problems xenos have at all, and i still think marines are stronger but w/e. My point is that this is just another bandaid over xenos having near to no content
> > 
> > 
> > Problem to me is that no matter what xenos have no variety in options. Just buffing stats overall at the cost of barely noticeable speed reduction won't do much with that.
> 
> I can go and add 50 castes, 100 strains, 200 buildings, and none of that will change. Everything that is added is balanced around things that already exist, xenos right now are simply put, weak, and anything that is added to them will be balanced around that and will in turn also be weak, we need to raise the baseline strenght of xenos before any additions make an actual effect, otherwise they'll just end up as another unnused xeno option.

At the same time this forces very few options on marine side to be able to put up a fight. Why experiment with your options if you're gonna get shat on for doing so even harder then before.

Plus, this just helps xeno stuns be even more fucking annoying to deal with so no matter what, as long as those are in I won't ever agree with these buffs being good.

**Comment by Kuro020** [comment]
> The health increases are excessive across the board. They should probably be reduced by half. They definitely need _something_, but I think this is too much as it stands.

Marines have received in the last few years:
- Storage and regular modules (They didnt exist before, so it was a straight buff, although they were my idea anyway)
- Guns that kill any xeno in one mag (I know because I added most of them, you can check my git history)
- Infinite ammo (I agreed to it and still do, but its a big buff)
- Aim mode (Do I need to say anything about this one?)
- FF reduction (even if you somehow FF someone the damage is reduced by 50%)
- Numerous arty options, emplacements, and cas got better overall (all cool stuff, I dont disagree with any of it)
- Vehicles (I made the balance and initial sprites for them, so obviously I dont disagree with their existence)
And so on and etc etc, infinite pill bottles and I'm sure I can name other stuff.

Meanwhile, xenos got some barely effective stat buffs, barely effective new castes (because they have to be balanced around the other weak xenos), barely effective buildings, and some qol, and are still WEAKER than they were back then, resulting now in a situation where we have had no burrowed rounds again and the winrates were heavily marine skewed in a 10 days timeframe.
These buffs are not even as extreme as I could justify them being, I'm being very moderate here.

**Comment by Kuro020** [comment]
> > > > Yeah, even though i really like the buffs, this will not improve xenos a whole lot, it feels nice to not get oneshot by tank with no counter but this doesn´t solve any problems xenos have at all, and i still think marines are stronger but w/e. My point is that this is just another bandaid over xenos having near to no content
> > > 
> > > 
> > > Problem to me is that no matter what xenos have no variety in options. Just buffing stats overall at the cost of barely noticeable speed reduction won't do much with that.
> > 
> > 
> > I can go and add 50 castes, 100 strains, 200 buildings, and none of that will change. Everything that is added is balanced around things that already exist, xenos right now are simply put, weak, and anything that is added to them will be balanced around that and will in turn also be weak, we need to raise the baseline strenght of xenos before any additions make an actual effect, otherwise they'll just end up as another unnused xeno option.
> 
> At the same time this forces very few options on marine side to be able to put up a fight. Why experiment with your options if you're gonna get shat on for doing so even harder then before.
> 

And what have xenos been playing this whole time? When xeno players are forced to sweat and tryhard for years because of how strong marines are, its not a problem, now that marines need to maybe consider what they're doing instead of brainlessly playing the game, it's a problem?

> Plus, this just helps xeno stuns be even more fucking annoying to deal with so no matter what, as long as those are in I won't ever agree with these buffs being good.


As for xenos being annoying to deal with, what can I say? I apologize that you're not happy with the changes, but this is the only way foward towards making tgmc a less xeno hostile experience.

**Comment by Ephemeralis** [comment]
> > The health increases are excessive across the board. They should probably be reduced by half. They definitely need _something_, but I think this is too much as it stands.
> 
> Marines have received in the last few years:
> 
> * Storage and regular modules (They didnt exist before, so it was a straight buff, although they were my idea anyway)
> * Guns that kill any xeno in one mag (I know because I added most of them, you can check my git history)
> * Infinite ammo (I agreed to it and still do, but its a big buff)
> * Aim mode (Do I need to say anything about this one?)
> * FF reduction (even if you somehow FF someone the damage is reduced by 50%)
> * Numerous arty options, emplacements, and cas got better overall (all cool stuff, I dont disagree with any of it)
> * Vehicles (I made the balance and initial sprites for them, so obviously I dont disagree with their existence)
>   And so on and etc etc, infinite pill bottles and I'm sure I can name other stuff.
> 
> Meanwhile, xenos got some barely effective stat buffs, barely effective new castes (because they have to be balanced around the other weak xenos), barely effective buildings, and some qol, and are still WEAKER than they were back then, resulting now in a situation where we have had no burrowed rounds again and the winrates were heavily marine skewed in a 10 days timeframe. These buffs are not even as extreme as I could justify them being, I'm being very moderate here.

I still think you've missed the mark, and your explanation alone kind of highlights why. You're doing the Bethesda equivalent of balancing by cranking numbers up instead of giving them meaningful new complexity. Flat EHP increases (often well past the realm of 20-30% after armor and the like are considered) are *downward* adjustment on essentially everything else that does damage, and it is really shaking out that way in how bullet-spongy many of the xenos feel post rework. Pocketed runners in particular are an especially prominent example of this.

**Comment by Kuro020** [comment]
> > > The health increases are excessive across the board. They should probably be reduced by half. They definitely need _something_, but I think this is too much as it stands.
> > 
> > 
> > Marines have received in the last few years:
> > 
> > * Storage and regular modules (They didnt exist before, so it was a straight buff, although they were my idea anyway)
> > * Guns that kill any xeno in one mag (I know because I added most of them, you can check my git history)
> > * Infinite ammo (I agreed to it and still do, but its a big buff)
> > * Aim mode (Do I need to say anything about this one?)
> > * FF reduction (even if you somehow FF someone the damage is reduced by 50%)
> > * Numerous arty options, emplacements, and cas got better overall (all cool stuff, I dont disagree with any of it)
> > * Vehicles (I made the balance and initial sprites for them, so obviously I dont disagree with their existence)
> >   And so on and etc etc, infinite pill bottles and I'm sure I can name other stuff.
> > 
> > Meanwhile, xenos got some barely effective stat buffs, barely effective new castes (because they have to be balanced around the other weak xenos), barely effective buildings, and some qol, and are still WEAKER than they were back then, resulting now in a situation where we have had no burrowed rounds again and the winrates were heavily marine skewed in a 10 days timeframe. These buffs are not even as extreme as I could justify them being, I'm being very moderate here.
> 
> I still think you've missed the mark, and your explanation alone kind of highlights why. You're doing the Bethesda equivalent of balancing by cranking numbers up instead of giving them meaningful new complexity. Flat EHP increases (often well past the realm of 20-30% after armor and the like are considered) are _downward_ adjustment on essentially everything else that does damage, and it is really shaking out that way in how bullet-spongy many of the xenos feel post rework. Pocketed runners in particular are an especially prominent example of this.

Read one of the responses above and I say why exactly adding stuff isnt gonna change anything if the baseline xeno strenght isnt improved

**Review by Lumipharon — APPROVED** [review]

**Comment by SimplySmiley123** [comment]
> And what have xenos been playing this whole time? When xeno players are forced to sweat and tryhard for years because of how strong marines are, its not a problem, now that marines need to maybe consider what they're doing instead of brainlessly playing the game, it's a problem?

Yeah, so the solution is apparently _not_ to climb out of the ditch but to drag the other side in? That's how this looks and feels. Unless you have never mentioned before plans on how to make xeno side more varied with this, somehow, without just making the other side's options invalid and a waste of a player.

> As for xenos being annoying to deal with, what can I say? I apologize that you're not happy with the changes, but this is the only way foward towards making tgmc a less xeno hostile experience.

I'm not happy because it genuinely will only make it even more _bullshit_ to go against stun-happy xenos.
It genuinely fucks over a regular player more then the top players.
Hell.
I genuinely wouldn't be as mad over this, if at all, if stuns weren't _Fucking Everywhere_ so easily available and _so_ easy to stunlock someone with. Stat buffs, fair, understandable, xenos, at the core of things, needed those. But it's just gonna make stuns even more annoying to deal with and even easier to dish out to take out the opponent's ability to do anything and I have zero confidence of anyone doing anything about those, especially with the tribalism going on between marines and xeno players.
Hell, before you say it, I do hate them on both sides, they don't belong in a PvP environment.

**Comment by Lefunny** [comment]
> 
> I'm not happy because it genuinely will only make it even more _bullshit_ to go against stun-happy xenos. It genuinely fucks over a regular player more then the top players. Hell. I genuinely wouldn't be as mad over this, if at all, if stuns weren't _Fucking Everywhere_ so easily available and _so_ easy to stunlock someone with. Stat buffs, fair, understandable, xenos, at the core of things, needed those. But it's just gonna make stuns even more annoying to deal with and even easier to dish out to take out the opponent's ability to do anything and I have zero confidence of anyone doing anything about those, especially with the tribalism going on between marines and xeno players. Hell, before you say it, I do hate them on both sides, they don't belong in a PvP environment.

Maybe if xenos weren't so weak they had to stun lock marine for half a hour stuns wouldn't be necessary

**Comment by SimplySmiley123** [comment]
> > I'm not happy because it genuinely will only make it even more _bullshit_ to go against stun-happy xenos. It genuinely fucks over a regular player more then the top players. Hell. I genuinely wouldn't be as mad over this, if at all, if stuns weren't _Fucking Everywhere_ so easily available and _so_ easy to stunlock someone with. Stat buffs, fair, understandable, xenos, at the core of things, needed those. But it's just gonna make stuns even more annoying to deal with and even easier to dish out to take out the opponent's ability to do anything and I have zero confidence of anyone doing anything about those, especially with the tribalism going on between marines and xeno players. Hell, before you say it, I do hate them on both sides, they don't belong in a PvP environment.
> 
> Maybe if xenos weren't so weak they had to stun lock marine for half a hour stuns wouldn't be necessary

Then remove the stuns while buffing xenos.
Do it together.

I have no faith in you lot removing stuns after buffing xenos at all.

**Comment by Arturlang** [comment]
Ravager being slowed down is a huge ravager nerf.

**Comment by Derrick2Electricboogaloo** [comment]
> Oh boy can't wait for the stun-reliant and brazil castes to be uncontested with this and for the game to get even slower for both sides.
> 
> Honestly if you want to buth health and damage across the board, nerf the stuns as well so it's not pure bullshit to go against. Speed doesn't matter as much when xenos have the control over the map and ful lfreedom of movement with x-ray vision to boot.
> 
> Also worth noting is that if this affects Puppeteer, shit's gonna become the meta to delete marines in an instant.

More and more TGMC embraces CMification. Soon enough we might even have capture back. Nature is healing? But seriously, yeah I can not wait to deal with more get of jail free nonsense from the xenos now that they have even more HP and damage protentional.

**Comment by Lefunny** [comment]
> Then remove the stuns while buffing xenos
> I have no faith in you lot removing stuns after buffing xenos at all.

Dumb take stuns are good and necessary, it's unfun for marines to die in 4 slashes which would be the case stuns were removed

**Comment by Lefunny** [comment]
> More and more TGMC embraces CMification. Soon enough we might even have capture back. Nature is healing? But seriously, yeah I can not wait to deal with more get of jail free nonsense from the xenos now that they have even more HP and damage protentional.

Dumb take in general 👍

**Comment by Derrick2Electricboogaloo** [comment]
> > > I'm not happy because it genuinely will only make it even more _bullshit_ to go against stun-happy xenos. It genuinely fucks over a regular player more then the top players. Hell. I genuinely wouldn't be as mad over this, if at all, if stuns weren't _Fucking Everywhere_ so easily available and _so_ easy to stunlock someone with. Stat buffs, fair, understandable, xenos, at the core of things, needed those. But it's just gonna make stuns even more annoying to deal with and even easier to dish out to take out the opponent's ability to do anything and I have zero confidence of anyone doing anything about those, especially with the tribalism going on between marines and xeno players. Hell, before you say it, I do hate them on both sides, they don't belong in a PvP environment.
> > 
> > 
> > Maybe if xenos weren't so weak they had to stun lock marine for half a hour stuns wouldn't be necessary
> 
> Then remove the stuns while buffing xenos. Do it together.
> 
> I have no faith in you lot removing stuns after buffing xenos at all.

Can not have that dopamine hit if the other player can actually fight back instead of just remaining horizontal until dead.

**Comment by SimplySmiley123** [comment]
> > Then remove the stuns while buffing xenos
> > I have no faith in you lot removing stuns after buffing xenos at all.
> 
> Dumb take stuns are good and necessary, it's unfun for marines to die in 4 slashes which would be the case stuns were removed

It's also unfun as fuck to have your ability to play the game and fight back in any capacity taken away at a press of a _single_ button. They take away any agency you may have beyond just, not existing in the area to begin with and waiting for someone else to be the sacrificial lamb.
Add how easy it is for xenos to stunlock the _everliving hell_ out of you all while sending you across the map.
It's even worse now as the xeno has more health to have an even easier time getting their stuns off with damage as a cherry on top.

It's far worse then just getting killed by damage.

Fuck stuns. They are a crutch for dogshit players.
They do not belong in a PvP environment.

**Comment by Lefunny** [comment]
> > > Then remove the stuns while buffing xenos
> > > I have no faith in you lot removing stuns after buffing xenos at all.
> > 
> > 
> > Dumb take stuns are good and necessary, it's unfun for marines to die in 4 slashes which would be the case stuns were removed
> 
> It's also unfun as fuck to have your ability to play the game and fight back in any capacity taken away at a press of a _single_ button. They take away any agency you may have beyond just, not existing in the area to begin with and waiting for someone else to be the sacrificial lamb. Add how easy it is for xenos to stunlock the _everliving hell_ out of you all while sending you across the map. It's even worse now as the xeno has more health to have an even easier time getting their stuns off with damage as a cherry on top.
> 
> It's far worse then just getting killed by damage.
> 
> Fuck stuns. They are a crutch for dogshit players. They do not belong in a PvP environment.

Merged

**Comment by Redrover1760** [comment]
> Though I was anticipating this to be a bandaid fix, I was surprised at how ineffective it felt in practice
> 
> [Example1.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17688334/ebff8d3c-ad5a-4e19-b6de-69500142d9ec) [Example2.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17688334/5ce1eb52-14e0-46d8-a97d-8f602ab3e1c6) [Example3.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/17688334/4b7e32b8-ab32-4e79-896a-a4a5478c1743)
> 
> Now you could argue - Just don't push marine aimballs alone. Which is the problem, big aim balls need cohesion to take down, or more accurately specific castes to be competent. And worse those specfic castes all have counters/mitigations.

To be fair, everyone one of those deaths except the last was a "Don't stand in front of the smartgunner/main line of fire" where there was plenty of cover to fight from where the marines behind couldn't shoot you from as a sentinel, the first was overextension, against a massive front you can't do much but poke at it most of the time if you are more than just a tier 1 due to aim mode and death. The 2nd you could have just stayed south of the 1 tile gap and avoided all the damage, and the 3rd was a good death. Although, your carrier kind of bodyblocked you instead of shuffling with you to tank for you so you could escape for some reason.

**Comment by MiniMeatwad** [comment]
Powercrepe 
firefox_b7iLQjAazT

**Pull request merged**
