### PR TITLE
Standardization of Round Start CAS ammo

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

All shipsides shall spawn with the following:
6 30mm ammo crates
2 banshees
2 keepers
2 widowmakers
4 mini rockets
2 GAU-21 30 mm cannons
2 rocket pods
2 minirocket pods

Update map contribution to ensure that other contributors can read good practices on map PRs.

## Why It's Good For The Game

Theseus is the only shipside map that has the most CAS ammo compare to all shipside maps. It is the most beloved of all the CAS PO since they can boom boom more. This ensures that all CAS PO have the same ammo across shipside maps.

Long time ago, Theseus was made for high pop (whatever that meant). Only Big Bury is the dedicated high pop shipside, and even then Crash game mode doesn't exist after 30+ pop.

Theseus has
6 30mm ammo crates
2 banshees
2 keepers
4 widowmakers
6 mini rockets
2 GAU-21 30 mm cannons
2 rocket pods
2 minirocket pods

Meaning that Theseus is going to bomb the crap out of planetside. This is a nerf to Theseus and a buff to all other maps. You're welcome, CAS PO.

**NO SHIPSIDE SHOULD HAVE MORE OR LESS THAN EACH OTHER!!**

## Changelog
:cl:
balance: All shipsides shall spawn with the following:, 6 30mm ammo crates, 2 banshees, 2 keepers, 2 widowmakers, 4 mini rockets, 2 GAU-21 30 mm cannons, 2 rocket pods, 2 minirocket pods
code: update map contribution page to ensure that other contributors can read good practices on map PRs
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
Theseus pays CAS PO well
image

Poverty in the PoS
image

NO ROCKETS IN SULACO; WHY
image

Mfw Minerva is the second best
image

**Comment by BraveMole** [comment]
Add in map contrib that cas ammo should be standardised

**Comment by mathis650** [comment]
speedmerge

**Comment by Andrewhedge** [comment]
elsa, bringer of cas communism

**Comment by FosterGrime-Heymynameslouie** [comment]
sppedhmehrg

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
