### PR TITLE
Plasma pistol is no longer an attachment, slight buff to compensate

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

See cl

## Why It's Good For The Game

David want PP removed, I do it!

## Changelog
:cl:
balance: Plasma pistol can use masterkey
balance: Shotguns can no longer attach plasma pistol
/:cl:

### CODE REVIEW

**Review by Pariah919 — APPROVED** [review]
yeah, good pr

**Comment by Lumipharon** [comment]
Perfection

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Why remove it off guns that dont have issues with it

**Comment by Naaanii** [comment]
> Why remove it off guns that dont have issues with it

No gun should have it honestly. It serves fine as a weapon on its own imo.

**Comment by Arctrooper8** [comment]
Don't half ass the removal. And if you are just gonna half ass the removal at least get rid of the freaking Masterkey being allowed on a pistol of all things.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
