### PR TITLE
Annihilate 6 chokepoints near Ice Colony's LZ2

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

image

image

## Why It's Good For The Game

Aesthetically, the ships are pretty garbage.

Tactically, you cannot engage them safely since you cannot blow them up.

Mapwise, the empty space looks awful, so I will have map maintainer's help to see what we can do to fill the void. I'm thinking of ice cover.

## Changelog

:cl:
del: two """""ships""""" near LZ2 that are indestructable and make 6 chokepoints.
/:cl:

### CODE REVIEW

**Comment by FIXTHERADBOXPLEASE** [comment]
Salt PR. The (intentional) downside of taking this LZ is that it gives the Xenos a favorable approach to assault the FoB.
If you can't cope with Xenos using the terrain against you, then take the north LZ.

**Comment by Derrick2Electricboogaloo** [comment]
I think the shuttles are fine. Hardly choke points when xenos use them 99.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999% of the time and marines rarely touch that place as if it has AIDS

**Comment by Al-1ce** [comment]
I think the entire area (including the dead-end deathtrap for bald xenos) should be atomized/redesigned.

**Comment by novaepee** [comment]
need to think omre on this

**Pull request closed without merging**
