### PR TITLE
pocket pistol obsfucation removal

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
pp no longer has multipliers

## Why It's Good For The Game
no dumb obsfuation 

## Changelog
:cl:
code: removes pocket pistols multiplier obfuscation
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -331. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SplinterGP** [comment]
remove changlog pls, misleading, also its just code

**Comment by David-Stormwell** [comment]
The PP no longer has multiplers on how long it is...

**Review by TiviPlus — APPROVED** [review]
David was banned for this post 👍

**Pull request merged**
