### PR TITLE
Adds a rainbow flag emoji

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request
🌈 
## Why It's Good For The Game
tgmc has gone woke
## Changelog
:cl:
add: Added the <:rainbow:> emoji
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
gayt

**Comment by Technical-l** [comment]
surely this will only be used in a non derogatory sense

**Comment by Pariah919** [comment]
He's going to rainbow me on sight. Help.

**Comment by TiviPlus** [comment]
Lepi emoji

**Pull request merged**
