### PR TITLE
Decreases the minimum time before you are able to deploy as marine.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Reduces deploy_time_lock from 15 minutes to 5 minutes
## Why It's Good For The Game
After some discussion on the discord, many people have brought up that the high amount of prep time is detrimental to enjoyment. Many people will simply latejoin because it's just not fun to vend your loadout to AFK on Alamo for 20 minutes.

Slimming the minimum time by 10 minutes should help alleviate the situation.

There might be some concerns about balance regarding xeno mazing/evo-ing, but the evo PR + Quick build should make these issues not be a problem.
## Changelog
:cl:
balance: Marines can now deploy 10 minutes sooner
/:cl:

### CODE REVIEW

**Comment by Ldip999** [comment]
10 minutes might be a bit too much, but you are very much onto something

**Comment by 00ze-cyclone** [comment]
I have doubts on the ability of xenos to build decent mazes in 5 minutes even with QB, I don’t want rushing groundside to catch xenos unprepared on an grand open field to become a legitimate strategy.

**Comment by Wisemonster** [comment]
Keep in mind, this is also meant to give xenos time to prep groundside. This not only includes mazing/evoing (evoing being instant during prep, not really a problem now), but also aciding walls/items and slashing apcs. This will give xenos 5 minutes to do what they need before they lose quick build, strong acid (if they don't have it by default), and instant evo.

**Comment by blackdav123** [comment]
make auto-open sooner too so if marines wipe at 12:20 we dont have to wait 13 minutes

**Comment by Barnet2** [comment]
This would be a great PR if not for the amount of time it takes to prep as Xeno and to an extent Corpsman making funny mixes or what not. The former is more of a problem since you need mazes to win - if there were pre-maze map changes then this would be good. You have to melt alot and build alot, not to mention sticky weeding / placing gargoyles / tunneling / hive jelly pods, you get the idea. Prep is way too long but alot of things are built off that and need to be changed.

**Comment by blackdav123** [comment]
with 15 minutes of prep time <5 xenos can usually spend all of the QB points, forcing a few of the hive to do all the work while 10 shitters afk on the silo

lowering this to 5 minutes will force xenos to either all chip in to help maze or get shit on because everyone wants to force the work onto somebody else.

if xenos want to get skill issued for being lazy that is entirely up to them.

**Comment by Looking4bros** [comment]
Mazing is le lame and boring. Rule of cool agrees with this PR, but would also need auto mazing/mazing presets for maps and sheeeeeit.

**Comment by jroinc** [comment]
This is a hard-nerf to every single build except "press button on vendor, auto-equip metaloadout, sprint to dropship".

There are people out there who might like to *not* be forced into a 5-minute metarush by the metaungas. And it will happen Every. Single. Round. once it's possible.

**Comment by Wisemonster** [comment]
Unless there's gonna be a bunch of prs involving pre-mazing all the maps, it'd probably be better to have the prep time be 10 minutes rather than 5.

**Comment by Lumipharon** [comment]
I don't think this change in isolation is a good idea considering the amount of **xeno** prep that happens every round, that is a direct punishment to xenos unless they're all mazing (which they should, but lets be real, doesn't usually happen).

**Comment by SimplySmiley123** [comment]
> This is a hard-nerf to every single build except "press button on vendor, auto-equip metaloadout, sprint to dropship".
> 
> There are people out there who might like to _not_ be forced into a 5-minute metarush by the metaungas. And it will happen Every. Single. Round. once it's possible.

What _do_ they do during wait time tho, make chems? Wait for req points? Have a short (why would you need anything longer then couple minutes is beyond me) briefing then go back to idling around?

**Comment by destrucktoid** [comment]
Why not make it so that during QB phase all xenos can maze rather than only the support castes?

**Comment by xzero314** [comment]
Why not just remove xenos losing their qb entirely. Then marines can early rush if they want and xenos still get to spend their qb. 

This would also be a massive QOL for times when there are only like 2 xenos using the qb and have no chance to use it all effectively.

**Comment by Looking4bros** [comment]
> Why not just remove xenos losing their qb entirely. Then marines can early rush if they want and xenos still get to spend their qb.

:O Gigga brian move, just set xenos to always have QB for the first 15 minutes, and if marines want to fight xenos who have QB and get boxed in they can

**Comment by Ldip999** [comment]
Capture gameplay is back?

**Comment by xzero314** [comment]
> > Why not just remove xenos losing their qb entirely. Then marines can early rush if they want and xenos still get to spend their qb.
> 
> :O Gigga brian move, just set xenos to always have QB for the first 15 minutes, and if marines want to fight xenos who have QB and get boxed in they can
> 
> > Make it so they cant use qb when near marines to prevent insta entombing people
> 
> Oh, i mean i suppose.

honestly like. The idea of not letting them do it near marines I tossed out since when I thought about it getting entombed by 50 walls sounded like it wouldn't be fun but when you put it that way why not

**Comment by XElectricX** [comment]
Should really be lowered to 10 minutes instead, Jroinc does make good points. What really gripes my nuts is the lobby time. THAT is absolutely a waste of time, you just sit there waiting for the arbitrary timer to count down.

>Make it so they cant use qb when near marines to prevent insta entombing people

Issue is this would be bad for performance.

**Comment by TiviPlus** [comment]
> Should really be lowered to 10 minutes instead, Jroinc does make good points. What really gripes my nuts is the lobby time. THAT is absolutely a waste of time, you just sit there waiting for the arbitrary timer to count down.
> 
> > Make it so they cant use qb when near marines to prevent insta entombing people
> 
> Issue is this would be bad for performance.

it probably wouldnt be that bad

**Comment by TiviPlus** [comment]
But yea as shown by the discussion it is this "high" because this is the current bare minimum we can allow for prep, you need to make the actual time some roles spend prepping lower before we open the book on this

**Comment by Ragecrabbo** [comment]
As others have already pointed out this would hurt xeno prep alot. Maps like LV or Big Red have abysmal amount of prebuilt walls and weed nodes and there are certain things outside QB like aciding and placing buildings/acid wells/hugger traps that also take their own time and cant really be made faster.
On marine side while not as impactful this will hurt pretty much any role that is not your average instant vend loadout squaddie with probably RO, vehicle pilots and command being most affected.

**Comment by XElectricX** [comment]
1984. 😞

**Pull request closed without merging**
