### PR TITLE
New Shotgun Seasonal

### PR DESCRIPTION
**Pull request by Otterwatch**
## About The Pull Request
Adds a new seasonal group of shotgun seasonals and gets rid of some shotgun tab bloat.

## Why It's Good For The Game
New seasonals make for more varied gameplay and this was requested by Bravemole.

## Changelog
:cl:
add: Added Paladin and Mk221 to seasonal weapons as an entire new season.
del: Removed Paladin and Mk221 from Shotgun weapon tab in marine vendor.
/:cl:

### CODE REVIEW

**Comment by hyper2snyper** [comment]
> Gives some uniqueness to it

This does nothing of the sort. All you did was add it to seasonal without anything extra.

**Comment by Otterwatch** [comment]
Finally fixed some issues with it and now it might work.

**Review by BraveMole — APPROVED** [review]

**Comment by Lumipharon** [comment]
MK221 has a specific niche of having an grenade launcher attachment. It means you can load it with impact nades and try wombo combo benos with buckstuns or whatever.

**Comment by Arctrooper8** [comment]
Is that paladin really so special that it deserves to go in the seasonal category? I understand moving the Mk221 to seasonal thanks to it's unique UGL attachment. But moving a pretty standard shotgun that is said to be commonplace from an always available weapon to a seasonal just confuses me. This could all just be nostalgia as I have fond memories of the weapon and would be sad to see it go. Overall I simply wish to better understand why such a seemingly standard weapon is moved to seasonal, please and thank you!

**Comment by Otterwatch** [comment]
> Is that paladin really so special that it deserves to go in the seasonal category? 
I believe being able to hold around 10 rounds and having a miniscope is fairly special for a shotgun. The db is the only other shotgun that can have a scope and it's the well... db. Both of the seasonal shotguns in this pr have special attachments for their class and were found to be bloat basically by most people when I discussed it. Bravemole said to remove them until someone brought up making them seasonals, so that's what I did.

**Comment by Arctrooper8** [comment]
Ah, that is a good point. Thank you for clarifying. And I much prefer them being seasonally available  then removed.

**Pull request merged**
