### PR TITLE
Medbay layout change

### PR DESCRIPTION
**Pull request by TobiNerd**
[Changelogs]: # 
🆑 TobiNerd
tweak: Cryotubes right next to surgery
tweak: Locker Room merged with storage, and can be accessed directly from the surgical hallway hallway
tweak: Lounge moved to where locker room used to be
tweak: Surgical hallway made wider for less bumping
tweak: Moved around a few other items on tables and such to match the new layout better
del: Removed two blood dispensers and two medplus vendors in hallway as direct access to storage makes them obsolete.
/🆑

[why]: # 
No reason to have locker room and storage separate. Merging them and having access directly from surgery should create better flow. 

Moving the cryotubes, is because they can easily be operated by a doctor performing triage. And that critically wounded is often dragged directly into surgery anyway. Most doctors tend to be too lazy to drag them to the cryotubes because they're far away.

### CODE REVIEW

**Comment by TobiNerd** [comment]
Looks little bleh because I accidentally put the map in the wrong folder first. Not used to github, barely used it. Forgive me.

**Comment by Hughgent** [comment]
in your CL, change "Change to medbay layout" to your name, or the name you want to use.

**Comment by Alterist** [comment]
`aeu" = (/obj/structure/closet/secure_closet/bar{name = "Success Cabinet"; req_access = null; req_access_txt = "1"},/turf/open/floor/wood,/area/almayer/living/commandbunks)`
this will need to be resolved

**Comment by TobiNerd** [comment]
Thank you, I'll fix them when I'm home in 6 ish hours

**Comment by TobiNerd** [comment]
God damn rebasing. I'll start over with a new PR

**Pull request closed without merging**
