### PR TITLE
Terran Dairies (used to be Uncle Amos)

### PR DESCRIPTION
**Pull request by SomrNetwork**
## About The Pull Request
Adds a new dairy drink to food vendors, death to the berry bars
## Why It's Good For The Game
Nicotine infused milk cream, smoke-free alternative for smokers all around TGMC
## Changelog
🆑 
add: Terran Dairies to food vendor
imageadd: terran_dairies
/ 🆑 
image

### CODE REVIEW

**Comment by Oscari-pog** [comment]
marlboro milk

**Comment by aarrisu** [comment]
fix it

**Comment by TiviPlus** [comment]
Checking for space indentation
code/game/objects/machinery/vending/vending_types.dm:118: 		/obj/item/reagent_containers/food/drinks/bottle/terran_dairies = -1,
space indentation detected
Checking for mixed indentation

**Comment by Barnet2** [comment]
I would take great care in the naming of this. Never forget https://github.com/tgstation/TerraGov-Marine-Corps/pull/7166

**Review by TiviPlus — APPROVED** [review]

**Pull request closed without merging**
