### PR TITLE
Boiler Globs are Poppable

### PR DESCRIPTION
**Pull request by SiegeB0t**
## About The Pull Request
Since the [smokening](https://github.com/tgstation/TerraGov-Marine-Corps/pull/12735) made gas behave like gas. Lets make boiler globs behave like balloons which can be popped with bullets. Now marines and sentries can be proactive against boiler spam. For balance, globs have been slowed and fire rate is improved by 5 seconds.

https://user-images.githubusercontent.com/108781465/235625389-dd3ce4eb-ff1b-45f3-ac74-8c66b31a87a2.mp4
## Why It's Good For The Game

Many players lamented the loss of smoke denial actions using smoke grenades. The only counters available now are hitting boiler globs with your face or using Mimir. Now a marine force that wants to decrease the pressure from boilers can try to pop the globs prematurely allowing for more natural counter play. Now, fob does not have to be covered in acid permanently during siege.
## Changelog
:cl:
add: Boiler smoke bombs can be shot and popped prematurely.
balance: Boiler glob speed cut in half and cooldown reduced by 5.
balance: Sentries have a chance of shooting down boiler globs.
/:cl:

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
Today, I wanted to make a xeno nearly useless in my 90% stray bullet game.

**Comment by Pariah919** [comment]
This is the type of skill based emergent gameplay PR we require. Good PR.

**Comment by Jalopkomit18** [comment]
When the boiler tries to hit me with that dollar store acid glob

**Comment by maikilangiolo** [comment]
Idk I think the speed reduction is excessive? The globs look easy to pop unless they require direct click. Still, making them slower but not that slow might be better.

**Comment by Lumipharon** [comment]
So one MG shooting in the general direction of a boiler means they can't do anything?

**Comment by Naaanii** [comment]
This is a pretty funny cope PR.

**Comment by FosterGrime-Heymynameslouie** [comment]
RELEAST CHANGE OF ALL SPEED MERHG INSTANTLY

**Comment by DeltaFire15** [comment]
So.. a single marine with any gun can effectively nullify any amount of boiler pressure?
This makes boilers completely useless as a caste in general, and especially at sieging which is supposed to be where they excel.

**Comment by Araulius** [comment]
so where's the pr that Lets me blow up your rockets mid air?

**Comment by MacBlaze1** [comment]
> so where's the pr that Lets me blow up your rockets mid air?

good idea

**Comment by MacBlaze1** [comment]
> But as someone who despises boilers, I have to agree, the speed change is unnecessary.
Seconded

**Comment by Losenis** [comment]
T60 NPC meta soon

**Comment by blackdav123** [comment]
speed up the globs dont slow them down

**Comment by Lumipharon** [comment]
Closed for reasons above, this just completely shuts down boilers.

**Comment by chizzy376** [comment]
> This is a pretty funny cope PR.

Marine nerf PR: "Finally, this change isn't even that detrimental just use something else"
Xeno nerf PR: "Skill issue cope cope you don't like t3 spam lol lol just use the 900 point dmr lol! You can't hit him because of a t1 soaking all the bullets? refer to first 2 words lol!!"

**Pull request closed without merging**
