### PR TITLE
readds rollettium, makes it gib you

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Reque
rollettium has a recipe again
it now gibs you instead if you fail your rolls, since sutures exist
## Why It's Good For The Game
The ultimate meme, the ultimate ending. Risk it all for the sweet chicken dineer.
## Changelog
:cl:
add: Added rollettium back into the game
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Didn't it always gib?

Also nuggetting might be better to avoid Xeno drain denial like with vests. (They can probably be revived but could make it decap as well)

**Comment by QualityVan** [comment]
roundban

**Comment by FosterGrime-Heymynameslouie** [comment]
ROLL THE DICE 
RISK IT ALL

**Comment by Al-1ce** [comment]
> ROLL THE DICE 
> RISK IT ALL

_Do you enjoy violence? Of course you do. It's a part of you. And who are you, to deny your own nature?_

**Comment by ThelastArchiver** [comment]
whats the recipe ?

**Comment by Strayed-Raven** [comment]
what is the point of roulettium again?

**Comment by Arturlang** [comment]
Keep in mind the chances of gibbing are stupidly high with how often that will run.

**Comment by Xander3359** [comment]
image
Another chem we never never ever see. Great PR

**Comment by Lumipharon** [comment]
image

**Pull request closed without merging**
