### PR TITLE
Port of Discord account link system from SSDiscord on /tg/.

### PR DESCRIPTION
**Pull request by MrStonedOne**
This is just the system to verify a user to a discord account. Relies on a bot made by @optimumtact (https://github.com/optimumtact/orangescogs/tree/master/tgverify)

I didn't port the notify system because tgmc has another system in place for that.

This is mostly a port of https://github.com/tgstation/tgstation/pull/53289

I haven't tested any of this because I need to look into setting up a copy of the cogbot orange's runs to test with.

## Changelog
:cl:
add: Added system for linking discord accounts to the OOC tab.
/:cl:

(As an aside, does tgmc have a ooc tab? should that go somewhere else?)

### CODE REVIEW

**Comment by SplinterGP** [comment]
We have OOC tab yes

**Comment by optimumtact** [comment]
fyi to properly install the cogs you need to manually install tgcommon as an egg dependency in the container

`pip install -e git+https://github.com/optimumtact/orangescogs#egg=tgcommon`

I have not got around to splitting it out into it's own repo and declaring it as a proper dependency of the cogs yet

**Comment by SplinterGP** [comment]
why are you marking stale on a draft, unga bot

**Comment by optimumtact** [comment]
@MrStonedOne you want me to finish this lol

**Pull request closed without merging**
