### PR TITLE
just connects xenohalla and marine valhalla together

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
why the fuck not? I'm too lazy to map out a proper solution and I need to test shit

"But what if someone-" Then ban them! I dont care!
## Why It's Good For The Game
yippe combo-valhalla!
## Changelog
:cl:
add: Connects Marine valhalla and Xeno valhalla
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
> Connecting Xeno and Marine Valhalla is a good idea but it needs safeguards so the players just messing around aren't relentlessly killed while testing gear. I don't see "the admins will ban them" as a valid solution to this problem, admins shouldn't have to babysit Valhalla (more than usual) in addition to their other duties.

There's nothing specific a xeno can do to grief marine valhalla you can't also do by just spawning in as a marine and going ham with grenades. I don't think this will make a problem of getting people killed while testing any more of an issue.

Likewise although there's nothing stopping marines from running into xenohalla and setting up a billion sentries or whatever, there's also nothing stopping them from griefing marine valhalla in a similar manner. I don't think it'll make a difference and for the rare few who will try to dick with xenos, I think you can just ban them

**Comment by FosterGrime-Heymynameslouie** [comment]
wouldnt a button that teleports both into an arena be alot better

**Comment by yyzsong** [comment]
> wouldnt a button that teleports both into an arena be alot better
> 
> edit: just realized that arena already exists, eord

if a coder wanted to code a solution, they would have coded a solution by now

all that's left is me and my dogshit mapping skills

**Comment by ivanmixo** [comment]
> > wouldnt a button that teleports both into an arena be alot better
> > edit: just realized that arena already exists, eord
> 
> if a coder wanted to code a solution, they would have coded a solution by now
> 
> all that's left is me and my dogshit mapping skills

lol

**Comment by Arturlang** [comment]
The proper way to do this is to just put things like fog but for both sides, with a central area that both can access, the fog will block anyone going into the gearing up areas where people can test in peace, while there is a middle area where both can mignle

**Comment by chizzy376** [comment]
> edit: just realized that arena already exists, eord

but it doesn't?

**Pull request closed without merging**
