### PR TITLE
Reworks xeno pheromones

### PR DESCRIPTION
**Pull request by psykzz**
## About The Pull Request

This removes pheromones from most xenos.
Now only Queen, Shrike, Prae, Crusher, Ravager, and Hivemind get pheromones. They also last only 10 seconds with a 60 seconds cooldown between activation. (plasma cost is negligable).

I also removed the idea of leader pheromones. Leaders can still be selected but wont emit your pheromones.

## Why It's Good For The Game

This reworks the idea of having pheromones on the entire round and forgetting about them, turning them instead into on-use abilities that can help with surviving an attack or during a push.

## Changelog
:cl:
tweak: pheromones are only available on Queen, Shrike, Prae, Crusher, Ravager, and Hivemind 
balance: pheromones have been buffed (most start from 4 and goto 5 at ancient)
balance: pheromones only last 10 seconds, with a 60 second cooldown
balance: buffed normal xeno resting regeneration (1.1 -> 2)
/:cl:

### CODE REVIEW

**Comment by drawsstuff** [comment]
what is it with all these shit takes on pheromones

**Comment by AdamElTablawy** [comment]
terrible idea

**Comment by spookydonut** [comment]
just remove leaders tbh this just makes them vanity BIG TEXT

**Comment by XElectricX** [comment]
May as well just take a bat and beat the support castes to death.

**Pull request closed without merging**
