### PR TITLE
Stun changes part 3- Runner

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
PART 3-
~~Rouny~~ Runner

NERFS
Pounce delay from 6 to 13

Compensation (If any)
Runner gets more health overall, caps at 240, runner overall didn't need anything other than this. And honestly this nerf should've happened a long time ago.

## Why It's Good For The Game
Stuns are bad. Death to stuns.
Runner specifically has probably needed a minor nerf and after headbites I think its fair to nerf its 1v1 minorly.

## Changelog
:cl:
balance: runner pounce delay made 13 rather than 6, and runner hp buffed up to capping at 240.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by MiniMeatwad** [comment]
amm

**Comment by Surrealaser** [comment]
This caste needs a nerf like good people need a bullet in their head, that is to say, not at all.

**Comment by MLGTASTICa** [comment]
Runner doesnt really need a stun nerf . Its short and its a very risk for them to do it.

**Comment by Pariah919** [comment]
> Surrealaser commented 7 hours ago
This caste needs a nerf like good people need a bullet in their head, that is to say, not at all.
>
good thing you're giving it evasion huh

**Comment by Surrealaser** [comment]
> > Surrealaser commented 7 hours ago
> > This caste needs a nerf like good people need a bullet in their head, that is to say, not at all.
> 
> good thing you're giving it evasion huh

That's not going to adequately compensate for this. At a minimum you should seriously start looking into applying larger stacks of soft CC (like stagger and slow) in lieu of hard CC.

My take away is that you're doing this primarily because of Headbites, or are at least using this as a justification for such changes, and the fact is that Headbites needs another kind of cure entirely.

**Comment by Walarks** [comment]
I think pounce will be better with a shorter stun than increased cooldown as this still makes it impact people less while not taking away from the xeno's fast and cooperative playstyle.

**Comment by TiviPlus** [comment]
Decrease the stun from getting pounced instead

**Review by Hughgent — APPROVED** [review]
Variable changes

**Comment by Hughgent** [comment]
```
Commander TGMC BOT
11/24/2020
REPO: Updating origin branch...
REPO: Merging PRs #5254, #5257, #5263, #5267, #5223, #5235...
```
```
DuccBot BOT
Today at 7:29 PM
TGMC Statbus
Winrate (Xenomorph to Marine)
64.52%
View Raw
http://statbus.psykzz.com:8080/api/winrate?delta=3
```
Reasonable balance

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-97). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
