### PR TITLE
nerfs ballistic/acid barricade armor upgrade and  nerfs plasteel hp by 100

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
nerfs plasteel cade hp by 100, nerfs reinforced cade armor by 20, nerfs acid upgrade by 10

## Why It's Good For The Game
fobs sieges last a long time, this should make them last a bit less longer

## Changelog
:cl:
tweak: renamed the ballistic armor upgrade for cades to reinforced
balance: nerfed plasteel cade hp by 100, nerfed reinforced armor upgrade for metal cades to 30 melee, nerfed acid by 10 to 20
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -67. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by MLGTASTICa** [comment]
unnecesarry . The only reason fob sieges take long is because either xenos don;t have a crusher/boiler or because marines are being fob-camped round start . Nerfing cades is not really the way to fix the issue since plasteel and metal are already very limited round-start for engineers, but to give a reason for marines to go out of the FOB other than miners.

**Comment by Guidesu** [comment]
I totally agree.
Maybe you should not remove that amount of HP from the plasteel barricade

**Comment by Knuff-les** [comment]
yes, instead of waiting 30 minutes for the FOB camp meta to work, lets just cut it down to 10. why play on these huge maps when we can just scrim over the pillar of thesus at the sulaco ad nauseum. groundside is overrated anyway

**Review by Hughgent — APPROVED** [review]
variable changes

**Comment by BeloneX** [comment]
If you don't want FOB sieges every round then get the Xenos to stop building a massive Führerbunker outside of the FOB every round.

**Comment by adamkad1** [comment]
Sounds like crushers are gonna breach fobs in no time now

**Comment by Hughgent** [comment]
```
Commander TGMC BOT
11/24/2020
REPO: Updating origin branch...
REPO: Merging PRs #5254, #5257, #5263, #5267, #5223, #5235...
```
```
DuccBot BOT
Today at 7:29 PM
TGMC Statbus
Winrate (Xenomorph to Marine)
64.52%
View Raw
http://statbus.psykzz.com:8080/api/winrate?delta=3
```
Reasonable balance

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-105). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
