### PR TITLE
Xenos Have Transvitox Instead of Neurotoxin Spit Now

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

1. Xenos have Transvitox spit instead of Neurotoxin Spit.

2. Transvitox: Each tick converts 0.25 * the number of cycles this toxin has been in the victim's body * 2x for each other Defiler chem in the victim's system burn damage to toxin.

3. Whenever its victim takes brute damage, Transvitox deals extra toxin damage to it if its current toxin doesn't exceed 180 toxin, equal to 10% of the damage dealt up to a maximum of 180 tox damage. This extra damage is doubled for each other Defiler chem in the victim's system.

4. Improves xeno chem display; xenos can now clearly see which chems humans are afflicted with; green for Transvitox, orange for Neurotoxin and blue for Hemodile.

## Why It's Good For The Game

Replaces neuro spam with a support toxin that isn't nearly as oppressive, yet still has significant synergies.

Improves toxin HUD feedback for xenos.

## Changelog
:cl:
balance: Neurospit replaced with transvitox spit.
balance: Transvitox reworked: it now converts only burn damage to toxin, and whenever its victim takes brute damage, Transvitox deals extra toxin damage to it equal to a % of this damage. Toxin damage inflicted/converted in this way is capped at 180.
code: Xeno HUD toxin feedback improved.
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
Dont see much the point of this honestly

**Comment by Surrealaser** [comment]
> Dont see much the point of this honestly

Your complaint was that neurotoxin was annoying and unfun to fight against relative to its abundance and ease of delivery, and overwhelmingly because of purging as you feel entitled to pre-meds.

So I thought to replace the effect with one that is much less oppressive to marines, but still provides valuable support; that is the point.

**Comment by Smudged** [comment]
Honestly I would rather have this buff soley for the defiler, since much of the feedback of Transvitox is it just heals brute damage.

It cheapens the defiler's transvitox ability when you give this to something that's not exclusively the defiler and may create MORE problems if not tested on Defiler first.  Many of the other neurotoxin reworks currently up are better since everybody (And partly myself included) believe the purging effect is the worst part and should be relagated strictly to melee abilities, or Defiler Neurogas or his reagent claws.

I would rather see one of those reworks in before completly changing neurospit to another chem, but I would like to see this "buff" for transvitox for defilers.

**Comment by Surrealaser** [comment]
> Honestly I would rather have this buff soley for the defiler, since much of the feedback of Transvitox is it just heals brute damage.
> 
> It cheapens the defiler's transvitox ability when you give this to something that's not exclusively the defiler and may create MORE problems if not tested on Defiler first. Many of the other neurotoxin reworks currently up are better since everybody (And partly myself included) believe the purging effect is the worst part and should be relagated strictly to melee abilities, or Defiler Neurogas and his reagent claws.
> 
> I would rather see one of those reworks in before completly changing neurospit to another chem, but I would like to see this "buff" for transvitox for defilers.

1: A stronger version of this transvitox has already been tested on the Defiler PR.

2: All of the nerf proposals I've seen thus far have either been hopelessly unconvoluted, unpopular, excessive, or all three.

3: Transvitox on spit 'cheapens' transvitox as much as neuro on spit 'cheapened' neurotoxin on it, which is to say not at all. Also your understanding of what Transvitox does (heals brute damage) is completely and totally wrong per this PR.

4: The only problem with the purging effect, if any, is that neurotoxin is too readily available due to its inclusion in spitting, not because of the neurosting which is uncomfortable to land as a sentinel and has a notable cooldown, or because of T3 exclusive access to it otherwise. Obviously changing the toxin the spits apply to Transvitox fixes this. Beyond that, no one is entitled to premeds, nor did we balance the game around premedding as a rule; xenos should have a counter to this. Further, the biggest issue with purging by far is the potential for traumatic shock to apply insanely long stuns, including at random due to painkiller depletion. I've a separate PR to address this problem here: https://github.com/tgstation/TerraGov-Marine-Corps/pull/6227

**Comment by Tennessee116** [comment]
This seems like the best solution, however I still think neurotoxin should be renamed.

**Comment by Pinkufeck** [comment]
i think this is a good change but shouldn't be applied to all castes able to spit neurotox

**Comment by SplinterGP** [comment]
> 
> 
> > Dont see much the point of this honestly
> 
> Your complaint was that neurotoxin was annoying and unfun to fight against relative to its abundance and ease of delivery, and overwhelmingly because of purging as you feel entitled to pre-meds.
> 
> So I thought to replace the effect with one that is much less oppressive to marines and doesn't chem purge, but still provides valuable support and synergies; that is the point.

reason why i don't like neurotox being promptly easy and abundant delivery its because its easily and abundantly delivered, spits feels like they spit too much neurotox and stuff, rather than just a low amount so you can keep spitting if you wanna make effect, don't see how just injecting alot of transvitox is any different, also thats pretty much a defiler exclusive chem.

**Comment by Surrealaser** [comment]
> > > Dont see much the point of this honestly
> > 
> > 
> > Your complaint was that neurotoxin was annoying and unfun to fight against relative to its abundance and ease of delivery, and overwhelmingly because of purging as you feel entitled to pre-meds.
> > So I thought to replace the effect with one that is much less oppressive to marines and doesn't chem purge, but still provides valuable support and synergies; that is the point.
> 
> reason why i don't like neurotox being promptly easy and abundant delivery its because its easily and abundantly delivered, spits feels like they spit too much neurotox and stuff, rather than just a low amount so you can keep spitting if you wanna make effect, don't see how just injecting alot of transvitox is any different, also thats pretty much a defiler exclusive chem.

Obviously transvitox is very different to the very different and less impositional effect of transvitox.

**Comment by Surrealaser** [comment]
> i think this is a good change but shouldn't be applied to all castes able to spit neurotox

Considering letting praes continue to spit neurotox since they're T3s.

**Comment by Smudged** [comment]
> > i think this is a good change but shouldn't be applied to all castes able to spit neurotox
> 
> Considering letting praes continue to spit neurotox since they're T3s.

I would say, I think this is a bad idea, the main sentiment being that purge on a ranged ability is bad, and putting it on one of the strongest t3's is not gonna be good, especially not for defiler who's main way of applying his chems is melee

**Comment by Surrealaser** [comment]
> > > i think this is a good change but shouldn't be applied to all castes able to spit neurotox
> > 
> > 
> > Considering letting praes continue to spit neurotox since they're T3s.
> 
> I would say, I think this is a bad idea, the main sentiment being that purge on a ranged ability is bad, and putting it on one of the strongest t3's is not gonna be good, especially not for defiler who's main way of applying his chems is melee

The real problem with neuro on spit is commonality; Praes aren't common, and the Defiler has a bunch of other strong traits going for it.

I haven't made up my mind on this though; interested in seeing how Transvitox pans out first.

**Comment by SplinterGP** [comment]
I honestly dont feel much like this one, neurotoxin spit is okayish and is just overally annoying sometimes and is actually pretty okay as it has a support role of making marines slower and all and at some point causes damage, meanwhile that one converts burn to toxin and adds +10% damage from brute, basically buffing every source of brute damage on the marine by 10% and then making it 20% if you reach close to the marine to inject the neurotox with sting(which it still has and injects neurotox) i'm honestly not sure if making xeno chems synergize with each other apart from its already normal effects due to it incetivizing types of xeno spamming, as it makes using defiler together with a sentinel veery veery strong.

**Comment by Surrealaser** [comment]
> I honestly dont feel much like this one, neurotoxin spit is okayish and is just overally annoying sometimes and is actually pretty okay as it has a support role of making marines slower and all and at some point causes damage, meanwhile that one converts burn to toxin and adds +10% damage from brute, basically buffing every source of brute damage on the marine by 10% and then making it 20% if you reach close to the marine to inject the neurotox with sting(which it still has and injects neurotox) i'm honestly not sure if making xeno chems synergize with each other apart from its already normal effects due to it incetivizing types of xeno spamming, as it makes using defiler together with a sentinel veery veery strong.

Xenos are built on inter-caste synergies, and frankly I don't think a fleeting +20% slash damage with the involvement of T3 or a risky Sentinel dive combo is particularly egregious, and frankly is kind of weak sauce compared to a lot of synergies that already exist.

**Comment by TiviPlus** [comment]
Neurotox is fine now

**Pull request closed without merging**
