### PR TITLE
Defiler fixes

### PR DESCRIPTION
**Pull request by goose4429**
## About The Pull Request

Makes all xeno toxins actually work in the defiler abilities, as intended, and as in ability description. 
Improves code as well.

- Sanguinal is also counted as xeno tox, even though you are unlikely to get the synergy.
- Transvitox accounts for ozy as well.
- Sanguinal has its effects **unchanged** in PR, as if ozy was not a thing.

## Why It's Good For The Game

Fix good. Code improve good.

## Changelog
:cl:
fix: Fixed defiler toxins sometimes not counting in synergies
refactor: Refactored xeno toxins code
/:cl:

### CODE REVIEW

**Comment by shelteredfreak** [comment]
speed merge now? (this comment was originally a rant about how useless neuro and oze are, but I sacrificed that to just say I hope this gets merged fast)

**Comment by goose4429** [comment]
> speed merge now? (this comment was originally a rant about how useless neuro and oze are, but I sacrificed that to just say I hope this gets merged fast)

They ARE useless. Sadly, unlikely to be changed in near future here - but on RU we're already working on it. Jump in in few weeks to check ;)

**Comment by Araulius** [comment]
> > speed merge now? (this comment was originally a rant about how useless neuro and oze are, but I sacrificed that to just say I hope this gets merged fast)
> 
> They ARE useless. Sadly, unlikely to be changed in near future here - but on RU we're already working on it. Jump in in few weeks to check ;)

yeah but i can't speak english there without bwoink. but good on you for developing your own code branch

**Comment by MisterGrimm** [comment]
Imagine speed merging a fix full of bugs related to Sanguinal. Sanguinal was never meant to be a standard reagent to be picked, it has no gas. and is significantly stronger then the other xeno chems.

**Pull request merged**
