### PR TITLE
revolver are bulky

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
revolver bulky

## Why It's Good For The Game
hmm 60 revolvers in my bag

## Changelog
:cl:
balance: revolvers are bulky
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -331. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Knuff-les** [comment]
I've seen this episode before #5147

**Comment by bowlofcereal** [comment]
ocelot nerf

**Comment by SilencedMP5A5** [comment]
ocelot nerf

**Comment by Sparrowbird611** [comment]
Why wouldn't you just reduce their rate of fire or something? You can still carry like five revolvers without this and plenty of ammo/support items to go with it if you set up right.

**Comment by TiviPlus** [comment]
Make the delay proper instead

**Pull request closed without merging**
