### PR TITLE
Martini Rework MK.IV - Revenge of the Tea

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Reworks Martini from a meme with no purpose beyond FF and triple juggle memes to something resembling a gun with a gimmick
- Ammo no longer has minimum range
- Sundering and staggerstun are entirely removed from the ammo.
- It now does 10 seconds of Shatter on hit.
- It now has aim mode, with an incredibly fast aiming time.
## Why It's Good For The Game
Martini now has some level of niche in the marine arsenal, it breaks through a large chunk of armor to allow teammates to follow up.
I removed the minimum range since it doesn't really feel like it fits here.
## Changelog
:cl:
balance: Martini rework, no longer has staggerstun nor minimum range. It now deals the shattering effect on hit instead.
/:cl:

### CODE REVIEW

**Comment by Mrrpip** [comment]
God save the Queen.

Also, do we get red coats or not...?

**Comment by Lumipharon** [comment]
Light railgun

**Comment by Barnet2** [comment]
Aim mode on this should have insane slowdown for firing line LARP

**Comment by Al-1ce** [comment]
Hard agree above. Slowdown should compensate.

**Comment by ClosetedSkeletonGH** [comment]
it being able to be fired with one hand also should probably be removed

**Review by ivanmixo — APPROVED** [review]
Probably fine tbh considering martini has barely any niche right now over slugs. Duration might be a bit long but it is just martini.

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Actually a bit concerned about how fast the aiming time is. Considering you can take off 20 armor for 10 seconds it should definitely not be that fast to IFF.

**Pull request merged**
