### PR TITLE
Adds a knee mortar

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
50mm knee mortar
Only has HE (1 heavy, 4 light)
5 minimum range
The mortar itself is normal sized, the ammo is tiny
150|5 points for mortar/shells (15|.5 under old system)

I have only placeholder sprites so the PR isn't going through yet

PASS 1
Added a 4 second cooldown inbetween shots, made shell speed slower. Should be less spammable now.
## Why It's Good For The Game
Its a cool and unique piece of artillery that I think will spice up gameplay
## Changelog
:cl:
add: Added new marine knee mortar- The TA-10.
/:cl:

### CODE REVIEW

**Comment by Tailiik** [comment]
Marines are already super good at turtling, having backpack sized artillery is lame

**Comment by Aporhtonoma** [comment]
no more offscreen bombardments for the love

**Comment by Coastfront** [comment]
Howitzer
CAS
Orbital bombardment
Mortar
Railgun

And so as the wicked forces, as uninteractive as a brick wall shield ever encroaching upon a weakened defense conspired, xeno mains wept as morning dew rolling from every tree leaf, only to be met by the bitter end of the ground, for somebody made another off-screen bombardment artillery mechanic.

**Review by Kuro020 — APPROVED** [review]
Approving this for TMC purposes, dont merge till a proper sprite is added

**Comment by Windryn** [comment]
This should be added, purely for the reason that MJP is voicing all the sounds.

**Comment by Lumipharon** [comment]
More smelly arty

**Comment by ClosetedSkeletonGH** [comment]
Marines don't need more intangible arty, just went against this for the first time, haven't used it yet, but the rate it was spammed was annoying af. Combined with mortar and CAS, this is not needed. Either make this replace a form of Fire Support, or do not add it

**Comment by Al-1ce** [comment]
This has <sub> (almost) </sub> all of the advantages of a regular mortar without any of the downsides. I think it's downright filthy balance wise but the concept is really cool, so +1 from me.

**Comment by Derpguy3** [comment]
Rangefinders are hard to get if you're not an engineer, can you let the mortar belt hold binoculars as well?

**Comment by Pariah919** [comment]
the end

**Pull request closed without merging**
