### PR TITLE
You can vote for civil war now

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Title. Need a config change.

I didn't test this

## Why It's Good For The Game

Gamemode almost ready, don't need admin intervention

## Changelog
:cl:
config: You can vote for civil war now
/:cl:

### CODE REVIEW

**Comment by mathis650** [comment]
yes

**Comment by SplinterGP** [comment]
Requires a bit of discussion considering this gamemode excludes xenos completely from the game.

**Comment by Wayland-Smithy** [comment]
Just delete all xenos when? Starting with bull.

**Comment by turnop** [comment]
CIVIL WAR, SLAUGHTER THE LOYALISTS

**Review by TiviPlus — APPROVED** [review]
david said yea

**Pull request merged**
