### PR TITLE
Areas with FOB shutters can no longer be weeded with closed shutters

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Helps with stopping FOBcamp?
Some areas may need to be amended but we'll see

## Changelog
:cl:
balance: Areas with FOB shutters can no longer be weeded with closed shutters
/:cl:

### CODE REVIEW

**Comment by neohenry** [comment]
Imagine if you use purple smoke to visualize where xenos can't weed outside the FOB. Maybe in lore, marines prepare their drop by sending purple smoke to make sure they don't get jump in the drop.

**Review by Hughgent — APPROVED** [review]

**Comment by jroinc** [comment]
This prevents weeding half of ice colony.

Including several miner zones in the north.

**Comment by MiniMeatwad** [comment]
Replace it with not being able to secrete resin near shutters

**Comment by adamkad1** [comment]
This seems to include most areas around miners. why.

**Pull request merged**
