### PR TITLE
[DNM] [April Fools] Larva primo

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
At ancient larva get the ability to bite things and gain maturity whenever they successfully bite a human.
At primordial larva get the ability to bite really, really hard.
## Why It's Good For The Game
danger noodle
## Changelog
:cl:
add: Tier 0 primordial unlock can be bought in the hive blessing menu
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
PRIMORDIAL
TIER
ZERO

**Comment by Alexeivichi** [comment]
"Do not Merge"
WRONG, SPEEDMERGE!

**Comment by QualityVan** [comment]
larva gaming is now over

**Comment by Aporhtonoma** [comment]
I will miss you lore accurate pasta worm :<

**Pull request closed without merging**
