### PR TITLE
Nerfs Incendiary Options for Marines

### PR DESCRIPTION
**Pull request by Max-023**
## About The Pull Request

This PR removes the incendiary slug box from req options, the heat mode from available options for the TX-73, and the incendiary mags option from req in distress, as well as ups the price from incendiary and HE mortar ammo from 3 to 10.

## Why It's Good For The Game

Right now the Marines are very oppressive when ganging up and can employ several incredibly effective options against the xenos to force them to disengage, allowing the Marines to lock the xenos in a constant state of retreat. The incendiary ammo for the DMR and the heat mode for the PFC lasgun are two especially prevalent due to how easy it is to obtain them. The two guns work fine with their other modules and ammo. The DMR does have a high damage, high AP shot that already is supposed to make xenos get to cover, and the TX has a multitude of modes, making it the end all be all for energy weaponry (even if it sacrifices balance).

As for the mortar price increases, right now it is incredibly easy to get ammunition for mortars and when the main meta for Marines is to rush until they need to recover, the mortar alone can help keep the xenos from pressing a counter attack. There hasn't been a round where ammo has been in short supply for very long so this should help counter mortar spam and disincentivize the idea of running multiple mortars at once. 

## Changelog
:cl: Guprei
del: Removes incendiary slugs from purchasable ammo
del: Removes incendiary ammo for DMRs in req vendors for distress
balance: Removes the heat ability from the TX
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
Removing heat lens from the lasgun doesn't make much sense, as you're trading effective use of the gun in combat for the ability to put a bean on fire, yet again. It's pheromone removal for loss of damage in the main part of the teamfight, the fumble requires you to stand still, and using it puts you on fire delay of 2 seconds.
Nobody uses incin slugs. Literally nobody. They're awful on paper and in practice.
DMR incin itself trades half it's damage for pheromone removal and it's laundering that can do nothing if you have no pheromones? Afterburn itself doesn't deal as much damage as a normal DMR shot. If your complaint is that there's too much of it just make it have 15 shots rather than 20.

Pheromones in and of themselves should either just be removed and added to base xeno values at some pre-determined pheromone value and replaced with some other mechanic, or work like orders for marines do.
Afterburn doesn't do enough consistent damage to be useful, as you usually trade damage for it in most cases.

>does PR to nerf incin options
>nerfs the mortar for reasons in the same PR???
>
The mortar itself fires per shell, not per box. You're pretty much removing the mortar from being a useable tool at 10 per shell, the mortar itself also requires 2 people to man it effectively on defense, and also doesn't deal enough consistent damage to be anything but a deterrence. 

This entire PR reeks of "I ded".

**Comment by Max-023** [comment]
It isn't so much pheroes that is concerning, it is the fact that fire stacks very quickly and so if you don't move back, you are just going to get a lot of snowballed damage. Additionally, if hit with enough, you will literally create light and end up screwing over your fellow xenos by exposing them. Not to mention to the T1 castes, you aren't trading that much damage considering they already have a lower health pool than the rest. It overall just sucks ass and the only real way to avoid it is to intentionally expose yourself and can get you killed, even if you win the fight.

Additionally, the DMR doesn't trade that much damage for burn, so it isn't like going the incen ammo is a straight downgrade by any means. 1 shot can cripple a runner's push.

As for the mortar ammo, making them more expensive is the point? I don't care if you need 2 dudes to make it functional on the frontlines, the reason why it is oppressive is because it forces the xenos to move. It is super easy to set mortars to chokepoints and just bombard them, keeping the xenos out entirely without any risk to it.  The only time a mortar will have any semblance of a downside is if some headass gives the wrong coords.

But of course a player who only knows how to buff Marines and rarely plays xeno will side against a nerf against the Marines.

**Comment by jroinc** [comment]
As much as I like the incendiary mode on the lasgun, he's right. It's too much to have a PFC-grade incin weapon with unlimited free ammo, that is ALSO a decent gun.

Incin DMR rounds are probably fine to stay, as it has issues being used at all ranges and can actually have ammo issues thanks to smol mag amounts and sizes.

I disagree with the amount of the mortar nerf, make it 5 instead of 10? Mortar's a situationally useful tool that requires cooperation to make work.

**Comment by Pariah919** [comment]
T1s on average have 250 health pool, not higher armor pools so they have less EHP. Their health pools in general have been buffed to acceptable numbers. The only real exception to this is runner, who has 225 rather than the average of 250. 
The light from afterburn is inconsistent, it usually doesn't happen unless you have high stacks of fire stacks.
Mortars are usually easy to dodge and forget replant the weeds, and they don't usually break chokepoints by themselves, they require 2 people to run, they're basically long ranged grenades, and like grenades their only use is breaking chokepoints and killing a boiler or two who refuses to move, and also doesn't make sense to even include in this PR?
The DMR incin trades half its damage to effectively function.

The lasgun heat lens doesn't really need to be removed. Incend in general isn't very useful and is usually used to scare benos away rather than actually kill them. And the lasgun in general has bad gun stats to offset the fact it has good option control. The other options such as wide and overcharge are even more situational. 
The light from afterburn is usually only useful in very select cases, such as when you're not running raillight or are running into a bodyblock fiasco for some reason.

**Comment by Kuro-ai** [comment]
the only thing the lasgun has going for it is the incend shot,the other modes are inferior versions of normal guns and you can't change modes on the fly,the DMR incind mag loses 40 damage and all it's AP to have the afterburn and not a single soul uses incendiary slugs
the mortar nerfs are just a ???
on a whole the pr just feels like a salty nerf because I've NEVER seen anyone complain about the lasgun/DMR/Mortar

**Comment by MacBlaze1** [comment]
please stop i-ded nerfing things with a sledgehammer, I dont see why the mortar/dmr are needed

**Comment by Max-023** [comment]
Ah yes the age old argument of 'u r just salty u died' without any confirmation.

I will change the ammo cost to be 6 instead of 10, but the point is to make ammo for the mortar harder to come by. Mortar spam makes it incredibly hard for xenos to gain ground, especially on maps like RO where the xenos are always going to be trying to push through chokepoints. And again, I give 0 fucks about how many dudes a mortar takes. I often see 1 dude manage it fine anyway.

If the incen is your only reason to go the TX, then that is really shitty. The 'situational' trait you are referring to is deathballing, which is extremely common and that is where it is really oppressive. Just remove the gun. The Marines already have a shit ton of options.

Also, Kuro, just because people haven't complained doesn't mean the opinion doesn't exist. There is a shit ton of people who regularly play the server and voice their opinions and never do it in the server or on the git. Saying that it never has been mentioned before means nothing.

As for the smoothbrain trying to say I am stealth nerfing, it is in the fucking changelog and incendiary shells literally count towards 'incendiary options'. Unless you mean I should just copy paste the changelog into the fucking title.

**Comment by XElectricX** [comment]
Fire is a proper counter for benos.

To start off, shells are very hit or miss. The advantage of the incendiaries it to serve as crowd control instead of pure damage.

The incendiary slugs are the only thing I ever saw fit to be added to the pool because they serve their role fine. Slugs that cause fire but have to be bought.

As for the heat lense, I don't know how effective it is as I rarely see it used from both sides. Serves a niche, but if it's too OP just nerf it instead of straight removal.

DMR ammo is the only thing that is retarded to have as incendiary. Free fire damage from long range.

**Comment by MacBlaze1** [comment]
> Ah yes the age old argument of 'u r just salty u died' without any confirmation.
> 
> I will change the ammo cost to be 6 instead of 10, but the point is to make ammo for the mortar harder to come by. Mortar spam makes it incredibly hard for xenos to gain ground, especially on maps like RO where the xenos are always going to be trying to push through chokepoints. And again, I give 0 fucks about how many dudes a mortar takes. I often see 1 dude manage it fine anyway.
> 
> If the incen is your only reason to go the TX, then that is really shitty. The 'situational' trait you are referring to is deathballing, which is extremely common and that is where it is really oppressive. Just remove the gun. The Marines already have a shit ton of options.
> 
> Also, Kuro, just because people haven't complained doesn't mean the opinion doesn't exist. There is a shit ton of people who regularly play the server and voice their opinions and never do it in the server or on the git. Saying that it never has been mentioned before means nothing.
> 
> As for the smoothbrain trying to say I am stealth nerfing, it is in the fucking changelog and incendiary shells literally count towards 'incendiary options'. Unless you mean I should just copy paste the changelog into the fucking title.
>
ARE YOU KIDDING ME, a few days ago on Icy Caves marines had 4 mortars all firing and the xenos still broke through easily. You're literally salt-pr-ing this. Im willing to guess that was the exact round that made you PR this.
>Just because people havent made the opinion exist doesnt mean that it doesnt exist
>
using the silent majority meme isnt a legitimate argument here, because unless they speak up its just you doing this alone. Tell us some names to prove the need of this nerf.
>As for the smoothbrain trying to say I am stealth nerfing, it is in the fucking changelog and incendiary shells literally count towards 'incendiary options'. Unless you mean I should just copy paste the changelog into the fucking title.
>
Namecalling is not okay, and you seem to be getting very angry over the backlash. You want this way too much for it to be reasonable.
> Just remove the gun. The Marines already have a shit ton of options.
>
You want to remove the TX-15. This is a salt pr.

**Comment by psykzz** [comment]
Spoke on discord, since no one agrees with the changes, okay to close.

**Pull request closed without merging**
