### PR TITLE
Adds tracker shells to regular vendors. Tracking fluid now layers over weeds.

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
Cool ammo that's not too game breaking and offers support like tac sensor but with it's own niche mechanic.
## Changelog
:cl:
add: Adds tracker shells to regular weapon vendors.
balance: Tracking fluid now layers over weeds.
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
Always thought they removed these.

**Comment by Oscari-pog** [comment]
This might be so forgotten that it might be worthy to add what they do, because I have no idea

**Comment by maikilangiolo** [comment]
> This might be so forgotten that it might be worthy to add what they do, because I have no idea

It's very simple. They do, essentially, absolutely nothing. Xenos hit by tracker shells leave behind difficult-to-see blue blood spatter, which by the way is rendered under weeds.

**Comment by Mrrpip** [comment]
And....The decals themselves stay for a loooong time.

So you're not going to be tracking much after the first shot in a given area. Not to mention tac sensors are free.

So while...Redundant, it won't break anything.

**Comment by bluezorua** [comment]
the trackers should make xenon visible on the minimal :trollface:

**Comment by Al-1ce** [comment]
These tracker shells are completely outdated and absolutely fucking useless. I don't see this being useful at all if there isn't a complete overhaul to their appearance.

**Comment by novaepee** [comment]
If this gets merged, I will make sure that ALL OTHER WEAPON SYSTEMS IN THE MARINE'S ARSENAL GET TRACKER!!!!

**Comment by Lumipharon** [comment]
This are giga useless. They're cool fluff though I guess, but I unno why you'd want them standard issue.

**Comment by irRegularGuy646** [comment]
glowstick fluid shell

**Comment by Naaanii** [comment]
> These are giga useless. They're cool fluff though I guess, but I unno why you'd want them standard issue.

Would be funny.
I dunno why they should be req helled.

**Comment by Lumipharon** [comment]
Because they're essentially a meme item.

**Pull request merged**
