### PR TITLE
FF is gone[DNM]

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Marines have a bullet armor of 100. That means no bullet damage, but they still block the bullets so it's not full IFF.

It's just a funny test, no merge.

### CODE REVIEW

**Comment by Tupinambis** [comment]
Good thing I still have my trusty high explosives to FF with!

**Comment by Losenis** [comment]
Isn't the 100 affected by ammo penetration?

**Comment by SpaceLoveSs13** [comment]
> Isn't the 100 affected by ammo penetration?

Yes he talked about it, AP still has same affects.

**Comment by BraveMole** [comment]
> Isn't the 100 affected by ammo penetration?

It is. It's not perfect anti-ff system, it's just a test to see if it has potential.

**Comment by usnpeepoo** [comment]
biggest marine buff pr ever do not ever merge this

**Comment by InTroubleWh** [comment]
no, even the TMR is painful *scream

**Comment by Losenis** [comment]
Should probably up the helmet armor too, given nothing modifies it so it stays at 0 and gets damage through by anything that has more than zero pen, which leads to shrap too

**Comment by lKiseki** [comment]
Very cool PR, but this practically invalidates the balance on the new terra laser guns. Those may have to be looked at if this goes through; right now, with this TM and the new guns, I'd say marines are a little bit overpowered, but I'd like to reiterate it's not the TM's fault, but rather a combination of two things.

**Comment by TiviPlus** [comment]
I saw enough

**Pull request closed without merging**
