### PR TITLE
Remove Mosin from Icy Cave

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

lel

## Why It's Good For The Game

I gamer too hard with mosin in Sensor Capture and Combat Patrol.

## Changelog

:cl:
del: Remove Mosin from Icy Cave due to HvH balance
/:cl:

### CODE REVIEW

**Comment by tanker4390** [comment]
Reverse salt PR

**Comment by FIXTHERADBOXPLEASE** [comment]
Nothing wrong with a single power weapon... think of it like TGMC Quake

**Review by RipGrayson — APPROVED** [review]
I suggest replacing the removed gun with a random version, but won't press for it

**Comment by Lumipharon** [comment]
Just make a non scoped version for map spawns, also non meme cl

**Comment by novaepee** [comment]
> Just make a non scoped version for map spawns, also non meme cl

Whether scope or not, mosin can delimb a marine with three shots, so it's not a weapon made for HvH.

**Pull request merged**
