### PR TITLE
Medvendor update

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
removes the noobtrap medkit spending 2 or 4 points in a medkit is now a complete waste since you get one for free. in the essential kit.
also removes other pouches. since the Advanced medical pouch is the only one that comes filled and is unique to their vendor. (plus you can get the other pouches in the regular surplus vendor)
also adds the BC and Gyro to medical prepp attachements. as a way to get more usefull attachements in the vendor

## Why It's Good For The Game
medics won't waste the precious points. without knowing better
and won't get empty generic pouches instead of the ones that come with specific chems (that can hardly be obtained otherwise)

## Changelog
:cl:
add: BC and gyro to the medic attachment list
del: Removes generic pouches from the medic preparation vendor
del: Removes medkits from the point medic vendor
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
14 commits to change like 2 things.

*reminds me of every PR I've ever made*

**Comment by davidchan13** [comment]
Sulaco doesn't have a Medicine Vendor in their prep room like PoS does, so keeping Advanced Medkits is desirable for corpsmans who want extra bic/kelo/tram pill bottles when the ungas already looted the marine meds in medbay.

**Comment by Chaznoodles** [comment]
image

yeah I feel you

Honestly I'd just remove weapon attachments from marine vendors entirely, and leave them in the attachies one. There's no real reason to have a 2-limit on what you can pick when you can take ten steps and vend fifty magharnesses.

**Comment by jroinc** [comment]
> Sulaco doesn't have a Medicine Vendor in their prep room like PoS does, so keeping Advanced Medkits is desirable for corpsmans who want extra bic/kelo/tram pill bottles when the ungas already looted the marine meds in medbay.

You get one for free now as medic, so it's not a big deal.

**Comment by davidchan13** [comment]
> > Sulaco doesn't have a Medicine Vendor in their prep room like PoS does, so keeping Advanced Medkits is desirable for corpsmans who want extra bic/kelo/tram pill bottles when the ungas already looted the marine meds in medbay.
> 
> You get one for free now as medic, so it's not a big deal.

And if you want more than one? The only pill bottles medics can directly buy are paracetamol, which is a noob trap in and of itself, meanwhile all the useful pill bottles were removed from the medvendor. Of all the things you can buy right now, Mera/Derm/Ironsug kits and adv first aid kits are the only things worth a damn that you can't already get from medbay.

**Comment by jroinc** [comment]
> > > Sulaco doesn't have a Medicine Vendor in their prep room like PoS does, so keeping Advanced Medkits is desirable for corpsmans who want extra bic/kelo/tram pill bottles when the ungas already looted the marine meds in medbay.
> > 
> > 
> > You get one for free now as medic, so it's not a big deal.
> 
> And if you want more than one? The only pill bottles medics can directly buy are paracetamol, which is a noob trap in and of itself, meanwhile all the useful pill bottles were removed from the medvendor. Of all the things you can buy right now, Mera/Derm/Ironsug kits and adv first aid kits are the only things worth a damn that you can't already get from medbay.

As a medic, you get 2 of each basic pill bottle (1 in your bag, another in the advanced medkit). That's 16 people FULLY healed from -100 to 100 HP, counting no other meds, no meralyne, no other medics, no self-treatment, no trauma packs. That's more than enough for you to head planetside with as a latejoin guy.

So, here's what you have to work with as a medic on the Sulaco, if you want more-

3 MarineMeds (One MORE than the POS has) (3 bottles each)-9
3-4 medbelts (1 bottle each)- 3
3-4 CLB's (1 bottle each)- 3
4 Advanced Medkits (1 bottle each)- 4
4 MD vendors with 2 medbelts each- 8

That's... 27 pill bottles for free. Of EACH basic chem. Some will be taken, sure. Not all.

Now, I don't know about you, but whenever I play PFC, I never have a problem finding like 2 full-stocked medbelts on the Alamo planetside.

I have also NEVER seen the medbay fully-emptied of medical supplies, including basic pills, even during hijack. Some are taken, yes. Not all of them, not by a long shot.

Paracetamol is a medic chem. It's not a noob trap, it's an alternative playstyle. If it's not for you, don't take it, it's weighted so you won't miss out on any of your precious meraderm by choosing to buy it.

I've done my best to remove any points-based item from the medvendors that you can get for FREE. On the basis that you shouldn't spend your points on FREE things.

One last comment. Feel free to add the Sulaco medvendor into the Sulaco medic preps (or beg someone to do it). As long as it's more-or-less medic only, I have no real problem with it, I just don't want people to waste points.

**Review by TiviPlus — APPROVED** [review]
Fix conflicts and this is good

**Review by Hughgent — APPROVED** [review]

**Pull request merged**
