### PR TITLE
Combat shotgun resprite

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image
Icon and Inhands by me.
## Why It's Good For The Game
Replaces our ages old T-39 with a more in style and modern sprite.
## Changelog
:cl:
imageadd: New SH-39 Combat Sprite. Sprite by MJP.
imagedel: Old SH-39 Sprite.
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
Dogshit

**Comment by yyzsong** [comment]
Dogshit

**Comment by xSlumLord** [comment]
Dogpeak

**Comment by Technical-l** [comment]
dog

**Comment by despong** [comment]
d

**Pull request merged**
