### PR TITLE
Give energy sniper rifle aim mode, increase fire delay, & balance its heat mode

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

https://cdn.discordapp.com/attachments/504094319075131402/975634899266580500/2022-05-15_22-43-55.mp4

## Why It's Good For The Game

Barely anyone use energy sniper rifle. You have to frontline with it, which defeats the purpose, or you are content with accidently FFing marines (with the latter more plausable).

Many people agree that the energy sniper rifle needs more, but they fear that a hitscan sniper will wreck balance. In an attempt to calm such doubts, I ensure that in heat mode it shall take all the energy of the energy sniper rifle, meaning that any gamers that want to lit xenomorphs up from afar shall have to reload every time they use head mode energy sniper rifle.

I also put an additional second fire delay on standard ammo. Pray that I don't increase fire delay.

## Changelog
:cl:
add: aim mode on energy sniper rifle
balance: aim mode on energy sniper rifle
balance: increase fire delay to 2 seconds on energy sniper rifle
balance: heat mode, which lit xenomorphs on fire, on energy sniper rifle uses all of 600 energy in mag, therefore one needs a fresh mag for every heat mode shot
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
image
Pray that I don't have to modify stats.

**Comment by Lumipharon** [comment]
Incend mode is cool though, making it 1 shot per mag is kinda, ???

**Comment by ilikesaying** [comment]
Ass-grabbed logik : it requires extra energy to warp the laser around ungas :)

**Comment by Naaanii** [comment]
One shot mags sound horrible and unusable. Rest seems fine though you could have just made a much higher fire rate penalty for a hitscan weapon with aim mode.

**Comment by AGasCanister** [comment]
Interesting PR! However,

https://user-images.githubusercontent.com/55928412/168619066-9b6f2110-ab46-440e-8754-f5f4af93a273.mp4

**Comment by novaepee** [comment]
Tivi said no.

**Pull request closed without merging**
