### PR TITLE
Limits scopes and the SR-127, and mosin

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Title, limits those items to 4 each. An alternative pr to #15998
## Why It's Good For The Game
See #15998
## Changelog
:cl:
balance: Limits the scope attachments, SR-127, and mosin to 4 each
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
Once again DMR27 and BR64 kept their miniscopes so you have infinite miniscopes

**Comment by SimplySmiley123** [comment]
Why limit the Martini Henry tho? It's not like it's a good weapon, or all that useful especially at longer ranges.

**Comment by TheUSSWatercooler** [comment]
A better option might just be to limit what guns the T-47 can go on, so only the SR-127 and DMR could actually use it, such that they could keep their role while xenos don't have to deal with every gun being able to see them from offscreen.

**Comment by Araulius** [comment]
I like what i see here aside from the martini henry.

**Comment by Wisemonster** [comment]
Alright, decided to unlimit the martini

**Comment by CVSthePharmacy** [comment]
with your logic I should just remove boiler's neuro and acid ball, due to them offscreening marines with no counter, as it'd require marines to go deep into the xenball. I really can't tell you how stupid this pr is, with the insane amount of xeno powercreeping, I feel like you're just buffing yourself, not actually balancing the game.

**Comment by Kuro020** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/16038

**Pull request closed without merging**
