### PR TITLE
Neurospit buff

### PR DESCRIPTION
**Pull request by Lefunny**
## About The Pull Request

Neurospit buff in the slowdown_stack

## Why It's Good For The Game

Neurotoxin is having a hard time since its chem purge got nerfed and is hardly used in most times, maybe this can give it more of an use to xenos placing neurotoxinspit castes into a more of a support role giivng marines slowdown

## Changelog
:cl:

balance: rebalanced something
code: changed some code

/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
hrmmm
seems legit!
image_2022-02-08_191420

**Comment by KrabSpider** [comment]
Praes use it all the time. Sentinels use it all the time. What?

**Comment by Lefunny** [comment]
> Praes use it all the time. Sentinels use it all the time. What?

Neuro itself still weak since the last nerf with just made the chem purge non existant and gave nothing in echange

**Comment by Redstonize** [comment]
This is obviously a meme and the person won't even stand behind his PR with a real name.

**Comment by Lefunny** [comment]
> This is obviously a meme and the person won't even stand behind his PR with a real name.

Lfmao nah the PR is legit and im here daily reading feedbacks, feel free to comment

**Comment by Naaanii** [comment]
Neuro should not have been used SOLEY for the chem purge to begin with and light neuro was removed giving castes regular neuro which was a decent compromise unless numbers were changed.

While it is already a stamina killer, which will slow down marines and reduce the ability for them to sprint again whilst also dealing damage over time is already decent enough and doesn't really warrant a buff.

Whether Xenos use it or not is up to them and their playstyles but neuro seems decent enough as it is for now.

**Comment by Lefunny** [comment]
> Neuro should not have been used SOLEY for the chem purge to begin with and light neuro was removed giving castes regular neuro which was a decent compromise unless numbers were changed.
> 
> While it is already a stamina killer, which will slow down marines and reduce the ability for them to sprint again it also deals damage over time and seems already decent enough and doesn't really warrant a buff.
> 
> Whether Xenos use it or not is up to them and their playstyles but neuro seems decent enough as it is for now.

Your only mistake there was, im not buffing neuro itself, im buffing the neurospit with are different things, the chem neurotoxin still the same thing without any change.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
