### PR TITLE
Quickbuild Rework

### PR DESCRIPTION
**Pull request by RikuTheKiller**
## About The Pull Request

Replacement for #13095

Combats chinawalls by making the quickbuild point pool shared across the hive.
Essentially, if someone makes a chinawall, the hive loses out on the rest of the maze.
## Why It's Good For The Game

Tries to make quickbuild balanced without removing it from the game.
The wonders of having quickbuild without all the chinawalls.
## Changelog
:cl:
balance: Quickbuild now uses a shared pool of points.
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
me watching the numbered drone cover the entire map with doors, wasting all of our collective quick-build points (I'm gonna have to individually click every door to deconstruct them)

**Comment by blackdav123** [comment]
magmoor should probably have 1600 points like big red considering how much of the map is wide open space

**Comment by Araulius** [comment]
Is it going to be map dependent or universal? the point count that is.

**Review by Lumipharon — APPROVED** [review]
Code seems fine, numbers seems super high though, but worth TMing

**Comment by RikuTheKiller** [comment]
> Is it going to be map dependent or universal? the point count that is.

It's stated in the PR description, the initial points are map dependent.

**Comment by RikuTheKiller** [comment]
Honestly, might as well remove pop scaling.

**Comment by Naaanii** [comment]
Unsure if this is in the scope of the PR but,

Would be nice if only leader appointed castes have access to quick build while others can just build regularly to help actually distinguish between necessary defences and extra work.

Would also stop one random funny troll/bald bean unnecessarily spam walls or doors in a likely to be uncontested area.

**Comment by RikuTheKiller** [comment]
> Unsure if this is in the scope of the PR but,
> 
> Would be nice if only leader appointed castes have access to quick build while others can just build regularly to help actually distinguish between necessary defences and extra work.
> 
> Would also stop one random funny troll/bald bean unnecessarily spam walls or doors in a likely to be uncontested area.

No, the purpose of quickbuild is QoL, restricting QoL to specific castes defeats the purpose.

**Comment by RikuTheKiller** [comment]
Also, this isn't the only fix for xhina, flamespread weapons, wall nerfs and general flamer buffs are still on the table.

**Comment by ivanmixo** [comment]
Xenos can insta delete walls and such even after shutter open

**Review by ivanmixo — CHANGES_REQUESTED** [review]
See above

**Comment by Barnet2** [comment]
Not enjoying this PR at all. Being cucked out of building because someone bricked is incredibly unfun.

**Comment by RikuTheKiller** [comment]
> Xenos can insta delete walls and such even after shutter open

guh

**Comment by AlexCrimson** [comment]
>Not enjoying this PR at all. Being cucked out of building because someone bricked is incredibly unfun.

Would that be solved by giving that specific map more build points(which i believe it still a point of balance for this PR, right?) or is it bad to the level of needing a big "HEY, build points are shared between the Hive" message?

**Comment by RikuTheKiller** [comment]
> Xenos can insta delete walls and such even after shutter open

this has been fixed

**Comment by Pariah919** [comment]
Doesn't feel like this solved the issue of "The entire map is one huge maze" at all with how many qikbild ™️ points you get.

**Comment by RikuTheKiller** [comment]
> Doesn't feel like this solved the issue of "The entire map is one huge maze" at all with how many qikbild ™️ points you get.

A big portion of the map is supposed to be mazed. Those amounts can be adjusted and this PR lays the framework for that.

**Comment by AlexCrimson** [comment]
I still think Walls and Sticky Resin should be in separate pools. If nobody spams Sticky Resin, the point amounts seem fine. If a little low on bigger maps. However if anyone gets the idea to spam Sticky Resin, all those points vanish fast, and you are stuck unable to build at all until the shutters open.

So yeah...

Remove Sticky Resin from the quickbuild mechanic

Give Sticky Resin its own pool of points 

Let us build after depleting quickbuild points

Just remove Sticky Resin as a buildable structure and rework it into the game some other way? Like blue weeds spawn it once every few minutes? Or give all builders the Hivelord resin spit?

Pick one or more of the above options? Or maybe its just not a big deal.

**Comment by imsxz** [comment]
a couple ideas ive had recently:
might be cool if only leaders/rulers can use quickbuild if theres a queen, the rest getting slowbuild(probably at the cost of some quickbuild points)

it would be nice if there was slowbuilding after the points are used up(in exchange, having less quickbuild points)

at that point, it shouldnt be possible to densely pack mazes into more than a couple parts of a map, especially not to the extent shown in grayson's screenshots, but there would ideally be enough quickbuild points to get a workable maze even with a lazy hive, while not disrupting the more dedicated xeno builders.

thoughts? sorry if this is outside of the scope of the PR

**Comment by RikuTheKiller** [comment]
> Let us build after depleting quickbuild points

This reintroduces the thing quickbuild aims to delete, which is that getting arthritis is beneficial for the hive.

> I still think Walls and Sticky Resin should be in separate pools.

I thought this for a while too, then I realized doing so would force builders to always use sticky resin if they want to maximize efficiency.

> might be cool if only leaders/rulers can use quickbuild if theres a queen

Yet another suggestion that eliminates the purpose of quickbuild. You aren't supposed to restrict QoL, especially like that.

**Comment by RikuTheKiller** [comment]
Is it that hard to come up with a suggestion that doesn't directly oppose the purpose of quickbuild?

**Comment by AlexCrimson** [comment]
>Is it that hard to come up with a suggestion that doesn't directly oppose the purpose of quickbuild? I've seen like, what, 6 of them already?

Letting people slow build after using up quickbuild points isnt removing the QoL that is quickbuilding. Its just adding an optional side quest to people who want to build more before the shutters open. 

>I thought this for a while too, then I realized doing so would force builders to always use sticky resin if they want to maximize efficiency.

Is that an issue? Filling a maze with sticky resin burns through points extremely fast. If the hive had like 800 sticky resin points, it would be used up within minutes, and with relatively little effort compared to normal mazing. Then it also stops people wasting the other quickbuild points on anything but walls.

**Comment by RikuTheKiller** [comment]
> Letting people slow build after using up quickbuild points isnt removing the QoL that is quickbuilding. Its just adding an optional side quest to people who want to build more before the shutters open.

It's directly readding the incentive to slowbuild which quickbuild is intended to remove in it's entirety.

> Is that an issue? Filling a maze with sticky resin burns through points extremely fast. If the hive had like 800 sticky resin points, it would be used up within minutes, and with relatively little effort compared to normal mazing. Then it also stops people wasting the other quickbuild points on anything but walls.

Honestly might consider the point pool for sticky resin.

**Review by Lumipharon — APPROVED** [review]

**Comment by AlexCrimson** [comment]
Seems to be working well. Ive seen less people spamming Sticky Resin, so maybe nothing really needs adjusting there. I will say that Gelida needs more points. 200-300, maybe even more.

**Pull request merged**
