### PR TITLE
New PFC armor sprites and new squad color armor markings

### PR DESCRIPTION
**Pull request by Metroidlover**
## About The Pull Request

New sprites for commonly available armor and the basic helmet

Also now redone all the squad color markings

## Why It's Good For The Game

We now have armor sprites that aren't from CM
## Light Armor
Light Front
Light Side
Light back

## Medium Armor
Reg front
Reg side
Reg back

## Heavy Armor
Heavy Front
Heavy Side
Heavy Back

## Edge Armor
Edge front
Edge Side
Edge Back

## Internal Storage Armor
Carrier Front
Carrier Side
Carrier Back

## Ballistic Armor
Ball Front
Ball Side
Ball Back

## Medium Armor with new SL markings
SL Front
SL Side
SL Back

## Changelog
:cl: Kuro
imageadd: Every PFC armor along with the basic helmet now has a new sprite!
imageadd: Redone all the squad color markings
/:cl:

### CODE REVIEW

**Comment by Metroidlover** [comment]
I'll update the images when Kuro is sure he isn't going to change things again

**Comment by Metroidlover** [comment]
Pictures updated

**Comment by Kuro-ai** [comment]
One day we'll get this thing right

**Comment by Kuro-ai** [comment]
squad colors we're very fucky so I had to change then,wait till leon updates the screenshots with new squad color scheme

**Comment by Kuro-ai** [comment]
I'm gonna drive leon insane before this ends

**Comment by Metroidlover** [comment]
I can't tell why it says the berets have changed, they're the exact same names and sprites that are merged already

**Comment by Metroidlover** [comment]
I'm losing my mind here, I don't even know what to do with this anymore

**Comment by Kuro-ai** [comment]
new helmet sprites soon honk honk

**Pull request merged**
