### PR TITLE
gives queen AP on slash damage

### PR DESCRIPTION
**Pull request by coldironwarrior**
~~it's not a swipe, i lied~~

## About The Pull Request

gives queen 10 AP on slash

## Why It's Good For The Game

kurt suggested this as a potential to making queen less whelming in combat; then we moved on to other ideas but i wasnt sure if anyone still wanted to see this one PR'd.

definitely not my intention to cook this with #15296

## Changelog
:cl:
add: queen has 10 AP on slash
balance: gives queen AP on slash damage
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
Me when da raid boss queen hits.

More seriously, I don't really care for tail sweep since it'll just get people killed more often than not but I don't really get what queen AP is for? Killing rushers? Just better direct frontline?

**Comment by Naaanii** [comment]
This is a terrible buff.

**Comment by bowlofcereal** [comment]
wtf lol

**Comment by MiniMeatwad** [comment]
I don't even want AP on xeno at all, please kill AP on xeno for anything except maybe abilities

**Pull request closed without merging**
