### PR TITLE
Automedicals have new sounsd

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
B18/Valk have new sounds
source: Me
## Why It's Good For The Game
More unique and original sounds, these might need a filter applied in the future though.
## Changelog
:cl:
sound: B18 and Valkyrie automedical modules have new sounds.
/:cl:

### CODE REVIEW

**Comment by Kuro020** [comment]
this is my favorite pr in this github

**Comment by Aroliacue** [comment]
you're so full of yourself

**Comment by Pariah919** [comment]
> you're so full of yourself

Maybe I am? I think they're better than old B18 sounds in the sense they're actually unique, but shrug. They probably need some kind of filter to make them work better if it won't pass as is. I'm not exactly sure what kind, though.

**Comment by Aroliacue** [comment]
> > you're so full of yourself
> 
> Maybe I am? I think they're better than old B18 sounds in the sense they're actually unique, but shrug. They probably need some kind of filter to make them work better if it won't pass as is. I'm not exactly sure what kind, though.

I thought this was a joke PR, but you're serious. Oh god

**Comment by tyeagg** [comment]
> > > you're so full of yourself
> > 
> > 
> > Maybe I am? I think they're better than old B18 sounds in the sense they're actually unique, but shrug. They probably need some kind of filter to make them work better if it won't pass as is. I'm not exactly sure what kind, though.
> 
> I thought this was a joke PR, but you're serious. Oh god

Why would you think this is a joke PR? this is a very serious codebase and we don't take kindly to your aggressive behavior

**Comment by Losenis** [comment]
mf wanted to remove valk so this is his new plan lmao

**Comment by Aroliacue** [comment]
> > > > you're so full of yourself
> > > 
> > > 
> > > Maybe I am? I think they're better than old B18 sounds in the sense they're actually unique, but shrug. They probably need some kind of filter to make them work better if it won't pass as is. I'm not exactly sure what kind, though.
> > 
> > 
> > I thought this was a joke PR, but you're serious. Oh god
> 
> Why would you think this is a joke PR? this is a very serious codebase and we don't take kindly to your aggressive behavior

I'm so sorry, please don't admin me

**Comment by Arctrooper8** [comment]
Where are the examples? Why do people never give photos or sound examples! How are we supposed to easily compare them?! 8scream

**Comment by FosterGrime-Heymynameslouie** [comment]
voice of an angel

**Comment by bowlofcereal** [comment]
> you're so full of yourself

you're so dumb lol

**Comment by TiviPlus** [comment]
> Where are the examples? Why do people never give photos or sound examples! How are we supposed to easily compare them?! 8scream

Think of the silkiest voice you can and multiply it by 100 with the best mic quality known to man and you get mjp

**Pull request closed without merging**
