### PR TITLE
adds unguided sadar and sg 62 reqtorio

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
see title
a completely untested pr
## Why It's Good For The Game
RO mains rejoice
## Changelog
:cl:
add: adds refills for unguided sadar rockets and SG-62 magazines to req
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
sg 153 ammo when sob

**Comment by yyzsong** [comment]
not adding thirty snowflake ammo types you will buy two mags of

**Comment by GrayRachnid** [comment]
> not adding thirty snowflake ammo types you will buy two mags of

I buy 30 mags of it because I go through them so fast

**Comment by chizzy376** [comment]
All we need now is tfoot grenade to be reqable

**Review by Lumipharon — APPROVED** [review]
I'm going to just assume these numbers are good.

**Pull request merged**
