### PR TITLE
RR doesn't have 5 times the intended effect

### PR DESCRIPTION
**Pull request by jroinc**
## About The Pull Request

fix

## Why It's Good For The Game

fix

## Changelog
:cl:
fix: fix
/:cl:

### CODE REVIEW

**Comment by Chaznoodles** [comment]
I thought you were buffing the RR x5 and I was about to have a wacky moment

**Comment by jroinc** [comment]
> I thought you were buffing the RR x5 and I was about to have a wacky moment

Nah. Intended effect- 1 pill heals 50 brute/burn rapidly for 20 permanent damage.

Current effect- 1 pill heals 250 brute/burn rapidly for 100 permanent damage, which is an OOF.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Fix changelog

**Comment by Hughgent** [comment]
I had asked you kindly to make every reference of `russianRed` into `russian_red`

Please finish doing that. ctrl+shift+f is your friend.

**Comment by Hughgent** [comment]
image

**Pull request closed without merging**
