### PR TITLE
Pillar of Spring Prep/Medical Optimization

### PR DESCRIPTION
**Pull request by Alterist**
## About The Pull Request

Arranges vendors more optimally so that you can have more than 3 medics/engineers in prep at a time
Adds back missing walls
unfucks apcs and pipes and wires
medical have been rearranged/expanded to be more roomy and allow for hopefully better flow
removes tube things because they were never meant to be placed that way
## Why It's Good For The Game

why not?

## Changelog
:cl:
add: PoS prep rooms have been rearranged to allow for better fung shui, also to let more than 3 medics gear up at the same time, but who cares about that?
add: PoS medical have been expanded and rearranged slightly, there's now a tiny break room and a bit more space to work with
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
I think there's a floating apc in medbay

**Comment by TiviPlus** [comment]
Also you didn't mention removing the tube things on the hull

**Comment by Alterist** [comment]
> 
> 
> I think there's a floating apc in medbay

???



> 
> 
> Also you didn't mention removing the tube things on the hull

added

**Comment by TiviPlus** [comment]
I know but it's floating in the middle of the hall might be mapdiff not rendering junk just be sure

**Comment by Alterist** [comment]
> 
> 
> I know but it's floating in the middle of the hall might be mapdiff not rendering junk just be sure

@TiviPlus if you had taken a look at any other apc you would have noticed they were all floating in the air, the offsets for all the apcs are applied somewhere during mapload, a direct render of them wouldn't show it

**Pull request merged**
