### PR TITLE
Kills lemoline recipes

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
Keeps it as a catalyst for the remaining lemo gated chems.
## Why It's Good For The Game
Lemogate isn't really required since marines and even SLs can't make their chem cocktails. Gives shipside MR and CMO and Doctors something to do when they're not handling patients

Players doing things to help their team mates is good.
Sweaty powergamer making their own mixes so they can avoid having to rely on team members as much as physically possible is bad.
## Changelog
:cl:
del: Removes lemoline from all recipes requiring it.
/:cl:

### CODE REVIEW

**Comment by Mrrpip** [comment]
Eh? But why would you need a catalyst then? If doctors (And medics) are the only people that can use it to begin with.

If they don't have lemoline, they buy an 8 point bottle and they're set, assuming they recycle.

**Comment by Al-1ce** [comment]
> Edit: Point is, is there any particular reason we don't know about not to go the whole 9 miles?

If you'd read the PR you'd realize it doesn't do that. All this does is remove lemolame, which has been a boring and meaningless gatekeep chem for years

**Comment by Lumipharon** [comment]
I'm not sure why you've made this when I already had issues with the last PR which did less than this one.

**Comment by SzkieletorNutric** [comment]
image

**Comment by Mrrpip** [comment]
> > Edit: Point is, is there any particular reason we don't know about not to go the whole 9 miles?
> 
> If you'd read the PR you'd realize it doesn't do that. All this does is remove lemolame, which has been a boring and meaningless gatekeep chem for years

Exactly! If you read my comment, you'd know I knew that! Catalyst and Removing the lock entirely would've been the same thing, so you may aswell have just done the latter.

**Comment by Al-1ce** [comment]
> Exactly! If you read my comment, you'd know I knew that! Catalyst and Removing the lock entirely would've been the same thing, so you may aswell have just done the latter.

Because we remove enough shit full stop as it is. Mama mia...

**Pull request closed without merging**
