### PR TITLE
Raises Queen Leader Slots

### PR DESCRIPTION
**Pull request by Sunsidec**
## About The Pull Request

Raises Queen leader slots from 2/3/3/4 at young/mature/elder/ancient to 2/3/4/5.

## Why It's Good For The Game

Makes more sense, spreads xenos pheremones a bit more, rewards maturing for Queen.

## Changelog
:cl:
balance: Queen leader slots adjusted.
/:cl:

### CODE REVIEW

**Review by Pariah919 — CHANGES_REQUESTED** [review]
Why though? This mostly affects lategame Queen. Pheromone towers exist now, there's no reason to increase the amount of leaders on the map on lategame to me at present time, honestly.

**Comment by Sunsidec** [comment]
> Why though? This mostly affects lategame Queen. Pheromone towers exist now, there's no reason to increase the amount of leaders on the map on lategame to me at present time, honestly.

For the sake of neatness! 2/3/3/4 looks strange, when everything else increases with maturity. It's either that or turn it to 1/2/3/4, which I don't think is a very nice thing to do with the current hell xenos are being put through. It's also a rare occasion you see a pheremone tower set to recovery over warding or frenzy due to queen pheremones generally being present at whatever fight has stalemated long enough for pheremone towers to be safely placed, and would enable an extra leader to be assigned to make flanks more of a threat.

**Comment by Naaanii** [comment]
With phero towers, don't think Queen needs more leader slots honestly.

Though Queen may have one of the best Primo abilities in the game, I wouldn't be opposed to adding an extra leadership slot for Primo Queen since it's rather hard to obtain and all the more punishing should she die.

**Comment by Losenis** [comment]
More leader slots are good due to the rally too, a xeno shouting "POD OPS IN THE FUNNY MINER UHHHHHHHHH NORF UHHH BY THE RED DOORS" can only help so much.

**Comment by DerpiestBruh** [comment]
sus pr

**Review by TiviPlus — CHANGES_REQUESTED** [review]
How about make it 4 accross the board

**Comment by Sunsidec** [comment]
> How about make it 4 accross the board

Seems silly as generally everything scales across maturation, this should be no exception, also see @Losenis' comment for additional justification re. rallies.

**Review by Sunsidec — COMMENTED** [review]
Updated to 4/4/4/4 across the board which is the preferable alternative to a closed PR.

**Pull request merged**
