### PR TITLE
Disables Carrier Evolution/Regression

### PR DESCRIPTION
**Pull request by Chaznoodles**
## About The Pull Request

Removes/Disables Carrier Evolution/Regression. Can still be adminspawned.

## Why It's Good For The Game

Every time we 'fix' carrier, people break it again. It's a nonstop source of cheese and bug abuse that isn't particularly fun or engaging for those on the receiving end compared to xenos they can actively contest, and we can't really punish people for doing it because _every_ carrier does it. There's about 15-ish relevant bugfixes for carriers, far more than any other issue in the game, and none of them matter because people always find a way around it. This disables carriers via two comments until they're in a better spot, have been properly fixed, or a different implementation is merged.

image

Naaanii, I sentence you to death

## Changelog
:cl:
tweak: Carriers disabled due to rampant circumvention of intended mechanics.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -24. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SilencedMP5A5** [comment]
based

**Comment by BraveMole** [comment]
Meme PR?

**Comment by Jeff-jefferson-jeffery** [comment]
Hello? Speedmerge department?

**Comment by Yttriums** [comment]
Ided

**Comment by Chaznoodles** [comment]
> Meme PR?

No

> Ided pr speedclose

No

**Comment by AbsoluteJerry** [comment]
Oh YES

**Comment by Naaanii** [comment]
Seems unnecessary when there's a rework PR in the works and Carriers can be played around. Removing is just makes marines less cautious about anything like traps or actually having to adapt to any situation. Its not like marines are winning any less or having difficulties dealing with Carriers with Carrier still in the game.

**Comment by Yttriums** [comment]
> being stunned for 30 seconds 

Hyperbole doesn't help the argument

>which you can't really fight back against at all

Except for counterplay by your team, who can just pull the hugger off your face, shoot it, communicate risk of huggers, etc

**Comment by SilencedMP5A5** [comment]
hugger holes can be hidden under pretty much everything and they're an instant death sentence 90% of the time

and people have found ways to get instahugs again

and as chaz said it's just abused nonstop despite attempts to fix it

kill it, kill it now

**Comment by Jeff-jefferson-jeffery** [comment]
just checked
hugger holes will stun a marine for 17 seconds if nothing happens to the marine throughout the whole duration
this could of course be extended by time dilation or pre-existing pain from attacks

**Comment by Yttriums** [comment]
> just checked
> hugger holes will stun a marine for 17 seconds if nothing happens to the marine throughout the whole duration
> this could of course be extended by time dilation or pre-existing pain from attacks

Seems like a justification for a nerf

**Comment by Chaznoodles** [comment]
Unstale me or by allah I will armcurl your dog at the bottom of your stairs

**Comment by AtlasRules** [comment]
it's either this or extensive reworks until it barely resembles carrier and is either more broken, or completely useless 

i think it's best if we put it down

**Comment by Chaznoodles** [comment]
Closing, no desire to contribute due to repeated instances of behaviour like below.

image

**Pull request closed without merging**
