### PR TITLE
HMG now only carries 300 rounds, and not 700

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title basically

## Why It's Good For The Game
this was way too much

## Changelog
:cl:
balance: HMG now can only hold 300 rounds in its boxes, or 300 clicks and 100 bursts. Rather than 700
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -28. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SilencedMP5A5** [comment]
are the boxes even orderable from req

**Comment by psykzz** [comment]
Missed a reference here https://github.com/tgstation/TerraGov-Marine-Corps/pull/4551/files#diff-851381e94d4816461e143d068cbf6085R13

This whole gun sucks, its deleteing the mag, when it should just spend rounds from the mag instead.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-33). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
