### PR TITLE
Removes dead huds

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Title
Dead code and extra processing bad

## Changelog
:cl:
code: Removes dead/unused huds
/:cl:

### CODE REVIEW

**Review by Hughgent — APPROVED** [review]
How could you do this? how could you make a PR that doesn't compile?!

HOOOOOOWWWWWWW?!?!?!?

**Comment by TiviPlus** [comment]
It does compile stinki

**Comment by AndroidMK2** [comment]
Quite a bad idea lad, sorry

**Comment by TiviPlus** [comment]
> Quite a bad idea lad, sorry

what

**Review by Hughgent — APPROVED** [review]

**Pull request merged**
