### PR TITLE
suppressor gaming

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request
suppressor gaming
## Why It's Good For The Game
suppressor gaming
## Changelog
:cl:
add: suppressor gaming
/:cl:

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
it's a quadfecta! Webedit, bad body, bad reason, incomplete and mislabeled CL. 👏 👏

**Comment by lovegreenstuff** [comment]
haha yes

**Comment by TiviPlus** [comment]
Supressor gaming

**Comment by David-Stormwell** [comment]
god I would've loved this, too bad it was made badly.

**Pull request closed without merging**
