### PR TITLE
Bodydragging is now a 2 Second timer on nonburst humans for xenos

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Soon we will remove capshit gameplay 

## Why It's Good For The Game

what it says

## Changelog
:cl:
balance: To start bodydragging is now a 2 Second timer on nonburst humans for xenos
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
Bodydragging delay gud.

Personally, I'd make it 5-10 seconds so you have to win a fight to drag, but obviously you can adjust it if you want.

**Comment by Wayland-Smithy** [comment]
I tested this, and it also prevents you from quickly pulling nonburst noncorpses, AKA living humans.

I was initially worried that this would make xenos stuck for 2 sec on grab with no feedback to the player, but that is not the case and you can easily cancel on move.

**Comment by AtlasRules** [comment]
y e s

finally, some reprise from bodydragging

**Comment by Wayland-Smithy** [comment]
> Soon we will remove capshit gameplay
Is this intended to make it harder in the meantime?

**Comment by TiviPlus** [comment]
The intent is to merge a bunch of PRs in short succession that discourage capture gameplay see
silos
respawns
this pr
haths biting pr

**Comment by Wayland-Smithy** [comment]
> The intent is to merge a bunch of PRs in short succession

Okay then I will trust if things don't go as planned this PR will either get a check for living or not happen.

**Comment by spookydonut** [comment]
@TiviPlus doesn't pass travis

**Review by Hughgent — APPROVED** [review]

**Pull request merged**
