### PR TITLE
New T2 Spitter sprites

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Back from GitHub hiatus. Will get back to hiatus again due to IRL.

Spitter is getting new sprites. 

https://user-images.githubusercontent.com/6610922/181091673-3ece5827-af2e-485f-a6b9-1bde4a3a3edd.mp4

https://user-images.githubusercontent.com/6610922/181091708-a150d01d-30f3-4101-a1fa-c5bc31484445.mp4

## Why It's Good For The Game

If you look very closely, spitter, sent, and drone sprites are the same. In fact, the base of the sprites for spitter and sent is the drone sprites (they even have the same wound overlay!) There was a previous attempt at making new spitter sprites, but the spriter left before the project was complete.

The old spitter sprites exist in the codebase, but I will let maintainers decide if they stay or get deleted and only be remember by Git.

Also, reorganize xeno sprites in 2x2 dmi by caste because it was pissing me off how unorganize it is.

Shoutout to Benjamin Carmine for the new sprites.

## Changelog
:cl: nova_epee, Benjamin Carmine
imageadd: new spitter sprites!
/:cl:

### CODE REVIEW

**Comment by Kuro020** [comment]
24 hours to merge

**Comment by UsernameIs-UnAvailable** [comment]
Ugly :(

**Comment by roarbark** [comment]
looks good, makes them quicker to tell apart from sents

**Comment by FosterGrime-Heymynameslouie** [comment]
holy shit thats one manacing looking xeno

sppede merhg

**Comment by Al-1ce** [comment]
Keep the old spitter sprites. Might make for a funny prank after a while and people forget/don't realize how smol spitter used to be.

**Comment by Naaanii** [comment]
Ngl this could serve better as a new Xeno caste (soon tm). Like ace said it makes spitters look like a large mod, also easier to click, then again carrier looks pretty big so that's okay I guess. All in all, sprite is pretty cool and better than sent +, but the og sprite isn't too bad and is very fitting.

**Pull request merged**
