### PR TITLE
Strippers begone

### PR DESCRIPTION
**Pull request by SpaceLoveSs13**
## About The Pull Request

All stripper cloths and icons begone.

## Why It's Good For The Game

Same reason bunny ears and maid skirts are gone. Stripper cloths? Really? TGMC ks marines vs Xenoes MRP server. We don't need stuff that can promote Rule 8 violations. This shit should have been removed a long time ago.

## Changelog
:cl: SpaceLove
del: Stripper suits gone.
admin: Removes admin ability to spawn stripper suits.
/:cl:

### CODE REVIEW

**Comment by bowlofcereal** [comment]
somewhere, somehow, someone is upset about this

**Comment by SplinterGP** [comment]
don't delete swimsuits, neither cheerleader stuff, they can be used for inmap fluff items, (like swimsuits in a pool area, or cheerleader in a basketball court) ~~the mankini too leave it in its funny~~

**Comment by SplinterGP** [comment]
also why did you delete BLANK from uniforms

**Comment by SpaceLoveSs13** [comment]
@SplinterGP Changes done

**Comment by AnCopper** [comment]
These items aren't even acquirable outside of Admins spawning them.

**Comment by SpaceLoveSs13** [comment]
> These items aren't even acquirable outside of Admins spawning them.

That's why they are getting removed. Useless LRP stuff in the codebase will always be useless and pointless and I don't see any admins doing rp with "stripper clothes"

**Comment by BraveMole** [comment]
THAT IS IT, I AM LEAVING TO SEXO

**Comment by Al-1ce** [comment]
Terrible PR.

**Comment by sunofang** [comment]
literally 1984.

**Comment by Ace2142** [comment]
Mm

**Pull request merged**
