### PR TITLE
Fix adding slots in job slots panel

### PR DESCRIPTION
**Pull request by vvvv-vvvv**
## About The Pull Request

Job titles are supposed to be unique because of SSjob.name_occupations which expects unique keys. Up until #13990, this was somehow working due to init order

## Changelog

:cl:
fix: Fix adding slots in job slots panel
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
this doesn't mess with their access to role vendors does it?

**Comment by vvvv-vvvv** [comment]
> this doesn't mess with their access to role vendors does it?

nope

**Review by Lumipharon — APPROVED** [review]

**Comment by Lumipharon** [comment]
> > this doesn't mess with their access to role vendors does it?
> 
> nope

ok, I know title effects something, but I think it may be map icons which doesn't matter for valhalla anyway so ye.

**Comment by KM-Catman** [comment]
No idea how to contact you (Lumi didn't tell me), but your PR broke Loadout Vendors in Valhalla since you made the Fallen job's titles different. Do you know if there is any way to fix that with a simple solution, or would it require fully changing how the Loadout Vendor dispenses loadouts?

**Comment by vvvv-vvvv** [comment]
I'll look

**Pull request merged**
