### PR TITLE
makes the t-19 into a bulky item

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
so you can't do this 
image

## Why It's Good For The Game
as funny as it is its kinda dumb that you can do this

## Changelog
:cl:
balance: can't fit t19s into your bag anymore
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -58. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Jeff-jefferson-jeffery** [comment]
but why?
sure doing that is a funny meme but it's no more effective than carrying a ton of it's tiny sized mags with you
gun is fine

**Comment by TiviPlus** [comment]
But why

**Comment by Knuff-les** [comment]
This doesn't make any sense, Cause using that same logic you would submit the same thing with ALL the pistols, cause you can do it with ALL the pistols.

**Comment by TiviPlus** [comment]
There is no dishernable balance reason for this change and this PR will therefore be closed

**Pull request closed without merging**
