### PR TITLE
prunes unused sprites from icons\mob folder

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request

prunes unused sprites in the \icons\mob folder

icons removed from **actions.dmi**
- grow ovipositor
- barbed weed sac
- silence marine ability
- old dig tunnel
- alien nest ability
- fire cannon
- thick resin door
- TL-84 flame and TL 84 water
- old SL orders
- synth backpack icons
- escaping guy
- a few other unused marine HUD icons (guy aiming gun and a claymore)
- extra votebox
- icons "64" (exit door in teal, recolored from "52") and "65" (i'd be hard-pressed to say what this is)

icons removed from **screen_ghost.dmi**
- old re-enter corpse + re-enter corpse animation
- jump to xeno and jump to xeno animation
- jump to marine and jump to marine animation
- orbit

icons removed from **cameramob.dmi**
- abductor camera
- yalp_elor

icons removed from **animal.dmi**
- forgotten
- brownbear
- morph
- floorbear
- viscerator

icons removed from **ai.dmi**
- old ai holograph

icons removes from **hud.dmi**
- hudill
- hudbuff
- hudbrainworm
- sunder break icons

## Why It's Good For The Game

cleans up the sprites in the repo; easier to navigate for later. preserved some unused ones in **actions.dmi** in case contributors want to use some for future xeno abilities

## Changelog

:cl:
imagedel: deleted unused icons and images from icons\mob.dmi
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
While it saves less than a MB, sprites generally take a bunch of time to recover, and more to recreate. I think it would much better to shove them into another DMI for future reference. 
Except if someone is thinking of a really particular sprite, no one is ever going to dig on github for them. But people absolutely do look around in DMI's for useful sprites.

**Review by ivanmixo — APPROVED** [review]

**Comment by Arctrooper8** [comment]
> While it saves less than a MB, sprites generally take a bunch of time to recover, and more to recreate. I think it would much better to shove them into another DMI for future reference. Except if someone is thinking of a really particular sprite, no one is ever going to dig on github for them. But people absolutely do look around in DMI's for useful sprites.

Could we put them in that one TG github branch where they store their old sprites?

**Comment by coldironwarrior** [comment]
> While it saves less than a MB

don't you worry one bit about it, i will surely be making more PRs of this nature :)

**Comment by Lumipharon** [comment]
That's annoying, the icon diffbot doesn't even show the sprites you're deleting, so I can't check them.

**Comment by coldironwarrior** [comment]
> That's annoying, the icon diffbot doesn't even show the sprites you're deleting, so I can't check them.

image
image
image

image

image

image

image

image
image

**Pull request closed without merging**
