### PR TITLE
You can now color jaeger any color you want

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

What the title says
image

## Why It's Good For The Game

Free speech or something idk

## Changelog
:cl:
expansion: Jaeger can now be painted any color you want
expansion: Jaeger visors can now be colored by right clicking the helmet with paint
expansion: Remember to save your jaeger in the loadouts vendor!
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
finally i can go full power ranger

**Comment by TheRealMedalis** [comment]
Madness.

**Comment by EvilMelonTheSecond** [comment]
Neon marine force assemble!

**Comment by RenGusta** [comment]
Have you not completed the auto pallette thing you were planning so the colors don't look like hastily applied crayons?

**Comment by TiviPlus** [comment]
> Madness. Will the old colors still be available?

Yes you can set them yourself, they are:
		"black" = "#474A50",
		"snow" = "#D5CCC3",
		"desert" = "#A57F7C",
		"gray" = "#828282",
		"brown" = "#60452B",
		"red" = "#CC2C32",
		"blue" = "#2A4FB7",
		"yellow" = "#B7B21F",
		"green" = "#2B7F1E",
		"aqua" = "#2098A0",
		"purple" = "#871F8F",
		"orange" = "#BC4D25",
		"pink" = "#D354BA",

default visor = "#f7fb58"

**Comment by AnCopper** [comment]
Finally, RGB Jaeger.

**Review by SplinterGP — CHANGES_REQUESTED** [review]
Did you ever do the shading stuff you said you were going to do? Plus the coloring should have brightness and darkness limitation so you cant do eye sore colors

**Comment by Pariah919** [comment]
this is going to be color hell, this shouldn't be a thing.

**Comment by ilikesaying** [comment]
fashionframe time

**Comment by Ragecrabbo** [comment]
rainbow jaegar

**Comment by Al-1ce** [comment]
I will stake in my opinion and humbly mention that the monochrome removal PR thing made most of the default colors look like shit, mostly due to the visors. This'll fix that, I hope.

**Comment by SilencedMP5A5** [comment]
this is good content, now i can attack xenos without actually attacking them 
image

**Comment by Tristan63** [comment]
I'm Commander Shepard, and this is my favorite PR on github.

**Comment by Passe2142** [comment]
> I will stake in my opinion and humbly mention that the monochrome removal PR thing made most of the default colors look like shit, mostly due to the visors. This'll fix that, I hope.
image

**Comment by TiviPlus** [comment]
Also PSA to interested players admins are apparently currently amicable to custom coloring your helmet visors for you, and it saves across rounds if you save it in a loadout

**Comment by SilencedMP5A5** [comment]
> Also PSA to interested players admins are apparently currently amicable to custom coloring your helmet visors for you, and it saves across rounds if you save it in a loadout

yep

**Review by Kuro020 — APPROVED** [review]
Interested in seeing how it goes

**Comment by Pariah919** [comment]
image
this is awful

**Comment by BraveMole** [comment]
amazing PR

**Comment by Kuro020** [comment]
> image
> this is awful

This is nice

**Comment by BraveMole** [comment]
Definitly break jaeger painting in civil war

**Pull request merged**
