### PR TITLE
Ares Bluespace recall armor module

### PR DESCRIPTION
**Pull request by tanker4390**
## About The Pull Request
Adds an armor module that can link to a weapon and summon to the user's hands at will (on a cooldown), just like a RPG protagonist. This may not be finished, possibly needing some bugs squashed or more sanity checks put in place to defend against powergaming. Oh, and balance changes.

Screenshot_20230201_085444

Further detail. After linking (with a cooldown) most weapons, except [some ludicrous ones](https://tgstation13.org/wiki/File:TGMC_sadar.png#file), they can be summoned with the ability button (again, cooldown) or re-linked to another weapon, for one at a time. Modules lose their links after being detached from armor, but not when armor is removed (armor has a weight class of huge [5], good luck with that).

Most likely these will come from req, but may be available from vendors depending on how balance goes.
## Why It's Good For The Game
For those times when you get pounced on 3 times in a row and drop all your weapons... ~~just use a magharness~~ simply pull your Mateba out of thin air, ~~then get pounced on again and have to wait the whole cooldown~~

Otherwise, you have to go back shipside, loot one, or run to where it was with a knife and pray you don't die instantly.
## Changelog
:cl: Tanker
add: Adds the Ares Bluespace recall system armor module, allowing you to summon a linked weapon at will.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
>no magic SADAR
>marines pop out funny RR or GL

truly a gilgamesh moment

image

**Comment by tanker4390** [comment]
Eh, the RR is a subtype of `rocket`, so it's banned. Launcher is fair game though.

**Comment by XSlayer300** [comment]
I was thinking it is a recall module, like, you personally recall yourself to a linked teleporter or something

**Comment by FosterGrime-Heymynameslouie** [comment]
"weight class of 5 (five)"

FATASS

**Comment by chizzy376** [comment]
GAR'YOK is real

**Comment by Coastfront** [comment]
Me firing my RR moments before summoning my 2nd, already loaded RR 

this is funny but good lord

**Comment by tanker4390** [comment]
Funny double merge conflict, reopening

**Pull request closed without merging**
