### PR TITLE
Railgun increased sunder

### PR DESCRIPTION
**Pull request by MiniMeatwad**
## About The Pull Request

More railgun sunder

## Why It's Good For The Game

Seems to be its niche as a weapon, could reduce its damage in exchange
## Changelog
:cl:
balance: 1.42x Railgun sunder
/:cl:

### CODE REVIEW

**Comment by coldironwarrior** [comment]
#13020

**Comment by Woker2004** [comment]
I will go ahead and state this, on the marine side you can literally hampter a crusher's sunder in a single hit, same with basically every caste as well as the fact you get multiple shots in a mag, now onto a xeno perspective, It simply destroys your sunder in 1 hit, to 50% or below, railgun is, in my opinion, balance pretty well the way it currently is

**Comment by MiniMeatwad** [comment]
I changed its value to be 1.42x what it was previously, in line with crusher's 70% sunder multiplier.

**Comment by MiniMeatwad** [comment]
> I changed its value to be 1.42x what it was previously, in line with crusher's 70% sunder multiplier.
> 
> I dunno about giving it a mechanic to have increased damage against the multiplier, just gonna let Juro Kaeger decide

As for what I found to be SMG pick-off territory, it's usually around 60-70% sunder. Aka most castes have no armor at 60-70% sunder.

**Comment by MiniMeatwad** [comment]
> We should go back to railgun having 1 shot capacity so you can try to bait it out as a xeno instead of just not getting to engage if you want to avoid huge sunder and/or stun/stagger.

This makes sense

**Comment by ivanmixo** [comment]
Not a fan. @Kuro020 cast judgement

**Comment by MLGTASTICa** [comment]
Not really a good change , the gun is fast to reload and can't miss since its hitscan. It effectively removes 30% of a xeno's effective in a single hit , i don't think even 20% is reasonable in first place.(ontop of dealing 150 damage , which  for most xenos is very significant)

**Comment by Kuro020** [comment]
I dont think the railgun needs a buff overall, I see it frequently and it does fine

**Pull request closed without merging**
