### PR TITLE
TM ONLY - LV-759 Campaign test

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
DO NOT MERGE - TM ONLY.

I want to see how city maps play out in campaign, so want to test LV-759 before making a dedicated campaign city map.

### CODE REVIEW

**Comment by PibeCantina** [comment]
Surely no maint will merge the "TM only" PR for the 15th time right?

**Comment by Lumipharon** [comment]
> Surely no maint will merge the "TM only" PR for the 15th time right?

:^)

**Comment by Lumipharon** [comment]
ok thats all I needed for now.

**Comment by Arturlang** [comment]
some longer term rounds with jumpscare meetings with enemies would be cool in campaign

**Pull request closed without merging**
