### PR TITLE
Nerfs A19 Impact Ammo

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request

Removes stagger and screenshake from A19/TX-8 Scout Rifle impact ammo. Slowdown and knockback are the same. 

## Why It's Good For The Game
If the gun in question was slower firing, I'd get _why_ the ammo is the way it is. But it ain't. The A19 is a pre-burst T-64 with built in IFF, it ain't any **business** having applying 2 stagger stacks, a full slowdown stack on the rate of fire it has. 

## Changelog
:cl:
balance: Deletes stagger and screenshake from A19 impact. 
balance: Damage increase to 30.
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
at least buff the damage a little to compensate for the reduction in debuffs

**Comment by KrabSpider** [comment]
> at least buff the damage a little to compensate for the reduction in debuffs

I'll consider it.

**Comment by Al-1ce** [comment]
TX-8 chews through ammo like nothing else when it comes to purchased guns. I think lowering the firerate and nerfing the stagger (while increasing magazine size or slight damage) would make it more effective.

**Comment by KrabSpider** [comment]
> TX-8 chews through ammo like nothing else when it comes to purchased guns. I think lowering the firerate and nerfing the stagger (while increasing magazine size or slight damage) would make it more effective.

I'll increase the slowdown and give it airburst.  Take it or leave it.

**Comment by Araulius** [comment]
should have removed the burst fire on the t-64 instead. funni salt PR

**Comment by maikilangiolo** [comment]
The TX8 is expensive and burns through ammo. A Minigun is more expensive but it actually kills xenos and ammo costs nothing in comparison. You only see the TX8 rarely because of this. 

Meh PR, but I don't get a say in it so it's up to mantainers.

**Comment by Passe2142** [comment]
The issue was never the rifle but the impact rounds, those rounds dont care if its King, an Ancient Queen or a big caste. The marine mains dont know that screen shake. That stagger denies every chance to use an skill, lag you and sunder ya. Iirc the rifle cost 40 points. Marines have been spamming it so much it shows.  And the strong point of the TX8 is that it can use all kinds of ammo. Only using the funny ones says a lot bout them.

**Comment by Lumipharon** [comment]
Using the Tx8 as a marine with high impact, it doesn't FEEL that powerful.
But playing as a beno getting shot by it though, is god awful, as Passe said. You can't do shit.

**Review by BraveMole — CHANGES_REQUESTED** [review]
leave slowdown alone, rest is fine for a test

**Pull request merged**
