### PR TITLE
Adds a delay when loading magazines from ammo packets

### PR DESCRIPTION
**Pull request by Yttriums**
## About The Pull Request

Adds a 1.5 second delay when loading a magazine from an ammo packet

Reworks transfer_ammo to use the fill delay of the source magazine rather than the target (this is currently unused)

## Why It's Good For The Game

Ammo packets generally offer 2-4x space efficiency over magazines when stored in general pouches, armor storage or satchels. Once you have the muscle memory for reloading a primary magazine from ammo packets, there's very little downside to running them - even in the heat of battle. 

This change balances ammo packets by slowing down their reloads and enforcing a bit of realism (loading magazines takes time in the real world). Should encourage healthier and more realistic usage.
## Changelog
:cl:
balance: loading magazines from ammo packets now has a 1.5 second delay
/:cl:

### CODE REVIEW

**Comment by Yttriums** [comment]
video example
https://github.com/tgstation/TerraGov-Marine-Corps/assets/49888953/1e8d660d-62de-4883-920e-f571ee28f32f

**Review by Kuro020 — APPROVED** [review]

**Comment by Lumipharon** [comment]
1.5sec is quite a long time just for loading a mag

**Comment by Yttriums** [comment]
> 1.5sec is quite a long time just for loading a mag

quite a short time compared to the real act of loading a magazine with loose rounds (while standing, in combat).

ultimately, this should be something you're using to refill your mag belt/pouch during downtime, not a replacement for carrying extra mags in the heat of combat

**Comment by Yttriums** [comment]
> I see the point of making magazine loading slower, but I'd be wary of drawing comparisons to real life 

When we can simultaneously deepen the game's simulation aspects and address unbalanced items at the same time, that's a good change imo.

**Comment by lbnesquik** [comment]
> > I see the point of making magazine loading slower, but I'd be wary of drawing comparisons to real life
> 
> When we can simultaneously deepen the game's simulation aspects and address unbalanced items, that's a good change imo.

We are absolutely not doing any simulation.

**Comment by Yttriums** [comment]
> We are absolutely not doing any simulation.

Simulation in the sense that it's used in the immersive sim genre of games, not in an arma sense or whatever

**Comment by Helg2** [comment]
Should probably also have the varying delay depending of firearms skill.

**Comment by 00ze-cyclone** [comment]
Refilling your mags with ammo packets already require you to put away your gun to do it, you already cannot do it mid combat.

**Comment by InterroLouis** [comment]
If you can record your screen like this, then why not do that during an actual round? Just about anything is a viable and good thing to do against an enemy that doesn't move or react or fight back. I wish to see you use this against actual xenomorph players.

**Comment by Yttriums** [comment]
> Refilling your mags with ammo packets already require you to put away your gun to do it, you already cannot do it mid combat.
Almost every required action is hotkeyable with 0 delay. It's possible during combat, and people do it.

> This is balancing enough IMO not only like stated does it take muscle memory to do this well

The average ss13 player would be impressed by the muscle memory of a toddler. It's not hard to do if you've ever played a fighting game, played an instrument, touch typed, etc. You don't deserve to 4x your ammo just for getting a few keystrokes under your fingers.

>It's not like every marine does this
True, only the sweats

 > most just bring ammo boxes with mags so making it more time intensive when it's not even that big of an effect 

Ammo packets allow you to carry a full magazine box worth of ammo using only a pouch slot and general armor storage in many cases. Ammo boxes can at least be melted, flung off tad, lost or left behind.

**Comment by lbnesquik** [comment]
I don't think most people do it.

**Comment by Weedmaster77** [comment]
> You don't deserve to 4x your ammo just for getting a few keystrokes under your fingers.

IMO you do when someone can just stand over or around an ammo box and Tac reload from it, giving you like 30x more ammo and not taking almost any button presses. Compared to unloading a mag, swapping hands, holstering your weapon, taking a box out, and refilling a mag, then putting ammo box away, and reloading the gun. Thats seven actions to just one, compared to tac reloading. 

> True, only the sweats

My argument exactly taking something that almost no one does and making it something no one will do when it's not a real issue.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
