### PR TITLE
Mining Drill Locations

### PR DESCRIPTION
**Pull request by Hathkar**
## About The Pull Request
Every map in rotation now has 4 mining drills. 3 phoron, 1 platinum.

## Why It's Good For The Game

The purpose of the mining drills are to make marines push out of the FOB in order to get more req points. I've moved the drills a bit further away from the FOB, so xenos don't have to FOB camp in order to deny marines the drills.
Some maps had a wild imbalance of drill types and locations. For example, LV had 1 phoron drill and 4 platinum drills.

## Changelog
:cl:
add: New mining drill locations
del: Old mining drill locations
/:cl:

### CODE REVIEW

**Comment by Hughgent** [comment]
#4355 
You've got this other one open as well. Which one will you be keeping?

**Comment by Hathkar** [comment]
Probably this one, since it's gotten more positive reception.

**Comment by Hughgent** [comment]
Keep one and close the other please.

**Comment by Hathkar** [comment]
I've been thinking it over, and the other PR is probably better for the game.

**Pull request closed without merging**
