### PR TITLE
Droppod location now has warning overlay

### PR DESCRIPTION
**Pull request by Runian**
## About The Pull Request
Drop pods now warn nearby marines of where it'll land with an overlay.
Port of https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/31

image

## Why It's Good For The Game
It is annoying when you'll just walking around or standing around and then BOOM random droppod on your face. Now you can stay away from random drop pods instead of pointing and yelling at the droppodder for being mean.

## Changelog
:cl:
balance: Drop pods now warns nearby marines of where it'll land with an overlay.
imageadd: Droppod warning overlay.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Lame

**Comment by Looking4bros** [comment]
What's next, Grenade explosion range indicators? Smh my head.

Also should it be inserted at around line 148 instead of at the very end? seems like the overlays.dm file has some organization to it.

**Comment by yyzsong** [comment]
Lame

**Comment by Technical-l** [comment]
obvious powercreep, this is going to tank the xeno winrate to 0%

**Comment by Clay500z** [comment]
You don't understand, getting fracced from a droppod is sovl, just like getting instantly killed by vali claymore FF

**Review by Kuro020 — APPROVED** [review]
visual clarity good

**Comment by TiviPlus** [comment]
OKAY FINE ILL REMOVE THE SOUL THIS HURTS ME

**Pull request merged**
