### PR TITLE
Adds Canister, Flechette, and APFDS shells to the LTB cannon alongside minor touchup.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Adds Canister, Flechette and APFDS to the tank. If you care about stats click below.
<details>

- APFDS - Works exactly like Flak APFDS outside of higher damage.
    - Damage: 350. Everything else is exactly like Flak APFDS.
- Canister - 
    - Damage: 17 per pellet.
    - Pellets: 40
    - Spread: 180 infront of the tank.
    - Penetration: 40 so it can actually hurt things.
 - Flechette - 
    - Damage: 20 per pellet.
    - Pellets: 16
    - Spread: 90 infront of the tank.
    - Penetration: 30
    - Sundering: 2.5 per pellet.

</details>

LTB no longer stops on click, and will continue flying until it hits something.
Minor touchup to LTB ammo, it now respects the (CALIBER) nomeculutre and is now a 105mm rather than a 84mm. LTB shells have been renamed to LTB 'HE' to represent the fact there are more than 1 type of shell.
Removed the unused CALIBER_84 and replaced it with CALIBER_105 for tank. Also made the unmanned vehicle section of calibers.dm into just being a vehicles section for ease of understanding.

## Why It's Good For The Game
Tank cannon outside of LTB HE fishing (which the target turf nerf makes singificantly harder to accomplish) seems inferior to me to the relatively simple point and click nature of the chaingun. I hope these changes will make it more appealing as the multi ammo weapon with many ammo types to adapt to the situation at hand.
The caliber and misc changes are mostly to make it more flavorful. A 84mm cannon seems kinda silly to me.

## Changelog

:cl:
add: Added three new LTB shells. APFDS, Canister, and Flechette.
balance: LTB HE shells no longer stop where you click.
/:cl:

### CODE REVIEW

**Comment by Kuro020** [comment]
tank loader gameplay about to get interesting

**Review by Kuro020 — APPROVED** [review]

**Comment by Lumipharon** [comment]
I look forwards to 1 hit killing full health crusher with cannister shot

**Review by Lumipharon — CHANGES_REQUESTED** [review]
Ok, I'm 100% for more ammo types, but I do have issues with these.
Cannister and flechette: These scatter from the middle of the tank, so this is visually very strange and unintuitive, and considering you can't hit xenos on top of the tank, this makes cannister shot actually pretty useless since you shoot at literally half the screen so its really only good for FF'ing loads of marines.
Flechette has a small enough scatter to be practical though.
One solution would to use SOM micronade style delayed detonation, although that would make cannister an insta kill weapon again, so kinda skeptical on that no matter what.

APFDS: This is actually both bugged and OP.
The on hit procs aren't named correctly so don't actually apply to any of the heavy_isg ammo types (so currently they don't lose any range by piercing shit). And the new ammo inherits from this nonexistant type, so it actually has no pen/sunder/traits etc.

Once this is fixed  however, this is just a heavy railgun. 100 AP, 100 sunder, pierces everything so you can snipe and insta kill many castes through walls. I'm already trying to nerf normal railgun for this cheese, and this is just a much stronger insta kill version.

**Comment by Pariah919** [comment]
Eh making this made me realize I don't have the motivation for this still.

**Pull request closed without merging**
