### PR TITLE
Buffs boiler glob storage CD reduction

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
Stored boiler globs now reduce the CD of a bombard by 3 seconds. (previously 1.5)
This means that at full glob storage, you are able to fire another glob roughly 2 seconds after the gas dissipates, however you glow like a christmas tree. Pre-buff, this would be somewhere around 22 seconds. 
## Why It's Good For The Game
Fun! But actually provides more reward for the risk of exposing your position, and also the position of any xeno near you. Combined with the relatively low range and extremely low survivability of the boiler when in it's more vulnerable positions due to the lesser range, I believe the reward for full glob storage should be greater. There is, for all intents and purposes(even before boiler got it's range nerfed), absolutely no reason to ever store more than 2 globs, which there is now plenty of reason to do so.

Remember that boiler has miniscope range. It is literally incapable of shooting globs deep into marine positions unless marines are holding a static position with no cades or it gets a lucky shot off right as marines push into where the boiler is currently standing. If you want to do REAL damage as a boiler, you will have to put yourself in risky spots, which the glow from storing many globs will make impossible.
credit to [uaioy](https://github.com/uaioy) for the idea
## Changelog
:cl:
balance: boiler glob storage CD bonus buffed from 1.5s to 3s
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
I could also make each glob glow slightly more if it's warranted.

**Comment by Lumipharon** [comment]
this is like... how it was before, this is just a revert

**Comment by Mannybrado** [comment]
> this is like... how it was before, this is just a revert

https://github.com/tgstation/TerraGov-Marine-Corps/pull/12831/files
this is the last pr to make a change to this file, if this is what you mean then sure

**Comment by ivanmixo** [comment]
100% gas uptime is not acceptable from just a single boiler, guh. The downtime between gas right now is like 7ish seconds last I checked at full glob, you do not need to make it zero.

**Comment by iforgotmeword** [comment]
Not sure how to feel about this but for one boilers get to do more but 80% gas up time seems very unfun (even without accounting for cave chokes)

**Comment by Mannybrado** [comment]
> There is actually zero reason not to, the snipers that are actually threatening have NVG anyway.

The snipers aren't going to be the thing that kills you. Boilers have to get close to shoot into good positions, and when you're at max glow it makes it very easy for a marine to walk up on you and blast you since you can't hide in the dark and you'll glow a little bit from off screen. It will definitely make boilers much better at locking down a chokepoint when marines stop their initial push, but this is what antigas and mimir are for. Also it isn't 7 seconds, it's 23. (screenshot is a second off because it takes like 3 for my computer to screenshot and im not going to get it that precise) 
image

**Comment by Mannybrado** [comment]
Oh, the downtime... uhhh... uhhhhhhh...

**Comment by Runian** [comment]
Having boiler globs with no downtime seems terrible. At the moment, downtime (aka time since gas dissipated) for max glob boiler is 7-9s depending on how lag is feeling that day. This change would decrease the downtime down by 9 seconds to literally 0. There will be no reason to not run full glob.

**Comment by tttruancy** [comment]
Another case where I think we just need to split the difference with the numbers. 1.75-2.25s of reduction would probably be fair and make the caste more fun while not being too oppressive.  Any more than that and you have to start looking at compensatory nerfs.

Ultimately, even on full glow, boiler is the least risky caste in the game because it gibs itself on death. You're only ever risking a larva, and when you die another t2 can replace you (typically) instantly. It's risk/reward mechanics are heavily undermined by that.

**Comment by SimplySmiley123** [comment]
> Another case where I think we just need to split the difference with the numbers. 1.75-2.25s of reduction would probably be fair and make the caste more fun while not being too oppressive. Any more than that and you have to start looking at compensatory nerfs.
> 
> Ultimately, even on full glow, boiler is the least risky caste in the game because it gibs itself on death. You're only ever risking a larva, and when you die another t2 can replace you (typically) instantly. It's risk/reward mechanics are heavily undermined by that.

And it's not like marines really have ways to _really_ threaten you, unless you're wildly out of position surrounded by marines, you can escape pretty easily, while artillery and snipers can't damage you fast enough / hard enough to kill you, at most give you some downtime to rest and heal up (if hivelord / drone is too busy to spare you a second I guess).

**Comment by Kuro020** [comment]
we dont want the ww2 simulator back, no thx

**Pull request closed without merging**
