### PR TITLE
Mini Bull rework and buff

### PR DESCRIPTION
**Pull request by Clay500z**
## About The Pull Request

- Gore: The bull now has poison glands in the roots of its horns that produce Ozelymelon, and the horns double as stingers. i.e Gore charge now also injects 10u Oze (same as Shrike sting). And it also deals 1 second of stagger (-50% damage).

- Headbutt: Stun time 2.5 > 2 seconds. Displacement 2 > 3 tiles (at max speed).

- Plow: Deals 0.2 seconds of stun (disarms whoever is hit), and can't multi-ram anymore.

## Why It's Good For The Game

Bull is objectively the weakest T2 in the game right now, worse than even T1s in most situations. I think one of the bigger issues with it is the fact that its abilities are designed for killing, and yet are also terrible at securing kills. Like man, if a marine enters crit (or even just lays down), its abilities are rendered completely useless, and slashing is generally a bad idea due to its slow speed outside of charges. So, instead of just pure damage, I'm tweaking Bulls abilities to be a mix of damage and support.

- Gore: While the damage is good, gore felt just a little weaker than it should be. The Oze forces the hit marine to slow down and eat meds again, pretty self-explanatory. The 1 second of stagger is there just to weaken a PB right after a successful gore, because walking into a charge just so you can PB the Bull is pretty silly (you just got penetrated by at least 10 inches of horn). Should significantly increase Bulls survivability after good hits.

- Headbutt: Less stun is more fun. The increased displacement also makes it easier for other Xenos to follow up and wombo combo.

- Plow: In practice, Plow simply disarms the marine now. This turns Plow into an anti-aimmode charge meant for causing chaos in unga lines. Though, the bigger reason for the micro stun is to circumvent multi-ram (see low quality video). Multi ram happened because a marine could bounce off a nearby wall and end up right back in front of the Bull to get hit again. But the bouncing off walls was entirely dependent on rng, meaning Plow could deal 15, 30, or 45 damage depending on rng. Neither side likes rng, so away it goes.

https://github.com/tgstation/TerraGov-Marine-Corps/assets/128223413/c23eeaf4-28f4-4f3c-86a8-171b919fc016

I'd also like to make a PSA:
Currently, the Bull primo does not work in Valhalla due to wacky code. It only works if it's acquired normally through upgrade progress. The Bull primo is actually good when its working, so I'm not making any changes to it yet.

## Changelog

:cl:
balance: Gore charge injects 10u Ozelymelon and deals 1 second of stagger
balance: Plow charge deals 0.2 seconds of stun
balance: Headbutt charge max stun reduced to 2 seconds, and displacement increased by 1 tile
fix: Bull can no longer multi-ram
spellcheck: Updated Bull ability descriptions.
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
Did you fix this Valhala spawn issue you mentionned? If no, we'd appreciate if you could make an issue.

**Comment by Clay500z** [comment]
> Did you fix this Valhala spawn issue you mentioned?
Nope, I don't really understand code at all other than the bare bones basics I'm afraid. Forgot to make an issue, I'll make one now.

**Comment by Clay500z** [comment]
> 10u of ozy will fully purge premed. Shrike at least needs someone else to stun or to use their own stun to get time to inject, queen needs someone else to stun (or waste their roar), defiler injects less iirc and is slower and has a massive sprite. The first 2 also have long cooldowns on being able to reuse ozy injection, and have an interruptible channel.

Bull needs 6 tiles of a charging lane, needs someone to be in said charging lane, and needs them to not dodge the charge if they spot it (or they just step away randomly). It also does not get to choose its targets most of the times, and can only charge whoever steps into the lane, which is usually going to be frontliners at full health and premed.

I think it's fair. There's also the more direct comparison of T2 Carrier with Oze huggers that inject 10u, and the carrier can also pick them up to inject 10u per slash.

**Comment by Looking4bros** [comment]
Imagine using long dose premed, lmao. If you premed Oxycodone and wrap everything into the regent canister pouch you can only premed 2 minutes worth at a time (Oxy's OD limit). Just embrace superior painkill, or other low dose medical premeds.

Here's a recipe, 
300u Oxycodone
240u Bicaridine, Kelotane, and Tricordrazine
120u Tramodol
60u Doctor's delight
All that fills out the 1200u of a reagent can. It's a nutty amount of painkill and a solid regular premed, easy to remember when to re up as Oxy gives you BIG LETTERS when it goes in and when it goes out. Two injections will give you two minutes worth of all the chems, as their metabolisms line up at the described amounts.

**Comment by Clay500z** [comment]
> Here's a recipe

Based and oxypilled

**Comment by lbnesquik** [comment]
> Imagine using long dose premed, lmao. If you premed Oxycodone and wrap everything into the regent canister pouch you can only premed 2 minutes worth at a time (Oxy's OD limit). Just embrace superior painkill, or other low dose medical premeds.
> 
> Here's a recipe, 300u Oxycodone 240u Bicaridine, Kelotane, and Tricordrazine 120u Tramodol 60u Doctor's delight All that fills out the 1200u of a reagent can. It's a nutty amount of painkill and a solid regular premed, easy to remember when to re up as Oxy gives you BIG LETTERS when it goes in and when it goes out. Two injections will give you two minutes worth of all the chems, as their metabolisms line up at the described amounts.

How many people actually run this, though?

**Comment by Looking4bros** [comment]
> How many people actually run this, though?

How many people are a suicidal frontliner, WITHOUT actually suiciding? How many people abuse the chem system in all it's glory? It's usually near zero. It's like Vali, very few people push Vali to it's prescribed limits. Why? they either haven't put the time into understanding the system, don't feel like doing the legwork if they do, or don't like change, as change messes with people's muscle memory. The inclusion of Doctor's delight would be a hurdle many people wouldn't jump for the loadout. 

Paracetamol, Tricord, and doctor's delight is a sidegrade to BKTT and is also not usually used. You could do a Paracetamol pill bottle, two Tricord pillbottles, and two MREs in your webbing vest, with two Canteens of Doctor's delight in your helmet, which provides 80 minutes of premed (i think the Paracetamol pillbottle is closer to 120 minutes). The inclusion of doctor's delight is still a hurdle for this chem selection.

A full large beaker of Doctor's delight can be made with a autoinjector of tricordrazine, inject twice, activate the injector in hand, set to 1u injection, inject 4 times, (24u of tricord) go to medbay/bar, and get 24u of Lime Juice, Tomato juice, Orange Juice and milk cream. An easier way of making a lot of Doctor's delight would be to vend an empty Reagent can, and just dumping 30u of the reagents needed. Or if you just want one canteen of Doctor's delight, (40 minutes worth of chem) just use 20u in a large beaker instead of 24 and drop the beaker on the floor for whoever.

Speaking from a Vali point of view, another xeno with Oze isn't notable at all, if i'm running nanites because i couldn't get enough MeraDerm, Oze without Defile doesn't mean anything to me, and if i have enough MeraDerm, i micro dose, and only lose 1-6 u of the stuff.

**Comment by Clay500z** [comment]
> This PR has been inactive for long enough to be automatically marked as stale.

caption-1

**Comment by Clay500z** [comment]
I am now going to shitpost in the comments every day until this pr gets reviewed. 
336387870_preview_Recettear Atmosphere Characters

**Comment by Clay500z** [comment]
RDT_20220323_2228472402914108699787639

**Review by ivanmixo — APPROVED** [review]

**Comment by zzurge** [comment]
Im glad bull wont be a non evo atleast

**Comment by Fawcksy** [comment]
Not entirely sure how I feel about ozy charges but honestly this doesn't sound half bad, let's see how it works in practice.

**Pull request merged**
