### PR TITLE
Las pouch

### PR DESCRIPTION
**Pull request by David-Stormwell**
## About The Pull Request

-Redo of PR #12896 because I'm stupid and stuff, additionally gives each lasgun a sprite icon when hooked up courtesy of OrcaOrca.

Gives Lasguns a universal pouch for all your energy needs! Pouches are equal to 4 cells and may be recharged at the Lasgun cell charger box.
Nutshell: Lasgun pouch which may be linked to a gun or used to charge respective cells.

## Why It's Good For The Game
A needed addition for the lasgun fan club, as they're lacking in that department and currently being overlooked heavily by other guns, now I don't expect the guns to be used too much more but it should be the start of something better.

image

## Changelog

:cl:
add: Added a Lasgun energy pouch which may charge or act as a cell for your TE guns! -Cabled icon sprites courtesy of OrcaOrca.
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
Now combine this with the self-recharging powercell

**Comment by isotope436** [comment]
> Now combine this with the self-recharging powercell

no

**Comment by David-Stormwell** [comment]
this is never going to be merged I'm going to cry

**Comment by isotope436** [comment]
@TiviPlus will this get merged even with the fact it says all these issues are present or is that just because github desktop go brrr?

**Comment by Aporhtonoma** [comment]
finnaly a good pr that reverts those pesky ballon messages(who even uses that i vomit at the mere sight) i like this pr and agree with its rejection for modernity embrace the old ways (you fucked up something and revert everything to paleolithic age)

**Pull request merged**
