### PR TITLE
Increases the cost of the IFF sniper

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
Increases the price of the IFF sniper from 30 to 50 (price subject to change)

## Why It's Good For The Game
20 round mag, high damage, sunder, night vision and IFF
for 30 points

## Changelog
:cl:
balance: increases the price of the IFF sniper
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
It really needs it, it's very difficult to counter mainly because of the NVG.
Autosnipe man just waits for beno to fight an unga, then when they're health is a little bit lower they just open up and beno dies because it is physically very difficult to get away from it.

Honestly the ammo should be 5 points like basic scout ammo. Currently it's 3 points.

**Comment by yyzsong** [comment]
> Honestly the ammo should be 5 points like basic scout ammo. Currently it's 3 points.

wyci

**Comment by Pariah919** [comment]
I could see 40 but not 50 personally.

**Comment by turnop** [comment]
I would vastly prefer T81 to just be straight up nerfed rather than price increase, but it should have both its price increased AND be nerfed

it is absolutely fucking ridiculous that an item that can straight up melt any caste in the game from 3 screens away (or 1 screen, it doesn't matter) costs 3 times less than a b18, and like half of a sadar, which does the same thing but objectively worse

frankly the t81 should just be removed and other marine weapons buffed, snipers in general are complete cancer that make the game less fun for everyone but themselves

**Comment by Lumipharon** [comment]
Autosniper is generally better than a scout though, and easily spammable. Scout is specifically better for chasing and having fat sunder, but that's it.

**Comment by Georgeur** [comment]
Snipers are balanced by scarcity, its one of the few things CM got right with specialists. 
A single sniper is a support burst damage weapon, several IFF snipers at once just increase the level of burst damage, turning it from support, to an offscreen instant crit with no counterplay. 
It's in PR's like this in which we must choose between, fewer snipers, less damage, or heavy damage falloff. 
I support the PR but its more long term beneficial if all snipers would get high damage but heavy damage falloff. 
Good pr.

**Comment by SrSC0ndition** [comment]
Old T81 was perfectly balanced - a better TL127 with semi auto firing mode, 12 rounds, NVG and IFF, costing 75 points
Currently T81 outplays anything from marksman branch, costs dirt cheap(you can buy two just at 1220, without actually dropping on the ground), and is mainly used as a clutch to achieve easy win by famous marine mains
Either nerf it to actually be a 30 points gun, or revert it back into old T81

**Comment by Ragecrabbo** [comment]
make it 75

**Comment by bluezorua** [comment]
personally a sniper with IFF and a sniper with NV should be two separate weapons

**Comment by turnop** [comment]
how has this not been merged yet with a 100% upvote rate, democracy has failed

**Comment by yyzsong** [comment]
> how has this not been merged yet with a 100% upvote rate, democracy has failed

This reminds me of a book i read the other day, George Bradbury's fahrenheit 1984

**Comment by yyzsong** [comment]
Lets go baby balance achieved

**Pull request merged**
