### PR TITLE
Reduce hunter knockdown from max of 6 secs to 0.5

### PR DESCRIPTION
**Pull request by psykzz**
## About The Pull Request

Hunter could knock someone unconcious for up to 6 secs, 2 if running.
This replaces that with a flat 0.5 sec knockdown but only when disarming instead of on harm.

## Why It's Good For The Game
Xeno balance
## Changelog
:cl:
balance: hunter stealth attack changed to flat 0.5 seconds, and only applied on disarm.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
There should be no knockdown at all, really.

**Comment by adamkad1** [comment]
is this gonna make hunter useless?

**Comment by XElectricX** [comment]
No more hunter stun memes. I could cry right now.

**Comment by terranaut1** [comment]
You should probably decrease the cooldown and plasmacost then, otherwise it loses its properties of being able to deal with heavier type marines with slow weapons.
Or maybe give it some AP :)

**Pull request merged**
