### PR TITLE
Autoshotgun has buckshot

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
adds autoshotgun buckshot to the tx-15
120/0/0 and 2 knockback

## Why It's Good For The Game
adds another cqc optino to rival the tx-15 flechette, and gives the tx-15 some stay away power if you need it in a pinch

## Changelog
:cl:
balance: tx-15 has it's own buckshot ammo, deals 120 damage on pb, zero penetration.
/:cl:

### CODE REVIEW

**Comment by InterroLouis** [comment]
Okay but why would anyone ever use this compared to the slug magazine?

**Comment by SplinterGP** [comment]
> Okay but why would anyone ever use this compared to the slug magazine?
> 

Slug doenst stun

**Comment by InterroLouis** [comment]
And neither does this. It just does what slugs do but with one tile more knockback and no penetration.

**Comment by Pariah919** [comment]
might give it stun not sure

**Comment by Gwuhja** [comment]
why would autoshotty need buckshot when theres, i dunno, like 4 other options for buckshot?
t-35 can fire it
t-39 can fire it
ts-34 can fire it
paladin can fire it
tx-15's entire gimmick is that it cant fire buckshot but it can autofire other types of shotgun ammo
seems like powercreep to me

**Comment by SplinterGP** [comment]
> 
> 
> why would autoshotty need buckshot when theres, i dunno, like 4 other options for buckshot?
> t-35 can fire it
> t-39 can fire it
> ts-34 can fire it
> paladin can fire it
> tx-15's entire gimmick is that it cant fire buckshot but it can autofire other types of shotgun ammo
> seems like powercreep to me

every other shotgun can also shoot flechette and slugs, the autoshotty niche is being a magazined shotgun that shoots very fast

**Review by TiviPlus — APPROVED** [review]

**Pull request closed without merging**
