### PR TITLE
Ice colony Edit's

### PR DESCRIPTION
**Pull request by vilereaver41**

### CODE REVIEW

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Add a changelog, post proof of it working and post pictures of your changes please

**Comment by vilereaver41** [comment]
> Add a changelog, post proof of it working and post pictures of your changes please

Fixed.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Thats not how the changelog should look, ours is auto generated and needs a special format
Additionally how did you add 99,462 lines without removing anything, you seem to have broken something

**Comment by vilereaver41** [comment]
> Thats not how the changelog should look, ours is auto generated and needs a special format
> Additionally how did you add 99,462 lines without removing anything, you seem to have broken something

hmm, i didn't change anything significant. Only changed the majority of Reinforced walls that weren't needed to normal walls. and added an APC to LZ. il check it out.

**Comment by SplinterGP** [comment]
probably used byond map editor, use strongdmm or use mapmerge in tools/

**Pull request closed without merging**
