### PR TITLE
add acid well to drones

### PR DESCRIPTION
**Pull request by Dikozda**
## About The Pull Request

lets drones place acid wells.
## Why It's Good For The Game
acid wells are a nice utility and its sad that one of the main builders of the hive does not have access to it while 5 other castes do, also from my experience i almost never see acid wells placed enough or even when they would be most useful.

i hope by giving drones this ability we can get this used more. 
## Changelog
:cl:
add: Drones can now place acid wells.
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
Fire nerf

**Comment by Naaanii** [comment]
Just go hivelord.

**Comment by Breadeagle** [comment]
People will call this powercreep which may technically be true, but also acid wells are like 40% of a drone's max plasma per cast lol

**Comment by ivanmixo** [comment]
You're a tier 1 as a drone, seems kinda moot to compare them to the other builders.

**Comment by ivanmixo** [comment]
@Kuro020

**Review by TiviPlus — APPROVED** [review]
code ok

**Pull request merged**
