### PR TITLE
Fixes Suits, New Helmets

### PR DESCRIPTION
**Pull request by Max-023**
## About The Pull Request
You saw this before. Now it works.

## Why It's Good For The Game
Because I said so.

## Changelog
:cl:
tweak: tweaks suit sprites
delete: deletes the old helmet sprites
add: adds new helmet sprites
/:cl:

### CODE REVIEW

**Comment by TheBimmer231** [comment]
I honestly believe the helmet edit is a downgrade from the original one, the stahlhelm look would look better in a more appropriate unit with armors to boot.

as for the armors I give my greenlight, Kuro's amazing.

**Comment by Max-023** [comment]
The helmets I would disagree. Kuro said himself that the original helmets were an after thought and he put no effort in them and that he doesn't really care about them. While his fully encased helmets are better than his open faced ones and we will be using those, I cannot stress enough about how god awful the current helmets are and how they make me want to look for alternatives. So far I have been very clear in the discord and have been posting updates in the spriter section, getting positive feedback from Kuro, Pixel, and many others.

**Comment by Rohesie** [comment]
TheBimmer is Pixel.

**Comment by TheBimmer231** [comment]
Even considering the lack of effort I still have the same opinion, visually it looks polished already ignoring a couple nitpicks.

**Comment by Rohesie** [comment]
Is this approved or not?

**Comment by TheBimmer231** [comment]
I do not approve of the helmets, that part will have to go.

**Comment by spookydonut** [comment]
@Max-023 merge conflict

**Comment by Rohesie** [comment]
Closing due to staleness.

**Pull request closed without merging**
