### PR TITLE
Lowpop ship pillar

### PR DESCRIPTION
**Pull request by KwinOriginal**
## About The Pull Request

This is a new ship map hopefully suited for lowpop rounds.
Also, Alamo and Normandy were changed slightly to be more of a dedicated Transport/ CAS ship.
I put it up here because I'd like some reviews, suggestions and critique on it since it's my first fully designed map.
Since it's the spawn area for the marines, it would need a code change to toggle between the Theseus and this one, a thing I'm not able to do. So I don't expect the PR to be merged but I changed some files to make it load up on my test runs, these are still in here (parallel to the deactivated ones fom the Theseus).

## Why It's Good For The Game

Theseus feels a bit barren as of today, if there is only a handful of marines there. This ship has only one level and reduced size, so we don't need 100+ players to make it feel somewhat inhabitated

## Changelog
:cl:
add: A new ship map for the TGMC
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Ok, giving it a look right now. Pretty good overrall, there are a couple issues:
- Hypersleep/Cryo inventory consoles are missing, so if someone cryos with stuff on it can't be retrieved by default. (Given its design, one by medical, one by sec checkpoint and one freely accessible standard should suffice)
- The Automated Closet vendors are for most of the wrong type, like engi ones by the spec/leader/smartie rooms and medic's by the engi room. All of them are also charlie, but I can understand as it was someone else's design stupidity.
- The self destruct room placement is a tad weird, also making the only evacuation pod require SD activation to be accessed.
- Tcomms is also way too compressed, but I can understand it requires a ton of components to be fully functional.
- Feel free to remove the canisters by the atmos gas rooms if you want. Even if atmos were functional, the canisters would still be a simply ornamental indicator, iirc.
- There is an useless corridor parallel to maintenance below the FC office. Merge the former two togheter.
- I may hazard saying that due to how shittily shuttle currently work, the normandy may fail without some code adjustments, also their landmark is located 6 tiles below where it should be.
- Dropship collision landmarks are missing too, not that I'd know where it should park in this little house.
- Escape pods are hardcoded and supposed to be 4 x 5 areas iirc, thanks legacy.
- Some core APCs are not properly hardened in the case of a dropship collision.

**Comment by KwinOriginal** [comment]
Thanks for the rapid feedback, I'll write some lines to each point and work on those that I can quickly fix.

> * Hypersleep/Cryo inventory consoles are missing, so if someone cryos with stuff on it can't be retrieved by default. (Given its design, one by medical, one by sec checkpoint and one freely accessible standard should suffice)

Yes, I forgot to add these. Have one in medical storage and then just didn't remember to add the other ones.

> * The Automated Closet vendors are for most of the wrong type, like engi ones by the spec/leader/smartie rooms and medic's by the engi room. All of them are also charlie, but I can understand as it was someone else's design stupidity.

Oof, looks like I messed up, will be swapped correctly. Any idea on how to make general ones? Copy-pasta?

> * The self destruct room placement is a tad weird, also making the only evacuation pod require SD activation to be accessed.

The SD was placed there for no particular reason, I initially didn't want to add one and got convinced to do so. Escape pod next to it was planned, it's intended to be the "Slap the butten then fuck off" escape type. But I can easily slap some standard pods too.

> * Tcomms is also way too compressed, but I can understand it requires a ton of components to be fully functional.

This was because I didn't unterstand how comms worked. It was at the end of the map design that I understood I need all of those damn parts. So I cramped them in. Will look if I can free some space.

> * Feel free to remove the canisters by the atmos gas rooms if you want. Even if atmos were functional, the canisters would still be a simply ornamental indicator, iirc.

I like those c:

> * There is an useless corridor parallel to maintenance below the FC office. Merge the former two togheter.

Urgh, I hate this corridor. Yes.

> * I may hazard saying that due to how shittily shuttle currently work, the normandy may fail without some code adjustments, also their landmark is located 6 tiles below where it should be.

Because it is too small? Or because of the multiple attachment points? Landmark will be moved.

> * Dropship collision landmarks are missing too, not that I'd know where it should park in this little house.

Forgot to add them, will be done.

> * Escape pods are hardcoded and supposed to be 4 x 5 areas iirc, thanks legacy.

I didn't know. Damn. So the SD shuttle won't work the way it is now? 

> * Some core APCs are not properly hardened in the case of a dropship collision.

Which one should be hardened? CIC? SD?

**Comment by Ghommie** [comment]
> 
> Oof, looks like I messed up, will be swapped correctly. Any idea on how to make general ones? Copy-pasta?
> 

You could make a general type of clothes vendor for engi/medic/spec/smartie/leaders and then subtype the current ones to them. But yea, that's mostly some work with copypasta, plus some map changes on the Theseus.

> 
> Because it is too small? Or because of the multiple attachment points? Landmark will be moved.
>

It's some hardcoded stuff with coordinates, maybe someone such as spooky may help you more on that field.

> 
> Which one should be hardened? CIC? SD?
>

CIC, Tcomms, SD, Ares (?). That's those.

**Comment by Ghommie** [comment]
Another thing I forgot to ask. are the tank and tanker quarters present somewhere on the map? If not and you don't intend to add them, you may want to ask someone to port the map config settings for available jobs (or guide you through it) so we don't end up with tankers having no tank to man up for the time being.

**Comment by KwinOriginal** [comment]
Good that you mention it, tank is left out on purpose because I thought it's not working that we'll during lowpop. I'll ad that to the description once I'm back at my pc, thanks

**Comment by Jalleo** [comment]
Technically telecomms can be setup to work as only a five unit system. That would make it much smaller. You could remove the server that saves chat to reduce it to four. It probably requires a new subtype to set it up though for each unit.

**Comment by DominikPanic** [comment]
> 
> 
> Technically telecomms can be setup to work as only a five unit system. That would make it much smaller. You could remove the server that saves chat to reduce it to four. It probably requires a new subtype to set it up though for each unit.

Or just use the /allinone once I finish the /tg/ port

**Comment by KwinOriginal** [comment]
I'll leave the Tcomms as they are and wait for your tg port then, La.
Sadly, I hade as good as no time at all to discuss and work with all of you this weekend, I'm sorry about that.

**Comment by Ghommie** [comment]
Actually, they completed the day before, so go ahead when you have free time.

**Comment by DominikPanic** [comment]
DNM since map freeze

**Comment by Rohesie** [comment]
I love this new map. Hope shuttles get ready soon so we can play it.

**Comment by DominikPanic** [comment]
Use mapmerge

**Pull request closed without merging**
