### PR TITLE
Medicine now doesnt heal you for 4 seconds if you get slashed/shot

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Tittle

## Why It's Good For The Game

Xenos struggle to deal with marines that armor stack and use heal chems, so instead of trying to deal with 5600 different chem mixes and endlessly nerfing them, this pr removes the problem completely

## Changelog
:cl:
balance: Medicine now doesnt heal you for 4 seconds if you get slashed/shot
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
A way for xenos to be informed that if a marine has medicine in them would be good, too

**Comment by usnpeepoo** [comment]
Fuck yeah

**Comment by KeRSedChaplain** [comment]
I feel like all this will affect is the vali kit

**Comment by Arturlang** [comment]
> I feel like all this will affect is the vali kit

I don't think vali actually uses the chemicals to heal, but simply directly heals you.
But this is a very big nerf to people who use chems to tank and just push ahead because they can't be hurt while they are premedding and using RR

**Comment by Tommy-211** [comment]
We know you are annoyed because you died, but what the fuck?
Why would you do this, you are shitting on 3 different methods of marine survival without being utterly buttfucked by xenos instantly
The three methods you are nerfing like a cretin:
Premed
Nanites
Vali

WHAT THE FUCK.

**Comment by SzkieletorNutric** [comment]
bruh

**Comment by Pariah919** [comment]
This is funny and will most definitely lead to even more passive gameplay, tm it

**Comment by Tommy-211** [comment]
-marks my point as abuse, sure nice xope pr tivi, what next are you gonna fuck marines into the dirt more just to find that the fact is, xenos fucking suck and the game and need time to get better rather than giving everything to them on a silver fucking plate?

**Comment by coldironwarrior** [comment]
i'd be interested to at least see this to see if it HELPS, but i think it'll just make marines into lazy boring slugs that are harder to fight and less fun to play as

**Comment by verywhiterabit** [comment]
4 seconds seems kinda excessive, as far as keeping marines from healing through dogpiling I think you could halve this to something like 2s and still effectively keep a marine from using harmor and meds to tank

main issue I think is 4s per attack is going to make normal healing much more annoying as you will, as others have mentioned, play infuratingly passive just to get your heal ticks

**Comment by Mrrpip** [comment]
Hm. Is there a check to see if an attack does any damage to begin with? It might be a bit awkward for Hod users.

In other news to keep in mind, Doctor's Delight, while weak will not be affected. (It's /reagent/consumable/drink/ not /reagent/medicine)

And...Depending how the latest nanite rework goes, that might be gimped or not affected as I believe that changes it's category too.

**Comment by BoltedAirlock** [comment]
> I don't think vali actually uses the chemicals to heal, but simply directly heals you

I think it sort of does actually; the chems are injected alongside the greenblood heal last I knew, so vali users will have their healing factor suddenly drop from the gentle caress of a drones claws, but probably not by much.

**Comment by novaepee** [comment]
This PR might actually answer the problem with premed. Xenomorph players can finally sigh of relief.

**Comment by Looking4bros** [comment]
I've thought to simply make some Xeno chems react with marine chems, and turn into toxin, (which does .5 toxin per tick or so) the ratio's would be important. And it would actually stop Vali heal's boosts, as it requires the chems to be inside the mob's system, but Reactions happen before the vali chem boost check.

**Comment by Woker2004** [comment]
> I've thought to simply make some Xeno chems react with marine chems, and turn into toxin, (which does .5 toxin per tick or so) the ratio's would be important.

This would be the better solution in my honest opinion, the amount of FF as is would make it damn near impossible to ever heal

**Comment by DeltaFire15** [comment]
> This PR might actually answer the problem with premed. Xenomorph players can finally sigh of relief.

It does. Into the complete opposite direction. Now, if you get simply poked, your meds will magically stop doing anything for *four seconds*, including emergency meds designed for use in heated situations (RR, inaprov),
Chems designed around *upkeep* & active maintenance (Nanites),
**Painkiller**, the type of chem that is exactly for cases where you are suffering pain..
hypervene in you to purge the xenochems (that still process by the way)? Nope, sorry pal.

This is a blanket nerf that is complete overkill and could be handled in a much more granular way instead of completely removing any notion of sustain marines have.

**Comment by Woker2004** [comment]
> Xenos struggle to deal with marines that armor stack and use heal chems, so instead of trying to deal with 5600 different chem mixes and endlessly nerfing them, this pr removes the problem completely

So as a maint, your solution is to simply do the lazy and cope way instead of needing individual medicines? Make it so medicine stacking can cause something like minor screen shake, this is significantly lazy and dumb to stop healing from being slashed once or shot once.

I am aware if you play marine you'd realize how often marine can and will FF, and as xeno this just encourages hit and runs and not actually trying to run and kill. 

On top of that your basically just making a stupidly free Ozy slash

**Comment by PibeCantina** [comment]
This also makes defiler (or oze/defile at least) near useless because you already get the same effect by just slashing them once.
Even as a xeno main i dont like this, or not like it's being done here.

**Comment by iskanderone** [comment]
possible suggestion to make this more palatable: make chems process half as much per tic while the stalled heal effect is ongoing, that way extreme chem waste is not happening

that being said, this is kind of a huge sentinel buff. if you're taking damage constantly from a single spit, you're basically unable to heal until you resist the toxic spittle off

**Comment by Woker2004** [comment]
> i support this change regardless as a marine player, there's a bit too much aggro play from marines right now and constantly ticking heal rate kind of encourages this behavior

I will state this, you can just add a effect that makes chems process at like 80% effectiveness instead, but this is overkill, this also makes CM just look more balanced

**Comment by Tommy-211** [comment]
> This PR might actually answer the problem with premed. Xenomorph players can finally sigh of relief.

How is premed a problem

**Comment by Woker2004** [comment]
> How is premed a problem

It never really was in my opinion, at worse you waste medicine, at best you'll slowly heal, but this PR just would encourage slowpushing every game, it's pacing would be slower than CM which is what TGMC was made to try and avoid

**Comment by TellyLsc** [comment]
4 seconds, isn't that a loss of 2 (bicard/kelo)+1 (tricord) damage healed of the whole 75/60 (bicard kelo/tricord total heal per 15u over 150 seconds) each time this procs? Might be pretty annoying with ranged castes hitting you for 5 damage just to stop chem heals but meh, sentinels and spitters are considered underpowered anyway right?

**Comment by Wisemonster** [comment]
As a note, this will nerf vali if the user uses chems in their module.

**Comment by Looking4bros** [comment]
If you so wish to pursue the chemical reaction route at all in "code/modules/reagents/reactions/other.dm"
you can find the following
/datum/chemical_reaction/toxin_two //Space Atropine!
	name = "Toxin"
	results = list(/datum/reagent/toxin = 3)
	required_reagents = list(/datum/reagent/medicine/synaptizine = 1, /datum/reagent/toxin/xeno_neurotoxin = 8)

which is a simple potential way to mitigate people who premed, as reactions also take place instantly. Whatever ratio you would like to try for xeno chem to marine chem would be pretty important. may have to set it as low as 0.1u marine chem to Xu xeno chem. as without going as low as that you could bypass it with micro injections.
it would let you dictate what chems screw over the marine more, or not at all.

**Comment by BonkaiB** [comment]
Dislike how this is just a huge blanket rather than a gradual see what works and what doesn't, All this is gonna do is encourage an even slower pace in matches, make slowpushing/passiveness even more common (which imo is the least fun type of pushing to fight against as a xeno, granted that type of push won't happen 100% of the time and of course some exceptions). even a machete i'd think would be better than a sledge hammer, i'm of course not a coder and respect people who put their time into this and i can only recommend rather than take action myself but. I feel like a system where it debuffs you for premedding, be it speed or their chems purging upon taking damage for x amount of seconds, would be somewhat better than just a flat out no healing for x seconds even if unstackable. or make the debuff for overmedding more severe since atm (its just rainbow screen and loss of control for 0.2 seconds) 

This gets a boowomp from me :((

**Comment by zzurge** [comment]
First they came for the ability to make chems,then they came for the chems themselves,then they lemolocked the good stuff yall should just cut chem out at this point,there isnt much left to nerf

**Comment by ilikesaying** [comment]
Will anything be done about the Valkyrie Module and B18's medicine injectors as their function is to inject medicine when the user reaches a certain threshold of damage/pain for immediate relief to the user, which will now take 4 seconds of non-combat to take effect?

**Comment by SimplySmiley123** [comment]
Tbh I can't really see it doing much but force marines to play even more passively overall and not just the rushing ungas that almost always die.
This does also ruin the point of the Valk module and B18 now that I think about it as well as fucks over medical doctors that use chems to heal people anywhere near the frontline.

Plus, 4 seconds feels like overkill when xenos already have tools to secure kills consisting of bullshit stuns and knockdowns, and in general throwing ungas around like no tommorow.

**Comment by Tommy-211** [comment]
standard (7)

**Comment by chizzy376** [comment]
4s means that chems are completely pointless
Prekit era starts NOW

**Comment by Tommy-211** [comment]
presplint meta

**Comment by chizzy376** [comment]
> I've thought to simply make some Xeno chems react with marine chems, and turn into toxin

Ozy sting and defiler.

**Comment by Yttriums** [comment]
Lord help Marines if good xenos ever show up again. Hope you like sitting on an MG and shooting walls because that's all that'll be left of the game.

**Comment by efzapa** [comment]
> This PR might actually answer the problem with premed. Xenomorph players can finally sigh of relief.

who's gonna tell him about defiler and the 3 different castes with ozy

**Comment by SimplySmiley123** [comment]
> > This PR might actually answer the problem with premed. Xenomorph players can finally sigh of relief.
> 
> who's gonna tell him about defiler and the 3 different castes with ozy

As if xeno players care what their team has.

**Comment by efzapa** [comment]
> > > This PR might actually answer the problem with premed. Xenomorph players can finally sigh of relief.
> > 
> > 
> > who's gonna tell him about defiler and the 3 different castes with ozy
> 
> As if xeno players care what their team has.

punishing marines for a xeno skill issue? classic

**Comment by Tommy-211** [comment]
Just close the fucking pr

**Comment by Tommy-211** [comment]
image

just close all of these while you are at it

**Comment by MLGTASTICa** [comment]
Even as a xeno main i do not believe this is the proper way to fix the issue. The issue itself is started by aimmode(which allows big clumps of marines to just do outrageous amounts of DPS at any direction without care for FF).
Another way to deal with the chem spam issue is to just have meds do less healing whilst someone is not resting(could even make beds/sofas/etc give buffs to this , making chems heal more and making fights closer to the FoB be more advantageous for marines)

**Comment by Lumipharon** [comment]
This has larger implications for gameplay beyond simply reducing marine peak tankiness, which I think will be quite negative.

Also with RR dead, that peak tankiness is like half of what is was, if not less.

**Pull request closed without merging**
