### PR TITLE
Properly Buffs/Nerfs the LMG

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

(-) LMG fire delay increased from 0.2 seconds to 0.25 seconds.
(-) LMG now slows you by 10% when not aiming.
(-) LMG increased aiming slowdown from 10% to 15%.
(-) LMG accuracy reduced from 1.05 to 0.75.
(-) LMG scatter increased from 15 to 35.
(+) LMG now gets a stock bipod.
(+) LMG damage multiplier increased from 0.85 to 1.
(+) LMG unwelded recoil reduced from 5 to 4.

(+) Removed slowdown from bipod.

## Why It's Good For The Game

The LMG is bad in several ways. Even after the pre-merge nerf, it's just an awfully balance gun for what it is. A damage malus doesn't make any sense at all, and there are other values you can touch that can make it a balanced gun, which is what this PR basically does. My philosophy is that the PFC standard-issue guns should all be pretty much the same in power but exceed in different areas and fail in others. Guns shouldn't be direct upgrades of eachother. The goal here is to make the LMG better than an assault rifle when deployed with a bipod, but weaker when it isn't.

## Changelog
:cl: BurgerBB
balance: Reworks the LMG again.
balance: Removes slowdown from LMG.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Rohesie** [comment]
This will need input from more players.

**Comment by Kuro-ai** [comment]
remove the fire delay nerf and the stock bipod and the changes are fine,the lmg's whole point is being great at autofire,giving it 0.3 fire delay just kills the gun

**Comment by Pariah919** [comment]
still personally dislike this but if other people want it then sure. Even with the changes.

**Comment by Mr-Worth** [comment]
I think this should at least be TM'd. Currently watching the games and the LMG has massive area control and damage ability.

**Comment by Kuro-ai** [comment]
after playing with it the scatter needs to be reduced,shit is insane,you can't hit a straight shot to save your life

**Comment by Kuro-ai** [comment]
just noticed but this gives 1.75 slowdown on wield which is way slower THAN THE MINIGUN,that is terrible,reduce that shit

**Comment by Rohesie** [comment]
This is currently TMed. Please provide further feedback.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
