### PR TITLE
widow can now (very slowly) lay weeds

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Widow now has very, very slow weed laying. 30 second cooldown.
## Why It's Good For The Game
Gives widow the ability to have some utility on lower populations, and also set up burrow/ambush sites better on their own.
## Changelog
:cl:
balance: Widow has weed laying, but it is very high cooldown per pod.
/:cl:

### CODE REVIEW

**Comment by Zangeiti** [comment]
powercreep much

**Comment by Oscari-pog** [comment]
Why are people so insistent on buffing widow when it already is the scariest xeno to encounter when not in a ungaball

**Comment by KerbalCitizen** [comment]
> Why are people so insistent on buffing widow when it already is the scariest xeno to encounter when not in a ungaball

It's pretty easy to 1v1 widow if you have slugs. Fire and explosions work pretty well on it too. I would rather fight widow in a 1v1 instead of ravager or defiler.

**Comment by FosterGrime-Heymynameslouie** [comment]
cool pr
honestly unsure why it wasnt a part of widows kit in the first palce considering it evos from a weed caste

**Comment by TiviPlus** [comment]
textbook unneeded creep

**Pull request closed without merging**
