### PR TITLE
engineer, corpsman, SG, & SL have 1,000 hours rank

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

Make TGMC marine players play a total of 5,000 hours to get new ranks

## Changelog

:cl:
add: engineer, corpsman, SG, & SL have 1,000 hours rank
/:cl:

### CODE REVIEW

**Comment by Strayed-Raven** [comment]
We now need a 1,000 hour rank of COLONEL for FC. ADMIRAL for Cap.

**Comment by novaepee** [comment]
> We now need a 1,000 hour rank of COLONEL for FC. ADMIRAL for Cap.

One PR at a time.

**Comment by Strayed-Raven** [comment]
> > We now need a 1,000 hour rank of COLONEL for FC. ADMIRAL for Cap.
> 
> One PR at a time.

Agreed. Also I do not think FC should go higher than Colonel. Colonel just sounds best really.

**Comment by isotope436** [comment]
what ranks did you add?

**Review by ivanmixo — APPROVED** [review]

**Comment by Sirsnek15** [comment]
If you're going to add NEW super ranks for specialized roles, they really should be 500 rather than 1000. Squaddie has a 1000 hour requirement for the super paygrade, and due to the established significance of seeing a MSGT, its too late to change it to 500, and I think 500 would be better for starting new paygrades off on the right foot.

**Comment by Derrick2Electricboogaloo** [comment]
I want my 500 CSE hour mark

**Pull request merged**
