### PR TITLE
Renames Gorger as Voreger

### PR DESCRIPTION
**Pull request by Xander3358**
## About The Pull Request
Atomization: https://github.com/tgstation/TerraGov-Marine-Corps/pull/13317
Renames gorger to voreger

## Changelog
:cl: Xander3358
fix: renames gorger as voreger
/:cl:

### CODE REVIEW

**Comment by aarrisu** [comment]
I HATE VORE!!!!

**Comment by lKiseki** [comment]
mods crush his skull thank you

**Comment by Xander3359** [comment]
Who the fuck is this 😂

**Comment by JohnFulpWillard** [comment]
Lgtm

**Comment by Tommy-211** [comment]
Starting to think lancet was onto something

**Pull request closed without merging**
