### PR TITLE
Synthetics can have hair again

### PR DESCRIPTION
**Pull request by Losenis**
## About The Pull Request
Command remembered wigs are a thing

## Why It's Good For The Game

Lorewise, wigs exist. If neon hair is an issue, maybe remove the ability to have neon as hair color for everyone.

## Changelog
:cl:
add: Synths can now have hair.
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
Why not give late synthetics hair back whilst keeping early synthetics bald? It makes sense if we look at stuff such as Alien Isolation where the Working Joes are bald metallic men, and actual synthetics are perfect replicas of humans. It would also help further differentiate what has for the longest time been nothing more than a colour choice between Grey or your chosen skin colour.

**Comment by Losenis** [comment]
Sounds like even less of a reason to play early synth if on top of being broken on the engineering skill it's also permabald

**Comment by bowlofcereal** [comment]
Frankly I think bald synthetics vastly improve the immersion of the game. Do not @ me, this is just an opinion that is most definitely a fact. Bald synthetics are the best thing to happen to this game since the afflictor testmerge. Possibly even better then the full auto m4a1!!

**Comment by Al-1ce** [comment]
I am _SERIOUSLY_ tired of these passive aggressive synth femstatics. I hate them all. Every single fucking one of them. Being bald sucks but it's the only way to kill them off.

**Comment by DerpiestBruh** [comment]
And here begins the war of people trying to bring back colorful pixels of a game character and the ones who are against it

**Comment by Kuro020** [comment]
@Pariah919 if you want to end the femstatic synths meme then make them robot race or something, making all of them bald is dumb as hell, and as such

**Pull request merged**
