### PR TITLE
Re-ports Xeno Sprites + General Cleanup

### PR DESCRIPTION
**Pull request by Alterist**
:cl: Alterist Spriter - ARefrigerator (Fridge)
imageadd: changed the 2x2 xeno icons back to the most modern sprites and 
imagedel: deleted some outdated sprites, and extra defiler files
/:cl:

due to recent discoveries by Drawsstuff we found out that we could use these sprites, rejoice!

### CODE REVIEW

**Comment by Rohesie** [comment]
You seem to be deleting crusher sprites and forgetting drone and hunter ones.
Intended?

**Comment by Borisvanmemes** [comment]
I like the old ones more tbh.

**Comment by Surrealaser** [comment]
Definitely use the old Carrier; new one doesn't look so hot.

**Comment by Rohesie** [comment]
This can't be merged without the new damage overlays.

**Comment by Alterist** [comment]
damage overlays can be left blank if sprites for it aren't made yet

**Comment by Alterist** [comment]
Made changes accoding to democracy votes, prae will remain the new one, to distinct them from the queen

**Comment by DominikPanic** [comment]
> 
> 
> Made changes according to democracy votes, prae will remain the new one, to distinct them from the queen

Democracy is an illusion. On a more serious note, thank you.

**Comment by Rohesie** [comment]
Are the mismatching wounded overlays removed?

**Comment by Alterist** [comment]
Not yet, will fix

**Pull request merged**
