### PR TITLE
Brings the medic medkit pouch in line with the advanced autoinjector pouch

### PR DESCRIPTION
**Pull request by Ldip999**
## About The Pull Request

The medkit pouch now contains an advanced quick clot+ injector (30u qc+) and an advanced peridaxon plus injector (6u peri+ 12u hyronalin). Removed an advanced brute and burn kit to make space.

## Why It's Good For The Game

Currently the medkit pouch for corspman is inherently inferior to the advanced autoinjector pouch, as it lacks these two chemicals. People who choose to go with a medical pouch/prefer advanced injectors over autoinjectors for any reason has to go through the tedious process of emptying the autoinjectors into the advanced injectors every time, bogging down prep. This PR brings the medkit pouch in line with the exact same amount of reagents as you would get using the autoinjector pouch (except the dexalin and the oxycodone, dexalin is... questionably useful in rare, edge case scenarios, and oxycodone can be aquired for free in infinite amount). We get enough advanced kits anyways from the free advanced medkit everyone gets as part of the corspman essentials, not to mention them being free in generous amount in the marinemed vendor. Doctors' (Synth, MD, RSR, and CMO) medkit pouches remain untouched to avoid powercreep, as these roles have no inherent access to the advanced autoinjector pouch. 

## Changelog
:cl:
balance: Medic medkit pouches now contain QC+ and Pe+ exactly like the medic autoinjector pouch
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
Just so you know, Hyronalin doesn't purge the toxins that Peri+ makes, I've never felt inclined to make a change as i pwrgame and use the Hyronalin for other purposes when vali'ing as hard as i can.

I think it was 9u of Dylovene sucessfully purges all the toxins, but it might be 10 or 11u, it's been a while. Rye would work if the consumer doesn't have Bicaridine, Kelotane, or Tricordrazine in their system, as it will purge the Rye before it does the job.
A partially full pillbottle may be a better fit than a hypospray, though i am partial to hyposprays myself. Also makes it harder for newbies to double dose people, or mess with the injection amount. Though, Peri+ is the best killer of the deathsquad when in hypospray form.

**Comment by Ldip999** [comment]
I know, hyro isn't a complete solution, the main thing was to bring it in line with the advanced autoinjector pouch, which has peri with hyro. Pill bottles feel too big for just a mere couple units of juice, hence why it's just an advanced injector.

**Comment by efzapa** [comment]
does this mean CMO finally gets good chems? based

**Comment by Looking4bros** [comment]
> does this mean CMO finally gets good chems? based

Vro, just use your Lemoline.

**Comment by efzapa** [comment]
> > does this mean CMO finally gets good chems? based
> 
> Vro, just use your Lemoline.

gotta use it for meraderm smh

**Comment by Looking4bros** [comment]
> gotta use it for meraderm smh

This is true, but the only other chem you might really need is Peri+, and you just blend some Phoron and a Rye pill from the Toxin first aid kit and you're good.

**Review by Kuro020 — APPROVED** [review]

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
