### PR TITLE
Increases stimulon gain per reaction.

### PR DESCRIPTION
**Pull request by Coastfront**
## About The Pull Request
Does whats on the tin, nothing more. Buffs the amount of stimulon you get per reaction from 1 to 10. Giving you 10 doses.
 

## Why It's Good For The Game

Stimulon, is a borderline shitpost meme chem that you don't even get to fuck around with if you make it because you get a literal single dose ever.
In fact, I am willing to bet many people reading this, wont even understand how bad it is, since ive literally seen it used once ever other than me making it.
Simulon: costs a LITERAL ENTIRE BOTTLE OF LEMOLINE. it takes, around 28-29 units of lemoline total. It needs 10 parts synaptizine, 20 arithrazine, and then 20 parts nutrient on top of another 20 parts of lemoline. Counting the cost of its components, that is around 28-29 units total.
For all of this, you get exactly 1u of stimulon.
The, only positive effect stimulon has, is massively buffing your movement speed, which, reminder, you instantly lose all of that buff from basically any level of pain.
Now what are its drawbacks again exactly?
Stimulon deals, fairly constant, severe brute at random with ticks, deals 10 cloneloss on application and then 0.05 cloneloss per tick that, do note, multiplies the longer its in your system. The brute it causes, also causes pain. On top of this, your stamina cant regenerate without extra chemicals while taking it.
In practice, to put in perspective exactly how bad stimulon is, in a local test, i injected stimulon into myself. Within 23 seconds I had 52 brute and nearly 30 cloneloss. Where, comparatively, if you want to chase things/go fast, you can: Get a bike for no cost, or use synaptizine. one of its literal ingredients. 
If you spend all of your lemoline on making synaptizine, you get 15 2u doses.
If you can, somehow, survive a single dose of stimulon and have it have been a good use, while then spending the GIGANTIC recovery time from the mountain of cloneloss you'll have, this at least means that you didn't spend 80 req points on a single use of a meme chem that has next to no viability in combat.

## Changelog
:cl:
balance: increased stimulons reaction production from 1 - 10.
/:cl:

### CODE REVIEW

**Comment by srxtreme** [comment]
REAL

**Comment by QualityVan** [comment]
You know 1u is already multiple doses of stimulon, right?

**Comment by Coastfront** [comment]
> You know 1u is already multiple doses of stimulon, right?

except for every time in human history byond has a stroke when you inject a decimal of a chemicle into somebody and has a solid chance to just not have it do anything. which is not an immense rarity.

**Comment by QualityVan** [comment]
Just inject more than .1u, that's the threshold at which the chem system cuts you off.

**Comment by Coastfront** [comment]
> Just inject more than .1u, that's the threshold at which the chem system cuts you off.

Then in that case this pr makes it more apparent to the likely audience of people who are going to make stimulon once and then die instantly from it that theres more than one dose of it.

**Comment by QualityVan** [comment]
Also, 30 cloneloss in 23 seconds purely from stimulon is measurably false. On average it's about 13.

**Comment by Coastfront** [comment]
> Also, 30 cloneloss in 23 seconds purely from stimulon is measurably false. On average it's about 13.

I am stating what I experienced when I ran it on local, Injected stimulon, started counting, and before the 30 second mark i had about 25-30 or so cloneloss. so either I was counting fast, but I know for a fact that a minute had not passed. which, is still a fairly atrocious amount of damage when you count in the 5 billion brute damage that it can deal (which then, again, disables its own effects without solid painkillers)

**Comment by Strayed-Raven** [comment]
Ever since the lemoline lock nobody really cares to do much of chem. Do not even know if anyone bothers to use larva to make more. Relying on marine coordination to get something used or if it even makes a difference by the time you can get it is cringe. Researchers dont even bother to keep their bottles at all for anything and just give it to medics. This should be a good change for a chem that comes with downsides and is never bothered to be made for the hoops you go through to even bother to make it

**Comment by Lumipharon** [comment]
I don't know why you're comparing stimulon to synap when they do entirely different things. And as QV has pointed out, 1u is not 1 dose.

**Comment by Coastfront** [comment]
> I don't know why you're comparing stimulon to synap when they do entirely different things. And as QV has pointed out, 1u is not 1 dose.

well then to answer the comparison, in terms of "chemical that grants enhanced mobility" synaptizine lets you shrug off stuns faster and gives better stam regen, whereas stimulon is just a speed buff. both of them in some way enhance your ability to move in a fight.

**Comment by Xander3359** [comment]
Just PR deleting it tbh

**Pull request closed without merging**
