### PR TITLE
Adds TX-12 Battle Rifle

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Adds TX-12 Battle Rifle, based on SHak-12 (ASh-12).
Ultimate sunder weapon, has 30 damage, 0 penetration, 4 sunder per bullet, 2 damage falloff, 0.25 sec fire delay. Adds 0.5 slowdown on hit within 7 tile range.
Has stats that make you choose your attachments: 2.5 recoil and 6 scatter, which means you would still have 0.5 recoil after installing one -recoil attachment. IMO this makes choosing attachments a bit less obvious and more interesting.

## Why It's Good For The Game

cool gun

## Changelog
:cl:
add: added tx-12 battle rifle
imageadd: added tx-12 sprites
/:cl:

### CODE REVIEW

**Comment by Araulius** [comment]
I feel this is redundant. this is straight up better sunder than a t-29 smartmachine gun, and from what i'm gathering, if it's an assault rifle, faster RoF than a slug shotgun can put out. marines already have sundering tools.

**Comment by Waselon** [comment]
> I feel this is redundant. this is straight up better sunder than a t-29 smartmachine gun, and from what i'm gathering, if it's an assault rifle, faster RoF than a slug shotgun can put out. marines already have sundering tools. If you're going to add this, it needs a different role. there are other ammo types and guns that fulfill this.

Damage and penetration traded for sunder and slowdown. There are no automatic rifle which can inflict slowdown, only shotguns, repeater and revolvers.

**Comment by Losenis** [comment]
>Adds slowdown

Oh god please no, having just one of these is gonna make an ungaball stupidly powerful. It'd be a death sentence for any xeno that's already slow, and god help them if they're getting slowed already.

>Damage and penetration traded for sunder and slowdown

Please consider that on the second shot it's the equivalent of having 30 damage and 5 penetration because it just tore 5 armor off the xeno, which adds up for every shot every 0.25 seconds up to 20 sunder per second. T12 has 0.5 sunder, and the tx11 which I thoght was bonkers for its firerate only has 1.25. This gun will do lots of damage to xenos with low armor while stripping armor off big xenos so fast that it'll start dealing way more damage than guns with armor penetration due to how fast it'll strip armor, and that's on a 1 on 1 scenario. A crusher charging cades will potentially run out almost dead due to this gun + a few other ungas shooting at it, _withot taking into consideration the slowdown to have it shot up even more on retreat._

**Comment by Waselon** [comment]
> Please consider that on the second shot it's the equivalent of having 30 damage and 5 penetration

Sunder is never 1:1 to penetration, with an exception of fortified Defender

**Comment by Araulius** [comment]
> > I feel this is redundant. this is straight up better sunder than a t-29 smartmachine gun, and from what i'm gathering, if it's an assault rifle, faster RoF than a slug shotgun can put out. marines already have sundering tools. If you're going to add this, it needs a different role. there are other ammo types and guns that fulfill this.
> 
> Damage and penetration traded for sunder and slowdown. There are no automatic rifle which can inflict slowdown, only shotguns, repeater and revolvers.

you are literally just readding the old tx-8 scout rifle impact ammo that was gutted of this a week ago

**Comment by Waselon** [comment]
> you are literally just readding the old tx-8 scout rifle impact ammo that was gutted of this a week ago
> 
> edit: where have i seen this before? #9388

This is nowhere near old tx-8 impact ammo

**Comment by KrabSpider** [comment]
...We have the TX8 for sunder (literally **10** sunder per shot) in req. We also have the fucking TX11 which deals 3.75 per burst. I dont think Marines need anymore high sunder weapons; this is just bloat tbh

**Comment by bowlofcereal** [comment]
powercreep and bloat

**Comment by OpsCoretango** [comment]
Everything can balance on cost.
Excuse, why ZX-76 costs 1 hundred bucks and  worthless piece of craft to his efficiency ? They scared of his double fire and possibilities like masterkey but his wielding time on Oh, god dont kill me.

Same situation is here, if you don't like technical stats of gun just make it too expensive for rare appearance in battle like dreadnoughts, battleship in real world.

**Comment by OpsCoretango** [comment]
Also, why are you not chose the 10x30mm?

**Comment by Waselon** [comment]
> Also, why are you not chose the 10x30(29) mm ? This would be a logical continuation of the company's experiment on automatic large-caliber weapons program.

10x30mm is used in MG-08 heavy machinegun, and very powerful

**Comment by Pariah919** [comment]
```
Adds TX-12 Battle Rifle, based on SHak-12 (ASh-12).
Ultimate sunder weapon, has 30 damage, 0 penetration, 4 sunder per bullet, 2 damage falloff, 0.25 sec fire delay. Adds 0.5 slowdown on hit within 7 tile range.
Has stats that make you choose your attachments: 2.5 recoil and 6 scatter, which means you would still have 0.5 recoil after installing one -recoil attachment. IMO this makes choosing attachments a bit less obvious and more interesting.
```
I don't mind the gun conceptually, it'd probably be better as a seasonal since I feel like autoshotgun slug already fills this overall niche. But recoil is a bad balancing mechanic.
Considering the T-21 Skirmisher is the most obvious comparison- You sacrifice all your pen for 2.75 more sunder, which is noticeable longterm. I don't personally mind this rifle but the sprite needs some work, and its honestly gun bloat. But it might feel unique enough to get added to seasonals atleast.

**Comment by Waselon** [comment]
God, seasonals, so many interesting and good guns are buried there.

**Comment by Redstonize** [comment]
**The TX-15 automatic shotgun** doesn't do enough damage yet. Prove me wrong instead of adding another good gun / seasonal / _unmentionnable req service._

**Review by TiviPlus — CHANGES_REQUESTED** [review]
This gun does not have a mechanics gimmick/niche

**Pull request closed without merging**
