### PR TITLE
Increases bullet and Laser armor on pas-11 and modular exo suit 

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
people said ff was pretty bad

## Why It's Good For The Game
makes ff no longer one shot you

## Changelog
:cl:
balance: jaeger and vest now cap out at 75 bullet/laser armor
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -26. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by XSlayer300** [comment]
Makes them also bullet sponge-y for people who uses HvH combat though.

**Comment by RenGusta** [comment]
Good tbh, HVH smelly

**Comment by jroinc** [comment]
This is high enough that it removes FF as a concern and allows spraying people down with rifle rounds as a valid tactic with no long-term consequences, given that shrapnel does NOTHING unless you run with it unsplinted.

**Comment by psykzz** [comment]
If this happens, it should be temporary, when aim mode or an alternative comes in that gives you IFF, then this should be reverted.

**Comment by Pariah919** [comment]
fixed in another pr aswell
the one that adds armor variance

**Pull request closed without merging**
