### PR TITLE
Nuke gibs

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Makes nuke gibs
## Why It's Good For The Game
I consider this a bugfix
## Changelog
:cl:
balance: Nuke gibs now
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Any increase in the amount of gibbing is good

**Comment by Xander3359** [comment]
> Any increase in the amount of gibbing is good

This game needs more gibbing tbh

**Comment by WinterDarkraven** [comment]
based plsllllls spedmarge nowwwwww

**Comment by fe-ed** [comment]
What about nuke map destroy

**Comment by AzonStarfall** [comment]
Doesn't this cause an apocalyptic end-round lag spike, since minions are included in the gib effect?

**Comment by coldironwarrior** [comment]
no more funny map images of tons of crosses when marines fail to launch alamo in time!!!
not the worst change, but worried about the lag as well.

**Review by Kuro020 — APPROVED** [review]

**Comment by Lumipharon** [comment]
I am somewhat concerned about potentially gibbing 100+ mobs at once

**Pull request closed without merging**
