### PR TITLE
Deletes the engineering dispenser.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Deletes the engineering dispenser.
## Why It's Good For The Game
image
Coders really dislike dispenser. This is the nuclear option.
now it's out of my hands, maintainers can do whatever they want with this PR.
## Changelog
:cl:
del: Deletes Engineering dispenser backpack.
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
image
It's obviously hated by designers. I would rather delete it in one go rather than slowly nerf it into the ground.

**Comment by Pariah919** [comment]
Removing bulky from dispenser would fix a lot of issues. Honestly.

**Comment by Pariah919** [comment]
Removing bulky from dispenser would fix a lot of issues. Honestly.

**Comment by TiviPlus** [comment]
Assuming this isnt a serious pr

**Comment by Xander3359** [comment]
It is a serious PR but ok.

**Pull request closed without merging**
