### PR TITLE
Sting nerfs

### PR DESCRIPTION
**Pull request by Naaanii**
Nerfs Larval and Neurosting

## About The Pull Request

Nerfs Larval and Neurosting to inject 5u per sting.

## Why It's Good For The Game

Larval and Neurosting were way too strong for a 0.5 second channel time and on T1 castes.

## Changelog
:cl:
balance: reduces larval and neurosting amount injected.
/:cl:

### CODE REVIEW

**Comment by BlueHNT** [comment]
It is very much annoying yes, drones are not really meant to be strong in combat as far as I know. The fact that they just run up to you and leave 10u of LA in you which slows you down and gives you jitters ain't exactly definition of "enjoyable" but It is not bad enough to warrant a nerf as while it might be annoying, it needs a bit of managing to actually do as it aint a simple bump attack and timing it is beyond annoying.
So with my thoughts out of the way, I believe it doesn't warrant a nerf just because it's slightly annoying as a slow. With proper teamwork it's also impossible to pull off.

**Comment by davidchan13** [comment]
As someone whos Drone as much if not more than any other xeno caste with 200+ hours in xeno combined, yes. This is actually a good merge. 

Outside scope, but honestly Drone sting could be removed entirely, it's a relic of capture gameplay, Defilers and Carriers IMO should be  the only ones with sting IMO as they are the ones who are supposed to focus on infection/injection gameplay, Queen, Shrike and Drone shouldn't have it anymore. Less buttons to clutter their hud and overall better balance.

**Comment by ilikesaying** [comment]
larval purges medicine at 3 units per tick which is pretty god damn fast

**Comment by davidchan13** [comment]
> larval purges medicine at 3 units per tick which is pretty god damn fast

In context for people not familiar with how meds operate, thats every medicine chem in the system purged 3u every 2 seconds. That's an entire 15u pill gone in 10 seconds (5 chem ticks), if someone popped one each of a Bic, Kel, Tric and Tram pill before a fight, then got LA'd, all 4 of those pills would be gone in 10 seconds when each of them would normally last 90 seconds. 

A single 5u sting metabs at .2u per tick, so one sting will last for 100 ticks and potentially purge 300u of each medicine in a victim if not purged with dylo, hyper and/or ryet. This doesn't just counter premed, it destroys the notion of premed being viable.

**Comment by BlueHNT** [comment]
> > larval purges medicine at 3 units per tick which is pretty god damn fast
> 
> In context for people not familiar with how meds operate, thats every medicine chem in the system purged 3u every 2 seconds. That's an entire 15u pill gone in 10 seconds (5 chem ticks), if someone popped one each of a Bic, Kel, Tric and Tram pill before a fight, then got LA'd, all 4 of those pills would be gone in 10 seconds when each of them would normally last 150 seconds.
> 
> A single 5u sting metabs at .2u per tick, so one sting will last for 50 ticks and potentially purge 150u of each medicine in a victim if not purged with dylo, hyper and/or ryet. This doesn't just counter premed, it destroys the notion of premed being viable.

At this point I would either advise removing it entirely as a remainder of catchplay OR just keep it as is, but either apply it at the end of the of the process line or at the start of the second one. I am saying this as basis from the pure fact that drone should have next to no combat abilities as it is meant to be supportive caste with basic self protection or enough speed to outrun the marines.
But what you have advised would work too but it wouldn't solve that much in the end.

**Comment by Dolth** [comment]
The current larval sting has no windup/channel.

**Comment by Naaanii** [comment]
Drone already nerfed.

This seems unnecessary unless larval sting is getting deleted.

**Comment by Dolth** [comment]
> Drone already nerfed.
> 
> This seems unnecessary unless larval sting is getting deleted, or the speed nerf reverted.

A good amount of castes can instantly inject you with larval accelerant mid-combat and that's still not okay. Keyword, instantly, midcombat.

**Pull request closed without merging**
