### PR TITLE
Makes FOB Drone Console Indestructable

### PR DESCRIPTION
**Pull request by KornFlaks**
## About The Pull Request

Adds flag that make the FOB drone console indestructable from Marine or Xeno action.

## Why It's Good For The Game

No more funny plasma cut or RR at start of round to instantly grief the marine side from making a FOB.
Im surprised it hasnt happened yet and only in my testing that I discovered this.

## Changelog
:cl:
fix: Made FOB drone console indestructable by both marines and xenos.
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
"No more funny plasma cut or RR at start of round to instantly grief the marine side from making a FOB." We have admins for that, they can respawn in it 10 seconds?

**Comment by KornFlaks** [comment]
Admins could respawn it but why is it even destructable to begin with? Admin interaction should not be manditory in game breaking instances if the code itself prevents it. It shouldnt be possible in the first place.

**Comment by BraveMole** [comment]
I don't really see the point of grief-proofing, because there are 100000 ways to grief. 

Even with your thing, nothings prevent an engineer to just eject the mats and hide them?

**Comment by KornFlaks** [comment]
Yes, there are 1001 ways to grief. That does not mean we should just shrug our shoulders and shove the responsibility of making a round run smoothly onto the admins when we could do something about a clearly unintended interaction.

An engineer rapidly ejecting the mats and hiding them is a ingame RP issue. That is intended and often a tactic used by Captains / FCs / whoever to force tadpole or no-FOB operation. Another engineer can just insert their own materials to build a FOB anyways.

Deleting the FOB drone console however is a drastic overreaction to force a tadpole operation and locks a key feature of marine gameplay due to the un-reversable action (by players) from a single individual.

**Comment by AnCopper** [comment]
> I don't really see the point of grief-proofing, because there are 100000 ways to grief.
> 
> Even with your thing, nothings prevent an engineer to just eject the mats and hide them?

What can be code should be code, what cannot be must be policy.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
