### PR TITLE
Skill locks chemistry

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Ungas lack the double digits neurons to use chemistry machines. Fixed this bizarre unimmersive oversight.
image

Also powergaming chem is bad, and just punishes people for not choosing to power game every round.
## Why It's Good For The Game
Powergaming chem is lame.
## Changelog
:cl:
balance: Chemistry machines now require skill to operate
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
skillissue-skill-2517675603

**Comment by Losenis** [comment]
me on my way to PFC+ with corpsman

**Comment by RipGrayson** [comment]
As much as I hate hard skill requirements, this is needed. If PFCs want chem so much they can ask a corpsman or doctor to get it for them.

**Review by TiviPlus — APPROVED** [review]
prolly should change it from skill issue but whatev

**Comment by Losenis** [comment]
> As much as I hate hard skill requirements, this is needed. If PFCs want chem so much they can ask a corpsman or doctor to get it for them.

I'd be more worried about an autistic MO introucing the entire server to powermixes by shitting out 50 pill bottles and giving them away. Or a random corpsman or two doing that in the 20mins of prep after getting a loadout.

If anything the whole powergaming chem shenanigans sound more like prep taking so long that you can actually take the luxury of spending 15+ mins doing the funny. Usually when I join 15 mins in I just take pill bottles, imialky injectors, and drop. It'll be funny to see what 50 bored marines will find in the absolute boredom of prep.

**Comment by Lumipharon** [comment]
> > As much as I hate hard skill requirements, this is needed. If PFCs want chem so much they can ask a corpsman or doctor to get it for them.
> 
> I'd be more worried about an autistic MO introucing the entire server to powermixes by shitting out 50 pill bottles and giving them away. Or a random corpsman or two doing that in the 20mins of prep after getting a loadout.
> 
> If anything the whole powergaming chem shenanigans sound more like prep taking so long that you can actually take the luxury of spending 15+ mins doing the funny. Usually when I join 15 mins in I just take pill bottles, imialky injectors, and drop. It'll be funny to see what 50 bored marines will find in the absolute boredom of prep.

Players doing things to help their team mates is good.
Sweaty powergamer making their own mixes so they can avoid having to rely on team members as much as physically possible is bad.

**Comment by Derrick2Electricboogaloo** [comment]
> As much as I hate hard skill requirements, this is needed. If PFCs want chem so much they can ask a corpsman or doctor to get it for them.

Again, it really is not even an issue when only a few people use the chem machine. Most unga's opt for sticking with BKTT pill packets. I am not for the CMification of TGMC in the slightest.

**Comment by Derrick2Electricboogaloo** [comment]
> > As much as I hate hard skill requirements, this is needed. If PFCs want chem so much they can ask a corpsman or doctor to get it for them.
> 
> I'd be more worried about an autistic MO introucing the entire server to powermixes by shitting out 50 pill bottles and giving them away. Or a random corpsman or two doing that in the 20mins of prep after getting a loadout.
> 
> If anything the whole powergaming chem shenanigans sound more like prep taking so long that you can actually take the luxury of spending 15+ mins doing the funny. Usually when I join 15 mins in I just take pill bottles, imialky injectors, and drop. It'll be funny to see what 50 bored marines will find in the absolute boredom of prep.

Too bad that will probably actually NOT happen. Maybe one every now and then. Most MOs are bald idiots who will never touch chem.

**Comment by ivanmixo** [comment]
Just urging people who wanna do this to take corpsman slots

**Comment by zzurge** [comment]
More ways to turn us into CM 2,a bunch of useless npcs walking round who cant even open pill bottles

**Comment by Naaanii** [comment]
> > > As much as I hate hard skill requirements, this is needed. If PFCs want chem so much they can ask a corpsman or doctor to get it for them.
> > 
> > 
> > I'd be more worried about an autistic MO introucing the entire server to powermixes by shitting out 50 pill bottles and giving them away. Or a random corpsman or two doing that in the 20mins of prep after getting a loadout.
> > If anything the whole powergaming chem shenanigans sound more like prep taking so long that you can actually take the luxury of spending 15+ mins doing the funny. Usually when I join 15 mins in I just take pill bottles, imialky injectors, and drop. It'll be funny to see what 50 bored marines will find in the absolute boredom of prep.
> 
> Players doing things to help their team mates is good. Sweaty powergamer making their own mixes so they can avoid having to rely on team members as much as physically possible is bad.

This is just going to encourage more bullying of doctors or corpsman, especially for new players when they don't know how to make basic chems and mixes.

**Comment by Al-1ce** [comment]
>encouraging bald ungas to play corpsman

I can't tell if this will be great or absolutely terrible, but I look forward to the chaos.

**Comment by RipGrayson** [comment]
> More ways to turn us into CM 2,a bunch of useless npcs walking round who cant even open pill bottles

This is just hyperbole, nobody is removing the ability to open pill bottles and nobody plans to.






> All the good chems have been locked behind lemoline, and those that didn't, have some fat clone damage to counter its strengths I don't know what people think marines cook at roundstart; but paracetamol, doctor's delight, and food pills ain't the biggest gamechanger let me tell you
> 
> Like, genuinely, what kind of mixes do you even do as a marine, I can't think of any.

If unga mixes are that harmless, surely the marines won't miss not making them round start.

> > > > As much as I hate hard skill requirements, this is needed. If PFCs want chem so much they can ask a corpsman or doctor to get it for them.
> > > 
> > > 
> > > I'd be more worried about an autistic MO introucing the entire server to powermixes by shitting out 50 pill bottles and giving them away. Or a random corpsman or two doing that in the 20mins of prep after getting a loadout.
> > > If anything the whole powergaming chem shenanigans sound more like prep taking so long that you can actually take the luxury of spending 15+ mins doing the funny. Usually when I join 15 mins in I just take pill bottles, imialky injectors, and drop. It'll be funny to see what 50 bored marines will find in the absolute boredom of prep.
> > 
> > 
> > Players doing things to help their team mates is good. Sweaty powergamer making their own mixes so they can avoid having to rely on team members as much as physically possible is bad.
> 
> This is just going to encourage more bullying of doctors or corpsman, especially for new players when they don't know how to make basic chems and mixes.

Unless I'm missing something can't your basic marine just vend healing meds for themselves without the need to mix them personally?

**Comment by Coastfront** [comment]
And as a door whose lock and bolts open to a key many hands hold, this does not really keep powergamers from power chemixing.

They will literally just pick corpsman and ignore healing instead. All this will do is mean that there are !!EVEN MORE!! corpsmen who ignore healing because me when free neuraline, and otherwise will just mean anyone who doesen't roll corpsman and wants to powergame chem will screech and moan whenever a doctor doesent want to spend 1/3rd of their prep making a pill bottle for them.

It's a valiant effort but one that measures short no less, this doesen't actually do anything to address its targeted issue. Going by memory, there are iirc 6-11 or so corpsman slots, though it may be slightly lower. There is, currently, usually around 3-4 corpsman roundstart with significant room to spare. The people who actually care about powergaming chem will instead fill up the remaining slots, which ultimately now just means that its harder to tell which corpsman will actually heal you and which one will ignore you.

The only real way to address that aspect of the problem would entail doing something to curb the amount of corpsman slots, which would be somehow fucking even worse since then its a 50/50 tossup on if the corpsman are normal human beings or playing it for powermixes.
Even now, as overturned stones are bound to unleash swathes of ants, corpsman already has a small colony of pfc+ players who infest it for the roundstart neuraline and advanced chem mixes. This serves only to toss rainwater and rotted food in prayer to drive away a swarm of locusts.

While this is not inheretly pointless its a knife trying to drill through a steel sheet. It's little more than scratching the issue.

**Comment by TChalkman** [comment]
> If unga mixes are that harmless, surely the marines won't miss not making them round start.
The point of this change is "powergaming". IF THEY'RE THAT HARMLESS, THE REASON GIVEN IS INVALID.


> And as a door whose lock and bolts open to a key many hands hold, this does not really keep powergamers from power chemixing (...)

Partially this ^
If there's chem abusers in the first place, they will just change to corpsman. Which is the only class that gets a fuckton of chems to actually mix stuff with anyhow, since they're the literal frontline medics.
With several hours as RO under my belt, I can assure you almost no marine even thinks of buying lemoline to get what corpsmen get. Only medics that do chemistry instead of going SSD shipside

**Comment by Losenis** [comment]
>If X is that harmless, surely the players won't miss not having them

Hyped for 95% of the game removed

**Comment by Strayed-Raven** [comment]
Xenos have to die. There is no changing this. Removing up time of healing chems is not going to stop the mindset, just make marines play safer or move aggressive with other up time strats. Marines that are in the DPS role will find a way either way.

**Comment by FosterGrime-Heymynameslouie** [comment]
what?

**Comment by Pariah919** [comment]
This doesn't really end up fixing anything in current state and is far too extreme. I'd say to wait and do the actual medical changes before you do things like this.

**Comment by Loldaddy5676** [comment]
why not just make it so they can use chem machines but they will have a chance to fuck up in making their chemmix. that way if they want their pills they can either try for 10 or so minutes failing some checks or just ask a doctor.

**Comment by Losenis** [comment]
>that way if they want their pills they can either try for 10 or so minutes

Fumbling did the same thing. IE, nothing.

**Comment by chizzy376** [comment]
This will unfortunately not fix anything, only create more issues.

**Comment by Losenis** [comment]
I still stand by the idea that if you want to cut down on midcombat healing, just make chems metabolize twice as slow but also heal twice as slow so that they heal the same amount on a per-unit basis but can't outheal the funny stabs.

**Comment by EvilMelonTheSecond** [comment]
Powergaming via chem is dead, most you can do is personal pill bottles instead of packets. This PR just makes people that want more pills to pick corpsman over marine and nothing else.

**Comment by Naaanii** [comment]
I'd honestly double down and kill pill packets and replace them with infinite pill bottles and injectors instead. Custom mixes can be made by docs/SLs/FC/and corpsmen. This will also somewhat fuck up Vali users too.

**Comment by Loldaddy5676** [comment]
> > that way if they want their pills they can either try for 10 or so minutes
> 
> Fumbling did the same thing. IE, nothing.

i was thinking more of no fumbling more if they press a button they get another chemical instead. though you do make a point that nothing will be changed.

**Comment by Losenis** [comment]
That'll hurt the ones intended to use the chem machine because the unga will just start over and spend more energy that will be the next person's problem rather than his.

**Comment by chizzy376** [comment]
> I'd honestly double down and kill pill packets and replace them with infinite pill bottles and injectors instead. 

This was the original way we had it around 2 years ago.

**Comment by ivanmixo** [comment]
Not true, pill bottles were limited and it was a rush to get your loadout vended from the loadout vendor before everyone else so you wouldn't have to cobble together your pills from spare medibelts from medical.

**Comment by XElectricX** [comment]
Bad PR. I don't want to be forced as CMO to do chemistry for everyone like it's CM. Also goes against the philosophy of everyone being able to do anything. Skills are for keeping one person from doing everything expertly, not to lock people out of content.

**Comment by chizzy376** [comment]
This shit will get merged because quality control nowadays is a myth and lumi along with mjp control all of the pr's, gg pack it up

**Comment by CCorvet** [comment]
Disagree with this PR. Fumbling the chem dispenser already serves this purpose. If you want to enfore PFC's having less access to chemistry, you can do it more organically. Make chem dispensers require hacking to allow PFC's to use em. Replace chemistry windows with kevlar infused ones. Or just, you know, increase the fumble time.

A different way to go about this is also instead of punishing PFC's for wanting a basic BKTT Mix, which rubs me the wrong way, encourage medical doctors and corpsmen to use the chem fridges and supply them, by placing them in better spots and linking their storage (So if you put something in chem fridge in front of chem, where windows are, it will also be accessible from the chem fridge at the back of chem, where door is. Adding an option to the chemmaster to instead of ejecting stuff it creates, to automatically push to chem fridges, and a button to move the beaker inside of chemdispenser/chemmaster to the other one without ejecting would increase convenience. Locking these advanced features to corpsman+ medical skill would also be a soft way of discouraging PFCs. Generally making chemistry more efficient for mass production would also solve the PFC using chem dispensers.

**Comment by iforgotmeword** [comment]
Bruh don’t remove bootleg OT you already removed making casings from metal 

my mixes are like 26 42 88 mixes this is going to be hell on the MD because i need like 18 different mixes that blows up if mixed wrong

**Comment by SilencedMP5A5** [comment]
how about make survival not literally hell without good chems before you merge this

straight up cannot play the game without oxycodone when i get clicked once and have 15 heart and lung damage and a fracture + 0 stamina perpetually due to the organ damage + perma stagger so i can't hit (or see, sometimes!!) + pain slow so i literally can't even just leave to get it fixed unless i'm in the middle of an ungaball

or, you know, just dont merge it at all that'd be cool

**Comment by Dolth** [comment]
There is no powergame anymore in chems because all strong chems requires lemoline.
Going to chem is just for QoL; get your proper mix of BKTT or whatever which is essentially the same as popping 4 pills, that is not powergaming. This PR is just taking away QoL and customisation from whoever decided to spend time doing so, it's a bad idea.

This would have been legit (and actually good imo) if docs/corpsmen could do advanced mixes like before without lemoline though.

**Comment by Losenis** [comment]
>straight up cannot play the game without oxycodone when i get clicked once and have 15 heart and lung damage and a fracture + 0 stamina perpetually due to the organ damage + perma stagger so i can't hit (or see, sometimes!!) + pain slow so i literally can't even just leave to get it fixed unless i'm in the middle of an ungaball

Me on my way to get 15 lung damage and an armfrac through heavy tyr2 by a funny warrior click as soon as shutters open

**Comment by ivanmixo** [comment]
To be fair ocelot that's the price you pay for going armorless... still a shitty PR though.

**Comment by Dolth** [comment]
> To be fair ocelot that's the price you pay for going armorless... still a shitty PR though.

Light armor should still not have to suffer such a drastic difference. Game should be funny, not hell to go through.

**Comment by Losenis** [comment]
The game is made hell to go through because every time any time anything that affects balance for the sake of making something less of a pain in the ass, the other side will argue against it due to them having it hell too. Justifiably too, since if that not-hell change goes through the not-hell pr that applies to the other side will get bonked with "muh powercreep". And if there's a change that balances it out by making it not-hell for both sides, it'll get bonked with "atomize".

Things that are a pain in the ass to deal with are kept in the game like a bucket of crabs pulling at each other back into the bucket they're trying to get out of.

**Comment by Oscari-pog** [comment]
Oxycodone pills incident

**Comment by Waselon** [comment]
speedmerge inshallah

**Comment by grinkgo** [comment]
Based as hell pr

**Comment by Barnet2** [comment]
its so over

**Comment by FosterGrime-Heymynameslouie** [comment]
lmao
droid supremacy era incoming

**Comment by Losenis** [comment]
>Putting bica and kelo in the same pill is considered powergaming

The absolute state of c*ders

**Comment by ivanmixo** [comment]
Can't wait to see people who play corpsman just for this ;3

**Comment by SpanishBnn** [comment]
C*ders when they don’t read and just merge (expecting somebody to unironically write a virus and it getting merged too)

**Comment by Derrick2Electricboogaloo** [comment]
> C*ders when they don’t read and just merge (expecting somebody to unironically write a virus and it getting merged too)

Tivi hates chem, they will merge anything that kills chem.

**Comment by SilencedMP5A5** [comment]
20$ to the first man to make a revert pr

**Comment by Dolth** [comment]
> Players doing things to help their team mates is good. Sweaty powergamer making their own mixes so they can avoid having to rely on team members as much as physically possible is bad.

I am afraid you are wrong. Chemistry does not make you "avoid to rely on team members" simply because PFCs have access to everything they need in the marine vendor already.
Chemistry however, was QoL. Quality of life because if you knew you would use more X or Y meds you could just mix them up instead of popping two pills at a time. It's also necessary for vali/nanites.

What you just did is going against TGMC motto which was to make everything possible for everyone. No more pill lock, no more specialist slot etc... But yeah again, nope, you're wrong.

**Comment by EvilMelonTheSecond** [comment]
Tivi killed specialist slot with mechs and now skill locked chem. Brace for MP and xeno tackle return a few PRs later.

**Comment by TChalkman** [comment]
image

**Comment by Al-1ce** [comment]
>dead server values from 3 years ago when people gave a shit

Look's like you need to get with the times.

**Comment by chizzy376** [comment]
Please lift lemolock!!!!!!!!!!!!!!!!!!!!!!

**Pull request merged**
