### PR TITLE
Readds extended and spray nozzles

### PR DESCRIPTION
**Pull request by Notamaniac**
## About The Pull Request

Readds the extended and spray nozzles

The extended nozzle is free, but the spray nozzle has been condemmed to req hell for 200 points

## Why It's Good For The Game

The extended nozzle was really just a sidegrade, losing it's ability to penetrate walls for better ammo efficiency. The best argument against it being that you have to be up close to use the flamer because (???). The plasma pistol exists for ranged wall destruction, and the laser sniper HEAT mode exists for setting xenoes on at fire at range so-

The spray nozzle in action could present some problems, being able to deny massive areas to xenoes, especially in cave pushes. While it was expensive in terms of fuel, a dead xeno is a dead xeno, and dead structures are also dead structures, which come both at massive costs to xenoes (while fuel itself is plentiful). Hence the decision to req hell it.

## Changelog
:cl:
add: Readds the extended nozzle (for free) and the spray nozzle (for 200 req points) for the FL-84 flamer.
balance: Extended nozzle now has a 2 second windup before firing. Wide nozzle has a 3 second windup. 
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
> The best argument against it being that you have to be up close to use the flamer because (???).

Because it has perfect ammo efficiency and you have to take zero risks to clear out swathes of walls with it. Proximity is a big factor when it comes to the balance of maze clearing, it being risk free can make xenos feel powerless to stop it and mazes are the cornerstone of xeno defensiveness so it's important there's counterplay to the counterplay to them. 

> The plasma pistol exists for ranged wall destruction

While also being significantly, significantly slower. And the ammo is comparatively more annoying to bring lots of. Also bad for defensive play against xenos trying to stop you because of the pathetic amount of fire stacks. There's a reason you almost never see anyone use it for maze clearing unless they're new or just very very patient.

> laser sniper HEAT mode exists for setting xenoes on at fire at range so

Really not relevant in this discussion, the issue with extended nozzle is it was very good against mazes. (Note the heat mode also does not do a lot of fire stacks per shot)

Don't really care about the spray module, especially if it comes at a price.

**Comment by FosterGrime-Heymynameslouie** [comment]
if its not gonna be added for flamer please at the very least be added for the extinguisher, its really really useful and im suprised it got removed from the water sprayer too when it got removed from the flamer way back when

**Comment by Wisemonster** [comment]
> The best argument against it being that you have to be up close to use the flamer because (???).

Because it adds counterplay. Needing to get near the maze opens up the player to getting fished/ganked, something the extended nozzle completely bypasses due to not needing to go anywhere near said maze. This problem with the nozzle hasn't been fixed at all, you're just re-adding it along with the spray nozzle. Btw, the spray nozzle costing slightly more than a T1 in exchange for providing the upsides you listed permanently (unless you end up perma, in that case womp womp)

**Comment by SimplySmiley123** [comment]
> Because it has perfect ammo efficiency and you have to take zero risks to clear out swathes of walls with it. Proximity is a big factor when it comes to the balance of maze clearing, it being risk free can make xenos feel powerless to stop it and mazes are the cornerstone of xeno defensiveness so it's important there's counterplay to the counterplay to them.

You still need to be ahead of marines for this.
At best you get 2-3 tiles of distance away from whatever singular wall you want to set on fire.
Otherwise, yeah, it is fuel efficient way to take down mazes, but also time inefficient and somewhat tedious because you gotta fire at every single wall individually instead of just spraying a lane and taking down couple of walls in one go.

**Comment by SimplySmiley123** [comment]
> > The best argument against it being that you have to be up close to use the flamer because (???).
> 
> Because it adds counterplay. Needing to get near the maze opens up the player to getting fished/ganked, something the extended nozzle completely bypasses due to not needing to go anywhere near said maze. This problem with the nozzle hasn't been fixed at all, you're just re-adding it along with the spray nozzle. Btw, the spray nozzle costing slightly more than a T1 does not remove the benefits you listed.

Extended or no extended, same shit in practice.
You ain't gonna be sniping the maze, at best the exterior walls, inner walls gotta get into the xeno breathing range if you still want to take that maze down in a timely manner.

**Comment by Lauwma** [comment]
Kill extended keep spray

**Comment by PibeCantina** [comment]
Spray is based because it can't kill walls fast, extended is just straight up better, keep spray, don't bring back extended

**Comment by iforgotmeword** [comment]
(you do know that normal flamer has really good and i do mean GOOD range right? granted it's fuel heavy but the range is there)

i can see this working but only with massive and i mean massive nerfs
my personal picks are for

extended fuel costs is 3X (each shot is now 3 fuel each) (166 for back 15 for tank)
and as well a cast time per shot (make the marine really stick out)

spray fuel costs should be 5X (something like idk 7 shots with back and 1 with tank)
A VERY long cast time
can only pen 1 wall

**Comment by SimplySmiley123** [comment]
> extended fuel costs is 3X (each shot is now 3 fuel each) (166 for back 15 for tank) and as well a cast time per shot (make the marine really stick out)

No one would bother then because then it would take ages to take down smaller parts of a maze for little benefit (you're still gonna be close to the maze anyway so might as well use no nozzle at that point and be far better at both maze clearing and dettering beans).

> spray fuel costs should be 5X (something like idk 7 shots with back and 1 with tank) A VERY long cast time (like a 1.2 sec charge up) can only pen 1 wall

Spray already gobbles fuel and tends to rarely have a space to be useful in, but here I can see cast delay working.

**Comment by ButterChugger** [comment]
The xeno main (except rav) fear the spray nozzle samurai. End of discussion.


Extended nozzle is fine. It's meant to poke and be completely useless if a beno walks up to them and slashes them (which all benos within reasonable extended nozzle distance can do). Back in the heyday you had aimballs to protect flamer users. So as follows, I see this. John unga and a group of deltards are near a maze edge. John unga hoses a wall down, the other group of deltards mulling a bit back to not be hit by the fireball. A singular xeno walks up to john unga and slashes him, lets say for example he hit that fireball on beno approach. What are the chances of the deltard team _lighting john the fuck up with gunfire_ because there's a xeno in front of him and they lack aim mode? While you see this as an inconvenience to benos, I see this as a glorious chance for combined friendly fire and raising medic players blood pressure levels.

**Comment by Notamaniac** [comment]
Adds a windup delay to both nozzles, but being shuffled/moving doesn't cancel firing, meaning the only way for a xeno to stop them firing is with a stun. Standard fire delay is removed in exchange for the windup, so you aren't left waiting for 2/3 seconds to begin firing again.

**Comment by ivanmixo** [comment]
That doesn't fix anything at all

**Comment by Lumipharon** [comment]
Literally nothing has changed from when these were removed, to make this a good idea.

**Pull request closed without merging**
