### PR TITLE
Motorbike sidecar

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Adds a motorbike sidecar that can be bought in req as a motorbike upgrade

## Why It's Good For The Game

Fun thing to buy in future maybe gets mounted gun

## Changelog
:cl:
add: Added a motorbike sidecar which can be bought in req, attached to motorbikes and detached with a wrench
spriteadd: Sprite by xana
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
@TiviPlus Still has a bug to fix

**Comment by BrandonSmith6** [comment]
Sounds epic, would love to see this ingame.

**Comment by AnCopper** [comment]
ocelot vs snake
Can't wait for this scene to play out.

**Comment by BraveMole** [comment]
Stale, reopen later when you have pc

**Comment by ZahaSanko** [comment]
_it has been over 90 years..._

**Review by BraveMole — CHANGES_REQUESTED** [review]
tm'ing, think it just need to doc

**Comment by Lumipharon** [comment]
It's pretty cute, but the dude in the sidecar has to use one hand to buckle in, so can't shoot a rifle or whatever out of it.
Is it possible to make them buckle in like a chair so they have two free hands?

**Comment by XANAv2** [comment]
Yes we should be testing that soon i hope right tivi

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
