### PR TITLE
Ares Bluespace recall armor module

### PR DESCRIPTION
**Pull request by tanker4390**
## About The Pull Request
**Relocated after pressing the funny merge button instead of rebasing, point and laugh**

Adds an armor module that can link to a weapon and summon to the user's hands at will (on a cooldown), just like a RPG protagonist. This may not be finished, possibly needing some bugs squashed or more sanity checks put in place to defend against powergaming. Oh, and balance changes.

Screenshot_20230201_085444

Further detail. After linking (with a cooldown) most weapons, except [some](https://tgstation13.org/wiki/File:TGMC_sadar.png#file) [ludicrous](https://tgstation13.org/wiki/File:TGMC_T160.png#file) [ones](https://user-images.githubusercontent.com/91577829/216520376-e3b41032-3444-4cff-b230-5e29c608c29f.png), they can be summoned with the ability button (again, cooldown) or re-linked to another weapon, for one at a time. Modules lose their links after being detached from armor, but not when armor is removed (armor has a weight class of huge [5], good luck with that).

Most likely these will come from req, but may be available from vendors depending on how balance goes.
## Why It's Good For The Game
For those times when you get pounced on 3 times in a row and drop all your weapons... ~~just use a magharness~~ simply pull your ~~RL160 recoilless rifle~~ Mateba out of thin air, ~~then get pounced on again and have to wait the whole cooldown~~
Otherwise, you have to go back shipside, loot one, or run to where it was with a knife and pray you don't die instantly.
## Changelog
:cl: Tanker
add: Adds the Ares Bluespace recall system armor module, allowing you to summon a linked weapon at will.
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
Gar Yok

**Comment by GreatKingWombat** [comment]
Won't this just lead to a blacklist where the pool of weapons it can work on will be constantly chipped away at?

**Comment by tanker4390** [comment]
> Won't this just lead to a blacklist where the pool of weapons it can work on will be constantly chipped away at?

That's just how rebalancing is done?

**Comment by Derrick2Electricboogaloo** [comment]
Thought this was going to be an armor module to recall to a previous position with a cool down if shit went bonk. Not sure I see much use with a armor mod that recalls guns out of thin air when I can just use a mag harness and never lose my gun ever and maintain the utility of other armor mods.

**Comment by tanker4390** [comment]
> Thought this was going to be an armor module to recall to a previous position with a cool down if shit went bonk. Not sure I see much use with a armor mod that recalls guns out of thin air when I can just use a mag harness and never lose my gun ever and maintain the utility of other armor mods.

This was intended as a sort of sidegrade to the magharness (doesn't occupy the rail slot), then I realized it could have more utility?
Also I thought marines could use some more cool "spells". I dunnoh.

**Comment by TheLeopold** [comment]
Spearthrowers rejoice!

**Comment by RaidarV** [comment]
tumblr_psvyvq7MqZ1wfchcio1_400

Maximum cosplay time

**Comment by Coastfront** [comment]
> Thought this was going to be an armor module to recall to a previous position with a cool down if shit went bonk. Not sure I see much use with a armor mod that recalls guns out of thin air when I can just use a mag harness and never lose my gun ever and maintain the utility of other armor mods.

carrying 3 rr's has never been easier

**Pull request closed without merging**
