### PR TITLE
Boiler: Acid shroud + extra boiler balance

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
Adds acid shroud for boiler; creates a small smokescreen on yourself for LoS block to (potentially) escape a chasing marine. It resets the cooldown of Bombard + 10 seconds, so only use it when you have to!
Increases boiler zoom by 2
Reduces normal glob range to zoom range

https://github.com/tgstation/TerraGov-Marine-Corps/assets/20828943/89eeb263-c5ae-4744-85ba-12f0ce15a08b
## Why It's Good For The Game
After the boiler changes, it was a change that (seems) to be a buff for good players but a nerf for bad players. While this doesn't eliminate the gap between good and bad Boilers, it should give a little extra tool to escape. Additionally via feedback the miniscope range was a bit too short, but this is still a lot less than original zoom and (hopefully) still rushable in the right circumstances. The final change was because people were abusing xeno vision to get a literal max range of 30 tiles, even further than original Boiler. This remedies that.
## Changelog
:cl:
add: Adds acid shroud for boiler; creates a small smokescreen on yourself for LoS block to (potentially) escape a chasing marine. It resets the cooldown of Bombard + 10 seconds, so only use it when you have to!
balance: Increases boiler zoom by 2
balance: Reduces normal boiler glob range to zoom range
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
Very cool looking no doubt, certainly a good tool that may be helpful. Would be funny to see a boiler use it offensively.

Could we get an example of a boiler using it to escape to the north? And would separating the gas type selection be difficult? I'd imagine some people would want to leave it on Acid, even if they use Neurotoxin to bombard.

**Comment by Looking4bros** [comment]
Le bumb

**Review by Kuro020 — APPROVED** [review]

**Comment by Looking4bros** [comment]
:eyes:

**Review by Lumipharon — APPROVED** [review]

**Comment by Looking4bros** [comment]
:trollface:

**Pull request merged**
