### PR TITLE
fix: Computer Barricades

### LINKED ISSUE #4506: Computer Barricades
## Testmerges:

#4487: 'Replaces player preferences with TGUI preferences.' by psykzz at commit 8bd8fb214f
#4467: 'dropped code pixel shifted items will retain their pixel shifts' by Hughgent at commit e5f7f72b0c
#3905: 'Vehicle Framework [Review Ready]' by TiviPlus at commit e655a76523

## Reproduction:

Place a computer frame, add the circuit board to it. Enjoy your acid-proof barricade.

### PR DESCRIPTION
**Pull request by KuzyXD**
## About The Pull Request

fix #4506

## Why It's Good For The Game

Aliens can destroy some computers, but not melt them. The Marines can fix them

## Changelog
:cl:
fix: Computers are now destructible but aliens can't melt critical computers
/:cl:

### CODE REVIEW

**Review by BraveMole — CHANGES_REQUESTED** [review]
Are you sure marines can fix them?

**Comment by KuzyXD** [comment]
> Are you sure marines can fix them?

not machinery

**Comment by ilikesaying** [comment]
lots of pods/cryopods to melt, and xenos would be winning if they're melting the machines anyways.
i think the consoles, computers and generators can be repaired.
dunno about alamo console since that's not listed under computers

**Comment by KuzyXD** [comment]
> lots of pods/cryopods to melt, and xenos would be winning if they're melting the machines anyways. i think the consoles, computers and generators can be repaired. dunno about alamo console since that's not listed under computers

Alamo console is /computer which have in attack_by function deconstruction
/machinery not

**Comment by Araulius** [comment]
so let me get this straight; You want to make the nondense supply pad destructable so a single xeno shipside can make marines forever unable to drop supplies. you want to be able to destroy the fucking *cryo computer* of all things. And the nav computer. this isn't about "barricades" in any way shape or form. that  much is obvious.

**Pull request closed without merging**
