### PR TITLE
Readds surv on hunt

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
Re-adds survivors on hunt, pools doenst have it. has all code from #6635 

## Why It's Good For The Game
Survivors are fun for who's playing, maybe less fun for xenos, depends who playing on it, fact is though 80% of the xenos can run away and ask for help if a surv goes after them, but mostly important a pool cant, so its only on hunt, where xenos are not stuck defending something like in pools, also gives something for xenos to do before 30 mins of game on hunt gamemode incase you're not a building caste.

## Changelog
:cl:
add: adds survivors back on hunt gamemode.
/:cl:

### CODE REVIEW

**Comment by David-Stormwell** [comment]
You'll need more work then just this.
If you can:
Edit all the maps, delete any T3 guns.
Remove survivor armor and instead have them with standard map armor barring PMC and above.

**Comment by SplinterGP** [comment]
> 
> 
> You'll need more work then just this.
> If you can:
> Edit all the maps, delete any T3 guns.
> Remove survivor armor and instead have them with standard map armor barring PMC and above.

i wont edit maps, most of them have just slightly better guns with low ammo

**Comment by SplinterGP** [comment]
armor you're literally 1v5 at best.

**Comment by SplinterGP** [comment]
plus the 5 in a row was during pools gamemode, totally a problem with survs of course

**Comment by Naaanii** [comment]
Survivor armour slowdown when?

**Comment by David-Stormwell** [comment]
remove survivor armor, make them scavenge for armor

**Comment by BraveMole** [comment]
If anything, survs have more impact on hunt than pool, so it's weird to enable on one and not the other?

**Comment by SplinterGP** [comment]
> If anything, survs have more impact on hunt than pool, so it's weird to enable on one and not the other? 

That's wrong, on pools survs are able to go after the pools early on and as you know pools dont move, on silos xenos dont rely that much on them and it does little to lose one, so they can just let the surv destroy it without any trouble if its in a bad spot they cant defend from surv or whatever

**Comment by SplinterGP** [comment]
> remove survivor armor, make them scavenge for armor

Yeah but what armor, also surv location is given on roundstart bioscan, so if they have no armor it turns very easy to just bumrush the survivor with a rouny

**Comment by BraveMole** [comment]
> > If anything, survs have more impact on hunt than pool, so it's weird to enable on one and not the other?
> 
> That's wrong, on pools survs are able to go after the pools early on and as you know pools dont move, on silos xenos dont rely that much on them and it does little to lose one, so they can just let the surv destroy it without any trouble if its in a bad spot they cant defend from surv or whatever, meanwhile on pools they obviously need to defend the pool

Xeno are never putting the pools early, because of tadpole meme. 
And xenos dead are more impactfull on silo than pool, so surv have more impact?
Plus pool has turrets to slow down surv and protect young xeno if surv are rushing (which they are not really doing, it's more young xeno rushing surv), so it's even better on that side?

**Comment by David-Stormwell** [comment]
> 
> 
> > remove survivor armor, make them scavenge for armor
> 
> Yeah but what armor, also surv location is given on roundstart bioscan, so if they have no armor it turns very easy to just bumrush the survivor with a rouny

Which is, for the most part fine.
What I would've liked to see instead of just how survivors where, where them being renamed into first responders/people who answered the distress beacon before marines with basic medical supplies and small amounts of engineering equipment and basic sidearms.

**Comment by InterroLouis** [comment]
Basic sidearms. So basically just free corpses for the silos?

**Comment by David-Stormwell** [comment]
> 
> 
> Basic sidearms. So basically just free corpses for the silos?

If that's what you want to see them as sure Harry.
Because having them any more then just basic sidearms, hell even with basic sidearms and map scavenging they'll probably be able to get out a hive wipe once in a while.

**Comment by ilikesaying** [comment]
Jeff Major

**Comment by TiviPlus** [comment]
Commit trash, missing scaling and doesnt solve any of the issues surv had

No.

**Comment by David-Stormwell** [comment]
I'll be working with Ren later to do a major survivor rework.

**Pull request closed without merging**
