### PR TITLE
Removes Tangle grenades from Marine access.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Tanglefoot grenades are no longer accessible by marines.

## Why It's Good For The Game
GL/Handheld Tanglefoot grenades suck. The systems used to fire them is literally acquireable by every player with ease (your hands, unless you've lost them both.) or a handheld GL.
This is bad. This allows you to create an area of no go zone without any setup, deployables require setup, artillery requires setup, CAS requires some level of setup and is more telegraphed.
Reducing their range doesn't solve the issue that it allows every single marine to carry around a "I live/win this area button.". In my opinion, this should be relegated to support tools, because they require some setup, are more likely to be used in a tactical/strategical manner, and also most of them reward teamwork and coordination more.

I've left TX-54 Tangle alone for now, since I don't really consider it *that* offensive due to being on a req gun, but it might also be able to go for precedent reasons.

## Changelog

:cl:
balance: Marines can no longer access handheld tanglefoot grenades, all other forms of tangle (AGLS, Mortar, etc) are untouched.
/:cl:

### CODE REVIEW

**Comment by isotope436** [comment]
GAS METAS BACK ON THE MENU BABY MARINES COPING AT ZERO GAS COUNTERS RETURNING RAAAAAAAAAAH 
image

**Comment by lKiseki** [comment]
chat he's fucking cooking

**Comment by chizzy376** [comment]
We love uncounterable boiler spam We love uncounterable boiler spam We love uncounterable boiler spam We love uncounterable boiler spam We love uncounterable boiler spam We love uncounterable boiler spam

**Comment by bowlofcereal** [comment]
PR-2

**Comment by blackdav123** [comment]
never really saw these as an issue as marines will have one or two at most, and they are usually short enough for a gorger or rav to defend the area long enough. other forms of tangle like mortar and cas tend to be spammed way more and just make xenos unable to fight for way longer.

**Comment by David-Stormwell** [comment]
Entirely based, problem though will be gas creep of course as pointed out by comments.
This however does seem quite swell for balance though

**Comment by SimplySmiley123** [comment]
> > GAS METAS BACK ON THE MENU BABY MARINES COPING AT ZERO GAS COUNTERS RETURNING RAAAAAAAAAAH image
> 
> you say this like tangle nades werent on a insanely long delay and did so much against gas. if a boiler shoots a glob into gas it lands on you (but with no stun) it does the equivalent amount of damage it would take for you to get out before tangle clears this gas. this is also assuming you had tangle BEFORE the boiler shot its glob, which most the time you dont. This will barely effect gas meta.
> 
> Im not saying gas meta isnt annoying af, but tanglenades as a counter to it were practically useless

It's probably more about annoying the boiler or something.
And to be fair I can see why any unga would take any chance at pissing off a boiler, they are annoying to deal with with the constant gas clouds everywhere, same as defiler who can just, run into the unga ball and walk out, or baneling that literally gets rewarded for running in and dying in front of a marine.

**Comment by usnpeepoo** [comment]
Finally

**Comment by 1kajowsmol** [comment]
at first i was against it but honestly boiler has root and defiler just needs a sh35 to be countered so i'm all for it

**Comment by Henrique9576** [comment]
image

**Comment by breadhunt** [comment]
BASED
Could also specialise them into an anti-gas nade if this gets denied for gas walance reasons

**Comment by SimplySmiley123** [comment]
> > 
> 
> > 
> 
> I mean the best and most popular use of them is spamming them multiple in a row. when its just 1 nade, its never an issue. it delays xenos by 10-15 seconds, doesnt even stop a lot of abilities, and just mainly prevents some xenos from going in deep, but it becomes an issue when its naded popped back to back and is mainly just annoying. there are 100 other ways to get t-foot onto the field so I think stripping this away isnt a huge deal

Thing is even those other methods in my experience are meh at best?
Wouldn't mind them getting axed, they rarely ever are of any impact even in the situation you mentioned which... I never ever seen happen because all the other grenades are way better in larger numbers, even when at the recieving end it just didn't matter much.

**Comment by EaglePhntm** [comment]
delet this

**Comment by ivanmixo** [comment]
> BASED Could also specialise them into an anti-gas nade if this gets denied for gas walance reasons

Anti gas gas seems solid as a future thing, you could even make it purge gasses faster than tangle does and it'd be okay even if really specialized me thinks

**Review by ivanmixo — APPROVED** [review]

**Comment by Pariah919** [comment]
>Thing is even those other methods in my experience are meh at best?

Sir. There are literally dozens of other methods which are better. The issue?

They're not convinent. Grenades are convinent because they require no investment other than one small storage slot. This is bad in my opinion because it disseminates all other forms of tanglefoot (And smoke in general) into being kind of worthless because of how insanely efficent tanglefoot grenades.

> Could also specialise them into an anti-gas nade if this gets denied for gas walance reasons

At that point I'd just add a grenade that purges gas in general. But I think that's cope.
You have AGLS (the probably best tfoot spreading device in the game btw), all the indirect forms, tx54, etc.

**Comment by usnpeepoo** [comment]
make the alpha change on the smoke nades just visible enough to see marines in the smoke while youre at it 💯

**Comment by chizzy376** [comment]
>  boiler has root

Unfortunately this does not make a boiler an easy kill as an actual boiler player will be picky about their spots

> defiler just needs a sh35 to be countered

This is so wrong on so many levels, that would be like if I told you that a mg user has long reloads and should be attacked only when reloading

**Comment by Oscari-pog** [comment]
Tangle spam needs to die, this is a good change.

Boiler is batshit easy to counter. One single sniper will shut the boiler off unless they find a maximum range angle to shoot from, and a autosniper present will cuck boiler entirely unless they get a defender to constantly babysit them.

Other forms of tangle also still exist, so Marines will simply have more difficult access to their "I win in this area" gas.

**Comment by SimplySmiley123** [comment]
> > Thing is even those other methods in my experience are meh at best?
> 
> Sir. There are literally dozens of other methods which are better. The issue?
> 
> They're not convinent. Grenades are convinent because they require no investment other than one small storage slot. This is bad in my opinion because it disseminates all other forms of tanglefoot (And smoke in general) into being kind of worthless because of how insanely efficent tanglefoot grenades.

Read my comment again, I said I don't mind tangle grenades getting removed as they already felt pointless.

> 
> > Could also specialise them into an anti-gas nade if this gets denied for gas walance reasons
> 
> At that point I'd just add a grenade that purges gas in general. But I think that's cope. You have AGLS (the probably best tfoot spreading device in the game btw), all the indirect forms, tx54, etc.

Thing is that xeno gas is spammable as all hell, even with tangle grenades unless you pop one perfectly timed with already popped one dissipating you're gonna be surrounded by gas nigh instantaniously be it from a boiler, a defiler running in with no fucks given or yet another suicidal baneling getting rewarded for dying in a dumb way.
Would love if smoke grenades, the regular kind, made it harder (not impossible) for gasses to spread into the smoke.

**Comment by SimplySmiley123** [comment]
> Tangle spam needs to die, this is a good change.
> 
> Boiler is batshit easy to counter. One single sniper will shut the boiler off unless they find a maximum range angle to shoot from, and a autosniper present will cuck boiler entirely unless they get a defender to constantly babysit them.
> 
> Other forms of tangle also still exist, so Marines will simply have more difficult access to their "I win in this area" gas.

Defiler and baneling still exist andh ave much much easier time then boiler to shit out gas constantly and reliably.

**Comment by efzapa** [comment]
improve don't remove

that's all

**Comment by efzapa** [comment]
> Tangle spam needs to die, this is a good change.
> 
> Boiler is batshit easy to counter. One single sniper will shut the boiler off unless they find a maximum range angle to shoot from, and a autosniper present will cuck boiler entirely unless they get a defender to constantly babysit them.
> 
> Other forms of tangle also still exist, so Marines will simply have more difficult access to their "I win in this area" gas.

nerfing HE grenade counts didn't kill grenade spam tbf

what coders eventually have to realize is that reqhelling and removing shit they don't like won't fix the ROOT OF THE PROBLEM

**Comment by Yttriums** [comment]
Really don't like the idea of removing tactical tools like tangle grenades from ordinary marines while leaving shit like tangle OB  and tangle CAS in the hands of a relatively small group of players. A marine throwing a tangle to clear a room, set up defenses or as a panic option is - to me- a perfectly reasonable/cool play pattern. What's more ridiculous is the FC getting to call a 1 minute time-out whenever they want with tangle OB.

If these are really overpowered, you could limit them to 1 or 2 per marine in vendors, reduce the radius, reduce the gas hang time further, increase req cost, etc. But completely removing them just makes ordinary marine gameplay more bland.

**Comment by Loafin34** [comment]
yet another xope PR. if you hate tanglefoot, try and get marines to waste their nades on your constant boiler attacks.

**Pull request merged**
