### PR TITLE
Adds ERP

### PR DESCRIPTION
**Pull request by mrhugo13**
## About The Pull Request
Adds most stuff described in the following image, also a bunch of improved clown gear
adds_erp_image_revision3

New distress beacon, Emergency Response Pranksters, a distress beacon spawn about as likely to spawn as special response forces. Aligned with the TGMC.
Adds some items for said distress beacon team and the relevant code for the jobs of that team.
Adds some sprites both for minimap blip & explosive cream pie grenade (when activated) & assault pie launcher
Adds 2 new files to .dme manifest
## Why It's Good For The Game
More distress beacons induce more variety induce more fun induce more players, which is to say I think this is a good addition because the contents therein will add more variety to the average round for people to experience & have fun with. Just imagine a squad of clowns rocking up with explosive cream pies to save the day as xenos are invading the station.

dreamseeker_2024-08-09_16-49-56
## Changelog

:cl: Vondiech/Citruses
add: Adds ERP, Emergency Response Pranksters, a new possible distress beacon spawn of clowns! Aligned with TGMC
/:cl:

### CODE REVIEW

**Comment by mrhugo13** [comment]
Also for those curious this was in-fact inspired by THIS pr on the /TG/ station main codebase branch made by Fikou https://github.com/tgstation/tgstation/pull/48699

**Comment by mrhugo13** [comment]
firefox_2024-08-09_17-19-42
very cool

**Comment by FosterGrime-Heymynameslouie** [comment]
erp

**Comment by Mantlecrawler** [comment]
Push a commit or something and it'll rerun checks, should work the second time

**Comment by Woker2004** [comment]
One day we will get a Hampter Response Team, one day...

**Comment by Lumipharon** [comment]
this should probs  be admin only.

**Comment by mrhugo13** [comment]
> this should probs be admin only.

Ehhhhh admin only content never gets spawned + the inherent way distress beacon spawns happens any one specific spawn occuring is unlikely.

**Comment by mrhugo13** [comment]
Now featuring: Assault pie launcher! (a red color swapped GL which is now *actually* by default filled with cream pie nades)
dreamseeker_2024-08-10_11-58-41

**Comment by Lumipharon** [comment]
> > this should probs be admin only.
> 
> Ehhhhh admin only content never gets spawned + the inherent way distress beacon spawns happens any one specific spawn occuring is unlikely.

This is a literal meme ert, just like the other admin only erts.

**Comment by mrhugo13** [comment]
> > > this should probs be admin only.
> > 
> > 
> > Ehhhhh admin only content never gets spawned + the inherent way distress beacon spawns happens any one specific spawn occuring is unlikely.
> 
> This is a literal meme ert, just like the other admin only erts.

Done as requested.

**Pull request merged**
