### PR TITLE
the game was rigged from the start

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
The ranks are technically army but who cares :tm:

## Why It's Good For The Game
DIfferent from American ranks atleast.

## Changelog
:cl:
tweak:The marine ranking system appears to have changed. How odd.
grammar:Some ranks now declare someone entire rank, for clarity for people who don't know the abbreviations.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -32. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by David-Stormwell** [comment]
Absolute madlad did it

**Comment by TiviPlus** [comment]
Please no

**Comment by Chaznoodles** [comment]
Wait a second this isn't Escalation

**Comment by davidchan13** [comment]
Thanks, I hate it.

**Comment by PigeonLord** [comment]
Nobody speaks German

**Comment by Chaznoodles** [comment]
image

**Comment by Pariah919** [comment]
solid kek

**Comment by psykzz** [comment]
couldn't even compile the meme was this bad.

**Comment by David-Stormwell** [comment]
it complied

**Comment by jroinc** [comment]
@Pariah919 

Closing your PR. Again.

Bitch~

**Comment by sunofang** [comment]
dew it

**Pull request closed without merging**
