### PR TITLE
Bring Back Salvage Biomass in light of Researcher

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Readd salvage biomass. Combat gib against researcher's attempt to invade the sacred body of a xenomorph.

## Why It's Good For The Game

Another counter, beside dragging, against researcher.

## Changelog
:cl:
add: Added new mechanics or gameplay changes
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
I'd say either remove gibbing or remove granting points altogether. Gibbing to deny corpses seems alright but Xenos shouldn't really be rewarded for perishing.

**Comment by SplinterGP** [comment]
marines can't even have peace of taking bodies anymore after their hard sweat kill of a xeno, now they have to stop other xenos from gibbing it too 😥

**Comment by Walarks** [comment]
I'd suggest a number nerf to the req points rewards if it is an issue, instead of cucking the researcher/req out of its job/niche.

**Comment by SilencedMP5A5** [comment]
yucky

time for every xeno that dies to get dragged to the caves by other xenos and salvaged

**Comment by RuneQuester** [comment]
If you don't secure the kills the xenos will

**Comment by SzkieletorNutric** [comment]
Uh oh

**Comment by novaepee** [comment]
Haven't implement QoL yet, Bravemole, but want to see if there is anything I need to change.

**Comment by hyper2snyper** [comment]
If you do this, perhaps make xeno corpses not dragable by xenos so marines actually have a chance at securing corpses

**Comment by novaepee** [comment]
Xenomorphs are winning, and marines need all the goods they need.

**Pull request closed without merging**
