### PR TITLE
magnetic harness now makes your gun heavier, aka giving you slowdown on aiming

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
~~oh no~~
magnetic harness now actually has a downside i guess. Which is fair considering splinter buffed it to also go on your back

## Why It's Good For The Game
mag harness is straight up better than every other rail attachment in the game, it should've  been nerfed a long time ago

## Changelog
:cl:
balance: magnetic harness now slows you down when you attach it to your gun and aim 
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
*insert marine main screeches*

**Comment by Pariah919** [comment]
>insert marine main screeches
>
insert funny retort about attachment balance

**Comment by jroinc** [comment]
> > insert marine main screeches
> 
> _insert funny retort about attachment balance_

*insert biased statement with dubious supporting evidence about how this change will kill off marines and drive players away*

**Comment by Jeff-jefferson-jeffery** [comment]
once again
mag harness is better than other attachments because the harness provides real utility while the other top attachments provide dubious at best utility, this is a case of of the alternatives sucking more than the harness being op
rail scopes need your targets to be lit up to have any use cuz they don't have NV
RDS is completely pointless on guns you twohand
rail flashlight is made obsolete because all armor has a light

**Comment by ilikesaying** [comment]
Rail flashlight is only useful for fucking minigunners and flamers who use belt harness or the disposable pistol/revolver mains

**Comment by Dolth** [comment]
I'd say mag harness is the only useful rail attachments not because it's good but because other attachments are useless.
But then if you use magharn you have no real light source.

**Review by Hughgent — APPROVED** [review]

**Comment by Pariah919** [comment]
pick up macro died

so this pr does too

**Pull request closed without merging**
