### PR TITLE
Catslug for research's pet

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title. You can thank Vorestation for the sprites and somewhat code.

## Why It's Good For The Game

More pets, more fluff for marines.

## Changelog
:cl:
add: Add catslug for research. Cute pet.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
image

**Comment by Very-Soft** [comment]
Nice!

**Comment by AndroidMK2** [comment]
Cute moment.

**Comment by Licherr** [comment]
edible

**Review by Kuro020 — APPROVED** [review]

**Pull request merged**
