### PR TITLE
king takes 90 minutes to enter the round

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
60 to 90, effectively considering most drops are at 12:20/30, this is 60/70 mintutes.

## Why It's Good For The Game
King comes in way too fast into the game in general

## Changelog
:cl:
balance: king is locked for 90 minutes rather than an hour
/:cl:

### CODE REVIEW

**Comment by KornFlaks** [comment]
Duplicate #7471

What changed in the time between these two?

**Comment by InterroLouis** [comment]
Not a duplicate. That was 100 minutes, this is 90.

**Review by David-Stormwell — APPROVED** [review]
Should be fine enough.
Even if the first Marine pushes get crushed, they still have a few more minutes to prep and push again before the death timer starts. 

If you are really salty about this as a Xeno main, reminder you can make multiple Kings in a round to really really crush FOBs and grant Xeno majors shipside as well.

**Review by TiviPlus — APPROVED** [review]
David say yes

**Comment by GradusNL** [comment]
This should be closed since #7807 was merged instead. The king mob damage nerf was explicitly described as an **alternative** to this PR.

**Pull request merged**
