### PR TITLE
pistols get aim mode now 

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
marines have learnt to aim with pistols
0.65 slowdown for now across the board

## Why It's Good For The Game
marines are gunning now
also all default guns should get aim mode tbh

## Changelog
:cl:
balance: pistols in general get aim mode
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -145. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by AbsoluteJerry** [comment]
Based. I will now akimbo T-19

**Comment by ilikesaying** [comment]
you can't aim with one hand, femmeboy

**Comment by AbsoluteJerry** [comment]
You have insulted me on a personal level I am so ahyvsdgsgssfs

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-171). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
