### PR TITLE
Remove xeno shuffling marine, remove aimmode 

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

This is an experiment, it's not really meant to be merged.

It does two things:

Marine will be able to body block xeno if that said marine is in harm intent. AKA, you can no longer force the shuffle as a xeno if the marines doesn't want to.

Marine lose the aimmode, except on snipers

## Why It's Good For The Game

At least 40-50% of the xeno gameplay right now is on how to shuffle, either to block marine retreat, to cast a displacement ability (like shrike), or shuffling to bait FF. This is kinda fun as a xeno, but that's not good gameplay at all for marines.

If we remove force shuffle, you push the xenos to be smarter in positionning, and always think on how he will engage, and how he will disengage. 
I think this will make gameplay more interesting for both factions; xeno have to play smarter, which is engaging, and marines no longer suffer of permanent forced displacement and retreat blocking.

I also remove aimmode from every gun but snipers, because this also force marine to be smarter on their positionning. Marine will have to think before shooting, and this allow xenos to attack an unga ball with more ease.

Overall, the goal of this pr is to make positionnal gameplay smarter

## Changelog
:cl:
balance: Xeno can no longer force shuffle
balance: Aim mode is gone on every gun but snipers
/:cl:

### CODE REVIEW

**Comment by EvilMelonTheSecond** [comment]
I accept the new heavy tyr shotgun meta with open arms but xeno will cry an entire ocean for losing their get out of jail free card

**Comment by Losenis** [comment]
It does feel like a uno reverse card given shotgun ungas will start doing the shuffling into an entire ungaball with the knockback if they JUST so happen to be behind a xeno.

**Comment by SilencedMP5A5** [comment]
i like the sound of this ngl

**Comment by Sebbe9123** [comment]
Won't change much i think, the shuffle part at least. Removing Iff might be more than marines can handle.

**Comment by RuneQuester** [comment]
Welp, Shrike just went from easiest to hardest caste

**Comment by Lumipharon** [comment]
I like this change. Both features are very significant for either side, and both have issues as you've described (aim mode is also pretty immersion breaking considering it works full auto, while running, against marines you can't even see off screen or in smoke).

Will definitely shake up gameplay

**Comment by Three333Digit** [comment]
Machinegun users needs their aim mode.

**Comment by Losenis** [comment]
>Machinegun users needs their aim mode.

image

**Comment by Losenis** [comment]
Thought about it more and been seeing more marines just spam autoshotguns with flechettes before this is even TMd, adding marine bodyblocking might just turn xeno gameplay into an unfun mess. If anything it'll lock the game into a shotgun meta since you'd want to get close enough as to not have your shots blocked by other marines anyway.

No caste without gratuitous amounts of stuns/displacement can 1v1 a tyr2 heavy constantly PBing you with a shotgun, and that's assuming it's not buck which will stunlock your abilities away with stagger anyway. And it won't be a 1v1, it'll probably be a 1v3 or 1v4.

**Comment by Licherr** [comment]
I want to see this shit happen. Temporarily ofcourse, I wanna see if the marine skill issue is funny or not.

**Comment by Walarks** [comment]
> I like this change. Both features are very significant for either side, and both have issues as you've described (aim mode is also pretty immersion breaking considering it works full auto, while running, against marines you can't even see off screen or in smoke).
> 
> Will definitely shake up gameplay

Aim mode isn't an immersion concern since the fact that you can only see 6-7 meters in front of you without scope and have eyes on the back of your head is already immersion breaking if we go by that logic.

**Comment by ivanmixo** [comment]
Hm yes remove all the skill needed for fishing and make the shotgun even more meta. No way this can go wrong.

**Comment by SplinterGP** [comment]
> > Machinegun users needs their aim mode.
> 
> image

maybe try not shooting your mate in the head

**Comment by SplinterGP** [comment]
also on second note, to reduce FF from machine guns just give 5 hard bullet armor to marines and all good

**Comment by Sebbe9123** [comment]
> also on second note, to reduce FF from machine guns just give 5 hard bullet armor to marines and all good

Powercreep moment

Unironically dont shoot your friends in the head and you wont get punished for it.

**Comment by DarkWolfKai** [comment]
shuffling is a coward tactic as well a salty one and just as how aim mode made everything a no-efford thing, while people that wont even use it get yelled by the most minuscule of errors, needed removal of both, good riddance

**Comment by Hecklingheck** [comment]
Really not a fan of this, at all. Some castes are specially nerfed by this, such as Shrike and Defiler. 
Removing aimmode is also pretty bad.

**Comment by bowlofcereal** [comment]
how is increasing the amount of friendly fire incidents and allowing me to force a xeno into a corner with a bayonetted buckshot t35 with no way of escaping in any possible way balanced in any shape or form. why are we reinforcing the shotgun meta instead of trying to branch out to make things more viable

i get that this is just an experiment but it is still a pretty bad idea on the drawing board, and i can imagine it would be even worse in action

**Comment by SevenHaven** [comment]
Hi. I made a GitHub account specifically to post this, so I'll be blunt.

After playing a round with this test merged, I am of the full belief that this was made without any regard for the game at all. That was, without a doubt, the most awful experience I have ever had when playing TGMC.

Instead of working with the perfectly functional aim mode and the way xenos play in a positive way, you simply opted to remove abilities from both sides. This is the most backwards form of design I've ever seen in my life. It's obvious to me that the only thought that went into this change as you set it up was 'hey maybe this will do something'. 

Please think about doing things before actually doing them next time.

**Comment by Miczu555PL** [comment]
_Ungas strong together.
No aim mode means unga split, to make room for bullets.
Ungas not strong alone._
**Xeno made this PR. Change my mind.**

**Comment by UntoldTactics** [comment]
A good idea in practice, I just hope it doesn't end in shotgun meta and marines shuffling xenos into ungaball. I can imagine the shield users doing it already

**Comment by ivanmixo** [comment]
> A good idea in practice, I just hope it doesn't end in shotgun meta and marines shuffling xenos into ungaball. I can imagine the shield users doing it already

It will end up in exactly that, lol

**Comment by Notamaniac** [comment]
Since only same factions can shove, marines can cut off xeno escapes by jetpacking over, making double shield jetpack marine disturbingly viable.

Shove should still probably be enabled.

**Comment by Tristan63** [comment]
this actually was a good experience until i got into the caves of big red then it turned into massive FF of epic proportions

i also was using semi on my t12 more often than not, which was pretty cool i guess, esp since i was able to land hits in a marine blob without FFing. Marines are completely capable of winning against xenos even with this "nerf", and xenos are still able to curb marines hard. Honestly this change is a good one, puts more emphasis on SLs and command actually organizing advances, flanks, etc while xenos retain the same relative gameplay, as stuncastes will still drop marines that could've been shufflefucked and then they get dragged to cover and killed for psypoints. The best part of this PR is bodyblocking runners and hunters, seriously, fuck those guys.

**Comment by Mechswordsman** [comment]
Consider, if you try this merge again, also upping xeno HP based on tier to actually allow them the space to fight their way out of a corner.  

In fact, it might even be a good idea to do a seperate PR testing how xenos fare with getting much more hp at higher tiers, but lowering their healing. This would allow those heavy hitters to engage in more decisive battles and win, but not nessecarily recover from them in a timely fashion, allowing for counter play.

**Pull request closed without merging**
