### PR TITLE
Synths can speak in xenocommon

### PR DESCRIPTION
**Pull request by Lefunny**
## About The Pull Request

Synthethics can now talk with xenos

## Why It's Good For The Game

Alow synths and AI to talk with xenos and plan about human extermination

## Changelog
:cl:
add: Synths and AI can speak in xenocommon now

/:cl:

### CODE REVIEW

**Comment by S1tr3p** [comment]
Project Fren Synth is now real.

**Comment by Ragecrabbo** [comment]
finally we will have the means of establishing diplomatic relations with xenomains

**Comment by Pill-U** [comment]
do xenos understand synths automatically or do you have to use some prefix like .a ?

**Comment by Lefunny** [comment]
> do xenos understand synths automatically or do you have to use some prefix like .a ?

i just gave synths the lenguage, you can set it as your sefault or use the prefix

**Comment by Derrick2Electricboogaloo** [comment]
Woohoo, now I they can understand me when I call them a cunt.

**Comment by Derrick2Electricboogaloo** [comment]
> do xenos understand synths automatically or do you have to use some prefix like .a ?

Synths can undetstand beans, but not vice versa

**Comment by Lefunny** [comment]
> Woohoo, now I they can understand me when I call them a cunt.

now you can understand and call they cunts back

**Comment by Losenis** [comment]
https://youtu.be/saaKnLX_qHU?t=9

Synth to xenos the first round this is TMd after hearing them shittalk for the Nth time

**Comment by vilereaver41** [comment]
Nice we can crap talk em now

**Comment by Losenis** [comment]
image
Best PR

**Pull request merged**
