### PR TITLE
Barrenquilla Mining Facility 2.0

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

Map wasnt liked because it had to much lava, this PR fixes all that.

## Why It's Good For The Game

The map has been tinkered with and revamped to a degree whilst keeping much of the original its also a fresh change to the same old maps.

## Changelog
:cl:
fix: 95% of lava is now gone
balance: lz's are a bit bigger and harder to penetrate into
balance: south of map is more xeno oriented for a better hive structure
add: new acid smoke enviormental effect made from acid splash remains on the turfs around xeno area with a strength of 3
add: zones and regions are now properly done north, northeast/etc meaning Tadpol and drop pods now work
fix: removed some useless outer map features that were meant for cosmetic but were really ugly

/:cl:

1 
image

2 - Just map layout
image

### CODE REVIEW

**Comment by Araulius** [comment]
pog

**Comment by Mrrpip** [comment]
No more void corgi :(

**Comment by Losenis** [comment]
>Removed the fun bar zone

Disgusting

**Comment by Ragecrabbo** [comment]
barren hunt when?

**Comment by Victor239** [comment]
See https://github.com/tgstation/TerraGov-Marine-Corps/issues/9766

**Pull request merged**
