### PR TITLE
Triples damage from guns/acid spit and xeno melee

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
3x damage for guns and xeno melee.

## Why It's Good For The Game
I think and believe our population is too high on average on a basic god given TGMC round, and we need a PR like this to reduce our overall player count by removing people from the round faster.

### CODE REVIEW

**Comment by Lefunny** [comment]
Based

**Comment by Luxyboo** [comment]
triple armour, health and plasma

**Comment by Ragecrabbo** [comment]
Finally some runner buffs

**Comment by MiniMeatwad** [comment]
why tho

**Comment by Fawcksy** [comment]
crackhead gaming

**Pull request merged**
