### PR TITLE
drone speed up from weeds massively reduced

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
-0.4 to .1

## Why It's Good For The Game
drone shouldn't be as fast as an ancient runner on weeds considering it can make weeds itself and has decent utility overall
this caste has been massively powercreeped overtime 

## Changelog
:cl:
balance: drone speed up on weeds reduced
/:cl:

### CODE REVIEW

**Review by SplinterGP — APPROVED** [review]

**Comment by usnpeepoo** [comment]
lol just pb the drone whats it gonna do? slash you for like 20 damage?

**Comment by davidchan13** [comment]
How bout you nerf castes that are actually over performing instead of the ones that annoy you?

**Comment by Walarks** [comment]
If drone is not supposed to fight, you can instead reduce slash by 50%+ and let it speed around to do support stuff/weed.

**Comment by davidchan13** [comment]
> If drone is not supposed to fight, you can instead reduce slash by 50%+ and let it speed around to do support stuff/weed.

Drones already do pitiful damage in a fight. Anyone who thinks drone is overpowered needs to get good or pay more attention. **Ancient** Drones do a whopping 20 damage a slash. Someone wearing Infantry Jaeger requires 12 slashes to put into crit, that's assuming no Tyr, no shield, and no premud or drugs healing them. PAS-11 takes 13 hits from a drone to put them into crit.  

With a whopping 300 HP and 31 bullet armor, it only takes 17 shots from a T-12 or T-18 to kill a drone. Guess which attacks faster, bullet or bump slash? Give you a hint, there is no such thing as burst slashing.

These people complaining about drones being too good are a combination of unrobust and allowing the drone to dictate the terms of the fight (I.E. fighting them in open areas with weeds, rather than pulling back to somewhere WASD won't let them get free hits), 2 buckshots at point blank kills a drone, no matter what pheros they have running. This is the equivalent of a xeno player being shot while standing in the open by a sniper, and complaining snipers are OP when they are doing nothing on their end to avoid a situation where they are standing out in well lit areas with no cover.

**Comment by SplinterGP** [comment]
> 
> 
> > If drone is not supposed to fight, you can instead reduce slash by 50%+ and let it speed around to do support stuff/weed.
> 
> Drones already do pitiful damage in a fight. Anyone who thinks drone is overpowered needs to get good or pay more attention. **Ancient** Drones do a whopping 20 damage a slash. Someone wearing Infantry Jaeger requires 12 slashes to put into crit, that's assuming no Tyr, no shield, and no premud or drugs healing them. PAS-11 takes 13 hits from a drone to put them into crit.
> 
> With a whopping 300 HP and 31 bullet armor, it only takes 17 shots from a T-12 or T-18 to kill a drone. Guess which attacks faster, bullet or bump slash? Give you a hint, there is no such thing as burst slashing.
> 
> These people complaining about drones being too good are a combination of unrobust and allowing the drone to dictate the terms of the fight (I.E. fighting them in open areas with weeds, rather than pulling back to somewhere WASD won't let them get free hits), 2 buckshots at point blank kills a drone, no matter what pheros they have running. This is the equivalent of a xeno player being shot while standing in the open by a sniper, and complaining snipers are OP when they are doing nothing on their end to avoid a situation where they are standing out in well lit areas with no cover.

>Pitiful damage
>1 less than rouny
🤣

**Comment by davidchan13** [comment]
> > Pitiful damage
> 
> 1 less than rouny
> way more resistant with only downside of very little speed which then they got frenzy to keep up with rouny

Rouny has evasion, pounce (an actual stun to force marine to drop their weapon) and the ability to run over tables, window frames and other climbable objects without pause.  Theres a huge gap between the combat potential of these castes.

**Pull request merged**
