### PR TITLE
change /droid/welder_act wording and update droid healthbar

### PR DESCRIPTION
**Pull request by Pill-U**
## About The Pull Request
Changes the alerts and adds an alert for when you try to repair a full hp droid
Droid healthbar updates when the droid gets repaired

## Why It's Good For The Game
Current alerts sound a bit off. These new ones are a bit large due to [src] but acceptable as long as you play above 800x600
Also you can rename the droid to shitfart14 MK9001 and it'll work
The healthbar health being different from the actual health is annoying and confusing

## Changelog
:cl:
fix:droid healthbar updates when repaired
/:cl:

### CODE REVIEW

**Comment by Pill-U** [comment]
"Make Shrike stronk" is from an older PR that got merged anyways not sure why thats there cause the PR got merged but shouldn't matter

**Comment by BraveMole** [comment]
> "Make Shrike stronk" is from an older PR that got merged anyways. Not sure why that's there since the PR got merged, but shouldn't matter

That means you branched out from the branch that made the pr.

This isn't an issue here, but that may become an issue on future pr

**Comment by Pill-U** [comment]
I did not tho? I only have my main branch currently

**Comment by BraveMole** [comment]
In that case, not having a new branch didn't cause issues; because the previous pr was merged, and because you didn't make another pr on the side. So it's not a problem here.

I can't reopen because you apparently deleted your repo though

**Pull request closed without merging**
