### PR TITLE
this adds the m25 to marine vendor just like the PPSH

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
this adds the m25 to marine vendor just like the PPSH

## Why It's Good For The Game
gives marines another SMG option roundstart

## Changelog
:cl:
add:the m25 to marine vendor just like the PPSH
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -7. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SilencedMP5A5** [comment]
i actually kinda think the M25 is just a straight better SMG than the T90 just like the M412 is a better T12

so this probably won't fly

**Comment by fernandos13** [comment]
oh.. is it? i just got it in for being "**effective one-handed** use that is ideal for close to medium range engagements. Uses 10x20mm rounds in a high capacity magazine."

**Comment by fernandos13** [comment]
own description "while the T90.. is not that good one handed.. even with supressor.. and laser sights.. and red dot.. idk what else to put tbh to make it .. better at one handling the T90
while the m25. flies pretty well with supressor gyro and red dot "i think the fact you CAN use a gyro in it is what makes it good"

**Comment by fernandos13** [comment]
SO from codex:
**_T90_**
> Basic Statistics for this weapon are as follows:
> Size: 4
> Base melee damage: 20
> Accuracy: +15%
> Damage modifier: 0%
> Damage falloff: -1 per tile travelled.
> Burst scatter chance multiplier: x3
> Accuracy modifier: 5%
> Accuracy unwielded modifier: -20%
> Recoil Unwielded: 0.5
> Unwielded Scatter chance modifier: +30%
> Movement unwielded penalty modifier: -45%
> Time between single-fire: 0.165 seconds
> Wield delay: 0.5 seconds

**_M25_**

> Basic Statistics for this weapon are as follows:
> Size: 4
> Base melee damage: 8
> Accuracy: +25%
> Damage modifier: 0%
> Damage falloff: -1.1 per tile travelled.
> Recoil: -4
> Scatter chance modifier: 10%
> Burst scatter chance multiplier: x3
> Accuracy modifier: 5%
> Accuracy unwielded modifier: 0%
> Recoil Unwielded: -3.5
> Unwielded Scatter chance modifier: +15%
> Movement unwielded penalty modifier: -37.5%
> Time between single-fire: 0.175 seconds
> Wield delay: 0.4 seconds
> Shots fired on burst mode: 3
> Time between burst-fire: 0.2 seconds

**Comment by RenGusta** [comment]
Marines have a better one handed SMG in the T19. Bloat detected.

**Comment by SplinterGP** [comment]
the M25 is available at Imports at req, its a PMC gun(not just that better), and can be found on map armories

**Comment by fernandos13** [comment]
t19 is technically a middleground between SMG and pistols...
sure better one handed than ANY other gun aside from literal pistols i guess
still i just want to have more SMG variety in the vendor. 
instead of
T90 
PPSh
and the T19 ""that is.. moving back and forth as a pistol or SMG"

**Comment by Chaznoodles** [comment]
Not a fan.

As far as I'm aware, it outclasses the standard T90, and with the "effective one-handed use that is ideal for close to medium range engagements", probably the T19 as well. The less accuracy can easily be handled via attachments, resulting in this being the better choice and the other two being irrelevant.

Also haha gun bloat go brrr, 4 SMGs to go with our 4 shotguns and 5 pistols

**Comment by TiviPlus** [comment]
Gun bloat

**Pull request closed without merging**
