### PR TITLE
adds a req only way to make advanced chemicals, lemoline

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
adds a req only way to make advanced chemicals if marines want to spend points on it

## Why It's Good For The Game
another way to get advanced chemicals that's expendable but expensive

## Changelog
:cl:
add: Added new recipe only req chem, added bottle sprite just for it
balance: added lemoline a way to get advanced chems with req
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -49. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
Please stop trying to give non-medical ungas advanced chems roundstart.

This gives ANOTHER thing for PFC's to try and rush and spend all the points on and keep to themselves. (and would enable 300 to 600u of advanced chems roundstart, enough to flood the battlefield. Again.)

There's a reason the MEDICAL roles get free advanced chems, with the option of purchasing more, and the non-medical ones don't.

**Comment by Chaznoodles** [comment]
lemon lime

**Comment by Pariah919** [comment]
>Please stop trying to give non-medical ungas advanced chems roundstart.

>This gives ANOTHER thing for PFC's to try and rush and spend all the points on and keep to themselves. EDIT- But will not flood the battlefield.

>There's a reason the MEDICAL roles get free advanced chems, with the option of purchasing more, and the non-medical ones don't.
you can already buy them for 30 for 120 so I don't see anything wrong with this

**Comment by Pariah919** [comment]
you also only get like 120 points in the early game so you're literally spending 1/3rd of your points for some extra advanced meds ~~when you can literally just go corpsman and get them for free lol~~

**Review by Hughgent — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-62). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
