### PR TITLE
Removes jumping

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Removes this bad and unnecessary part of the game.
## Why It's Good For The Game
Remove unneeded bloat.
## Changelog
:cl:
del: Removed the jump emote
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
i read pr title, and i got JUMPSCARED
but reading pr further, i relaxed when i saw that jump emote was getting removed, not jump

**Comment by Tommy-211** [comment]
clickbait

**Comment by Pariah919** [comment]
I can't believe you're removing this hyper important emote and not the WORTHLESS and TRASH mechanic that is jumping.

**Comment by DerpiestBruh** [comment]
HRP nerf of the year. Will roleplay ever recover?

**Comment by TellyLsc** [comment]
No.
I bind my jump emote AND the jump action to the same key.

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
