### PR TITLE
Russian Red rework

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Russian red rework
- Now knocks you out durning the process of healing, with a slight delay.
- Heals slightly more (8 per tick)
- Clone loss is way less. Also offset by the fact you're sleeping.
- The windup before the heal has incredibly high pain resist, you could technically use this as a super inaprov if you time it well on downed teammates.
## Why It's Good For The Game
Makes Russian Red less of an emergency combat chem and more of an emergency out of combat chemical, you could still use it in combat for the super high pain resist, however such a manuever is ill advised.
## Changelog
:cl:
balance: Russian red has been entirely reworked, it now knocks you out durning the process of healing, has slightly higher healing, has high pain resist before the windup, the emergency healing on crit marines has been unchanged.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
So robot repair mode in an injector

**Comment by Barnet2** [comment]
This is alot healthier than "win a fight for free" atleast.

**Comment by srxtreme** [comment]
1. We have a chem that does almost exactly this, it's called somolent.
2. In the same period of time you could've healed yourself for a similar amount of health without using a snowflake CL causing medicine as well as yknow. Stunning yourself for a shitload of time and spending 20 seconds waiting for the meds to kick in.
3. If you want to remove a chem from the game PR a hard removal.

**Comment by QualityVan** [comment]
This does seem like just somolent. Faster activation, but less healing and also it causes cloneloss instead of fixing it.

**Comment by Arturlang** [comment]
Yeah I agree that RR is *really* bad when used together with certain things, but this isn't the way to go about this.

**Comment by Lumipharon** [comment]
Somolent 2

**Pull request closed without merging**
