### PR TITLE
Resprites 571, adds 2 new sentry types.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Adds new sentry sprites.
Adds Sniper and Shotgun sentry, 2 for free for now for testing purposes.
Stats below if you really care.

<details>

Shotgun Sentry
- Damage: 20
- Pen: 40 (so it can damage most castes in the game consistently.
- Pellets: 7
- Spreads consistently in a <) shape
- Drum Size: 100
- Range: 8
- Fire Delay: 1 SECONDS

Sniper Sentry
- Damage: 80
- Pen: 50
- Sundering: 5
- Drum Size: 75
- Range: 21
- Fire Delay: 1 SECONDS
</details>

## Why It's Good For The Game
Adds new sentry guns for more variety of what you can get, allowing for more interesting base setups and defences. Also updates the ages old sentry sprites.
## Changelog
:cl:
add: Added new Sniper and Shotgun sentry to the marine arsenal, as well as new sentry sprites.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
sniper sentry sounds absolutely hilarious. 
good pr spedemerhg

**Comment by Lumipharon** [comment]
I foresee absolutely no issues with mass sniper turrets insta killing xenos from 3 screens away.

**Comment by Kuro020** [comment]
> I foresee absolutely no issues with mass sniper turrets insta killing xenos from 3 screens away.

if its a issue we could make it lase xenos before shooting, but lets test like this for now

**Review by Kuro020 — APPROVED** [review]

**Comment by lbnesquik** [comment]
booo put pictures

**Comment by SimplySmiley123** [comment]
> i eagerly await seeing the sniper sentry empty all its ammo into a wall firing at a runner 20 tiles away

I cannot wait for these sentries to get cheesed by warlocks anyway.

**Comment by Yttriums** [comment]
:clueless:

**Review by TiviPlus — APPROVED** [review]
No way it could go wrong

**Comment by Arturlang** [comment]
Xeno sniper sniper turrets when?

**Pull request merged**
