### PR TITLE
smoking is cool, right?

### PR DESCRIPTION
**Pull request by grinkgo**
## About The Pull Request

Increases cigarette pack capacity to 18. Adds some fancy cigars to contraband. Also adds a little bit of nicotine to cigars.

## Why It's Good For The Game

ar-pee and muh immersion.

## Changelog
:cl:
tweak: Cigars actually have nicotine in them now.
tweak: Cigarette packets now contain 200% more cigarettes!
/:cl:

### CODE REVIEW

**Comment by MoXuT0** [comment]
Might wanna update sprites too, because visually they still can hold only 6.

**Comment by Rohesie** [comment]
Where is the nicotine added?

**Comment by grinkgo** [comment]
> Might wanna update sprites too, because visually they still can hold only 6.

ah tits, you are correct.

**Comment by grinkgo** [comment]
> Where is the nicotine added?

Just pushed it. oops

**Comment by grinkgo** [comment]
Having storage issues I'll try to fix tomorrow

**Pull request merged**
