### PR TITLE
Flamethrower Rework 2

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
reworks the flamethrower to be like a proper flamethrower, fire burn time decreased so if you want area denial your gonna need to constantly expend ammo deletes nozzles and flamethrower code deletes x fuel and replaced with new flamethrower that fires x fuel but uses normal flamethrower tanks

also updates sprites

stats not final
image

https://user-images.githubusercontent.com/98577688/236756196-75ce7692-a11a-4b6b-8ffa-14b495210558.mp4

todo: balance it, maybe get a new sound
## Why It's Good For The Game
flamethrowers now work like videogame flamethrowers rather than whatever ss13 flamethrowers are, will require more ammo management now
sprites are cooler i guess
## Changelog
:cl:
add: reworked flamethrower
add: flx-150 flamethrower
del: x fuel
del: flamer nozzles
balance: rebalanced something
imageadd: new flamer sprites
code: removed flamer code
/:cl:

### CODE REVIEW

**Comment by ClosetedSkeletonGH** [comment]
Am I crazy or did you add bird noises to Orion

**Comment by Lumipharon** [comment]
Its not really like a video game (or real) flamer though, its an incendiary machine gun.

SS13 flamers are definitely weird, but thats more a visual thing. They still flame an actual area of effect, where as this flamer (and extended nozzle) only hit one thing, which blocks the fire. Explodey fire is cool though.

**Comment by maikilangiolo** [comment]
> new flamethrower that fires x fuel but uses normal flamethrower tanks

Zased....so fvcking based....

**Comment by KillerOrcaCora** [comment]
Something about it just feels very uncanny and not really fitting for the medium.

**Comment by maikilangiolo** [comment]
I think the on-hit damage should be increased a bit. You need to burn a lot of fuel now, which is good if it has a better tradeoff

**Comment by isotope436** [comment]
this is actually pretty neat and i could see it having use however i do not like the sprites but thats just me

**Comment by FosterGrime-Heymynameslouie** [comment]
THE FLAMETHROWER REWORK RETURNS

GODLBESS YOU TYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Mrrpip** [comment]
My question is this: How will the new flamethrower tanks react to trying to use them to reload a jetpack?

Currently, it is possible to reload jetpacks with flamethrower magazine tanks (Or attachable mags? Point is, not the backtank mags, the normal ones.). Will this have any jank reactions or has the ammo increase in the mags been compensated for and taken into account?

**Comment by BlueHNT** [comment]
This looks like a very cool rework, however. It might cause balance issues if there's direct hit damage from the stable flamethrower as they are already one of the most potent and powerful tools at marine disposal.

**Comment by Aporhtonoma** [comment]
flamethrowers a glorified wall cleaner and even then most of the times they shutoff marine pushes this is a good fucking change .give them more damage or nerf all xenos flame armor but THIS is what flamers need to be no question about it.

**Comment by Tonklaatech** [comment]
> My question is this: How will the new flamethrower tanks react to trying to use them to reload a jetpack?
> 
> Currently, it is possible to reload jetpacks with flamethrower magazine tanks (Or attachable mags? Point is, not the backtank mags, the normal ones.). Will this have any jank reactions or has the ammo increase in the mags been compensated for and taken into account?

How are you gonna refuel a jetpack with napalm

**Comment by Arctrooper8** [comment]
I'm curious, what happens to underbarrel flamers? Are they simply gone or do they also act like the new flamers now?

**Comment by Mrrpip** [comment]
> > My question is this: How will the new flamethrower tanks react to trying to use them to reload a jetpack?
> > Currently, it is possible to reload jetpacks with flamethrower magazine tanks (Or attachable mags? Point is, not the backtank mags, the normal ones.). Will this have any jank reactions or has the ammo increase in the mags been compensated for and taken into account?
> 
> How are you gonna refuel a jetpack with napalm

It just works. The point is, if it's not thought out, things will break/unintentionally change balance. Don't care if the interraction is shrugged at, removed entirely or adjusted. But it should be pointed out at the very least.

#12303 for example didn't take the UBF/Backtank into account and had broken the interraction.

**Comment by FosterGrime-Heymynameslouie** [comment]
> > > My question is this: How will the new flamethrower tanks react to trying to use them to reload a jetpack?
> > > Currently, it is possible to reload jetpacks with flamethrower magazine tanks (Or attachable mags? Point is, not the backtank mags, the normal ones.). Will this have any jank reactions or has the ammo increase in the mags been compensated for and taken into account?
> > 
> > 
> > How are you gonna refuel a jetpack with napalm
> 
> It just works. The point is, if it's not thought out, things will break/unintentionally change balance. Don't care if the interraction is shrugged at, removed entirely or adjusted. But it should be pointed out at the very least.
> 
> #12303 for example didn't take the UBF/Backtank into account and had broken the interraction.

looking at the code flamer mag remains untouched
you can still very much use it to refuel jetpacks

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Actual rest of the code looks fine I guess

**Comment by Joe13413** [comment]
might be out of the scope of this PR but new SFX would probably be in order, something more continuous instead of what sounds like the flamer turning on and off

**Comment by FosterGrime-Heymynameslouie** [comment]
apart from the pr completely fumbling quick equp the new flamer is a substantial upgrade to the old one spedgemehrg inasntaly

**Comment by tyeagg** [comment]
> apart from the pr completely fumbling quick equp the new flamer is a substantial upgrade to the old one spedgemehrg inasntaly

it was strip menu fucking it up i told you this yesterday

**Comment by FosterGrime-Heymynameslouie** [comment]
> apart from the pr completely fumbling quick equp the new flamer is a substantial upgrade to the old one spedgemehrg inasntaly

~~apart from the pr completely fumbling quick equp the~~ new flamer is a substantial upgrade to the old one spedgemehrg inasntaly

**Review by Kuro020 — CHANGES_REQUESTED** [review]
The normal flamer is way too ugly, I see no reason to make the limited one have a better sprite than the one that will show up everywhere

**Comment by maikilangiolo** [comment]
1. xfuel glob mode spawns normal fuel and not x fuel
2. the flames are way too slow to travel. you legit cant hit xenos unless they walk at you. removed all the offensive abilities of flamer since xenos can easily sidestep it (runners can dodge it too) or walk out of range

**Comment by Mrrpip** [comment]
One odd balance consideration is this. As a projectile, all 3 modes can now be reflected by warlocks.

On the other hand though, who goes hunting warlocks with flamers?

**Comment by Krypandenej** [comment]
If this deletes the flamethrower nozzles, are you planning on changing the hydrocannons to work similarly? They also use the nozzles and I would hate to see the extended nozzle mode on mine go.

Also, echoing what some have said in the rework test, but this feels like a huuuge nerf, plus the pilot flame at the end looks... A little uncanny.

**Comment by novaepee** [comment]
Fuel economy leaves much to be desired. It takes 15 fuel to get rid of 1 resin walls. With large flamerthrower tank of 200 fuel, only 13.33 walls can be destroyed. With back fuel tank of 700, 46.66 walls can be destroyed.

**Comment by QualityVan** [comment]
I don't like this because it removes the current flamethrowers and I like those.

**Comment by TiviPlus** [comment]
> I don't like this because it removes the current flamethrowers and I like those.

valid tbh

**Comment by zzurge** [comment]
Ive been skeptical of the flamethrowers thing for a while but bringing X fuel out of req hell in light of the changes...i might be coming around ngl

**Comment by Arctrooper8** [comment]
When is this actually getting TM'd? I haven't seen it a single time on the server since it got the TM candidate tag.

**Comment by Lumipharon** [comment]
why was xfuel removed and replaced with 'better flamer makes fire better also blue'? The lack of req dependency is lame, also muh immersion or whatever.

**Comment by Burger1998** [comment]
> Underbarrel needs to be toned down unlike its big counterpart it does not have a do after and its ammo is much easier to store.

**Comment by Pinkufeck** [comment]
The fuel efficiency is way down for clearing walls, don't know if it's intentional.

**Comment by Krypandenej** [comment]
I feel like the back fuel tank needs a buff to justify carrying it around, given the new large fuel tanks are, what, 400 units each? The backpack is only 1000, why not buff it to at _least_ 1200?

**Comment by FosterGrime-Heymynameslouie** [comment]
very cool pr please mergh

**Review by Kuro020 — APPROVED** [review]

**Comment by ivanmixo** [comment]
Needs a wall piercing nozzle or this is a straight downgrade and a balance concern since tools to deal with the xeno maze in a timely manner are few and far between as is.

**Comment by maikilangiolo** [comment]
> Needs a wall piercing nozzle or this is a straight downgrade and a balance concern since tools to deal with the xeno maze in a timely manner are few and far between as is.

Disagree. I've used these ones extensively, and the wall pen loss is not that noticeable. You can take down walls quick enough after the improvements (don't hold down M1, just do two short bursts and you're set), so even if you can't take down 2-3 walls in a row, you take down one much faster. Consider than the burn timer is much, much shorter than with previous flamers, so 3 walls in a row meant you had to wait for the fire to clear, or waste water on it.

**Comment by isotope436** [comment]
bring back S fuel >:(

**Comment by Lumipharon** [comment]
To reiterate my point for other maints, I like Tye's flamers, but I don't like it replacing existing flamers as they have a very different role. I'd prefer it as A: a different nozzle, or B: A different gun (i.e. if the plasma flamer cannon thing worked like Tye's flamer, I think that would be awesome).

**Comment by tyeagg** [comment]
thsi pr is in hell

**Comment by maikilangiolo** [comment]
Holy fucking shit, this is such an improvement over normal flamers and yet it stuck in pr hell due to personal bias

**Comment by Lauwma** [comment]
Bring this back, NOW!!

**Pull request closed without merging**
