### PR TITLE
Fatty Rework 2.0 (Cluster strikes back!)

### PR DESCRIPTION
**Pull request by KacperRaid**
## About The Pull Request

Changes fatty back to its original state from before #9786

Adds prediction to the first Explosion for Fatty

## Why It's Good For The Game
_Approved from original author!_
Fatty back

### But why?: 

- HE OB is just better version of you, with more range and damage to every xeno structure and xenos for less hussle.
- PC does your job faster, and its less expensive in long run, it can also remove weeds, other types of walls and hurt xenos.
- Flamers are practicly dominating wall removal game, by the time you manage to get a shot out, they will remove that maze twice.
- Marines with boot knife can effectly remove walls _if they suck it up and actually do it_, and they cost less then your rockets!

**Overall fatty is in pretty bad place right now.**
so to change that, i'm making it back to cluster explosive!

## Changelog
:cl:
add: Adds prediction to first explosion for Fatty
balance: Instead of walls, Fatty now remove lives (also brings back cluster explosion)
balance: Changes price back to 250 points
/:cl:

### CODE REVIEW

**Comment by Araulius** [comment]
bring back the x fuel napalm bomb while you're at it

**Review by TiviPlus — CHANGES_REQUESTED** [review]

**Comment by Starfirejordan** [comment]
marine keep getting FF by me because they see the area of effect warning for fatty and think its small thus walks into the area of effect for the split of 8 explosion's, it quite funny watching a marine think there safe near it only to be hit by 2-3 explosion's and instantly crit or die

**Comment by KacperRaid** [comment]
> marine keep getting FF by me because they see the area of effect warning for fatty and think its small thus walks into the area of effect for the split of 8 explosion's, it quite funny watching a marine think there safe near it only to be hit by 2-3 explosion's and instantly crit or die

i've actually intented to make prediction for that cluster effect as well, but scarpped it due to preformence issues it caused.

**but on topic of FF, that is actually by original design!**

"Fatties" were supposed to give false sense of security after first explosion (tricking xenos or _**ungas who don't pay attention to comms**_ into thinking its minirocket) into pushing right after it gone off, just to be blasted by 8 other explosions few seconds later. 

**However**
back then we only had green dot for every CAS weapon, making it really unpredictable what CAS is going to drop on everyone heads. 
**But** now we have custom dots for every single one of them, so I think its just gonna be matter of time before everyone starts recognizing 4 deep blue dots with cluster death from above. _and get hint to start running away from that "safe zone"._

**Comment by TiviPlus** [comment]
>but scarpped it due to preformence issues it caused.

This sounds like you were doing something very wrong

**Comment by KacperRaid** [comment]
> This sounds like you were doing something very wrong

Yea, i was thinking same thing, so i asked original author about it.
and he had same problems.

> Also code-wise calculating prediction for 9 different explosions would be painful so we're not doing that. Fatties already freeze the game for a couple seconds on their own

from #9786

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
