### PR TITLE
"Logistics Bike" balance

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Once upon a time I was told (by maints) the motorbike vehicle is meant to be used for logistics and carting around supplies on the surface.
Unfortunately, its abuse has only worsened since its introduction with the sidecar and fire extinguisher shenanigans.
This PR seeks to make taking it into front lines battle, or close up combat period, a fairer amount of risk compared to what is now.

Contrary to popular belief xenos cannot unbuckle with help intent, so please do not cite that bad info in the comments.

Alien attacks on the bike itself unbuckles the rider(s).
Additionally if they are in motion they are thrown off the bike in the direction of travel.

Closes: #13217

## Why It's Good For The Game

Long overdue semblance of balance.

## Changelog
:cl:
balance: Motorbikes unbuckle their rider(s) when attacked by xenos, and if they are moving are thrown forward from the vehicle. Not possible with bump attacks.
fix: When unoccupied Motorbikes are bump attackable by xenos on harm intent, otherwise redirects to the driver like usual.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
This just makes bikes awful at attacking, though? Seems heavyhanded.

**Comment by Wayland-Smithy** [comment]
That is the point.

**Comment by Mrrpip** [comment]
Yeah...But uh....It won't be great for support neither (Despite the fact that it never was.), because you're going to get flung 9 miles the moment a runner decides to backline, instantly losing whatever supplies you were dragging. (And possibly had in the bike with that paralyze.)

**Comment by Derrick2Electricboogaloo** [comment]
Can not wait for the one random ass backlining hunter to just invalidate this vehicle.

**Comment by FIXTHERADBOXPLEASE** [comment]
> Yeah...But uh....It won't be great for support neither (Despite the fact that it never was.), because you're going to get flung 9 miles the moment a runner decides to backline, instantly losing whatever supplies you were dragging. (And possibly had in the bike with that paralyze.)
Just shoot at the single runner with a rifle and kill it. The supplies aren't destroyed because you got attacked once.

**Comment by zzurge** [comment]
Bro chased a bike marine and got put down doing it so he got to writing a PR Mid game

**Comment by Lumipharon** [comment]
This seems extremely cope, bikes aren't even particularly good for combat. The extinguisher thing is a bug that needs to be fixed. I don't see why this is needed at all?

**Comment by maikilangiolo** [comment]
>he doesn't know any of the 500 stuns immediately unbuckles

**Comment by chizzy376** [comment]
> Just shoot at the single runner with a rifle and kill it. 

We can shoot rifles onehanded now?

**Comment by Wayland-Smithy** [comment]
I don't fight bikes because I recognize them for the abuseable vehicle they are. I have simply seen too many xenos die trying to run from 2 people with SMGs that hug an unga ball only overextending INTO A MAZE to abuse their speed and stacked firepower then dash back into cover before anyone can land a stun in such tight quarters. You can't stun them in the open with any amount of supporting marines either because they move too fast. Good luck landing a crusher fling, defender sweep, runner pounce, etc.. If you think it is so easy I invite you try.

Say "xope, just stun" all you want, but we all know calls for stun removal and actions in that direction are all too common so that just sounds silly.

**Comment by Wayland-Smithy** [comment]
> Yeah...But uh....It won't be great for support neither (Despite the fact that it never was.), because you're going to get flung 9 miles the moment a runner decides to backline, instantly losing whatever supplies you were dragging. (And possibly had in the bike with that paralyze.)

For the record it's 2 tiles max so bike - 1 tile - you, less if anything is in the way, and .5 seconds is just a token to knock a weapon out of your hands. You are pretty much already standing back up by the time you reach the ground.

**Comment by bowlofcereal** [comment]
> > he doesn't know any of the 500 stuns immediately unbuckles

**Comment by Wayland-Smithy** [comment]
> > > he doesn't know any of the 500 stuns immediately unbuckles

I don't get how that is relevant when it usually plays out like this:

"Oh noes I was unbuckled by queen screech, king roar, boiler glob, spitter/prae spit, and so forth" 
_\*click drag sprite onto bike\*_ 
"nevermind, enjoy the cooldown sucka"

**Comment by Wayland-Smithy** [comment]
> > > he doesn't know any of the 500 stuns immediately unbuckles

Really disappointed to see your continual bad takes bowl just to be a pure troll but I'll bite. You are a horrible example of staff.

I don't get how that is relevant when it usually plays out like this:

"Oh noes I was unbuckled by queen screech, king roar, boiler glob, spitter/prae spit, and so forth" 
_\*click drag sprite onto bike\*_ 
"nevermind, enjoy the cooldown sucka"

I am curious are there any other marine mobile offensive threats that require specific high cooldown displacement stuns to have any hope of killing?

**Comment by blackdav123** [comment]
wraith can already hard counter bike by either banishing the bike and eating the defenseless rider or banishing the rider and eating a defenseless bike.

removing the fire extinguisher interaction is the only good part mentioned in the PR yet you didnt even do that

**Comment by Wayland-Smithy** [comment]
I have no obligations to the codebase, you are free to fix extinguishers as-well you know.

Simply pointing out a hard counter, situational option, exists is the weakest flavor of argument and I am so sick of it.
A lot of imbalanced things in the past have had counters that are found and used out of necessity. That as little impact here other than to point out a common counter is indeed lacking.

**Comment by TiviPlus** [comment]
> Once upon a time I was told (by maints) the motorbike vehicle is meant to be used for logistics and carting around supplies on the surface.

Dunno who told you this but as the creator it wasnt what it was made for

**Comment by TiviPlus** [comment]
The other PR is much more reasonable for discussion and this is very heavy handed so I'll go ahead and close it

**Comment by Wayland-Smithy** [comment]
> > Once upon a time I was told (by maints) the motorbike vehicle is meant to be used for logistics and carting around supplies on the surface.
> 
> Dunno who told you this but as the creator it wasnt what it was made for

Pretty sure you in particular have defended pulling things while on bike with "logistics" as a chief concern. The RO controls bike access after-all. I see no point in finding discord proof when you seem to have changed your stance since.

> The other PR is much more reasonable for discussion and this is very heavy handed so I'll go ahead and close it

Fair enough.

**Comment by Wayland-Smithy** [comment]
Reply was directed at the original comment, but I also think pointing out staff setting a bad example for the community is valid.

> the average person still will have their key one of the WASD key which displaces you from the bike

Skill issue. It's the ones who are, above average in your opinion, that are reacting by letting go of WASD until they rebuckle that are the problem here. It takes 1 tick to rebuckle and negate almost all negative effects so you can zoom away from the danger.

**Comment by chizzy376** [comment]
> Skill issue. 

We're done here

**Pull request closed without merging**
