### PR TITLE
Adds a speedloader for the leicaster repeater.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds a speedloader for the leicaster repeater.
image

## Why It's Good For The Game
Refilling the repeater by hand is miserable. This adds a speedloader that you can use to reload a repeater once it's empty.

## Changelog

:cl: @Xander3359 @KillerOrcaCora 
add: Leicaster Repeater Speedloader
imageadd: Leicaster Speedloader sprites
/:cl:

### CODE REVIEW

**Comment by Mrrpip** [comment]
Well, they shouldn't end up as a big X in the big ammo boxes, due to inheriting the rifle's sprite. So, that's good!

**Comment by BlueHNT** [comment]
I may be a xoper, but this kinda addition for a widely unpopular gun sounds nice. Even if it might be slightly annoying for me.. Tbf Mosin might be meta again if it had a clip too..

**Comment by KrabSpider** [comment]
It's effectively a shotgun with aim mode. Having it cause carpal tunnel is a fine enough tradeoff.

**Comment by KillerOrcaCora** [comment]
Ugly ass sprite

**Comment by Xander3359** [comment]
mosin has a clip...

**Comment by BlueHNT** [comment]
> mosin has a clip...

Ok ah uh, stinky

**Comment by Jalopkomit18** [comment]
Nitpick but a clip for a lever action rifle doesn't make sense. Closest thing I've found is this tube you shove into feed port, but even then it seems janky
image

**Comment by Xander3359** [comment]
That tube is what inspired this.
Orca also propsed a different sprite for this but Kuro hasnt responded to either
image

**Comment by BlueHNT** [comment]
>It's effectively a shotgun with aim mode. Having it cause carpal tunnel is a fine enough tradeoff.
@KrabSpider

I wish it was, but it's just a 1s stagger gun that depends so highly on skill that a normal unga would die from just the sight of it.

**Comment by Jalopkomit18** [comment]
> That tube is what inspired this. Orca also propsed a different sprite for this but Kuro hasnt responded to either image

This one definitely looks better

**Review by TiviPlus — APPROVED** [review]
@Kuro020

**Review by TiviPlus — APPROVED** [review]
@Kuro020

**Review by TiviPlus — APPROVED** [review]
@Kuro020

**Review by TiviPlus — APPROVED** [review]
@Kuro020

**Review by TiviPlus — APPROVED** [review]
@Kuro020

**Review by TiviPlus — APPROVED** [review]
@Kuro020

**Comment by TiviPlus** [comment]
Github not doing so good

**Pull request closed without merging**
