### PR TITLE
sends panther to the shadowrealm 

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
deletes panther  and sprites and all the snowflake proqs, as after captures are gone its essentially a shitty runner with a longer stun with double the cooldown

## Why It's Good For The Game
panthers concept is literally to be a runner that does tackle damage, nobody wants that and you could probably forward anything you add to runner anyway.
the sprites are also literally a runner reskin which makes them look bruh.

## Changelog
:cl:
del: Removed panther from the game, same with the sprites
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -68. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
>You currently have a negative Fix/Feature pull request delta of -68. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

shut up bot

**Comment by Hughgent** [comment]
Bad.

Remove the panther from the runner evolve to's do not delete it entirely. 

Just because you don't find it useful now, does not mean someone will repurpose it in the future.

**Comment by Pariah919** [comment]
@Hughgent git exists for a reason, if anyone wants to use the caste they can go use git to restore it and the sprites.

**Comment by spookydonut** [comment]
> 
> 
> Bad.
> 
> Remove the panther from the runner evolve to's do not delete it entirely.
> 
> Just because you don't find it useful now, does not mean someone will repurpose it in the future.

wrong, delete it completely.

**Review by spookydonut — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Review by Hughgent — APPROVED** [review]

**Pull request merged**
