### PR TITLE
Turrets don't detect people in stealth

### PR DESCRIPTION
**Pull request by QualityVan**
Different implementation of #7494 

## About The Pull Request
Hunter stealth grants a trait that makes turrets not target you as long as it's present.

## Why It's Good For The Game
Getting shot by AI when you're invisible is lame. 

## Changelog
:cl:
balance: Turrets won't target you when you're stealthed via hunter ability.
/:cl:

### CODE REVIEW

**Comment by Ieteihowmee** [comment]
Sounds pretty good.

**Comment by vilereaver41** [comment]
Honestly i was under the impression smoke nades always hid marines from them rip to marinea of the past. Good pr for both sides

**Comment by InterroLouis** [comment]
What about the scout cloak?

**Comment by KornFlaks** [comment]
This will singlehandedly make current acid spray turrets obsolete... I like it.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
1) remove it from camo smoke
2) add the same functionality to marine turrets

**Comment by BraveMole** [comment]
> 2. add the same functionality to marine turrets

But it is on marine turrets?  And smoke prevents xeno turrets from firing, camo smoke not doing the same is a bit weird IMO

**Comment by InterroLouis** [comment]
Well on the one hand, camo smoke isn't opaque and thus doesn't block line of sight, but on the other hand it renders marines invisible inside it. Balance wise, though, it turns cloak grenades into the ultimate anti xeno turret item, because you can just smoke cloak it and then everyone can shoot it perfectly safely with no repercussions. I would rather it be added to the scout cloak instead of smoke cloak, personally.

**Comment by Ragecrabbo** [comment]
> 
> 
> > 1. add the same functionality to marine turrets
> 
> But it is on marine turrets? And smoke prevents xeno turrets from firing, camo smoke not doing the same is a bit weird IMO

last time i checked xeno turrets also werent repairable, didnt kill marines in 6 hits and didnt have barricades to protect them from smoke globes

**Comment by InterroLouis** [comment]
> last time i checked xeno turrets also werent repairable, didnt kill marines in 6 hits and didnt have barricades to protect them from smoke globes

And last I checked marine turrets don't heal over time automatically like xeno turrets do, and aren't nearly as cheap and spammable.

**Comment by lbnesquik** [comment]
Please make it so hunters can't kill turrets in stealth

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
