### PR TITLE
Add crawling and ability to still use your hands when lying down

### PR DESCRIPTION
**Pull request by XElectricX**
## About The Pull Request

Any mob/living that has can_crawl = TRUE will be able to move on the ground. Currently, this is only for any /human mobs. I don't know what the situation for benos and crawling should be.

In addition to crawling, you also can use your hands. This includes shooting guns, grabbing items, etc. The only limitation is complex stuff like trying to use a vending machine and you cannot wield, so you can't shoot something like a rifle when lying down.

Mobs can also now be bump attacked if they are lying down since it's no longer a "stun" state.

## Why It's Good For The Game

Being down on the ground doesn't turn you into an immobile potato sack anymore.

## Changelog
:cl:
balance: Humans can crawl and use their hands when lying down.
balance: Mobs can be bump attacked when lying down.
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
A very interesting addition. I'd suggest TMing this first to gather feedback, particularly on the end of balance.

**Comment by MLGTASTICa** [comment]
What about xeno slashing people on the ground ? especially ravager or other castes with huge sprites that can't easily click adjaecent tiles. Are you gonna implement bumpslash for those?

**Comment by novaepee** [comment]
Using hand on ground? We will have to bring back bump slash hitting people on the ground if this PR gets merged.

https://github.com/tgstation/TerraGov-Marine-Corps/pull/3970

https://github.com/tgstation/TerraGov-Marine-Corps/pull/4767

**Comment by XElectricX** [comment]
I tested it before PRing and yes, ungas cannot be bumpslashed if on the ground. I can make it be if needed.

**Comment by Naaanii** [comment]
Sounds neat, would be nice for certain sniper buffs/changes with this mechanic ngl.

**Comment by Losenis** [comment]
Hyped purely for how this'd make shufflehells like cramped tadpole, corridors, and the like way better to live with.

**Comment by KrabSpider** [comment]
Atleast shoulder holsters and pistol laces will be much more useful to have on you. 

Also...is it possible to remove items from your bag whilst prone/stunned?

**Comment by XElectricX** [comment]
> Also...is it possible to remove items from your bag whilst prone/stunned? 

Yes, would be silly not to. You can do anything that is not a complex interaction.

**Comment by XElectricX** [comment]
Did a lot of testing with different conditions and multiple mobs. No runtimes so far and stuff works fine. TM is fine but not ready to merge yet as there is a funny bug where if you have a pile of mobs, only one is ever targeted for purposes of bump attacks so you become invulnerable to it if you have a corpse on top of you. Need to rectify that.

**Comment by Pariah919** [comment]
Needs a TM for a balance opinion that's correct, otherwise a preliminary states that this could help flesh out future xeno abilities and replace several that currently hardstun with crawling.

I don't like gun use when lying down, might be rocking the boat too much.

**Comment by XElectricX** [comment]
> I don't like gun use when lying down, might be rocking the boat too much.

Only guns that can be one shot with one hand can be used as you cannot wield when lying down. If it becomes a problem during test rounds, I'll make it a config toggle so you guys can disable it. 🤠

**Comment by Losenis** [comment]
Could also make it so that in the future a gun may be usable only if you're lying prone with it wielded too, actually.

**Comment by private-tristan** [comment]
can't wait for 10 marines all 1handing a p90 on a single tile killing a queen in 1/5th of a second

this will be very fun

**Comment by Losenis** [comment]
Me and the 30 proneboys on our way to the silo (We're about to get wiped by a WP)

cs-go-squat-walking

**Comment by BraveMole** [comment]
Code is a meme

**Pull request closed without merging**
