### PR TITLE
Specs are gone, reduced to ashes. Everyone can now use spec weapons effectively.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Specs are now disabled from being picked.

## Why It's Good For The Game
I'm curious to see how this pans out, removing specs and making their gear expensive power tools.
Specialists are bad for game design in a game that's centered around team based play, mostly because the entire team is dependant on 4 dudes, who if they die cripple the entire team. Balancing them is a chore as well.
If this makes marines lose literally every round I'm up for buffing PFCs rather than re-adding them personally.

## Changelog
:cl:
balance: Specs are gone. Anyone can use spec gear weapons now.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -11. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by TiviPlus** [comment]
Nice PR description

**Comment by Kuro-ai** [comment]
And now we see how it goes

**Comment by RenGusta** [comment]
based and PFC pilled, maybe xenos will turn the tide a little.

**Comment by psykzz** [comment]
> You currently have a negative Fix/Feature pull request delta of -11. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

denied

**Comment by KwinOriginal** [comment]
Will they be renamed for the different function that was discussed? 2nd in command and such? If not, I'm highly against removing the role because of its rank.

**Comment by psykzz** [comment]
The kits for the specs are being redistributed. The role of spec is becoming redundant.

**Comment by TiviPlus** [comment]
Comrade Headcoder destroys MJP nerd

Also Kwin, from the vibes I got in discord this is more of a "what happens if we try to spread the damage out by removing specs" type of deal

**Comment by KwinOriginal** [comment]
I know and I can see that you want to distribute the power. That's alright. I'm talking about a second in command guy. And I can hardly see that a new role gets added, where the alteration of an existing one seems not that hard.

**Comment by MacBlaze1** [comment]
cockblocked by the headcoder lmao

**Comment by jroinc** [comment]
I'd be interested in seeing how this goes.

My gut feeling is that marines are gonna start losing more (duh), and there's gonna be a LOT more focus on req points and miners, and no more ~500 pt surpluses at roundend.

**Comment by psykzz** [comment]
Honestly sounds like a good change if thats how it goes.

**Comment by MacBlaze1** [comment]
do it

**Comment by Pariah919** [comment]
on further thoughts the spec guns should probably come in boxes that cost 200 points maybe

**Comment by KwinOriginal** [comment]
I'll say it again. You'd remove the possible 2nd in command guy of the squads. Make the Specs duties different, heck, rename him. But don't just outright delete.

**Comment by spookydonut** [comment]
aSL exists, lets give this a test merge for a while

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-14). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Pariah919** [comment]
ggez

**Comment by Kuro-ai** [comment]
Now go fix some bugs to not have -14 social credit score

**Pull request merged**
