### PR TITLE
Laser Machine Gun Buffs

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
Projectile: 15 - > 20 damage 
Wield delay: 1.5 seconds -> 1 second

## Why It's Good For The Game
Gun is stupid unwieldy and damage was too low for its rate of fire.

## Changelog
:cl:
balance: Laser MG wield delay decreased to 1 from 1.5
balance: Laser MG lasers buffed to 20 from 15.
/:cl:

### CODE REVIEW

**Comment by KrabSpider** [comment]
Tell me something I don't know.

**Comment by vilereaver41** [comment]
> Tell me something I don't know.

In 2003 it is believed by conspiracy theorists that the war in Iraq was started over the supposed discovery of Gilgamesh's tomb where U.S soldiers kicked archaeologists out, found his body and retrieved it.

**Comment by novaepee** [comment]
> Tell me something I don't know.

All epee blades should be equal to ensure that duelists have no unfair advantage. Epee blades should be 35 inches long, or #5.

**Comment by SilencedMP5A5** [comment]
the soviet light machinegun 'RPD' is not actually an AK variant, as it was developed in 1943, far before the AK was prototyped

**Comment by Lumipharon** [comment]
It has higher AP than ballistic machine guns, reloading is instant instead of a channel, it has zero scatter and of course hitscan. So it actually scores far more hits than ballistics. And engineers can recharge mags in like 2 seconds, for infinite ammo.

Not necessarily saying it doesn't need a buff (I don't use them enough to say that), but it's definitely not clear cut worse than it's competitors, other than no aimmode.

**Review by BraveMole — CHANGES_REQUESTED** [review]
post the former dps, new dps, and compare it to other guns

**Comment by private-tristan** [comment]
how will this affect the whole 3 Build-a sentry laz machine gun instant melt stratagey that engis occasionally use to kill beans in 3 seconds?

**Pull request closed without merging**
