### PR TITLE
Combat Patrol: The loadouts just keep coming

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Some new loadouts plus tweaks.
As always, let me know if you have any ideas/suggestions.

- Adds an AR-18 scout loadout to TMGC (light armour/shield)
- Adds MPI loadouts to SOM veterans and SL's

- Buffs the SH-15 shocktrooper loadout with Tyr II for slightly better armour and mobility
- The two machinegun loadouts for TGMC now have half of their sandbags filled roundstart
- Increased the quantity and tweaked the types of grenades over a whole bunch of different TGMC loadouts (usually at the expense of a box of ammo)
- Some more C4 on certain marine SL loadouts
- Shield loadout gets a single extended SMG-25 mag
- SOM engie and medic MPI loadouts no longer have a UGL (MPI is actually rather good as it turns out), the medic also gets an extinguisher
- The engies that have razorburn grenades now have the large version (They're kinda funny area denial that you can shoot past)

- Tweaked the offsets of underbarrels on the SH-15, as attachment weapons looked funny
- Cleaned up MPI code since unremovable attachments were fixed

## Why It's Good For The Game
More loadouts, loadout improvements

## Changelog
:cl:
add: Combat Patrol: Added a new AR-18 scout loadout for TGMC marines, and MPI_KM loadouts for SOM veterans and SL's
balance: Combat Patrol: Several  tweaks and changes to various loadouts
/:cl:

### CODE REVIEW

**Comment by MereWalker** [comment]
Can you be sure to add more grenades for the som gls and add sandbags for som gunners if you plan on adding som gunners. This is also my 30th time saying it. Please add a Recoilless rifle load-out for som and other factions when you bake them. Marines having a straight up moving rocket is straight a power house if used correctly. My suggestion is to make the som rocket kit use the same ammo as the marine RR and give them a rifle preferably the ak with no GL. I look forward to to nearly all of your ideas lumi! With love.

**Comment by MereWalker** [comment]
I forgot to say this in any of your prs. Since we have incind and players catching fire I don't see a reason not to include flamer troops. I think it would work well. Just have to find a middle ground for a good flaming loadout! Preferably for all factions.

**Comment by Lumipharon** [comment]
> I forgot to say this in any of your prs. Since we have incind and players catching fire I don't see a reason not to include flamer troops. I think it would work well. Just have to find a middle ground for a good flaming loadout! Preferably for all factions.

See my flamer PR, they will come after that gets merged.

**Comment by MereWalker** [comment]
Alright! I still enjoy the game even with the current setup. I don't think it's lacking in any way. Just figured for the sake of keeping things even on both sides would be a good idea. Such as mirror RR. Perhaps I'm just not using the mini rail gun to the fullest and it's a sleeper. Culverin is powerful as can just wish the power pack would charge somewhat faster. As for the flamer kits. I so look forward to it. I'm a flamer main at heart. I just hope that this makes me spark up once again! Thank you!

**Comment by Lumipharon** [comment]
> Alright! I still enjoy the game even with the current setup. I don't think it's lacking in any way. Just figured for the sake of keeping things even on both sides would be a good idea. Such as mirror RR. Perhaps I'm just not using the mini rail gun to the fullest and it's a sleeper. Culverin is powerful as can just wish the power pack would charge somewhat faster. As for the flamer kits. I so look forward to it. I'm a flamer main at heart. I just hope that this makes me spark up once again! Thank you!

The charge rate is the big balancing factor for the culverin. It's basically a minigun but with deflagrate, if it had too much ammo or charged to quickly, you would be able to spam it with impunity, which would be guh.

**Pull request merged**
