### PR TITLE
Adds chemistry request lines to (most) shipmaps

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
Read title.
Here is what chem looks like now on the shipmaps:
image
image
image
image
## Why It's Good For The Game
Since there are still req lines (on PoS, for example), if we ever need chemical request lines they are there; smartfridge only is sort of sad.
## Changelog
:cl:
add: Added chemistry request lines to most shipmaps.
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
I can not wait for these to not be used, since MDs still do not make chems for people.

**Comment by iforgotmeword** [comment]
Yum yum more metal to the fob gods

**Comment by Strayed-Raven** [comment]
Ah I see. instead of breaking windows we just have to break windoors now.

**Comment by ThelastArchiver** [comment]
the reason usualy mds dont make chems for marines is because they already always break into chemistry on their own

**Review by RipGrayson — APPROVED** [review]

**Comment by Derrick2Electricboogaloo** [comment]
> the reason usualy mds dont make chems for marines is because they already always break into chemistry on their own

Literally not even the sole reason. Most MDs do not want to, or do not know how to.

**Pull request merged**
