### PR TITLE
MG-60 Nerf

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
T-60 damage nerfed from 25 to 21.5.
Mag capacity increased from 200 to 250. 
## Why It's Good For The Game
This gun wasn't really hurting for any buffs and giving it a whole extra 5 damage while it has the rate-of-fire of a whole damn SMG is goofy.  
## Changelog
:cl:
balance: MG-60 damage decreased (25 -> 21.5)
balance: MG-60 ammo capacity increased (200 -> 250)
/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
rogan
THERE IT IS

**Comment by Losenis** [comment]
Salt PR?

**Comment by KrabSpider** [comment]
> Salt PR?

A concerned parent PR, if you will.

**Comment by Pariah919** [comment]
This just makes the gun a noob trap again, like it was pre-buff.

**Comment by FosterGrime-Heymynameslouie** [comment]
with this PR and https://github.com/tgstation/TerraGov-Marine-Corps/pull/12066

the GPMG, now has

- lower ammo count, both compared to before and after it was buffed in https://github.com/tgstation/TerraGov-Marine-Corps/pull/11885
- lower damage overall
- lower AP 
- low ROF

this PR makes it so that its even worse PRE buff, which is kinda strange?

would be okay if you return the ammo count or something.

also this PR was already done 3 weeks before by this https://github.com/tgstation/TerraGov-Marine-Corps/pull/12066

**Comment by Joe13413** [comment]
"Mag capacity increased from 200 to 21.5."
the best nerf of the year

**Comment by Lumipharon** [comment]
The gun was pretty trash before the buff, other than for people that just enjoyed shooting lots of bullets.
Massed T60 can be a bit oppressive but xenos do have tools to deal with it, so I don't think a nerf is warranted at this stage.

**Comment by KrabSpider** [comment]
> The gun was pretty trash before the buff, other than for people that just enjoyed shooting lots of bullets.
> Massed T60 can be a bit oppressive but xenos do have tools to deal with it, so I don't think a nerf is warranted at this stage.

Completely fine by me.

**Comment by Losenis** [comment]
Remember that the stronger a gun is the more marines will die to FF by it. The problem balances itself out pretty damn hilariously.

**Pull request closed without merging**
