### PR TITLE
remove old cm actions for guns

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
removes these things
image
## Why It's Good For The Game
noob bait to use, all of these things are keybindable and can be used by actions on the top left
## Changelog
:cl:
del: Removed old cm gun actions
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
Are those binded by default? And I'm not sure all of the buttons are usable via top left.

**Review by Lumipharon — APPROVED** [review]

**Comment by Joe13413** [comment]
i dont think i've used a single one of these buttons in my life, i dont know what the other people are saying about not being able to use them on the top left, legit just click your gun to remove mag or press space to cock it

**Comment by GreatKingWombat** [comment]
Does this actually hurt anything by being in the game though?

**Comment by novaepee** [comment]
> Does this actually hurt anything by being in the game though?

It's bad leftover from CM, and anything that is a bad leftover from CM ought to get removed even as something as minor as this.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
