### PR TITLE
made deploying items make you automatically interact with them

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

This change adds an interact(user) on the deployable_item object inside finish_deploy. Also I am back.

## Why It's Good For The Game

This is a QOL and a balance change that will help make using emplacements and other weapons deployable much nicer, instead of a need to manually interact with them.

## Changelog

:cl:
qol: made players automatically interact with deployables when they deploy them, it is now an option in game preferences that you can enable and disable at will.
balance: This change applies to all weapons deployables, like emplacements and machine guns

/:cl:

### CODE REVIEW

**Comment by pilotmans** [comment]
nice shouldn't be too OP

**Comment by XElectricX** [comment]
Make it a var. Might be annoying depending on the item.

**Comment by maikilangiolo** [comment]
Awesome PR

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Make it a gamemode pref flag
put it in the pref TGUI UI
remove the verb

**Pull request merged**
