### PR TITLE
SMG-25 added to marine vendors, now fits UGL

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
SMG-25 added to marine vendors, it now fits UGL
## Why It's Good For The Game
~~Gun bloat~~
Gives a interesting gun option, and is already used by marines in HvH, I don't think it shakes up balance too hard, as it isn't the B2 version..
## Changelog
:cl:
add: Added SMG-25 to marine vendors.
balance: SMG-25 now fits UGL.
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
So we are going the half life route?

**Comment by Derrick2Electricboogaloo** [comment]
Also this is already in seasonals and able to be req bought

**Comment by Derrick2Electricboogaloo** [comment]
Make sure to add SMG-25 belt/holster

**Comment by Pariah919** [comment]
> Also this is already in seasonals and able to be req bought

wait what
well guess then this was pointless

**Comment by Derrick2Electricboogaloo** [comment]
> 

Yep. only 5 points... Err.. 50 now probably. But still cheap and easy to get.

**Comment by FIXTHERADBOXPLEASE** [comment]
Could still be added IMO. There's like five different rifles and only two marine SMGs, one of which is actually a machine pistol.

**Comment by FIXTHERADBOXPLEASE** [comment]
More like the MP19 had its niche changed into an actual machine pistol, thus creating a missing slot for SMGs.

**Pull request closed without merging**
