### PR TITLE
shotguns no longer get miniflamer

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
temp fix till hyper get's off his buttocks and makes flamer refactor

## Why It's Good For The Game
this is a dumb combo

## Changelog
:cl:
balance: shotguns don't get miniflamer anymore
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
mini flamers are fine for now, no need for this, cant see nothing wrong with it

**Comment by Nirvan4** [comment]
Good change, too strong to be put into a weapon already strong, if a xeno approaches you to slash you can PB and flame the thing dealing 50 damage ignoring armor, put them on fire with damage over time, area denial and turning the pheros off.

Just the 50 damage is already stupid, its a huge chunk of health to every caste

**Comment by Al-1ce** [comment]
Now that flamethrowers are actually viable attached to guns I can see the issue with this. T-35/flamer is downright bussin

**Comment by EvilMelonTheSecond** [comment]
Shouldn't we just remove the 50 true damage from miniflamer instead?

**Comment by QualityVan** [comment]
Leaving it on the t35?

**Comment by hyper2snyper** [comment]
> Shouldn't we just remove the 50 true damage from miniflamer instead?

shitcode says no.

**Review by BraveMole — APPROVED** [review]
This is a bandaid fix that will be reverted when miniflamer will get refactored by bird (soonTM)

**Pull request merged**
