### PR TITLE
Gives armor to the HSG102 and MG08

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request
Both guns get TAT level of armor, the other limited fixed gun, *without* an increase in integrity.
Got the go ahead from Tivi, but she simply said "idk" on exactly what armor to give so no doubt this PR needs discussion.

## Why It's Good For The Game
These two fixed guns are essentially forced into an aggressive, frontline role considering the very short scope, and the MG08 even more due to total lack of IFF. they had 0 armor except bullet, so I gave them the armor TAT has (plus 40 acid since the TAT has 0) but did not touch the 200 integrity (vs TAT 500). So they wont be nuked as easily even through cades with scatter spit, particualrly the 08.
I know the armor might seem like removing all the counter play, but I personally did not see complaints specifically about the TAT tankiness, and considering the machineguns will be placed at the front without the long zoom, you can still shuffle, displace, hugger, gas (boiler and defiler) and crush them as counters.

## Changelog
:cl:
balance: HSG2102 nd MG08 now have bomb armor, and 20 acid armor.
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
The positioning is a core feature of a gun that has a large damage output.

**Comment by Lumipharon** [comment]
200 dps with 40 AP and 5 sunder(!) is incredibly strong. Being punished for bad positioning is a good thing.

**Comment by Pariah919** [comment]
Eh, for turrets sure. No for crew weapons

**Comment by novaepee** [comment]
Just wait for deployable shield to protect HSG and MG. Armor on guns not needed then.

**Comment by Mannybrado** [comment]
powercreep

**Comment by TiviPlus** [comment]
Halve the acid and remove melee buff

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
