### PR TITLE
Increases sentry supply pack price.

### PR DESCRIPTION
**Pull request by DominikPanic**
:cl: LaKiller8
balance: Sentry price has been increased.
/:cl:

### CODE REVIEW

**Comment by Alterist** [comment]
175? jesus christ what

**Comment by DominikPanic** [comment]
> 
> 
> 175? jesus christ what, i feel like 150 is a better starting number for now

Sure

**Comment by AdamElTablawy** [comment]
why are sentries more expensive than additional spec weapons

**Comment by DominikPanic** [comment]
> 
> 
> why are sentries more expensive than additional spec weapons

That just means we should increase/remove the spec weapons too.

**Pull request closed without merging**
