### PR TITLE
Removes MPs

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
MPs are bad

## Why It's Good For The Game
Only griefers play MPs and its OOC rule breaking to work against the marines.

## Changelog
:cl:
del: MPs removed
/:cl:

### CODE REVIEW

**Comment by henriquekill9576** [comment]
bruh muh MP bullying and EORD powergaming

**Comment by terranaut1** [comment]
Griefers get banned and often it's nice to let MPs deal with vaguely shitty but not rule-breaking enough to ban marines ICly

**Comment by spookydonut** [comment]
> 
> 
> bruh muh MP bullying and EORD tazer

Tazers still exist

> 
> 
> Griefers get banned and often it's nice to let MPs deal with vaguely shitty but not rule-breaking enough to ban marines ICly

If people wanna RP as MPs the equipment is still there

**Comment by spookydonut** [comment]
Okay so at somepoint someone commited theseus to the repo as CRLF

**Comment by XElectricX** [comment]
Good MPs are very important. They keep marines from destroying shit and from raising shutters early.

**Comment by KwinOriginal** [comment]
If MPs work against marines breaking the rules, they shall get bwoinked.

I don't think they should be removed. If the gear is to be dirstributed, it would lower marine strength (where do you take MPs from?). 
Also, if someone chooses MP role, you can somehow expect he knows what he's getting himself into. If PFC Jim gets MP because Commander Honk said so...it's a bit more difficult, I'd say

**Comment by Toxici11i** [comment]
+1 the same excuse was used for CM and look where that went.

On another note, yeah MP's contribute nothing to gameplay  other than 'MUHH ICCCC'.
Synths are essentially mini-mp's anyway, and anything worth arresting somebody for is bwoinkable due to m'uh mrp.

**Comment by davidchan13** [comment]
Unironically this, There is other shipside personnel that could access the equipment and if the MP wants to play minicommand then just play command and not be some over bearing prick looking for excuses to HvH marines.

**Comment by KwinOriginal** [comment]
If you abuse the role, you get a bwoink.

**Comment by Toxici11i** [comment]
> If you abuse the role, you get a bwoink.

And? That doesnt matter if the role itself is useless and contributes nothing to gameplay.

**Comment by spookydonut** [comment]
MPs pose a balance issue, they're either OOC restricted to never deploy and you balance around them not existing, or you allow them to deploy and balance around them always deploying which then hamstrings the marines when they don't deploy.

**Comment by psykzz** [comment]
I generally agree with this, but want @MerryweatherLost to chime in

**Comment by jroinc** [comment]
I disagree with this, cause it means that if there's no possibility of IC enforcement of rules, all rule enforcement falls on admins. I mean, I'll gladly ban people who break into req when it's manned, but eeh.

I also don't really see MP "abuse". More often, I see MP's at the FoB, moving supplies and shooting at ayys.

**Comment by MerryweatherLost** [comment]
Going to leave this out a bit more before I reach a decision on this tomorrow. MP's I never had an issue with, they are a balance issue?

**Comment by spookydonut** [comment]
> 
> 
> Going to leave this out a bit more before I reach a decision on this tomorrow. MP's I never had an issue with, they are a balance issue?

yep same as survivors

**Comment by Toxici11i** [comment]
survivors pose a greater threat to xenos than MP's but both should be nuked

**Comment by davidchan13** [comment]
We still have a chain of command from the CO down to the SLs and Specs to enforce IC rules. And the Chain of command works a hell of a lot better when the officer is dealing with the infraction personally than just handing it off to MP thugs to deal with it instead.

**Comment by spookydonut** [comment]
If you test merged this silently with no other rule changes or admin policy changes I really doubt anyone would even notice.

**Comment by Hekzder** [comment]
Was originally in favor of this PR until I started to play Command roles and realized how nice MPs are to have around for dealing with incompetence, disobeying orders, and shitters who ruin the op and get Marines killed. 

Yes, other people _can_ become impromptu MPs since the gear is still there, but that's just taking away from their role doing something else and wasting their time to do so. If we're looking to cut down on useless Marine roles, I'd much rather see a CL removal for a variety of reasons.

**Comment by Rohesie** [comment]
Last round with 48 players had two survivors, a Captain, a a CE, a CMA and other shipside roles.
The marines mounted a VIP-extraction operation on the survivors who went up and RPed along with the rest of command, the whole machine was pretty well-oiled and it was a pleasure to see, while the ungas down there hunted the xenos.
It ended in a marine major and it reminded me just how nice the game can be.

That is the game I contribute to, and the one that interests me.

**Comment by KwinOriginal** [comment]
Since the last touch was over two weeks ago and just removing game features that people use to have fun is a bad move, I guess it's time to close this pr.

**Comment by spookydonut** [comment]
@KwinOriginal that's up to @psykzz, you dont get to just close prs you disagree with

**Comment by psykzz** [comment]
I did want merry to comment before I decided., I'll push this with aiia and see if they want to comment.

Also spooky is right we don't close prs unless the author agrees or it is definitely a waste of time. ( Trolling, has been discussed before, etc)

**Comment by KwinOriginal** [comment]
Ah, so if Psy closes PRs it's alright but if I do it's not? Shame I'm not your buddy, eh?

How long does a PR need to be idle to be considered a waste of time/abandoned/something like that if the project lead does not have a word? I hope we have some kind of guideline there, because discussions seem fruitless.

**Comment by psykzz** [comment]
Yes it is fine if i close, since thats a perk i get as headcoder, nothing to do with being a buddy.
Merry has _just_ left and i haven't had time to speak to AIIA yet.

That said, there are many other PRs out there that are open without resolution that should be closed before we get to closing this one.

**Comment by Max-023** [comment]
Meh. I still see a reason for MPs as they allow the other heads of staff to actually enforce shit. Nothing is worse than an RO trying to plan shit out just for a pyro to come in and order a shit ton of fuel, leaving every other spec out. Or a PO trying to keep the Marines from launching the Alamo early, just for someone else to come in and launch while you are still prepping. Removing them means Marines are forced to self police, which they have been shown in the passed at being incapable of such a task.

**Comment by KwinOriginal** [comment]
@psykzz Well, that's at least an explanation, I for sure hope so.

Still, there is my question: When is a PR open for too long or considered not fit to be continued? Will there be a real discussion or is it just a final decision from you at some point?

Also, I agree with the point brought up so far. Removing MPs won't solve anything and will just create new problems for the marines, if any.

**Comment by psykzz** [comment]
A lot was discussed around MPs
https://discordapp.com/channels/498569646014857217/500801682058379265/713368463795552447

To sum it up
> We agreed to remove the MP role and will leave the marine discipline to staff, otherwise it falls to the admins.
> Potentially talked about having it reworked into a guard role that is focused on guarding objectives vs the ship

**Comment by psykzz** [comment]
@spookydonut we're good to merge this as soon as conflicts are resolved

**Comment by spookydonut** [comment]
@psykzz done.

**Pull request merged**
