### PR TITLE
Deletes PAS, adds Xenonauten

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Sprites by kuro, other than balls(istic)which is made by me
Deletes PAS since it's old and stinky (helmets to be done later depending on kuro response)
Moved all Xenonauten related armor (AKA non-jaeger) to it's own file.
Deleted old helmets, PAS, etc.

--
Adds xenonauten, which has it's own unique sprite sheet for modules and stuff. 
Has FLAK/LIGHT/MEDIUM/HEAVY variants.
Is map variants right now, as per kuro request, so all code related to old coloring is gone.
Stats are EQUIVALENT to a Jaeger with 2 arms and chestpiece, so light is light jaeger with 2 arms flat, etc etc. Stats to be posted in a bit.
--

Module crates replace the old module big back thingies, as the back thingies are wacky and weird.
image
image
image

## Why It's Good For The Game
Better sprites, new days. Better identification, and better stuff to go along with it (also david paid 60$)
Moved all non jaeger pieces to their own file in normal_armor.dm, name can be changed. Since there was way too much garbage in one file.

## Changelog
:cl:
add: Xenonauten armor by kuro, has it's own module sprites and everything unique! Go to PR to see.
Adds Flak, Light, Medium, Heavy armor variants of Xenonauten, Their armor levels are equivalent to a jaeger chestpiece+2 arms of their equivalent armor level, Flak is just a exo with nothing on it statwise.
del: PAS is gone, forever to be sent to the shadowrealm. 
/:cl:

### CODE REVIEW

**Comment by Alexeivichi** [comment]
Basically PAS 2. Nice.

**Comment by DarkWolfKai** [comment]
LETS FUCKING GOOOOOOOOOOO

**Comment by ilikesaying** [comment]
ayy lmao

**Comment by BraveMole** [comment]
Can't wait for kuro to approve this

**Review by David-Stormwell — APPROVED** [review]
Gaming 👍
Been waiting for this for ages.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Yeah no, you're not changing the type path cause that's killing loadouts

**Comment by davidchan13** [comment]
> Basically PAS 2. Nice.
> 
> Edit: PAS 2 but more modular.

Not PAS 2, Jaeger 2.

**Review by Kuro020 — APPROVED** [review]
we do a little trolling

**Comment by Kuro020** [comment]
after discussing this with the person that paid for the sprites in the first place (cof cof david cof cof) coloring xenonauten will stay,so do the change mjp :whip:

**Comment by Pariah919** [comment]
i'm gonna redo this pr

**Pull request closed without merging**
