### PR TITLE
GL 70 nerf

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Increases the fire delay of the GL 70 to 2
## Why It's Good For The Game
Nade spamming shouldn't be as easy as it is, this should tone it down a bit and AGLS will retain it's top spot for nade spam.
## Changelog
:cl:
balance: Increases GL 70 fire delay to 2
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
Nades are limited. Wait them out you salty goober.
-1

**Comment by Tupinambis** [comment]
Incredibly severe nerf tbh. If they have to be nerfed it shouldn't go all the way from 50 RPM to 30 RPM

**Comment by GreatKingWombat** [comment]
> Nades are limited. Wait them out you salty goober. -1

"Limited"

**Comment by Naaanii** [comment]
> Incredibly severe nerf tbh. If they have to be nerfed it shouldn't go all the way from 50 RPM to 30 RPM

This also gives single handed launchers a niche along with the AGLS which both have a lower rate of fire but one requires skill to use and the other points.

**Comment by Tailiik** [comment]
> Nades are limited. Wait them out you salty goober. -1

The only way marines are using up the 800+ nades they get is if they have a whole squad of nade spammers in a 3 hour hellround or if 1 griefer detonates them all with fire

**Comment by srxtreme** [comment]
In my opinion a nerf to GL70 is long overdue, but the delay between shots should be around 1.6 or 1.7 instead of 2.0

**Comment by Lumipharon** [comment]
This seems like a pretty severe nerf.

**Comment by Naaanii** [comment]
> This seems like a pretty severe nerf.

Severe but just. It puts it on par with the 35 and again, the one handed launchers can still be used and have more reason to do so with the right amount of skill.

**Review by Lumipharon — CHANGES_REQUESTED** [review]
nerf it to like 1.6 if you want, but 2 is a lot.

**Comment by Naaanii** [comment]
I'll let someone else nerf nade spam.

**Pull request closed without merging**
