### PR TITLE
HPR for PFCs

### PR DESCRIPTION
**Pull request by InterroLouis**
## About The Pull Request

This puts the HPR in the gun vendors. Wider testing of the weapon should give a better indication of what changes are necessary, if any, to allow the wide release of the Big Dakka. Testmerge this alongside #3218 for better data. 

## Why It's Good For The Game

It gives marines another option. Options are good. Options are fun. Yay, options. 

## Changelog
:cl:
balance: Marines get HPRs. 
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
probably shouldn't tm this without edge removal aswell

**Comment by Kuro-ai** [comment]
TM it,needs testing to become a full fledged PFC weapon

**Comment by spookydonut** [comment]
blocked by #3120

**Comment by Metroidlover** [comment]
Please list all your changes in your PR's description please

**Comment by Rohesie** [comment]
This one will most likely have to come as the new LMG instead.

**Pull request closed without merging**
