### PR TITLE
Refuel flamerbag from welding kits

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
You can now refill the backpack directly from welding kits, instead of just large fuel tanks.
## Why It's Good For The Game
Being able to refuel the backpack the same way you'd refuel a flamethrower tank is nice.
## Changelog
:cl:
qol: Flamethrower backtank can be refilled from welding kits
/:cl:

### CODE REVIEW

**Comment by Yttriums** [comment]
qol changes are nice but prescriped magharn is goofy. this is an incredibly space-efficient item already and not being able to magharn is a fair tradeoff for that. certainly not a 'grief option' when it costs 0 engi points.

**Comment by FosterGrime-Heymynameslouie** [comment]
this is pretty good
kinda wondered why it didnt have built in mag harn to begin with and the fact you cant refuel it with m22 welder kits when the normal one can, felt like it was built off the welding satchel and was just given a space for the flamer (side note, can we also have the welder satchel refuel with m22 welder kits? might pair nicely with this pr) 
pretty cool pr

**Comment by lbnesquik** [comment]
I think part of those decisions were intentional at the time.

**Comment by Lumipharon** [comment]
having no magharness into the bag was intentional. its a trade off for getting gun storage on top of normal storage (and fuel)

**Comment by Tailiik** [comment]
Seems op to be honest, it's already very easy to just press E to instantly stuff the flamer into your backpack when you see a xeno approaching. It's good for xenos to have a chance to steal flamers away if marines have an option to put them inside a backpack and not lose out on back/suit storage space to carry one.

**Review by Lumipharon — APPROVED** [review]
this is extremely snowflake, but its a larger issue so eh.

**Pull request merged**
