### PR TITLE
Reskin SG-29

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

https://user-images.githubusercontent.com/6610922/235382700-b8b589b2-1c4b-406f-8c7f-5ebd5d74e495.mp4

image

how-to

Copy paste from Tye's CM April Fool PR, https://github.com/tgstation/TerraGov-Marine-Corps/pull/12569

Sprite made by Crow.

Make SG-29 more beautiful and soulful.

Small gun_system update as well to make this gun work well.

## Why It's Good For The Game

Current SG-29 sprite is a long tube. This SG-29 from Crow is slick and awesome, more Aliens inspired than whatever CM has.

## Changelog

:cl: novaepee, Tye, Crow
imageadd: new SG-29 skin
code: added firing_volume and muzzle_flash_offset from Tye's CM PR
/:cl:

### CODE REVIEW

**Comment by dinkNH** [comment]
the one hand sprite looks a little scuffed, maybe having it be at a 90 degree angle and vertical instead of slightly aiming down would get the juices flowing. Sound is perfect, definite improvement.

**Comment by Arctrooper8** [comment]
It's more evocative of the original smartgun from Aliens for sure. But it almost looks a bit comically long? I get that you were trying to match the long style of the Aliens gun but I'm not sure if that works that well for the on mob sprite.

**Comment by Lumipharon** [comment]
The north facing sprite is scuffed. Both arms are behind the gun.

**Comment by Al-1ce** [comment]
The inhands sprite kind of looks like a massive dildo but otherwise I like this.

**Comment by Pariah919** [comment]
Eh, does a scuffed MG-42 really fit more than the T-29? I think this makes more sense replacing the smart minigun than it does the SMMG.

**Comment by Arctrooper8** [comment]
> Eh, does a scuffed MG-42 really fit more than the T-29? I think this makes more sense replacing the smart minigun than it does the SMMG.

I agree with MJP, this feels really heavy duty and cumbersome and thematically could fit the SG Minigun more than the honestly quite agile SG-29. The SG Minigun even has a backpack just like in CM and the movies.

**Comment by zzurge** [comment]
Part of me doesn't mind returning to roots but the other part of me feels like our design has grown on me over time

**Pull request closed without merging**
