### PR TITLE
Fixed Movement Bug With Evasion

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

Evasion now fails as it should if the runner is targeted by flamethrower projectiles, or hasn't moved in the past 0.5 seconds.

## Why It's Good For The Game

Evasion now fails as it should if the runner is targeted by flamethrower projectiles, or hasn't moved in the past 0.5 seconds.

## Changelog
:cl:
fix: Evasion now fails as it should if the runner is targeted by flamethrower projectiles, or hasn't moved in the past 0.5 seconds.
/:cl:

### CODE REVIEW

**Review by SplinterGP — APPROVED** [review]

**Comment by Wayland-Smithy** [comment]
> Evasion now fails as it should if the runner is targeted by flamethrower projectiles
flamethrower projectiles
`p r o j e c t i l e s`

As you point out the flames act as a slow projectile when travelling, so why should they not be dodged unlike a speedy boolet?

**Comment by Surrealaser** [comment]
> > Evasion now fails as it should if the runner is targeted by flamethrower projectiles
> > flamethrower projectiles
> > `p r o j e c t i l e s`
> 
> As you point out the flames act as a slow projectile when travelling, so why should they not be dodged unlike a speedy boolet?

Because it's an abstraction of a large undodgeable wall of fire.

**Comment by Wayland-Smithy** [comment]
IMO they should he able to juke the "wall of fire" which is actually a slow moving stream, and upon being ignited like from crossing a tile with fire their evasion should end.

**Comment by SplinterGP** [comment]
> 
> 
> IMO they should he able to juke the "wall of fire" which is actually a slow moving stream, and upon being ignited like from crossing a tile with fire their evasion should end.

the bullet from the flamethrower signifies a direct hit, so i feel it should hurt

**Pull request merged**
