### PR TITLE
MG-27 no longer accepts suppressors

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title.

## Why It's Good For The Game
I'm not trying to balance this I just want to be able to hear what's sundering the ever living shit out of me so I can react to it.

## Changelog
:cl: Lewdcifer
balance: MG-27 no longer accepts suppressors.
/:cl:

### CODE REVIEW

**Review by Lumipharon — APPROVED** [review]

**Comment by Derrick2Electricboogaloo** [comment]
Lots of me-me in this PR.

**Comment by Strayed-Raven** [comment]
How can you honestly not notice the big sprite in arms next to you?

**Comment by Al-1ce** [comment]
The sprite itself is pretty large. The large magazine size means you can *generally* deduce what’s shooting at you - it’s either a '60, ’42, or '27.

At the end of the day it doesn’t really matter *which type of MG is turning you to swiss cheese*, because they all achieve the same goal. 

If you really cared enough why not give the '27 a more unique sound while shooting suppressed? That’s a lot better than taking away the suppressor.

**Comment by iforgotmeword** [comment]
suppressors, 
isn't this the point of suppressors?
to mask what gun is shooting you?
it's like removing Hunter Stealth because it makes it hard to see what you are shooting at...

**Comment by Pariah919** [comment]
Funy

**Comment by Yttriums** [comment]
xenos have the tools (venting/vision sharing/hivemind comms) to identify this threat even if it's offscreen

**Comment by lbnesquik** [comment]
No, this gun is already too loud

**Comment by ju45he** [comment]
This is like giving marines a separate compass to tell them which way is north. (I mean, marines probably need one but not beno players who are smarder not harter)

**Comment by Otterwatch** [comment]
It is a quite loud gun as it is, but it is still fairly quiet compared to the other guns in the round. I have to play with my sound down nearly all the way just so I can hear guns at a semi normal level. I've found that if there's another gun firing alongside a suppressed mg27; I can usually only hear the former meaning I have to spot the scoped emplacement before it shreds me. Honestly, with how terrible our audio balancing is in tgmc, guns probably shouldn't be able to be made quieter in the first place. 

This pr is still a nerf for a weapon that doesn't exactly need it. Suppressors provide benefits other than being quieter to your ears and I don't think that those few situations when you do get hit by it unexpected outweigh the usefulness of the attachment compared to other options.

**Comment by Windryn** [comment]
_I'm not trying to balance_

**
Labels: Balance)**

**Comment by Tommy-211** [comment]
Really defines "Cope merge"

**Comment by Nuker555** [comment]
>none of the issues adressed
>stealthmerged

**Comment by docRoboRobert** [comment]
Lol, another great copium pr getting merged with no regards.

**Comment by Tommy-211** [comment]
no way is this still merged with 21 downvotes

**Comment by chizzy376** [comment]
Can't even be bothered to make the sound less silenced, just outright remove it because you hate players having variety.
Great work on the stealthmerge, really puts "open" in the open source.

**Comment by Al-1ce** [comment]
Tempted to revert.

**Pull request merged**
