### PR TITLE
reduces rockets travel speed

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
reduces rocket travel speed in around 25%, so its easier to react them somewhat

## Why It's Good For The Game
Rockets are very fast IMO to what results some of them are way too fast and unreactable, this slows them down, if the RR doenst deserve this i'll increase it back, but SADAR and all overall rockets seems very fast, 

## Changelog
:cl:
balance: rockets travel speed reduced by around 25%
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
sadar finally nerfed fellow t1s/t2s

**Comment by TiviPlus** [comment]
Are you not going to compensate it in any way?

**Comment by Tupinambis** [comment]
They are expensive spec weapons, I don't think this is necessary, especially for the RR.

**Comment by SplinterGP** [comment]
> 
> 
> Are you not going to compensate it in any way?

compensate in what, its a nerf, i think they travel way too fast, thats it

**Comment by usnpeepoo** [comment]
sadar hits fast as fuck and satanizes any t1/t2 glad its being nerfed

**Comment by Pariah919** [comment]
bad pr unless he buffs rockets in some way
SADAR has a high travel time to offset the fact that its a one shot weapon per magazine, those rockets are 4 points each and in general hitting a direct hit on the faster castes is already difficult enough, the SADAR is a weapon of oppurtunity and the high projectile speed helps that a lot.

If you're going to nerf the projectile speed with no compensation then I have no words for you, it is a 100 point item with high upkeep unless the player behind it is astronomically good enough to keep pumping out kills with it, I can outfit a small group of marines with valkyries instead to probably get better team wide support in a push, or give them TX8s so they can keep sundering going.

**Comment by Pariah919** [comment]
>compensate in what, its a nerf, i think they travel way too fast, thats it, i barely even see the rockets ingame, specially the AP ones
>
Rocket based weaponry does not need a straight nerf in any form, and reducing projectile speed by 25% is a big nerf in practice due to how these weapons function. If you're going to nerf it then buff it in some way.

**Pull request closed without merging**
