### PR TITLE
New Title Art: Grief of a loved one

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

It's times for the feels.

image

image

## Why It's Good For The Game

Even if this person is known in TGMC, it has a tone I like that isn't explored in TGMC: loss.

## Changelog

:cl: novaepee, lich, zaha, relevation
add: New Title Art: Grief of a loved one
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
Loss

**Comment by Serxule** [comment]
can we see it?

**Comment by zee11zee** [comment]
Emotional Damage

**Comment by Al-1ce** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Review by TiviPlus — APPROVED** [review]

**Comment by Oscari-pog** [comment]
Do not

**Comment by SilencedMP5A5** [comment]
huge

**Pull request merged**
