### PR TITLE
Adds LOOC

### PR DESCRIPTION
**Pull request by DominikPanic**
:cl: LaKiller8
add: LOOC has been re-added.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
> 
> 
> 🆑 LaKiller8
> add: LOOC has been readded.
> /🆑

FIFY. 
Anyway I'd suggest you change the stat check to `stat != CONSCIOUS` and word the feedback message to be "alive and conscious" or something, to reduce potential salting.

**Comment by Borisvanmemes** [comment]
Didn't the headcoder say no to LOOC, or have they changed their mind?

**Comment by DominikPanic** [comment]
> 
> 
> Didn't the headcoder say no to LOOC, or have they changed their mind?

Rohesie said that they want it added, and with their recent rank change from Manager to Project Lead they have more authority here.

**Comment by DominikPanic** [comment]
> 
> 
> > cl LaKiller8
> > add: LOOC has been readded.
> > /cl
> 
> FIFY.
> Anyway I'd suggest you change the stat check to `stat != CONSCIOUS` and word the feedback message to be "alive and conscious" or something, to reduce potential salting.

A frequent use of LOOC is talking with the doctor who's doing surgery on you though, it's a legitimate way to pass time.

**Comment by Ghommie** [comment]
> 
> 
> > > cl LaKiller8
> > > add: LOOC has been readded.
> > > /cl
> > 
> > 
> > FIFY.
> > Anyway I'd suggest you change the stat check to `stat != CONSCIOUS` and word the feedback message to be "alive and conscious" or something, to reduce potential salting.
> 
> A frequent use of LOOC is talking with the doctor who's doing surgery on you though, it's a legitimate way to pass time.

I can't disagree because I have also done that. Up to you then.

**Comment by spookydonut** [comment]
make the default looc_allowed value get loaded via config

**Pull request merged**
