### PR TITLE
Fixes inflatables not being opaque

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Forgot this line. Sad.
## Why It's Good For The Game

They aren't supposed to be seethrough.
## Changelog
:cl:
fix: Fixes inflatables not being opaque
/:cl:

### CODE REVIEW

**Review by Lumipharon — APPROVED** [review]

**Comment by XElectricX** [comment]
Inflatables are meant to be opaque? I thought they were emulating Bay inflatables, which are also see through.

**Comment by ivanmixo** [comment]
Hmmm unsure. All I know it messes with doors so they are opaque when open and not opaque when closed. Easily fixed though. 

I'm 60% sure they're meant to be opaque though. The sprite doesn't exactly look seethrough.

**Comment by XElectricX** [comment]
> I'm 60% sure they're meant to be opaque though. The sprite doesn't exactly look seethrough.

Yeah I always thought it was just the sprite being wrong. I don't remember the doors being opaque though. I always chalked it to the inflatables being like chest-high so you could see over them. All I see them used is for medical so it's pretty much just nerfing it into uselessness since you won't be able to see out of your FOB clinic, which is a bit sad.

**Comment by Lumipharon** [comment]
Checking old code, these weren't opaque in the past.

**Pull request closed without merging**
