### PR TITLE
Fix mech lights

### PR DESCRIPTION
**Pull request by TiviPlus**

### CODE REVIEW

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 61cd35e853782933f17fcb554a886c92e89910bf
Pull Request: 01c76df73ab36fa6f60d2f9026d16f38da3a5864
Server: 9766cfa7e7d99647d4c82b590054102718700d07

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Review by Cyberboss — APPROVED** [review]
Hope you don't mind, testing TGS stuff

**Comment by Cyberboss** [comment]
Rip, no owner anymore

**Comment by Cyberboss** [comment]
I made them do it

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Pull request merged**
