### PR TITLE
removes unused icons in the "unused" folder

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request

title. gets rid of the whole thing. 
files re/moved were:
xmas.dmi (none of these are used and the special MREs are duplicated in the food dmi where they're actually called from)
Marine_Research.dmi (resin jelly's sprite and the sprite for xeno scalps were from here)

- renames "biomass" sprite to "resin jelly"
- re-homes those two in a new dmi for "xeno materials"
- edits the name pathing of any other dmis in the "Xeno" folder that didn't have spacing in the name for /readability/
- renames the acid well file to "acid_well.dmi" since it was "acidpool.dmi" before which can cause confusion with the actual acid pool structure

## Why It's Good For The Game

spring cleaning, baby steps. none of these were used, but moreover i don't think they have the potential to *be* used; they're very old CM-era sprites and not our style.

## Changelog
:cl:
imagedel: deleted the "unused" folder of dmis
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
some of these are definitely used in the chrismas PR's, but I guess they can just be in that pr

**Comment by coldironwarrior** [comment]
i mean, "yes" to your point about putting relevant sprites on the christmas PRs;

but no, actually, not a single one of these is used as per checking the files of #11624. we don't override weeds with snowmen and cocoons with snow angels. we don't override armor with christmas variants, that's a CM thing. we don't override all helmets with santa hats, that's a CM thing. we don't use any of these present icons, the icons we use are called "gift", not "present" and are housed elsewhere. as stated in the PR body, the seasonal MRE sprites we use are duplicated of the ones here called from "food/mre.dmi", not this dmi, so the ones in here are unused.

**Comment by lbnesquik** [comment]
Does clearing icons like this actually save significant bandwidth for anyone? For anyone coding, it just adds extra .git to download when you first clone the repo, no?

**Review by TiviPlus — APPROVED** [review]
code ok

**Pull request merged**
