### PR TITLE
Loadouts vendor in Twins Pillars (HvH)

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Add loadouts vendor to hvh mode

## Changelog
:cl:
expansion: Loadouts vendor works in Hvh
/:cl:

### CODE REVIEW

**Comment by MereWalker** [comment]
Could you get items that you wouldn't find in HVH or would this be fine?

**Comment by InterroLouis** [comment]
I'm more concerned about this making it so you can't loadout things that aren't in the hvh vendors in distress signal.

**Comment by TiviPlus** [comment]
Answer the questions please

**Comment by BraveMole** [comment]
> Could you get items that you wouldn't find in HVH or would this be fine?

No

> I'm more concerned about this making it so you can't loadout things that aren't in the hvh vendors in distress signal.

This has no effect on distress signal?

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
