### PR TITLE
More big red shutters

### PR DESCRIPTION
**Pull request by DominikPanic**

### CODE REVIEW

**Comment by Alterist** [comment]
this needs to be rebased

**Comment by DominikPanic** [comment]
Done

**Comment by Alterist** [comment]
still doesn't look right, a previous pr I did made a significant change to how the code for big red was laid out, you might have to do your changes from scratch

**Comment by DominikPanic** [comment]
Copy, will do

**Comment by DominikPanic** [comment]
Down to 11 lines now

**Pull request merged**
