### PR TITLE
Nuke can no longer be portalled

### LINKED ISSUE #12615: Wraith can teleport nuke into fog
### Description

The griefer caste known as Wraith can utilize portals to push one-of-a-kind objects into UNREACHABLE areas for the enemy team.

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [20503](https://scrubby.melonmesa.com/round/20503)
BYOND Version: 515.1604
Server revision compiled on: 
Master commit: [ac56f43309c2ba24213b24fd70b7a72ce7246bda](https://github.com/tgstation/TerraGov-Marine-Corps//commit/ac56f43309c2ba24213b24fd70b7a72ce7246bda)
The following pull requests are currently test merged:
[#12584: 'Adds minimap drawing' by TiviPlus at commit 957675a705](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12584)

Local commit: 925e61c433d25affcf115c0798d9156308ba1ae6
Server tools version: 5.7.3

### Reproduction Steps

1. Steal unanchored nuke from marines (Or even have marines do it for you by putting the portal in front of nuke as they're moving it lol!!!)
2. Put one portal in fog, one outside of fog
3. Push nuke through
4. Make the game unwinnable for marines

### Screenshots

This shouldn't be a thing
bullshit

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
You can no longer portal the nuke.
Fixes #12615
## Why It's Good For The Game
Being able to queen scree the marines and have a wraith drop a portal to instantly steal the nuke is cringe.
## Changelog
:cl:
balance: The nuke can no longer travel through portals
/:cl:

### CODE REVIEW

**Comment by Runian** [comment]
Skill issue on marines for not clicking the instant anchor button.

**Comment by iforgotmeword** [comment]
Pure Mope

(Anyway I rarely see nuke being used at all so I got nothing really to say)

**Comment by Arturlang** [comment]
Ah yes, let's remove every wraith fuckery possible.

**Comment by Mannybrado** [comment]
honestly might as well prevent anything but xenos and projectiles from going through portals at this point

**Comment by Kuro020** [comment]
Is there not an anchor button marines can press to prevent this? Not feeling this one boss

**Comment by Lumipharon** [comment]
because trying to simply drag it away canbe stopped, but a queen can literally screech the marines, then wraith blinks in and insta portals it away and its instantly out of marine range. Also yes, fuck wraith basically.

**Comment by Arturlang** [comment]
> because trying to simply drag it away canbe stopped, but a queen can literally screech the marines, then wraith blinks in and insta portals it away and its instantly out of marine range. Also yes, fuck wraith basically.

Sounds like proper teamwork!

**Review by TiviPlus — APPROVED** [review]

**Comment by iforgotmeword** [comment]
> Is there not an anchor button marines can press to prevent this? Not feeling this one boss

Can't the wraith just banish the marine pulling it?
(Kinda point talking about it this late but meh)

**Pull request merged**
