### PR TITLE
Corpsmen Storage QoL V2

### PR DESCRIPTION
**Pull request by Swagile**
## About The Pull Request

Adds a 15 point buyable to corpsmen vendors; the combat backpack. Balanced around the fact that you get 2 less meraderm hypos / case, and/or 1 less neuraline in return for greatly increased storage space.

## Why It's Good For The Game

With the constant addition of anti-chems (neuro, larvae injection being used more, neurotox clouds, ranged prae neuro) and the nerf to webbing (no surgical vest), corpsmen gaming is at an all time low. One of the issues is that storage is a huge issue; you have to carry extra hypervene (or ryt if your a gamer like fernando), dylovene (to deal with OD's of these xeno chems) and dexalin (same reason), alongside other specialized meds such as iron sugar. This means you basically have little to no room for ammo to be an actual corpsman; a healer and defender of your patients. This PR helps to alleviate that while still having a drawback for choosing it.

## Changelog
:cl:
add: Adds combat backpack to corpsman point vendor for 15 points.
/:cl:

### CODE REVIEW

**Comment by Swagile** [comment]
ok i figured out how to separate my commits, should work now

**Comment by SpaceLoveSs13** [comment]
This is honestly a nice trade-off for extra storage whenever needed. I like this.

**Comment by fernandos13** [comment]
well fuck meraderm and neura cause they are pointless with the new purge chem meta GIMME BACKPACK!

**Comment by EvilMelonTheSecond** [comment]
I ain't giving up 12u of neuraline for anything. Comparing the rarest chemical in the game to anything below 40 req points is pointless to me.

But I know for a fact that doing custom mixes is a rare thing and even people that do might want the extra storage. Corpsman are the most storage starved marines in the game and they certainly need the biggest backpack they can get. The QoL of having a combat backpack is a tasty treat most corpsman don't know about since it is buried in req list of useless/overpriced gear. Only problem I can think of is the 15 point price driving people to buy 3 and distribute to their team for storage creep.

**Comment by Swagile** [comment]
> 
> 
> I ain't giving up 12u of neuraline for anything. Comparing the rarest chemical in the game to anything below 40 req points is pointless to me.
> 
> But I know for a fact that doing custom mixes is a rare thing and even people that do might want the extra storage. Corpsman are the most storage starved marines in the game and they certainly need the biggest backpack they can get. The QoL of having a combat backpack is a tasty treat most corpsman don't know about since it is buried in req list of useless/overpriced gear. Only problem I can think of is the 15 point price driving people to buy 3 and distribute to their team for storage creep.

I thought of that and honestly.

If a corpsmen is willing to give up all their special chems for 2 other marines in their team getting some extra storage, then by all means. It just makes them a LOT less effective early to mid game.

Not like the combat backpack is some massive game changing item anyway.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
