### PR TITLE
Lower Marine Respawns

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request

Lowers marine respawn timer to 15 minutes

## Why It's Good For The Game

Enables more faster paced gameplay and dying as marine doesn't feel so punishing. Seems worth trying with the current open PRs.

## Changelog
:cl:
balance: Marine respawn timer lowered
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
15 is way too high, it should be 10

**Comment by Jeff-jefferson-jeffery** [comment]
respawn time?
Infinite marine respawns. Instant marine respawns. As a balancing measure reduce the amount of weapon vendors to 1 per map.

**Comment by Tupinambis** [comment]
This feels inappropriate without a nerf to cadehugging or allowing for marines to be permakilled/harder to revive. I don't want marines holding out for respawns to be a meta.

**Comment by TiviPlus** [comment]
Meme Pr

**Pull request closed without merging**
