### PR TITLE
Walk/Run and Melee reworks

### PR DESCRIPTION
**Pull request by Rohesie**
## Changelog
:cl:
balance: Walk-mode is now the default, and much faster than before. Run-mode is the same as before, faster than walk, but it carries penalties. This should slow down the pace of the game a little.
balance: Melee attacks, including both unarmed and with weapons, now respect melee armor. They are affected by melee accuracy. For now a walking user will always hit, but a running one will have a small miss chance.
/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
Does this effect xenos in any capacity?

**Comment by Rohesie** [comment]
Currently yes, making them choose between run speed and 80% melee hitchance and a `0.1` seconds movement delay and guaranteed melee.
This is a draft, though, so things may change.

**Comment by jroinc** [comment]
+1

**Comment by spookydonut** [comment]
@Rohesie let us know what you intend to do with this draft

**Comment by Rohesie** [comment]
This one should wait for stamina, and be linked to it.

**Comment by Rohesie** [comment]
This will be done in the aforementioned PR, due to how closely related it is.

**Pull request closed without merging**
