### PR TITLE
Sentinel movement animation

### PR DESCRIPTION
**Pull request by rusher210**
I wish to make all xenos move

## About The Pull Request

Made walking/running animation for sentinel, i want to make animations for all the xenos but this is my first time creating so all all feedback is apreciated

## Why It's Good For The Game

It's fun to look at and hunter deserves an animated xeno companion 

## Changelog
:cl: glassyduke

imageadd: added some icons and images for sentinel

/:cl:

enomorph

### CODE REVIEW

**Comment by MereWalker** [comment]
Im going to laugh at this but at the same time, I love it. Keep at it I say!

**Comment by Walarks** [comment]
I think the front and back walking sprites shift too much and look silly.

**Comment by RenGusta** [comment]
Do an actual animation separate from just flipping the facing, basically, and it might look Bueno.

**Comment by mateus460** [comment]
the animation shifts too much,needs some inbewteen frames to look smoother

**Comment by Kuro020** [comment]
Needs some more frames to look smoother imo

**Comment by Al-1ce** [comment]
> Needs some more frames to look smoother imo


You have no idea how hard that is to do with directional sprites. They've done an excellent job with the resources that they have. (BYOND)

**Comment by KornFlaks** [comment]
Yea, the tail swipe movement needs to be reduced, maybe to half the arc. Right now, it's too jarring for 2 frame.

**Comment by SplinterGP** [comment]
also use a good delay, put 2 delay between each frame like hunter i think or 2.5

**Comment by rusher210** [comment]
thanks everybody for the feedback!
so far added 2 extra frames (4 total) for the front and back, smoother tail animation, reduced the tail swipe and adjusted the tail acordingly. my skills still lack so sideways didn't get 2 extra frames of animation (had to scrap it because it sucked).

**Comment by KornFlaks** [comment]
If it's not too difficult, can you also add those two new frames in reverse? 
So it doesnt go from 1-2-3-4 --- 1 (new cycle). Instead: 1-2-3-4-3-2 --- 1 (new cycle)

**Comment by SplinterGP** [comment]
DM has a button which lets you put it to loop to do the above.

**Comment by TiviPlus** [comment]
@Kuro020

**Comment by Kuro020** [comment]
> @Kuro020

it's cool now

**Pull request merged**
