### PR TITLE
Adds 50 more health to every beno but runner, adds 10 slash damage to ravager

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title basically

## Why It's Good For The Game
beno man squishy, this adds on average should make benos take more bullets before dying.
Ravager is ass right now.

## Changelog
:cl:
balance: Ravager deals 10 more damage. Every xenomorph but runner has gained 50 health.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -32. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Chaznoodles** [comment]
Not good. Xenos can now bruteforce defences and it takes a good deal more shots to bring them down. Pistols and machinepistols now pointless. 100 extra health is a lot more than you think, when you remember armour exists.

**Comment by RenGusta** [comment]
Update the description to reflect the 50 damage slash you applied to ravager, which is excessive.

**Comment by psykzz** [comment]
Disagree with changing it to 50, it feels like it barely does anything. Xenos need enough time to be able to brawl, something they are not getting right now with just 50.

Also the healing and plasma nerf were made with 100 hp in mind.

**Comment by psykzz** [comment]
I removed the health nerf from my pr

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-38). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
