### PR TITLE
The Gun Sound Overhaul 2.0 + More Weapons to EORD (PART 1)

### PR DESCRIPTION
**Pull request by XSlayer300**
## About The Pull Request

It's 2023, and it's time for a re-do!

Reoverhauls almost every gun sound in the game, once again. This is part one of IDK series for resounding every gun once again, this one covers almost every weapon available in the TGMC vanilla vendor, not including seasonals or energy weapons (at least for the moment).

All sounds are from various owners.

**All (new) sounds are from (once again) their respective owners, and I (and the entire community) do not take ownership from these sounds, mixed or not. They use the CC-BY-NC-SA 3.0/Creative Commons Attribution-NonCommercial-ShareAlike 3.0 United States license.**

**If any IP wants me to remove those sounds mixed in with the original ones, I would be glad to oblige.**

In addition to minor changes to descriptions of guns, this PR also adds new weapons to the EORD weapon pool.
## Why It's Good For The Game

It's almost been three years since the last gun sound overhaul, and I think it's about time to do a make over of all of the sounds we've made along the way. Also, more weapon variety in EORD.
## Changelog
:cl:
soundadd: Completely OVERHAULED every weapon firing sound, once again! Sounds use CC-BY-NC-SA 3.0.
add: Added more weapons to the EORD weapon pool.
spellcheck: Changed some descriptions and renamed the 88 mod 4 to the MK88 mod 4.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
> They use the CC-BY-NC-SA 3.0/Creative Commons Attribution-NonCommercial-ShareAlike 3.0 United States license.
You can't just uh, take sounds from a game and license them under a license, non commercial or not. This PR is still illegal.

(I don't care about using sounds from well known games, im just saying that it doesn't make us look any better)

**Comment by XSlayer300** [comment]
> > They use the CC-BY-NC-SA 3.0/Creative Commons Attribution-NonCommercial-ShareAlike 3.0 United States license.
> 
> You can't just uh, take sounds from a game and license them under a license, non commercial or not. This PR is still illegal.
> 
> (I don't care about using sounds from well known games, im just saying that it doesn't make us look any better)

Honestly, I am not too familiar with licensing at all. All I just did was mix sounds from various sources, I simply do not know what's the best thing to do.

**Comment by Kapu1178** [comment]
> > > They use the CC-BY-NC-SA 3.0/Creative Commons Attribution-NonCommercial-ShareAlike 3.0 United States license.
> > 
> > 
> > You can't just uh, take sounds from a game and license them under a license, non commercial or not. This PR is still illegal.
> > (I don't care about using sounds from well known games, im just saying that it doesn't make us look any better)
> 
> Honestly, I am not too familiar with licensing at all. All I just did was mix sounds from various sources, I simply do not know what's the best thing to do.

The license of the audio is whatever the creator put them under. It's not impossible and even highly likely that most of these studios got alot of their sound from either free audio sources or paid audio sources. In most cases they are licensed under whats called All Rights Reserved which means the owner of the asset has exclusive rights to do whatever they want with i. Anyone else doing something like redistributing is a copyright infringement. That is what this PR is doing.

**Comment by XSlayer300** [comment]
> The license of the audio is whatever the creator put them under. It's not impossible and even highly likely that most of these studios got alot of their sound from either free audio sources or paid audio sources. In most cases they are licensed under whats called All Rights Reserved which means the owner of the asset has exclusive rights to do whatever they want with i. Anyone else doing something like redistributing is a copyright infringement. That is what this PR is doing.

I see, any suggestions in mind, besides closing the PR or modifying the sounds in the first place to not get the sounds up?

**Comment by XSlayer300** [comment]
Maybe just put in "all rights reserved from the original owners" i guess, no license or soemthing?

**Comment by Kuro020** [comment]
just remove the list of games you took it from and play dumb like I do

**Comment by XSlayer300** [comment]
> just remove the list of games you took it from and play dumb like I do

done :p

**Review by Lumipharon — APPROVED** [review]
probs shouldn't have the gun editions in a sound pr but eh

**Comment by yyzsong** [comment]
👎 
The new gun sounds are not very good. For one, they're way too loud. More substantially, they don't really sound like guns- they'd probably fit better on the mech's cannons (and one of the sounds is pretty much identical)- what franchise did you steal these from?

Also, what was wrong with the old gun sounds? """"We haven't done a resound in three years"""" Because the sounds are fine!

**Comment by Strayed-Raven** [comment]
The new sounds are not very neat. The AR11 sounds good. The shotgun ones could be kept separate, for instance the auto shotgun can be the old one. and the pump the new sound. the regular revolver sound are also a downgrade and very loud. AR-12 is not good. You really should focus on rifles having different sounds instead of all being homogenous. The SMGs sound the same as Rifles. DMR sounds good. Bolt action should stay the same. Old MG60 was better. Probably the BEST and only example I can find to illustrate what I am talking about is the quality and variety with the pistol sounds in this PR. More of THAT please.

**Comment by Sirsnek15** [comment]
Several problems with this. ar12 ar18 and ar21 are completely the same, many weapons have unfitting sounds such as the mp19+smg90+p14, some weapons sound more powerful than others when they are not. Listening to the .ogg's they sound good, but this is horrible game-sound-design, many were changed for the worse. For example, the changed smg90 sound does not match a submachinegun. But it sounds great, and it tells the players that it is an assault rifle. See the problem? Its like this everywhere. In addition, less powerful pistols don't sound less powerful. I appreciate the effort put into the pistol variety in particular, but the p14 sound would be better as the p23, and the old p14 sound restored. Theres probably countless critiques I could give about the different sounds but it would take a very long time to compile. If you're deadset on these sounds though, I can do that.

**Comment by XSlayer300** [comment]
Alright, the following sounds are updating for the next TM:

- AR12
- AR18
- AR21
- MG60

- MP19
- SMG90

- P14
- R44

- SH15
- SH35
- SH39

**Comment by FosterGrime-Heymynameslouie** [comment]
these are really cool sounds, especially like the kaboom ones, you also shouldnt listen to people sahying the t60 and m27 sounds too lound they are perfect as is

**Comment by XSlayer300** [comment]
> these are really cool sounds, especially like the kaboom ones, you also shouldnt listen to people sahying the t60 and m27 sounds too lound they are perfect as is

Well, it's MY PR, but I have a degree of freedom on what others say and apply it as suggestions.

**Comment by Kapu1178** [comment]
> > these are really cool sounds, especially like the kaboom ones, you also shouldnt listen to people sahying the t60 and m27 sounds too lound they are perfect as is
> 
> Well, it's MY PR, but I have a degree of freedom on what others say and apply it as suggestions.

if people hate your entirely subjective PR it will likely not be merged. this aint the way chief.

**Comment by maikilangiolo** [comment]
All the sounds are pretty good. Def upgrade

**Comment by FIXTHERADBOXPLEASE** [comment]
A little silly to say that when he is taking heavy feedback...

**Comment by FosterGrime-Heymynameslouie** [comment]
> > these are really cool sounds, especially like the kaboom ones, you also shouldnt listen to people sahying the t60 and m27 sounds too lound they are perfect as is
> 
> Well, it's MY PR, but I have a degree of freedom on what others say and apply it as suggestions.

I uhh, shouldve probably made it more clear that the last part was a joke 

good pr noentheles 101/0

**Comment by AlexCrimson** [comment]
It is a bit loud. Is it not possible to have volume control for guns? That would probably help a lot. Right now i can clearly hear gunshots from over a screen away and i have volume set to 2%! I cannot even hear footsteps with sound set that low, but gunshots are crazy loud.

**Comment by Lumipharon** [comment]
> It is a bit loud. Is it not possible to have volume control for guns? That would probably help a lot. Right now i can clearly hear gunshots from over a screen away and i have volume set to 2%! I cannot even hear footsteps with sound set that low, but gunshots are crazy loud.

Range doesn't necessarily corrolate with volume. Sound range is a specific var for sounds, so you can have a very quiet sound that everyone on the map can hear, if you wanted.
Otherwise, range is based on the CODE volume of the sound (i.e. making the sound file quieter does not effects its range in any way).

**Comment by AlexCrimson** [comment]
>Range doesn't necessarily corrolate with volume. Sound range is a specific var for sounds, so you can have a very quiet sound that everyone on the map can hear, if you wanted.
Otherwise, range is based on the CODE volume of the sound (i.e. making the sound file quieter does not effects its range in any way).

In my dumb unga brain, all i know is that the gun sounds are too loud. To the point i need to turn down my volume to a level where i cannot even hear other sounds(like footsteps), just to stop them being distractingly loud. The only time they are bearable is when i am over a screen away from them. 

Considering there is almost always multiple people shooting on the frontline, it doesnt seem like a bad idea to have a volume controller for guns. Unless it requires an unreasonable amount of work to implement something like that.

**Pull request merged**
