### PR TITLE
Lower the price of sadar WP and HE by 1 point, so we see something besides AP for once.

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
See title. Decrease is from 7 to 6. Not huge, but it might be enough to change things a little.

## Changelog
:cl:
balance: Very slight reduction in price of HE and WP sadar rockets, with the aim of varying ammo usages.
/:cl:

### CODE REVIEW

**Comment by Hekzder** [comment]
I almost feel like you could maybe make it 5? A one point reduction is not super substantial, even in a bulk purchase.

**Comment by Pariah919** [comment]
don't reduce HE
it's better than AP but because of complacency gaming syndrome everyone teters to AP because that's just what they think does the most direct hit damage, but he does more direct hit damage because of the explosion.
Reduce WP to 5 so it has some use

**Comment by lbnesquik** [comment]
WP has been reduced to five. He is still 6 after feedback

**Comment by Ieteihowmee** [comment]
Nice

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
