### PR TITLE
Rock and Stone.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds a brick and stones.
image
## Why It's Good For The Game
Brick
## Changelog
:cl:
add: New brick in req
/:cl:

### CODE REVIEW

**Comment by 74delta** [comment]
mmmm brickmsmmsmmss

**Comment by Lumipharon** [comment]
Bruh, how do you turn a brick into a stone?

**Comment by Xander3359** [comment]
> Bruh, how do you turn a brick into a stone?

Smack 2 bricks together and you pick up the pieces.
I'm only loosely using video game logic here cmon.

**Comment by FosterGrime-Heymynameslouie** [comment]
brik

**Comment by lbnesquik** [comment]
Add a supreme version.

**Comment by Xander3359** [comment]
> Add a supreme version.

Is this you offering to give me free sprites?

**Comment by TheUSSWatercooler** [comment]
brick cades?

**Comment by TiviPlus** [comment]
Young runner is hit by the supreme brick

**Pull request merged**
