### PR TITLE
Hunter Buff

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Grants hunter .1 speed.
## Why It's Good For The Game
Helps hunter be a bit more mobile and easier to combat aim mode balls. Don't think damage needs a buff with AP being added.
## Changelog
:cl:
balance: Increases hunter speed to -1.5
/:cl:

### CODE REVIEW

**Comment by Arkansas-Bar-Association** [comment]
Duties: Attack marines' backline in the dark, pick off lone wolves by winning duels, finish off Marines, make marines hate you for delimbing them

Why does hunter need to combat aim mode balls?

**Comment by Barnet2** [comment]
I am usually all for xeno buffs, but I don't think Hunter is the one who needs it.

**Review by Kuro020 — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Comment by coldironwarrior** [comment]
not necessary. i actually play hunter. the caste is fine and playing against aimmode balls is not at all the optimal way to play, so expect it to suck.

**Comment by FosterGrime-Heymynameslouie** [comment]
hunter is already pretty fast why would it need to be faster

**Pull request merged**
