### PR TITLE
Fixes vents going under weeds.

### PR DESCRIPTION
**Pull request by DominikPanic**
:cl: LaKiller8
fix: Vents are now visible over weeds.
/:cl:
Fixes: #1613

### CODE REVIEW

**Comment by DominikPanic** [comment]
> 
> 
> I would not call this a valid fix.

It works and doesn't break anything. Could you go into more detail and suggest an alternative, please?

**Comment by spookydonut** [comment]
Removing plane code is not a fix, you need to fix weeds to work with planes correctly.

**Comment by Rohesie** [comment]
This is a bug that severely hurts xenos and planes are not likely to happen anytime so soon.
I agree with not merging it, even though the feature shouldn't happen if incomplete, but TMing this will be kind of necessary.

**Comment by spookydonut** [comment]
Planes are already mostly a thing.

**Comment by Rohesie** [comment]
Alright, we'll TM it until then.

**Comment by spookydonut** [comment]
> 
> 
> Alright, we'll TM it until then.

just copy the vent plane code for weeds, duh.

**Comment by spookydonut** [comment]
ffs i'll fix it myself.

**Pull request closed without merging**
