### PR TITLE
Hypo Belt Rework + New Hypos

### PR DESCRIPTION
**Pull request by CCorvet**
## About The Pull Request

Reworked the hypo belt, look at images to see before and after, this includes allowing it to hold these new items.  The combat mix hypo(Cm one) has 40 40 bica kelo 20 20 tricord tram, 10u dose

Before
image

After
image

Also Hypobelt and Lifesaver can now hold the same items, AKA all of them, but not the syringe pouch anymore.

## Why It's Good For The Game

Hypobelt is currently in a bad place due to both neglect and just outright not being viable. Now the pros/cons between it and lifesaver should be about equal in my estimate, with instant application, higher amount of basic chems, and a simple combat mix in hypobelt, in contrast to more total chems and kits overall in lifesaver.

Naturally, people will min-max like they usually do, so a rebalance will need to be done in the future.
I am also aware that some of these changes may be controversial, so I'll leave up to the maints what parts to keep. If nothing else, the replacement of dexalin with isotonic should stay.

## Changelog

:cl:
add: New Large Combat mix, Hypervene, Isotonic hypos
add: Hypo belt can now hold pill bottles and kits
del: Removed reagent bottles from hypo belt
add: Replaced them with pill bottles
del: Replaced Dexalin and Hypervene hypo with Isotonic and big variant
qol: Hypobelt now starts completely full of supplies, like the lifesaver belt
qol: Lifesaver and Hypo belt now can hold all of the medical items each could for consistency
/:cl:

### CODE REVIEW

**Comment by CCorvet** [comment]
am dum, images comin'

**Comment by CCorvet** [comment]
> Looks fine to me. Oh wait, you made the combat mix have 20 20 trama trico, not 30 30

ah, good catch, updating the original post

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Why are you making it lifesaver 2

**Comment by novaepee** [comment]
It's intended to be limited compared to lifesaver (source: I made hypospray belt). If anything, increase reagent bottle capacity instead of allowing to hold pill bottles.

This PR won't get merged unless you deal with Tivi's feedback.

**Comment by CCorvet** [comment]
> Why are you making it lifesaver 2

So it is as viable as lifesaver belt. Instead of balancing it by limiting what stuff each can hold, gimping loadout freedom, it is balanced by what it starts with, especially since pill bottles and hypos, especially big ones, are roundstart limited. This feels more in line with the balancing of stuff like grenades in my point of view.


> It's intended to be limited compared to lifesaver (source: I made hypospray belt). If anything, increase reagent bottle capacity instead of allowing to hold pill bottles.
> 
> This PR won't get merged unless you deal with Tivi's feedback.

In what way do you mean limited? Is the holding pill bottles the issue? 

Anyway, got an idea that may satisfy you both but may require some coder sprites, Preassurised Hypospray Refills, act like a 240u or 300u beaker, that can only be filled from chem masters (and come filled), but also only comes from hypo belt and as a buyable from corpsman equipment.

Issue is it will be either codersprites with my literal zero experience (i am scared of how reagent amount/color overlays work already), or a spriter has mercy.
I'll start looking into the former after a quick call for mercy in #artwork.

**Comment by Arctrooper8** [comment]
Instead of bothering with bottles or pills at all why not change the hyposprays themselves?

You could just give them a much bigger capacity (but smaller than pills total reagent count for balancing), this also removes the need to constantly fiddle around with refilling your hypospray from bottles in the middle of battle.

Or even better why not make the hypospray belt really unique by having each hypospray slowly refill itself over time, this gives it a unique niche of instant injection and no need to resupply but storing less overall and not holding kits or splints.

**Comment by Lumipharon** [comment]
You're just making it a better lifesaver belt? Why?

**Comment by CCorvet** [comment]
> You're just making it a better lifesaver belt? Why?

It'd be as good as the lifesaver not better? Less kits, less niche chems,gets disorganised with normal use when lifesaver doesnt, at benefit of more basic chems, instant application, basic combat mix that are in autoinjectors anyway?

**Comment by Lumipharon** [comment]
Everything in a life saver is available for free ship side. This hypobelt is better because it has a whole bunch of free big hypos which aren't normally free.

**Comment by CCorvet** [comment]
> Everything in a life saver is available for free ship side. This hypobelt is better because it has a whole bunch of free big hypos which normally cost 10 points or whatever.

If hypobelt is purely better because of the big hypos, then instead of making hypobelt as a whole viable while keeping its gimmick of big hypos, we should have it remain completelly unviable, other than for its free big hypos, and let medics still deploy with a livesafer belt thanks to the ones in medbay lockers?

If you wish to remove big hypos from hypobelt, i'd be down for a more complete rework, but please be clear with me.

**Comment by Lumipharon** [comment]
You are trading capacity and storage options for being able to A: store hypos at all, and B: get free big hypos.

You're just making it the objectively superior option. There would be no reason to not just always take it, dump everything but the big hypos then use it as a lifesaver.

If the niche doesn't work for you, don't use it. 

If you want lifesaver plussome hypos, just use your other storage for hypos.
If you want hypo belt but with more chem storage, just vend the 500 pill bottles in medbay and put them in your other storage.

**Comment by Joe13413** [comment]
> Instead of bothering with bottles or pills at all why not change the hyposprays themselves?
> 
> You could just give them a much bigger capacity (but smaller than pills total reagent count for balancing), this also removes the need to constantly fiddle around with refilling your hypospray from bottles in the middle of battle.
> 
> Or even better why not make the hypospray belt really unique by having each hypospray slowly refill itself over time, this gives it a unique niche of instant injection and no need to resupply but storing less overall and not holding kits or splints.

holy shit that auto refill idea is actually pretty fucking cool
gives hypo more of a niche than instant injection (which is already not SUPER good, it only takes half a second to feed someone a pill)

**Comment by BlueHNT** [comment]
> You are trading capacity and storage options for being able to A: store hypos at all, and B: get free big hypos.
> 
> You're just making it the objectively superior option. There would be no reason to not just always take it, dump everything but the big hypos then use it as a lifesaver.
> 
> If the niche doesn't work for you, don't use it.
> 
> If you want lifesaver plussome hypos, just use your other storage for hypos. If you want hypo belt but with more chem storage, just vend the 500 pill bottles in medbay and put them in your other storage.

Noone really cares about free hypos to begin with if they're gonna be useless cuz of em. I tried to make it work on several occasions but there is no niche other than taking it apart for the hypos and reusing them for your own shit.

The belt would be completely useless if not counter productive if you didn't get the hypos. It almost still is. Free hypos doesn't equal out to not being able to carry majority of vital chems.

**Comment by CCorvet** [comment]
> You are trading capacity and storage options for being able to A: store hypos at all, and B: get free big hypos.
> 
> You're just making it the objectively superior option. There would be no reason to not just always take it, dump everything but the big hypos then use it as a lifesaver.
> 
> If the niche doesn't work for you, don't use it.
> 
> If you want lifesaver plussome hypos, just use your other storage for hypos. If you want hypo belt but with more chem storage, just vend the 500 pill bottles in medbay and put them in your other storage.

I'll address it paragraph by paragraph to keep this organized.

Big hypos really aren't that big of a thing, if you are using them actively then you need 2 max, a Combat one, and a critheal one, and even then both of these can be done with small ones, you just need to refill the mixes more often.

Objectively superior by making lifesaver and hypobelt hold the same things? if so, if you want to dump out everything, replace say spaceacilin big hypo with a pill bottle, fuck it, you can, what will stop you will be it being a waste of your time for negligible advantage, and the limited amount of pill bottles in vendors. If you want to waste 30 mins for that, feel free to.

Issue with Hypobelts niche, is that it doesn't HAVE a niche. NO-ONE uses the fucking thing, very understandably so because as it is ingame, its just free big hypos if you want to min max medic equipment and you powergame into medical storage for the lifesavers there. If you want to argue that its only me who doesn't understand how to make hypobelt work, you are very welcome to ask Nani or any other admin to make a player poll. I am quite convinced the results will be "No, i don't use it because its bad".

Already do that! I don't need the hypobelt rework to enjoy my proffered corpsman playstyle, but i want to make it better so there are more medic playstyles for others to also enjoy.


Unrelated, i am pretty sure the Preassurised Hypospray Refill beaker idea is possible for me to implement, but i will hold off on any more work on this PR until its decided whether it will eventually be merged or not. Regarding the regenerating chemicals hypospray idea, i personally dislike it, so i wont make that myself, but you are free to implement it yourself and make a pull request.

**Review by QualityVan — CHANGES_REQUESTED** [review]
Not sure why you're increasing hypervene hypo size, the normal hypo is already more than a pill bottle.
Don't like the hypobelt can_hold changes. Pills and syringes are very why would you ever use this, not wild about stacks (they seem unfitting, aside from the general 'medics want these'), and pill bottles are definitely just lifesaver again. Also unconvinced that lifesaver needs changing. If you want them to hold the same things,  just make it a single belt and the vending choice changes what it's populated with.

**Comment by BlueHNT** [comment]
> Not sure why you're increasing hypervene hypo size, the normal hypo is already more than a pill bottle. Don't like the hypobelt can_hold changes. Pills and syringes are very why would you ever use this, not wild about stacks (they seem unfitting, aside from the general 'medics want these'), and pill bottles are definitely just lifesaver again. Also unconvinced that lifesaver needs changing. If you want them to hold the same things, just make it a single belt and the vending choice changes what it's populated with.

I'd say that's fair. The entire point of this PR is to make hypobelt actually be usable. Not double the semi-limited med. While reworking the unused ones like Dexalin and the fact you don't have to smash every pill into your backpack so you can actually refill it.

**Comment by CCorvet** [comment]
> Not sure why you're increasing hypervene hypo size,

The hypervene thing is a brainfart, good catch, gonna revert that

>just make it a single belt and the vending choice changes what it's populated with.

Essentially what i am doing, just using the hypobelt sprite because no one will cry for it, and it is thematic being a hypo centric loadout

Frankly a bit tired of arguing the point back and forth, especially with the lack of progress. I guess if you do not want all of the changes listed here (barring the Hypervene which i am gonna revert), then please close this PR, and i will make a seperate one to replace dexalin with isotonic and fill empty space with some trash like reagent bottles and keep the status quo.

**Comment by zzurge** [comment]
Im gonna be honest Hypo belt needs some love or SOMETHING because as it stands i just dont see a reason to take it over lifesaver,its not even in COMPETITION

**Comment by QualityVan** [comment]
Closing by request, then, since as stated I don't like reducing two different belts into being exactly the same in terms of storage options. The iso/space filling PR mentioned would be welcome.

**Pull request closed without merging**
