### PR TITLE
Fixes asset topic sanity

### PR DESCRIPTION
**Pull request by DominikPanic**
Stolen from /tg/
https://github.com/tgstation/tgstation/pull/44550

### CODE REVIEW

**Comment by Rohesie** [comment]
Can you make it shriek if that value is negative?

**Comment by DominikPanic** [comment]
> 
> 
> Can you make it shriek if that value is negative?

No. /tg/ doesn't do that.

**Comment by Rohesie** [comment]
Just run a `stack_trace` so we know if it happens.

**Comment by DominikPanic** [comment]
> 
> 
> Just run a `stack_trace` so we know if it happens.

If ninja says so I will. He merged it on /tg/ and I assume there's a good reason this is not present.

**Pull request merged**
