### PR TITLE
Shrike's gravity nade fix.

### PR DESCRIPTION
**Pull request by Passe2142**
## About The Pull Request

Makes gravity nade works on where you throw it. (I tested it and works).
If its not the right way to fix it, excuse my lousy byond code.
Fixes: #9570

## Why It's Good For The Game

Fix 

## Changelog
:cl:
fix: Added in the proc view center on loc. 
/:cl:

https://user-images.githubusercontent.com/82890915/153613577-c8ce4c26-dd75-4a95-a746-d0228a016217.mp4

(Dont know where to put the video).

### CODE REVIEW

**Comment by Naaanii** [comment]
Can you post a video?

**Comment by Passe2142** [comment]
> Can you post a video?

I opened up both lockers to pull on those stuff, and added the issue's number too with video of said funny issue.-

**Comment by Naaanii** [comment]
Looks good, would be nice to see range on mobs too but I'll check it myself.

**Review by TiviPlus — APPROVED** [review]
lol

**Pull request merged**
