### PR TITLE
Double Acid Turret

### PR DESCRIPTION
**Pull request by chesse20**
## About The Pull Request

dreamseeker_EFAfqqJiq7
Double acid turret, it shoots twice as fast but has less range due to being clunky. Costs 150 points instead of 100 to compensate. Since it has less range you can shoot it from the edge of the screen without a scope and it can't shoot back 

## Why It's Good For The Game

Xeno winrate is down the drain and players keep asking for xeno content so i made some

## Changelog
:cl:
add: Double headed acid turret that spits twice as fast with less range, watch out!
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Kind of overkill since Xenos already tend use regular turrets as a killer comboing with displacement abilities like Shrike and Warrior.

**Comment by Lumipharon** [comment]
You can setup killboxes with multiple turrets all shooting at the sam ungas, so it's not really needed.

**Comment by ThelastArchiver** [comment]
this highly depends on the hive having capabale warriors and shrikes its also probably really easy to take out because of its limited range this seems reasonably balanced. i think the phrase high risk high reward first very well here.

**Comment by Pill-U** [comment]
tgmc turning into PvZ

**Comment by AnCopper** [comment]
> tgmc turning into PvZ
marinez

**Review by Kuro020 — CHANGES_REQUESTED** [review]
side sprite is way too similar to the normal acid turret

**Comment by hyper2snyper** [comment]
ima tmc this

**Comment by Kuro020** [comment]
> > side sprite is way too similar to the normal acid turret
> 
> new double turret image vs single image better?

nope, the shape is too similar

**Comment by chesse20** [comment]
any ideas on how to make it look different the perspective is hard

**Comment by Pill-U** [comment]
perhaps make it a different color make it easier to recognize like the resin turret? maybe red to emphasize on how dangerous it is or green because of all the acid inside?

**Comment by vilereaver41** [comment]
Sorry gona down vote. If xeno winrates are down this feels like a forced buff that is randomly stitched together we dont need double turrets we need a stat rework

**Comment by TiviPlus** [comment]
@Kuro020 review sprite

**Comment by Kuro020** [comment]
> any ideas on how to make it look different the perspective is hard

try to separate both uh turret mouths more, make one go on top and the other one below it on the side sprite

**Comment by chesse20** [comment]
image

**Pull request closed without merging**
