### PR TITLE
Makes R-walls flat out un-damageable from bullets and lasers

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
see title
this might require map changes
image
## Why It's Good For The Game
Marines have a wide variety of tools available to destroy walls already–ones that either cost req points or require actual risk to use.

Marines should not be able to freely open up the map as much as they can by just getting a guy with a t60 to mindlessly hold M1 at a wall for a couple of minutes; it isn't fun for xenos when marines do it en masse, and it probably isn't fun for the marines doing it except for the inherent satisfaction that comes from doing something stupid with a crowd of people.
## Changelog
:cl:
balance: Reinforced walls are now immune to bullets and lasers. Use your specialized tools, kids.
/:cl:

### CODE REVIEW

**Comment by bowlofcereal** [comment]
enjoyingthet60-1

**Comment by MiniMeatwad** [comment]
enjoyingthet60-1

**Comment by coldironwarrior** [comment]
nah; this is a tdm that takes place in a sandbox. allowing interactions between projectiles and walls augments that and allows for matches on the same terrains to change from round-to-round

**Comment by yyzsong** [comment]
> nah; this is a tdm that takes place in a sandbox. allowing interactions between projectiles and walls augments that and allows for matches on the same terrains to change from round-to-round

Marines already have tools available to change the map as they wish (OB, C4, detpacks, PCs)
Reinforced walls are meant to be reinforced, and should take a bit more specialization than holding m1

**Comment by Fawkes541** [comment]
>prs something that will most definitely require map changes
>provides no map changes
ngmi

**Comment by yyzsong** [comment]
> > prs something that will most definitely require map changes
> > provides no map changes
> > ngmi

that's what testmerges are for

**Comment by 74delta** [comment]
enjoyingthet60-1

**Comment by yyzsong** [comment]
> enjoyingthet60-1

Thomas_C _Lea_III_-_That_Two-Thousand_Yard_Stare_-_Original

**Comment by bowlofcereal** [comment]
fortnite villains

**Comment by novaepee** [comment]
303905700-2d69f06a-1847-40b5-8b04-b4c3f94498b2

**Comment by FosterGrime-Heymynameslouie** [comment]
honestly if you get like, 6 other dudes to use the t60 exclusively, cucking marines out of actual gameplay, without being able to disperse them with the amount of gas options xenos are capable of thats like a gameplay issue and not an r wall issue

**Comment by novaepee** [comment]
image

**Comment by thatguythere03** [comment]
This really sounds like it's only an issue under very specific circumstances (bowl managing to get a bunch of marines to T60s once in a blue moon). If it happened every other round and DIDN'T require a thousand marines to happen in the first place, I would say it's an issue. But it doesn't, so I'm gonna say it's not.

**Comment by 1kajowsmol** [comment]
t60spam1

**Comment by novaepee** [comment]
image

**Comment by TiviPlus** [comment]
image

**Review by TiviPlus — CHANGES_REQUESTED** [review]
From code perspective this doesnt work but ill wait for kuro to comment

**Comment by bowlofcereal** [comment]
slavery

**Comment by novaepee** [comment]
image

**Comment by novaepee** [comment]
image

**Comment by bowlofcereal** [comment]
fortnite cope

**Comment by SimplySmiley123** [comment]
> > nah; this is a tdm that takes place in a sandbox. allowing interactions between projectiles and walls augments that and allows for matches on the same terrains to change from round-to-round
> 
> Marines already have tools available to change the map as they wish (OB, C4, detpacks, PCs) Reinforced walls are meant to be reinforced, and should take a bit more specialization than holding m1

Okay let r-walls be r-walls and make them impossible to break down with acid too.

**Comment by yyzsong** [comment]
> From code perspective this doesnt work but ill wait for kuro to comment

it works I tested it

**Comment by novaepee** [comment]
image

**Comment by WinterDarkraven** [comment]
This would be nice. We could make C4 and plasma cutters cheaper to account for this.

**Comment by yyzsong** [comment]
> This would be nice. We could make C4 and plasma cutters cheaper to account for this.

#15045 adds detpacks and C4 to reqtorio, and reqtorio is usually more efficient than just buying the same amount of an item

**Comment by WinterDarkraven** [comment]
> > This would be nice. We could make C4 and plasma cutters cheaper to account for this.
> 
> #15045 adds detpacks and C4 to reqtorio, and reqtorio is usually more efficient than just buying the same amount of an item

I meant in the engie vendor. This will probably make plasma cutter and C4 mandatory. I'll see how this goes first, but my guessing is the plasma cutter will need a price cut.

**Comment by breadhunt** [comment]
> This really sounds like it's only an issue under very specific circumstances (bowl managing to get a bunch of marines to T60s once in a blue moon). If it happened every other round and DIDN'T require a thousand marines to happen in the first place, I would say it's an issue. But it doesn't, so I'm gonna say it's not.

image

**Comment by SzkieletorNutric** [comment]
spam

**Comment by Naaanii** [comment]
This seems quite over the top since Rwalls are kind of meant to be destructible, albeit with a bit more resistance. Full on immunity to one side's damage is wack.

**Comment by yyzsong** [comment]
> This seems quite over the top since Rwalls are kind of meant to be destructible, albeit with a bit more resistance. Full on immunity to one side's damage is wack.

You can still use OB, C4, or PCs to take down Rwalls, same as before.

**Comment by Helg2** [comment]
303911407-7fa52623-9ac7-495e-a350-c53bbadb2867

**Comment by Kuro020** [comment]
Nerfing something due to circunstances that only happen once in a blue moon is cringe, also xenos have caste swap now, you have no excuse to not shift to a better hive comp to counter the m60 unga ball

**Comment by Woker2004** [comment]
> Marines already have tools available to change the map as they wish (OB, C4, detpacks, PCs) Reinforced walls are meant to be reinforced, and should take a bit more specialization than holding m1

Walls are reinforced, not invulnerable in the real world

**Comment by yyzsong** [comment]
image
XOPERS WE'RE BACK

**Review by Kuro020 — APPROVED** [review]
it turned into a reocurring issue, so sad

**Comment by Looking4bros** [comment]
At least let us hit them with regular melee weapons, lmao.

**Comment by Kuro020** [comment]
MJPs pr is a better solution akshually

**Pull request closed without merging**
