### PR TITLE
5 new title paintings!

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

They are pretty nice! Contribution from the community is always encourage as long they enrich the players' experience. Say thank to Foster for making these cool title painting!

## Changelog
:cl: novaepee, foster
imageadd: add 5 brand new title painting!
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
image

image

image

image

image

**Comment by Arctrooper8** [comment]
These look... weird?
I'm not sure, something about them feels off.

**Comment by novaepee** [comment]
image

Approved by Kuro.

**Comment by FosterGrime-Heymynameslouie** [comment]
oh yeah if the majority of people dont want it or you want something changed please do comment it hear.
I want everyone to like what they're looking at whenever they boot up the game, or atleast, the majority.

**Pull request merged**
