### PR TITLE
Hivelord can build on nearby turfs again

### PR DESCRIPTION
**Pull request by XElectricX**
## About The Pull Request

A one variable change to allow the Hivelord to build on adjacent turfs again.

## Why It's Good For The Game

Haha yes let's just gutter a caste's entire niche. When are we removing the spit from Spitters? While the resin wall nerf is something I can live with there was no reason to turn the Hivelord into a fatter drone when it came to building.

## Changelog
:cl:
balance: Hivelord can build in a 3x3 area again.
/:cl:

### CODE REVIEW

**Comment by Chaznoodles** [comment]
Mmm, spitter strawman

As a hivelord with adjacent building, you can effectively stop any marine effort short of a SADAR/OB/suicide shotgun rush, because you can sit behind a wall and constantly keep the way blocked or choked. If the wall you're hiding behind starts taking damage when marines spot what you're doing, you can just shuffle to a different wall and resume, expanding your cover from cover. There is near-zero risk involved for a hivelord doing this, for a pretty high reward.

Being able to build only on the tile you're on means that hivelords have to take some risk if they build in a gunfight instead of before it, having to expose themselves if they want to do certain things.

**Comment by AdamElTablawy** [comment]
noodles winning the national award for being wrong yet again

maybe marines should try shooting the hivelord

**Comment by XElectricX** [comment]
Reminder that Hivelord has had this ability since forever, only taken away a month ago. This kind of thing has never been a problem.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
