### PR TITLE
Gives king sledge inmunity

### PR DESCRIPTION
**Pull request by PibeCantina**
## About The Pull Request

Gives king sledge immunity
## Why It's Good For The Game
Due to Kuro's changes on xenos that nerfed their speed, this makes king SUPER slow with no frenzy, meaning that stuff that slow a lot like vali and this (to some extent) really fuck over him.
Also i think that due being a 700 hp thank, this should be a thing for him too

## Changelog

:cl:
balance: Makes king immune to rocket sledge stun
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
In my opinion should extend to Queen as well.

**Comment by PibeCantina** [comment]
> In my opinion should extend to Queen as well.

Queen already has it

**Comment by Naaanii** [comment]
>Vali fucks over King
>Buffs King vs sledge

Wut?

In all seriousness having a reason to swap to frenzy is a better gameloop than afk leaving it on warding.

**Comment by Lumipharon** [comment]
> Due to Kuro's changes on xenos that nerfed their speed, this makes king SUPER slow with no frenzy

If only king had some kind of reliable way to get powerful frenzy at any time.

**Comment by PibeCantina** [comment]
> > Vali fucks over King
> > Buffs King vs sledge
> 
> Wut?
> 
> In all seriousness having a reason to swap to frenzy is a better gameloop than afk leaving it on warding.

I said things with big slows LIKE vali and sledge fuck him over!!!

> > Due to Kuro's changes on xenos that nerfed their speed, this makes king SUPER slow with no frenzy
> 
> If only king had some kind of reliable way to get powerful frenzy at any time.

Now one of the biggest baddest xenos, slow as fuck, worth the most in req, locked behind pop, will still get slowed, just not stunned.
Frenzy does make it better though, I still think it shouldn't be a thing with this particular caste

**Comment by Arturlang** [comment]
Honestly, king is kinda meh compared to queen in a lot of ways.

**Comment by Naaanii** [comment]
>I said things with big slows LIKE vali and sledge fuck him over!!!
>Now one of the biggest baddest xenos, slow as fuck, worth the most in req, locked behind pop, will still get slowed, just not stunned.

Sledge doesn't really slow iirc and you're removing the one thing it does. It hard stuns and that's like kind of it's whole gimmick. Queen is the only exception and given that King is only countered by stagger, sledge being a melee counter to king feels fine.

Making it stagger (king) instead would probably be more fair since it can still counter king without being a hard stun but removing a counter and niche gimmick from a melee weapon is kinda eh.

**Review by Kuro020 — APPROVED** [review]

**Pull request merged**
