### PR TITLE
Removes sneak attack bonus damage from hunter

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Hunter sneak attack bonus damage is now removed. Hunters will not get increased damage from sneak attacks.

## Why It's Good For The Game

Hunter op plz nerf.

## Changelog
:cl: BurgerBB
balance: Removed hunter sneak attack damage.
/:cl:

Closes #3390 
Closes #3440

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -4. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by spookydonut** [comment]
This is probably a better solution, but perhaps it should get added armor penetration?

**Comment by InterroLouis** [comment]
Adding armor penetration is basically the same as adding damage. The overall effect is it does more damage and becomes once more a 1shot attack to cripple/kill, especially heavy armor users who are slow and can't avoid the fast walk speed of the invisible hunter coming at them for that knockout and big damage.

**Comment by Rohesie** [comment]
Can you remove unused definitions, such as `HUNTER_SNEAKATTACK_MAX_MULTIPLIER`?

**Comment by spookydonut** [comment]
#3390 
#3440

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
