### PR TITLE
The rare rouny 

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

If a flag is enabled, every runner has a one percent chance of becoming a rouny

## Why It's Good For The Game

It's a fun config, and everyone loves rouny

## Changelog
:cl:
expansion: The rare rouny has arrived
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
image
when are we getting this tbh

**Comment by Sebbe9123** [comment]
> image
> when are we getting this tbh

Make this a 1% chance of happening every time someone gets the 1% rouny

**Comment by Al-1ce** [comment]
> If a flag is enabled, every runner has a one percent chance of becoming a rouny


Is this at random or when they evolve to runner?

**Comment by SpaceLoveSs13** [comment]
> ## About The Pull Request
> If a flag is enabled, every runner has a one percent chance of becoming a rouny

Doesn't rouny currently have no slash cooldown or something? Or so I have been told by players.

**Comment by TiviPlus** [comment]
Nein

**Comment by Hekzder** [comment]
> Nein

Literally 1984

**Comment by BraveMole** [comment]
Sad

**Pull request closed without merging**
