### PR TITLE
xeno are universally slower on weeds

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
-0.4 has shown to be universally too high, -0.15 seems more fair to me.

## Why It's Good For The Game
Xenomorphs on weeds are too fast

## Changelog
:cl:
balance: xenos are slower on weeds in general.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -350. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Smudged** [comment]
I don't really like this, because it makes slower xeno's significantly slower. 

If you could individually adjust each xeno's speed on weeds it'd be a little better

**Comment by Swagile** [comment]
but why

run mode marines already outrun 70% of the hive even ON weeds due to their high DPS potential

and good marines already clear weed nodes or use flamer before pushing when they know entire hive is there

**Comment by Al-1ce** [comment]
"has shown to be too high" - without citing any examples why. 
Marines can easily outrun most xenos. I feel like this choice wasn't carefully considered as this could be end-up being a serious nerf.

**Comment by DrCrawler** [comment]
"Xenomorphs on weeds are too fast". Get this stuff out of my face, if you want to outrun a xeno on weeds just press alt and run. Guys like you want to turn xeno gameplay into a litteral nightmare. 1.4 multiplyer is balanced, and was here for ages. You are the first one in a year trying to re-balance something everybody else doesnt even care about. Guess why? It was rebalanced like 10 times already. Also work on your midget pull request, i wont tolerate such short requests with 0 examples. Like come on man, i know you can do better then this!

**Comment by TiviPlus** [comment]
I'd rather wait until pools are in a more stable state before we get back to hashing out xeno speed

**Pull request closed without merging**
