### PR TITLE
Make the T-64 Great Again

### PR DESCRIPTION
**Pull request by Redstonize**
## About The Pull Request

Made it a uniquely good weapon at medium to long range since autoburst delay and extra delay are shorter.

## Why It's Good For The Game

Autoburst gets to be equal to burst, you shouldn't need to be a good CS:GO player to use the Battle Rifle.

~~Scatter forces you to use a recoil compensator or a vertical grip while making long range shots more difficult, therefore you are more likely to miss, but you have better punch ESPECIALLY AT CLOSE RANGE.~~ Only low scatter (from burst multiplier) makes it a weapon of choice for ranged, ~~plus the accuracy multiplier of 1.25,~~  this is magnified by the bullet changes, but then we remove plasma pistol, UBF and masterkey. 

Last change I made was the accuracy and fine tune balance change.
## Changelog
:cl:
balance: Light marksman bullet gets 5 AP, 2.5 damage and 0.25 sunder.
balance: The T-64 Battle rifle gets slightly better stats in autoburst and burst, can no longer use UBF, plasma pistol and masterkey.
/:cl:

### CODE REVIEW

**Comment by vilereaver41** [comment]
got a before and after clip ?

**Comment by Redstonize** [comment]
**Before**
https://user-images.githubusercontent.com/5296592/152906174-eeb6b627-2535-4a65-bc0a-24bd3c3beae3.mp4


https://user-images.githubusercontent.com/5296592/152906179-eaebe5bd-8b99-42ec-8086-305b778dd1ac.mp4


**After**

https://user-images.githubusercontent.com/5296592/152906273-b4f279c0-4b5a-4878-b1ea-8e910cc32aa0.mp4

**Comment by BraveMole** [comment]
@Pariah919 opinion?

**Comment by Redstonize** [comment]
**New Autoburst**

https://user-images.githubusercontent.com/5296592/154387273-b81cdc45-d02e-4812-89a3-837b0b9430dd.mov

**Comment by Redstonize** [comment]
**New Autoburst value = .56**

https://user-images.githubusercontent.com/5296592/154391092-22c5c253-9d51-4f25-94ba-2f51e7401730.mov

**Comment by Redstonize** [comment]
**Final Autoburst (And burst) value = .65**
https://user-images.githubusercontent.com/5296592/154586243-4555085c-a442-462c-b959-b127c2e8597f.mov

**Comment by OpsCoretango** [comment]
2 weeks later..

**Comment by Pariah919** [comment]
Seems okay now?

**Comment by Redstonize** [comment]
> Keeps the T-64s niche of being the difficult to use but difficult to master Burst fire weapon. So it seems fine now.

Heavily disagree. See the difference in firepower from t-37 to t-64, then t-18 and t-64. Every weapon in the game is better.

**Comment by Redstonize** [comment]
My preferred loadout during Testing phase was as follows: **Close range build:**
Magharness, Bayonet, Gyroscopic Stabilizer on T-64 on the suit slot.
Magharness, Barrel Charger, Gyroscopic Stabilzier on the T-64 back slot.

**Pull request merged**
