### PR TITLE
Mortar now warns of minimum range during lase, not only during firing.

### PR DESCRIPTION
**Pull request by JackTheJackhammer**
## About The Pull Request

Makes the Mortar inform the Artillery-man if his target from binoculars is too close before he tries to fire the round

## Why It's Good For The Game

Its annoying having to press z a billion times because you goofed up the ranging 

## Changelog
:cl:
qol: Mortar now informs user if a lased target is too close when the target is lased.
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by JackTheJackhammer** [comment]
> Actually isn't it the mortar saying this not the binocs

Well I was thinking since you can lase multiple mortars, the mortar should be the one doing the talking to minimize confusion

**Comment by TiviPlus** [comment]
> > Actually isn't it the mortar saying this not the binocs
> 
> Well I was thinking since you can link multiple mortars, the mortar should be the one doing the talking to minimize confusion

Yea but the thing is the person lazing is the one who cares because if he lazes bad then not much the mortar guy can do about it

**Comment by JackTheJackhammer** [comment]
> > > Actually isn't it the mortar saying this not the binocs
> > 
> > 
> > Well I was thinking since you can link multiple mortars, the mortar should be the one doing the talking to minimize confusion
> 
> Yea but the thing is the person lazing is the one who cares because if he lazes bad then not much the mortar guy can do about it

yeah that makes sense, ill fix it

**Comment by lbnesquik** [comment]
Millions must stale

**Pull request closed without merging**
