### PR TITLE
removes shift spits from queen

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

removes shift spits from queen because it only has 1 spit type now

### CODE REVIEW

**Comment by InterroLouis** [comment]
On the one hand, this makes sense. On the other hand, we would have to readd it if we ever decide to give the Queen an additional spit option in the future.

**Comment by Fikou** [comment]
> On the one hand, this makes sense. On the other hand, we would have to readd it if we ever decide to give the Queen an additional spit option in the future.

what kind of argument is this thats like scrapping an entire ability but keeping the button to use it

**Comment by factoryman942** [comment]
yeah, it's literally just a 1 line change to readd it later if/when needed

**Comment by Rohesie** [comment]
Yes, it should be re-added only if she gets more spits.

**Pull request merged**
