### PR TITLE
Move flare code to individual file

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

Seperate the flare code into it's own file.

### CODE REVIEW

**Comment by ivanmixo** [comment]
Why. This is completely unnecesarry.

**Comment by ivanmixo** [comment]
It being in a separate file doesn't make it easier

**Comment by timothymtorres** [comment]
It's good practice to break large files into smaller ones for better organization.  This is already done with several subtypes of the grenade object that makes navigating the code quicker and easier.

It's better to have seperate PRs one with the code into its own file and then another with the refactor and improvements.  It gives the review process more clarity like so:

<details>
<summary>Code Review for Refactor + File Split</summary>

chrome_tWMlaSpIGh
chrome_ZyegdhAsGX

</details>

<details>
<summary>Code Review for Refactor after File Split</summary>

chrome_ga28fM1igk
chrome_jtYQNzj808

</details>

However the downside to splitting the PRs is approval time.  I originally attempted to bundle all my changes into one PR and highlight the important stuff instead of waiting weeks or months for all the changes to go through.  Even something as simple as a one-line fix can take a week to get merged.

**Comment by ivanmixo** [comment]
wait til you see gun_system.dm

**Comment by ivanmixo** [comment]
> It's good practice to break large files into smaller ones for better organization. This is already done with several subtypes of the grenade object that makes navigating the code quicker and easier.
> 
> It's better to have seperate PRs one with the code split into a solo file and then another with the refactor and improvements. It gives the review process more clarity like so:
> 
> Code Review for Refactor + File Split
> Code Review for Refactor after File Split
> However the downside to splitting the PRs is approval time. I originally attempted to bundle all my changes into one PR and highlight the important stuff instead of waiting weeks or months for all the changes to go through. Even something as simple as a one-line fix can take a week to get merged.

Literally just do the changes you want in place instead of splitting into new file AND doing your changes. You're "fixing" an issue you yourself are causing here. It's fine if the flare code stays where it is.

**Pull request closed without merging**
