### PR TITLE
Railgun nerf partial revent and Sunder Halving (and more!)

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Partially reverts https://github.com/tgstation/TerraGov-Marine-Corps/pull/15867
Also decreases railgun sunder to half. (Willing to do more).

Specifically:
Reverts the ammo per box from 1 to 3.
Reverts the fire delay from 2 to 3.

Note I kept the reduction in Railgun ammo cost.
50 Points per box is equivalent to a SADAR rocket which a railgun box is certainly not, even with 3 shots.
The seasonal provides enough Railgun ammo additional shots do not need to be

I also kept the reduction in penetration damage through walls from 85% to 75% as well as the range decrease after penetration.

I'm very willing to discuss reducing this PR's effects somewhat if that is deemed necessary.

Later Changes:

1. Adds a shatter effect to all railgun projectiles, 8 second duration for HVAP, 3 second duration for other shells.
2. Increases damage +25 to all railgun projectiles. (175 standard, 125 IFF and HVAP).
I'll note that I'm willing to remove this +25 damage increase if asked to do so, I just think it will be generally supported.
3. Increases penetration on IFF and HVAP railgun projectiles to 100, equal to standard.
(IFF and HVAP already have significantly less damage, I dont see why they should have both less penetration and damage).

## Why It's Good For The Game

Railgun went from somewhat in meta to almost nonexistent with this PR.
I intend to bring railgun back to relevance in a somewhat reduced form from when it was nerfed.

## Changelog

:cl:
balance: Railgun ammo per box 1 => 3.
balance: Railgun sunder halved.
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
revent

**Comment by Naaanii** [comment]
Sisyphean...

**Comment by Woker2004** [comment]
I'd say if the sunder gets reduced more than it is, maybe add another 1-2 shots to mags

**Comment by GravitronBlue** [comment]
>balance: Railgun sunder halved.

HVAP sundering 50 > 25

May as well start looking at some of the previous comment suggestions if sunder is going to get cut so much from HVAP.

>Looking4bros commented on May 18
"Just use a long SHATTER effect or something lmao. Like the Laser sniper, Squashhead SMG rounds, Martini, or Tricordrazine Harvester blades. The effect is very good, but the weapons that have it aren't good at following up on it.It's a temporary 0.2 multiplier on the armor values. ..."

Decent enough way to attack armor without it being overly punishing/lasting for an attack that can hit through walls.
Still ought to be reflectable by warlocks if it isn't already but that's for a different PR to fix.

**Comment by Isy232** [comment]
I've added 8 seconds of shatter to HVAP to somewhat make up for the reduction in sunder per shot.
I've also added 3 seconds of shatter to the other railgun projectiles.

The sunder must remain significantly lower if the railgun is going to 3 shots as both Kuro and Lumi are opposed to sunder spam.

**Comment by Isy232** [comment]
Okay, 1 more change, +25 damage to each railgun projectile.
I personally think this is a good thing, but if Lumi, Kurt, one of the other maints or several people object I'll just undo the +25 damage.

**Comment by Isy232** [comment]
I gave 100 penetration to the IFF and HVAP ammo types, it really made no sense for base railgun to have 100 penetration but IFF to only have 20 and HVAP 30. These other rounds have lower damage numbers already.

**Pull request closed without merging**
