### PR TITLE
Add the FCDR vendor

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14446

Add the FCDR vendor into the FC Valhalla room. 
Extended the room for it by eating some Rwalls. 

image

## Why It's Good For The Game
Useful

## Changelog
:cl:
add: Added FC vendor to valhalla 
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
doesnt this need a valhalla variant or is everything infinite

**Comment by lbnesquik** [comment]
> doesnt this need a valhalla variant or is everything infinite

Is there? I never go to that place. I'll check it out.

**Comment by lbnesquik** [comment]
Well, the gear vendors aren't infinite. So I'm not sure why they need to be special versions?

**Comment by RipGrayson** [comment]
> Well, the gear vendors aren't infinite. So I'm not sure why they need to be special versions?

The special version needs to use no power and be indestructible so people can't grief it with grenades. I don't know if the vendor you added has either of those traits.

**Comment by lbnesquik** [comment]
> > Well, the gear vendors aren't infinite. So I'm not sure why they need to be special versions?
> 
> The special version needs to use no power and be indestructible so people can't grief it with grenades. I don't know if the vendor you added has either of those traits.

Well I copied the squad leader version. It should be sturdy, but I saw nothing about power.

**Comment by Helg2** [comment]
Can you move the "nosmoking" sign a bit higher so it doesn't stack in the mapper?
Also maybe add a second table to the first one so there's less just empty space?

**Comment by lbnesquik** [comment]
> Can you move the "nosmoking" sign a bit higher so it doesn't stack in the mapper? Also maybe add a second table to the first one so there's less just empty space?

I can't believe you are nitpicking me too. 
Done.

**Pull request merged**
