### PR TITLE
Draw order UI

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds a new UI to game prefs, allowing you to customize your default draw order.
image
## Why It's Good For The Game
Massive QOL
## Changelog
:cl:
qol: You can now change your default draw order in prefs.
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]
Very nice

**Comment by Xander3359** [comment]
> Very nice

LETS FUCKING GOOOOOOOOOOOOOOOOOOO

**Comment by Derrick2Electricboogaloo** [comment]
Seems to cause problems with the quick equip hotkeys not working properly. The draw order seems to just completely bypass the key strokes completely and sends it straight to the top. For example I use F to get my boot knife, but it still draws from my armor suit storage and place it is back.

**Review by Lumipharon — COMMENTED** [review]
bruh

**Comment by Lumipharon** [comment]
well no one is posting any issues so I assume everything is working now.

**Comment by Looking4bros** [comment]
> well no one is posting any issues so I assume everything is working now.

i weep, be this the reason draw order does not work like it used to?

**Pull request merged**
