### PR TITLE
Panther is removed(unpickable), reduced to ashes.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
It is now an admin event only mob.
It already is anyway.

## Why It's Good For The Game
Less noobtraps, if you're required to have a 15 second stun to be relevant the entire caste needs an overhaul and rework from the ground up. Better to remove it until it does.

## Changelog
:cl:
balance: You can no longer pick panther.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -17. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
should say Jake is doing a trapper class that will use panther's sprite,so until then +1

**Comment by Pariah919** [comment]
for some reason this is shown as having different changes than the actual branch.

**Comment by Kuro-ai** [comment]
pr is gone,reduced to ashes

**Comment by Pariah919** [comment]
nevermind I can't READ

**Comment by jroinc** [comment]
He's scared cause I found a way to make it functional that would shit on solo ungas, per the caste's design~

**Pull request closed without merging**
