### PR TITLE
Buffs shoulder holster webbing

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Buffs shoulder holster webbing from 1 gun >>> 1 gun + 6 mags
## Why It's Good For The Game
Making the holster webbing work like a pistol belt means that you no longer have to give up your belt storage if you want to hold a pistol + some mags.
## Changelog
:cl:
balance: shoulder holster webbing can hold carry some additional pistol magazines.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
I can sense that the xeno balance cabal would claim storage creep.

**Comment by Al-1ce** [comment]
After seeing it implemented once on a Fallout server, it's always been my personal belief that shoulder-holsters and webbings should be combinable/wearable at the same time.

**Comment by FIXTHERADBOXPLEASE** [comment]
Gee, can't wait for revolver spam to last two guns longer...

**Comment by Xander3359** [comment]
> Gee, can't wait for revolver spam to last two guns longer...

1 gun longer.

**Comment by RaidarV** [comment]
YES. This will be a great addition to "THE FUCKING WALL™®©"

**Comment by chizzy376** [comment]
Based

**Comment by Strayed-Raven** [comment]
Based

**Comment by SilencedMP5A5** [comment]
time to main shoulder holster

**Comment by GreatKingWombat** [comment]
Shoulder holster could work like two pistol belts and it wouldn't matter. It's still slower and less capacity than a crate of backpacks full of guns.

**Comment by Lumipharon** [comment]
I'd rather shoulder holster be like a mini pistol belt (i.e. hold some ammo) instead of just moar gunz

**Comment by Redrover1760** [comment]
I'm all for sidearm buffs, they seem prohibitively expensive atm to run.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
