### PR TITLE
Increase the number of pill bottles in the marine meds.

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
This commit doubles the number of pill bottles in the vendor. 

## Why It's Good For The Game
It punishes corpsmen who spawn a little later into the game a little less. With 12 bottles in one vendor, it doesn't take too long before that thing is out dry. Especially if anyone decides to hoard a bit.

## Changelog
:cl:
balance: Doubled the number of pill bottles to the Marine Med
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
The MEDIC-ONLY vendor has something like twelve pill bottles.

You do not need a billion pills. Please stop powercreeping squad unga.

**Comment by lbnesquik** [comment]
The point vendor doesn't have the basic meds, not at two points nor in pill form.

**Comment by jroinc** [comment]
I checked, and the non-point vendor still has 14. 6 medbelts, 8 advanced medkits.

I'll check the points vendor when I find it.

**Comment by lbnesquik** [comment]
> 
> 
> I checked, and the non-point vendor still has 14. 6 medbelts, 8 advanced medkits.
> 
> I'll check the points vendor when I find it. EDIT- There _used_ to be a 2 pt Advanced Medkit in there. I killed it cause it was a noobtrap. I could re-add it... but you already get 14 sets for free, not counting the 12 additional ones for everyone.

I could settle on increasing less, and only the basics. I just want some bicaridine pills for my kit.

**Comment by EvilMelonTheSecond** [comment]
> 
> 
> and you can vend a set of basic pills for 2 points from the point vendor if there's literally nothing anywhere.
> 

Any solution involving the corpsman point vendor is pointless to me as it has the now nearly unobtainable neuraline. I never take anything other than the 3 neuraline injectors for 42 points and the remaining 3 is near useless to top off my medical supplies.

But I do agree that the solution needs something other than increasing the free pill pool. Sadly I can't think of any way to make it corpsman only without the point vendor.

**Comment by jroinc** [comment]
> 
> 
> > and you can vend a set of basic pills for 2 points from the point vendor if there's literally nothing anywhere.
> 
> Any solution involving the corpsman point vendor is pointless to me as it has the now nearly unobtainable neuraline. I never take anything other than the 3 neuraline injectors for 42 points and the remaining 3 is near useless to top off my medical supplies.
> 
> But I do agree that the solution needs something other than increasing the free pill pool. Sadly I can't think of any way to make it corpsman only without the point vendor.

Increase the ones in the corpsman-only free vendor then.

**Comment by lbnesquik** [comment]
> 
> 
> > > and you can vend a set of basic pills for 2 points from the point vendor if there's literally nothing anywhere.
> > 
> > 
> > Any solution involving the corpsman point vendor is pointless to me as it has the now nearly unobtainable neuraline. I never take anything other than the 3 neuraline injectors for 42 points and the remaining 3 is near useless to top off my medical supplies.
> > But I do agree that the solution needs something other than increasing the free pill pool. Sadly I can't think of any way to make it corpsman only without the point vendor.
> 
> Increase the ones in the corpsman-only free vendor then.

**Comment by EvilMelonTheSecond** [comment]
> 
> 
> > > and you can vend a set of basic pills for 2 points from the point vendor if there's literally nothing anywhere.
> > 
> > 
> > Any solution involving the corpsman point vendor is pointless to me as it has the now nearly unobtainable neuraline. I never take anything other than the 3 neuraline injectors for 42 points and the remaining 3 is near useless to top off my medical supplies.
> > But I do agree that the solution needs something other than increasing the free pill pool. Sadly I can't think of any way to make it corpsman only without the point vendor.
> 
> Increase the ones in the corpsman-only free vendor then.

I just assume anything that can be accessed by hacking will be. A minor roadblock at best for veteran players but maybe good enough to prevent the average unga from the holy heal capsules.

**Comment by jroinc** [comment]
> 
> 
> > > > and you can vend a set of basic pills for 2 points from the point vendor if there's literally nothing anywhere.
> > > 
> > > 
> > > Any solution involving the corpsman point vendor is pointless to me as it has the now nearly unobtainable neuraline. I never take anything other than the 3 neuraline injectors for 42 points and the remaining 3 is near useless to top off my medical supplies.
> > > But I do agree that the solution needs something other than increasing the free pill pool. Sadly I can't think of any way to make it corpsman only without the point vendor.
> > 
> > 
> > Increase the ones in the corpsman-only free vendor then.
> 
> I just assume anything that can be accessed by hacking will be. A minor roadblock at best for veteran players but maybe good enough to prevent the average unga from the holy heal capsules.

Cross that bridge when we come to it. Currently, the medic-only vendor isn't hacc'd.

**Comment by TiviPlus** [comment]
The medics already have more than enough pill bottles

**Pull request closed without merging**
