### PR TITLE
AI QOL stuffs (bounty)

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

- AI eyes can hear stuff the camera eye hears
- AI eyes can see runechat from mobs (and objects) talking around them
- There's also some runtime fixes and a readme file being converted to a .md instead of a .dm

https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/0deb657d-37ed-4d82-9714-7e0629fd19c2

## Why It's Good For The Game

Qol 
## Changelog
:cl:
qol: AI eyes can hear stuff the camera eye hears
qol: AI eyes can see runechat from mobs (and objects) talking around them
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
AIs can understand xenomorphs and listen in, CIC listening bypasses caves supposedly disrupting comms, both bypass comms outages.
Additionally neither seems limited of what the eye can actually "see", only the position in general mattering regardless of static which also allows listening for any xeno foolish enough to talk while trying to do covert stuff.
Seems to have some wide-reaching implications for a qol PR.

**Comment by bowlofcereal** [comment]
does this fix AI only being playable in widescreen because the camera is broken

**Comment by DeltaFire15** [comment]
After some closer looks the runechat change doesn't appear to affect CIC overwatch eyes as opposed to what the changelog is saying, so that part of concern is unneeded.

However, the fact the current playsound implementation ignores camera static remains and is problematic as neither CIC nor AI should be able to hear things in static (if at all).

**Comment by Lumipharon** [comment]
Yeah if this lets you hear in static, thats not ideal.

**Comment by ivanmixo** [comment]
CIC eye doesn't hear audio or runechat because of the fucked up subtyping people did when making it. I may refactor that whole thing. 

I'll fix hearing in static though.

**Review by Lumipharon — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
