### PR TITLE
AR-55 is now buyable in req.. and by SLs, makes GL-54 magazines cheaper in req

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
AR-55 is now buyable by SLs for 25 points, Rifle mags for 3 points, and GL mags for 5 points.
AR-55 is now buyable from req for 525 points and 25 points for the mags.
Makes GL-54 magazines cheaper in req.
As reference GL54 mags are used in the GL.
image

## Why It's Good For The Game
Adds this in an acquireable form for marines, and adds some extra fluff to roundstart SL, I honestly don't think this gun is very good..
## Changelog
:cl:
add: AR-55 is now avaliable to be bought from req for 525 points, magazines are 25 points. 
add: SLs can now buy AR-55s from their vendors, and as such can also buy basic GL-54 magazines.
balance: GL-54 Airburst magazines have been halved in price in req from 40 to 20.
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
>500 point gun
Lol.

**Comment by Xander3359** [comment]
> I honestly don't think this gun is very good..
> 525 points
> 25 points per mag
??????????
Make it 100 points like all the other imports then.

**Comment by Lumipharon** [comment]
For the record TX-55 mags are LOREwise supposed to be t18 mags. It should totally be updated to make that the actual case, regardless of this PR going in or not.

Also it does seem a tad expensive relative to AMR etc, considering it has very expensive ammo (probs make the basic ammo cheaper).

**Comment by FosterGrime-Heymynameslouie** [comment]
no clue hwo this will affect balance but the gun itself does look cool so spedemgehr

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
