### PR TITLE
survivor trackplaytime hope it works

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
adds survivor playtime, ULTRA MAYBE

## Why It's Good For The Game
survivor doenst get their playtime tracked

## Changelog
:cl:
add: Adds tracking to survivor playtime(HOPEFULLY)
/:cl:

### CODE REVIEW

**Review by Hughgent — APPROVED** [review]
I like the idea. please demonstrate it working locally.

**Comment by TiviPlus** [comment]
It doesnt work why was this approved before proof aaaaa test it

**Comment by Hughgent** [comment]
Jesus christ, this was TM'd without the Test Merge Candidate.

**Comment by SplinterGP** [comment]
sadly cant demonstrate locally, no way to store my playtime locally, so i dindt even manage to test.

**Comment by TiviPlus** [comment]
Stale, closing

**Pull request closed without merging**
