### PR TITLE
port TG surgery tool sprites

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

title but with TACTICAL GREEN

image

sorry, MDs, CMOs, and synths, you will have to relearn what sprite is what

## Why It's Good For The Game

begone, cm sprites

## Changelog

:cl:
imageadd: port TG surgery tool sprites
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
These are way too bright and blue isn't medbay's colour here.

**Comment by bowlofcereal** [comment]
change the color of the blue to green and it's good imo

**Comment by QualityVan** [comment]
i don't like how ungrungy the new ones look (although boy a couple of the old tools are dated looking)
The blue's also just out of place because a ton of med gear/props is that shade of green.

**Comment by Pariah919** [comment]
Looks ugly. At least bother to tweak them.

**Comment by Derrick2Electricboogaloo** [comment]
CM surgery tools still look way better.

**Comment by efzapa** [comment]
based, considering I'm already used to tg/para sprites anyways

**Comment by Lumipharon** [comment]
You haven't updated the mob sprites

**Pull request merged**
