### PR TITLE
LV 2022 Rework

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Before:

image

After:

image

## Why It's Good For The Game

I think the current LV is not as good as the other maps on offer. The first goal of this PR is to make the whole general western area of the map more playable for both the xenos and marines, as currently it's just a lot of grass, water and a huge cliffside on both sides of the river, hard to approach for both xenos and marines. To address this, I opened up the southwestern exit out of the LZ and added a dome and paths around it for easier navigation. The cliffside north of the river has been cut open a tablefort area has been added. This area has a miner, so marines have a reason to go for it. It also has a bridge to get to it across the river, xenos no longer have to suffer over the tiny 2 tile bridge to attack the red disk, they have more options and I think that's good. The exit of this bridge can also be flanked via the little passage through the cliffside, so you shouldn't go all in on it, either.

The second goal is getting engineering back to where it used to be. On every single other map engineering is very difficult to get to and it's a goal for the marines to get to, so I don't think marines should get it so easily. This should make it similar to other maps in the sense its just outside the caves, so it can be taken with a good push and held. The semi-open areas around it should allow marines to not have to push through a narrow bottleneck, as well. The area where enginerring was is now just the recreation area that used to be there before.

## Changelog
:cl:
expansion: Various changes and additions to LV, check github for more info.
/:cl:

### CODE REVIEW

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Solid job overall, I have one complaint though. We only have 6 domes for spawn, with this revision you have 7 modular dome spawners out.

This will either lead to a repeated dome, or a blank void, not sure which. Either is bad and needs corrected.

**Comment by Al-1ce** [comment]
Looks nice. There used to be a lot of dead/empty space and pointless bends that aren't there anymore. Only issue with this is that the tablefort and the area around it looks a little too wide open.

**Comment by Weedmaster77** [comment]
I like that someone is trying to change the map up some only problem I have with it is there are new cave openings on the south beach making it very easy for flanking and flanking seems to be a mostly xeno sided move it seem like it could make a lot cave pushes just get flanked and very hard for marines to defend all the opening if there trying to trap xenos in. As for the dome and building at the Tfort I like the more cover for both sides as a place to hold off.

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: fd13cccb034c3ed8b1e7f742ecb93ac14c7e70a6
Pull Request: 6cf2ba5ea81e37d170ede81420d10e310d42b580
Server: 932d5fc994524e8e809075a694fc03e13400a193

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: fd13cccb034c3ed8b1e7f742ecb93ac14c7e70a6
Pull Request: 6cf2ba5ea81e37d170ede81420d10e310d42b580
Server: 03bfcac3bdfdd9dab131bb3b9be127e451515037

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Single space tile west of LZ2, discovered by shiryu
tile16
spesstile

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\naaanii

##### Revision
Origin: d9f05eb44f958814783b33f5e725a88de2ce56cb
Pull Request: fbb326ce8565e5dc4bd9dc65d37dca3a94cac49d
Server: a1f8f0c0a902ff188116e56b2f95f1572f222a74

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: f672f018d98fbc3542ada38d6260f37d4c50d0e3
Pull Request: fbb326ce8565e5dc4bd9dc65d37dca3a94cac49d
Server: 0f2e13d46370ed4b71632488688e40bdd3acef2e

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 244e28c96322ec39d06af2ab8d05ce6051299714
Pull Request: fbb326ce8565e5dc4bd9dc65d37dca3a94cac49d
Server: b22fb77831c1f2dbc2222fb125416ba2220e64c4

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 244e28c96322ec39d06af2ab8d05ce6051299714
Pull Request: fbb326ce8565e5dc4bd9dc65d37dca3a94cac49d
Server: 08424fe2de96d50e0d4e6739f9184a5fd165907b

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by Starfirejordan** [comment]
image
this is horrible, This is more then awful

**Comment by ivanmixo** [comment]
Elaborate

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 3398322f1f506d5ac8ae36ca492d3fb015506b02
Pull Request: fbb326ce8565e5dc4bd9dc65d37dca3a94cac49d
Server: 8a3c8b025777ba377bb061b61a5c7ec23f61e9af

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Review by RipGrayson — APPROVED** [review]

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 97bb57b1283bcd96910a866f9b257d4422f807e6
Pull Request: fbb326ce8565e5dc4bd9dc65d37dca3a94cac49d
Server: 55af5738f09e4f32af093c8b6b6aba41f6390460

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Pull request merged**
