### PR TITLE
Removes the ability to build cades on tadpoles, adds a new mapping helper and flag

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Adds a new flag, NO_CONSTRUCTION, for areas. This prevents building things like cades, wires, and using foam wires in areas with this flag. Adds a mapping helper for injecting this flag into areas. Uses the new flag on the tadpole areas. Also removes all existing cades on current tad models.
## Why It's Good For The Game
Was mentioned that after the apc got in, the tad should receive some nerfs to make it less of a mobile fob, and more of a transport unit for marines. This will hopefully reduce the tad's fobiness, and make it more for transporting marines between the ship and groundside.
## Changelog
:cl:
add: Added NO_CONSTRUCTION flag to use for areas and a mapping helper for said flag.
del: Removed cades from current tadpole models
balance: Tadpoles can no longer have cades or razorwire built on them
/:cl:

### CODE REVIEW

**Review by Lumipharon — CHANGES_REQUESTED** [review]
Unless I'm missing something, I see nothing stopping you from just directly building a cade in the tad, this is just stopping you from moving ones in and anchoring them.

Also why are you making a mapping helper instead of just directly adding the flag to the tad area?

**Comment by Wisemonster** [comment]
I was asked to make and use a helper instead of editing the area itself by Grayson. Also, from what I understand cades made from sheets being able to bypass construction restrictions is a bug, cause it currently works with the alamo as well.

**Comment by Wisemonster** [comment]
Ok, made it so cade construction actually checks for area, so you can't build/anchor on the tad.

**Comment by Coastfront** [comment]
In light of a sunrise; It is foolish to pray for each candle to fall still.

This will not "Reduce the tads fobiness" this will reduce the number of TO players due to killing practically any reason to bring the tadpole.
1. "Using it to transport marines from groundside & to the ship, and vice versa"
A path wound, made from more brambles than soil will never once bear a footstep next to one clear.
Typically, the (very short) list of reasons why marines would leave groundside to go to shipside;
- Gregnant
- "Oh my god all of my bones are broken"
- "Oh my god both of my legs are missing"
If there is a synth doing groundside surgery; The major reasons to go shipside neigh cease to exist if you are near him.
Otherwise; These reasons are rare enough to never have enough actual marine traffick going to and fro to warrant wanting to take the tadpole over simplly medevaccing (Which, all of these 3 are the REASON why medevaccing exists.) and then podding back down.
Both of which; are faster than the tadpole.
And now, 2.
"Also removes all existing cades on current tad models."
And replaces them with... What?
Are you genuinely saying that now the tadpole gets its shutters and fuckall else? Even a crate has nails, a satchel its drawstring; Even something made as transport bare minimum needs an actually decent way to remain "shut" beyond turning itself into free cover for xenos.
If you want to make a pr to remove the tadpole; Stop being a fucking coward and actually make it a removal PR, without playing charades through it.
This will literally just guarantee that absolutely-fucking-no-one will ever touch the tadpole again, due to it now just being glorified xenomorph cover if they catch up to it.

Otherwise; If you simply massively-over-shot any reasonable change and jump to this, for making the tadpole less of a mobile FOB I'd reccomend trying:
Disabling its ability to bring extra turrets & removing its turret mounts.
Actually adding a reason to the videogame to want to protect the FOB beyond FOBcamping when the marines start losing to discourage just loading every single emplacement onto the tad & calling it a day.
Pulling a weed by turning every measure of soil in its garden serves only to leave such bare; There are better things to try before immediately reaching for killing the tadpole & soft removing it from the game.

**Comment by Wisemonster** [comment]
> Not a coder here,
> 
> If this PR gets merged, can marines subvert this via deployable cades and put these on the tadpole?

Currently, yes, though this also applies to the alamo, so if I were to change them to not be deployable on tad, I'd also want to prevent them from being deployable on the alamo, which is a bit of scope creep.

**Comment by Wisemonster** [comment]
As an additional note, this pr is meant to me merged with #15694

**Review by RipGrayson — CHANGES_REQUESTED** [review]
So I talked to Lumi, I agreed with him that it would probably be simpler to flip the flag when it comes to the tadpole area instead of doing 6 map edits. You can keep the helper though, it will probably be useful later.

**Comment by Wisemonster** [comment]
Alright, removed the helpers on the tads and just set the flag on the tad areas instead.

**Comment by iforgotmeword** [comment]
just to be clear if this gets added this will kill any fun that tad had out-right
tad has been nerfed repeatedly (with good reason)
however this is about 6 steps jump from: nerf to landing in buildings to whatever this is 

what is this even intended to do?
because it fixes NONE of the problems your pointed out "mobile fob"
if the problem is how good it is at holding ground YOU DIDN'T FIX IT

like you said tad is a "mobile FOB" know what makes fob so good?
multiplying the power of marines
tad is that: multiplying the power of marines around it and you did nothing to change that 
because the support DOESN'T COME FROM THE CADES
it's from the safely of IFF sentries and MGs
("so this change doesn't matter then" - yes, but TO can just build cades outside of tad so you just made QOL worse is all...)

(here is a idea: make tad only able to land near some kind of beacon make it so APC is good for pushs tad for hunkering down)

- TO main

**Review by Lumipharon — APPROVED** [review]

**Comment by Helg2** [comment]
So tad basically will be one-time transport, because you won't be able to repair any broken barricades.
If someone needs just a transport they use alamo/pod/medevac.
With such changes you could as well just remove the tad from the game, as it won't be worth the trouble to defend or drive it.

**Comment by SimplySmiley123** [comment]
I don't think this is gonna accomplish anything but soft remove the Tadpole leaving a hole in it's place that APC is genuinely not gonna fill with how jank both it and the tank are to move around (let alone transport anything without giving both the crew and the marines an aunerysm). With FOB still rotting away in the corner anyway because of how easy it is for xenomorphs to siege an FOB.

**Comment by Arturlang** [comment]
Might be better to give the TAD some snowflakey cade-ish things that can always be repaired at the cost of metal and don't completely get destroyed, however the main issue with the TAD is that it can have a lot of sentries and has a deployable machinegun, not the cades themselves, and marines are not blocked from stacking turrets closeby, but xenos are, which is odd by itself.

**Comment by coldironwarrior** [comment]
> Might be better to give the TAD some snowflakey cade-ish things that can always be repaired at the cost of metal and don't completely get destroyed, however the main issue with the TAD is that it can have a lot of sentries and has a deployable machinegun, not the cades themselves, and marines are not blocked from stacking turrets closeby, but xenos are, which is odd by itself.

yea, i have to agree with this, cade-less totally is ??? but i'd be fine with limited cades that you start with and have to give some upkeep to, otherwise you lose them.

sentries need to be taken off tad, yeh. there's so much specialty stuff that it gets into here though, i'd honestly just rather see tad removed, i dont think it'll be doing much in a round without cades; and without sentries + with cades, it just sort of becomes APC 2

**Comment by SimplySmiley123** [comment]
> > Might be better to give the TAD some snowflakey cade-ish things that can always be repaired at the cost of metal and don't completely get destroyed, however the main issue with the TAD is that it can have a lot of sentries and has a deployable machinegun, not the cades themselves, and marines are not blocked from stacking turrets closeby, but xenos are, which is odd by itself.
> 
> yea, i have to agree with this, cade-less totally is ??? but i'd be fine with limited cades that you start with and have to give some upkeep to, otherwise you lose them.
> 
> sentries need to be taken off tad, yeh. there's so much specialty stuff that it gets into here though, i'd honestly just rather see tad removed, i dont think it'll be doing much in a round without cades; and without sentries + with cades, it just sort of becomes APC 2

And then what's left in it's place?
At the moment it is a necessity due to all the other means of transporting supplies from the ship to the frontline, then moving with that frontline being, in all honesty, _fucking horrible._

**Comment by hivemuscle** [comment]
what the fuck is this pr
i can't even call it xope, it just, idk, fucking insane
go further and disallow marines to build at all: fuck TO, fuck engis, millions must unga silo rush

but you are right at something - tad must be reworked, but not in such way

**Comment by FosterGrime-Heymynameslouie** [comment]
woudlnt turning tadpole into an apc where it has its own interior but you cant place cades on it be alot better in terms of everything?

**Comment by Victor239** [comment]
This doesn't stop cades being dragged onto the tadpole https://github.com/tgstation/TerraGov-Marine-Corps/issues/15746

**Comment by Wisemonster** [comment]
> This doesn't stop cades being dragged onto the tadpole #15746

Not sure how to prevent this outside of destroying the cades when the tad lifts off, or having an invisible barrier prevent the cades from going onto the tad. You sure these were un-anchored and not made through the crafting menu?

**Comment by Victor239** [comment]
@Wisemonster not sure how it was done exactly tbh

**Comment by iforgotmeword** [comment]
ok just tried this out - this killed tad
tad doesn't have a role any more so yea i don't know what to say because it sucks 

please just remove tad just put it down
i don't want to see my tad being a senile old man

**Comment by Redrover1760** [comment]
Tad cades are not scary.

A sitting duck Tad is just a target for boilers. You are removing xeno content from the game by getting rid of the ability to siege tad.

Transport Officer is a ton of fun but its not even remotely a free win. This PR is dumb. Make FOB useful again please.

**Comment by SimplySmiley123** [comment]
> Tad cades are not scary.
> 
> A sitting duck Tad is just a target for boilers. You are removing xeno content from the game by getting rid of the ability to siege tad.
> 
> Transport Officer is a ton of fun but its not even remotely a free win. This PR is dumb. Make FOB useful again please. Remove supply beacons, remove the ability to put machine guns on tad. I dunno.

The problems with FOB are that xenos have an _extremely_ easy time sieging FOBs, to the point a single xeno can break through, two if there's any more resistance then stationary turrets and a stray marine or two (there's not enough mannpower on the marine side to go out and not get wiped easily by xenos _and_ defend an FOB without it getting wiped by xenos with barely any effort), it being tedious as fuck to use an FOB as a supply point if it _isn't_ moving alongside the frontline (read: isn't the tadpole) as well as dangerous as fuck (as xenos have free reign over the map and can gank anyone that would go between the FOB and the frontline for easy kills) for so little benefit that you could just drag a crate with whatever supplies you need with you since the start of a round and do better.
Only ungas that ever care about FOB existing and surviving for longer then 5 minutes after marines get away from the FOB, are arty enjoyers.

Maybe forcing supply beacons off the tad could make it more interesting, make it so they gotta build out a bit to be a safe enough req supplies beacon, but outright removing beacons wouldn't do any good.

**Comment by Admiral-Gigaton** [comment]
to fix the DOGSHIT idea of putting a fucking bullet through the TAD's spine and crippling it for life, you could (somehow) add a player count lock to it, or simply buffing the TAD shutters in turn so that its actually used still (make them able to be repaired, but not replaced?)

in the current state, players either lockcade the TAD, or just dont use it (the latter being done most commonly)

**Comment by lbnesquik** [comment]
At the very least, tadpole should be able to land anywhere if this happen. And maybe you could just remove sentries instead of cades.

**Comment by Wisemonster** [comment]
Alright, made a separate pr that let's tad land in more areas.

**Comment by SimplySmiley123** [comment]
> this is most likely going to be my last comment (not like anyone cares) but just a idea i had: TAD should no longer able to land and it's and should be replaced with a Rappel system (reusable drop pods) a 5X5 elevator (evacs and transporting APCs and Tanks - should act like to how tad work with this TM) drop shoots for crates (ammo (no guns or req stuff) can be printed with "matter" that only be refilled by req) as well CAS should be moved to tad - gives a reason to land back on the ship and to pick up more marines
> 
> Rappel system](#11636)

Zeus drop pods exist, why would anyone use the rappel in this case.

**Comment by iforgotmeword** [comment]
> 
> Zeus drop pods exist, why would anyone use the rappel in this case.

- No more droppod FF
- TO can tell you what your going down into
- You don’t waste droppods
- You go down with other marines 
- Cooler (drop pods are only cooler when it’s a iron rain)
- Not as loud
- Technically faster zipping down TAD compared to dropping from the ship 
- you can land with APC/TANK if elevator is added
- CAS

**Comment by Fawcksy** [comment]
ah sure was a nice break i had from TGMC I wonder what theyre doing with the bala-

**Comment by Barnet2** [comment]
I absolutely hate Tadpole as a concept as a forewarning, but I don't think this is it. Seeing TO's refuse to play is funny and all, but we are too deep in Tadpole being vital to just rip it out -- APC did not replace it despite expectations. I think you'll have to find otherwise to de-tangle Tadpole from the gameloop instead of making it a liability to bring down outside of a shipside evac.

**Comment by lbnesquik** [comment]
> Alright, made a separate pr that let's tad land in more areas.

Nice, that got instantly closed.

**Comment by zzurge** [comment]
Terrible idea

**Comment by RipGrayson** [comment]
I largely concur with Barnet here. Tad is buried too deep for a soft removal like this PR does. I think it would be *healthier* if tad was gone, but you'll have to figure out a replacement since everything has been built around the tad existing (which this PR doesn't do).

**Comment by SimplySmiley123** [comment]
> I largely concur with Barnet here. Tad is buried too deep for a soft removal like this PR does. I think it would be _healthier_ if tad was gone, but you'll have to figure out a replacement since everything has been built around the tad existing (which this PR doesn't do).

First there needs to be changes that would allow the complete removal, otherwise you just leave a big gaping hole with nothing in it's place.

**Comment by Looking4bros** [comment]
I would be convinced that removal of the Tad is compensated by the APC/tank/land vehicle if they gibbed more often. It's hard to replace watching someone/being gibbed by a Tad landing with a MD and a surgical table.

**Comment by Gregormack** [comment]
I don't know who decided that this is a good idea. It's stupid.

**Comment by regieKingH** [comment]
still a bad idea!

**Pull request merged**
