### PR TITLE
Revert "Grav crush does less damage to mobs"

### PR DESCRIPTION
**Pull request by Lefunny**
## About The Pull Request
Revert king crusher to its forgotten state

King grav crusher got itself being miss nerfed as it was supposed to go instead of a timelock PR with got mergeded togheter with the nerf

## Why It's Good For The Game

King is in a horrible place, it got no skills to provide damage, and no way to get close to a marine without tanking several shots, this PR aims in making it more of a threat to marines and a punishment in order of having a push wipe, giving king its old damage, the 3x3 attack inst hard to dodge so its also fair having a good amount of damage.

## Changelog
:cl:

balance: Buff King grav Crush, reverting an old pr

/:cl:

### CODE REVIEW

**Comment by Luxyboo** [comment]
mmmmmm kill orange marines mmm knock full health marine to orange mmmmm

**Comment by Lefunny** [comment]
> mmmmmm kill orange marines mmm knock full health marine to orange mmmmm

its an 3x3 aoe attack with the king needs sight in order to start, the attack itself got some quite big cooldown and cast time, a marine can also hear the sound and the tiles where it is affecting, they can dodge it.

**Comment by Derrick2Electricboogaloo** [comment]
Yeah no, it is for sieging not crowd control, it DID fine at sieging until primos came along.

**Comment by Lefunny** [comment]
> Yeah no, it is for sieging not crowd control, it DID fine at sieging until primos came along.

not even close of worth as a silo spam or spawn spam with indeed inst funny for marines. King got literal only one skill, lets at least make it good, also again its a 3x3 aoe area, not hard to avoid, not staying enough to be a crowd control

**Comment by EvilMelonTheSecond** [comment]
Buffing the king with the old grav crush that broke bones of full health marines and killed those below that isn't the way to make it interesting. An overtuned ability will flip the problem and make it lose the niche of a FOB breaker.

King should probably get removed and forgotten like the marine tank it got released with. It is from a time where FOBhug stalemates and shrike running around the map would delay the game for hours, we no longer have that problem.

**Comment by novaepee** [comment]
> Buffing the king with the old grav crush that broke bones of full health marines and killed those below that isn't the way to make it interesting. An overtuned ability will flip the problem and make it lose the niche of a FOB breaker.
> 
> King should probably get removed and forgotten like the marine tank it got released with. It is from a time where FOBhug stalemates and shrike running around the map would delay the game for hours, we no longer have that problem.

Tivi recommends reworking king. It is not a stalemate breaker anymore.

image

**Comment by Lefunny** [comment]
Making king stronger as a combat caste as we dont need a stalemate breaker, expensive but powerfull sounds good to me, if you really cant dodge the 3x3 Block just use a b18

**Comment by Lefunny** [comment]
> 

This is wrong and took out of place

**Comment by Lefunny** [comment]
> > Buffing the king with the old grav crush that broke bones of full health marines and killed those below that isn't the way to make it interesting. An overtuned ability will flip the problem and make it lose the niche of a FOB breaker.
> > King should probably get removed and forgotten like the marine tank it got released with. It is from a time where FOBhug stalemates and shrike running around the map would delay the game for hours, we no longer have that problem.
> 
> Rework king. It is not a stalemate breaker anymore.
> 
> image

This is wrong and out of place

**Comment by Lefunny** [comment]
> Buffing the king with the old grav crush that broke bones of full health marines and killed those below that isn't the way to make it interesting. An overtuned ability will flip the problem and make it lose the niche of a FOB breaker.
> 
> King should probably get removed and forgotten like the marine tank it got released with. It is from a time where FOBhug stalemates and shrike running around the map would delay the game for hours, we no longer have that problem.

Xenos already got no content, removing it is just straight up bad, being unable to dodge the 3x3 atack is a skill issue tbh

**Comment by BraveMole** [comment]
King no longer fits the game, making him op doesnt fix much

**Comment by hyper2snyper** [comment]
brave you get to close shit when you come back

*please come back*

**Comment by TiviPlus** [comment]
Hes maintainer hes just larping as not being one

**Pull request closed without merging**
