### PR TITLE
Removes the MK88 Mod 4 Combat Pistol from standard vendors and map spawns

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title. ERTs and HvH loadouts will still get it, of course.

## Why It's Good For The Game
This is option 1 of two PRs I intend to put out for the 88M4 (see: #13816). This thing is allegedly meant to be an ERT-only sidearm that somehow became common access. It currently is hands down one of the best weapons in the game, and xenos aren't having a fun time fighting it in its current state... if they even get the chance to, considering how fast this kills.

## Changelog
:cl: Lewdcifer
del: MK88 Mod 4 Combat Pistol is no longer obtainable outside of ERTs and HvH loadouts.
/:cl:

### CODE REVIEW

**Comment by Barnet2** [comment]
Agreed that it should be where the AP guns are, in ERT loadouts. As discussed in dev gen a different magazine for marines is possible, but I do like this option better. +1

**Comment by ivanmixo** [comment]
Heavily disagree with this. The reasoning of "its meant to be an ERT weapon" is just not true and it being strong doesn't mean it should be snapped out of the vendor, either.

**Comment by Lumipharon** [comment]
I don't actually care that much if this is removed or not, but the gun has been an ert gun since CM days, with only a very small number available to marines. It was only made more accessible in 2020.

**Comment by FIXTHERADBOXPLEASE** [comment]
Aktually, it wasn't an ERT gun, it was the Pilot Officer's gun.

**Comment by Al-1ce** [comment]
>This thing is allegedly meant to be an ERT-only sidearm that somehow became common access


Because something a developer from 3 years ago alluded to must be written in stone.

Here's the issue I see:

Sidearms aren't really _used_ as sidearms on this server. You have far more people with an entire loadout dedicated to revolvers than people using them in a webbing/pouch. People go for the MK88 because the other pistols suck, plain-and-simple.

The only thing this PR will change is add consistency so *all* of the pistols are hot-garbage and not worth your time when a rifle or SMG does the same job better.

**Comment by imsxz** [comment]
> > This thing is allegedly meant to be an ERT-only sidearm that somehow became common access
> 
> Because something a developer from 3 years ago alluded to must be written in stone.
> 
> Here's the issue I see:
> 
> Sidearms aren't really _used_ as sidearms on this server. You have far more people with an entire loadout dedicated to revolvers than people using them in a webbing/pouch. People go for the MK88 because the other pistols suck, plain-and-simple.
> 
> The only thing this PR will change is add consistency so that _all_ of the pistols are hot-garbage and not worth your time when a rifle or SMG does the same job but better.

Sidearms will never really have a place so long as mag harness is a thing. Additionally, they’re made further useless because all guns can be equipped instantly. Shotguns will always be the best sidearm because you can pull them out instantly and force the xeno away. Pistols as sidearms simply have no place in the game.

**Comment by chizzy376** [comment]
>  Sidearms will never really have a place 

Alright, let's just remove them entirely then if that's your point.
(Aside from Magnums and matebas since those will always be useful)

**Comment by sockbyte** [comment]
> xenos aren't having a fun time fighting it in its current state

I agree with the nerf PR, but outright removing it from the vendor is overkill.

**Comment by Coastfront** [comment]
> Actually now that I read your response, I don't even know what you were going with.
> 
> > Sidearms will never really have a place so long as mag harness is a thing.
> 
> Magharned guns can still be stolen/broken if deployed.
> 
> > Shotguns will always be the best sidearm
> 
> I don't see shotguns fitting in bags and webbings or even boots.
> 
> > Pistols as sidearms simply have no place in the game.
> 
> They do? The pistols that loadouts do get are a great "get off me" tool, either as this PR's Mod88 or a knockback/knockdown pistol/revolver.

The problem with ever viewing a pistol as a sidearm is the fact that, in almost every situation, it would have been more useful to have just had more primary ammo than to have carried a pistol with you.

For the "Sidearms can make a decent get off me tool", there yet lays a key greater tuned to that lock: Literally just having teammates.
If you're completely alone, and get knocked down and disarmed by most ambush caste's, you're either already basically dead by the time you've stood back up, or they are durable enough to facetank the entire magazine and kill you.
And if you're in a group: Your teammates will have shot them off of you if they aren't already being wiped, and in the case of they're already being wiped: then your sidearm still either doesen't get to finish shooting because you died from the hunter "reconstructing" your body, the woyer wrenching your limbs off, or whatever T3 has decided you're going on the killcount, and your teammates wont be able to help in a wipe.

It's a tool that'd only fit in its pouch if it didn't innately come at the place of something else: Any sidearm that can't fit in your shoe or some other spot you couldn't theoretically put a pouch/more ammo/even debatably throwing knives because they can still inexplicably break basically every obstacle is then space you've likely wasted.
And from personal experience of the few times I've tried to make carrying a "sidearm" gun that is meant to serve as a spare option, were the words "I wish I had more ammo for my primary" made acquainted as dear friends to this memory.

In general, if a pistol can't be used as a decent primary akimbo/etc then unless if it offers actual supportive utility (self pp) it won't be used by anybody who has experience enough to see ammo for a better gun as valuable.

The handles of a tool scarcely used only serve to push its betters to its sides, and thus people would rather just have what is universally good (more ammo) over something that saves you in 10% of situations.

**Comment by ivanmixo** [comment]
See first comment I left

**Pull request closed without merging**
