### PR TITLE
Wraiths Can't Banish While Incorporeal

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

Wraiths Can't Banish While Incorporeal

## Why It's Good For The Game

Wraiths Can't Banish While Incorporeal

## Changelog
:cl:
balance: Wraiths can no longer Banish while incorporeal.
/:cl:

### CODE REVIEW

**Comment by Swagile** [comment]
> 
> 
> Marine cope just like all the attempted armor nerfs. This literally only stops longer cooldown banishing (since you have to wait for phase shift also) of things like HMG, Turrets, Mortar, and more often than not fully occupies the wraith and has little impact more than an annoyance. This will just make them more prone to be kidnapping and hunting miners instead so enjoy that.
> 
> Next they will come for Phase Shift entirely or Blink because the windup and critdrag damage for kidnapping is not enough for them.

good

wraith wasn't designed around current TGMC maps and marines and it shows and if you can't see that then idk what to say bro, you do you

**Comment by Swagile** [comment]
> 
> 
> > wraith wasn't designed around current TGMC maps and marines and it shows and if you can't see that then idk what to say bro, you do you
> 
> Don't get me wrong I am not saying wraiths design is perfect or even good just that I wouldn't be surprised if the salt factor were to in-fact go up instead of down as a result of removing one of the least harmful wraith gimmicks.

oh yeah, there are definitely worse applications of a wraith, like hopping past 2 lines of cades to slash a miner once or twice to break it down, then teleporting out before you can even weld your gun, but thats for a separate topic altogether

**Comment by Surrealaser** [comment]
> Marine cope just like all the attempted armor nerfs. This literally only stops longer cooldown banishing (since you have to wait for phase shift also) of things like HMG, Turrets, Mortar, and more often than not fully occupies the wraith and has little impact more than an annoyance. This will just make them more prone to be kidnapping and hunting miners instead so enjoy that.
> 
> Next they will come for Phase Shift entirely or Blink because the windup and critdrag damage for kidnapping is not enough for them.

I want to be clear that Phase Banishing was actually on my watch list since pretty much the beginning due to it being a risk free (albeit plasma costly) way to utilize Banish, which is pretty much the only reason this PR exists. I decided to keep this mechanic in to see if it would be a problem, and it seems to be according to multiple people. If this isn't the case, I certainly don't mind hearing contrary opinions.

Having said that, I am much less convinced of other grievances to which counterplay exists.

**Comment by ThatGuyFromThatPlace** [comment]
> > oh yeah, there are definitely worse applications of a wraith, like hopping past 2 lines of cades to slash a miner once or twice to break it down, then teleporting out before you can even weld your gun, but thats for a separate topic altogether
> 
> Once miner operators adapt I'm sure we'll see more claymore + concussive cade traps, turrets, and tgas counter measurers until the wraith is dead at which point the thorn, which again was focusing miners and not kidnapping people, is gone if not for the rest of the round at least a good 5-10 minutes before it can respawn.
> 
> IMO the miner strats are getting pretty annoying to deal with for xenos like engis putting walls on all 4 sides (I know someone will cry "but that is because of wraith" and it's irrelevant, gamers going to game with an excuse or not) or blocking a whole side of attack or more to a plat miner with the tadpole.
> 
> I'd totally be in favor of a anti-wraith armor upgrade for miners or something like that to make it easier to thwart the wraith while not stopping it completely as a dedicated tool for the xenos to have against mining, but like you said this is a separate topic altogether probably more suited for #balance.

Traps don't work if the Wraith simply phases or blinks past the traps

**Review by SplinterGP — CHANGES_REQUESTED** [review]
put this check before the ismovableatom iseffect ones

**Comment by Tupinambis** [comment]
I'd rather just remove or rework it entirely but this will at least make it less annoying to deal with.

**Review by SplinterGP — APPROVED** [review]

**Comment by DerrickChamberlain** [comment]
FINALLY PLEASE MERGE AHHHHHHHHHHHHHHHHHHHHHHH

**Pull request merged**
