### PR TITLE
TAT APCR rebalance

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
The TAT's APCR shell will receive the following tweaks:
- Damage reduced from 200 to 100.
- Sundering increased from 65 to 100.

## Why It's Good For The Game
TAT APCR is currently capable of very easily scoring offscreen kills. This is very much NOT fun to deal with, hence the rebalancing. I don't want to nerf it and kick it into the dirt, so I'm pushing it into the full sundering niche while reducing its damage.

## Changelog
:cl: Lewdcifer
balance: TAT damage reduced from 200 to 100, sundering increased from 65 to 100.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Didn't I already severely nerf/fix this?

**Comment by lKiseki** [comment]
> Didn't I already severely nerf/fix this?

Wasn't enough, then.

**Comment by FosterGrime-Heymynameslouie** [comment]
this allows t1 xenos to walk off literally having a tank shell punched through their guts and walk off with sunder damage. even more for t2 and t3 which is the target audience for tat in the first place, maybe 150 damage is a good compromise?

**Comment by Lumipharon** [comment]
> > Didn't I already severely nerf/fix this?
> 
> Wasn't enough, then.

This makes it worse than HE in most cases, considering HE has an explosion plus 90 damage.

**Comment by Al-1ce** [comment]
> this allows t1 xenos to walk off literally having a tank shell punched through their guts and walk off with sunder damage. even more for t2 and t3 which is the target audience for tat in the first place, maybe 150 damage is a good compromise?


I, as well as others, would be in favor of the TAT doing more damage if it wasn't obtainable for completely free at roundstart.

**Comment by Dolth** [comment]
Why not removing the offscreen ability just like SADAR? It's an anti-tank cannon there's no reason it deal as much damage as a sniper rifle.

**Comment by SilencedMP5A5** [comment]
just make the TAT req only lol

**Comment by Weedmaster77** [comment]
Maybe damage lowered to 150 or 160 
Sunder up to 75 or 80 
Seems far to make it still something a T1 will not want to be in line of but not nerf it into the ground.

**Comment by BraveMole** [comment]
No one reviewed that and MJP abstained, so I close

**Pull request closed without merging**
