### PR TITLE
the normal marine vest uses pas vest stats, and normalizes non pas vest stats to pas vest for shipside armor

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
so they inherit pas level stats from the marine armor
also normalizes shipside armor

## Why It's Good For The Game
game consistency

## Changelog
:cl:
fix: shipside armor now has pas vest stats
/:cl:

### CODE REVIEW

**Comment by Sulaboy** [comment]
Sticking the /obj/item/clothing/suit/storage/marine to pas stats might be good for defaulting armors to that standard value for PAS armor as a baseline, but even then new armor is usually assigned an armor value.

Really you’re only snipping 5 melee off some armors, but I feel like command and engineering armors should have that extra 5 as an reward for playing them. It isn’t often you see STs walking around the ship, and command often consists of one FC.

**Comment by TGCMbetcher** [comment]
Move these armors to a job locked vendor or something. I get the issue is marines go and take them but thats just punishing the command and support roles for what marines do. We have items that are job locked, the taser, stun baton, flash. Just add those armors behind a wall too.

**Review by TiviPlus — APPROVED** [review]
As stated the correct solution is to subtype properly but this is fine

**Review by SplinterGP — APPROVED** [review]

**Comment by SplinterGP** [comment]
> Move these armors to a job locked vendor or something. I get the issue is marines go and take them but thats just punishing the command and support roles for what marines do. We have items that are job locked, the taser, stun baton, flash. Just add those armors behind a wall too.

why do shipside jobs even need better armor, they dont fight

**Pull request merged**
