### PR TITLE
Surv armor now has slowdown

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Noone wants to touch survs I guess
If they arent fixed after this just disable them

## Changelog
:cl:
balance: Surv armor now has slowdown
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
Surv armor doenst need slowdown, theyre literally 1 or 2 against 10 to 20 xenos, how are they supposed to run from xenos ?

**Comment by revelation-8468** [comment]
Survs robusting so hard c*ders literally need to nerf them. Quite sad really.

**Comment by Smudged** [comment]
> Surv armor doenst need slowdown, theyre literally 1 or 2 against 10 to 20 xenos, how are they supposed to run from xenos ?

They shouldn't the game is primarily about marines fighting xenos, half the time the survivors aren't 'surviving they're bum rushing silo's or young xenos

**Comment by BeloneX** [comment]
> Survs robusting so hard c*ders literally need to nerf them. Quite sad really.

Can we gitban this guy? He doesn't have any contributions and only makes off-topic/disruptive comments.

**Comment by TiviPlus** [comment]
Not needed anymore

**Pull request closed without merging**
