### PR TITLE
squad/Radio TTS fix

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Fixes a bad runtime. AFAIK squad TTS just doesn't work right now, which is funny because it looks like it didn't work for half of the TM period and just no one said anything.
## Why It's Good For The Game
image
## Changelog
:cl:
fix: fixed squad/radio TTS
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Going to TM this to make sure this really is the problem, since I can't local test.

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
I assume it works?

**Comment by Lumipharon** [comment]
Day 5284, still no tts to actually check this change

**Comment by Lumipharon** [comment]
this is good to merge

**Pull request merged**
