### PR TITLE
Allows DB to take extended barrel and barrel charger

### PR DESCRIPTION
**Pull request by Losenis**
## About The Pull Request
Title

## Why It's Good For The Game
The other shotguns can take them anyway. This'd give the db a proper use other than 4 db juggling at pb range where projectile speed is irrelevant anyway. It also competes with bayonet, actually making it a worse attachment when it comes to PBing.

Potential (non)issues:
"Flechette/slug hitscan": The other shotguns have this and hasn't been a problem.
"DB can fit miniscope": Lacking aim mode it'd turn it into a martini downgrade since it'd just turn into an FF machine. Slugs don't do stagger nor knockdown or anything at range, and flechette being multiple projectiles get hit by damage falloff [number of projectiles] times as hard. Sniper buckshot is funny. What's more, if you're running DB as a scoped gun, wouldn't you be better off going with the SR127 since you don't need to unwield out of the scope every 2 shots and it can take barrel charger too?

Also it'd be hilarious to see marines thinking that last part is viable and causing absurd levels of ff with slugs that go so fast they can't even check who's knocking them over.

## Changelog

:cl:
balance: DB can now take Extended Barrel and Barrel Charger attachments

/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
Why can DB even take a scope? wtf

**Comment by Xsdew** [comment]
The SH-35 and SH-39 have a slower rate of fire when compared to the Double Barrel. With the SH-39 having a damage malus too. EB and BC being attachable to shotguns is a CM legacy and doesnt make much sense as shotguns are CQC weapons.

This change doesn't create a competing  attachment loadout for the DB. It just lets you hit xenos easier as they are moving around in combat, espically for follow up shots with mutliple DBs and a retreating Xeno.

**Comment by Losenis** [comment]
Haven't you seen pit boss juggle agrip T35s?

**Comment by Xsdew** [comment]
> Haven't you seen pit boss juggle agrip T35s?

This PR is about the Double Barrel Shotgun. Which when used with Juggling allows you to fire at least four shotgun shells in rapid succession. Which can allow for shots to land at range (Flechette) , with higher accuracy if given a EB/BC.

The SH-35 is most effective when used normally as in combat you need to both move and shoot.

**Comment by wezsel11** [comment]
> Why can DB even take a scope? wtf

I made that DB pr for scopes more than a year ago. aka, more of a hunting variant and it was before the growth of juggling DB's.

**Comment by Losenis** [comment]
>This PR is about the Double Barrel Shotgun

DB juggling is outside the scope of this pr

**Comment by helper-2** [comment]
But that is double barrel gun, how do you mean to fit single barrel attachment to it?

**Comment by Losenis** [comment]
>how do you mean to fit single barrel attachment to it?

_Very carefully._

**Comment by Lumipharon** [comment]
> But that is double barrel gun, how do you mean to fit single barrel attachment to it? That's doesn't make much sense

Muh immersion.

**Comment by Naaanii** [comment]
> > But that is double barrel gun, how do you mean to fit single barrel attachment to it? That's doesn't make much sense
> 
> Muh immersion.

Time to add a forced check to double add 2 barrel chargers for consistency.

**Comment by Lumipharon** [comment]
Closing due to muh immersion.

**Comment by Losenis** [comment]
sasuga

**Pull request closed without merging**
