### PR TITLE
Introduce a reqtorio valhalla vendor

### PR DESCRIPTION
**Pull request by Delnth**
## About The Pull Request
Brings all the factorio goodness in a compact, hopefully well organized package, in the form of a valhalla vendor. Currently has every factorio machines, the factorio paper guide, conveyor belts and the switch to go with it. Every refill available to req has is available with the only exception being drop pods as I suspect it could be used to deploy valhalla characters on the map. I am not sure. But if it's safe to do so I might add it.
## Why It's Good For The Game
It would allow req enthustiasts to experiment with factory designs in valhalla, check recipes, improve productivity, learn about the intricacies of production, so on and so forth.
## Changelog
:cl: Koenigsegg
add: Added a valhalla reqtorio vendor
add: Added the reqtorio valhalla vendor to the vehicle pit in valhalla
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
This will probably skew round end stats, not that it matters but yeah

**Comment by Delnth** [comment]
> This will probably skew round end stats, not that it matters but yeah

I didn't think about that huh. Sadly my understanding of the dm language is relatively limited so I'm not too sure how I'd go about writing an exception for end of round stats. I could look into it though and attempt to decipher the dark magic behind it.

**Comment by lbnesquik** [comment]
> > This will probably skew round end stats, not that it matters but yeah
> 
> I didn't think about that huh. Sadly my understanding of the dm language is relatively limited so I'm not too sure how I'd go about writing an exception for end of round stats. I could look into it though and attempt to decipher the dark magic behind it.

Round End Stats just take a variable and add +1. You could find where the variable gets incremented for the stats relevant to this PR. And then, add a check. If this is located in Valhalla, or if this is an item flagged as being a Valhalla spawned thing, don't increment it.

**Review by TiviPlus — APPROVED** [review]
Would be scared of people building this at highpop but we'll delete this if it becomes na issue i guess

**Comment by TiviPlus** [comment]
Also yea tweaking the stat to check for if its on the admin z would be good

**Comment by Delnth** [comment]
I looked into it, might have the part of the code that registers specific stuff to display them at round end but really that is beyond what I am capable of, it might be more trouble than it is worth. I can understand code that add lists, items, and such, but the rest is unknown territory.

**Comment by lbnesquik** [comment]
Well, I just looked at round_statistics.dm and there's nothing about reqtorio in there. There's some stats for how many bullets have been shot, but this PR won't affect this much. Green light from me.

**Comment by TiviPlus** [comment]
> I looked into it, might have the part of the code that registers specific stuff to display them at round end but really that is beyond what I am capable of, it might be more trouble than it is worth. I can understand code that add lists, items, and such, but the rest is unknown territory.

/obj/item/factory_part/proc/advance_stage()

you should check if is_gameplay_level is true

before GLOB.round_statistics.req_items_produced[production]++

is called it shouldnt be that hard lmk if you need help

**Pull request merged**
