### PR TITLE
hunter nerf, speed and slash nerf

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
less slash

## Why It's Good For The Game
hunter shouldn't be doing this much damage

## Changelog
:cl:
balance: nerfs hunter slash by 3 points, weed speed from -0.4 to .1 and he's slightly slower off weeds too
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
even more xeno nerfs

**Comment by David-Stormwell** [comment]
Fineish on Paper.
Still think hunter should be reverted to how it was before, problem is before bump slash didn't exist.

**Comment by Naaanii** [comment]
Maybe nerf one slash but nerf movespeed on weeds as well.

**Comment by David-Stormwell** [comment]
> 
> 
> Maybe nerf one slash but nerf movespeed on weeds as well.

No, if you nerf a caste too much it'll just be a dogshit caste no one uses much anymore.
You still want to have it in gameplay and used, just not as OP as it is.

**Comment by TGCMbetcher** [comment]
I honestly believe hunters are in a good spot right now. They cant even 1v1 marines anymore. I fumbled with my slug shotgun for like 7 seconds, it broke my arm, and I still won a duel simply because it you hit it consistently it doesnt matter what youre using it cant take the damage.

**Comment by SilencedMP5A5** [comment]
hunter fine tbh

**Comment by Losenis** [comment]
I'd sooner take a look at what lets it deliver that damage rather than the damage itself, since it's essentially a rouny+. At least it'll alleviate the free hits in stun breaking your arm a bit. WASDing with -1.5 offweeds speed and bumpslash is ridiculous when a player that knows how to use it properly controls it, let alone two or three at the same time.

**Comment by bobmancer343** [comment]
get good

**Comment by Losenis** [comment]
>posted while getting free hits with stun

**Comment by lKiseki** [comment]
Hunter is most definitely not fine. While nerfing the slash damage could be a solution, I personally believe nerfing its move speed would be a good change as well. It goes too fast, even off weeds, and it's very hard to punish a Hunter due to this. A Hunter can also WASD you to death, and other marines _normally_ won't shoot due to fear of committing friendly fire.
In summary, I believe nerfing its general move speed a little would be a good change as well.

**Comment by Naaanii** [comment]
Decent changes.

**Comment by Naaanii** [comment]
Maybe reduce the slash nerfs to 2 instead of 3.

**Review by TiviPlus — APPROVED** [review]

**Comment by Al-1ce** [comment]
>Hunter can also WASD you to death, and other marines _normally_ won't shoot due to fear of committing friendly fire.
This is why aim-mode exists.
> In summary, I believe nerfing its general move speed a little would be a good change as well.
Slowing down what is essentially a slightly better runner in terms of HP makes evolving into Hunter less worth it. I think that reducing the bump-slash damage somehow would be a better fix, since most hunter players rely on that.

**Pull request merged**
