### PR TITLE
Anti-juggling component

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Adds a component to prevent the juggling of weapons to bypass firing rate limitations. Yes this is extremely silly and a mob var could just do the trick but hey ho :)
## Why It's Good For The Game

Juggling bad.
## Changelog
:cl:
balance: Added a component that prevents the juggling of weapons to bypass firing rate limitations
/:cl:

### CODE REVIEW

**Comment by Strayed-Raven** [comment]
Is this gonna affect people that get stunned with low duration stuns from firing again if they fired before the stun?

**Comment by ivanmixo** [comment]
If the stun is somehow shorter than the next time the gun would be able to fire sure

**Comment by Kapu1178** [comment]
This does add non-zero overhead to one of the hotter paths in the game. IS it REALLY worth a component

**Comment by ivanmixo** [comment]
Tivi is fully against a mob var so

**Comment by shelteredfreak** [comment]
Finally... Let it die... Kill juggling... No more... Fire your guns like a normal person.

**Comment by ClosetedSkeletonGH** [comment]
Hero hero hero hero

**Comment by Kapu1178** [comment]
> Tivi is fully against a mob var so

that's kinda cringe, a component is slower and it's never going to be used as a component, since it's just set-and-forget on marines.

**Comment by Strayed-Raven** [comment]
> If the stun is somehow shorter than the next time the gun would be able to fire sure.
> 
> This only cares about the next time the last gun you successfully fired would've been able to shoot again.

I would look into it because synap users exist and King roar and other stuns are at times pretty short.

**Comment by Redrover1760** [comment]
This PR is terrible now that it exists everyone is spamming DB someone please help us

-Xeno main 258

**Review by Lumipharon — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Comment by DorfGuy1** [comment]
Hey uh, so the fix for shotgun juggling was to add in click delay? Why would you do this.

**Pull request merged**
