### PR TITLE
Removes dark frost wall cuttable subtype

### PR DESCRIPTION
**Pull request by blackdav123**
## About The Pull Request
Replaces all instances of standard walls with indestructible and all instances of cuttable walls with standard. Standard is now cuttable.
## Why It's Good For The Game
Having a secret third type of this wall makes it a pain to map when you cant tell what is cuttable or not.
## Changelog
:cl:
code: Standardized dark frost walls with other wall types.
/:cl:

### CODE REVIEW

**Comment by RipGrayson** [comment]
If I recall correctly, there was a period after the new sprites went in where darkfrostwalls didn't have PC resistance and it caused a lot of balance issues. Setting this PR on DNM until I get a handle on those.

**Comment by Arturlang** [comment]
Making any environment wall in general is a huge balance issue as you can just hide the nuke behind a 1 wide tunnel and make it near impossible to stop.

**Comment by blackdav123** [comment]
> Making any environment wall in general is a huge balance issue as you can just hide the nuke behind a 1 wide tunnel and make it near impossible to stop. Mostly because xenos cannot cut the walls themselves.

not really an issue considering the round is usually over once marines have moved the nuke regardless of how they defend it, and that icy caves is the only map that uses a ton of these near the fob.

**Comment by Victor239** [comment]
> not really an issue considering the round is usually over once marines have moved the nuke regardless of how they defend it, and that icy caves is the only map that uses a ton of these near the fob

Why make nuke defence a boring and impossible to lose scenario by allowing these 1 wide tunnels then? That's not fun for either team.

**Pull request merged**
