### PR TITLE
Rifle family has been re-statted, carbine and lmg have been reworked.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
LMG got faster fire rate, better gun stats, higher slowdown to give it more a heavy weapon feel rather than an AR with more magazine size.
AR got more slowdown and lost angled grip as it basically made the carbine irrelevant.
This attempts to make the carbine more relevant by giving it auto fire and making it a faster variant of the AR. And removes its angled grip.

This changes the rifle family to be more unique amongst themselves, rather than the AR just reigning over all of them.
The Carbine now has .2 fire delay and .1 burst delay and full auto. Giving it a fast AR niche but has low overall ammo. Meaning you'll run out fast. (32 vs 50.)
The AR lost the ability to take an A-grip, and gained .1 slowdown because it had .4 before, and the a-grip made it far too fast to wield overall in my opinion. Though I might make a-grip worse in the future or rework it entirely.
LMG has seen the most substantial change. As it goes from .6 to .8 wield delay, fires minorly faster to .18 from .2 (11 bullets in 2 seconds rather than 10.) giving it an edge in the suppressive fire, and makes it feel like a heavy weapon than anything else. I also gave it baseline accuracy and a bit less scatter to make it good without attachments.

## Why It's Good For The Game
Hopefully makes the rifle family more unique and sees people run something other than just the AR amongst them.

## Changelog
:cl:
balance: The rifle family has seen substantial changes. The LMG has more slowdown, but fires minorly faster over longer periods of time (.2 vs .18) and has better base stats, also wields faster than before. The AR lost a-grip and has .1 more slowdown when wielded. The Carbine now fires at .1 burst delay and has .2 fire delay and gained full auto.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -14. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by XSlayer300** [comment]
Can the T-18's description be changed to represent this change (by removing the lack of automatic fire)?

**Comment by Pariah919** [comment]
I feel like this is ready to be merged.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-19). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
