### PR TITLE
Custom hotkeys

### PR DESCRIPTION
**Pull request by psykzz**
Definitely needs #1540 to go first, however we should prefer #1558 

## About The Pull Request

Allow players to set custom hotkeys for actions in game preferences

## Changelog
:cl:
add: Adds the ability to change your keybindings in settings.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
This is incredibly lovely.
@ninjanomnom had things to say about Yog's implementation, so they might want to have a say here as well.

**Comment by psykzz** [comment]
I tried to look around for a any other implementation for inspiration and didn't find one so this is how i would approach it.

**Comment by Rohesie** [comment]
Yogstation is the only one I know has implemented it:
https://github.com/yogstation13/Yogstation-TG/
But as said, it has issues.

**Comment by ninjanomnom** [comment]
If this is based on yog's just don't even bother. Th method they use is awful and if you want to implement this you need to write most of it from scratch just making use of some of the core framework from the overhaul on tg.

Just port that first then work on custom controls

**Comment by Rohesie** [comment]
That is happening here, @ninjanomnom : https://github.com/tgstation/TerraGov-Marine-Corps/pull/1540

This PR is built on top of it, just a draft until that other one gets merged.

**Comment by ninjanomnom** [comment]
Still, don't use yog's as your inspiration. Using it makes it a massive pain to be able to improve it later because of how entangled it is with all the other code, and it definitely needs improvements.

**Comment by psykzz** [comment]
As a note, i haven't used anything as inspiration this is just me building ontop of `SSinput`

**Comment by psykzz** [comment]
Closed for #1602

**Pull request closed without merging**
