### PR TITLE
Adds in a new crash shuttle for 25+ pop

### PR DESCRIPTION
**Pull request by mrhugo13**
## About The Pull Request
Adds in the new Bigbury shuttle for crash, is only used when there are 25 or more players.
dreammaker_2020-08-09_16-28-55
Also adds in a bunch of docking ports for the shuttle to crash on, and moves around some.
Makes SL's able to access the canterbury cockpit via requiring you needing only access to `ACCESS_MARINE_DROPSHIP`

## Why It's Good For The Game
Currently if you try to play crash around 25 or more players it becomes really painful due to things like nobody being able to fit into the PFC equipping room which usually causes a brawl there.

This fixes that by making a crash ship able ment for higher pops if the situation ever were to happen, generally improving the fun you can have on crash with 25+ players.

## Changelog
:cl: Vondiech
add: The TGMC has shipped out blueprints for a ship ment for crash operations made to have a higher capacity for more marines.
tweak: The TGMC has, alongside with shipping out the blueprints, decided that Marine Squad Leaders should have access to the crash operation cockpits aswell
/:cl:

### CODE REVIEW

**Comment by mrhugo13** [comment]
Might have to fix the merge conflict tommorow, due to me being especially bust today. Seems just to be one of the maps messing with me.

**Comment by mrhugo13** [comment]
> 
> 
> Very nice, though I have some suggestions mapping wise as prep was a clusterfuck again:
> -Cryo can be moved to the relatively empty medbay to free up space for another set of prep vendors
> -Marines were having difficulty getting to the back vendors far away from the door, this might be alleviated if you move some stuff up a tile to create a corridor
> image

Changes suggested/requested implemented as wished.

**Comment by TiviPlus** [comment]
image
This area on LO is very marinesided as it only has 1 easily defensible entrance on the topleft, please fix

also probably unrelated to this PR but it appears bigbury (and probably canterbury) count as being an open area

**Comment by mrhugo13** [comment]
> 
> 
> image
> This area on LO is very marinesided as it only has 1 easily defensible entrance on the topleft, please fix
> 
> also probably unrelated to this PR but it appears bigbury (and probably canterbury) count as being an open area

Moved it around, should hopefully be fixed now.

**Comment by psykzz** [comment]
Could you add a few more pinpointers to the map?
Cant has 2 normally for lowpop, and i think this only had 1?

It may be worth adding them to a vendor separately.

**Comment by mrhugo13** [comment]
> 
> 
> Could you add a few more pinpointers to the map?
> Cant has 2 normally for lowpop, and i think this only had 1?
> 
> It may be worth adding them to a vendor separately.

It has 2
dreammaker_2020-08-09_16-22-24


However i get what you're saying so i'll add in 2 more if that's more comfortable for you.

**Pull request merged**
