### PR TITLE
Cooking Supplies 2.0

### PR DESCRIPTION
**Pull request by KaleRobe**
## About The Pull Request

Allows for players to order food ingredients from req.

## Why It's Good For The Game

Adds more roleplay opportunities allowing players to develop their culinary skills.

## Changelog
:cl:
expansion: Added cheese, eggs, flour, meat, milk, pepper, potatoes, salt, soymilk, and sugar to the Req list 
/:cl:

### CODE REVIEW

**Comment by KaleRobe** [comment]
Now with the proper file and commas in the new lists.

**Review by BraveMole — CHANGES_REQUESTED** [review]
I don't know how you're doing your prs, but everytime your commits are all fucked. 

Like here, you are readding the entirety of supplypacks.dm, adding 1773 new lines.

Please go look at the tutorial how to contribute : https://tgstation13.org/wiki/TGMC:Guide_to_contributing

**Comment by KaleRobe** [comment]
> I don't know how you're doing your prs, but everytime your commits are all fucked.
> 
> Like here, you are readding the entirety of supplypacks.dm, adding 1773 new lines.
> 
> Please go look at the tutorial how to contribute : https://tgstation13.org/wiki/TGMC:Guide_to_contributing

So I shouldn't have been solely using dream maker?

**Comment by AnCopper** [comment]
> > I don't know how you're doing your prs, but everytime your commits are all fucked.
> > Like here, you are readding the entirety of supplypacks.dm, adding 1773 new lines.
> > Please go look at the tutorial how to contribute : https://tgstation13.org/wiki/TGMC:Guide_to_contributing
> 
> So I shouldn't have been solely using dream maker?

Fuck no, NEVER use dream maker, use VScode or something.

https://code.visualstudio.com

**Pull request closed without merging**
