### PR TITLE
Lv rework

### PR DESCRIPTION
**Pull request by Hathkar**
## About The Pull Request

RedesignsLZ2 almost completely. Moved robotics dome, added atmospherics dome. Changed old atmospherics area's layout and removed the APC.
Redesigned the east side of LZ1.
Moved a few phoron drill locations to account for LZ2 changes.
Added a couple new survivor spawn spots.
Removed a large portion of the northern caves that rarely, if ever, see use.
Moved cave areas to fit with the remaining caves.
Added a bridge north of LZ2 across the river.
Redid some pipes and wiring in the colony.
Changes in jungle to the south of LZ1.
Walls in north LZ.
Map resized, removing large swathes of empty space.

## Why It's Good For The Game

Landing Zone 2 in LV624 is widely regarded as a complete joke. This PR aims to fix that.
A new atmospherics dome fills in some of the empty space in the jungle.
The far north caves contributed nothing meaningful to the map.
Landing zones are a bit less siege-able, to discourage early xeno camping.

## Changelog
:cl:
add: A new atmospherics dome for LV624
add: Completely redone LZ2 LV624
add: New survivor spawn points LV624
add: New bridge north of LZ 2 LV624
del: Removed the far north caves LV624
tweak: Cable and pipe placement LV624
tweak: Jungle south of LZ1 LV624 
balance: LZ1 and LZ2 walls LV624
/:cl:

Previews:
LZ1
https://i.imgur.com/KDFAjgX.jpg
LZ2
https://i.imgur.com/pnuZE30.jpeg
North Caves
https://i.imgur.com/uwodQdi.png

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Hughgent** [comment]
Considering you've removed a large portion of the map, can you also please 'resize' the map to take this into consideration? 

This might impact computational performance.

**Comment by Hathkar** [comment]
I did that, but forgot to add that to the changelog.

**Comment by psykzz** [comment]
Found some space tiles here 
image

**Comment by Hathkar** [comment]
> 
> 
> Found some space tiles here
> image

Thanks, I patched those holes up.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-3). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
