### PR TITLE
Make ryetalyn accessible

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Welcome the pill bottle, ryetalyn!

Do you want to not rush chem lab just to make ryetalyn? Now you don't need to with this PR! The brother of hypervene, ryetalyn is for any corpsman that want to REALLY purge toxin!

You can find it in your local MarineMed or lifesaver belt!

## Why It's Good For The Game

Seriously, why wasn't this easily obtainable for marines? You can either make this from a CRAZY amount of steps or raid the toxin first aid; yeah, of all the places in the world, toxin first aid has this in stock.

I know that Tivi has #9591 up, but I know that people really like to have ryetalyn in their pocket.

## Changelog
:cl:
add: ryetalyn pill bottle, pink and cute; you can find this at your local lifesaver belt or MarineMed 
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
It's a really powerful chem, I don't think making this a vendor item is a good idea.

**Comment by EvilMelonTheSecond** [comment]
> It's a really powerful chem, I don't think making this a vendor item is a good idea.

Chems being limited by giving them zero stock on roundstart is bad design and does not stop powergamers from accessing it. If the chem can be made with the chem dispenser then it should be available to all.

**Comment by OpsCoretango** [comment]
I rush the chem but i have it in recipe, so i dont feel any challenge to just make pills or bottle for vali

**Comment by InterroLouis** [comment]
If anything I would say to remove one of the combat injectors from the lifesaver belt instead, medics need those advanced kits.

**Comment by Lumipharon** [comment]
> > It's a really powerful chem, I don't think making this a vendor item is a good idea.
> 
> Chems being limited by giving them zero stock on roundstart is bad design and does not stop powergamers from accessing it. If the chem can be made with the chem dispenser then it should be available to all.

Time is a comodity, so it requires a degree of effort. There is a significant difference between things being readily available at hand, and things being available if you can be assed for them.
Especially with chem, you can make all sorts of funky powerful mixtures and shit if you can be assed, and it says something that only a relatively small number of people bother to use chem every round.

Also as Interro said, if you are going to replace anything, make it the combat injectors.

**Comment by Derrick2Electricboogaloo** [comment]
Ryetayln is incredibly easy to make, no need to make it more accessible, it already is. I will release a video on how to make 16 pills easy.

**Comment by Derrick2Electricboogaloo** [comment]
Personally I think we need to remove the damn timer delay on chem dispensers

**Comment by OpsCoretango** [comment]
> Personally I think we need to remove the damn timer delay on chem dispensers

Skill issue, you a Marine, not Medical Crew

**Pull request closed without merging**
