### PR TITLE
Psychic Shield: Targetted Reflection (Warlock Primo)

### PR DESCRIPTION
**Pull request by Runian**
## About The Pull Request
Warlock's Psychic Shield can be re-selected to switch to an alternative shield if they are Primordial.

The alternative shield halves the shield's health from 650 to 325.
The alternative shield can be detonated early to direct reflected projectiles toward a target in front of them (135 degrees).

Example of Warlock reflecting a Recoilless Rifle toward a Moth:
awooga

Example of Warlock's shield breaking too early because of the reduced health:
awooga1

Comparison to Warlock's normal shield health:
awooga2

## Why It's Good For The Game
Warlock is great at doing damage without having to risk much. Their abilities don't really need line of sight to their target as they do area-of-effect damage, though direct hits do more damage. In some cases, Warlock's Psychic Lance which is their current primo ability is arguably worse than their base Psychic Blast as it lacks the area-of-effect damage, bad against Tanks, and can't take advantage of the fact that it can go off-screen. In my opinion, all it is great for is abusing certain map locations that use shutters, shooting over cades, or just shooting from the edge of the screen. Since Psychic Lance leans more toward direct confrontation than its counter part, I thought: why not add something for Psychic Shield where they can risk their life for more damage?

## Changelog
:cl:
add: Primordial Warlock can use their psychic shield to reflect projectiles in exchange for reduced shield health.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Cool primo idea, but warlock already has an issue of being extremely primo dependant, after several nerfs to base abilities.
So this will be a pretty funny reinforcement to that.

**Comment by Lauwma** [comment]
So basically auto aim ?

**Comment by Runian** [comment]
> Cool primo idea, but warlock already has an issue of being extremely primo dependant, after several nerfs to base abilities. So this will be a pretty funny reinforcement to that.

You cool with this if I made it base kit?

**Comment by Helg2** [comment]
What concerns me is that it's nowhere mentioned anything about either shield health, or lowered shield health, and thus newbies won't have even an idea how exactly the shield health works, and why it suddenly collapses.

**Comment by Lumipharon** [comment]
> > Cool primo idea, but warlock already has an issue of being extremely primo dependant, after several nerfs to base abilities. So this will be a pretty funny reinforcement to that.
> 
> You cool if I made it base kit?

Kuro problem.

Although I also note that the reduced shield hp means reflecting rockets is almost guaranteed suicide, since only a few bullets + rocket will break it, and I think ap sadar 1 hit breaks it?

**Comment by iforgotmeword** [comment]
> Although I also note that the reduced shield hp means reflecting rockets is almost guaranteed suicide, since only a few bullets + rocket will break it, and I think ap sadar 1 hit breaks it?

i say it pretty fair seeing how fast a warlock can reflect it (im pretty sure reflect it has no cast time)

**Comment by Arturlang** [comment]
Makes this the real primo and just remove blast, it's useless without it's ability to knock around abilities

**Review by Kuro020 — CHANGES_REQUESTED** [review]
you should prolly recolor it so it becomes clear what shield the warlock is using, aside from that lgtm

**Comment by Runian** [comment]
> you should prolly recolor it so it becomes clear what shield the warlock is using, aside from that lgtm

image

**Review by TiviPlus — APPROVED** [review]
very simple love it

**Pull request merged**
