### PR TITLE
you can now only vote combat patrol

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
not liking hvx

## Why It's Good For The Game
i like combat patrol so this should be merged

## Changelog
:cl:
qol:  you can now only vote combat patrol
config:  you can now only vote combat patrol
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
speedmerge

**Comment by Lantekk** [comment]
based pr speedmerge

**Comment by RikuTheKiller** [comment]
unbased speedmerge (unpopular opinion)

**Comment by BraveMole** [comment]
Jokes on you, this doesnt do anything since you have to change the config on server. This is just an example config

**Pull request closed without merging**
