### PR TITLE
Simplify the game

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Remove useless bloat from weapon vendors

## Why It's Good For The Game

It's time to learn from CM and simplify the balance. Remove the bloat is very beneficial for balance.
Also i think shotguns were a bit weak so i buffed them because i love CM

## Changelog
:cl:
balance: Remove useless bloat from weapon vendors
/:cl:

### CODE REVIEW

**Comment by SpaceLoveSs13** [comment]
Making meme prs and giving them TM yikes.

**Comment by vilereaver41** [comment]
Why did you increase revolver dmg to 50 from 40?

**Comment by David-Stormwell** [comment]
only eoe would think this is a real pr

**Comment by private-tristan** [comment]
speedmerge, this pr is absolutely amazing, I, a 100000 hour marine main, greatly approve of this pr due to it's beautiful Code. Lovingly featuring my 2nd favorite color in a majority of it, but not Overly so, along with a bit of my favorite color right at the end to brighten up my day! this pr does not make me feel Sad at all!. I feel that this is one of, if not the greatest PRs in the game, both balance wise, code wise, and feature wise. also very Enjoyable as well. :)

**Pull request closed without merging**
