### PR TITLE
Revolver changes

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image

TP44 changes

Damage 30->40
Penetration 20->15
Sunder 1,5->1
Slowdown removed entirely. It now only knockbacks.

## Why It's Good For The Game
Makes the TP44 more useable as a sidearm and primary as right now its difficult to use at all in my opinion, TP-14 can put out more damage with less skill required due to having more in a magazine. Removing the slowdown as a tradeoff for more damage and slightly less pen seems like a good change to me.

## Changelog

:cl:
balance: Revolver now does no slowdown. It now does more damage, and slightly less pen and sunder.
/:cl:

### CODE REVIEW

**Comment by Licherr** [comment]
truly a mjp moment

**Comment by MathiasOrtega** [comment]
This is good with sidearm theme. Should be geared against tier one enemies

**Comment by SilencedMP5A5** [comment]
👀

**Comment by DerpiestBruh** [comment]
This man is insane.

**Pull request merged**
