### PR TITLE
Reworks efficiency into Beam mode.

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Reworks the laser MG Efficiency into Beam mode.
Deals a whopping 1 damage and 0.5 sunder per hit.
Has a beam fire rate.
Renamed the efficiency HUD icon to beam.

## Why It's Good For The Game
Efficiency mode is bait and awful by so many standards. This aims to rework it into a beam mode of constant damage except there's no damage so it specialises in sundering Xenos instead giving it an interesting fire support niche.

<a href="https://cdn.discordapp.com/attachments/498576457740714001/1090965849801760928/What_if_acatually_laser.mp4">Looks cool</a> (If you want a link to the discord post, <a href="https://discord.com/channels/498569646014857217/498576457740714001/1090965851911491594">here</a>)

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Adds beam mode for the Laser MG.
del: Removes efficiency mode for the Laser MG.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
haha wouldnt it be also funny if it was given aim mode that totally hanst been done before

aside that, funny efficiency mode actually being viable now is pretty kewl

also the laughter around the time you started shooting the thing to be greeted by a barrage of laser pew pews is very funny cant wait to use it in hvh

**Comment by Lumipharon** [comment]
Firerates are in multiples of 0.05, an no 0.05 fire rates. Efficiency mode is already the sunder mode due to the higher rate of fire and same sunder (not saying it's good). If you want to change it then just change its stats.

**Comment by FIXTHERADBOXPLEASE** [comment]
Don't get why this was closed so fast. Could've just been balanced to be the same as regular efficiency with the cooler visual effect.

**Comment by Naaanii** [comment]
> Firerates are in multiples of 0.05, an no 0.05 fire rates. Efficiency mode is already the sunder mode due to the higher rate of fire and same sunder (not saying it's good). If you want to change it then just change its stats.

Efficiency has no sunder and I just thought laser beam looked cooler.

**Pull request closed without merging**
