### PR TITLE
Adds more stuff to Valhalla

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Adds shoulder mount
Moves RR to its OG position in the vendor and adds heat, cloak, smoke and tfoot shells.
Adds cloak implant
Adds blood implant
Adds Garand and ammo
Adds MBX and its shell types
## Why It's Good For The Game
More testing, more fun.
## Changelog
:cl:
add: Adds shoulder mount, cloak and blood implant and RR heat, smoke, cloak and tfoot shells to Valhalla.
add: Adds Garand and MBX and its shell types to Valhalla.
qol: Moves RR shells to the same position in the normal vendor along with its ammo.
qol: Moves tracker shells from valhalla req vendor to seasonals vendor for the MBX.
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Add more import weapons (like the MBX hint hint) into valhalla

**Comment by Naaanii** [comment]
> Add more import weapons (like the MBX hint hint) into valhalla

Done.

**Comment by Oscari-pog** [comment]
Could you check for any SoM Guns that arent added and also add the new hostile faction Guns if they arent in? If it wouldnt be too much of a bother

**Comment by Naaanii** [comment]
> Could you check for any SoM Guns that arent added and also add the new hostile faction Guns if they arent in? If it wouldnt be too much of a bother

I added all SOM guns the last update iirc.
Garand is one of the few new faction guns.
Sectoid guns are unusable by humans so I'm unsure what's left to be added.

**Pull request merged**
