### PR TITLE
Martini Henry rework and resprite

### PR DESCRIPTION
**Pull request by ClosetedSkeletonGH**
**notice, as of 2023/01/07 this PR has had its AP changed**

## About The Pull Request
-Updates Martini Henry Ammo sprites to new sprites by Ocelot
-Updates Martini Henry sprites by me :)
-Reworks the Martini Henry as a whole to be a complete and non-meme weapon that fills a unique and currently unfilled niche

image
(If you want to see what it looks like with 4, 3, 2, or 1 bullet left, close your eyes and imagine the full five, then imagine it with 1, 2, 3, or 4 less bullets respectively)

## Why It's Good For The Game
This PR seeks to change the Martini Henry into what the gun actually is, a marksman rifle. The current niche for the Martini Henry is just to run up to the xeno and shoot it in its ass cheek, which is what the shotguns are meant to do, and what the Martini's competition, the repeater, does better in every way. This PR tries to make the Martini Henry not a "FUNNY MEME GUN HEHE". 

Also it is physically impossible for a human to fire a Martini Henry one handed. Even with two hands, it required people to take a weird pose to fire it.

## Changelog
:cl:
Balance will be discussed soon
imageadd: Updated Martini Henry sprites by ClosetedSkeleton
imageadd: Updated Martini Henry ammo sprites by ocelot
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
It's good PR practice to show picture of sprite changes for people that don't know how to access to iconchange.

image

**Comment by maikilangiolo** [comment]
Is it possible to give martini a marginally faster aim mode speed? Since it's single shot and you have to unwield it to reload, having to spend just a little less time on watching red bar turn blue would be nice.

Regardless I agree with everything on PR, and probably the idiotic accuracy range than gives you a 50/50 chance of hitting should be also tweaked.

**Comment by GreatKingWombat** [comment]
Removing one handed firing is a low key buff. Now I can stop NDing while reloading.

**Comment by Naaanii** [comment]
Remove aim mode and remove the negative accuracy at close range tbh.

**Comment by ClosetedSkeletonGH** [comment]
> Remove aim mode and remove the negative accuracy at close range tbh.

The issue with this is that the Martini Henry is a sniper, but with the niche right now of running up to xenos and shooting into their asscheek, then running away. In pretty much everyway of carrying this out, it id worse than the repeater, which also has high damage but is both better than the martini at ranged and close quarters engagements. This PR is mostly focused on making the Martini Henry not the only Marksman weapon (or non-smg weapon really) that doesnt have aimmode.

I will change the accuracy tho when I get home

**Comment by Starfirejordan** [comment]
sprite good, everything else bad

**Comment by Lumipharon** [comment]
Martini isn't really a sniper, the stun reinforces that. I would remove the funny min accuracy (really the ammo shouldn't be a child of sniper ammo at all), but I wouldn't give it aim mode/buff it's pen.

No one hand fire makes sense for big boolet.

**Comment by ClosetedSkeletonGH** [comment]
> Martini isn't really a sniper, the stun reinforces that. I would remove the funny min accuracy (really the ammo shouldn't be a child of sniper ammo at all), but I wouldn't give it aim mode/buff it's pen.
> 
> No one hand fire makes sense for big boolet.

This PR is trying to make the Martini Henry closer to what it is IRL, and shift it away from the "Hehe funny meme gun" meta. I'll touch it up some more to make it have a more unique niche that isnt occupied by many other guns like its current niche, but right now with its meme gun strat, its outcompeted by both shotguns for the general niche, and the repeater for the specific niche.

**Comment by ClosetedSkeletonGH** [comment]
converting to a draft. Im actually going to go into a full rework for the Martini Henry

**Comment by MereWalker** [comment]
I recall when hyper added this gun as a meme gun and one off event round... look how far it has come! It's trying to become a real gun now!

**Pull request closed without merging**
