### PR TITLE
remove easy plat miner in Gelida IV

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

image

## Why It's Good For The Game

Too easy for engineers to gamer.

## Changelog

:cl:
del: remove easy plat miner in Gelida IV
balance: remove easy plat miner in Gelida IV
/:cl:

### CODE REVIEW

**Comment by Aporhtonoma** [comment]
mandatory engie nerf of the month

**Review by RipGrayson — APPROVED** [review]

**Comment by isotope436** [comment]
who even thought this was a good idea lmao

**Comment by ChocolateBickie** [comment]
I've abused this plat miner spot as a lone engineer. 3 tile entrance is too easy to fortify.

Remove it or add more flanks with a lot more open space.

**Comment by FosterGrime-Heymynameslouie** [comment]
I think just adding more flanks and cave openings is alot better than outright removing stuff

now that part of the cave would just seem useless and a weirdly shaped crevasse

maybe a place for a silo at best?

**Comment by novaepee** [comment]
image

For people who don't have StrongDMM,

Here is what the map looks like.

**Comment by isotope436** [comment]
honestly the map itself needs a redesign lmao

**Comment by RipGrayson** [comment]
> honestly the map itself needs a redesign lmao

When you map it

**Pull request merged**
