### PR TITLE
Vendor QOL #2

### PR DESCRIPTION
**Pull request by collinlunn**
## About The Pull Request
Vendors will now try to insert spawned items into the player's currently opened container, before trying to put them into their hand.
For instance, you can open your ammo belt, vend 6 mags, and they will be auto-inserted into the belt, without you having to manually click them each in.

Does not affect the auto-closet, which still attempts to auto-equip relevant items.

## Why It's Good For The Game
Reduces repetitive clicking to fill storages during prep.

## Changelog
:cl:
qol: Vendors will try to insert vended items into the player's currently opened storage. Does not affect Automated Closet.
/:cl:

### CODE REVIEW

**Comment by collinlunn** [comment]
https://user-images.githubusercontent.com/60152240/211092763-7d640579-1014-46b8-b3b5-be71c0be3257.mp4

**Comment by Aporhtonoma** [comment]
the future is here

**Comment by breadhunt** [comment]
It's.. it's beautiful..

**Comment by FosterGrime-Heymynameslouie** [comment]
speedmeghe this instantly the fate of the world and carpel tunnel statics lie within this pr

**Comment by Losenis** [comment]
BASED HOLY SHIT

Tell me this works with ammo boxes too

**Pull request merged**
