### PR TITLE
kill the shield

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
shields removed from vending machines and req still available in hvh

image

## Why It's Good For The Game
makes marines way too tanky, nerfing will make it useless

## Changelog
:cl:
del: remove shields from vending and req
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
thank you for taking the time to censor his name and image
idtentity theft is bad and we must do everything we can to prevent it

**Comment by CabbageOnTable** [comment]
Salt pr?

**Comment by Lumipharon** [comment]
> thank you for taking the time to censor his name and image idtentity theft is bad and we must do everything we can to prevent it

Who is this mystery individual? We must unravel their secrets.

**Comment by Mrrpip** [comment]
Well. That's a yikes from me, chief.

But on a less jokey note, does this really make marines too tanky? Unless you're going AAA tier powergaming (Or robot, which has it's own set of drawbacks) it's countered pretty well be defiler, carrier and sentinel to some extent.

Two shields are probably over the top for tanking, that I agree with, but with the innate slowdown, you're not really chasing much, let alone the fact you can't carry many weapons besides a sword due to a lack of storage space balances it out.

Synth and Shield is also strong. But that's a symptom of synth having increased melee skill and no proper marine armor bar the flak jacket, so of-course they'd benefit a ton from it. I'd reckon that mess would still be a pain, even with the lesser deployable shield.

I mean, yeah, not much will be lost if shields are removed, but, well. It's a fun little thing to use, I guess.

**Comment by DerpiestBruh** [comment]
:(

**Comment by tyeagg** [comment]
thought of a rework

**Comment by Zar000** [comment]
Speedmerge rn

**Comment by 567Turtle** [comment]
Shields slow you down a bunch and take up a whole hand, which you, y'know, kind of need to be able to shoot something, this just seems like you got killed by a shield marine and then frantically began backspacing code through the tears in your eyes. There's only 6 of them anyway so yknow it's not like they're being given to every marine.

**Comment by Derrick2Electricboogaloo** [comment]
Yeah this is some omega cope, only get 5, lots of slowdown. who plays hvh?! Basically deleting it from the came

**Comment by TiviPlus** [comment]
Shields have downsides I dont see them as something crazy

**Pull request closed without merging**
