### PR TITLE
Gives a new sprite to most attachments and nerfs bc and buffs suppressor

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Resprites most attachments so its consistent with the style
The BC was unintentionally buffed to be basically a straight upgrade on most guns.
The suppressor was really really bad.

## Why It's Good For The Game
Better consistent styling.
BC was too good, suppressor was never used outside of memes.

## Changelog
:cl:
add:New attachment sprites
del:old attachment sprites
balance: bc nerfed suppressor buffed. BC gives halve the damage buff and gives you -75% accuracy and 30 scatter. Suppressor no longer has any damage malus
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -42. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by RenGusta** [comment]
A good suppressor buff would be removing impact noise from gunfire so it can be used sneakily

**Comment by DerFlammenwerfer** [comment]
The barrel charger already has a -45% accuracy penalty attached to it. Is 20% extra damage really that powerful if you're nearly 50% less likely to hit your shots?

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Give the new scope a unique desription please

**Comment by TiviPlus** [comment]
Still pending

**Review by TiviPlus — APPROVED** [review]

**Review by Hughgent — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-43). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
