### PR TITLE
Fine, it is Armoured Flood Light

### PR DESCRIPTION
**Pull request by Derrick2Electricboogaloo**
## About The Pull Request

Capitalizes the letters so it does not look stupid.

## Why It's Good For The Game

Consistency good.

## Changelog
:cl:
fix: Fixes Armoured Floodlight name by captializing it.
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
So I was trying to originally fix it so the cell starts with a high cap cell, but when I replace the var: "var/'obj/item/cell/cell" with "var/obj/item/cell/high" it breaks. I know why. But I was hoping that replacing the cell in the list would be easier, anyone have an idea? I know the cell var is tied to other aspects of the floodlight and it being powered.

**Comment by TiviPlus** [comment]
/me blasts u with my english beam

**Comment by Derrick2Electricboogaloo** [comment]
WHAT. WHY was it closed!

**Comment by Derrick2Electricboogaloo** [comment]
Heinous, you are truely an evil villan!

**Pull request closed without merging**
