### PR TITLE
New Lobby Screen: Gorger Hospital Scene

### PR DESCRIPTION
**Pull request by Jalopkomit18**
## About The Pull Request
Adds new title screen in widescreen format.
shinjiGorgerTitle
## Why It's Good For The Game
More lobby art, and gorger ass has not been memed enough
## Changelog
:cl:
add: Adds new lobby art: Gorger Hospital Bed
/:cl:

### CODE REVIEW

**Comment by Blundir** [comment]
Kinda generally poorly made, also the joke itself is not very funny... I dunno man

**Comment by FosterGrime-Heymynameslouie** [comment]
waht

**Comment by GreatKingWombat** [comment]
Large chunk of the playerbase might be too young to understand the reference, and it's not funny enough to be good without understanding the reference.

**Comment by Lumipharon** [comment]
Nah.

**Comment by Kuro020** [comment]
> Nah.

wtf you're not art director bro

**Comment by Kuro020** [comment]
Hell nah

**Comment by FIXTHERADBOXPLEASE** [comment]
The most controversial PR in TGMC history...

**Comment by Araulius** [comment]
> Large chunk of the playerbase might be too young to understand the reference, and it's not funny enough to be good without understanding the reference.

wont' somebody THINK OF THE CHILDREN

**Pull request closed without merging**
