### PR TITLE
synth has a melee damage malus

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
synth deals doctor damage on melee (so like less)
## Why It's Good For The Game
combat synth deserves a nerf
## Changelog
:cl:
balance: Synths deal less damage on melee now.
/:cl:

### CODE REVIEW

**Comment by veterath** [comment]
does he know chat (clearly not)

**Comment by Barnet2** [comment]
Least based MJP PR

**Comment by Derrick2Electricboogaloo** [comment]
Yes please make it more impossible for me to defend myself.

**Review by ivanmixo — APPROVED** [review]

**Comment by Xander3359** [comment]
PRAISE BE, THE ERA OF COMBAT SYNTH IS GONE OOORAH

**Comment by efzapa** [comment]
> Yes please make it more impossible for me to defend myself.

if you wanna defend yourself against xenos play marine you goober

**Pull request merged**
