### PR TITLE
Defender rebalance

### PR DESCRIPTION
**Pull request by Spyroshark**
## About The Pull Request

This gives defenders better stats and somewhat better upgrades, to make staying as a defender more viable.

## Why It's Good For The Game

The other combat T1 xenos, runner and sentinel, are useful throughout the round and are just as capable as T2s by the time they reach elder. Defenders are currently much worse then warriors and other front line xenos and need to be buffed so that they are viable later on in the round, since this caste is currently useless late game.

## Changelog
:cl:
balance: Defenders now have more health, armor, and stronger defensive abilities.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
what even

**Comment by drawsstuff** [comment]
Defender is worse than warrior in every single way. 
Ancient defender has worse armor than a **young** warrior

**Comment by Spyroshark** [comment]
Defender is too squishy and unarmored for a front-line caste. Since it's abilities aren't as good as they used to be it needs to be stronger to be worth playing

**Comment by spookydonut** [comment]
I dont think these stat changes will meaningfully address the perceived issues with the defender, but they are worth a try.

**Comment by Rushnagar** [comment]
I don't see why the slash damage needs to be increased, they deal more damage by having increased staying power after all.
I also dislike changing too many things at once, makes hard to tell where the buffs "went too far" in cases where things go wrong.

**Comment by Rohesie** [comment]
Agreed, changing armor, speed and damage all in one go is a bit too much.

The change is slow, but you've said the defender is squishy. Do you also feel it does too little damage and is too slow?

We don't want to move towards making the game faster and more rocket-tag-based in general, so only buff speed and damage in those situations, else leave them as they are.

**Comment by Spyroshark** [comment]
That's fair. I'm gonna close this pr since it isn't really thought through well enough, I'll ask for some more opinions on defender in the balance channel on the discord and maybe make a better PR in the future.

**Pull request closed without merging**
