### PR TITLE
boiler gets NO speed up from weeds

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
boiler is too fast for a backliner, it is hardly punished for being caught off guard, it has average health stats and is nearly always a leader, and you can stack it.

## Why It's Good For The Game
this is desperately needed, boiler shouldn't have got this in the first place

## Changelog
:cl:
balance: boiler gets NO speed up from weeds, at all.
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
Not a bad change. Currently, Boilers are able to outrun most marine setups on weeds and it's rather hard to kill them as a result even if they make mistakes. This should help with that.

**Comment by lbnesquik** [comment]
I am not a fan, but note that boiler fire rate was recently buffed. The caste got a fair bit strong from that.

**Comment by BorranScail** [comment]
Marines can currently outrun Boilers on weeds. This would make the problem even worse.

**Comment by GradusNL** [comment]
> 
> Currently, Boilers are able to outrun most marine setups on weeds

> Marines can currently outrun Boilers on weeds.

The duality of man. Which is true?

**Comment by davidchan13** [comment]
This doesn't make any sense, marines can sprint faster than Boilers can move. Boiler is the tied for the slower xeno in the game, only a young hivelord is slower and an ancient tier Boiler, Crusher and Hivelord all have .1 speed. And now we saying the slowest xeno needs to be slower when it already struggles to defend itself against a competent marine?

**Comment by TiviPlus** [comment]
Boiler doesnt need this nerf

**Pull request closed without merging**
