### PR TITLE
Typescripts orbit menu and adds dead section to it

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
typescript fun
also comes with a few fixes from another PR i'll make because wont work without it.

## Why It's Good For The Game
Typescript good. also knowing dead good too.

## Changelog
:cl:
qol: dead people now appear on orbit menu under dead section.
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
still gotta rebuild bundle and port to tg

**Comment by TiviPlus** [comment]
Still waiting 😩

**Review by TiviPlus — APPROVED** [review]
Splinter said no mor waiting

**Comment by SplinterGP** [comment]
was too lazy lmao

**Pull request merged**
