### PR TITLE
Helping make room for queen's abilities

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Watch Xenomorph, Hive message, Set leader, Queen deevolve, blessing Menu, and Call of the Burrowed are now collapsible. You can open them with Hive Management!

## Why It's Good For The Game

Too much bloat in queen's UI. These six abilities in Hive management take a lot of space and you don't need to use them all the time compare to other abilities. **Queen is keybind intensive, so we might as well reinforce that fact. If this is daunting for new queen players, that is the point. Read the wiki.**

The following I might add into Hive Management to help with space:
- Plant weed (you should have this keybinded, so why use up UI space?)
- Plant acid well (you should have this keybinded, so why use up UI space?)
- Psychic Drain (not used often, so you might as well just open up Hive Management)
- Cocoon (not used often, so you might as well just open up Hive Management)
- Screech (you should have this keybinded, so why use up UI space?)
- Rally Minion (not used often, so you might as well just open up Hive Management)
- Set Aggresitivity (not used often, so you might as well just open up Hive Management)

If you really need more keys in your keyboard to keybind, I recommend replacing 2 and 3 with something else. TGMC enomorphs do not need to change into grab or disarm intent.

The future is now. 

## Changelog
:cl:
add: The Hive Management Action holds Watch Xenomorph, Hive message, Set leader, Queen deevolve, blessing Menu, and Call of the Burrowed
qol: Now you can see north of you. Maybe.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
The future

https://user-images.githubusercontent.com/6610922/147446728-3b534437-0226-45aa-bf3c-556f82c2a474.mp4

**Comment by novaepee** [comment]
I might get around to making Hive Management a keybind. Maybe.

**Comment by TheLeopold** [comment]
Fun thing is there's no keybind option for acid well. (Unless it was added and I missed that moment)

**Comment by Verlurk** [comment]
Why not just move these to the xenos tab instead of making collapsibles on the HUD?

**Comment by Losenis** [comment]
Bring back inject larval

**Comment by novaepee** [comment]
> Fun thing is there's no keybind option for acid well. (Unless it was added and I missed that moment)

Will check that.

**Comment by novaepee** [comment]
> Bring back inject larval

HMMMM

**Comment by novaepee** [comment]
> Why not just move these to the xenos tab instead of making collapsibles on the HUD? I don't think "you should have these keybinded" is a particularly good reason for moving the others you mentioned.

We're trying to avoid adding stuff in xeno tab. Heck, I even want to double click on vent just to vent in. Also, more travel time for mouse cursor to get to xeno tab.

Speaking of that, I might as well add hive status on hub . . .

**Comment by novaepee** [comment]
Closing because it's bad code and Bravemole wants something else.

**Pull request closed without merging**
