### PR TITLE
Mechs can honk now

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

https://user-images.githubusercontent.com/57223640/190482270-35a8939e-d97e-410d-9d72-c9dc2ab9e556.mp4

## Why It's Good For The Game

Beep beep

Sound by Sym/Grimmy#7205

### CODE REVIEW

**Comment by Lumipharon** [comment]
Expection: H.O.N.K.
Reality: Dreams crushed

**Comment by MereWalker** [comment]
Should add more honk sounds. So we get variety.

**Comment by Al-1ce** [comment]
Multiple to choose from would be cool.

**Comment by BraveMole** [comment]
Mechs are not clown, get real

**Pull request closed without merging**
