### PR TITLE
Valhalla Mech Pilot

### PR DESCRIPTION
**Pull request by Ben10083**
## About The Pull Request
Mech Pilot added to Valhalla ghost roles, as well as a mech computer 
image

## Why It's Good For The Game
Allows for people to test how the mech works outside of the round, should appease those who like to experiment and want to see how to refine their mech loadouts.

## Changelog
:cl:
add: Valhalla given Mech Pilot role.
expansion: Mech Computers added to Valhalla for MP
/:cl:

### CODE REVIEW

**Comment by zzurge** [comment]
i know its not my place to say but if it hasnt been already **speed merhg**

**Comment by FosterGrime-Heymynameslouie** [comment]
I beleive a testing area for this is also needed, maybe recommission dorms/cafetria to be a war zone like simulation simmilar to the shooting ranges for marine?

might be out of the scope of the pr

spede mrhge

**Comment by tyeagg** [comment]
add more than one console

**Comment by Tailiik** [comment]
It would be nice to see a beno section of valhalla to test keybinds/castes/damage as well

**Pull request merged**
