### PR TITLE
Test pr pls ignore

### PR DESCRIPTION
**Pull request by TiviPlus**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
I refuse to ignore this

**Comment by godspeedfunnyman** [comment]
jesus christ...

**Comment by David-Stormwell** [comment]
kiss me when

**Comment by BraveMole** [comment]
> kiss me when

That's sexual harassment bro, you really want that lawsuit?

**Comment by David-Stormwell** [comment]
> 
> 
> > kiss me when
> 
> That's sexual harassment bro, you really want that lawsuit?

I consent

**Comment by Pariah919** [comment]
bad pr

**Comment by hyper2snyper** [comment]
literally gamebreaking

**Comment by neohenry** [comment]
c*ders

**Comment by ilikesaying** [comment]
wot

**Comment by TiviPlus** [comment]
you had one job

**Pull request closed without merging**
