### PR TITLE
Adds Terra Gov logo to briefing

### PR DESCRIPTION
**Pull request by MoXuT0**
## About The Pull Request

Per title. Also fixes some inconsistency with plating and office tiles.

## Changelog

:cl:
imageadd: Added Terra Gov logo to briefing room of Theseus.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
Didn't you want to make it a bit darker?

**Comment by MoXuT0** [comment]
It’s already much darker than initial version, might wanna lower transparency but later.

**Comment by MoXuT0** [comment]
I still don’t like how it looks so DNM for now.

**Comment by MoXuT0** [comment]
Should look gucci now, maybe a bit too bright but I don't want to remake it one more time.

**Pull request merged**
