### PR TITLE
Fixes PMC sniper IFF

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request

title

## Why It's Good For The Game

fix

## Changelog
:cl:Slotbot
fix: PMC sniper has IFF again
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
what ? PMC Sniper dind't ever have IFF

**Comment by Chaznoodles** [comment]
image

Y-you know it never had IFF, right?

**Comment by Walarks** [comment]
> what ? PMC Sniper dind't ever have IFF



> image
> 
> Y-you know it never had IFF, right?

Capture3
Capture2
From aim mode file changes PR
Capture

**Comment by Wayland-Smithy** [comment]
Right because PMC need a buff 😞 

How about fixing the 100 sunder in .5 seconds from the leaders SG?

**Review by Hughgent — APPROVED** [review]
as it should have always had.

**Review by TiviPlus — APPROVED** [review]
This is correctly a bugfix, PMCs being shit needs to be fixed seperately

**Pull request merged**
