### PR TITLE
Updated walls and resin/weed sprites

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Updated weed, resin wall, resin door, wall, r-wall and white (sulaco) walls.
Shout out to Gregormack for the awesome new sprites.

Also reenabled wallweeds, since it looks a lot nicer.

image
Resting weeds are the green, bubbly looking ones, and slow weeds are the pale thin twiggy ones.
And a bad screenshot of some of the new walls.
image

## Why It's Good For The Game
Improved art is good.

## Changelog
:cl:
imageadd: Updated wall, r-wall and white wall sprites
imageadd: Updated weed, resin wall and resin door sprites
code: Renabled wallweeds
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
bless the enigma, the miracle man, known as gregor for sacrificing a lifetime in order to make this possible

speedem meghrd

**Review by TiviPlus — APPROVED** [review]

**Comment by iLikeMemes** [comment]
All Sprites look amazing but I dont know how I feel about the weeds. They kind of feel out of place for some reason. Could just be I need to get used them but who knows.

**Comment by Kuro020** [comment]
24 hour to merge, as always

**Comment by Al-1ce** [comment]
The sprites are good, but they really do not blend in with the old cm shit we've got. The blend just doesn't work.

**Comment by Lumipharon** [comment]
> The sprites are good, but they really do not blend in with the old cm shit we've got. The blend just doesn't work.

Lucky they're going to be taken out behind the shed eventually.

**Comment by Losenis** [comment]
Conceptually it *might* work with a bit of an art clash to differentiate normal human aesthetic with xeno-controlled areas constrasting enough to not blend in. It might also be the novelty factor idk.

**Comment by Kuro020** [comment]
> The sprites are good, but they really do not blend in with the old cm shit we've got. The blend just doesn't work.

that just means we need to kill cm sprites later then

**Comment by Al-1ce** [comment]
> that just means we need to kill cm sprites later then

That's a much larger project than this. Easily x100. In the meantime, I don't think anyone would want to have this mis-match style confrontation while waiting weeks for the spiriting to finally be done. These sprites look like they're from a completely different server with it's own unique shading/palette. The queen doesn't even fit in. You would need to resprite _everything_.

**Comment by Kuro020** [comment]
> > that just means we need to kill cm sprites later then
> 
> That's a much larger project than this. Easily x100. In the meantime, I don't think anyone would want to have this mis-match style confrontation while waiting weeks for the spiriting to finally be done. These sprites look like they're from a completely different server with it's own unique shading/palette. The queen doesn't even fit in. You would need to resprite _everything_.

Yeah but if we were like this with sprites we will literally never get better art wise, gotta push the artstyle in the direction of progress, if it ends up with some mismatched stuff staying in the game at least some parts of it are looking better

**Comment by Al-1ce** [comment]
> Yeah but if we were like this with sprites we will literally never get better art wise, gotta push the artstyle in the direction of progress, if it ends up with some mismatched stuff staying in the game at least some parts of it are looking better

It's difficult to visualize this looking better when it is seldom in it's design/style. Sure, there are plenty of sprites that have variation or look different, but none on a level this extreme.

As I initially mentioned, **_everything_** but the weeds themselves looked like they didn't belong in the initial picture. The contrast is mind numbing. Forgive me for being doubtful that you can adapt the entirety, or even a large majoriety of our current sprites to match the style of the couple included in this PR.

**Comment by Kuro020** [comment]
> 

Thats a sacrifice im willing to make

**Comment by gast03** [comment]
It does not work with the other sprites. I want the old sprites back.

**Comment by gast03** [comment]
It does not look better. Related to this game if that makes sense. Sure it is beautiful but it does not feel grounded. Things blends each other too much ,color pallet is off compared to other stuff as  mentioned before.

**Comment by Al-1ce** [comment]
After some consideration, I think these sprites are actually okay. My first impression of them was on Big Red where the contrast is the most by far.

**Comment by gast03** [comment]
Please revert the sprites.

**Comment by gast03** [comment]
Day 7 of praying the resin sprite changes is reverted.

**Pull request merged**
