### PR TITLE
The Year of the Rabbit is Here

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Readds bunny ears (and maid outfit for flavour because I couldn't find the bunny outfit.)
## Why It's Good For The Game
Nice flavour and fits map themes with maid bars and whatnot.
## Changelog
:cl:
add: Adds bunny ears and maid outfit.
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]
I still like catgirls more

**Comment by lKiseki** [comment]
Can you stop readding this? There’s a clear reason why such content was removed and I’d rather not see us go full circle.

**Comment by Pariah919** [comment]
AGHHHHHHHHH

**Comment by GreatKingWombat** [comment]
Dew it.

**Comment by Losenis** [comment]
no balls

**Comment by Naaanii** [comment]
> Can you stop readding this? There’s a clear reason why such content was removed and I’d rather not see us go full circle just like how we did with cat ears.

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVyS-IfM_MYvvRgyZKNPbac5L2Wk-dizCVgyvtjvsn&s

**Comment by Ragecrabbo** [comment]
Merge it but force Naaanii to host every round until they get removed again

**Comment by Windryn** [comment]
Rabbit season is now open.

**Comment by Coastfront** [comment]
This only exists for the same reason it is a lesson seldom learned by coders to keep such words as "sex appeal" a rivers measure away from the code.
It is not that they can't understand such reasoning, it is that they simply don't care.

You know fulll well that outside of just being a shitpost, this is going to be used for ahem, in lack of more endearing terms, "weird horseshit"

**Comment by FosterGrime-Heymynameslouie** [comment]
here goes fourth times the charm of naini trying to add this weird thingn

**Comment by spookydonut** [comment]
No.

**Pull request closed without merging**
