### PR TITLE
Adds more Captain Ranks

### PR DESCRIPTION
**Pull request by Naaanii**
Adds more ranks relating to playtime for Captain.

## About The Pull Request

Adds more ranks for Captain.

## Why It's Good For The Game

Adds more flavor and hopefully incentive to play the leading Command role. Also makes use of unused ranks in code and now that we have our first RADM, the higher ranks might finally get used.

## Changelog
:cl:
add: Added more ranks regarding playtime for the Captain role.
/:cl:

### CODE REVIEW

**Comment by Swagile** [comment]
you just wanna be a grand admiral, huh?

😎

**Review by Naaanii — COMMENTED** [review]
Fixed code

**Comment by SpaceLoveSs13** [comment]
> 
> 
> Fixed code

Yea it's good now.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Im going to think about it but if I say yes it'll be to one rank max

**Comment by TiviPlus** [comment]
Ok one extra rank at 1000 as the main shipside role to complement the PFC 1000 rank

**Comment by Naaanii** [comment]
> Ok one extra rank at 1000 as the main shipside role to complement the PFC 1000 rank

Marines half a 300 rank too though. This is mainly flavor stuff but I can add 2 ranks at least.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
I'm not budging on this

**Comment by Naaanii** [comment]
This PR is too low effort.

image

**Pull request closed without merging**
