### PR TITLE
Icy Cave's addition's and tweak.

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

New area northeast of caves, Monorail & Research.

## Why It's Good For The Game

More fun spots, cave gameplay constantly on this map is boring.

## Changelog
:cl:
add: new area northeast of caves.
balance: West-LZ1 to make it a bit more open north of it. also made lz1 bigger so marines got more room
balance: the pre shutter open no-build zone has been reduced.
balance: added more weed nodes and doors in caves for quality of life.
/:cl:

Red is the build zone. blue is a no-build zone.
LZ1
image
LZ2
image

LZ1 change.

image

New area.

NO you cant access the tank, it's behind indestructible podlocks and it's zoned out. only there for cosmetics

image

### CODE REVIEW

**Comment by Luxyboo** [comment]
what is purple

**Comment by chesse20** [comment]
i can't tell anything from the comparison screenshots lz1 looks unchanged

**Comment by private-tristan** [comment]
marines can lock left and right side of Alamo on the western LZ, and the south entrance is blocked meaning that marines can effectively lock down Alamo without risk of hijacking from outside (obviously not wraith immune)
forgot to take a screenshot, but you can test it out yourself, can probobly be fixed by removing 1-3 tiles along the south.

**Comment by vilereaver41** [comment]
> marines can lock left and right side of Alamo on the western LZ, and the south entrance is blocked meaning that marines can effectively lock down Alamo without risk of hijacking from outside (obviously not wraith immune) forgot to take a screenshot, but you can test it out yourself, can probobly be fixed by removing 1-3 tiles along the south.

il fix that

**Pull request merged**
