### PR TITLE
Removes lrp dolls

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
removes dumb lrp dolls that should not bei in the game

## Why It's Good For The Game
10 year old dead internet memes be gone

## Changelog
:cl:
deal:touhou
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Lel, can you do even more knee jerk?

**Comment by Kuro-ai** [comment]
> Lel, can you do even more knee jerk?

shut,kill the anime,anime is bad

**Comment by SpaceLoveSs13** [comment]
Is this some salt pr? 

Regardless, a pr that just got merged gets a removal pr that has merely any reason of doing so. Also having something in game that can ne:er be accessed but by admins is not really ruining rp in anyway in my opinion. So to me even the rp reason seems invalid.

**Comment by AnCopper** [comment]
> > Lel, can you do even more knee jerk?
> 
> shut,kill the anime,anime is bad

touhou is not anime, checkmate atheist.

**Comment by AnCopper** [comment]
based

**Comment by TheBimmer231** [comment]
based and redpilled.

**Comment by jroinc** [comment]
The lizard doll is still in so I'm fine

**Comment by ZahaSanko** [comment]
not my Fumo..

**Comment by bobmancer343** [comment]
wait the dolls are touhou? ok remove them

**Pull request merged**
