### PR TITLE
Decreases the size of some fog areas on icy caves, slightly widens western cave tunnels

### PR DESCRIPTION
**Pull request by Technical-l**
## About The Pull Request

Pushes the fog near security further east 
image

Confines the fog at the monorail station to this room
image

Fog close to refinery slightly shortened
image

Passage to monorail from refinery widened by 1-2 tiles
image

## Why It's Good For The Game

Icy caves is a somewhat xeno sided map, hoping these changes will make it easier for the marines to get to and hold disks.

## Changelog

:cl:Joe13413
balance: Adjusted fog closest to each disk on Icy Caves, widened western cave passage to northwest disk
/:cl:

### CODE REVIEW

**Comment by Technical-l** [comment]
gotta write some stuff gimme a sec

**Comment by TiviPlus** [comment]
@RipGrayson

**Comment by RipGrayson** [comment]
@TiviPlus This isn't passing checks, if he doesn't want to fix his PR it can stale out.

**Comment by Technical-l** [comment]
im gonna be real i forgot about this PR right after opening, gimme a few to fix this

**Comment by Technical-l** [comment]
> the path to nuke is still pretty dammed funky i say lessen the fog in the left a bit

also not a bad idea, opening up the passages there a bit
image

**Comment by Technical-l** [comment]
couldnt be bothered to figure out how to update this PR with a different branch, so i chose the easy option

**Pull request closed without merging**
