### PR TITLE
New motorbike upgrade, the Anti-Tank Motorbike.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Introduces a new upgrade for the motorbike, the anti-tank motorbike attachment allows you to attach a RL-160 cannon directly onto your bike, allowing you all the benefits of having a cannon strapped onto a motorbike.
New sprites added 
image

## Why It's Good For The Game
Ever wanted to ride a bike and fire a cannon at the same time? Well this is exactly the upgrade you are looking for.
## Changelog
:cl:
imageadd: new cannon-mounted motorbike sprites.
/:cl:

add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: new cannon-mounted motorbike sprites.
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know

### CODE REVIEW

**Comment by Addust** [comment]
quick idea for this:

load tadpole with angry antitank motorbike marines
commit rapid D-day and wipe out xenos in an area
get back in tadpole
do it again repeatedly

**Comment by RaidarV** [comment]
This PR is endorsed by GLA Combat cycle gang.

**Comment by Goblinu** [comment]
Will there be any noticable drawbacks to this kind of bike compared to the usual back?

**Comment by Al-1ce** [comment]
BY THE GODS, THERE'S A PSYCHOPATH ON THE LOOSE!

**Comment by RuneQuester** [comment]
Because marines definently needed more ways to deliver high alpha ordnance without any downside of having to set it up, or be exposed while using it.

yup. thats a good idea.

**Comment by XElectricX** [comment]
Very cool but very broken. Maybe give it to an ERT.

**Comment by Autisem** [comment]
we really giving the ADHD riddeld machine pistol spammer an anti tank gun?

**Comment by Beepinex** [comment]
aww man I cant hold my 2 handed rpg while on my bike, if only i could powercreep this away

**Comment by ChristianDenDanske** [comment]
An RR gun on a motorbike is cool and all, but i doubt the xeno mains would approve

**Comment by Joe13413** [comment]
how has this been a draft for a month and a half what is going on with this thing

**Comment by Xander3359** [comment]
> how has this been a draft for a month and a half what is going on with this thing

It's just been in backlog man.
I'm just 1 guy and I dont understand how to attach a weapon to a bike so I have a lot of learning to do still.

**Pull request closed without merging**
