### PR TITLE
ONE new title art from Zaha!

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title!

## Why It's Good For The Game

More art, more life in TGMC!

## Changelog
:cl:
add: A new title art from Zaha, your own trial admin!
imageadd: ibit
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
image

**Comment by Losenis** [comment]
>Get rid of the black bars put there specifically to stop it from stretching
>It stretches

Bruh

**Comment by Alexeivichi** [comment]
You draw art of me as a twink.
I'm too busy murdering xenomorphs.

We are not the same.
I approve of the 2nd one of Tanya/Losenis.

**Comment by David-Stormwell** [comment]
bruh

**Comment by novaepee** [comment]
qdel alek as femboy, make Tanya/Losenis better
image

**Comment by Losenis** [comment]
Now this is podracing

**Comment by AndroidMK2** [comment]
The second one is nice, the first is quite sus.

**Pull request merged**
