### PR TITLE
Removes chem purging from neurotox.

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
Removes chem purging from neurotoxin, as of the neurospit and stamina things from Surr #5501 neurotox is now injected by neurotox spit, which then makes every caste with neurospit able to remove marine chems at distance.

## Why It's Good For The Game
makes neurotox not nuke people meds, which is not needed since larval growth already exists to do that and neurotox spit is now injected at distance by neurotox spit, which makes marine lose all their meds in their bloodstream just by getting spit once or twice.

## Changelog
:cl:
balance: neurotoxin no longer removes marine meds.
/:cl:

### CODE REVIEW

**Comment by Swagile** [comment]
On one hand, this buffs pre-medding marines, which isn't good.

On another hand, this makes being a marine less shit.

Maybe nerf the effect a bit so that it purges less good chems instead of nuking it from existence, so the first few shots aren't that bad but if you keep getting hit, you have to retreat or your good meds run out?

A better compromise, since pre-medding makes marines way too tanky, and ranged neurotox is a way to stop them.

**Comment by SplinterGP** [comment]
> On one hand, this buffs pre-medding marines, which isn't good.
> 
> On another hand, this makes being a marine less shit.
> 
> Maybe nerf the effect a bit so that it purges less good chems instead of nuking it from existence, so the first few shots aren't that bad but if you keep getting hit, you have to retreat or your good meds run out?
> 
> A better compromise, since pre-medding makes marines way too tanky, and ranged neurotox is a way to stop them.

premed marines is the default behaviour, neurotoxin shots dindt use to inject neurotoxin before so it was more allowed, but now its basically injected by anything.

**Comment by SplinterGP** [comment]
>Maybe nerf the effect a bit so that it purges less good chems instead of nuking it from existence, so the first few shots aren't that >bad but if you keep getting hit, you have to retreat or your good meds run out?

meds run out by default, they get used with time, even when not using.

**Comment by Al-1ce** [comment]
I'd say a nerf to its effectiveness (like 50-70%) would be a better fix for the time being, as pre-medding marines are frustrating to deal with. It also makes Neurotox absolutely useless in the current meta.

**Comment by SplinterGP** [comment]
> I'd say a nerf to its effectiveness (like 50-70%) would be a better fix for the time being, as pre-medding marines are frustrating to deal with. It also makes Neurotox absolutely useless in the current meta.

we can buff the other neurotoxin that aint from spit, but being as is on spit is yikes.

**Comment by Sulaboy** [comment]
> > I'd say a nerf to its effectiveness (like 50-70%) would be a better fix for the time being, as pre-medding marines are frustrating to deal with. It also makes Neurotox absolutely useless in the current meta.
> 
> we can buff the other neurotoxin that aint from spit, but being as is on spit is yikes.

What about removing neurospit from prae. Sentinel would be the only class with it, and it’s acid spit is weak. It might have that push to make it a support caste instead of a ranged skirmisher.

**Comment by Smudged** [comment]
> > > I'd say a nerf to its effectiveness (like 50-70%) would be a better fix for the time being, as pre-medding marines are frustrating to deal with. It also makes Neurotox absolutely useless in the current meta.
> > 
> > 
> > we can buff the other neurotoxin that aint from spit, but being as is on spit is yikes.
> 
> What about removing neurospit from prae. Sentinel would be the only class with it, and it’s acid spit is weak. It might have that push to make it a support caste instead of a ranged skirmisher.

It'd be better if neurospit was removed from Sentinel, so in order to have it you need a T3, keeep neuro sting for sentinel though because it's melee.

**Comment by Walarks** [comment]
Pre-medding is balanced so that you would need meds that aren't widely available to make a noticeable difference in-combat. Also meds, like bullets, eventually run out so marines can't stay on them forever and need to additionally carry and prepare them along with their other equipment.

Neutorox being widely available with a purging effect essentially removes a part of the game that is ok without it for no good reason.

**Comment by Pariah919** [comment]
no

**Comment by SplinterGP** [comment]
> 
> 
> no

shuddup dude you have -350 gbp

**Comment by Surrealaser** [comment]
Terrible idea for reasons discussed at length with you previously unless neurotoxin is made better in some other way to compensate.

**Comment by Naaanii** [comment]
Just nerf the amount injected instead of downright making it borderline useless. No reason to completely nuke the effect and say 'larval exists' since larval is even less useless with our movement away from cap gameplay, might as well just remove larval and let Neurospit retain its effect.

**Comment by Walarks** [comment]
> Just nerf the amount injected instead of downright making it borderline useless. No reason to completely nuke the effect and say 'larval exists' since larval is even less useless with our movement away from cap gameplay, might as well just remove larval and let Neurospit retain its effect.

Neurotox spit's purpose isn't to nuke your chems, it's to drain your stamina and give you continuous tox damage. If its purpose was to nuke chems, it should be balanced differently.

**Comment by TiviPlus** [comment]
I dont think anyone likes this 
Maybe implement swagiles suggestion in a different PR?

**Comment by SplinterGP** [comment]
Neurotox alrready does too much and makes marines also a pain to revive, i domt believe nuking a shitty mechanics that removes fully other people play or tactics is good

**Comment by Swagile** [comment]
I based my feedback on just the simple chems marines have access to.

Bic + Kelo + Tram + Inap + Tric popped once before an engagement can make you live up to 10-15 seconds longer than a normal marine who doesn't do any of this. This might not seem like a lot, but thats 2-3 extra PB's with a T35, an entire clip of a T12, half a clip of a T42, you get the picture. The extra amount of DPS that you are able to output in this time frame can be the difference between life or death, or in the case of a xeno, whether to go for a killing slash or let you live and retreat so they can heal.

Usually its the latter, which lets you (who premedded) limp back to a corpsmen or to other marines to cover you, while the un-premedded marine dies or worse, gets combat dragged to brazil.

This is why neurotoxin is crucial, especially when you face experienced marine who use a similiar (or even better, for cases like Dolthgar) mix of chems. Neurotoxin levels the playing field for both competent and gamer level marines.

However I do agree the effect is a little too strong, especially for a T1 sentinel. Maybe make the effect less (less injection of the neurotoxin itself) for sentinel and keep it as is for the Prae since it IS a T3.

Just spit balling; outright removing chem purging just makes it a LOT more difficult to deal with marines who know what they are doing (especially when they unga ball).

**Comment by Walarks** [comment]
> I based my feedback on just the simple chems marines have access to.
> 
> Bic + Kelo + Tram + Inap + Tric popped once before an engagement can make you live up to 10-15 seconds longer than a normal marine who doesn't do any of this. This might not seem like a lot, but thats 2-3 extra PB's with a T35, an entire clip of a T12, half a clip of a T42, you get the picture. The extra amount of DPS that you are able to output in this time frame can be the difference between life or death, or in the case of a xeno, whether to go for a killing slash or let you live and retreat so they can heal.
> 
> Usually its the latter, which lets you (who premedded) limp back to a corpsmen or to other marines to cover you, while the un-premedded marine dies or worse, gets combat dragged to brazil.
> 
> This is why neurotoxin is crucial, especially when you face experienced marine who use a similiar (or even better, for cases like Dolthgar) mix of chems. Neurotoxin levels the playing field for both competent and gamer level marines.
> 
> However I do agree the effect is a little too strong, especially for a T1 sentinel. Maybe make the effect less (less injection of the neurotoxin itself) for sentinel and keep it as is for the Prae since it IS a T3.
> 
> Just spit balling; outright removing chem purging just makes it a LOT more difficult to deal with marines who know what they are doing (especially when they unga ball).

If pre-medding is so strong, it should be limited in a way that isn't godlike without purge and useless with.

**Pull request closed without merging**
