### PR TITLE
Makes standard marine vendors unwrenchable

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Namely the clothing, armor, mech and youtool vendor.
## Why It's Good For The Game

These should not be something you should be able to bring groundside ever, they bring shipside level supply groundside at no cost.
## Changelog
:cl:
balance: Makes standard marine vendors unwrenchable
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
what did the youtool ever do to you?

**Comment by ivanmixo** [comment]
Not exactly a fan of infinite healing for the clankers groundside

**Comment by EvilMelonTheSecond** [comment]
So instead people should vend as much shit as they can and drag it with crates? I don't see the problem of having a vendor that needs power and is hard to drag around being deployed in FOB. Not sure if this will do more than add more prep time outside of very niche cases

**Comment by ivanmixo** [comment]
We should be consistent. One type of vendor being wrenchable while all the others aren't just because it's not as egregious is a bit silly.

**Comment by EvilMelonTheSecond** [comment]
> We should be consistent. One type of vendor being wrenchable while all the others aren't just because it's not as egregious is a bit silly.

That's a weak reason, the lasgun battery charger can move for QoL and youtool is not that different in practice. If you mean its because it has the sprite and title of a vendor those are easy changes to make to differentiate it. Throwing away functionality because of how it looks is not good reasoning.

**Comment by ivanmixo** [comment]
It is. Also the laser recharger thingy is very much meant to be movable, it was added with that in mind. Who in their right mind considers it a shipside vendor? Why would you recharge cells slowly when the weapons vendor is right there to vend fresh cells?

**Comment by lbnesquik** [comment]
How about removing their movement in the alamo or tadpole? That would achieve the same thing, but marines could still shuffle things around.

**Comment by Lumipharon** [comment]
> We should be consistent. One type of vendor being wrenchable while all the others aren't just because it's not as egregious is a bit silly.

I mean, most are still wrenchable, and the tool vendor is groundside as well

**Comment by chizzy376** [comment]
Absolutely not, bad PR.

**Comment by TellyLsc** [comment]
What's the problem with those vendors being dragged to planetside? 
Outside of the LZ FOBs and Tads it's really a pain in the ass to make sure the area APCs don't get slashed in the first place, so I don't buy "dragging it to the frontline and having infinite supply on the spot" bit.

And if the issue is that "the FOB has too many supplies" well isn't that what the FOB is supposed to be? These vendors don't even have the most essential part of FOB defense: ammo; other than welding fuel and TE Powerpacks, which then maybe just move them into the green vendors that are already unwrenchable then?
What else? Pre-filled flare pouches lighting up areas surrounding the FOB? That one isn't even an issue of "infinite flares" like in that other PR from couple weeks ago, it's just an issue of couple guys actually willing to flare areas and keep it lit up for once, I'd know because I was one of those guys and let me tell you: I only use flare pouches because it was a pain in the ass to right click flare packs inside backpacks (which could've carried 12*14 flares mind you instead of the pouch's 28) since you'd have to sprite-hunt the flare pack, you can't just right click the blank space around the sprite inside storage like you can with slot based storages like flare pouch, which REALLY adds up for how much of a chore spamming flare is because god forbid marines have autoflares like xenos have autoweed.
Alright what other thing then? Machete belts? Last time I left a pile of those on FOBs no one really picked them up. Prefilled BKTT reagent pouches? Yeah sure, because infinite BKTT really grinds FOB sieges to a halt by making marines unkillable as RR does. Oh wait, they don't.
Oh wait I get it, it's the protein pack belts isn't it?

I'll throw a bone here, how about making the vendors only movable by clicking on them with powerloaders/making dragging them to be VERY SLOW instead of making them unwrenchable?

**Pull request merged**
