### PR TITLE
Explosive Vest Engoodening

### PR DESCRIPTION
**Pull request by Ragecrabbo**
## About The Pull Request

Increases marine explosive vest explosion range from `(2, 2, 6, 7, 5, 5)` to `(3, 3, 6, 7, 5, 5)` increasing devastate and heavy explosion ranges by single tile while keeping everything else the same.
**(Yellow = Old, Red = New)**
boomie

Moves explosive vest from requisitions vendor to specialized section of marine weapons vendor.

Fixes incorrect description telling people to control-click vest to set warcry and now correctly mentions cloaking effects such as tarp or cloaking nades preventing use of vest.

## Why It's Good For The Game

The explosive vest has become weaker and weaker as a result of changes to how explosions work, from nuggeting the user to straight up gibbing them instead and with warding pheromones now affecting deva explosions even drone-tier pheros are enough to prevent a boiler from getting even crit by a point-blank explosion. Ontop of this simply moving to a diagonal position from the vester has been enough to completely invalidate the deva part of the explosion, making the vest as damaging as detonating a HE and incendiary grenade ontop of you while also completely removing the vester from the game. Increasing the heavy/deva range should give the vester more of a chance to actually cause some damage without praying that their target does not happen to move diagonally from them while also making it more effective in general (for blowing up both marines and xenos).

The reason for moving vest from req vendor to specialized section is to allow people to use it in loadouts and prevent certain people (me) from having to hack the req vendor at the start of every round.

## Changelog

:cl:
balance: Increases heavy and devastate explosion range of explosive vest by one tile
qol: Moved explosive vest from req vendor to specialized section of automated weapons rack
spellcheck: Fixed explosive vest description to accurately represent how it works ingame
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Vest being a thing at all is already questionable. I really don't think suicide mechanics should actually be viable, a marine's life is not the same worth as that of a xenos.

**Comment by SimplySmiley123** [comment]
> Vest being a thing at all is already questionable. I really don't think suicide mechanics should actually be viable, a marine's life is not the same worth as that of a xenos.

Someone's round removing themselves in an instant to deliver the mail.
IMO, at least they should be able to crit a xeno that decided to stay in hugging distance, but apparently that was and is too much.

**Comment by TiviPlus** [comment]
kuro man say no and i agree with ivan

**Comment by hivemuscle** [comment]
at this point just make vest an optional armor storage module: no shovel, wires and sandbags for you but you can go boom

**Pull request closed without merging**
