### PR TITLE
Tactical Wedding Gear

### PR DESCRIPTION
**Pull request by Jackal-boop**
## About The Pull Request
adds wedding dresses to the surplus clothing vendor
## Why It's Good For The Game
tactical battle dresses!
## Changelog
:cl:
add: adds dresses to the surplus clothing vendor
/:cl:

### CODE REVIEW

**Comment by Bluedino1025** [comment]
we are so back

**Comment by Jackal-boop** [comment]
why

**Comment by yyzsong** [comment]
Reopen and merge this pr immediately

**Comment by Bluedino1025** [comment]
it is so over

**Comment by DeltaFire15** [comment]
I salute your courage.

**Pull request closed without merging**
