### PR TITLE
Allows respawning into EORD directly

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
image
For some reason, you can only spawn into EORD wjhen you are ghosted. If you are like me, and you do not always want to get roped into the stuff, that can be a little annoying, as a bit of the fun if that is testing your loadout on people. 

This PR (hopefully) makes it possible. I made it by simply removing the living check of the verb, and slapping a cooldown I stole from code down below.  The timer is here to avoid people being able to spam endless hordes of EORD'd people. Kept it short to avoid it taking you out of the fun. Still plenty of time to die. 

I did NOT test it, given I couldn't figure out how to start a proper running game without it ending instantly, ya know? But it should work? 

## Why It's Good For The Game
Lets you jump into EORD at willing instead of having to ghost to spawn in. I think. 

## Changelog

:cl:
add: Made it possible to spawn into EORD without ghosting. 
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
I managed to test it, and it works!

**Comment by Joe13413** [comment]
yo is there any way to prevent valhalla nerds from spawning into EORD with B18 + sadar and whatnot?

**Comment by lbnesquik** [comment]
> yo is there any way to prevent valhalla nerds from spawning into EORD with B18 + sadar and whatnot?

They could, but I think they'll just get mulched.

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Doesn't this make it so you can already respawn into eord while being in eord?

**Comment by lbnesquik** [comment]
> Doesn't this make it so you can already respawn into eord while being in eord?

Yes, but the timer prevents a ton of spawning. Given the limited duration, I honestly think this is a good thing.

**Comment by ivanmixo** [comment]
I'd refrain.

**Comment by Lumipharon** [comment]
> > yo is there any way to prevent valhalla nerds from spawning into EORD with B18 + sadar and whatnot?
> 
> They could, but I think they'll just get mulched.

People go out of their way to prep in valhalla and brag about how they're gonna stomp on people in eord with b18, invisibility and pepperball spam. This'll just let people do that repeatedly, or flood eord with 1 million bodies by spamming a button.

**Comment by lbnesquik** [comment]
They can't load the gear that quick, honestly, if some kitted out dude joins every 1-2 minutes, given the short time of the EORD, it's really not a big deal. It's not like there's much of an experience to ruin!

**Pull request closed without merging**
