### PR TITLE
Removes meme and /tg/ music from rotation.

### PR DESCRIPTION
**Pull request by DominikPanic**
:cl: LaKiller8
sounddel: Removes meme and /tg/ music from rotation.
/:cl:

### CODE REVIEW

**Comment by Firecage** [comment]
Whats the point of this PR?

**Comment by Hughgent** [comment]
Space Hero best anyways.

**Comment by Ghommie** [comment]
Made exception of the clown one, none of them is really a meme.
It would be a sad day if you removed the robocop mix.

**Comment by optimumtact** [comment]
you won't get away with this

**Comment by DominikPanic** [comment]
> 
> 
> you won't get away with this

You have no power here, juice man.

**Comment by Qustinnus** [comment]
but I do

**Pull request closed without merging**
