### PR TITLE
Smartgun Resprite

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Resprites the Smartmachinegun.
Sprite entirely by me, beyond the magazine which is a recolor.
image
## Why It's Good For The Game
Makes the sprite not ancient and updates the gun to our pallete.
## Changelog
:cl:
imageadd: New Smartmachinegun icon by me.
imagedel: Deleted old Smartmachinegun icon.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
Probably would be good to put the full name in the PR Body/Title so there's no confusion in further resprites of the SG line.

**Comment by 00ze-cyclone** [comment]
bro what the fuck is this discount MG27?

**Comment by yyzsong** [comment]
t27 w/blue IFF sticker

**Comment by iforgotmeword** [comment]
going to be real i liked the old one better

**Comment by DrAmazing343** [comment]
yeah honestly I'm not sold on this one

**Comment by Lumipharon** [comment]
This looks like it's just the mg42 with the mg27 barrel

**Comment by Pariah919** [comment]
e

**Pull request closed without merging**
