### PR TITLE
Fixes aheal not getting rid of larva

### PR DESCRIPTION
**Pull request by DominikPanic**
Fixes: #1981

### CODE REVIEW

**Comment by psykzz** [comment]
Can you also add a proc to impregnate a host?

**Comment by DominikPanic** [comment]
> 
> 
> Can you also add a proc to impregnate a host?

:noerp:

**Comment by psykzz** [comment]
This is Github dont bring your erp drama here

**Comment by DominikPanic** [comment]
oof

**Comment by psykzz** [comment]
More serious though, is it in scope for this PR to handle all aspects of larva for admins?
Adding / remove / changing stage?

**Comment by DominikPanic** [comment]
> 
> 
> More serious though, is it in scope for this PR to handle all aspects of larva for admins?
> Adding / remove / changing stage?

This is best done through VV really, I don't feel like this needs an admin tool.
Spawn a facehugger to hug someone, mess with the stages via VV. Not everything needs admin buttons, else there would be no point to even having VV.

**Pull request merged**
