### PR TITLE
Survivor Gets Master In Non-Combat Skills

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Survivor gets master in non combat skills.

## Why It's Good For The Game

Survivor is masochistic already, why not give them a little something to slightly increase their chance of making it out alive as well as giving the marines a reason to rescue survivors.

## Changelog
:cl:
balance: Survivors get master in non combat skills.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Rohesie** [comment]
Make a different survivor type instead.

**Comment by Isy232** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/3290

**Comment by Isy232** [comment]
I messed this one up, made a new one

**Pull request closed without merging**
