### PR TITLE
Removes banish

### PR DESCRIPTION
**Pull request by chizzy376**
## About The Pull Request
Because turns out having the ability to single out any marine and make them zzz 33% of their playtime, cades and items for long periods of time isn't fun or balanced at all, especially at the low cooldown.
Right now a wraith can banish you, place a teleport under you, drag you as soon as you come from the banish and pull your dropped item through the teleport with absolutely no way of counterplay! With this change it will actually take skill to commit to this combo, being a high risk high reward instead of no risk instant reward.
~~Unless someone addresses the issue of a wraith being able to single out any marine and teleport them 20 tiles away anywhere they want without any **counterplay**, this is a good change for the time being.~~ oops im a boomer
## Why It's Good For The Game
Makes the game more balanced by removing a frustrating and unfair ability from an already annoying caste.
## Changelog
:cl:
balance: removed the ability "banish" from the wraith caste
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
Wraith isn't even that good, literally just shoot it, or STAY NEAR YOUR TEAMMATES. Wraith punishes people who stray off alone.

**Comment by Xander3359** [comment]
LOL You aren't even properly deleting the ability. You are leaving all references to it still up.
Did you not even try to compile your code?

**Comment by chizzy376** [comment]
> Wraith isn't even that good
it is lol
> literally just shoot it
can't shoot something behind walls
> or STAY NEAR YOUR TEAMMATES
he thinks that my teammates will save me
> Wraith punishes people who stray off alone.
no i literally spoiled THE wraith tech to single out any marine, read the pr description before commenting

**Comment by Aporhtonoma** [comment]
omega levels of salt pr might as well delete wraith next my dude

**Comment by chizzy376** [comment]
> LOL You aren't even properly deleting the ability. You are leaving all references to it still up. Did you not even try to compile your code?

What the fuck is a compile
I'm just deleting the garbage

**Comment by chizzy376** [comment]
> omega levels of salt pr might as well delete wraith next my dude

If this pr passes I'll do it next yes

**Comment by SomeDongus** [comment]
average marine main

**Comment by chizzy376** [comment]
> average marine main

average xeno main does the same but to marines, this is just basic open-source github

**Comment by novaepee** [comment]
image

**Comment by chizzy376** [comment]
> image

This only proves that wraith is a bad caste and a removal is in order

**Comment by zuneshine** [comment]
It doesn't qdel people, it banishes them. It's a temporary displacement where you come out stunned at the end, sure, so wraith with teammates can set you up for a world of pain. Such as shrike, crusher, warrior, etc. All of these are horrifying teammates with wraith picking off marines with banish to set them up.

Wraith impact on a round is heavily dependent on the person playing it and their grasp on what they can banish, portal, etc. They can't banish crew guns to teleport them around because they're fixed in place. It is the most high skill ceiling caste in the entire game. It's fine if it has that impact because it requires good timing and skill, as well as really unresponsive marines, to pull off most of the gamebreaking stuff anyway.

Also the idea that you can drag mobs through portals is a literal lie and it hasn't been this way for months

**Comment by Pariah919** [comment]
While personally I think  banish with something this is kind of a cringe salt PR.

**Comment by blackdav123** [comment]
Right now a wraith can banish you, place a teleport under you, drag you as soon as you come from the banish and pull you through the teleport with absolutely no way of counterplay! With this change it will actually take skill to commit to this combo, being a high risk high reward instead of no risk instant reward. Unless someone addresses the issue of a wraith being able to single out any marine and teleport them 20 tiles away anywhere they want without any **counterplay**, this is a good change for the time being.

this isnt possible stop making shit up

**Comment by chizzy376** [comment]
> It doesn't qdel people, it banishes them. It's a temporary displacement where you come out stunned at the end, sure, so wraith with teammates can set you up for a world of pain. Such as shrike, crusher, warrior, etc. All of these are horrifying teammates with wraith picking off marines with banish to set them up.

It teleports you into a place you can't get out of unless the timer on the ability ends, effectively qdeling you out of the fight for an extended period of time



> Also the idea that you can drag mobs through portals is a literal lie and it hasn't been this way for months

I am a boomer it used to be this way back in my days

**Comment by novaepee** [comment]
image

**Comment by Xander3359** [comment]
>Making a PR based on how a ability used to function, and not based on how it currently fuctions.
😂

**Comment by Barnet2** [comment]
Sanest TGMC player, we have reached new heights people!

**Comment by blackdav123** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10434 removed marines going through portals

**Comment by yyzsong** [comment]
> > LOL You aren't even properly deleting the ability. You are leaving all references to it still up. Did you not even try to compile your code?
> 
> What the fuck is a compile I'm just deleting the garbage

compile = your code works at all

**Comment by chizzy376** [comment]
> compile = your code works at all

ah shit

**Comment by chizzy376** [comment]
I'll return stronger than ever I promise

**Comment by zuneshine** [comment]
"What the fuck is a compile"

C'mon, man.

**Comment by chizzy376** [comment]
> "What the fuck is a compile"
> 
> C'mon, man.

Do I look like a coder to you look at my PR's
I'm using the github web app to do everything, even map changes where I meticulously single out a line in the 200k .dmm folder

**Comment by novaepee** [comment]
skill issue

**Comment by chizzy376** [comment]
> skill issue

Buzzword issue

**Comment by zzurge** [comment]
FINALLY WRAITH GAMING WILL ONCE AND FOR ALL COME TO AN END

**Comment by Derrick2Electricboogaloo** [comment]
Based, reopen.

**Comment by Derrick2Electricboogaloo** [comment]
Just remove wraith, simple as. No more bullshit caste.

**Comment by KillerOrcaCora** [comment]
man I miss the circus PR

**Comment by SomeDongus** [comment]
> Just remove wraith, simple as. No more bullshit caste.

unknown

**Comment by ClosetedSkeletonGH** [comment]
> It doesn't qdel people, it banishes them. It's a temporary displacement where you come out stunned at the end, sure, so wraith with teammates can set you up for a world of pain. Such as shrike, crusher, warrior, etc. All of these are horrifying teammates with wraith picking off marines with banish to set them up.
> 
> Wraith impact on a round is heavily dependent on the person playing it and their grasp on what they can banish, portal, etc. They can't banish crew guns to teleport them around because they're fixed in place. It is the most high skill ceiling caste in the entire game. It's fine if it has that impact because it requires good timing and skill, as well as really unresponsive marines, to pull off most of the gamebreaking stuff anyway.
> 
> Also the idea that you can drag mobs through portals is a literal lie and it hasn't been this way for months

>high skill

1) create portal in areas marines can’t reach like big red/swagmoor Gen machines or another out of bounds place

2) banish marines

3) create a portal on their items

4) watch as anything dropped is permanently removed from the entire game

This has been pretty much the entirety of good wraith plays, just removing any held item from the round that isn’t magharned if no one can shotgun them fast enough

**Comment by henriquekill9576** [comment]
i think its best if you stop replying my dude, you're digging your hole even deeper with each post

**Comment by chizzy376** [comment]
> i think its best if you stop replying my dude, you're digging your hole even deeper with each post

What

**Pull request closed without merging**
