### PR TITLE
Smart Minions by default

### PR DESCRIPTION
**Pull request by tanker4390**
## About The Pull Request
Smart Minions is enabled for by default.  
## Why It's Good For The Game
From my experience, Smart Minions is almost never purchased, and minion spawners are not always purchased. Even when Smart Minions is purchased, it may be ignored or overlooked in favor of spawning a larva, potentially wasting its purchase. I don't think it is such a huge advantage over AI-controlled minions, since they are slightly robust, and even if it is better than some of the AI's shortcomings, such as getting stuck, these aren't intended anyway.
## Changelog
:cl: Tanker
balance: Smart Minions is now enabled by default.
/:cl:

### CODE REVIEW

**Comment by zee11zee** [comment]
Ok now this is a win for minion mains

**Comment by ClosetedSkeletonGH** [comment]
Y'all arent ready for me, certified beet main

**Comment by Kapu1178** [comment]
i didnt even know this was a thing

**Comment by novaepee** [comment]
#9115 made player-controlled minions a hive blessing choice. At the time, xenomorphs used player-controlled minions to defeat marines en masse, and Bravemole, both coder of minion and prior maintainer for TGMC, decided to stop the minion rampage. It would be a tall order to get this PR merged, but I for one welcome it.

**Comment by Al-1ce** [comment]
This might require some tweaking to the overall minion spawn-rate, since a ghost army of beetles will absolutely demolish the marines. Limiting the amount of spawners is a good start.

**Comment by Al-1ce** [comment]
Limiting the amount of buildable spawners will probably bandaid most the balance issues regarding this.

In any case - smart minions being default has been a long time coming.

**Review by ivanmixo — CHANGES_REQUESTED** [review]
You forgot the `GHOSTS_CAN_TAKE_MINIONS` flag

**Review by ivanmixo — APPROVED** [review]

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Undocumented change limiting spawners. I don't think it's necessary at all considering there's a cooldown to taking a new minion anyway.

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
