### PR TITLE
laser pistol can be held in shoulder holster, and pistol belts can hold 6 lasgun mags

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title, basically.

## Why It's Good For The Game
Makes the laser pistol more useable, rather than being complete trash to use and carry.

## Changelog
:cl:
fix: laser pistol fits in shoulder holster
balance: pistol belts can hold 6 lasgun magazines
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
energy weapon users rejoice, now a better alternative to mag belt

**Comment by Kuro020** [comment]
+1 for this pr, laser gun is literally unusable, the pistol belt only takes TWO mags, and the web holster doesnt even accept it

**Comment by Lumipharon** [comment]
Wouldn't this make the pistol belt better than a mag belt for laser ungas? 7 mags, including one with a gun attached.

**Comment by AndroidMK2** [comment]
Energy weapons are a newbie trap if you ask me, nice pr and hopefully we get a buff to them.

**Comment by Frampox** [comment]
So i got a free pistol slot(not a laser pistol) for my laser gun.

**Pull request merged**
