### PR TITLE
Greyscale jaeger

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

further stuff to be explored after this
-glowing visor emissive
-more colors?
-Jaeger vendor
  -Color wheel jaeger painting for super customizing
  -Visor painting

## Changelog
:cl:
qol: Jaeger can now be painted hot pink
refactor: Jaeger is now greyscale
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
ah yes the rise of the pink marines,this is where the fun begins

**Comment by TiviPlus** [comment]
> ah yes the rise of the pink marines,this is where the fun begins

image

**Comment by ilikesaying** [comment]
it is crayon vomit time

**Comment by XSlayer300** [comment]
inb4 gradient tint

**Review by SplinterGP — APPROVED** [review]

**Pull request merged**
