### PR TITLE
nerf puppeteer and puppets

### PR DESCRIPTION
**Pull request by SomrNetwork**
## About The Pull Request
nerfing puppeteer and puppets
## Why It's Good For The Game
lower the heavy amounts of xope
## Changelog
🆑 
code: reduced puppet damage to 9
code: reduced puppet health by 50
code: reduced puppeteer puppet amount to 3 and 4 for primo
/ 🆑

### CODE REVIEW

**Comment by SomrNetwork** [comment]
me when I accidentally add the skirt commit into a nerf

**Comment by Lumipharon** [comment]
Can you please not nerf everything at once? Choose one thing to nerf and see how it goes, because you're comically nerfing their puppet dps by more than 60% on top of having dramatically less total ehp.

**Comment by SomrNetwork** [comment]
> Can you please not nerf everything at once? Choose one thing to nerf and see how it goes, because you're comically nerfing their puppet dps by more than 60% on top of having dramatically less total ehp.

so say for example

nerf puppeteer puppet capacity first
end
nerf puppet damage to 9
end
nerf puppet health to 200
and then mix them all together in one round and see how it goes from there?

**Comment by Oscari-pog** [comment]
Massive Marine cope pr lmao

**Comment by Lumipharon** [comment]
> > Can you please not nerf everything at once? Choose one thing to nerf and see how it goes, because you're comically nerfing their puppet dps by more than 60% on top of having dramatically less total ehp.
> 
> so say for example
> 
> nerf puppeteer puppet capacity first end nerf puppet damage to 9 end nerf puppet health to 200 and then mix them all together in one round and see how it goes from there?

No, it means don't nerf it into the ground to the point its clearly going to be bad. Reduce it slightly because more prs can always be made if a change isn't sufficient.

**Comment by SomrNetwork** [comment]
> > > Can you please not nerf everything at once? Choose one thing to nerf and see how it goes, because you're comically nerfing their puppet dps by more than 60% on top of having dramatically less total ehp.
> > 
> > 
> > so say for example
> > nerf puppeteer puppet capacity first end nerf puppet damage to 9 end nerf puppet health to 200 and then mix them all together in one round and see how it goes from there?
> 
> No, it means don't nerf it into the ground to the point its clearly going to be bad. Reduce it slightly because more prs can always be made if a change isn't sufficient.

I understand, I'll see if I can reduce it to a reasonable number

**Comment by Aporhtonoma** [comment]
I like puppeter too much so i might be biased but ill drop my piece here

puppeter is a snowball heavy caste.Half the cast is his economy with biomass/puppets.If he takes a fight that actually yields them less biomass than what they lost (usually 1 death is more than enough) then he is kinda murked.The thing with his economy is that he gets more bio the more damage he does (excluding this flay which gives 100 flat (which is not enough for a puppet)).So with this not only you are nerfing his damage but you make the puppets harder to aquire too by gutting their damage currently.
also people keep saying that his puppets are tanky and do more damage but those same people loadouts are usually heavier armors and single shot guns like damage which are good against 1v1s situations.While one flame grenade or hell even 1 frag will basically cripple if not kill all the puppeters puppets.Also being a relatively squishy caste you are very depented on your puppets to even get a flay to restart your economy.
Sorry to say so flat but most people who are saying its overpowered are the same people that the caste excells with dealing with those being people going alone or flatout getting ambushed/getting caught alone.
my point here is gutting his economy by 33% (not counting the total puppet reduction part) is already too much for a caste that can already be basically gutted by someone who brought even a small amount of aoe damage.especially for a caste that is depentent on snowballing and cant rebuild itself as easy as conventional castes.
besides that as i said i like the caste for what it is and i might be biased but i find it silly people screaming nerf it because of damage and making it out to be theres no way to deal with it

**Comment by bowlofcereal** [comment]
bro why are you fucking obliterating everything about the caste in a single pr lol

the whole point of the caste is ambushing lone marines and fucking them up for being cocky and going off alone, this is destroying more more than 50% of its DPS, please do not merge this holy shit

i have been aware of some flaws in the caste but this is *not* the way to fix it, you need to dripfeed this stuff with testing

**Comment by technicianman** [comment]
the caste's dps is enough to kill a tyr 2 harmor user faster then he can even respond

**Comment by Lumipharon** [comment]
Other pr up that just cuts puppet numbers

**Pull request closed without merging**
