### PR TITLE
Pre shotgun nerf

### PR DESCRIPTION
**Pull request by ZanderDowdall**
## Why It's Good For The Game

Most players dont like the new Jaeger armour stuff that got merged, and noone seems to be bothered to make a PR to revert, so here I am

## Changelog
:cl:
Literally just old files of before the shotgun nerf. I think thats when this is from, but if its from earlier then I can download and re-PR whatever was added
/:cl:

### CODE REVIEW

**Comment by ZanderDowdall** [comment]
90% chance Ive already fucked something here lads so, at the very least comment here to say that you want this shit undone

**Comment by ZanderDowdall** [comment]
Well, from what I can see this does fix it back to before, someone correct me if Im wrong please and tell me how to fix

**Comment by spookydonut** [comment]
Unclear on what you're trying to do here

**Comment by XSlayer300** [comment]
image
image
Pretty sure this is not a shotgun, but since you screwed up at one point, I guess we dunno what you actually did with the shotgun. if you need help, ask the discord chat view #dev-general or #coding. We also have #4511 soo...

In addition, changelog seems to be screwed up a bit.

**Comment by spookydonut** [comment]
no author response

**Pull request closed without merging**
