### PR TITLE
Remove sec gear from ice colony + replace all guns by tiered weapon spawner

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Title

## Why It's Good For The Game

Prevent from having sniper or shotguns in HvH

## Changelog
:cl:
balance: Remove sec gear from ice colony + replace all guns by tiered weapon spawner
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
Why sec gear

**Comment by BraveMole** [comment]
> Why sec gear

flashbangs, flash, etc. are op

**Comment by SplinterGP** [comment]
> 
> 
> > Why sec gear
> 
> flashbangs, flash, etc. are op

marines cant use those you know right ? only synth and stuff can but they shoulndt be on battle, for self defense itd be fine

**Comment by TiviPlus** [comment]
What splinter said

**Pull request closed without merging**
