### PR TITLE
Old EORG is back, as a modular map!

### PR DESCRIPTION
**Pull request by XSlayer300**
## About The Pull Request
Re-adds the old EORG arena before #4473 as one of the selectable modular map options.

## Why It's Good For The Game
Nolstalgic reasons.

## Changelog
:cl:
add: The old EORG map now has a chance to spawn as an EORG arena!
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -36. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by XSlayer300** [comment]
augh hold on, did not mapmerge.

**Comment by XSlayer300** [comment]
Let's try this again...

**Review by TiviPlus — APPROVED** [review]

**Review by SplinterGP — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-34). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
