### PR TITLE
Broken CM vendor and old armors

### PR DESCRIPTION
**Pull request by SomrNetwork**
## About The Pull Request
Adds a broken CM vendor that includes a **few** CM armors and PAS! Note: this is not located anywhere in maps, possible admin spawn required until someone or I place it maints
## Why It's Good For The Game
A sense of nostalgia (possible) and adds a new set of armors so that marines wouldn't have to stick with BORING old JAEGAR and XN for 20 more years
## Changelog
🆑 
add: Broken CM vendor
add: CM medium, light, heavy and PAS
code: Armor assets are located at the bottom of marine_armor.dm and helmet.dm
code: Vendor is located in vending.dm
imageadd: marine_clothing_broken_CM
imageadd: CM armors and helmets
/🆑 

image
image

### CODE REVIEW

**Comment by SomrNetwork** [comment]
"old armors" just being PAS

**Comment by Oscari-pog** [comment]
PAS the return, at last

**Comment by zee11zee** [comment]
Very cool

**Comment by Kuro020** [comment]
>CM Sprite

Lol, lmao even

**Comment by AnotherNobodie** [comment]
Pain, Missouri

**Pull request closed without merging**
