### PR TITLE
Nerfs Shields melee/acid resistances and shield melee coverage overall

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Non-Deployable shields now have 10% less melee and 5% less acid resist.
Dropped melee coverage from 80 to 50.
## Why It's Good For The Game
Shields give you an absurd amount of effective HP in their current state, I think reducing their resist is a good change. 10% melee reduction and 50% melee absorption is a noticeable amount, but should still keep the shield as a viable option.

## Changelog
:cl:
balance: Shields have lost 10 melee armor, and 5 acid armor. As well as dropping melee coverage from 80 to 50.
/:cl:

### CODE REVIEW

**Comment by srxtreme** [comment]
Deployable shields are nice for using in field as cades (for emplaced weapons). I'd suggest obiliterating their shield stats in hand if possible but keeping them in vendor.

**Comment by Coastfront** [comment]
Because stuns are a myth and raw damage is the only way to defeat marines.

**Comment by Guidesu** [comment]
We already had this PR already and it was denied.
MJP moment

**Comment by Guidesu** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/11430

**Comment by Tupinambis** [comment]
Marines are tanky but can't wield most weapons, that's the balance. This is silly and nerfs melee marines (a fairly niche play style) a ton.

**Comment by Tailiik** [comment]
Heavy armor vali marine with a shield getting gangbeat by 8 xenos and limping away spinclapping: "They simply were not skilled enough to kill me"

**Comment by ClosetedSkeletonGH** [comment]
> Heavy armor vali marine with a shield getting gangbeat by 8 xenos and limping away spinclapping: "They simply were not skilled enough to kill me"

I wish this was a joke but we once had a hunter, warrior, and me as shrike continue to stun a shield marine over and over while just beating down on them and preventing them from escaping (they were solo and no other marines were nearby). It took over a minute of them trying to get away while being chain stunned by all our abilities and they had ~60% health for pretty much the whole fight. It was honestly ridiculous and everyone by the end of the fight was pissed off that it took us so long to kill them with 2 DPS castes and a T4. 

I love shielding, its a key component to my strat when I tower. This just locks it behind 10 points and is a very valid change imo

Its not like its removing it from the game/going to get stuck behind 2,000,000 optical imager orders

**Comment by Durbles** [comment]
The hand shield is already limited, only about 5-6 in the vendor. Using it practically sacrifices most of a marines offensive capabilities. The whole point is that it defends well against slashes and acid. Xeno chems FUCK a shield user though.
TL;DR, krill issue

**Comment by Lumipharon** [comment]
@Pariah919 This does not do what you think it does.

**Comment by Pariah919** [comment]
> @Pariah919 This does not do what you think it does.

It does exactly what I think it does, I just screwed up my PR description. I lowered coverage now.

**Comment by chizzy376** [comment]
Bad PR, sacrificing 1 hand for defense is a lot. Making them even worse just means they'll be untouched by everyone. No reason to merge this, as xenos have many ways of dealing with MARINE damage sponges. (Unlike the MP which can not be stunned, blinded, rooted, flung, thrown, etc.) Shield users are already pretty vulnerable.

**Comment by Coastfront** [comment]
Just for the sake of it, here are some very common ways to kill a shield user:
Stun into defiling them (most shield users premed, this will delete a majority of their hp if they did so.)
Spitter acid pools still burn & stun them, regardless of shield use (to the point where, on one of my first rounds as spitter, all i needed was another spitter to just slip somebody with a shield and tear them to shreds)
Boiler clouds, though this is impractical.
Widow, by sheer volume of damage from the spiderlings, can also pretty quickly get through their hp and damage the shield to uselessness
Sentinel acid DOT still applies, which you can also constantly shuffle them/use other xenos to interrupt removal of the acid stacks

Every mail coat has its needle gaps. 
Xenos have several means of damage that just outright ignore armor against human enemies, and only a single one of the caste's mentioned are hard countered by the sidegrade to human (combat robots arent immune to boilers, spitters, etc.)

Shield users, are very killable to the right caste's, and if we want to argue "BUT MARINES HAVING THINGS THAT ARE ONLY COUNTERED BY X CASTE IS ROCK PAPER SCISSOR BALANCING" then remove mimir aswell because mimir hardcounters several of the things mentioned here, except doesent give you the same offensive weakness as attempting to climb a mountain with a 30 pound weight on your ankles gives to your speed. There, barring an oversight in game balance, not many one handed weapons that let you kill a xeno in 1-2 magazines or less, vs 2 handed weapons that do. The revolver is one of few exceptions, though revolver juggling is horrifically strong regardless of if you shield build or not.

**Review by Lumipharon — APPROVED** [review]

**Comment by Lumipharon** [comment]
I think a 50% damage reduction is still pretty huge, but lets take a look.

**Comment by chizzy376** [comment]
If you actually do think about merging this for real, I'd suggest an increase in stun resistance to offset the nerf.

**Comment by Araulius** [comment]
> If you actually do think about merging this for real, I'd suggest an increase in stun resistance to offset the nerf.

shield already makes you immune to pounce

**Comment by chizzy376** [comment]
> > If you actually do think about merging this for real, I'd suggest an increase in stun resistance to offset the nerf.
> 
> shield already makes you immune to pounce

1 stun out of 50. Here's what it makes you NOT immune to. Boiler/spitter ground acid. Shrike fling. Shrike screech. Queen screech. Entirety of crusher (bull too). Gorger stun. 
Being immune to 1 (one) T1 stun is not it, chief.

**Comment by Redrover1760** [comment]
> > > If you actually do think about merging this for real, I'd suggest an increase in stun resistance to offset the nerf.
> > 
> > 
> > shield already makes you immune to pounce
> 
> 1 stun out of 50. Here's what it makes you NOT immune to. Boiler/spitter ground acid. Shrike fling. Shrike screech. Queen screech. Entirety of crusher (bull too). Gorger stun. Being immune to 1 (one) T1 stun is not it, chief.

And also it doesn't even block hunter pounces either. Literally ONLY runner pounces.

**Comment by Joe13413** [comment]
> > > > If you actually do think about merging this for real, I'd suggest an increase in stun resistance to offset the nerf.
> > > 
> > > 
> > > shield already makes you immune to pounce
> > 
> > 
> > 1 stun out of 50. Here's what it makes you NOT immune to. Boiler/spitter ground acid. Shrike fling. Shrike screech. Queen screech. Entirety of crusher (bull too). Gorger stun. Being immune to 1 (one) T1 stun is not it, chief.
> 
> And also it doesn't even block hunter pounces either. Literally ONLY runner pounces, as I've found out.

bro i literally got blocked by a shield like 2 rounds ago what the hell are you saying (as hunter). also shield only blocks pounces if you're facing the xeno btw

**Comment by maikilangiolo** [comment]
After using new shield a bunch, I don't like this change. Either reduce only coverage, or only the resistance, both is overkill when shield already forces you to use one handed weapons, and only those that can be tac reloaded, so not even the strongest ones (no revolver for example).

**Comment by Redrover1760** [comment]
> > > > > If you actually do think about merging this for real, I'd suggest an increase in stun resistance to offset the nerf.
> > > > 
> > > > 
> > > > shield already makes you immune to pounce
> > > 
> > > 
> > > 1 stun out of 50. Here's what it makes you NOT immune to. Boiler/spitter ground acid. Shrike fling. Shrike screech. Queen screech. Entirety of crusher (bull too). Gorger stun. Being immune to 1 (one) T1 stun is not it, chief.
> > 
> > 
> > And also it doesn't even block hunter pounces either. Literally ONLY runner pounces, as I've found out.
> 
> bro i literally got blocked by a shield like 2 rounds ago what the hell are you saying (as hunter). also shield only blocks pounces if you're facing the xeno btw

Ohhhhhhhhh

ok thanks

**Comment by pilotmans** [comment]
Xeno cope lol

**Comment by zzurge** [comment]
Unnecessary

**Pull request merged**
