### PR TITLE
Reduces sunder spam.

### PR DESCRIPTION
**Pull request by Aquilar**
## About The Pull Request

This PR removes or reduces sunder of many frontline weapons

My explicit intention is try and push sunder to be more of a support weapon stat.
 I want sunder to be for helping marines burst down tanks with an opening with support tools such as say a rocket, a smart gun, DMR or laser weapons, therefore letting the rest of the group do more damage, rather than having sunder spread out as a stat on many different weapons.
 
 so with sunder being more rare, sunder heals will get a slight nerf too.

AP ammo for these is left untouched
Ammo types with sunder removed:
bullet/rifle
bullet/rifle/hv
bullet/pistol
bullet/pistol/tiny
bullet/pistol/hollow
bullet/revolver
bullet/smg
bullet/shotgun/slug
bullet/shotgun/incendiary
bullet/shotgun/tx15_slug
bullet/minigun

Ammo types with sunder reduced
bullet/rifle/heavy
bullet/rifle/mpi_km
bullet/rifle/standard_br

Ammo types with sunder added:
bullet/rifle/machinegun since parent lost it.

includes minor fix on bullet/revolver/tp44

edit: added additional penetration to guns that lost sunder, nerfed hivelord sunder  healing

## Why It's Good For The Game

Penetration stat exists to support these weapons, many of these ammo types had either good damage stats, good penetration stats, stuns or all three, sunder just added extra on top of the good performance resulting in a cavalcade of issues for any weapons that had good gun performance. 
In removing and reducing sunder on these ammo types is allows support orientated weaponry to have more value and impact which all have good or amazing sunder stats already. 
On the same note, this allows tankier xenos to make use of their armour against smaller groups and flanks while it'll still melt when trying push the main line since they don't have to worry about their armour being nullified by in the first few moments of engagement.

## Changelog
:cl:
balance: Hivelord sunder healing nerfed
balance: Many rifles, pistols, revolvers, SMGs and LMGs lose sunder or have it reduced, penetration values increase to compensate them.
balance: Shotgun slugs no longer have sunder, penetration value increased to compensate. 
balance: Minigun (not SG minigun) loses sunder, increases penetration values to compensate.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Straight nerf is a bit much but a good step towards a sunder rework (if you have one in mind).

Imo, compensate with some pen stats as a lot of guns also reduce their time to kill with the help of Sunder.

**Comment by Aquilar** [comment]
> Straight nerf is a bit much but a good step towards a sunder rework (if you have one in mind).
> 
> Imo, compensate with some pen stats as a lot of guns also reduce their time to kill with the help of Sunder.

adjusted values as requested.
well what I have in mind is just reeling in sunder and keeping as a statistic for support weaponry, basically anything that has to hang out behind the frontline providing support fire, and also lasers because they need something keep relevant sorry can't think of a valid reasoning for them other they're lasers.

**Comment by lbnesquik** [comment]
I feel like slug giving sunder just makes sense

**Review by Pariah919 — CHANGES_REQUESTED** [review]
```
bullet/rifle
bullet/rifle/hv
bullet/pistol
bullet/pistol/tiny
bullet/pistol/hollow
bullet/smg
```
Pistols, SMGs, and Intermediate caliber Rifles have sunder but very low to effectively cause xenomorphs to have to retreat and also cause sunder regen to cease and thus up the effective sunder of the entire marine force by allowing massed fire to eventually break armor, and buffing their overall penetration seems even dumber considering 5 pen is made to be the baseline overall, and you're increasing it to 10.
```
bullet/revolver
```
Revolver has high sunder because its supposed to be the handcannon of the marine sidearms of high risk high reward due to incredibly low capacity for marine standards.
```
bullet/shotgun/slug
bullet/shotgun/incendiary
bullet/shotgun/tx15_slug
```
Slugs have too high sunder, but removing it entirely is a sledgehammer nerf even I can't agree with and that's saying a lot personally. They should have passable sunder, and most high damage weapons should have their sunder decreased and more evenly spread around to DPS weapon and crew weapons where they already have been overall.
```
bullet/minigun
```
lmao what why are you nerfing the minigun its fine


All I see you doing is removing sunder as a mechanic from the cries of people who have never followed the sunder balance pipeline and believe it was added just yesterday when the values have never ever changed on 95% of guns because most of them are entirely non issue, most firearms have a fine level of sunder outside of edge cases like slugs and moving all of the sunder overall to penetration which is a bad change since penetration and sunder are entirely different game mechanics in how they are applied and should function.

**Comment by MrSerpentarius** [comment]
Making unpopular guns more trash and making meta guns more preferable is bruh

**Comment by Losenis** [comment]
I remember a video of a test of someone shooting at a defender with and without bursts on his guns. I'd post it if I could find it, but the difference was absolutely atrocious to the point the defender was effectively immortal.

If you want to nerf sunder, make the sunder regen for xenos faster so that sunder pileup still affects the engagement but doesn't last for the next 5. Nerfing sunder from guns will make armor-heavy castes like crusher and defender absolute aids to deal with on top of making primo queen charging even more difficult to take down even if you bait it into razorwire.

**Comment by Losenis** [comment]
Also it's good form to actually present math on how many rounds it'll take to kill pre and post change. Do us a favor and test how many T12 rounds it'd take to kill an ancient defender on fortify without sunder and with sunder, given the video seems to be lost.

**Comment by Losenis** [comment]
I actually found the video


https://user-images.githubusercontent.com/72712909/195152796-81f5c696-c29a-456b-9ce8-9fe61447ae7d.mp4

**Comment by Aquilar** [comment]
> 

specifically for you

without fortify
25 rounds to kill ancient defender with pre nerf AR-12
16 rounds to kill ancient defender with pre nerf BR-64
5 rounds to kill ancient defender with pre nerf SH-35

with fortify 
70 rounds to kill ancient defender with pre nerf AR-12
34 rounds to kill ancient defender with pre nerf BR-64
8 rounds to kill ancient defender with pre nerf SH-35

without fortify
23 rounds to kill ancient defender with post nerf AR-12
16 rounds to kill ancient defender with post nerf BR-64
5 rounds to kill ancient defender with post nerf SH-35

with fortify
90 rounds to kill ancient defender with post nerf AR-12
34 rounds to kill ancient defender with post nerf BR-64
11 rounds to kill ancient defender with post nerf SH-35

**Comment by Al-1ce** [comment]
Sunder itself should be specialized. This would require a much larger rework by the looks of things.

**Comment by Aquilar** [comment]
> Sunder itself should be specialized. This would require a much larger rework by the looks of things.

I wanna try some broad balance changes before reworking, through sunder a mechanic is fine, through the original intention was that concentrated fire would wear xeno armour down, but that just punished castes who job it is to get shot at while lighter castes don't real care about their armour at all until it's mostly broken. 
there's a lot of way a rework could be do:
-Like just removing sunder entirely and bringing back AP ammo for marine guns. 
-Adding max sunder caps
-Making sunder even rarer but forcing xenos to return a structure to heal it
-or this method, pushing sunder to be a support item.

**Comment by Autisem** [comment]
>a xeno called "the defender" while "fortified"(being unable to move in any capacitiy) not dying in 1-2 mags is bad

Aight, sure

**Pull request closed without merging**
