### PR TITLE
Coastfront research rework part 1A: Detaching from RNG

### PR DESCRIPTION
**Pull request by Coastfront**
## About The Pull Request

Hello, I've pitched my idea to a maintainer, and their response gave me the confidence to start this. This is part 1A of a 3 part (around 2 pr's per part) rework im planning. Each pull request is an incremental move towards it.
The end goal of these PR's is to move research from the rng hellscape it is, and to ultimately make it more skill based, and add in a tech tree for it.

Part 1A-1B aims to largely decouple research from random chance, part A addresses research sample rewards. This Pull request puts down the random chance in credit rewards. Each xeno sample tier rewards a fixxed amount of credits, 100% of the time.
The only randomized aspect of this pr, is research item acquisition, I was originally going to temporarily remove the items until I fully implement the tech tree, but that felt shitty without any immediate replacement.
The reward tiers have been changed to points, items, and advanced item. Point rewards are guaranteed, Item reward chances have been increased to become more consistent (NOTE: THEY WILL EVENTUALLY BE FULLY DETACHED FROM SAMPLES, AND MOVED TO A TECH TREE.)
The items are structured in this way: The cloak implant & blood recovery implant are normal items for xenomorph samples, cloak is replaced by blade injector for currency from yellow digsites, and the shoulder attachment is the advanced item reward.
The rates are (and awarded credits) are:
Xenomorph tier 1 samples: 100 credits, 20% chance for normal items
Xenomorph tier 2 samples: 150 credits, 25% chance for normal items, 20% chance for advanced
Xenomorph tier 3 samples: 250 credits, 40% chance for normal items, 35% chance for advanced
Xenomorph tier 4 samples: 600 credits, 60% chance for normal items, 50% chance for advanced
Currency from digsites (yellow): 250 credits, 40% chance for normal items,  35% chance for advanced.

## Why It's Good For The Game

Firstly, researcher can at times feel, very unrewarding. Regardless of how good you do, the total amount of points you can generate is ultimately limited to how much rng hates you, and does not respect time. Walking 3 tiles from the fob and doing a digsite for 1.6k, is horseshit, when you then walk 6 minutes to the other side of the map, do a digsite and get 100 bucks.
This pr alone would (partially) remedy these odds, by ultimately making the amount of money digsites yield VASTLY more consistent.
The PR that will ultimately follow after this one gets merged, will address the RNG of excavation sites, though this PR is functional on its own, as will all of my rework pr's be, with the  exception of  the last 2.
Researchers will now, at a guarantee, gain 400 from green digsites and 1,000 from yellow max, and at minimum, 500 from yellow and 200 from green. 
I do not believe making the items more common is going to completely break the game balance, as the cloak implanter is an even shittier version of the scout cloak, the blood pump is only useful for nanites, mantis is just a semi better machete, the only genuinely "good" reward is the shoulder mount, which is rarely used in favor of other armor modules, by anyone.

While I am relatively set on the item drop values, as they are ultimately a temporary measure I am willing to compromise, and the current point values can be adjusted as needed, though in the future will be changed accoording to my design plans.

The link provided is a document with my overall plans for research & researchers rework, detailing each step of implementation.

## Changelog

Sample reward pools & chances changed as follows:
Xenomorph tier 1 samples: 100 credits, 20% chance for normal items
Xenomorph tier 2 samples: 150 credits, 25% chance for normal items, 20% chance for advanced
Xenomorph tier 3 samples: 250 credits, 40% chance for normal items, 35% chance for advanced
Xenomorph tier 4 samples: 600 credits, 60% chance for normal items, 50% chance for advanced
Currency from digsites (yellow): 250 credits, 40% chance for normal items,  35% chance for advanced.
50 point coin replaced by 100 point coin
800 points changed to 600 points
:cl:
balance: all requisition point research rewards are no longer random, and are given at fixxed values per tier
balance: 50 point research grant buffed to 100
balance: 800 point research grant nerfed to 600
balance: increased chances for cloak implanter, blood implanter, mantis blade implanter, and shoulder mount
code: changed reward tiers and tier names
/:cl:

### CODE REVIEW

**Comment by UsernameIs-UnAvailable** [comment]
This PR is beyond stupid and won't solve your stated issue. 
1. Guaranteed 33% to 60% credits from xenos will exacerbate the issue of marines (you do not even need a researcher to do this) doing next to nothing except spending a extra 30 seconds fucking around the corpse to extra rewards.
2. Digsites in general are awful seeing as they have no real counter play (no, running around the backlines and randomly bumping into a researcher at a digsite is not a real counter play), so giving them a guaranteed 200 to 1000 credits will just make them even worse.
3. Increasing the droprate for the items will just make the role more appealing to powergamers who run around getting a shoulder mount and enough points to get a SG, then drop all pretence of being a researcher and join the main marine push.
4. The researcher feeling unrewarding is A. Subjective (alot of people find most jobs outside of marines boring and/or unrewarding, it just depends on the person), and B. Synths and POs can do at least xenos sampling part better by loading the kit into Tad landing it near the marine push, so the marines do not have to drag the body all the way back to the fob to get it sampled.
All in all this just a unnecessary and poorly thought-out buff to marines credit gain masquerading as a researcher rework.
Thank you for listening to my TED talk.

**Comment by Coastfront** [comment]
> This PR is beyond stupid and won't solve your stated issue.
> 
> 1. Guaranteed 33% to 60% credits from xenos will exacerbate the issue of marines (you do not even need a researcher to do this) doing next to nothing except spending a extra 30 seconds fucking around the corpse to extra rewards.
> 2. Digsites in general are awful seeing as they have no real counter play (no, running around the backlines and randomly bumping into a researcher at a digsite is not a real counter play), so giving them a guaranteed 200 to 1000 credits will just make them even worse.
> 3. Increasing the droprate for the items will just make the role more appealing to powergamers who run around getting a shoulder mount and enough points to get a SG, then drop all pretence of being a researcher and join the main marine push.
> 4. The researcher feeling unrewarding is A. Subjective (alot of people find most jobs outside of marines boring and/or unrewarding, it just depends on the person), and B. Synths and POs can do at least xenos sampling part better by loading the kit into Tad landing it near the marine push, so the marines do not have to drag the body all the way back to the fob to get it sampled.
>    All in all this just a unnecessary and poorly thought-out buff to marines credit gain masquerading as a researcher rework.
>    Thank you for listening to my TED talk.

1. The part of getting marines to do more things comes later, as featured in later seps in the design document. The current currency rewards are adjustable since these are temporary until I finish a later PR to mostly conver them into a different resource

2. Digsite current values can be adjusted to be more reasonable for their rewards, and In a soon-ish pr im also going to add digsites to xenomorph minimaps, to make them a plannable feature. The current rewards they give can be adjusted to have lowered values, but even outside of this PR, they range from giving dogshit nothing to giving 2k points. This atleast makes them consistant, and can be reigned in until future pr's are ready.

3. The current research items are just objectively shit, shoulder mount included. The shouldermount is worthless on 95% of guns, provides 0 armor, permanantly breaks half the time if you get stunned literally every, requring you to unequip and re-equip the module to fix it, and goes ignored functionally every time its ever obtained. The one reason I even kept the item rewards, which I was originally planning to completely remove in this PR, was because it felt shitty to take them out when their replacement PR is going to take the longest.

4. Researcher feeling urnewarding is subjective, yes, but outside of watching a number increase there generally isnt much reward beyond req items, which are still poorly spent on researcher. Yes, synth and PO do part of a researchers job better,  but synths have both more important things to do, and a thousand things to do. And PO exists I guess.

If your complaints amount to the credits being buffed too much and item drops being more consistant. Then I can just completely remove the items until part 2A to the rework, which will add the planned tech tree, and can adjust the values.

I would appreciate if you would read the fucking google document, that you extremely obviously neither read nor considered in this.

**Comment by Naaanii** [comment]
Remove credits being a thing from scanned dead Xenomorphs. Since they can be analysed and sold, it basically doubles the reward of a dead Xeno.

I have no idea what you could add to replace it however but consistent researched gear would be much nicer.

**Comment by UsernameIs-UnAvailable** [comment]
> > This PR is beyond stupid and won't solve your stated issue.
> > 
> > 1. Guaranteed 33% to 60% credits from xenos will exacerbate the issue of marines (you do not even need a researcher to do this) doing next to nothing except spending a extra 30 seconds fucking around the corpse to extra rewards.
> > 2. Digsites in general are awful seeing as they have no real counter play (no, running around the backlines and randomly bumping into a researcher at a digsite is not a real counter play), so giving them a guaranteed 200 to 1000 credits will just make them even worse.
> > 3. Increasing the droprate for the items will just make the role more appealing to powergamers who run around getting a shoulder mount and enough points to get a SG, then drop all pretence of being a researcher and join the main marine push.
> > 4. The researcher feeling unrewarding is A. Subjective (alot of people find most jobs outside of marines boring and/or unrewarding, it just depends on the person), and B. Synths and POs can do at least xenos sampling part better by loading the kit into Tad landing it near the marine push, so the marines do not have to drag the body all the way back to the fob to get it sampled.
> >    All in all this just a unnecessary and poorly thought-out buff to marines credit gain masquerading as a researcher rework.
> >    Thank you for listening to my TED talk.
> 
> 1. The part of getting marines to do more things comes later, as featured in later seps in the design document. The current currency rewards are adjustable since these are temporary until I finish a later PR to mostly conver them into a different resource
> 2. Digsite current values can be adjusted to be more reasonable for their rewards, and In a soon-ish pr im also going to add digsites to xenomorph minimaps, to make them a plannable feature. The current rewards they give can be adjusted to have lowered values, but even outside of this PR, they range from giving dogshit nothing to giving 2k points. This atleast makes them consistant, and can be reigned in until future pr's are ready.
> 3. The current research items are just objectively shit, shoulder mount included. The shouldermount is worthless on 95% of guns, provides 0 armor, permanantly breaks half the time if you get stunned literally every, requring you to unequip and re-equip the module to fix it, and goes ignored functionally every time its ever obtained. The one reason I even kept the item rewards, which I was originally planning to completely remove in this PR, was because it felt shitty to take them out when their replacement PR is going to take the longest.
> 4. Researcher feeling urnewarding is subjective, yes, but outside of watching a number increase there generally isnt much reward beyond req items, which are still poorly spent on researcher. Yes, synth and PO do part of a researchers job better,  but synths have both more important things to do, and a thousand things to do. And PO exists I guess.
> 
> If your complaints amount to the credits being buffed too much and item drops being more consistant. Then I can just completely remove the items until part 2A to the rework, which will add the planned tech tree, and can adjust the values.
> 
> I would appreciate if you would read the fucking google document, that you extremely obviously neither read nor considered in this. (the link to which is featured at the bottom of the changelog)
Your design document does not matter when you clearly state and I quote "The PR that will ultimately follow after this one gets merged, will address the RNG of excavation sites".
I am judging this as a stand-alone PR since I do not know how long it's going to take for you to do the others.
My main compliant is this would speed up the marines credit gain with xenos being able to do little about it but that's just the problem with the researcher in general, you're PR as it currently stands would make it worse.

**Comment by Coastfront** [comment]
> > If your complaints amount to the credits being buffed too much and item drops being more consistant. Then I can just completely remove the items until part 2A to the rework, which will add the planned tech tree, and can adjust the values.
> > I would appreciate if you would read the fucking google document, that you extremely obviously neither read nor considered in this. (the link to which is featured at the bottom of the changelog)
> 
> Your design document does not matter when you clearly state and I quote "The PR that will ultimately follow after this one gets merged, will address the RNG of excavation sites".
> 
> I am judging this as a stand-alone PR since I do not know how long it's going to take for you to do the others.
> 
> My main compliant is this would speed up the marines credit gain with xenos being able to do little about it but that's just the problem with the researcher in general, you're PR as it currently stands would just make it worse.

Then do you have a suggestion of a better rate for credits, since while I think that the rate for green excav sites as i've set it (400 points cap, 200 points minimum) isn't too obscene, I could lower yellow digsites to 150 points per token, which would cap them at 600 points with a max roll for the tokens, and 300 points with a minimum roll.

**Comment by Coastfront** [comment]
After some deliberation I've decided to snuff out this pr and with it the ambitions of the outlined researcher rework, regardless of feedback or reception.
I deluded myself unintentionally by mainly looking at this from a scope that disregarded mech, and have come to the conclusion that marines neither need another means to get stronger with time (what the rework would ultimately cause) nor does the game need more major features, and thus I wont be the one who tacks another one onto it.

The only way this would end is bloat in the best case and powercreep in the worst case. Ergo this is pointless and I've only made myself a fool by even humoring the concept.

**Pull request closed without merging**
