### PR TITLE
Hyposprays/Autoinjectors now have 2 second injection delay on non-same faction injectees

### PR DESCRIPTION
**Pull request by mrhugo13**
## About The Pull Request
Added a check in the hypospray code that creates a 2 second delay on attempting to inject someone else who is not the same faction as you and alerting both the injectee and injector as to this occuring.
firefox_2024-09-27_07-46-43

Tested on a local client with zero (0) runtimes/errors
dreamseeker_2024-09-15_12-13-27

Made sincerily with imdedplzrestart energy.
## Why It's Good For The Game
In any situation where HvH is involved, if one person has a peridaxon+ or qc/qc+ full hypospray set to inject on maximum they can just click on an enemy once in close range (use shield if you want to get close) and they will die in 10 seconds flat unless they already have extreme amounts of hypervene in their system. This fundamentally changes how HvH gamemodes work by having one person with a shield running around with hyposprays injecting people with OD levels of meds and almost instantly killing them, centering the balance all around them and how you can counter them essentially. Even when you have corpsmen with you they can take quite a while to fix you up from having insane amounts of toxins in your system and by the time you've gotten fixed up either the respawn timer allows you to get another body or the op/round is already over.

IM LOOKING AT YOU JEDD YES YOU I HAD TO DEAL WITH YOUR QC+/PERI+ HYPOSPRAY MEDRUSH STRAT YESTERDAY IN A CAMPAIGN ROUND I CONSISTENTLY DIED FROM YOUR ACTIONS AND ALTHOUGH I UNDERSTAND YOU WERE SIMPLY USING THE TOOLS YOU WERE GIVEN WITH AND THEREFOR WERE WITHIN THE MECHANICAL BOUNDARIES OF THE GAME I ABSOLUTELY HAVE NOT FELT MORE FRUSTRATION FROM ANY ONE SPECIFIC GAMEPLAY METHOD THANS YOURS CAN WE PLZ RESTART ROUND IMDED.
## Changelog
:cl: Vondiech/Citruses
balance: Hyposprays and Autoinjectors now have a 2 second delay on trying to inject someone in a different faction than yours.
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
Injectors used to have a Police or CQC skill check that stopped other people from being able to inject you, i think it disappeared in the reagents to chemistry changes.

**Comment by Naaanii** [comment]
The Waltuh nerf is so real

**Comment by AusarAtkin** [comment]
> Injectors used to have a Police or CQC skill check that stopped other people from being able to inject you, i think it disappeared in the reagents to chemistry changes.

Lumi removed it in one of their HvH PRs about skills.

**Comment by Lumipharon** [comment]
this is some omega stinky copypaste code, and has no relevant checks or anything else

**Comment by mrhugo13** [comment]
> this is some omega stinky copypaste code, and has no relevant checks or anything else

CODE IMPROVED AND, ATLEAST IN ATTEMPT, MADE LESS STINKY (AFTER A CODE BATH)

**Review by ivanmixo — APPROVED** [review]
@Lumipharon stop procrastinating

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
