### PR TITLE
Plantable flag XvH debuff removal

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Pr for discussion since people keep whining about it
## Why It's Good For The Game

Something something griff fc throwing round yet again
## Changelog
:cl:
balance: Plantable flag XvH debuff removal
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Then its just a flat buff to marine crit treshold, which is really problematic for reasons I shouldn't even have to state

**Comment by Pariah919** [comment]
Realistically this should really do something else more minor.

**Comment by DrAmazing343** [comment]
XvH flag should really just be a weaker version of the real flag in both ways- When it's planted, it's a VERY noticeable survivability defensive buff. When it's destroyed, it's an even MORE noticeable debuff that often spells the death of the entire battalion no matter how disconnected from any flag-carrying you were. If flag goes, marines die. Every time, without exception.

**Comment by SimplySmiley123** [comment]
What if instead of removing the downside, there was a way to work your way over the debuff?

**Comment by Looking4bros** [comment]
> Then its just a flat buff to marine crit treshold, which is really problematic for reasons I shouldn't even have to state

It's like, the ONLY non perk thing to lower the crit threshold. Also i think the only thing to raise it with the debuff. It's best to state the reasoning as it's this unique. Pain does not change Crit threshold, no matter your pain, humans crit at 150 damage without health buffs.

**Pull request closed without merging**
