### PR TITLE
Revert "513.1526 is now stable (#4271)"

### PR DESCRIPTION
**Pull request by MrStonedOne**
you didn't think it would be that easy did you?

### CODE REVIEW

**Comment by Chaznoodles** [comment]
He can't keep getting away with this

**Comment by saprasam** [comment]
godspeed brave soldier

**Comment by spookydonut** [comment]
See: #4354

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by spookydonut** [comment]
> 
> 
> Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.
> 
> Your current title and or body content does not meet requirements, so please update it.

In addition to this being a low/no effort PR that you've spent more effort on than just reverting the part you disagree with, I'll close this until you're willing to actually just make the two line change you want.

**Pull request closed without merging**
