### PR TITLE
AI powerloader drones now function like proper powerloaders (mostly)

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

gives them an internal powerloader clamp and just hooks cargo handling to that instead
which allows them to handle stuff like ob warheads and such

## Why It's Good For The Game

AI can load ob if the STs are busy fucking off groundside

## Changelog
:cl:
balance: ai powerloaders can now handle most stuff a normal powerloader can
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
third times the charm?

**Comment by mc-oofert** [comment]
> third times the charm?

yeah

**Comment by TiviPlus** [comment]
Third times not the charm

Same as the previous attempts, AI is an AI and shouldnt just be doing shipside roles

**Comment by mc-oofert** [comment]
> Third times not the charm
> 
> Same as the previous attempts, AI is an AI and shouldnt just be doing shipside roles

i tried to reason many times but its like talking to a fucking brick wall so im just not even going to bother on arguing on why youre wrong

**Pull request closed without merging**
