### PR TITLE
Adds a RPD machinegun to the game, and adds it to CLF Leader loadout.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image
Larp name is just the EG degisnation for the RPD, which is lMG-D, since the AK uses the EG designation ingame already.
Basically an AK sidegrade, extra ammo for more slowdown and a few different attachment options, not acquireable by marines.
Magazines fit in belts since its an ERT only gun.
Ideally, I'd like to move this to a future CLF "heavy" role.
Gun Sprite by ocelot, ammo/mob sprite by me.
## Why It's Good For The Game
Adds more variety to CLF, which really needs some. Could be added in the future to SoM or some other HERT if someone wants it there.
## Changelog
:cl:
add: New lMG-D machinegun, a beltfed variant of the MPi, better known as the "RPD".
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
Should be a seasonal.

**Comment by Naaanii** [comment]
Pretty neat but the belt fit is kinda wack ngl.

**Review by Lumipharon — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]
Kuro

**Comment by isotope436** [comment]
this should 100% have been made a seasonal as well like the other CLF guns

**Pull request merged**
