### PR TITLE
Removes xenohide from runner.

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request

See title. 

## Why It's Good For The Game

Runner hide pounce OP, please remove.
## Changelog
:cl:
del: hide from runner
fix: proper roony abilities
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
i ded pls nerf

**Comment by lovegreenstuff** [comment]
> i ded pls nerf

haha yes

**Comment by Wayland-Smithy** [comment]
Will it even pass CI?

**Comment by lovegreenstuff** [comment]
mild alcoholism

**Comment by DerrickChamberlain** [comment]
Do it. Not that I even see runner hide unless it is a vent. Last one tried to hide from me in a dead end room and I blasted his ass back to space.

**Comment by David-Stormwell** [comment]
runner flipped vendor In Alamo and hideded and I deded because I was a doctor in medbay with no helmet plz nerf

**Comment by Walarks** [comment]
You could add a 2s cooldown to the hide when a runner pounces instead.

**Comment by Losenis** [comment]
> is this a meme ided or a serious pr

Runner can pounce a marine and immediately hide, making its sprite go under the marine. This makes it harder to PB, and makes it easier to spamclick the marine since you're not hunting the few pixels you're blocking. That, on top of evasion working while staying still.

**Comment by lovegreenstuff** [comment]
> is this a meme ided or a serious pr

it is the awkward, meme fueled, *shrug filled grey area between those two extremes.

**Comment by lovegreenstuff** [comment]
https://user-images.githubusercontent.com/59631103/119220719-b9d1cc00-baa0-11eb-8651-4cf758123766.mp4

**Comment by lovegreenstuff** [comment]
#6937 
If this gets merged and it functions as intended, this PR ain't gonna be necessary.
Runner hiding under people is still dumb and janky though.

**Comment by Naaanii** [comment]
You can still just shoot the runner by shooting past the tile because the person is downed.

**Comment by lovegreenstuff** [comment]
> You can still just shoot the runner by shooting past the tile because the person is downed.

they literally do that in the video provided.
the big problemo 'ere is that evasion makes you immune to not PB bullets
while hide makes you basically immune to PB

**Comment by TiviPlus** [comment]
Make it have a cooldown after you pounce or whatever properly instead

**Comment by lovegreenstuff** [comment]
brb closing this while i actually code this shit

**Pull request closed without merging**
