### PR TITLE
tx-11 gets higher force

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title, 30

## Why It's Good For The Game
Getting hit by a brick hurts

## Changelog
:cl:
balance:tx-11 has higher melee damage
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
The TX-11 which is based off the G-11 is not a 'brick' and only weighs about 10bs loaded, the average rifle weight. I don't really understand why boosting the melee damage is reasonable considering its already unwieldy to fire let alone use as a club.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
A) Why
B) fix cl

**Comment by davidchan13** [comment]
On the one hand, bash attacks mean _nothing_ and all the guns could have 30-50 melee damage without major change.

On the other hand, this gives it more bash damage than the T-12, T-37 and T-64, let alone stuff like the AK. This puts it on par with the T-42, T-29 and just shy of the T-60 in terms of bash damage, as a carbine parallel weapon that just doesn't make sense.

**Comment by TiviPlus** [comment]
Stale

**Pull request closed without merging**
