### PR TITLE
Adds MBX to standard weapon vendors.

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
Slept on weapon. Pretty bad for the price it offers and doesn't justify the cost at all. Fulfills the niche of a rapid pump fire shotgun whilst having the ability to use a long forgotten caliber of tracker shells.

Will look to making the gun more viable yet not better than it's alternatives and making tracker rounds not obsolete versions of tac sensor.
## Changelog
:cl:
add: Adds the MBX shotgun to the standard weapons vendor.
del: Removes the MBX shotgun from req hell.
/:cl:

### CODE REVIEW

**Comment by FIXTHERADBOXPLEASE** [comment]
Neat, this was always one of my favorite guns to use. The hunting-tracking niche is only shared with the HEAT laser pistol, arguably.

**Comment by Al-1ce** [comment]
>Pretty bad for the price it offers and doesn't justify the cost at all

You want to use the gun. Trust me, I do too, but this is just not true at all. It costs 15 credits. That's what, three more than a valk? It has no cooldown between shots, a fast wield timer and kickass ammo. It used to cost _SIXTY_ credits back when people actually used it - and xenos rightfully complained.

With all that considered, I think the MBX _does_ deserve being dragged out of req hell.

There's an issue with the .410 sabots though. They're unpurchasable. Only 2 boxes can be found in the req vendor, and once you've used that up, you're done. It would be wise to include them in req, and also probably remove the buckshot since that's becoming free.

**Comment by Al-1ce** [comment]
>Pretty bad for the price it offers and doesn't justify the cost at all

You want to use the gun. Trust me, I do too, but this is just not true at all. It costs 15 credits. That's what, three more than a valk? It has no cooldown between shots, a fast wield timer and kickass ammo. It used to cost _SIXTY_ credits back when people actually used it - and xenos rightfully complained. Price went down anyways.

With all that disregarded, I think the MBX _does_ deserve being dragged out of req hell. Will .410 Sabots remain unpurchasable? There's only two boxes roundstart and once those are dry, you're out for good.

**Comment by Naaanii** [comment]
> > Pretty bad for the price it offers and doesn't justify the cost at all
> 
> You want to use the gun. Trust me, I do too, but this is just not true at all. It costs 15 credits. That's what, three more than a valk? It has no cooldown between shots, a fast wield timer and kickass ammo. It used to cost _SIXTY_ credits back when people actually used it - and xenos rightfully complained. Price went down anyways. I think the MBX _does_ deserve being dragged out of req hell despite this.
> 
> Will .410 Sabots remain unpurchasable? There's only two boxes roundstart and once those are dry, you're out for good.

Shells were also added to the vendor.

The damage is by far terrible. The high rof does this gun little favours and even a repeater will outdps this weapon but the repeater has the added benefit of stagger to it. Xenos may have complained back then but I don't know what changed and I don't see how they can complain now as both shells don't have stagger, buck doesn't even have a knockback or stun and the regular Sabot shells do pitiful amounts of damage except they don't even sunder as much as base flechette does.

**Comment by Al-1ce** [comment]
> The damage is by far terrible. The high rof does this gun little favours and even a repeater will outdps this weapon but the repeater has the added benefit of stagger to it. Xenos may have complained back then but I don't know what changed and I don't see how they can complain now as both shells don't have stagger, buck doesn't even have a knockback or stun and the regular Sabot shells do pitiful amounts of damage except they don't even sunder as much as base flechette does.

The numbers aren't everything. Or, at least they don't paint as accurate of a picture as we'd like. I've probably ordered (and used) the MBX more than anybody on this server in the last year and I can say it shreds, just from personal experience.

Xenos complained back then and I'll wager they'll start again. +1 from me.

**Comment by FIXTHERADBOXPLEASE** [comment]
It's an unfamiliar shotgun that tends to catch xenos off-guard, and it gets kills because of that. The actual stats aren't anything insane. 
Once xenos learn what it sounds like, and how much damage it does, it'll be easily manageable.

**Comment by Coastfront** [comment]
Xenos die to it due to scarcity in the same sense that a shitty move in a fighting game is the best: nobody anticipates its presence.

MBX gets kills currently because xenos dont know what it is because its noticably worse than other shotguns: and thus xenos approach it without caution and die.
When people use it more and the novelty fades away, a few set people will keep using it, xenos will realize what it is and will treat it acoordingly, and life will return to the same.

**Comment by TiviPlus** [comment]
Where niche

**Comment by FIXTHERADBOXPLEASE** [comment]
Very light shotgun that's capable of chasing xenos. Has tracking rounds and improved falloff to make that easier. All in exchange for much less hard damage. 
Every other shotgun is horrible in a chase, making the MBX sort of the SMG of shotguns.

Although yeah it'd also be fine as a seasonal. Most of the other import guns are also seasonals already.

**Comment by Naaanii** [comment]
> 

Mentioned above. Also it uses its own variation of ammo instead of regular slugs or buck and has tracker shells.

**Pull request closed without merging**
