### PR TITLE
Adds the x-fuel tank to req

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds a 1000u xfuel tank to req
image

It's 300 points for 1000u of xfuel. I made the price cheaper than the tanks because this is ONLY able to refuel xfuel tanks.
## Why It's Good For The Game
Gives you an option to refill your xfuel, rather than just throwing it away.
## Changelog
:cl: @KillerOrcaCora 
add: You can buy an x-fuel tank from req. It's capable of refuelling xfuel tanks
imageadd: x-fuel tank sprites.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
0/10 unless it makes a proper xfuel explosion.

**Comment by KillerOrcaCora** [comment]
I second with lumi the hell you doing son fix this oversight NOW.

**Comment by Al-1ce** [comment]
The price should stay as it is. X-Fuel is expensive because of it's unmatched utility and area-denial.

Fine with the tank.

**Comment by Xander3359** [comment]
I can't figure out how to make the explosion xfuel and I'm not gonna bother.

**Pull request closed without merging**
