### PR TITLE
Drone movement

### PR DESCRIPTION
**Pull request by rusher210**
## About The Pull Request

Added drone walking/running animations, feedback is very much appreciated 

## Why It's Good For The Game

more animated xenos, hunter and sentinel are animated so why not drone

## Changelog
:cl: glassyduke

imageadd: added some icons and images

/:cl:

enomorph2

### CODE REVIEW

**Review by Kuro020 — COMMENTED** [review]
but how do these look with wounded sprites overlayed on top, those aren't made with this kind of animation in mind.

**Comment by rusher210** [comment]
> but how do these look with wounded sprites overlayed on top, those aren't made with this kind of animation in mind.

i dunno really, i did the same process for the sentinel animations

**Comment by BraveMole** [comment]
> but how do these look with wounded sprites overlayed on top, those aren't made with this kind of animation in mind.

On hunter and sentinel, it's fine.

**Comment by Kuro020** [comment]
> > but how do these look with wounded sprites overlayed on top, those aren't made with this kind of animation in mind.
> 
> On hunter and sentinel, it's fine.

But hunter and sentinel have different animations,this one has more movement and frames

**Comment by SplinterGP** [comment]
pretty sure movement animations for overlays are possible ? can do wound too  if so

**Review by Kuro020 — APPROVED** [review]
it turns out sentinel is in fact animated and I didn't notice,oh well

**Comment by BraveMole** [comment]
Closing as stale

**Pull request closed without merging**
