### PR TITLE
TGUI Hive Status

### PR DESCRIPTION
**Pull request by KornFlaks**
## About The Pull Request

Hive status page is now rendered in a TGUI element.

Massive restructuring of queen abilities to be fully integrated with new TGUI page and actions.

## Noted Issues

* Unique xeno identification is based on if the xeno is tier 4. Hiveminds are not tier 4 but unique.
Will be addressed after #10275 gets merged as the relevant flag would be under `xeno_caste.can_flags`.

* Overwatch cancel by clicking the name again does not work.
Fixed in #10282 and #10274.

* Xenos can still evolve despite the hive status stating there are no more caste slots.
Fixed in #10283.

* Larva do not see evolution bar in hive status and unable to use the evolution button built into the hive status.
Fixed in #10285. Larva in the meantime can still use the Evolve verb found in the top right.

* Hive status background displays Marine background.
Fixed in #10291.

* Sorting by location only sorts alphabetically by the first 5 letters. Locations like Engineering and Engine Room result in mixing of xenos without proper sorting.
Limitation of 32 bit integer. 5 letters with each a possible 26 letter combination means a maximum of 30 bit unique combination. Refactoring the sorting code to instead be a deliberate sort of the xeno initial data list would result in a complete overhaul of the TGUI react code and making me reopen this PR as TGUI Hive Status v3.

## Why It's Good For The Game

Samples below may not reflect the current or full development of the hive status page.

image
image

## Changelog
:cl:
add: Xeno hive status is now a constantly updating TGUI page.
add: Xeno hivemind players can now select a xeno to jump to using the hive status UI overwatch button.
add: Evolving now closes all UI pages open.
add: Xeno purchased primordial tiers now display as a green [PRIMORDIAL] next to the tier population in the hive status UI.
imageadd: Ported CM hive status SSD icon.
qol: Evolution is displayed and can now be accessed through the hive status UI.
qol: Xeno overwatch selection now done through hive status UI. Action button no longer visible.
qol: Xeno overwatch can now be canceled without having to move by selecting the same xeno to overwatch again.
qol: Queen leadership toggle now done through hive status UI. Action button no longer visible.
qol: Queen transfer plasma now possible through hive status UI.
qol: Xeno minimap icons now display next to corresponding xeno names in hive status UI.
qol: Xeno collapse timers now display in hive status UI instead of game tab.
qol: Hive status UI can sort xeno lists by clicking on the column headers. Sorting is done by xeno tier, health points, plasma remaining, and location by alphabetical order to the first 5 letters.
fix: Queen transfer plasma message now only visible to xenos.
fix: Ghost orbiting code now properly returns an accurate reference to the atom it is orbiting.
refactor: Hive upgrades purchasing UI relocated to separate datum.
refactor: Distress mode collapse timers are now a define.
del: Old HTML hive status page now lives at your grandparents' farm upstate.
del: Queen order, the unused direct to xeno version, has been removed.
del: Removed a vestigial time check that checked if a distress beacon could be launched at 10 minutes into a round. Xenos can not hijack before 30 minutes into a round.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
👻

**Comment by Al-1ce** [comment]
Looks nice. Caste icons could use a little more distinction though.

**Comment by Al-1ce** [comment]
>wysi

It's hardly 8x8 pixels. I just think the distinction between these two is very vague and not exactly helpful at a glance.
image

**Comment by KornFlaks** [comment]
It's in fact 14x14 pixels, same size as they're displayed on the minimap. Upscaled from the actual 7x7 pixel minimap icons.

**Comment by Wayland-Smithy** [comment]
@Al-1ce do you mean like the rows are too tight? Maybe some `nth-child(odd)` styling could help?

**Comment by KornFlaks** [comment]
(You need to turn the brightness of your monitor really high to see this)
image

Unfortunately `nth-child(odd)` styling will not work with the table I have generated. Due to the dynamic nature in which this flex items are ordered, the actual element index does not correspond with item order. Breaking any meta class styling. Doing the same in the code doesnt work either.

**Comment by Wayland-Smithy** [comment]
@KornFlaks Okay thanks for trying. I think the difference of the rows backgrounds on their own is noticeable with normal brightness, but probably is much less so when populated. Maybe after merge I will play around with it.

**Comment by Al-1ce** [comment]
> @Al-1ce do you mean like the rows are too tight? Maybe some `nth-child(odd)` styling could help?

I should have specified. That's exactly what I meant. Thankyou for clarifying.

**Review by Kuro020 — APPROVED** [review]

**Comment by KornFlaks** [comment]
Linters had a stroke. There is nothing wrong with my code.

**Comment by KornFlaks** [comment]
I am big dumb.

**Comment by FosterGrime-Heymynameslouie** [comment]
based pr spdee mrehg

**Comment by Al-1ce** [comment]
image
In testing, the middle part really doesn't look that good. It's much easier to comb through the old straight list than it is to look at every section for their respective number. If the hive population tab was converted to how it was previously listed, while keeping the general information & xenomorph list I feel like this would be good.

**Comment by Wayland-Smithy** [comment]
I wonder if just left justifying it would help. Plus don't forget about the "show empty" toggle to reduce clutter.

**Comment by KornFlaks** [comment]
Have you tried toggling off show empty?

Worst case, I can always just make an option to not use TGUI.

**Comment by Al-1ce** [comment]
> Have you tried toggling off show empty? Button at top right side of hive population. Also is cached for xenos so you dont need to keep toggling it off if you reopen. Only for xenos as caching it for ghosts as well is iffy.

This really doesn't help much. It's still in the tier alignment from low to high which isn't easy to comb through in the midst of battle. Additionally, not being able to lock the compass onto other xenomorphs/silos is really, _really_ stupid.

**Comment by KornFlaks** [comment]
Locking the compass to a xeno is not something I am willing to reimplement. Use the minimap and ask where they're at.

Structures perhaps. As there are no "overwatch" for structures, the watch button can instead be used as compass lock possibly.

Still up in the air right now.

**Comment by Al-1ce** [comment]
> Locking the compass to a xeno is not something I am willing to reimplement. Use the minimap and ask where they're at.

That's just stupid. I hope you're self-aware enough to know that it is. The compass is an essential tool when it comes to navigating and helping out the team, especially as a support caste. Checking the map and asking where somebody might be is far, far less efficient.

This removal alone is something that makes the rest of this PR negligible. What an awful change.

**Comment by KornFlaks** [comment]
Closed until I, or someone more experienced in UI/UX design, does a pass through the central hive population pyramid. 

Possibly compact it into linear lines.

**Comment by matt81093** [comment]
That is unfortunate. I have to agree regarding the compass following. But I'm honestly not sure what the issue is regarding the visual other than maybe separating support and melee and ranged castes just by position on the top list (left to right, same tiers).

**Comment by Wayland-Smithy** [comment]
Unless Korn does I plan to resurrect this with an "simple/complex mode" button that will display the caste counts in a less visually busy and hopefully easier to parse at a glance way and with any luck figure out a smooth way to select compass targets.

**Comment by matt81093** [comment]
@Wayland-Smithy I was actually thinking a compact toggle like you were saying might be a good move. Glad to see I wasn't the only one who came to that conclusion. Appears Korn is off the discord for now though.

I'll see play with it in the mean time locally.

**Pull request closed without merging**
