### PR TITLE
Ammo Box Pickup QoL

### PR DESCRIPTION
**Pull request by TheOneAndMightyRed**
## About The Pull Request

Makes it so you can instantly pick up all ammo in a tile to the ammo box á la trashbags.
One line PR lets go

## Why It's Good For The Game

Not having to spam left click and e to fill ammo boxes is good. Less prep time.

## Changelog
:cl:
qol: You can now click a stack of magazines with the ammo box to fill the ammo box with.
/:cl:

### CODE REVIEW

**Comment by Swagile** [comment]
have you tested to make sure this doesn't have other behaviors, like picking up a fuckload of other stuff like nades in a ammo box?

just curious cause byond code is weird like that sometimes

**Comment by TheOneAndMightyRed** [comment]
My testing was:
-vend 30 tp mags and pick it up (all were picked up and stored as it is the maximum)
-vend 45 shotgun shell boxes (15 each type alternating) and pick it up (only 15 boxes made it in as it is the maximum for shells)
-vend guns and ammo and click on the gun (only ammo was picked up, guns ignored until it is full)
-vended one of each item in the Automated Weapons Rack and it only picked up ammo while ignoring everything else.
-can't hold nades

Just like a normal trashbag, it can only hold items it is allowed to hold via the `can_hold` var

**Comment by Swagile** [comment]
> 
> 
> My testing was:
> -vend 30 tp mags and pick it up (all were picked up and stored as it is the maximum)
> -vend 45 shotgun shell boxes (15 each type alternating) and pick it up (only 15 boxes made it in as it is the maximum for shells)
> -vend guns and ammo and click on the gun (only ammo was picked up, guns ignored until it is full)
> -vended one of each item in the Automated Weapons Rack and it only picked up ammo while ignoring everything else.
> -can't hold nades
> 
> Just like a normal trashbag, it can only hold items it is allowed to hold via the `can_hold` var

ok cool

my full support to this QoL cause picking shit up individually hurts wrists

👍

**Comment by Losenis** [comment]
Will this have the option to pick up only one type of ammo at a time? Sometimes people just spamclick the ammo, fill up ammo box, and leave the surplus on the vendor tile. Then another comes in and does the same, so suddenly you have like 4 types of ammo on the same tile that'd require just as much effort.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
