### PR TITLE
Neuraline cost increased by 1

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Nerfs neuraline to cost 14rather than 13, making it so you can't get 240u of meraderm and neuraline.

## Why It's Good For The Game
Getting 240+advanced combat pouch (so 180) and neuraline was way too much. Neuraline injectors were also way too cheap for their effectiveness (13 cost for 3 shots of a chem that basically makes you literally invincible. Epic. and you get 240u of advanced chems. Epic.)

## Changelog
:cl:
balance: neuraline injector increased by 1 to 14 in medic vendor
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -61. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
Costs are balanced as-is to allow you to get 1, or more than 1 at the cost of meraderm.

Giving a free one and upping the cost just gives "most" medics effectively more points to spend.

**Comment by Pariah919** [comment]
> Costs are balanced as-is to allow you to get 1, or more than 1 at the cost of meraderm.

Giving a free one and upping the cost just gives "most" medics effectively more points to spend.
>
i can remove the free one, i'm not attached to it. I just thought it'd be too much of a nerf to medics

**Comment by Dolth** [comment]
Salt PR to nerf what a minority of player does.

**Comment by Pariah919** [comment]
> Salt PR to nerf what a minority of player does.
>
Alright then, then tell me what else people order in the medic vendor?
Most people by now know that synap is really bad, you already get qc+ and peri+ isn't that useful in a lot of scenarios outside of that one time you get slashed by a ravager and get heart damage.

This makes the most optimal choice to pick neuraline+meraderm separated or not for 240u of advanced chemicals at literally no cost, this forces you to actually make a choice between both, which is supposed to be the point of a point based system no? Engineers already have to do it. I don't see how medics don't have to.

**Comment by Dolth** [comment]
You might want to observe medics more often because you never see anyone using neuraline and meraderm is still uncommon. Most medics are doing the (bad yet still) choice of taking other chems than just meraderm and neuraline and that's their deal.

If having 240u of advanced chemical such a big deal why not lowering it anyway? You're ALREADY going to nerf neuraline working with meraderm, is really proper to ONTOP OF THAT remove the ability to take 240u AND neuraline?

**Comment by jroinc** [comment]
This is fine now.

I could remove my downvote. It'd just take one click. One... *little* click..

**Comment by Pariah919** [comment]
>They also take iron sugar, FYI.
>
ironsugar is a noobtrap

**Review by Hughgent — APPROVED** [review]
Code is fine

**Comment by MiniMeatwad** [comment]
Sledgehammer balancer

**Review by TiviPlus — APPROVED** [review]

**Comment by Hughgent** [comment]
Choose one of the two PR's to keep, and close the other.
#5222

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-65). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
