### PR TITLE
Larva Soup

### PR DESCRIPTION
**Pull request by Hughgent**
## About The Pull Request

This could use a new soup bowl sprite.

## Why It's Good For The Game

larva soup
larva soup 2
larva soup 3
larva soup 4

## Changelog
:cl:
add: Soups on! You can grind extracted alien embryo and turn them into jelly to make soup with.
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
I 100% support this.

**Comment by AbsoluteJerry** [comment]
I too, have neglected my digestive health for a nice snack

**Comment by XElectricX** [comment]
"Baby eating heathens!"

_Queen clutches her eggs_

**Comment by ilikesaying** [comment]
_xenos watch on in horror as a lone marine makes soup out of their dead sisters_

**Comment by davidchan13** [comment]
>Not calling it Noodle Soup in reference to Larva players being referred to as noodles...

**Pull request merged**
