### PR TITLE
Removes recoil from all weapons

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Recoil doesn't exist anymore. Your screen will no longer shake like a shakeweight:tm: when firing any gun.

## Why It's Good For The Game

Recoil is shit in a 2D spessmans game. This isn't a third person shooter; it's a top down shooter where the recoil system makes absolutely no sense. Recoil shaking should be used in special circumstances only, such as getting hit with something, explosions, or taking damage; not firing a gun.

Also recoil has 0 effect on the performance/damage/accuracy of the gun: it's literally just a cosmetic effect.

## Changelog
:cl: BurgerBB
del: Removes recoil from the game, aka that shitty screenshake you get when you fire a weapon sometimes.
fix: Fixes any and all past, present, and future recoil bugs.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
yey

**Comment by Rohesie** [comment]
Hello, no.
Recoil is good for allowing people to shoot a gun they shouldn't normally, with a consequence. Such as having no skill, or terrible modifiers. The alternative of not letting them shoot is worse.

**Comment by InterroLouis** [comment]
And what are the guns they shouldn't normally shoot? Because any guns you shouldn't normally shoot are typically...specialist guns. Which do come with having no skill. Or smartguns, which have terrible modifiers for anyone that isn't a smartgunner. Does recoil actually do anything aside from a majorly annoying screenshake? It's not even a good consequence.

**Comment by BurgerLUA** [comment]
Recoil is cosmetic, annoying, and affects nothing other than your viewport, and in that case, it fucking shakes that thing like a martini.

**Comment by Pariah919** [comment]
The only gun that actually has recoil is the M44 and that's mostly annoying to most people.

Spec guns recoil isn't usually noticeable since you're usually firing a gun with modifiers so bad you won't hit shit anyway like the minigun that being unable to fire it is probably honestly better or they have such a high fire delay that the recoil isn't noticeable (RPG/sniper) 

The recoil itself is cosmetic and can be outdone anyway if the player knows about attachments.

**Comment by spookydonut** [comment]
weird flex but ok

**Comment by Teaika** [comment]
akimbo LMGs when

**Comment by jroinc** [comment]
-1

It generally only punishes people with unwielded guns, or those without the skill to use them.

It's 100% obnoxious and annoying, but has a purpose.

Additionally, as a marine firing a wielded gun I'm meant to use, I have never had recoil, ever.

**Comment by Rohesie** [comment]
If the gun is recoiling, then a message is being sent. You shouldn't be shooting it without penalties.

**Comment by BurgerLUA** [comment]
> If the gun is recoiling, then a message is being sent. You shouldn't be shooting it without penalties.

Recoil is a shitty clientside effect that should only be used as a "gun-feel" tool to gauge how powerful the weapon is in a top-down shooter. In this game, the effects are VASTLY over exaggerated and cartoonish and serves no purpose other than to give motion sickness to the player, worst case scenario, and a minor annoyance best case scenario. I've fired a shotgun one handed before on a table and in no way did it make my entire world shake violently. Unless it is canon that weapons are fired pressed against your forehead, there is no way recoil would be this bad.

**Comment by Rohesie** [comment]
There are several levels of recoil. The mechanic is to do a soft punishment for firing weapons in certain ways. If you want it changed, then suggest a different method, not just remove this one.

**Comment by spookydonut** [comment]
stale closing

**Pull request closed without merging**
