### PR TITLE
kills 4 cape styles and style jaeger

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Deletes 5 Capes (Overlord+Variants, Jacket, Star)
Deletes Style Jaeger (Kabuto, Overlord, Hotaru)
## Why It's Good For The Game
Kuro asked for this.
Also just generally these kind of don't fit the art style anymore, its a tone back on the silliness.
## Changelog
:cl:
del: A few cape styles have been removed. (Overlord+Variants, Jacket, Star)
del: Style line jaeger has been removed. (Kabuto, Overlord, Hotaru)
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]
indeed

**Comment by Alexeivichi** [comment]
Bad PR.

**Comment by bowlofcereal** [comment]
PR-2

**Comment by ilikesaying** [comment]
https://tenor.com/view/kamen-rider-build-rain-gif-25546573

**Comment by 1kajowsmol** [comment]
overlord should stay imo

**Comment by Henrique9576** [comment]
image

**Comment by FosterGrime-Heymynameslouie** [comment]
giving the armor to special ERT instead sounds cool, samurai ert with energy weapons

or just chuking them into req hell or some groundside spawn sounds alot better than completely removing them. I believe they were commisioned too

**Comment by Oscari-pog** [comment]
These capes are absolute dogshit, glad to see them go

**Comment by chizzy376** [comment]
Ah yes, because we are an EXTREMELY High Roleplay server where we have to be taken seriously and having silly additions completely RUINS the immersion. 😐😐😐

**Review by ivanmixo — APPROVED** [review]

**Comment by Mrrpip** [comment]
Don't really use the armors/capes much, so I don't mind that as much.

But...When did the artstyle change to make the sprites inadequate? The MK1/MK2 Jaegar was in feburary and seems to be the last major rework, while the removed Hotaru/Dashe/Kabuto armors were after the fact and approved ( #13893 ) or Merged ( #14119 , #13457 ) by Kuro.

Maybe guidelines should be set?

**Comment by lbnesquik** [comment]
> Aside from a lot of them looking stupid and not fitting in the game, they also hide what equipment you're wearing.

It isn't like you can really read equipment anymore.

**Pull request merged**
