### PR TITLE
Vendor changes

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

Properly removes vendor hacking
Removes vendors throwing out items when damage or hacked
Removes vendors electrifying themselves when hacked
Removes vendors having wires or a panel

## Why It's Good For The Game

Hacking is a leftover feature all the way from baystation when the game was still a paranoia laden atmospheric job simulator. We now have an objective based asymmetric deathmatch twin stick shooter which has no usage at all for vendor hacking. Hacking has only ever been used by powergames to access items they generally aren't expected to have. Recent PRs have been made to ensure that items which should be available to all won't be affected by this (e.g. TerraGovTech Engineer Vendor).

## Changelog
:cl:
del: Vendor hacking has been completely removed.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
>Properly removes vendor hacking

Anyone with access dumping out all the contents roundstart will become meta and will probably also fuck over latejoining jobs with loadouts that use said vendors for that reason. Less reason to join corpsman when there's none because you'll get hounded for them.

There's not enough actual good alternatives to pills to have any nerf actually do what it intends to do given that loadouts now give marines enough time to circumvent any nerf.

**Comment by Frinid1** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10452#issuecomment-1153812613
Only week passed since your same PR, reason for deny didn't change, you just cleaned more code while keeping same problem
изображение
Did you even read it?

**Comment by Pariah919** [comment]
> > Properly removes vendor hacking
> 
> Anyone with access dumping out all the contents roundstart will become meta and will probably also fuck over latejoining jobs with loadouts that use said vendors for that reason. Less reason to join corpsman when there's none because you'll get hounded for them.
> 
> There's not enough actual good alternatives to pills to have any nerf actually do what it intends to do given that loadouts now give marines enough time to circumvent any nerf.
> 
> And the word powergaming has been thrown around so much that it has lost any and all meaning other than "you're applying more effort into your playstyle than I personally would and I don't like that".

I guess this is kinda balance so I'll throw in my 5 cents as balance man

Generally hacking is used to get shit because you can't get someone else to give it to you, but it also has a legit use in lowpop where people can't access this shit, 99.5% of people won't need the shit anyway if they're powergayming (this doesn't lock chem) anyway, and there's legit uses for it in emergencies scenarios.

I don't like this PR.

**Comment by Nanu308** [comment]
Put Ckey next to the CL at the top, so people can see who added it ingame.

**Comment by Autisem** [comment]
As stated by others, this propably harms more on lowpop. Requiring X job to get 1 very specific neech 1 time task done is very annoying.

Skeleton crew would be a good alternative though

**Comment by Al-1ce** [comment]
You were already told this was a bad idea. Tivi already said he had no intention of merging this.

And yet here we are. Again. Why?

**Comment by TiviPlus** [comment]
image

**Pull request closed without merging**
