### PR TITLE
swaps o6 and o7 ranks so its a bit more clear

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Commodore looks a lot like commander, so this is probably better longterm.

## Why It's Good For The Game
clarity

## Changelog
:cl:
tweak: swapped o6 and o7 so o6 is commodore and o7 is captain

/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
image
since git seems to be fucky

**Comment by Pariah919** [comment]
ok appreantly commodore isn't evne a rank that exists anymore, let me fix this

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Commodore is above captain though just rename COMM or something

**Comment by davidchan13** [comment]
This wouldn't be a problem if you used actual Marine ranks and not outdated Naval Ranks from the 16th Century.

**Comment by TiviPlus** [comment]
Merge into master to fix travis

**Comment by TiviPlus** [comment]
Just change commodore to CDRE

**Comment by Pariah919** [comment]
i need moe thought

**Pull request closed without merging**
