### PR TITLE
infinite chems for non-gamer chems

### PR DESCRIPTION
**Pull request by MuhreenGroyper**
## About The Pull Request

Makes spaceacillin, alky, imi, and whatever else that doesn't need phoron/lemo to make, infinite in the two med vendors.

## Why It's Good For The Game

"Balance" change that makes it easier to get changed chems that were free to make anyway

## Changelog

:cl:RasKrigare123
balance: Spacecillin, Alkysine, Imidazoline, Soporific, and Polyhexanide are now all infinite in their vendors.
/:cl:

### CODE REVIEW

**Comment by PowerHedgehog** [comment]
Is there any plan on touching tadpole med vendor? Currently it has only one non refillable injector of each type. I fell it is kinda useless now and I suspect it was made this way with refilling mechanic in mind

**Comment by Xander3359** [comment]
This is, in fact, not a qol change. Label it as balance

**Comment by DorfGuy1** [comment]
> Is there any plan on touching tadpole med vendor? Currently it has only one non refillable injector of each type. I fell it is kinda useless now and I suspect it was made this way with refilling mechanic in mind

You can't refill injectors in that anymore?

**Comment by PowerHedgehog** [comment]
> > Is there any plan on touching tadpole med vendor? Currently it has only one non refillable injector of each type. I fell it is kinda useless now and I suspect it was made this way with refilling mechanic in mind
> 
> You can't refill injectors in that anymore?

yes. I can't point to the exact PR that touched it, but since not long ago you can no longer refill injectors that you can't vend infinite amount of, even if its a common one like bica or kelo, which it is in tadpole vendor. I hope its an oversight that people are aware of

**Pull request closed without merging**
