### PR TITLE
Refactor logging and add JSON logging

### PR DESCRIPTION
**Pull request by vvvv-vvvv**
## About The Pull Request

Continuation of #13672

Mainly tgstation/tgstation#72814, tgstation/tgstation#73604 and tgstation/tgstation#75617 and probably some more that I missed

## Changelog

:cl:
admin: Added JSON logging. Use the new View-Round-Logs verb for a nicer UI
/:cl:

### CODE REVIEW

**Review by BraveMole — CHANGES_REQUESTED** [review]
You need to compile rust yourself, no one will do it for you I a afraid

**Review by Lumipharon — APPROVED** [review]
seems good, not sure if anyone else wants to check this out before merge though.

**Comment by vvvv-vvvv** [comment]
@psykzz this might break your statbus? not sure if you parse logs

**Comment by psykzz** [comment]
Statbus will be fine. it reads from the database

**Comment by Lumipharon** [comment]
@vvvv-vvvv BM said you need to "compile with pathfinder feature" or this pr will break AI.

**Comment by vvvv-vvvv** [comment]
> @vvvv-vvvv BM said you need to "compile with pathfinder feature" or this pr will break AI.

it is compiled with it https://github.com/vvvv-vvvv/rust-g/actions/runs/6756473831/workflow

**Pull request merged**
