### PR TITLE
Powerpack resprites (and minor fix)

### LINKED ISSUE #9722: minigun powerpack breaks back slot
### Description

Back slot becomes unusable and when minigun powerpack runs out of ammo. You also can't interact with it. 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [13643](https://scrubby.melonmesa.com/round/13643)
BYOND Version: 514.1575
Server revision compiled on: 
Master commit: [7883e4250c7f8e522749a12c9d77515ee7bea8da](https://github.com/tgstation/TerraGov-Marine-Corps//commit/7883e4250c7f8e522749a12c9d77515ee7bea8da)
The following pull requests are currently test merged:
[#9650: 'Adds the TAT-36 AT Gun' by Pariah919 at commit 4b6864213a](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9650)
[#8932: 'Icarus Shipyard. (New map)' by vilereaver41 at commit 4fb3c277f3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/8932)
[#9645: 'sentry rework' by Pariah919 at commit 93d1ebb043](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9645)
[#9659: 'Extreme Requisition Map Makeover: ASRS edition' by novaepee at commit d4e19edfb5](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9659)

Local commit: b989a9084a43d4d06aef6fc2a3158379cb165983
Server tools version: /tg/station 13 Server v3.2.6.2

### Reproduction Steps

put on power pack. click minigun to power pack. fire until empty.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Notamaniac**
## About The Pull Request

Fixes #9722

powerpack1powerp2

Powerpacks had no empty sprite (since they were converted into a magazine), and there wasn't any easy way to make a powerpack look empty without a complete resprite. So here we are.

Standard Variant

standard (Custom) (2)standard2 (Custom) (2)

Jungle Variant

mstandard (Custom) (2)mstandard2 (Custom) (2)

Snow Variant
snow (Custom) (2)snow2a (Custom)

Big Red Variant
bigred (Custom)bigred2a (Custom)

Prison Variant
prison (Custom)prison2a (Custom)

PMC Variant

pmc (Custom) (2)pmc2 (Custom) (2)

Merc Variant

merc (Custom) (2)merc2 (Custom) (2)

## Why It's Good For The Game

Less broken sprites, marines can tell when a powerpack is completely out of ammo.

## Changelog
:cl:
fix: Powerpacks don't disappear on your back when they run out of ammo anymore
imageadd: Powerpacks have been resprited
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
okay legitmate question, the mob sprite has the powerpack worn on the front, is this intentional or have we been lied to all this time

**Comment by Kuro020** [comment]
> okay legitmate question, the mob sprite has the powerpack worn on the front, is this intentional or have we been lied to all this time

intentional, but you can put it on the back

**Comment by Notamaniac** [comment]
okay mob sprites are done

**Review by TiviPlus — APPROVED** [review]
No code so code ok

**Pull request merged**
