### PR TITLE
A Goon's Life For Me

### PR DESCRIPTION
**Pull request by tyeagg**
### PLEASE READ https://hackmd.io/@wlLEbadtQoCyE4iytTkonw/HymHjCLf0

per request of art directors
A push towards proper art direction
Removal of: 
- mk1 jaeger
- style line armor
- xenonauten 
- crasher armor
- uniform variations 
- colorable gloves
- majority of capes with exception of short, and scarves 
- armor coloring with exception of secondary colors located on arm plates, leg plates, and visors

image

## Why It's Good For The Game
Create uniformity and a sense of cohesion in the art style, things have been taken too far and its time to take a step back
## Changelog
:cl:
del: limited armor coloring
del: colorable uniforms
del: colorable gloves
del: orion,big red, lv, turtlenecks, black suit, jaeger undersuit uniforms
del: crasher armor
del: xenonauten
del: jaeger mk1
del: style line armor
imageadd: uncolorable elements to armor
imagedel: several capes with exception of scarf and short
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
no omore capes

**Comment by Barnet2** [comment]
Ragnarok

**Comment by CoastalCookie** [comment]
Tgmc prepare to cry edition...

**Comment by chizzy376** [comment]
and on the third day He took all the customization away that he once gave, as the people abused it to look like crayon rangers

**Comment by SimplySmiley123** [comment]
Removal of style line and xenonauten?
Cringe as _fuck._

**Comment by Ispartanli** [comment]
hmmm today im gonna be cringe as hell and remove fun marine stuff even though it does not effect gameplay, because im inspired by helldivers 2 and i like to give worst decisions ever in history.

**Comment by Aidenzack1** [comment]
“A push towards proper art direction”

Aka, 1.5 people (whom I’ve never actually seen on the server playing), removing shit people actually like purely because they don’t personally like it is shitty and an abuse of power. I’ve seen literally no justification for this other than Kuro personally hates how TGMC looks, even though he is quite literally one of the only people whom I’ve seen with this take.

Why remove shit people like? Why not just add stuff instead of taking it away?

Why do you have to be cringe as fuck during a time where we’ve already had issues with _lots of people leaving_? 

the fact that this is being proposed at all proves we need new directors to push the game to a state that the players actually want, instead of turning this server into a jumbled mess of pet projects nobody wants, and that actively make the server worse.

**Comment by Looking4bros** [comment]
The Tyr helmet module going from looking like the Maska-1SCh faceplate to some kind of Footballer's head protection was gross as it was, I have no expectation that the replacements for wider armor aesthetics to be any better.

**Comment by Araulius** [comment]
finally snowflake getup's are kill

**Comment by novaepee** [comment]
image

**Comment by Alexeivichi** [comment]
Kuro works for Sony.

Joking aside, generally bad PR. If I wanted uniform cohesion I'd play CM-SS13.

**Comment by BonkaiB** [comment]
Uniformity i feel isn't a valid argument here as people don't come here for such. I feel this should extend to things that aren't maintained and or aren't maintainable. Cohesion should be something encouraged rather than forced ontop people and frankly isn't impossible even now to achieve it. it's just not your version of your idea of cohesion. We're not CM, nor does the majority of people here want it to be akin to CM's uniformity or cohesion 

The only points here i see as valid are mk1 jeager and a good portion of capes (not all of them). The extremes of it should be cropped out but literally not 75% of the armor choices and conveniently the armors i see the least used (diet cola syndicate, Clone armor (?) if its still in and the power rangers armor) unless this is included in style line, are missing from this if you're truly trying to go after extremes of it

**Comment by Wisemonster** [comment]
I can understand things like reducing the style lines and variety of capes, considering I've been able to use capes and style line jackets to make my character look like an egg/chicken, but stripping out so much without adding anything in it's place is gonna just make marines look like a Halo Reach match. Not to mention the little parts left in for customization (a cape/scarf, helmet cosmetics, masks) are in short supply, or just not visible on the jaeger helmets (in the case of masks). Will there even be a way to look like a generic marine anymore? Overall, unless there's a follow-up pr adding some kind of customization, I really don't think this is a good pr as it's currently planned.

**Comment by Zangeiti** [comment]
WE RETURNING TO CM WITH THIS ONE!!! 🔥🔥🔥🔥

**Comment by Derrick2Electricboogaloo** [comment]
Why xenonauten?! It is hands down the best.

**Comment by SimplySmiley123** [comment]
> I can understand things like reducing the style lines and variety of capes, considering I've been able to use capes and style line jackets to make my character look like an egg/chicken, but stripping out so much without adding anything in it's place is gonna just make marines look like a Halo Reach match. Not to mention the little parts left in for customization (a cape/scarf, helmet cosmetics, masks) are in short supply, or just not visible on the jaeger helmets (in the case of masks). Will there even be a way to look like a generic marine anymore? Overall, unless there's a follow-up pr adding some kind of customization, I really don't think this is a good pr as it's currently planned.

Epretty much.
I can understand some of the extreme capes getting axed, but not removal of mk1, style line and xenonauten. especially the latter 2, they allow for some really good customisation and get more into gimmicks.

**Comment by chizzy376** [comment]
ragnarok

**Comment by Aroliacue** [comment]
If I didn't want to see Power Rangers I'd go play CM, don't take away the stuff that makes us unique!

**Comment by Aidenzack1** [comment]
> this is the worst pr ive ever seen in my entire life and its gonna br approved either way nobody wants this its too late to change the art direction tgmc...is known for silly capes and stuff we aint the next Cm 😭😭😭

Because they aren't art directors, they're art dictators lmao

they give no shits for what they playerbase wants and only consider their own views to be valid.
image

**Comment by Fawcksy** [comment]
Leave my drip alone leave my drip alone leave my drip alone LEAVE MY DRIP ALONE

**Comment by Yttriums** [comment]
You are so brave for this 🙏🥹

**Comment by ZAMODA** [comment]
### **Leave my fucking moth-wing cape alone!!!!!**

**Comment by Isy232** [comment]
Removing even Armour Colouring? Thats just going too far I think.

**Comment by Kuro020** [comment]
Deleted all comments I felt weren't contributing to the discussion.
Locked conversation because github isnt your personal complaint zone, you have thumbs down for that

**Comment by Kuro020** [comment]
As far as the plan on what's gonna happen with tgmc customization goes, its detailed on the hackmd for Mk3 Jaeger

https://hackmd.io/@wlLEbadtQoCyE4iytTkonw/HymHjCLf0

**Comment by MiniMeatwad** [comment]
Sounds cool, hope you don't have to put on 20 armor pieces like with Jaeger.

**Comment by SilencedMP5A5** [comment]
kuro what are you DOING

**Comment by Coastfront** [comment]
Tools of the same box bear still the handle of their forge; People playing TGMC are infact, not playing it for its art direction. nor to roleplay.
People are mainly here to experience gameplay; And ergo have mostly no sense of needing to be in "Uniform."

I will genuinely, never understand arguements for stripping armor-customization options past optimizing file sizes, yet its evident that this is doomed to be merged, as a forest is doomed to its fire even in rain.
The entire community, at once, could vote against this and it'd be merged at the whims of a dozen; Every tree could plea to be more than smoke yet the dried bush only longs for warmth.

For what its worth, I respect your honesty as to "why this is happening" in the hack.md; That its happening solely because you felt like doing it, over the community actively wanting it.
The vote ratio on this even shows; This transcends not being asked for, people actively do not want this.

**Comment by deathrobotpunch** [comment]
This entire PR goes against the whole spirit of TGMC,

People do not join this server for uniformity, cohesion or immersion.

They come here for a more relaxed alternative to CM, the unpredictability of TG’s rounds and an engaging community who cares.

The entire soul of TGMC is intended to be a polar opposite to CM and their Uniform round structure and strict rules.

uniformity has no place here

**Comment by chizzy376** [comment]
I do like the new proposed mk3 jaeger, but I feel as though the community wouldn't be hating this PR at all if other armors weren't removed in its place. Letting them choose the old or the more inline new armor would be neat.

**Comment by Wisemonster** [comment]
Another factor is that there is no guarantee that because this pr is merged, that Jaeger MK. III will be made and merged. This was the reason the tad wasn't nerfed till after vehicles was made and merged, cause until the follow-up pr is made, it will be a "maybe this will replace it eventually". And if that pr isn't made, then what we are left with is a pr stripping out a lot of cosmetics in anticipation for a pr that will never come.

**Comment by FountainOfNil** [comment]
> Another factor is that there is no guarantee that because this pr is merged, that Jaeger MK. III will be made and merged. This was the reason the tad wasn't nerfed till after vehicles was made and merged, cause until the follow-up pr is made, it will be a "maybe this will replace it eventually". And if that pr isn't made, then what we are left with is a pr stripping out a lot of cosmetics in anticipation for a pr that will never come.

I hope every thing you've ever liked about TGMC, prs that have massive like/dislike ratios, just like your own, are merged so you get to feel powerless beneath bigger autists.

**Comment by Kuro020** [comment]
> I do like the new proposed mk3 jaeger, but I feel as though the community wouldn't be hating this PR at all if other armors weren't removed in its place. Letting them choose the old or the more inline new armor would be neat.

TGMC has a severe problem with making something new then leaving behind the old stuff because some people liked it, which ends up with 500 versions of the same think.

Leaving Mk1 in when Mk2 was added made sense because they functioned differently. Mk3 is a mix of everything we had so far, so it should not be necessary for the old stuff to hang around anymore

**Comment by Kuro020** [comment]
> Another factor is that there is no guarantee that because this pr is merged, that Jaeger MK. III will be made and merged. This was the reason the tad wasn't nerfed till after vehicles was made and merged, cause until the follow-up pr is made, it will be a "maybe this will replace it eventually". And if that pr isn't made, then what we are left with is a pr stripping out a lot of cosmetics in anticipation for a pr that will never come.

Already in talks with tivi and MK3 is being made, idk if we'll even need this pr, I'm leaving it up to ~~annoy everyone~~ have insurance

**Comment by Aidenzack1** [comment]
> > Another factor is that there is no guarantee that because this pr is merged, that Jaeger MK. III will be made and merged. This was the reason the tad wasn't nerfed till after vehicles was made and merged, cause until the follow-up pr is made, it will be a "maybe this will replace it eventually". And if that pr isn't made, then what we are left with is a pr stripping out a lot of cosmetics in anticipation for a pr that will never come.
> 
> Already in talks with tivi and MK3 is being made, idk if we'll even need this pr, I'm leaving it up to ~annoy everyone~ have insurance

Honestly? I’d be much more fine with this if it was a gradual thing, with mk3 equivalents being added over time instead of everything being nuked at once, as I believe this would be better for spriters and players alike, so I truly do hope you go through with not adding this PR directly.

**Comment by Kuro020** [comment]
> > > Another factor is that there is no guarantee that because this pr is merged, that Jaeger MK. III will be made and merged. This was the reason the tad wasn't nerfed till after vehicles was made and merged, cause until the follow-up pr is made, it will be a "maybe this will replace it eventually". And if that pr isn't made, then what we are left with is a pr stripping out a lot of cosmetics in anticipation for a pr that will never come.
> > 
> > 
> > Already in talks with tivi and MK3 is being made, idk if we'll even need this pr, I'm leaving it up to ~annoy everyone~ have insurance
> 
> Honestly? I’d be much more fine with this if it was a gradual thing, with mk3 equivalents being added over time instead of everything being nuked at once, as I believe this would be better for spriters and players alike, so I truly do hope you go through with not adding this PR directly.

I need to set expectations for what it actually does:

image

**Comment by MiniMeatwad** [comment]
TGMC Slang

**Comment by EEASAS** [comment]
the comments were unlocked, so i'll state this

i dont entirely give a fuck

**Comment by CVSthePharmacy** [comment]
removing a bunch of clothings is not at all what the community wants, the ratio on this pr is proof, I feel like no actual feedback from the COMMUNITY was taken. Close this PR

**Comment by Tailiik** [comment]
Let him cook

**Comment by XElectricX** [comment]
Do this PR _AFTER_ the Mk3 armor stuff is made, not before. Like someone mentioned with Tad not being nerfed until APCs were a thing.

**Comment by gpinrgrmoma** [comment]
> Do this PR _AFTER_ the Mk3 armor stuff is made, not before. Like someone mentioned with Tad not being nerfed until APCs were a thing.

This PR is literally just a political move to get coders to do a thing

(they did not tell the coder what they want, lol, lmao)
image

**Comment by Kuro020** [comment]
> removing a bunch of clothings is not at all what the community wants, the ratio on this pr is proof, I feel like no actual feedback from the COMMUNITY was taken. Close this PR

cute

**Comment by gpinrgrmoma** [comment]
> removing a bunch of clothings is not at all what the community wants, the ratio on this pr is proof, I feel like no actual feedback from the COMMUNITY was taken. Close this PR

yeah lol Kuro doesn't really care what the community actually wants

this will hopefully inspire people to reach out to headmins/host/whoever controls directors and beg for a new team leading sprite directing

**Comment by Yttriums** [comment]
> removing a bunch of clothings is not at all what the community wants, the ratio on this pr is proof, I feel like no actual feedback from the COMMUNITY was taken. Close this PR

Damn the permabanned boomers are really putting their foot down on this one

**Comment by FosterGrime-Heymynameslouie** [comment]
I kinda agree with the points except for jeager being choosen
id be alot cooler if xenonatuean was the standard instead of jeager
jeager and halo armor as cool as it is, is kinda boring and generic

while xenonatean compared to jeager has way more personality and more variety and is kinda ingrained in tgmc culture by now

like cmon, generic sci fi halo armor vs a dude with a body armor, muscles exposed and a whole lot of determination is a match up where I know where my money is going

also really like how different modules actively change how they look, instead of just having a simon says circle toy in the back change colors

**Comment by ilikesaying** [comment]
Robot Armour Mk2 when

**Comment by CVSthePharmacy** [comment]
> I hope this never gets merged, simple as. This whole thing looks to me as if a few coders/autistics decided to snap out majority of customisation from players just because they feel like it despite majority of the player base being against it. This ain't your personal game pal, you're just autistic enough to know how to add code to it so maybe consider what others actually want to keep before thanos snapping the entirety of armor customisation.

I honestly hope kuro gets removed, we need an actual head coder who listens to the community

**Comment by FountainOfNil** [comment]
hey buddy
people don't like this, nor do they like you when you write "cute" to dismiss them
this is the type of stuff that kills servers in the span of a couple of years or so
how about, instead of deleting things, you modify it to make it look better and more inline with what you wanted as a compromise

**Comment by FosterGrime-Heymynameslouie** [comment]
> I kinda agree with the points except for jeager being choosen itd be alot cooler if xenonatuean was the standard instead of jeager jeager and halo armor as cool as it is, is kinda boring and generic
> 
> while xenonatean compared to jeager has way more personality and more variety and is kinda ingrained in tgmc culture by now
> 
> like cmon, generic sci fi halo armor vs a dude with a body armor, muscles exposed and a whole lot of determination is a match up where I know where my money is going
> 
> also really like how different modules actively change how they look, instead of just having a simon says circle toy in the back change colors

image

I conceced my statement, I havent played like in 4 months and didnt know jaeger also changes depending on modules

**Comment by DrAmazing343** [comment]
As long as the ODST helmet remains in the game, I can LARP in peace. I do certainly hope some of the cape/mantles stay in, at least the variants that just hang around the neck rather than going all the way down; the shredded variants especially cut off around the waist so it doesn't significantly cover it all and looks cool as hell as an accessory.

**Comment by KingkumaArt** [comment]
image

**Comment by Iamgoofball** [comment]
can we get some actual pictures about how this looks or is this just removing all the colonial marines looking shit

**Comment by Iamgoofball** [comment]
straight up, i come to TGMC because i wanna larp with the plasma rifle and colonial marine armor shooting the xenomorphs while quoting aliens

i dont want to look like whatever the fuck this PR wants me to look like, i want to dress up as Hicks and declare we should nuke the site from orbit, because it's the only way to be sure

**Comment by MrStonedOne** [comment]
I don't understand wtf any of this is about, but the antagonistic way @Kuro020 and @MiniMeatwad are acting, is a great way to build and foster the kind of toxicity and hostility they are complaining about.

Good job, you are part of the vicious circle that leads to players becoming toxic towards game devs. :clap:

**Comment by spookydonut** [comment]
Please read: https://hackmd.io/@wlLEbadtQoCyE4iytTkonw/HymHjCLf0

This PR is unlikely to be merged, or at least not until after or as part of the introduction of the replacement armor

**Comment by spookydonut** [comment]
Per discussion with kuro this PR is no longer needed, please read the hackmd documented linked if you are unclear on what is happening with changes to armor: https://hackmd.io/@wlLEbadtQoCyE4iytTkonw/HymHjCLf0

**Pull request closed without merging**
