### PR TITLE
Make Shrike stronk

### PR DESCRIPTION
**Pull request by Pill-U**
## About The Pull Request
Gives Shrike the flag CASTE_IS_STRONG, allowing Shrike to destroy walls with an acid hole. That's it.

## Why It's Good For The Game
Makes Shrike more of an allrounder. Also kind of qol because you now dont need to scream at another caste to tear open a hole.

## Changelog
:cl:
balance: Shrike can destroy walls with holes
/:cl:

### CODE REVIEW

**Comment by Passe2142** [comment]
Smol claws.

**Comment by EvilMelonTheSecond** [comment]
Unnecessary. It's a team game, you are encouraged to scream at others. 

But it ain't a powerful tool anyways, so I guess it's fine either way?

**Comment by davidchan13** [comment]
If a Hivelord can tear down walls, Shrike and Praetorian definitely should be able to as well.

**Comment by Ragecrabbo** [comment]
Good change for lowpop hives so you dont need to scream at that single ravager to open every hole you make. 
Also you can just pretend the shrike is using their big brain powers to open holes if using their tiny arms is too immersion breaking.

**Pull request merged**
