### PR TITLE
Kills shotgun juggling

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

This PR kills shotgun juggling. If you drop a shotgun on the ground you won't be able to fire another shotgun for 3 seconds.

## Why It's Good For The Game

Shotgun juggling is bad.

## Changelog

:cl:
balance: If you drop a shotgun on the ground you won't be able to fire another shotgun for 3 seconds
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
totally agree and I support this pr not only because shotgun juggling is kinda getting absurd and old now (it was very funny first 4 rounds) but also because your pr description is so blunt that it's also equally funny in its own right

spddeemghr

**Comment by siegluck** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10852

**Comment by Waselon** [comment]
> #10852

I dont care, juggling is still there

**Comment by Naaanii** [comment]
> 

It makes you unable to fire a shotgun at all in combat, even if you get stunned.

**Comment by TiviPlus** [comment]
Adds mob vars, we can't accept this kind of implementation, see the PR siegluck linked

**Comment by Waselon** [comment]
> Adds mob vars, we can't accept this kind of implementation, see the PR siegluck linked

Linked PR solved nothing

**Pull request closed without merging**
