### PR TITLE
Icon purge and optimizations

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Killed some dupe icons and used a lossless compressor on the rest

Should be merged quickly to avoid conflicts

## Why It's Good For The Game

downloading ram

## Changelog
:cl:
code: Purged duplicate icons and compressed the rest
/:cl:

### CODE REVIEW

**Comment by psykzz** [comment]
What did you use for the lossless compression? pngout?

**Comment by TiviPlus** [comment]
optipng

**Comment by Hathkar** [comment]
A quick merge would be appreciated, since I'm also working on some icon files.

**Comment by psykzz** [comment]
@TiviPlus any idea of the general saving from the compression?
If its like 2mb, its not worth the risk imo.

**Comment by TiviPlus** [comment]
before 
image
after
image

So this shaves off about a quarter of the used memory

**Pull request merged**
