### PR TITLE
Panther Buff

### PR DESCRIPTION
**Pull request by Max-023**
## About The Pull Request

This is basically a recreation of SenioScore's PR 4055, https://github.com/tgstation/TerraGov-Marine-Corps/pull/4055/files, without the queen changes. It gives the panther a neuro tox sting to help it act as a nonlethal xeno. Additionally, the self stun time for the panther has been removed due to it making the caste unplayable.

## Why It's Good For The Game

Panther sucks. Everyone agrees it needs a buff.

## Changelog
:cl: Guprei
add: Panther variant of the neurotox sting
add: Neurotox sting to the panther abilities
tweak: Brings young panther speed to be -.8 to be more consistent with the other speeds, instead of being +.5
/:cl:

### CODE REVIEW

**Comment by XElectricX** [comment]
Just delete Panther. We already have capture-oriented castes.

**Comment by jroinc** [comment]
Alright, impressions from playing buffed panther with GODMODE aheals-

-You're tissue paper. A SG burst takes 2/3 your health. At ancient.

-You still cannot reliably deliver enough stamina damage to take down ungas.

-If you miss your pounce, you're useless for half a minute.

-you no longer self-stun on pounce, which is nice, it's not an insta-die button.

-Neuro is helpful, but doesn't last long enough when combined with tackles to actually DOWN someone. Maybe with a buddy...

5 respawns, 5 deaths, 16 aheals.

ONE stun. On someone who fell in lava. And they critted me.

The sad thing? This is a definite improvement, I could actually escape if I pounced someone with a buddy rather than 100% die every time due to self-stun.

Suggestions to fix this?

Uh. Up tackle damage EVEN MOAR, up neuro amount on inject to 4 or 5, lower pounce C/D to ~10 seconds rather than half of a minute so you can actually use it twice in one "combat"...

Or just trash the caste. This buff makes it go from "If you pounce an unga, you die" to "If you pounce an unga, you live most of the time, but do no actual damage."

**Comment by jroinc** [comment]
https://docs.google.com/spreadsheets/d/1ZnYftMYg-F3gr1vSm1i_jm3t3TBVKGnL7Aa5BQq72Uk/edit#gid=0

Relevant info. Based off of the current stats VS the other T1's, panther can't do much that they can't.

**Comment by jroinc** [comment]
Additional testing as an ayy cooperating with other ayys-

You cannot get caps in any situation where the person wouldn't be captured without your help.

Your stun is both too short at 4.5 seconds to do anything to a group, AND makes you the priority target.

Your ridiculous C/D and single actual combat ability puts you out of combat 90% of the time.

Recommendations- EITHER up the stun time to like 15 seconds OR lower pounce C/D to 9 seconds at ancient so that if you're PERFECT with pouncing, you can down people for half of your cooldown time. Currently, it's about 1/9'th.

Up the stun time to like 15 seconds OR up the damage where you're reliably getting ~40 damage a hit past a heavy user. You can't take a solo guy, at ancient, without backup, even if they're running and below 50 HP.

Up the FUCKING HEALTH. I'll pounce someone, tackle them to high green, they'll get up and shotgun me, and half my health's gone. I can run or die (though at least it's a choice now, no more self-stun). Up it to like 50% over a runner's.

Finally, remove all harm intent damage. Zero it out, nothing there.

**Pull request merged**
