### PR TITLE
Gives gorger plasma on attack

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Gives gorger plasma on attack
## Why It's Good For The Game
Gorger struggles with gaining blood after using carnage and feast.
This buff aims to allow Gorger to take longer engagements and have some source of blood that doesn't stun himself.
## Changelog
:cl:
balance: Gorger gains blood on hit
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
Practically speaking, how much plasma is that? Is it a good chunk of the gorger plasma reserves?

**Comment by Arctrooper8** [comment]
What happened to the Gorger buff that was definitively liked: https://github.com/tgstation/TerraGov-Marine-Corps/pull/14389

Also I don't think this is a good buff for gorger since it discourages using her abilities, gives them too much blood, and encourages them into just being Rav 2.0

**Comment by Xander3359** [comment]
> What happened to the Gorger buff that was definitively liked: #14389

Maintainers didn't want the buff. Only Ivan had an opinion on it and they were against it.
It was amazing to play with but it seems like we can't have nice things.
> Also I don't think this is a good buff for gorger since it discourages using her abilities, gives them too much blood, and encourages them into just being Rav 2.0

Contrary to popular belief, gorger WANTS a lot of blood. It means you can heal a lot and use your other abilities (feast/primo)
The amount of blood you get might be a bit overtuned, which I'd like to adjust (via TM), but I don't think this steps on the idea that rav has (rip and tear)

**Comment by imsxz** [comment]
gorger does want a lot of blood but it also wants to spend it very quickly because it loses the stun+movespeed on carnage if you have too much. it can become an issue especially because it takes a while to empty out blood using just the overheal, takes over a minute to use 400 blood even if theres enough xenos around to spend it on

**Comment by Xander3359** [comment]
> gorger does want a lot of blood but it also wants to spend it very quickly because it loses the stun+movespeed on carnage if you have too much. it can become an issue especially because it takes a while to empty out blood using just the overheal, takes over a minute to use 400 blood even if theres enough xenos around to spend it on

Feast and the primo ability both exist.
Although the feast ability would be a lot more usable if they didn't stale the buff PR to death.
I want to give him a new primo/rework his current primo, so that could be another good way to use blood.

**Comment by Xander3359** [comment]
Maintainers are clearly not interested in any sort of Gorger buff.

**Pull request closed without merging**
