### PR TITLE
Adds the FL-112 flamer

### PR DESCRIPTION
**Pull request by Notamaniac**
## About The Pull Request
Adds the FL-112 flamer, aka the tye_agg flamer

https://github.com/user-attachments/assets/6bb46147-f507-4ded-b7df-5c4b39907ff3

newsprites

https://github.com/user-attachments/assets/17321b7a-2438-471c-a67a-2009ebcbb622

(fire sprite examples)
tyefire1
fire2

It has a much lower burn duration compared to the standard flamer, so there's an emphasis on hitting your target rather than using it for area denial.

https://github.com/user-attachments/assets/624641e9-b07a-4fc1-ab9b-2e50b433f673
(Standard flamer for burn duration comparision)

Is this balanced? I have no idea.

3 start in the marine vendor, and fuel tanks are unlimited (for now). Back tank needs to be bought for 100 at req, but only contains 300 fuel.
X fuel tanks can also be bought in req for 15 per tank, with the back tank being 150 (though not being cost efficent).

Biggest balance issue might be how the firestacks either do/don't make up for the lower damage and projectile speed compared to rifles.

No hydrocannon attachie for now, if there's enough requests I'll add it.

## Why It's Good For The Game
New pyro guy option

## Changelog
:cl:
add: Added the FL-112 flamer, a projectile based flamer. Limited to 3.
add: Adds FL-112 back tank, FL-112 X tank, and FL-112 X backtank to req for 100, 15, and 150 points each. FL-112 can also be ordered by itself for 100 points.
/:cl:

### CODE REVIEW

**Comment by Lauwma** [comment]
As long as it does some sort of direct damage it can be balanced on the two parameters: firestacks and direct damage

**Review by Kuro020 — CHANGES_REQUESTED** [review]
ok, but tyes pr had way better flamer sprites, so use those...

**Comment by Notamaniac** [comment]
flamer sprites changed, though the fire sprite shares the same one with the APC spray (hence why I went with a different one)
Flamer might look a little too simillar to the other one, which is why I went with a bizzare design (not based off a gacha honest) so people could actually tell them apart. Could go with a different colour scheme but eh.

**Comment by zzurge** [comment]
PISS FLAMER RETUVN

**Comment by ButterChugger** [comment]
Based on the preview video of this, I don't honestly see the point of this flamer. Unless it's applying full flame stacks on a single hit then it's purely a poor imitation of our long lost beloved extended flamer nozzle. Even then there's a more rapid fashion of lighting things on fire remotely (plasma pistol, laser pistol on heat mode, laser sniper rifle of heat mode) with the same area denial effect of 'Don't stand in front of the X when they're using their weapon'. Increase the projectile speed massively, give it flame stacks. Make it actually hurt (or slow?) if it hits. Give it some gimmick that actually separates it from the other forms of fire. For now it just seems bloat.

**Comment by Notamaniac** [comment]
> Based on the preview video of this, I don't honestly see the point of this flamer. Unless it's applying full flame stacks on a single hit then it's purely a poor imitation of our long lost beloved extended flamer nozzle. Even then there's a more rapid fashion of lighting things on fire remotely (plasma pistol, laser pistol on heat mode, laser sniper rifle of heat mode) with the same area denial effect of 'Don't stand in front of the X when they're using their weapon'. Increase the projectile speed massively, give it flame stacks. Make it actually hurt (or slow?) if it hits. Give it some gimmick that actually separates it from the other forms of fire. For now it just seems bloat.

I want to see it in action first before tweaking it, chances are it might be disappointing but theory crafting can only get so far before seeing actual results. The plasma pistol fires slowly, and the laser pistol/rifle (didn't even know the pistol had a heat mode) heat mode doesn't set the tile that it's on fire- there's some leniency with missing which is why I gave it a slower fire speed and shorter burn duration to begin with. Hitting multiple times should apply max flame stacks, and slowdown is an option if it feels too weak.

If this PR doesn't get merged though, I'll see about readding the extended nozzle back in a limited amount, since the code for it is still there and it wasn't as borderline OP in area denial as the spread nozzle.

**Comment by ButterChugger** [comment]
> I want to see it in action first before tweaking it, chances are it might be disappointing but theory crafting can only get so far before seeing actual results. The plasma pistol fires slowly, and the laser pistol/rifle (didn't even know the pistol had a heat mode) heat mode doesn't set the tile that it's on fire- there's some leniency with missing which is why I gave it a slower fire speed and shorter burn duration to begin with. Hitting multiple times should apply max flame stacks, and slowdown is an option if it feels too weak.

Valid, though I feel you wont get much test data back unless it has some sort of gimmick.

> If this PR doesn't get merged though, I'll see about readding the extended nozzle back in a limited amount, since the code for it is still there and it wasn't as borderline OP in area denial as the spread nozzle.

Honestly would be a welcome sight.

**Pull request closed without merging**
