### PR TITLE
Replaces all instances of highdanger with userdanger, and updates tgui-chat constants

### PR DESCRIPTION
**Pull request by Neocloudy**
## About The Pull Request
- Replaces all instances of highdanger in the game with userdanger. Affects xeno spans too
  - These styles used to be different but after #14850 they became identical (I made them the exact same), so I'm choosing userdanger: this is the name that TG and other servers have for this combat warning style
- Updates tgchat constants accordingly, also adding spans that weren't already in for some reason
  - Admin announcements and roundend boxes will now be filtered into the OOC category
## Changelog
:cl:
code: Updated tgui chat constants so that bold warnings and alerts (red, nonitalic nonbold) are under the warning category
code: All highdanger spans have been renamed to userdanger in the code
qol: Admin announcements and roundend boxes are under the OOC category, so they will appear in chat tabs with OOC enabled
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by Lumipharon** [comment]
this wasn't a specified change in that previous pr, what actually changed? Wasn't userwarning like omega large text?

**Comment by Neocloudy** [comment]
> this wasn't a specified change in that previous pr, what actually changed? Wasn't userdanger like omega large text?

yes

**Comment by Lumipharon** [comment]
> > this wasn't a specified change in that previous pr, what actually changed? Wasn't userdanger like omega large text?
> 
> yes

bruh, about to explode your balls

**Comment by Neocloudy** [comment]
image

**Comment by Looking4bros** [comment]
Megalarge text is the only things i read, speedmerge.

**Pull request merged**
