### PR TITLE
Gives big canterbury's cockpit shutters

### PR DESCRIPTION
**Pull request by chizzy376**
## About The Pull Request
For some reason the cockpit shutters on big canterbury was missing.
Before you describe this as a balance thing, you can still melt these easily so it shouldn't be too hard to remove.
These are still meltable like the other shutters, so it shouldn't be so gamebreaking.
## Why It's Good For The Game

More windows covered, more privacy. (I get very anxious when xenos taunt me by pointing at the launch computer repeatedly)
## Changelog
:cl:
fix: gave big canterbury more shutters to work with
/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
I DID IT AGAIN

**Comment by chizzy376** [comment]
fixed i think

**Comment by dopamiin0** [comment]
make them unbreakable like you said you would coward

**Comment by chizzy376** [comment]
> make them unbreakable like you said you would coward

oh no the warlock mains are here quick scuttle the pr

**Comment by Derrick2Electricboogaloo** [comment]
I would not matter if the shutters were indestructible or not. Cant windows are hull windows. Also beans can see you through them anyways.

**Pull request closed without merging**
