### PR TITLE
cool flames now using particles

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
since lewd asked me to

https://github.com/tgstation/TerraGov-Marine-Corps/assets/98577688/faa4e4ee-ade3-4077-99e1-d48d36e6bc3f
## Why It's Good For The Game
looks cool
## Changelog
:cl:
add: new flame particles
imageadd: new flame sprites
imagedel: old flame sprites
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
Lots harder to see through. Could we get a **test merge** ?

**Comment by Lumipharon** [comment]
From a practical point of view these layer over stuff and making it impossible to see what is happening on flaming turfs.

**Comment by tyeagg** [comment]
> From a practical point of view these layer over stuff and making it impossible to see what is happening on flaming turfs.

No its below obj layer

**Comment by Coastfront** [comment]
A painting made from ground sun; As though only mirror to the torch above.
This both burns my eyes & looks incredibly fucking obnoxious, in terms of when it will actually completely replace flames in actual gameplay.

Please do not do this.

**Comment by Kapu1178** [comment]
this is gonna cause so much lag for people on lower end pcs

**Comment by Technical-l** [comment]
im not against particle fire but this needs to be worked on, dont like the colors or how much space the flames take up

**Comment by lbnesquik** [comment]
This really should get a test merge before a full merge. It has real chances of slowing down the game of people with shitty PC's. Especially if CAS or OB's get involved.

**Comment by Lumipharon** [comment]
I like particle effects, but in this case I think its a downgrade

**Pull request closed without merging**
