### PR TITLE
nerf tl-127 aim mode fire speed

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
0.1->0.3 for 1.65

## Why It's Good For The Game
nerf or nothing

## Changelog
:cl:
balance: tl 127 aim mode nerf
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -243. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SplinterGP** [comment]
how much is on mosin ? nerf it too

**Comment by David-Stormwell** [comment]
nerf or nothing boyyyysssss
also nerf mosin k ty

**Comment by TGCMbetcher** [comment]
Guess its time to break out the 37, only reason it was bad was because of the 127s firing speed.

**Review by SplinterGP — APPROVED** [review]
nerf mosin aimmode too later nerd

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-273). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
