### PR TITLE
Humans can no longer cheesily kill xenos from the inside in 10 seconds.

### LINKED ISSUE #763: Devoured humans can slash xenos from inside
## Testmerges:

Not affected by test-merges.

## Reproduction:

Devours a human, human can use their knife to hit you while being invulnerable until you spit them out.

### PR DESCRIPTION
**Pull request by DominikPanic**
:cl: LaKiller8
fix: Humans can't slash xenos from the inside anymore.
/:cl:
Fixes #763

### CODE REVIEW

**Comment by Alterist** [comment]
this is intended behaviour on tg tho

**Comment by DominikPanic** [comment]
> 
> 
> this is intended behaviour on tg tho

@Rohesie Told me it's a bug (which is why I've reported it)

**Comment by Ghommie** [comment]
Despite this possibly being a bad feature, it'd be better if this were replaced with a "resist to crawl out" do_after of 30 seconds or someting, lest we want the insider to be more of a sitting duck.

**Comment by Rohesie** [comment]
The insider is already auto-spat after two minutes. We can reduce that timer if needed, but it would be a different issue.

This is a feature that bugged out in CM code and they never fixed it. So the bug became the fix.

**Comment by Rohesie** [comment]
Damn, I thought this PR was older. Merged it too fast. Oh well.

**Pull request merged**
