### PR TITLE
Nerfs lasgun overcharge

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
you get pen or you get sunder, not both.
Damage reduced to 40, sunder to 5.

## Why It's Good For The Game
15 sunder 55 damage 40 pen and 12 shots is a big funny man meme

## Changelog
:cl:
balance: nerfed lasgun overcharge to 5 sunder and 40 damage
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -117. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by AndroidMK2** [comment]
I'm just gonna say nah to those changes

**Comment by Chaznoodles** [comment]
Revert changes and re-examine how we can change the Overcharge mode to fit into the sniper niche of the lasgun without making it the preferred mode, rather than just stepping some of the values down to make them 'not as bad'.

**Comment by SplinterGP** [comment]
reduce AP and add more damage imo

**Comment by BeloneX** [comment]
He's going for the -200 PR delta.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-135). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
