### PR TITLE
Adds marine Heavy SMG

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Heavy SMG, has Hollow points and normal ammo.
- .25 fire rate.
- 40 mag size
- 27.5/5/1
- .25 slowdown, .5 wield delay.
- Same underbarreleds as SMG-25
image

## Why It's Good For The Game
New subgun for marines, a category solely lacking in like.. any gun variety for the normal vendor beyond the 90.
## Changelog
:cl:
add: Added new SMG-45, heavy submachinegun for marines.

### CODE REVIEW

**Comment by 1kajowsmol** [comment]
🙏

**Comment by Lumipharon** [comment]
I don't see the fall off mult, unless I missed it.
Also seems weird for the smg to have a slower rate of fire than most rifles lol

**Comment by SimplySmiley123** [comment]
> I don't see the fall off mult, unless I missed it. Also seems weird for the smg to have a slower rate of fire than most rifles lol

tbf I think there is already a slow firing SMG in req/one of the seasons
_and it's the crap one_

**Review by Kuro020 — CHANGES_REQUESTED** [review]
what is this gun sprite mjp pls

**Comment by Mrrpip** [comment]
> > I don't see the fall off mult, unless I missed it. Also seems weird for the smg to have a slower rate of fire than most rifles lol
> 
> tbf I think there is already a slow firing SMG in req/one of the seasons _and it's the crap one_

SMG-27/Grease gun my beloathed.

**Comment by Loafin34** [comment]
based. now add the charge rifle

**Review by Kuro020 — APPROVED** [review]

**Comment by TellyLsc** [comment]
Unless the magazines fit into pistol mag pouches I don't see good use for it, it's the thing holding back the SMG90 too.

**Comment by 1kajowsmol** [comment]
Honestly making it so all smg mags could fit into pistol mag pouches would be awesome buff for the weapon class

**Comment by Loafin34** [comment]
This fits a cool niche of pocket suppression. If it fits in a bag like the mp-19, or in a holster like the mp-25, it'll be great. Otherwise, why bother?

**Comment by Pariah919** [comment]
letssssss gooooooooooooo

**Review by Lumipharon — APPROVED** [review]
Code fine

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Todo:
Make sprite smaller (guh)
Give it an actual fire sound
Buff the damage or the rof cuz rn its kinda stinky
Give it aimmode

**Comment by novaepee** [comment]
smg-45's volume can be lowered

**Comment by TellyLsc** [comment]
after playing with it, it plays like an ar21 with burst, less range, but no aim mode.
also .45 acp packets are only 50 bullets/packet which makes them rather bad for refilling empty magazines, not to mention there's no hollowpoint packet and req ammo boxes for the magazines.

**Comment by blackdav123** [comment]
hollowpoints are weak enough that the standard ammo will kill carriers in almost the same amount of time while being worse on everything with more armor

**Comment by Tailiik** [comment]
It needs the attachment offsets to be adjusted, they show up in weird spots. Slow firing smg feels really weird personally, doesn't really click with me and I like to run up in front so I figured I'd like a new smg. I saw a bunch of people dual wielding them though, but it seems kinda weird to have UGL type attachies on a gun that is supposed to be dual wielded.

**Comment by Breadeagle** [comment]
Any plans on letting it fit a tactical sensor? I like the gun otherwise, its fun. Kind of like a chunkier laser carbine or something.

**Pull request merged**
