### PR TITLE
Add wheelchair-mounted minigun for the elderly

### PR DESCRIPTION
**Pull request by XElectricX**
## About The Pull Request

Adds a wheelchair modified for combat. Comes with a minigun strapped to it. For use with the old man ERT.

https://github.com/tgstation/TerraGov-Marine-Corps/assets/30136710/29396220-52da-4f38-b915-3586bb602ae0

Differences from the standard minigun:
- 1000 rounds
- No recoil
- Operated with one hand
- Must be seated in the wheelchair to operate, cannot detach

## Why It's Good For The Game

It's a wheelchair-mounted minigun. The elderly have just as much a right to heavy weapons.

## Changelog
:cl:
add: Wheelchair-mounted minigun.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Funny. You should probably do something similar for sidecars, as a non meme use for this.

**Comment by XElectricX** [comment]
> Funny. You should probably do something similar for sidecars, as a non meme use for this.

I thought maintainers didn't like vehicles. If you told me this a year ago I'd have been so on it.

**Comment by AwkwardStereo** [comment]
real bloodborne hours

wheelchairminigun

**Comment by Ragecrabbo** [comment]
Best PR of 2023

**Comment by Alexeivichi** [comment]
Speedmerge (Ignore the Integration tests)

**Comment by XSlayer300** [comment]
naw you gotta make it that the minigun pushes you backwards when you shoot at it


jetpack joyride moment

**Comment by XElectricX** [comment]
> naw you gotta make it that the minigun pushes you backwards when you shoot at it
> 
> jetpack joyride moment

If there is a demand for a dual-miniguns version, I would make that a side effect.

**Comment by XElectricX** [comment]
Closing since #14697 incorporates this.

**Pull request closed without merging**
