### PR TITLE
Acid rain is now colored, and changed rain code a bit to reflect that

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

You can see acid rain being acid. Very bad, stay in door.

Thank you for RipGrayson for helping with sprites.

Here is how it goes:

You get a message that that acid rain is coming with normal rain.

Then you see visual change.

When normal rain comes back, you can go outside.

Green is bad.

With normal rain, I let it use rain_high since this used to be the acid rain sprites.

## Why It's Good For The Game

It's an additional design in the gameplay loop that acid rain really needed. If you check the sprite, acid rain is just rain_high / normal rain but faster. That's confusing and wack.

This is the one time that green doesn't mean go.

## Changelog
:cl: novaepee, RipGrayson
expansion: Acid rain is now colored; don't go outside if it starts raining green
code: Normal rain uses rain_high, the previous acid rain sprite, for nice effect
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
https://user-images.githubusercontent.com/6610922/154857743-ccf05bea-ba7b-4ab3-9994-ba2cd34b6993.mp4

**Comment by novaepee** [comment]
Acid rain has alpha on it, but just thicker. Don't be outside.

image

**Comment by Lefunny** [comment]
Can u show how it is in game?

**Comment by novaepee** [comment]
> Can u show how it is in game?

https://www.youtube.com/watch?v=m0OvE-9dC20

**Comment by novaepee** [comment]
https://www.youtube.com/watch?v=7TGR5ZBdlio

**Comment by novaepee** [comment]
https://cdn.discordapp.com/attachments/500801682058379265/945141217040154736/2022-02-20_18-12-35.mp4

**Comment by novaepee** [comment]
https://cdn.discordapp.com/attachments/504094319075131402/945427395157061672/2022-02-21_13-09-29.mp4

Kuro approves

image

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
