### PR TITLE
is to is a

### PR DESCRIPTION
**Pull request by Hughgent**
[why]: 

Reeeeeee
grammer
to
1grammer

### CODE REVIEW

**Comment by Hughgent** [comment]
the staffwho verb in the admin tab.

**Comment by DominikPanic** [comment]
You will see `is a Admin`

**Comment by Hughgent** [comment]
image

**Comment by Rohesie** [comment]
Honestly something like `Name - Rank - Playing as` would look better than "is" or "is a". There will always be different cases, such as "is a mentor" and "is an admin".

**Comment by DominikPanic** [comment]
Agreed with Roh here.

**Comment by Hughgent** [comment]
easy enough.

**Comment by Hughgent** [comment]
image

**Pull request merged**
