### PR TITLE
Removes Vgrip off SG

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Removes VGRIP off SG.
## Why It's Good For The Game
Why did we give SG vgrip which allows it to have way less slowdown, makes it 0.85 rather than 0.95 which is just silly.
## Changelog
:cl:
balance: Removes vertical grip off SG-29.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
frank-castle-wait-1577226130

**Comment by novaepee** [comment]
image
image

**Comment by Lumipharon** [comment]
this is going to fail checks, the subtype used in hvh has a vgrip that you didn't remove.

**Comment by Pariah919** [comment]
> this is going to fail checks, the subtype used in hvh has a vgrip that you didn't remove.

darn

**Comment by yyzsong** [comment]
Xope pr etc etc

**Comment by FosterGrime-Heymynameslouie** [comment]
whats up with removing attachies from guns, I only recently found out that rds got removed from t60. Why do we need to remove content from stuff

**Comment by SimplySmiley123** [comment]
> whats up with removing attachies from guns, I only recently found out that rds got removed from t60. Why do we need to remove content from stuff

Xenomorph players noticed what was killing them so they wanna nerf anything related to it even if little by little.
Or something along those lines.

**Comment by Mrrpip** [comment]
...Is...That really a big difference? It's still...Slow as shit compared to a good few other things.

**Review by Lumipharon — APPROVED** [review]

**Comment by Pariah919** [comment]
ok i was like 2 years late, but still we win these

**Comment by Nuker555** [comment]
today i will nerf the only useful smartgun because i can.

**Pull request merged**
