### PR TITLE
give me back my decaps

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
moves head hp from 150 back down to 100

## Why It's Good For The Game
decaps are basically impossible right now
this is dumb

## Changelog
:cl:
tweak: head health is now 100 again.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -28. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
I can feel them,they're coming

**Comment by psykzz** [comment]
im just here for -29

**Comment by SilencedMP5A5** [comment]
bro i want to wear a beret pls stop

**Comment by spookydonut** [comment]
does anyone remember why it was changed to 150 in the first place?

**Comment by psykzz** [comment]
Decaps are just an unfun mechanic that is unrevivable.
It should happen but rarely. 

Every rav attack shouldn't end in decaps.

**Pull request merged**
