### PR TITLE
Fob Construction Improvements

### PR DESCRIPTION
**Pull request by CCorvet**
## About The Pull Request
By default cades now will be placed wired
Comments out fob drone sentry code

## Why It's Good For The Game

Less hassle making fob is good
Removing not used code and icons for players is good

:cl:
qol: By default, cades are wired
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
We're not going back to sentries being in the machine, it was changed for a reason.

**Comment by CCorvet** [comment]
> We're not going back to sentries being in the machine, it was changed for a reason.

Oh aight, i'll remove that change, can i get a link to the PR that did that?
Guess i'll just remove the place sentry button and make razor cades the default?

**Comment by Lumipharon** [comment]
default barbed is good yeah

**Comment by CCorvet** [comment]
actually, scratch that, just merge it it, i'll leave it for someone else/me in the future if i get the inspiration again

**Comment by Lumipharon** [comment]
Why are you commenting out stuff? If it's actually unused delete it, or just ignore it.

**Comment by CCorvet** [comment]
> Why are you commenting out stuff? If it's actually unused delete it, or just ignore it.

fixed, merge if i didnt miss anything

**Pull request merged**
