### PR TITLE
Removes the Tadpole's exterior mount points

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Removes the Tadpole's exterior mount points

## Why It's Good For The Game

Gauss cannons on the land anywhere dropship were a bad idea.

## Changelog
:cl:
balance: Tadpole exterior mount points are gone.
/:cl:

### CODE REVIEW

**Review by Hughgent — APPROVED** [review]
changes are ok

**Comment by MLGTASTICa** [comment]
Even if it can land anywhere, the turrets won't do much, Removing them would make the tadpole effectively useless and defenseless against  xenos , which would turn the tadpole useless and niche.

**Comment by Wayland-Smithy** [comment]
You are simply wrong. A tad with just a handful competent marines properly prepared to build a mini-fob around a miner will now just not be killing t1s for free cause they got too close.

Just bring purp gas, flame, razerburn, frag grenades, and plenty of ammo instead of relying on the Alamos literal last line of static defense.

**Comment by AdamElTablawy** [comment]
@MLGTASTICa imagine actually believing this shit

**Comment by TiviPlus** [comment]
Tadpole balance is as stands fine

**Comment by Wayland-Smithy** [comment]
> Tadpole balance is as stands fine

image

**Pull request closed without merging**
