### PR TITLE
unused clothing icon removals + synth vendor edits

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request

~~every file i looked in got worse~~

mostly this is to clean up the synth vendor! wowza! itemized changes below

### **Synth Vendor Things:**
**_Synth essentials bundle_**
- deleted light replacer
- deleted health analyzer (all med belts come with one)
- added high-cap powercell
- added APC board

**_Backpacks_**
- deletes industrial backpack, the only one with nothing unique about it

_**Suits**_
- deletes the rsr labcoat
- adds paramedic labcoat

**_Undersuits_**
- removes the kilt. redundant and much worse looking than the kama --> kilt variant
- removes vice officer undersuit, also awful looking

**_Pouches_**
- removes the flare pouch. useful until you discover the synth can't even shoot the flare gun included
- removes the electronics pouch; although useful, i'm of the mind that synth vendor stuff should come pre-dispensed to allow for easy prep and prevent noob traps. to rectify, a powercell and APC board were added into the synth base kit
- removed the general utility pouch (can re-add); not actually a pouch?

**_Webbings_**
- deletes all the ties, they don't even attach to most TGMC undersuits and are ancient

**_Gloves_**
- deletes officer gloves and white gloves since they provide no value to the wearer and the appearance is better served by the chameleon combat gloves
- adds combat gloves as an option with a "provides armor" tag

**_Headwear_**
I believe it's bad to keep redundant items when they're not available otherwise and we have different versions readily available that have entirely different stats and head protection. new synths shouldn't be tricked into not knowing the difference between their vendor's surplus ushanka and the style line one every other marine is going to wear.
- deleted the boonie; replaced with style line and appropriate armor/storage tag
- deleted the beanie; replaced style line and appropriate armor/storage tag
- deleted the caps; replaced style line and appropriate armor/storage tag (the RO cap doesn't even show up properly on the mob)
- deleted the berets; replaced with classic style line and appropriate armor/storage tag
- deleted the ushanka; replaced with style line and appropriate armor/storage tag

### **Not Synth Vendor Things:**
- deleted a morbillion unused clothing items with old sprites. they don't appear on maps anywhere or in storage container spawns or random spawners. they're currently only admin-accessible but probably need to go (dutch's dozen remnants, for example)
- changed the purple suit jacket sprite to be identical to the blue suit jacket sprite
- removed the proc for toggling open/close on the suit jackets because it doesn't even appear as an option on the hud when you wear them; related sprites were pruned

## Why It's Good For The Game
the synth vendor is kind of awful to look at from a UI perspective and backend
image
it's also rarely maintained with regards to cosmetics, so there's tons of old stuff, and then some of the items in the vendor i think have the potential to cause psychic damage
image
image

cleaning up the list of stuff helps new players, and even a lot of experienced ones.

1. less crap to look at, gets right to the essential stuff needed to do the job
2. other critical pieces like the cell and board are more easily available, and this reinforces that fixing APCs is a core part of the role
3. removes old and awful sprites
4. removes noob trap items that are just going to get them decapped

cleaning unused icons out makes doing things like the first part of this PR easier for people in the future

## Changelog
:cl:
del: deleted a bunch of unused suit types
qol: cleaned up the synth vendor
imagedel: deleted old suit images
/:cl:

### CODE REVIEW

**Comment by coldironwarrior** [comment]
rambo linter spawn thing noted, will fix tomorrow

**Comment by Xander3359** [comment]
> Not Synth Vendor Things:

Probably should have been atomized

**Comment by coldironwarrior** [comment]
rambo linter thing still noted, will get back to this in 2 days + double-check one thing on techpriest robe

**Comment by coldironwarrior** [comment]
running final checks but closing to prevent auto-stale.

**Pull request closed without merging**
