### PR TITLE
defilers can no longer vent crawl

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

defilers can no longer vent crawl, this will prevent them from coming out of vents and instantly spreading gas and infecting.

## Why It's Good For The Game

this is cancer, and defilers are way too powerful for this, and too large

## Changelog
:cl:
balance: defilers can no longer vent crawl
/:cl:

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
> and too large

Maybe they should also have `mob_size = MOB_SIZE_BIG` then?

**Comment by MacBlaze1** [comment]
> > and too large
> 
> Maybe they should also have `mob_size = MOB_SIZE_BIG` then?
> 
> > defilers are way too powerful for this
> 
> Are they? Last I checked they don't even have a stun skill like other crawlers.

I mean from a physical point for the mob size big, but they arent exactly big enough for mob size big

**Comment by qfmysteryman23** [comment]
Defiler has already been nerfed enough. Stop trying to ruin shit for the xenos because you got killed in game.

**Comment by Hecklingheck** [comment]
Here's why i think this shouldn't happen.

1.**Vent-crawling is ESSENTIAL to a Defiler**
Defiler is the least armored caste of all the T3 (except boiler), and even tough it has good mobility, it isn't anywhere near that of a runner, so marines can still hit a Defiler with relative ease, specially considering Defilers have a rather big sprite.
Therefore, a Defiler **NEEDS** to get the jump on marines, with vent-ambushing being the most useful and prominent way of ambushing.
Removing vent-crawling from a Defiler would be like removing charging from a Crusher, vent-crawling is a core part of a Defiler.

2.**There are already ways to counter it**
You can weld vents, it's pretty fucking easy.
When a Defiler comes out of a vent, there is still a channel time for the smoke, time in wich the Defiler needs to stand COMPLETLY still, otherwise the channel will be canceled.
If you can react fast enough, and have something like a shotgun or a revolver, you can stun the Defiler during his channel, not only cancelling the smoke, but also leaving him as an easy picking, because, as i've said before, Defiler is rather squishy, with only the Boiler being more squishy.
The thing is, that a Defiler also needs to the on the frontlines and in active, close-quarters combat, where-as a boiler can just stand back and shoot.

3.**Defiler doesn't have any instant, easy-to-use stun**
The neurotoxin from his smoke and stings are slow-acting, and take some reasonably large time to kick into effect, let-alone actually stamina crit a marine, and you can also just run away from his smoke, and just stay away from him to not get neurostinged, and even if you do get neurostinged, the amount is so small, it probably won't do anything unless you already got alot of stamina damage.
This is why he needs to ambush, so that his smoke can actually do something, otherwise, marines just run away from it without any bad effect on them.

4.**Defiler also doesn't instantly infect**
The infection sting is a channel, and, unlike the neurotoxin sting, the first part of it **ISN'T INSTANT.**
For the infection sting to work, both the Defiler and the target have to stay still during the entire channel, if the target or Defiler moves, the channel is cancelled.
Meaning the only way you can actually infect marines is:

-  If you corner them into a single tile (and even then, they can still keep shooting you before you complete the channel)

-  If they have an awfully slow, like, really fucking slow, reaction time, and you get the drop on them through a vent or anything like that.

-  Or, the most likely and common, if you manage to crit them so that they stop moving.

And, EVEN THEN, due to the squishy nature of a Defiler, he still has to use his smoke to infect a single person, because chances are, they have teammates who will shoot at him, and because he needs to stay still to infect someone, he basically becomes a sitting duck.
The problem with this is that **SMOKE ALSO BLOCK'S A DEFILER'S VISION**, meaning that a Defiler needs to guide himself to his target using the emotes marines make when they cough and the light from a marine's flashlight as a way to guide themselves, and then also have to position their cursor _just right_ so that they can actually infect someone under the cover of smoke.

Anyways, this was my Ted-Talk.

**Comment by MacBlaze1** [comment]
> Here's why i think this shouldn't happen.
> 
> 1.**Vent-crawling is ESSENTIAL to a Defiler**
> Defiler is the least armored caste of all the T3 (except boiler), and even tough it has good mobility, it isn't anywhere near that of a runner, so marines can still hit a Defiler with relative ease, specially considering Defilers have a rather big sprite.
> Therefore, a Defiler **NEEDS** to get the jump on marines, with vent-ambushing being the most useful and prominent way of ambushing.
> Removing vent-crawling from a Defiler would be like removing charging from a Crusher, vent-crawling is a core part of a Defiler.
> 
> 2.**There are already ways to counter it**
> You can weld vents, it's pretty fucking easy.
> When a Defiler comes out of a vent, there is still a channel time for the smoke, time in wich the Defiler needs to stand COMPLETLY still, otherwise the channel will be canceled.
> If you can react fast enough, and have something like a shotgun or a revolver, you can stun the Defiler during his channel, not only cancelling the smoke, but also leaving him as an easy picking, because, as i've said before, Defiler is rather squishy, with only the Boiler being more squishy.
> The thing is, that a Defiler also needs to the on the frontlines and in active, close-quarters combat, where-as a boiler can just stand back and shoot.
> 
> 3.**Defiler doesn't have any instant, easy-to-use stun**
> The neurotoxin from his smoke and stings are slow-acting, and take some reasonably large time to kick into effect, let-alone actually stamina crit a marine, and you can also just run away from his smoke, and just stay away from him to not get neurostinged, and even if you do get neurostinged, the amount is so small, it probably won't do anything unless you already got alot of stamina damage.
> This is why he needs to ambush, so that his smoke can actually do something, otherwise, marines just run away from it without any bad effect on them.
> 
> 4.**Defiler also doesn't instantly infect**
> The infection sting is a channel, and, unlike the neurotoxin sting, the first part of it **ISN'T INSTANT.**
> For the infection sting to work, both the Defiler and the target have to stay still during the entire channel, if the target or Defiler moves, the channel is cancelled.
> Meaning the only way you can actually infect marines is:
> 
> * If you corner them into a single tile (and even then, they can still keep shooting you before you complete the channel)
> * If they have an awfully slow, like, really fucking slow, reaction time, and you get the drop on them through a vent or anything like that.
> * Or, the most likely and common, if you manage to crit them so that they stop moving.
> 
> And, EVEN THEN, due to the squishy nature of a Defiler, he still has to use his smoke to infect a single person, because chances are, they have teammates who will shoot at him, and because he needs to stay still to infect someone, he basically becomes a sitting duck.
> The problem with this is that **SMOKE ALSO BLOCK'S A DEFILER'S VISION**, meaning that a Defiler needs to guide himself to his target using the emotes marines make when they cough and the light from a marine's flashlight as a way to guide themselves, and then also have to position their cursor _just right_ so that they can actually infect someone under the cover of smoke.
> 
> Anyways, this was my Ted-Talk.

@Hecklingheck this was really well said, so Im closing this pr

**Pull request closed without merging**
