### PR TITLE
adds ammo packets for several calibers and adds them to the marine ammo cargo vendor

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
ammo packets are cool, they fit in your bag and they hold more ammo. Too bad you can't load them into your gun.

sizes are the size of the average size in the gun class, for exception of gpmg which is small

50 magnum
70 9x19 (pistol)
150 10x24 (rifles)
100 10x27 (dmr/br)
100 10x26 (gpmg also small)
also 50 45

## Why It's Good For The Game
Introduces an okay tradeoff.

## Changelog
:cl:
add: Added new ammo packets, and adds them to marine ammo cargo vendor
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -163. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by fernandos13** [comment]
add one for .44 ammo please

**Comment by revelation-8468** [comment]
Absolutely awesome.

Might be better putting them in the munitions vendor marines get in prep, though. The cargo vendor is pratically overflowing with ammo-related items now.

**Comment by Chaznoodles** [comment]
Remove the ammo boxes from the Req vendor, replace them with these, make the big boxes order-only?

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-199). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
