### PR TITLE
Adds the felinid species

### PR DESCRIPTION
**Pull request by DominikPanic**
Admeme only, very light and clean code-wise.

:cl: LaKiller8
add: Felinids have been added for admin events.
/:cl:

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
Did you ask Oranges for permission?

**Comment by optimumtact** [comment]
that's how it starts my man

**Comment by ishitbyabullet** [comment]
Yeah, this PR should be denied immediately. At first, it'll be event only. Soon, you'll have a repeat of /tg/ drama and a toxic community. This is a slippery slope waiting to happen where the endresult will be tons of bitching.

> You don't know what you'll unleash! You could bring down this whole Citadel! Think, man, think - of the people below! - _Dr. Breen_

**Comment by optimumtact** [comment]
jerry stick to your server

**Comment by DominikPanic** [comment]
Moths didn't enter any slippery slope and they have been in for 5+ months. Equally memey and admin-only species.

**Comment by ishitbyabullet** [comment]
Mothpeople are different for some reason. I don't think anyone would start a vote poll on tgmc or /tg/ to remove them tbh.

Best case scenario, I'll be proven wrong and look like a big loser. If so then I'm happy to not be right on this. I just don't think the risk is worth it though.

**Comment by DominikPanic** [comment]
There already was a poll regarding moths actually, that's how they became an admin-only species. Players didn't want them to be a marine race.

**Pull request closed without merging**
