### PR TITLE
jooks

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
he said i was a poorgamer

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -315. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Texicos** [comment]
stop coding

**Comment by joookschad** [comment]
please speedmerge so i will use another gun

**Comment by Pariah919** [comment]
lmao i stole the 6000th pr on this

**Comment by BeloneX** [comment]
He claimed ID 6000

**Comment by MACIEKBAKI** [comment]
based

**Comment by David-Stormwell** [comment]
fucking based as fuck

**Pull request closed without merging**
