### PR TITLE
*warcry

### PR DESCRIPTION
**Pull request by BeloneX**
## About The Pull Request

Ports warcries and all their sounds from Colonial Marines.

## Why It's Good For The Game

*warcry

## Changelog
:cl:
add: *warcry
/:cl:

### CODE REVIEW

**Comment by Guidesu** [comment]
You mad lad did it.
Good job

**Comment by Hughgent** [comment]
Update the emote help text.

**Comment by BeloneX** [comment]
> Update the emote help text.

Update the what?

**Comment by Guidesu** [comment]
He means the
says "*help"
To show wich emotes you have it

**Comment by BeloneX** [comment]
> ~Update the emote help text.~
> 
> never mind

The list is generated automatically.

**Comment by Hughgent** [comment]
Prove it works please. Screenshots/video

**Comment by BeloneX** [comment]
https://streamable.com/zv41bg

**Comment by BeloneX** [comment]
> Prove it works please. Screenshots/video

https://streamable.com/zv41bg

**Review by Hughgent — APPROVED** [review]
LGTM

**Comment by XSlayer300** [comment]
Uhh, problem. Can we make *warcry only exclusive to humans only? No other species because, well... moffs and sectoids can do *warcry too.

**Review by spookydonut — APPROVED** [review]

**Pull request merged**
