### PR TITLE
Buffs wraith's melee damage, from 20 to 23

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Wraith currently flops as it's support abilities are super niche even compared to other castes.
This pr is Kuro approved
## Why It's Good For The Game
Wraith's pretty much unused by xeno players after those two nerfs, sadly
## Changelog
:cl:
balance: Ups wraith damage from 20 to 24
/:cl:

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
just cause people don't use a caste every round doesn't mean it's bad, I feel like this is just cope code

**Comment by Arturlang** [comment]
The actual question is, why don't people play this caste?

**Comment by KrabSpider** [comment]
> The actual question is, why don't people play this caste?

Its situational, offensively and defensively weak, and you're more likely to die contributing overall nothing to the round while Marines punch your corpse as catharsis.

**Comment by lbnesquik** [comment]
> The actual question is, why don't people play this caste?

Probably not slash damage.

**Pull request merged**
