### PR TITLE
Add a samurai ERT

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
It does look a little jank without proper laminated armor, but it can be fun as an admin spawn.

## Changelog
:cl:
add: Added a new Samurai ERT for admin-spawns;
/:cl:

### CODE REVIEW

**Comment by Walarks** [comment]
give samurai weapons bump attacks

**Comment by lbnesquik** [comment]
> 
> 
> give samurai weapons bump attacks 

I have...No clue how t o do that.

**Comment by TiviPlus** [comment]
Pics of their outfit?

**Comment by lbnesquik** [comment]
> 
> 
> Pics of their outfit?

It is pretty bland ngl. I'm going to check out other codebases for other sprites.

**Comment by BraveMole** [comment]
> > give samurai weapons bump attacks
> 
> I have...No clue how t o do that.

Check Vali, it's just a component to add really easy

**Comment by lbnesquik** [comment]
I can't find any decent outfits, so i'll close this for now.

**Pull request closed without merging**
