### PR TITLE
Change Minerva's Req, CAS armament area, and add Briefing Area

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

One picture is worth a thousand words.

image

Two pictures are worth twice the thousand words

image

## Why It's Good For The Game

Minerva is known for its symmetry. I didn't follow that philosophy when I changed its req, so here we go.

To deal with the empty space from the symmetry adjustment, I had to add a briefing area. You're welcome, RPers.

Also, CAS armament area is more pretty.

## Changelog
:cl:
add: Minerva's req has been change to make req conveyor belt symmetrical in respect to req
add: briefing area in Minerva
add: Minerva's CAS armament area is now prettier
/:cl:

### CODE REVIEW

**Comment by RipGrayson** [comment]
Space tiles, otherwise looks fine to me
tile

**Comment by novaepee** [comment]
> Space tiles, otherwise looks fine to me tile

AAAA

**Comment by RipGrayson** [comment]
AI nodes don't seem to link to hallways here, please fix this
tile11

There's dense objects between these two nodes, please eliminate the left one
tile12

Besides the fact that these two nodes are stacked, the south one is unneeded, please remove it.
tile13

This isn't necessary, nodes connect diagonally so one of these nodes is extraneous. There's several of these formations around, please fix them all.
tile14

Please link the ship nodes into maint in these areas
tile15
tile16

**Comment by RipGrayson** [comment]
Only complaint is that there's no linking the nodes here to maint, which means the minions have to take a very large detour.
nod12

Otherwise everything looks good

**Pull request merged**
