### PR TITLE
Rework how shields reduce incoming damage

### PR DESCRIPTION
**Pull request by XElectricX**
## About The Pull Request

I was wondering why shields were not working when giving them high armor values. Discovered that if hard armor was higher than the damage being dealt, it just did an early return.

This PR gives shields a new formula for damage reduction, changes the integrity damage on the shield to be the amount that was absorbed overall minus the soft armor on itself, and adds new messages for when most or all of the damage is negated.

## Why It's Good For The Game

The TGMC shields have very low hard armor so I do not think this problem was ever faced yet, but in the future if any sturdier shields are added they won't bug out from trying to reduce damage to 0.

## Changelog
:cl:
fix: Hard armor on shields were not reducing damage at all if it was greater. Not anymore.
refactor: Rework how shields reduce incoming damage.
/:cl:

### CODE REVIEW

**Comment by Dzhimax** [comment]
автор долбоёб, it`s bad for the game. пиздуй на подстанцию, электрик

**Comment by helper-2** [comment]
> автор долбоёб, it`s bad for the game. пиздуй на подстанцию, электрик

Джимакс, ты чё, вообще забыл на каком языке тут говорят?

**Comment by Naaanii** [comment]
I believe hard armour was removed for a reason.
https://github.com/tgstation/TerraGov-Marine-Corps/pull/7021

Don't really want to go back to God mode shields and having to slash someone 50+ times just to kill.

**Comment by Lumipharon** [comment]
What are you doing with the code here exactly? The code was wack before but I don't think this exactly resolves it.
Absorbing_damage is what's actually applied to the shield, the damage that's reduced against the mob is separate to the shield's actual armour values, but yeah hard armour was wack.

**Comment by BraveMole** [comment]
@helper-2 @Dzhimax only english there please

**Comment by XElectricX** [comment]
> I believe hard armour was removed for a reason.
> https://github.com/tgstation/TerraGov-Marine-Corps/pull/7021
> 
> Don't really want to go back to God mode shields and having to slash someone 50+ times just to kill.


This does not add hard armor to the shield, please reread the PR. Also if melee was 0 that means shields were not actually doing anything against melee this whole time.

**Comment by XElectricX** [comment]
> What are you doing with the code here exactly? The code was wack before but I don't think this exactly resolves it.
> Absorbing_damage is what's actually applied to the shield, the damage that's reduced against the mob is separate to the shield's actual armour values, but yeah hard armour was wack.


It says it in the PR. It just fixes the calculation for when the hard armor value is higher than the damage. If a bullet did 5 damage but the hard armor was 10, the bullet still did 5 damage. Now it would do 0.

I know what absorbing_damage does, it has no effect on the damage reduced beyond telling the shield the portion of damage it can block, then it calculates hard armor. The change I made to it is that instead of the total damage reduced being what the shield takes in terms of integrity damage, it will now be what was absorbed overall. For example, a 10 damage bullet with the shield having 5 hard armor. 5 damage is the damage taken by the user, but 10 damage is what the shield takes because it was trying to block all 10 points of damage. Now let's say the shield has a different cover value and it only calculates 50% of all damage taken. The absorbing_damage would equal 5, and because that is what the shield was attempting to block, it takes the 5 integrity damage.

**Comment by Pariah919** [comment]
Shields work and are balanced off a two step system of cover that redirects the damage to the shield rather than the mob. And then that damage to the shield is reduced by hard armor (which shields have hard bullet armor to reduce low damage rounds for) then soft armor reduces that leftover damage, whatever is left over reduces the shields HP.

**Comment by XElectricX** [comment]
Misinterpreted how shields were meant to function as.

**Pull request closed without merging**
