### PR TITLE
adds thermal tarps to valhalla

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
see title
## Why It's Good For The Game
more toys for boys
## Changelog
:cl:
add: adds thermal tarps to valhalla (marine weapons vendor, specialist tab)
/:cl:

### CODE REVIEW

**Comment by Coastfront** [comment]
Memories of fire fade to sparks; Fades to cool, until a bonfire is known only as night-shaded logs.

Valhalla USED to have thermal tarps IIRC.
This lasted exactly up until "You can use a valhalla thermal tarp to become completely invisible whilst still being able to attack in the EORD" became common knowledge.

There is a decent reason they're in-hand to that glove no longer.

**Comment by 00ze-cyclone** [comment]
> Memories of fire fade to sparks; Fades to cool, until a bonfire is known only as night-shaded logs.
> 
> Valhalla USED to have thermal tarps IIRC. This lasted exactly up until "You can use a valhalla thermal tarp to become completely invisible whilst still being able to attack in the EORD" became common knowledge.
> 
> There is a decent reason they're in-hand to that glove no longer.

Did we seriously remove stuff from valahalla because of EORD? I need to go kill whoever did that

**Comment by Admiral-Gigaton** [comment]
> Memories of fire fade to sparks; Fades to cool, until a bonfire is known only as night-shaded logs.
> 
> Valhalla USED to have thermal tarps IIRC. This lasted exactly up until "You can use a valhalla thermal tarp to become completely invisible whilst still being able to attack in the EORD" became common knowledge.
> 
> There is a decent reason they're in-hand to that glove no longer.

you cant even bring shit to EORD from Valhalla, you get spawned as a faceless nerd like every other ghost who decides to join. definitely a good PR, I was wondering where they were when I was making my medic setup...

**Comment by Looking4bros** [comment]
PR #13932 Fixed the EORD invisible thing. No real reason for it to be restricted to the Valhalla SL vendor. (Whoever removed it from the main vendors didn't remove it from the SL vendor, kinda negating the point.)

**Comment by Technical-l** [comment]
> > > Memories of fire fade to sparks; Fades to cool, until a bonfire is known only as night-shaded logs.
> > > Valhalla USED to have thermal tarps IIRC. This lasted exactly up until "You can use a valhalla thermal tarp to become completely invisible whilst still being able to attack in the EORD" became common knowledge.
> > > There is a decent reason they're in-hand to that glove no longer.
> > 
> > 
> > you cant even bring shit to EORD from Valhalla, you get spawned as a faceless nerd like every other ghost who decides to join. definitely a good PR, I was wondering where they were when I was making my medic setup...
> 
> And going by memory; Back when tarps were still in valhalla, though I admit I do not know how valhalla works now; If you were living, you would spawn into valhalla as whomever you were. If you were in a container; You would be ported out of it, but for whatever reason; The tarp would keep you invisible, whilst still behaving as though you were a normal marine.
> 
> I distinctly recall one round outright seeing 6 people sit in valhalla for the entire round inside of a tarp, armed with the silly paintball guns waiting for the EORD to do funny. This was then arbitrarily declared "too much" for the world, and thus was the tarp taken from valhalla.

administration issue

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
