### PR TITLE
Revert "Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them."

### PR DESCRIPTION
**Pull request by TiviPlus**
Reverts tgstation/TerraGov-Marine-Corps#9220

I really should not have to explain why this should not have been merged

:cl:
del: Removed defender ricochet
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Do explain either way. 

>:)

**Comment by Alexeivichi** [comment]
Funmode: Disabled.

**Review by BraveMole — CHANGES_REQUESTED** [review]
why no fun mode?

**Comment by Losenis** [comment]
Finally

**Comment by GravitronBlue** [comment]
Preferably see this put behind the fun config, but otherwise reflecting every bullet results in far too much damage for an otherwise defensive ability.

**Comment by Mechanelize** [comment]
ya still take damage and the bullets only reflect back to the shooter if theyre directly nesw

**Comment by novaepee** [comment]
Plasma pistol does the job to force ancient defenders from fortify.

**Comment by Losenis** [comment]
>the bullets only reflect back to the shooter if theyre directly nesw

No they don't, they can easily reflect diagonals and I even ended up FFing people to crit that way by accident

>Plasma pistol and flamethrowers do the job of forcing ancient defenders out of fortify

Not everyone packs them, and resin jelly is a thing.

**Comment by Mechanelize** [comment]
> > the bullets only reflect back to the shooter if theyre directly nesw
> 
> No they don't, they can easily reflect diagonals and I even ended up FFing people to crit that way by accident
the shooter not other marines, its their responsibility to make sure their shots arent being deflected to other marines. playing as defender people sometimes completely stop shooting you to prevent FF and thats when the balance is fine

**Pull request merged**
