### PR TITLE
Revolver ammo rebalance, seasonal M44 bag nerf

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Fixed the full stagger effects being applied to `/datum/ammo/bullet/revolver/small/` and `/datum/ammo/bullet/revolver/ricochet/`

Increased the size of the M-44 SAA for it shoots full stagger revolver ammo without a snub-nose variant.

## Why It's Good For The Game

QHuzWEfGOB

## Changelog
:cl:
balance: S&W .357 Revolver ricochet rounds no longer stagger or knockback.
balance: M-44 SAA Revolver is now bulky like an extended barrel TP-44.
balance: M-44 SAA Revolver now does 5 more damage.
/:cl:

### CODE REVIEW

**Comment by DerrickChamberlain** [comment]
Guess we will see. This only really affects Ocelot I think. Which is hilarious. But I guess: REVOLVER ON SUICIDE WATCH.

**Comment by SilencedMP5A5** [comment]
you're funny

**Comment by SilencedMP5A5** [comment]
ok serious response though, M44 fires slow as shit and is a straight downgrade to even the snubnose.

bad pr.

**Comment by Wayland-Smithy** [comment]
>M44 fires slow as shit 

Literally only by 0.05 seconds.

**Comment by DerrickChamberlain** [comment]
Bro, all my shit gets marked as spam, sad days.

**Comment by Wayland-Smithy** [comment]
Stop shitposting constantly if you want to participate. A pure reaction post is okay once in a while, but really the PR comments are for discussion and argument about the code. If you just want to express dislike there is a thumbs down button for that, but if you have any legitimate reasons why you think this should not be merged feel free share them and I'm sure your posts would not be hidden.

**Comment by SplinterGP** [comment]
> 
> 
> Bro, all my shit gets marked as spam, sad days.

it doenst stop people from seeing it

**Comment by SplinterGP** [comment]
i say give the m44 slightly more damage, even 10 or 15% would be good considering its a bit slower than the TP44, give it some upside or something

**Comment by Wayland-Smithy** [comment]
I can dig that, will do.

**Pull request merged**
