### PR TITLE
Pillar of Spring Summer 2023 Remodel

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Expand morgue and medical supply room in Medbay. Make room for robotic cradle. Remove triage room.

image

Adjust requisition to have marines make orders right after they leave prep.

image

Add crates nearby vendors and engineering vendors close to Alamo.

image

Add MarineMed in all the specialized roles.

image

Add more easter eggs in PoS!

## Why It's Good For The Game

TGMC meta is always changing, and with that, important additions to the PoS comes with the meta.

## Changelog

:cl:
add: Expand morgue and medical supply room in Pillar of Spring Medbay.
add: Adjust Pillar of Spring requisition to have marines make orders right after they leave prep.
add: Add crates nearby vendors close to Pillar of Spring Alamo landing zone.
add: Add more easter eggs in PoS, making a total of eight easter eggs!
/:cl:

### CODE REVIEW

**Comment by blackdav123** [comment]
droppod pads are genius

**Review by RipGrayson — CHANGES_REQUESTED** [review]
stile
Space tile here

**Comment by Tailiik** [comment]
The drop pod bays might convince the Sulaco voters to not vote for such a horrible map and go to Pillar instead :hampter:

**Comment by GreatKingWombat** [comment]
Can we get the nanomed back in medical supply?

**Comment by Lumipharon** [comment]
The droppod thing looks really jank.
I feel like we just need a better system to move pods, instead of just moving everything to req because its convenient.

**Comment by coldironwarrior** [comment]
misplaced status display here
image


any chance for you to fix the wiring from the gens to the SMES? the generator APC is wired into both the grid output from the SMES and hotwired to the generators themselves. should be hotwired to just the generators themselves, i think?

**Comment by novaepee** [comment]
> also in the engineering room with all the floor tiles pried up

intended

**Comment by coldironwarrior** [comment]
> Map maintainer says it's fine for TGMC to not separate writing; after all, this isn't TGStation
> 
> image

no, I asked out of curiosity because someone who's a pretty experienced engineer player fixes it manually in the round every time and seemed to believe it had an effect on the power consumption of the ship

thanks for clarifying

**Pull request merged**
