### PR TITLE
Fix vent crawl 

### PR DESCRIPTION
**Pull request by Dgeen**
## About The Pull Request

A year and a half ago, the mechanics of climbing into the ventilation were reworked. Larvae and hunters had to get into the ventilation quickly and silently. And it is. BUT ONLY IF YOU USE THE ALIEN TAB.
If you use alt-click speedup doesn't work. This pr fixes this bug.

## Why It's Good For The Game

Fix bugs good. Larva buff double good

## Changelog
:cl:
fix: Larva and hunter now crawl into the ventilation faster (as it should have been for like a year and a half)
/:cl:

### CODE REVIEW

**Comment by Ragecrabbo** [comment]
THANK YOU

**Review by TiviPlus — COMMENTED** [review]
Shouldnt you just be updating handle_ventcrawl to just pass args properly

**Comment by Dgeen** [comment]
> Shouldnt you just be updating handle_ventcrawl to just pass args properly

"vent_enter_speed" and "silent_vent_crawl" is a xeno var, so you can't use them with living_mob. And I can't rule out that it will be used not only by xenos

**Comment by TiviPlus** [comment]
ehwhatever

**Pull request merged**
