### PR TITLE
Disable wraith ventcrawling

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
As it says on the tin.

## Why It's Good For The Game
I do not think that the one xeno which can phase through walls should get access to the vent system, an even faster way to move around the ship and past any sort of defenses. 

## Changelog
:cl:
balance: disabled wraith vent crawl
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Full salt pr lel

**Comment by InterroLouis** [comment]
Don't do it like this, remove the vent crawl caste flag from the caste datum.

**Comment by GradusNL** [comment]
Why should wraith's ability to phaseshift affect ventcrawling? How does the combination of those two traits make wraith OP? Just saying that wraith shouldn't get ventcrawling is not a justification for removing it. All I am reading is that ventcrawling is better then phaseshift, but why does that mean wraith shouldn't get it? You should describe how ventcrawling wraiths are an issue ingame instead of just saying it's bad.

**Comment by lbnesquik** [comment]
Wraith is a complete package, with ventcrawl and phaseshift, and you have to treat it that way. There is a reason not every xenos have access to every ability. 
To me, ventcrawling and phaseshift are two different mobility enhancing abilities, but with different strengths to each. 
My issue with having a wraith with ventcrawl is that they can ventcrawl into a favorable position anywhere in the ship to wreck things, before either phasing out of trouble, or phasing into somewhere to give marines trouble. 
It just feels too strong to me.

**Comment by GradusNL** [comment]
> 
> 
> My issue with having a wraith with ventcrawl is that they can ventcrawl into a favorable position anywhere in the ship to wreck things, before either phasing out of trouble, or phasing into somewhere to give marines trouble.

You can do that with vent crawl alone. Instead of phasing out of trouble you just vent crawl out of trouble. To me it seems like your issue is with vent crawling as a concept, not phaseshift or wraiths having it. That's my two cents. I'm interested to see what others think, because so far all you've got is BM saying it is a salt PR, which I am inclined to agree with. The reactions you got on discord were pretty mixed too (where you also said that you do not like vents).

**Comment by vilereaver41** [comment]
This is definetly a salt pr to stop me shipside lmao

**Comment by Surrealaser** [comment]
Probably a salt post.

Wraith is an infiltrator caste by design and ventcrawling is one of its valuable tools.

**Comment by XSlayer300** [comment]
If you die to a wraith, next time, ask marines for backup. If you know there is a wraith on the Alamo, let the shipside marines know and let them guard to important places, or just weld vents lmao.

**Comment by KrabSpider** [comment]
Shipside, wraiths are NOT going to last all that long and will just end up getting themselves killed with the abilities they have. Phase shift uses health and sunder to compensate for plasma, warp shadow is practically BEGGING people to camp it ontop of using almost all your plasma just to swap with if its far. 

They hardly have much health or armor at all, are hardly all that fast, have shit slash damage, and for the most part are practically sitting ducks waiting to be killed if they run out of plasma (which will inevitably happen with the costs they have).

**Pull request closed without merging**
