### PR TITLE
MP cant enter the mech with jetpack of his back

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Mech pilot now cant enter the mech while wearing jetpack. Also pilot will drop items in hands to prevent cheese.

## Why It's Good For The Game

Mech pilots can escape easily on mech destruction, which encourages reckless pushes with little to no risk of being killed. Inability to wear a jetpack makes pushes actually dangerous and punishable.

## Changelog
:cl:
balance: mech pilot cant enter the mech while wearing jetpack, and will drop items in hands on entering the mech.
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Might be a good idea to, in addition to just dropping items in hands on enter, give the pilot two "offhand" items while piloting (like for example two-handed weapons do to block the other hand, though here for both hands). Since, even if you drop all items when entering, what is to stop you from just leaving it in your inventory and grabbing it later when already in the mech.

**Comment by Moggram** [comment]
ejecting! ejecting! ejecting!

Ejecting out of a mech has been apart of mechwarrior pilot culture long then most of us have been alive.

**Review by RipGrayson — APPROVED** [review]
Good idea

**Comment by Derrick2Electricboogaloo** [comment]
Salt PR? :)

**Comment by Lumipharon** [comment]
> ejecting! ejecting! ejecting!
> 
> Ejecting out of a mech has been apart of mechwarrior pilot culture longer then most of us have been alive.

Someone should make an ejector seat module

**Comment by MereWalker** [comment]
I detect a salt pr.

**Comment by RipGrayson** [comment]
> > ejecting! ejecting! ejecting!
> > Ejecting out of a mech has been apart of mechwarrior pilot culture longer then most of us have been alive.
> 
> Someone should make an ejector seat module

To me this is the proper solution, make a proper ejector seat module and then we can tie it to other mechanics like mech health without a bunch of hacks.

**Comment by Strayed-Raven** [comment]
Salt PR?

**Pull request merged**
