### PR TITLE
Xenos do not keep the skills of previous lives anymore.

### PR DESCRIPTION
**Pull request by DominikPanic**
Fixes: #1883

### CODE REVIEW

**Comment by Rohesie** [comment]
This should happen when becoming a ghost.

**Comment by DominikPanic** [comment]
> 
> 
> This should happen when becoming a ghost. The skills shouldn't carry over then.

That will have more sideeffects. Aghosting vs just ghosting, also if you die, ghost, then reenter, all your skills are gone since everything is kept in the mind. This is the cleanest solution I could come up with.

**Comment by Rohesie** [comment]
Yet the mind is a mob var. Why does it have to be carried over to the ghost, and from the ghost to the living body?

**Comment by DominikPanic** [comment]
> 
> 
> Yet the mind is a mob var. Why does it have to be carried over to the ghost, and from the ghost to the living body?

Because that's how minds work. The mind is the mob representation of the client in a way, it's made to be persistent.

**Comment by spookydonut** [comment]
What does this have to do with xenos

**Comment by DominikPanic** [comment]
> 
> 
> What does this have to do with xenos

Some things check `usr.mind?.cm_skills` meaning that if there are CM skills, it treats it like a human person.

**Comment by spookydonut** [comment]
This should be done in mind transfer code not login

**Pull request merged**
