### PR TITLE
Adds the Ornamented Cap

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
jojogaming

## Why It's Good For The Game
More clothing options are cool.

## Changelog
:cl: Lewdcifer
add: Added the ornamented cap.
/:cl:

### CODE REVIEW

**Comment by Blundir** [comment]
It's cool and all, but... vendor?... Seriously? I got answer no for putting non fitting stuff in vendors before.

**Comment by novaepee** [comment]
image

**Comment by Lumipharon** [comment]
Awesome sprite. Anime reference as standard marine equipment is guh though.

**Comment by MereWalker** [comment]
JOJO fans when they see an unsucked **** in ss13.

**Comment by Al-1ce** [comment]
Feels like something that should be planetside.

**Comment by FosterGrime-Heymynameslouie** [comment]
this feels way out of place for tgmc I think

**Comment by Tupinambis** [comment]
Good as a rare meme item, awful as a vendor item.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
shouldnt be a vendor item

**Comment by lbnesquik** [comment]
Good, but not standard items.

**Pull request merged**
