### PR TITLE
Field commanders can no longer use the smartgun effecitvely

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Title. Removes the skill entirely.

## Why It's Good For The Game
FC shouldn't be played as smartgunner 5. That's dumb and detracts from the role.

## Changelog
:cl:
balance: fc can no longer use smartguns effectively
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -44. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by ilikesaying** [comment]
targeted towards the best SG ever:
Elsa

**Comment by David-Stormwell** [comment]
epic

**Comment by neohenry** [comment]
> 
> 
> targeted towards the best SG ever:
> Elsa

kek, I always wonder when the FC will not have the SG ability anymore. It's always fun to see how I can grab a SG as a FC.

**Comment by Dolth** [comment]
FCDR will still deploy and join the fights. This is just removing IFF which, as a reminder, allowed FCDR to stay behind the lines while being on the frontline.

**Comment by Marmio64** [comment]
being able to use the smartgun is nice since it allows field commanders to play more safe, unnecessary in my opinion.

**Comment by neohenry** [comment]
It's the marine's job to secure the kills, not the FCDR. When deployed, the FCDR operates as a medic, RO (ensuring that the marines have supplies), SL, and engineer to ensure that marines do their job. The FCDR is essentially a synthetic with a gun as a self-defense option.

The SG on the FCDR will force the FCDR to focus on killing xenos when that's the job of the marines, and on the right hands, the SG is a weapon to reckon with. Let the marines do that, not the FCDR.

**Comment by Marmio64** [comment]
Smartgunners are never supposed to be the ones to secure kills, if you're trying to secure kills as a smartgunner you are doing it wrong. You are a support soldier as a smartgunner, you provide covering fire for escaping marines, you help when fast xenos are weaving in between marines, and you help weaken xenos with your weapons sunder. Smartguns have poor damage, they're for supporting team mates, not securing frags.

**Comment by neohenry** [comment]
> Smartgunners are never supposed to be the ones to secure kills, if you're trying to secure kills as a smartgunner you are doing it wrong.

They assist in securing kills. Sundering and hitting xenos hard help in assisting kills. Even then, they can one vs one against xenos (assuming SG don't go horizontal).

The proper supports are the medic and engineers. It's important to separate support from assisting kills; Sibg had the same argument against removing SG from FCDR since the argument claims that SG is support. It did not convinced people that SGs are support, so FCDR does not spawn with a SG.

**Comment by neohenry** [comment]
FCDR should use CAS, railgun, mortar, and OB more than the SG to assist the marines, and I'm guilty of not using those four more.

**Comment by davidchan13** [comment]
Pretty neutral on this, SG machine gun is pretty stronk but Leaders don't get unique weapons as is. It's nice when the FC can sit in the middle of the marines, and it's not like the FC spawns with the mg in their locker anymore. 

As an alternative to this PR, I'd suggest some kind of IFF Carbine, SMG or Pistol to help reinforce that FCs are not front liners but should be sticking with the pack of marines to provide support.

**Comment by Chaznoodles** [comment]
Good. The FC shouldn't be running about with muh IFF gun. They don't need something special, their role already does that for them. Playing them as rooty tooty IFF gunman is bad.

**Review by Hughgent — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-46). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
