### PR TITLE
Re-adds Hyperscale guns.

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request
Readds hyperscale guns, since Lumi's fix on gun updates, that could be the issue.
While this is merged, please report random crashes.

## Why It's Good For The Game

Colorable guns - maybe

⠄⠄⠠⠂⠁⢂⠨⠡⡑⢀⠈⠄⠄⠄⠄⠄⠄⠄
⠄⠑⠁⠂⠪⢈⢆⢧⡺⡜⡜⡌⡆⢆⠆⡆⣣⡣⡀
⠄⡡⠨⠐⡐⡰⡑⡧⣫⡺⡱⡱⢘⠔⡑⢌⠎⣞⣵⠄
⠁⠄⢂⠅⢬⡸⡮⣫⢧⠫⢊⠊⡂⠣⠊⢜⢪⢪⢺⣷
⢁⠌⠄⢪⣺⢽⡹⣜⢔⠜⠔⠐⠄⢀⢈⠈⢔⢸⠱⠿⡀
⣣⡮⢂⡳⡽⡵⡝⡎⡆⡊⠊⠄⢀⠄⠰⡽⡌⡇⠄⠄⣆
⣕⢽⢈⢸⢹⡪⡯⡺⣪⠪⠌⡂⠄⢂⢽⣺⢪⢢⠂⢦⠌
⡹⣽⢐⠘⢜⢎⠮⡫⢸⢘⠌⠄⠂⡢⡳⠭⢧⠣⡮⣪⡆
⣮⠣⢂⡳⡑⠜⢈⠄⡳⠁⠄⡀⠡⢀⠐⢈⢘⡎⠅⡺⡇
⣟⠈⡆⡅⠅⡃⠠⠄⢌⠂⠄⡈⠮⡢⢕⣐⣠⢳⠡⡻
⣫⢊⢸⢱⠁⡂⢀⠄⠠⠁⠄⠈⠡⠒⠅⢕⣻⣦⢀⠅
⢾⡤⡈⠂⢁⠐⠄⠄⠰⠄⠄⠈⠄⢈⠠⠠⢨⢆⢢⠁
⡽⣞⣗⢧⡢⡀⡁⠄⢈⠂⠅⢀⠠⠄⠄⠄⡁⠂⣝
⣯⣗⢗⢇⢯⢺⢨⢢⠄⠂⠅⠅⢀⠄⠂⠄⠔⢱⢹
⡯⣞⡝⣎⢧⢳⡹⡼⡸⡐⠠⠐⢀⠈⠄⠁⢄⠣

## Changelog

:cl:
add: Readds hyperscale guns.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
The resurrection.

**Comment by Alexeivichi** [comment]
Finally, we're going full AAA experience in 2d spessmen.

**Comment by women-not-real** [comment]
⠄⠄⠠⠂⠁⢂⠨⠡⡑⢀⠈⠄⠄⠄⠄⠄⠄⠄
⠄⠑⠁⠂⠪⢈⢆⢧⡺⡜⡜⡌⡆⢆⠆⡆⣣⡣⡀
⠄⡡⠨⠐⡐⡰⡑⡧⣫⡺⡱⡱⢘⠔⡑⢌⠎⣞⣵⠄
⠁⠄⢂⠅⢬⡸⡮⣫⢧⠫⢊⠊⡂⠣⠊⢜⢪⢪⢺⣷
⢁⠌⠄⢪⣺⢽⡹⣜⢔⠜⠔⠐⠄⢀⢈⠈⢔⢸⠱⠿⡀
⣣⡮⢂⡳⡽⡵⡝⡎⡆⡊⠊⠄⢀⠄⠰⡽⡌⡇⠄⠄⣆
⣕⢽⢈⢸⢹⡪⡯⡺⣪⠪⠌⡂⠄⢂⢽⣺⢪⢢⠂⢦⠌      Finally, the colored guns we need and definitely don't deserve.
⡹⣽⢐⠘⢜⢎⠮⡫⢸⢘⠌⠄⠂⡢⡳⠭⢧⠣⡮⣪⡆      
⣮⠣⢂⡳⡑⠜⢈⠄⡳⠁⠄⡀⠡⢀⠐⢈⢘⡎⠅⡺⡇
⣟⠈⡆⡅⠅⡃⠠⠄⢌⠂⠄⡈⠮⡢⢕⣐⣠⢳⠡⡻
⣫⢊⢸⢱⠁⡂⢀⠄⠠⠁⠄⠈⠡⠒⠅⢕⣻⣦⢀⠅
⢾⡤⡈⠂⢁⠐⠄⠄⠰⠄⠄⠈⠄⢈⠠⠠⢨⢆⢢⠁
⡽⣞⣗⢧⡢⡀⡁⠄⢈⠂⠅⢀⠠⠄⠄⠄⡁⠂⣝
⣯⣗⢗⢇⢯⢺⢨⢢⠄⠂⠅⠅⢀⠄⠂⠄⠔⢱⢹
⡯⣞⡝⣎⢧⢳⡹⡼⡸⡐⠠⠐⢀⠈⠄⠁⢄⠣⠁

**Comment by Starfirejordan** [comment]
Causing crashes again Le sadge

**Comment by Starfirejordan** [comment]
image

**Pull request closed without merging**
