### PR TITLE
Replace the lobby HTML window with a new lobby menu

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

The new lobby is done with screen objs and maptext so 0 icons needed
When moused over options will glow red (please pick a nonarbitrary color for me to use instead)
Note there seems to be a race condition when sending people back to lobby will try look again later maybe

## Changelog
:cl:
add: Replace the lobby HTML window with a new lobby menu
code: Removed some junk code
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
image
@SplinterGP

**Comment by grinkgo** [comment]
this is dope af

**Review by SplinterGP — APPROVED** [review]

**Comment by Tennessee116** [comment]
~~Suspiciously semblant of Aurora~~

Looks particularly cool. I personally think stating the current year isn't necessary though.

**Comment by TheWiznard** [comment]
bro I logged on and this is epic, good job

**Comment by XSlayer300** [comment]
> ~Suspiciously semblant of Aurora~
> 
> Looks particularly cool. I personally think stating the current year isn't necessary though.

The current year is already in the Background section, so yeah. I can agree.

**Comment by spookydonut** [comment]
> It makes ghosts observing have ghost [NAME] from observing from lobby

**Comment by TiviPlus** [comment]
> > It makes ghosts observing have ghost [NAME] from observing from lobby
> 
> > On initialize() for some reason it does NOT update some buttons stuff
> 
> as reported on discord apparently.

Yes I'm aware I was telling splinter as I was fixing it

**Comment by AtlasRules** [comment]
yeah you can't even hit the observe button

are you familiar with the phrase "if it ain't broke don't fix it"?

because the old one was fine

**Comment by SplinterGP** [comment]
> yeah you can't even hit the observe button
> 
> are you familiar with the phrase "if it ain't broke don't fix it"?
> 
> because the old one was fine

this was not even what caused it, also following your speech we'd be on 2009 space station 13

**Comment by EgorDinamit** [comment]
Could you make buttons' active space less advanced to the right? Most people could press on empty space, to focus on Byond window, and accidentally click one of those.

**Comment by TiviPlus** [comment]
> Could you make buttons' active space less advanced to the right? Most people could press on empty space, to focus on Byond window, and accidentally click one of those.

Fixed in the newer commits

The observe bug was caused by a oversight changing it to tguialert so stop crying on the wrong pr thanks

**Pull request merged**
