### PR TITLE
Adds a vehicle spawner to xeno valhalla

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Adds a vehicle spawning area to xeno valhalla. Also adds the associated button and landmark for spawning vehicles (currently apc and tank)
tgmc  _maps_map_files_generic_Admin_Level dmm  - StrongDMM 5_9_2024 12_59_39 PM
## Why It's Good For The Game
Let's xenos test their abilities on vehicles safely within valhalla.
## Changelog
:cl:
add: Added a vehicle spawning area to xeno valhalla
add: Added a vehicle spawner and vehicle spawner landmark (Things used for spawning in Valhalla)
/:cl:

### CODE REVIEW

**Comment by Wisemonster** [comment]
Note, I didn't add the vehicle button to marine Valhalla cause I didn't know how qdell_null affected mobs inside of a vehicle.

**Comment by MLGTASTICa** [comment]
if interior doens't matter for xeno valhalla then why not make a subtype without one ? code is all compatible.

**Comment by Wisemonster** [comment]
It doesn't really affect anything, considering the interior is deleted when the apc is, and if there ever is a caste that can enter the apc, that should be testable in valhalla.

**Comment by TiviPlus** [comment]
> Note, I didn't add the vehicle button to marine Valhalla cause I didn't know how qdell_null affected mobs inside of a vehicle.

it force ejects them iirc

**Review by TiviPlus — APPROVED** [review]

**Review by TiviPlus — COMMENTED** [review]
Actualy just checking i see where = xenocave and link = vehiclexenocave

**Comment by Wisemonster** [comment]
Yes, because I was only adding the 1, so I figured not having it be named "xenocaveleft" would be fine

**Pull request merged**
