### PR TITLE
NV scopes

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
requested, title

only big scopes have nv for now
-> only for a special scope for now
## Why It's Good For The Game

Yay content

## Changelog
:cl:
add: As of yet unavailabe NV scope
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
How do you counter this as an ayy, assuming that people throw 3-5 scopes on the Alamo and just prevent anyone from getting closer than a screen to the FoB?

**Comment by TiviPlus** [comment]
Made only a special as of yet available nvscope since mjp told me he'd balance it

**Comment by psykzz** [comment]
Just to be clear, this is a new scope that isn't available right now, just adminbus?

**Comment by TiviPlus** [comment]
Yes

**Pull request merged**
