### PR TITLE
Revert "ballistic armor module"

### PR DESCRIPTION
**Pull request by BeloneX**
Reverts tgstation/TerraGov-Marine-Corps#5767

You didn't think this trough MJP, this ruins hostile ERT and HvH.

## Changelog 
:cl: 
del: removed the ballistic armour module.
/:cl:

### CODE REVIEW

**Comment by TGCMbetcher** [comment]
Everyone aims for the head anyway. This changes nothing

**Comment by BeloneX** [comment]
> Everyone aims for the head anyway. This changes nothing

Everyone = me

**Comment by Kuro-ai** [comment]
HvH isn't balanced for,and like the other dude said,this doesn't affect helmets,hostile ERTs can aim head and ignore the module completely

**Comment by fernandos13** [comment]
HvH has nothing to do with this.. if your doing HvH right your already aiming head....
and this wont save you.. unless jaeger also.... slots in head? idk

**Comment by TiviPlus** [comment]
Nerf it if you disagree

**Comment by SplinterGP** [comment]
HvH = Aim head

**Pull request closed without merging**
