### PR TITLE
Xeno scalping

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

It's a Element
Also cleaned up some bayonet shitcode
## Why It's Good For The Game

Mhmm yes

## Changelog
:cl:
add: Machetes and Knives can now be used to scalp dead xenos
/:cl:

### CODE REVIEW

**Comment by Chaznoodles** [comment]
What does this add other than a gimmick for one player

**Review by psykzz — APPROVED** [review]

**Review by Hughgent — APPROVED** [review]
Neat

**Comment by joookschad** [comment]
I guess it fixes shitcode so it's alright. Also something new, so its cool

**Comment by AtlasRules** [comment]
could make xeno scalps sellable, who knows, the skin of vicious, acid-blooded beasts might sell well to private collectors?

**Pull request merged**
