### PR TITLE
Mjolnir, a new armor

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request
security
image

image

Add a new arm, leg, chest, and two helmets. One helmet shows the lower jaw, the other covers the entire head.

## Why It's Good For The Game

M A R A T H O N

## Changelog

:cl:
add: Mjolnir, a new armor
/:cl:

### CODE REVIEW

**Comment by XSlayer300** [comment]
john haloma-


gohs dangit

**Comment by Derrick2Electricboogaloo** [comment]
I love how the first one is just SPI armor instead of Mjolnir

**Review by Kuro020 — APPROVED** [review]

**Comment by SzkieletorNutric** [comment]
Really mid.. and barely looks different from the ones already in the game imo
Visor is also way too big from the side.
If it's supposed to be a nod at the Marathon pc vibes then even that is barely noticeable

**Comment by novaepee** [comment]
image

**Comment by ilikesaying** [comment]
image

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
