### PR TITLE
Deployable items can be deployed on turfs with dense border objects.

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
What it says on the tin. Provided that the border object isn't facing you (and so blocking your access) you can deploy items like teleporters/sentries etc onto turfs with barricades or other border objects.

More of a QOL change than anything.

## Why It's Good For The Game
Being able to deploy things on a turf you can walk through is good.
QOL

## Changelog
:cl:
qol: Deployable objects can be deployed on turfs with border objects such as barricades, that aren't obstructing your access
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
one step toward deployable guns on deployable shields

**Comment by bowlofcereal** [comment]
always been an annoyance that you couldn't do that

**Comment by Losenis** [comment]
Finally, some good fucking prs

**Review by TiviPlus — APPROVED** [review]

**Comment by Losenis** [comment]
Was this tested? You can no longer move from cade to cade.

image

**Comment by Al-1ce** [comment]
Experiencing the same issue as [Losenis](https://github.com/Losenis). This is terrible for marines and is making the FOB impossible to navigate on high-pop. This needs to be removed immediately until whatever problem is fixed.

**Comment by Lumipharon** [comment]
It has nothing to do with this pr, I can't replicate it on master so it's probably one of the test merges.

**Pull request merged**
