### PR TITLE
Adds a three minute cooldown to Drones recycle abilities

### PR DESCRIPTION
**Pull request by ClosetedSkeletonGH**
## About The Pull Request
Adds a three minute cooldown to drones recycle abilitiy

## Why It's Good For The Game

The ability is very good and given to a T1 that gets plenty of population, with the amount of ways you can transfer plasma to anyone who needs it/amount of drones running around at any time, I feel like it getting a real cooldown is a good idea.

## Changelog
:cl:
balance: Adds a 3 minute cooldown to Recycle
/:cl:

### CODE REVIEW

**Comment by Araulius** [comment]
Wut? Just secure the body like you would a marine. 01110011 01101011 01101001 01101100 01101100 00100000 01101001 01110011 01110011 01110101 01100101

**Comment by Wayland-Smithy** [comment]
I'm not sure what this accomplishes other than making recyclers who are support castes jobs even more hectic because they need to manage a long cooldown and plasma now, also nice webedit.

Marines can quickly bike around a dozen T3 and T4 corpses to FOB which will be impossible to recover no matter how long they take to turn into points. Maybe this would make sense if all xenos had the ability.

**Comment by Mrrpip** [comment]
Can't you just evolve/devolve shift to bypass this?

**Comment by AlexCrimson** [comment]
Seems kinda pointless. If a Drone has access to a dead Xeno, it can probably hide the body or ask another with the ability to recycle, if their own is on cooldown.

**Comment by Lumipharon** [comment]
Yeah this seems needless. Forcing xenos to store bodies somewhere and manage a cooldown is pretty ??? at that stage they might as well just brazil the body for 2 minutes like they used to instead of gibbing.

**Pull request closed without merging**
