### PR TITLE
add big map table to cic

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
its a big map table also has drawing functionality
image
## Why It's Good For The Game
big map table for command looks cool
## Changelog
:cl:
add: big map table to cic
/:cl:

### CODE REVIEW

**Review by Lumipharon — CHANGES_REQUESTED** [review]
Make it like an actual table. i.e. it has coverage, and you can jump on it. Gotta have my CIC shootouts

**Review by Lumipharon — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Your map versions are old and would revert the fixes and changes I made in https://github.com/tgstation/TerraGov-Marine-Corps/pull/13417

Please update your repo, there shouldn't be any merge conflicts, since you're only adding a single prop.

**Comment by Lumipharon** [comment]
Add this to init so you can cross between this and other raised objects
```
var/static/list/connections = list(
	COMSIG_OBJ_TRY_ALLOW_THROUGH = PROC_REF(can_climb_over),
)
AddElement(/datum/element/connect_loc, connections)```

**Review by Kuro020 — APPROVED** [review]

**Comment by Lumipharon** [comment]
BTW why is this a new object and not just a child of normal map tables?

**Review by RipGrayson — APPROVED** [review]

**Pull request merged**
