### PR TITLE
PoS prep overhaul

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
overhauls PoS prep

## Why It's Good For The Game
hopefully faster prep and a better experience when the round starts. 
whole

and some changes that i did after but only affects the selected area ((LZ ERT on the north still is the same))
flufl

## Changelog
:cl:
qol: overhauls PoS prep
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by XSlayer300** [comment]
Y'got space tiles.

**Comment by fernandos13** [comment]
last commit was to fix that (and the cryo posters that got splatterd in doors instead of walls)

**Comment by fernandos13** [comment]
commit "space tiles fix. and cryo doors" to be more precise

**Comment by SpaceLoveSs13** [comment]
Add the TGMC logo instead of multiple N logos please.

**Comment by fernandos13** [comment]
TGMC logo is 3x3. i cant fit it in there

**Pull request merged**
