### PR TITLE
Fixes Sh*taco Engineering prep 

### PR DESCRIPTION
**Pull request by Alterist**
Fixes an oversight in engineer prep where the closets were only alpha squad accessible

Why It's Good For The Game

Fixes a bug. bugs are bad on a server that is constantly live, requiring admins to deal with your mistake for 24+ hours

🆑
fix: Fixes closet issue in Engineer Prep
qol: Adds seed extractor to Hydro
/🆑

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by BraveMole** [comment]
it's not Sh*taco, it's Suc*laco

**Comment by SplinterGP** [comment]
Its sucklaco not shitlaco

**Comment by DerrickChamberlain** [comment]
Yeah I have been having git issues, thanks!

**Comment by DerrickChamberlain** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/6768
Tivi, use mine. I was having git issues, but they are now fixed.

**Pull request closed without merging**
