### PR TITLE
Kill gas mask sound pref

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Removes a pointless pref.

So it turns out we have a funny verb pref for the sound effect some gas masks play when equipped.
Thats it. This pref is for one specific sound in the game.
## Why It's Good For The Game
Verb bloat, also cope if you can't bear the 1 second sound effect of someone putting on a gas mask, which you probably can't hear over the sound of 50 ungas spamming warcry.
## Changelog
:cl:
del: Removed a pref verb for gas mask equip sounds
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
This sound is actually annoying, though. If it shouldn't be a verb preference, at least implement it into game preferences.

**Comment by chizzy376** [comment]
why not remove the sound outright?

**Comment by Looking4bros** [comment]
Simply play without sound, i do it all the time now. It's Ez.

**Comment by Lumipharon** [comment]
It's a minor sound that plays once. If you have a problem with this I unno how you deal with all the other sounds in the game.

**Comment by chizzy376** [comment]
>  how you deal with all the other sounds in the game.

I have my tgmc set to 5% when groundside because the gunshots have started giving me tinnitus

**Comment by lKiseki** [comment]
At this point just remove the thing entirely, yeah. It was a preference for a reason, and forcing players to hear something they didn't want to is stinky.

**Comment by lbnesquik** [comment]
I thought it was cool :(

**Comment by Zangeiti** [comment]
just kill the sound itself, its incredibly annoying and its loud AF

**Comment by TiviPlus** [comment]
Just make it a pref in the UI

**Comment by Lumipharon** [comment]
> Just make it a pref in the UI

why? Are we going to add a pref for warcry sounds?
For bag rustling?
Every other sound?

**Comment by XElectricX** [comment]
> > Just make it a pref in the UI
> 
> why? Are we going to add a pref for warcry sounds? For bag rustling? Every other sound?

Probably not bad ideas actually. Maybe not war cries but stuff like bag rustling and stuff that's purely for flavor.

**Pull request merged**
