### PR TITLE
Nerfs throwing knives

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Reduces damage from 25 to 20
## Why It's Good For The Game
Marines are still too strong
image
## Changelog
:cl:
balance: knives damage 25 -> 20
/:cl:

### CODE REVIEW

**Comment by Tailiik** [comment]
Pretty easy to see that knives are silly strong when throwing knives are the second best choice at breaking down doors/shutters only to actual C4

**Comment by Oscari-pog** [comment]
If not a damage buff they really shouldnt be able to quickly break things which exist as a block to be opened by a limited, dedicated tool.

**Comment by Strayed-Raven** [comment]
Just gonna throw this in here. Doors only. If you want to bust a wall you have to shoot it or use C4. And not everywhere you want to enter you want to through the door. Also I cannot believe you people are taking this PR that seriously. Really speaks for the state we are in though.

**Comment by Xander3359** [comment]
I can't believe people are actually taking this seriously. Knives are in a awful position right now. Yikes.

**Pull request closed without merging**
