### PR TITLE
Swaps sleep() to use SECONDS define

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
 decided to go through and run thesleep\((..)\) regex from https://github.com/tgstation/tgstation/pull/70452 
## Why It's Good For The Game
Better readability, better maintainability (probably). Looks nicer too
## Changelog
 no player changes

### CODE REVIEW

**Comment by SplinterGP** [comment]
no idea why desc not showing but  "decided to go through and run thesleep\((..)\) regex from https://github.com/tgstation/tgstation/pull/70452 "

**Review by Lumipharon — APPROVED** [review]

**Review by TiviPlus — CHANGES_REQUESTED** [review]
I feel like a lot of thse like the MC less than 10 tick ones shouldnt be using the define

**Comment by SplinterGP** [comment]
> I feel like a lot of thse like the MC less than 10 tick ones shouldnt be using the define

on the tg pr MSO says the intent of those is sleeping as little as possible(so it just wakes up on next tick) so them using TICKS makes sense you can check on 70452

**Comment by TiviPlus** [comment]
oh i see its a port ok tzhen

**Pull request merged**
