### PR TITLE
Removes old mechas.

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull Request
Deletes old mechas such as ripley, gygax, phazon and etc.
Deleted old mecha weapons and utility tools.
Deleted useless defines and vars for mechs.
Deleted temp control and pressure control mech alerts, as we don't have such.
Combined duplicates of files with mecha wreckage, mecha parts and mech bay.
Props weren't touched.
Mech ui now looks like this with all the changes:
image
## Why It's Good For The Game
Less unused code, less unused sprites.
## Changelog
:cl:
del: Removed old mechas.
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
I dont get this code, the unused mech code is kept for the sake of tg parity to make drag and drop ports easy? You're also removing stuff like props so i dont get why this is useful

**Comment by Helg2** [comment]
I'll readd `mecha_parts` as props if you meant them.

**Comment by chizzy376** [comment]
Please don't remove this. People, like mappers and admins, still use these.

**Comment by lbnesquik** [comment]
Don't remove the props.

**Comment by Helg2** [comment]
Not removing them.

**Comment by Helg2** [comment]
It would be pretty cool only for a few rounds, before rushing them becomes a meta.
Also in our realities you don't get anything useful from salvaging except from some metal, but it's just easier to wrench a few chairs.

**Comment by TiviPlus** [comment]
While I usually agree with removing dead code, in this case I disagree because this was left in on purpose in order to make maintaining it easier so you can just drag drop from tg
ill let other maintainer wigh in before I close this though

**Comment by Helg2** [comment]
Can you list what are you referring to as left on purpose, because if it's not all of the changes, it can be just reverted.

**Comment by Lumipharon** [comment]
I'm fine with leaving it as is for maintainability reasons

**Comment by Looking4bros** [comment]
A UI change to cut out all the unused stuff would be nice. I reflexively set Mechs to take from internal tank, even though that's not a thing here.

**Comment by TiviPlus** [comment]
> Can you list what are you referring to as left on purpose, because if it's not all of the changes, it can be just reverted.

The thing is all of it

The reason it's like this is we want it to be as drag and drop as possible so we dont need to do any extra work when maintaining it

**Pull request closed without merging**
