### PR TITLE
reduces runner pounce stun time

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
2 seconds is a long time considering most stuns now stun for like 0.5 to 1 second, reduced the freeze time to 0.25 to compensate though

also touches hunter pounce to still have the same stats as befo

## Why It's Good For The Game
brings runner stun in contention with most other stuns in the game

## Changelog
:cl:
balance: runner pounce stun time reduced, freeze time reduced
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
Good change. I personally requested this and I feel it's necessary given how oppressive Runner is currently.

**Comment by lbnesquik** [comment]
Hrmmm, on one hand it is strong, but runner is sort of carrying the role of hunter/lurker atm. Not sure if it is that strong.

**Comment by BorranScail** [comment]
Runner stun time is on par with runner's survivability. Pounce, get a couple slashes in, and leave quickly. This is an ideal case. Most of the time they are also getting shot at and losing health. Runner is in a good place right now.

**Comment by turnop** [comment]
> 
> 
> Good change. I personally requested this and I feel it's necessary given how oppressive Runner is currently.


Literally and unironically a skill issue

**Review by David-Stormwell — APPROVED** [review]
Disapproved, sadly Xenos fucking suck and don't need nerfs to a noob caste.
A highly skilled Marine can still kill a highly skilled runner with the correct loadout or teamwork.

**Comment by David-Stormwell** [comment]
fuck I approved it.
 **IT IS NOT APPROVED.**

**Comment by Pariah919** [comment]
david moment

**Pull request closed without merging**
