### PR TITLE
Announcements now use TTS

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
Untested because my docker is dying

## Why It's Good For The Game
HEAR NO ORDERS SEE NO ORDERS SPEAK NO ORDERS

## Changelog
:cl:
add: Orders and hivemind now use TTS
fix: fixed default tts not working
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
oh i forgot to say hivemind has tts now

**Comment by coldironwarrior** [comment]
~~i really hate to ideasguy so this sucks because i know it's way way way more effort than how you currently have it implemented and potentially also not possible given how TTS is implemented~~

im big on accessibility, i like high-qol stuff, a big part of that is multimodal communication of important information so in concept having not just visual but also audio modes for orders seems cool and i really want this

the quality of squad and command orders on tgmc is so incredibly low though that i know better and that this would be a detriment to the game. squad orders have the mercy of disappearing after a few seconds on screen even if they're chock full and chock full of garbage. i dont want to have to listen word-for-word to someone spam repeating "PUSH CAVES/CLEAR WEEDS, CLEAR WALLS, CLEAR XENOS/Get on TAD" for six lines dictated to me. this happens very often and my experience in administrative handling of it is that it's...not...so you get the same people doing the same spam over and over and over again.

i'd only be down to see this implemented if there was a way to toggle announcement TTS separate from local chat TTS; otherwise this is going to be a hinderance to the game.

**Comment by Lumipharon** [comment]
turn it on for campaign announcements

**Comment by lbnesquik** [comment]
We have a lot of announcements, and they often have special characters. Not suuure about this, although I get where you are coming from.

**Comment by aarrisu** [comment]
wwhen big text tts so leaders can make people hear them in radio :)

**Review by Lumipharon — APPROVED** [review]

**Pull request closed without merging**
