### PR TITLE
New Jaeger set: Helljumper

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request

Adds a new set of Medium Jaeger armor, the Helljumper armor series.

image
Image shows the 4 base colors. Its compatible with all other color variants.

Sprites done by Fitz on discord

*I also moved around the greyscale configs a little to clean them up.*

## Why It's Good For The Game

Cool new armor set.

## Changelog
:cl: Fitz
add:Adds a new set of Medium Jaeger armor, the Helljumper armor series.
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]
name it ODST :shotgun:

**Comment by Tristan63** [comment]
image

**Comment by ilikesaying** [comment]
Helljumper Helljumper where you been?
Feet first into Hell and back again!

**Comment by RuneQuester** [comment]
HELLDIVERS

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
