### PR TITLE
DMR now has sniper range

### PR DESCRIPTION
**Pull request by EvilMelonTheSecond**
## About The Pull Request
DMR given 40 tile range same as snipers.

## Why It's Good For The Game
DMR has standard range despite being a "Designated marksman rifle" meaning it can't even use its 30 tile accuracy for some reason. Now bullets won't go poof before even reaching the accuracy falloff.

## Changelog
:cl:
balance: DMR gets sniper range
/:cl:

### CODE REVIEW

**Comment by EvilMelonTheSecond** [comment]
Now with 100% less web edits

**Comment by Naaanii** [comment]
Not really needed nor is it a good change. Just use the TL if you want sniper range.

**Comment by EvilMelonTheSecond** [comment]
> 
> 
> Not really needed nor is it a good change. Just use the TL if you want sniper range.

Why use DMR then? The same range as an AR and lower DPS. I don't see why its a bad thing if people want long range options.

**Comment by SplinterGP** [comment]
> Not really needed nor is it a good change. Just use the TL if you want sniper range.

Imagine having a DMR with less range than GPMG and other rifles

**Comment by usnpeepoo** [comment]
pretty sure DMRs were already buffed with ammo capacity this seems a little overkill

**Review by SplinterGP — APPROVED** [review]

**Pull request merged**
