### PR TITLE
Brings back Icarus Shipyard/millitary outpost.

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

Remember this map? yeah i fixed it, and it is playable now, compared to the old version, this should have better flow, less clunkiness and be more straight forward.
## Why It's Good For The Game

I like to think this map is as straight forward as big red, compared to other big maps that might seem tedious to play. more maps are also good.

## Changelog

:cl:
add: near total revamp of icarus.
/:cl:
Edited icarus.
image

### CODE REVIEW

**Comment by Naaanii** [comment]
Would be nice to see miner locations and underground if possible.

**Comment by vilereaver41** [comment]
> Would be nice to see miner locations and underground if possible.

Updated below picture.

**Comment by Ldip999** [comment]
Two green disks at the same time

**Comment by vilereaver41** [comment]
> Two green disks at the same time

Fixed as part of a big bug squash.

**Comment by 00ze-cyclone** [comment]
it's not fucking playable in the sligthest

**Comment by DemonOfHatred** [comment]
There's alot I could say about this map but I'm just going to say absolutely awful. No one enjoyed being put in this fish barrel.

**Comment by Ldip999** [comment]
Long sieges are my favourite part of magmoor but an even field where neither side steamrolls the other will mean the first disk will bog for a whole hour of xeno d-day which I don't think is fun for either side but might be wrong

**Comment by Aroliacue** [comment]
Spots that're roofed and marked as caves are pretty consistent and very confusing. The image above that has the 'underground' areas circled are inaccurate, caves stretch into science and medical hallways too.

**Comment by CaputCapital** [comment]
icaruslines

This is more accurate if I'm correct.

**Comment by Apple-107** [comment]
the crashed ship being an alamo causes some issues where xenos cant build, considering its a disk, that means its wide open for mariens to push into

i think this map has some fundamental issues with its design and doing some touch-ups arent going to fix it

there's no way this is okay either
image
image

**Comment by vilereaver41** [comment]
A lot of changes have been made to adress issues, the crashed alamo, aswell as center disk have been opened up a whole lot more to make it more fun and easy.

**Review by RipGrayson — COMMENTED** [review]
Due to increasing player complaints, I'm setting a hard limit on this map. If the fundamental issues this map has aren't resolved within 24 hours I will take this map off TM until it's sufficiently reworked to be re-tested. This will likely require extensive reworking of practically every part of the map until it meets quality standards.

**Comment by vilereaver41** [comment]
Closing because no fix seems to be making players happy.

**Comment by Looking4bros** [comment]
F

**Comment by Ldip999** [comment]
The map's design is just garbage. Thank you for trying though, nothing but respect.

**Pull request closed without merging**
