### PR TITLE
T-26 AMR price reduced from 75 to 65

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Title.

## Why It's Good For The Game

This gun needs some love.

## Changelog
:cl:
balance: T-26 AMR price reduced from 75 to 65
/:cl:

### CODE REVIEW

**Comment by OpsCoretango** [comment]
65

**Comment by David-Stormwell** [comment]
Way too fucking low, considering it's a IFF sniper rifle with the ability to Lase for huge amounts of damage + AP.
Most I'd say would be 65+.

**Comment by Waselon** [comment]
> Way too fucking low, considering it's a IFF sniper rifle with the ability to Lase for huge amounts of damage + AP. Most I'd say would be 65+.

изображение

 It is, in fact, only slightly better than free TL-127, and worse than T-81

**Comment by OpsCoretango** [comment]
70 points?

**Comment by Waselon** [comment]
Honestly i dont understant whats the big deal around this shitty gun, i just wanted to make it used more, but everyone is like, hey its too cheap for a shitty gun that is bought in 1/1000 rounds.

**Pull request merged**
