### PR TITLE
Buffs Carrier Panic drop Ability while still mainly retaining the nature of the nerf before it

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
## About The Pull Request

Increases the HP requirement for Panic drop usage from 81/275 or below (0.25) to 145/275 or below (0.56)
image
image
image
image

## Why It's Good For The Game

The ability was introduced with #10910. From what I gathered it was semi-OP and an instant kill trap card toward marines for most of the time, especially in 1v1 situations. Then came #11028 which I think was a good direction in evening out the ability from a trap card to more of an escape tool for them. 

The only issue with the latest nerf PR is it makes the ability basically for 99% of situations impossible to use, Carrier is by far nowhere near a durable caste where you can easily gauge up 81 HP to use your "escape tool" because the carrier is practically already dead at that HP. You are straight up pop tart status and to top it off your targeted hard. 

I like to think I have a pretty normal reaction time and even with the ability keybinded I still can't use panic drop and that is mostly due to the PR setting the health requirement of an already squishy caste way too low. 

With my changes I try to stay and appeal to both sides with the middle ground being, the health requirement is bumped up but not by that much, it is still very much in the "Carrier you need to GTFO off frontlines you stupid who-" amount of HP while now being far more practical as an escape tool where you don't have to be 3 shots away from death just to use it. 

Will the marine 1v1ing the carrier get fucked again now? Yes, they will but now marines have a huge deterrent that they will be quick to learn before chasing carriers since they tend to target them hard anyways, If the carrier still fights even after pulling the panic drop it's still far risky because they are already at 145 HP and carrier is in no way a melee slash and clash caste.  

## Changelog
:cl:

balance: Carrier panic drop ability being adjusted after being nooked! 

/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Lol

https://github.com/tgstation/TerraGov-Marine-Corps/pull/11079

**Comment by KillerOrcaCora** [comment]
That is mighty funny, hopefully with 2 PRs saying the same thing our overlords can come to reason this time around...

**Comment by Strayed-Raven** [comment]
Anything is better than carriers being able to unload all the huggers at the drop of a hat. I can accept that health threshold at least

**Comment by KillerOrcaCora** [comment]
The ability can longer drop specialty Hugger types, which is not what I had intended and that is severely busted.

**Comment by KillerOrcaCora** [comment]
No reason to remove the ability has its purpose in the carrier kit.

**Review by TiviPlus — APPROVED** [review]

**Comment by Ragecrabbo** [comment]
honestly with huggers now visible on carriers this doesent seem so bad anymore

**Pull request merged**
