### PR TITLE
Reworks armor entirely, adds new modular armor sprites. Deletes the old ones.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Title basically.

Reworks most marine armor to be entirely homogenized with some minor exceptions, removes old armor sprites and removes the old marine modular armor sprites as the behest of kuro.

Base armor starting is 45+5. So 50 with .4 slowdown, .5 if you put storage on it.
Every piece is 10 armor, every piece adds .1 slowdown.

To be paired with a xeno slash damage rework PR which is #4436 

Adds a vest which is basically equivalent to vanilla modular armor, just looks nice I guess if you don't want to be chonky boy.

Removes pyro because surt is basically the same thing.

Restats b18 and 17 to be in line with the future slash pr

tm with #4436 

## Why It's Good For The Game
Homongenizes armor because bump basically made mobility irrelevant.

## Changelog
:cl:
add: The PAS-11 vest, new modular armor sprites. Jaeger undersuit.
del: Removed old marine armor from the vendors, deleted the old modular armor sprites at the behest of kuro.
balance: ALL armor is now homogenized, jaeger armor is now 15, has .1 slowdown. The armor totals on EVERYTHING total up to 45+5. Removed old marine armor. Added the PAS-11 vest, which is basically equivalent to a jaeger armor with baldur and magazine pouches.
/:cl:

### CODE REVIEW

**Comment by DinkleNH** [comment]
Its balancing, in the way that nuking all options and choices for game play and leaving 1 armor set with three different appearances is balancing.

**Comment by LorenzoTheMarauder** [comment]
I discussed some of this shit in deadchat the first round this PR was merged, here are my most relevant points:

1: The ability to mix and match armor plates was a pretty big factor in making a build, for example you could go all heavy/medium/light plates or take the heavy chestplates and helmet, the light arm and leg plates, and a valkyrie module to resplint your limbs when they get broken over and over. You protect your organs but still have a decent amount of speed.

2: Removing shit instead of fixing a problem with balance is lazy.

3: Pretty much gimps the idea of MODULAR armor when you make it less modular.

4: Paired with the xeno slash nerf this whole PR basically changes nothing. Xenos deal less damage, marines take more damage. You've essentially canceled out your own changes.

**Comment by ZanderDowdall** [comment]
What I like 
-New armour looks cool
-Jaeger undersuit is a nice touch

What I dislike
-Combined with the shotgun nerf #4389 marines are now way easier to gank when using stuns
-Illusion of choice because all armour is the same
-When paired with the xeno damage thing it cancels out in terms of raw damage, but doesnt account for stuns, which again makes marines less powerful

**Comment by Kuro-ai** [comment]
Almost like that was the point or something
Modular is still modular,each piece still adds armor and slowdown and you can not attach pieces to be faster

**Comment by rhomm-dev** [comment]
Not a big fan of **completely** homogenized armor values as it takes away variety, perhaps just tightening up the old differences would be good better?

**Comment by mrhugo13** [comment]
I'll explain my issue with this rework simply with these 2 pictures and by telling you to compare those top 2 armor values

**Comment by Kuro-ai** [comment]
Yes the other suits need to be brought down in value to be consistent

**Comment by Kuro-ai** [comment]
There is no difference,they're all the same stats

**Comment by AndrixBr** [comment]
matching the armor rework with the shotgun nerf now runners have a chainstun meta since there is no counterplay to then whatsoever

**Comment by RenGusta** [comment]
Mkay so since I can't reply directly I'll address by person. 

@DinkleH.
Armor was Heavy or Nothing anyway. Regularly I'd have the armor values of all Marines checked, and it'd be Heavy or Higher. Homogeny in line with the norm created. 

@Lorenzo. 
I tried to fix it with balance for over 6 months but it wasn't able to be done, so the Nuclear option was enacted. 
Mix and Match was Heavy and Almost Heavy. 
The point of Modular was always aesthetics, as Kuro can attest to. 
The idea of this was homogeny and de-escalation. Isn't shy the results are very similar, but I've made the numbers smaller and created greater consistency based on the new xenos slash balance. 

@MrHugo
It wasn't touching other armors yet because that would have been a bit too much work to ask. 

@Andrix
I kind of expected I to misbehave but I wasn't pushing for or supporting the Shotgun Nerf anyway. I have my own solution for what it addresses.

**Comment by saprasam** [comment]
if we're nerfing xeno slashes and marine armor then will it even make a difference other then just "we removed armor"

**Comment by sunofang** [comment]
*pain. remove

**Comment by DinkleNH** [comment]
Why did this get merged, all it does is reduce marine armor to friendly fire and other sources while keeping xenos relatively the same

**Pull request merged**
