### PR TITLE
Revert "Modularizes half of Big Red [MDB ignore] (#9750)"

### PR DESCRIPTION
**Pull request by Victor239**
## About The Pull Request

This should have been a long testmerge, there's huge issues:

- Stationside vendors fully powered on groundside:

- 3 miners right infront of LZ

Not pictured is additionally buildings that are fully powered without a breakable APC.

Also this PR in general clearly modularises too much of the map - it makes it very difficult for xenos to adapt to because every single round you have to figure out new natural chokepoints and ideal maze locations. Why did 50+ areas have to be modularised instead of a more conservative number?

With the already existing awful Xeno win rate (about 23% this past week) this is just one of the recent code changes that have hugely damaged balance. 

## Why It's Good For The Game

This map is in a genuinely awful state and absolutely horrible for xenos now.

## Changelog
:cl:
del: Reverted Big Red modularisation.
/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
relevant clip

https://user-images.githubusercontent.com/54422837/158049260-a8acde60-9b64-4af5-adaa-a3e6dc3b8c69.mp4

p

**Comment by Al-1ce** [comment]
I wonder which mapper added the vendors? That's insane powercreep.

**Comment by EvilMelonTheSecond** [comment]
"xenos can't adapt" is not a real problem as marines also have to adapt, it ain't a one side ordeal.

The vendors on the other hand are probably an oversight by the map maker since most of the vendors have semi recently got changed to be different for shipside-groundside.

Area power I have no clue about. Every area needs an APC to power machines normally. And no, electrified razorwire has nothing to do with APC power as the posted clip suggests.

**Comment by Firefox13** [comment]
> Every area needs an APC to power machines normally

It is possible to areas (with or without some edits) to work without an APC built in them.

> electrified razorwire has nothing to do with APC power as the posted clip suggests.

it depicts a defender having "fun" by having to destroy a ton of razorwire roundstart. It's not electrified

**Comment by RipGrayson** [comment]
So let me get this straight.

There are oversights (who would have thought that 100+ modular maps would have a couple inserts with problems) so instead of I dunno, reporting or even correcting the issues yourself, you just decided to go for a full on revert.

And you did this less than 24 hours after merge before I could even push out a patch to fix the **known** issues. If I didn't check this PR I wouldn't have even known about some of them because you decided you had to revert instead of opening issues or even pointing them out on discord.

The telling part of OP's revert description is here
>every single round you have to figure out new natural chokepoints and ideal maze locations
It's almost like we don't like having to learn new areas, so we dug around and found some issues less than 24 hours after merge so we would have a excuse for a complete revert.

**Comment by hyper2snyper** [comment]
Issue reporting bugs is better in this situation. Either to the GitHub to the pr maker directly.

**Comment by Victor239** [comment]
> There are oversights (who would have thought that 100+ modular maps would have a couple inserts with problems) so instead of I dunno, reporting or even correcting the issues yourself, you just decided to go for a full on revert.

I'm not a mapper so I won't be correcting the issues myself. The PR covers my description of the existing issue, the same way most PRs do. I didn't see any contribution guidelines saying I need to make an issue to describe the problem before making a separate PR, and am coming from having contributed to other SS13 servers in this way so that sounds like a personal preference.

Additionally I posted this revert because this map clearly wasn't testmerged for long enough. Merging straight to master is pretty bizarre for a rework this large so it seemed sensible to revert until you fix all your issues.

**Pull request closed without merging**
