### PR TITLE
Tactical Sensor Helmet Module

### PR DESCRIPTION
**Pull request by Runian**
## About The Pull Request
Port of https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/149 (only the sprites)

Adds a helmet module that functionally acts like a tactical sensor. Can be activated/deactivated while worn.
Can be attached to any helmet that can also attach a night vision helmet module (completely arbitrary).

Purchasable at Requisitions for 150 points under the Clothing tab.

Code-wise, makes the code for tactical sensor / motion sensor into a component.

## Why It's Good For The Game
More stuff to bring req to its knees of 0 points when marines want the best of both worlds (knowing where xenos are and not dropping their gun).

## Changelog
:cl:
add: Tactical Sensor Helmet Module. Only obtainable via Requisitions for 150 points in the Clothing tab.
/:cl:

### CODE REVIEW

**Review by Neocloudy — COMMENTED** [review]
peak idea

i'm not a maintainer but this is all just copypasta from the normal motion sensor and you may want to make this into a component/element or something so the exact same behavior can be shared between this and the tac sensor and be a little Less Shitcodey

**Comment by FosterGrime-Heymynameslouie** [comment]
spedemrhg

**Comment by Admiral-Gigaton** [comment]
damn, seems a little expensive considering the dispenser is only like... 80 credits and its a pretty decent building, while this is... 150, almost double that of something that could be considered better... anyways great PR fucking FINALLY I can actually use the sensor

**Review by Kuro020 — APPROVED** [review]

**Comment by SimplySmiley123** [comment]
> damn, seems a little expensive considering the dispenser is only like... 80 credits and its a pretty decent building, while this is... 150, almost double that of something that could be considered better... anyways great PR fucking FINALLY I can actually use the sensor

I mean, this is still a helmet module.
By default this would be a direct upgrade to other modules, bar welding for engineers/miner centered loadouts lmao.

**Comment by Lumipharon** [comment]
This is stinky req powercreep. If you want tac sensor and magharness, take the belt.

**Comment by Lauwma** [comment]
Me when 150 points + opportunity cost but surely it's powercreep and just not a mid investment of points (you could be getting tyr 2 for this price and an actual good module)

**Comment by DorfGuy1** [comment]
As if the xeno mortar wasn't power creep, but that got merged.

**Comment by Looking4bros** [comment]
> This is stinky req powercreep. If you want tac sensor and magharness, take the belt.

Tac sensors don't work on the belt, it's Joever...

**Pull request closed without merging**
