### PR TITLE
Buffs PAS storage

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request

Increases storage capabilities to bring it closer to Jaeger and its storage mods after they were buffed.

## Why It's Good For The Game

Makes PAS a more competitive choice instead of being chosen simply out of laziness or stubbornness. 
Also marine buff good, xeno buff bad. Thank you for coming to my Ted-Talk

## Changelog
:cl:
balance: Increased allowed item size in PAS storage.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
just remove general storage holding up to normal sized

**Comment by lovegreenstuff** [comment]
oh also
web edit gaming.

**Comment by QualityVan** [comment]
add the quickdraw toggle while you're at it

**Comment by QualityVan** [comment]
also everything in the weight bypass list is weight_class_normal

**Comment by SplinterGP** [comment]
Just do storage buff ? dont think it needs to be faster than medium jaeger with general storage

**Pull request closed without merging**
