### PR TITLE
Armor Check Refactoring

### PR DESCRIPTION
**Pull request by KornFlaks**
## About The Pull Request

All armor checks now execute through proper soft armor checks instead of ancient CM armor checks.

How ancient you say?

image

## Why It's Good For The Game

All armor interactions now execute through TGMC armor checks and returning TGMC values.

That means yes, Xeno armor now mean something.

Previously, xeno armor was infact returning 0 (as in no armor for anything) for numerous interactions. This was legacy code from Apop himself in the initial commit of open source CM.

Several ancient interactions such as acid rain were in fact doing 100% of damage to xenos regardless of armor due to this legacy code. Now, acid rain damage is mitigated according to xeno "acid" armor and, in the case of ancient crusher (and only ancient crusher), now made immune to acid rain.

**WILL NEED TESTING. XENO ARMOR WILL NEED REBALANCING / REDUCING.**

Note that all checks were replaced with soft armor pulls. THIS IS INTENDED. Previous legacy code checking armor ONLY CHECKED SOFT ARMOR ON TARGET LIMBS.

This is a refactor only, enabling intended gameplay. NO BALANCE CHANGES DONE except in the case where armor now is properly pulled.

**NOT COMPATIBLE WITH #10213** as we change the same lines.

## Changelog
:cl:
refactor: Armor checks now correctly request target armor.
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
It's just the few lines in that one lava change so it'll just be a super easy merge conflict to resolve.

**Comment by Lumipharon** [comment]
Nice

**Review by TiviPlus — APPROVED** [review]
Improvement but ideally hard armor should also be considered later

**Comment by KornFlaks** [comment]
Pain. God damn it git

**Comment by KornFlaks** [comment]
I hate my life

**Pull request closed without merging**
