### PR TITLE
Changes isotonic mix to 7.5 iron, 7.5 nutriment.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Changes isotonic mix to 7.5 iron, 7.5 nutriment.
Isotonic injectors hold 2 doses of isotonic solution (2x 7.5 iron 7.5 nutriment)
## Why It's Good For The Game
Better mix than current isotonic.
## Changelog
:cl:
balance: Isotonic injectors hold 2 doses.
balance: Isotonic solution is now 7.5 Iron and 7.5 Nutriment.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
All in all, you're removing the sugar from them and changing the amounts of the rest of them.

**Comment by Derrick2Electricboogaloo** [comment]
About time this was made.

**Comment by Xander3359** [comment]
> All in all, you're removing the sugar from them and changing the numbers of the rest. Saying it here since it's not explicitly said in the PR

Yes, I guess that is relevant to mention.
This is the old injector mix
image
This is the old pill mix
image

**Comment by iforgotmeword** [comment]
I would have liked to keep sugar in it as if I remember right it stacks with the other chems

**Comment by Xander3359** [comment]
Sugar just turns into nutriment at a lower ratio.

**Comment by Xander3359** [comment]
Closing this since I put up a new PR changing the mix.

**Pull request closed without merging**
