### PR TITLE
MG-60 reduction

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Reduced MG-60 bullet damage to 25 from 27.5. AP and sunder unchanged.

Also reduced capacity to 200 because the damage per mag is still hugely better than what it was previously.

The MG-60 buff pushed the gun to a level of DPS exceeding anything else in the game (except the two bigger MG's) which is not particularly ideal considering it is usable in hand, and viable on the move.

It will still be better DPS that any other portable gun by a fair margin, but slightly less guh to fight.
## Why It's Good For The Game
Giga MG-60 bad.
## Changelog
:cl:
balance: Reduced MG-60 damage to 25 from 27.5, and reduced magazine capacity to 200 from 250
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
viable on the move

implies that the t60 can be moved around alot with bipod deployed and aimmode move speed reduction enabled?

**Comment by srxtreme** [comment]
RIP NPC

**Comment by XElectricX** [comment]
Leave the mag size alone. It's the most important/useful part of the gun. Just revert the damage buff it was recently given.

**Comment by Tupinambis** [comment]
Disagree with mag size change. Damage nerf is good though

**Comment by This1sPanda** [comment]
In which timeline do I live, where this gun is worthy of any kind of nerf. It's already a miracle we still have that peashooter in weapons vendor.

**Comment by Al-1ce** [comment]
the T-160 is already a noob trap. this is really not needed.

**Comment by Starfirejordan** [comment]
I support because currently a belt that holds 3 T60 mags plus 1 one loaded in the gun = 1000 rounds of ammo, not to mention if they use general storage moduel to carry 2 more which make its 1500, this also doesn't include satchel and backpacks, which make it ammo econ god tier. not to mention ammo packets which have more ammo and save better on room

So even tho I dislike this PR out of personal reasons, I support this balance change. because yea know maybe having more ammo then the SG85 with god tier suppressing fire isn't such a good thing

**Comment by Lumipharon** [comment]
For reference, T60 is currently just a better, free minigun.
After the change it will be the same as a minigun but slightly lower ap.

**Comment by Starfirejordan** [comment]
> For reference, T60 is currently just a better, free minigun. After the change it will be the same as a minigun but slightly lower ap.

Personally already been routing for Minigun to get a buff since it kinda just sucks, only thing good about it is ammo capacity, that the only reason I get it

**Comment by Al-1ce** [comment]
> For reference, T60 is currently just a better, free minigun


 I don't really get your arguement. Minigun powerpacks have like... a thousand rounds. The T-60 didn't come up last time the minigun was buffed, so why now? What changed? I feel you got hosed down with it and died:  -- is this is a salt PR?

I don't really get the 'issue' here, but if you really want ...maybe consider making the minigun more dangerous? Higher RPM, sunder, raw damage, or a _MUCH_ larger ammo capacity would work.

**Comment by Lumipharon** [comment]
> > For reference, T60 is currently just a better, free minigun
> 
> I don't really get your arguement. Minigun powerpacks have like... a thousand rounds. The T-60 didn't come up last time the minigun was buffed, so why now? What changed? I feel you got hosed down with it and died: -- is this is a salt PR?
> 
> IMO there is no 'issue' here, but if you really want ...maybe consider making the minigun more dangerous? Higher RPM, sunder, raw damage, or a _MUCH_ larger ammo capacity would work.

What changed is the t60 was buffed less than two weeks ago from 20 damage to 27.5. It was overbuffed, and I am tweaking it down. It is still significantly better than it was a fortnight ago.

**Comment by Durbles** [comment]
If you're nerfing the damage and AP then nerfing the magazine seems unnecessary. 90% of the time that I see this gun in the field it's by marines who just wanna dakka.

**Pull request merged**
