### PR TITLE
Buffs BR damage by 2.5 and reduces falloff by 0.2

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

After having used the BR a fair amount, I am still a firm believer that the BR is not very good. This PR hopes to remedy that by buffing it's base damage slightly, reducing it's falloff by 0.2 since it's a flat reduction and falloff is currently shared with the marksman bullet, meaning the BR suffers much more from falloff than the DMR.

All together this should make the BR much more competitive, especially with the potentially incoming addition of the Skirmish Rifle which may otherwise step on it's toes a fair amount.

## Why It's Good For The Game

The BR is underused and not that good compared to either using a T12 or a DMR. With the Skirmish Rifle likely on the horizon as well, without some buffs the BR may just become completely obsolete. This reduces it's incredibly crippling 0.5 damage falloff to 0.3, and also gives it just a bit more base damage.

## Changelog
:cl:
balance: BR now has +2.5 damage, and -0.2 damage falloff.
/:cl:

### CODE REVIEW

**Comment by RenGusta** [comment]
Should help offset the more notable falloff impact of the bullet with the halved base damage. Not a bad way to do it.

**Comment by EvilMelonTheSecond** [comment]
I still refuse to use a full auto gun with <50 ammo mag

**Comment by davidchan13** [comment]
I feel like burst fire is the thing BR needs to better differentiate itself from the DMR,

**Comment by Pariah919** [comment]
I'd like the BR upped to 40 round magazines and  which gives it double over the DMR and puts the Heavy rifle category at 30 (skirmisher, if that's merged), 20 (dmr) and 40 (BR).
Skirmisher has generally better fire rate than the BR and better cqc potiential, but the BR has better ammo economy, but worse damage than the DMR.
Give it far lesser falloff as well.

**Comment by Hekzder** [comment]
Took in MJP's feedback, overall think it helps to carve out the BR's niche as a medium-long range weapon in the heavy rifle category better than the previously proposed flat damage buff.

**Comment by SplinterGP** [comment]
> 
> 
> I still refuse to use a full auto gun with <50 ammo mag

skill issue

**Review by SplinterGP — CHANGES_REQUESTED** [review]
i'm just agains't the mag increase, it shoulndt have that much more ammo, it should be smaller than double of DMR's always

**Comment by Hekzder** [comment]
> i'm just agains't the mag increase, it shoulndt have that much more ammo, it should be smaller than double of DMR's always

Okay done.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
@SplinterGP Dont like this

**Comment by Hekzder** [comment]
> @SplinterGP Dont like this

why

**Comment by SplinterGP** [comment]
> 
> 
> @SplinterGP Dont like this

hit up on discord and tell why, i think the falloff change is okay

**Comment by BraveMole** [comment]
Closing as stale.

**Pull request closed without merging**
