### PR TITLE
Sulaco Dirt + SD

### PR DESCRIPTION
**Pull request by Hathkar**
## About The Pull Request

Adds some dirt to the Sulaco's floors.
Re-arranged Sulaco's SD a bit.
Added some extra windows.
Removes the memorial floating in space.

## Why It's Good For The Game

SD is slightly easier to defend.
SD: https://i.imgur.com/tME2OCu.png
Dirt.

## Changelog
:cl:
add: Dirt on the floors in the Sulaco
tweak: Sulaco SD is slightly easier to defend
/:cl:

### CODE REVIEW

**Comment by neohenry** [comment]
Marines don't have access to SD, so they would have to blast the doors down.

**Comment by jroinc** [comment]
Is it really a good idea to add dirt to the shipmaps to allow unfilled sandbags to be used? 

The assumption is if you're up there you should be at a disadvantage, and it currently feels like retreating is just a way to get better ground.

**Comment by Hathkar** [comment]
Dirt as in dust and general filth, not actual dirt you would put a plant in.

**Comment by Hathkar** [comment]
> 
> 
> Marines don't have access to SD, so they would have to blast the doors down.

Changed the airlocks to Free Access.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
