### PR TITLE
Replaces SL vendor flamethrower options with flamethrower bag

### PR DESCRIPTION
**Pull request by Yttriums**
## About The Pull Request

Replaces SL vendor flamethrower options with flamethrower bag, priced at 25 points
## Why It's Good For The Game

Currently the SL vendor allows you to purchase an FL 84 flamethrower and extra tanks for it. This is rarely useful, as there are free roundstart flamers available. If all free flamers are taken, you generally don't need the SL to use a flamethrower as well, hence it's almost always a bad option.

The flamethrower bag is an actual upgrade to the standard flamer that lets the SL flex into a mazeclearing role while still retaining space for a well-rounded kit. I've priced it at 25 points, as it's a powerful option even when competing with radiopack.
## Changelog
:cl:
balance: Replaces SL vendor flamethrower options with the Flamethrower bag at 25 points
/:cl:

### CODE REVIEW

**Comment by Zangeiti** [comment]
The flamer variant in the flamethrower bag doesn't include an under-barrel extinguisher (and you can't put one on), so it is more of a sidegrade in exchange for more storage space. Perhaps include it as another option rather than an outright replacement?

**Comment by Yttriums** [comment]
> The flamer variant in the flamethrower bag doesn't include an under-barrel extinguisher (and you can't put one on), so it is more of a sidegrade in exchange for more storage space. And if kept in the bag, any mag harnesses will not work and will drop to the ground, making it easy to lose. Perhaps include it as another option rather than an outright replacement?

I think the downsides are overstated. The bag contains space for it's own extinguisher. The magnetic harness issue might be fixed, and it's also minor - the bag gives you the space to run a strong backup weapon with which to defend your flamer when stunned.

I considered keeping the existing option, but it really hurt the clarity of the vendor. If more people express this sentiment, I'll add it back.

**Comment by Zangeiti** [comment]
> I think the downsides are overstated. The bag contains space for it's own extinguisher. The magnetic harness issue might be fixed, and it's also minor - the bag gives you the space to run a strong backup weapon with which to defend your flamer when stunned.
> 
> I considered keeping the existing option, but it really hurt the clarity of the vendor. If more people express this sentiment, I'll add it back.

I disagree with having to be forced to go through the tedium of unequipping your flamer, taking out an extinguisher, and re-wielding just to extinguish vs. hitting right-click once with the regular flamer. And why is it priced twice as much as a regular flamer? If you're running out of fuel, then why not just carry a welding tank around? 

P.S. The backpack flamer's tank can't be refilled via the vendable welding tank, so unless you can find a welding fuel cart on the map you're kinda screwed

**Comment by Yttriums** [comment]
> > I think the downsides are overstated. The bag contains space for it's own extinguisher. The magnetic harness issue might be fixed, and it's also minor - the bag gives you the space to run a strong backup weapon with which to defend your flamer when stunned.
> > I considered keeping the existing option, but it really hurt the clarity of the vendor. If more people express this sentiment, I'll add it back.
> 
> I disagree with having to be forced to go through the tedium of unequipping your flamer, taking out an extinguisher, and re-wielding just to extinguish vs. hitting right-click once with the regular flamer. For players like me with carpal tunnel it helps a lot to not go through a roundabout way to do something easily done with one button (even if done with hotkeys). And why is it priced more than twice as much as a regular flamer? If you're running out of fuel, then why not just carry a welding tank around?
> 
> P.S. The backpack flamer's tank can't be refilled via the vendable welding tank, so unless you can find a welding fuel cart on the map you're kinda screwed

There would still be roundstart normal flamers for you to use. Flamer bag can now be refilled by the vendable welding tank, that was changed a bit ago.

The price is accounting for the increased fuel capacity over the regular flamer option - you are holding a flamer,  hundreds of fuel, and other items in one slot. You can also reload your flamer instantly via bag. These are all big quality of life bonuses. The current SL vendor options are similarly price if you account for backup fuel tanks.

If there's a good faith accessibility concern here then I'm sympathetic to that, but I don't necessarily buy that one is significantly more micro intensive than the other unless you're constantly extinguishing

**Comment by Yttriums** [comment]
Remembered why I don't contribute, exhausting

**Comment by AusarAtkin** [comment]
> Remembered why I don't contribute, exhausting

You're replying to someone that is not even a contributor, just ignore those if you dont feel like it and talk to maints or Kuro instead.

**Pull request closed without merging**
