### PR TITLE
Hunter Stealth Stun removal

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request

Removes the Hunter Stealth stun and increases the Sneak Attack armor penetration.
## Why It's Good For The Game

Hunter is a bit too strong and cheesy with the sneak attack stun combined with the pounce, eventually stunlocking marines for easy kills. This change makes it easier to counteract without taking away too much of the hunter's skirmishing capability.

## Changelog
:cl: Naaanii
balance: removed stealth stun and increased armor pen from 20% to 40% on sneak attack.
/:cl:

### CODE REVIEW

**Comment by neohenry** [comment]
HUNTER MAINS BE MAD

**Comment by David-Stormwell** [comment]
Like I said before in Discord, instead of removing it I would suggest making taking damage remove the stealth.

**Comment by SilencedMP5A5** [comment]
i hate the stun too but what stormwell said is probably better

**Comment by SpaceLoveSs13** [comment]
I think buffing armor in this case is worse. Agree with david.

**Comment by SplinterGP** [comment]
i say just remove stun, it already does stagger(which halves damage) and slowdown. surr hunter PR touches it but its a big PR so this is good

**Comment by Naaanii** [comment]
Armor pen buff reverted.

**Review by SplinterGP — APPROVED** [review]

**Comment by SplinterGP** [comment]
> Like I said before in Discord, instead of removing it I would suggest making taking damage remove the stealth.

probably in surr hunter PR, but that will take some time so.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-3). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Al-1ce** [comment]
> Like I said before in Discord, instead of removing it I would suggest making taking damage remove the stealth.

Agreed. If you get sneak attacked, you probably were wandering alone/off to begin with.

**Review by Naaanii — COMMENTED** [review]
Oops

**Pull request merged**
