### PR TITLE
Double down on the spear buff

### PR DESCRIPTION
**Pull request by saprasam**
## About The Pull Request

Doubles down on the spear buff, giving it an extra 25 damage to throwing and wielded.

## Why It's Good For The Game

Spear ungas are funny, and this puts spears in the phenomenal range of doing 100 damage dual wielded. (yikes)
Doubling down on this is extremely important for two reasons
A: It's funny watching xenos complain in dchat.
B: I am extremely biased.

## Changelog
:cl:
balance: Spears now do even more damage. Too bad!
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
I'm gonna be real with you. That PR description is not gonna help you much.
Jokes aside, and taking this PR seriously? 100 damage on a melee weapon is far too much, especially given the spear has additional range. I'd advise against it.

**Comment by saprasam** [comment]
I can assure you that this is a VERY good idea. Surely you understand the comedic value of seeing a xenomorph complain over a melee weapon.

Xenomorphs already have stuns to disable melee combatants, which is significantly superior against a spear user as they do not have any countermeasures against stuns such as a clamp, or a wristwrap.

Spear users also have to dual wield or be thrown to deal good damage, which both have their own downsides.
Downside one: Dual wielding prevents you from equipping a gun with haste, or a grenade.
Downside two: Throwing completely bars you from reobtaining your spear unless you are die hard on it, which will most likely get you stunned, or take high damage.

One of the greatest downsides to a spear is the fact you cannot use a shield. A shield lets you block attacks and adds damage resistance. It's within reasonability that a man with a machete and shield could be significantly more powerful then a spear.

i'm standing on this grave

**Comment by InterroLouis** [comment]
Don't forget that xenos have functional melee armor.

**Comment by RenGusta** [comment]
Xenos melee armor ranges from like 15-90. 

So like. Losing at like 15 damage minimum on any target.

**Comment by saprasam** [comment]
> Xenos melee armor ranges from like 15-90.
> 
> So like. Losing at like 15 damage minimum on any target.

The absolute bare minimum armor is given to a young runner, with only 5 armor flat across the board, and even this armor is boosted up to 19 with warding. Even the lowest amount of warding to my knowledge will boost a runner's ability to survive a spear's damage up to 3 hits or more, and every other caste has far superior melee armor and health.
Seeing five spear ungas rush up to a queen to stab her to death is a funny thought, though.

**Comment by InterroLouis** [comment]
Just for some transparency, the throwforce of 100 results in 60 damage from throwing it at a xeno because of how the code works.

**Comment by Losenis** [comment]
> Jokes aside, and taking this PR seriously? 100 damage on a melee weapon is far too much, especially given the spear has additional range. I'd advise against it.

Accidentally click friendly when trying to hit the purple sac under him, arm flies off. Whoops.

**Comment by saprasam** [comment]
> Just for some transparency, the throwforce of 100 results in 60 damage from throwing it at a xeno because of how the code works.

that's simply just how it is sometimes

**Comment by Georgeur** [comment]
this pr is unbalanced 
you need to buff the machete if you're willing to merge this, every melee item is balanced around it

but importantly... fucking why
we havent had the spear buff pr out long enough for this to be out
I've killed 2 xenos today, maybe 3 if you wanna be generous, all with the spear
doesnt need a buff YET imo
this pr is a shitpost

**Comment by TiviPlus** [comment]
Powercreep

**Pull request closed without merging**
