### PR TITLE
Howie Shell cost increased

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Increases the shell price for Howitzer shells.

## Why It's Good For The Game
The Howie is great at holding a siege and with a steady income, makes sieges almost endless.
The value it provides far outweighs the price it can be obtained for.
Shells can still be spammed granted marines are still selling corpses or have a miner.
This just slightly slows down it's capability if marines are struggling for points.

## Changelog
:cl:
balance: Increased Howie HE and Incen shell prices to 4
balance: Increased Howie Tfoot and WP shell prices to 6
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
> I feel like HE & Inc being 5 is too much. I can see tangle getting that price.

5 Isn't that much at all considering I wanted to make it 7 and Tfoot 10.
Mortar can do a similar job and be a budget Howitzer for a fraction of the cost and this won't gut or kill the Howitzer in any way.

**Comment by Pariah919** [comment]
4 and 6 would probably be what I'd do, but I made howi so.

**Comment by Naaanii** [comment]
> 4 and 6 would probably be what I'd do, but I made howi so.

I'd be okay with this.

**Comment by FosterGrime-Heymynameslouie** [comment]
4 and 6 is totally cool
after using howie for what is a life time, this nerf was a long time coming

cheap howie barrage I am going to miss you

**Comment by Derrick2Electricboogaloo** [comment]
Negative, ghost rider the pattern is full.

**Comment by MereWalker** [comment]
Personally I'm against this but then again there has been power creep with marines. So I'm fine with this. Will have to be diligent about miners now.

**Pull request merged**
