### PR TITLE
UV small balance changes

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
slight nerf to light uv and droid move speed increased integrity of medium uv from 200 to 300 and heavy uv from 250 to 500, nerf to droid ammo count from 300 to 100, adds an internal ammo storage for uvs and droids that can hold 3 magazines(you still need to manually reload it) adds different sprites for light uv and heavy uv mag and adds a mag for the droid turret

## Why It's Good For The Game
slight nerf to light uv and droid speed so its a bit more manageable for xenos, increased integrity of medium and heavy uv to make up for their pretty slow speed, nerfed droid ammo count since it was 300 rounds of overcharge lasers, adds internal ammo storage so its more easier to store ammo and ask people nearby to reload if your far away from your uv and adds a mag for droids since they didn't have one before

## Changelog
:cl:
add: internal uv ammo storage, droid mag
balance: slight nerf to light uv and droid move speed increased integrity of medium uv from 200 to 300 and heavy uv from 250 to 500, nerf to droid ammo count from 300 to 100
imageadd: light turret heavy turret droid turret magazine sprites
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
500hp is a pretty chunky monkey, that would be pretty hard to murder since it simply has the health to face tank and just unload into you.

**Comment by tyeagg** [comment]
> 500hp is a pretty chunky monkey, that would be pretty hard to murder since it simply has the health to face tank and just unload into you.

70 points

**Comment by lbnesquik** [comment]
You are changing the names a bunch, but the ammo reference is still around in the UV code. Might want to check that out.

**Comment by Naaanii** [comment]
Doubling HP is a bit much for the heavy.

I'd personally keep the speed but let weed and cc slowdown effects work on droids.

**Pull request closed without merging**
