### PR TITLE
Halves Flare Min/Max Fuel

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
Flare fuel decreased to 400:460 (~13 to 15 minutes) from 800:1000 (~27 to 33 minutes)

## Why It's Good For The Game

Light is essential for marines in order to even get off a shot or appropriately react to the approach of a xeno. Flares burning out sooner just means that Marines won't have as much control over an area for a long period of time. Xenos also won't be _as_ pressed to melt every flare they see and can afford to be more selective in that process.

## Changelog
:cl:
balance: Flares now run out of fuel within 13 to 15 minutes.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
I think buffing the efficiency of acid on flares would be a better solution but seems alright as marines also have an infinite supply of flashlights as well.

**Comment by KrabSpider** [comment]
> Can you buff CAS and mortar flair in your PR?
> also new one on tadpole. They all is kinda shit.
> Its changes look okay for me, but marines don't have good alternatives for now

Out of scope tbh

**Comment by goose4429** [comment]
Sounds fine. 15 minutes per flare is still more than enough.

**Review by Pariah919 — COMMENTED** [review]
I'm not really sure on this considering how flares generally are a tradeoff to store usually, but could be fine.

**Comment by Al-1ce** [comment]
> Can you buff CAS and mortar flair in your PR?


CAS in-and-of-itself needs a major rework. Relying on marines to lase fucking sucks and isn't fun for either party. This is somewhat unrelated to the PR but I still find it mind-numbing that there isn't a rocket pod or attachment which would allow CAS to flare for itself.

**Pull request closed without merging**
