### PR TITLE
Hyposprays resprite

### PR DESCRIPTION
**Pull request by Blundir**
## About The Pull Request

Edited sprites, port of Aurora's [normal](https://github.com/Aurorastation/Aurora.3/pull/8216) and [combat](https://github.com/Aurorastation/Aurora.3/pull/8919) hypospray sprites. Edits were made by me.

Adds new draw/inject bar.
dreammaker_zvGOLN4xBX

Adds a unique sprite to a big hypospray (white one, why is it big? nanotechnologies, son), previously big hypospray looked identically to a regular hyposrpay.
dreamseeker_GjsBj2UerL

Added inhands sprites with the new hypo sprites.
dreamseeker_DOQVyC8LLD

Also done a little syringe sprite retouch, and a bit of code and sprite cleaning related to it.
dreamseeker_hhj3PuCGa7

## Why It's Good For The Game

CM sprites was extremely outdated and bad in general, with draw/inject being straightforward terrible.

Here is a comparions of the same thing:

Before:
dreamseeker_Yv6UgWrs1F

After:
dreamseeker_QMUsmvZj2I

This is how hypospray belt insides now look like (i'm gonna harvest souls of CM health analyzer and bottle sprites a bit later).
dreamseeker_sQngALxp2E

## Changelog

:cl:
imageadd: new hypospray sprites
code: removed some completely redundant syringe code and sprites
code: changed hypospray code to fill the needs of the new sprites
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]

**Comment by FosterGrime-Heymynameslouie** [comment]
speddemheg instantly

**Comment by FIXTHERADBOXPLEASE** [comment]
They're beautiful... The PR that singlehandedly made an entire med-system worth using.

**Comment by 567Turtle** [comment]
shits heat speedmerge

**Comment by Al-1ce** [comment]
sprites are sexy. i approve

**Comment by Lumipharon** [comment]
The smaller 'big' hypo sprite is kinda misleading.

**Pull request merged**
