### PR TITLE
Lasgun pouch

### PR DESCRIPTION
**Pull request by David-Stormwell**
## About The Pull Request

Gives Lasguns a universal pouch for all your energy needs! Pouches are equal to 4 cells and may be recharged at the Lasgun cell charger box.
Nutshell: Lasgun pouch which may be linked to a gun or used to charge respective cells.

## Why It's Good For The Game
A needed addition for the lasgun fan club, as they're lacking in that department and currently being overlooked heavily by other guns, now I don't expect the guns to be used too much more but it should be the start of something better.

image

## Changelog

:cl:
add: Added a Lasgun energy pouch which may charge or act as a cell for your TE guns!
/:cl:

### CODE REVIEW

**Comment by ClosetedSkeletonGH** [comment]
I cannot wait for a PVT to fire 800 TE-MG Effeciency shots down a hallway, thank you

**Comment by novaepee** [comment]
image

Is there a state for zero?

Also, can't wait to see charger box back in action.

**Comment by David-Stormwell** [comment]
> 

Doesn't use one as default is 0.

**Comment by KerbalCitizen** [comment]
> I cannot wait for a PVT to fire 800 TE-MG Effeciency shots down a hallway, thank you

Efficiency mode is bad and they could just bring an ammo box full of cells with them anyways.

**Comment by SapphicOverload** [comment]
Does this work with the power fist too?

**Comment by isotope436** [comment]
> Does this work with the power fist too?

the right question because is so then we are so fucking back

**Comment by ClosetedSkeletonGH** [comment]
> > I cannot wait for a PVT to fire 800 TE-MG Effeciency shots down a hallway, thank you
> 
> Efficiency mode is bad and they could just bring an ammo box full of cells with them anyways.

but imagine this:

You want to walk down a hallway on prison station to get towards the silo. You turn the corner to hear a strange noise, a non-stop ping of a tiny laser being fired at 6.5 lasers a second

you finally enter the hallway, a constant stream of a tiny blue laser races down the hallway infront of you. At one end you see PVT Kah Kenbuls, at the other end you see them firing into a metal wall that is 2 tiles out of their sight

you request of them "PVT Kah Kenbuls, may you please stop firing in order for me to pass, I am making a journey towards the Silo for the corps". PVT Kah Kenbuls does not respond, they continue to fire

you beg "PVT Kah Kenbuls, I must request you stop firing at once, your lasers are only hitting a metal wall, please grant me passage!"

You examine PVT Kah Kenbuls character, their description is entirely Cyrillic, you come to the realization that they do not speak a word of English and that you must wait for all 800 efficiency rounds to be exhausted. 

Dismayed at the futility of your journey, you sit down on a prison station bed. A young red Rounathan peaks their head out of a vent and quickly removes your throat. 

PVT Kah Kenbuls continues to fire, ignorant to your fate.

**Comment by Losenis** [comment]
Does this self-recharge? I honest to god want a self-recharging pouch given ballistics already have ammo packets on top of having the benefit of aim mode, it'd give lasguns a great gimmick of a long-term logistic option. Wouldn't be gamebreaking given engis can already vend 50 rechargers for ungas anyway.

**Comment by isotope436** [comment]
i think it should be dependant on what gun its linked to just to keep better balance plus it means you can tweak the ammo per gun independantly

**Review by TiviPlus — APPROVED** [review]

**Comment by zzurge** [comment]
Energy rifle overcharge ENJOYERS rise UP

**Comment by David-Stormwell** [comment]
> Does this self-recharge? I honest to god want a self-recharging pouch given ballistics already have ammo packets on top of having the benefit of aim mode, it'd give lasguns a great gimmick of a long-term logistic option. Wouldn't be gamebreaking given engis can already vend 50 rechargers for ungas anyway.

Discussed this feature with my co-conspirator and decided against it, as engineers need to have a reason to have a crank charger anyways.

**Comment by Losenis** [comment]
>as engineers need to have a reason to have a crank charger anyways.

Crank charger as a lasgun recharger is already a secondary purpose at best though. The purpose of a charger is saving slot space for basically every APC cell since otherwise you need 3 cells for the 3 disk gen APCs not counting additional APCs like medbay and the sort. If you grab a charger, you can put your starter cell into the charger and then put that charger in the webbing for pretty much the same space the cell on its own would take up. Every APC comes with an empty cell so you can just slap in the full cell, grab the empty one, charge it, and be ready for the next APC.

I honest to god never came across an engi that also ran charger for eguns when I played. It's that rare when you can just refill your mags with packets or just pack an ammo box with you, or just get req to send you more ammo given that as engi you'd be running with radiopack or antenna module anyway.

**Review by Lumipharon — CHANGES_REQUESTED** [review]
If this is 4 cells worth, isn't this literally just a better mag pouch, before even taking into account being able to plug it in?

Also the linked gun sprites are just the empty sprites with the light on lol.

If you haven't changed anything, the power level overlays will never update either.

**Comment by FosterGrime-Heymynameslouie** [comment]
honestly would be a great option if a req buyable version of this exists where it recharges on its own
maybe abysmal ammo count, but having the ability to recharge seems pretty cool I think, or hell, maybe crank it on your own

10/10 pr

**Comment by Losenis** [comment]
>If this is 4 cells worth, isn't this literally just a better mag pouch

Given that lasgun cells have never received a packet equivalent, being able to carry one single more cell and only cell with no options of throwing any other mag in there doesn't seem too wild. Same reasoning applies to pistol mag pouches carrying far more than normal mag pouches.

**Comment by isotope436** [comment]
are these able to be stored into ammo box's? and if not can they be made to be?

**Comment by David-Stormwell** [comment]
> If this is 4 cells worth, isn't this literally just a better mag pouch, before even taking into account being able to plug it in?
> 
> Also the linked gun sprites are just the empty sprites with the light on lol.
> 
> If you haven't changed anything, the power level overlays will never update either.

Correct in the assessment that it's 4 cells worth, as currently, lasguns do not have "energy packets" so this balances things out at least a little more in terms of such.

Yes.

Unsure of what you mean? Which power level overlays? The pouch or the gun?
If you're referring to the gun I didn't think much of a need to, additionally the gun isn't working off a "cell", instead working off the pouch so no need to do so.
Also as you said the parent needed self-charge to update the sprite charge, and thusly I'm fine in the end if it doesn't update.

**Comment by Xsdew** [comment]
Some of the fire modes of Laser weaponry shouldn't get Extended Magazines (The pouch when linked with a weapon). I am referring mainly to Shotgun Laser Carbine, and Over Charged Rifle. Four cells of power gets you 80 shots of OC Lasguns. The main disadvantage of OC mode being ammo capacity and rate of fire.

**Comment by David-Stormwell** [comment]
Pending due to Lumi's request on discord for a power cable for each one.

**Comment by KillerOrcaCora** [comment]
Power cables are done, Now lets stick one in lumis-

**Comment by Losenis** [comment]
>The main disadvantage of OC mode being ammo capacity and rate of fire.

Not precisely. OC gets less base dps (double damage for over double the firerate) for additional penetration while also losing damage per mag efficiency due to, despite having twice the damage per shot, has less than half the shots per magazine.  The shot/magazine economy drawback would also carry over to the lasgun pouch in equal measure. Ammo capacity was never really relevant given you can tacreload in the time it took to shoot it once anyway.

**Comment by isotope436** [comment]
> Some of the fire modes of Laser weaponry shouldn't get Extended Magazines (The pouch when linked with a weapon). I am referring mainly to Shotgun Laser Carbine, and Over Charged Rifle. Four cells of power gets you 80 shots of OC Lasguns. The main disadvantage of OC mode being ammo capacity and rate of fire.

this isnt really a factor since the only thing the pouch actually does in the long run is remove the need to tac reload a new cell into your gun so your basically removing a total overall 2-3 seconds in reload times but even then if this works like the flamers tank link getting stunned will disconnect it so it balances itself out

**Pull request closed without merging**
