### PR TITLE
Tx8 Impact Ammo Re-Rebalance

### PR DESCRIPTION
**Pull request by EvilMelonTheSecond**
## About The Pull Request
Adds back stagger to TX8 impact ammo, increases damage by 15 and removes penetration trait

## Why It's Good For The Game
TX8 rebalance PR fully butchered the niche of the higher cost impact ammo by removing both its higher damage and the crowd control capabilities of it. The penetration added in exchange is frankly obsolete on a gun with full auto with lower end DPS.

This PR adds back the stagger and increases damage so it isn't out DPS'd by the cheaper ammo giving it the crowd control niche back partially. This probably isn't enough to make it viable but I'm no numbers expert, feel free to recommend stats.

## Changelog
:cl:
balance: TX8 impact ammo stagger readded, damage increased by 15, penetration removed.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Stagger is a bad mechanic and shouldn't be viable or readded. Just increase the damage but the weapon still kind of feels fine. Just keep the increased damage if needed.

**Comment by Luxyboo** [comment]
stagger is a great mechanic and should be viable for every weapon that lost it

**Comment by lKiseki** [comment]
This is a very silly PR. Not only are you readding back what was arguably the most broken part prior to its nerf in #9388, you're also increasing its damage by a whopping 15. This is just plain powercreep.

**Comment by KrabSpider** [comment]
This is literally just the regular ammo with stagger. Stop.

**Comment by EvilMelonTheSecond** [comment]
TX8 is a req gun with DMR levels of firerate and mag capacity, the damage being so low makes it a terrible choice and the stripped stagger made it fully useless. You lads are freaking out as if I'm buffing T12 ammo and not a 5 req points per 20 ammo magazine gun.

**Comment by Araulius** [comment]
> TX8 is a req gun with DMR levels of firerate and mag capacity, the damage being so low makes it a terrible choice and the stripped stagger made it fully useless. You lads are freaking out as if I'm buffing T12 ammo and not a 5 req points per 20 ammo magazine

it's 7 points per magazine, actually.

**Comment by lKiseki** [comment]
> TX8 is a req gun with DMR levels of firerate and mag capacity, the damage being so low makes it a terrible choice and the stripped stagger made it fully useless. You lads are freaking out as if I'm buffing T12 ammo and not a 5 req points per 20 ammo magazine gun.

For good reason, my dude. The TX-8 being a requisitions gun does _not_ justify it being as broken as you intend it to be. The damage isn't even that low, it has a lot of armor penetration and its stats are good enough. To compare stats to the T-12, which is practically the baseline for all guns;
image

It easily deletes armor and ignores a good bunch of it already. Stagger denies the usage of abilities and having it be applied on every bullet is unhealthy for balance.
If you want to buff it, look into other alternatives instead of basically reverting changes. There's a reason why those changes were made.

**Comment by EvilMelonTheSecond** [comment]
It has been made clear this is not the correct rebalance needed. I may be defeated now but I will return stronger and with a much dumber PR.

**Pull request closed without merging**
