### PR TITLE
[CI] Install PCREGREP for Linters 

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Did you know that the linters have been failing silently ever since the CBT port?
Now they don't!

## Changelog
:cl:
server: Fixes the CI Linters
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
As proof that this works linters now fail loudly.

**Comment by ZephyrTFA** [comment]
@SplinterGP asking for a review

**Comment by SplinterGP** [comment]
checking

**Comment by SplinterGP** [comment]
can you fix that error on the linter btw so it doenst keep failing after

**Review by SplinterGP — APPROVED** [review]

**Comment by ZephyrTFA** [comment]
> 
> 
> can you fix that error on the linter btw so it doenst keep failing after

Done.

**Review by SplinterGP — APPROVED** [review]

**Pull request merged**
