### PR TITLE
Buffs the everlasting shit out of Squad Leader's M41AE2 heavy pulse rifle

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Added incendiary and armor piercing ammo variants to the M41AE2 heavy pulse rifle. They can only be purchased from the Squad Leader Vendor for 5 and 10 points, respectively.
Reduced the cost of the M41AE2 heavy pulse rifle from 12 to 10.
Reduced the cost of the M41AE2 heavy pulse rifle ammo from 4 to 3.
Increased the firerate of the M41AE2 heavy pulse rifle from 0.4 seconds to 0.3 seconds.
The following attachments now work with the M41AE2 pulse rifle:
- Flamer
- Grenade Launcher
- Masterkey Shotgun
- Bayonet
- Burstfire Assembly
- Gyroscopic Stabilizer
- B A R R E L C H A R G E R
- Laser Sight
- Mini Scope
- Suppressor

## Why It's Good For The Game

The heavy pulse rifle is pretty shit. I barely see Squad Leaders use it, and honestly I barely see people pick squad leader when they rather pick specialist. Hopefully this buff to Squad Leaders will make people play them more than specialist. The buffs make sense because it isn't just a damage increase, but rather a firerate increase to an LMG that should fire pretty fast, but not as fast as a minigun. The LMG should be versatile as well, like the regular rifle that marines use. Overall, it's now a more flexible weapon.

## Changelog
:cl: BurgerBB
add: Added Incendiary and AP mags for the M41AE2 heavy pulse rifle.
balance: Reduced the cost of the M41AE2 heavy pulse rifle and it's ammo in the Alpha Squad Leader vendor. Increased the firerate of the M41AE2 heavy pulse rifle from 0.3 to 0.2. More attachments now work with the M41AE2 heavy pulse rifle.
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
The hpr will be replaced soon with the lmg that will be a pfc weapon,the current hpr was itself supposed to be a pfc weapon but it didnt go trough,I think these changes are pretty unecessary

**Comment by Pariah919** [comment]
I'd make the orders better likr teaikas PR personally. That and the HPR is probably gonna be reworked into pfc gun. But lettin SL buy ap ammo for it in the future would be fine
Not sure about incin rounds. Could be eh or op depending.

**Comment by BurgerLUA** [comment]
Where is the PR to replace the Heavy Pulse Rifle?

**Comment by Rohesie** [comment]
This gun will be replaced and stored soon. No use in giving it big balance changes.
That is, let's try not to overbuff stuff.

**Comment by BurgerLUA** [comment]
The only overbuff I see here is the firerate change but it seems consistent with most LMGs that exist. You can lock the AP and incin rounds after the change to something that you have to order from req.

**Comment by jroinc** [comment]
Incin rounds, even req-orderable will be MASSIVELY OP.

Add them to the vendor for 10 points, and the SL will vend 4 and toss 3 out.

Add them to req, and they'll get bought en masse every round.

If they were available in any form, I'd switch my primary to HPR no matter what class I'm playing as in the off chance I get one.

**Comment by BurgerLUA** [comment]
removing incind rounds

**Comment by BurgerLUA** [comment]
Closing this PR until the game is in a better state.

**Pull request closed without merging**
