### PR TITLE
Xeno selling rework

### PR DESCRIPTION
**Pull request by tanker4390**
## About The Pull Request
Xenomorphs are ~no longer~ gibbed by devastating explosions, and are instead instantly ~put into crit~ gibbed if their bomb armor is low enough. Instead of having an ever-present 5% chance to be gibbed, the chance to gib on death is now affected by how much damage they took while in crit. If a xenomorph sustains more than ~20~ `70` damage while in crit (bleeding-out damage not counted, of course), they will have a ~x * 0.75 - 12~ `{total damage taken} - 65`% chance to be gibbed. This resets when they leave crit. 

Xenos now have -140 crit health (die at -140) and bleed out 7 per life tick instead of 5.

(also they have a 1% chance to drop a slab of meat on death hehe)

All xenos now sell for ~15% less req points.
## Why It's Good For The Game
Kings shall not unceremoniously blow up after marines make a effort to carefully recover the corpse, ~nor~ the shrike shall blow up instantly after hitting their head on a flying artillery shell. Now rewarded for making an effort to preserve the corpse.
## Changelog
:cl:
balance: Xenos have a chance to be gibbed on death based on how much damage they took while in crit. Try to keep them in one piece.
balance: Xenos sell for ~15% less req points.
qol: Xenos are no longer randomly gibbed on death.
/:cl:

### CODE REVIEW

**Comment by Araulius** [comment]
should make xeno gibs drop xeno meat slabs smh

**Comment by SimplySmiley123** [comment]
> I don't know how the math works out here for gib chance, but it's pretty common to shoot the xeno a bit into crit, either because people are slow to react or they don't want to risk heal ticks kicking in and putting the xeno back on their feet instantly. I think in 95% of cases people will still unload into the crit xeno until it's dead, especially new players.

There's also a case to be made that the dead and crit xeno sprites do look very similiar and ain't something you'll notice in the heat of a moment.

**Comment by Lauwma** [comment]
I think any explosions or very big burst damage that kills a xeno should gib it and any other reason shouldn't

**Comment by yyzsong** [comment]
> `x * 0.75 - 12`

what is the X in this equation? Crit damage > 20?

**Comment by dopamiin0** [comment]
the first part feels really silly and weird? its already rather easy to overcome the devastate gib with warding pheroes as even the squishiest of castes. if you're a squishy and you get hit with a devastating explosion AND you're not near the main xeno forces so you have no warding, you SHOULD get blown to little bits for being a silly goose

**Comment by lbnesquik** [comment]
Not sure how this would actually play out, but securing bodies isn't always easy already.

**Comment by Lumipharon** [comment]
This is some big smelly cope to guarantee more req points for marines.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Dying as a xeno is already extremely punishing, not only you lose a important member of the hive (depending on tier it varies), you also make marines stronger in the process, xeno gib is kinda smelly the way its rng but with req being full of cringe stuff as it is rn, if body selling becomes more consistent, then the points you get from selling said bodies should be lowered to make up for it

**Pull request closed without merging**
