### PR TITLE
Victory Music Combat Patrol

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
victory music for combat patrol

## Why It's Good For The Game
combat patrol has no victory music this makes it have that

## Changelog
:cl:
soundadd: victory music for combat patrol
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Now all we need is a snazzy ending animation https://www.youtube.com/watch?v=feHAHB4gLEM

**Comment by FosterGrime-Heymynameslouie** [comment]
command and conquer generals prep music when.......

**Comment by TiviPlus** [comment]
image

**Comment by tyeagg** [comment]
> image

Its a most likely no from the music owner since y know github open source files so im looking for different music now

**Pull request closed without merging**
