### PR TITLE
Baldur Helmet Module

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
baldur module but for helmet 

## Why It's Good For The Game
sacrifice head module for light could be interesting

## Changelog
:cl:
add: baldur helmet module
imageadd: baldur helmet module
/:cl:

https://user-images.githubusercontent.com/98577688/182858989-fe616ad5-5d89-4bc4-9e87-aa4aad477630.mp4

### CODE REVIEW

**Comment by Pariah919** [comment]
wait this is my troll module

**Comment by Kuro020** [comment]
hilarious

**Comment by Kuro020** [comment]
now die

**Comment by Starfirejordan** [comment]
Kuro i will PAY YOU to let this get added in

**Comment by Kuro020** [comment]
> Kuro i will PAY YOU to let this get added in

No

**Comment by Al-1ce** [comment]
Tyr 1 helmet mod exists for a reason?

**Comment by FlakBait00** [comment]
are these cat ears!?

**Pull request closed without merging**
