### PR TITLE
TAT Nerf #???: Electric Boogaloo

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
Nerfs TAT, gives more reasons to use rounds other than APCR. Makes it into a more static weapon that requires teamwork (already somewhat enforced due to loader) rather than being able to 360 noscope any flanker.
## Why It's Good For The Game
It has been this song and dance since TAT was released, but due its merit of being an offscreen HVAP round with the sunder it has I seek to nerf it. I'll put justifications in bullet points.
- APCR is the defacto best round; APHE might do more damage to lower bomb armor targets but it can FF while APCR cannot (you should always be using aimmode on TAT). In addition, given that TAT should be used as a "support weapon", giving an immediate 65 sunder offscreen allows the ungas next to the Xeno marked for death to kill it much easier, even without considering the 200 damage applied
- TAT isn't exactly vulnerable to flankers since you can quickly turn the TAT to immediately delete the xeno next to you, even while in aimmode
- Having to have someone supporting against flankers is already encouraging given it takes forever to reload without a loader

These changes hope to turn TAT into a dedicated area denial with more counterplay given you can flank it easier, making marines have to think where they should put it. The anchor time is used to, again, keep the aim and direction more static allows xenos to play around it while it is still being a tangible -200hp threat.
## Changelog
:cl:
balance: Decreased sunder on TAT APCR and increaed pen, increased sunder slightly on other rounds
balance: TAT has an anchor channel time of 1 second, and cannot be rotated while anchored, or fired while unanchored.
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
Please don't. It doesn't need more nerfs.

> These changes hope to turn TAT into a dedicated area denial

So making it unable to turn, making it take 3 seconds to anchor, making it unable to fire while anchored, and nerfing the ammo, is supposed to improve the ability to area denial? No turn means it's worthless in pushing and defending fob, because you will have to spend 6 seconds to turn it, and another 5 to aim and scope, meaning you are in fact worse at area denial then before.

All these changes make it worse at its job. Why the nerf on the ammo to 15 sunder? A dmr, mosin or bolt action can outsunder the tat with these changes, which is a single shot gun with a 3 second reload time (ignoring the extra time for self loading). Why is >30 sunder in 5 seconds less scary than 15 sunder every 8? Adding 10 more sunder to other ammo doesn't make them worth it either.

TAT has a ton of counters already. It's outranged by boilers. It can be gassed also by defilers. It isn't dense when manned, which makes the user vulnerable to fishing and flanking, or being run over. It has a long reload time. Plus, explosions don't knock around large xenos anymore, further reason not to use the other ammo even with the joke sunder increase.

**Comment by Barnet2** [comment]
Numbers are up to change, but the justifications are there regardless. I already explained why APCR shouldn't have 65 sunder (mini HVAP lol) and I was asked to give a little sunder outside so I did.

Even without turning, the cone in which TAT can shoot is actually VERY large and it essentially just cannot shoot to things directly left, right or anywhere behind it. You have a loader, make them do a job of protecting you. Hell, this should encourage sandbag usage to help protect against flanks.

TAT is fundamentally broken being completely offscreen mark-for-death. AMR was nerfed for the same reason, having its slow being taken away. The funny thing is, AMR is not free and TAT is, with more killing potential and "group clearing". If I made it unclear, yes, this is a nerf, but it restricts TAT to pretty clearly denying an area instead of 360 noscoping the beano next to you.

**Review by ivanmixo — APPROVED** [review]

**Comment by Pariah919** [comment]
this honestly entirely kills TAT beyond just using it to defend flat corners which is more an HMG thing

**Comment by Naaanii** [comment]
Delayed anchor mechanic is kind of cringe, kind of like how Boiler was made unrobust and unfun.

Should probably either put the delayed anchor or remove the rotate instead of a double whammy nerf.

Another idea could be to force the TAT gunner to zoom out if they want to rotate but probably out of scope for this PR

**Comment by Lumipharon** [comment]
This makes it extremely unfun and difficult to use, for a static gun weaker than a sadar.

Not really sure the point of it will be at that point.

**Comment by Pariah919** [comment]
>This makes it extremely unfun and difficult to use, for a static gun weaker than a sadar.
>

As much as I hate to Ofnir-max, the reality of the PR is to make the reality is to the reality of handling TAT so unwieldly that it is essentially soft-removed, 3 seconds is an incredibly long time to setup in any scenario and alongside the aim and then having to aim and scope, etc makes it an incredibly unwieldy gun that only will only serve to be put into FOB and never be used in any bearable scenario because you're literally better off running an RR/HSG/HMG in every single situation due to them being more mobile. (Mobility is by far the most important thing in this game)

In my take the issues TAT has is bloated sunder numbers on APCR but that's mostly because I didn't have any other real ability to inflict armor debuffs in the way I did, if I did make it today I'd probably make APCR deal shattering and maybe rebalance the assorted utility rounds as I never see anyone run them.

Also the APCR nerf is understandable but this version of the nerf will make it straight worse than APHE due to having no explosive filler, just make it inflict 20 sunder and deal shattering instead of the current effect of 65 sunder.

**Comment by Pariah919** [comment]
> Numbers are up to change, but the justifications are there regardless. I already explained why APCR shouldn't have 65 sunder (mini HVAP lol) and I was asked to give a little sunder outside so I did.
> 

I semi-agree with this, but APCR should still deal noticeable sunder, as it is reducing it to *15* makes it the worst at it, which is kind of silly considering the role I intended for it was to break xeno armor for a noticeable amount of time. Reduce it to 20 flat sunder and give it 15 seconds of shattering which would make it more fair for both sides while not removing the original purpose.

> Even without turning, the cone in which TAT can shoot is actually VERY large and it essentially just cannot shoot to things directly left, right or anywhere behind it. You have a loader, make them do a job of protecting you. Hell, this should encourage sandbag usage to help protect against flanks.
> 

I already tried making things unable to turn, it makes it effectively useless due to the way TGMC maps flow alongside the set-up time, leading to people not using it because the feeling of their game impact is literally next to none due to the lack of ability to turn alongside the deploy time makes them awful to run, and turning anyways makes you have to re-scope which has its own delay unless you're moving your scope to engage something next to you which will probably hurt you unless you're running APCR or beehive.

> TAT is fundamentally broken being completely offscreen mark-for-death. AMR was nerfed for the same reason, having its slow being taken away. The funny thing is, AMR is not free and TAT is, with more killing potential and "group clearing". If I made it unclear, yes, this is a nerf, but it restricts TAT to pretty clearly denying an area instead of 360 noscoping the beano next to you.

TAT requires more set up, more time to use, has less actual range than the AMR which was nerfed in slowdown because it made getting shot by literally anything unbearable alongside the NVGs, you can't compare both outside of them having scopes and having high on hit damage because their purposes in their contexts are vastly different. You're trying to apply apples to oranges, also if you walk up to an AMR user they're probably just going to kill you compared to TAT which has to deal with the fact it can only fire one round.

TAT was already nerfed (really a fix) by having to use a loader to reload it while scoped in, if you have no loader your set up time is horrendous which is good, good luck convincing people to be a loader after this when you soft-remove it from the game (and yes this is an accusation) where they'll have to sit with you as you slowly set up every single time you want to move to fire which is will around 15~ seconds to just anchor the gun then aim it which you'll have to do every time.

**Comment by Coastfront** [comment]
Listen dearly, to the sounds of the wind at your ears.
Strain yourself, as eyes shutter away into darkness, and as silence pervades over your final sense, it will be heard:
Nothing.
No one
An empty space of dialogue, where words that could be are scarcely found.
Where every single wish for another tat nerf can be so gently heard.

Who wants this.
Who asked for this.
Who unironically complains about the tat being overpowered in 2023
Why would literally fucking anyone even consider this?

This would, just make the tat, the GIANT EMPLACED GUN, objectively weaker than every single anti armor marine carried gun that exists. and it instead requires 2 people to use, is comically vulnerable to literally every LOS blocker that exists, is out ranged by the xenos area denial unit, and fucking explodes if its found out in the open because it can fire exactly once

**Comment by maikilangiolo** [comment]
> force the TAT gunner to zoom out if they want to rotate

Brother, this is already how it works. The noscope turn is cope because if you turn, you lag out due to scope lag, and lose the scope too.

**Comment by iforgotmeword** [comment]
let me ask this how many times you have seen TAT used?
and there is a reason for that

**Comment by DorfGuy1** [comment]
literally nobody is asking for this. Also as mentioned previously, the scope zoom turn thing is really just a cope, because you will lag out.

**Comment by DorfGuy1** [comment]
Also, the loader thing? Nobody ever gets a loader. Never seen it once. They just deal with the shitty reload.

**Comment by 1kajowsmol** [comment]
i disagree with this being added thanks

**Comment by Coastfront** [comment]
How magical it is that not a single word of kindness falls upon a mural, no color upon it found with love by its onlooking eyes yet still is it sold for millions.

They did literally nothing to address nor place a counter point to literally any fucking concern people had and it got merged.

**Pull request merged**
