### PR TITLE
Fix minigun aimbot

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7332

YOUR MOVE ZACK

## Changelog
:cl:
fix: Minigun no longer has aimbot
/:cl:

### CODE REVIEW

**Comment by vilereaver41** [comment]
Wow who was aimboting with it? What a grub

**Comment by Ragecrabbo** [comment]
futurevision

**Comment by TiviPlus** [comment]
Can you explain this fix

**Comment by BraveMole** [comment]
> Can you explain this fix

So i added a windup check specially for SADAR, so you don't have to keep pressing the mouse button up to fire.

This works fine for the sadar, but the minigun uses the same windup system. Hence, the mouse button up signal was not doing anything, and the minigun was acting like you kept pressing your button.

So you kept firing, and nothing was reseting or changing your target. Hence, aimbot

**Review by SplinterGP — APPROVED** [review]

**Pull request merged**
