### PR TITLE
Derringer Buff 2: Revengeance.

### PR DESCRIPTION
**Pull request by Al-1ce**
## About The Pull Request

This makes the derringer bullet in-line with the T-44 revolver, giving it simple knockback.

## Why It's Good For The Game

The derringer has remained in vendor-hell for ages now. It's only ever used by people who mistakenly think that it will actually do anything. This aims to make it _somewhat_ useful in an emergency scenario. 

Currently, the derringer;

* Loads slower than a Martini.
* Has harsh recoil for a pocket-pistol. 
* Has only two shots. 
* Mediocre damage. (It takes six shots to kill an ancient rouny)
* Limited supply. Only ten of these exist in the vendor.

This is basically just a tiny revolver that can fit in your pocket. I feel like this the drawbacks of this gun more than make up for giving it this buff.

## Changelog

:cl:
balance: Derringer now applies knockback.
/:cl:

### CODE REVIEW

**Comment by docRoboRobert** [comment]
Still will be overly weak but ok i guess

**Review by KrabSpider — COMMENTED** [review]
`knockback = 1` is all you need as an fyi.

**Comment by Lumipharon** [comment]
I would say this is a nerf since no more staggerslow, but eh.

**Comment by FIXTHERADBOXPLEASE** [comment]
Knockback (tends to) to scare Xenos a lot without actually threatening them that much.

**Comment by Al-1ce** [comment]
> Still will be overly weak but ok i guess

I am well aware of this. However, in #12271, Lumi compared these to the pocket pistols... despite them;

*Having a fraction of the DPS
*Being almost impossible to reload mid-combat
*Doing fuck-all for damage
*And having only two bullets

Do tell if you can think of something that wasn't addressed in the last PR and I'll see what I can do to change it.

> I would say this is a nerf since no more staggerslow, but eh.

Staggerslow doesn't matter **at all** because this gun is inaccurate and not something you'd ever use to chase a xeno with. 

It's also completely outclassed by literally any other gun in the game. Knockback is scary for most xenos and I want the derringer to be _somewhat_ usable. P

I'd have tried to do something else but you shot down my last PR and didn't seem to understand that these **are not** pocket pistols.

**Pull request merged**
