### PR TITLE
Queen get gut back

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Since spec are coming back, a small buff to queen to compensate.

Basicly instant gib with a cooldown of 5 seconds, i think it's balanced

https://user-images.githubusercontent.com/25491240/114190735-ecd65b00-994b-11eb-8930-dc4aed514956.mp4

## Why It's Good For The Game

Spec too good, need permakill

## Changelog
:cl:
balance: Queen get small buff
/:cl:

### CODE REVIEW

**Comment by Walarks** [comment]
I think specs are actually a better replacement to smartgunner.

**Comment by TGCMbetcher** [comment]
> I think specs are actually a better replacement to smartgunner.

as long as one of their weapon options is smartgunner

**Comment by Chaznoodles** [comment]
Hmm today I will say headbite bad and reinvent the wheel via Pools PR, then kneejerk Gut back in as a reaction to MJP's spec PR whilst attacking him on Discord.

image

You are not in TGMC to make the server better - you're in it to make it yours.

**Comment by BraveMole** [comment]
> Hmm today I will say headbite bad and reinvent the wheel via Pools PR, then kneejerk Gut back in as a hyperbole reaction to MJP's spec PR whilst attacking him on Discord as a combined effort to lower the value of his contributions.
> 
> image
> 
> You are not in TGMC to make the server better - you're in it to make it yours.

You really managed to bring back pool in this? lel

**Comment by Chaznoodles** [comment]
> You really managed to bring back pool in this? lel

You really managed to ignore every point made regarding your bad faith acting?

**Comment by DerrickChamberlain** [comment]
Wait we are putting specs back but not SGs? Fucking what?!

**Comment by SplinterGP** [comment]
Meme PR 
image

**Comment by DerrickChamberlain** [comment]
Yeah I was starting to realize that when I actually looked at the others.

**Pull request closed without merging**
