### PR TITLE
Fixes *help spamming the user.

### PR DESCRIPTION
**Pull request by DominikPanic**
Fixes: #1601

### CODE REVIEW

**Comment by spookydonut** [comment]
You haven't explained the issue in the PR description.

**Comment by DominikPanic** [comment]
The linked issue explains it.

**Comment by spookydonut** [comment]
Needs a valid description and changelog entry

**Comment by Rohesie** [comment]
Not adding a changelog entry for a bugfix most people would have missed is not a reason to invalidate a PR, Spooky.

**Pull request merged**
