### PR TITLE
Adding floppa and Martin!

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

More pets in TGMC! Also, got sprites from CM SS13.

## Why It's Good For The Game

To balance the canine that is Ranger, I decide to put a floppa named Martin that will be the moral support for requisition. He's a good cat.

## Changelog
:cl:
add: Floppa and Martin, the req caracal
imageadd: floppa sprites!
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
image

**Comment by novaepee** [comment]
martin wants you to stop buying from req; martin wants to be rich
image

**Comment by jroinc** [comment]
Give ayys a pet :|

**Comment by Luxyboo** [comment]
i hate floppa

**Comment by novaepee** [comment]
> Give ayys a pet :|

when xenos get major, they get pet

**Comment by token-map** [comment]
image
can xenos get a pet wasp

**Comment by bowlofcereal** [comment]
make it invincible or else

**Comment by novaepee** [comment]
recent minerva update

**Review by Kuro020 — APPROVED** [review]
cool floppa

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
