### PR TITLE
Fixes a TL-102 ammo counter bug

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request

Fixes a TL-102 ammo counter bug.
If the 102 is deployed with ammo, the ammo counter wont update until it is fire once. Its mild, but annoying.

## Why It's Good For The Game

Bugs = Bad

## Changelog
:cl:
fix: Fixes a TL-102 ammo counter bug.
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
```
[18:28:40] Runtime in data_huds.dm,500: bad index
  proc name: hud set machine health (/obj/machinery/proc/hud_set_machine_health)
  src: the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret)
  src.loc: the machinegun deployment syst... (/obj/structure/dropship_equipment/mg_holder)
  call stack:
  the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret): hud set machine health()
  the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret): update icon()
  the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret): Initialize(0)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret), /list (/list))
  the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret): New(0)
  the machinegun deployment syst... (/obj/structure/dropship_equipment/mg_holder): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the machinegun deployment syst... (/obj/structure/dropship_equipment/mg_holder), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(665150)
  Master (/datum/controller/master): Initialize(10, 0, 1)
```

**Comment by hyper2snyper** [comment]
> ```
> [18:28:40] Runtime in data_huds.dm,500: bad index
>   proc name: hud set machine health (/obj/machinery/proc/hud_set_machine_health)
>   src: the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret)
>   src.loc: the machinegun deployment syst... (/obj/structure/dropship_equipment/mg_holder)
>   call stack:
>   the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret): hud set machine health()
>   the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret): update icon()
>   the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret): Initialize(0)
>   Atoms (/datum/controller/subsystem/atoms): InitAtom(the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret), /list (/list))
>   the TL-102 heavy smartgun nest (/obj/machinery/standard_hmg/mg_turret): New(0)
>   the machinegun deployment syst... (/obj/structure/dropship_equipment/mg_holder): Initialize(1)
>   Atoms (/datum/controller/subsystem/atoms): InitAtom(the machinegun deployment syst... (/obj/structure/dropship_equipment/mg_holder), /list (/list))
>   Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
>   Atoms (/datum/controller/subsystem/atoms): Initialize(665150)
>   Master (/datum/controller/master): Initialize(10, 0, 1)
> ```

I know, but why?

**Comment by Swagile** [comment]
bruh ya gotta test your shit to see if it actually works before PRing it

or at least semi works

go to vsc, and go to debug, run with debugging on, and this woulda popped up

most likely because you removed the hud check somewhere it shoulda stayed after a quick look at the code

**Comment by hyper2snyper** [comment]
> bruh ya gotta test your shit to see if it actually works before PRing it
> 
> or at least semi works
> 
> go to vsc, and go to debug, run with debugging on, and this woulda popped up
> 
> most likely because you removed the hud check somewhere it shoulda stayed after a quick look at the code

dude i did test it, its working code. just with uh... a screwy runtime. I didnt notice the runtime so here we are.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
