### PR TITLE
Removes most uniform and mask armor values

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Edit: This PR now removes the armour values from hopefully all non admeme uniforms and powergamable masks.

Removes the armour from PMC uniforms and balaclavas and put it into their helmets and armour.
No change for PMC, but prevent marine cheese when they get their hands on it on certain maps.

## Why It's Good For The Game
Super high melee resist cheese bad

## Changelog
:cl:
balance: Removed armour from PMC masks and uniforms, and increased their helmet and suit armour accordingly
balance: Removed armour from non admin uniforms
/:cl:

### CODE REVIEW

**Comment by Jordanstolethepreciousslam** [comment]
And what about sec uniform? 5 armor is not a free tyr but is a big armor buff nontheless.

**Review by TiviPlus — APPROVED** [review]

**Comment by DerpiestBruh** [comment]
The horrors!

**Comment by Nickkoranda** [comment]
> PMC are the special response forces so they should have some more armored gear if you ask me.

The chest armor gains the armor from the uniform, no change to PMCs just marines getting the uniform.

**Comment by lbnesquik** [comment]
Perhaps we should replace the PMC gear on the maps instead.

**Comment by GravitronBlue** [comment]
Considering the goal of this PR consider changing the armor values of tactical jumpsuits, swat helmets, and possibly swat shoes found on bodies around the crashed ship on prison station.

**Comment by Lumipharon** [comment]
Done. Shoes/helmets and the like don't matter since you have to replace your equipment for that so it's not just free armour stacking.

**Comment by Jordanstolethepreciousslam** [comment]
Now this is based. But i would argue that the real problem is the way armor stacks. It shouldn't stack additively at all. Armor should stack multiplicatively. That would fix bullshit hand/feet armor and make targeting them viable and not a noob trap

**Comment by FIXTHERADBOXPLEASE** [comment]
Senior SS13 server running expert here. This will kill TGMC in 3 months if merged.

**Comment by Strayed-Raven** [comment]
If you do this. Add the uniforms to clothing vendor. Tis only fair. Otherwise I can see why reduction of armor.

**Pull request merged**
