### PR TITLE
disables valkyrie modules

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
i don't want this merged, but i do want it tested after seeing shit like this 
image
for refusing to spend all my points as captain on fucking valkyrie modules because i wanted to actually try something else roundstart for once

## Why It's Good For The Game
i want to see if people will cater to more interesting roundstart pick and options rather than spending 120 points on fucking valkyrie modules, though it might just be better to nerf the module itself

## Changelog
:cl:
balance: valkyrie modules disabled
/:cl:

### CODE REVIEW

**Comment by David-Stormwell** [comment]
based as fuck.
Problem is it's not gonna be merged, instead it should be reworked as like what me and Ren talked about in #devgen

**Comment by RenGusta** [comment]
Salt Baste

**Comment by lKiseki** [comment]
A based man ahead of his time. Would also suggest doing what David said, though.

**Comment by Naaanii** [comment]
Remove valk. Buff splints.

**Comment by bowlofcereal** [comment]
I would rather not have valks get removed over me making statements I didn't plan on actually doing, but this is funny as fuck as much cringe as it is.

**Comment by SkeletalElite** [comment]
If valk goes then bone breaks need to be nerfed severely. Splints are complete and utter garbage because any damage at all can remove them and the only alterative to splinting is surgery.

**Comment by Losenis** [comment]
>Autosplint bad
I bet the hunters did this

**Comment by BraveMole** [comment]
So you want people to do more "interesting" choice rather than letting chose what they want? M'kay

**Comment by Pariah919** [comment]
>So you want people to do more "interesting" choice rather than letting players chose what they want? M'kay
i guess i worded it poorly
i want to see what people move towards if valk is disabled, though it moreso speaks to the hilarious level of how broken autosplinting and good it is, guess it might need a bat finally

**Comment by SpaceLoveSs13** [comment]
> > So you want people to do more "interesting" choice rather than letting players chose what they want? M'kay
> 
> i guess i worded it poorly
> i want to see what people move towards if valk is disabled, though it moreso speaks to the hilarious level of how broken autosplinting and good it is, guess it might need a bat finally

If valk gets removed, marines need to have a medical skill buff to compensate for valk. The instant scan was extremely helpful.

**Comment by Losenis** [comment]
Instead of seeing valks and tyr2 you'll see more tyr2s to try prevent bonefracs when they can't autosplint them, but then xenos will start aiming head since tyr2 doesn't cover head. Autosplinting isn't good per se, it's that splints are dogshit and bonefrac is simply absolute hell on earth to deal with given its effects range from unwielding if not outright dropping your gun to actually being sentenced to death with every step damaging organs. If it's a head frac, the consequences are atrocious even with just a little bit of damage because brain damage force rests you without warning. This, combined with normal splints coming off extremely fast to the point one round I witnessed the entire marine side running out of splints and the other alternative was field surgery without even a vendor, gaming it by telling people to spam sleep on IC tab. 

Compare avoiding certain death to just having a bit more armor, or not getting gassed, or a couple tiles more light, or not getting set on fire which is purely for flamer loadouts, and yes people will gravitate to valk. Valk already has the downside that it can keep you alive when you want to die like in critdrag through tricordrazine, and even after the oxyloss on critdrag it still leaves you draggable for longer due to tricord healing all damage types at the same time. And this isn't even touching on how valk can get you accidental OD that rests entirely on a corpsman having imialky to save you the trip shipside.

Make splints not come off but make them only be applied on already broken limbs rather than preemptively splint and I'll give up valk, otherwise nah.

**Comment by Georgeur** [comment]
The reason why people are against this pr, is because its not nuanced enough. 
You're coming at this from the right direction, but it requires more work.

**Comment by Naaanii** [comment]
> > > So you want people to do more "interesting" choice rather than letting players chose what they want? M'kay
> > 
> > 
> > i guess i worded it poorly
> > i want to see what people move towards if valk is disabled, though it moreso speaks to the hilarious level of how broken autosplinting and good it is, guess it might need a bat finally
> 
> If valk gets removed, marines need to have a medical skill buff to compensate for valk. The instant scan was extremely helpful.

Vali does it too.

> > So you want people to do more "interesting" choice rather than letting players chose what they want? M'kay
> 
> i guess i worded it poorly
> i want to see what people move towards if valk is disabled, though it moreso speaks to the hilarious level of how broken autosplinting and good it is, guess it might need a bat finally

Might as well disable Tyr 2 as well.

**Comment by EvilMelonTheSecond** [comment]
Like other have said the problem isn't valk. Valk is the bandaid to the problem, that marine is right he needs valk or he can't do anything but sit behind cades with aimmode.

I would say mimir, baldur, tyr and hlin are all viable modules but valk is mandatory for all types of jaeger even if you are a corpsman with plenty of splints. The problem is fractures being too debilitating and splints being unusable in combat. Disabling valk will push people to tyr2 but disabling both valk and tyr2 will push people to baldur2 or MAYBE mimir and in niche cases Hlin

**Comment by BraveMole** [comment]
Yeah just buff splints so they don't break in one slash. That will make vali less of a goto module

**Comment by AnCopper** [comment]
Valklets on suicide watch.

**Comment by Swagile** [comment]
either someone will find a way to buff self scan + splints for everyone, or ill do it tomorrow, cause i got projects today

and then this can get merged

**Comment by Dolth** [comment]
That'd be nice to not have petty PR like that and actual proper work.

**Comment by Losenis** [comment]
Packed more splints than usual knowing this pr was TMd, and I still almost run out of them despite even resupplying from a gigantic stack of splints in a crate at fob. Some people needed three splints reapplied after every fight, and once you had one frac that means a splint reapplied after every single fight because xenos are already targetting that limb to frac it in the first place. It got more cancerous when I was the corpsman, I was the one handing out splints so I also had to splint myself, and at one point I had to reapply a splint twice in 10 second because I happened to get scratched.

Splint supply used to not be a problem because many people used valk so one didn't need to use splints on them. Now, once marines start running out of splints, getting chest or head frac will be a death sentence.

**Comment by Knuff-les** [comment]
Splintman marines rely on medics to bring bags of splints. Imagine tming a genuine salt PR

**Comment by Walarks** [comment]
Remove valk, readd specs

**Comment by Swagile** [comment]
a based and bold decision thrown back into the void

a pity

**Pull request closed without merging**
