### PR TITLE
Adds Nanites to Research Rewards

### PR DESCRIPTION
**Pull request by Verlurk**
## About The Pull Request

Adds 10u bottles of nanites to researcher uncommon rewards tier, coupled with #9012 .

## Why It's Good For The Game

Stops people insulting me on Discord for removing the unintended source of nanites in the form of razorwire grenades (more commonly used to spam dropper wire and not for medical nanites). Means medical nanites and razorwire can be produced in limited quantities with an active researcher.

## Changelog
:cl:
add: Nanite bottles added to Research Rewards.

/:cl:

### CODE REVIEW

**Review by BraveMole — CHANGES_REQUESTED** [review]
wrong nanite. If people want razorburn they buy razorbun nades

**Comment by Verlurk** [comment]
> wrong nanite. If people want razorburn they buy razorburn nades

@BraveMole This is intended to make them cart it shipside and actually make recipes, thereby involving doctors in the loop. I feel like handing them the finished product off the bat defeats the point!

**Comment by BraveMole** [comment]
> > wrong nanite. If people want razorburn they buy razorburn nades
> 
> @BraveMole This is intended to make them cart it shipside and actually make recipes, thereby involving doctors in the loop. I feel like handing them the finished product off the bat defeats the point!

And what's preventing them to use that to create more razor wire with it, just like the current situation

**Comment by Verlurk** [comment]
> > > wrong nanite. If people want razorburn they buy razorburn nades
> > 
> > 
> > @BraveMole This is intended to make them cart it shipside and actually make recipes, thereby involving doctors in the loop. I feel like handing them the finished product off the bat defeats the point!
> 
> And what's preventing them to use that to create more razor wire with it, just like the current situation

@BraveMole The razorburn recipe requires 7u of nanites as a side thing, and 1u per reaction. The bottle given is only 10u, as a reward for killing and researching xenos. The first bottle's only giving 3 razorwire reactions due to the 7u side, the second will give the full 10, and so on. This also relies on it 1. Dropping as a reward from research, which is already a random chance, and it's on the uncommon tier so won't drop from minions, and 2. The chain being in place for the researcher to do his thing,  a MD to send down the chemicals/make grenades, then send it back down!

**Review by BraveMole — APPROVED** [review]

**Comment by Licherr** [comment]
me when the researcher becomes essential in merely only 3 months

**Comment by Walarks** [comment]
> The bottle given is only 10u, as a reward for killing and researching xenos. The first bottle's only giving 3 razorwire reactions due to the 7u side, the second will give the full 10, and so on.

If the reward is for xeno drops, put it in the xeno instead of the money bucket.

**Comment by BraveMole** [comment]
Allright, after thinking about this, such a "useless" item does not belong with shoulder gun and armblade. So we'll go with the other solution instead

**Pull request closed without merging**
