### PR TITLE
Doctor's delight rebalance

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
Changes DD: rather than flat healing, it determines healing per tick based on healing chems in the same mob. Typically supplies half of the drug's effect. It also shows up on med scanners.
DD metabolizes faster and adds nutrition instead of removing it. 
Soda vending machines and booze-o-mats stock DD in cans and bottles.
Hypervene additionally purges consumable reagents (foods and drinks).

Current chems DD works with: bicaridine, kelotane, dylovene, dexalin, paracetamol, meralyne, and dermaline. Suggestions for others welcome.

## Why It's Good For The Game
I've got a handful of gripes against DD: reagent med is at its least interesting when it's just stack all these different juices that heal without thought, the drawback (nutrition drain) is negligible given that marines have infinite food available, it doesn't have ODs so you can just drink a few gallons and be fine, and since DD isn't classed as a medicine it's unaffected by purges (marine or xeno) and doesn't matter for kidney cap.
This handles those without reducing DD's effectiveness in specific use cases, as well as makes it available without relying on chem mixing.
Since it relies on other meds in the body, their being purged results in DD not healing, plus it play into the kidney limit.
Making it add nutrition instead of reduce it causes overuse to be more of a nuisance, and that combined with a higher metabolisation rate encourages spot use instead of continuous.
Hypervene purging food and drinks is important as a backup, as even without specific OD effects you might want to remove it.

## Changelog
:cl:
add: Following a space fax campaign by health advocacy groups, the Souta Soda Company has started stocking a healthy juice blend in their vending machines. The TerraGov Marine Core has also updated their basic health scanners to be able to detect this mix, citing popularity among medical staff.
balance: Instead of applying flat healing, doctor's delight increases the healing of most common chems by half.
balance: Doctor's Delight increases nutrition instead of draining it and metabolizes significantly faster.
balance: Hypervene purges consumable reagents.
/:cl:

### CODE REVIEW

**Comment by XxBarotraumaBugReporterxX** [comment]
I dont see how this could make anyone willing to use DD

**Comment by goose4429** [comment]
So, when you have chems inside, DD buffs the healing? Sounds OP actually. I'd **definitely** abuse the hell out of it, because with hypos I care little about chem limits.

But you know what? I think just giving it in booze-o-mats is a nice idea. And the heal factor is a nice idea. Just make the DD purge the meds! 3 per tick or so. Mwahaha

**Comment by Al-1ce** [comment]
### DD:
>Heals 0.5 of OXY, TOX, BURN, BRUTE. (per tick)
>Cannot be overdosed
>Causes no pain
>0.05 Metabolism rate (emphasis on the extra zero)
>Causes hunger (allows for eating, which restores blood)
### Tricor:
>Heals 0.8 BRUTE and BURN, 0.4 TOX, and 0.5 OXY (60 Brute, 30 Burn, 40 Tox, 20 Oxy, per pill)
>Causes increasing pain at 10u (+5), and 20u (+15).
>At 30u, causes jitteriness and damages the brain by 1
>At 50u, deals 3 BRUTE, 3 BURN and 3 TOX


Tricordazine is a proper medication with sufficient upsides and downsides. It can be misused and will incur heavy penalties.

Doctor's Delight is an ancient remnant from /tg/ bar-code. It does exactly what Tricordazine does, except without any downsides. There is absolutely no reason to use Tricordazine when DD does everything it can, without causing pain or overdose.

DD should be removed, or have the medical properties completely atomized. It currently functions as a powercreep chem with **_literally_** zero downsides. You couldn't even fuck up with it if you tried. 



> So, when you have chems inside, DD buffs the healing? Sounds OP actually. I'd **definitely** abuse the hell out of it.

That's the problem. You can't do the same with Tricordazine, why should you be able to with DD? This chem shouldn't exist.

**Comment by ilikesaying** [comment]
Being fat applies slowdown.

**Comment by Al-1ce** [comment]
> Being fat applies slowdown.

You can easily not become fat by observing the status messages when eating. "unwantingly biting into [food]" -- the slowdown is marginal at best and temporary, while also easily removable with, say, hypervene.

**Comment by Lumipharon** [comment]
Wait, why are you massively buffing DD? Now it's designed specifically to be powergamed by multiplying as many healing chemicals as possible.

Just remove the Chem, or give it an OD. It's dumb.

**Comment by MathiasOrtega** [comment]
With all the back and forth tweaks to chems and medical. Is there no real place in it for marines? This is a nice attempt, but even when the dispensers were added so you could make DD it was never utilized except for the marine that added said dispensers. There is no incentive for more chems when the holy quadtrinity exists (BKTT). Premed is being targeted. This maybe would have been nice 4 months ago.

**Comment by QualityVan** [comment]
> You can easily not become fat by observing the status messages when eating. "unwantingly biting into [food]" -- the slowdown is marginal at best and temporary, while also easily removable with, say, hypervene.

Can you explain how exactly hypervene removes excess nutrition? Also, you don't bite into DD.

> Wait, why are you massively buffing DD? 

I'm not sure how it's a massive buff. If you have four different chems in your system (bic+kelo+dylo+dex) it's on par with how it was before this. It'll heal more if you run it with meraderm, but that should be largely limited to corps rather than the current complete uptime.

**Comment by Al-1ce** [comment]
> Can you explain how exactly hypervene removes excess nutrition? Also, you don't bite into DD.
Hypervene causes vomiting. Vomiting causes you to vomit, which makes you more hungry.

>I'm not sure how it's a massive buff

"Instead of applying flat healing, doctor's delight increases the healing of most common chems by half." - This is broken.

**Comment by Al-1ce** [comment]
>Can you explain how exactly hypervene removes excess nutrition? Also, you don't bite into DD.

Hypervene causes vomiting, which reduces nutrition significantly. 

> I'm not sure how it's a massive buff

You're allowing a decrypt regnant from ancient bar code to increase the healing of most common chems by half. As I've mentioned above, this chemical has absolutely zero downsides and cannot be OD'd. It's an incredibly massive buff to something which shouldn't exist to begin with.

**Comment by QualityVan** [comment]
> Hypervene causes vomiting, which reduces nutrition significantly.

That's true, I hadn't considered that. Let's take a look. Vomiting drains 40 nutrition, and can activate once every 40 seconds. Hypervene has a 5% chance per tick, so on average it'll activate once every 40 seconds. With a 1u metab rate, that's 20u per vomit, or just south of seven pills. You could, if you so wished, chug half a bottle of hypervene to probably vomit once. I'm not super worried about this, since doing so means you're cleaning out all chems you had prior and also during.

> This has nothing to do with anything I've ever said in this PR. I'm quite aware it's a.. chemical. o__o

That being the case, could you explain the comment about 'observing the status messages when eating' is at all relevant to the pr?

> You're allowing a decrypt regnant from ancient bar code to increase the healing of most common chems by half. As I've mentioned above, this chemical has absolutely zero downsides and cannot be OD'd. It's an incredibly massive buff to something which shouldn't exist to begin with.

Again, could you explain how keeping a chem at roughly the same healing rate in one case (running four basic chems), higher with niche chems that (should) have highly limited availability, and lower while standalone is a massive buff? Even at max, DD doesn't begin to touch actual massive heal chems like RR or neura. If you'd like to open a pr to remove it entirely, you're certainly welcome to do so. Or, feel free to suggest further, specific drawbacks/OD effects?

**Comment by KrabSpider** [comment]
Literally just make it an alcohol. Even if theres a chem that heals drunkenness it also PURGES alcohol reagents.

**Comment by Lumipharon** [comment]
You're buffing it for powergamers, who invariably WILL use it with 9 chem cocktails. The average unga wouldn't bother to even make DD in the first place. DD is purely a powergamer chem, so it being equal or worse with small amounts of chems is irrelevant.

**Comment by goose4429** [comment]
> > Wait, why are you massively buffing DD?
> 
> I'm not sure how it's a massive buff.

It _is_ a massive buff, because instead of BKMD and Tricord mix, you use BKMD and DD mix. Overall, this buffs your healing from 3.8 to 4.5. If the dosage is small, you can use Tricord as well, making it 5.3. In this particular case, it's a massive buff by exactly 1 per tick from MD, and 0.5 from being easily available.

It does the healing already, but most people don't bother using it. Now you're making it more available, which means allowing the use of one more heal freely. From BKT for 1.8 heal per tick, we turn to BKTD, with 2.3. Again, this _is_ a buff.

**Comment by QualityVan** [comment]
> You're buffing it for powergamers, who invariably WILL use it with 9 chem cocktails... [I]t being equal or worse with small amounts of chems is irrelevant.

Putting aside that you can't walk straight with 9 meds in you, it only works with the list of chems mentioned in the pr desc. It's not just slap it with anything and have it work.

> It does the healing already, but most people don't bother using it. Now you're making it more available

So to be clear, your issue is with improving the availability? I'm not fond of framing the comparison as drugs without old dd versus drugs with new dd otherwise. Alternatively, if you're concerned that the bonus with meraderm will be overly prevalent, isn't that a sign that meraderm itself is too publicly available? I'm not hugely tied to that pair regardless, I just thought it'd be nice for something called doctor's delight to synergize with something that doctors specifically should have.

**Comment by Al-1ce** [comment]
> That being the case, could you explain how the comment about 'observing the status messages when eating' is at all relevant to the pr?

I was clearly responding to the message made by @ilikesaying.

> Again, could you explain how keeping a chem at roughly the same healing rate in one case (running four basic chems), higher with niche chems that (should) have highly limited availability, and lower while standalone is a massive buff?

It's needlessly accelerating healing. It is simply unneeded. The vast majority of kills xenos acquire are obtained by chip damage, which would be largely, if not entirely negated if basic healing chems did 50% more than what they already do. It **_does not matter_** what drawbacks you add, this is completely unfair and unbalanced for the other party. Accelerated healing is very limited on this server for a reason.

I'll reiterate again: **_this chem shouldn't even exist._** It's a remnant from drink code. It is not a medicine and should have all of its medical properties atomized. We do not need this. Simple as. It's already powerful enough as it is.

**Comment by Lumipharon** [comment]
> Putting aside that you can't walk straight with 9 meds in you, it only works with the list of chems mentioned in the pr desc. It's not just slap it with anything and have it work.

Microdosing. And I didn't mean literally 9 meds, just whatever mixture of everything to max healing + max DD bonus, chuck it in a hypo/cigar/whatever and dose as needed.

**Comment by Weedmaster77** [comment]
So its used in Somolent recipe so removing it means replacing it in that.  But to be honest I've only ever seen a few people use it in my almost 200 hour of medical staff and medic and most people don't know its even exist to powergame with it so completely removing it seem like a bit much but taking it healing away might be a good compromise to just removing it.

**Comment by Naaanii** [comment]
Making it easier to obtain seems okay, but this seems like an overbuff. I feel like DD is in an okay spot as it's harder to obtain, drains nutrition from healing but can also basically be a permaheal chem in the right hands. 

While nerfing and compensating is fine, this overall feels like an overbuff overall.

**Comment by TiviPlus** [comment]
Why is this drafted btw

**Comment by QualityVan** [comment]
> Why is this drafted btw

mjp said he was gonna talk to me but hasn't yet, and having thought more about it I either want to reduce the potencies or adjust it to count as a medicine. Not sure which.

**Pull request closed without merging**
