### PR TITLE
Sawn-off shotgun must now be wielded to fire

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title.

## Why It's Good For The Game
Very powerful shotgun, shouldn't be something you can one hand.

## Changelog
:cl: Lewdcifer
balance: Sawn off shotgun must now be wielded to fire.
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
So, the entire gimmick of it is dead then?

**Comment by Lumipharon** [comment]
I like killing ravs in 0.2 seconds tho

**Comment by RipGrayson** [comment]
> So, the entire gimmick of it is dead then?

I thought the gimmick of a sawn-off shotgun was more damage in exchange for greater spread. At least that's the way it is in most games.

**Comment by Mrrpip** [comment]
Well. Ivan, if you read this. It wasn't me. -Skye

**Comment by Derrick2Electricboogaloo** [comment]
Have you ever seen terminator?

**Comment by ivanmixo** [comment]
> Well. Ivan, if you read this. It wasn't me. -Skye

I told him :)

**Comment by Victor239** [comment]
Yeah tbh everyone having a fucking **shotgun** as a *sidearm* is ridiculous.

**Pull request merged**
