### PR TITLE
Scout and Sniper cloaks buff

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Adds one (1) cloak of each type to a marine vendor.

Changes invisibility on sniper and scout cloaks:

Running: 50% >>> 25%
Walking: 15% >>> 5%
Standing: 5% >>> 1%

## Why It's Good For The Game

Cloaks were last touched 4 years ago, and are pretty useless right now since everyone can spot you so easily. This PR increases invisibility on cloaks, allowing to be less likely to spotted, and adds 1 cloak of each type to a marine vendor so more people can try them out.

## Changelog
:cl:
balance: scout cloaks invisibility increased, and added 1 of each type to marine vendors
/:cl:

### CODE REVIEW

**Comment by iLikeMemes** [comment]
#11680 This PR is currently open which also proposes a change for scout/sniper cloaks, might interfere with what you are attempting to do.

Beside that I do certainly think that a scout/sniper cloak buff is warranted, but this is too much of a buff in one go (imo). Either buff the invisibility or make 1 of each cloak free. After that see how the game plays and fine tune it after.

**Comment by FIXTHERADBOXPLEASE** [comment]
This is probably the better option. The cloaks sucking at their main purpose is the bigger issue, and anything that helps save an item from Req hell is good in my book.
Even a buffed cloak wouldn't be able to compete with buying as many b18s and special weapons as you can. Which is one of the huge problems with req-exclusives.

**Comment by Pariah919** [comment]
Cloaks are poor choices due to how beno vision works. Though I don't know about making them roundstart.

**Comment by FIXTHERADBOXPLEASE** [comment]
A cloak with decent stats is a plenty good choice.
Xenos can see terrain through walls, unlike on CM, so there's something for the Marine's sprite to blend in with.

This is why the chirp-implant cloak from Xeno Research is so great. The slight decrease in visibility it has makes the user that much harder to detect, whereas the back-mounted cloaks turn a Marine into a nigh fully visible glass-man the moment he takes a step.

**Comment by SilencedMP5A5** [comment]
do not make these roundstart items.

**Comment by 567Turtle** [comment]
Hey, creator of #11680 is I, I think this is better honestly.

**Comment by Waselon** [comment]
guess nobody wants this

**Comment by Luxyboo** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO MY BELOVED

**Pull request closed without merging**
