### PR TITLE
Spitting anything (acid spit, slowdown spit, boiler spit) as a Xeno slows you down for a short time.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Spitting anything as a xeno will slow you down for about 2 seconds. The slow effect is based on the game's slow effect, and you will progressively increase in speed as the effect reduces.

## Why It's Good For The Game

Honestly one of the worst things about TGMC right now is the 2 hour rounds that are only 2 hours long because the last few xenos consist of a shrike and two spitters/sentinels. The marines proceed to chase these 3 xenos through the winding ice caves, almost killing one each time, but only to get healed or get away at 25% health because the xenos just spam their short cooldown spit abilities.

The second worst thing about TGMC is those lone sentinels/spitters who repeatedly hide behind a corner, spit at a turret, then go back behind that corner and/or run off into the distance to repeat the process a thousand times over. They don't bother to evolve to boiler because that means they're too weak and important to be alone, which means that they, god forbid, have to work with other xenos.

This is not good gameplay. It's getting extremely stale, especially on crash rounds. Even playing spitter/sentinel doing this, it just feels wrong. Hopefully this PR will be the first of many reworks/buffs/nerfs that prevent the sort of hit and run gameplay that should only be reserved to the hunter/runner/pred castes. 

## Changelog
:cl: BurgerBB
balance: Spitting as xeno slows you down for 2 seconds. The slow's magnitude is reduced when the duration is depleted.
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
It's hard to really explain the slowdown mechanic but it doesn't feel like 4 seconds. Many people may think it's a hard 4 second slow at 50% but it's more like a 50% slow at second 1, 30% at second 2, and 10% at second 3 and 0% at second 4.

**Comment by terranaut1** [comment]
Spitters rely excessively on hit and run tactics when harassing marines in a fortified position, when they're moving a convoy or just to slow them down as the hive retreats. This is an awful idea.

**Comment by Kuro-ai** [comment]
Are you nerfing hit and run tactics on a antagonist that is all abou hit and run tactics?this is not a good solution to end round delaying

**Comment by InterroLouis** [comment]
This is an unnecessary change which will send spitting to the shadow realm. I say nay.

**Comment by Rohesie** [comment]
Don't you think that slowing down these fast xenos might be a better alternative?

**Comment by BurgerLUA** [comment]
> Don't you think that slowing down these fast xenos might be a better alternative?

I mean, this is what the PR does.

**Comment by jroinc** [comment]
Uh. Make it a 3 second slow and I can see it. 4 seems a little too long in combat.

**Comment by BurgerLUA** [comment]
Made it 2.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
