### PR TITLE
Nerfs bookcases

### PR DESCRIPTION
**Pull request by jonash07**
## About The Pull Request

Changes the bookcase integrity from 500 to 200

## Why It's Good For The Game

I swear i have no idea why are they so tanky it takes around 10 machete hits to take ONE down its genuinely infuriating

## Changelog

:cl:
balance: changed bookcase integrity from 500 to 200
/:cl:

### CODE REVIEW

**Comment by blackdav123** [comment]
its over

**Comment by Lumipharon** [comment]
the power of books.

**Comment by yyzsong** [comment]
something something pen something something sword

**Comment by chizzy376** [comment]
All that studying pays off you know

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
