### PR TITLE
A 1600 req point miniscope for SADAR

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

From #13396 , this PR.

## Why It's Good For The Game

SADAR should be used more, but its increased capability requires a big cost. You better stack a lot of good points for this funny mini scope.

## Changelog

:cl:
add: A 1600 req point miniscope for SADAR
balance: SADAR gets miniscope back but at a cost of 1600 req point
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
I'm against this change. I removed this for a reason.

**Comment by Tonklaatech** [comment]
Literally 2 un-scope SADAR worth of points???

**Comment by Al-1ce** [comment]
This was killed a while ago for a good reason.

But I'd still like to see it given another whirl.

**Comment by ivanmixo** [comment]
Uhhhh no. Slapping a ridicilous pricetag on offscreen instakills still doesn't make them okay.

**Comment by Mrrpip** [comment]
...I don't know if this is an army joke about the scope costing more than the gun or something but uh....

This feels like one of those things where it won't be used unless the ungas are already stomping or the RO is pulling everyone's leg without admitting it.

**Comment by Mrrpip** [comment]
Aside from that though, and my low opinion of funni fortified defender offscreen OHKOs with old AP rockets. 

The scope should have a icon or something to make it stand out. I feel like if it's just a name change, some dum dum's going to lose it...Or pretend to.

**Comment by novaepee** [comment]
sorry, mjp, maintainer says no

**Pull request closed without merging**
