### PR TITLE
Disables survivor

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Disables survivor from being picked
## Why It's Good For The Game
Survivor is barely maintained, every map varies hilariously badly in the amount of gear and people barely take it into consideration while designing their maps (any map that isn't ice colony is awful to play in as it's either small or has no defendable points outside the FOB)

## Changelog
:cl:

balance: survivors are dead
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
rip survivor bois,gone but...they actually were always forgotten

**Comment by jroinc** [comment]
David's gonna kill you.

**Comment by spookydonut** [comment]
Survivor is bad just rip out the whole job

**Comment by henriquekill9576** [comment]
no bad

**Comment by David-Stormwell** [comment]
MJP... you betrayed the surivor role.... how could you

**Comment by TiviPlus** [comment]
based fix tag

**Comment by Hathkar** [comment]
The point of survivor is to give the xenos something to do before the marines arrive, and it makes for some interesting RP if you actually manage to survive.

It also weeds out the stupid xenos who just rush in.

**Comment by jroinc** [comment]
Random thought- What if a few survivor slots open up when the shutters do, but there are no roundstart ones?

**Comment by spookydonut** [comment]
survivors are a distraction from the core gameplay, do not lend themselves to supporting the team ethic, are not actively developed for, and mean less players for the two 'real' teams.

Not to mention its proven impossible since they first were added to strike any kind of meaningful balance between just being free extra larva for xenos and hive destroying, balance wrecking, killing machines

**Comment by drawsstuff** [comment]
It would be a shame to see them go. I enjoyed toying with them a bit more than the standard ungie dungie

**Comment by Spyroshark** [comment]
if this is a balance issue why not just make it impossible to infect survivors

**Comment by spookydonut** [comment]
> 
> 
> if this is a balance issue why not just make it impossible to infect survivors

then they're just a snowflake vanity role that marines will use as minesweepers

**Comment by drawsstuff** [comment]
replace survivors with sapient monkeys

**Comment by spookydonut** [comment]
survivors are extremely skill dependent and high skill players shouldn't be catered to with a non-marine role.

**Comment by Pariah919** [comment]
it appears this isn't that wanted, another day I suppose

**Pull request closed without merging**
