### PR TITLE
Adds new Tadpole - Outrider Transport

### PR DESCRIPTION
**Pull request by Apple-107**
## About The Pull Request

Adds a new tadpole, called the Outrider. As big as cargo tad, but with more enclosure. Design similarities to Umbilical, but larger.

_outrider

First PR. I put this together and had admins saying to PR it.

## Why It's Good For The Game

More tad designs. The large tad was always 'grief' because its wide open and big. Now, after removal of cades, its even more so. This should be a bit easier to hold, but still have the disadvantage of being large and hard to land. It might also just be grief, that'd be funny.

If changes are made to tads in the future to limit APC/tank presence on them, this would be one of the few tads to be able to accommodate both an APC and a tank simultaneously.

## Changelog
:cl:
add: Added new tadpole- the Outrider- an asymmetric design for carrying large vehicles.
/:cl:

### CODE REVIEW

**Comment by Apple-107** [comment]
it's in DMM instead of TGM, working on it.

**Comment by ivanmixo** [comment]
Doesn't this just powercreep out the big tad then? Maybe delete it if it's straight up worse if this is approved

**Comment by Apple-107** [comment]
> Doesn't this just powercreep out the big tad then? Maybe delete it if it's straight up worse if this is approved

maybe? there's probably a few situations where you'd want the open tad (big marine force, indirect weapon spam), I'm obviously not gonna be the one deleting it

**Comment by Lauwma** [comment]
Big tad is technically better for HSG I guess

**Comment by lbnesquik** [comment]
I am not sure I would pick this over the big tad, but sure!

**Review by TiviPlus — APPROVED** [review]
Code ok

**Comment by Apple-107** [comment]
there's weird behaviour with the fire extinguisher cabinet sprites but the extinguisher always appears in the correct place. I think it's an issue with the extinguishers themselves rather than the way I put them in

**Comment by ivanmixo** [comment]
The warning black and yellow lines annoy the hell out of me also. Why are 2 on the inside, but that one is just on the outside of the inner square? Literally unplayable

**Comment by Apple-107** [comment]
> The warning black and yellow lines annoy the hell out of me also. Why are 2 on the inside, but that one is just on the outside of the inner square? Literally unplayable

_outrider

**Comment by Apple-107** [comment]
it passes all checks,  big github lies to you

**Comment by Fawkes541** [comment]
great vehicle tad balanced by pilot glass not in turret cone of arc + goofy turret placement 

10/10 new and interesting tad

**Pull request merged**
