### PR TITLE
Re-PR Lewd's Behemoth changes

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

https://github.com/tgstation/TerraGov-Marine-Corps/pull/14716
## Why It's Good For The Game

https://github.com/tgstation/TerraGov-Marine-Corps/pull/14716
## Changelog
:cl: Lewdcifer
add: Behemoth 2: Now with more caffeine! Check the relevant PR for the full detailed changelog.
add: Completely revamped Earth Riser's primo. Meteors rain from above!
balance: Behemoth melee damage reduced from 26 to 23. This also affects all ability damage.
balance: Maximum health reduced from 750 to 650, maximum wrath adjusted accordingly.
balance: Movement speed increased from -0.2 to -0.5, weed speed modifier increased from -0.1 to -0.2.
balance: Behemoth roll wind up increased from 1.8s to 2s.
balance: Behemoth roll speed gain reduced from 0.4 to 0.35.
balance: Landslide movement speed increased from 1.7 to 1.5. This is much faster than it sounds!
balance: Earth Riser plasma cost reduced from 30 to 20.
balance: Earth Riser cooldown reduced from 15s to 10s.
balance: Seismic Fracture is no longer ranged, but rather an AoE around the Behemoth.
balance: Seismic Fracture attack radius increased from 2 to 3.
fix: Fixed a bug where Primal Wrath would no longer replace plasma costs with wrath.
fix: Fixed a bug where Landslide couldn't be cancelled sometimes. Now it's responsive and reliable.
spellcheck: Behemoth cooldown messages no longer include the ability's plasma cost.
sounddel: Removed an unused Behemoth sound file.
imageadd: Added an icon for the primordial version of Earth Riser
refactor: Refactored Behemoth AoE attacks.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
OK but can you not add the slash damage nerf? Then it'll be practical to use.

**Comment by ivanmixo** [comment]
Youre not having hunter level slash damage on a ranged tank

**Comment by Arturlang** [comment]
> Youre not having hunter level slash damage on a ranged tank

Can you tell me what role behemoth currently fulfills? Tanking alone is not it's job, due to the low armor which gets mulched moreso than even gorger as it lacks self-healing. Stunning does not apply here as it's stuns are too quick. Damage does not apply either as you're making it not able to kill single marines alone as it can't outdamage them due to low damage even without meds. So far what behemoth can do is interrupt marines in doing things. I wouldn't call a behemoth a ranged tank either due to it only having one somewhat long cooldown ranged attack.

**Comment by Kuro020** [comment]
lets test this out

**Comment by Kuro020** [comment]
it merge conflicting, so over

**Comment by Carnage068** [comment]
> Youre not having hunter level slash damage on a ranged tank

why even reopen this if you're not gonna change anything? do you NOT listen to feedback that people give? goodness, what a waste of time

**Comment by Carnage068** [comment]
welp. glad i'm on break lol

**Pull request merged**
