### PR TITLE
.44 Rimfire Rifle Rounds (Leicester Repeater)

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
For my own sanity and because the very person that has PR'd it disappeared from the face of the Earth, I have taken it upon myself in my own ineptitude to create a new caliber and ammunition exclusive to the Leicester Repeater. The ammunition deals 65 base damage, 20 armor penetration, 1.25 sunder. The high impact bullets tag targets within a 3 tile range for 2 slowdown.

~~By the way, first aid pill packets have their own icon states. Did I mention that? That change is non-negotiable.~~ **Nevermind. The "Man" has proven more powerful than previously anticipated**. 

## Why It's Good For The Game
-The Leicester is a dying gun without much appeal for many. It has no unique aspects in the attachments it can utilize, its ammo, or even its stats. It simply exists to take up space and I believe that it deserves better than that. 
-Repeater bullets serve the function of providing moderate damage and self defense within a range where targets that _could_ be sniped would have be in buckshot's point blank range to begin with. 

## Changelog
:cl:
add: .44 Rimfire Bullets, exclusive to the Leicester Repeater. Deals 65 damage/20 AP/1.25 sunder with 2 slowdown within a 3 tile range. 
imageadd: .44 Rimfire Ammo Packets

/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
It shouldn't even be a default gun, it's out as place as fuck. Having it's own ammo is good though.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
atomize this sir, pill packet getting new sprites should be its own pr

**Review by Kuro020 — APPROVED** [review]

**Review by BraveMole — APPROVED** [review]

**Comment by AndroidMK2** [comment]
What we're the ammo stats of this weapon before? Also it very much so needs the buffs couse it's near useless now.

**Comment by KrabSpider** [comment]
> What were the ammo stats of this weapon before? Also it very much so needs the buffs couse it's near useless now.

60 damage, 20 armor pen.

**Comment by KrabSpider** [comment]
Deleting the stagger. Buffing the slowdown I guess.

**Comment by KrabSpider** [comment]
29 commits made. Making a new PR

**Comment by KrabSpider** [comment]
#8946 Does this better and has no conflicts whatsoever.

**Pull request closed without merging**
