### PR TITLE
Adds new stuff to the CL briefcase vendor!

### PR DESCRIPTION
**Pull request by DeerJesus**
## About The Pull Request

I've been really wanting some stuff to be added to the vendor for a long time. It's basically empty outside of cigars and cash. I want to add more things, more expensive things, that prey on marine's vices.
## Why It's Good For The Game

Corporate liason is sorely lacking in content. No one's going to go to them for just a few cigars or 500 dollars of unusable space cash. This adds some things that are actually usable. Mostly liquor and drugs- but a few medical items that aren't 'too op' but not too bad either.

This also adds a way to get a drink over 100 boozepower (like TG's bacchus blessing) and an actual way to get a bottle of the special reserve whiskey. Hooray!
## Changelog
:cl:
add: added nt-06 experimental liquor, a proto-bacchus-blessing that fucks up any liver it touches
add: added the bottle of space-aged whiskey (like ship-aged whiskey irl but a pun and more relevant)
add: added SIX new items to the corporate liason suitcase!
/:cl:

### CODE REVIEW

**Comment by DeerJesus** [comment]
why did these fail? im new to this

**Comment by lbnesquik** [comment]
image

Check out the bot things by clicking on details. Your code doesn't compile, so, you oughta go back and fix it till it does.

**Comment by DeerJesus** [comment]
ia got it

**Comment by Mrrpip** [comment]
Now that's interesting to see. A purchasable Roullettium and Elite injector.

**Comment by InterroLouis** [comment]
50u seems a bit excessive for mindbreaker, especially with a default injection amount of 50.

**Comment by DeerJesus** [comment]
How about like 30?

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
