### PR TITLE
Kill sticky, weeds slow down

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Sticky no longer exist, sticky spit and sticky huggers have buffed slowdown and stagger to compensate

Weeds natively slowdown (1/4 of sticky slowdown)

## Why It's Good For The Game

Sticky is terribly boring to put in mazes, and then terrible to clear for marines. 
Meanwhile, they are almost necessary to win as a xeno, meaning that if drones/queen/shrike are too lazy (and you can't really blame them, cause putting sticky is so shit), you have automaticly lost 

The weeds are far easier to make, but also far easier to clear, so the game should feel better for both sides.

And marines are way too fast on weeds anyway IMO, xeno deserve that buff 

## Changelog
:cl:
del: Sticky no longer exist
balance: weeds natively slowdown
balance: sticky spit and hugger have more slowdown and stagger
/:cl:

### CODE REVIEW

**Comment by RenGusta** [comment]
Remove xenos speed up on weeds if we're going back to marines taking a heavy speed penalty on weeds again. That's why they got it, after all.

**Comment by KornFlaks** [comment]
This not only nerfs sticky mazes, it nukes it from the game.

I get it, sticky mazes are annoying as fuck to set up. As a queen main, it feels like I'm a glorified hivelord that spends 40 to 60 minutes of round start just checkerboarding sticky throughout the map and if the queen doesnt do that, well we have 11% winrates for a reason.

I didnt realize that sticky staggers on hit. Hrm. I should make my first PR making sticky screenshake as well to give Ocelot a taste of his own medicine.

**Comment by SplinterGP** [comment]
This wont go in, not with xeno speed on weeds since we added one to remove this

**Comment by Pariah919** [comment]
considering how easy it is to weed in tgmc, you're either forcing cas to be a thing and making the game even more defensively oriented for marines, which is pretty silly
i only added weed native slowdown to the run pr because marines got overall faster as well.

**Comment by BraveMole** [comment]
> considering how easy it is to weed in tgmc, you're either forcing cas to be a thing and making the game even more defensively oriented for marines, which is pretty silly
> i only added weed native slowdown to the run pr because marines got overall faster as well.

Eh, you're most probably right, i just hate sticky with much passion.

Weeds is to easy to put, i'll try to think of a replacement for sticky one day

**Comment by SplinterGP** [comment]
> 
> 
> > considering how easy it is to weed in tgmc, you're either forcing cas to be a thing and making the game even more defensively oriented for marines, which is pretty silly
> > i only added weed native slowdown to the run pr because marines got overall faster as well.
> 
> Eh, you're most probably right, i just hate sticky with much passion.
> 
> Weeds is to easy to put, i'll try to think of a replacement for sticky one day

i'll think probably make them slow less, make it a harder structure to put and also in less amount.

**Comment by DerrickChamberlain** [comment]
I would take some slower movement and reverted xeno speed on weeds to kill resin that sounds pretty good to me.

**Pull request closed without merging**
