### PR TITLE
Gets rid of the /device item subtype

### PR DESCRIPTION
**Pull request by DominikPanic**
Why?
Because it was just an icon redefinition.
This PR simply mass-replaces those files AND moves all of the icons into the proper place. No functionality changes.

### CODE REVIEW

**Comment by Ghommie** [comment]
Would you be kind enough to also to apply these  changes to the couple maps not located in the map_files folder (if you haven't already)? 
Made exception of the Chigusa Shipyard, they are generally worth maintaining.

**Comment by DominikPanic** [comment]
> 
> 
> Would you be kind enough to also to apply these changes to the couple maps not located in the map_files folder and the whiskey outpost?
> Made exception of the Chigusa Shipyard, they are generally still worth maintaining.

Okay

**Comment by spookydonut** [comment]
why?

**Comment by DominikPanic** [comment]
> 
> 
> why?

```
//electronic devices

/obj/item/device
	icon = 'icons/obj/items/devices.dmi'
```

device.dm

This is why.

**Comment by Rohesie** [comment]
This brings us closer to /tg/ but away from Baystation.
Modern Bay uses /device/

**Comment by DominikPanic** [comment]
> 
> 
> This brings us closer to /tg/ but away from Baystation.
> Modern Bay uses /device/

me likey good /tg/ backend code easy copypastas

**Pull request merged**
