### PR TITLE
one shot gl has rail scopes now

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title

## Why It's Good For The Game
it's cool

## Changelog
:cl:
balance: t-81 is able to use rail scopes
/:cl:

### CODE REVIEW

**Comment by bobmancer343** [comment]
ultimate cadehugging machine

**Comment by TiviPlus** [comment]
Go home mjp you're drunk

**Comment by Tupinambis** [comment]
"It's cool" is not a good reason. Unless it is boonie hats.

**Comment by TiviPlus** [comment]
We both know why im closing this

**Pull request closed without merging**
