### PR TITLE
minigun sprite update

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
by kuro
image
I'd have used his better one but his hard drive exploded or something

## Why It's Good For The Game
better sprite than a years old one and more in style

## Changelog
:cl:
add: Added new minigun obj sprite
del: old minigun obj sprite
/:cl:

### CODE REVIEW

**Comment by InterroLouis** [comment]
Thicc.

**Comment by Tennessee116** [comment]
Barrel looks like an inflatable pool chair.

**Comment by SplinterGP** [comment]
@TheBimmer231 pls

**Review by SplinterGP — APPROVED** [review]

**Comment by Pariah919** [comment]
pr kill until kuro update

**Pull request closed without merging**
