### PR TITLE
insane ravager buff

### PR DESCRIPTION
**Pull request by Technical-l**
## About The Pull Request

gives rav drip
https://cdn.discordapp.com/attachments/1102430518206808105/1253893699226570762/image.png?ex=66778302&is=66763182&hm=4d0c3c645a05156bf3ff1f23261fd336fab5e220c6bec0a4ce0b7d0cf33e9667&

## Why It's Good For The Game

rav got just a weak ass necklace, aint pulling with that shit.

## Changelog

:cl: Joe13413
imageadd: added new rav rouny sprites
imagedel: deleted old rav rouny sprites
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
This makes Ravager too strong tbh

**Comment by Technical-l** [comment]
blaijughjfdikghfjdshgjldsogefdghdfsjngfwdsghiweruhgti2r3tyi82 qwerty

**Comment by novaepee** [comment]
image

**Comment by Araulius** [comment]
BAHAHAHAHA, speed merge NOW

**Review by TiviPlus — APPROVED** [review]

**Comment by breadhunt** [comment]
xeno buffs getting out of hand

**Pull request merged**
