### PR TITLE
Removes maid spawn.

### PR DESCRIPTION
**Pull request by SpaceLoveSs13**
## About The Pull Request

Removes spawn" maid itemspawner. It spawns blindfold, bunny ears and black skirt altogether.

## Why It's Good For The Game

We are a MRP server based on the lore of marines vs xenomorphs. Even with RP events here and there, I don't see a reason to keep these maid outfits especially with bunny ears, blindfold, black skirt that may potentially promote rule 8 violations(erotic, lewd rp). Unlike the bartender loadout which does have a reason sometimes to exist for the sake of RP events.

## Changelog
:cl: SpaceLove
del: Removed Maid outfit spawn command.
admin: Removes Admin ability to spawn maid loadout.
/:cl:

### CODE REVIEW

**Comment by SpaceLoveSs13** [comment]
> Webeddit, insta close
I deserve praise for my hardwork.

**Comment by SpaceLoveSs13** [comment]
Add an admin tag btw please.

**Comment by SplinterGP** [comment]
@lKiseki

**Comment by MerryweatherLost** [comment]
based

**Comment by Ragecrabbo** [comment]
First they take away our survivors and now they want to take our maid outfits

**Comment by SomeDongus** [comment]
Literally 1984

**Comment by EgorDinamit** [comment]
Literally 1984.

**Comment by DenialDuckOfService** [comment]
As the others have said, literally 1984. TGMC needs MORE Femboy appropriate clothing, why take them away? It fits the RP setting. It fits the gameplay.

Massive -1, I don't think you truly understand what you're doing.

**Pull request merged**
