### PR TITLE
Increases the price of SG factory refills

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
Smartgun reqtorio is insanely efficient for how basic SG drums are - each reqtorio refill provides 10 t29 drums or t85 bins for half the price of manually bought drums/bins. With the t62, this is even worse - ~700 points worth of t62 magazines for 250 points (this one is admittedly my fault)

to make things worse, all of the factory parts are available for free within the req vendor, meaning there's no "break-even point" where factory production of SG ammo becomes more efficient than buying it. Reqtorio simply *made sg cheaper*, outright for just a minute of setup.

This PR tones down the efficiency of reqtorio to ~130% (from 200%) for t29&t85 ammo, and 175% (from 280%) for t62 magazines. Still cheaper than just buying it outright, but less so.
## Why It's Good For The Game
2x ammo for sgs dawg 😭 
who merged this shit... 😭 
## Changelog
:cl:
balance: SG-29 reqtorio drum refill 250 -> 350 points
balance: SG-85 reqtorio bin refill 250 -> 350 points
balance: SG-62 reqtorio magazine refill 250 -> 400 points
balance: SG-62 reqtorio ammo bin refill 250 -> 400 points
/:cl:

### CODE REVIEW

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Point increase is maybe too high, i'd make it 350

**Comment by 00ze-cyclone** [comment]
Point increase is maybe too low, I’d make it 550

**Comment by Lumipharon** [comment]
Points increase is maybe too narrow, I'd nerf everything

**Comment by yyzsong** [comment]
> Point increase is maybe too high, i'd make it 350



> Point increase is maybe too low, I’d make it 550



> Points increase is maybe too narrow, I'd nerf everything

im not sure what to believe.

**Comment by TiviPlus** [comment]
I roll for charisma

**Review by TiviPlus — APPROVED** [review]

**Comment by Tonklaatech** [comment]
Point increase maybe to meaningless, i'd remove reqtorio

**Pull request merged**
