### PR TITLE
Adds voicelines to CAS

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

begin mission/fuel/firing fluff and minor code improvements

## Why It's Good For The Game

cool or something

## Changelog
:cl:
add: Added some voicelines to CAS
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
now marine players can be the pilots they always dream to be

**Comment by Nuker555** [comment]
now make it play danger zone

**Comment by FosterGrime-Heymynameslouie** [comment]
ammunition zero!

**Review by ivanmixo — APPROVED** [review]

**Comment by GuyGuysonF19** [comment]
based

**Pull request merged**
