### PR TITLE
Minor sprite, equipment and sound changes

### PR DESCRIPTION
**Pull request by zerosexualpartners**
## About The Pull Request

Minor sound, gun and uniform sprite rework, minor changes in gun modules offsets so now it looks OK then before.

## Why It's Good For The Game

Its more pleasant to play with a little bit of new sounds and well worked gun modules that now sits on the weapon better then before.

## Changelog
:cl:
add: plus one rocket in T-160 crate bundle in vendor, now it comes with scope as well
tweak: tweaked suppressor and extended barrel sprites, tweaked pistols and T-160 sprites
soundadd: old hit sounds on live target changed on better one, suppressor sound changed
/:cl:

### CODE REVIEW

**Comment by Hughgent** [comment]
You've changed a lot of sprites. Would you be so kind as to put together a collage of them?

**Comment by zerosexualpartners** [comment]
> You've changed a lot of sprites. Would you be so kind as to put together a collage of them?

Nothing special actually
image

**Comment by Hughgent** [comment]
Delightful, now how do they look in game?

Specifically the attachment offsets.

**Comment by zerosexualpartners** [comment]
> Delightful, now how do they look in game?
> 
> Specifically the attachment offsets.

Quite correct I shall say, silencer now stands on almost all weapons as if it were threaded, no more gaps per pixel.

**Comment by zerosexualpartners** [comment]
Checked everything on local server, everything works.

**Comment by Pariah919** [comment]
Why does the t-160s rail scope have different zoom stats than the normal miniscope

**Comment by zerosexualpartners** [comment]
> Why does the t-160s rail scope have different zoom stats than the normal miniscope

For better magnification I guess?

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Atomize this

**Pull request closed without merging**
