### PR TITLE
Kuro2.0 gun sprites

### PR DESCRIPTION
**Pull request by Xsdew**
## About The Pull Request

Taking feedback from the previous Gun Re-sprites, Kuro made a second redesign. The AR12, AR18, MG42, P14, SMG90, and SH35 remain the main guns for this spriting.

## Why It's Good For The Game

The goal of the original Re-sprites was to bring uniformity to the design of Marine Standard Weapons. This PR does the same but with a different style all sprited by kuro.

unknown

## Changelog
:cl:

imageadd: Once again changed the Sprites of the AR12, AR18, MG42, P14, SMG90, and SH35. Sprites by Kuro.

/:cl:

### CODE REVIEW

**Comment by Xsdew** [comment]
Once the Checks are complete. I'd recommend Test Merging this PR. That way the Marines can all post their feedback here and can be adjusted as needed all in one PR.

**Review by Kuro020 — APPROVED** [review]

**Comment by Kuro020** [comment]
third time is the charm

**Comment by Serxule** [comment]
they all look the same

**Comment by Xsdew** [comment]
> they all look the same

They have the same color patterns and shading yes. They are all unique designs.

**Comment by Serxule** [comment]
> > they all look the same
> 
> They have the same color patterns and shading yes. They are all unique designs.

if unique means a couple of differences but still mostly indentical then sure.

**Comment by MereWalker** [comment]
Look forward to more sprites.

**Comment by DerpiestBruh** [comment]
Why are we respriting them? They were fine before.

**Comment by Losenis** [comment]
Fucking blessed, no longer is the T12 a bullpup shitshow

**Comment by cazuccmuss** [comment]
curious as to why the t90 kept the old magazine sprite for the ammo boxes when the singular mag sprite got reverted

**Comment by Kuro020** [comment]
> curious as to why the t90 kept the old magazine sprite for the ammo boxes when the singular mag sprite got reverted

we forgot to update it back

**Comment by Al-1ce** [comment]
These look pretty good. The pistol sprite is a little bit big but that's about all I can think of.

**Pull request merged**
