### PR TITLE
Ports CORSAT Research Station

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Ports CORSAT research station from CM. 
Continuing a tradition from the last CM map I ported, I'm going to preemptively answer some questions that I'm sure you'll have.

**Q**. Can we do this?
**A**. This map uses no CM assets but their bench sprites, which are licensed under Creative Commons 3.0 BY-SA so there's nothing stopping us.
**Q**. I want to do *insert CM mechanic here* can I do this on CORSAT?
**A**. This is just the map, specific mechanics may or may not be added based off player feedback.
**Q**. Can I at least ride the monorail?
**A**. Not in CORSAT's current state, it might be added later on.
**Q**. CORSAT is meant for 100 players, can it really fit here?
**A**. CORSAT has already been modified to be quite a bit smaller, regardless, fully expect the size of the map to shrink as the results of playtesting come in.

## Why It's Good For The Game

More maps are always good, and it doesn't hurt to have another one to break up monotony. I received a number of DMs asking for this map, so I think it should be appreciated once its adjusted to TGMC balance standards.

## Changelog
:cl:
add: Added CORSAT Research Station
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: Added some new icons for space station flooring.
imageadd: Ported CM style benches.
imageadd: Ported area icons for CORSAT.
imageadd: Created quite a few new decals.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
image

Holy smokes

**Comment by InterroLouis** [comment]
Massive, an absolute unit.

**Comment by novaepee** [comment]
Since Chaz is gitban,

"There's countless unpredictable dead ends, all the internal space windows are accessible to space, there's free gamer gear EVERYWHERE, LZs are surrounded by unbreakable hull windows/heavy rwalls."

**Comment by Mrrpip** [comment]
Well.

This map is probably more used for high-pops we barely ever get, seeing it was a high-pop CM map.

Along with that, most of the central places either have gamer gear (PMC grenades, landmines, Neurostim implants) or are dead space.

The miners are so spread out that you'd either need hivelord tunnels or to run a marathon.

Lastly, the Eastern Block doesn't have any miners, so you'd have no reason to go there outside of xenos hiving there

Now, I think the main issue is that you're trying to port CORSAT. We're not CM.

You could cut it down and all that...But that wouldn't be CORSAT persay.

CORSAT had teleporters, trams, gamer gear for survivors.

This doesn't feel like CORSAT and it'd be a space station with CORSAT's name if it was cut down because CORSAT's whole schtick was size.

**Comment by ChocolateBickie** [comment]
The southern generators count as outerspace/a vacuum which makes decorrupting them impossible without dying

**Comment by XANAv2** [comment]
Saw a weird looking mants hatch imbedded in a wall around the first bio dome from lz2

**Comment by Lumipharon** [comment]
Corsat seems to crash some byond versions. I was on 514.1557, updating to the latest fixed it. Some other people on other versions seemed to have the same problem.

**Comment by Dueu** [comment]
There is a vacuum zone that causes huge amount of burn damage and suffocation to the left of big dome of the center, specifically the generators room

**Comment by RipGrayson** [comment]
Thank you for coming along on with us on the CORSAT™ experience. This map has a long way to go, but I intend to fix all your problems and trim the map down. **Thank you** for your patience with it.

**Comment by novaepee** [comment]
> You could cut it down and all that...But that wouldn't be CORSAT persay.

It's already cut down. We've cut down CM LV-624 and we still call it LV-624.

**Comment by Mrrpip** [comment]
> > You could cut it down and all that...But that wouldn't be CORSAT persay.
> 
> It's already cut down. We've cut down CM LV-624 and we still call it LV-624.

Mhm, but you have the general structure.

A.E Colony south, caves north with jungle imbetween and Secure dome far to the left.

Same goes for Big Red/Ice

CORSAT, as a space station built around domes....I don't see that one happening without it becoming awkward.

**Comment by AnCopper** [comment]
LagSat here we come.

**Comment by RipGrayson** [comment]
My current mapping workload has become too large, I'm closing this PR down and will bring it back when I have the time to address the size/flow issue.

**Comment by RipGrayson** [comment]
> I'm closing this PR down and will bring it back when I have the time to address the size/flow issue.

I lied, this map can burn in hell.

**Pull request closed without merging**
