### PR TITLE
Synthetic Rank Progression

### PR DESCRIPTION
**Pull request by SpaceLoveSs13**
## About The Pull Request

Gives Synthetics the time progression they should have.

## Why It's Good For The Game
Synthetic is essentially a mini captain that can and should do most shipside job especially when there is a lack of command.
People should be encouraged to play this role as well as it will let others know how much experience that player has.
We have ranks for that very reason. Plus it is my first PR so wanted to start out simple.

## Changelog
:cl: SpaceLove
add: Synthetic ranks added

/:cl:

### CODE REVIEW

**Comment by SpaceLoveSs13** [comment]
Also since this is my first PR, please give me feedback if I have messed up something.

**Comment by Losenis** [comment]
Synth ranks sound nice, but I don't know if having them be hierarchy-based would be good since they're synths rather than full proper marine/navy crew, that also are capable of fitting any lacking job or skill so they'd be swapping roles on the go. Maybe having the rank reference their artificial nature, like GEN1/GEN2/GEN3 to also account for how a later gen (IE player with more hours) would know more than its predecessors.

**Comment by davidchan13** [comment]
Should be Warrant Officer IMO but what evs.

**Comment by SpaceLoveSs13** [comment]
> Synth ranks sound nice, but I don't know if having them be hierarchy-based would be good since they're synths rather than full proper marine/navy crew, that also are capable of fitting any lacking job or skill so they'd be swapping roles on the go. Maybe having the rank reference their artificial nature, like GEN1/GEN2/GEN3 to also account for how a later gen (IE player with more hours) would know more than its predecessors.

That is indeed a good idea, however I want to keep the chat itself neat and small. Adding Gens front of a one word name to me is not as good as adding small contraction of words.

**Comment by Losenis** [comment]
GEN itself would be a contraction of Generation, and it's a 4 character (GEN + Number) rank that there's a good few of already like LCPL, SCPL, SSGT, MSGT, COMM, CMDR, and even a 5 character for max rank SL as GYSGT. Alternatively you can shorten it even more to just be G1/G2/G3

**Comment by grinkgo** [comment]
> GEN itself would be a contraction of Generation, and it's a 4 character (GEN + Number) rank that there's a good few of already like LCPL, SCPL, SSGT, MSGT, COMM, CMDR, and even a 5 character for max rank SL as GYSGT. Alternatively you can shorten it even more to just be G1/G2/G3

I like the idea of using a technological "rank" as opposed to a military-style rank such as First Class or Major, since synths aren't considered part of the chain of command. Alternative to Gen you could designate synths by mark, so Mk1, Mk2, Mk3.

**Comment by SpaceLoveSs13** [comment]
> > GEN itself would be a contraction of Generation, and it's a 4 character (GEN + Number) rank that there's a good few of already like LCPL, SCPL, SSGT, MSGT, COMM, CMDR, and even a 5 character for max rank SL as GYSGT. Alternatively you can shorten it even more to just be G1/G2/G3
> 
> I like the idea of using a technological "rank" as opposed to a military-style rank such as First Class or Major, since synths aren't considered part of the chain of command. Alternative to Gen you could designate synths by mark, so Mk1, Mk2, Mk3.

I think yes, I like the Mk.I,Mk.II,Mk.III than gens. Replaced the CS,MS and SO1. Thanks for the feedback.

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Losenis** [comment]
Still having Mk.I despite having around 70 hours on synth.

**Pull request merged**
