### PR TITLE
Marines start the round with only 1 squad now

### PR DESCRIPTION
**Pull request by breadhunt**
## About The Pull Request

Changes squads from having 4 default squads at roundstart --> 1. The amount of squad leaders is unchanged. Effectively this will mean the round starts with Alpha, Bravo, Charlie or Delta as the default squad and squad leaders can then create custom squads on top of that.

Intention is to have a single squad for the frontline ungaball and custom squads can then be added/opted into as needed. 

image
_Further squads can be added through the SL's Squad Manager console._

This was the original plan like months ago when custom squads were originally being added. If people are very against we can TM and see how it goes but I don't think it'll be an issue, alpha/bravo/charlie/delta is soul but this change does need to be made really & there's no reason people can't just make custom squads for them anyway
## Why It's Good For The Game

 **We are not CM, people are not forced to do [x] duty and so randomly assigning duties doesn't make sense as a result.** Having a single squad is way more intuitive for how TGMC round flow usually goes - most rounds have a singular marine ungaball (i.e one squad) with people opting into extra squad stuff if/when they want to. Having this carry over into squad structure makes more sense in general.

This also provides a couple smaller benefits for command:
- Custom squads are more malleable than roundstart squads. 
- SLs helping with the frontline can send squad orders/announcements across the default squad, rather than pissing in the wind on general radio.
- Currently there can be between 4-8 squads. We do not have the population to support this, so half of them end up as bloat with nowhere near enough SLs to fill in.
- Hopefully greater clarity for plans as specific squads can be mentioned
## Changelog
:cl:
add: Maximum number of starting squads 4 --> 1
/:cl:

### CODE REVIEW

**Comment by Gregormack** [comment]
This is good, it'll help to organize people more efficiently

**Comment by Neocloudy** [comment]
it might be a good idea to remove references to roundstart squads from files like `command_alert` 

(maybe i can make a way for squad announcements in custom squads to be colored like the squad's color in the future)

**Comment by Zangeiti** [comment]
DELTA SQUADDDDDDDDD

**Comment by Woker2004** [comment]
In my honest opinion we have squads so you can do coordination, single squad would just be brain dead in my opinion

**Comment by Zangeiti** [comment]
finally, I can use squad chat to communicate with everyone instead of clogging the common channel

**Comment by Derrick2Electricboogaloo** [comment]
Are you going to rebuff their leadership skill and leadership skill all around now? Having 4 SLs was the reason why the skill itself was nerfed a while ago.

**Comment by gpinrgrmoma** [comment]
> Are you going to rebuff their leadership skill and leadership skill all around now? Having 4 SLs was the reason why the skill itself was nerfed a while ago.

number of SLs is staying the same, the PR says.

**Comment by gpinrgrmoma** [comment]
Are the different starting squads going to be chosen randomly? Code shows only alpha will be chosen, but the screenshot provided shows only delta?

**Comment by breadhunt** [comment]
> it might be a good idea to remove references to roundstart squads from files like `command_alert` and wherever else they may be. i'm not a maintainer though

I'll look into this

> (maybe i can make a way for squad announcements in custom squads to be colored like the squad's color in the future)

I thought they did so by default??



> Are the different starting squads going to be chosen randomly? Code shows only alpha will be chosen, but the screenshot provided shows only delta?

Starting squads are chosen as they are currently; the one with the most people set in prefs to "preferred squad: [x]" is selected. In practice, well, Delta is usually the largest squad, soo..

**Comment by breadhunt** [comment]
> In my honest opinion we have squads so you can do coordination, single squad would just be brain dead in my opinion

I have yet to see someone in the last couple years actually execute teamwork as a squad that couldn't be done just as easily _if not easier_ in a custom squad. TGMC teamwork is opt-in by design, contrary to CM's forced squads.

**Comment by Wisemonster** [comment]
This would be nice, especially considering the default radio for marines atm is the current squad radio, meaning that you won't need to type :h in order to tell the majority of marines some kind of info

**Comment by Naaanii** [comment]
Wouldn't it be better to just let leaders rename their squads?

**Comment by breadhunt** [comment]
> Wouldn't it be better to just let leaders rename their squads?

Doesn't prevent the issue of squads being literally never used unless some random SL decides to

**Comment by carlarctg** [comment]
delta autism is a holdover from cm where delta is the pointman squad, good to see it finally kick the dust here

**Comment by Draggeru** [comment]
This is very meh.

The only reason people are going to be cohesive is if there's a good communicative SL or FC. Not because you compress everyone into a single squad.

>Currently there can be between 4-8 squads. We do not have the population to support this, so half of them end up as bloat with nowhere near enough SLs to fill in.

Also this is a straight up lie, we were hitting pop cap the other day.

If this PR goes through Sulaco MUST be able to create custom squads.

**Comment by breadhunt** [comment]
> This is very meh.
> 
> The only reason people are going to be cohesive is if there's a good communicative SL or FC. Not because you compress everyone into a single squad.

very true; this does however make things more intuitive both for marines and for beginner SLs/FCs on how to get people engaged with squad teamwork

> Also this is a straight up lie, we were hitting pop cap the other day.

4 squads was for CM's 200-250 pop shenanigans, the maximum TGMC can hold before the server fucking implodes is ~120. 

> If this PR goes through Sulaco MUST be able to create custom squads.

@TiviPlus we don't have this????????

**Review by TiviPlus — APPROVED** [review]

**Comment by breadhunt** [comment]
not forgotten, still awaiting TM

**Comment by TiviPlus** [comment]
bleh mb

**Comment by TiviPlus** [comment]
wanted to give squad tts a moment to settle

**Comment by Ldip999** [comment]
May want to add a balance tag, since it means there can are 3 less acting SLs at any time, meaning 3 less people shouting marine pheros.

**Comment by CoastalCookie** [comment]
While this is a cool idea i personally selected charlie so i can be grouped with the general squad community that is charlie (aka grape squad) This basically makes that impossible to occur unless a SL recreates that squad (which never happens cause SL is used as Marine+)

So i feel like this pr would be useful if playing SL actually mattered instead of being Marine+ for now its mostly just a change that mostly just annoys some people

**Comment by breadhunt** [comment]
PSA:
I forgor to remove SL slots scaling with squad numbers (in a PR that sets the number of squads to always be 1)
_This is not intentional,_ if you're seeing nobody do custom squads or anything fun it's probably because there is literally only one SL per round at the minute
Fix has been up for a while, just waiting for re-TM + server to update so that it actually goes through on the server.

> While this is a cool idea i personally selected charlie so i can be grouped with the general squad community that is charlie (aka grape squad) This basically makes that impossible to occur unless a SL recreates that squad (which never happens cause SL is used as Marine+)

I haven't seen any "squad community" outside of a few specific SLs who create one (source: I made grape squad). Identity is difficult to form without an objective; and it's more intuitive to form a custom squad around a specific objective or piece of gear. You might still be right, I want to see what happens after SLs actually exist again though

**Comment by Wisemonster** [comment]
Seems this pr affects the amount of ASLs command can assign, meaning that if there are less than 4 SLs, you can only assign 1 ASL unless each SL make a custom squad

**Comment by Lumipharon** [comment]
stop tm'ing this, its causing issues with SL's because changes haven't been tested

**Comment by breadhunt** [comment]
> Seems this pr affects the amount of ASLs command can assign, meaning that if there are less than 4 SLs, you can only assign 1 ASL unless each SL make a custom squad

Well yes, this is unchanged & probably fine

> Seems this pr affects the amount of ASLs command can assign, meaning that if there are less than 4 SLs, you can only assign 1 ASL unless each SL make a custom squad

why would you have more than one aSL per squad?

**Comment by JackTheJackhammer** [comment]
What would FCDR do in this case then?

**Comment by brisidlif** [comment]
> What would FCDR do in this case then?

FCDR is SL leader, SLs either help FC with the sisyphean task of wrangling marines or go off on their own squads

**Comment by Wisemonster** [comment]
> > Seems this pr affects the amount of ASLs command can assign, meaning that if there are less than 4 SLs, you can only assign 1 ASL unless each SL make a custom squad
> 
> Well yes, this is unchanged & probably fine
> 
> > Seems this pr affects the amount of ASLs command can assign, meaning that if there are less than 4 SLs, you can only assign 1 ASL unless each SL make a custom squad
> 
> why would you have more than one aSL per squad?

You're misunderstanding what I said, it's not that you can only assign one aSL per squad, it's that this pr makes it so there can only be 1 aSL period. Currently on live, there can be up to 1 aSLs per squad, usually meaning up to 4 if no custom squads are made, so that if any squad is missing an SL, they can at least get some benefit from an aSL. This pr is (trying) to keep the 4 SL slots, but due to there only being 1 squad by default, only 1 aSL can be assigned at any given time, unless an SL makes a new squad. But in that case, the new squad will already have the SL of whoever made it, meaning another aSL will only appear after an SL dies.

**Review by Lumipharon — CHANGES_REQUESTED** [review]
Actually, doesn't this cause issues in HvH? You've hard coded 1 squad, you're forcing alpha to be the preferred squad even if that's not your faction

**Comment by breadhunt** [comment]
> Actually, doesn't this cause issues in HvH? You've hard coded 1 squad, you're forcing alpha to be the preferred squad even if that's not your faction

it doesn't force squad, it changes the default number of squads to 1, it only forces alpha if NOBODY has a squad preference
it's also not interfering with hvh squads at all in testing

**Comment by efzapa** [comment]
we love metagang PR on god

no more deltard jokes
no more grape/blueberry squad jokes

you WILL play your custom metagang squad
you will NOT play your preferred squad

we literally live in a society

**Comment by TiviPlus** [comment]
@Lumipharon why is this dnm

**Comment by breadhunt** [comment]
> we love metagang PR on god
> 
> no more deltard jokes no more grape/blueberry squad jokes
> 
> you WILL play your custom metagang squad you will NOT play your preferred squad
> 
> we literally live in a society

My brother in christ you have the tools to make those squads
I sure as hell ain't gonna stop doing grape squads

**Comment by efzapa** [comment]
> > we love metagang PR on god
> > 
> > no more deltard jokes no more grape/blueberry squad jokes
> > 
> > you WILL play your custom metagang squad you will NOT play your preferred squad
> > 
> > we literally live in a society
> 
> My brother in christ you have the tools to make those squads
> I sure as hell ain't gonna stop doing grape squad

the tools being dealing with SL hell

**Comment by breadhunt** [comment]
> the tools being dealing with SL hell 

COWARD
jokes aside I think this is fine, any kind of squad identity other than Delta is scarce without anything going on in the squad anyway

> no reason NOT to have the squads tbh

Fair enough I didn't explain this too well in PR body, but there is. 
We don't have enough SLs to reliably fill four squads. This means that most of the time, when you join a squad, there's not actually an SL (or they're not leading the squad, since many SLs choose to just herd cats at the frontline).
It's better to have fewer squads that (semi-)reliably have _something_ going on than four squads that barely have anything going on is the idea

**Comment by Looking4bros** [comment]
Is co-ordination real? I've never done it. I don't think I've ever stuck with one squad sized group, I've always just flocked around the flanks, W+M1d, and walked towards all the other green crosses.

**Comment by breadhunt** [comment]
> Is co-ordination real? I've never done it. I don't think I've ever stuck with one squad sized group, I've always just flocked around the flanks, W+M1d, and walked towards all the other green crosses.

this is because our current squad structure does not function (alongside a bunch of other unhelpful aspects of current command)

the hope is that after making things as intuitive and helpful for new SLs as possible, the skill floor for SL will be lower and thus more squad-focused stuff will emerge

obviously this is also pending serious objective reworks soon:TM:

**Comment by YehnBeep** [comment]
From a logical standpoint, I understand where this PR is coming from and can't disagree with much of the reasoning...

But personally, I find having all the comms on one squad channel is overwhelming and difficult to keep up with. Even if before it's been "Just support the main push" from SLs (if there even is an SL), having it somewhat sectioned helped keep it manageable, at least for me.

Another thing lost here is... there's less ability to distinguish people you see on the map, or by their hud icon. Calling out say "Alpha smartgunner" or "Charlie corpsman" or "Delta engineer" was a relatively meaningful distinction at least fairly often before, while this makes the blob (even more) amorphous.

And then, lastly, not just anyone can make a squad. Of course you could say "Well go SL if you want to do that" but - I think there is a level of value for the game, socially, if I see someone (or they see me) and we decide to switch over to the same squad to better coordinate a bit. Which - anyone can do without being command in the 4 squad structure.

So I suppose, if this is to stay, I'd at least ask that squads be publicly creatable.

**Comment by novaepee** [comment]
make delta the default squad

**Comment by Lumipharon** [comment]
Kinda dubious on this as a default tbh. People have squad prefs for a reason, and its so easy to swap squads. As Yehn said above, there is value in people being distinguishable, as opposed to a sea of alpha squad everywhere.

**Comment by Lauwma** [comment]
I don't really understand what you need this distinction for though. You rarely have anything to say in a single marine in the middle of a ton of marines. If you want to ask a smartgunner in the middle of the blob to start shooting you probably want all smartgunners to start supressing. If you want to tell corpsman to move on with the push you probably want to tell all corpsman to move on with the push. if you want to tell someone their order is here please do not call them by what they are but call them by their name because most people have an highlight of their name in chat.

**Comment by Looking4bros** [comment]
>  in the middle of the blob 

> highlight of their name in chat.

As someone who fits neither of these parameters, i do see some niceties in having random granularity. As someone (with a random name) who is usually on the flanks with at most two or three other uncoordinated marines with no leadership, a decent amount of my short term memory of them is the color of their squad. As well, if you note someone as competent in the role of Corpsman/Engineer/Smartgunner/Squad Leader the random granularity can be helpful for guessing their location by minimap.

I also feel less inclined in following a SL who's not my current randomly assigned SL. Of which, this PR would muddy my flippant decision to wordlessly follow someone off into a maze.

**Comment by Lumipharon** [comment]
Bread said he was going to kill this pr. Reopen if you change your mind

**Comment by Looking4bros** [comment]
🫡 A good idea to implement if Marines ever actually behave like an organized group.

**Comment by YehnBeep** [comment]
If this does come along again, my request would be the same: Please make squads publicly creatable.

**Pull request closed without merging**
