### PR TITLE
Unmanned vehicles redesign, coming soon 2077

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Aims to redesign UVs to fit current gameplay standards more.
Redesign pending, doc coming soon 2077. Sit tight.

## Why It's Good For The Game
Xenos can do little to deter UVs, and most abilities do not work on them.
That is pretty bad, considering they also go pretty fast.
Must fix.

## Changelog
:cl: Lewdcifer
del: oh god you merged a draft pr what have you done
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
40 points is still a considerable cost for a droid, especially if it is lost early. They are glass cannons not tanks. And die pretty quick if you are not careful.

**Comment by TiviPlus** [comment]
Liguana

**Comment by Al-1ce** [comment]
Points should remain the same, at fourty. The rest of this is fair though.

**Comment by Lumipharon** [comment]
Their mobility is what makes them difficult to deal with. I don't think nerfing their damage/cost is really the right thing to do.
I would just nerf the mobility and see how it settles for a bit.

**Comment by Naaanii** [comment]
Agree with Lumi. Nerf mobility but buff HP slightly rest seems fair considering their DPS and inability to be CCd unless cornered completely.

**Comment by DerpiestBruh** [comment]
You're turning these into noob traps

**Comment by MLGTASTICa** [comment]
I think theyre fine as is, any form of basic mazing counters them .

**Comment by lbnesquik** [comment]
Nerfing damage, speed and price of UV's is a very heavy nerf. Speed is the only thing that really keeps them alive, because they really aren't that sturdy once you start hitting them.

**Comment by BraveMole** [comment]
Liguana

**Comment by BraveMole** [comment]
No but for real this smells like "ided pr". A pr that nerfs everything is a bad pr

**Comment by Kuro020** [comment]
Liguana

**Comment by ivanmixo** [comment]
bravemole moment

**Comment by novaepee** [comment]
Liguana

**Comment by lKiseki** [comment]
Gonna just close this until I finish design.

**Pull request closed without merging**
