### PR TITLE
Don't allow supply beacons on tadpole

### LINKED ISSUE #13039: Req beacons on tad misbehave
### Description

With a beacon placed on tad that's groundside, sending orders there works as normal, but then when the tad goes to the sky and lands elsewhere, sending things to the beacon sends things to the OLD location, not the new one 

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [21246](https://scrubby.melonmesa.com/round/21246)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [037175690c375449937d061d078f3eb9e7606d09](https://github.com/tgstation/TerraGov-Marine-Corps//commit/037175690c375449937d061d078f3eb9e7606d09)
The following pull requests are currently test merged:
[#12892: 'Adds a delay to throwing' by ivanmixo at commit a99898c494](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12892)
[#12990: 'Autocannon rework MK2' by Pariah919 at commit 75d34f1c10](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12990)
[#13004: 'Text to speech' by TiviPlus at commit 03d2a45c79](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13004)
[#13035: 'Fix some pref bugs' by Lumipharon at commit 2aea1551af](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13035)
[#13027: 'Maybe fix radio keys being filtered' by TiviPlus at commit a959345250](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13027)
[#12977: 'Reworks boiler into having to be rooted to fire' by ivanmixo at commit ce93326fe3](https://github.com/tgstation/TerraGov-Marine-Corps//pull/12977)

Local commit: 1aca0dafb7d05c099bb673d6c2a855abbda7d7af
Server tools version: 5.12.1

### Reproduction Steps

1. Go groundside with tad, land anywhere
2. plant beacon on tad that's landed
3. RO sends things to beacon, works as expected
4. Tad moves into the sky, lands elsewhere on ground
5. Sending things to beacon now makes the beacon send to the old location

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by vvvv-vvvv**
## About The Pull Request

Fixes #13039

## Changelog

:cl:
fix: supply beacons can't be planted on tad
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
This isn't really a fix. There's no specific reason a beacon shouldn't work on tad.

**Comment by Strayed-Raven** [comment]
Supply beacon on TAD makes more sense than Alamo. Gonna downvote because this seems very needless

**Comment by isotope436** [comment]
theres no real reason for this to exist even from a balance perspective especially since you can just radio bag or antenna on tad to side step

**Comment by FosterGrime-Heymynameslouie** [comment]
this should be repoened, didnt get to comment here earlier now I found out it was closed
people tend to add beacons in tad then switch postions, not realizing that the things sent to tad beacon will be sent on the previous location instead of the new one

and yeah people can just side step it entirely and all that but if you dont put a railing on a long ass stairway people WILL still fall no matter how much you say to just stay in the sides

this is that railing

**Pull request closed without merging**
