### PR TITLE
Cooldown Fix for Fling and Grapple Toss

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

Fixes the shared cooldown for Grapple Toss and Fling so it works properly.

## Why It's Good For The Game

Fixes the shared cooldown for Grapple Toss and Fling so it works properly.

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/6266

## Changelog
:cl:
fix: Shared cooldown for Grapple Toss and Fling fixed so that using one doesn't cause the other to have an indefinite cooldown.
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
This appears to have very much been intentional justify your changes

**Comment by SplinterGP** [comment]
i remember this was intentional so you could use fling or grapple toss for more range and more controlled ?

**Comment by Surrealaser** [comment]
> This appears to have very much been intentional justify your changes

No.

The way it was supposed to work is that the cooldown is shared, so you can't combo them both in a single go, but that you could use both, just not in tandem; not that you pick one and then you're stuck with it forever.

I thought this is the way it was working; I was shocked to find out that this was not the case.

When I tested prior to merging it worked as intended.

**Comment by SkeletalElite** [comment]
so does this PR get rid of the shared cooldown? Or was there a bug with the shared cooldown that it fixes?

**Comment by Surrealaser** [comment]
> so does this PR get rid of the shared cooldown? Or was there a bug with the shared cooldown that it fixes?

The shared cooldown is an actual shared cooldown as opposed to usage of one perma disabling the other.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
