### PR TITLE
Adds a confirmation to hijacking the alamo, adds a line when you lock the alamo as xeno by clicking the console

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

- The option to hijack the alamo to go shipside now has a yes/no prompt so you don't fat finger it.
- Locking the alamo by clicking the console as a hive ruler now actually gives out a line in chat so you know you actually did it

## Why It's Good For The Game

Mmm how is it not?

## Changelog
:cl:
add: Added a yes/no prompt for hijacking the alamo
add: Hijacking the alamo by clicking the console as a hive ruler now gives out a line in chat so you can be sure you actually did it
/:cl:

### CODE REVIEW

**Comment by InterroLouis** [comment]
salt pr

**Comment by ivanmixo** [comment]
> salt pr

Yesh huggy is stinky thats what prompter this

**Comment by bowlofcereal** [comment]
salt pr but actually alright for once

**Comment by Ragecrabbo** [comment]
> > salt pr
> 
> Yesh huggy is stinky thats what prompted this

thank you, can confirm i havent showered in 20 years

**Pull request merged**
