### PR TITLE
Ports TG Deathsquad sprites

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Ports TG Deathsquad sprites:
image
## Why It's Good For The Game
I'm tired of looking at CM sprites.
## Changelog
:cl:
imageadd: Ports deathsquad sprites from TG
/:cl:

### CODE REVIEW

**Comment by Luxyboo** [comment]
cant say im too fond of them

**Comment by Tommy-211** [comment]
I like it over what we have rn, what we have rn is really bad lmao

**Comment by Xander3359** [comment]
> I like it over what we have rn, what we have rn is really bad lmao

I hate CM sprites. We are still using CM sprites. I'm so tired of looking at CM sprites they are so bad.
If someone wants to give me some proper deathsquad sprites, I would prefer it, but I am no spriter.

**Comment by Tommy-211** [comment]
> > I like it over what we have rn, what we have rn is really bad lmao
> 
> I hate CM sprites. We are still using CM sprites. I'm so tired of looking at CM sprites they are so bad. If someone wants to give me some proper deathsquad sprites, I would prefer it, but I am no spriter.

For once i agree with you

**Comment by Pariah919** [comment]
CM sprites are ugly but at least they look more in style than TG

**Comment by Kuro020** [comment]
Surely a xander pr wont break anything

**Pull request merged**
