### PR TITLE
Fixes T2 and T3 Hive Status Limit Calcs

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

Per title.

## Why It's Good For The Game

Fixes the Hive Status Limit calculations so they have full precision.

## Changelog
:cl:
fix:  Hive Status T2 and T3 limit calculations fixed.
/:cl:

### CODE REVIEW

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Please provide explanations for your changes

**Comment by Surrealaser** [comment]
> Please provide explanations for your changes

The old calc wasn't working with full precision, this does.

It's been more rigorously tested.

**Comment by TiviPlus** [comment]
I dont know what more precision means please explain the difference from before and after this PR and why you think this change is necessary

**Comment by Surrealaser** [comment]
@TiviPlus It corrects some niche inaccuracies in the displayed number

**Review by TiviPlus — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
