### PR TITLE
Miners give less points

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Or well ore boxes.

Phoron has been havled.
Plat lost 10 points.

## Why It's Good For The Game
Ore miners after the advent of the tadpole and miner upgrades give too many points too fast, this seems like a better compromise than nerfing the miners themselves.

## Changelog
:cl:
balance: ore miners nerfed to 10 for phoron and 30 for plat
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -199. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by BraveMole** [comment]
Please atomize

**Review by SplinterGP — APPROVED** [review]
i like it, after balance freeze we can do this while reducing sentry cost probably, need to make marines take more miners instead of just camping one.

**Comment by Pariah919** [comment]
no point to bothering

**Pull request closed without merging**
