### PR TITLE
Canteens added to utility in marine vender

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Canteens added to utility. Has water, for loadouts.

## Why It's Good For The Game
I want to have a loadout with a canteen in my helmet.

## Changelog
:cl:
tweak: Canteens are now in marine venders in the utility tab.
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
The canteen is already in the food vendor though.

**Comment by Al-1ce** [comment]
> The canteen is already in the food vendor though.

Things from the food vendor typically don't save in loadouts. I've never had an issue with saving canteens in any of mine though, so I don't really get the point of this PR either.

**Comment by Lumipharon** [comment]
You literally can't play the game without having to walk past the food vendor, and it does save to loadouts. MJP pls

**Comment by Arctrooper8** [comment]
> You literally can't play the game without having to walk past the food vendor, and it does save to loadouts. MJP pls

It's so sad to see Alzheimer's take our greatest contributors from us.

**Comment by Lumipharon** [comment]
click food vendor 5head

**Comment by Derrick2Electricboogaloo** [comment]
Loadout vendors take from food vendors. I have never had a problem with them.

**Pull request closed without merging**
