### PR TITLE
Revert "Salvage dead xenos is gone (#6366)"

### PR DESCRIPTION
**Pull request by BraveMole**
This reverts commit 9cb7b564fcc2f11ac7d962aa12f6e59a4f8b3468.

## About The Pull Request

Put back salvage xeno ability

## Why It's Good For The Game

Was a mistake. Marines gets enough points from miner, they don't really need that extra amount of points. 
And xenos were not always managing to snatch back bodies, so it was actually interresting 

## Changelog
:cl:
balance: Put back salvage dead xeno ability
/:cl:

### CODE REVIEW

**Comment by EvilMelonTheSecond** [comment]
Marines don't get enough points from miners. Miner output got nerfed to shit, the only way to get points is to set up stealth miners that are completely unprotected, give no indication when they get attacked and die to a single slash from any xeno.

Non-stealth miners are rarely protected and almost always phoron miners that give like 7.5 points per minute I believe. Passive point generation at orbit 5 gives more. This PR will likely fix nothing, marine req point generation needs a rework not random a nerf/buff every week.

**Comment by BraveMole** [comment]
> Marines don't get enough points from miners. Miner output got nerfed to shit, the only way to get points is to set up stealth miners that are completely unprotected, give no indication when they get attacked and die to a single slash from any xeno.
> 
> Non-stealth miners are rarely protected and almost always phoron miners that give like 7.5 points per minute I believe. Passive point generation at orbit 5 gives more. This PR will likely fix nothing, marine req point generation needs a rework not random a nerf/buff every week.

I've seen a lot of sg and sadar spam as soon as 13:00, that's why this PR is here? They don't seem to have a problem with points, for real

**Comment by EvilMelonTheSecond** [comment]
> 
> 
> > Marines don't get enough points from miners. Miner output got nerfed to shit, the only way to get points is to set up stealth miners that are completely unprotected, give no indication when they get attacked and die to a single slash from any xeno.
> > Non-stealth miners are rarely protected and almost always phoron miners that give like 7.5 points per minute I believe. Passive point generation at orbit 5 gives more. This PR will likely fix nothing, marine req point generation needs a rework not random a nerf/buff every week.
> 
> I've seen a lot of sg and sadar spam as soon as 13:00, that's why this PR is here? They don't seem to have a problem with points, for real

Like I said, that's only because engineers do stealth drops and repair/automate plat miners. I'm not too sure about the exact numbers with passive point generation myself but I've seen many times where marines are completely out of points when they only get closest miners to FOB(Only 1 phoron miner most of the time)

Spamming anything is really hard at 13:00 if marines haven't done stealth miners. And when they get like 4+ plat miners on giant maps they get more points than they can spend. I don't have enough data to suggest a fix to numbers but I don't think bringing back salvage will change anything about it.

**Comment by BraveMole** [comment]
> > > Marines don't get enough points from miners. Miner output got nerfed to shit, the only way to get points is to set up stealth miners that are completely unprotected, give no indication when they get attacked and die to a single slash from any xeno.
> > > Non-stealth miners are rarely protected and almost always phoron miners that give like 7.5 points per minute I believe. Passive point generation at orbit 5 gives more. This PR will likely fix nothing, marine req point generation needs a rework not random a nerf/buff every week.
> > 
> > 
> > I've seen a lot of sg and sadar spam as soon as 13:00, that's why this PR is here? They don't seem to have a problem with points, for real
> 
> Like I said, that's only because engineers do stealth drops and repair/automate plat miners. I'm not too sure about the exact numbers with passive point generation myself but I've seen many times where marines are completely out of points when they only get closest miners to FOB(Only 1 phoron miner most of the time)
> 
> Spamming anything is really hard at 13:00 if marines haven't done stealth miners. And when they get like 4+ plat miners on giant maps they get more points than they can spend. I don't have enough data to suggest a fix to numbers but I don't think bringing back salvage will change anything about it.

Hum, not bad arguments. Let's say this PR is on pause until more time has passed

**Pull request closed without merging**
