### PR TITLE
TGS Arachne

### PR DESCRIPTION
**Pull request by AzonStarfall**
## About The Pull Request

Adds the TGS Arachne, a rework/replacement for the TGS Minerva.

TGS_Arachne

Following the extensive tour of duty of the Minerva, Nanotrasen has finally lobbied TerraGov to return their premier research vessel. In exchange, Nanotrasen offers a lease agreement for the Arachne, her sister ship.

With consideration to her original designation as a military research craft, a lesser degree of retrofitting was required in order to get the Arachne into working order with the rest of the TerraGov Navy; as the ship was designed following notes from standard military blueprints, originally intended as an element of corporate security.

This PR serves as a rework and replacement for the TGS Minerva. As such, this PR disables the Minerva in config for the time being, until a final decision can be made on removal. This has been discussed and approved with the mapping director.

## Why It's Good For The Game

The Minerva has had a number of mapping inefficiencies that, for the past two years, have harmed playability. While addressing these on a point-by-point basis is possible, the symmetrical-design nature of the Minerva makes this exponentially more difficult as time goes on. Starting from scratch with a reworked model will resolve many of these issues, such as excessive prep transit routes, strange spacing between primary command areas, and others.

## Changelog

:cl:
add: Added the TGS Arachne, a replacement for the TGS Minerva
config: Added the TGS Arachne in config
config: Disabled the TGS Minerva in config
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Finally, Minerva but no longer coneless.
Perfect.

**Comment by RipGrayson** [comment]
You did a good job on this, here's some minor problems.

The status displays here should be on the wall, not hanging in midair

The AI nodes need to connect here, there's no way for the AI to go from the north node to the one west

AI should really have a single instance of its shutter lockdown button within the core area itself


Finally, CIC, SD and AI core all need /obj/machinery/power/apc/mainship/hardened, not /obj/machinery/power/apc/mainship.
This is because unlike all the other APCs these areas need to retain power after the xenos crash their ship into the Arachne.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
You did a good job on this, here's some minor problems.

The status displays here should be on the wall, not hanging in midair

The AI nodes need to connect here, there's no way for the AI to go from the north node to the one west

AI should really have a single instance of its shutter lockdown button within the core area itself


Finally, CIC, SD and AI core all need /obj/machinery/power/apc/mainship/hardened, not /obj/machinery/power/apc/mainship.
This is because unlike all the other APCs these areas need to retain power after the xenos crash their ship into the Arachne.

**Comment by AnotherNobodie** [comment]
THERES NO BOOZE DESPENSER, HOW AM I SUPPOSED TO DRINK THE PAIN AWAY WORST MAP -10/10. SHIT MAP111!1!1!1!!!!1!11111!!!111!

**Comment by Otterwatch** [comment]
The OB room has Security Airlocks that Ship Tech does not have access to, meaning you have to break in or hack to load OB.

**Comment by AnotherNobodie** [comment]
image

**Comment by KerbalCitizen** [comment]
Seems like there are no ship engineer lockers, which afaik all other ship maps have a few of. I looked around to find one to get mesons but didn't manage to find one.

**Comment by Wisemonster** [comment]
I've noticed in the AI core, that having the shutters off is kinda weird? With a couple doors not being affected by the button at all, and the north and south entrance doors to the room itself (where the drones are) are not blocked by the fire alarm when it's activated (I only know this cause the lockdown button also does not block the entrances to said room, unlike another map like Pillar of Spring. I do not know if this is intentional).

TerraGov Marine Corps 9_9_2023 6_30_01 PM

**Comment by ivanmixo** [comment]
Loadout vendor near the alamo would be cool so I don't have to add it myself later.

**Comment by AzonStarfall** [comment]
> Vendors near the alamo would be cool so I don't have to add it myself later.

Specifically the vendors nearby that POS has, limited to Loadout, Weapons, Armor, Clothing, and both Engineering types?

**Comment by AzonStarfall** [comment]
> I've noticed in the AI core, that having the shutters off is kinda weird?

This is a bug, yeah. Fixed the shutter IDs, it should be resolved.

**Comment by verywhiterabit** [comment]
I'm hearing the map might be missing the corporate liason's vendor briefcase.

**Comment by Xander3359** [comment]
Recycler doesn't work

**Pull request merged**
