### PR TITLE
Limits the amount of a single T3 caste to 3

### PR DESCRIPTION
**Pull request by ClosetedSkeletonGH**
## About The Pull Request

Limits the amount of a single T3 caste to 3

EX; a maximum of 3 warlocks, a max of 3 boilers, a max of 3 gorgers/

Say there are 9 T3 slots open, a possible mix could be
3 ravs
3 boilers
3 warlocks

## Why It's Good For The Game

Most balance issues when it comes to T3's are necessarily the classes themselves, but when there are 3 or more of a single caste that can just continually spam their abilities because they can cover eachother while on cooldown.

You can see this in rounds where there have been 5-6 boilers, (or even 3-4), or when there are 3 or more warlocks. Obviously the CD's and whatever arent balanced for there being 4-6 of a single T3.

Salt PR active

## Changelog

:cl:
balance: limits the amount of a single T3 caste to 3
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
This is some omega cope which presumes one team is not allowed to actually form a strategy, and the other team is incapable of counter play.

**Comment by breadhunt** [comment]
Someone didn't take the mimir modules I dragged to the front on last night's 5 boiler Chigusa round...

**Comment by Coastfront** [comment]
The wonders of a bird calling one cast in chains a failure for the inability to fly.

Marines can bring, a functionally unlimited amount, of basically every combination of weapon in the game. 
5 billion shotguns with buckshot, 40 mimirs, 50 tyr, as long as it isnt req or resting in the ever exclusive palm of limited stock roundstart weapons, marines can bring an infinite amount of them.

Not only this, unlike xenos. Marines can actively change their equipment, near instantly.

Marines spamming shotguns? If most of the hive went cqc castes get fucked because now if you want to actually reliably counter them either they have to fucking devolve, which iirc does fuck with maturity progress, or B. wait until somebody else can evolve.

Xenos spamming boilers? literally ask the RO to vent like 18 mimir and send it down in a box and marines can now literally instantly change what their armor is weakest to.

But forbid, that an ever feeble vind dares to writhe and twist up this frozen pole to meet the sunlight, for only our ever metamorphosing worm may hold the key to progress.

If this gets merged when are we capping the amount of every roundstart gun to 5? If xenos are going to find insufferable weight along their ankles its only fair their chain connects to the wrist of their counterpart.

**Comment by Losenis** [comment]
If marines are getting BTFO'd by 5 boilers, I doubt they'd get BTFO'd any less by 2 of those boilers going hivelord to maze the marines in and give the 3 boilers an even easier time to peek out of mazes and retreat into a sea of acid wells should any marine rush forwar, or going rav to eviscerate any rusher that will have to run out of the cloud and therefore lack any cover due to the LoS block.

**Pull request closed without merging**
