### PR TITLE
Makes binary :n so it won't conflict with bravo

### PR DESCRIPTION
**Pull request by DominikPanic**
Bravos are allowed to exist once again

### CODE REVIEW

**Comment by san7890** [comment]
Isn't the ":n" key used for science? This'll really mess things up for the AI and Cyborgs. Try to find another key to use.

**Comment by DominikPanic** [comment]
> 
> 
> Isn't the ":n" key used for science? This'll really mess things up for the AI and Cyborgs. Try to find another key to use.

We don't have science here, this is TGMC.

**Comment by san7890** [comment]
> > Isn't the ":n" key used for science? This'll really mess things up for the AI and Cyborgs. Try to find another key to use.
> 
> We don't have science here, this is TGMC.

Oh I see, I just barely saw it be merged in game, and all I saw was "PR: [tgstation/TerraGov-Marine-Corps] Pull Request merged by Rohesie: #1884 DominikPanic - Makes binary :n so it won't conflict with bravo". I got confused. Sorry!

**Comment by DominikPanic** [comment]
All good! ^^

**Pull request merged**
