### PR TITLE
Plasma pistol now has ammo packet

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

The TX-7 Plasma Pistol now has an ammo packet! It contains at least 40 plasma bolt worth. It can be nerfed to less if needed, but other ammo packets often have 4 times the mag size. You can find it in the Weapon Vendor's boxes tab.

Used sprites from TG Station's sheater. funny

Also, had to add flags_magazine so that plasma pistol cell doesn't produce handful. Got Hyper to help me while giving him a brain aneurysm in the process. Sorry, Hyper, for giving you a brain aneurysm.

## Why It's Good For The Game

Other weapons have it including pistols, so TX-7 Plasma Pistol deserves it.

## Changelog
:cl:
add: The TX-7 Plasma Pistol now has an ammo packet! It contains at least 40 plasma bolt worth. You can find it in the Weapon Vendor's boxes tab.
imageadd: The energy case of ionized plasma, the plasma pistol's ammo packet, uses sprites from TG Station's sheater. Just look very carefully.
code: Add MAGAZINE_NO_HANDFULS with a huge help from Hyper; sorry, Hyper, for making you suffer
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
https://user-images.githubusercontent.com/6610922/150629446-6ac253d5-7e56-47f6-a8a3-60df2f86bdc5.mp4

fancy sci-fi ammo packet

**Comment by novaepee** [comment]
ooo it has animation
image

**Comment by bowlofcereal** [comment]
There's already an infinite amount you can get from the weapons vendor, so I don't see how this would hurt to add in

**Comment by novaepee** [comment]
Bravemole said no. Hyper also think that this is creep.

**Pull request closed without merging**
