### PR TITLE
xeno turrets take far more damage from heavy explosions and have 100 less overall health

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
turrets take far more damage from heavy explosions, as generally these are things as rockets, and other high explosive armament that marines don't get much access to so I don't see the issue in making it damage them heavily
turrets have 100 less overall health

## Why It's Good For The Game
Turrets are surprisingly strong against heavy explosions overall and this would make them more suspectible to them in general, which would give them another soft counter other than flaming them or using a smoke grenade
turrets also have a bit too much health so shaving off a hundred doesn't seem to bad for me, as it makes them a bit more susceptible to small arms fire.

## Changelog
:cl:
balance: xeno turrets take far more damage from heavy explosions, and have 100 less overall health and start with 100 less health
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
For the record, i though rockets and cas were all explosion_devastate, so this is what it should have been at the start

**Review by SplinterGP — APPROVED** [review]

**Comment by GradusNL** [comment]
Why the health nerf? Making xeno turrets take the appropriate amount of damage from rockets is logical, but you throw in a health nerf too. Your reasoning for the health nerf is also very poor, "turrets also have a bit too much health"? Why do they have too much health? "it makes them a bit more susceptible to small arms fire", why do turrets need to more susceptible to small arms fire? They are already easy to kill with small arms fire, marines regularly tank the turrets and kill it anyways.

An earlier PR to nerf turrets by upping the cost #7543 was closed by @TiviPlus because "turrets are easy enugh to deal with, and currently there is too much rushing xenos, as they have no turrets, and too much focus on king since its a better bang for your buck than a turret will be". I don't see how any recent PR's change this reasoning and I am including the king mob damage nerf.

To me it seems you are trying to push an illogical and unexplained health nerf into a PR primarily aimed at fixing the explosion damage. I would tell you to atomize it if it were up to me. I'll probably make a PR to revert the health nerf if this gets merged.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
I dont like this

**Comment by SplinterGP** [comment]
> Why the health nerf? Making xeno turrets take the appropriate amount of damage from rockets is logical, but you throw in a health nerf too. Your reasoning for the health nerf is also very poor, "_turrets also have a bit too much health_"? Why do they have too much health? "_it makes them a bit more susceptible to small arms fire_", why do turrets need to more susceptible to small arms fire? They are already easy to kill with small arms fire, marines regularly tank the turrets and kill it anyways.
> 
> An earlier PR to nerf turrets by upping the cost #7543 was closed by @TiviPlus because "_turrets are easy enugh to deal with, and currently there is too much rushing xenos, as they have no turrets, and too much focus on king since its a better bang for your buck than a turret will be_". I don't see how any recent PR's change this reasoning and I am including the king mob damage nerf.
> 
> To me it seems you are trying to push an illogical and unexplained health nerf into a PR primarily aimed at fixing the explosion damage. I would tell you to atomize it if it were up to me. I'll probably make a PR to revert the health nerf if this gets merged.

Turrets are not easily killable by guns in any way, unless when theyre deployed because they take time to get to full health, no marine in the world can facetank and kill it, it is also not killable with a whole t12 magazine.

**Comment by David-Stormwell** [comment]
> 
> 
> I dont like this

It's only 100 less health, it isn't much for something which may have up to 1400 max health.
Additionally, if marines use RRs or otherwise+ then that's them using up a rocket. 
It isn't too bad of a nerf, and if you already have Xenos placing turrets in open spaces it'll die either way.

**Review by David-Stormwell — APPROVED** [review]
As per above

**Comment by GradusNL** [comment]
> Turrets are not easily killable by guns in any way, unless when theyre deployed because they take time to get to full health, no marine in the world can facetank and kill it, it is also not killable with a whole t12 magazine.

Marines are should never alone, so your example of 1 marine facetanking it alone should never happen. It's always multiple marines focusing the turret down with small arms fire so they get away with facetanking it and the combined small arms fire kills turret easily, not to mention you can just snipe it from offscreen alone. I'm not sure why you focus on it taking more than 1 T-12 magazine, why should it be killable with one mag? If a turret would be that easy to kill they would be even more obsolete then they are now.

Marines can deal with most xeno turrets without specialized equipment (i.e. using their guns) by sniping/combined fire and only have to use equipment they ALL have access to (nades, flamer or plasma pistol) IF a turret is very well placed. If they accept some damage they can just facetank well placed turrets too. This is why xeno turrets are easy to deal with for marines. Marines being braindead and just facetanking them alone is a skill issue, not a balance issue.

> It's only 100 less health, it isn't much for something which may have up to 1400 max health.
Why nerf it then? It either matters or it doesn't. A nerf like this is death by a thousand cuts. Upping the price here, lowering health there. You know what happens? You nerf something into obsoleteness. Turrets already never get used except as silo early warning system, nerfing them further isn't going to change any of that. All it does is make them even more obsolete, if such a thing is even possible.

**Comment by SplinterGP** [comment]
@GradusNL Sniping is a sorta specialization, everyone takes mag harness for the utility it gives, theyre not easily breakable like that other than standing still.

**Comment by lbnesquik** [comment]
I think the core of the PR is good. If there is too much pushback, remove the health changes.

**Comment by GradusNL** [comment]
> 
> 
> @GradusNL Sniping is a sorta specialization, everyone takes mag harness for the utility it gives, theyre not easily breakable like that other than standing still.

I agree that sniping xeno's requires trading the mag harness for a scope and counts as a specialization, but since turrets are static objects you don't need a scope to snipe them. You just spot the turret, walk offscreen before it starts firing and shoot it from there. Because the turret doesn't move you can just fire in it's direction from offscreen and kill it. So turret sniping doesn't require specialized equipment either.

**Comment by jroinc** [comment]
Seems reasonable. Hell, I'd be fine with dropping it's health to 1000, if you add on 10 bullet hardarmor.

**Comment by GradusNL** [comment]
> 
> 
> Seems reasonable. Hell, I'd be fine with dropping it's health to 1000, if you add on 10 bullet hardarmor.

Why does it seem reasonable? Lowering the health by such a huge amount means that xeno turrets are going to be even less useful and more obsolete. Explain to me why turrets need a health nerf.

**Comment by TiviPlus** [comment]
> > I dont like this
> 
> It's only 100 less health, it isn't much for something which may have up to 1400 max health.
> Additionally, if marines use RRs or otherwise+ then that's them using up a rocket.
> It isn't too bad of a nerf, and if you already have Xenos placing turrets in open spaces it'll die either way.

Turrets are currently a waste of points and there is zero reason to nerf them even more, epecially when we already have an issue with marines rushing every round

**Comment by TiviPlus** [comment]
as above

**Pull request closed without merging**
