### PR TITLE
boiler light gets reset properly on being ahealed

### LINKED ISSUE #3333: Ahealing a boiler makes its light go out
## Reproduction:
Aheal a boiler and watch as its light goes out

### PR DESCRIPTION
**Pull request by terranaut1**
## About The Pull Request

Fixes #3333 

## Why It's Good For The Game

bugs bad

## Changelog
:cl:Terranaut
fix: fixed boilers going dark when ahealed
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
This gets called a lot.
When does it stop emitting light?

**Comment by Hughgent** [comment]
if this gets merged, it will mess with my current boiler rework.

**Comment by Rohesie** [comment]
There's that.

**Comment by terranaut1** [comment]
better fix and and doesnt mess with #3329 anymore

**Comment by terranaut1** [comment]
nevermind fuck git hold on

**Pull request closed without merging**
