### PR TITLE
Fire Support Changes

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
changes a few prices of cas stuff so their worth it to invest in

## Why It's Good For The Game
reduced hv ammo travel time because it only did 1 second off for 2 x the points of normal 30mm, delete landing zone detector because it was useless, increased dropship points received from req dropship point voucher from 100 to 150 so its more worth it for ro to invest in, decreased laser battery price to 85 somewhat nearing 30mm price also increasing the laser gun price to 600 to compensate, decreased fatty price to 150 because its pretty expensive for what it does which is clearing a tiny bit of resin walls

## Changelog
:cl:
balance: reduced hv 30mm ammo travel time to 3 seconds
delete: removed landing zone detector
balance: increased dropship points received from voucher to 150
balance: laser beam gun price increased to 600
balance: laser battery price reduced to 85
balance: fatty rocket price decreased to 150
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Powercreeping firesupport here, other than fatty which is terribly post change.

**Comment by Losenis** [comment]
Powercreeping CAS is balanced by itself because half the time it hits marines instead of xenos anyway

**Comment by Pariah919** [comment]
railgun should just be its own ammo type, gonna be real here

**Comment by tyeagg** [comment]
> railgun should just be its own ammo type, gonna be real here

it is it just uses minirocket for stats

**Comment by FosterGrime-Heymynameslouie** [comment]
floodlights being placed on tadpole is a long time coming thank you for making it happen
can you perhaps also decrease tangle price from 150 to 100 or 125.

**Comment by tyeagg** [comment]
personally i think tangle is already very opressive towards xenos and i dont really wanna make that more spammable

**Review by TiviPlus — CHANGES_REQUESTED** [review]
This needs to be atomized

**Review by Pariah919 — APPROVED** [review]
Flipflopping on HV GAU buff, but this seems okay overall to give a spin or merge and change later.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
