### PR TITLE
Better keybind registering system

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Better system to register keybinds, more intiutive

## Changelog
:cl:
qol: Better keybind registering system
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
explain pls

**Comment by BraveMole** [comment]
> explain pls

It waits for the first push of key, then it will register every key that was ever pressed 0.2 sec later. 

So you don't need to hold, and in practice this feels exactly like a keybind register for most games

**Comment by SplinterGP** [comment]
> 
> 
> > explain pls
> 
> It waits for the first push of key, then it will register every key that was ever pressed 0.2 sec later.
> 
> So you don't need to hold, and in practice this feels exactly like a keybind register for most games

did you try also doing the thing i said about waiting till its pushed up ?

**Comment by BraveMole** [comment]
> > > explain pls
> > 
> > 
> > It waits for the first push of key, then it will register every key that was ever pressed 0.2 sec later.
> > So you don't need to hold, and in practice this feels exactly like a keybind register for most games
> 
> did you try also doing the thing i said about waiting till its pushed up ?

Harder to code, i'll try if this got complaints.

This new system has barely any change, so easy to do

**Comment by SplinterGP** [comment]
> 
> 
> > > > explain pls
> > > 
> > > 
> > > It waits for the first push of key, then it will register every key that was ever pressed 0.2 sec later.
> > > So you don't need to hold, and in practice this feels exactly like a keybind register for most games
> > 
> > 
> > did you try also doing the thing i said about waiting till its pushed up ?
> 
> Harder to code, i'll try if this got complaints.
> 
> This new system has barely any change, so easy to do

ye i'll get it in, just wanted to know

**Review by SplinterGP — APPROVED** [review]

**Pull request merged**
