### PR TITLE
Revert "Add support for right click human actions"

### PR DESCRIPTION
**Pull request by Pariah919**
Reverts tgstation/TerraGov-Marine-Corps#6069

### CODE REVIEW

**Comment by Walarks** [comment]
Why?

**Comment by SpaceLoveSs13** [comment]
Why?

**Comment by SplinterGP** [comment]
It bugged annd broke unique action

**Comment by SplinterGP** [comment]
supposedly fixed on https://github.com/tgstation/TerraGov-Marine-Corps/pull/6385

**Pull request closed without merging**
