### PR TITLE
Sidearm size increase.

### PR DESCRIPTION
**Pull request by David-Stormwell**
## About The Pull Request

As the title suggests, all normal pistols and revolvers now have had a size increase by one.
They may no longer be put into backpacks or satchels, subject to change.
Also on another note this PR unshitcodes shoulder holsters and normalizes them into something akin to webbing.
If needed later on and the balance isn't accepted, I'll still re-code the webbing so it'll be unshitcode. 

## Why It's Good For The Game

To be fair, I don't know if it is or not, I have a feeling this PR will make quite a few people angry at me and even myself, using sidearms almost always inside my own loadout satches. 
but it's a general fix to pistol/revolver spam and may make it easier to balance in the end.

## Changelog
:cl:
balance: Size increase for all pistol types by 1, now allowing only pouches/belts designed to hold said weapon.
refactor: Refactored shoulder holster code to be a child of normal webbing
/:cl:

### CODE REVIEW

**Comment by Dolth** [comment]
Good.

**Comment by AnCopper** [comment]
I have a problem with this PR.
Pistols are Side-Arms, how do you expect people to carry Side-Arms if they can't store it anywhere?

**Comment by Georgeur** [comment]
Copper how about the belts MADE FOR THEM, or the pouches MADE FOR THEM, or the exosuit slot MADE FOR ALL WEAPONS. 
Pistol spam is a crutch for people who cant combat reload. Made even worse by the fact its actually optimal. 
Pistols are partly balanced by having a low mag size. 
The tp14 wouldnt be balanced if it had a mag size of 483, but it basically does have a 483 size mag if you press q and then e. 
Source: me, a tp14 user

**Comment by ilikesaying** [comment]
imagine not abusing pistol lace and tactical/instant reloads

**Comment by Georgeur** [comment]
lace is being nerfed in a separate pr

**Comment by SilencedMP5A5** [comment]
finally, they have killed me

it's over

**Comment by neohenry** [comment]
So can't spam pistols in G8 pouch?

**Comment by David-Stormwell** [comment]
> So can't spam pistols in G8 pouch?

Yes, they no longer fit right now.

**Comment by AnCopper** [comment]
> Copper how about the belts MADE FOR THEM, or the pouches MADE FOR THEM, or the exosuit slot MADE FOR ALL WEAPONS.
> Pistol spam is a crutch for people who cant combat reload. Made even worse by the fact its actually optimal.
> Pistols are partly balanced by having a low mag size.
> The tp14 wouldnt be balanced if it had a mag size of 483, but it basically does have a 483 size mag if you press q and then e.
> Source: me, a tp14 user

Putting it into a Belt or a Pouch compromises your ability to carry other gear. the answer is to nerf the TP-14 if it's really that good in that case, not make Sidearms require you to either carry way less ammo or way less meds.

**Comment by lKiseki** [comment]
While I understand why some people would oppose this, I personally believe this is a much needed change. It denies some of the more crazy stuff, like multiple sidearms in backpacks/satchels. There's still options to carry one, like sidearm pouches or the belts made for them, and they're quite viable I'd say.

**Comment by Georgeur** [comment]
> > Copper how about the belts MADE FOR THEM, or the pouches MADE FOR THEM, or the exosuit slot MADE FOR ALL WEAPONS.
> > Pistol spam is a crutch for people who cant combat reload. Made even worse by the fact its actually optimal.
> > Pistols are partly balanced by having a low mag size.
> > The tp14 wouldnt be balanced if it had a mag size of 483, but it basically does have a 483 size mag if you press q and then e.
> > Source: me, a tp14 user
> 
> Putting it into a Belt or a Pouch compromises your ability to carry other gear. the answer is to nerf the TP-14 if it's really that good in that case, not make Sidearms require you to either carry way less ammo or way less meds.

Yes. That's what inventory management is called. 
The comparison between ammo and meds is moot. Neither of these are particularly effected, if you wanna carry more ammo carry less guns, that's true before and after this pr, if you wanna carry more meds, just use the corpsman webbing or a single medkit pouch and you can fit an entire medkit on you. 

TP14 doesn't really need a nerf, some people haven't cottoned onto the fact that past 5 tiles it only deals 75% effective damage, minus the 2 sunder. 
Funnily enough no one has actually noticed the TP23 deals higher dps, and is less effected by the damage falloff kek.

**Comment by SplinterGP** [comment]
generally i feel like just nerfing the TP-14 sunder should do a big difference in that, + that pocket pistol will fit just fine still.

**Comment by Georgeur** [comment]
> generally i feel like just nerfing the TP-14 sunder should do a big difference in that, + that pocket pistol will fit just fine still.

pocket pistol isnt being touched
its a child of the pistol type but changes its item size from its inherent size

**Comment by David-Stormwell** [comment]
fix map e

**Comment by Alterist** [comment]
Map diff is failing because the old holster still exist on some maps, you need to load them up and get update their type paths

**Comment by David-Stormwell** [comment]
Ae, pressed wrong button.
Or hm.
I don't think Tivi will accept it anyways, and I don't feel like wasting time on a argument.
I'll PR the refactor in a little.

**Comment by DerrickChamberlain** [comment]
I swear I am the only one who carried ONE pistol in my backpack as a backup with some spare mags. It was pretty good by it's self. Now soon I will not be allowed to, sad days.

**Comment by Georgeur** [comment]
blame it on the guys who carried round 20 of them, just use a pouch I guess

**Pull request closed without merging**
