### PR TITLE
Larva, health, plasma, etc hud minor resprite

### PR DESCRIPTION
**Pull request by Blundir**
## About The Pull Request

Adds shading to xenohealth, plasma, leader stars, maturity ranks, etc
dreamseeker_FkrmPDOeFg

Partially ports more golden looking active pheromone/marine buff layer
dreamseeker_dBpSasFPZA
dreamseeker_MF0GSEjNHM

Ports larva hud from cm, mainly from these prs [[1]](https://github.com/cmss13-devs/cmss13/pull/2510) [[2]](https://github.com/cmss13-devs/cmss13/pull/1612) , which eliminates duplicates from growth icon stages.

Before:

dreammaker_l6NA8ILtj0

After:

dreammaker_8KIen816Ni

dreamseeker_qijkNwVZNv

Also i did the same to the carrier buffed growth icons

dreammaker_AaIRhWCcYc

## Why It's Good For The Game

Better looking in general, new larva hud provides more information about the exact larva growth stage 

## Changelog

:cl:
imageadd: resprited xenohealth, plasma, leader star, active phero/buff status, larva huds
/:cl:

### CODE REVIEW

**Comment by Blundir** [comment]
Ugh.... why exactly did it fail?...

**Comment by Xander3359** [comment]
> Ugh.... why exactly the check failed?...

I think something about the check broke, it's failing in my PR too

**Comment by Ultimate-Fluff** [comment]
I did not give you permission to take my sprite edits and merge them with your PR. Ask, first, please. I also edited the leader star to be more detailed and actual-star shaped. 
star
I also made a recent sprite edit to the larva HUD, so yours is outdated.

**Comment by Blundir** [comment]
> I did not give you permission to take my sprite edits and merge them with your PR. Ask, first, please. I also edited the leader star to be more detailed and actual-star shaped. star I also made a recent sprite edit to the larva HUD, so yours is outdated. In addition, you changing the position of the leader star will cause it to collide with the banished and the queen vision HUD icon states, so you need to move it back to its original position, or one pixel to the right from its original position so it at least does not collide with the Prime HUD state.

Sorry for not notifying you, didn't think of it as a big deal, since we are all open source, and i did the mentioning, my bad if it troubled you. About the positions, i didn't change any positions whatsoever, tgmc has different placement for various hud elements, also banishment as a mechanic is non existent whatsoever.

**Review by Kuro020 — APPROVED** [review]

**Comment by ivanmixo** [comment]
Just push an empty commit to re-run, tgui just failed fnr.

**Comment by Xander3359** [comment]
Check failed because of this PR https://github.com/tgstation/TerraGov-Marine-Corps/pull/12101 . Just pull master again

**Pull request merged**
