### PR TITLE
Deletes the entire tgmc codebase and replaces it with Blackstone

### PR DESCRIPTION
**Pull request by Clay500z**
## About The Pull Request
tgmc has fallen, this is what it needs. Blackstone.

## Why It's Good For The Game
We can TM this to just play Blackstone for a few days. This will lure the Blackstoners back to tgmc, reviving it.

## Changelog

:cl:
add: Blackstone
del: tgmc
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
pray that spooky doesn't git mute you

**Comment by Naaanii** [comment]
Where's the replacement?

image

**Comment by Alexeivichi** [comment]
Finally the revival of tgmc

**Comment by Clay500z** [comment]
Aight I cooked. It actually adds Blackstone now.

**Comment by FosterGrime-Heymynameslouie** [comment]
speedmerhg NOW

**Pull request closed without merging**
