### PR TITLE
Removes hunter games

### PR DESCRIPTION
**Pull request by MoXuT0**
## About The Pull Request

Per title.

## Changelog

:cl:
del: Removed hunter games.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
What is the purpose of this?

**Comment by MoXuT0** [comment]
Dead game mode whose only purpose is to pollute maps with retarded landmarks. It’s not working due to it counting one additional person on alive humans list, landmarks with random loot don’t produce anything, maps are not made for it. If there would be battle royale mode, it should have unique map/mode. But for right now it’s dead weight that doesn’t gets used at all, lowpop mode is already in works.

**Comment by Rohesie** [comment]
Oh well, looks like I'm outnumbered here.

**Comment by DominikPanic** [comment]
:owl: :gun:

**Pull request merged**
