### PR TITLE
Revert "Revert "Revert "Revert "Revert "deletes cat ears"""""

### PR DESCRIPTION
**Pull request by SpaceLoveSs13**
Reverts tgstation/TerraGov-Marine-Corps#5918

We need it back. @TiviPlus @SplinterGP @TheBimmer231 

Please.

### CODE REVIEW

**Comment by joookschad** [comment]
close asap

**Comment by SpaceLoveSs13** [comment]
> 
> 
> close asap

This is a serious PR.

**Comment by joookschad** [comment]
we literally do not need this back, it was only spawned for people who wanted to larp as cats on a tdm server

**Comment by David-Stormwell** [comment]
brimmer, the one person you don't wanna @mention...
Unless you can bribe him...

**Comment by SpaceLoveSs13** [comment]
> 
> 
> brimmer, the one person you don't wanna @mention...
> Unless you can bribe him...

It would auto review him anyway. Might as well ~~butter~~ convince him.

**Comment by Tennessee116** [comment]
This PR is heavily redundant. This code still contains the Tajaran species, which, within itself, is, as @joookschad said, "people who wanted to larp as cats on a tdm server".

If you want your nyauwunuzzlefurball catastrophe, just set the species of your target to Tajaran. They even _come_ with (built-in) cat ears.

**Comment by BraveMole** [comment]
This should be atomised

**Comment by SplinterGP** [comment]
Sorry but this is a no from me and bimmer, if you REALLY and REALLY want catears go ask spookydonut

**Comment by TiviPlus** [comment]
1984

**Pull request closed without merging**
