### PR TITLE
nerf TAT scope on ATR-22 mounted flak gun, AT-36 anti tank gun, and AGLS-37 Kauser automatic grenade launcher to slightly less than mini scope

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

image

miniscope
image

image

Supreme Leader Kurt's orders

image

"We're removing offscreen gameplay since its uninteractive and heavily stacked for marines, mounted weapons are also culprits of off screening tho less so than the other stuff that is getting a nerf, since boiler is having his range reduced I don't think mounted weapons need mini scope range anymore"

## Changelog

:cl:
balance: nerf TAT scope on ATR-22 mounted flak gun, AT-36 anti tank gun, and AGLS-37 Kauser automatic grenade launcher to slightly less than mini scope
/:cl:

### CODE REVIEW

**Comment by SimplySmiley123** [comment]
Then remake these to not be FF machines *without* those scopes pretty please.

**Comment by Pariah919** [comment]
why would you remove it from these? they're all unwieldly as hell mounted weapons for a reason.

**Comment by chizzy376** [comment]
Snipers aka "offscreens" aren't the problem. It's the lack of a sunder dmg drop off. You merge this and the skill ceiling for both teams will lower for no good reason. Heavy ided vibes and a bad solution to a whole different problem. Don't merge this lol.

**Comment by 74delta** [comment]
Kill off screen for everything but shit that makes sense for it to have it* 

They all have aimmode/iff make sure it's kept post scope removal

Bare minimum I think they need miniscopes though as emplacements.

**Comment by novaepee** [comment]
Supreme Leader Kurt is merciful. He allowed TAT scope to be nerf to be less than mini scope.

The Heaven Protects Supreme Leader Kurt.
image

**Comment by TChalkman** [comment]
Walls are a thing.
Explosion radius and overall friendly fire, is a thing.
Long ass timers just to anchor the gun and look through the scope, is a thing. 
Depending on marines and/or tad to cover you so a hunter/runner doesnt disintegrate you while wielding your gun, or when trying to go from point A to B, is a thing
boilers shooting nonstop where you are so you cannot fire, since they outrange you, is a thing
abilities like queen screech and king screen dropping you off of your gun and having to ride and aim it again, is a thing

holding down bases like FOB or TAD is not as possible anymore, specially since you cant build cades inside TAD now. 
If you have to shoot something like an at36 with barely any scope range, you might as well just park it infront of a xeno and shoot them in the face (oh right, you cant even do that because even for anchoring you got a timer)

This will make stationary machineguns and artillery unplayable. Holding a point with these weapons will be impossible, you will be bullied by any xeno with a range ability, and you won't even get to shoot for 80% of the time because you are *just* out of range. Also since you need cover, your gun range is likely going to be right where marines WILL BE, so anything you shoot is gonna hit them instead.
You don't get the privilege of being immune to stuns, or moving around while ready to fire, or even turning your gun around with certain guns. Thats only for tanks, mechs and APCs

If you really want to turn them this useless, just delete them from the game lol

**Comment by iforgotmeword** [comment]
won't this going destroy all of weapons?
I get removing scope is a universal.
but uh you can't shoot pass xenos meaning any xeno can just kind of body block?
and without HEAVY nerfs to the ammo
it's more likely then not going be just grief to use the weapons

**Comment by Araulius** [comment]
I don't think heavy emplacements such as the flak88 and the AT gun should be getting this treatment. the rest is "eh"

**Comment by Kuro020** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/16038

**Pull request closed without merging**
