### PR TITLE
Crawling

### PR DESCRIPTION
**Pull request by Rohesie**
## Changelog
:cl:
add: Crawling.
/:cl:

### CODE REVIEW

**Comment by spookydonut** [comment]
pics or it didnt happen

**Comment by spookydonut** [comment]
Still waiting on pictures of how this looks @Rohesie

**Comment by Rohesie** [comment]
Pictures of what? *eyebrow
Crawling happens with the mob's face looking north or south.
When the mob is otherwise laying down without mobility, the face is looking to the ground or "up".

**Comment by spookydonut** [comment]
> 
> 
> Pictures of what? *eyebrow
> Crawling happens with the mob's face looking north or south.
> When the mob is otherwise lying down without mobility, the face is looking to the ground or "up".

@Rohesie pictures of crawling north/south? maybe a gif? maybe like any of what you just commented in the PR body?

**Comment by Rohesie** [comment]
https://i.imgur.com/rg1lakQ.gifv

**Comment by spookydonut** [comment]
It might be better if you rotated them by like 20degrees while they're crawling

**Comment by Rohesie** [comment]
I tried that. It didn't look great, and it also rotates the icons such as squad role HUD and health HUD, distorting them a little.
Do try it locally and you'll see what I mean.

**Comment by Rohesie** [comment]
This is not stale, this is fully functional.

**Comment by David-Stormwell** [comment]
This still needs quite some balancing, also someone mentioned un-stunable Xenos such as a Deifler can be put into rest if applied with a stun.

**Comment by Rohesie** [comment]
Defilers were never unstunnable. They weren't made as big xenos, instead they were made as vent-crawling frontliner T3s.

That said, tell me exactly which balance changes to make and I'll do them.

**Comment by TiviPlus** [comment]
Some bugs I saw: 
Resisting makes you have to get up again from rest state, even after the resisting animation is done
Sometimes when I rest for too long my stalk/run seems to set itself to stalk (?)
Marines can crawl out of grabs

**Comment by spookydonut** [comment]
> 
> 
> Some bugs I saw:
> Resisting makes you have to get up again from rest state, even after the resisting animation is done
> Sometimes when I rest for too long my stalk/run seems to set itself to stalk (?)
> Marines can crawl out of grabs

@Rohesie

**Comment by TiviPlus** [comment]
2 More marine bugs:
-Scopes only work to the left and right when crawling
-It seems that when getting stunned and/or crawling when fireman carrying you lose the "pull" inhand object meaning that yo can no longer drop the person on your own

**Comment by spookydonut** [comment]
> 
> 
> 2 More marine bugs:
> -Scopes only work to the left and right when crawling
> -It seems that when getting stunned and/or crawling when fireman carrying you lose the "pull" inhand object meaning that yo can no longer drop the person on your own

@Rohesie

**Comment by Rohesie** [comment]
> Resisting makes you have to get up again from rest state, even after the resisting animation is done

Sorry, what resist animation? As xeno or human? Could you give a way to reproduce this?

> Sometimes when I rest for too long my stalk/run seems to set itself to stalk (?)

Need a way to reproduce this.

> Marines can crawl out of grabs

Grabs were a bit broken, should hopefully be fixed now.

> -Scopes only work to the left and right when crawling
> -It seems that when getting stunned and/or crawling when fireman carrying you lose the "pull" inhand object meaning that yo can no longer drop the person on your own

I'll need to check these out.


Made the following changes on the last commit:
* If a xeno disarms a prone human, the human gets stunned. Should help with marines crawling to shotgun xenos while avoiding pounces, as it will make them otherwise vulnerable.
* Crusher (and Bull) ramming, crest tossing and stomping stun times halved.
* Runner pounce cooldown doubled.
* Warrior lunge is now optional, depending on if you have the ability selected or not. If you don't, warrior grabs things as any other xeno would. If it is then it always tries to neckgrab valid targets on grab actions, and doesn't even try when on cooldown. Furthermore, lunge can be used as a pounce, and if a valid target blocks your path you'll neckgrab them instead. Shields block these lunge-pounces, though, and can stun the xeno.

**Comment by Rohesie** [comment]
Someone else may continue this if they want.

**Pull request closed without merging**
