### PR TITLE
The End of Jaeger MK.II

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Fully removes Jaeger, any mention of it from the code and most items associated with it. most backend stuff is untouched outside of deletion of bloat stuff that's now unused like visors, chestpieces and other stuff. Some of it is renamed, most of the descriptions have been purged of it.
## Why It's Good For The Game
Our artstyle is an utter mess, and I believe starting by removing Jaeger is a good start since it'll let us consolidate, we have way too many colors running around and shrinking down to Xenonauten is a good start.
People want to make new stuff and hyperscale is a pain to do it in, removing Jaeger for now to add spots for new items in the future and expanding Xenonauten and perhaps a new armor set is the preferable way to go than to keep ourselves in an unteneable position with the horror that is using hyperscale.
## Changelog
:cl:
del: Removed Jaeger, most items associated with it such as the bodysuit, and any mentions of it in the code.
/:cl:

### CODE REVIEW

**Comment by MiniMeatwad** [comment]
vox a pox

**Comment by Zambie-Tron** [comment]
I dont like this so it should be removed (inspired by this PR's logic)
 
image

**Comment by lKiseki** [comment]
So let me get this right...
- You remove a crucial part of loadout customization by removing Jaeger entirely. The only choices in armor that you're leaving behind is xenonauten's map variants, flak jackets, and the armored trenchcoats, most of which offer little to no customization.
- You add no form of replacement for Jaeger and all of the customization it offered, instead forcing players to use either of the options mentioned above with the lack of customization that entails.
- When Kuro's plans were prompted in the Discord server's #artwork channel, the following was mentioned, and I quote with screenshots:
image
image
image
- The above is not necessarily wrong, but I'm sure many players would appreciate having something immediate in return when prompted with such an important removal.
- You do not take the playerbase's opinion or feelings into account *at all*. Everything is done purely on approximately two people's whims.

Before you proceed with the removal of Jaeger, I would suggest that Kuro enacts their plans. Once Kuro has some form of finished product with which to replace Jaeger, *then* you could definitely do it. It'd lessen the impact of what you're trying to do.

**Comment by Strayed-Raven** [comment]
keep the helmets

**Comment by Losenis** [comment]
>You remove a crucial part of loadout customization

You have no drip here
image

>You do not take the playerbase's opinion or feelings into account at all. Everything is done purely on approximately two people's whims.

Welcome to github

**Comment by FIXTHERADBOXPLEASE** [comment]
This PR is right and just.

**Comment by Al-1ce** [comment]
ultimately this is better for our style
keep the undersuit though its drippy

**Comment by Tailiik** [comment]
What if you add something in place of it at the same time instead of just removing it? Tons of people use it, straight up removing it without adding anything in place is stinky

**Comment by LeAntek** [comment]
Good PR 
Speedmerge

**Comment by Starfirejordan** [comment]
Make the replacement for xenonaught and jaeger if you intent to replace them

**Comment by Kuro020** [comment]
> Make the replacement for Xenonaught and jaeger if you intend to replace them
> 
> _[community requested changes]_

Its already being sprited

**Comment by TiviPlus** [comment]
https://discord.com/channels/498569646014857217/500801682058379265/1060248695431499786

**Comment by KerbalCitizen** [comment]
Jaeger allows you do some very specific niche things that xenonauten cannot. Light chestplate only (no leg or arm pieces), is often paired with arrowhead for best armor/ survivability to speed ratio. In the past before Rownin, Jaeger exoskeleton was the only way to run modules for no slowdown. Completely removing an (albeit niche) playstyle unintentionally is something I'm strongly against. 

In terms of drip, I'm pretty neutral. Some combinations of Jaeger look good, others not so much. 

Removing Jaeger and the undersuit does mean a lot of people will have to remake their loadouts, which is annoying to do for 10+ loadouts, especially if you don't remember the exact contents for all of them. When the duplicate tgmc uniform PR got merged, it seems no one cared to fix it though, so maybe this doesn't really matter to maints or people who can code.

**Pull request closed without merging**
