### PR TITLE
Russian Red is no longer commonly accessible

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
- Removes Russian Red pill bottles and packets from most vendors (including the Tadpole med vendor) except Valhalla's.
- Russian Red storage options have been replaced in first aid kits where appropriate.
- Reduced the amount of Russian Red autoinjectors in normal vendors from 30 to 10.

## Why It's Good For The Game
Russian Red is admittedly fine, just needs to be made more limited so that everyone and their mother can't have the chem.

## Changelog
:cl: Lewdcifer
balance: Removed Russian Red pill bottles and packets from most vendors (including the Tadpole med vendor) except Valhalla's.
balance: Russian Red storage options have been replaced in first aid kits where appropriate.
balance: Reduced the amount of Russian Red autoinjectors in normal vendors from 30 to 10.
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
Why must you nerf every single place where RR is in a single balance PR that will obviously raise a fuss when you could've just as easily changed one that would've had the most impact? (such as the vendor)

Also reducing the amount of RR per injector is just plain bad alongside all the other changes.

**Review by Lumipharon — APPROVED** [review]
some of these firstaid kits are kinda ??? looking at em now, but someone else can worry about that I guess.

**Comment by Xander3359** [comment]
> some of these firstaid kits are kinda ??? looking at em now, but someone else can worry about that I guess.

Yeah the first-aid kits were always dogshit. The only place they are useful is on CM because they fit inside backpacks, but here they don't fit anywhere so they're always bad.

**Comment by Barnet2** [comment]
You can get your personal RR injectors in the GHMME anyway, good change. Way, way too much RR just out in the wild.

**Comment by coldironwarrior** [comment]
dont like the injector amount reduction, other two changes seem good

**Comment by chizzy376** [comment]
Atomize changes pls

**Comment by Xander3359** [comment]
> Atomize changes pls

Lumi already approved it, it's fine as it is.

**Comment by chizzy376** [comment]
> > Atomize changes pls
> 
> Lumi already approved it, it's fine as it is.

no i just dont like 66% of the pr

**Comment by Sirsnek15** [comment]
Reduced the amount of Russian Red autoinjectors in normal vendors from 30 to 10.
You literally have no idea what this does do you?
Russian red auto injectors have 20 units of RR and 10 units of oxycodone. All other changes are supportable, messing with injector in addition is just plain awful. Reconsider.

**Comment by Xander3359** [comment]
> Reduced the amount of Russian Red autoinjectors in normal vendors from 30 to 10. You literally have no idea what this does do you?

If you re-read the PR instead of foaming at the mouth, you will realize that the RR injectors still contain the same amount.
What changed was the supply of RR injectors in the marine med was reduced from 30 separate injectors, to 10 separate injectors.

**Comment by srxtreme** [comment]
shit change. this is borderline complete removal. the other PR is more than enough

**Comment by lKiseki** [comment]
> I'd rather just have its healing amount scaled down by the amount of cloneloss you have, this is a bit much

I personally believe Russian Red's healing is fine, and even if you were to change it, you'd still have to deal with how commonly available the chemical is if it is meant to keep its strength to some degree. I am willing to change numbers within the context of this PR and its intentions, if that's fine with you.

Additionally, I would _really_ appreciate it if you and Lumi sat down and talked about what you two want. I've been at this for at least four to five PRs now -- both of you have completely different opinions and I honestly cannot satisfy both of you without going insane.

**Comment by Tommy-211** [comment]
#14170
Why are you still trying, this is your 4rth pr trying to fuck over red russian.

**Comment by Tommy-211** [comment]
> > Reduced the amount of Russian Red autoinjectors in normal vendors from 30 to 10. You literally have no idea what this does do you?
> 
> If you re-read the PR instead of foaming at the mouth, you will realize that the RR injectors still contain the same amount. What changed was the supply of RR injectors in the marine med was reduced from 30 separate injectors, to 10 separate injectors.

Meatride alert

**Comment by Lumipharon** [comment]
I prefer this to the other pr but eh, other one is merged so we'll see how RR lands for a bit.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
