### PR TITLE
Removes the LZ 2 Phoron Miner on Prison

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Removes the phoron miner thats literally almost inside of LZ 2.

image

Image is how it looks after the change

## Why It's Good For The Game

Imagine actually needing to push out to earn req points?

## Changelog
:cl:
del: Removes LZ 2 phoron miner on Prison.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by spookydonut** [comment]
@Isy232 Please use proper sentences and PR titles.

We have the map diff bot, you don't need to include screenshots.

**Comment by Isy232** [comment]
Oh, I didn't know about the map diff bot.

And sure, I'll stop using meme language and actually use english for PR names.

**Comment by Isy232** [comment]
Fuck wrong button I meant to press comment

**Review by Hughgent — APPROVED** [review]

**Pull request merged**
