### PR TITLE
Converts REM to a reagent var

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request
Converts REM to a reagent var so that reagent effects containing it can have their strength increased/decreased. Changed calculations to reflect REM being 1 instead of 0.5.

## Why It's Good For The Game
Going through chem code is less confusing since REM is 1 by default.

## Changelog
:cl:Slotbot
tweak: changed REM to a reagent var, changed related calculations in code, added REM to some calculations
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -18. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by fernandos13** [comment]
cannot wait to make 2 new drugs
fast metabolism drug
double the rate chems are consumed and the effects while it goes "bad and good ones"
slow metabolism drug
slow the rate chems are consumed etc etc

if mixed create toxin cause f you. just kidding it purges each other

**Comment by spookydonut** [comment]
REM is a relative value lol.

**Comment by Walarks** [comment]
> REM is a relative value lol.

From what I see, REM is always 0.5 because REAGENTS_METABOLISM is always 0.2. Is its value changed at one point that I am missing? Or do you mean to change REM to 1 and adjust the related calculations?

**Comment by Walarks** [comment]
Changed rem's value to 1 and tweaked calculations that relied on REM being 0.5.

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-18). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
