### PR TITLE
fixes mr-25b2 sprites

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title

## Why It's Good For The Game
free gdp

## Changelog
:cl:
fix: fixed mr-25 having broken things sprites
/:cl:

### CODE REVIEW

**Comment by Hughgent** [comment]
Show me it works

**Comment by Pariah919** [comment]
https://streamable.com/z5i3yl

**Comment by Hughgent** [comment]
Looks like the south facing sprite is holding it in the wrong hand.

**Comment by XSlayer300** [comment]
I fixed it on #5044

**Comment by XSlayer300** [comment]
... *scream

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
