### PR TITLE
Motion detector sounds are no longer local

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
What it says on the tin. Motion sensor pings used to be audible to anyone near the user, but was made local when it changed to a weapon attachment.

I unno if it needs to be quieter though.
## Why It's Good For The Game
MD being useful for team mates (and letting hostiles know they're getting tracked) is good.
## Changelog
:cl:
balance: Motion sensor pings can be heard by other mobs up to 7 tiles away
/:cl:

### CODE REVIEW

**Comment by Luxyboo** [comment]
PLEASE NO I DONT WANT TO HEAR ALL THE NOISES IN THE ALAMO!!

**Comment by Losenis** [comment]
I thought the noise only happened on detecting a xeno

**Comment by Al-1ce** [comment]
I can't imagine this being anything but annoying.

**Comment by BraveMole** [comment]
I removed because it was annoying as hell

**Comment by lbnesquik** [comment]
Is there a preference toggle for that thing?

**Pull request merged**
