### PR TITLE
Incendiary Slugs Now Pierce Mobs

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
Incendiary slugs now pierce mobs (pierce mult of 0.75).  Slowdown removed.

## Why It's Good For The Game
I want to ensure everyone, marines AND xenos suffer. One person should not be subject to the intense pain that is being lit ablaze and dealt medium-high damage. No. Everyone in the shooters wake should feel this pain. The ammo would also be a sufficient enough answer to the great equalizer known as "surround that motherfucker and keep him DOWN" (otherwise known as ganking or stunlocking).

## Changelog
:cl:
balance: Incendiary slugs now pierce mobs (75% pierce multiplier), leaving a trail of fire in its wake. 
balance: Removes slowdown from incendiary slugs (I would be lying if I said I was high when I added that)
/:cl:

### CODE REVIEW

**Comment by KrabSpider** [comment]
Removing the stagger, knockback, and slow.

**Comment by Lumipharon** [comment]
That's a spicy meatball
Also I don't think it does due to how projectile code works, but it would be funny if the knockback caused recurring hits on the same mob.

**Comment by Luxyboo** [comment]
" Incendiary slugs now pierce mobs, leaving a trail of fire in its wake." flamer but with a lot of impact damage

**Comment by ilikesaying** [comment]
>I want to ensure everyone, marines AND xenos suffer. One person should not be subject to the intense pain that is being lit ablaze and dealt medium-high damage. No. Everyone in the shooters wake should feel this pain.

Chaotic Evil

**Comment by Andrewhedge** [comment]
evil man making evil pr

**Comment by Lumipharon** [comment]
Add the on_pierce_multiplier var to the ammo if you're gonna make it pierce, otherwise it's just full damage all the way.

Also slugs piercing anything seems uh, odd.

**Comment by TiviPlus** [comment]
david say no

**Pull request closed without merging**
