### PR TITLE
adds milk dispenser and breaks FC balance forever

### PR DESCRIPTION
**Pull request by MsSeraph**
## About The Pull Request

LITERALLY BREAKS MARINE BALANCE GIVING THEM A !!!CLEAR!!! EDGE OVER THE XENOS AS THEY CAN NOW USE !!!!!!!!MILK!!!!!!!!! FOR ITS MANY COMBAT USES
MAKES THE FC OP BY GIVING THEM EASY TO ACCESS MILK, LITERALLY UNPLAYABLE

## Why It's Good For The Game

In all honesty, milk was unacquireable shipside, and some people like coffee with milk, so it adds some RP and makes a miscellaneous item accessable

## Changelog
:cl:
add: Added milk dispenser
/:cl:

### CODE REVIEW

**Comment by ondrej008** [comment]
milk dispenser

**Comment by ilikesaying** [comment]
FC milk

**Comment by MsSeraph** [comment]
yes ondrej, your observation is correct
ilikesaying, i *assure* you its cow milk

**Comment by Swagile** [comment]
i am disgusted that i know where that pfp comes from

therefore i have downvoted your PR and remove 10 social credits from your social credit score

**Comment by MsSeraph** [comment]
Look man, it used to be a meme where im from, ask Monster860

**Comment by monster860** [comment]
I disagree, it wasn't really much of a meme

**Comment by MsSeraph** [comment]
shut up u nerd u don't even exist

**Comment by Swagile** [comment]
image

image

image

**Comment by MsSeraph** [comment]
Its not lewd! I just want milk to be obtainable shipside

**Comment by optimumtact** [comment]
Milk truk has arrived

**Comment by Kuro-ai** [comment]
orange man good?

**Comment by David-Stormwell** [comment]
orange man is orange

**Comment by MsSeraph** [comment]
Orange man based
I hope this stays

**Comment by TiviPlus** [comment]
Lmao

**Pull request merged**
