### PR TITLE
Introduces the snack tin.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Introduces an alternative to the MRE. It's functionally the same as an MRE but the sprites are much more enjoyable.
Examples:
image
image
image
image

## Why It's Good For The Game
Introduces more food items to add variety.
Balance-wise, it has 24 nutriment, split over 4 food items, so it's purely just an MRE with different sprites (And this tin doesnt crumple like an MRE)
## Changelog
:cl: @Xander3359 @MysteryMan21333
add: Snack Tin, an alternative option to MREs
imageadd: Snack tin and all the food sprites that go with it.
/:cl:

### CODE REVIEW

**Comment by AviiCinders** [comment]
Common Xander win

**Comment by FosterGrime-Heymynameslouie** [comment]
Godbless mysteryman and his sprites and the absolute blast that is watching everyone suggest the most wacky snacks and him spriting it in under 2 seconds

**Comment by Kuro020** [comment]
Everything in a red square either has no outline or has poor shading or both and need work
ff6cbdd8-5ee5-46e8-bf15-63e90649be70

**Review by Kuro020 — CHANGES_REQUESTED** [review]
also the xeno snacks are very meme and either should be locked behind fun mode or removed

**Comment by dopamiin0** [comment]
>doesnt crumple like the MRE

when will the powercreep end. marine food storage reusability has become ridiculously overpowered now. xenomorphs will never be able to recover from this change

fr tho this is super cool and i love all the new little foods. cant wait to trade a galactic brownie for a tricord twink-e with a pfc while sitting at disk.

**Comment by metalyc** [comment]
Bento 👀

**Comment by XElectricX** [comment]
Adorable sprites no matter what Kuro says, speed merge.

**Comment by Al-1ce** [comment]
Restricting these to an admin/mentor fun verb would be pretty lame. Also these sprites are very similar to almost all of the food currently in circulation, so I don't see a problem at all there.
+1

**Comment by Kuro020** [comment]
> Adorable sprites no matter what Kuro says, speed merge.

🤓

**Comment by Al-1ce** [comment]
> 🤓 

Shut up retard.

**Comment by Al-1ce** [comment]
> 🤓 

Shut up retard.

**Pull request closed without merging**
