### PR TITLE
Adds oxy pills, acquirable through vendor

### PR DESCRIPTION
**Pull request by 567Turtle**
## About The Pull Request

the ringing of the ping commands me

## Why It's Good For The Game

You can get oxycodone, you can make it into pills. Cuts out the middle man and makes it so you dont have to look at the shitty custom pill bottle sprite.

## Changelog
:cl:
add: oxycodone pill bottles
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Basado

**Comment by KerbalCitizen** [comment]
> so you dont have to look at the shitty custom pill bottle sprite.

Green facepaint from armor vendor. I like painting it black then white. Blue and pink if its for byoo.

**Comment by Joe13413** [comment]
> > so you dont have to look at the shitty custom pill bottle sprite.
> 
> Green facepaint from armor vendor. I like painting it black then white. Blue and pink if its for byoo.

are you kidding me you can recolor pill bottles? that is based as hell thank you

**Comment by Lumipharon** [comment]
Super painkillers don't need to be easier to powergame

**Comment by 567Turtle** [comment]
> Super painkillers don't need to be easier to powergame

alright, I'll be removing oxycodone injectors from the vendors as well, you'll now only be able to get oxycodone from chemistry 👍

**Comment by Redrover1760** [comment]
> Super painkillers don't need to be easier to powergame

What is your problem

**Comment by Strayed-Raven** [comment]
> Super painkillers don't need to be easier to powergame

absolutely kek

**Comment by Al-1ce** [comment]
> Super painkillers don't need to be easier to powergame

What are you smoking? It's already **THIS** easy. All this PR does is take out the middleman.

**Comment by Losenis** [comment]
C*ders try not to say powegame for 2 minutes challenge (impossible)

**Comment by Joe13413** [comment]
> C*ders try not to say powegame for 2 minutes challenge (impossible)

ciders

**Pull request closed without merging**
