### PR TITLE
Exploding barrels

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
I wish for immersive gameplay.
Everyone knows that red barrels are explosive and are found on every street corner and strategic chokepoint.

Fixes this gross, unimerssive oversight.

Red barrels now behave like fuel tanks (they're just a cylinder instead of a box), with all that entails.

## Why It's Good For The Game
More environmental explosions are cool.

## Changelog

:cl:
balance: All red barrels have been filled with fuel, and can be interacted with like normal fueltanks
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
me and my private buddy giggling as we set up a cunning ambush in our explosive barrel fort

**Comment by Losenis** [comment]
Me on my way to step out of fob to find xenos dragged every barrel in the map to the shutters

**Comment by Lumipharon** [comment]
> Me on my way to step out of fob to find xenos dragged every barrel in the map to the shutters

To clarify, it's only red barrels, not all.

**Comment by Ragecrabbo** [comment]
Barrels of Fun

**Comment by RipGrayson** [comment]
I see no issues that could possibly result from this PR, let's put it on TM

**Pull request merged**
