### PR TITLE
update xeno UI

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

At 50% of a xeno's health or plasma, the UI changes color and blink.

For hivelord, a bit different. See video.

https://user-images.githubusercontent.com/6610922/162275055-770f8efa-286c-4a75-a478-114368e02d0a.mp4

## Why It's Good For The Game

Marine's UI, assuming healthhud, changes colors and has blinking, so why not give that to xenomorphs. The sprites are from CM; I ported from them and modifed for our purposes.

## Changelog
:cl:
add: At 50% of a xeno's health or plasma, the UI changes color and blink.
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
Not exactly related (per-se) but the health globule/circle UI can be wildly inaccurate with the limited intervals its sprite has.

**Comment by Arctrooper8** [comment]
Can we see it ingame please?

**Comment by novaepee** [comment]
https://user-images.githubusercontent.com/6610922/162331884-e358b6b9-b628-4d49-8d5f-73372f767734.mp4


https://user-images.githubusercontent.com/6610922/162331676-cd2f9e5b-c8ca-47d5-a733-f955301a01f1.mp4

**Comment by Pill-U** [comment]
this is gonna trigger my OCD

**Review by BraveMole — CHANGES_REQUESTED** [review]
I think this hinders visibility. I'm tming this but if I see people complaining this won't be merged

**Comment by TiviPlus** [comment]
aösp get kuro to approve this ispose

**Review by Kuro020 — APPROVED** [review]

**Comment by Wayland-Smithy** [comment]
Not a huge fan, but if it helps others I will cope.

Something else to also consider is fixing the z-index because multiple objects can block the bars including smoke. For humans this makes sense so they can hide, but not for xenos especially when random walls and windows block it too as a side effect.

**Pull request merged**
