### PR TITLE
Marine respawn from 45 minutes to 30 minutes

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Ttile

## Why It's Good For The Game

Don't know if people will like it, but I think the marines push mid round are a bit sad. This will maybe allow marines to make a second push mid round that's more dangerous than the one they are currently doing

Give feedback

## Changelog
:cl:
balance: Respawn for marines are now 30 minutes instead of 45
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -14. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by neohenry** [comment]
And the cycle continues to balance marine respawn.

**Comment by Cowbin** [comment]
If xenos actually get something for respawns sure.  Right now xenos get nothing for latejoins and respawns and this will just further push that issue.

**Comment by BraveMole** [comment]
> If xenos actually get something for respawns sure. Right now xenos get nothing for latejoins and respawns and this will just further push that issue.

I mean this will need some balancing for xenos, whether by giving something when respawning, or buffing pools a little, or buffing psy drain etc

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
