### PR TITLE
Increases warrior wall hit damage

### PR DESCRIPTION
**Pull request by blackdav123**
## About The Pull Request
Increases the bonus damage on wall hits from 0.5x slash damage to 2x slash damage.
The warrior rework added bonus damage to warrior throwing people against walls. Currently, throwing someone against a wall deals 13.5 damage (before armor) instead of the usual 5. A full combo from a warrior including a wall hit and a grab punch currently deals 25 damage to a medium armor marine. This changes the full combo to 40 damage on a medium armor marine, and 56 for primo. 

For anyone fearing the return of the instafrac, fear not. The damage from the wall hits is already applied randomly so this wont result in anyone instantly getting their limbs torn off.
## Why It's Good For The Game
Warrior used to be a staple burst damage caste that could always provide value to the team even if marines arent blindly rushing into maze waiting to be flung. Right now the caste has very high risks for very little gain. This hopefully increases the baseline value of a warrior allowing it to do things other than just throw people at puppeteers.
## Changelog
:cl:
balance: Warriors now deal 2x slash damage on a wall hit instead of 0.5x.
/:cl:

### CODE REVIEW

**Comment by blackdav123** [comment]
> Increasing xeno slash damage breaks our medical system. This makes throws deal 40 slash damage, on top of stunning. Warrior isn't a solo caste (until you have primo at least) - you're meant to use your abilities to CC and brazil marines for you and another xeno to cut down.

sorry if the pr didnt make it clear, warrior has a multiplier for how much damage throwing people against a wall deals that scales off of warrior's slash damage (in case they have a different slash damage number for whatever reason). this multiplier is currently 0.5x and this pr increases it to 2x, slash damage itself isnt touched.

**Comment by blackdav123** [comment]
> Warrior's slash damage is 20 which means the 2x multiplier will result in a 40 brute damage hit for the throw.

warrior has 22 slash so its 44 damage on a naked marine which is reduced by armor to around 20

**Review by Lumipharon — CHANGES_REQUESTED** [review]
this is a significant buff considering slash damage was already buffed close to the original amount, so I'm not sure what this is trying to fix, other than simply buffing warrior just cuz

**Comment by blackdav123** [comment]
> this is a significant buff considering slash damage was already buffed close to the original amount, so I'm not sure what this is trying to fix, other than simply buffing warrior just cuz

warrior had wall hits on every ability in the earlier drafts of the rework and it was changed to only get those on the throw and fling so now warrior full combo is two slashes of damage. this gives warrior more damage if they are trying to fight instead of just throw people into hive

**Comment by blackdav123** [comment]
> It's not two slashes' worth of damage in the standard warrior damage combo. You lunge, slash once (can do twice if you click well), then punch while the grab is still active, then you can fling them at a wall for a little extra damage plus a small stun. The damage comes out to 22 (44 if you slash twice before punch) + 33 (punch) + 11 (fling) = 66-88 damage, all while a marine is stunned+staggered for the duration. You can then slash normally after this.
> 
> With this buff, that changes to 99-118 damage in a combo that takes about four seconds and has a marine stunned for the duration. Warrior isn't bad at dealing damage, it's just finicky to execute and vulnerable to being interrupted by other nearby marines.

marines have armor so this is typically halved

**Comment by Lumipharon** [comment]
Yeah I don't understand this. The net changes weren't really much of a nerf, it still does what its always done, even if its a bit more gimmicky with abilities now.

**Pull request closed without merging**
