### PR TITLE
Nerfs Meme guns

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request

Nerfs the mosin from 80/60->65/40 and the PPsh to 23/0 from 30/5

## Why It's Good For The Game

Nerfs to the meme guns.
## Changelog
:cl:
balance: Meme guns such as the Mosin and the PPSh have been nerfed.
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
Mjp did a pr,the world is gonna end!

**Comment by Metroidlover** [comment]
Geeze, I leave for a few weeks and all the lazy people actually start making their own PRs.

How you idiots have grown

**Comment by Rohesie** [comment]
I feel both are still too powerful but it's a step in the right direction.

**Comment by ArcaneCarrot** [comment]
The great patriotic war is no meme

**Pull request merged**
