### PR TITLE
Xeno turrets have 10 bullet and laser hardarmor

### PR DESCRIPTION
**Pull request by jroinc**
## About The Pull Request

Xeno turrets now have 10 bullet and laser hardarmor.

## Why It's Good For The Game

Getting slightly annoyed by how weak ayy turrets seem to be. They're incapable of slowing a rush, because ungas just gun them down with one GPMG or LMG mag while tanking the damage or dodging or offscreening, or head in and shotgun them. 

This should make it significantly more difficult to just ungarush-shoot them, or offscreen them (due to falloff) while still allowing grenades (which take storage space) to rapidly kill them and fire to reliably, but slowly, kill them.

## Changelog
:cl:
add: Added new mechanics or gameplay changes
balance: Added 10 bullet and laser hardarmor VS ayy turrets.
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
the what, sentries never died easily to guns, it takes like 1 or 2 mag to kill one with a t-12

**Comment by jroinc** [comment]
> 
> 
> the what, sentries never died easily to guns, it takes like 1 or 2 mag to kill one with a t-12. the problem with sentries is way less getting shot and how much you basically need grenades to kill them reliably, sentries warm up to 1500 HP and thats a heck ton

The issue is that 2-3 people can just mow one down in seconds. One person can, and it's not even a single mag with a LMG or GPMG. Testing some stuff now.

**Comment by jroinc** [comment]
Okay, I just watched Lewdicifer solokill a resin turret (four times) in the tdome with a T12. It took two mags, he stayed in range while dodging in heavy armor the whole time, and he took around twenty to thirty damage total.

We made sure the last one was full HP, and it took him a mag and a half to kill it, and only took 40 damage.

That's ONE unga with the basic weapon. One and a half mags. And you can fire from offscreen!

**Comment by jroinc** [comment]
https://discord.com/channels/498569646014857217/500801682058379265/879984242107510796

**Comment by Pariah919** [comment]
This is a meme of a PR, makes turrets take 100 shots to kill with a t-12 before falloff, I'd say that's a lot and pretty silly considering turrets are going to be used around chokes and doesn't fix the main issue is that flamers are absurd and kill mazes in like 2 minutes, it isn't a turret issue.
I don't think it's good for the game that turrets are absurdly tanky and forces marines into using hardcounters to deal with them at all, which is the main issues turrets have always had.
Also turrets aren't placed on open planes, I've seen them slow down rushes plenty of times.
Main issue turrets have is fire owns them incredibly fast, and they take psypoints which makes them terrible if misused overall.
Also makes pen literally do nothing against turrets at all, which is stupid.
Hard armor is flat values that penetration does nothing against which means that every single gun in the game loses a flat ten damage and doesn't have armor applied?
It makes the pen weapons have and makes it entirely pointless, I'd just make it have 40% soft armor which does the same job but allows penetration to do something for the game.
Grenades still don't kill turrets in a good amount of time takes 2/5 to kill a just made turret and , and heavy explosions still don't deal much damage to them.

Pretty much boils down to using only hard counters to deal with them, either smoke grenading them or just incend spamming them, seems kinda dumb.

Also turrets heal passively overtime? So they have more effective HP than they seem.

**Comment by jroinc** [comment]
> 
> 
> This is a meme of a PR, makes turrets take 100 shots to kill with a t-12 before falloff, I'd say that's a lot and pretty silly considering turrets are going to be used around chokes and doesn't fix the main issue is that flamers are absurd and kill mazes in like 2 minutes, it isn't a turret issue.
> I don't think it's good for the game that turrets are absurdly tanky and forces marines into using hardcounters to deal with them at all, which is the main issues turrets have always had.
> Also turrets aren't placed on open planes, I've seen them slow down rushes plenty of times.
> Main issue turrets have is fire owns them incredibly fast, and they take psypoints which makes them terrible if misused overall.
> Also makes pen literally do nothing against turrets at all, which is stupid.
> Hard armor is flat values that penetration does nothing against which means that every single gun in the game loses a flat ten damage and doesn't have armor applied?
> It makes the pen weapons have and makes it entirely pointless, I'd just make it have 40% soft armor which does the same job but allows penetration to do something for the game.
> Grenades still don't kill turrets in a good amount of time takes 2/5 to kill a just made turret and , and heavy explosions still don't deal much damage to them.
> 
> Pretty much boils down to using only hard counters to deal with them, either smoke grenading them or just incend spamming them, seems kinda dumb.
> 
> Also turrets heal passively overtime? So they have more effective HP than they seem.

Yeah, I tested this and it's fine IMO. Turrets are easily killable by a single person for less than 2 full mags currently. That's not really OK. All of the other counters are fine, but it's too easy to just tank the damage and shoot them to death.

**Comment by jroinc** [comment]
An unmodded T12 took two magazines and 10 bullets to kill a regular turret from offscreen.

The same unmodded T12 took two magazines and 13 bullets to kill a 10 hardarmor turret from offscreen.
I tested it again, making sure that the armor was properly updated and the integrity was full. Two magazines, eight bullets.

This is *very* weird. More testing is required.

**Comment by EvilMelonTheSecond** [comment]
Do I remember wrong or wasn't the use of hardarmor a REALLY bad idea due to how code works?

**Review by BraveMole — CHANGES_REQUESTED** [review]
Hard armor is a bad idea.

If you're annoyed that people can dancer around turrets, make the projectiles faster

**Comment by jroinc** [comment]
> 
> 
> Hard armor is a bad idea.
> 
> If you're annoyed that people can dancer around turrets, make the projectiles faster

nah, I'm good

**Pull request closed without merging**
