### PR TITLE
Valkyrie net nerf, no longer splints bones, now gives hydrocodone instead of tram and no slow.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Valk now no longer splints bones, but gives you B18 hydrocodone instead of tramadol.
It has no slowdown.
## Why It's Good For The Game
Valkyrie inheriently breaks the game by allowing you to ignore the biggest source of longlasting damage which is broken bones, this is pretty much hands down the fastest way to ignore your longlasting damage as marine outside of limited use pills and such, it has needed to go for quite a while.
## Changelog
:cl:
balance: Valkyrie automedical module no longer splints bones, now gives hydrocodone instead of tramadol and no slowdown.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
What if each splint caused a fair bit of slowdown, because it's making movement more cumbersome?

**Comment by Alexeivichi** [comment]
Just try to delete it again, MJP. It'd better than this weird change.

**Comment by bowlofcereal** [comment]
you'd have just been better off trying to delete the module instead of doing whatever the fuck this is dude

**Comment by Pariah919** [comment]
fastest feedback in 1 hour

**Pull request closed without merging**
