### PR TITLE
Adds KTLD sight sunglasses

### PR DESCRIPTION
**Pull request by Alfalfa523**
## About The Pull Request
Adds the ability to attach the KTLD sight to the fake sunglasses you can spawn with.
gitpic1
gitpic2
gitpic3
## Why It's Good For The Game
Most huds like the medhud and mesons can be attached to sunglasses, but not the KTLD sight.
This adds the ability to attach the KTLD sight to sunglasses, behaves exactly the same but looks more stylish.
## Changelog
:cl:
add: Ability to attach the KTLD sight to sunglasses
add: KTLD sunglasses w/ new sprite
/:cl:

### CODE REVIEW

**Comment by aarrisu** [comment]
look at this mope pr ughhh holy carp can we gitban this guy....

**Comment by tanker4390** [comment]
Can you maybe add the ability to add them to the goggles while you're at it?

**Comment by Alfalfa523** [comment]
> Can you maybe add the ability to add them to the goggles while you're at it?

Eventually yes, this was my first PR so I didn't want to change or add a ton of stuff right off the bat.

**Comment by lbnesquik** [comment]
Nice job for a first PR! Do try to use branches for your code next time. Trust me, it really helps avoid messing up your master branch, and having to fix that when you are starting? Sucks!

**Comment by imsxz** [comment]
YIPPIE

**Comment by veterath** [comment]
wowzers

**Comment by Sirsnek15** [comment]
why not blue?

**Comment by zzurge** [comment]
DRIP

**Pull request merged**
