### PR TITLE
smart pistol now avaliable to smartgunners plus balance changes

### PR DESCRIPTION
**Pull request by Scarlet-Oduko**
## About The Pull Request 

Allows SG's to get a free holster and SP-13 smart pistol with two mags as a sidearm. Any further ammo is 2 points per or from req. 
Also allows the smart pistol to be one handed, stats adjusted to make it cause recoil even with gryo. adjusted scatter as well.
## Why It's Good For The Game

it's a smart pistol, smart gunners should have access to a specific side arm for them to use, provides a good sidearm to go with their main guns while not being overpowering.
Adjustments to the gun itself will out it to be whipped out in emergency's, but still scatters and recoils. 
## Changelog
:cl:
add: SP-13 and ammo to smartgunner prep vendor
balance: SP-13 can be one handed, recoil of 2 and scatter of 7 when wielded.

/:cl:

### CODE REVIEW

**Comment by 74delta** [comment]
based

**Comment by dontob** [comment]
respect

**Comment by InterroLouis** [comment]
What's the point of making it fireable one-handed if you also make it terrible when fired one-handed?

**Comment by Scarlet-Oduko** [comment]
> What's the point of making it fireable one-handed if you also make it terrible when fired one-handed?

so you can whip it out in a pinch if a xenos point blank. it also accepts gyro which helps with the recoil. if I made it have no recoil one handed people would just meme on it akimbo and maints don't want that.

**Comment by grinkgo** [comment]
> > What's the point of making it fireable one-handed if you also make it terrible when fired one-handed?
> 
> so you can whip it out in a pinch if a xenos point blank. it also accepts gyro which helps with the recoil. if I made it have no recoil one handed people would just meme on it akimbo and maints don't want that.

Could make it perform better/worse based on smartgun skill?

**Comment by Scarlet-Oduko** [comment]
> > > What's the point of making it fireable one-handed if you also make it terrible when fired one-handed?
> > 
> > 
> > so you can whip it out in a pinch if a xenos point blank. it also accepts gyro which helps with the recoil. if I made it have no recoil one handed people would just meme on it akimbo and maints don't want that.
> 
> Could make it perform better/worse based on smartgun skill?

SG skill is off or on, there aren't tiers for it.

**Comment by Arctrooper8** [comment]
Making this a bundle in the smartgunner vendor I believe makes it so that it won't vend with a saved loadout through the loadout vendor.

**Comment by Scarlet-Oduko** [comment]
> Making this a bundle in the smartgunner vendor I believe makes it so that it won't vend with a saved loadout through the loadout vendor.

hmm, that's fair but if anyone actually wants to use them they'll just have to deal with it. as it'd be a mess to put individually.

**Comment by 00ze-cyclone** [comment]
SG pistol build real

**Pull request merged**
