### PR TITLE
Prevent self harm

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Title

## Why It's Good For The Game

If you really want to suicide just flame yourself or use fists

## Changelog
:cl:
qol: Prevent self harm
/:cl:

### CODE REVIEW

**Comment by FIXTHERADBOXPLEASE** [comment]
Don't merge this I beg you. Or at least let you attack yourself on harm intent only.

**Comment by Starfirejordan** [comment]
dumb PR, skill issue of hitting self should be punishing

**Comment by crayonLover09** [comment]
> dumb PR, skill issue of hitting self should be punishing

On one hand yes, but on the other hand giving yourself frac because the game decided to not recognize your swap hand keybind when you tried to give yourself a pill is not fun.

**Comment by mc-oofert** [comment]
Prevents you from eating food

**Comment by mc-oofert** [comment]
Actually you cant use anything on yourself

**Comment by Panzerkampfwaggen** [comment]
Robots and synths can't use the soldering tool on themselves

**Pull request closed without merging**
