### PR TITLE
Squad marine role now shows as Recommended in lobby job selection

### PR DESCRIPTION
**Pull request by Losenis**
## About The Pull Request
Squad marine role now shows as Recommended in lobby job selection

## Why It's Good For The Game
Squad marine role now shows as Recommended in lobby job selection
also should help in pointing rookies what role they should probably focus on getting competent at first given it's also the role that has the newcomer guide on vendor

## Changelog

:cl:
qol: Squad marine role now shows as Recommended in lobby job selection
/:cl:

### CODE REVIEW

**Comment by GreatKingWombat** [comment]
Won't that give new players the wrong idea? Every other use of the recommended tag in the codebase is to say "pick this or you're running a meme loadout".

**Comment by ClosetedSkeletonGH** [comment]
> Won't that give new players the wrong idea? Every other use of the recommended tag in the codebase is to say "pick this or you're running a meme loadout".

That’s just not true at all nor would a new player know this

**Comment by Losenis** [comment]
>Every other use of the recommended tag in the codebase is to say "pick this or you're running a meme loadout"

It sounds that by the time you start thinking it in that manner you're way, way past the target demographic this pr is for

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Good idea but horrible implementation lol
You're whiping Job related things and changing the actual displayed job name instead of just the UI

**Comment by Losenis** [comment]
I swear that's the only relevant result I got from searching for the actual text there lmao, gonna see if I can find it later

**Comment by TiviPlus** [comment]
image
https://tenor.com/view/john-cena-john-cena-are-you-sure-about-that-gif-7788121

**Comment by TiviPlus** [comment]
Also its set in title which is used in persistently

**Comment by Losenis** [comment]
By relevant I mean that the other results were derived from the main one that I ended up changing, so I must've skipped a good bunch of them

**Pull request closed without merging**
