### PR TITLE
Plasma Cutter Changes

### LINKED ISSUE #15284: Too easy to accidently cut weeds on walls and waste PC charge
### Description

What happens:
The Plasma Cutter gets used cutting weeds on the walls instead of the actual wall and you lose 1000 charge
What should happen: 
Cutting weeds on walls should be be a free action like attacking with any ohter melee weapon

### Test Merges

Round ID: [25991](https://scrubby.melonmesa.com/round/25991)
BYOND Version: 515.1626
Server revision compiled on: 2024-03-05T02:29:15+00:00
Master commit: [9993935d3bc1df73ccecddf47ec1ce509f206ea1](https://github.com/tgstation/TerraGov-Marine-Corps//commit/9993935d3bc1df73ccecddf47ec1ce509f206ea1)
The following pull requests are currently test merged:
[#14615: 'Revamps the Alamo with doublewide seats and enchanced player visibility' by ClosetedSkeletonGH at commit 3423a95c7d](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14615)

### Reproduction Steps

Cut Wall with Weeds on it and accidently click the weeds instead of the wall sprite

### Screenshots

_No response_

### LINKED ISSUE #16471: You can't plasmacut resin doors anymore
### Description

see title
when do we revert that fucking door pr

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [29084](https://scrubby.melonmesa.com/round/29084)
BYOND Version: 515.1633
Server revision compiled on: 2024-08-15T01:43:49+00:00
Master commit: [7823b111792fbfa4ed1e5293b7bed9aed25833f4](https://github.com/tgstation/TerraGov-Marine-Corps//commit/7823b111792fbfa4ed1e5293b7bed9aed25833f4)
The following pull requests are currently test merged:
[#15961: 'Squad radio TTS' by breadhunt at commit fd2840fa91](https://github.com/tgstation/TerraGov-Marine-Corps//pull/15961)

Local commit: d6ff4d156a52ba7c7373317ea0981d7faec04915
Server tools version: 6.8.0

### Reproduction Steps

1. Get pc
2. hit resin wall
3. it opens up a do_after instead of vapourizing it
4. cry

### Screenshots

image

### PR DESCRIPTION
**Pull request by Runian**
## About The Pull Request
Plasma cutters can be used on resin doors without a delay similar to resin walls.
Closes #16471

Weeds no longer has any plasma cutter interaction (as a normal attack is good enough to kill the weeds).
Closes #15284

By default, trying to use a plasma cutter on a object while on harm intent will try to attack the object normally if possible.
Other intents (or if above doesn't do anything) will try to cut down the object (which comes with the standard 1000 charge cost).

The bonus damage/interaction between plasma cutters and xeno turrets have been expanded to all xeno structures, but now causes 100 charge per attack.
## Why It's Good For The Game
1. I got annoyed that I can't one-shot resin doors with a plasma cutter (its also a bug).
2. I actually just wasted 1000 charge on cutting weeds on walls. I'm coping.
3. "Starts cutting apart" spam is cringe.
4. How come only resin walls (and resin doors later) are generally one-shot, but xeno structure (I'm looking at you, resin pod) requires me to smack it like 10 times with an active plasma cutter (which costs no charge atm).

## Changelog
:cl:
qol: Using harm intent with a plasma cutter on an object tries to attack it normally if possible. Other intents will try to cut it down.
qol: Xeno weeds have no interaction with plasma cutters and thus will not waste nor require 1000 charge on cutting it down.
balance: Plasma cutters now uses charge to deal additional damage to (more) xeno structures similar to how bonus damage is dealt to resin walls.
fix: Plasma cutters now attack resin doors just like resin walls.
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
Balance of Life PR

**Comment by Wisemonster** [comment]
Removing the function of a tool is not QoL, it's either del or balance.

**Comment by iforgotmeword** [comment]
> Removing the function of a tool is not QoL, it's either del or balance.

just wondering what function?

**Comment by SimplySmiley123** [comment]
> Removing the function of a tool is not QoL, it's either del or balance.

What is it removing lol

**Review by Kuro020 — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
