### PR TITLE
The end of Jaeger

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image

Removes Jaeger from any acquireable source, only Xenonauten is now avaliable.
## Why It's Good For The Game
Our artstyle is an utter mess, and I believe starting by removing Jaeger is a good start since it'll let us consolidate, we have way too many colors running around and shrinking down to Xenonauten is a good start.
## Changelog
:cl:
del: Jaeger is gone. Reduced to ashes. Any mention of it is replaced with Xenonauten.
/:cl:

### CODE REVIEW

**Comment by srxtreme** [comment]
Holy shit. I love you MJP.

**Comment by LeAntek** [comment]
Good PR
Speedmerge

**Review by Kuro020 — APPROVED** [review]
Die hyperscale

**Comment by Starfirejordan** [comment]
MJP and Kuro what the fuck are you doing.

**Comment by iLikeMemes** [comment]
New drip meta incoming.

**Comment by Kuro020** [comment]
> MJP and Kuro what the fuck are you doing.

Saving tgmc

**Comment by Losenis** [comment]
Xenonaut drip keep winning

**Comment by MereWalker** [comment]
I will miss you jaeger. Anyways, I like xenonaut armour more anyways.

**Comment by Derrick2Electricboogaloo** [comment]
BASED CHANGE WE NEED.

**Comment by maikilangiolo** [comment]
Keep the helmets at least.

**Comment by Licherr** [comment]
Have someguy reuse the Jaeger Helmet sprites as some look well with current xeno.

**Comment by 567Turtle** [comment]
https://tenor.com/view/why-crying-emotional-tears-sobbing-gif-17306861

**Comment by Aporhtonoma** [comment]
you kill my pink armor loadout im comming for you

**Comment by WEWLAD2222** [comment]
Xeno talons wrote this PR

**Comment by TiviPlus** [comment]
Not proper removal

**Pull request closed without merging**
