### PR TITLE
Adds Cat Ears (back)

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Adds Cat ears back.
Approval obtained from Art Maintainer.

## Why It's Good For The Game
More diverse and much needed fluff aesthetics.

## Changelog
:cl:
add: Adds Cat Ears.
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
Queue half the marine force getting decapped because they simply cannot resist the kitty ears.

**Comment by Naaanii** [comment]
> Queue half the marine force getting decapped because they simply cannot resist the kitty ears.

Admin spawn only. <s>(For now).</s>

**Comment by Derrick2Electricboogaloo** [comment]
All the failed checks. The universe speaks!

**Comment by Arctrooper8** [comment]
> Admin spawn only. (For now).

Kitty ears marine helmet module when?

**Comment by bowlofcereal** [comment]
rot in hell

**Comment by Losenis** [comment]
Hyped for the amount of salt by xenoids beaten by people wearing them

**Comment by Coastfront** [comment]
No.

**Comment by Al-1ce** [comment]
Add a tyr with cat ears for helmets.

_nya_

**Comment by Al-1ce** [comment]
nya

**Comment by RipGrayson** [comment]
nya

**Comment by Araulius** [comment]
I will only support this if it adds a "kick me" sign on the neko nerds back

**Comment by Kuro020** [comment]
and now tgmc will know pain again

**Comment by Ragecrabbo** [comment]
why

**Comment by Alexeivichi** [comment]
**Wowwwww, you meow like a cat! That means you are one, right? Shut the fuck up. If you really want to be put on a leash and treated like a domestic animal then that’s called a fetish, not “quirky” or “cute”. What part of you seriously thinks that any part of acting like a feline establishes a reputation of appreciation? Is it your lack of any defining aspect of personality that urges you to resort to shitty representations of cats to create an illusion of meaning in your worthless life? Wearing “cat ears” in the shape of headbands further notes the complete absence of human attribution to your false sense of personality, such as intelligence or charisma in any form or shape. Where do you think this mindset’s gonna lead you? You think you’re funny, random, quirky even? What makes you think that acting like a fucking cat will make a goddamn hyena laugh? I, personally, feel extremely sympathetic towards you as your only escape from the worthless thing you call your existence is to pretend to be an animal. But it’s not a worthy choice to assert this horrifying fact as a dominant trait, mainly because personality traits require an initial personality to lay their foundation on. You’re not worthy of anybody’s time, so go fuck off, “cat-girl”.**

**Comment by MiniMeatwad** [comment]
Add a 1000x damage multiplier. Die instantly to a vending machine flinging a 0.2 damage object at you.

**Pull request merged**
