### PR TITLE
Add new supply drop console

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Total rip off of https://github.com/tgstation/TerraGov-Marine-Corps/pull/4540

Removes supply drops from overwatch
Adds a new console for doing supply drops, this can be placed in Req to better facilitate squads.

UI is also TGUI.

## Why It's Good For The Game

Ease the support of squads.
Also breaks up a bit of the complicated overwatch.dm file.

RO running between CIC and req is utterly stupid

## Changelog
:cl:  PsyKzz & Kuro (Sprites) & Bravemole (Merging conflict and bug fixes)
add: Added supply drop console
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
no more Req exercise now

**Comment by Swagile** [comment]
As a RO main, thank you.

**Review by TiviPlus — APPROVED** [review]

**Comment by SplinterGP** [comment]
My man, are you here to revive the Psykzz legacy ? you are a man of good heart

**Comment by Swagile** [comment]
So not sure if its just uhhh me fucking up somewhere but...

I sent a crate then stepped away from the console and it never launched.

Ill have to test it but during the round this happened after this issue appeared, I always stayed near the console until the crate was launched, then moved.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
