### PR TITLE
[APRIL FOOLS] [DNM] TGMC APRIL FOOLS 2022 PR

### PR DESCRIPTION
**Pull request by mrhugo13**
## About The Pull Request
This is a massive collection of shitpost, with mixed amounts of effort.

### PR WILL BE UN-DRAFTED/OPENED ON MARCH 31ST FOR SOONEST POSSIBLE TESTMERGE

CONTENTS OF APRIL FOOLS PR:
- Added a bunch of old (meme) warcries + one loaned from /TG/ for robots.
- Tips replaced with 2022 april fools tips (the only tips it can pick from)
- Defiled/Vandalized a bunch of the title/lobby art.
- Meme title/lobby art is now in title/lobby art rotation once again, these are the only ones not vandalized or defiled.
- Fart reverb sound on all explosion cinematics.
- Cat ears on all helmet attachments.
- New hit sound for harvester (may get annoying but that's what harvester users will love)
- [After-shutters-opening song](https://youtu.be/peuTnilEv9g) to pump marines up.
- Added cirno plushie from #8658
- Queen now picks either been SCOTTLAND FOREVER or vine boom sfx when screeching
- Shrike now either plays the john cena or [sly marbo AAAAAAAAAAAA](https://youtu.be/jCMNWAJiz5Y?t=148) sound when roaring
- Roomba replaced with lusty xeno maid (with lusty xeno dialogue)
### THIS PR IS NOT MADE WITH INTENTION OF GAME BALANCE FUCKERY, ALL TO MOST OF THIS WILL BE ENTIRELY COSMETIC.

CURRENT TO-DO'S/REQUESTS:
- ~~Slothbot — Today at 15:59
add the tgstation lobby music~~ discontinued due to TGMC lobby music is entirely chosen serverside.
- ~~Poofy 2 User — Today at 16:00
Just add cat ears as a helmet attachmeny~~ kuro said no, >:( (but i'm gonna do it anyway cuz tivi agreed on the idea)
- Firefox ✩ — Today at 16:33
make it rand(10)
so it will won't be THAT annoying (referring to the harvester hit sound)
- Maybe more some comedic sounds/music
- Think up of more stuff
## Why It's Good For The Game
April fools is once a year and i did something like this last year, i see no reason as to stop this tradition now.
Also most of these changes will most likely not actually affect game balance, simply just alot of shitposting flavor.

## Changelog
:cl: Vondiech
add: If you see this then someone has merged the 2022 april fools PR, oh god no.
/:cl:

### CODE REVIEW

**Comment by Chip11-n** [comment]
Based

**Comment by FosterGrime-Heymynameslouie** [comment]
make felinds a playable race in april fools mode
guns have a random chance to jam/eject their magazines (debatable) 
every xeno sprite by default is their rounyfied counter part (woyer, rouny, quoen, etc.)

**Comment by Pill-U** [comment]
add sanctions back

**Comment by mrhugo13** [comment]
> add sanctions back

This one is already a thing and i believe still TM'd?



> make felinds a playable race in april fools mode guns have a random chance to jam/eject their magazines (debatable) every xeno sprite by default is their rounyfied counter part (woyer, rouny, quoen, etc.)

tivi said no on 1st and 3rd, 2nd i'm putting my foot down on as no big game balance fuckery will be going on.

**Comment by bruhlookatthisdood** [comment]
change runner's sprites to roony

**Comment by mrhugo13** [comment]
> change runner's sprites to roony



> change runner's sprites to roony

Tivi said no on that, it's up to admins if they wanna activate fun mode or not.

**Comment by bruhlookatthisdood** [comment]
add lusty xeno maids on the stations

**Comment by bruhlookatthisdood** [comment]
> > add lusty xeno maids on the stations
> 
> we don't have any in code, as much as that hurts to say.

port lusty xeno maids to add on the stations

**Comment by FosterGrime-Heymynameslouie** [comment]
now that I think of it
wouldnt adding cat ears on all helmet attachments discourage marines from wearing helmets and thus be considered shifting balance a bit
or is it just a specific attachment that you can choose to add yourself and not all attachments looking like cat ears

**Comment by bowlofcereal** [comment]
You know how last april fools we made everyone SOM? Do that again.

Also, make the queen screech the vine boom sfx.

**Comment by mrhugo13** [comment]
> > > add lusty xeno maids on the stations
> > 
> > 
> > we don't have any in code, as much as that hurts to say.
> 
> port lusty xeno maids to add on the stations

Figured out a method of doing this, will be posted later.

> now that I think of it wouldnt adding cat ears on all helmet attachments discourage marines from wearing helmets and thus be considered shifting balance a bit or is it just a specific attachment that you can choose to add yourself and not all attachments looking like cat ears

either you accept the cat ears or you accept death, your choice marine.



> You know how last april fools we made everyone SOM? Do that again.
> 
> Also, make the queen screech the vine boom sfx.

first part is out of scope, second is definetly worth it.

**Comment by mrhugo13** [comment]
Today is mostly small stuff cuz I wanted to do something else other than focus most of my day onto this april fools PR, but eitherway here's todays progress:

- Added cirno plushie from #8658
- Queen now picks either been SCOTTLAND FOREVER or vine boom sfx when screeching
- Roomba replaced with lusty xeno maid (with lusty xeno dialogue)

**Pull request closed without merging**
