### PR TITLE
Removes FAMAS from seasonals

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request
title

## Why It's Good For The Game
FAMAS gaming

## Changelog
:cl:
balance: remove famas from seasonals
/:cl:

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
speedmerge

**Review by SplinterGP — APPROVED** [review]

**Comment by BraveMole** [comment]
speedmerge

**Comment by KornFlaks** [comment]
Xenos might actually be playable now. Speedmerge.

**Comment by InterroLouis** [comment]
What are you going to replace it with? This will leave one seasonal rotation with just one gun.

**Comment by David-Stormwell** [comment]
Just make another PR to put the mosin and similar into it

**Comment by InterroLouis** [comment]
THE MOSIN. Eugh. Marines already get the mosin, and it's easier to just ask for a change on an existing PR instead. What about the M412 Pulse Rifle?

**Comment by Walarks** [comment]
> What are you going to replace it with? This will leave one seasonal rotation with just one gun.

Unless someone suggests something balanced, I won't.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
