### PR TITLE
adds some tx54 grenades to valhalla vendors

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
https://github.com/tgstation/TerraGov-Marine-Corps/pull/13972
he didn't put them back in valhalla even after Lumi told him to keep them
## Why It's Good For The Game
Deltafire your days are numbered. Sleep lightly
## Changelog
:cl:
fix: readds tx54 razor nades to valhalla
add: adds tx54 acid grenades to valhalla
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
I got told to not full remove it from the code as lumi had use for it yet. As marines have zero way to access it, I did not see any purpose in supporting it in valhalla.

**Comment by yyzsong** [comment]
> As marines have zero way to access it

The purpose of valhalla is to play with toys you can't play with otherwise. Which is why all of the PMC and req weapons are there. Marines can't get SOM, ICC or PMC gear regularly, but they're still in there. Very stinky.

**Comment by Wisemonster** [comment]
Yes, but those items are used in-game witb their respective erts. Is there anywhere that TX-54 razorwire nades are used at all?

**Comment by yyzsong** [comment]
> Yes, but those items are used in-game witb their respective erts. Is there anywhere that TX-54 razorwire nades are used at all?

Do not act like the regular player will get those weapons all the time with the space to test them on xenos and shit. Valhalla has shit like the robocop pistol, which isn't accessible by normal means. Not being able to be accessed in game is no reason to keep it out of valhalla.

**Comment by TellyLsc** [comment]
ok but what if someone spams it on the spawn area, you don't spawn with a knife or any melee weapon to break the razor wire

**Comment by yyzsong** [comment]
> ok but what if someone spams it on the spawn area, you don't spawn with a knife or any melee weapon to break the razor wire

There are also regular razor grenades in valhalla. You can spawn in as a engineer, vend a shitton of metal and then fill all of valhalla with walls

and then you can just ahelp to get rid of it. This won't do anything.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
