### PR TITLE
deletes unused gun sprites 

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
deletes unused gun sprites and some map variants of unused guns, removes the old b92fs sprite and uses the m9 one in the code as it is marginally better

## Why It's Good For The Game
less clutter in gun.dmi

## Changelog
:cl:
del: Removed old unused gun sprites
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -68. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by David-Stormwell** [comment]
Check if freelancers use the M9, pretty sure they might

**Comment by XSlayer300** [comment]
They use the 93R, the burst fire barretta.

**Review by TiviPlus — APPROVED** [review]

**Review by XSlayer300 — CHANGES_REQUESTED** [review]
M9 custom pistol sprites will be null if you don't revert them to "b92fs" too.

**Comment by XSlayer300** [comment]
image
Are we still using camo variants for this gun only for EORG spawns?

**Comment by XSlayer300** [comment]
image
Are we still using this?
image
If these are old, why is it still here then? Maybe you can replace the M37 sprites with the unused T35.
image
I don't understand why are you not deleting this too.

**Comment by Pariah919** [comment]
>Are we still using this?
>
no clue if the syringe gun exists or is used but one day someone might restore it
>If these are old, why is it still here then? Maybe you can replace the M37 sprites with the unused T35.
>
they're still somewhat in style compared to the old guns, could probably reuse them
>I don't understand why are you not deleting this too.
>
done
>Are we still using camo variants for this gun only for EORG spawns?
>
done

**Pull request merged**
