### PR TITLE
Nymph Support Minion

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Adds a new type of minion, Nymph. Can be spawned by minion spawners and silos. As an AI, it will autoweed the area. If a player takes control, it can also build resin walls.

Sprites from https://github.com/tgstation/TerraGov-Marine-Corps/pull/11273

## Why It's Good For The Game

Xeno helper, marine target.

## Changelog
:cl:
add: New xeno support minion: Nymph
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
spedmrhg instantley

**Comment by GrayRachnid** [comment]
Does it respect minion cap on silos?
Does it stay near silos or wander the map to weed?

**Comment by Waselon** [comment]
> Does it respect minion cap on silos? Does it stay near silos or wander the map to weed?

it counts and behaves as a normal minion

**Comment by Zangeiti** [comment]
I HATE WEEDS I HATE WEEDS I HATE WEEDS

**Review by Kuro020 — APPROVED** [review]
image
cute mf

**Comment by yyzsong** [comment]
If this dumb fuck plants over my sticky weeds I'm blowing up my silo

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
