### PR TITLE
ravager buff

### PR DESCRIPTION
**Pull request by Zar000**
## About The Pull Request

Increases Ravagers bomb armor
## Why It's Good For The Game
Currently ravager is awkward. She needs to be up close and personal yet when she does get close the punishment is borderline unbearable. 

Also decreased charge plasma cost

With the slight bomb armor increase, I believe ravager will get that extra freedom in the battlefield that she deserves.

And with the decreased cost of charge, even more freedom.
## Changelog
:cl:
balance: increased ravagers bomb armor
balance: decrease charge plasma cost from 500->400
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
would be better if they could trigger endure more often and if they could not have their ability use blocked by staggers.

**Comment by Naaanii** [comment]
Health is a bit weird, I think all armour including melee would be better.

**Comment by ScheveningenZonn** [comment]
hp buff goes a bit too far because the soft armor values increase EHP by a percentage -- assuming no sunder. you should raise soft armor about 10% instead so that SADARing a ravager to 0% armor means they can still die to any type of bullets, but a ravager should be able to take on SMG rounds fairly easily

**Review by Pariah919 — CHANGES_REQUESTED** [review]
Why? Ravager has high EHP with endure.. Why should it be any less fragile? I would understand if you did this and deleted endure but otherwise its a no from me..

**Comment by Lumipharon** [comment]
I'm inclined to agree with MJP here. Rav is good, it just relies heavily on being smart with using endure and rage. A competent rav is pretty deadly and hard to kill.

**Comment by FIXTHERADBOXPLEASE** [comment]
Ravager is easily the second worst tier 3. It's a direct combat caste that instantly dies in direct combat. No real reason to evolve into it when you can stay hunter/bull, have similar DPS, and NOT be a massive target with a huge sprite.

**Comment by Goblinu** [comment]
> it when you can stay hunter/bull, have similar DPS, and NOT be a massive target with a huge sprite.

This is definitly one of the biggest thing about ravager and why it is my least played T3

It is meant to be played as an assassin yet it's kit and sprite size says more of a fighter while it stats screams "im a runner with a big target on myself", hell even evasion is a 100x better survival tool than endure as of right now

**Comment by Zar000** [comment]
> I'm inclined to agree with MJP here. Rav is good, it just relies heavily on being smart with using endure and rage. A competent rav is pretty deadly and hard to kill.

> Why? Ravager has high EHP with endure.. Why should it be any less fragile? I would understand if you did this and deleted endure but otherwise its a no from me..

When was the last time that any of you played specifically ravager?

This caste does worse on frontline than a defender or rouny and it gives more points to marines

**Comment by Lumipharon** [comment]
> > I'm inclined to agree with MJP here. Rav is good, it just relies heavily on being smart with using endure and rage. A competent rav is pretty deadly and hard to kill.
> 
> > Why? Ravager has high EHP with endure.. Why should it be any less fragile? I would understand if you did this and deleted endure but otherwise its a no from me..
> 
> When was the last time that any of you played specifically ravager?
> 
> This caste does worse on frontline than a defender or rouny and it gives more points to marines

It's not really a frontliner though. You're relying on good use of both endure and rage/super rage to take people down while managing your low/negative health. Front lining means you can't really use your abilities well and you're at the mercy of getting insta killed by some offscreen tat/amr.

**Comment by Araulius** [comment]
> > > I'm inclined to agree with MJP here. Rav is good, it just relies heavily on being smart with using endure and rage. A competent rav is pretty deadly and hard to kill.
> > 
> > 
> > > Why? Ravager has high EHP with endure.. Why should it be any less fragile? I would understand if you did this and deleted endure but otherwise its a no from me..
> > 
> > 
> > When was the last time that any of you played specifically ravager?
> > This caste does worse on frontline than a defender or rouny and it gives more points to marines
> 
> It's not really a frontliner though. You're relying on good use of both endure and rage/super rage to take people down while managing your low/negative health. Front lining means you can't really use your abilities well and you're at the mercy of getting insta killed by some offscreen tat/amr.

widow outperforms it as an ambush caste.

**Comment by zzurge** [comment]
Ravager has the strongest slash damage of any of the caste if memory serves. its not supposed to be tanky its supposed to hit hard

**Comment by Goblinu** [comment]
> Ravager has the strongest slash damage of any of the caste if memory serves. its not supposed to be tanky its supposed to hit hard

There is a difference in being tanky and being paper thin, all damage caste got tools to get in and out quickly, ravager got lots of tool to get in but none to get out

**Comment by MemedHams** [comment]
Rav very awkward structurally- it's flavoured like a rampaging frontliner(which is how it originated) but currently can only meaningfully benefit the hive by running ambushes and supplying support DPS

It actively punishes running in to participate in an assault or being in any way bold, which feels kind of like a noob trap considering how it's effectively flavoured as Xenomorph Doomguy

This leads to a common situation where Rav picks are often treated poorly by hives as well, since they're seen as a dumb choice compared to other t3's and a KIA waiting to happen
Which combines with the gameplay awkwardness to make them unpleasant to play in general and a bad early t3 experience for new xenos who pick The Badass-Looking Sword Alien

I'd be onboard with removing some utility if we get a more assertive rav that's more forgiving to newer players and leads to less Wasted T3 picks and hive infighting

**Comment by UntoldTactics** [comment]
Overall ravager's inherently hinted to be yes, doomguy, but has actual horrid performance on frontlines because indeed, it has zero tools to escape fights and whilst endure and rage are decent, most damage can just overpower that very easily, its not that it uses endure and rage to be able to fight, it uses them to JUST BARELY BE ABLE TO SURVIVE on the frontlines for more than 5 seconds. It could definitely use some kind of changes to make it better- and marines might complain in smaller gatherings, but I think thats the point of ravager and direct combat castes in general. 

Think about it. It's the ONLY TIER 3 fully dedicated to direct combat. It should be utterly terrifying to face in its specialization without enough firepower to counteract it.

**Comment by Lumipharon** [comment]
I'm not satisfied that rav needs a buff of any sort, as it's already very strong when used correctly. Additionally, it has received a fairly strong indirect buff from the sunder change.

**Pull request closed without merging**
