### PR TITLE
m39 rework: Slowdown, damage, recoil

### PR DESCRIPTION
**Pull request by Aurelien3189**
## About The Pull Request
m39 stat changes:
aim_slowdown = 0 -> 0.15
smg ammo damage:
regular: 30/0 -> 23/0
ap: 20/40 -> 15/40
recoil: 2 -> 0.5

## Why It's Good For The Game
Just adds MJP's requested changes, which should by extension, automatically deny this PR. Gives a minor slowdown to the m39 to prevent it from being a "killing machine", reduces smg bullet damage as well to let it fit this category.

Changelog
🆑
balance: m39 rework: minor slowdown (0 => 0.15), smg bullet reduced (Regular: 30/0 => 23/0, AP: 20/40 => 15/40). smg recoil reduced to 0.5, so it's not entirely unviable one handed.
/🆑

### CODE REVIEW

**Comment by Rohesie** [comment]
The m39 is traditionally used on burstfire mode. How does this affect it?

**Comment by Aurelien3189** [comment]
That's a good question. The QFA would have lowered the burst, I haven't taken that into account for this PR. This is turning out to be a buff I'm having some trouble working around, any suggestions?

**Comment by Rohesie** [comment]
You can diminsh the burst amount.
You'll need to test how good burst and auto burst are now, and tweak them appropriately.

**Comment by Pariah919** [comment]
This kind of seems too good right now. Would recommend adding minor slowdown to the gun. Like 0.1 or 0.15?

**Comment by Rohesie** [comment]
The current status has overbuffed the M39.
We don't need more marine weapon buffs. We need nerfs.

**Comment by Aurelien3189** [comment]
Huh, what's your suggestion now?

**Comment by Rohesie** [comment]
Did a poll, and it's deemed currently too powerful.
Brainstorm with people in #balance before changing and TMing it again into a weaker version, please.
The old M39 is not bad, it's just burst focused.

**Comment by Pariah919** [comment]
I'd recommend just tossing the idea of buffing the SMG-
In my honest opinion, it's still too good in it's un-buffed state and really should gain minor slowdown (0.15)

**Comment by Pariah919** [comment]
rohesie asked me to give me this my salt man seal of approval so I approve of these changes I guess

**Comment by davidchan13** [comment]
Smg too good... What?

**Pull request merged**
