### PR TITLE
combat shotgun can be fired one handed

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
combat shotgun can be fired one handed 

## Why It's Good For The Game
a much needed buff to a near useless gun

## Changelog
:cl:
balance: you can fire the combat shotgun one handed
/:cl:

### CODE REVIEW

**Comment by Jeff-jefferson-jeffery** [comment]
mjp what the fuck are you doing

MJP, please continue

**Comment by lKiseki** [comment]
no
stop

**Comment by SpaceLoveSs13** [comment]
I feel like this is a bait to nerf combat shotgun in future. But oh well, the idea sounds quieky but eh makes sense.

**Comment by David-Stormwell** [comment]
@Pariah919 Give us the math for damage output of buckshot and flechette with combat shotgun, bayonet added

**Comment by Al-1ce** [comment]
I have the strangest feeling the CS was added for this exact sole purpose to be later implemented (because it wouldn't make it past the addition PR)

sure

**Comment by ilikesaying** [comment]
**wheeze**

**Comment by Ragecrabbo** [comment]
Stealth shield buff? 
Also wouldnt this make reloading absurdly fast since you wouldnt need to unwield and wield the weapon again to shoot? I suppose it all depends on if you'll be able to hit anything at all shooting one handed.

**Comment by Pariah919** [comment]
> Give us the math for damage output of buckshot and flechette with combat shotgun, bayonet added
>
grab a pump with a stock and a bayonet and reduce it by 30%

136 with bayonet on t39 w/ flech (this might seem big but you have to remember 45 of this is ALSO checked on melee armor, so the actual damage is less than it seems, usually.)
213 with buckshot and bayonet though buckshot will do less damage because of how the knockback works on stunnable castes
If you have a pump shotgun and good hands because you can fire while wielding you'll deal more damage overall, so this is just a sidegrade, as it is. As a pump shotgun with agrip/no stock has little to no wield delay already. And you can't rip the stock off the combat shotgun, so I don't see a reason to not give it a small edge to it's peers

**Comment by ZahaSanko** [comment]
oh god it's happenin

**Comment by Captiajoe** [comment]
This is gonna be **great**

**Comment by davidchan13** [comment]
INB4 people dual wield and do 2x the damage of a pump, or use a shield and 2 combat shotguns for constant fire.

**Comment by AnCopper** [comment]
MJP is insane.

**Comment by usnpeepoo** [comment]
finally, dual shotties coming home

**Pull request merged**
