### PR TITLE
Combat Patrol tips of the round

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Adds some tips that are relevant to HvH. Leave comments if you have any more ideas.

I assume keyholders need to do some config thing to actually use this new file, I couldn't see anything in code.

## Why It's Good For The Game
More useful tips.

## Changelog
:cl:
add: Adds some tips of the round for HvH
/:cl:

### CODE REVIEW

**Comment by zzurge** [comment]
secure medbay or middle ground,lock it down and if your forces deplete hold the line long enough for respawn wave,flanks flanks flanks

**Comment by zzurge** [comment]
wasd your way around bullets like neo,DANCE MONKEY DANCE!!

**Comment by zzurge** [comment]
sacrifice your firstborn son for a combat mech,he will understand the glory of Mars is eternal.

**Comment by Serxule** [comment]
tip idea: remember: spawncamp the other team, they literally cant fight back.

**Pull request merged**
