### PR TITLE
Adds cleaning supplies to the NanotrasenMed Plus

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
Adds sterilizing spray (100u spray bottle) and ***limited*** amounts of Soap to the vendor.
## Why It's Good For The Game
Nice to keep the Medbay clean, and I made sure the soap is limited to limit grief by slipping people. Good on the conscious to not have to take from Medbay when you want to clean yourself for field surgery, too; even if there is usually some spray bottles there. Soap is already available on the shipmap, just making it more easily accessible to doctors who don't memorize the spawns.
## Changelog
:cl:
add: Added soap and sterilizing spray bottles to the NanotrasenMed Plus
/:cl:

### CODE REVIEW

**Comment by DeltaFire15** [comment]
I'm sure the soap change isn't in any way related to its disinfection potential for field surgery, and just for cleaning.

**Comment by Barnet2** [comment]
> I'm sure the soap change isn't in any way related to its disinfection potential for field surgery, and just for cleaning.

That is another reason why it is limited, in addition I gave unlimited spray bottles for field surgery, which could also be found enmass in medbay already. If QV wills it I will kill the soap change, but you can already find soap in ***various*** spots around the ship.

**Comment by ClosetedSkeletonGH** [comment]
> I'm sure the soap change isn't in any way related to its disinfection potential for field surgery, and just for cleaning.

soap isnt on everyship so having your time as MD being determined by if youre on theseus or not isnt cool

**Comment by RipGrayson** [comment]
> soap isnt on everyship so having your time as MD being determined by if youre on theseus or not isnt cool

Every ship has soap has except Minerva, albeit not always in medbay itself.

**Review by QualityVan — APPROVED** [review]

**Pull request merged**
