### PR TITLE
Deletes distress signal

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Completely deletes distress and mechanics specific to it (so just siloless collapse) + a random hunt type marco

TM THIS PLEASE IT CAN BREAK A BUNCH OF STUFF
## Why It's Good For The Game

We don't use this gamemode, and it just dirties up the path for nuke war
## Changelog
:cl:
del: Deleted the distress signal gamemode
/:cl:

### CODE REVIEW

**Comment by Luxyboo** [comment]
BRING IT BACK

**Comment by Lumipharon** [comment]
I guess its a problem for the future, but this may make it more inconvenient to make other HvX modes going forwards. I can't remember whats in infestation tho

**Comment by Strayed-Raven** [comment]
We do not keep dead code. Remove it.

**Comment by ivanmixo** [comment]
> I guess its a problem for the future, but this may make it more inconvenient to make other HvX modes going forwards. I can't remember whats in infestation tho

Infestation is the baseline xvh gamemode, not distress. Everything that has xenos is infestation apparently.

**Comment by chizzy376** [comment]
> We do not keep dead code. Remove it.

The 500+ unused assets, sprites, undeclared and unused variables:
(Yes these are real, I found many by combing through a local tgmc copy)

**Comment by Al-1ce** [comment]
Xenos still think "it's xover" when a single silo dies.
Marines still think "we've won" once they've killed a silo.

Secretly, distress is still hardwired into our monkey & alien brains.

-1 from me.

**Review by TiviPlus — APPROVED** [review]

**Comment by Kapu1178** [comment]
Seeing siloless collapse & the Hunt gamemode go makes me a little sad.

**Comment by ivanmixo** [comment]
Hunt is already gone for quite a long time and I plan on reintroducing a psuedo siloless collapse and this will allow me to implement it more cleanly.

**Pull request merged**
