### PR TITLE
Wo refitting

### PR DESCRIPTION
**Pull request by KwinOriginal**
## About The Pull Request

Adds an updated, old WO map with even little layout changes. Everything that needed it was modernized. Hopefully some errors removed, too.

## Why It's Good For The Game

If the Cimex or similar AI enemies might arrive eventually, WO would be a very nice map to fight endless waves of them. Now one of the steps is done, no more excuses for the missing map!

## Changelog
:cl:
add: updated WO map
/:cl:

### CODE REVIEW

**Comment by KwinOriginal** [comment]
WO

That's the map as it looks now. I did no code changes, though

**Comment by Rohesie** [comment]
Nice. Do extend the fog inside the cave walls, as plasma cutters could break it.

**Comment by Timmeye** [comment]
Forcefields are very useful, nothing can cross them
also unbreakable minerals (rocks) exist

**Comment by DominikPanic** [comment]
Let us know when it's done.

**Comment by spookydonut** [comment]
travis is being travis this compiles fine

**Comment by spookydonut** [comment]
@KwinOriginal step_x/y in the mapfile

**Pull request merged**
