### PR TITLE
Removes Big Red's Modular LZ's

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
Replaces the modular object in Big Red's LZ for a static LZ, removes the associated .dmm's and objects.
## Why It's Good For The Game
LZs are pretty important balance wise, and the goal of modulars is to provide a fresh experience every round without much cost to the overall flow and balance of the map; it is extremely hard to accomplish that with LZ's compared to any other area of the map. Here are the two LZ variations picked:
image
image
After this people are free to edit the basemap of BR for these LZs, if they prove to be too bad (the only concern is NE LZ 1, that is pretty easy to breach. I may make a follow-up PR on that if need-be)
## Changelog
:cl:
del: Removed all Big Red LZ modulars, replaces them with a static LZ for each spot.
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
now demodularize the rest of it

**Comment by RipGrayson** [comment]
> now demodularize the rest of it

No

**Comment by chizzy376** [comment]
> I like the different LZs. Changes things up a little each round.

Except when you get hit by the office lz1 and now you have to build 5x5 cubicles or the engi in charge of fob tells someone else to make fob.

**Review by RipGrayson — APPROVED** [review]

**Comment by Xander3359** [comment]
A light appears at the end of the tunnel

**Pull request merged**
