### PR TITLE
SL Kit additions

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Adds SL kits (Thermo/Mateba/BR8/Autosniper) for 40 point range weapons.
image
## Why It's Good For The Game
I believe SL needs more options to spice up their gameplay, as picking SL is usually a big burden mentally. So they deserve a bit more fun.
## Changelog
:cl:
add: Added SL kits. Currently has Mateba, BR8, Autosniper and Thermobaric SL kits avaliable.
/:cl:

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
people will just pick this to powergame lmao

**Comment by Ragecrabbo** [comment]
return to spec

**Comment by Tupinambis** [comment]
Probably a terrible idea, it'd be better to give them more utility options. Access to req armor modules, defib gloves, insuls, etc. Would be a good start.

**Comment by Luxyboo** [comment]
BASED

**Comment by Losenis** [comment]
Xenos about to get memed with quad autosniper roundstart

**Comment by Pariah919** [comment]
i have something else in mind now

**Comment by KerbalCitizen** [comment]
BR-8 is really good, legit better than T29 (and therefore SG85). Very high sunder per second, I believe the DPS is also better, probably less slowdown. Only downside is small mag capacity, but the low rof helps deal with that. 

I believe FC and captain get mateba for free, rarely see it used groundside. Mateba seems like a meh weapon at best, more of a sidegrade than a direct upgrade. Stun is useful but situational. 

Autosniper is also kinda a sidegrade. I remember hearing DMR has better DPS, not sure if that was calculated with or without aim mode rof penalty. The ammo costing req points is a pretty major downside. Being able to move around while sniping could be useful, but ultimately doesn't seem good enough to make up for it. 

Quad thermobaric launcher is a bit of a meme. 4 round burst seems pointless from the times I've seen it. Reload is very long. A GL with WP nades seems much better in general. 

The balance of this seems like its completely off. BR-8 is just so much better than all the other choices, unless you are trying to do a very specific niche.

**Comment by Losenis** [comment]
Autosniper has NVG too

**Comment by FIXTHERADBOXPLEASE** [comment]
Kerbal you're wrong... autosniper is easily the best choice. The DMR only has better DPS at near-point blank. There's a reason the meta on ruTGMC is still buying as many autosnipers as possible.
The Mateba is also very good, combination of a revolver and slug shotgun, it's just that no one is familiar with how to use it. Black Box Rockets are a 100% secured kill on any xeno if you don't waste the ammo.

This PR was basically specs 2.0, but the facts have to be corrected.

**Pull request closed without merging**
