### PR TITLE
Fixes resin hole chain stun

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
I dunno why this stuns for 4 whole seconds but uh, chain stunning is generally bad.
## Why It's Good For The Game
Infinite brazil memes bad.
## Changelog
:cl:
balance: Resin holes can no longer chain stun
/:cl:

### CODE REVIEW

**Comment by Strayed-Raven** [comment]
Four years. FOUR. YEARS. Finally.

**Comment by FIXTHERADBOXPLEASE** [comment]
Thank god...

**Comment by novaepee** [comment]
image

https://www.youtube.com/watch?v=oExrq6vkl4g

**Comment by iforgotmeword** [comment]
boo

**Review by ivanmixo — APPROVED** [review]
Sad

**Pull request merged**
