### PR TITLE
WALANCE - WIDOW BUFF - Spider can now web (maze)- Complete

### PR DESCRIPTION
**Pull request by Lauwma**
## About The Pull Request

Widow gains mazing abilities:
plant_weeds,
secrete_resin/widow,
secrete_special_resin,

Spiderlings can now be built on with resin structures

## Why It's Good For The Game

Widow is a very situational xeno that has a lot of downtime and heavily profits from having very specific types of mazes. Giving widow maze capabilities would give it the edge necessary to reinforce its traps setup and flanks while furthering its spidery vibe that creates a nest. 
Its plasma economy is shit though so I may have to change that so it is able to maze without resting after 3 walls.
Also based builder T3 and opens ways for a new primo 

## Changelog
:cl:
add: Widow can now plant weed 
add: Widow can now secrete resin walls
add: Spiderlings can be built on with resin structures
balance: Widow gains mazing abilities, be careful when stepping in the Widow's nest
/:cl:

### CODE REVIEW

**Comment by Wisemonster** [comment]
Not really sure widow needs access to blessings menu (not sure why hivelord has it to begin with, but that's off topic for this pr)

**Comment by novaepee** [comment]
the t3 hivelord
what we needed the most
on god

**Comment by Lefunny** [comment]
Tbh i think thats just skill bloating a t3 for zero reason other than "looks like it would do that" i'm not against a builder t3 neither transforming widow in one i just think it should firstly be actively reworked instead of just be getting hivelord skill package

**Comment by hivemuscle** [comment]
that's a real great idea! widow will be finally stronger than puppeteer (t2) but not just in banal "i have more damage, HP and armor" way. sometimes you really lack the ability to build mazes as a puppeteer and are forced to fight in open areas, so now reason to evolve into a widow exist.

**Comment by Aroliacue** [comment]
Awesome way to start off on the track to buffing Widow, you know its bad when a T3 is almost completely equivalent to its T2 equivalent (Puppeteer) besides some niche abilities

I know a lot of people will probably say, 'ERRMM AKTUALLY' but that's been my experience both fighting against and playing as these castes. I do not feel as much fear seeing a Widow in a maze as I do seeing a Puppeteer in one

**Comment by Arturlang** [comment]
Xenos could use more builders, and having a combat builder would be cool...

**Review by Kuro020 — CHANGES_REQUESTED** [review]
I would rather it have unique skills than literally ctrl c ctrl v of hivelord's skills

**Comment by Naaanii** [comment]
If it can plant weeds, I'd give it pheros too.

**Comment by Kuro020** [comment]
castedatum changes will conflict with my xeno buffs pr, should prolly wait for it to get merged

**Comment by Lauwma** [comment]
> castedatum changes will conflict with my xeno buffs pr, should prolly wait for it to get merged

Okay 👍

**Comment by chizzy376** [comment]
Let widow build nests and cobwebs because funny spider
Jokes aside looking forward to this, always wanted to be a builder without being a t2 main

**Review by TiviPlus — APPROVED** [review]
code ok

**Review by Kuro020 — CHANGES_REQUESTED** [review]
ok well, widow shouldnt really have tunnels

**Comment by Woker2004** [comment]
> ok well, widow shouldnt really have tunnels

I caused this thought, was funny

**Pull request merged**
