### PR TITLE
update atomns init

### PR DESCRIPTION
**Pull request by TiviPlus**
I just copy pasted Tgs file for this and tweaked it for us, tm before merge

### CODE REVIEW

**Comment by TiviPlus** [comment]
```mermaid
pie title test Pie
    "1" : 10
    "2" : 99
    "3" : 150
```

**Comment by novaepee** [comment]
image

Something happened in weapon tab. The rest in req is fine.

**Comment by AGasCanister** [comment]
> image
> 
> Something happened in weapon tab. The rest in req is fine.

image
the long description causes it

**Comment by RipGrayson** [comment]
This PR appears to be inconsistently causing modular spawns to break as reported in https://github.com/tgstation/TerraGov-Marine-Corps/issues/9811.

dreamseeker_VRQaT2xCzh

Before anyone asks I did locally test this branch with no other PR TM'ed to make sure it was this one that caused the breaking.

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
