### PR TITLE
Adds lever action rifle to standard vendor

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request

Adds the lever action rifle to the standard marine vendors.

## Why It's Good For The Game

It's literally the revolver but worse. This just allows for more yeehaw in our lives.
I tested it out on a local server, worked fine.

## Changelog
:cl:
add: lever action .44 rifle to vendors.
/:cl:

### CODE REVIEW

**Comment by Jeff-jefferson-jeffery** [comment]
maybe

**Comment by Pariah919** [comment]
We don't need to add every gun in  the game to marine vendors.

**Comment by Kuro-ai** [comment]
That sprite is shit,no

**Comment by Knuff-les** [comment]
I order it roundstart at req so I don’t see an issue with it, but last I used it a day ago it didn’t have the right back sprites, as it still used the old ones, and it has no inhand sprites so that might be an issue

**Comment by TiviPlus** [comment]
> That sprite is shit,no

It doesnt have its own sprite because the sprite got removed and replaced with the mbx one so get a proper sprite for this pr to be considered

**Comment by DerrickChamberlain** [comment]
Close but no cigar

**Pull request closed without merging**
