### PR TITLE
Add extra attachments to the ERT shuttles.

### PR DESCRIPTION
**Pull request by psykzz**
## About The Pull Request

Add extra attachments to the ERT shuttles. 

## Why It's Good For The Game

Allows for stronger weapons and easier balance for the ERT.

## Changelog
:cl:
add: Added new attachments to the ERT shuttle.
/:cl:

image

### CODE REVIEW

**Comment by Rohesie** [comment]
As discussed in #balance , rebalance the weapons if you want to make them stronger.
Attachments are made for weapon variations, not for buffing them.

**Comment by Alterist** [comment]
Should probably be done with creating a crate/locker subtype with the attachments inside, then adding that to the map, instead of pure map edits

**Comment by spookydonut** [comment]
> 
> 
> Should probably be done with creating a crate/locker subtype with the attachments inside, then adding that to the map, instead of pure map edits

Yep!  `/obj/structure/closet/crate/ert_attachments`

**Comment by Rohesie** [comment]
This shouldn't be made through attachments at all, unless the objective is to add customization options.

**Comment by Rohesie** [comment]
Closing this PR.
Stronger weapons should be achieved via weapon stat changes, and this doesn't make it easier to balance it.
If anything, ERT weapons shouldn't be accepting most attachments.

**Pull request closed without merging**
