### PR TITLE
Flick overlay view/item pickup/drop animation optimization

### PR DESCRIPTION
**Pull request by TiviPlus**
believe it or not, using GLOB.clients in a for loop for something that absolutely does not need it scales horribly

### CODE REVIEW

**Comment by TiviPlus** [comment]
sister pr https://github.com/tgstation/tgstation/pull/71156

**Review by Lumipharon — APPROVED** [review]

**Comment by SplinterGP** [comment]
honestly this doenst even need flick_overlay() which should actually be called flick_image_to(), could just add it as an overlay and remove afterwards(an actual flick_overlay())

**Comment by TiviPlus** [comment]
overlays didnt work cus the animation changes the appearance which means you cant remove it after

**Comment by TiviPlus** [comment]
also this has 1 or 2 bugs see sister pr so hold off on merge

**Pull request merged**
