### PR TITLE
replaces the machete we have with one you can attach to your gun

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
the title basically

## Why It's Good For The Game
I think its cool but eh.
Let's people have cool sword bayonets
should probably get a better sprite

## Changelog
:cl:
add: Added new machete you can attach to your gun
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
image

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -51. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Hathkar** [comment]
Machetes on guns is a bit too silly.

Also
``melee_mod = 40``

**Comment by jroinc** [comment]
You want to put a sword.

A full-size sword. 

A 3-4 foot-long sword, balanced for slashing.

On the end of your gun.

The gun that in itself is about 3-feet long.

Sure. Just throw in an actual scatter mod that has effects, not a negligible accuracy reduction, and up it 1 size category. Yes, this means you can't hold it in suit storage.

**Comment by Pariah919** [comment]
>Sure. Just throw in an actual scatter mod that has effects, not a negligible accuracy reduction, and up it 1 size category. Yes, this means you can't hold it in suit storage.
>
It doesn't do anything.

**Comment by TiviPlus** [comment]
uhhh nooo?

**Comment by Hathkar** [comment]
This is really seems like a bad idea. The idea doesn't make sense, the stats are bonkers.

**Comment by Autisem** [comment]
Seems a little dumb to have a machete on your gun, especially since bayonets already are a thing that everyone has access too

**Comment by TiviPlus** [comment]
Closing because a machete mounted on a gun is wierd and because yea stats are high

**Pull request closed without merging**
