### PR TITLE
Synth can now wear M3 marine harness (IGNORE apparently I did something wrong.)

### PR DESCRIPTION
**Pull request by Derrick2Electricboogaloo**
## About The Pull Request

Synth could never wear the M3 pattern harness. Why? it has no armor already this appears to be an oversight.

## Why It's Good For The Game

I want a compelling reason why this is bad for the game. Gives the synth more options for wearing stuff and it is absolutely an oversight when TGMC forked off from CM.

## Changelog
fix: Remove synth restriction from M3 harness.
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
Ah, it added the map shit from my other PR, fuck.,

**Comment by Derrick2Electricboogaloo** [comment]
I guess I will wait until my Sulaco stuff gets merged since I can not figure out how to seperate these two

**Comment by Derrick2Electricboogaloo** [comment]
I just wanted one file change for gods sakes POOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Derrick2Electricboogaloo** [comment]
okay I will figure this out when I wake up. Stupid git.

**Comment by Moggram** [comment]
Don't let it get to you bro. Remember you can always ask for help on discoed.

**Comment by Derrick2Electricboogaloo** [comment]
> 

Hahaha, yeah. I probably have to update my master, then try to push it. Going to ask how to undo the map file implementations in this PR.

**Comment by Derrick2Electricboogaloo** [comment]
Going to close for now, until I fix the issue of other files being here. This is not permanent.

**Pull request closed without merging**
