### PR TITLE
SG Minigun balance

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

1. SG minigun firerate from .1 -> .15
2. SG minigun windup delay from .75 -> .4
3. SG minigun damage multiplier from .8 -> 1
4. SG minigun damage per bullet from 10 -> 15
5. Removed smartgun type bullet and the tank weapon that used it (Both were unused)

## Why It's Good For The Game

1. Right now the minigun is a bit too fast
2. Windup delay was a copy paste from MJP's original minigun I forget to change (shouldn't affect too much)
3. The SG minigun has its own bullet type and doesn't need a damage multiplier (Another copy paste forget)
4. Less firerate means more damager per bullet to maintain a DPS similar to the SG-29
5. Unused, removed to reduce confusion between actual SG weapon ammo

## Changelog
:cl:
balance: SG minigun fires slower and does more damage
fix: SG minigun is now consumer safe and no longer bullies low end devices
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
It may be beyond the scope of this pr but is it possible to have ammo boxes made to refill the powerpack with that could be put in the G8 belt storage? Absolutely loathing powerpacks when you're stuck to one single slot for ammo and don't even have half the ammo a T60 dunga could have.

**Comment by Arctrooper8** [comment]
> It may be beyond the scope of this pr but is it possible to have ammo boxes made to refill the powerpack with that could be put in the G8 belt storage? Absolutely loathing powerpacks when you're stuck to one single slot for ammo and don't even have half the ammo a T60 dunga could have.

Brilliant idea, that'll be my next PR

**Comment by KornFlaks** [comment]
I am quite concerned about this IFF Minigun buff.

Reducing windup and increasing damage by 87.5% (damage mult increased by 1.25x times damage value increased by 1.5x = 1.875x) while only reducing fire rate by 50%? 

This needs some testing on time to kill before merging. Please.

**Comment by Arctrooper8** [comment]
> I am quite concerned about this IFF Minigun buff.
> 
> Reducing windup and increasing damage by 87.5% (damage mult increased by 1.25x times damage value increased by 1.5x = 1.875x) while only reducing fire rate by 50%? I would expect only the damage value to be changed to remain the same as the current minigun.
> 
> Nor does this touch it's sunder value which is the main concern of this gun. Now we increase the damage as well? Please, we're not blind.
> 
> This needs some testing on time to kill before merging. Please.
> 
> I know it's not gonna happen and instead speedmerged but still, I would like to think that this might get tested before we see it permanently on the battlefield. Unlike the... IFF minigun itself.


I just used the values that MJP suggested. And yeah, the SG minigun should've been TM'd but oh well, that's why I'm making these Knee-jerk reaction PRs.
I'll do a bit more mathematics and testing though, thanks for the feedback.

**Comment by Lumipharon** [comment]
> I am quite concerned about this IFF Minigun buff.
> 
> Reducing windup and increasing damage by 87.5% (damage mult increased by 1.25x times damage value increased by 1.5x = 1.875x) while only reducing fire rate by 50%? I would expect only the damage value to be changed to remain the same as the current minigun.
> 
> Nor does this touch it's sunder value which is the main concern of this gun. Now we increase the damage as well? Please, we're not blind.
> 
> This needs some testing on time to kill before merging. Please.
> 
> I know it's not gonna happen and instead speedmerged but still, I would like to think that this might get tested before we see it permanently on the battlefield. Unlike the... IFF minigun itself.

Nerfing firing rate from 0.1 to 0.15 cuts the sunder/second by a third. Still fairly high though.

**Comment by goose4429** [comment]
You should decrease sunder further, it's still pretty high at 13/sec. For each second under fire, beno needs to rest on white weeds under rec pheros for about 15 secs. Not very cool.

**Comment by turnop** [comment]
> You should decrease sunder further, it's still pretty high at 13/sec. For each second under fire, beno needs to rest on white weeds under rec pheros for about 15 secs. Not very cool.

Or they just need to use armor fruit that literally nobody ever uses, or fight at less than 100% armor (after a full second of concentrated minigun fire mind)? This looks good to me, the 85 definitely needs a buff though I am sad that it will brrt less

**Comment by Losenis** [comment]
[Laughs in Gorger]

**Comment by Arctrooper8** [comment]
> Or they just need to use armor fruit that literally nobody ever uses, or fight at less than 100% armor (after a full second of concentrated minigun fire mind)? This looks good to me, the 85 definitely needs a buff though I am sad that it will brrt less

Sadly too much Brrrrt kills Russian computers, perhaps one day when we evolve from the limitations of Byond we shall reach enuff Dakka

**Comment by Arctrooper8** [comment]
A lot of people don't seem to be considering the fact that most Xenos dodge, hide behind cover, or the fact that SG weapons have always had the niche of high sunder. You're not gonna hit every single shot, and you're certainly not gonna hit any shots if the Xenos get close to you.

**Pull request merged**
