### PR TITLE
Removes the Bull from the game

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title. Removes Bull entirely from the code.

## Why It's Good For The Game
Nobody is going to rework Bull, we've given it far too much time and it's just the same boring and broken mess. Better to just remove it. If anyone wants to rework it, they can just readd it later.

## Changelog
:cl: Lewdcifer
del: Bull, the xeno tier 2 caste, has been removed from the game.
/:cl:

### CODE REVIEW

**Comment by FIXTHERADBOXPLEASE** [comment]
Salt PR?

**Comment by Barnet2** [comment]
Best PR since ever, speed merge instantly.

**Comment by bowlofcereal** [comment]
clown-face_1f921

**Comment by FIXTHERADBOXPLEASE** [comment]
Salt PR?

**Comment by FIXTHERADBOXPLEASE** [comment]
Just change or remove the buggy, broken primo that lets you instagib marines. Bull without the primo serves a perfectly fine role as a mix of Runner 2.0 and Crusher 0.5. Only reason I'm not actively playing it is because Warrior outshines all other frontliners in the current meta.

**Comment by Coastfront** [comment]
I remember seeing someone in dchat saying that they hate bull and wish it wasnt in the game, guess they might get what they wished for.

**Comment by Oscari-pog** [comment]
Akimbo SMG gets a slight nerf that doesnt change anything
Bull gets straight up nuked from the game
Society

**Comment by lKiseki** [comment]
Sweet baby jesus on a holy cow I can't believe someone's changing Bull.
Bye PR. Go praise #11391.

**Comment by Wayland-Smithy** [comment]
👀

**Comment by lKiseki** [comment]
The Bull changes didn't go through, so we return.

**Comment by srxtreme** [comment]
Salt PR?

**Comment by MiniMeatwad** [comment]
Killing primordial bull? Yes please, incinerate it with hellfire.

Killing bull? Although you can't guarantee 10 marine kills per round with it, it's not a shit caste, it's just a niche caste. Maybe I am the only bull player, but it's rather fun, and removing the entire caste because you don't like the primordial is silly.

**Comment by lKiseki** [comment]
If mech can stay then so can Primo Bull.

**Comment by Luxyboo** [comment]
HOLY SHIT THIS IS BASED BEYOND BELIEF

**Comment by Losenis** [comment]
> If mech can stay then so can Primo Bull.

Lost all the respect I ever had for you tbh

**Comment by Wayland-Smithy** [comment]
Mech is fine. It's all the other req bullshit toys that make primo bull look weak by comparison. *Looking at you AMR*

**Pull request closed without merging**
