### PR TITLE
Sharable NanotrasenMed Plus & rebalancing the NanotrasenMed Plus

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Shared NanotrasenMed Plus is important to keep medical balance in check.

There are two types of NanotrasenMed Plus; planetside and shipside.

Shipside NanotrasenMed Plus cannot be wrench.

Shipside NanotrasenMed Plus shares among each other.

Planetside NanotrasenMed Plus does not share among each other.

Rebel NanotrasenMed share among each other but cannot be wrench.

Shipside NanotrasenMed Plus does not make contact with Vahalla.

Makes med rework a bit easier now that NanotrasenMed Plus is accounted for.

## Why It's Good For The Game

People forgot about NanotrasenMed Plus, so it's not shared, meaning that all shipside maps have different amount of particular medical supplies on them.

If #9525 gets merged before this PR, it will conflict, but easy to solve.

## Changelog
:cl:
code: Difference between shipside and planetside NanotrasenMed Plus
add: shipside NanotrasenMed Plus is now shared
balance: All shipside shall have the same amount of medical supplies that come out of the shipside NanotrasenMed Plus
balance: shipside NanotrasenMed Plus cannot be moved
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
Accountability on medical supplies in NanotrasenMed Plus:

The inventory:
image

Numbers of NanotransenMed Plus in each shipside map
image

With this PR alone, this effectly reduce:
PoS med supply from NanotrasenMed Plus by 3
Theseus med supply from NanotrasenMed by 4
Minerva and Sulaco med supply from NanotrasenMed by 6

This means that

1) HealthHud is reduced to only 2, which forces shipside maps to have at bare minimum 6 HealthHud (the four you can find in the medic vendor)
2) Advanced burn and brute kit reduced to 5 from NanotransenMed Plus 
3) reagent bottles as a whole is reduced

image

**Review by BraveMole — CHANGES_REQUESTED** [review]
:/

First some of those vendors are in vahalla, other groundside, other shipside, so sharing them is wtf.

Second, why are you not changing the amount of stuff inside that vendor?

**Comment by Mrrpip** [comment]
I don't want to have to beat someone over the head to get one of two Russian Red pill bottles ._.

We should probably up the supply ammount.

**Comment by Mrrpip** [comment]
To add on to the prior comment.

The NT+ is moveable, if it's on Tad and shared, what's to stop you from feeding in X neccesity in trough the shipside vendor?

**Comment by novaepee** [comment]
> some of those vendors are in vahalla, other groundside, other shipside

The Vahalla ones are their own vendors.

Will need to see how to not connect shipside from planetside. Unwrenchable fits that profile and having to make new vendors for planetside.

**Comment by novaepee** [comment]
> Second, why are you not changing the amount of stuff inside that vendor?

There is currently no established baseline for NanotrasenMed Plus medical supply. The one that comes to mind is PoS since it has the lowest inventory, so we can model after that.

I was planning to make another PR for accounting the nerf, but it sounds like this is the PR for that.

**Comment by novaepee** [comment]
> The NT+ is moveable, if it's on Tad and shared, what's to stop you from feeding in X neccesity in trough the shipside vendor?

I will think of a new vendor for tadpole to use that is not the NTMed +.

**Review by TiviPlus — APPROVED** [review]

**Comment by Losenis** [comment]
image

Nerfing healbus to actual oblivion ft. Valibros nabbing all the reagent bottles. This sounds more like a mapping issue of abnormal vendor counts.

**Comment by TiviPlus** [comment]
Use a crate

**Comment by Losenis** [comment]
Well shit healbus is straight up dead

**Pull request merged**
