### PR TITLE
AMR normal pen reduced to 50, lase pen mult reduced to 1.25 from 1.7, sunder readded on normal ammo.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
80->50.
0->5 sunder.
It multiplies by 1.25. Lase hits up to 62.5.
Nerfs other ammos by proxy.

## Why It's Good For The Game
AMR is pretty overtuned, and the lase changes are overtuned in hindsight, might need further pen nerfs though, still.

## Changelog
:cl:
balance: AMR Normal ammo pen reduced to 50 from 80, lase pen multiplier 1.25 from 1.7. Sunder readded on normal ammo.
/:cl:

### CODE REVIEW

**Comment by InterroLouis** [comment]
Legit you're going to try and make it worse than before the buff?

**Comment by Pariah919** [comment]
>Legit you're going to try and make it worse than before the buff?
>
it went from 80/60/15 to 90/50/5, i guess i could move up the sunder back to 15. But the damage is still higher than before (Far higher) so i think its fine like this?

**Comment by goose4429** [comment]
To continue our sweet talk, #10052 got merged as well, probs should reduce the nerfs.
And IMO the pen should be higher, it certainly should have a role of strong anti-armor rifle.

**Comment by Pariah919** [comment]
#10052 got merged

**Pull request closed without merging**
