### PR TITLE
Makes xenomorph health/sunder healing, evo progress, maturity, and plasma regen scale based on delta_time/second_per_tick

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Makes xenomorph health/sunder healing, evo progress, maturity, and plasma regen scale based on delta_time/second_per_tick, also makes some of the xenomorph status effect buffs also use this system for their ticking healing 
## Why It's Good For The Game
In cases where lag gets really bad, this can really help, as each tick will heal more based on how much time has passed since the last time it has run. 
## Changelog
:cl:
add: Xenomorph life will now adjust the amount of healing/sunder/plasma/evo/maturity based on any extra time that Life has not run for.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Later it's probably smart to add this to stuns, chems, anything else that happens constantly

**Comment by Arturlang** [comment]
Tested normal xeno regen stuff, gives you the same current healing as it does currently while there is no lag

**Review by TiviPlus — APPROVED** [review]

**Comment by MiniMeatwad** [comment]
I believe we have a delta_time in the master controller

**Comment by Arturlang** [comment]
note, seconds_per_tick is a STATIC VALUE, because wait is static
image

**Pull request merged**
