### PR TITLE
increase head max damage to 150

### PR DESCRIPTION
**Pull request by BobSlim**
## About The Pull Request

1 variable change, head increased hp

## Why It's Good For The Game

better for people without helmets

if you've taken 150 brute damage and you don't have a helmet for some reason you're dead anyway.

this just means that people without helmets won't also have an effective decrease in hp by 2/3.

## Changelog
:cl:
balance: increased the amount of damage (100 -> 150) heads can take before decap. Hurrah for headbands!
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
cringe!
Too much of a marine buff. Even for me!

**Comment by Hughgent** [comment]
Suffer for your fashion choices

**Comment by Rohesie** [comment]
I'm not against this.

**Comment by XElectricX** [comment]
I'd rather limb reattachment be implemented but this is fine.

**Comment by AdamElTablawy** [comment]
if you aren't wearing a helmet you deserve to die

**Pull request merged**
