### PR TITLE
tadpole 3 tile cade all sides

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
tadpole now has 3 tiles of cades on all sides

image

## Why It's Good For The Game
more space for tadpole

## Changelog
:cl:
balance: slightly more space for tadpole
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
FAT

**Comment by Strayed-Raven** [comment]
While you are at it. Give TAD the ability to play music ala Vietnam

**Comment by iLikeMemes** [comment]
Thats not a tadpole, thats a fucking frog

**Comment by Serxule** [comment]
this makes tad less maneuverable, dont really like it

**Comment by tyeagg** [comment]
> this makes tad less maneuverable, dont really like it

what is that even supposed to mean

**Comment by FIXTHERADBOXPLEASE** [comment]
> this makes tad less maneuverable, dont really like it

This is the same width as the normal tadpole?

**Comment by tyeagg** [comment]
> > this makes tad less maneuverable, dont really like it
> 
> This is the same width as the normal tadpole?
yes
image

**Comment by MereWalker** [comment]
I love how players are upset with tadpole being "bigger" when it's the same thing just removed two walls. It's alright with me. If you can please adjust the sentry sprites they are off. Keep getting ahelps regarding "help I can't set the sentry" and which I have to spawn in and show them they need to look harder.

**Comment by Weedmaster77** [comment]
I love and hate it. It make its easier to shot out of but also make it easier for xenos to breach and get gas clouds farther in with less place to hide from them. If there was a way for PO or who ever to PC the wall out so they could pick if they wanted 3 or 2 cades that would be better but just my opinion.

**Comment by Naaanii** [comment]
Looks less like a ship honestly. While the QoL is nice, I think the walls serve a bit better purpose than being open.

**Comment by Starfirejordan** [comment]
this is feel like a nerf honestly

**Review by Pariah919 — COMMENTED** [review]
Looks uglier.

Balance wise I'm unsure if I like this, but it seems like a "Test and give feedback later" case to me.

**Comment by FosterGrime-Heymynameslouie** [comment]
> I love and hate it. It make its easier to shot out of but also make it easier for xenos to breach and get gas clouds farther in with less place to hide from them. If there was a way for PO or who ever to PC the wall out so they could pick if they wanted 3 or 2 cades that would be better but just my opinion.

This

Make it so that the wall acts like a rock wall where you can either leave it be or PC it, so tad people have the option to go with the old or with the new? Good compromise I think

cool pr nonetheless

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: fd13cccb034c3ed8b1e7f742ecb93ac14c7e70a6
Pull Request: 47fe525df55e420ea5998c532757a55ab2322b65
Server: 932d5fc994524e8e809075a694fc03e13400a193

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: fd13cccb034c3ed8b1e7f742ecb93ac14c7e70a6
Pull Request: 47fe525df55e420ea5998c532757a55ab2322b65
Server: 03bfcac3bdfdd9dab131bb3b9be127e451515037

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\naaanii

##### Revision
Origin: d9f05eb44f958814783b33f5e725a88de2ce56cb
Pull Request: 47fe525df55e420ea5998c532757a55ab2322b65
Server: a1f8f0c0a902ff188116e56b2f95f1572f222a74

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: f672f018d98fbc3542ada38d6260f37d4c50d0e3
Pull Request: 47fe525df55e420ea5998c532757a55ab2322b65
Server: 0f2e13d46370ed4b71632488688e40bdd3acef2e

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: fd0c8e2705b023a4e1b22feff1b96b8908cce6a1
Pull Request: 47fe525df55e420ea5998c532757a55ab2322b65
Server: f4842f3380ec3cf27cf7ef503c540da2c545ff38

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 244e28c96322ec39d06af2ab8d05ce6051299714
Pull Request: 47fe525df55e420ea5998c532757a55ab2322b65
Server: 08424fe2de96d50e0d4e6739f9184a5fd165907b

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Comment by Starfirejordan** [comment]
this should be unmerged ngl it sucks balls

**Pull request merged**
