### PR TITLE
runner weed speed/slash nerf

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
mjp has come to break rounys legs

anyways i nerfed slash damage by 2 points at yung and 1 at elder/ancient and made weed speed -0.1.

## Why It's Good For The Game
rouny is way too fast on weeds and deals a bit too much damage in my opinion for a t1, considering pools make losing xennomorphs 

## Changelog
:cl:
balance: runner has lost 2 points of damage at yung/mature to 15 from 17, lost 1 at elder/ancient to 20. Only gets -0.1 weed speed bonus.
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
it only does 21 damage at ancient, dies in 2 pbs too. don't understand this pr other than "too much for a t1" when its insanely easy to kill them except for the fact that they have a godmode button.

**Comment by Cowbin** [comment]
I don't believe people have had any issues at all with the runners speed or damage.  They die extremely fast to any kind of burst damage like a shotgun, if I remember correctly a single buckshot PB will one shot almost all ages of runner.  If people want runner speed on weeds to be slower, they should simply just break weeds as they move instead of leaving them behind during a push.  This just seems like a nerf no one asked for or needs.

**Comment by optimumtact** [comment]
wtf bbq posting this on reddit can't believe xander greene is killing TGMC fucking typical coders don't even play

**Comment by SplinterGP** [comment]
> 
> 
> wtf bbq posting this on reddit can't believe xander greene is killing TGMC fucking typical coders don't even play

gitgud noob

**Comment by SplinterGP** [comment]
> 
> 
> I don't believe people have had any issues at all with the runners speed or damage. They die extremely fast to any kind of burst damage like a shotgun, if I remember correctly a single buckshot PB will one shot almost all ages of runner. If people want runner speed on weeds to be slower, they should simply just break weeds as they move instead of leaving them behind during a push. This just seems like a nerf no one asked for or needs.

rouny speed as is its pretty bad when you stack it with frenzy and weed speed

**Comment by TiviPlus** [comment]
> wtf bbq posting this on reddit can't believe xander greene is killing TGMC fucking typical coders don't even play

Go home oranges you're drunk

**Comment by TiviPlus** [comment]
Im only okay with the speed nerf

**Comment by SplinterGP** [comment]
i prefer if hunter got more of that nerf too
since hunter is way stronger than rouny even

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Still waiting for changing this to a speed nerf only

**Pull request closed without merging**
