### PR TITLE
Fixes the helmet sprites

### PR DESCRIPTION
**Pull request by Metroidlover**
## About The Pull Request

Moves the new helmet's left-facing sprite over by one pixel

## Why It's Good For The Game

It's not supposed to be like that

## Changelog
:cl: MetroidLover
fix: The basic Marine Helmets are now properly set when facing left
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
Not my fault

**Comment by Metroidlover** [comment]
Definitely your fault

**Comment by Kuro-ai** [comment]
Prman mad

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is now above zero (0). Feel free to make Feature/Tweak/Balance PRs.

**Pull request merged**
