### PR TITLE
MREs are much more nutrient dense.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Increases the nutrients in the food that a MRE contains.
## Why It's Good For The Game
Currently a MRE takes up the equivalent space of 2 protein bars, but it only has 12 total nutriment. which is worse than just carrying 2 protein bars.
This will make carrying MREs more worthwhile, as you actually get more than 1 nutriment per bite.
## Changelog
:cl:
balance: MREs contain a lot more nutriment.
/:cl:

### CODE REVIEW

**Review by QualityVan — APPROVED** [review]

**Comment by Joe13413** [comment]
dude..... powercreep....... smh....... >:(

**Review by Lumipharon — APPROVED** [review]
Nutrient dense is a great phrase.

Also wtf is snack code 
image

**Comment by Autisem** [comment]
> Nutrient dense is a great phrase.
> 
> Also wtf is snack code image

is there not bites var or smth?

**Review by Lumipharon — CHANGES_REQUESTED** [review]
actually for real, this makes an MRE worth fucking 7 protein bars, wtf?

**Comment by Xander3359** [comment]
> actually for real, this makes an MRE worth fucking 7 protein bars, wtf?

I think all food needs a buff to be honest. Protein bars should be upped to at least 10 as well.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
