### PR TITLE
Adds the TL-34 AGSLS 

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Adds an uber expensive marine endgame weapon to finish off incredibly long rounds, the AGSLS.

It is an IFF deployed grenade launcher that costs 450 points, does heavy explosions and will pretty much shred anything off the face of the universe.

It costs 10 points to reload, 50 round belts.

100/10/10. Before explosion damage.

## Why It's Good For The Game
Gives marines a way to help them close out incredibly long rounds that are going in their favor.

## Changelog
:cl:
add: Added new TL-34 AGSLS, incredibly expensive smart beltfed 40mm grenade launcher. 450 points in Req.
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
Marines already got a shitton of late game weapons, why would they need a new one with inst even that expensive

**Comment by theta006** [comment]
we love IFF just like the good old IFF spear and the IFF sadar

**Comment by bowlofcereal** [comment]
but why

**Comment by Pariah919** [comment]
>MJP, how do you like idea a two handed belt-fed semi-auto grenade launcher based on backpack magazine mechanic?
We have flamer, minigun so why not bring evolution of T-70?
A "mobile siege unit"
>
wack
>Marines already got a shitton of late game weapons, why would they need a new one with inst even that expensive
>
considering this is the price of 4 fully kitted SADARs, this is pretty balanced honestly, sure it owns things off the map but you'll need to save for a long time considering TGMC usually lasts for 30~ minutes.
>we love IFF just like the good old IFF spear and the IFF sadar
>
meme strawman
>but why
>
it's cool and adds a lategame siege weapon.
>it has potential problem, what if retarded RO will make excuse of 'smh just buying thanos gun, no req for you' entire round. also with xenocoin mining 450 point is something easy to get. Plus if it is that strong xeno mains will seethe in maramount salt and this will get Qdel'd in 3 min.
>
450 is pretty steep, it can only be in one place at once, and if it dies thats 450 points down the drain, plus ammo. I don't think this is as opressive as it seems, it is a mounted weapon after all.
If ROs spam order it I'll timelock it to 13:30 or something and lower the cost, but I doubt it'll happen.

**Comment by Lefunny** [comment]
> 
> 450 is pretty steep, it can only be in one place at once, and if it dies thats 450 points down the drain, plus ammo. I don't think this is as opressive as it seems, it is a mounted weapon after all. If ROs spam order it I'll timelock it to 13:30 or something and lower the cost, but I doubt it'll happen.

Also it sounds like just another weapon to fuck up with sieges with are already a hell of a pain for both sides as marines stay behind cades firing with a shitton of deployable guns.

**Comment by Luxyboo** [comment]
make it 500 because 45 is relatively easy to get. marines get gl and xenos get king, cant wait for the two to duke it out

**Comment by Losenis** [comment]
This is how I picture this being used in practice.

A) Doesn't happen because marines are losing so they can't afford to get 450 points.
B) No RO until he arrives to like 600 points. Best case scenario since even in fobsiege it's gonna fuck shit up, though debatable if the RO/whoever with access will hail mary it on a single marine with that or just get a ton of B18s/miniguns/sadar with rocket factory/etc.
C) Marines are winning hard enough to get so many unspent points that a stationary gun won't do much in a mopup instance with no silos.
D) Ideal scenario where marines get a lot of miners that xenos can't push but xenos are strong enough to stop marines from pushing. Grenade launcher gets sent down. Set up and gets used, inevitably a bit behind the marines due to its stationary nature as a second entity you're not carrying in your hands with magharn. Shoot a few volleys and xenos get scared enough to fall back a bit, marines start pushing, xenos start engaging marines again at the edge of the maze. Either the GL doesn't shoot which beats the point of the gun, or unga starts shooting at the hive that is engaging the marines, and because the grenades are IFF but the explosions are not, hits the marines with atrocious FF killing hard the push much like Sadars tend to nowadays.

I like the idea of marines getting something more individually powerful than just spamming B18s and miniguns should they get hundreds of points, but this gun feels far, far more susceptible to push-wiping skill issues than its worth compared to giving 4 marines B18s that you can already start buying at 120 points. It'd be funny to see a defender charge into an ungaball and fortify to have the GL shoot it for no damage while killing everyone around it.

**Comment by TiviPlus** [comment]
Im 60% sure this is a shitpost pr but even if it isnt this looks like itll end up with more marines exploding than xenos

**Pull request closed without merging**
