### PR TITLE
Miners give dropship points but removes the dropship points voulcher from req

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Re-pr of #12492, credit to @Al-1ce. I just removed the voulcher.

image
## Why It's Good For The Game

See the original PR, it explains it pretty well.
## Changelog
:cl:
balance: Dropship fabricators now earn 30 and 15 points from respective miners.
del: Removed the dropship points voulcher
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by Lumipharon** [comment]
Marine cabal conspiracy, Agent tibi has been compromised. Send halp.

**Comment by ivanmixo** [comment]
> Are these intentional

Strongdmm did them automagically, don't worry bout it

**Comment by Al-1ce** [comment]
Very cool!

**Comment by Al-1ce** [comment]
I approve.

**Comment by XElectricX** [comment]
No one should be buying the voucher anyways.

**Pull request merged**
