### PR TITLE
Readds Survivors

### PR DESCRIPTION
**Pull request by Chaznoodles**
## About The Pull Request

Readds survivors.

image

## Why It's Good For The Game

Opening 25-33 minutes of game are AFK simulator for xenos, gives them something to do. Gives players who don't have time for a full round to participate. Gives xenos the opportunity to build teamwork and have fun.

Serious PR, but everyone else is on meth today anyway so might as well join them

## Changelog
:cl:
add: Readds survivors.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Number of based PRs rising.....

**Comment by Dolth** [comment]
If you do that PLEASE put some slowdown on the survivors armor OR lower the overall armor OR both.
No slowdown with 55 slash *ALLOWS* robust players to actually storm hives, they are survivors not fucking no slowdown/average guns/high melee armor people. This role shouldn't be a xeno killer anyway.

Issue was a too high skill ceiling, lower it by lowering the survivor speed/armor/both so robust players have more trouble pulling a major and regular player still can play as a survivor with cades or else.

**Comment by Tupinambis** [comment]
Ensure survivors start in an entrenched position and have armor slowdown and I'd be okay with this. Survivor should be a role about holding out until marines can rescue you, not an unga the hive role.

**Comment by Chaznoodles** [comment]
> If you do that PLEASE put some slowdown on the survivors armor OR lower the overall armor OR both.
> No slowdown with 55 slash _ALLOWS_ robust players to actually storm hives, they are survivors not fucking no slowdown/average guns/high melee armor people. This role shouldn't be a xeno killer anyway.
> 
> Issue was a too high skill ceiling, lower it by lowering the survivor speed/armor/both so robust players have more trouble pulling a major and regular player still can play as a survivor with cades or else.

yes

> Ensure survivors start in an entrenched position and have armor slowdown and I'd be okay with this. Survivor should be a role about holding out until marines can rescue you, not an unga the hive role.

no

**Comment by TiviPlus** [comment]
User has since been banned

**Pull request closed without merging**
