### PR TITLE
Adds Vatborn (or Vatgrown) and their naming system (as per Kuro's request)

### PR DESCRIPTION
**Pull request by XSlayer300**
## About The Pull Request
As per title. Adds Vatborn (or Vatgrown) as a species (humans but cloned) which had different naming conventions than humans. 

This is at Kuro's request, so if anyone wants this to go down. Probably best not to ask me. http://prntscr.com/t7ur47

It compliments #4357 

The naming convention for Vatborns are the following:

- Vatborn follows standard human first name, depending on the gender. Followed by a dash and a random number between 1 - 999 (ie. John-117)

- There is a 25% chance (regardless of gender) that the standard human first name will be replaced by any 26 letters of the alphabet. Then followed by a dash and a random number. (ie. F-420)

Demonstration: https://prnt.sc/t7ul0p

## Why It's Good For The Game
Because I like fufiling requests.

## Changelog
:cl:
add: Added Vatborn (Vatgrown) naming conventions and as a species only for admins. Demonstration here: https://prnt.sc/t7ul0p
/:cl:

### CODE REVIEW

**Comment by Hughgent** [comment]
I disagree from a lore perspective.

Giving them 'real' names is making them more human when they should be classified as equipment.

**Comment by XSlayer300** [comment]
I might have to wait for @Kuro-ai for this one, though.

**Comment by Kuro-ai** [comment]
The first name is just to make it possible to have a greater variation of combinations,also it sounds coool

**Comment by Hughgent** [comment]
They are vatgrown, they aren't special, they all look the same. Them having 'unique' names goes against the spirit of what they are, equipment.

**Comment by Kuro-ai** [comment]
they don't all look the same either,you can customize them as any other human mob,this is just for the sake of having a new naming system for people that don't want to make full names,it's fluff,idk why lore matters (considering we don't even have lore)

**Comment by Pariah919** [comment]
Vatborn follows standard human first name, depending on the gender. Followed by a dash and a random number between 1 - 999 (ie. John-117)

hello halo
no

**Comment by Kuro-ai** [comment]
> Vatborn follows standard human first name, depending on the gender. Followed by a dash and a random number between 1 - 999 (ie. John-117)
> 
> hello halo
> no
> i think a letter and then numbers is better personally.

a name is just a collection of letters

**Comment by Pariah919** [comment]
ok then go with names

**Comment by Kuro-ai** [comment]
you can still name yourself J-101,it's both

**Comment by Kuro-ai** [comment]
also I just realized this is admin only,my idea was for people to be able to roundstart spawn as one and pick their name on the setup window

**Comment by Kuro-ai** [comment]
well it's fine to add it like this,I can see about it being added as a lobby selectable thing later

**Comment by XSlayer300** [comment]
Sure, I am not really capable of making it lobby selectable though. Not enough skill yet.

**Pull request merged**
