### PR TITLE
Add queen egg laying back

### PR DESCRIPTION
**Pull request by MiniMeatwad**
## About The Pull Request
Egg

## Why It's Good For The Game
Enables a supportive playstyle encouraging trapping while building resin structures.

## Changelog
:cl:
balance: Queen egg laying added
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Xenopause is _over_

**Comment by Barnet2** [comment]
I find it really odd that this was removed; it has genuine utility and I love using it on shrike to troll marines.
It was then replaced with probably the worst ability in the game (bulwark), would glad to see it come back.

**Comment by Technical-l** [comment]
> I find it really odd that this was removed; it has genuine utility and I love using it on shrike to troll marines. It was then replaced with probably the worst ability in the game (bulwark), would be glad to see it come back.

it werent even replaced by bulwark, this shit was missing for like years and years because of "bloat" or some shit like that idk

i genuinely cannot see why coders removed egg laying for queen, they say it was for bloat but there's clearly a dedicated community of queen mains who loved that ability. And as if people didn't pick queen enough, they removed some ability that a few people loved for the sole purpose of "uhhh ummm not enough people use it idk"

**Comment by novaepee** [comment]
This was closed a few months ago: https://github.com/tgstation/TerraGov-Marine-Corps/pull/13138

**Review by ivanmixo — APPROVED** [review]

**Comment by Oscari-pog** [comment]
People that never played Queen arguing that Queens dont want the ability to lay eggs despite every actual Queen player wanting it

Comical that this was removed

**Pull request merged**
