### PR TITLE
LV624: 2020 Edition

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Mostly returns LV624 to it's state before https://github.com/tgstation/TerraGov-Marine-Corps/pull/4570. 
This (mostly) isn't a strict revert though, I've ported our current LZs and added features that didn't exist at the time LV was originally reworked, as such it's more of a fusion between our current LV624 and the old one.

## Why It's Good For The Game

Currently LV624 isn't liked very much, it mostly consists of marines charging into a cave and getting slaughtered time after time. The actual colony part is almost entirely ignored. You could honestly remove 90% of the map and put the landing pads directly south of a generic cave system and the gameplay would be unchanged.
 
I asked around and collected feedback about what could be done to fix LV624 and the most common response outside of "remove caves" was bring back the version of LV624 before it got overhauled. 
This pull does that. 
Looking at the old map, it does have more of an emphasis on the colony compared to our current version. This should result in more varied gameplay for both sides, or at least more rounds where marines and xenos battle over control of the domes instead of endless caves.

Even if it's ultimately not merged, I'm very interested in the feedback regarding this map change and am willing to make further changes based off player reactions. I can still use the feedback for improvement of modern LV624.

## Changelog
:cl:
balance: Fused LV624 with it's pre-rework 2020 counterpart.
/:cl:

### CODE REVIEW

**Comment by RipGrayson** [comment]
As a bonus, here's BraveMole's assessment of current LV624.
bmcomplaint

**Comment by Mrrpip** [comment]
Bravemole's diagram seems about right.

**Comment by DarkWolfKai** [comment]
too bad that the rest of the colony's only played during civil war, cuz' loyalist spawns on east

**Comment by Lumipharon** [comment]
Fighting outside as a beno has no advantages and a lot disadvantages.

Lv has a large enough cave network that you can comfortably fallback and keep fighting.
Then it has the river right outside, which is a significant reason to not push out into the open.

That's on top of the normal OB, CAS and mortar firepower to worry about.

If the buildings were bomb proof, that would different.

**Comment by Walarks** [comment]
Fighting outside is 200% more fun than caves. I'd suggest removing 80% of caves and keeping outside. Maybe add some dirt mounds in river so it isn't a total death trap for xeno.

**Comment by vilereaver41** [comment]
changing layout means nothing if you dont give both sides something to fight over or go there for

**Comment by RipGrayson** [comment]
> changing layout means nothing if you dont give both sides something to fight over or go there for

This revision has engineering in the main colony, if that isn't sufficient then I'll add other incentives to make the colony the main focus. Caves are not fun, but they are somewhat necessary for the xenos to have a fighting chance, so I don't want to nerf them unless I have no other balancing option.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Old lv was shit as well, that's why it had so many reworks. 
The river need to be reduced in size, add more bridges, reduce caves size, reweed colony

**Comment by Sebbe9123** [comment]
Can you weed on the grass in the caves? Would be really dumb to not be able to like in the colony.

**Comment by RipGrayson** [comment]
> Can you weed on the grass in the caves? Would be really dumb to not be able to like in the colony.

Weeding on the grass probably deserves a PR of its own. We'll see what the map looks like after all the requested changes have been done.

**Comment by RipGrayson** [comment]
This PR has been superseded by https://github.com/tgstation/TerraGov-Marine-Corps/pull/8806.

**Pull request closed without merging**
