### PR TITLE
Coffee/water rework and minor chem changes

### PR DESCRIPTION
**Pull request by jroinc**
## About The Pull Request

Coffee does more
Water does something

## Why It's Good For The Game

Encourage people to engage in realistic behavior by adding smol benefits to it.

## Changelog
:cl:
add: Water regens stamina and heals brute and burns slightly at the cost of purging all chems slowly.
add: Coffee regens stamina and makes you run faster at the cost of purging oxy and removing stamina when it runs out.
tweak: Doubles metabolism rates of roulettium, polyhexanide, and synaptizine to match intended 
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
Reduce the size of that changelog.
Add to it the fact that water now heals brute and burns.

**Comment by jroinc** [comment]
> Reduce the size of that changelog.
> Add to it the fact that water now heals brute and burns.

It's in the changelog.

The obnoxiously big changelog with exact info on what it does :)

**Comment by jroinc** [comment]
Well, it works now, except there's an error in the Xenomorph Death file.

Wat.

BYOND!

**Comment by jroinc** [comment]
This is broken and it's broken in a way unrelated to anything I've changed. Pls advise if you see the issue.

**Comment by jroinc** [comment]
Functions properly, ready for TM. Values will still need tweaking, please DNM-tag this.

**Comment by Rohesie** [comment]
If this went as it is it'd be at least three times larger than the largest thing that was changeloged.
Reduce it in size. Look at how actual changelogs look.

**Comment by jroinc** [comment]
> If this went as it is it'd be at least three times larger than the largest thing that was changeloged.
> Reduce it in size. Look at how actual changelogs look.
Fine, I'll strip out the actual info.

**Comment by Rohesie** [comment]
This is enough for a changelog:
```
add: Water regens stamina slightly at the cost of purging all chems slowly
add: Coffee regens stamina and makes you run faster at the cost of purging oxy and removing stamina when it runs out.
```
The rest is in excess.
Add the rest to the wiki or to the body of the PR they can check.

**Comment by jroinc** [comment]
Rebalanced shit to it's final form, also added tweaks to 3 chems as listed due to an error in the last PR I made. Request removal of DNM tag and merging eventually, assuming no one else sees any balance issues.

**Comment by Rohesie** [comment]
Fix the changelog, follow the format!

**Comment by jroinc** [comment]
> Fix the changelog, follow the format!

I did reeeeeeee

**Pull request merged**
