### PR TITLE
Theseus Remodel/Rework

### PR DESCRIPTION
**Pull request by Alterist**
## About The Pull Request

Remodels Theseus into a 1 z-level, 2 squad ship:
thes

## Why It's Good For The Game

more ship options is good

## Changelog
:cl:
add: new and improved(?) TGS Theseus, Olympia-Class Assault Transport Block-II
/:cl:

### CODE REVIEW

**Comment by InterroLouis** [comment]
The SD here seems even less holdable than the previous one to me.

**Comment by SpaceLoveSs13** [comment]
Where would tadpole land? Also please put the MRE, Flare, Water etc crates amd fuel tank near hanger pads like Sulaco has.

**Comment by Alterist** [comment]
Update 1: fixed all the pipenets/powernet/disposalnet, thanks to Theoneandmightyred. Fixed overlapping tables and pipes. Added generic airlock types to reduce varedits.

> The SD here seems even less holdable than the previous one to me.

The back of SD is unmeltable, so it's only assailable from the front, with some flanking possible from the sides.

> Where would tadpole land? Also please put the MRE, Flare, Water etc crates amd fuel tank near hanger pads like Sulaco has.

Tadpole lands right below the condor, fuel/water tank is right below the DS, I'll put the MRE and flare crates in the same place as well

**Comment by Alterist** [comment]
The should be no major issues remaining, this is ready for testing

**Comment by InterroLouis** [comment]
So the back of the SD is outer hull walls, then? Okay. Just one last thing. That's a lot of generators and only one recharger for the generator cells. Maybe one more?

**Review by TiviPlus — APPROVED** [review]
Fix the conflict and ping me for merge

**Comment by Alterist** [comment]
halfed filesize using voodoo witchcraft

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
