### PR TITLE
Balances vial, small and large beakers.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Buffs beakers to hold 120 units
Buffs vials to hold 60 units
Buffs vials to be w_class tiny, they fit in helmets and hold the same amount of liquid as a combat canteen.
Makes large beakers larger, but hold more reagent.

## Why It's Good For The Game
Vials and small beakers are literally just downgrades to large beakers. This change intends on giving each one it's own purpose.

## Changelog

:cl:
balance: Vials are smaller, hold 60u.
balance: Small beakers hold more reagent 120u.
balance: Large beakers are bigger and hold 240u.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Why are vials on par with bottles?

**Comment by KerbalCitizen** [comment]
> Why are vials on par with bottles?

Looks like this PR will make them on par with combat canteen. Tiny item (fits in helmet), 60u storage.

**Comment by Xander3359** [comment]
Yeah what kerbal said. 
Currently there is 0 reason to ever use anything other than large beakers, since they all use the same storage space, do the same thing, and the only difference is how much chem they hold. Objectively meaning that large beakers are the best with absolutely 0 drawback.
I've buffed vials to be on par with canteens (hold 60, fit in helmet)
Buffed beakers to be about 1/2 of a pill bottle (which holds 240u, but isnt liquid form)
And buffed large beakers to be double a normal beaker, at the cost of requiring more storage space.

**Comment by Lumipharon** [comment]
I wouldn't really compare them to flasks. Also those should be small but still made to fit in boots/hats,

**Comment by Xander3359** [comment]
Bluespace beakers are bluespace powered, they are fine as is.

**Comment by XElectricX** [comment]
They are still pretty big. As it is there would be no reason to use a normal beaker over a large one.

**Pull request closed without merging**
