### PR TITLE
rouny takeover

### PR DESCRIPTION
**Pull request by Zar000**
## About The Pull Request

Funny rouny sprites for all castes
## Why It's Good For The Game

Its not, but its fun
## Changelog
:cl:
fun: more fun
imageadd: added some icons and images
/:cl:

### CODE REVIEW

**Comment by bowlofcereal** [comment]
speedmerge when complete immediately

**Comment by Alexeivichi** [comment]
the best thing since rouny

**Comment by UntoldTactics** [comment]
blessed

**Comment by iLikeMemes** [comment]
Shrike screech sprite, my beloved.

image

**Review by Kuro020 — APPROVED** [review]

**Pull request closed without merging**
