### PR TITLE
Three Marching Cadences Added in Lobby

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

SIR YES SIR OORAH!

In the United States Marine Corps Recruit Training (commonly known as "boot camp") and other branches in the US military, new recruits or trainees remember singing while marching or running. These songs are called cadences (or in the Air Force "jodies" (never understood why Air Force would use this name)). It is a privilage from the drill instructor (Marine Corps), chief (Navy), drill sergeant (Army), or military training instructor (Air Force) to be permitted to sing cadences. Yes, this means you cannot sing them inside the barracks, only when they permit you is when you are allowed to sing.

Enough of my boot PTSD . . .

It brings more soul to lobby. It is different than what civilians are used to, but it's worth the change. Tivi says yes to adding these songs.

## Changelog
:cl:
expansion: Add three songs in the lobby which are military cadences!
soundadd: Hear the melodic voice of the Marine Corp while you wait in lobby
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
The songs!

I Left My Home
https://youtu.be/wktDhK5wBx4

Mama Told Johnny Not to Go Downtown
https://youtu.be/n1kFFoHIFwU

She Wore A Yellow Ribbon
https://youtu.be/Lu7le9EXSEs

**Comment by TiviPlus** [comment]
Config change
(Which also doesn't do anything btw which means you didn't test it)

**Comment by novaepee** [comment]
dang it; time to better code it

**Pull request closed without merging**
