### PR TITLE
Improves maid spawn.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Alternative to #7101

Improves maid itemspawner. It spawns bunny ears and REAL maid skirt altogether.

## Why It's Good For The Game

We are an MRP server based on the lore of marines vs xenomorphs. With RP events here and there, I see a reason to keep the maid outfit with bunny ears and maid suit. Just like the bartender loadout which does have a reason sometimes to exist for the sake of RP events.

## Changelog
:cl:
add: Added proper maid costume
admin: Admins now can spawn proper maid costume
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
based and redpilled

**Comment by TheRealScarHomie** [comment]
BIMMER, READ THE FEMBOY MAID CODE

**Comment by DenialDuckOfService** [comment]
I don't normally post, because I don't really see any reason to. However, this pull, is unlike anything I have ever seen before. I truly think, from the bottom of my heart, that this will improve the quality of TGMC.

+1 from here, TGMC really needs more Femboy changes like these.

**Comment by SpaceLoveSs13** [comment]
Can we not have any erotic stuff PRd please.
@lKiseki

**Comment by EgorDinamit** [comment]
> Can we not have any stuff that may promote erotic shit, PRd please.
> @lKiseki

Idk why you think it's necessarily for "erotic shit", but at the same time, it's more a joke PR, so, do not fear, SkyRay won't suddenly appear in there.

**Comment by Pariah919** [comment]
i'll fix this

**Pull request closed without merging**
