### PR TITLE
Water decreases smoke lifespan

### PR DESCRIPTION
**Pull request by Redory**
## About The Pull Request

Water splashes will now decrease the current lifespan of smoke effects by 33%.
The smaller the lifespan of the smoke the less effect water will have, since it just shaves off 33% off the current lifespan.

Hydro cannon can now be attached to the following weapons:
- TE Laser Rifle
- TE Laser Carbine
- AR-12
- AR-21
- MG-42
- SH-15
- AR-55

Hydro cannon water tanks now only hold 125 water instead of 200, but are now smaller in size.

(I don't know what happened that made the videos say they are 321 hours long.
I just downloaded OBS and converted the .mkv files into .webm using VLC)

[2023-10-27 18-59-03.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/41807890/8b977113-2db6-4886-971a-bf66aa309ea3)

[2023-10-27 19-01-45.webm](https://github.com/tgstation/TerraGov-Marine-Corps/assets/41807890/97b18328-3036-42b3-928c-ec55a32596a8)

Just a random thought i had today and made with like 1.5 hours of work.
## Why It's Good For The Game

I think water could become somewhat more of a support role in dealing with excessive amounts of smoke spam.
I know Mimir exists, but i thought water clearing smoke could become an interesting concept.
I tweaked the water amount and gave it only to specific weapons, so i don't think it's gonna change the balance all too much.

But, hey, at least a couple more muhreens to extinguish you exist when you inevitably run into your own incendiary grenade.

In the videos above i used 4 spray splashes of water and used up A LOT from the water tank, just to clear a small patch of smoke from the acid grenade quicker.
## Changelog
:cl:
balance: Water splashes will now decrease smoke lifespan by 33%.
balance: Hydro water canisters now hold 125 water instead of 200.
balance: Hydro water canisters are now small size instead of normal size.
balance: Hydro cannon can now be attached to: TE Laser Rifle, TE Laser Carbine, AR-12, AR-21, MG-42, SH-15 and AR-55.
/:cl:

### CODE REVIEW

**Comment by Barnet2** [comment]
That is.. actually a pretty cool idea not gonna lie. Worth to try.

**Comment by DeltaFire15** [comment]
For reference, here is the effect vs. smoke you actually get to encounter in games with attachment choices, as opposed to hvh only nades:
water_effect_real
(oh god my compression is cooking)

**Comment by Deputi** [comment]
Gas is the only way for xenos to deal with large groups of marines and this pr will let any of the 20 ungaball marines with a fire extinguisher reduce the efficacy of gas. Tangle removing gas was balanced because it's in limited supply. This isn't balanced because flamers and most marines have fire extinguishers. During fob sieges, this would be especially painful for xenos when their gas is being reduced by marines with infinite water. This would be good if it only affected hvh nades.

**Comment by zee11zee** [comment]
I second Deputi, as this will allow any marine to counter a whole cast with no downside as underbarrels are just a plus.

**Comment by Lumipharon** [comment]
This is bad. Tfoot is very limited for a reason. Giving all marines a way to just click the gas away eith an unlimited supply of water is an exceptional nerf to xenos.

**Comment by Redory** [comment]
> For reference, here is the effect vs. smoke you actually get to encounter in games with attachment choices, as opposed to hvh only nades: water_effect_real [ water_effect_real ](https://user-images.githubusercontent.com/46569814/278740072-5d55a46e-4bf6-4061-810d-5a25d9f2dfb6.gif) [ ](https://user-images.githubusercontent.com/46569814/278740072-5d55a46e-4bf6-4061-810d-5a25d9f2dfb6.gif) (oh god my compression is cooking)

Why is your smoke clearing instantly in the gif? Is it from my PR? my PR shouldn't just qdel all the smoke away

**Comment by DeltaFire15** [comment]
> Why is your smoke clearing instantly in the gif? Is it from my PR? my PR shouldn't just qdel all the smoke away

my first extinguisher burst is covered by the smoke till I step away so this is the effect of 2 spray-mode uses (since I feel anyone wanting to counter smoke would run spray. Or line if they just want to sprint through it)
It uses the exact code of your PR (commit [d13ff6c]) and a normal (primordial) boiler I rigged for fire to a location I wanted to.

**Pull request closed without merging**
