### PR TITLE
Felinids

### PR DESCRIPTION
**Pull request by Max-023**
## About The Pull Request
Adds the Felinid species. Work was done by A-lexa.

## Why It's Good For The Game
Just adds another race to the game, maybe another Marine race.

## Changelog
:cl:
add: Felinid Race
add: Felinid sprites
/:cl:

### CODE REVIEW

**Comment by terranaut1** [comment]
There's no reason to do random PRs that have been closed in the past, are sadly discussed every other fucking day with the project lead being firmly against them. Please stop wasting everyone's time and good mood.

**Comment by Timmeye** [comment]
** I n s t a n t   d e n y**

**Comment by psykzz** [comment]
Closed until this gets approved by @MerryweatherLost.

**Comment by Max-023** [comment]
The project lead at the time was Rohesie. I was encouraged to make an attempt by Tivi as they were allowed to pursue new race creation by Merryweather.

**Comment by TiviPlus** [comment]
I do in fact have approval for this race, I'll post the screenshot in a a moment

**Comment by TiviPlus** [comment]
Capture1

**Comment by Rohesie** [comment]
The tail wags by default, that is very unfortunate.

**Pull request closed without merging**
