### PR TITLE
AI powerloader drones now function like proper powerloaders (mostly)

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

gives them an internal powerloader clamp and just hooks cargo handling to that instead
which allows them to handle stuff like ob warheads and such

## Why It's Good For The Game

AI can load ob if the STs are busy fucking off groundside

## Changelog
:cl:
balance: ai powerloaders can now handle most stuff a normal powerloader can
/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
YESSSSSSSSSSSSSSSS SPEEDEMERGHEHRER PLEASE

**Comment by Derrick2Electricboogaloo** [comment]
Holy based, finally?! AI far more useful!

**Comment by Barnet2** [comment]
I don't mind the idea really, but in theory should always be someone shipside to load OB before they deploy. If there is no one then yeah, it is what it is. We kinda already have Captain for the Swiss knife anyway.

**Comment by spookydonut** [comment]
You've been warned about branch names before

**Pull request closed without merging**
