### PR TITLE
fixes map issues

### PR DESCRIPTION
**Pull request by Alterist**
:cl: 
fix:  Fixes APC, light placements, missing tables and other minor Theseus map issues. 
/:cl: 
Fixes floating APCs and alarms, overlapping brig lights, and holes to space
Based on #127, thanks @F-OS

### CODE REVIEW

**Comment by Alterist** [comment]
adds tables to missing overwatch consoles
more pipenet and wiring improvements 
fixes unconnected apcs

**Comment by Rohesie** [comment]
270yfqp
This doesn't look intended.

**Comment by Rohesie** [comment]
The changelog should be something like this:
```
:cl:
fix: Fixes APC and light placements and other minor Theseus map issues.
/ :cl:
```

**Comment by Alterist** [comment]
done

**Pull request merged**
