### PR TITLE
Hivelord Infusion Nerf

### PR DESCRIPTION
**Pull request by Chaznoodles**
## About The Pull Request

Makes healing a flat 25 modified by regen pheremone level, instead of 10+5%maxHP modified by regen pheremone level.
Halves default sunder healing from the ability.
4 second windup cancelled by movement from either involved.
30 second cooldown.

## Why It's Good For The Game

Hivelords can no longer allow xenos to frontline 24/7 with a frankly ridiculously overpowered heal on both health and sunder that could be spammed until the cows come home. I was going to fiddle more with making the beam part of the channel, but I'd rather get the ability in a state that doesn't throw gameplay out the window.

## Changelog
:cl:
balance: Hivelord Infusion cooldown increased, windup added, sunder healing and health healing lowered.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -19. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Chaznoodles** [comment]
Holy commits, batman

**Comment by BraveMole** [comment]
So a hivelord will have half the healing per second than a drone? And can't use its heal in emergency. OK

**Comment by Pariah919** [comment]
@BraveMole i mean drone has to sit in front of it and stop everything its doing to heal the dude. Hivelord can still run around and bonk people over the head with sticky resin.

I don't really see anything wrong with this other than the windup movement

**Comment by Chaznoodles** [comment]
> So a hivelord will have half the healing per second than a drone? And can't use its heal in emergency. OK

Because it's not an emergency heal, for the amount it gives, plus sunder.


> I don't really see anything wrong with this other than the windup movement

J-just stand still bro. Might lessen the windup seeing as it's a 30 second cooldown anyways, so the windup's not particularly a limiter.

**Comment by SkeletalElite** [comment]
Cooldown increase is too much IMO. A small increase is probably fine but combined with all the other changes in this PR I don't think it needs a 30 second cooldown.

**Comment by Chaznoodles** [comment]
> Cooldown increase is too much IMO. A small increase is probably fine but combined with all the other changes in this PR I don't think it needs a 30 second cooldown.

It does, else it lets xenos frontline 24/7. The cooldown has been upped for that reason.

**Comment by Chaznoodles** [comment]
Closing, no desire to contribute due to repeated instances of behaviour like below.

image

**Pull request closed without merging**
