### PR TITLE
INFINITE FIRE EXTINGUISHERS!!!!

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

You can find infinite fire extinguishers, both big and mini, in the Specialized tab underneath the Automated Weapons Rack.

You can ALSO have fire extinguishers in loadout!

## Why It's Good For The Game

Currently, you get fire extinguishers in two ways: in limited supplies from fire locker or mass produce from autolathe. The former is how almost everyone gets it and the latter is how almost no one gets it. Since friendly fire from fire is common and the demand for fire extinguisher is always on the rise, it is time to make the process of acquiring fire extinguisher easier!

## Changelog
:cl:
qol: infinite fire extinguishers are now in vendors! Find it in the Specialized tab under flamethrowers. I wonder why I put infinite fire extinguishers underneath flamethrowers.
/:cl:

### CODE REVIEW

**Comment by EvilMelonTheSecond** [comment]
you're just giving it for free because it's boring to get it

**Comment by novaepee** [comment]
> you're just giving it for free because it's boring to get it

And Bravemole agrees.

**Comment by Mrrpip** [comment]
> > you're just giving it for free because it's boring to get it
> 
> And Bravemole agrees.

And there's only 3 mini-extinguishers a map, which is eh, I never knew why they weren't an autolathe thing, so now we can probably actually use them.

**Comment by EvilMelonTheSecond** [comment]
#9054 got refused with the exact reason I've said BY Bravemole

**Comment by novaepee** [comment]
> #9054 got refused with the exact reason I've said BY Bravemole

Talk to the man. Never hurts to ask maintainer their opinion in real time.

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
