### PR TITLE
Small fixes to LV624

### PR DESCRIPTION
**Pull request by psykzz**
## About The Pull Request
Moves a crash site lower to avoid having a free wall
Joins the security area into a single area supported by a single APC.

## Why It's Good For The Game

Marines got a free wall on one of the crash sites,
Makes assault the security (green disk) easier

## Changelog
:cl:
balance: updated the lv624 map a little
/:cl:

image

### CODE REVIEW

**Comment by spookydonut** [comment]
diff bot isnt showing whatever you changed on security?

**Comment by psykzz** [comment]
the area was combined (was previously security + armoury) and the cable removed alongside the apc for the old armory.

image

**Comment by spookydonut** [comment]
ooooooooh ok

**Comment by jroinc** [comment]
The "atmospherics" area north of LV engineering has a missing wire preventing generators from linking to 2/3 of the powergrid, any chance of getting that fixed?

**Comment by KwinOriginal** [comment]
Will you fix the wiring issue or is it already done?

**Comment by psykzz** [comment]
I was planning to, not done yet

**Comment by psykzz** [comment]
Also need to adjust the northern crash location in caves, it currently bottlenecks half the caves out and should be moved to over t-fort of the cargo area there.

**Comment by KwinOriginal** [comment]
Just for clarification, I spoke with psy and will merge it. The new changes will get up in a new pr.

**Pull request merged**
