### PR TITLE
You can now toggle auto aim mode while trying to wield a gun

### PR DESCRIPTION
**Pull request by vvvv-vvvv**
## About The Pull Request

So guns with a long wield time (e.g. SVD) can be aim moded during the do_after

## Changelog

:cl:
qol: You can now toggle auto aim mode while trying to wield a gun
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
This is an intended walance point for slower wield time weapons, and will also lead to funny situations where you're on aim mode without even being fully wielded.

**Comment by vvvv-vvvv** [comment]
> This is an intended walance point for slower wield time weapons, and will also lead to funny situations where you're on aim mode without even being fully wielded.

It won't start aim moding DURING the do_after, it'll start aim moding after it

**Comment by Lumipharon** [comment]
As soon as you press wield, you're wielded. the aim mode proc afaik checks for wielded not fully wielded, but this proc currently catches those first. I could be wrong though

**Comment by Lumipharon** [comment]
It just werks

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
