### PR TITLE
Droon

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request
Droon

*sprites by Elsa/Nova*

## Why It's Good For The Game

image

## Changelog
:cl:
add: Droon
/:cl:

### CODE REVIEW

**Comment by neohenry** [comment]
good evening, my queen, may i serve you some resin?

**Comment by Luxyboo** [comment]
next one should be woyer or woorrier

**Review by Kuro020 — APPROVED** [review]

**Comment by ThelastArchiver** [comment]
this is great i have been staring at this for 5 hours and its still great.

**Comment by Mechanelize** [comment]
whats with the H

**Comment by EvilMelonTheSecond** [comment]
Such a polite boy with a bright smile 4/10 would bang

**Comment by Losenis** [comment]
OH GOD IM GONNA

IM GONNA DROOOOON

**Comment by Mechanelize** [comment]
Stop

**Pull request merged**
