### PR TITLE
Psychic Sensors

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
sensor capture but with ai xenos and maybe a few sentient xenos
how it works:
capture 5 sensor towers win
fights lots of t1s
also includes a new map specifically for this mode that also works for sensor capture and combat patrol and a new shipmap
todo:
figure out if i want premade loadouts or player built loadouts

## Why It's Good For The Game
more gamemode good also good alternate low pop hvx gamemode other than crash
## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
SENSOR CAPTURE BUT COOL

**Comment by Kuro020** [comment]
nobody can stop this man

**Comment by XElectricX** [comment]
I look forward to this. Hope it is not crippled like how HvH is.

**Comment by novaepee** [comment]
image

image

image

just some small touch up for AI

**Pull request closed without merging**
