### PR TITLE
boiler hp/armor rebalance

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
boiler is tnakier against snipers, dies to shotguns and dps faster

## Why It's Good For The Game
boiler armor/hp stats are wack,dps sucks against a backliner and snipers deal too much damage to it

## Changelog
:cl:
balance: boiler has far less armor, has higher health. It taeks one more sniper shot but they die far faster to cqc dps
/:cl:

### CODE REVIEW

**Comment by davidchan13** [comment]
MJP got dunked by a boiler, didn't he?

**Comment by ilikesaying** [comment]
mjp got dunked as boiler by local firing squad of snypers probably

**Comment by BraveMole** [comment]
Boiler is annoying because of neuro spam from afar. Why would you want to nerf snipers against them? If anything, buff snipers

**Comment by Moggram** [comment]
https://user-images.githubusercontent.com/63105585/117734338-3de2a480-b1c1-11eb-913f-96c0d38828d2.mp4

**Comment by InterroLouis** [comment]
Is this about snipers or is this about SADAR

**Comment by InterroLouis** [comment]
Did MJP get dunked as a boiler by SADAR?

**Comment by Losenis** [comment]
Hypervene and kelotane already invalidate boiler unless you're getting fucked up by the rest of the hive anyway, and one engi can keep up an insane number of cades repaired, even moreso if he has mimir to ignore gas. Boiler is also slow enough that if a marine actually gets close enough to you to start shooting, it's going to get a good few shots before you can escape unless it's in a maze where there's only one tile to acid spray and stun him with.

**Comment by Naaanii** [comment]
You can nerf Boilers vs Snipers AND consistent dps if you delete Mimir.

**Comment by davidchan13** [comment]
> You can nerf Boilers vs Snipers AND consistent dps if you delete Mimir.

Gas masks are a something for nothing counter too.

**Pull request closed without merging**
