### PR TITLE
Line of sight proc

### PR DESCRIPTION
**Pull request by Rohesie**
An attempt at making an performant LoS proc, as /tg/'s seemed a bit expensive.

Could do a `get_step()` each time, but `getline()` uses `locate(x,y,z)` which is supposedly optimized, so I'm not sure if it would be better performant on all cases, specially considered I see this being used at range 7 by default. On long ranges where line of sight is cut early I can see the alternative being better.

This is for #1769

### CODE REVIEW

**Comment by DominikPanic** [comment]
Rev up those profiles :eye:

**Comment by Rohesie** [comment]
Profile version done.

**Comment by Rohesie** [comment]
Attempted to create an environment similar to what one would find on the game, though the number of packed mobs might be a bit high, in comparison to that of objects:
LOS profile
Profiling results:
```
Proc Name                                                                  Self CPU    Total CPU    Real Time     Overtime        Calls
----------------------------------------------------------------------    ---------    ---------    ---------    ---------    ---------
/atom/movable/proc/line_of_sight                                              0.005        0.165        0.165        0.002         1350
/atom/movable/proc/line_of_sight_one                                          0.004        0.010        0.011        0.002          450
/atom/movable/proc/line_of_sight_two                                          0.005        0.005        0.005        0.001          450
/atom/movable/proc/line_of_sight_three                                        0.145        0.145        0.145        0.057          450
```

**Comment by Rohesie** [comment]
Latest profile results:
```
Proc Name                                                                                Self CPU    Total CPU    Real Time     Overtime        Calls
------------------------------------------------------------------------------------    ---------    ---------    ---------    ---------    ---------
/atom/movable/proc/line_of_sight                                                            0.026        0.475        0.478        0.009         3596
/atom/movable/proc/line_of_sight_one                                                        0.013        0.026        0.027        0.004          899
/atom/movable/proc/line_of_sight_two                                                        0.020        0.020        0.020        0.001          899
/atom/movable/proc/line_of_sight_three                                                      0.321        0.321        0.321        0.089          899
/atom/movable/proc/line_of_sight_four                                                       0.082        0.082        0.083        0.029          899
```

**Comment by Rohesie** [comment]
Last profile result:
```
Proc Name                                                                                Self CPU    Total CPU    Real Time     Overtime        Calls
------------------------------------------------------------------------------------    ---------    ---------    ---------    ---------    ---------
/atom/movable/proc/line_of_sight                                                            0.026        0.125        0.125        0.011         3034
/atom/movable/proc/line_of_sight_one                                                        0.032        0.051        0.053        0.023         3034
/atom/movable/proc/line_of_sight_two                                                        0.006        0.006        0.006        0.003         3034
/atom/movable/proc/line_of_sight_three                                                      0.036        0.036        0.036        0.022         3034
```
The three of them yield the same result.
The `viewers` method was removed because darkness blocks sight, and it depends on the person viewing's sight, not the viewer.
`view` was much less performant, though it would be appropriate if we wanted to take lighting into account.

By the looks of this the second method is simply superior, and the attempt of the third one of reducing proc overhead helped some, but not enough.

**Pull request closed without merging**
