### PR TITLE
shields have toggleable no drop

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title basically
alt click for no drops
thanks to @TiviPlus who i took the code from

## Why It's Good For The Game
makes shields have no drop i guess, should probably nerf shield protection in trade but this makes them more consistent

## Changelog
:cl:
balance: shields have no drop, press alt click to toggle it.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -53. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by neohenry** [comment]
melee spec in the making

**Comment by TiviPlus** [comment]
Space indentation and merge into master for travis

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-55). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Surrealaser** [comment]
I can't believe my proposal got 7 downvotes, but this thing that gives Marines insanely overpowered easy access to de facto god mode was merged immediately. Unbelievable.

**Comment by MiniMeatwad** [comment]
Revert time

**Pull request merged**
