### PR TITLE
Armor rebalance 2.0:Eletric bump boogaloo

### PR DESCRIPTION
**Pull request by Kuro-ai**
oh boy here we go again

## About The Pull Request

Rebalances PFC armor sets (again) to account for bump melee and stamina

## Why It's Good For The Game

Light armor and standard armor are quite useless right now,bump melee made speed not so good since you can't dodge hits anyway,this change is made to make them less punishing,Light armor now has more light radius and better armor stats to fit more of a recon playstyle,and standard has been buffed a bit to make it more protective.Edge is unused but got changed for the day in which it will make it's glorious comeback,same as ballistic.IS has been slightly nerfed to make it weaker against ranged attacks,Heavy armor is balanced and needs no changes as is.

## Changelog
:cl:
balance:Buffed light armor values and increased light range; buffed standard armor values; nerfed IS acid and bio values; nerfed edge and ballistic armor
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
Bad

**Comment by Kuro-ai** [comment]
> Bad

salt nerd

**Comment by Rohesie** [comment]
Be a bit more descriptive on the changelog, please.

**Pull request merged**
