### PR TITLE
Synths no longer can have hair

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Synthetics can no longer have hair.

## Why It's Good For The Game
Hair is an expensive thing, and a military synth probably shouldn't have neon colored hair, and I believe would enhance the roles authenticity towards being towards being a better defined and shown role ingame.

## Changelog
:cl:
tweak: For lore purposes, synths can no longer have lore.
/:cl:

### CODE REVIEW

**Comment by bowlofcereal** [comment]
The best PR I have ever seen! Will fix all problems in TGMC and will cause none whatsoever! I love it!

**Comment by Licherr** [comment]
ourFP1uKV0U

**Comment by Alexeivichi** [comment]
God finally talked to me and told me that this PR needs to make it. It is his will.

**Comment by Losenis** [comment]
>"I can't be considered bald if I make everyone else also bald"

**Comment by KrabSpider** [comment]
Why is it good for the game though? Please answer. 🍵

**Comment by FosterGrime-Heymynameslouie** [comment]
BALD

**Comment by DerpiestBruh** [comment]
Good PR it depicts the synth playerbase accurately

**Comment by Al-1ce** [comment]
femstatic synths instant btfo

**Comment by Losenis** [comment]
image

**Comment by Alexeivichi** [comment]
Very good change now make it for marines please.

**Comment by Al-1ce** [comment]
> Very good change now make it for marines please.

The amount of hair you can have should be dependent on how many hours you have as a marine. That way, the bald are actually bald.

**Comment by c4xmaniac** [comment]
TGMC synths stay losing

**Comment by Geevies** [comment]
@stanalbatross looks portable

**Comment by stanalbatross** [comment]
> @stanalbatross looks portable

good idea, we can't allow ourselves to fall behind in QOL

**Comment by Losenis** [comment]
All synths will be gasmasked derrick clones undifferentiated from marines now tbh

**Pull request merged**
