### PR TITLE
Modifies the sadar to have a pre-attached scope that can be removed, and to no longer have the ability to walk while scoped.

### PR DESCRIPTION
**Pull request by MiniMeatwad**
## About The Pull Request

Modifies the sadar to have a pre-attached scope that can be removed, and to no longer have the ability to walk while scoped.

## Why It's Good For The Game

Makes it so that the sadar cannot be scoped while moving to make it more difficult to get off-screen instant kills.

## Changelog
:cl:
balance: Made it so that the sadar cannot remain scoped in while moving, and now starts with a removable scope.
imageadd: Added the "sadarscope" as an attachable.
imagedel: Modified "m5" sadar sprite to have no scope.
/:cl:

The sprites, and poor quality videos demonstrating the changes in-game:

sadarscope
sadarscope_a
m5
https://user-images.githubusercontent.com/22848292/132400775-1cf857ed-785a-4f95-b439-45b9401ae97e.mp4
https://user-images.githubusercontent.com/22848292/132400778-8202aece-0ce4-44aa-bcf9-a92c2f12a4e7.mp4

### CODE REVIEW

**Comment by Dolth** [comment]
Gucci.

**Comment by David-Stormwell** [comment]
@BraveMole 
Unless there's any changes you need from your side this looks good enough, and will be needed before we start getting insane amounts of salt.

**Review by SplinterGP — APPROVED** [review]

**Review by BraveMole — CHANGES_REQUESTED** [review]
It should be the gun preventing the ability to walk while scoped, with a bitfield on the gun.

What if there is another gun that needs that kind of limitation, we will have to make another scope for it?

**Comment by MiniMeatwad** [comment]
> 
> 
> It should be the gun preventing the ability to walk while scoped, with a bitfield on the gun.
> 
> What if there is another gun that needs that kind of limitation, we will have to make another scope for it?

How would I go about doing this? I don't know the byond language or the ss13 codebase, so I can't figure it out.

**Comment by BraveMole** [comment]
> How would I go about doing this? I don't know the byond language or the ss13 codebase, so I can't figure it out.

First, you'll have to wait for this https://github.com/tgstation/TerraGov-Marine-Corps/pull/8221 to be merged because we can't add new flags for now.

Once this is done, you want to look at this proc : 
image

As you can see, it does different things if the scope is allowing movement or not. You want to check if the scope allows movement AND if the gun allow it. 

I suggest adding a bitfield named GUN_INNATE_CANNOT_MOVE_WHILE, and adding it to the sadar.

Then, you can do something like if(zoom_allow_movement && master_gun.flags_gun_innate_features & GUN_INNATE_CANNOT_MOVE_WHILE)

**Comment by MiniMeatwad** [comment]
Thanks. I'll look into it when I can.

**Review by Kuro020 — APPROVED** [review]

**Comment by BraveMole** [comment]
I'm closing this because : 
I'm not even sure sadar needs that "nerf". You pr would be fine, but it is really usefull?

For this to works, i will have to finish my other PR allowing this one. I'm a bit lazy at the moment, so later

**Pull request closed without merging**
