### PR TITLE
you can no longer fire th elasgun one handed

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
you can't fire it one handed
the penalties it had for it we're already pretty high anyway.

## Why It's Good For The Game
Lasgun heavily penalizes you for using it one handed already, making the only real use of one handed lasmeme being pointblanking things with a shield or using it as a budget shotgun since those can't be used one handed.

## Changelog
:cl:
balance: you must wield to use a lasgun
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -243. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Swagile** [comment]
why though

lasgun shield meme is fun

**Comment by neohenry** [comment]
THE ENDDDDDDDDDDDDDD

**Comment by Drevenshek** [comment]
all this is doing is getting rid of a fun playstyle that has very obvious downsides and can be countered quite easily, railroading for no reason at all

**Comment by TGCMbetcher** [comment]
People will just swap to master key onehanded PBs. More damage anyway.

**Comment by davidchan13** [comment]
Unless you're giving Lasguns aim mode or something to compensate this is pretty dumb. I don't even use the damn thing (cause it's shit and highly niche for being  a catch all weapon) this takes away the only reason to use the weapon.

Silly as the onehanding is, it's the only good thing about the weapon right now.

**Comment by Guidesu** [comment]
The whole thing of laser gun being able to shoot one-handed because it has no recoil because its shooting laser not real bullet

**Comment by SplinterGP** [comment]
i'll think on this.

**Comment by SplinterGP** [comment]
eh, not needed, lasgun PB meme with shield aint that good and it aint even any better than using a pistol which can also be used from range, cant reload, if you wanna make shotgun mode 2 handed go for that mode only

**Comment by brasscastle187** [comment]
> 
> 
> all this is doing is getting rid of a fun playstyle that has very obvious downsides and can be countered quite easily, railroading for no reason at all. TGMC is fun because of the wide range of playstyles available, and theirs nothing OP or broken about shield and PB lasgunning. Their isn't even a reason given as to why this is a good addition to the game, or why using a lasgun one handed is bad for balance. Plus it'll make the shield even more limited in its possible uses

Also windhealer on carrier rework: "What if we delete it lol".
Carriers that are countered by grouping up or clicking 1 (ONE) time on a still sprite - ridiculously OP, lasgun + shield that makes you inherently tankier than any other marine while simultaneously still dealing very respectable damage through PBs (since xenos still have to melee you) - perfectly fine.

**Pull request closed without merging**
