### PR TITLE
PO Qol (Small Buff really) 2.0

### PR DESCRIPTION
**Pull request by Naaanii**
Adds engi skills to PO

## About The Pull Request

Gives PO Engi skills.

## Why It's Good For The Game

Would be nice for the PO to be able to reinforce tadpole or even FOB in some scenarios without having to rely on engineers all the time.

## Changelog
:cl:
balance: Gave PO engi and Construction skills
/:cl:

### CODE REVIEW

**Comment by vilereaver41** [comment]
nomgpowercreepbalancebreakreallyaSKILLISSUE

**Comment by Lumipharon** [comment]
They can... already build shit, it's just a little slower which is fine for tad.
They shouldn't be building fob, they're a pilot.

**Comment by novaepee** [comment]
what if make an entirely dedicated barricade that only po can make?

nah

**Comment by TiviPlus** [comment]
Powercreep

**Pull request closed without merging**
