### PR TITLE
Queen Charging

### PR DESCRIPTION
**Pull request by David-Stormwell**
## About The Pull Request

Queen can charge like the chroooshherrr

## Why It's Good For The Game

it isn't but tivi said i'd get points or something also it turns out it was just one line of work

## Changelog
:cl:
add: queen shares crusher charge
/:cl:

### CODE REVIEW

**Comment by David-Stormwell** [comment]
oh gotta update my codebase one sec

**Comment by usnpeepoo** [comment]
based

**Comment by ilikesaying** [comment]
OH GOD OH FUCK THE QUEEN'S CHARGING DOWN THE HA-

**Comment by MiniMeatwad** [comment]
Discord_1LjlTUcpNO

**Comment by Pariah919** [comment]
specs

**Comment by BraveMole** [comment]
I don't want to play queen until she get this. Speedmerge

**Comment by Chaznoodles** [comment]
Today is really a day, huh

**Comment by SplinterGP** [comment]
is that crusher charge

**Comment by Swagile** [comment]
https://youtu.be/N_mpV9zViUs?t=71

fear

**Comment by David-Stormwell** [comment]
> Today is really a day, huh

yes

**Comment by David-Stormwell** [comment]
oh god please don't tm this

**Pull request closed without merging**
