### PR TITLE
Stun changes part 1- shrike

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Stuns bad, time to kill some CC

PART 1-
Shrike

NERFS
Psychic fling is nerfed to effectively only really stun you for 0.1 seconds or so, and basically just disarms your weapon. Its more a displacement tool now.

Shrike screech only stuns you for half the time.

Compensation (If any)
Shrike is still an incredibly good caste, so the only compensation is slightly better pheros at ancient.

## Why It's Good For The Game
Stuns bad, down with the stuns.
Shrike should've been nerfed stunwise a long time ago. They had 2 ranged stuns, pheromones, healing and building in their kit? This nerfs them and gives them slightly better pheromones. As I still personally think they'll still be good at displacing marines.

## Changelog
:cl:
balance: Shrikes stuns have been nerfed, psychic fling effectively no longer stuns other than basically disarming. Screech only stuns for half the time, slightly better ancient pheros
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by MLGTASTICa** [comment]
One of the steps towards making marines hug the cades less. Might want to add some damage to the ability however.

**Comment by Pariah919** [comment]
it does damage already

**Comment by MiniMeatwad** [comment]
Sle

**Comment by Surrealaser** [comment]
Shrike is fine and is balanced by being unique; double shrike should be fixed though.

**Comment by SilencedMP5A5** [comment]
xenos dont need a shitload of stuns while they have high damage and can take you out of the round for thirty minutes in 10 seconds :)

**Comment by TheGandalf85** [comment]
I promised myself I wouldn't play again until a PR like this happened. My faith has been restored. Thanks Poohriah919.

**Review by Hughgent — APPROVED** [review]
variable changes

**Comment by MiniMeatwad** [comment]
Xenos don't need a stun nerf while marines get shields.

**Comment by Hughgent** [comment]
TM'd Since:
Commander TGMC
BOT
11/21/2020
REPO: Updating origin branch...
REPO: Merging PRs #5261, #5223, #5252, #5258, #5299...
DM: Compiling...
DM: Compile complete! Server will update on reboot.

TGMC Statbus
Winrate (Xenomorph to Marine)
46.15%
View Raw
http://statbus.psykzz.com:8080/api/winrate?delta=2

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-70). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
