### PR TITLE
Add a camera to the tadpole

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
This add a camera to the tadpole. It should be decently out of the way, looking like a dashcam

## Why It's Good For The Game
Fewer moments of wondering WHERE THE HELL IT IS.

## Changelog
:cl:
qol: Added a camera to the tadpole, like alamo. 
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Liveleak footage of tadpole getting bombarded by boilers , defilers and praetorians ? just what i need as command!

**Comment by Losenis** [comment]
More like russian dashcam footage of tadpole hitting marines on landing

**Comment by Lumipharon** [comment]
Make sure the PO can view it on their tablet.

**Comment by Derrick2Electricboogaloo** [comment]
I noticed this a long time ago, especially when we kept getting reports of the tadpole being lost after AI launched it. Maybe we can bring back AI interaction with the tad since the camera is back. That is what really was wrong. Should probably put one of those invisible ones if that is the case.

**Pull request merged**
