### PR TITLE
Adjusts marine ranks required time. values suggested by RenGusta

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
Adjusts marine ranks required time, and adds a chonk specialist extra rank for marines, allowing long time marines to have a neater rank of Specialist(you thought specialist were gone HUH), values given by RenGusta.

## Why It's Good For The Game
better values, now they differ from different roles.

## Changelog
:cl: SplinterGP and RenGusta.
tweak: Adjusts marine/eng/corpsman/SL ranks required  playtime.
/:cl:

### CODE REVIEW

**Comment by Chaznoodles** [comment]
This just adds confusion.

**Comment by Pariah919** [comment]
Specialist is probably too confusing for most people, just do corporal

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Aye dont use specialist its confusing
Also please use something more clear than ... E2, E3, E3S, E4, E5 ...

**Comment by SplinterGP** [comment]
Specialist cringe then ren, will change in a bit.

**Comment by Pariah919** [comment]
Squad marine should need 100 hours to be an E4, not just 80.

**Comment by SplinterGP** [comment]
im pretty sure its 160 ?

**Review by Hughgent — APPROVED** [review]

**Pull request merged**
