### PR TITLE
Flash powder removal

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
What it says on the tin.
## Why It's Good For The Game
30 second aoe spammable stun serves no genuine purpose in TGMC.
## Changelog
:cl:
del: Removed the flash powder reaction
/:cl:

### CODE REVIEW

**Comment by Ragecrabbo** [comment]
Im suprised it took this long for someone to remove it considering any map with groundside chem lets you absolutely troll HvH rounds as corpsman.

**Comment by jroinc** [comment]
Why don't you just change the 30-second paralyze and 10-second stun to something more-suited to the game rather than feature-ripping?

I agree it's way way way too much as-is, but like- *just the white-screen of the flash and no para/stun* seems more reasonable than "nothing".

**Comment by Looking4bros** [comment]
If var/eye_protection < 1
       var/datum/internal_organ/eyes = exploded

**Comment by Lumipharon** [comment]
> Why don't you just change the 30-second paralyze and 10-second stun to something more-suited to the game rather than feature-ripping?
> 
> I agree it's way way way too much as-is, but like- _just the white-screen of the flash and no para/stun_ seems more reasonable than "nothing".

Because you can spam it 500 times in a beaker repeatedly.

**Comment by jroinc** [comment]
> > Why don't you just change the 30-second paralyze and 10-second stun to something more-suited to the game rather than feature-ripping?
> > I agree it's way way way too much as-is, but like- _just the white-screen of the flash and no para/stun_ seems more reasonable than "nothing".
> 
> Because you can spam it 500 times in a beaker repeatedly.

So fix that instead- there is code to make reactions in a beaker clear all reagants in the container. I can get it for you.

Or make the radius of the (now-stunless) flash depend on the square root of the reagants reacting (like all the chemical explosives for the murdered grenade system).

**Review by Kuro020 — APPROVED** [review]

**Comment by yyzsong** [comment]
> Why don't you just change the 30-second paralyze and 10-second stun to something more-suited to the game rather than feature-ripping?
> 
> I agree it's way way way too much as-is, but like- _just the white-screen of the flash and no para/stun_ seems more reasonable than "nothing".

Why is feature ripping a problem here? There's no inherent virtue in keeping useless shit in the game, and if someone wants to use it for a future thing they can just add it back.

**Comment by Looking4bros** [comment]
Like the only "suitable" change i could see would be to make it have the same effects as the stun grenade, which is still cringe, and i hate the stun grenade and the fact that they're in the support pouches with the smoke grenades, wasting two slots. I just want the smoke.

**Review by ivanmixo — APPROVED** [review]
lol

**Pull request merged**
