### PR TITLE
Warrior nerfs, lunge cooldown drastically increased, grapple toss distance reduced by one, and punch lunge damage lowered.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Punch damage multiplier on grappled enemy reduced to 1.25x from 2x.
Lunge C/D increased to 50 seconds.
Grapple Toss distance reduced by one.

PASS 1
Makes Lunge C/D 35 rather than 50.
Warrior punch is 1.5x instead of 1.25x.

## Why It's Good For The Game
Punch never got changed for TGMCs overall lower damage values, but it might be too nerfed.
Lunge shouldn't be used twice in a fight, and the high C/D makes you have to use it strategically instead of just lol stunning anyone you see in CQC.
Grapple toss brazil should be reduced, use fling if you want to brazil people.

## Changelog
:cl:
balance: Warrior nerfs, grapple toss distance reduced by one, lunge C/D increased to 35 seconds from 20, punch damage multiplier on grappled enemies reduced to 1.5 times damage from 2 times.
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
CD increase? Very good, very excellent, good change.
Damage decrease? No, terrible.
With this change, the damage will go from 40+ on a grappled target to 28 max at elder. Base slash damage at elder is 23. 
This nerf makes it always preferable to throw your grappled targets, because it will make it easier to get more slashes off versus doing a single punch, which will make you more vulnerable AND do less damage. Why? Did you think about this?

**Comment by Pariah919** [comment]
> CD increase? Very good, very excellent, good change. Lunge is the actual issue here.
Damage decrease? No, terrible
>


1.25 might be too low considering I lowballed pretty considerable on starting values. 
But its not likely I'd go above 1.5 considering TGMC has generally de-escalated damage and x2 is a pretty old value from CM times allowing you to do frankly pretty absurd damage.

Unsure on if I might keep grapple toss changes, might be better to do the lunge/damage now and then change grapple later.

**Comment by usnpeepoo** [comment]
Highly unnecessary, warrior is already weak enough damage wise. It only really shines on primordial, and all of its potential as a caste comes from it using grapple toss (which was nerfed already). -1.

**Comment by Passe2142** [comment]
I understand the cool down but the range tile for toss you did it way back, I killed its stun to 0.5s for it to be 4 tiles instead of 3 (at that time it was 5 tiles with 1s stun).
You can adjust the damage to make sense, if they gonna combo it shouldn't feel like a bit stronger slash or knock it out of the park either. I could see it 1.35. Fling for braziling makes its a bit like shrike style, indirect fishing aka shuffle them and fling so you kinda kill woyers gimmick. 
The woyer gimmick is to be a direct fisher, grab the marine and toss it by playing the corners.

**Comment by Lumipharon** [comment]
I agree with the punch nerf, the others are kinda lame though.

**Comment by siegluck** [comment]
Very bad for game

**Comment by TiviPlus** [comment]
mjp what are you on

**Comment by Naaanii** [comment]
3 nerfs is a bit too much.

Lunge CD nerf is good as it nerfs toss and punch along with it. While lunge punch is strong the cd nerf makes it a good enough nerf already. Punch was changed to specifically do x2 damage so idk what you're referring to when you say it never got changed.

Toss was already nerfed to reduce the distance to what it is now which feels fair than what it was, nerfing it further just kills the ability.

**Comment by Al-1ce** [comment]
SALT PR DETECTED

**Comment by Al-1ce** [comment]
Salt PR.

**Comment by vilereaver41** [comment]
Im jealous, i wish my pr's got this many downvotes. anyway this PR feels malicious in a "i hate woyers so i nerf" kinda way with the ammount of uneccesary nerfs, warrior has a niche and requires the player to understand how to synergize its abilitys. why are you punishing player skill cause you got smacked?

**Comment by Starfirejordan** [comment]
Democracy has spoken 
image

**Comment by lbnesquik** [comment]
Maybe split each of those changes into separate PR's, and make people pick one?

**Comment by Al-1ce** [comment]
_"Lunge shouldn't be used twice in a fight"_ is not a reason. You're not explaining anything, you're just stating what you think is right. I think people wouldn't be outright against this PR if you had actually listed reasons for why these changes are good for the game, instead of outright declaring that they are.

I, as like much of the community, don't really feel this necessary or needed. That's just the way things are.

**Comment by Al-1ce** [comment]
_"Lunge shouldn't be used twice in a fight"_ is not a reason for change. You're not explaining anything, you're just stating what you think is right. People wouldn't be outright against this PR if you had actually listed reasons for why these changes are good for the game, instead of just declaring that they are.

I, as like much of the community, don't really feel this necessary or needed. That's just the way things are.

**Comment by Al-1ce** [comment]
_"Lunge shouldn't be used twice in a fight"_ is not a reason for change. You're not explaining anything, you're just stating what you think is right. People wouldn't be so against this PR if you had actually listed reasons for why these changes are good for the game, instead of just declaring that they are.

I, as like much of the community, don't really feel this necessary or needed. Maybe you could articulate your point some more?

**Comment by Technical-l** [comment]
man it already feels like forever waiting for the lunge CD to be over and now you wanna increase lunge CD to 50 seconds? that sounds pretty fuckin crazy to me. i don't think that making people wait longer is a fun way to nerf something, especially if its an ability that is CRUCIAL to the roles effectiveness. maybe just nerf the damage or something because waiting a minute sounds like it'd be hell man.

**Comment by Al-1ce** [comment]
Necroposting a tad but congrats on having the third most disliked PR in the history of this Github.

**Pull request closed without merging**
