### PR TITLE
Aim mode rework

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request
Makes shots fired while in aim mode have 30% damage decrease per marine passed, but aim mode doesn't decrease fire rate, give slowdown or have a delay for activating.

## Why It's Good For The Game
Could make it less clunky and feel better to play with compared to the previous iteration. I could re-add the slowdown part with decreased slowdown amount of it ends up being too good.

## Changelog
:cl:
balance: Makes shots fired while in aim mode have 30% damage decrease per marine passed, stacking multiplicatively, but aim mode doesn't decrease fire rate, give slowdown or have a delay for activating.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
have two levels of aim mode

**Comment by Walarks** [comment]
> have two levels of aim mode

Too much work to design it/too abstract to implement directly

**Comment by Elli-Skala** [comment]
so unless im missing something this removes all the down sides of aim mode? doesnt this just mean instead of shooting friendlys you have less damage and that's it, making it so there is no reason not to us it?

**Comment by Walarks** [comment]
> so unless im missing something this removes all the down sides of aim mode? doesnt this just mean instead of shooting friendlys you have less damage and that's it, making it so there is no reason not to us it?

the downside is that shots deal reduced damage for every marine passed, meaning it's less damage if more marines vs constant damage from current aim mode

**Comment by Elli-Skala** [comment]
> > so unless im missing something this removes all the down sides of aim mode? doesnt this just mean instead of shooting friendlys you have less damage and that's it, making it so there is no reason not to us it?
> 
> the downside is that shots deal reduced damage for every marine passed, meaning it's less damage if more marines vs constant damage from current aim mode

no i mean in terms of what it will be like post this pr, after this pr will be done they appers to be no reason not to do it over non aim mode

**Comment by Elli-Skala** [comment]
aim mode thing

**Comment by TiviPlus** [comment]
This isnt needed

**Pull request closed without merging**
