### PR TITLE
Foam razorwire doesn't exist anymore.

### PR DESCRIPTION
**Pull request by jroinc**
## About The Pull Request

Razorburn gas makes regular razorwire. You can't repair it anymore without metal, so I believe this is acceptable.

## Why It's Good For The Game

Tweak to make a marginal item more relevant and keep crushers out. Also prevent acid from one-shotting a whole canister in one go.

## Changelog
:cl:
balance: Razorburn starts at full HP.
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
This is simple enough I'm not gonna bother testing it, as it's a one line tweak. If it was fucked, it wouldn'ta compiled.

Request review and TM at a maintainer's leisure.

**Comment by Swagile** [comment]
You sure?

Razorburn grenade box is buyable as per a PR I made a few months back, and SL's can buy a bunch at roundstart with their points.

**Comment by jroinc** [comment]
> 
> 
> You sure?
> 
> Razorburn grenade box is buyable as per a PR I made a few months back, and SL's can buy a bunch at roundstart with their points.

Yeah. It's not *that* oppressive at 100 HP, and xeno AOE attacks currently just remove razorburn instantly.

**Comment by DerrickChamberlain** [comment]
Finally it will be useful for more than 1 second when there is a praetorian.

**Review by SplinterGP — APPROVED** [review]

**Pull request merged**
