### PR TITLE
adds cloneloss healing multiplier from sleeping with a plushie

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request

allows plushies to slightly increase the cloneloss heal multiplier when sleeping; you MUST be sleeping with a bedsheet  for the cloneloss multiplier to proc as well

**for references**
sleeping on the floor - heals 0.5037 CL per sleep cycle
sleeping on the floor with a blanket - heals 1.0193 CL per sleep cycle
sleeping on the floor with a blanket and plushie - heals 1.4072 CL per sleep cycle

sleeping on a bed - heals 1.536 CL per sleep cycle
sleeping on bed with a blanket - heals 2.0574 CL per sleep cycle
sleeping on a bed with a blanket and plushie  - heals 2.4515 CL per sleep cycle

each sleep cycle is ~20 seconds.
so you'd go from being able to sleepmax heal 20 CL from a drain, using a bed and blankie, in 195 seconds to being able to do it in 162 seconds using a bed, blankie, and plushie

**some particulars**
- you MUST have a blanket first to have the additional healrate from the plush work. they need comfort too.
- you do NOT need a bed, necessarily; tables or the floor work
- you only get the multiplier once; you can't have a plushie pile to make CL heal faster or anything
- if the plush is in your inventory, it won't work; share the bed!
---
tested extensively; this doesn't cause changes to anything with blankets

## Why It's Good For The Game

i think it's a cute idea and not too cheesable since it's also locked to having a blankie. 
could maybe encourage groundside sleeping instead of running to cryotubes every time you have CL. you might then have more people that float around with some CL damage, making it less all-or-nothing and slightly more permanent as people fiddle with how much they want to rest. also a few people also genuinely thought plushies did this already.

_can lower the multiplier, right now it's 0.75 * 0.0125 extra healing per tick_
ie, you heal an additional 0.009375 CL damage per tick you're sleeping

## Changelog
:cl:
add: Any plushies (or gnomes) now help heal cloneloss a little faster while you sleep; share the bed with them and make sure you bring a blanket!
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
THEFT

**Comment by coldironwarrior** [comment]
> THEFT
🐹

**Comment by coldironwarrior** [comment]
> idk man that seems like a little more than "slightly" for something people will just min/max to become the new norm. All for a dumb gimmick.

it's healing an additional .4 health per 20 seconds. wat.

**Comment by AlexCrimson** [comment]
>it's healing an additional .4 health per 20 seconds. wat.

Am i misreading something? 195 seconds to 162 does not seem small. A little over 15% decrease? In what world is it small?

**Comment by coldironwarrior** [comment]
you can waste three minutes and 12 seconds healing a full psydrain or you can waste two minutes and 42 seconds healing a psydrain.
or you can just go shipside and get it fixed in 10 seconds 🤷

**Comment by Pariah919** [comment]
I can't believe I'm saying this but this seems like powercreep.

**Comment by coldironwarrior** [comment]
> I can't believe I'm saying this but this seems like powercreep.

we're coining this "plushiecreep".

**Comment by coldironwarrior** [comment]
dont care enough to baby this one. if anyone wants to adopt later, feel free

**Review by QualityVan — CHANGES_REQUESTED** [review]
Plushies shouldn't give you any benefit unless you're holding them while sleeping.

**Comment by coldironwarrior** [comment]
> Plushies shouldn't give you any benefit unless you're holding them while sleeping.

resting makes you drop and held items

**Comment by EaglePhntm** [comment]
plushies with pistol lace when

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
