### PR TITLE
Meme emotes because fun

### PR DESCRIPTION
**Pull request by sunofang**
## About The Pull Request

Adds a *dab emote that makes the person doing the dab look visibly confused and wonder why they are doing it.

Adds a *awoo emote that will make anyone using it unconcious for 3 seconds.

## Why It's Good For The Game
It's not. But it's funny.

## Changelog
:cl:
add: Added some new emotes....
soundadd: Added Awoo.ogg
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]
Awoo Awoo
dancerainbow

**Comment by RenGusta** [comment]
If only this wasn't a DNM, I was going to suggest stealing some ideas from CM, like warcry, and golfclap.

**Comment by TiviPlus** [comment]
Its a meme PR but you're welcome to add more emotes

**Comment by Eskjjlj** [comment]
Speedmerge

**Comment by AtlasRules** [comment]
@RenGusta we have golfclap already, but...

we need *puff for cigar users
COPE

**Pull request closed without merging**
