### PR TITLE
LV624 Overhaul: 2021 Edition

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Overhauls LV624 to mix up gameplay and reduce stalling. Amongst other changes this pull,
-Expands the colony section
-Reworks caves to reduce stalling and attrition
-Adds a lake into caves, to allow for limited Tad-ops within cave itself.
-Moves Engineering back into the colony, so xenos have a reason to actually fight somewhere other than caves.
-Moves mineral turfs and jungle walls to their own area to improve mapper visibility and to keep weather overlays from affecting them.
-Changes the Sand Temple so it's no longer an eyesore that blocks eastern caves.
-Changes LZ2 so it no longer connects directly to caves
-Returns Tablefort to the beach area
-Adds several new domes
-Fixes rare pipe errors making modular domes not accessible via the pipe network
-Increases pre-weed density in some colony areas to encourage fortification of the domes.

## Why It's Good For The Game

LV624 needs shaken up badly, it's a mess where xenos hide in boring cave passages and marines fight in boring cave passages for about an hour until one side runs out of ~~patience~~ stamina and ~~ragequits~~ falls. 
This PR attempts to fix the the caves by making them easier for the marines to hold while also giving the xenos the option of escaping into colony if outclassed. 
It also increases increases the size of the colony and relocates engineering to be within the colony itself so the xenos have reason to actually contest it, in addition to adding a variety of new features to caves and colony to shake up gameplay.

## Changelog
:cl:
add: Added Tablefort back to LV624 beach.
add: LV624 has several new domes to fight in.
expansion: Expanded LV624 colony.
balance: Completely overhauled the Sand Temple.
balance: Overhauled half of LV624 caves.
balance: Pre-weed density in certain parts of the colony has been increased.
balance: LV624 LZ2 has been shifted again, this time without a direct connection to caves.
fix: Fixed pipes not properly connecting to modular domes on LV624
imageadd: Ported robotic showcase from TG 
imageadd: Added a few area icons
imageadd: Added icons for corner variants of stairs
imageadd: Added river decals for flooded areas
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Semi related, is there any particular reason why weeds can't be placed on grass tiles? That's honestly something that makes contesting the colony difficult, as your weed areas are heavily restricted. Sure benos have evolved to defeat grass though?

**Comment by RipGrayson** [comment]
> Semi related, is there any particular reason why weeds can't be placed on grass tiles? That's honestly something that makes contesting the colony difficult, as your weed areas are heavily restricted. Sure benos have evolved to defeat grass though?

I kind of thought it would be out of scope to add that to what is primarily a map edit PR. I'll make a secondary PR allowing weeds on grass and see if it flies with maintainers.

**Comment by RipGrayson** [comment]
nwlvbeforeandafter
Caves have been somewhat simplified and shrunken, in accordance with maintainer requested changes.

**Comment by RipGrayson** [comment]
westerncolony
part of the western section of colony

**Comment by RipGrayson** [comment]
tfort
T-fort is back, I had a surprising amount of requests for it to be restored.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Looks really cool. 

Two things:
- Colonist bodies should be spread around the map, having them in old spots no longer makes sense (no more capture)
- Do you want this tm'd with weed pr?

**Comment by RipGrayson** [comment]
> Looks really cool.
> 
> Two things:
> 
> * Colonist bodies should be spread around the map, having them in old spots no longer makes sense (no more capture)
>
Done. Colonist bodies added throughout colony, I didn't remove the colonists in cave though but can if you want.
> * Do you want this tm'd with weed pr?
>
I don't have a lot of confidence in the weed PR, and didn't rework this map with it in mind. If possible I think they both need tested separately.

**Comment by RipGrayson** [comment]
Barring more maintainer requests this pull is ready for testmerge, I'm done making tweaks.

**Comment by RipGrayson** [comment]
Prefacing this to say, I know LV has some problems and I've already responded to some of them. I've moved engineering farther north and fixed comms being broken.
https://github.com/tgstation/TerraGov-Marine-Corps/pull/8808 will fix most of your complains about too much grass, and I'm already looking into adjusting caves again.
Thank you for your patience, I look forward to your feedback.

**Comment by ChocolateBickie** [comment]
> LV624 needs shaken up badly, it's a mess where xenos hide in boring cave passages and marines fight in boring cave passages for about an hour until one side runs out of ~patience~ stamina and ~ragequits~ falls.

During the test round the hive positioned itself into the NE corner of caves and the vast majority of the round became exactly what you have just described.

>This PR attempts to fix the the caves by making them easier for the marines to hold while also giving the xenos the option of escaping into colony if outclassed. <

If marines break they usually get run down, a shorter distance between caves and the LZs would be required for this...which would lead to easier rushes.

Marines did however hold several chokes near miners for some time before getting flanked.
>It also increases increases the size of the colony and relocates engineering to be within the colony itself so the xenos have reason to actually contest it, in addition to adding a variety of new features to caves and colony to shake up gameplay.<

This just denies xenos their main source of psy points. Xenos can't hold central map without getting attritioned so the correct choice is always to just camp caves and wait for bored marines to feed you psy points.

Also the opening of the round generally involves marines rushing caves anyway, so xenos never have a chance to contest engineering anyway.

It's be better if engineering was dead centre of the map or on the river on the marines side, but still mid map (with a bridge because attacking it over water would be terrible).

- Choc

**Comment by RipGrayson** [comment]
> > LV624 needs shaken up badly, it's a mess where xenos hide in boring cave passages and marines fight in boring cave passages for about an hour until one side runs out of ~patience~ stamina and ~ragequits~ falls.
> 
> During the test round the hive positioned itself into the NE corner of caves and the vast majority of the round became exactly what you have just described.
> 
> > This PR attempts to fix the the caves by making them easier for the marines to hold while also giving the xenos the option of escaping into colony if outclassed. <
> 
> If marines break they usually get run down, a shorter distance between caves and the LZs would be required for this...which would lead to easier rushes.
> 
> Marines did however hold several chokes near miners for some time before getting flanked.
> 
> > It also increases increases the size of the colony and relocates engineering to be within the colony itself so the xenos have reason to actually contest it, in addition to adding a variety of new features to caves and colony to shake up gameplay.<
> 
> This just denies xenos their main source of psy points. Xenos can't hold central map without getting attritioned so the correct choice is always to just camp caves and wait for bored marines to feed you psy points.
> 
> Also the opening of the round generally involves marines rushing caves anyway, so xenos never have a chance to contest engineering anyway.
> 
> It's be better if engineering was dead centre of the map or on the river on the marines side, but still mid map (with a bridge because attacking it over water would be terrible).
> 
> * Choc

LV has already received a mid round patch swapping Fitness and Engineering, I'm open to moving it even farther north.

**Comment by Mechswordsman** [comment]
So besides the stuff mentioned in game about changes, the best way to give the xenos more of a fighting chance in the colony, without giving them the ability to build and weed in a already dense maze, is to just add more vines and tall grass for would be skirmishers to make use of. And have it be more and more dense the further from the fob you get.   More so than it is now even.  Consider even choking the inside of colony buildings with them, which would also look cool as well.

Also I am not sure how much on the sprite side you can or are willing to do, but also consider adding in floor/wall tiles that are more overgrown as well.

**Comment by RipGrayson** [comment]
> So besides the stuff mentioned in game about changes, the best way to give the xenos more of a fighting chance in the colony, without giving them the ability to build and weed in a already dense maze, is to just add more vines and tall grass for would be skirmishers to make use of. And have it be more and more dense the further from the fob you get. More so than it is now even. Consider even choking the inside of colony buildings with them, which would also look cool as well.
> 
> Also I am not sure how much on the sprite side you can or are willing to do, but also consider adding in floor/wall tiles that are more overgrown as well.

Probably a different PR, but adding in ruined/overgrown variants for the domes would be awesome.

**Comment by ChocolateBickie** [comment]
Rolled researcher during today's round and none of the excavation sites spawned in caves, they were all in the colony.

Could just be RNG but worth checking if it's a mapping issue.

Screenshot (79)

Also North Lake Tad Ops is way too strong. Reasons;
1. Surrounding area can't be weeded. This means no walls, no healing, reduced speed for xenos.
2. Two natural barriers. The north part of the lake is rock with no flanks. The south part has a lake, which further slows down xenos.
3. Platinum miners. It is easier to secure the 2 northernmost platinum miners because of Reason 2. This gives marines alot of resources at virtually no cost.

**Comment by RipGrayson** [comment]
> Rolled researcher during today's round and none of the excavation sites spawned in caves, they were all in the colony.
> 
> Could just be RNG but worth checking if it's a mapping issue.
> 
Almost positive it's a mapping issue, I'll sort it out.
> Screenshot (79)
> 
> Also North Lake Tad Ops is way too strong. Reasons;
> 
>     1. Surrounding area can't be weeded. This means no walls, no healing, reduced speed for xenos.
> 
>     2. Two natural barriers. The north part of the lake is rock with no flanks. The south part has a lake, which further slows down xenos.
> 
>     3. Platinum miners. It is easier to secure the 2 northernmost platinum miners because of Reason 2. This gives marines alot of resources at virtually no cost.

The lake seems to a sore point for many, I'm either removing it or severely nerfing it soon.

**Comment by RipGrayson** [comment]
> Rolled researcher during today's round and none of the excavation sites spawned in caves, they were all in the colony.
> 
> Could just be RNG but worth checking if it's a mapping issue.
> 
> Screenshot (79)
> 
> Also North Lake Tad Ops is way too strong. Reasons;
> 
>     1. Surrounding area can't be weeded. This means no walls, no healing, reduced speed for xenos.
> 
>     2. Two natural barriers. The north part of the lake is rock with no flanks. The south part has a lake, which further slows down xenos.
> 
>     3. Platinum miners. It is easier to secure the 2 northernmost platinum miners because of Reason 2. This gives marines alot of resources at virtually no cost.

Researcher spawns fixed, lake no longer has grass can can't be tadpoled into.

**Comment by BraveMole** [comment]
image

This area was awfull to fight in, too cramped

**Comment by RipGrayson** [comment]
> image
> 
> This area was awfull to fight in, too cramped

Removed. 

> image
> 
> This area was awfull to fight in, too cramped

Believe it or not that's actually an area that's (nearly) the exact same between reworks. I'll adjust it to make the whole thing flow easier.

**Comment by RipGrayson** [comment]
> image
> 
> This area was awfull to fight in, too cramped


after
Changed the area you posted to be more open, made the rest of NE caves more linear. I can go the opposite direction and open the NE cave up more if you want.

**Pull request merged**
