### PR TITLE
SG Minigun balance part two

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

SG minigun windup from .4 -> .7
SG minigun sunder from 2 -> 3
SG minigun damage from 15 -> 13

Removed some unused Smartgun bullet types

## Why It's Good For The Game

More tweaking, more support focused, ammo boxes coming soon.

## Changelog
:cl:
balance: SG minigun has slightly less damage, longer windup, and more sunder.
del: Unused smartgun bullet types
/:cl:

### CODE REVIEW

**Review by BraveMole — CHANGES_REQUESTED** [review]

**Comment by goose4429** [comment]
Sunder damage is overboard already, and you want to make it bigger? Bruh. Bad PR

**Comment by Lumipharon** [comment]
50% more sunder when it's already considerably higher than the other SG weapon is a lot. I'd probably put it at 2.5 tbh.

**Comment by Arctrooper8** [comment]
This is but another temporary step, soon we shall reach perfection. Soon the supreme SG minigun shall reveal itself in all it's glory

**Comment by TiviPlus** [comment]
You should probably keep the sunder as is or nerfed if people are complaining about it already

**Comment by lordexvar** [comment]
high sunder fits the role of defensive smartgun, xenos would have almost a full second before it even starts firing meaning they are not going to be charged with this thing. plus a 1.5 second wield delay means the wielder can effectively be stunned at the start of any engagement if they are caught out and left trying to wield and reconnect the powerpack. account for aliens evading and hiding behind walls, as well as damage dropoff and how many bullets are actually going to be hitting, and this balance just brings it up to speed with the t-29 instead of being a brrrt gimmick. it might even remind xenos that armor fruit exists. i do have a feeling though that this is another [https://www.youtube.com/watch?v=RDxiuHdR_T4](url) situation.

**Review by BraveMole — CHANGES_REQUESTED** [review]
sunder cringe, no

**Comment by lordexvar** [comment]
if sunder is a no go just leave it at 2 and bump damage and pen to 20 along with the windup increase

**Comment by Arctrooper8** [comment]
IT COMES!!

**Pull request closed without merging**
