### PR TITLE
Hunters can now disguise as humans & can psychic mark without line of sight

### PR DESCRIPTION
**Pull request by Mantlecrawler**
## About The Pull Request
Allows hunters to psychic mark targets through walls & allows them to use disguise (primo ability)  to disguise as humans

## Why It's Good For The Game
https://youtu.be/OR4N5OhcY9s
Hunters mark change is mainly just QQL; as it stands, a hunter has to go run in to the line of fire, switch to the mark, mark the target, and then just run away, which really isn't all that fun and defeats the point of hunter being a stealthy xeno, and if you miss you have to wait 60 seconds to do it again. As for the disguise change, hunter primo kinda sucks right now in general because moving as a object is fairly obvious & not all that useful, and if you use it to stay still for however long you can just use stealth and 99% of marines  won't see you

A human disguised hunter can be detected by all of the following
grabbing them (automatically stuns you)
damaging them enough
IFF shooting (will hit them)
Not being able to open cades, nor rest
Medhuds wont show a icon over them
movespeed
not being able to speak common

## Changelog
:cl: Cheese
qol: Hunter's mark no longer requires line of sight
balance: Hunters can now disguise as humans with their primordial ability.  Shoot a red spy near you today!
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
im...impos...imposte...r......

**Comment by Mantlecrawler** [comment]
> im...impos...imposte...r......

you should explode spontaneously

**Comment by Looking4bros** [comment]
I would like to direct your attention to Line 40 of the Hunter's Castedatum DM file

	caste_traits = list(TRAIT_CAN_VENTCRAWL)

**Comment by Mantlecrawler** [comment]
> I would like to direct your attention to Line 40 of the Hunter's Castedatum DM file
> 
> ```
> caste_traits = list(TRAIT_CAN_VENTCRAWL)
> ```
fake, not real, not amogus.

**Comment by Mantlecrawler** [comment]
Should work properly now
a human disguised hunter will
copy the targets name
copy the targets appearance, at the moment of toggling disguise (this means it won't automatically update)
clear their own description
A human disguised hunter wont
copy the targets description (or examine text, such as the equipment list)
copy anything else from the target

this means you can detect a human disguised hunter by all of the following
grabbing them (automatically stuns you)
IFF shooting (will hit them)
Not being able to open cades, nor rest
Medhuds wont show a icon over them
movespeed
not being able to speak common

**Comment by ToasterBan** [comment]
"sorry for magdumping you I thought you were a hunter"

**Comment by Mantlecrawler** [comment]
Im half tempted to make stealth strikes do more damage if its a backstab

**Comment by FosterGrime-Heymynameslouie** [comment]
I think should make it so that hunter health appears as the human health when seen through medhud but when scanned with the medscanner it just shows "unknown biology" or something because given how common medhuds are, anyone can sniff out a hunter the moment they get in sight, point repeatedly at the guy without a medhud indicator, shout "hunter" or "xeno" and get obliterated instantly by 6 different marines

I dont know though this is all in paper havent seen it in action yet could be entirely wrong 

(could also be a double edged sword for medics who point repeatedly at an injured marine to make them stop, have other marines think medic is accusing them of being a xeno without a second thought or confirmation and have them killed lol)

**Comment by Mantlecrawler** [comment]
> I think should make it so that hunter health appears as the human health when seen through medhud but when scanned with the medscanner it just shows "unknown biology" or something because given how common medhuds are, anyone can sniff out a hunter the moment they get in sight, point repeatedly at the guy without a medhud indicator, shout "hunter" or "xeno" and get obliterated instantly by 6 different marines
> 
> I dont know though this is all in paper havent seen it in action yet could be entirely wrong
> 
> (could also be a double edged sword for medics who point repeatedly at an injured marine to make them stop, have other marines think medic is accusing them of being a xeno without a second thought or confirmation and have them killed lol)

yeah, i wanna see how it goes without that first but if its still useless i might do that

**Comment by Nerev4r** [comment]
skinwalker strain when

**Comment by TiviPlus** [comment]
This was denied at the inception of hunter because it just gives excuses/reasons to shoot/distrust teammates, which is not a playstyle that we are interested in encouraging

P.S this is why you should atomize changes, the QoL sounds fine

**Comment by Mantlecrawler** [comment]
> This was denied at the inception of hunter because it just gives excuses/reasons to shoot/distrust teammates, which is not a playstyle that we are interested in encouraging
> 
> P.S this is why you should atomize changes, the QoL sounds fine

I dont think marines need to be coddled, theres a 100 ways to tell a disguised hunter from a human; The QQL charges for hunters mark are basically useless without the other changes because hunter's mark has almost no use, asides from shifting into object with disguise. Being able to track a target isn't all that helpful when everything but the RSR stays in the main ball, silence is also useless so the miniscule buff having a target gives to that is equally as useless

**Comment by FunkyMonke47** [comment]
this is a really cool idea, why can't it get tested at least, instead of just denying it outright?

**Comment by iforgotmeword** [comment]
should be an admin only or a new xeno to itself to be real a bit saying this tho

**Pull request closed without merging**
