### PR TITLE
Reflavors brute packs and ointments to be TG-based

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Brute packs are now rolls of medical gauze.

Ointment is now regenerative mesh. (Needs to be ripped open to use)

Ported modern CM splint sprites.

Everything is identical stat-wise.

Repathed ointment.

## Why It's Good For The Game

Brute packs and ointments feel like ancient baystation12 leftover while medical gauze and mesh feels cool and tg and modern.

In my opinion the splint sprites are a bit more out of place looking than the current CM ones.

## Changelog

:cl:
imageadd: Brute packs are now rolls of medical gauze.
imageadd: Ointment is now regenerative mesh. (Needs to be ripped open to use)
imageadd: Ported modern CM splint sprites.
add: Everything is identical stat-wise.
code: Repathed ointment.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
For people that want to see the sprites

image

**Comment by Losenis** [comment]
>Ointment is now regenerative mesh. (Needs to be ripped open to use)

Doesn't this just add busywork or ripping open every mesh you have as soon as you grab it off the vendor or loadout?

**Comment by Al-1ce** [comment]
I believe they were resprited to look like the healing kits from Metal Gear. In either case I'm really not a fan of this change. I think the sprites from tg look worse by a very large margin.

**Comment by Xander3359** [comment]
Not a big fan, but also, if you are to replace burn with regen mesh, then brute should be replaced with sutures, not gauze.

**Comment by Derrick2Electricboogaloo** [comment]
I would rather not. I much prefer the ointment and gauze we have over TG-base. And their sprites were fine.

**Comment by Xsdew** [comment]
Given that Ointment and Roll of Gauze function differently to Regenerative Mesh and Sutures. It may be best to keep the sprites separate. This is purely to avoid players from assuming they function like TGMed.

**Comment by Kuro020** [comment]
Cool and tg dont fit on the same comment, also these sprites are worse than the current ones and the gauze looks like the bandages which is confusing

**Comment by Derrick2Electricboogaloo** [comment]
> Cool and tg dont fit on the same comment, also these sprites are worse than the current ones and the gauze looks like the bandages which is confusing

That is how the gauze functions, should just rename it bandages.

**Comment by Starfirejordan** [comment]
why was this killed

**Pull request closed without merging**
