### PR TITLE
Pillar of Spring's Spring Remodeling: Vehicle Bay

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

A lot of new update on PoS!

PoS

Add vehicle bay in PoS.

image

Change TO and PO's bunk

image

Expand req!
image

Note no more window frame to destroy to increase req size
image

Move droppods to be closer to req and prep
image

Move mech to where droppods were
image

move droppod closer to prep, medbay, and req
image

put briefing where droppod was
image

Spawned barbed wires next to tadpole and crowbar for TO to use.
image

Moved OB to be closer to CIC. Also add brig.
image

Due to moving OB, change location of evac.
image

Change bar and memorial for RP and flair
image

update med to have more food vendors and move surgery table closer to door so that docs can easily put patients on tables
image

## Why It's Good For The Game

https://github.com/tgstation/TerraGov-Marine-Corps/pull/15063

## Changelog

:cl:
add: Pillar of Spring's Vehicle Bay
add: Change POS's TO and PO's bunk
add: expand PoS' req
add: Move PoS' OB to be closer to CIC. Also add brig.
add: move PoS' droppod to where mech is and vice versa
add: move PoS' tadpole to where briefing is and vice versa
/:cl:

### CODE REVIEW

**Comment by coldironwarrior** [comment]
photos!! sounds good

**Review by RipGrayson — CHANGES_REQUESTED** [review]
rivbarge1
Minor nitpick, but I'm not sure I like the vendors being in the way of flow here. I understand we have limited space, but is there any other place you could put these?

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Prop carp randomly move two tiles on init, if you put them in this small space they'll get stuck in the wall or another prop. 
carp1
Should we be including hostile factions (even as props) on a marine ship from round start? I don't want to confuse people.
carp2
You have a space tile in your relocated firing room.
carp3
I don't understand the point of this change, it's a bunch of bunks and then randomly a beach? I'm not against a pool though, provided we themed it correctly.
carp4

**Comment by RipGrayson** [comment]
carp4
Spacetiles under this shutter

**Comment by lbnesquik** [comment]
So how does evac work now? Is it one giant ship?

**Comment by coldironwarrior** [comment]
east maint behind pilot bunks is space tiles

**Comment by Fawkes541** [comment]
req, pod, and tad changes are goated, I like them very much

**Comment by Looking4bros** [comment]
This killed Hangar holds, Early evac was never a real issue before, as Tad was in a prime fighting position. Horrible.

**Pull request merged**
