### PR TITLE
Add Asteroid floor sprites

### PR DESCRIPTION
**Pull request by honorconner**
## About The Pull Request
Add Asteroid floor sprites

-Added sprites

## Why It's Good For The Game
More sprites, even zoomed in asteroid photos are good. 

## Changelog

:cl:
add: New asteroid floor sprite

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
straight up looks like a picture of the moon just cut up into peices lmao

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Follow the PR template and name the PR properly.

**Comment by chizzy376** [comment]
can we get them more akin to tgmc spritework instead of being pixelated scans? not sure if these would currently fit any map without looking out of place, but I like the idea

**Comment by honorconner** [comment]
> can we get them more akin to tgmc spritework instead of being pixelated scans? not sure if these would currently fit any map without looking out of place, but I like the id

**Comment by Kuro020** [comment]
oh lol its a downsized picture of the moon wtf

**Pull request closed without merging**
