### PR TITLE
more vali knives

### PR DESCRIPTION
**Pull request by 567Turtle**
## About The Pull Request

mor evaeli knieves :)

## Why It's Good For The Game

people called me fat and stinky because there were only 6 vali knives, now they might stop

## Changelog
:cl:
balance: Amount of harvester knives in the marine vendor increased
/:cl:

### CODE REVIEW

**Comment by bluezorua** [comment]
I think just have it be req buyable would be a better option?

**Comment by Al-1ce** [comment]
> I think just have it be req buyable would be a better option?

Regular vali costs nothing. I don't see why the little knives should.

**Comment by 567Turtle** [comment]
>  I think just have it be req buyable would be a better option?

I was advised against making them buyable from req for some reason
> Regular vali costs nothing. I don't see why the little knives should.

Because you get the usefulness of a vali weapons chemical systems without the hassle of having to carry a big ol' vali weapon.

**Comment by Al-1ce** [comment]
> Because you get the usefulness of a vali weapons chemical systems without the hassle of having to carry a big ol' vali weapon

At the expense of it being completely impractical and doing almost no damage, I'd say the tradeoff is fair for it to be free?

**Comment by Alexeivichi** [comment]
Just make them infinite -MJP, probably

**Comment by 567Turtle** [comment]
If any of you ask about why its not infinite again I will do things I probably can't say
https://discord.com/channels/498569646014857217/498576457740714001/1047931329477615656

**Comment by Alexeivichi** [comment]
> If any of you ask about why its not infinite again I will do things I probably can't say https://discord.com/channels/498569646014857217/498576457740714001/1047931329477615656

> I love you Aleksy but I just want to
to grab you by the throat and throttle you

love you too man, hopefully people stop asking for more knives :)

**Comment by 567Turtle** [comment]
> love you too man, hopefully people stop asking for more knives :)

We both know damn well their hunger for knives sha'll not be quenched

**Pull request merged**
