### PR TITLE
TL-127, Mosin, and SVD lose aim-mode

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Title.

## Why It's Good For The Game

Balance? All I know is Splinter told me to do it, and snipers are super annoying to fight with it.

## Changelog
:cl:
balance: TL-127, Mosin, and SVD sniper rifles no longer have aim-mode.
/:cl:

### CODE REVIEW

**Review by SplinterGP — APPROVED** [review]

**Comment by MLGTASTICa** [comment]
finnaly , sniper stacking is gone.

**Comment by ilikesaying** [comment]
removing the only reason why people play sniper?

**Comment by David-Stormwell** [comment]
Makes the IFF sniper from req a thing to buy again, tis fine.

**Comment by SkeletalElite** [comment]
Yes let's remove aim mode from the weapon intended to be used from the back line. 

Nerf it's fire rate in aim mode instead.

**Comment by Knuff-les** [comment]
mfw the precision rifle loses it’s ability to be precise. What’s the point of sniper rifles then?

**Comment by Pariah919** [comment]
i mean this kind of makes sniper rifles useless in a sniper role most of the time

**Comment by DerrickChamberlain** [comment]
All other snipers now on suicide watch. Guess we have to hope we have req or no snipers. It is a no from me.

external-content duckduckgo

**Comment by SplinterGP** [comment]
> 
> 
> mfw the precision rifle loses it’s ability to be precise. What’s the point of sniper rifles then?

be precise by aiming yourself

**Comment by DerrickChamberlain** [comment]
My comment marked as spam?!?!?!?!!? I POSTED ONCE before this.

**Comment by spookydonut** [comment]
> 
> 
> My comment marked as spam?!?!?!?!!? I POSTED ONCE before this.

@DerrickChamberlain keep shitposting like this and you'll earn a gitban eventually.

**Pull request merged**
