### PR TITLE
Adds fat removal surgery, kills a dead var

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
Scalpel on torso with an active incision. Deals damage scaling with nutrition removed.
## Why It's Good For The Game
Adds an alternative to waiting it out/mixing custom chems
Overeat duration did nothing, so it's dead. Also relative pathing bad.
## Changelog
:cl:
add: Marines can't stop stuffing their mouths? New surgery will get them back in order, scalpel with an open incision on torso
/:cl:

### CODE REVIEW

**Comment by tyeagg** [comment]
doctors hate him

**Comment by FIXTHERADBOXPLEASE** [comment]
Feels like yet more marine powercreep. Overeating punishes marines for prepping carelessly, why make it instantly fixable with one surgical tool?

**Comment by Lumipharon** [comment]
God damn back alley doctor just hacking fat out with a butter knife.

**Comment by Losenis** [comment]
inb4 50 cases of necro as marines think they're safe by eating their 50% bloodloss off and go to the MD that has no apron, mask, nor gloves for field surgery

**Comment by FosterGrime-Heymynameslouie** [comment]
FAT

**Comment by Al-1ce** [comment]
> Feels like yet more marine powercreep. Overeating punishes marines for prepping carelessly, why make it instantly fixable with one surgical tool?

Because field-surgery is fucking dangerous. And on the off-chance that you _DO_ get sent shipside for something as menial as 0.3 slowdown, you're wasting valuable time. It's not like this is going to be the nail in the coffin for the winrate or something you alarmist shit.

I've been playing xeno here for about three years. This is QOL, not powercreep. Finishing your pretzels shouldn't result in some uncurable super-aids that lasts for half the fucking round.

Sheesh.

**Comment by Al-1ce** [comment]
> Feels like yet more marine powercreep. Overeating punishes marines for prepping carelessly, why make it instantly fixable with one surgical tool?

> Feels like yet more marine powercreep. Overeating punishes marines for prepping carelessly, why make it instantly fixable with one surgical tool?

Because field-surgery is fucking dangerous. And on the off-chance that you _DO_ get sent shipside for something as menial as 0.3 slowdown, you're wasting valuable time. It's not like this is going to be the nail in the coffin for the winrate or something you alarmist shit.

I've been playing xeno here for about three years. This is QOL, not powercreep. Finishing your pretzels shouldn't result in some uncurable super-aids that lasts for half the goddamn round.

**Comment by Al-1ce** [comment]
> Feels like yet more marine powercreep. Overeating punishes marines for prepping carelessly, why make it instantly fixable with one surgical tool?

> Feels like yet more marine powercreep. Overeating punishes marines for prepping carelessly, why make it instantly fixable with one surgical tool?


Because field-surgery is fucking dangerous. And on the off-chance that you _DO_ get sent shipside for something as menial as 0.3 slowdown, you're wasting valuable time. It's not like this is going to be the nail in the coffin for the winrate or something you alarmist shit.

I've been playing xeno here for about three years. This is QOL, not powercreep. Finishing your pretzels shouldn't result in some uncurable super-aids that lasts for half the goddamn round.

**Comment by Al-1ce** [comment]
> Feels like yet more marine powercreep. Overeating punishes marines for prepping carelessly, why make it instantly fixable with one surgical tool?


Because field-surgery is fucking dangerous. And on the off-chance that you _DO_ get sent shipside for something as menial as 0.3 slowdown, you're wasting valuable time. It's not like this is going to be the nail in the coffin for the winrate or something you alarmist shit.

I've been playing xeno here for about three years. This is QOL, not powercreep. Finishing your pretzels shouldn't result in some uncurable super-aids that lasts for half the goddamn round.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
