### PR TITLE
Gives Ravager 2 tile slash reach.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Gives Ravager 2 tile slash reach
## Why It's Good For The Game
Gives Ravager a pretty neat advantage when compared to other xenos. 
Considering he's basically runner-lite but without evasion and less speed, it's really hard for a Rav to catch up to their victim, or even to slash them at times due to their big sprite.
This aims to give Rav the power to rip and tear without falling victim to big-sprite-impossible-to-click-enemy syndrome.

I also just think it's neat that a xeno with scythe arms has above-average slash range. Makes much more sense considering how massive his spear-arms are.
## Changelog
:cl:
balance: Ravager has 2 tiles of slash range
/:cl:

### CODE REVIEW

**Comment by Lantekk** [comment]
Great PR.

**Comment by Pariah919** [comment]
what.. why?

**Comment by Xander3359** [comment]
> what.. why?

Coolness factor. I think this would be awesome

**Comment by Pariah919** [comment]
>Coolness factor. I think this would be awesome
 >
What? Why?

**Comment by chizzy376** [comment]
> What? Why?

Xali spear

**Comment by zee11zee** [comment]
Rav finally getting its own thing instad of the 50/50 endure and 78% death on rage. And vampirism only seen during seiges. I would like to see this in action.

**Comment by Tailiik** [comment]
Xali Spear

**Comment by lKiseki** [comment]
> what.. why?

Y'know, it's been a hot minute since I last agreed with MJP on something, and this is one of those occasions.
Why tho???

**Comment by Lumipharon** [comment]
Surely nothing bad could happen.

**Comment by Xander3359** [comment]
> Surely nothing bad could happen.

Pls if you intend to kill it at least TM for a bit, I would love to see the glorious xhali xpear.

**Comment by Arturlang** [comment]
I suppose there's nothing bad to seeing how horrificaly -broken- fun this is

**Comment by ilikesaying** [comment]
we should testmerge this to see if people like it :)

**Comment by lorianss** [comment]
Great PR.

**Comment by spookydonut** [comment]
This is a bad idea and the code is awful

**Pull request closed without merging**
