### PR TITLE
Makes somolent heal cloneloss before limb damage

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Per title, makes somolent heal clone before healing limb damage.
Just the way the math works out, if you heal limb damage before healing clone damage, you will heal less clone due to the limb damage healing before the clone damage checks for limb health.
## Why It's Good For The Game
The reason for this change is to provide a decent option for healing cloneloss outside of cryo.
If you are willing to engage in having high amounts of damage and sleeping in order for somolent to work, you should be rewarded for using the chem appropriately.
## Changelog
:cl:
balance: Somolent heals a bit more cloneloss while you have limb damage
/:cl:

### CODE REVIEW

**Comment by QualityVan** [comment]
You're describing why it's a buff to somolent, not why it's good for the game.

**Comment by Araulius** [comment]
why bother psydraining when you can just sleep off the clone loss even faster than before?

**Comment by BlueHNT** [comment]
I mean, there's like a whole amount of 2 people using somolent. So why not

**Comment by Joe13413** [comment]
> why bother psydraining when you can just sleep off the clone loss even faster than before?

hardest xeno cope i've ever seen... who the fuck actually uses somolent? like it's probably one of the most underused drugs in TGMC

**Comment by Coastfront** [comment]
> > why bother psydraining when you can just sleep off the clone loss even faster than before?
> 
> hardest xeno cope i've ever seen... who the fuck actually uses somolent? like it's probably one of the most underused drugs in TGMC

It's underused not for weakness but for there being a limited amount of people who are actually good at med.
Not once ever have I thought a knife many rarely use needs to sharpen to cut boulders when its already fine in adept hands.

People dont use somolent because most people don't care to make funny advanced chem mixes to necromance somebody from dead with 345874598673 damage in 15 seconds.
All this will do is make the people who DO use funny advanced chems to necromance somebody with 8 trillion damage and 90 cloneloss even more efficient when doing so.

**Comment by Lumipharon** [comment]
No proper reason provided

**Comment by QualityVan** [comment]
Slightly late, but there's decent reasoning provided. That said, I don't agree that marines need better cloneloss healing groundside, and this buff wouldn't particularly change the use or gain from somolent regardless.

**Pull request closed without merging**
