### PR TITLE
Nerfs mine boxes back down to small, and makes the normal box hold 5 again, adds a mine box that holds 10 mines

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Mines being so hilariously common isn't good for normal gameplay, and causes stupid shit like people stacking 10 mines in a corner and instagibbing everything that comes through, this is a better compromise between the increased mine count and not giving marines like 40-60 mines every round for some reason.m

Mines didn't really need a big buff.

## Why It's Good For The Game
Mines aren't fun to play against, in any way shape and form. This is a better compromise than the lootbox of the previous one

## Changelog
:cl:
balance: mines are small items again,average mine box holds 5 mines again
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -199. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SplinterGP** [comment]
Funnilly to instagib something with miners is extremely rare because the consequent explosions happen on next tick from the other mines, so most cases it doenst, unless the mob is stuck, what happens generally are grenades, i like size related they get small so for me its okay

**Comment by EvilMelonTheSecond** [comment]
Back it goes to never being used again. I don't like gameplay getting narrowed down to "just shoot gun" and I don't even see mines being used much. I kinda wanna hear more feedback from some active players before getting mines sent to shadowrealm again.

Also
"Mines aren't fun to play against, in any way shape and form"
Does this mean Carrier's hugger traps will get the same treatment?

**Comment by Pariah919** [comment]
no point to bothering

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-296). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
