### PR TITLE
hunter slash nerf

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
23 to 20
26 to 22

## Why It's Good For The Game
hunter has hilarious damage for a -1.1 to -1.4 thing

## Changelog
:cl:
balance: hunter slash downgraded
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -346. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Naaanii** [comment]
Funny

**Comment by Walarks** [comment]
Death: It is time...
Hunter: Was I a good xeno?
Death: You are here, aren't you?

**Comment by BraveMole** [comment]
there's a rework on the table, what the fuck is this?

**Comment by Chaznoodles** [comment]
As a hunter player, this is entirely fair. Hunters cause massive damage, have the pounce stun and AP in the form of stealth, as well as fast movement speeds, good health and armour. This goes towards making them a bit _less_.

> there's a rework on the table, what the fuck is this?

The rework is not good, in my opinion.

**Comment by vilereaver41** [comment]
I would argue this needs to be combined with a more useful haunt ability.

**Comment by SilencedMP5A5** [comment]
funny arm removal all day

do it

**Comment by Naaanii** [comment]
> > remove stealth slash
> > remove damage
> > Unironically worse than runner now bruh

It's still 'tanky' bruh

**Comment by Texicos** [comment]
> > > remove stealth slash
> > > remove damage
> > > Unironically worse than runner now bruh
> 
> It's still 'tanky' bruh

Speed lets you deal more damage and avoid damage, hunters extra health is meh.

**Comment by TiviPlus** [comment]
I doo ok not see this as a priority

**Pull request closed without merging**
