### PR TITLE
Raises Glove/Boot Armour

### PR DESCRIPTION
**Pull request by Chaznoodles**
## About The Pull Request

Raises Glove/Boot Armour.

## Why It's Good For The Game

Less frequent delimbing.

help how do I stop github from tagging my other account in every PR I make

## Changelog
:cl:
tweak: Raises glove/boot armour.
/:cl:

### CODE REVIEW

**Comment by Hathkar** [comment]
Buffing glove/boot armor just punishes xenos who don't know to aim for arms/legs instead of hands/feet.

**Comment by Chaznoodles** [comment]
> Buffing glove/boot armor just punishes xenos who don't know to aim for arms/legs instead of hands/feet.

To my knowledge, hands have far less max hp than the rest of the limb, making them easier to remove. This should balance that out.

**Review by Hughgent — APPROVED** [review]
var changes.

**Comment by AtlasRules** [comment]
@Hathkar if they don't know how to aim for arms/legs then i think there's more issues than this PR

**Pull request merged**
