### PR TITLE
LV624 cave tweaks and engineering expansion.

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Tweaks LV caves to be slightly more open by changing number of long straight corridors to be more curved, allowing for more varied tactics for both marines and xenos when fighting in the caves. Also expands cave engineering, allowing for more room to maneuver and makes defending the position more interesting.

## Why It's Good For The Game

Currently caves are a pain to fight in, and engineering is a pain to hold. There's little room to move around or build and marines suffer horrible attrition when trying to hold ground. Opening the cave up a little and expanding engineering allows for more creative ambushes for xenos and a little less attrition for marines.

## Changelog
:cl:
balance: LV624 caves are now slightly less cramped, engineering is slightly larger.
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Some pictures?

**Comment by RipGrayson** [comment]
Sorry, was a little frazzled getting git up and running. Here's a look at engineering before and after.
eengineer

A side by side of cave tweaks is harder, I'll try to capture some of the more visible changes.

**Comment by RipGrayson** [comment]
Here's probably the most visible change outside of engineering,  beach north of storage bridge has been opened up a bit.
caveb

**Comment by KornFlaks** [comment]
I think you got the before and after images swapped but, as a xeno main, I like it.

Engineering right now is basically a single room and if the marines cade it up, basically impossible to take back due to the long straight firing lanes from all the doors. This basically turns it more into Big Red Medical situation where plenty of acidable reinforced walls and compartmentalized interior allows for defeat in detail of any marines that try to set up shop.

I would like a screenshot of what you did north of engineering. That 2 tile wide vertical hallway got more xenos killed than any marine. Please either open it up to more fortifications or somehow angle it so a marines cant just camp the bottom and conduct a firing squad down the lane.

**Comment by RipGrayson** [comment]
As requested, a picture of the area north of engineering. Left is original, right is current PR.

ncave1

**Comment by davidchan13** [comment]
> Sorry, was a little frazzled getting git up and running. Here's a look at engineering before and after.
> eengineer
> 
> A side by side of cave tweaks is harder, I'll try to capture some of the more visible changes.

You've got the before and after mixed up.

**Comment by RipGrayson** [comment]
> > Sorry, was a little frazzled getting git up and running. Here's a look at engineering before and after.
> > eengineer
> > A side by side of cave tweaks is harder, I'll try to capture some of the more visible changes.
> 
> You've got the before and after mixed up.

Well I did say I was frazzled, I'll edit my post to fix the image soon. Thanks for reporting!

**Comment by Ieteihowmee** [comment]
Looks solid.

**Comment by RipGrayson** [comment]
Barring any requested changes, this is ready to be merged or tested. I'm done making nitpicky changes.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
