### PR TITLE
Webbing reduction

### PR DESCRIPTION
**Pull request by Hughgent**
:cl:
code: made webbing storage list equal to armor
/:cl:

the three slot webbing had a list of ammo_magazines it could hold, while the armor did not. Made the webbing list the same as the armor list. left the original list in as a comment.

### CODE REVIEW

**Comment by Rohesie** [comment]
We can filter them by size.

**Comment by Hughgent** [comment]
Added "hold.max_storage_space = 9" to be in line with the armors 2 slot max hold of 6.

as @spookydonut mentioned, tank ammo does NOT fit in the webbing now.

**Comment by spookydonut** [comment]
dont break bypass_w_class just for the sake of this, its fine how it was.

You cant filter by size because it bypasses size restrictions.

**Comment by Hughgent** [comment]
this is an issue that extends out to marine armor storage as well. it only has "/obj/item/ammo_magazine" in it's bypass list.

I think this can be overcome with the w_class on certain ammo_magazines. Everything in the /tank is at 10 or above, which doesn't fit this new webbing.

the other issue is Flamer tanks for the Pyro is currently set at w_class = 3
rockets for the sadar spec are set at w_class = 3 also

**Comment by Hughgent** [comment]
I believe this comes down to three options.

1. make armor storage equal to current webbing storage exemptions.
- limits specialists (Pyro and Sadar) ammo carrying capabilities.
- fixes being able to carry shotgunbox in armor storage
- another place to remember when adding new ammo_magazine types

2. make webbing equal to current armor as per this PR
- makes adding future weapons easier as there is no need to remember this exception list (see Sur's Sunfury lasgun)
- /ammo_magazine that shouldn't fit into webbing needs to be w_class =10 (or greater)
- said w_class =10 ammo_magazines also won't fit into backpacks

3. leave well enough alone and forget about it.

**Comment by spookydonut** [comment]
3, spec ammo comes under /rifle/

**Comment by Hughgent** [comment]
Pyro and Sadar ammo isn't under Rifle. 
The "large incinerator tank" the backpack fuel tank, two of them fit nicely into the armor inventory because it's a child of the squad leader flamer_tank.

Same with the Sadar m5 rockets, two of those also fit into the armor inventory due to the armors exception list and the rockets w_class.

This all could be a large amount of technical debt relating to w_class because the scale goes

1. cigs and things that fit inside the palm of the hand
2. things the size of your hand, pill bottles
3. magazines and longer items, defibs, tele beacon
4. things too big for a backpack
5. most boxes that you carry
then 10 and up for really really big things

but really, in the end, it boils down to this

are the 2 pockets on the armor bigger than the 3 pockets on the webbing?

**Comment by spookydonut** [comment]
then change armor slots to match webbing

**Comment by Hughgent** [comment]
gonna "bugfix" armor storage instead

**Pull request closed without merging**
