### PR TITLE
Buffs default light range, removes Baldur

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Increases the default light range of most undersuit and armor choices to the maximum possible value of 6.
Removes Baldur, since all choices already hit the cap and Baldur is doing practically nothing as a result.

## Why It's Good For The Game
Marines gain better visibility and can better contest xenos in dark environments. Requiring imagers to properly fight in the darkness does not seem like a good thing from a design standpoint.

This PR is open at the same time that #11887 is; both were meant to be in the same PR, but I found it a more sensible choice to separate these into two PRs, so as to give maintainers options to choose from.

## Changelog
:cl: Lewdcifer
del: The Baldur armor module has been removed.
balance: All clothing and armor choices have had their light range increased to the maximum possible value of 6.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
Rest in peace my boy baldur, forever gone. Now the only 0 slowdown module is vali.

**Comment by MiniMeatwad** [comment]
I wonder what happens when you let Xenos drag flares around instead of having to melt them, causing flares to become useless, the only other source of light for marines?

**Comment by Mrrpip** [comment]
> Rest in peace my boy baldur, forever gone. Now the only 0 slowdown module is vali.

And the arrowhead.

**Comment by FIXTHERADBOXPLEASE** [comment]
> I wonder what happens when you let Xenos drag flares around instead of having to melt them, causing flares to become useless for area control, and diminish the only other source of light for marines?
This isn't a nerf, it's basically just giving everyone built-in Baldur.

**Comment by RuneQuester** [comment]
> > I wonder what happens when you let Xenos drag flares around instead of having to melt them, causing flares to become useless for area control, and diminish the only other source of light for marines?
> 
> This isn't a nerf, it's basically just giving everyone built-in Baldur.

Which...is a buff to marines, considering now everyones light range is much much bigger, even on xenonauten.

**Comment by Tupinambis** [comment]
Marines have flares if they're not using them that's their problem. Flat out buffing marine vision across the board with no opportunity cost is a terrible idea.

**Comment by Waselon** [comment]
изображение

**Comment by Coastfront** [comment]
Removing a walking cane to then teach its user to sprint a mile.
This is just a hard buff to marines with no downside

**Comment by bowlofcereal** [comment]
i beg of you to stop removing stuff for the sake of removing them and instead consider incentivizing the other multiple light source options we have

**Comment by RuneQuester** [comment]
I seriously can't understand why its good for the game.  
> Marines gain better visibility and can better contest xenos in dark environments
Use flares, or light shells, or anything else. 

> Requiring imagers to properly fight in the darkness does not seem like a good thing from a design standpoint.

Xenos require the light to operate effectively. Marines have other options for lights. Its Fine

**Comment by Alexeivichi** [comment]
Power creep.

**Pull request closed without merging**
