### PR TITLE
Pump shotgun rework+Paladin 12 attachments

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Buckshot no longer deals 240 damage, now deals 165 damage if all pellets connect.

Max range of the effects of the main pellet and side pellets staggerstuff is now 5. Halved falloff and less spread. 3 knockback rather than 2.
Side pellets deal /1 slowdown.  Per hit
Flechette deals 10 less damage, .5 more sunder.

Slugs deal 0.5 slowdown
Paladin 12 has bayonets now.

## Why It's Good For The Game
12 gauge shotguns should honestly be relegated to a more support oriented role rather than being this stupid big dick damage machine that encourages rocket tag gameplay, they were the last vestiage of the rocket tag era in tgmc and this aims to reduce them to a more reasonable level.

## Changelog
:cl:
balance: Buckshot deals 165 from 240 damage, flechette unchanged, slugs now deal slowdown once again. Buckshot knocks back a tile further and all the pellets deal slowdown.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -189. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
I can feel the salt coming

**Comment by David-Stormwell** [comment]
buckshot is life, buckshot is love

**Comment by Pariah919** [comment]
oops i've made a mistake

**Pull request closed without merging**
