### PR TITLE
All Tyr modules are no longer available in HvX

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title. Alternative PR made in #14874 that keeps Tyr 1, so maintainers can choose whichever of the two they prefer.

## Why It's Good For The Game
We're trying to cut down on just how tanky marines can be, and this is one of many offenders.

## Changelog
:cl: Lewdcifer
del: Tyr modules are no longer available in HvX game modes.
/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
Not needed.

**Comment by TellyLsc** [comment]
Why? HeavyTyr users move slow enough as it is don't they?
Tyr in general is already a very mid tier armor module with how bad the armor:slowdown ratio is.
LightTyr is literally less armor for more slow than medium, and MediumTyr is "might as well use heavy armor".

**Comment by Pariah919** [comment]
My opinon on this is that you might as well remove every module as you remove Tyr, we're just falling own on the list.
If you remove tyr the obvious next pick is mimir to become immune to acid foreva, after you remove mimir the obvious pick becomes valk, if you remove that one the pick is pretty much between free health scan or slightly more light. Which is.. Not even a choice honestly, as for hlin/surt they're easily rollable into specialized armors which already exist.

**Comment by TellyLsc** [comment]
Oh wow, no more Tyr2 instead? Let's just buy riot armor then.

**Comment by yyzsong** [comment]
> might as well remove every module as you remove Tyr

If you so much as even touch baldur I'm gonna hurt you

**Comment by FosterGrime-Heymynameslouie** [comment]
> My opinon on this is that you might as well remove every module as you remove Tyr, we're just falling own on the list. If you remove tyr the obvious next pick is mimir to become immune to acid foreva, after you remove mimir the obvious pick becomes valk, if you remove that one the pick is pretty much between free health scan or slightly more light. Which is.. Not even a choice honestly, as for hlin/surt they're easily rollable into specialized armors which already exist.

Screenshot 2024-01-16 104843

**Comment by SimplySmiley123** [comment]
> 
> Screenshot 2024-01-16 104843

As long as there's any equipment left on the ungas some xeno player is gonna want something nerfed.

**Comment by Yttriums** [comment]
Devo to puppeteer is free.

**Pull request closed without merging**
