### PR TITLE
Bike nerf

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Two changes to bikes to make them less cheesy in terms of their abusable game mechanics.

You can now jump over bikes (a mob bucked to it will still block you however)

Xenos and explosions can knock bikes over, making them nondense and briefly stunning any occupants.
Humans can flip the bike back so it can be ridden again.

Its only a 10% chance on xeno melee attacks (and you do need to hit the actual bike) but it means xenos aren't just completely ggnore'd if they get trapped behind a bike.
## Why It's Good For The Game
The ability to hard trap xenos isn't great gameplay for xenos.
## Changelog
:cl:
balance: Bikes can be jumped over
balance: Bikes can be knocked over by xeno melee attacks or explosions
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
i have a feeling it being rng like this will make it shit for both sides

**Comment by Lumipharon** [comment]
If its a guaranteed thing, that kills bikes entirely for combat use. I don't personally mind using bikes to fight, other than funny trapping stuff, but open to suggestions.

**Comment by ivanmixo** [comment]
Damage treshold of some kind even.. I don't know what would be best.

**Comment by Lumipharon** [comment]
Damage threshold would be the same as just nerfing its hp to be honest. Once it falls over the rider is either dead or running away

**Comment by Nuker555** [comment]
maybe dont hard commit to 1 tile openings instead of nerfing bike?

**Comment by SimplySmiley123** [comment]
> maybe dont hard commit to 1 tile openings instead of nerfing bike?

Xeno players when they can't always overextend and eat whole ungaball worth of lead and walk out easly and very much alive 100% of the time.

**Comment by Tommy-211** [comment]
> maybe dont hard commit to 1 tile openings instead of nerfing bike?

Clearly one of TGMC's greatest minds

**Pull request closed without merging**
