### PR TITLE
No more hunter stealth attack

### PR DESCRIPTION
**Pull request by InterroLouis**
## About The Pull Request

Removes Hunter Sneak Attack

## Why It's Good For The Game

Sneak Attack Gone
## Changelog
:cl:
balance: Sneak attack is gone from hunter
/:cl:

Closes #3390 
Closes #3439

### CODE REVIEW

**Comment by spookydonut** [comment]
#3390

**Comment by Rohesie** [comment]
Travis failing.
People really want this gone.

**Comment by spookydonut** [comment]
> 
> 
> Travis failing.
> People really want this gone.

Not without a replacement

**Comment by spookydonut** [comment]
#3390 
#3439

**Pull request closed without merging**
