### PR TITLE
Clean Up Action Icons

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
removes the frames from actions and replaces them with semi transparent minimalist ones also includes resprite of minimap icon also fixes autodoc not showing that its activated because its sprite was over the toggle frame
image
## Why It's Good For The Game
cleaner look and the entire top left of your screen is now more visible
## Changelog
:cl:
imageadd: new action frames, show/hide order option icons, and minimap action icon
fix: autodoc not showing that its activated, join larva queue not showing that its activated and empowered ability not disappearing 
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
this looks cinredibly cool wtf

**Comment by lbnesquik** [comment]
Not 2 be rude, but can you check every frame to make sure that there's always enough contrast on them?

**Review by Kuro020 — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Comment by Tupinambis** [comment]
I think the icons should still have purple shading, it's more aesthetically consistent and pretty.

**Comment by Jalopkomit18** [comment]
Much less of an eyesore, doesn't feel like I'm playing a roblox game as much. Very nice

**Comment by Lumipharon** [comment]
Unfug the warlock psyblast/lance sprites. You can reuse the originals from projectiles or replace them if you prefer.

**Pull request merged**
