### PR TITLE
Fixes Reqtorio surt module printing violins 

### PR DESCRIPTION
**Pull request by chizzy376**
Reqtorio part 2 electric boogaloo
## About The Pull Request
Fixes surt recipe making violins
## Why It's Good For The Game
Another bad recipe squashed, reqtorio players in awe
## Changelog
:cl:
fix: Creating surt modules through reqtorio should no longer disappoint you with 10 violins
/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
no more roqtorio cope

**Comment by Naaanii** [comment]
Damn, how does it keep happening?

**Comment by chizzy376** [comment]
NOBODY tested the og reqtorio PR, and thus many broken recipes slipped through the cracks.

**Comment by Naaanii** [comment]
> NOBODY tested the og reqtorio PR, and thus many broken recipes slipped through the cracks.

I tested it but it seemed to work for the most part, at least the shared recipes did.

**Comment by MLGTASTICa** [comment]
world's most expensive violins.

**Pull request merged**
