### PR TITLE
Fix long hair getting its top cut off by helmet

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

image

my hair

## Why It's Good For The Game

It looks better, also Lumi told me that I could fix it IF other hairs don't look bad on new alpha. They look pretty fine, to be honest.

Just comment in PR which hair to test out new alpha, and I test them out and post screenshots.

## Changelog

:cl:
fix: Fix long hair getting its top cut off by helmet
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
Femstatics rejoice.

**Comment by Al-1ce** [comment]
Ziegler?

**Comment by Al-1ce** [comment]
Ziegler, Mulder and Bed 2? I see these pretty often.

**Review by TiviPlus — APPROVED** [review]
get kuro to merge

**Pull request merged**
