### PR TITLE
Tanky xenos get more sundering capacity

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Queen 100 > 150 sunder
King 100 > 150 sunder
Crusher 100 > 200 sunder
Defender 100 > 150 sunder

## Why It's Good For The Game

Hopefully this makes slow tanky xenos more comfortable to play since they suffer the most from sundering feature.

## Changelog
:cl:
balance: Queen, King, Crusher and Defender get more sundering capacity
/:cl:

### CODE REVIEW

**Comment by Alexeivichi** [comment]
Values are too high, will break the balance and cause massive xeno Ws endlessly. Try smaller value increases instead, maybe?

**Comment by DeltaFire15** [comment]
Don't all sunder heals heal flat sunder? 
This just makes beans more hard to crack, while sending them to rest jail for even longer if they get hit by any funny "you are now sundered to hell" weapons. (crusher needs to rest for twice as long to get the same amount of armor% back, for example)

**Comment by ivanmixo** [comment]
These are the castes that are supposed to suffer from sunder though

**Comment by Pariah919** [comment]
I gave crusher lowered sunder in the crusher pr I made ages back because I gave it less HP. All this does is make tanky xenos resistant to armor breaking despite that being supposed to be one of their big downsides, funny powercreep really.

**Comment by bowlofcereal** [comment]
the entire point of sunder is to effect tanky xenos so they actually get punished

**Comment by Waselon** [comment]
I think tanky xenos should recieve updated sunder values since marine sundering capabilities have been inevitably increased over the years.
Values are going to get lowered if a maintainer says so.

**Comment by tmurphy7** [comment]
While I think there should be some sunder tweaks, the values on 95% of xenos is fine as is.  The only caste I think that should have a sunder capacity increase is King because most of their abilities require them to stand still and tank damage for a while, making them more susceptible to sunder.  Even then, King is mostly fine overall, so I'd only argue for 125% on king at most.  The rest of these would just make those xenos unbearably strong.

**Comment by Pariah919** [comment]
> I think tanky xenos should recieve updated sunder values since marine sundering capabilities have been inevitably increased over the years. Values are going to get lowered if a maintainer says so.

The only sunder straight buff have mostly been like... some mounted weapons and GPMG if I remember right? If anything, sunder is LOWER across the board than it was on release, most things have reduced in sunder, and or otherwise stood the same. The biggest changes has been makign railgun magfed and reducing its sunder to 50 and me making disposables more expensive. (which is a net positive for game health imo) 

Either way sundering is basically nearly the same as it was on release, so that's not a good justification.

**Comment by Waselon** [comment]
> > I think tanky xenos should recieve updated sunder values since marine sundering capabilities have been inevitably increased over the years. Values are going to get lowered if a maintainer says so.
> 
> The only sunder straight buff have mostly been like... some mounted weapons and GPMG if I remember right? If anything, sunder is LOWER across the board than it was on release, most things have reduced in sunder, and or otherwise stood the same. The biggest changes has been makign railgun magfed and reducing its sunder to 50 and me making disposables more expensive. (which is a net positive for game health imo)
> 
> Either way sundering is basically nearly the same as it was on release, so that's not a good justification.

_Flechette casually removing half of the xeno armor in just 3 shots_

**Comment by TiviPlus** [comment]
See bowl/ivan/mjp/etc comments

**Pull request closed without merging**
