### PR TITLE
Add Kabuto armor, a Japanese-Inspired Armor

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

PROTECTOR OF YOUTH
VOICE OF ALL UNGA
KAAAAAAAAAAAAMEEEEEEEEEEEEN COOOOOOOORRRRRRRRRPPPPPPPPPPPPPPP

salmon color
image

SPOILER_kamerider

## Why It's Good For The Game

https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/39d2dac6-a4bb-4819-99ac-78edff6fb43c

More armor! Kuro approves! 

image

image

Find Kabuto armor in style tab as compromised.

image

## Changelog

:cl:
add: Kabuto armor, a Japanese-Inspired Armor; find it in the style line tab!
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
grif rejoice

**Comment by QualityVan** [comment]
Does not let the wearer perform a jump kick, 0/10

**Comment by ilikesaying** [comment]
Karate Bugman Armor my beloved

**Comment by Tonklaatech** [comment]
SUPER SENTAI!!!!

**Review by TiviPlus — APPROVED** [review]
Anime begone code ok

**Comment by Wirpy** [comment]
bug inspired

**Comment by Sirsnek15** [comment]
Based

**Pull request merged**
