### PR TITLE
Significantly reduces snow storm opacity

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Reduces the opacity of snow by about 50% due to complaints.

## Why It's Good For The Game

The current snow effects are blinding and you cannot see anything while they're going on. People are complaining in OOC that this is worse than acid rain and calling for the removal of snow effects altogether.

BONUS: Here's a video of a marine in a snow storm with our current effects.
dreamseeker_QkHa2opRcR

unknown2
unknown

## Changelog
:cl:
qol: Snow storms are significantly less blinding
/:cl:

### CODE REVIEW

**Comment by Spyroshark** [comment]
not being able to see is a feature

**Comment by Lumipharon** [comment]
It's so bad it's kinda good.

**Comment by Mechanelize** [comment]
this time its an actual feature

**Comment by BraveMole** [comment]
Not being able to see is a feature. Everyone loves random spraying

**Comment by Lefunny** [comment]
God be saved

**Comment by TiviPlus** [comment]
Post pictures

**Comment by RipGrayson** [comment]
New snow opacity (with suit light on)
dreamseeker_9goKbcYbkw
Old snow opacity
dreamseeker_57X6fgIL1J (with suit light on)

**Review by TiviPlus — APPROVED** [review]
@Kuro020

**Review by Kuro020 — APPROVED** [review]

**Pull request merged**
