### PR TITLE
Make Miner minimap icons show if they are active

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

image

## Why It's Good For The Game

Minimap is more useful.

## Changelog
:cl:
expansion: Miner minimap icons now show if they are active or not.
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by BraveMole** [comment]
Death to stealth mining

**Comment by EvilMelonTheSecond** [comment]
Can we revert #7125 with this if stealth mining ain't gonna be an issue anymore?

**Comment by KornFlaks** [comment]
Is this marineside or universal to both marines and xenos?

I guess it doesnt really matter since dead xenos can ghost and scan the map instantly and check for miners. Then respawn and slash them.

**Comment by Wayland-Smithy** [comment]
Correct the miner icons are universal so long as you have map access.

**Pull request merged**
