### PR TITLE
Sniper Kit Buffs

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl: by Surrealistik
balance: Sniper improved to be more on par with other spec kits.
tweak: Sniper NV range increased from 12 to 24 tiles. Laser targeting range increased from 23 to 24 tiles. Sniper rounds inflict 3 slow stacks on hit (subject to tweaks).
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
No damage and penetration buffs, please.

**Comment by Surrealaser** [comment]
@Rohesie 10% is fine and doesn't hit any key breakpoints.

**Comment by Rohesie** [comment]
Nope.

**Comment by Surrealaser** [comment]
> Nope.

If you're going to contradict me, at least come with some math/facts supporting your assertion.

**Comment by DominikPanic** [comment]
Welp, you two should talk it out.

**Comment by Surrealaser** [comment]
@DominikPanic I've removed the bonuses, fuck it.

**Pull request merged**
