### PR TITLE
ERT Changes

### PR DESCRIPTION
**Pull request by XSlayer300**
## About The Pull Request
Changes many of ERT's loadouts. Plus some changes and fixes.

## Why It's Good For The Game
It removes most of the bad and duplicate stuff from the ERT with actually good ones.

## Changelog
:cl:
tweak: Changed most of the ERT loadouts, it is expected to be more useful than before.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -36. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Swagile** [comment]
i have no idea how to do reviews, so ill just say this here

the only real questionable part I can see is giving the AT sniper role 2 extra AT sniper mags, considering the 3 they get in their pouch and one already in is enough to wipe out multiple xenos alone, let alone with concentrated fire with other PMC's such as a PMC SG.

**Comment by XSlayer300** [comment]
> i have no idea how to do reviews, so ill just say this here
> 
> the only real questionable part I can see is giving the AT sniper role 2 extra AT sniper mags, considering the 3 they get in their pouch and one already in is enough to wipe out multiple xenos alone, let alone with concentrated fire with other PMC's such as a PMC SG.

Any suggestions on what to fill up other than the mags?

**Comment by Swagile** [comment]
> 
> 
> > i have no idea how to do reviews, so ill just say this here
> > the only real questionable part I can see is giving the AT sniper role 2 extra AT sniper mags, considering the 3 they get in their pouch and one already in is enough to wipe out multiple xenos alone, let alone with concentrated fire with other PMC's such as a PMC SG.
> 
> Any suggestions on what to fill up other than the mags?

2 tangle foots instead.

lets the IFF sniper escape or engage big hordes

**Comment by XSlayer300** [comment]
Waiting...

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-38). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
