### PR TITLE
Hivemind core is trackable by the xeno structure pinpointer

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

- Hivemind core is trackable by the xeno structure pinpointer
- This required me making it a `/obj/structure/xeno` instead of `/obj/alien` to avoid shitcode

## Why It's Good For The Game

It makes sense, right? Hiveminds often hide themselves similar to maturity/evolution towers so there should be some way to track them down.

## Changelog
:cl:
balance: Hivemind core is trackable by the xeno structure pinpointer
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
While the core is a structure, it's still a caste.

This also makes it even easier for someone to just pod down and kill the hive core on hijack.

**Comment by lKiseki** [comment]
Bear in mind that if the core is cleared, the hivemind is pretty much out of the round until they get a larva again.
Were this a mere structure, nobody would mind; but given that it's a player, I disagree with this change.

**Comment by Weedmaster77** [comment]
A good hivemind player is super useful and this would give marine as way to take them out instead of just running around the whole map to find them. I think its a nice idea and makes the hivemind not just build the core in a stupid spot and make lots of walls, so they either build by the silo so its protected some or build in so hidden spot and risk it. Seems good so it forces hivemind to make a hard choice so either be stealthy with placement of protected.

**Comment by Dgeen** [comment]
>  hard choice so either be stealthy with placement of protected.

On the contrary, it deprives you of a choice. Right now you have a choice - hide the core or put it in a safe place. If it is added to the monitored structures, you will have no choice, you cannot bet on invisibility when marin has a direct arrow on you.
Also, mind is already very limited, and has a low quality of life. To make it even worse, it needs to be the height of unreasonableness.

**Comment by ivanmixo** [comment]
I'm not sure why the hivemind is entitled to being effectively immortal, compared to a hivelord, for example. They fulfill essentially the same function, but hivemind is both immortal and it can build and weed at range, not to mention them moving at mach 1 speed, allowing them to easily escape.

Dying for the hivemind also barely matters since it doesn't age, so the player could just queue and be back where they were in like 5 minutes from spawning, shouldn't take that long to get a larva with nuke war being played so much.

A good hivemind can be an absolute game changer for the xenos, but unlike someone being good at any other caste it's very hard to kill unless you're about to destroy the silo.

**Comment by Losenis** [comment]
A competent hivemind is already stupidly oppressive and can lead to an entire push getting wiped since it can weed, wall, not give a shit about getting shot to death, on top of weird things like weeding through walls and so on. One tends to forget about the potential of a hivemind until you suddenly find out the rear of the push got walled off by something that will come back even if you hit it with a sadar. The only way to kill it is to get to its core which sometimes can also mean having to successfully push to the silo itself through all the other xenos, so this feels like a good change for avoiding funny hivemind core hiding god knows where and realistically only a guy with mesons being able to spot the hole in the hundred thousand resin walls around.

**Comment by Weedmaster77** [comment]
> On the contrary, it deprives you of a choice. - hide the core or put it in a safe place.

You act like if this was merged you couldn't do that still, but yes it take away hiveminds  "Oh my safe place that no one can find me unless they run all around the map "crap but you still can put yourself away from the silo, and add in more choices for marines to split the marine push if they want to get rid of you and want to push silo at the same time which happens or plant at the silo and get the silos protection.  

> Also, mind is already very limited, and has a low quality of life.

Limited is not true at all Hivemind are better frontline builders then all caste but Queen and maybe Shriker. Also can be dropped to 0 health and wall marines in from behind with very little consequences, they have one of the best if not the best quick heal abilities, on top of having better Pheros then Shriker and one of the best movement speeds, and can phase out of reality and run. As for quality of life they have the same as all building and noncombat caste which is not great and most people don't like to play so that is not a good argument.

**Comment by Al-1ce** [comment]
I have to agree with [Losenis](https://github.com/Losenis) here. It isn't ideal, but this is a pretty good solution.

> This also makes it even easier for someone to just pod down and kill the hive core on hijack.

Nearly every round the hivemind is evolved near the silo. If you willingly build somewhere "hidden" or "away", then you accept the risks that follow. This really isn't as big of an issue as you're making it out to be.

**Comment by Dgeen** [comment]
`they have one of the best if not the best quick heal abilities`
He has shrike heal, and this is worst heal in the game, drone heal much better, and i don't talk about hivelord, which has best heal. Hivelord also have stronger wall & door, access to many additional structures. He better than HM in everything, except maybe weeding and speed. 
Also
`and add in more choices for marines to split the marine push if they want to get rid of you and want to push silo at the same time which happens or plant at the silo and get the silos protection.`
 I don't understand what kind of separation of marins you are talking about, just one marin with a pinpoint will go along the edge of the map and kill hm. Good luck catching him, only if you're not going to surround another point with acid turrets

**Comment by Weedmaster77** [comment]
> He has shrike heal, and this is worst heal in the game, drone heal much better

So unless the Wiki is out dated on the drones heal ability there the same as shriker and hivemind but the ability takes into count the current heal phero aura present to which the Hivemind's aura is better then drone so it still quick heals more if the Hivemind is using heal pheroor has stronger phero near.


> I don't understand what kind of separation of marins you are talking about, just one marin with a pinpoint will go along the edge of the map and kill hm. 

So yes this happens but not only do they have to have a pin pointer which isn't just given to anyone other then the one in REQ vendor but all it takes is on combat caste that knows how to fight and they can pick off a single marine even some of the most robust marines out there die to a runner when there all alone deep in a maze and that is not accounting for if the hivemind is helping the one other xeno with heals or pheros. 

> Good luck catching him, only if you're not going to surround another point with acid turrets.

So if the xenos value there Hivemind they go put even one turret at there hidden core even a resin turret for 50 PP will do for alert. This would force the xenos to value the hivemind core more then they do and maybe add so more team communication or awareness of there team.

**Comment by Losenis** [comment]
Hivemind is the only caste that can do anything it wants without risk of death. Hivemind can waltz in and heal the xeno about to die in situations where a hivelord, shrike, queen, drone, etc would get instakilled by a sadar or shot to death. The most a hivemind would get is a short timeout as it waits to heal. It can even go corporeal and dive into an ungaball to shuffle everyone for shits n giggles and even get a few FF incidents _purely for laughs even if it has no actual concrete benefit_. If you want to compare abilities, you have to increase the range of whatever it's being compared to so much that it won't really care about danger.

**Comment by Dgeen** [comment]
>  Wiki 

Bruh

>  drones heal ability there the same as shriker and hivemind

Now i see, you never played for xeno. Maybe you can try to play a couple of rounds for them? At least you will stop inventing their abilities...
Joke aside, drone have a small heal with 5 sec cd, and hm have big heal with 1 minute cd. While hm heal one xeno, drone can heal 2 or 3. Queen also have drone heal ability.

> So yes this happens but not only do they have to have a pin pointer which isn't just given to anyone other then the one in REQ vendor but all it takes is on combat caste that knows how to fight and they can pick off a single marine even some of the most robust marines out there die to a runner when there all alone deep in a maze and that is not accounting for if the hivemind is helping the one other xeno with heals or pheros.

Robust marin just won't catch your eye until it's too late. That's all. There will be no fight, and even if you kill him after, the life of 1 Marine is worth nothing.

> So if the xenos value there Hivemind they go put even one turret at there hidden core even a resin turret for 50 PP will do for alert. This would force the xenos to value the hivemind core more then they do and maybe add so more team communication or awareness of there team.

Oh, yes, resin turret. Well, they'll be in time for the wake. Even if they enlist the support of the Hive Lord (isn't it funny?, a support needs a support to get a chance of survival), if you don't position several turrets, one marine will still be able to kill hm.

**Comment by Naaanii** [comment]
A better solution would be to nerf the ability of Hivemind to spam out walls instead of this.

**Comment by Weedmaster77** [comment]
> Now i see, you never played for xeno. Maybe you can try to play a couple of rounds for them? At least you will stop inventing their abilities... Joke aside

So instead of being a prick about something that is untrue and you have no idea about when this is for constructive feedback, just state what info I am unaware of and leave it to that, don't assume things about people that have nothing to with the thing that is being discussed and try to act its a joke. Also for you future info I rarely play drone, shriker or queen and mostly play hivelord if I am playing support or I play combat caste.  

> Robust marin just won't catch your eye until it's too late.

This is not set in stone when marines get killed often going alone to hunter hivemind, reguardless of how robust they are. 

> There will be no fight, and even if you kill him after, the life of 1 Marine is worth nothing. 

The worth is Hivemind doesnt lose their core and if it was a robust marine hunting it really can count of a lot. Some of the best marine do the work of three or four not experienced and knowledgeable marines.

> Oh, yes, resin turret. Well, they'll be in time for the wake. Even if they enlist the support of the Hive Lord (isn't it funny?, a support needs a support to get a chance of survival), if you don't position several turrets, one marine will still be able to kill hm.

You are missing my point the turrets not about kill them or even slowing them down its about the alert it give to all xeno. An god forbid Hivemind have to ask a teammate to come and help build a turret in a team game.  

> Except attacking. HM has already paid the price for his supposed immortality. He can't fight, and also he can't move his core. 

Yes Hivemind cant attack as the trade off for Hivemind's ability to change locations quickly and go from building for defense and building to wall in marines that is his roundabout attack. Walling in a push from behind very easily and getting marines trapped and killed is Hivemind's value to offensive pushes, even if other caste can do the same they cant just phase though a ungaball and start walling them in quick and that time matters often to if any marine escape of all wipe.

**Comment by Losenis** [comment]
"Some of the best marine do the work of three or four not experienced and knowledgeable marines."

My brother in Ra I don't think you understand how utterly braindead normal "not experienced and knowledgeable marines" are. I've seen shit you wouldn't believe. T60s backlining without aim mode, shotgunners on harm intent trying to push to the front moving people into turrets, ungas moving into the line of fire of the RR that had previously spamclick to make the alert icon as visible as possible, people shuffling medics in the middle of defibs that lead from red to perma, medics that deliberatedly leave their beacon unlinked on the floor in prep, people that unironically play PO.

You'd do the work of multiple people by doing nothing given how much work the average marine is capable of undoing by their baldness. And that's coming from me who landed the tadpole on top of the red disk generator yesterday.

**Comment by Weedmaster77** [comment]
> My brother in Ra I don't think you understand how utterly braindead normal "not experienced and knowledgeable marines" are. I've seen shit you wouldn't believe. T60s backlining without aim mode, shotgunners on harm intent trying to push to the front moving people into turrets, ungas moving into the line of fire of the RR that had previously spamclick to make the alert icon as visible as possible, people shuffling medics in the middle of defibs that lead from red to perma, medics that deliberatedly leave their beacon unlinked on the floor in prep, people that unironically play PO.


I do I am just giving the baldness the benefit of the doubt since everyone was somewhat bald at one time and many of them learn if they hang around or ask people with experience. 

> And that's coming from me who landed the tadpole on top of the red disk generator yesterday.

 We all do dumb shit by accident even players with 2000+ hours do its just they don't most of the time.

**Comment by Dgeen** [comment]
> So instead of being a prick about something that is untrue and you have no idea about when this is for constructive feedback, just state what info I am unaware of and leave it to that, don't assume things about people that have nothing to with the thing that is being discussed and try to act its a joke. Also for you future info I rarely play drone, shriker or queen and mostly play hivelord if I am playing support or I play combat caste.

Wow, how serious we are. Well, then maybe you'll start with yourself? And before you tell me about how to conduct a discussion, will you start reading what other write to you?
I directly pointed out that the heal drone, shrike and hm are different in my first message, but you continued to bend your line, so also referring to the wiki. It is quite difficult to talk seriously with a person who uses wiki as information.

> The worth is Hivemind doesnt lose their core and if it was a robust marine hunting it really can count of a lot. Some of the best marine do the work of three or four not experienced and knowledgeable marines.

You missing my point. I meant that the exchange of 1 marin for the core is very beneficial for them (as well as any exchanges in principle).

> You are missing my point the turrets not about kill them or even slowing them down its about the alert it give to all xeno. 

I get your point, but you missed my. I said that the warning itself will not help if you do not place it at a sufficient distance from the core (and then we will need several turrets) or use a turret that can slow down the marina (that is, an acid turret)

**Review by Pariah919 — APPROVED** [review]
Seems good to me.

You can't really find hivemind outside of the obvious 50 walls in a random corner of the map and this would allow marines to kill it more easily considering how low risk high reward it is usually, even if it is awful to play right now for most people.

**Comment by TiviPlus** [comment]
I wont accept "it makes sense" as a why its good for the game balance change justification

**Review by BraveMole — APPROVED** [review]

**Comment by TiviPlus** [comment]
Conflicts

**Comment by Derrick2Electricboogaloo** [comment]
Time to kill that bastard. :)

**Review by BraveMole — CHANGES_REQUESTED** [review]
How about, you add this but hivemind core has a proximity alert like silos ?

**Comment by ivanmixo** [comment]
> How about, you add this but hivemind core has a proximity alert like silos ?

Yeah...? That got merged #11057

**Comment by Starfirejordan** [comment]
image
image
democracy has failed

**Pull request merged**
