### PR TITLE
retvrn to colonial marines [DNM] [April Fools]

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
feel free to review even if its draft
image
terragov and nanotrasen sucks screw this scifi jaeger mech bullshit we out here using kitbashed vietnam equipment
happy apirl 1

credits to crow for smartgun sprite

todo:
maybe a few more guns
quick load loadouts for uscm
## Why It's Good For The Game
1 of april
## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
the best april fools in the histroy of human kind

actually beat cm in their own game lol

**Comment by Al-1ce** [comment]
Those sprites look way better than what we currently have, tbh.

**Comment by Oscari-pog** [comment]
Smartgun, flamer and recoilless gun should become permanent, they look better than what we got.

**Comment by Pixelknightly** [comment]
Some of these sprites look really fucking good. Can't we keep them?

**Review by Kuro020 — APPROVED** [review]

**Comment by TiviPlus** [comment]
hurry up i want to tm this

**Comment by Xsdew** [comment]
The sprites in this PR are the same as the game. The only difference is that the lights actually exist on the armor sprite, and there is a uniform tye made that is entirely brown. The drip is just xenonuaghten with light bulbs attached more or less.

**Comment by tyeagg** [comment]
to return in alien anniversary day i guess

**Comment by Autisem** [comment]
Id not be mad if this was an actuely new gamemode. If we could tune down the xeno pop this could be a nice crash replacement

**Pull request closed without merging**
