### PR TITLE
Removes aim mode

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request
Removes aim mode and associated vars. Tested with smartgun and T18 and they work as intended.

## Why It's Good For The Game
Marines had a lot of time to get accustomed to aim mode and start playing more aggressively and organized, but this never happened. Currently aim mode only helps people play too defensively and contributes to rounds feeling stale.

Additionally, when it comes to FF, aim mode was added at a time when tweezers were not a thing. Now that they are, marines don't need to go back to shipside due to accidental FF. Adding to this, FF still happens a fair amount even if aim mode is a thing.

Due to these reasons, aim mode's negatives outweigh the positives when it comes to overall contribution to making round engaging for both sides.

## Changelog
:cl:
del: Removed aim mode
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -37. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
"Marines had a lot of time to get accustomed to aim mode and start playing more aggressively and organized, but this never happened. Currently aim mode only helps people play too defensively and contributes to rounds feeling stale."

Probably because aim mode slows you to a crawl and reduces your dps, meanwhile xenos are faster than ever with weed speed stacking, boy I wonder why pushing with aim mode is so hard. 
Also weren't you complaining on discord that marines pushing with aim mode was impossible to counter, what changed?

"Additionally, when it comes to FF, aim mode was added at a time when tweezers were not a thing. Now that they are, marines don't need to go back to shipside due to accidental FF. Adding to this, FF still happens a fair amount even if aim mode is a thing."

I think you misunderstood something here, the "going back to shipside because of FF" was never the reason why aim mode got added, ever, and nobody was under the impression that aim mode was gonna completely end FF, saying it's a failure because it didn't do a thing nobody was expecting it to do is dumb. 

"Due to these reasons, aim mode's negatives outweigh the positives when it comes to overall contribution to making round engaging for both sides."

I can give you a list of negatives that outweight the positives of a bunch of changes in this game and they never got removed after they went in, aim mode is fine, it allows marines to counter the "I run around at mach 5 and now I will go in the middle of the unga ball to cause FF because shuffle goes brrrr" tactic without being obligated to carry around shotguns, gives some previously pretty garbage weapons (like the sniper) an actual use, and gives newer players the ability to bundle up together without having to kill each other with FF (even if that still happens sometimes)
Overall pretty bad PR, should just get closed for trying to remove a feature with no good reasoning.

**Comment by Walarks** [comment]
> Also weren't you complaining on discord that marines pushing with aim mode was impossible to counter, what changed?

Ping me on discord with some quote where I said this since I don't remember it.

> "Additionally, when it comes to FF, aim mode was added at a time when tweezers were not a thing. Now that they are, marines don't need to go back to shipside due to accidental FF. Adding to this, FF still happens a fair amount even if aim mode is a thing."
> 
> I think you misunderstood something here, the "going back to shipside because of FF" was never the reason why aim mode got added, ever, and nobody was under the impression that aim mode was gonna completely end FF, saying it's a failure because it didn't do a thing nobody was expecting it to do is dumb.

People were expecting it to reduce FF when I made it.

**Comment by Kuro-ai** [comment]
"Ping me on discord with some quote where I said this since I don't remember it."
Yeah I confused you for someone else,oops

"People were expecting it to reduce FF when I made it."
And?

**Comment by Walarks** [comment]
> "People were expecting it to reduce FF when I made it."
> And?

It didn't reduce FF attrition in terms of pushing to outweigh the negative of increased power when it comes to prolonging sieges.

**Comment by Kuro-ai** [comment]
> > "People were expecting it to reduce FF when I made it."
> > And?
> 
> It didn't reduce FF attrition in terms of pushing to outweigh the negative of increased power when it comes to prolonging sieges.

It reduced some FF, not all of it, which is good enough. 
And sieges only go on for so long because marines only need to get 1 miner with tadpole to keep the points rolling forever, it has very little to do with aim mode, and with bravemole and splinter doing changes to silos and how miners work I expect that to not be true for long.

**Comment by Pariah919** [comment]
all this does is exagerrate the hugging issue even more, marines are unable to push out because the punishment for ff is hilariously high, and runners and hunters deal too much damage that's justified because "Shotguns lmao"

nerf shotguns, nerf tag

**Comment by Sulaboy** [comment]
Aim Mode is good because it lets marines defend outside of cades better. If you’re standing behind another marine you can’t shoot the bug on the opposite side of them without aim mode. You used to have to let that marine in front of you get either knocked down or critter to shoot the bug killing him, now you can help him. I see no reason to remove it.

 If you don’t like it you don’t have to use it. I like it as marine, it makes the snipers usable because we all love being hit with crude sniper bullets, and lets you protect you teammates.

**Comment by DrCrawler** [comment]
So you are telling us that you want to make like 80% of the weapons into absolute garbage? Dude, try using the T-127 without the aim mode, yeah, you will shoot your fellow marines. Come on, aim mode is absolute garbage to my opinion, you loose that speed and rate of fire. It is useless when you need to chase some runner. I want you to do the opposite, buff the fire rate and the movement speed instead, xenos are still faster, but it will give you a chanse to chase em down.

**Comment by TiviPlus** [comment]
pretty much everyone agrees that aim mode is a net benefit so I see no reason to do this

**Pull request closed without merging**
