### PR TITLE
Moves PPSH to seasonals from marine vendor, adds a new gun for seasonals, MKH98

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
MKH98 icon by IamTheDude, inhands by me.
Moves PPSH to seasonals from marine vendors, it isn't unique enough and it's a meme gun anyway, so it should be in seasonals, atleast mosin is unique enough to pass as it's own weapon, the ppsh is just a bad meme.

image

MKH98 STATS
- 30/15/1.75 with a 0.25 ROF, same DPS as an AKM
- Has a few more attachment options than the AKM, mostly in miniscope and vert grip.
- 26 magazine size.
- Better overall mobility stats than an AK

## Why It's Good For The Game
PPSH is a meme gun that should've been moved to seasonals since it's been a thing, I'd argue the mosin as well.
The MKH98 fills a decent niche as it's basically a faster moving AK, it has assault rifle stats, but suffers with no mag harness (though i might add that back) and has decent mobility. I think it has a decent niche in CQC that nothing else has yet, and suffers in ammo economy.

## Changelog
:cl:
tweak: PPSH moved to seasonal guns.
add: MKH98 rifle, and PPSH/MKH98 seasonal. MKH basically feels like a lower capacity higher mobility AK.
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]

**Review by BraveMole — APPROVED** [review]
David said yes

**Comment by David-Stormwell** [comment]
cute sprite.
if you need to balance the guns so so in another PR

**Comment by Sirsnek15** [comment]
There is no set definition of "meme gun" and it is unclear why the classification would remove PPSh from standard selection, as its been in the main vendor for a long while and isn't even a groundside weapon. The MKH 98 is a good addition to the seasonals, however, PPSh should not be sacrificed to seasonals just to give MKH a partner in it's rotation like all the other seasonals. Basically, there are no reasons to move this weapon away from standard to seasonals. It also limits a player's choice, and exploration of what they like and don't like in a weapon.

**Comment by Sirsnek15** [comment]
Am I going to have to learn coding, erase the PPSh from seasonal rotation, then put it back in standard vendors and make a PR?

**Comment by BraveMole** [comment]
Stop necroing

**Pull request merged**
