### PR TITLE
Crusher unique explosion handler removal

### PR DESCRIPTION
**Pull request by goose4429**
## About The Pull Request

Crusher was the only xenos to have unique explosion handler, which overrides default behavior with 0 damage from light or heavy explosions, but doubled damage from devastating ones. This PR removes this handler. This code is likely a remainder from CM, since it wasn't ever changed by anybody.

## Why It's Good For The Game

Makes game more intuitive - game plays as you expect it to play. Crusher now can be damaged by nades, but is very resistant to them, as he still has tier 3 armor. He can also be damaged by all CAS weapons. For info - CAS machinegun and nades will deal 30 damage on average. 

## Changelog
:cl:
code: Removed ex act from crushher.dm
balance: crusher is no longer immune to some explosions
balance: crusher gets less damage from biggest explosions
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
its missing the balancment cl

**Comment by Wayland-Smithy** [comment]
1. Lefunny is correct this is a balance change and needs to be CLed as such.
2. Please do not remove crushers ex act immunity because they are slow and suffer enough from the displacement effects as is, and spinning under CAS railgun is of the few joys in my life.

**Comment by goose4429** [comment]
Thanks to the guys above, fixed cl with balance

**Comment by Naaanii** [comment]
Nerfing the most currently underwhelming T3 guh...

Crusher feels like it should be immune to explosions with the way it plays and even with this trait, it hasn't ever felt too oppressive. Maybe Gorger should have something similar actually.

**Comment by Naaanii** [comment]
> > Nerfing the most currently underwhelming T3 guh...
> > Crusher feels like it should be immune to explosions with the way it plays and even with this trait, it hasn't ever felt too oppressive. Maybe Gorger should have something similar actually.
> 
> Doing this just for the sake of consistency. We can give Crusher ex immunity no problem. For info, usual nade will deal 30 damage on average, which is very small. No slowdown, no sunder.

Fair enough

**Review by TiviPlus — APPROVED** [review]
Merging for maintenance purposes if theres balance issues people can feel free to buff it with numbers

**Pull request merged**
