### PR TITLE
Adds New Title Screens

### PR DESCRIPTION
**Pull request by Alterist**
🆑 
imageadd: added all the submitted titlescreens, some are not in active rotation. Also readded all the retired titlescreens, none are active. Adjusted some titlescreens to say TGMC instead of DMCA
/ 🆑 
low quality and meme titlescreens are listed by alphabets A ~ J

### CODE REVIEW

**Comment by Ghommie** [comment]
`title_paintingG` may seem off topic for players who don't relate much with git's ambient. But it's humor anyway.
`title_paintingF` looks a bit abstract and senseless at a first glance due to the silhoutte being a resized 32x32.
`title_paintingI` works better as an humorous outro.
`title_paintingC` looks fun but cimexs are early in the works. 🤷‍♂️

**Comment by Alterist** [comment]
There is no need to change the code, its currently set to generate a number from 1 to 9, selections of  the 9 different numbered titled screens
See: https://github.com/tgstation/TerraGov-Marine-Corps/blob/80920790895de6772a1629557bdef3afff0da7ee/code/game/turfs/walls/wall_types.dm
A to J WILL NOT SHOW UP without var editing

**Comment by Alterist** [comment]
titlescreen0 is the shutdown lobbyscreen now, I edited one of valmoric's titlescreens back to active rotation

**Comment by DominikPanic** [comment]
Per Rohesie and Arachnidnexus:
Could you remove the text on `title_painting3`?

**Pull request merged**
