### PR TITLE
Rave-ager

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request
Rave-ager

*sprites done by the cool dude waodo#4526 on discord*

## Why It's Good For The Game

image

## Changelog
:cl:
add: Rave-ager
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]
woorrior next

**Comment by Toastgoats** [comment]
> woorrior next

I personally really want the bool.

**Comment by lKiseki** [comment]
speedmerge

**Comment by bowlofcereal** [comment]
speedmerge

**Pull request merged**
