### PR TITLE
Adds berets and headbands to the marine uniform vendor

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title. Asked Kuro before doing the PR, he said it was fine.

## Why It's Good For The Game
_**F a s h i o n .**_

## Changelog
:cl: Lewdcifer
add: Multiple berets and headbands added to the uniform vendor.
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]

**Comment by David-Stormwell** [comment]
how dare you add the snake headband to the vendor for everyone to use

**Comment by lKiseki** [comment]
David wants me to restrict the Snake headband behind a playtime requirement, marking this PR as draft until I do that.

**Comment by lKiseki** [comment]
god bless mementainers

**Review by TiviPlus — APPROVED** [review]
@Kuro020

**Comment by TiviPlus** [comment]
oh wait he approved

**Pull request merged**
