### PR TITLE
Removes AR55 from SL and FC vendors

### PR DESCRIPTION
**Pull request by blackdav123**
## About The Pull Request
See title. This gun has the incredible 21 sunder per shot and 140 damage of the GL54 while also being able to provide its own suppressive fire and finishing shots that the GL54 cant. This gun is comparable to the other high end req weapons such as the scout rifle and AMR and should stay as a req weapon rather than being free roundstart. 
## Why It's Good For The Game
"who gives out 520 points req guns for free" -yyzsong 2023
## Changelog
:cl:
balance: AR55 is no longer in FC and SL vendors.
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
> "who gives out 520 points req guns for free" -yyzsong 2023

Wow what a deep and insightful quote. I'd sure like to meet the guy that said that

**Comment by chizzy376** [comment]
Why not instead remove the gl mags and make the gun cost the whole vendor points? This way if they want to juice up with HE/whatever mags they still have to order it.

If that doesn't work you can also just remove the aim mode functionality instead of req helling it

**Comment by blackdav123** [comment]
> Why not instead remove the gl mags (from the point vendors) and make the gun cost the whole vendor points? This way if they want to juice up with HE/whatever mags they still have to order it.
> 
> If that doesn't work you can also just remove the aim mode functionality instead of req helling it

i could do all those things and the gun would still kill a queen in half a mag so i'd rather just make it not roundstart

**Comment by Pariah919** [comment]
This seems like the wrong fix, I'd rather point to the direct hit PR if its suddenly making a bunch of frag stuff do full direct hit damage on contact with a mob. Which shouldn't be happening just like it shouldn't have been happening with AGLS which was fixed with #16484. I might be a dunce and misremembering, however.

Though as a side note,
>high end req weapons such as the scout rifle and AMR 
>
What? Its in the point range as the *scout rifle*. Not really 'high end'. The really defined point brackets are like 50/150/300/400. Everything above around 600~ points is generally a bit weirdly pointed since it also takes into consideration high ammo costs.
I'm not really sold on the AR-55 being 525 as it currently is. But it does have to cost marginally more than the GL-54. Which is fine at 300. It could honestly drop to 400 and be there with the SR. But the T-12 strapped onto it is free so..

**Comment by Lumipharon** [comment]
To clarify #16484 was just a bug fix. It just returned it to previous behavior.
Airburst always hit all shrap on direct hit (against large xenos. Against humans or smaller xenos, the knockback means this won't always be the case).

I don't really care if this gets req zoned, but if this is actually a problem gun, then by extension the tx54 would also be problematic and need addressing.

**Comment by Lauwma** [comment]
Comparing the gun to an amr or a scout rifle is just dead wrong because it doesn't nearly have the same DPS or kill potential these two weapons have, especially given the weapon doesn't have iff. AMR can offscreen and auto aim while applying slow down, scout rifle does more damage if you count the fact it can fit Underbarrel such as sticky grenades.

The weapon can't have aimmode if you remove its scope so even if you are playing it CQC with magharness it comes as the cost of you not having iff. You could use the belt but it comes as the cost of a valuable belt slot (and aimmode nerfs its dps anyway)

The ar55 also comes with the downside of having a very shit ammo economy (ar18 mag + limited gl54 mags) so you usually end up sacrificing a lot of your inventory to that. While we live in an infinite ammo economy you often have to sacrifice crucial minutes in ressuplying or refilling mags.

Its offscreen capabilities are mild given it has the falloff of an ar18 on its ar18 so it doesn't change much damage compared to the gl54. Did I mention the gl54 projectile is almost impossible to direct hit with past 6 tiles given how slow it is ? Yes don't try the gun in Valhalla because of course if you are against a xeno that doesn't move or doesn't attack it's gonna be very effective. 

The ar55 doesn't kill a queen with half its mag I don't know where you pulled those numbers from.

HE/Razorwire were removed so idk why they are mentioned here.

The ar55 definitely is better than just the ar18 but it comes with downsides

**Comment by Lauwma** [comment]
If a nerd needs to happen it'd be to add a -%damage modifier on the attachment.

The gun got readded to SL vendor because the reason it got removed for (he/razorwire spam) don't exist anymore. 

During the time it wasn't in vendors it wasn't played because it was overpriced, required a whole loadout meaning you needed to go back shipside to use it or make a loadout that can adapt itself with big compromises.

**Comment by Arturlang** [comment]
the AR55 is just way too insane right now to play against as xenos, mainly due to the airburst rounds causing insane damage with the fix to how it hits the targets.

**Review by Kuro020 — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
