### PR TITLE
Changes Intel computers to now be a loot box reward event.

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

This gives heavy incentive to doing the event when it occurs, instead of marines ignoring them, while rewarding them for their effort. this requires marines to be careful as xenos might use this to pick off loners, so risk reward.

EDIT: upon completion, it will generate a loot box at the intel disk. the contents dont have anything new, except deplorables being removed from the loot table, more or less. intel computer can only be used once.

## Changelog

:cl:
add: loot box event reward system instead of intel req point reward event system.
balance: updates event weight from 25 to 30
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Based based based.

**Comment by jonash07** [comment]
i fucking LOVE gambling

**Comment by lbnesquik** [comment]
You describe why it is good, but not what it does. Is there a lootbox back at the ship? An airplane drops a flare with loot? Also, do you fully replace the intel computer event or is this an addition and both can happen?

**Comment by ivanmixo** [comment]
Very against this, random rewards are a balance nightmare since you can't balance around them properly (req lootboxes existing is already dubious). Nevermind the fact that literally every case here is extremely good so there is 0 risk-reward. Cutting out the "why it's good for the game" also doesn't really help your case.

**Comment by vilereaver41** [comment]
> You describe why it is good, but not what it does. Is there a lootbox back at the ship? An airplane drops a flare with loot? Also, do you fully replace the intel computer event or is this an addition and both can happen?

edited change

**Comment by FosterGrime-Heymynameslouie** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/assets/59080633/a54ad226-823f-486a-ae7a-a6a5b0dfd5b9

I FUCKING LOVE GAMBLING URAHHHHHHHHHHHH

**Comment by LohnRan** [comment]
Extremely soulful PR. One of the greatest of all time.

**Comment by Kuro020** [comment]
Ok, let's analyze this:

Legendary and rare lists are just no, no you're not gonna get a b18 from a goddamn side objective, this is dumb.

Then the other ones are questionable at best, why do we need intel to be RNG loot? 600 points seems fine to me, you get points, RO decides what to spend it on, thats already a marine positive for the round, making it RNG seems to just make it harder to balance. I don't see how this pr is good for the game

**Pull request closed without merging**
