### PR TITLE
More Mining Drill Locations

### PR DESCRIPTION
**Pull request by Hathkar**
## About The Pull Request

Adds a bunch of new mining drill locations to the current maps in rotation (Minus Whiskey Outpost).
Generally, phoron (I hate that name) is located between the two landing areas of each map.
The platinum miners are located deeper in the maps, away from the landing zones.

## Why It's Good For The Game

Instead of 4-6 drills per map, this spreads a whole bunch of them all over the map. This is to encourage more of the maps being used, marines pushing out to secure resources more, giving xenos more chances to ambush, etc.

This is also meant to go along with a PR that modifies the supply point price of the ore as well, since there are so many more miners now. Or it could be tested by itself.

## Changelog
:cl:
add: New phoron drill spots
add: New platinum drill spots
del: Removed some old drill spots
/:cl:

### CODE REVIEW

**Comment by XElectricX** [comment]
Current drill positions are fine. Making them any closer would be too easy for marines and farther would be useless for them.

**Comment by Hathkar** [comment]
I disagree, current drill placement makes little sense on most maps.  Phoron was fewer in number and farther away from the LZs than platinum in some cases.

With more drills, marines have more choices on what positions to hold and reinforce.

**Comment by Kuro-ai** [comment]
Miners are too strong,you should increase the time it takes to get one crate so marines don't easily end up with thousand of points

**Comment by Pariah919** [comment]
If you're going to add more drills make them less profitable, I personally think it should be a phoron crate every 5 minutes, as they currently are they basically literally break req balance in half.

**Comment by Hathkar** [comment]
Yeah, I was planning on making another separate PR for the mining prices and such, since I was told to atomize this.

**Comment by Hathkar** [comment]
After thinking it over, I'm going with my original idea.
The other PR, with 4 miners per map, basically designates the miners as "fighting areas", leaving the rest of the map unused.
More miners = More spots to fight at.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
