### PR TITLE
Resprites nuke again, reverts vests

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

The people have spoken and they don't like how bright/flat the nuke is, and they don't like the new vests I ported.

I have opted to give the nuke a much subdued color scheme and give it some extra details in hopes of making it less flat. The vests are back to what they were before https://github.com/tgstation/TerraGov-Marine-Corps/pull/10999.

Let it never be said that I don't listen to feedback or take responsibility for my sprites.

## Why It's Good For The Game
The nuke sprites are better, or at least less controversial, people didn't like the vests. Better sprites = better game.

## Changelog
:cl:
imageadd: The nuke has been partially resprited to be less saturated and more detailed.
imagedel: The green nuke sprites have been deleted.
imagedel: New style vests are back to what they were.
/:cl:

### CODE REVIEW

**Comment by Toastgoats** [comment]
Hey add images please

**Comment by Strayed-Raven** [comment]
Nothing wrong with old nuke. Also could use images please.

**Comment by Nickkoranda** [comment]
You can check the sprite changes on the 'checks' tab of the PR and going to icondiffbot: https://github.com/tgstation/TerraGov-Marine-Corps/pull/11064/checks

**Comment by Toastgoats** [comment]
> You can check the sprite changes on the 'checks' tab of the PR and going to icondiffbot: https://github.com/tgstation/TerraGov-Marine-Corps/pull/11064/checks

I mean yeah, but it's still nice to have images for people who dont know that.

**Comment by RipGrayson** [comment]
> Nothing wrong with old nuke. Also could use images please.

oldbomb
The old nuke is a one dimensional eyesore that conflicts with our 3/4ths art style. Any replacement for the nuke sprite should ideally be in 3/4ths also. 

I'm very committed to that, and am willing to go through a dozen radically different resprites for the nuke before returning to the ancient one.

**Comment by Kuro020** [comment]
the nuke sprite is ok, I'll merge in 24 hours

**Pull request merged**
