### PR TITLE
pepperball gun now has a coaxial water cannon

### PR DESCRIPTION
**Pull request by Pariah919**
## 
About The Pull Request
dreamseeker_YdI8ZQOTa1
## Why It's Good For The Game
I believe a coaxial water cannon will greatly improve pepperball gun usage and encourage high use of emergent gameplay to perform interesting and highly detailed emergent gameplay manuevers like extingushing your teammates.
## Changelog
:cl:
add: Pepperball gun has a coaxial water gun now.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
water gun

**Comment by Mrrpip** [comment]
Summer update 2023 is here bois! Get your rubber rings! :D

**Comment by Burger1998** [comment]
bro is really trying to get in as many words for his essay.

**Review by ivanmixo — CHANGES_REQUESTED** [review]
image

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
