### PR TITLE
Health kits chain apply

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
After being applied to a treatable limb, health kits (gauze/ointment/advanced) will then cycle through all the other patient's limbs with a delay on each treatable one. They'll only use one unit of the stack for this entire cycle.
Alternative to #9968 

## Why It's Good For The Game
Helps with a primary complaint of basic kits, which is that if you apply them regularly you'll burn through them super fast.
Might be excessive with regard to advanced kits, in which case their max stack could be reduced to five or so.

## Changelog
:cl:
add: After applying a health kit to one limb, you'll start applying it to all other damaged ones without using additional stacks.
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
I prefer MJP solution.

**Review by BraveMole — CHANGES_REQUESTED** [review]

**Comment by Durbles** [comment]
Kits seem to apply chain healing to limbs that have no damage. I've even seen it apply the kit to robotic limbs.

**Comment by QualityVan** [comment]
> Kits seem to apply chain healing to limbs that have no damage. I've even seen it apply the kit to robotic limbs.

That'll happen if there's untreated wounds on the limb, even if they have zero damage. The robolimbs thing was an oversight, fixed now.

**Comment by Durbles** [comment]
> > Kits seem to apply chain healing to limbs that have no damage. I've even seen it apply the kit to robotic limbs.
> 
> That'll happen if there's untreated wounds on the limb, even if they have zero damage. The robolimbs thing was an oversight, fixed now.

How can a limb have a wound if it has zero damage?

**Comment by XSlayer300** [comment]
Make it so that the brute healing supplies (bandages and brute trauma kits) chain applies will prioritize bleeding first then the rest of the damaged parts. In addition, should the chain healing stuff should have a minimum damage limit of sorts? Maybe around 10 so you won't waste healing kits?

**Comment by Losenis** [comment]
Any chance to open a new pr and make bandages and ointments (IE NOT Trauma and burn kits) apply instantly to all bodyparts at a high enough medical skill level? Like MO or Synth high. It'd make them have a use compared to trauma kits and burn kits, and they don't heal enough to make midcombat spamclicking relevant afaik.

**Pull request merged**
