### PR TITLE
Neurotox Rework

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
neurotox no longer deal EXTRA TOX damage. and OXY damage on its own.

it will only deal as much as the stamina crit already do

the stam damage got changes tho

it starts at 8 now and drops down to 0.1 over 30cycles

if the marine gets in orange stamina "aka" slowdown but still no crit then the toxin will only halt stamina regen

BUT.. if left un atended after 31ticks it will start to pick up again and go up no matter what. "untill its purged"

## Why It's Good For The Game ##
TLDR:

if the marine is alread low at stamina or gets really close to crit before 31 cycles.
he will be kept from taking more stam damage "FROM THE NEUROTOX: if queen screeches. then you still take damage"
if the marine got full stamina it will deplet the starting stamina faster and slowdown for a while when hits orange

after 31 cycles no matter how much stamina the marine got the stam damage will grow over time untill treated or fully metabolized

## Changelog
:cl:
balance: neurotox have a higher stam damage upfront that lowers overtime
balance: neurotox have a "sweet spot" where the marine is slowdown but not lying down in crit yet
balance: neurotox stam will grow back again after 31 cycles if the marine does nothing about it
balance: neurotox extra oxy and Tox damage removed so will only take damage from the stamina itself
/:cl:

### CODE REVIEW

**Comment by Tennessee116** [comment]
> neurotoxin

> does not have serious toxic effects

I feel like, at this rate, it might deserve a rename just to clear the confusion.

**Comment by SkeletalElite** [comment]
I like the other PR better

**Comment by fernandos13** [comment]
comments above this one are outdated since recent changes and actually getting the Pull request well done

**Comment by Walarks** [comment]
I think #6364 is better simply because it removes purge, which is an annoying and bad mechanic when spammed.

**Comment by SplinterGP** [comment]
> balance: neurotox extra oxy and Tox damage removed so will only take damage from the stamina itself
can you test and see if this was because it woulndt take directly of stam, would probably ask to atomize this one as its one i might be up to pass easier

**Comment by TiviPlus** [comment]
Neurotox is fine now so the redundancy is not needed anymore

**Pull request closed without merging**
