### PR TITLE
Engineers do not require skill check for Chem vendors

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Engineers have now been educated on how to use chem vendors.

Engineers also have access to Chemistry.

## Why It's Good For The Game
Chem nades are interesting and the system can be further improved. Random ungas breaking into chem wasn't a desired outcome, engineers are discouraged from making wacky custom nades due to the skill check. This should help in that aspect as chemistry really shouldn't be for meds only.

## Changelog
:cl:
add: Engineers now have the skills to use the chem vendor.
add: Engineers (and Rebel Corpsmen) have access to Chemistry.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
tbh chem checks should be removed altogether, hardly anyone uses it enough to demand it given that most people don't even know about them with the recent influx of new players or they use it for a few things the delay doesn't have any impact whatsoever in terms of prep time. Given some recipes that'd have been used to make shit now require lemoline like synaptizine, as well as things like mixing two pill bottles into one like the old remove peridaxon + qc for space efficiency, there's even less things to make.

**Comment by maikilangiolo** [comment]
> tbh chem checks should be removed altogether, hardly anyone uses it enough to demand it

This tbh.

**Comment by Derrick2Electricboogaloo** [comment]
> tbh chem checks should be removed altogether, hardly anyone uses it enough to demand it given that most people don't even know about them with the recent influx of new players or they use it for a few things the delay doesn't have any impact whatsoever in terms of prep time. Given some recipes that'd have been used to make shit now require lemoline like synaptizine, as well as things like mixing two pill bottles into one like the old remove peridaxon + qc for space efficiency, there's even less things to make.

I agree with this. Before it was even added it was never a problem. It fixed a non-issue.

**Comment by ivanmixo** [comment]
Me shamelessly buffing the job I main

**Comment by Lumipharon** [comment]
CHem nades are OP, they're just not generally abused because of the effort involved. But that effort is not counterable by xenos, since they can't effect the nerd spending 30 minutes makes 30 doom grenades round start.

So anything to make it easier to spam chem nades is bad imo.

**Comment by Losenis** [comment]
"CHem nades are OP" if chem delay was of any issue to them they'd go corpsman for PFC+ or FC for both corpsman and engi skill though, or even deploy as RSR. Chem delay never did anything against that, much less nowadays that prep time is shortened considerably compared to ages ago.

**Pull request closed without merging**
