### PR TITLE
Fix performance issues

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

This remove autofire and diagonal move.

## Why It's Good For The Game

This will help us support more pop and ultimatly become CM

## Changelog
:cl:
fix: Fix performance issues
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Thank you bravemole, very brave

**Comment by Waselon** [comment]
remove autofire???

**Comment by BraveMole** [comment]
> remove autofire??? Is this a meme PR?

No i am convinced that a good player is a player able to click fast

**Comment by Otterwatch** [comment]
My carpal tunnel Brave. Why are you making me suffer?

**Pull request closed without merging**
