### PR TITLE
Remove a lot of skills from FC

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

FC get more basic skills

## Why It's Good For The Game

FC should not be the powergamer role it is now. 

## Changelog
:cl:
balance: FC has less skill in pistols and melee
/:cl:

### CODE REVIEW

**Comment by David-Stormwell** [comment]
Here's my suggestion, as this is probably too much of a nerf.
Lower medical skill to SL's level, removing pistols and melee is fine. Keep engineering as it is due to lack of engineers at times and encourages support/non-combat FCs.

**Comment by KornFlaks** [comment]
Other than the trained pistol skill, what's the difference from just using an SO instead for the surgery/medical skill and construction powergaming?

Sure, you dont get the roundstart tac binos (I think) but pretty much everything else relevant is the same.

Might also include the removal of medical skill from SOs as well if we want command staff to stop deploying and being just superior Ungas.

**Comment by SplinterGP** [comment]
Surgery skill is fine for FC, they're the guy who knows all on ground, they should be able to do anything

**Comment by BraveMole** [comment]
> Surgery skill is fine for FC, they're the guy who knows all on ground, they should be able to do anything

Well, no, FC should lead? What you're saying kinda is powergamer thing, which i want to eradicate a bit.

**Comment by Pariah919** [comment]
field commander should have surgery 2 all it basically does is make the fumble timer SLIGHTLY less bad and let's them put people in autodocs fast, which is perfectly fine, and medical skill is fine
trained pistol is a meme it should go

**Comment by David-Stormwell** [comment]
> > Surgery skill is fine for FC, they're the guy who knows all on ground, they should be able to do anything
> 
> Well, no, FC should lead? What you're saying kinda is powergamer thing, which i want to eradicate a bit.

it isn't exactly powergaming, no powergamers abuse that really.
It helps out in lowpop and support FCs.

**Comment by SplinterGP** [comment]
> 
> 
> > Surgery skill is fine for FC, they're the guy who knows all on ground, they should be able to do anything
> 
> Well, no, FC should lead? What you're saying kinda is powergamer thing, which i want to eradicate a bit.

last i checked powergaming ain't a rule on TGMC, and thats kinda the whole point of the role, its the Field Commander, it should be able to help in whatever is possible to, even more being a limited role, the combat nerfs are fine, the FC shoulndt be suicide frontlining, but i dont see how surgery makes the FC make non sense

**Comment by Swagile** [comment]
the whole point of the FC is to be the super role; its like the Queen equivalent for marines

it helps both in low, med (and even sometimes highpop) to have 1 guy who knows how to do everything and is also willing to do everything; that is the FC role

pistol skill removal to appease SilentMP5 haters, ok, but why remove medical, engineering, etc?

**Comment by BraveMole** [comment]
No, it's not the FC role. It's the synth role. The FC role is here to lead, not to do everything

**Comment by Pariah919** [comment]
>No, it's not the FC role. It's the synth role. The FC role is here to lead, not to do everything
>
synth has better support skills that usually matter more than field commanders support skills, the only skill that fc shouldn't have is trained pistols, and even then I can see the argument for keeping trained pistols, as they should be incentivized to use their pistol more.

**Comment by SplinterGP** [comment]
> 
> 
> No, it's not the FC role. It's the synth role. The FC role is here to lead, not to do everything

synth is a role that exists just as a failsafe of someone being completely bad at their job and one man having to deal with all other people trouble, if people are doing their stuff properly synth is obsolete

**Comment by SplinterGP** [comment]
> 
> 
> No, it's not the FC role. It's the synth role. The FC role is here to lead, not to do everything

The FC role is literally the guy who knows how to do most things, and thus is capable of leading, the role which most strictly job is leading is captain, even more considering the FC is also meant to participate in battles somewhat

**Comment by BraveMole** [comment]
> > No, it's not the FC role. It's the synth role. The FC role is here to lead, not to do everything
> 
> The FC role is literally the guy who knows how to do most things, and thus is capable of leading, the role which most strictly job is leading is captain, even more considering the FC is also meant to participate in battles somewhat

well go look at captain skill, it's incredible

**Comment by usnpeepoo** [comment]
people have said the FC is the equivalent to the queen, which is basically the do-it-all (queen spit, building, etc) it should keep its medical/engineering skills just because it could be used for powergaming doesn't mean it should be removed when it has actual capabilities for helping marines on low/med pop where there couldn't be enough medics or engineers.

**Comment by Naaanii** [comment]
Nerfing pistols and melee is kind of lame for the 'best' combat role. Leading is fine but doesn't mean they should be mediocre in combat too like a SL and you only get one throughout the entire gamez whereas a Queen can be replaced in 5 minutes.

**Comment by EgorDinamit** [comment]
I don't know why the only role that spawns with the funny sword should have less melee skill, same for pistols.
Surgery? It's fine imo, never I expected FC to do field surgery, that's what corpsmen are for.

**Comment by bowlofcereal** [comment]
there is no rule on powergaming, also

- spawns with sword, but decreasing the melee skill, ah yes
- less skill in pistol even though a lot of FCs use a pistol as a sidearm, like why wouldnt the marine fucking commander know how to use pistol firearms literally anyone in this god damn world can use a pistol
- how is the FC knowing medical skill bad at all, he can use trauma kits on the frontline to help his ungas

cant tell if this is salt pr or just super bad take

**Pull request merged**
