### PR TITLE
Explosive grenades are limited to 50 per marine

### PR DESCRIPTION
**Pull request by Canohaaaaaaa**
## About The Pull Request

M40, M15 and impacts are limited to 50 TOTAL per marine (read : you can have 30 M15 + 20 impacts for example)

## Why It's Good For The Game

Requested by mole in order to keep chain nading in.
Isn't supposed to have any meaningful effect on balance.

## Changelog
:cl:
balance: Explosive grenades (M40, M15 and impacts) are limited to 50 per marine to prevent server crashing chain nades.
/:cl:

### CODE REVIEW

**Comment by Canohaaaaaaa** [comment]
You can only vend up to 50 of those grenades from the shared vendors. You don't have to.

**Comment by Mrrpip** [comment]
Jesus.

I know we joke about the T70 being an upscaled flaregun, but at this rate...

**Comment by Eskjjlj** [comment]
Why would we even want to keep chain nades in the game...
And this is a marine nerf as they won't be able to resupply during long rounds.

**Comment by novaepee** [comment]
> this is a marine nerf as they won't be able to resupply during long rounds.

Just order nade boxes.

**Comment by InterroLouis** [comment]
Why would anyone want to order nade boxes if there are still grenades in the vendor? You shouldn't have to spend points on something the ship already has, just to resupply.

**Comment by Canohaaaaaaa** [comment]
Chain nading is staying gone.

**Pull request closed without merging**
