### PR TITLE
Req ARSR and drop console aren't deconstructable anymore

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Don't move these guh!
## Why It's Good For The Game

These really shouldn't be moved since it screws over req.
## Changelog
:cl:
del: Req ARSR and drop console aren't deconstructable anymore
/:cl:

### CODE REVIEW

**Review by lKiseki — CHANGES_REQUESTED** [review]
Computers use an `attackby` proc and don't call `screwdriver_act` anywhere. You'd have to change that code a little, but the easiest solution seems to be removing the `circuit` var for these two consoles here. It's only needed for deconstruction from what I can see, and its absence prevents it too.

**Comment by lKiseki** [comment]
> Computers use an `attackby` proc and don't call `screwdriver_act` anywhere, so this does nothing. You'd have to change that code a little, but the easiest solution seems to be removing the `circuit` var for these two consoles here. It's only needed for deconstruction from what I can see, and its absence prevents it too.

**Comment by DeltaFire15** [comment]
> but the easiest solution seems to be removing the `circuit` var for these two consoles here
Both the current and suggested approach would make you unable to repair either console if damaged or destroyed. If you are doing this, the console must be indestructible aswell.

**Comment by Wirpy** [comment]
The req console can be killed by like 3 paint ball shots btw.

**Review by Lumipharon — CHANGES_REQUESTED** [review]
Did... you test this?
Also does this stop you from repairing it if it gets damaged?

**Comment by FosterGrime-Heymynameslouie** [comment]
I kinda like moving them to places more convinient within req to make req run more efficiently, specially the drop console one

**Pull request closed without merging**
