### PR TITLE
Remove IMDPs

### PR DESCRIPTION
**Pull request by Kuro-ai**
#About The Pull Request

Bad memes begone

## Why It's Good For The Game

They're unbalanced evil,begone!

## Changelog
:cl:
balance: Removed all the ways to acquire IMDPs
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
IMDPs should be removed from being gettable by normal marine forces outside of crazy admin events or PMCs for now until someone reworks them to not stun T3s.

They should honestly just work like reskinned shotgun slugs that deal explosive damage instead of brute damage stun and damage wise.

**Comment by jroinc** [comment]
Eh, I'd leave them but drop the explosion radius to 0,1,1 down from 0,1,2. That way they do the same damage, but they have zero AOE, which would make it much harder for the GL spec to permastun ayys. Still doable if he aims good, but if he misses one click directly on the ayy, the ayy can get away.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-6). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
