### PR TITLE
Plasma pistol nerf.

### PR DESCRIPTION
**Pull request by David-Stormwell**
## About The Pull Request

Removes the plasma pistol as a attachable gun.

## Why It's Good For The Game

This should've had never been added in the first place. If you want a long-range underbarrel shot that supports you and your teammates use masterkey slugs or impact grenades.

## Changelog
:cl:
balance: Plasma pistols can no longer be used as an underbarrel attachment.
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
cope seeth ratio unbased

**Comment by Eskjjlj** [comment]
salt pr

**Comment by bowlofcereal** [comment]
A nuclear option I am all for

**Comment by Ragecrabbo** [comment]
fix the scatter too pls

also skill issue

**Comment by Waselon** [comment]
> If you want a long-range underbarrel shot that supports you and your teammates use masterkey slugs or impact grenades

If only i could attach those to a shotgun...

**Comment by Lumipharon** [comment]
> > If you want a long-range underbarrel shot that supports you and your teammates use masterkey slugs or impact grenades
> 
> If only i could attach those to a shotgun...

That's what the Mk221 is... shame it got sent to seasonal oblivion

**Comment by boartem** [comment]
Why not first remove them only from shotguns and reduce ammunition? Why so radical?

**Comment by EvilMelonTheSecond** [comment]
Shotgun salt decimates the game balance yet again. Can we try and find a different solution before one more resin wall clearing tool gets the nerf hammer?

**Comment by Mrrpip** [comment]
> > > If you want a long-range underbarrel shot that supports you and your teammates use masterkey slugs or impact grenades
> > 
> > 
> > If only i could attach those to a shotgun...
> 
> That's what the Mk221 is... shame it got sent to seasonal oblivion

'Weapon bloat' moment.

**Comment by bowlofcereal** [comment]
> Why not first remove them only from shotguns and reduce ammunition? Additionally, you can take away the ability to shoot with one hand when it is attached to a weapon. Why so radical?

I removed them from shotguns only and my PR was promptly closed. I wouldn't even bother. This frankly doesn't effect my gameplay in any way because I found the plasma pistol to be a lame powercreep item anyways.

**Comment by AndroidMK2** [comment]
Salt pr cope + seethe + mald + mad + sus opinion

**Comment by usnpeepoo** [comment]
how about u just remove every gun but the t12 and the t35 huh how about that

**Comment by Redstonize** [comment]
Removing the tool doesn't seem to make any sense.

**Comment by Otterwatch** [comment]
> Shotgun salt decimates the game balance yet again. Can we try and find a different solution before one more resin wall clearing tool gets the nerf hammer?

The plasma pistol isn’t getting removed though? This pr is removing the attachability of the gun. You can also still use under barrel or nades or flame nades or the pp or a flamer or a machete. Pp on shotguns and smart rifle is just plain power creep.

**Pull request closed without merging**
