### PR TITLE
Brings Some Soul Back For Modules

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
image
## Why It's Good For The Game
More soul good.

(I also got Kuro's approval)
## Changelog
:cl:
imageadd: added new (the OG) module icons and sprites
imagedel: removed current module icons and sprites
/:cl:

### CODE REVIEW

**Comment by Kuro020** [comment]
current modules interfere too much with customization, and tgmc's main marine feature is customization, therefore I dont believe the current set of module sprites is a good thing overall

**Comment by FosterGrime-Heymynameslouie** [comment]
current module look way better than power ranger colors on the back tbh

**Comment by chizzy376** [comment]
> The current sprites are massively easier to distinguish 

Yeah but they look like shit and clash with drip, like why do I have green nipples
engi 1
Anyways good PR, speedmerge

**Comment by CoastalCookie** [comment]
Maybe make it a toggle with customisation kit? I know some fashion sets do infact use the original modules to well be "drippy" so said

**Comment by Kuro020** [comment]
> Maybe make it a toggle with customisation kit? I know some fashion sets do infact use the original modules to well be "drippy" so said
> 
> This would also make room for people adding more thematic options later on perhaps after all modules are used allot so there's no doubt someone will have a original idea but they don't want to overwrite the original modules

We do not have that kind of functionality for modules

**Comment by CoastalCookie** [comment]
> > Maybe make it a toggle with customisation kit? I know some fashion sets do infact use the original modules to well be "drippy" so said
> > This would also make room for people adding more thematic options later on perhaps after all modules are used allot so there's no doubt someone will have a original idea but they don't want to overwrite the original modules
> 
> We do not have that kind of functionality for modules

I know its a WYCI moment but its something you can put into concept after all badges have the ability with ALT + Click to change style and colour and there's bound to be people who use modules for fashion

**Comment by Wisemonster** [comment]
Don't personally like the un-equipped modules just being various palette swaps, considering it makes seeing which module is which now require memorizing the colors of each module. Don't really have an opinion on how they appear on armor other than they remind me of Gamer™ rgb lights.

**Comment by lbnesquik** [comment]
I was going to say it appears less clear, but at the same time, neither versions are really clear. I think current but with bigger sprites would be the better option. Of course, that's ideasguys.

**Review by TiviPlus — APPROVED** [review]

**Comment by SimplySmiley123** [comment]
> I was going to say it appears less clear, but at the same time, neither versions are really clear. I think current but with bigger sprites would be the better option. Of course, that's ideasguys.

Svallin and Mimir are already bigger then your armour's chestplate and honestly I hate 'em for it.

**Comment by lbnesquik** [comment]
> > I was going to say it appears less clear, but at the same time, neither versions are really clear. I think current but with bigger sprites would be the better option. Of course, that's ideasguys.
> 
> Svallin and Mimir are already bigger then your armour's chestplate and honestly I hate 'em for it.

I was talking about the items on the ground, not on the armor.

**Comment by Kuro020** [comment]
the boxes are really boring, at least the colored rgb rectangles look pretty when i'm drunk

**Pull request merged**
