### PR TITLE
Prison Station Removal

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
I will put a forewarning that in all honesty, not likely to be accepted. I do hope, however, my grievances are addressed later if not with this PR; though I still do believe a full removal is the best course of action as this map does not fundamentally work.

Removes Prison Station as a selectable map.
## Why It's Good For The Game
This will be a rant, so if you don't want to read through it:
TL;DR: Inherent flow issues with 2x2 hallway spam being integral to the map, prone to extreme stalemating (honestly out of all the maps, it is the worst next to Ice Colony), the entire map is a flanking point for Xenos, poor FOB design in regards to surroundings.
That is most of what I will be discussing, so if you want to go and disagree in the comments (please feel free to, Grayson will be looking at it as a community discussion) this should be enough. Now, onto the rant.

**Issues of Flow**
To put it simply, the "flow", moreso how the game plays out, just does not work with Prison due to how TGMC works. An integral part of the map is cramped, CQC fighting; but that is what the map is. The limited open areas are surrounded by 2x2 hall maintenance, which is overall hell for Marines to push without using up limited OB supplies. I will say it here; Marines should have to use their orbital cannons, but it becomes an issue when nearly the entire map is a candidate for one. The twisting halls are hell to push through for ungas, which leads into my second point:
**Stalemating**
Out of all the maps in TGMC, this is the worst one when it comes to stalemating. As mentioned before, the open areas surrounded by maintenance are absolute hell for marines to push through, but also to Xenos. Nothing short of a 4-5 boiler spam will crack a marine defense with OB's, due to how large these open areas can become in relation to the closed tunnels that surround them. It is no coincidence that some of the longest (from observation) on average rounds are on Prison Station, next to Ice Colony. Ice Colony somewhat alleviates this issue by having the rest of colony able to be pushed by marines, but this is simply not the case in Prison. It will devolve to an absolute war of attrition, but not the fun kind. Some may like it, I most definitely do not; the ebb and flow is stopped by a constant grinding of who can spam the hardest, be in warlocks, TAT or artillery. Not to mention that outside of FOB a plasma cutter can make it absolute hell for xenos to push through, giving more and more open space. The entire map should not have to be PC'd or OB'd to be pushed through, that just is not healthy.
**Balance**
I hope it is pretty self-explanatory that this is a xeno-sided map. It takes a tremendous effort to push against Xenos who have a semblance of what they are doing, and vice-versa. There is too much hard-to-push areas in the map, without any "freebies" that other maps provide, such as Southern Admin in Big Red. It will always be surrounded by a massive concrete maze. This may not be a problem with bad Xenos, but that should not be the standard of quality; neither should it be bad Marines as well. Marines do not have enough equipment to tackle Prison Station effectively, and they shouldn't have that much equipment in the first place. Not to mention the vent system, which is the most extensive out of any map allowing Xenos to quickly traverse and reposition without consequence, making supply lines a living hell for Marines.
**FOBs**
Attributing to all listed above, the FOBs are absolute HELL to siege with their designs. It is hard to explain, but it is a mix of open and closed off areas that is good enough for marines to shoot through and hold a choke right outside of them. This may be the solvable issue out of all of them, as David pointed out that the FOB's could be wrapped around more with different entrances. Regardless, with the state they are in, it is Statemate Central™️ 

A bad part of this PR is that it sadly is removing variety. But I believe the negatives outweigh the benefits of it being a different map to play on, in this case. Though I like to make maps, I don't consider myself to be an expert on theory or anything like that: Prison simply sticks out like a sore thumb.
## Changelog
:cl:

del: Removes Prison as a selectable map.

/:cl:

### CODE REVIEW

**Comment by MiniMeatwad** [comment]
You have mope, you have xope, get ready for the pope.

**Comment by Lumipharon** [comment]
I'll stab you with a spork.

**Comment by imsxz** [comment]
just had a terrible round on prison station so im down

**Comment by FosterGrime-Heymynameslouie** [comment]
lmao

**Comment by chizzy376** [comment]
I think a rework of the map would be better. As it stands now, prison is a one of a kind map and just slashing it would mean the current map rotation would get staler even faster.

**Comment by Alexeivichi** [comment]
Salt PR. 1v1 HVH

**Comment by ivanmixo** [comment]
Not a fan of removal

**Comment by Pariah919** [comment]
Prison sucks because it's made for tdm and the disks all force you through hellzones

**Comment by RipGrayson** [comment]
Just for anyone who doesn't already know, CM in their infinite wisdom decided to make Prison a literal copy of a Prison Architect map Apop liked. 
harbor
https://steamcommunity.com/sharedfiles/filedetails/?id=524359537

This is why it plays differently and also why it doesn't play well, it was never designed with HvX in mind.

**Comment by David-Stormwell** [comment]
We all know this PR is never being merged, but ideally someone starting a prison redo would he interesting to say the least

**Comment by Wirpy** [comment]
I love prison

**Comment by isotope436** [comment]
i love prison and im summoning the gang to tell you why its based

**Comment by Mannybrado** [comment]
really gonna make a prison station removal pr but keep gelida and shitmoor

society

**Comment by lbnesquik** [comment]
Even if prison is bad, I don't think we have enough map variety at the moment to remove maps that are just bad. I personally mostly have a problem with the landing zones on that map.

**Comment by Joe13413** [comment]
> I think a rework of the map would be better. As it stands now, prison is a one of a kind map and just slashing it would mean the current map rotation would get staler even faster.

i fucking love this map but there is no shortage of people who bitch about it, which is fair, cause it's unbalanced as hell. A full rework is probably in order here

**Comment by LoganKele** [comment]
Going to miss and not miss this map, since i've been playing TGMC since 2019. I hate to see it go but it's not a very fun or fair map to play as Marine, any CQC xeno caste can just stalemate or stunlock without repercussion and marines all just use shotguns.

**Comment by Barnet2** [comment]
Closed for now, will likely be a HvH removal in the end once we get a few more maps.

**Pull request closed without merging**
