### PR TITLE
general purpose storage module bypasses ammo 

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
hugh did a dumb

## Why It's Good For The Game
it holds ammo again

## Changelog
:cl:
fix: general purpose module holds ammo
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -341. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SpaceLoveSs13** [comment]
No what why? IS module already got removed for stkrage creeping. How else will Smartgunners put extra drumd given to them and carry another gun? Even eith utility belt. general rarely gets used. And it can contain two mag/drum ammo. Really don't want this to be changed.

**Comment by SplinterGP** [comment]
> No what why? IS module already got removed for stkrage creeping. How else will Smartgunners put extra drumd given to them and carry another gun? Even eith utility belt. general rarely gets used. And it can contain two mag/drum ammo. Really don't want this to be changed.

general storage cant hold ammo, this makes it hold

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-346). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
