### PR TITLE
Decap gone, farewell

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Remove the decap mechanic

## Why It's Good For The Game

Decap is RNG based with a huge impact : be revivable or get removed from the game.

You can only be subject to decap if you don't have a helmet at all or a beret. Both have inferior armor, so they already  are inferior to jaeger. Why adding decap on top of that?

## Changelog
:cl:
del: Remove decap from game
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
Bearing the discussion held in various channels throughout the Discord server in mind, I'm honestly going to say most of the arguments I've seen for keeping decapping are downright silly. Realism, hilarity, 15-20 armor on this cosmetic option is a huge difference, I wAnT mUh nEcKgUaRd.

First off, _we're not a realistic simulator_. We're a game -- an RNG mechanic that has a chance of removing you from the round permanently with no chance of revival is very bad and poses little to **no fun** for our players.

I don't think I even need to construct an argument for hilarity here.

Berets get something between 15-20 armor. This is nothing compared to the constant 60-80 armor most of the marines get on normal helmets. Sure, it's not 0, but what's so bad about having 15-20 armor on a beret? It's still a low value, won't make that big of a difference and is still very easy to kill someone with this little protection.

It is my understanding that David wanted this neckguard idea of his, but I honestly don't see why we should keep decapping until a coder does whatever he wants. It's a stupid mechanic and it's about time it got removed.

**Comment by Lefunny** [comment]
If you get decaped you are dumb as hell, just use a fucking helmet, inst hard and no decap inst a """RNG""" if you arent using nothing that protect your head then you are going to be decapped, cry about it.

**Comment by GradusNL** [comment]
> 
> 
> Bearing the discussion held in various channels throughout the Discord server in mind, I'm honestly going to say most of the arguments I've seen for keeping decapping are downright silly. Realism, hilarity, 15-20 armor on this cosmetic option is a huge difference, I wAnT mUh nEcKgUaRd.

It being "silly" is the **_point_** of it. By wearing anything not a helmet you are picking the inferior option. It's like hardcore mode, not just a "cosmetic option". If you want it to be just a cosmetic option all hats should have the same stats as helmets and be able to take jaeger modules, which would be the real silliness here.

> First off, _we're not a realistic simulator_. We're a game -- an RNG mechanic that has a chance of removing you from the round permanently with no chance of revival is very bad and poses little to **no fun** for our players.
> 
> I don't think I even need to construct an argument for hilarity here.

First off, you aren't removed from the round permanently, you can just respawn in 30 minutes. Second, this RNG mechanic you are describing is **_entirely_** optional. Don't want it? Don't wear a beret. Everyone has access to helmets, nobody is forced to wear a beret.

As for hilarity, what is wrong with that? You said it yourself, TGMC is not a realistic simulator. A player **_choosing_** to handicap themselves and then suffering the effect of said handicap is inherently hilarious.

> Berets get something between 15-20 armor. This is nothing compared to the constant 60-80 armor most of the marines get on normal helmets. Sure, it's not 0, but what's so bad about having 15-20 armor on a beret? It's still a low value, won't make that big of a difference and is still very easy to kill someone with this little protection.
> 
> It is my understanding that David wanted this neckguard idea of his, but I honestly don't see why we should keep decapping until a coder does whatever he wants. It's a stupid mechanic and it's about time it got removed.

Decapping is not a stupid mechanic. It's a form of hardcore mode which comes with bragging rights. There is a reason you only see certain marine mains wearing a beret. Some of them even claim it as a form of tanking, pulling attention away from other marines since they themselves are more vulnerable targets. Just because you personally might not like it doesn't mean it has to be removed from the game, wear a helmet instead.

**Comment by AnCopper** [comment]
> > Bearing the discussion held in various channels throughout the Discord server in mind, I'm honestly going to say most of the arguments I've seen for keeping decapping are downright silly. Realism, hilarity, 15-20 armor on this cosmetic option is a huge difference, I wAnT mUh nEcKgUaRd.
> 
> It being "silly" is the **_point_** of it. By wearing anything not a helmet you are picking the inferior option. It's like hardcore mode, not just a "cosmetic option". If you want it to be just a cosmetic option all hats should have the same stats as helmets and be able to take jaeger modules, which would be the real silliness here.
> 
> > First off, _we're not a realistic simulator_. We're a game -- an RNG mechanic that has a chance of removing you from the round permanently with no chance of revival is very bad and poses little to **no fun** for our players.
> > I don't think I even need to construct an argument for hilarity here.
> 
> First off, you aren't removed from the round permanently, you can just respawn in 30 minutes. Second, this RNG mechanic you are describing is **_entirely_** optional. Don't want it? Don't wear a beret. Everyone has access to helmets, nobody is forced to wear a beret.
> 
> As for hilarity, what is wrong with that? You said it yourself, TGMC is not a realistic simulator. A player **_choosing_** to handicap themselves and then suffering the effect of said handicap is inherently hilarious.
> 
> > Berets get something between 15-20 armor. This is nothing compared to the constant 60-80 armor most of the marines get on normal helmets. Sure, it's not 0, but what's so bad about having 15-20 armor on a beret? It's still a low value, won't make that big of a difference and is still very easy to kill someone with this little protection.
> > It is my understanding that David wanted this neckguard idea of his, but I honestly don't see why we should keep decapping until a coder does whatever he wants. It's a stupid mechanic and it's about time it got removed.
> 
> Decapping is not a stupid mechanic. It's a form of hardcore mode which comes with bragging rights. There is a reason you only see certain marine mains wearing a beret. Some of them even claim it as a form of tanking, pulling attention away from other marines since they themselves are more vulnerable targets. Just because you personally might not like it doesn't mean it has to be removed from the game, wear a helmet instead.

.t Xeno Main.

**Comment by AnCopper** [comment]
> > .t Xeno Main.
> 
> Yes, and? Make an argument smoothbrain.

You are mad, I am calm and collected, therefore I win.

**Comment by Tristan63** [comment]
Swagger should always have a downside, decap was the biggest.

**Comment by BorranScail** [comment]
> > 
>
> > Berets get something between 15-20 armor. This is nothing compared to the constant 60-80 armor most of the marines get on normal helmets. Sure, it's not 0, but what's so bad about having 15-20 armor on a beret? It's still a low value, won't make that big of a difference and is still very easy to kill someone with this little protection.
> > It is my understanding that David wanted this neckguard idea of his, but I honestly don't see why we should keep 
> Decapping is not a stupid mechanic. It's a form of hardcore mode which comes with bragging rights. There is a reason you only see certain marine mains wearing a beret. Some of them even claim it as a form of tanking, pulling attention away from other marines since they themselves are more vulnerable targets. Just because you personally might not like it doesn't mean it has to be removed from the game, wear a helmet instead.

Thank you

**Comment by Ieteihowmee** [comment]
> Bearing the discussion held in various channels throughout the Discord server in mind, I'm honestly going to say most of the arguments I've seen for keeping decapping are downright silly. Realism, hilarity, 15-20 armor on this cosmetic option is a huge difference, I wAnT mUh nEcKgUaRd.
> 
> First off, _we're not a realistic simulator_. We're a game -- an RNG mechanic that has a chance of removing you from the round permanently with no chance of revival is very bad and poses little to **no fun** for our players.
> 
> I don't think I even need to construct an argument for hilarity here.
> 
> Berets get something between 15-20 armor. This is nothing compared to the constant 60-80 armor most of the marines get on normal helmets. Sure, it's not 0, but what's so bad about having 15-20 armor on a beret? It's still a low value, won't make that big of a difference and is still very easy to kill someone with this little protection.
> 
> It is my understanding that David wanted this neckguard idea of his, but I honestly don't see why we should keep decapping until a coder does whatever he wants. It's a stupid mechanic and it's about time it got removed.

We could always just readd head reattachment.

**Pull request closed without merging**
