### PR TITLE
re-balances req gun prices, removes some irrelevant power weapons, adds two new ones.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Adds an anti material rifle and railgun, removes the battle rifle and m92, makes the mbx a import gun.
Adds normal tracker ammo for shotguns, adds it to req only.
Rebalanced some of the vendor prices.

Needs inhands and December freeze finished

## Why It's Good For The Game
Most of the req guns suck poop right now, and most of them need rebalancing after aim mode.
MBX can just be an import gun, just make tracker ammo req only.

## Changelog
:cl:
balance: req has been redone.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -135. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
Oh boy here I go making more sprites

**Comment by Hughgent** [comment]
This lives, only because it is a draft

**Comment by TiviPlus** [comment]
no it doesnt

you know the rules
and so do I
say goodbye

**Comment by Pariah919** [comment]
sadge

**Comment by David-Stormwell** [comment]
poor mjp

**Comment by joookschad** [comment]
MBX should be made a normal gun for marines, or given to them like the T160, it's weaker than most marine guns anyway

**Pull request closed without merging**
