### PR TITLE
Updating the Sulaco [NEEDS POLISHING]

### PR DESCRIPTION
**Pull request by Timmeye**
I have never played on this map and but I know its one of the oldest CM:SS13 ship maps. I think I can completely redo the ship. Also im keeping the old walls even thought they're kinda bad, they smoothen out. **FUN FACT:** There was actually a super matter on the Sulaco but due to updates its broken.

### CODE REVIEW

**Comment by Timmeye** [comment]
shit I think I forgot to mapmerge

**Comment by jroinc** [comment]
PLEASE PLEaSE PLEASE FINISH THIS PLZ I WANT SO BAD

**Comment by MerryweatherLost** [comment]
It's okay, but

notable things:
half of the vendors missing
req is filled with walls
certain items like nanomed pop OUT of the direction its in into the hallways.
plagued with wall issues.

**Comment by jroinc** [comment]
Pls leave walls old sulaco walls 

And yeah, req's completely fucked, and vendors need a rework.

Other than that, it was amazing and I miss it so much.

**Comment by Timmeye** [comment]
Yeah, this isn't done yet.

**Comment by KwinOriginal** [comment]
I actually have an almost finished reworked Sulaco file, on my crashed laptop. Recovery needs to be done but it's there. So we should maybe talk to prevent double the work for a single output.

**Comment by Timmeye** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA WHY WONT IT MAP MERGE

**Comment by spookydonut** [comment]
Why are you changing bigert and admin level in a sulaco pr

**Comment by XSlayer300** [comment]
Try to compile it, mapmerge and see if you can find errors in it.

**Comment by spookydonut** [comment]
Still has changes to bigert and admin level

**Comment by spookydonut** [comment]
Still there

**Comment by Timmeye** [comment]
Fuck it, i'm  completely remaking this PR. The new PR wont have any other map changes other than the edits to the Sulaco

**Pull request closed without merging**
