### PR TITLE
Orion Military Outpost

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
Adds a new map and ports cm tall grass credits to the cm dev team

## Why It's Good For The Game
New map for low pop plus more map content is good

## Changelog
:cl:
add: Orion Military Outpost
imageadd: bunkbeds
fix: broken vendor props not having density
imageadd: tallgrass
delete: slowdown from bushes
/:cl:

manthese

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
**_nut_**

(this is ape speak for good fucking design)

**Comment by RipGrayson** [comment]
Nice to see more maps being added, you did pretty well so there's not much for me to nitpick over.
However there are some issues that need addressed

Your caves are not underground, and are vulnerable to CAS/Mortar. You can fix this by adding 
ceiling = CEILING_DEEP_UNDERGROUND to your cave areas.

There is no default CAS point, please add dropship_start location to your map so CAS isn't entirely useless.

You have space tiles in several areas, please remove them
space1
space2

In general please avoid long stretches of 2 tile long straight corridor, it tends to lead to stalemates that nobody can push through.
tun1

Please add another entrance or two, preferably a two tile entrance to engineering. It's very closed off right and could become a "binary" area that flips between one side and the other with no middle ground.
engi1

**Comment by MiniMeatwad** [comment]
Looks like jungle caves, cool

**Comment by RipGrayson** [comment]
This looks fine, it should be good for a TM.

**Comment by FosterGrime-Heymynameslouie** [comment]
is this a desert or a jungle map, maybe a mixture of both?
still, pretty cool to see a map that isint overly white, or red or yellow, brown is also a kewl color

**Comment by tyeagg** [comment]
its kinda like a very muddy jungle

**Review by BraveMole — CHANGES_REQUESTED** [review]
You need anti fob hug areas

**Comment by henriquekill9576** [comment]
FOB is not protected from acid rain (although it is funny)

**Comment by ilikesaying** [comment]
the dense bushes randomly cause massive slowdown
the randomly appearing fog is really frustrating to deal with

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Please remove the slowdown on bushes or replace them entirely.
chem2

I'm not sure why the tank needs inbuilt lights, is there a reason for this?

**Comment by tyeagg** [comment]
> Please remove the slowdown on bushes or replace them entirely.
> chem2
> 
> I'm not sure why the tank needs inbuilt lights, is there a reason for this?

because the tank is not actually multitile for some reason and requires just a little bit of light to be visible else its invisible with 0 light and requires another light source

**Comment by TiviPlus** [comment]
Why did you even add the tank its super broken

**Comment by tyeagg** [comment]
> Why did you even add the tank its super broken

for props, you cant move it since its anchored because the multitile on it is broken and the collision only exist in the center of the sprite  its also blocked by 3x3 invi wall to emulate collision so theres 0 ways to move it

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Given the broken state of the tank and the fact that it's getting added a lot to maps these days, I feel it would be best if you either converted it to an inert prop or made a prop version for mapper use.
Tivi can overrule me on this if needed.

**Comment by RipGrayson** [comment]
I think this map is ready for another TM before any final decisions are made on it.

**Comment by tyeagg** [comment]
in process of reworking this do not merge

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Overall this a much better layout than the first version, good job.

However there are no LZ computers, making hijack (mostly) impossible, I also could not locate the nuke generator please fix this.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
I don't see any xeno spawnpoints, please add them

**Review by RipGrayson — APPROVED** [review]
I don't see any reason why this shouldn't be merged, good job.

**Pull request merged**
