### PR TITLE
Jetpack buff

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

You can hop over razor wire with jeptack
You can pull something while jetpacking
More fuel

## Why It's Good For The Game

I forgot to allow jetpacker to go over razor wire, but this makes total sense if you can hop over wired barricade and fire
Pulling something while jetpacking will maybe allow medic to pull corpses or things like that, so this just allows jetpacker to do more things (even though it's a really minor thing)
You can know use flamer tanks to recharge the jetpack, which is a huge QOL as you don't have to run to a fuel tank all the time

## Changelog
:cl:
balance: You can jump over razorwire with jetpack
balance: You can drag someone while jetpacking. Carefull, any obstacle will block the person/object you are holding
balance: You can use flamer tanks to refuel the jetpack
balance: Slightly more fuel in the jetpack (75), so it matches a large fuel tank
/:cl:

### CODE REVIEW

**Comment by Walarks** [comment]
I don't know about pulling corpses since it might make retrieving marines or other pullable items too trivial and personally I don't think it should be jetpack's specialty.

**Comment by Guidesu** [comment]
> I don't know about pulling corpses since it might make retrieving marines or other pullable items too trivial and personally I don't think it should be jetpack's specialty.

wairth can do that....

**Comment by Swagile** [comment]
yeah this is still a req item and takes a backslot, so you'd have to setup your entire getup to saving people

and you can already save people pretty fast with the (free) roller beds which no one uses anyway so :shrug:

**Review by TiviPlus — COMMENTED** [review]
didnt submit

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
