### PR TITLE
Grapple Toss Distance is Now 4 Instead of 3 Because 3 Is A Stupid Overnerf

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

Per title.

## Why It's Good For The Game

Per title.

## Changelog
:cl:
balance: Warrior Grapple Toss distance increased from 3 to 4.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Decent.

**Comment by BraveMole** [comment]
So this is how the warrior toss war began ...

**Comment by usnpeepoo** [comment]
next thing you know they'll nerf fling to "compensate" but otherwise thanks for bringing warrior out of the ditch

**Comment by TiviPlus** [comment]
This pr is being closed for no justification provided as well as insulting other contributors in the pr title

**Pull request closed without merging**
