### PR TITLE
You can now fire the minigun one handed.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

This Pull request makes the T-100 Minigun able to be fired with a single hand.

## Why It's Good For The Game

To aid the ongoing trend of making every gun able to be fired one-handed with complete disregard to any gameplay balance, the T-100 minigun can now be fired with one hand.

Now you can finally roleplay as Frank Horrigan.

T2e1888

## Changelog
:cl:
tweak: You can now fire the minigun with one hand.
/:cl:

### CODE REVIEW

**Comment by RenGusta** [comment]
Dual Wield Minigun, basado???

**Comment by BraveMole** [comment]
Doesn't make any sense

**Review by SplinterGP — CHANGES_REQUESTED** [review]
that's not even the minigun youre changing the T-26

**Comment by BraveMole** [comment]
Out of all the guns, minigun is the less likely to be one handed, with maybe sadar...

**Pull request closed without merging**
