### PR TITLE
edits armor color names and organization; adds two new armor colors

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request

**renames some colors for accuracy of the names to the hues**

salmon --> pearl pink
magenta --> azalea
sakura --> coral

bronze red --> copper

_old_ yellow --> olive
honey --> cathay

beige --> ginger

jade --> kelly green
smoked green --> rifle green

navy --> blue
_old_ blue --> turquoise
cottonwood --> cornflower
aqua --> teal
cerulean --> stone blue

iris purple --> purple
_old_ purple --> red violet
orchid --> heron
lavender --> violet

**adds a new yellow and a new pink color**

this is "yellow". this replaces the old "yellow" (which is now "olive")
image

this is mountbatten pink.
image

**re-orders color lists**
this is hard to explain but a rather intuitive concept, so i've included an image to offer a better sense of what this all means. currently, the colors are listed in no particular order under the hue they are.
this reorders the list of colors (and associated palettes in the code for consistency), to:
1. have whatever the **base color** for each hue is be the first color listed. if you go looking under the hue "yellow", the first option in the list will be the color "yellow" (versus "gold")
2. squad colors will always be at the end of the list of whatever their respective hue is. faster to filter this way.
3. colors in each hue are grouped based on whether they lean blue- or red-shifted. the ordering depends on wherever in the rainbow the hue itself falls. (ie, reds will now transition from reds to orange reds, as the next hue listed after the reds is orange). just think rainbow order.
4. aside from the organization based off the shift of the colors listed under a hue, they're also organized in value. colors with more grey that appear darker now appear in the list after colors that appear lighter.
image

used pantone color system for reference; mountbatten pink based off the one presented in _the secret life of colors_ by kassia st. clair.
## Why It's Good For The Game

some hues were mis-named for what they are. it made it a little harder if you have an idea of a particular shade of something you want and it's not named in a way that makes you think "ah, that's what i'm looking for!".

adds two new colors, one pink and one yellow. i thought these were colors that filled in some gaps we had with our collection.

re-organizes the way colors will appear in the tgui list when someone's using their facepaint on an armor piece. this keeps it a little more organized, so now people can just go down the list to cycle through (relatively) darker shades

## Changelog

:cl:
add: adds two new armor colors: mountbatten pink and yellow (replaces the old "yellow" which is now "olive")
fix: fixed a few color names
/:cl:

### CODE REVIEW

**Comment by Otterwatch** [comment]
"Navy" being just regular blue and "blue" being Greenish Blue infuriated me for trying to find which shade I wanted. I had to click every single random named blue just to find the right shade. Thank you. Also, nice work with all of the details you've provided on your pr.

**Comment by Tailiik** [comment]
New colors are cool but I see 0 point to renaming colors, just gonna make people think that their favorite color got axed and make them have to check a bunch to find it

**Review by TiviPlus — APPROVED** [review]
code ok ask kuro for merge

**Comment by coldironwarrior** [comment]
> New colors are cool but I see 0 point to renaming colors, just gonna make people think that their favorite color got axed and make them have to check a bunch to find it

this is fair; i was thinking about this from the opposite standpoint and for players who might be just starting to make new loadouts

**Comment by coldironwarrior** [comment]
will fix conflicts when i have time

**Comment by coldironwarrior** [comment]
this is good to go again and is updated with all of the newer colors added

**Comment by Kuro020** [comment]
I'm not gonna read all of this

**Pull request merged**
