### PR TITLE
Refurbishes thunderdome

### PR DESCRIPTION
**Pull request by breadhunt**
## About The Pull Request

Touches up thunderdome, adds some extra fluff rooms to observer side, adds hidden cameras (I am in your walls) to view the dome with, and adds buttons to toggle the blast shutters on either side.

Wider view in sdmm:
image
Ingame view:
image
Central camera view:
image

## Why It's Good For The Game

-Makes 2d spessman prettier (the real reason why it's good for the game)
-Admin stuff working is always nice
-Currently thunderdome cams are (basically) exclusively viewable in tdome. But we could add them to shipmaps/bars/whatever in the future (maybe, eventually) for viewing pleasure while RPing. Could even give admins something !!FUN!! to do
-Gives more options for bored admins, and thus options for those poor few with MASSIVE skill issues
-Did I say it looks pretty? Having a nice tdome is so fucking cool

## Changelog
:cl:
admin: Refurbished thunderdome
/:cl:

### CODE REVIEW

**Comment by RipGrayson** [comment]
This probably needs admin approval since they're the ones that actually use thunderdome, but otherwise looks fine except for one tiny thing.

Please move this shark one more north, on map load the carp can randomly move two tiles in any direction and is currently in danger of appearing inside the thunderdome wall.
shark

**Comment by breadhunt** [comment]
> Please move this shark one more north, on map load the carp can randomly move two tiles in any direction and is currently in danger of appearing inside the thunderdome wall.

It's a feature, the wall carp is the mascot of the bar

Either way, fixed. PR ready for TM/merge now

**Comment by lKiseki** [comment]
Looks good to me.

**Comment by MereWalker** [comment]
Personally, I don't see how this will help it or hinder it. So it's a yes for me.

**Review by RipGrayson — APPROVED** [review]
Looks fine to me

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
