### PR TITLE
Removes juggling NO MOB VARS edition

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Title. You wont be able to fire a weapon for its fire_delay when you pick it up.

## Why It's Good For The Game

removes juggling without touching mob vars

## Changelog
:cl:
balance: removed juggling
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
Doesn't that also nerf every instance of getting knocked down and trying to quickly get your weapon back up and shoot?

**Comment by Waselon** [comment]
> Doesn't that also nerf every instance of getting knocked down and trying to quickly get your weapon back up and shoot?

it is unnoticable on every other weapon except shotguns. If you are using a shotgun, just dont get stunned

**Comment by Losenis** [comment]
Marine to xeno: Just stun lol
Xeno to marine: Just dont get stunned lol

**Comment by ZahaSanko** [comment]
> > Doesn't that also nerf every instance of getting knocked down and trying to quickly get your weapon back up and shoot?
> 
> it is unnoticable on every other weapon except shotguns. If you are using a shotgun, just dont get stunned

Just don't get shot by a juggler then, let's not be hypocrites

**Comment by Losenis** [comment]
Just stun the juggler too. It's not that hard.

**Comment by Lumipharon** [comment]
That's a pretty huge stun buff against what's supposed to be cqc weapons

**Comment by Losenis** [comment]
It also sounds like it won't do anything vs DB juggling given it already has a very short weapon cooldown, probably just enough to cover the wielding time.

**Comment by Naaanii** [comment]
This also nerfs using Shotguns in general, not the just the juggling issue.

Don't really see how this is much different from just disallowing shotguns to fire mid wield and increasing wield timers.

**Comment by Losenis** [comment]
The last thing I'd have expected this guy to support is a cover to keep juggling in and pretend they're doing anything, by his own suspicion.

**Comment by Waselon** [comment]
> It also sounds like it won't do anything vs DB juggling given it already has a very short weapon cooldown, probably just enough to cover the wielding time.

DB got an additional 1 second delay

**Comment by Naaanii** [comment]
> Shotguns are already an extremely powerful choice that can instantly shut-down all but two castes in the game. I'm not sure* what marine-mains are coping about in this PR. Just... wait 0.3 seconds? Use an angled grip? *(They're running cover to keep juggling from being patched, as is typical for marine-mains.)

At least they don't just comment 'Salt PR' and give absolutely 0 feedback :^)

**Comment by Naaanii** [comment]
This doesn't seem to work on the DB with the current TM.

**Comment by Waselon** [comment]
additional DB pickup delay increased to 2 seconds

**Comment by lKiseki** [comment]
comment from the discord
image

**Comment by Xsdew** [comment]
The point of juggling is that you can swamp to another primary to continue firing instead of reloading. So if you wish for shotguns not to be juggled all you have to do is add GUN_WIELDED_FIRING_ONLY and make the wield_delay be slightly slower than the fire rate of the weapon. In this particularly case it is only the DB that needs it.

**Comment by Lumipharon** [comment]
Juggling is an issue specifically for shotguns, so I don't thing a solution that effects all guns is a good one. There are other ways to effect all or specific shotguns to get this effect.

**Comment by Jordanstolethepreciousslam** [comment]
> Juggling is an issue specifically for shotguns, so I don't thing a solution that effects all guns is a good one. There are other ways to effect all or specific shotguns to get this effect.

Not true. You can also juggle DMRs fairly effectively, repeaters and some slow firing handguns

**Pull request closed without merging**
