### PR TITLE
Jaeger rework/balance, all stats moved to chestpiece. Armor stats changed.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
All stats are moved to chestpiece, arms/legs are cosmetic.

Armor is now 30/40/50 from 40/45/50.
Bomb armor has been changed slightly, it has -5 on light, same on medium, 5 more on heavy. Makes sense this'd be slightly different.
Otherwise all stats have been moved to the chest piece from the arms.

## Why It's Good For The Game
Light armor is absurd and needs a melee nerf, there's a .6 difference in levels for a 10% dfiference, which is usually one or two slashes. and you can make that up in dodging.
Medium needs a minor nerf, .4 difference between it and heavy.
Heavy is unchagned outside of a minor bomb buff.

Jaeger arms/legs are basically cosmetic these days and should reflect that, this makes making stats for jaeger less annoying as hell.

## Changelog
:cl:
tweak: all stats on jaeger have been moved to chestpieces, arms/legs are cosmetic, all the arm/leg stats have been moved to chestpieces.
balance: light jaeger has lost ten melee armor and five bomb, medium jaeger has lost five melee armor, heavy jaeger is unchanged in melee and gained 5 bomb armor. 
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
what's the reason for this ? thats a pretty huge nerf which leaves heavy untouched, which is basically only module which can use tyr with any benefit at all

**Comment by EvilMelonTheSecond** [comment]
This seems like it'll force heavy jaeger builds. Light armor already feels paper thin since a single runner can just pounce and cause a chest frac.

**Comment by RenGusta** [comment]
The reason we did 40/45/50 for armor was so the gap wasn't huge and we saw something other than heavy Jaeger only. This will almost definitely return us to heavy Jaeger days, unless light has some substantial bonus to justify it being many seconds less survivable.

**Comment by Kuro020** [comment]
Currently there is no reason to use anything but light armor, 0.3 speed for 10% more damage is absurd, you're not paper thin by any stretch and you're also fast as fuck,there should be a tradeoff for that kind of speed

**Comment by Losenis** [comment]
>which is usually one or two slashes. and you can make that up in dodging

Enlighten me how I can dodge the slashes a rouny is giving while pouncestunned, or a warrior's 2x flingpunch damage bonus, or getting hit by a bull's/defender's stun, etc.

**Comment by SplinterGP** [comment]
> Currently there is no reason to use anything but light armor, 0.3 speed for 10% more damage is absurd, you're not paper thin by any stretch and you're also fast as fuck,there should be a tradeoff for that kind of speed

>removes storage  module slowdown
>complains marines are too fast

**Comment by SplinterGP** [comment]
> Currently there is no reason to use anything but light armor, 0.3 speed for 10% more damage is absurd, you're not paper thin by any stretch and you're also fast as fuck,there should be a tradeoff for that kind of speed

Also yes it is 10% compared to base damage being caused, but from the damage received by a 23 damage attack, light receives 13,8 and heavy receives 11,5
If you look from that
11,5 10% is 1,15
11,5+1,15 = 12,65
12,65 + 1,15 = 13,8

From looking at the base damage yes its 10% but you gotta do more than 10% damage to reach that damage without the 10% reduction, the more armor you have the more efficient each small amount of armor is.

**Comment by Hekzder** [comment]
> > which is usually one or two slashes. and you can make that up in dodging
> 
> Enlighten me how I can dodge the slashes a rouny is giving while pouncestunned, or a warrior's 2x flingpunch damage bonus, or getting hit by a bull's/defender's stun, etc.

By not getting hit by any of those stuns in the first place via having substantially more mobility than someone in Heavy armor. Pounce stun isn't super easy to dodge regardless of speed, I'll give you that. Warrior combo is more so just punishing aggression, over extend and you get memed, but with more speed you can escape being brazil'd more easily or evade a combo at the last second. Getting hit by Bull/Defender stun in light armor is a genuine skill issue, that is a complete non argument here.

**Comment by SplinterGP** [comment]
> 
> 
> > > which is usually one or two slashes. and you can make that up in dodging
> > 
> > 
> > Enlighten me how I can dodge the slashes a rouny is giving while pouncestunned, or a warrior's 2x flingpunch damage bonus, or getting hit by a bull's/defender's stun, etc.
> 
> By not getting hit by any of those stuns in the first place via having substantially more mobility than someone in Heavy armor. Pounce stun isn't super easy to dodge regardless of speed, I'll give you that. Warrior combo is more so just punishing aggression, over extend and you get memed, but with more speed you can escape being brazil'd more easily or evade a combo at the last second. Getting hit by Bull/Defender stun in light armor is a genuine skill issue, that is a complete non argument here.

well you forget every other source of slowdown exists, modules, wounds, even gun itself causes slowdown and most times higher than the armor you're using

**Comment by SplinterGP** [comment]
This is wack and makes little sense at all.

**Comment by Losenis** [comment]
"Just don't get hit bro"

**Pull request closed without merging**
