### PR TITLE
MMG sprite update by Ocelot

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
T-27 MMG gains a better icon sprite.

## Why It's Good For The Game
Doesn't look like its straight out of 2019 CM, and is cooler.
image
has RDS and Supperssor on it.

## Changelog
Pariah919, Ocelot
:cl:
spriteadd: New MMG sprite, by Ocelot/SilencedMp5A5 (Or Przyjaciel on discord)
/:cl:

### CODE REVIEW

**Comment by FlakBait00** [comment]
based, speedmerge

**Comment by Lumipharon** [comment]
Probs should show the sprite without the suppressor, btw. Unless you made that part of the base sprite? Looks pretty snazzy either way

**Comment by Pariah919** [comment]
> Probs should show the sprite without the suppressor, btw. Unless you made that part of the base sprite? Looks pretty snazzy either way

image

**Comment by FosterGrime-Heymynameslouie** [comment]
based spped mehrg

revert the sound it does back to when it used to sound beffier too, current sound is PUNY compared to the previous one

**Review by TiviPlus — APPROVED** [review]
Kuro when review pr 🛌

**Review by Kuro020 — CHANGES_REQUESTED** [review]
update the mob sprite to reflect these changes

**Comment by MereWalker** [comment]
YES! Thanks!

**Pull request closed without merging**
