### PR TITLE
Soldering tool repairs the next damaged limb

### PR DESCRIPTION
**Pull request by Three333Digit**
## About The Pull Request
Soldering tool now works like welder and cable coil where it'll repair the next damaged limb until it's done

## Why It's Good For The Game
I'm lazy

## Changelog
:cl:
qol: soldering tool repairs the next damaged limb
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
spded megh instantly

**Comment by Losenis** [comment]
B A S E D

**Comment by Beepinex** [comment]
this would make me want to help robots as engi more

**Comment by MereWalker** [comment]
Would be nice if medics got a solder for this reason here. It's a pain to ask engis for their kit. Would be nice if it came with the loadout or you could buy it.

**Comment by vilereaver41** [comment]
holy shit! thank youuuuu. its so annoying to find the right limb

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
