### PR TITLE
Infinite Ammo for Operations Vendor in Req

### PR DESCRIPTION
**Pull request by FosterGrime-Heymynameslouie**
## About The Pull Request

Infinite Ammo for Operations Vendor in Req. This PR aims for carpel tunnel rates among RO players to go down. 

I understand that specailized ammo boxes hold more ammo than ammo boxes, but granted that the RO has a stack of cardboard at req at the start of the round and can make more, they virtually have infinite specialized ammo boxes. I also do not believe that balancing out usage through obscurity is a good idea.

To the people who vend all ammo during prep then shove them on a nearby crate so they can drag them to alamo, their is an ammo crate that does the loading alamo with ammo process nearby most reqs.

Also hurray for my very first PR. Id like to thank lumi, a potted plant and being ignored in dev chat that bought me here today!

This PR is meant to be the sister PR of: #11951

## Why It's Good For The Game

I believe spam clicking on weapons vendor for ammo as RO whenever someone asks for ammo should be avoided as much as possible, this PR aims to streamline the supply process while also cutting down on carpel tunnel development rates.

## Changelog

:cl:
balance: infinite pre filled ammo boxes in op vendor
/:cl:

### CODE REVIEW

**Comment by DerFlammenwerfer** [comment]
> You can just click once and hold space though.

That's really cool, but who asked?

**Comment by Barnet2** [comment]
Good change.

**Comment by Losenis** [comment]
Based pr

**Comment by FosterGrime-Heymynameslouie** [comment]
> You can just click once and hold space though.

bruhg....

**Comment by FosterGrime-Heymynameslouie** [comment]
> This makes it mega easy to effortlessly spam infinite amounts of ammo everywhere. I don't really play RO but I unno if this is desirable.

is possible but you also need a dedicated person with a beacon or antenna
given how fluid tgmc gameplay is youd be hard pressed to find a place to flood ammo, plus you can already do this with the ammo crates that we already have, its just that youll get carpel tunnel as a side effect If we really do be havin a dedicated guy popping their beacon, antenna or radiopack and constantly reseting em instead of shooting the xenos

pr mainly makes it so that RO's, st's or req personnel no longer have to sacrifice their fingers or make an auto clicker macro in order to vend ammo for the occasional person asking for some in comms (plus, also negates having to wait for a minute because you cliked too much in a short time frame)

**Comment by DerFlammenwerfer** [comment]
It seems like a good QoL change for RO, at the end of the day.

**Pull request closed without merging**
