### PR TITLE
Warrior lunges grab humans in their offhand

### PR DESCRIPTION
**Pull request by psykzz**
## About The Pull Request

Warrior lunges grab humans in their offhand

## Why It's Good For The Game

Helps to ease the pain of playing warrior

## Changelog
:cl:
tweak: Warrior lunges now grab humans in their offhand.
/:cl:

### CODE REVIEW

**Comment by psykzz** [comment]
I dont see how replacing this with 3 procs 
```
swap_hands()
start_pulling()
swap_hands()
```

Is better than updating a proc to directly add an item into the offhand?

If you dont like how the tenary was used, I can always make a sister function to improve readability.

**Comment by Rohesie** [comment]
Guess Spooky meant #1638 .
Think you can make it compatible with it?

**Comment by psykzz** [comment]
Originally from discord the conversation was to add the extraa swap_hand() procs but yeah once #1638 is merged ill rebase and try this again, can block it until then.

**Comment by Rohesie** [comment]
It's in, feel free to rebase.

**Comment by psykzz** [comment]
@Rohesie @spookydonut updated this with the latest rebase

**Pull request merged**
