### PR TITLE
Removes the ability for the FK-88 to be rotated while deployed

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
Saltpr? Yes absofuckinglutely
## Why It's Good For The Game
The ability for an incredibly powerful anchored gun like the FK-88 to turn on a dime and fire instantly is mildly problematic as it means that xenos have no ability to safely approach it. 
## Changelog
:cl:
balance: Removes the ability for the FK-88 to be rotated while deployed
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
Only experience i have with the FK-88 was pre Devastation buff, where i shot a Sentinel with HE and it didn't die from the hit. someone else had to mop them up, and only because the sentinel didn't jump behind cover for some reason, as on reviewing the footage, i'm pretty sure they could have.

**Comment by yyzsong** [comment]
> pre Devastation buff

The FK-88 doesn't actually have Deva, only heavy explosion. A direct hit probably would have killed it, though.

**Comment by Looking4bros** [comment]
> A direct hit probably would have killed it, though.

I know it was a direct hit because it blew up our barricades it was dancing around. Would have sailed past and hit the wall behind them. Pretty sure they had Queen or at least King level Warding Pheros though as it was during a hijack, Did you?

**Comment by Looking4bros** [comment]
On MUCH closer inspection of the video, the sentinel i shot didn't die (SA-X) a different sentinel is the one that died pushing recklessly. Here have a video, not the Sentinel who throws the gas nade, the one who dies shortly after(Wyvern), and the one that slashes me at the end of the video(SA-X).


https://github.com/user-attachments/assets/ddc6c5ce-1700-4cdb-83ef-9be6c007b725

Mind you, my original intention when loading it was not to nuke the barricades, but to fire it into the room they were using as cover, but the temptation was too great, alas, i didn't know how weak this gun is.

**Comment by Kuro020** [comment]
The FK is most likely the worse mounted weapon MJP added, i do not see why it needs this nerf

**Pull request closed without merging**
