### PR TITLE
new jaeger light set and open helmet

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
kuro told me to add these so i did, idk ask him for pictures i just compiled and made sure it isn't broken i don't wanna compile again

## Why It's Good For The Game
more customization and David stops complaining about open helmets

## Changelog
:cl:
add: Added new  jaeger light set, and new jaeger open helmet
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -243. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
Open Helmet
image

Closed Helmet
image

**Comment by Guidesu** [comment]
FINNALY!

**Comment by David-Stormwell** [comment]
speed merge when

**Review by TiviPlus — APPROVED** [review]

**Review by SplinterGP — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-267). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
