### PR TITLE
TGMC Ingame Store

### PR DESCRIPTION
**Pull request by Ragecrabbo**
## About The Pull Request

Adds brand new ingame store to TGMC!!!
TGMC STORE INGAME
Using real money or **TGMC coins™** (aquired either from playing or using real money) you can purchase never before seen content to the game to spice up your rounds, including but not limited to:

**GOLDEN SKINS**
Golden

**NEW UNLOCKABLE XENOS**
XENO HORDE
AND MUCH MUCH MORE
## Why It's Good For The Game

new content : )

## Changelog
:cl:
add: Added brand new TGMC store into the game where you can buy skill improving upgrades and skins.
add: Added **TGMC coins™** which can be gained from playing the game or bought with real money.
qol: Made game better.
balance: Fixed Balance forever.
fix: fixed TGMC
/:cl:

### CODE REVIEW

**Comment by Ragecrabbo** [comment]
speedmerge pls i'll buy you steam games

**Comment by FosterGrime-Heymynameslouie** [comment]
sppedmehge

**Comment by Alexeivichi** [comment]
This PR gave me depression.

**Comment by BraveMole** [comment]
Not even nfts. Also can't merge because it is failing ci

**Comment by Ragecrabbo** [comment]
> do you take rouny coin ?

no this is a serious PR, im not accepting meme currency



> Not even nfts. Also can't merge because it is failing ci

maintner cabal once again keeping down common man, this is why TGMC is failing :/

**Comment by SpaceLoveSs13** [comment]
You broke CI for map compile somehow with bad changes. Really good pr. FIx them and get this new content merged ASAP(REAL).

**Comment by Ragecrabbo** [comment]
> You broke CI for map compile somehow with bad changes. Really good pr. FIx them and get this new content merged ASAP(REAL).

Any clue what might be causing this? My changes are very good! 🙂

**Comment by TiviPlus** [comment]
Can I get a rouny nft

**Comment by Ragecrabbo** [comment]
Thank you for letting this april fools PR stay up, hope you all had a good laugh ❤️

**Pull request closed without merging**
