### PR TITLE
Deletes the engineering dispenser.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Now that it's not april first, deletes the engineering dispenser.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/pull/12590
## Why It's Good For The Game
Reasons why the dispenser should be removed:
- Large items are balanced by the fact that they are large, which the dispenser completely bypasses.
- Solder was removed for being the powercreep robot healing device, yet this functionality is on dispenser but even better because it doesn't even require someone to actually channel through progress bars + AOE.
- All the suggestions for balancing dispenser are focused on removing features (the healing, holding bulky items), removing storage space (make it backpack sized but let it hold bulky items) or make it slower to deploy/undeploy/make it more vulnerable.
- The fact that dispenser exists means that it becomes the ONLY option for engineers to take. Because it's so powerful, taking any of the other options is seen as trolling/griefing. 

Reasons why it should be kept:
- Engineering powergaming with 3 BAS sentries in a dispenser with 200 ammo boxes for degenerate strategies.
- Powergaming as a robot with the free heal
- Powergaming with a flamethrower (It can hold 6000 units of welding fuel)
## Changelog
:cl:
del: Deletes the engineering backpack dispenser.
/:cl:

### CODE REVIEW

**Comment by Autisem** [comment]
was the point not that you had to deploy it, making your storage vulnerable and unavailable immediately?

>The fact that dispenser exists means that it becomes the ONLY option for engineers to take. Because it's so powerful, taking any of the other options is seen as trolling/griefing.

you remove this it will become the welderbackpack just like old times. Engineers simply get better backpacks but the options are normal packs, radiopack(completly outshined by the antenna module) or the welder pack(new engineer meta pick)

**Comment by Xander3359** [comment]
> was the point not that you had to deploy it, making your storage vulnerable and unavailable immediately?

It is actually immediately available from the second that you begin the deployment.
On the topic of vulnerable: Engineers would rather die than lost their dispenser, they will undeploy it immediately after taking whatever items they needed out of it.

> you remove this it will become the welderbackpack just like old times. Engineers simply get better backpacks but the options are normal packs, radiopack(completly outshined by the antenna module) or the welder pack(new engineer meta pick)

AND THATS OK. THERE IS CHOICE, YOU ARE NO LONGER FORCED TO PICK DISPENSER.

**Comment by Otterwatch** [comment]
The Engineering Dispenser is the more interesting and ultimately more fun version of the solder. Xenos can counter the dispenser unlike the solder. There are many ways for them to kill it such as acid spit, crushing, or just good old slashing. 

Dispenser being a meta pick is completely irrelevant to whether it should be removed or not. Improve the other options or nerf dispenser. 

> * All the suggestions for balancing dispenser are focused on removing features (the healing, holding bulky items), removing storage space (make it backpack sized but let it hold bulky items) or make it slower to deploy/undeploy/make it more vulnerable.

Literally any of those options (minus the removal of healing) are better than removing the item outright. 

Your pros and cons list (reasons to be kept versus removed) is clearly just a shitpost, but there are actual cons to the dispenser. Having to deploy it and risk losing it and all of the items inside is a major con. It taking up a backpack slot compared to what you compared it to (the solder) is another con. Finally, people can take anything from inside of it. Which you could view as a pro and a con. A curse and a blessing, because while it's nice to have a setup where people can resupply; there are other situations where some random marine steals something vital for your setup and runs off with it. 

If you came up with a better alternative to improved robot healing, this would be a drastically better pr. If this pr added anything to the game at all, it might be a half decent pr. Straight up removing features/content is not an interesting pr, nor is it needed.

**Comment by Losenis** [comment]
>Powergaming
>Powergaming
>Powergaming

There it is again, the magical word

**Comment by Oscari-pog** [comment]
image

**Comment by docRoboRobert** [comment]
Quite the salt pr

**Comment by Lumipharon** [comment]
Rather nerf then delete it.

**Pull request closed without merging**
