### PR TITLE
Late Synthetics now look better.

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

Synthetics now use the same sprites as humans. 

## Why It's Good For The Game

Synthetics are artificial bio-mechanical beings meant to provide support to marines, generally in non-combat focused roles (Medical, Engineering, etc). Because of their necessity to interact with humans in a meaningful and even caring way it makes sense that they would be produced to emulate humans as closely as possible. I know we don't use the movies as much as CM but even in the first movie the crew's synthetic (who pretends to be human and fools everyone until he reveals it) looks exactly like a human.

Gameplay wise this just looks better, the current synthetic sprites are these awful default human sprites. And the female sprite in particular has this horrendous forced lipstick on it that just ruins it.
Worries about being unable to identify synthetics are insubstantial, marines have the map icon and job hud icon. While both Xenos and Marines can also still easily identify synthetics visually thanks to their civilian choice of outfit, the synthetics always stand out among the armor wearing marine with their casual (or sometimes ridiculous) outfits.

As for the removal of early synthetics, it seems silly that the fancy well equipped TGMC would have such an old model.
Gameplay wise the sprite is just a low quality recoloring and early synthetic is never used, it doesn't even have the gameplay differences it used to just looking different.

Kuro Approved
00 aaaaA

## Changelog
:cl:
expansion: All TGMC assigned synthetics have been updated to ease uncanny valley complaints from marines.
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
Also if anyone does know why the wisp hair is so bright I'd love to know.
00 Wisp comparison
For example the left is TG and the right is TGMC, the hair color hex value is completely the same.

**Comment by XSlayer300** [comment]
tg uses a white base for their hairs i think, while tgmc uses a black base.

**Comment by Ragecrabbo** [comment]
> Also if anyone does know why the wisp hair is so bright I'd love to know. 00 Wisp comparison For example the left is TG and the right is TGMC, the hair color hex value is completely the same.

Not sure if this is TGMC specific but hair color seems to be in some weird state where you have an entire color wheel to work with but the game still picks from a few presets rather than the color you picked. Makes getting a specific color you want very annoying.

**Comment by Arctrooper8** [comment]
> > Also if anyone does know why the wisp hair is so bright I'd love to know. 00 Wisp comparison For example the left is TG and the right is TGMC, the hair color hex value is completely the same.
> 
> Not sure if this is TGMC specific but hair color seems to be in some weird state where you have an entire color wheel to work with but the game still picks from a few presets rather than the color you picked. Makes getting a specific color you want very annoying.

As XSlayer notes TGMC uses black hair bases that compared to TG's white hair bases the final product can be much brighter than the color wheel implied. Tivi told me that while you can't change the whole system you can edit the hair bases themselves if you feel they are too bright.

**Comment by Al-1ce** [comment]
Synths for the longest while have looked strange and spawn with an unusual palate for the face that makes it seem like they're wearing lipstick or some shit.

While I don't necessarily disagree with them looking the same, extensive damage should have some sort of affect on certain bodyparts or the overall sprite.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
I see no valid reason to remove early synth as well on top of it not being atomized

**Review by BraveMole — APPROVED** [review]
You gotta fix CL and pr description

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
