### PR TITLE
Adds new male scream

### PR DESCRIPTION
**Pull request by crayonLover09**
## About The Pull Request
Adds 2 new male scream and male pain sounds

## Why It's Good For The Game

https://user-images.githubusercontent.com/105026812/177893140-d9a88876-aca5-46d1-863e-f5371941f0aa.mp4

## Changelog
:cl:
soundadd: added 2 new male scream/pain sounds
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
juicy

**Comment by Losenis** [comment]
When do we get the hl2 scientist sounds

**Comment by helper-2** [comment]
"I need a medic bag."

**Comment by TiviPlus** [comment]
Copyright

**Pull request closed without merging**
