### PR TITLE
Reverts #12118 "Redoes robot healing a little"

### PR DESCRIPTION
**Pull request by chizzy376**
### About The Pull Request

The removal of solder, a very important tool in the kit of a synth has drastically nerfed the role while also flipping off every engineer/corpsman wanting to fix up robots. This change was hidden from the PR's title which **skews votes and** I find extremely shady.

### Why It's Good For The Game

Solder being a thing = robot repair doesn't mean you have to carry 50 cable coils and 50 blowtorches anymore.

### Changelog
Reverts tgstation/TerraGov-Marine-Corps#12118
🆑
balance: reverts the solder removal
/🆑

### CODE REVIEW

**Comment by QualityVan** [comment]
What do you mean, undocumented? It's the first line in the changelog.

**Comment by novaepee** [comment]
> This change was not only hidden from the PR's title, but also in the CL's balance which I find extremely shady.

False. Read the CL, and it explicitly says that the PR removes soldering tool.

image

**Comment by Xsdew** [comment]
Fuel, welders, and coils are not hard to grab for a loadout. And are more in line with gauze and ointment. 

Solder is just free unlimited healing for the two damage types that matter to robots.

**Comment by chizzy376** [comment]
> What do you mean, undocumented? It's the first line in the changelog.

The title didn't mention anything about a solder removal

**Comment by novaepee** [comment]
Soldering tool will be replaced by https://github.com/tgstation/TerraGov-Marine-Corps/pull/12122 , which, in my opinion as the creator of soldering tool, will help combat robot more than soldering tool. Combat robot is less healing intensive compared to a human, and the PR I've mentioned will permit combat robot to be more independent for healing.

**Comment by novaepee** [comment]
> The title didn't mention anything about a solder removal

You need to read more than the PR's title to grasp what the PR entails otherwise you miss out important information.

**Comment by chizzy376** [comment]
Synths use their high engineering skill to repair themselves (And other robots) faster. That is the point of the soldering tool, a robust alternative that usually takes longer (Since it costs nothing) but is very well worth it. Synth is useless without this. Please do not split a "removal" and "replacement" pr, as the time between the two is without a purpose.

**Comment by chizzy376** [comment]
> First they came for imagers
I did not complain because I did not use imagers

> Then they came for female robot sprites
I did not complain because I did not use robot sprites

> Then they finally came for solder
And there was nobody else left to defend my solder

**Comment by novaepee** [comment]
> Synths use their high engineering skill to repair themselves (And other robots) faster. That is the point of the soldering tool, a robust alternative that usually takes longer (Since it costs nothing) but is very well worth it.

The soldering tool was made in light of combat robot not healing well to the point that squad corpsman doesn't want to heal them. I've made the PR, #9131 , and I can tell you that the reason why soldering tool had infinite use was because my negligence of game design. Tivi is correct, and have disagreed with the existence of soldering tool since the beginning as they have made combat robot, that it is a powercreep tool, and needs to get replaced by something better.

**Comment by chizzy376** [comment]
Synth needs it, fuel or not.

**Comment by novaepee** [comment]
> Synth needs it, fuel or not.

Synth can just take nanopaste from surgery tray, a more balanced alternative.

**Comment by Lumipharon** [comment]
Infinite mega heal item is bad.

Also unrelated, but robots can use engie storage modules now if you're having issues with carrying repair supplies.

**Comment by chizzy376** [comment]
> > First they came for imagers
> > I did not complain because I did not use imagers
> 
> > Then they came for female robot sprites
> > I did not complain because I did not use robot sprites
> 
> > Then they finally came for solder
> > And there was nobody else left to defend my solder

Did you not read the entirety of my pr and comments? I want this for synth, synth synth synth synth synth

**Comment by chizzy376** [comment]
SYNTH CAN'T WEAR MODULES LAST TIME I CHECKED

**Comment by Coastfront** [comment]
Brute and burn kits are both limited, and do not heal every damage type at once. However they do last awhile.

Synth gets the giga blowtorch, the best backpack in the game, pouches, etc. I have played synth. Frequently. 
If you are taking damage/in combat so often as the strictly support oriented role to the point where you are running out of healing supplies, then you are combat synthing which is mechanically punished by having both 0 armor and 0 guns.
The one least negatively impacted by this is synth.

An ant weeps fore a landscape dotted with tattered hills, as an eagle casts itself down a ravine for a single stem-snapped feather.

Synth neither has reason to need to heal extremely often, nor even to be on max hp 100% of the time (I have very often gone 5+ minutes without break to heal myself while on half hp from just being busy) and has the storage capacity to easily support literally just bringing 1-2 cable coils or nanopaste.

**Pull request closed without merging**
