### PR TITLE
Removes wallpiercing from mech railgun

### PR DESCRIPTION
**Pull request by GravitronBlue**
## About The Pull Request

Removes wall piercing flag from mech railgun ammo.

## Why It's Good For The Game

Akimbo railguns with infinite free ammo  with 15 round mags is and continues to be a terrible design.
(Normal railgun rounds cost 2 req points each)

## Changelog

:cl:
balance: Mech railgun no longer shoots through walls
/:cl:

Given the growing list of broken mech metas, balance, and mechanics I'd frankly prefer a temporary full mech removal like #11723 until someone goes over the current issues. Mainly mech spam, disposability, and zero effective cost. For now this PR just addresses another symptom of broken mech metas.

### CODE REVIEW

**Comment by Naaanii** [comment]
While I support this. The wall pierce is intended.

What isn't and the real bug behind the issue is the instant reload making it spammable and deadly when it should only be firing once for a decent amount of time. Fixing the reload bug would be better but I don't see any fixes being made for the foreseeable future.

**Comment by GravitronBlue** [comment]
> The wall pierce is intended.

Until it costs 64 req points (The cost of 32 railgun shells) to arm a mech with two railguns I don't see why or how it's intended.

No other weapon of this kind simply has completely free ammo, TAT, howe, mortar, and most req guns might all come with a free starting supply but there's still a cost if you want more.

Mechs continue after 2 months to ignore this limitation or cost balance.

**Comment by SilencedMP5A5** [comment]
salt PR because of the denholm thermals incident

**Comment by GravitronBlue** [comment]
BraveMole commented:
> You are free to make balance change to mech. Maybe try before doing a full removal

_Make one PR nerfing the most broken of the mech guns_

SilencedMP5A5 commented:
> salt PR because of the denholm thermals incident

Which is it?

Considering you already saw how powerful the mech railgun is I suggest you stick around to see more of the same, because this has been the case every round today.

**Review by RipGrayson — APPROVED** [review]

**Comment by RipGrayson** [comment]
Walance maintainer approved, will be merged in 24 hours unless another maintainer wants to chime in here.

**Comment by Naaanii** [comment]
> > The wall pierce is intended.
> 
> Until it costs 64 req points (The cost of 32 railgun shells) to arm a mech with two railguns I don't see why or how it's intended.
> 
> No other weapon of this kind simply has completely free ammo, TAT, howe, mortar, and most req guns all come with a free starting supply but there's still a cost if you want more.
> 
> Mechs continue after 2 months to ignore this limitation or cost balance.

Fair, but the damage and instant reload is still going to be there.

**Pull request merged**
