### PR TITLE
More armor and no more Squad markings on armor

### PR DESCRIPTION
**Pull request by Metroidlover**
## About The Pull Request

Kuro never rests, and I will match that if I can. More armor changes as well as proper Snow Variants.
Also, I fixed a few things with the Scout helmet's icon sprites.

Oh, and Squad marking on armor are gone now. 

_We may or may not be using the black ones for something later_

_Images to be added upon request_

## Why It's Good For The Game

I mean it's more sprites and sprite tweaks to already added sprites, so yeah.
We couldn't get the Squad Markings to play nice with the designs easily and the helmet markers, gloves, squad Hud and other things can fill the role just fine.
The Scout helmet's Base Icon Sprite had weird transparent shadows around it and was copied for the Snow variant, so I fixed that

## Changelog
:cl: Kuro & MetroidLover & Spyroshark
del: Removed Squad markings on armor suits
fix: fixed the Scout Helmet's Icon Sprites
imageadd: added some new Helmet Sprites and Snow Variants for the recently added armors
imageadd: New sprites, again. Some new colorings aswell.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
Why was the squad overlay removed? Out of curiosity.

**Comment by Metroidlover** [comment]
Kuro couldn't get it to look nice with his armor sprites, so he said it would be better for it to go

**Comment by Spyroshark** [comment]
Why not just add helmet variants for each squad?

**Comment by spookydonut** [comment]
Players rely a surprising amount on armor squad stripes

**Pull request merged**
