### PR TITLE
Makes the AI able to use sentries again

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
This Pr allows the AI to properly interact with sentries. The amount of things you can do is still very limited, but at least you can stop people from forgetting radial or something.

## Why It's Good For The Game
One step closer to shodan. Lowers the impact of bad engineers.

## Changelog
:cl:
qol: made it possible for the AI to actually interact with sentries.
/:cl:

### CODE REVIEW

**Comment by GradusNL** [comment]
This isn't QoL, it's balance. You admit it yourself when you say this "lowers the impact of bad engineers". Not giving the AI the ability to interact with turrets was a very deliberate balance decision IIRC, but I'm not going further into that since this is a balance PR during the balance freeze.

**Comment by lbnesquik** [comment]
> 
> 
>  Not giving the AI the ability to interact with turrets was a very deliberate balance decision IIRC

I am not sure who has intended anything regarding the AI. We don't have a creative director with a clear plan for AI as far as i know.

**Comment by GradusNL** [comment]
> 
> 
> > Not giving the AI the ability to interact with turrets was a very deliberate balance decision IIRC
> 
> I am not sure who has intended anything regarding the AI. We don't have a creative director with a clear plan for AI as far as i know.

Maybe I remember it wrong then, but I thought that not having the AI be able to use turrets was either involved with the groundside AI access or one of the sentry reworks as a balancing thing. Not that it matters much, since BM told you to ignore it anyways. Nothing wrong with it being judged on it's own.

**Comment by David-Stormwell** [comment]
It is balance, not sure why this has QOL tag, but neither the less approved balance, as if anyone goes AI or even has much to do besides spam the battle droid buttons.

**Review by BraveMole — COMMENTED** [review]
David said yes

**Pull request merged**
