### PR TITLE
Placed AI nodes, fixed some messy things

### PR DESCRIPTION
**Pull request by KwinOriginal**
## About The Pull Request

Placed AI nodes and fixed some wrong tiles on good old WO

## Why It's Good For The Game

FRICKING WO, MAN!
## Changelog
:cl:
add: AI nodes
/:cl:

### CODE REVIEW

**Comment by KwinOriginal** [comment]
> Remove the backup file `_maps/map_files/Whiskey_Outpost/backup/Whiskey_Outpost_v2.dmm`

Should be gone now

**Comment by psykzz** [comment]
@KwinOriginal is this ready to merge?

**Comment by KwinOriginal** [comment]
> @KwinOriginal is this ready to merge?

It is in theory but I have to adjust some things, so give me a day or two more. That'd prevent that there'll be another PR soonish

**Comment by psykzz** [comment]
Poke me to remove the DNM

**Pull request merged**
