### PR TITLE
Adds knight armor

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds knight armor to the marine vendors
image
image
image

## Why It's Good For The Game
Because it's dripped up to the roof, and I'm drowning.
## Changelog
:cl: @Xander3359 @KillerOrcaCora 
add: Knight armor to the marine armor vendor.
imageadd: Knight armor mob sprites, helmet item sprites.
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]
did you really not have better names for them

**Comment by KillerOrcaCora** [comment]
image

**Comment by blackdav123** [comment]
call it the XLC-OR Heavy Armor (Excelsior)

**Comment by Kuro020** [comment]
Upon further thought I have decided that I want to be 1984 again

**Pull request closed without merging**
