### PR TITLE
New bull charge action icon

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title. 'nough said

## Why It's Good For The Game

Bull uses crusher's charge action icon, which I always find wack. My coderspriting skill permits me to make a new action icon for bull. Now bull can admire their charging icon without having to think, "Why do I have a crusher on me?"

## Changelog
:cl:
soundadd: bull charge action icon; that's it
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
image

**Comment by Lumipharon** [comment]
Makes sense for it to have a different icon since their charge abilities don't work the same. Where as queen primo charge (I think?) is functionally just crusher charge.

**Comment by novaepee** [comment]
> Makes sense for it to have a different icon since their charge abilities don't work the same. Where as queen primo charge (I think?) is functionally just crusher charge.

I am now compelled to give queen a charge icon.

**Review by TiviPlus — APPROVED** [review]
kuro pr

**Review by Kuro020 — APPROVED** [review]

**Pull request merged**
