### PR TITLE
MR loadout vendor for prep, need it to be mapped later.

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
adds a MR loadout vendor for prep
with the following list of things

image
image

CHANGES made to abide discussion ongoing. this is now restricted to **Medical RESEARCHER**
some proof and the things two in one

## Why It's Good For The Game
a more streamlined way to get Researcher their stuff. also with more personalized experience, and more versatiles loadouts for those in field surgery or shipside maintaining 

ALSO hopefully gives MR more stuff to play with and a higher reason for existing

## Changelog
:cl:
add: MR vendor 
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Chaznoodles** [comment]
Opposed to this. Gives yet more free meds to the people who already have unending meds, and as JPR put it, "in practice, it's gonna end up being a vend stuff and give it directly to ungas roundstart thing".

**Comment by fernandos13** [comment]
how about it being limited to MR. (since at the moment MR is basically the role that got nothing going for it)

**Comment by fernandos13** [comment]
fuck wrong button

**Comment by fernandos13** [comment]
so tending to this PR further
as is. MR is for medical the same CL is for Command
one could argue hes even LESS than a CL "since CL at least get the exclusivity of FAX"

so this PR should shiny some love in the MR, helping him to get a push on its OWN vendor. at the moment we dont really have exclusive mechanics. and with the death of capture not even the "rise a hive" in shipanymore

so this should at least help us adding a way to deliver new stuff to MR and helping him either deploy or having special gear to move about.

would be cool if later we added stuff like the syringe gun for him. or other RsR related gear. maybe experimental limb printer? a portable yet working printer. that lets you get limbs in the field. at the cost of phoron or even larva/dead face huggers

**Comment by revelation-8468** [comment]
You can literally get 90% of what's in this vendor by just playing the round and/or learning how to do chemistry. Doesn't seem at all needed.

**Comment by fernandos13** [comment]
`You can literally get 90% of what's in this vendor by just playing the round and/or learning how to do chemistry. Doesn't seem at all needed.`
that could be said about the marine vendors too, and many others in fact. i mean its not to give MR something unique as of now
is to make its life during prep easier.

**Comment by TGCMbetcher** [comment]
> Opposed to this. Gives yet more free meds to the people who already have unending meds, and as JPR put it, "in practice, it's gonna end up being a vend stuff and give it directly to ungas roundstart thing".

If marine were given a fair fail rate with syringes, say 30% chance of 20 brute and have to do it again, and then hypos were job locked to medical this wouldnt be an issue. Pills are easy you throw it in their mouth. Syringes are hard, hypos are expensive. Then its a hand to corpsman at most vendor and will let doctors deploy if there arent enough of them to man the FOB.

**Comment by TGCMbetcher** [comment]
> how about.. i speed up syringes for doctors. make it as fast as pilling. and move everything thats hypo/syringe based in the vendor to bottles?

I men it sounds like if you get rid of the chems everyone would be fine with it. Take the amount of points required for surgical trays again from the round start req points and then make it a surgery vendor for points. Then they can still get the armor/clothes they want and the tools for their job. No extra chems, nothing to give to ungas, still have a nice vendor that gives them what they need.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
The clothes should be in the uniform vendor and medics have enough meds

**Comment by fernandos13** [comment]
new changes made so you cannot get meds from it. just the basics surgery stuff and polyhex still

**Comment by fernandos13** [comment]
doesn have jaeger anymore

**Pull request closed without merging**
