### PR TITLE
Praetorian, Acid Splash replaced with Acid Gloom.

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

Replaces the boring ability Acid splash with Acid gloom.

## Why It's Good For The Game

Acid splash was the same stats as spitter except the puddle did 14 damage not taking acid armor into account meaning it probably did around 3-4 dmg a tick if someone stood on it, making it a very useless very BORING ability barely useful in sieges not befitting of a T3. 

Acid gloom adds an in-between of acid/light and acid/burn which makes Praetorian more focused towards area denial whilst not making it overpowered, does include clips/screenshot

## Changelog
:cl:
add: replacement ability for praetorian Acid Gloom.
/:cl:

image
Edit: fine tuned after extensive testing via local still needs tm testing

clips

How it looks

https://user-images.githubusercontent.com/64131993/155979880-3169116a-7d15-4649-a6dc-0a42b386f911.mp4

4 shots against a marine with heavy assault and Mimir 1's on helmet and chest which adds up to 76 acid armor

with mimi1

https://user-images.githubusercontent.com/64131993/156103099-c1b1aacd-124b-4e0e-9c0d-ec0a7de31ce2.mp4

Without Mimir same test
no mimirs

https://user-images.githubusercontent.com/64131993/156103169-4037e769-896d-4384-9900-a0eead6dd767.mp4

### CODE REVIEW

**Comment by ThelastArchiver** [comment]
does it also keep damaging cades? or is it only onhit damage now?

**Comment by Moggram** [comment]
> does it also keep damaging cades? or is it only onhit damage now?

It has the dame smoke effect as a boiler, so it should keep damaging cades. But boiler gas dose not do alot to cades anyway.

**Comment by vilereaver41** [comment]
> does it also keep damaging cades? or is it only onhit damage now?

It can damage cades but gas dmg on cades even boiler gas does very little dmg, iv shot 9 of these at a plasteel + gas and it didn't do much

**Comment by Moggram** [comment]
Hmmm.... At 80 plasma cost and 1/2 sec delay, you are going to run out fast. Drones are going get yelled at to give plasma and I like this.

**Comment by TiviPlus** [comment]
Powercreep, david agrees

**Pull request closed without merging**
