### PR TITLE
UGLs can no longer load Sticky and Impact nades.

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title

## Why It's Good For The Game
Less 100-0 combos. Regular nades give (slightly) more time for Xenos to react and seem a bit more fair.
Could also help bring back impact nades as the main issue was the UGL. (In the future) 

## Changelog

:cl:
balance: UGLs can no longer load Sticky or Impact nades.
/:cl:

### CODE REVIEW

**Comment by BonkaiB** [comment]
Normal nades out of the UBGL  IMO deal too little Damage AOE or incen wise since it's only just 2 nades. I think all this will do is push people away from UBGL and make it unused

unless i'm mistaken even with the extra fire from your main gun you aren't going to get a xeno near crit remotely nor will the slowdown be a bother unless you manage to knock them back towards you and if it's a prae, spitter or runner. Of which aren't just sitting still or giving you an opening to shoot ahead of them 

If it was just the impact nades i'd more than understand due to Impacts being instant on tile slowdown + damage but stickies i simply do not agree with their removal from UBGL

The entire reason why people choose the UBGL over say the mini-flamer or the various grips is due to the fact UBGL can take sticky grenades. If you want to make them less oppressive why not give marines overall less sticky grenades and give req the ability to make them or buy them in bulk. Make them Eco their grenades instead of spamming them out

**Comment by Derrick2Electricboogaloo** [comment]
> Normal nades out of the UBGL IMO deal too little Damage AOE or incen wise since it's only just 2 nades. I think all this will do is push people away from UBGL and make it unused
> 
> unless i'm mistaken even with the extra fire from your main gun you aren't going to get a xeno near crit remotely nor will the slowdown be a bother unless you manage to knock them back towards you and if it's a prae, spitter or runner. Of which aren't just sitting still half the time or giving you an opening to shoot ahead of them
> 
> If it was just the impact nades i'd more than understand due to Impacts being instant on tile slowdown + damage but stickies i simply do not agree with their removal from UBGL
> 
> The entire reason why people choose the UBGL over say the mini-flamer or the various grips is due to the fact UBGL can take sticky grenades. If you want to make them less oppressive why not give marines overall less sticky grenades and give req the ability to make them or buy them in bulk. Make them Eco their grenades instead of spamming them out

I think making marines have less is a better solution.

**Comment by Losenis** [comment]
Imagine using UGL for damage instead of the knockback + weedclearing + slowdown

**Comment by Strayed-Raven** [comment]
Marines dont even have access anymore to impact nades?? Also the sticky nades were a compromise to funny impact nades. So it still can't be accepted and removed. heh.

**Comment by srxtreme** [comment]
Noo my 1.5 second oneshot combo how will I get marine majooors now?

**Comment by Naaanii** [comment]
> 

Funnily UGLs should've been 1 nade but unsure how lowering the amount solves the issue of it being a 100-0 gun in several scenarios even at a range. This seems like the best balance solution till nades themselves can be adjusted or UGLs can have their own specific nades.

Alternatively I could just add a delay but then all nades would be underwhelming.

**Comment by Pariah919** [comment]
Seems good to me. Run a dedicated GL to use sticky nades.

**Review by RipGrayson — APPROVED** [review]
Ambivalent towards this change, but sure

**Comment by Lumipharon** [comment]
This will fug half the hvh marine loadouts and pmc leader. Also I'd rather just tweak the nades themselves, but that's more effort.

**Comment by Naaanii** [comment]
I can adjust the loadouts to use regular nades.

**Pull request closed without merging**
