### PR TITLE
MPs available on distress/nuclear war

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
Still needs some content related work but it shouldnt blow up in anyones face anymore

## Why It's Good For The Game

Woo new job

## Changelog
:cl:
add: Mechs are now available ingame
add: MPs may pilot mechs, in order to be one you must have the same amount of playtime as for captain (15 hours)
add: Mechs are tanky and pack a decent punch but are slow and cannot turn instantly. Targetting left/right arm when attacking them can also disable their weapons. Attacking from behind deals extra damage attacking from front less
fix: fixed MP not being visible on minimap
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
ITS HAPPENING

**Comment by srxtreme** [comment]
powercrepe

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 0c19629ac043c6320b1b363608067f791d618c66
Pull Request: 91cc309b623ea746cb2c657369e892fd4da3e772
Server: 860083ac405d81ad7bd7d01c6aca22a496f0248a

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 1a7897fb75c0bc591fc470eeb19602cedd44f913
Pull Request: 91cc309b623ea746cb2c657369e892fd4da3e772
Server: 39862f7d553c85a605709fa41bd5380a2f39c840

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by Losenis** [comment]
MP slots seem bugged

https://github.com/tgstation/TerraGov-Marine-Corps/issues/11401

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 48bb57ab23241cd1fe25e1c80ec1cfa43da71592
Pull Request: 91cc309b623ea746cb2c657369e892fd4da3e772
Server: 9eda513e79e9a6a25c9ef0ba9b659d01bc276131

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 48bb57ab23241cd1fe25e1c80ec1cfa43da71592
Pull Request: 91cc309b623ea746cb2c657369e892fd4da3e772
Server: e5943caf779b3b116338f723ad981803b280edd2

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by Ben10083** [comment]
> MP slots seem bugged
> 
> https://github.com/tgstation/TerraGov-Marine-Corps/issues/11401

Should be fixed by #11421

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
