### PR TITLE
Standardizes OB rooms on all shipmaps

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
title
## Why It's Good For The Game
Sucklaco moment. Turns out sulaco and thesus just got four extra OBs for completely free (???)
also gives every shipmap the same amount of solid fuel (35)
## Changelog
:cl:
balance: Standardizes shipmap OB and solid fuel count
/:cl:

### CODE REVIEW

**Comment by RipGrayson** [comment]
Christmas shipside freeze is in effect, wait until December 31.

**Comment by yyzsong** [comment]
> Christmas shipside freeze is in effect, wait until December 31.

it hasn't even been thanksgiving 
hampter

**Comment by RipGrayson** [comment]
> it hasn't even been thanksgiving hampter

Christmas PR goes live around the start of December, about 12 days. Any shipside map changes causes merge conflicts, which means all new features/landmarks have to be redone for each shipside PR merged.

Your PR won't stale out, I'll keep it open until merge time.

**Comment by Strayed-Raven** [comment]
Didn't someone already try this and it was explained why it was the way it was?

**Comment by coldironwarrior** [comment]
muh OB rooms!!! 
all honestly, probably good since the fuel amounts don't equal the OB amounts either

**Comment by yyzsong** [comment]
> Didn't someone already try this and it was explained why it was the way it was?

I've got no idea and they were probably wrong anyways.

**Comment by lbnesquik** [comment]
Why not increase the other ships OB's instead?

**Comment by dopamiin0** [comment]
> muh OB rooms!!! all honestly, probably good since the fuel amounts don't equal the OB amounts either one use of each OB at randomized amounts would be 36 fuel though, i think 🐹

that'd be two uses of each ob. one use of each is 18. (3+4+5+6)

**Comment by yyzsong** [comment]
Endraftening this until christmas is over

**Pull request merged**
