### PR TITLE
Fix reverse grip in vali sword on right hand

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title

image

## Why It's Good For The Game

Not intentional. Maybe one day, we will let vali users go reverse grip.

## Changelog

:cl:
fix: reverse grip in vali sword on right hand

/:cl:

### CODE REVIEW

**Comment by Tupinambis** [comment]
anime protag cosplay nerf

**Comment by Xander3359** [comment]
Salt PR?

**Comment by Starfirejordan** [comment]
Salt PR?

**Comment by FIXTHERADBOXPLEASE** [comment]
Why though. It looks cool.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
