### PR TITLE
Needed (removed two names)

### PR DESCRIPTION
**Pull request by XSlayer300**
## About The Pull Request
Because.

## Why It's Good For The Game
No accidental namechecking to see if it is not allowed

## Changelog
:cl:
del: Removed some names in the last name list.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -8. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by XSlayer300** [comment]
wow r00d

**Comment by RenGusta** [comment]
>leaving trudeau

**Comment by XSlayer300** [comment]
whot the heck is that

**Comment by MLGTASTICa** [comment]
When are we purging the name of everyone since theres always someone a politician named like a name ?

**Comment by sunofang** [comment]
This is a good change that removes politics

**Comment by Tennessee116** [comment]
Not sure why these obvious political inserts were shafted in at any point to be honest.

**Comment by XSlayer300** [comment]
> Not sure why these obvious political inserts were shafted in at any point to be honest.

Likely because of #3665

**Comment by TiviPlus** [comment]
@XSlayer300 remove trudeau and check for goebbels too if you dont mind

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
