### PR TITLE
Chigusa Removal

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request

Removes Chigusa as a selectable map.

## Why It's Good For The Game

Grayson himself has noted that this map is not good for TGMC, and is willing to remove it; feel free to discuss this in the comments.

## Changelog
:cl:

del: Removed Chigusa from selectable maps.

/:cl:

### CODE REVIEW

**Review by RipGrayson — APPROVED** [review]
Approved, one week until this is merged. Discuss the merits of this approval and I might save it or cut the time until merge down some.

**Comment by RipGrayson** [comment]
Putting this on DNM until a week is up

**Comment by Overdrive659** [comment]
I could try remake Chigusa as i did with magmör. But I'll have to take on that task after my finals💀

**Comment by Aporhtonoma** [comment]
merits of removing chigusa :no more chigusa
chigusa is no longer a part of rotation
chugusa is not longer part of the selection
demerits:
the 2 chigusa fans will be shattered


good riddance unless someone wants to rework it (like magmoor)

**Comment by Lumipharon** [comment]
Why'd you wait until after I smacked my head on the table for an hour replacing all the platforms? Guh

**Comment by BlueHNT** [comment]
Pluses and Minuses?

In my opinion, the map itself is not inherently bad, but it does give Xenos a fair bit of playground which leads to Captain and FC having to devise a smart plan to work instead of rush silo and hope we don't die number26479.

It also forces the marines to use teleporter gear for once which I find amusing.

The back and forth can be mitigated a bit by giving Marines loot centers on the planet with mats and gear so they have something to work for and Xenos defend other than nukes. [not accessible by Xenos] If they were to manage to get these it would stop the back and forth with them being able to use it somewhat like a mostly safe place for a little bit.

Off course it would still not solve the fact that Xenos can just ignore them and go siege FOB.

Overall this map needs some creative ideas to balance out the back and forth without making either side decisively overpowered and it, just can't work as it is now.

**Comment by FIXTHERADBOXPLEASE** [comment]
It's useful to have exist for when the pop is hyper-inflated. It doesn't need to be constantly played to have merit.

**Comment by RipGrayson** [comment]
> It's useful to have exist for when the pop is hyper-inflated. It doesn't need to be constantly played to have merit.

If low playtime was grounds for removal then a lot of maps would be removed. The Chigusa removal is approved because it's a horrible map and not getting any better, not because it's infrequently played.

**Comment by isotope436** [comment]
finally a good pr

**Comment by RipGrayson** [comment]
chig

**Pull request merged**
