### PR TITLE
Removes Synthetic as a job

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Removes synth as a pickable job, the race, skills and most things not related to it being a marine job still exist in the code, but the preferences and references are removed.
I still need to get rid of it on shipmaps.
## Why It's Good For The Game
Synth is a terrible role that encourages powergaming behavior to get around the issue of having the inability to fight, you can do surgery and hold the entire marine forces support by yourself, considering most support staff basically have the inability to fight anyway it doesn't make sense that the tradeoff is that you can't use guns when *that already barely matters*.
## Changelog
:cl:
del: Synthetic has been removed as a pickable job. The race still exists in the game, but is admin only.
/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
What?

**Comment by Naaanii** [comment]
Basado.

Captain surgery skill when?

**Comment by Derrick2Electricboogaloo** [comment]
That is kind of the purpose of synth. To be the ultimate support role, it is not a fighting role.

**Comment by Loldaddy5676** [comment]
thats...... the point of synth???
improve dont remove or somthing idk

**Comment by Neocloudy** [comment]
A better salt PR idea would've just been, making synth do shit melee damage [worse than it already does given its slow speed with most of the powergame loadouts]

**Comment by Strayed-Raven** [comment]
I love seeing what the BINGO results are for the next 'Do a PR for the sake of making a PR' event. Sad to see Synth came up

**Comment by Loldaddy5676** [comment]
> i have something else in mind now
is this what you had in mind?

**Comment by Losenis** [comment]
>The job that can't use guns, can't run, can get permacrit, can't wear 99% of armors, is focused by any xeno with frontal lobe development, and is generally thrown around by ungas to do req or whatever else due to having all access is the role that encourages powergaming

Salt PR?

**Comment by Zambie-Tron** [comment]
image

**Comment by lKiseki** [comment]
nick-young

**Comment by Coastfront** [comment]
Synth is the least viable support role for combat, infact the disparity between even a normal researcher vs a synthetic in terms of combatitive ability is obscene.

Synthetics are slow, fragile (light armor) and constrained to exclusively fight on xenos terms (melee only.) They arent resistant to stuns, nor do they have no-crit from combat robots and neither do they benefit from chems. Infact, they dont even get crit oxyloss and can be dragged back to hell if they get critted by any caste in combat.
Their main (only) strength in combat is the fact that they have slight speccies armor, and deal slightly more melee damage.

Comparatively, even a researcher (who can ALSO do surgery, just not as quickly) with medium armor, shield + any melee weapon is already both more durable in melee combat, and doesen't suffer from brazil critdrag. Not even taking into account premedding which humans can do, or if they go crobot to just not have crit. 

Any xeno who pins their failings against a combat synth upon the balance of the game would likely do the same against an ob as they hesitate in its center.

Synth is the strongest support role in the game skills wise, and while it is difficult to permanantly knock them off the roster, it is both doable (brazil dragging, etc.) and possible to massively inconvenience them by harassing them during surgery.

Also, it is outright a lie to say that a synth, alone, can support the entire marine push. There is generally only ever 2 tops, surgery is still, though lesser, time consuming. I have even experienced, playing synth, the nightmare that is "all of the medics died and researchers arent doing groundside surgery either." where you get bogged down by having to revive 3 people at once, remove a larva, AND fix somebodies 120 organ damage that you might not even have peri+ for.

Synth aswell, is only as effective as the marines are. If the marines are squandering its healing speed by just getting fucking maimed constantly, the synth will be tied up fixing the same 3 people over and over while trying to fix everyone else.

An omnitool fills little of a toolbox by itself. If the other support are dead/incompetant/incapacitated/nonexistant, synth starts to struggle when marines eat shit due to being ONE GUY.

**Comment by HenryOfSkalitz** [comment]
You can't be real, man, you can't be REAL. This is FAKE. SICK joke. UNREAL. ABSOLUTELY. My man SYNTH was TOO POWERFUL that he is being REMOVED?!

DuDE?!
POweRGAmIng?
Synth is POWERED, he is a ROBOT FRIEND who can be CRITTED unlike, for example, BOBOTS, who exist until they straight up DIE.
Synth's damage income multiplier affects only brute, and the only viable armor he can use has MINIMAl acid resistance. Paradoxally, SYNTH is more vulnerable to burn (acid) damage even MORE than actual robots who were DESIGNED to suffer more from acid for a balance.

CSE is a Synth minus the medicine, CSE is even better in some cases thanks to the command
Captain is the Ultimate Support and Ultimate Commander of the Ship, Synth is the fren on both sides he feels comfy with
Not get me started on the fact that Synth, my boy synth, was nerfed SO HARD in his life and is still fun thing.

Name me ONE xeno who got insanely mad about Synth. 

Combat Synth is not even reliable since they are, again, ultimate SUPPORT - they can tank some damage, they can scare off some unrobust/non-combat benos, they can rapidly evacuate, bodyblock, ASSIST on the battlefield much more effective than anyone thanks to his unique weaknesses and powerful points. Its THE POINT of SYnth - being ULTIMATE assistance tool, limited only to 1 per somewhat somewhat pops. You don't see two synths too often, and three synths is a legend I screencapped. 

The only point I can agree on Synth powergaming is MAAAYBE shield synth, but its the shield issue, not Synth issue

This is just a sick joke.

#FreeAleks

**Comment by FosterGrime-Heymynameslouie** [comment]
what?

**Comment by Pariah919** [comment]
I was given constructive criticism and decided on something else to do with synth

Also threats of violence 
image

**Comment by Ragecrabbo** [comment]
> Also threats of violence
 image
>
Should have speedmerged just for that image alone

**Comment by Alexeivichi** [comment]
Cringe PR.

Speedmerge IMMEDIATELY.

**Comment by Alexeivichi** [comment]
> Cringe PR.
> 
> Speedmerge IMMEDIATELY.

NEVERMIND IT'S CLOSED WHY LIVE

**Comment by Windryn** [comment]
#FreeAleks2023

**Comment by RaidarV** [comment]
#KeepTheTwinkImprisoned2023

**Pull request closed without merging**
