### PR TITLE
Mech can't be Plasmacut

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
No more qdelete. Self destruct button would be based.
## Changelog
:cl:
fix: Mech can't be plasmacut
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Salt PR?

**Comment by RipGrayson** [comment]
literally 1984

**Comment by Lumipharon** [comment]
Should probs just do damage, not qdel.

**Comment by Naaanii** [comment]
> Should probs just do damage, not qdel.

Why? Just use a machete or melee instead.

**Pull request merged**
