### PR TITLE
Adds contextual tutorials

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/72292/files basically, its very limited and bad rn but I intend to expand later
## Why It's Good For The Game
What if we taught new players how to play the game???????

## Changelog
:cl:
add: Adds contextual tutorials for picking things up, dropping them and swapping hands
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
DNM until DB update

**Comment by Jackal-boop** [comment]
Is this also going to have steps for acquiring a weapon and other basic actions

**Review by Lumipharon — APPROVED** [review]
Very cool addition, hopefully we can get a bunch of tgmc specific stuff loaded in later.

**Comment by optimumtact** [comment]
```
MariaDB [tgmc]> 
MariaDB [tgmc]> INSERT INTO `schema_revision` (`major`, `minor`) VALUES (2, 2);
Query OK, 1 row affected (0.001 sec)

MariaDB [tgmc]> CREATE TABLE `tutorial_completions` (
    ->   `id` INT NOT NULL AUTO_INCREMENT,
    ->   `ckey` VARCHAR(32) NOT NULL,
    ->   `tutorial_key` VARCHAR(64) NOT NULL,
    ->   PRIMARY KEY (`id`),
    ->   UNIQUE INDEX `ckey_tutorial_unique` (`ckey`, `tutorial_key`));
Query OK, 0 rows affected (0.033 sec)

MariaDB [tgmc]> describe tutorial_completions;
+--------------+-------------+------+-----+---------+----------------+
| Field        | Type        | Null | Key | Default | Extra          |
+--------------+-------------+------+-----+---------+----------------+
| id           | int(11)     | NO   | PRI | NULL    | auto_increment |
| ckey         | varchar(32) | NO   | MUL | NULL    |                |
| tutorial_key | varchar(64) | NO   |     | NULL    |                |
+--------------+-------------+------+-----+---------+----------------+
3 rows in set (0.002 sec)
```

**Pull request merged**
