### PR TITLE
LMG now has better aim mode stats.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Identical to the T-12 (.1 extra fire delay and 2 aim speed modifier)

## Why It's Good For The Game
Its a T-12 sidegrade in design and there's absolutely no reason it should have worse aim stats than its Assault Rifle cousin.

## Changelog
:cl:
balance: LMG now has identical aim mode stats to the AR, which ends up as a buff, aim mode fire rate stat buffed from .2 to .1, and aim slowdown from 5 to 2. Tottaling to .3 fire delay and 2.85 aim slowdown in total.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
bad change, unlike the AR,  the LMG has 100+ rounds to fire and can be done so for a very long time.

**Comment by Losenis** [comment]
>100+ rounds

It's still a sidegrade given you can't store ammo on the ammo belt and need the 3-slot G8 belt for it. Actual ammo count would be similar given for the T12 you'd also be packing ammo boxes to refill the mags if you wanted longetivity anyway, as a full backpack would net you 1200 rounds of it if you're not going for the dedicated box with 12x24mm box.

And that's if there isn't an RO to drop you a full ammo box of T12 mags which renders the argument entirely irrelevant. If you know how to tacreload, ammo count of a drum is irrelevant if you can just reload the T12. Source: Ran loadout with RDS Bipod Barrel charger T12 with big 10x24mm ammo box on backpack slot for a while.

**Comment by Tailiik** [comment]
Even with tac reloads it still gives xenos a window to attack you with your gun announcing that you're almost out of ammo by the sound changing. Eliminating that lets you just hose, and you can stack a bunch of marines on top of each other with aim and npc spray for days if you have a box of ammo on the ground. 

I think smoke should break the aim mode on projectiles that go through it or something since it's "aiming" not iff tech, but that's a whole other story.

**Comment by Losenis** [comment]
>Even with tac reloads it still gives xenos a window to attack you with your gun announcing that you're almost out of ammo by the sound changing

You are aware of how stupidly slow the MG42 fires on aim mode, right? Even if you take into account a slow tacreload the AR12 still has thrown more bullets downrange than the MG42.

And the window to attack you is as irrelevant as people irl saying the M1 Garand's ping would just alert the enemy that you're out of ammo. The actual window of opportunity to attack allows the xeno to move 2 tiles or so if even that at high TD, any wider window of opportunity is 100% skill issue on lack of tacreloading practice.

The AR12's aim mode stats make it it a better LMG than the actual LMG.

>and you can stack a bunch of marines on top of each other with aim and npc spray for days if you have a box of ammo on the ground

Irrelevant considering that not only you'd not go for those guns and would rather pick a T60, you'd also go for bipod and RDS that cancel out the aim mode debuff in the first place.

**Comment by Al-1ce** [comment]
Me shamelessly buffing the gun I main.

Jokes aside, the GMPG or whatever it is seriously sucks on aim. +1 from me.

**Comment by Lumipharon** [comment]
Aim mode is inherently far worse on autofire weapons as opposed to burst weapons due to how its applied. So even with the same aim mode penalties, t12 is still far better on aim mode than the autofiring t42.

**Comment by Tailiik** [comment]
> > Even with tac reloads it still gives xenos a window to attack you with your gun announcing that you're almost out of ammo by the sound changing
> 
> You are aware of how stupidly slow the MG42 fires on aim mode, right? Even if you take into account a slow tacreload the AR12 still has thrown more bullets downrange than the MG42.
> 
> And the window to attack you is as irrelevant as people irl saying the M1 Garand's ping would just alert the enemy that you're out of ammo. The actual window of opportunity to attack allows the xeno to move 2 tiles or so if even that at high TD, any wider window of opportunity is 100% skill issue on lack of tacreloading practice.
> 
> The AR12's aim mode stats make it it a better LMG than the actual LMG.
> 
> > and you can stack a bunch of marines on top of each other with aim and npc spray for days if you have a box of ammo on the ground
> 
> Irrelevant considering that not only you'd not go for those guns and would rather pick a T60, you'd also go for bipod and RDS that cancel out the aim mode debuff in the first place.

Except we're not talking about real life gun myths we're talking about 2d spaceman where you can very clearly hear the firing sound change as marines near empty and benos can and should punish that.

**Comment by Losenis** [comment]
Skill issue, tacreload faster.

**Pull request merged**
