### PR TITLE
Autosniper now has a ammo packet

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Box, so normal sized.
20x5 so 100.
50 points.
image

## Why It's Good For The Game
Autosniper now has an ammo packet, which allows it to have better ammo economy in general.
## Changelog
:cl:
add: Autosniper now has a ammo packet available to be bought in req.
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Comment by chizzy376** [comment]
Isn't it still more point effective to just buy the reqtorio ammo refill instead?

**Comment by Autisem** [comment]
> Isn't it still more point effective to just buy the reqtorio ammo refill instead?

The point of reqtorio was putting more effort in exchange for slight point discount. all the reqtorio is more point effective the investment comes in having to set it up

**Review by Lumipharon — CHANGES_REQUESTED** [review]
This is absurdly efficient. 20 bullets is 30 points, 150 is now 50 points. It's literally 5 times more effective.

**Comment by Pariah919** [comment]
> This is absurdly efficient. 20 bullets is 30 points, 150 is now 50 points. It's literally 5 times more effective.

TX8 ammo tin is same point cost for 25x5. I'll just reduce it to times 5 which is just 120.

**Pull request merged**
