### PR TITLE
Brings back all the pills

### PR DESCRIPTION
**Pull request by chesse20**
## About The Pull Request
i accidently deleted the ability to make 90% of the pills in the chemmaster whoops

## Why It's Good For The Game

because the chemmaster shouldn't be missing 90% of the pills because i messed up while changing the chemmaster code.

## Changelog
:cl:
fix: 90% of the pills are no longer missing from the chemmaster
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]
Fix your changelog

**Comment by chesse20** [comment]
like that?

**Comment by AndroidMK2** [comment]
Bruh moment

**Comment by TiviPlus** [comment]
> like that?

yea

**Pull request merged**
