### PR TITLE
Fix flak jacket accepting modules

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title. Sorry, synthetic players. Maybe we can make a dedicated synthetic armor that accept modules but give barely any armor. Food for thought.

## Why It's Good For The Game

Bug fix. One line change with null list.

The 6 months of bug abuse on flak jacket that synthetic players have used is no more. I recommend making a new armor for synthetic.

## Changelog
:cl:
fix: flak jacket accepting modules
/:cl:

### CODE REVIEW

**Comment by Mechanelize** [comment]
FEATURE

**Comment by Derrick2Electricboogaloo** [comment]
Omega no. I think it was Zack, maybe snyder that made them modular. Makes sense bearable if beans get their grubby claws on you. Since they removed uniform armor and bullet proof vest is just icky. It is not not being shot back by FF into the 'loving' arms of beanos. Also increases our utility having storage module on armor.

**Review by BraveMole — APPROVED** [review]

**Comment by Losenis** [comment]
Literally unplayable

**Comment by novaepee** [comment]
> Omega no. I think it was Zack, maybe snyder that made them modular. Makes sense bearable if beans get their grubby claws on you. Since they removed uniform armor and bullet proof vest is just icky. It is not not being shot back by FF into the 'loving' arms of beanos. Also increases our utility having storage module on armor.

It was me that accidently made them able to accept modules.

**Comment by Al-1ce** [comment]
> It was me that accidently made them able to accept modules.


Why not rebrand the flak-jacket to do exactly that? Give it a niche that other armors lack.

**Review by TiviPlus — APPROVED** [review]

**Comment by Losenis** [comment]
Whelp, synth gaming is dead.

**Comment by Al-1ce** [comment]
> Whelp, synth gaming is dead.

To be fair, they were aiming for the head anyways.

**Comment by thebestcodertoevercode** [comment]
rip my synth build, now the only other viable option is the suicide vest

**Pull request merged**
