### PR TITLE
Free sg kits in req vendor, linked to pop

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Give free sg kit, at the same rate that sg roles were added when marine are spawning

## Why It's Good For The Game

Marine could use a small boost in early game, and sg loadouts are cool. Spooky agreed with this

## Changelog
:cl:
balance: Give free sg kits in req vendor, at the same rate that sg roles were added when marine are spawning. 
/:cl:

### CODE REVIEW

**Comment by David-Stormwell** [comment]
Why not revert to how it was before?
I still think having a dedicated SG role is better instead of handing them out to marines.

**Comment by SplinterGP** [comment]
I prefer the SG role than free SG kits, this leads to basically people rushing to get the SG +not being able to know who has that important weapon

**Comment by lKiseki** [comment]
A lot of people would prefer the SG role back, and I believe that should be the solution.
This PR would promote rushing to get the SG kit first, other marines stealing some of the SG gear (see: SG NVG gear), among other things. Not a good solution, I would say.

**Comment by SplinterGP** [comment]
also one dude can just take all the ammo to theirselves, and the dude wont have the SG icon on them for the team to know

**Comment by BraveMole** [comment]
> also one dude can just take all the ammo to theirselves, and the dude wont have the SG icon on them for the team to know

It's req vendor. So ro

**Pull request closed without merging**
