### PR TITLE
Tadpole breacheable

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

You can now melt and destroy tadpole windows. Inner walls are also destroyable. Consoles inside tadpole cockpit are also passable 

## Why It's Good For The Game

Prevent tadpole blocking. Remove a lot of cancer tadpole position. Still takes a while to breach into tadpole

## Changelog
:cl:
tweak: Tadpole windows are breacheable
/:cl:

### CODE REVIEW

**Comment by revelation-8468** [comment]
Just get a wraith.

Wraith nullifies the tadpole completely anyway.

**Comment by Swagile** [comment]
tadpole is really good as a battle bus or else you die if you push past FOB if xenos know what they are doing

doing this will just destroy its purpose even more; tadpole isn't the issue, its miners right now thats the real issue and some mapping problems

**Comment by SplinterGP** [comment]
fun idea make tadpole a platform without walls but fully buildable

**Comment by davidchan13** [comment]
Removing tadpole's ability to be an impassable roadblock would be justification to buff it's other properties. The reason it's in such a sorry state right now is because map design allows it to park down in front of a cave or against indestructible terrain and completely block off xeno assault paths.

**Comment by SplinterGP** [comment]
> Removing tadpole's ability to be an impassable roadblock would be justification to buff it's other properties. The reason it's in such a sorry state right now is because map design allows it to park down in front of a cave or against indestructible terrain and completely block off xeno assault paths.

it has some other uses people dont use to, forward miners carry, getting hurt marines up from field etcetera.

**Comment by Swagile** [comment]
> 
> 
> > Removing tadpole's ability to be an impassable roadblock would be justification to buff it's other properties. The reason it's in such a sorry state right now is because map design allows it to park down in front of a cave or against indestructible terrain and completely block off xeno assault paths.
> 
> it has some other uses people dont use to, forward miners carry, getting hurt marines up from field etcetera.

I do this a lot as CPT or SL; using the Tadpole at the front to evac marines. INCREDIBLY useful on Magmoor NW Caves, Big Red Lambda pushes, and LV Tfort so that a retreating force doesn't just die on its way back to FOB.

**Comment by BraveMole** [comment]
closing it before git bot get me. You want have me this time!

**Pull request closed without merging**
