### PR TITLE
Add M10X reskin based off of MASKA-1SCh

### PR DESCRIPTION
**Pull request by irRegularGuy646**
## About The Pull Request

adds a reskin of the M10X helmet that looks like the russian MASKA-1SCh helmet
image
image
image
image

## Why It's Good For The Game

cheeki breeki iv damnke

## Changelog
:cl:
add: Added MASKA helmet "M10ASKA-1SCh"
/:cl:

### CODE REVIEW

**Comment by irRegularGuy646** [comment]
the "visor" (adidas stripes) currently aren't working for some unknown reason

**Comment by irRegularGuy646** [comment]
decided to just add a separate striped version instead, i can't figure out how to get the stripes to cooperate with hyperscaling

**Comment by Wisemonster** [comment]
Images of the sprites would be nice

**Comment by irRegularGuy646** [comment]
the Tyr helmet module takes up a module slot and also has a significantly different shape than a rectangular face shield

**Comment by irRegularGuy646** [comment]
you could also just notice that there's a different module's sprite?

**Review by TiviPlus — APPROVED** [review]
code ok

**Comment by Kuro020** [comment]
we already have tyr, which looks exactly like this

**Comment by irRegularGuy646** [comment]
it really doesn't + takes a module slot

**Pull request closed without merging**
