### PR TITLE
Doubles offensive ability cooldowns of Warlock

### PR DESCRIPTION
**Pull request by chizzy376**
## About The Pull Request
Doubles the cooldown of both psychic crush and psy blast for the warlock.
Before you call this ided, please read below.
## Why It's Good For The Game
As it stands right now, the warlock can extremely easily poke at any defensible marine position with 0 risk, given he isn't locked into any of his abilities for longer than half second with his beam ability which is a windup (And can still be walked out of casting I believe).
It isn't really fun for either side to be constantly harassed from offscreen when you can't do anything about it.
While I'm a fan of the caste's kit, being centered around warping the very energy around them to damage the marines, their offensive capability feels a bit too powerful considering they have a significant long range with their abilities.
We've already demonstrated we don't like off screens as we've been slowly but surely removing scopes from powerful weapons (RR, sadar, etc.) and this should hopefully help with that effort. 

This PR does not touch its shield ability, as it's a good escape+displacement tool when used right and it has a long cooldown already.
## Changelog
:cl:
balance: warlock offensive ability cooldowns doubled
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Warlock isn't offscreen dd, to normally cast spells he needs to see the turf he casts, and don't forget marines have a lot of stagger weapons, which will make him completely harmless.

**Comment by BoltedAirlock** [comment]
for context, warlocks current ability cooldowns are:
- six seconds for the psychic blast
- twelve seconds for psychic crush
- ten seconds for psychic shield
you can, very easily, combo a psychic blast into a crush then a third blast with almost no counterplay to put a marine close to crit because by the time you've started the crush attack there's about three seconds until the blast is ready to fire again, then you can float out of sight to rest for about five seconds before you can charge a second crush up and start the loop all over again. And, if they decide to try and chase you down, you can fling them back for a stun and knockdown with your shield before giving them another lance for their trouble, just in time for the crush cooldown to finish and restart the chain a different way.

**Comment by chizzy376** [comment]
> Warlock isn't offscreen dd, to normally cast spells he needs to see the turf he casts, and don't forget marines have a lot of stagger weapons, which will make him completely harmless.

His range + the fact that his psychic crush is an AoE that goes further means that he can very safely do so. Most stagger weapons lose their effectiveness at that range.

**Comment by usnpeepoo** [comment]
A single marine with slugs can completely counter and shut down a warlock. Grenades absolutely fuck it over as well. Warlock is not a caste that needs ifs abilities nerfed, for how fragile it is as a T3 I believe having shorter cooldowns is a good trade off.

**Comment by chizzy376** [comment]
> "offscreen" 

The non-primo laser can go through corners and offscreen as it has an AoE as well.

**Comment by SimplySmiley123** [comment]
> A single marine with slugs can completely counter and shut down a warlock. Grenades absolutely fuck it over as well. Warlock is not a caste that needs its abilities nerfed, for how fragile it is as a T3 I believe having shorter cooldowns is a good trade off.
> 
> Also I don't know why you're mentioning warlocks abilities being offscreen when it's AoE crush is the only warlock ability that would actually be "offscreen" but even then it takes a long ass time for it to reach maximum size, and all you have to do as a marine is just walk backwards to avoid it.

Shotgun? No, warlock has a shield to pull a "no u" on them.
Grenades? Probably, never seen one do anything to a warlock before they just, run away. Though I can imagine a well cooked grenade or someone with a nade launcher could do anything to the warlock.

**Comment by Arturlang** [comment]
Just keep in mind warlock can't actually outdamage heavy armor using marines if they premed, anyone with reasonable healing can just escape and heal up as a warlock will struggle to push someone. This really completely ruins a warlock's ability to kill anyone, further relegating them into a far slower siege role. Perhaps look at reducing structure damage instead or keeping this change and increasing damage dealt on mobs.

**Comment by TellyLsc** [comment]
> Just keep in mind warlock can't actually outdamage heavy armor using marines if they premed, anyone with reasonable healing can just escape and heal up as a warlock will struggle to push someone. This really completely ruins a warlock's ability to kill anyone, further relegating them into a far slower siege role. Perhaps look at reducing structure damage instead or keeping this change and increasing damage dealt on mobs. The biggest weakness to a warlock is multiple marines just running it down as it's rather slow, and can easily miss it's shield which has odd directional targeting.

What? The psylance has 50 AP (and 60 burn damage which is one of the MOST damaging per hit skill for xenos on top of burn being 1.2 pain) on its own already, that already negates most of heavy armor's energy protection, the other skills are harder to dodge just because of the extra slowdown from heavy armor as well, not to mention you have a harder time to "flank" the psychic shield because heavy armor slow.

**Comment by zzurge** [comment]
thank GOD

**Comment by Arturlang** [comment]
> > Just keep in mind warlock can't actually outdamage heavy armor using marines if they premed, anyone with reasonable healing can just escape and heal up as a warlock will struggle to push someone. This really completely ruins a warlock's ability to kill anyone, further relegating them into a far slower siege role. Perhaps look at reducing structure damage instead or keeping this change and increasing damage dealt on mobs. The biggest weakness to a warlock is multiple marines just running it down as it's rather slow, and can easily miss it's shield which has odd directional targeting.
> 
> What? The psylance has 50 AP (and 60 burn damage which is one of the MOST damaging per hit skill for xenos on top of burn being 1.2 pain) on its own already, that already negates most of heavy armor's energy protection, the other skills are harder to dodge just because of the extra slowdown from heavy armor as well, not to mention you have a harder time to "flank" the psychic shield because heavy armor slow.

Psylance is only on primordial, which you don't usually get, usually only if you're winning.

**Comment by Arturlang** [comment]
Plus this will also require the warlock to just... wait around for it's abilities to recharge, since you only have 3 abilities now with damn long cooldowns, and you're too slow to go around slashing marines while waiting for it like other xenos.

**Comment by Lumipharon** [comment]
Warlock is hard countered by stagger or grenades, or any rushes that gets past or around the shield for that matter. Literally 1 bro with a jetpack and shotgun wrecks it's shit.

**Comment by chizzy376** [comment]
We can agree to disagree :)

**Pull request closed without merging**
