### PR TITLE
no more backpack strap in mob sprite

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

image

more drip

## Changelog

:cl:
del: no more backpack strap in mob sprite
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Gross

**Comment by Strayed-Raven** [comment]
Go even further and make it a gray version of the lightweight combat pack

**Comment by FosterGrime-Heymynameslouie** [comment]
teenage mutant ninja turtles

**Comment by Blundir** [comment]
I agree with Lumi, backpacks look really weird without straps, fanny packs at this point

**Comment by KM-Catman** [comment]
Personally I hate the strap from the Satchels. Always just a random ugly line on my otherwise bright and colorful outfit.

**Comment by ClosetedSkeletonGH** [comment]
satchel strap was important for some of my outfits (IE the freelancer one), could it just be an enable and disable option on rightclick? Id love that since it can look very ugly on some armors, and amazing on others

**Comment by grinkgo** [comment]
why not make it toggleable like rolling up sleeves or unbuttoning jacket

**Pull request merged**
