### PR TITLE
Flamer changes

### PR DESCRIPTION
**Pull request by jroinc**
## About The Pull Request
 Changes flamers. Much higher firerate, lowered welding kit capacity.

## Why It's Good For The Game

Flamers are currently inferior to miniflamers in nearly every niche due to reload speed and firerate. This isn't really acceptable for a primary, so this changes that without significantly affecting the DPS. 

You still do roughly the same damage, but a miss isn't a "well fuck, guess I'm getting beat to shit", and you can reliably coat large areas. 

Also, being able to carry around 0.7 Welding Fuel tanks feels wrong so I lowered it to 0.5 Welding Fuel tanks (a 50% increase over a satchel full of fuel tanks) so that you might actually need to restock occasionally.

Also, given as we have 2 backpack tanks with the same capacity and stats, but different sprites, there's a clear niche to move one (ideally the standard pack) to the belt slot with ~350u (for a 50% increase over the 3 tanks you could normally hold there), but mobsprites are hard so I'll leave that to kuro. 

## Changelog
:cl:
balance: Lowered both flamer fire delays from 2 seconds to 0.4 seconds. 
balance: Lowered welding fuel backpacks capacity from 600 and 700 to 500 for both.
/:cl:

### CODE REVIEW

**Comment by davidchan13** [comment]
Can you fix the damn flamers to not solid objects like walls and and doors?

**Comment by jroinc** [comment]
> Can you fix the damn flamers to not solid objects like walls and and doors?

Nope!

What do you mean by "not" solid objects?

**Comment by davidchan13** [comment]
> > Can you fix the damn flamers to not solid objects like walls and and doors?
> 
> Nope!
> 
> What do you mean by "not" solid objects?

Not PASS THROUGH solid objects, seems my phone effed up and I missed it.

Basically if you stand next to a wall, be it resin, metal or an r wall, and click onto fog off war, you can go to the other side of the wall and see the flamer pass through the wall entirely.

**Comment by jroinc** [comment]
> > > Can you fix the damn flamers to not solid objects like walls and and doors?
> > 
> > 
> > Nope!
> > What do you mean by "not" solid objects?
> 
> Not PASS THROUGH solid objects, seems my phone effed up and I missed it.
> 
> Basically if you stand next to a wall, be it resin, metal or an r wall, and click onto fog off war, you can go to the other side of the wall and see the flamer pass through the wall entirely.

So, I'm not gonna address that in this PR as it's byond the scope (Badum-tish!) but I'll point out 2 cases.

Flamers can't shoot through metal walls at all, regular or rwall. I'll test that, but they shouldn't be able to. They CAN shoot through resin walls, which I find entirely reasonable as they're just firing over the walls and letting the napalm fall down.

MINIflamers are a whole different story. If you can see it with regular vision, you can flame it in almost all cases, which allows limited wallhacks.

**Review by Hughgent — APPROVED** [review]

**Comment by jroinc** [comment]
Oddly enough, this seems to not affect the fire delay. I'll look at this soon.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by jroinc** [comment]
oh god it wasn't ready.

IT WASN'T READY!

~eh, I'll just make a new one in a day or two, changes still good~

**Pull request merged**
