### PR TITLE
LV Edit & Tweaks

### PR DESCRIPTION
**Pull request by Alterist**
:cl:
tweak: opens a few paths in the fog on LV, removes vines on dense jungle tiles to make open paths clearer
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
I believe the fog was meant to intentionally delay marine contact with the hive. I'm perfectly fine with the dense jungle changes, but I'm not so keen on such a major change in the function of the fog.

**Comment by Rohesie** [comment]
It is true, that's the function of the fog. But it's also true that's a major disadvantage for the marines to be cut off from their supply lines. To re-purpose the fog into turning the area as a xeno chokepoint could be something interesting, but a lot should be considered. For example that marines can laze and shoot the tank through the fog.

**Comment by francinum** [comment]
There's a hole into the internal fog channel at 65,86. Seal it.

**Comment by Alterist** [comment]
fixed

**Comment by Kingtrin** [comment]
This PR has completely broken LV's balance. I understand fog is not a fun concept, but its even less fun for the xenos to be rushed down. Xenos cannot hold the chokepoint early on due to a lack of T3's and a weak queen, meaning it devolves into a cave rushing shitshow. Marines are now encouraged more than ever before to rush down the xenos and ignore everything else.

**Pull request merged**
