### PR TITLE
Standard Issue Incend Slugs

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request

see title

## Why It's Good For The Game

now you dont have to roll lootboxes to get your shitty meme shotgun shells anymore
the likelihood that these will affect balance in any way is tiny, absolutely miniscule, these things are garbage
i'd add a big box like the standard three have but that requires sprites and im really lazy

## Changelog
:cl:
add: incen slugs are now standard issue
/:cl:

### CODE REVIEW

**Comment by lovegreenstuff** [comment]
and before anyone says anything about "ohhh but what about underbarrel shotgun"
no these suck even in those like they have peepee damage and do less fire stacks than a thrown flare

**Comment by ilikesaying** [comment]
Underbarrels got nerfed anyways lol

**Comment by DeltaFire15** [comment]
> and before anyone says anything about "ohhh but what about underbarrel shotgun" no these suck even in those like they have peepee damage and do less fire stacks than a thrown flare

Incendiary projectiles deal 10 firestacks which is 2x those of a flare and 50% of the cap (provided no armor) Furthermore, their base damage is ~twice that of the magfed shotgun and 70% that of normal slugs. After 3 fire ticks, the fire DoT combined with previous damage will outperform base slugs (provided no fire armor, about 6 on xenos with decent-good armor). Besides that, a stack of 1 is already enough to suppress any pheromone effects.

**Comment by lovegreenstuff** [comment]
nerd.

**Comment by Lumipharon** [comment]
> and before anyone says anything about "ohhh but what about underbarrel shotgun" no these suck even in those like they have peepee damage and do less fire stacks than a thrown flare

underbarrel shotgun is garbage because PP is just better, except if you're using buck explicitly for stuns not damage.

Akimbo combat shotty is gonna be aids again if you do this tho.

**Comment by bluezorua** [comment]
if you are adding underused ammo types from req might as well throw in track shells

**Comment by Wayland-Smithy** [comment]
Akimbo slugs are already cancer, and this will just be a different version without stagger (still has knockback = 2, slowdown = 1) and added fire effects. IMO there are plenty of free fire sources already between PP, flamer, UBF, tx54, and nades.

That said I am all for this and the impact on the almighty winrates it will have.

**Comment by BraveMole** [comment]
No way

**Pull request closed without merging**
