### PR TITLE
New Tank Sprites

### PR DESCRIPTION
**Pull request by Arachnidnexus**
This will require **new code** to work because it has a separate turret and base. Moved vehicle related stuff to **icons/obj/vehicles** both to avoid clutter and also to have a folder for future ground vehicles such as the APC. This PR can be merged right now since it doesn't affect any tank sprites currently in use.

**Done:**
image

General
- minigun and cannon item icons
- support/secondary module item icons
- armor item icons (4+snowplow)
- treads item icon

EW
- base frame (+damaged)
- two turrets + shadows (+damaged)
- animated treads (+ broken)
- minigun and cannon (+damaged)
- support modules (+damaged)
- secondary modules (+ damaged)
- jungle/bread/ice/urban camos (base, 2 turrets, 4 armors)
- all armors, snowplow (+ damaged)
- hardpoint dmg overlays

NS
- north/south tank frame (+damaged)
- north/south turrets + shadows (+damaged)
- animated treads (+ broken)
- minigun and cannon (+damaged)
- support modules (+damaged)
- secondary modules (+damaged)
- jungle/bread/ice/urban camos (base, 2 turrets, 4 armors)
- all armors, snowplow (+ damaged)
- hardpoint dmg overlays

**For Future PRs:**
- add Manezinho's animations (currently .gif, convert and move to appropriate .dmi files)
- clean up item icons
- better damage overlays?
- more camo options
- decals
- autocannon primary (shorter, thinner barrel with bulky housing? near turret)
- joke camos such as cardboard camo

**Notes**

_Edit: Spoilers but nobody reads PRs anyways_
image

_Also reminder to self to name the jungle pattern Bimmer and the urban one Granite._

### CODE REVIEW

**Comment by ActualRory** [comment]
Loving the choice of turret and camo-pattern.
Turning out great so far!

**Comment by Arachnidnexus** [comment]
New tank is going to require a lot of overlays same as old tank. Order will probably be something like this with things left of < being underneath the overlay to the right of the <:

_base_
treads < tread dmg
tank < tank camo < tank dmg
dmg support module / support module < support dmg
armor <armor camo <armor dmg
turret <turret camo < turret dmg?
dmg secondary module / secondary < secondary dmg
dmg primary / primary < dmg primary
_top layer_

**Comment by Arachnidnexus** [comment]
image

**Comment by Rohesie** [comment]
Wooooooooooo

**Pull request merged**
