### PR TITLE
Adds 41 new sounds

### PR DESCRIPTION
**Pull request by drawsstuff**
Adds 41 new unused sounds for xenos and ungas alike.

:cl: Drawsstuff
soundadd: Added 41 new sounds from AVP (2010)
/:cl:

### CODE REVIEW

**Comment by tortellinitony** [comment]
What's the license on these sounds, though?

**Comment by drawsstuff** [comment]
same licence as the rest of the sounds, shamelessly stolen

**Comment by Qustinnus** [comment]
a lot of our audio is actually from FXhome which released them with a CCA license iirc

**Comment by Qustinnus** [comment]
I don't like adding things with no code.

**Comment by DominikPanic** [comment]
Current policy by ninja is to not merge PRs like this, try finding a coder that will help you implement the sounds.

**Comment by drawsstuff** [comment]
someone's be using my sounds,
ZOUNDS!

**Pull request closed without merging**
