### PR TITLE
Research Outpost Map

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Adds a new map, Research Outpost. Its a bit smaller than other maps but I made sure to put a lot of detail into it. I've tested it locally as much as I can and I am pretty sure I got it right as I've done this once before and I've looked at other maps to make sure I have everything needed.
image
image

I am expecting there to be a few issues with the map like any other major changes often have, but I've tested it thoroughly and I believe it will be very functional and enjoyable in its current state and I've squashed all of the bugs I can find.

## Why It's Good For The Game

A nice new map to play on.

## Changelog
:cl:
add: Research Outpost Map
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -4. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Isy232** [comment]
I had the file named as "research _outpost"
Note the space                           ^  
And of course it couldn't find the file.

**Comment by Isy232** [comment]
I forgot the / infront of the area
Should be:
/area/outpost/...
I did:
area/outpost/...

It still compiled locally but failed travis.

**Comment by Isy232** [comment]
NEVERMIND, I FOUND IT

So I was thinking that I shouldn't mess with the dme file and since there was an include list on maps I thought there would be one for areas.

A lot of wasted time wondering if I was searching the wrong things and thinking it may have been other issues, just added the include area thing to the dme file and it works now.

I think I did it right, let me know if not

**Comment by XElectricX** [comment]
LZ 2 does not have any access set. No could get the shutters open, even a synth.

**Comment by Isy232** [comment]
LZ 2 shutters are LZ 1 shutters, fixed that

**Comment by Isy232** [comment]
Found some more walls under shutters, fixing them

**Comment by KwinOriginal** [comment]
Taking the rare opinions to the map into account, you might want to provide the edge buildings (especially next to LZ1) with more flanks. Maybe extend the cave system around the whole colony for the most parts. Add some wall remains leading there, smashed windows and the like, stuff that opens paths for both sides alike, to not be forced on the streamlined ones solely.
Other than that, it looks good.

**Comment by Isy232** [comment]
I'll see to changes in a bit as I got a bit of IRL stuff I need to do.

**Comment by Isy232** [comment]
Okay, did it anyways, see mapping on discord for a list of changes, destroyed a few windows and walls

**Comment by spookydonut** [comment]
> 
> 
> Okay, did it anyways, see mapping on discord for a list of changes, destroyed a few windows and walls

Please post them here

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
