### PR TITLE
Hivelords get double plasma capacity but can only regen to half of it.

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
This makes the hivelord be able to store more plasma, althought they cant regen to it theyre able to be given more plasma from drones so they kinda act like a battery, the plasma until 50% looks like its normal then the "extra" plasma you get fills the bar in orange, this reduces a bit of the plasma precision because it makes a higher jump between the plasma states but display better without seeming like you are on 50% plasma when the other 50% is actually a extra "battery"
image

## Why It's Good For The Game
Gives a bit more difference from hivelords to drones, letting hivelords store some extra plasma if theres drone to give it to em'

## Changelog
:cl:
balance: hivelord gets their plasma pool doubled but they can only regen to half of it, they can however be given plasma functionally working like a extra plasma battery.
/:cl:

### CODE REVIEW

**Comment by KornFlaks** [comment]
There's gonna be a time every game where the queen and hivelord stand right next to each other cycling instant plasma transfer to generate infinite plasma.

This is gonna definitely separate bald hivelords with robust ones if they're willing to poke the queen and start filling the second half of plasma capacity through plasma transfers.

**Comment by SplinterGP** [comment]
> 
> 
> There's gonna be a time every game where the queen and hivelord stand right next to each other cycling instant plasma transfer to generate infinite plasma.
> 
> This is gonna definitely separate bald hivelords with robust ones if they're willing to poke the queen and start filling the second half of plasma capacity through plasma transfers.
> 
> Yea, this isnt gonna be a drone plasma battery but a queen plasma battery. I rarely see drones transfer plasma as they burn through their meager storage weeding, walling, and healing. I like it.

i mean queen doenst use plasma to transfer, they outright give it, hivelords transfer their plasma that they have i believe.

**Comment by KornFlaks** [comment]
> i mean queen doenst use plasma to transfer, they outright give it, hivelords transfer their plasma that they have i believe.

It costs the queen plasma to transfer, 100 plasma. Results in 300 plasma in the target xeno.

**Comment by BraveMole** [comment]
This seems a bit useless to me. IMO giving hivelord a way to recharge its battery alone (consuming stuff? licking bodies or i dunno) would be great

**Comment by lbnesquik** [comment]
Maybe we could have like, plasma wells.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
