### PR TITLE
Normal magazine pouches now unavailable in medic/engineer vendors

### PR DESCRIPTION
**Pull request by Chaznoodles**
## About The Pull Request

Normal magazine pouches now unavailable in medic/engineer vendors, replaced with large equivalent.

## Why It's Good For The Game

MJP oversight

## Changelog
:cl:
tweak: Normal ammo pouches now unavailable in medic/engineer vendors

/:cl:

### CODE REVIEW

**Comment by AtlasRules** [comment]
they also appear in the standard marine vendor

**Comment by Chaznoodles** [comment]
@AtlasRules 
image

They shouldn't!

**Comment by davidchan13** [comment]
@Chaznoodles They do on the live server.

**Comment by Chaznoodles** [comment]
> @Chaznoodles They do on the live server, for pistols at least
> 
> image

I am going to do unspeakable things to mjp

**Review by Hughgent — APPROVED** [review]

**Comment by TiviPlus** [comment]
loading tgmc.mdme
loading interface/skin.dmf
code/game/objects/machinery/vending/marine_vending.dm:441:error: /obj/item/storage/pouch/pistol/large: undefined type path
code/game/objects/machinery/vending/marine_vending.dm:579:error: /obj/item/storage/pouch/pistol/large: undefined type path
tgmc.mdme.dmb - 2 errors, 0 warnings (10/1/20 12:27 pm)

**Comment by Chaznoodles** [comment]
:eyes:

> loading tgmc.mdme
> loading interface/skin.dmf
> code/game/objects/machinery/vending/marine_vending.dm:441:error: /obj/item/storage/pouch/pistol/large: undefined type path
> code/game/objects/machinery/vending/marine_vending.dm:579:error: /obj/item/storage/pouch/pistol/large: undefined type path
> tgmc.mdme.dmb - 2 errors, 0 warnings (10/1/20 12:27 pm)

Fixed, incorrect type path. Missed a /magazine/.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
