### PR TITLE
fire support bino tweaks

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Adjust some targeting code for fire support binos, and cleaned it up a bit.

- You now actually needactually see your target to lase so no more calling cas through walls, and you can block it with smoke etc.
- Lasing is now done against an atom, not turf. This means if you lase a human/mech/etc, THE FIRESUPPORT WILL TARGET THEM IF THEY MOVE. This only lasts until the firesupport is actually called in (i.e. once the lase goes away) so you still have time to run away before the firesupport blasts the spot you were standing in.
- This also means you could cancel the firesupport entirely if you break LOS around a corner or something, so in most cases its probably better to still target a turf, but could be funny for dropping missiles on mechs.

In the future I might add the ability to keep painting a target for guided munitions (like the cruise missile), but not for now.
## Why It's Good For The Game
Funny cas through walls is kinda wack.
Proper ability to lase a specific target.
## Changelog
:cl:
balance: Campaign: Fire support binos require line of sight, but can now target any atom
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Fire support sucks even with through-wall lazing. I'd say its far better to have it like this , else it just becomes unused again.

**Comment by Lumipharon** [comment]
this is for campaign.

**Review by Kuro020 — APPROVED** [review]

**Comment by MLGTASTICa** [comment]
> this is for campaign.

my bad then

**Comment by Lumipharon** [comment]
updated to use byond vision, as its too frustrating with how different true LOS is vs byond LOS.

**Pull request merged**
