### PR TITLE
Increases GL-54 razor magazine price

### PR DESCRIPTION
**Pull request by henriquekill9576**
## About The Pull Request

changes GL-54's razorburn magazine price in req from 96 to 150

## Why It's Good For The Game

this shouldn't be this cheap for the area denial potential it has, a single marine can razorburn a giant room with just one magazine as seen in the pictures, all 5 are from different locations that were taken 1 hour and 30 minutes into the round
https://gyazo.com/9683b2c4157f42489646270ae4036a22
https://gyazo.com/d637e1aa0909c46f0076638858c9edf8
https://gyazo.com/c3b8fb2e56dd299ef3ac2a1ac29a3373
https://gyazo.com/3fd5a75db82191c930cf15e8aad1d965
https://gyazo.com/3fd5a75db82191c930cf15e8aad1d965

## Changelog
:cl:
balance: Increased GL-54 razor mag price from 96 to 150 in req
/:cl:

### CODE REVIEW

**Comment by Sirsnek15** [comment]
tell xenos to use defilers next time instead of straight doubling the price

**Comment by henriquekill9576** [comment]
> tell xenos to use defilers next time instead of straight doubling the price

no

**Comment by coldironwarrior** [comment]
just for clarity; 210 razorburn grenades were also produced in this round through factory and much of this razorwire is from factory grenades in combination with the GL mags.

**Comment by lbnesquik** [comment]
Coldironwarrior raises a good point, I was in that round, and I threw at least 5-10 RB grenades whenever I had to seal a hole, and I saw a lot more laying around.

**Comment by henriquekill9576** [comment]
> Coldironwarrior raises a good point, I was in that round, and I threw at least 5-10 RB grenades whenever I had to seal a hole, and I saw a lot more laying around. It could use a price increase, for sure, but 2x might be a lot. How about 1.5x ?

yeah i was debating either 1.5x or 2x, i suppose it's fine, just want to make it not spammable since it can create more razor than a normal grenade if aimed correctly

**Comment by chizzy376** [comment]
wow! another salt pr because of one xope round!

**Comment by Tailiik** [comment]
The only saving grace for xenos when marines do razor spam used to be praetorian, but now acid sprays stop after a single razor. P r e t t y silly how much wire marines can shit out for how long it takes to deal with a single nade's worth

> wow! another salt pr because of one xope round!

**Comment by Joe13413** [comment]
> wow! another salt pr because of one xope round!

my brother in christ, every xeno round i've played in the last few days has been plagued by razorwire spam
it's one of the only strats that genuinely gets me so mad that i don't want to play

**Comment by Lumipharon** [comment]
> The only saving grace for xenos when marines do razor spam used to be praetorian, but now acid sprays stop after a single razor. P r e t t y silly how much wire marines can shit out for how long it takes to deal with a single nade's worth
> 
> > wow! another salt pr because of one xope round!

if this is happening bug report it.

**Comment by Joe13413** [comment]
> wow! another salt pr because of one xope round!

bro.... im about to spit some xope out right here because razorwire spam infuriates me as a xeno player
No other strat over the years has ever come close to how much razorwire spam pisses me off
This one round was bad, but then it was like every single fucking round, we'd be spammed with razorwire.
Honestly the most shitass experience i've ever had on tgmc was these last few weeks, with every single person in sight abusing razorwire and the fact that prae can't even counter it right now

anyways, fuck you or something. Go play xeno when marines spam razorwire, you won't find it fun.

**Comment by Lumipharon** [comment]
Closing this for now. While this may or may not need a price increase, this pr is basically a salt pr after a single round where people have said most of the razor wasn't even from the tx-54, and there was a (now fixed) bug stopping xenos from using their main razor killing abilities.

**Pull request closed without merging**
