### PR TITLE
Defensive Xeno Buffs

### PR DESCRIPTION
**Pull request by Max-023**
## About The Pull Request
This is a PR to help rebalance xenos so they can take more punishment, T2s and T3s getting more armor while T1s get more health.

## Why It's Good For The Game
Right now xenos are a joke. They barely win and are way too punishing to play. Queens are deleted by flech using ungas and other xenos keel over with a simple sneeze. This will hopefully make them better to play and not nearly as overbearing.

I talked with others in the gen chat of the discord and it was agreed, the squishiness of the xenos was the main issue, as opposed to damage.

## Changelog
:cl:
balance: T2s and T3s now sport new armor
balance: Queen and shrike get additional health
balance: T1s get additional health
balance: Defiler has more speed
balance: Rav gets additional speed and health
balance: Prae gets more plasma regen
balance: Carrier hugger cap decreased by 5.
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
praise the lord

**Comment by SeniorScore** [comment]
As an austistic man who's played xeno 3 times total (most of that as a larva) I can say without a doubt this will throw balance WAAAAY out of whack, rip marines.

Seriously they were too fucking squishy. One marine being able to chase down any T3 with a pocket full of flechette to cancel the pitful amount of armor and some light armor to outrun a few of them is a bit much.

**Comment by psykzz** [comment]
You don't really need to open / close the review if you want to update the PR. Just make the changes as you like. 
Github will handle the rest

**Comment by Max-023** [comment]
it was automatic. not sure why it closed.

**Comment by Kuro-ai** [comment]
TM this so we can test it pls

**Comment by Kuro-ai** [comment]
Ok I see 2 problems with this pr
1-you didn't take warding in consideration,at lv 5 warding ancient crusher gets 100 bullet armor and a lot of xenos get close to it,should probably nerf warding or reduce some numbers,100 armor isn't a thing that should happen unless it's death squad
2-why does the bull have more armor than a warrior at ancient?it's not supposed to be a mega tank caste that frontlines,I would suggest reducing it to 50 at ancient

**Comment by jroinc** [comment]
What are your thoughts on raising base rifle round sunder to 1 pt, or lowering sunder regen by half? Currently, sunder is very difficult to actually get decent quantities on an ayy.

Besides that… lower bull and crusher armor slightly, and check warding.

**Comment by psykzz** [comment]
Warding is getting nerfed in https://github.com/tgstation/TerraGov-Marine-Corps/pull/3938
Max warding would be *2.5 instead of *5.
I'll tm both together.

**Comment by psykzz** [comment]
Make sure to update your CL with the updated changes

**Comment by psykzz** [comment]
These numbers work well with <5 xenos but when you get upwards to like 10+ it becomes a pain.
I think we should look into updating the xeno/human coef on the server alongside this.

**Comment by Max-023** [comment]
I don't really understand the coding for that. But I would agree, xenos can gather a lot of momentum once they get 7 or 8 xenos on the field. Additionally, I think frenzy should be reduced like warding as with some xenos, such as the rav, they become super powerful.

**Comment by psykzz** [comment]
I would try to avoid this being another full xeno reword (since you included the carrier changes)

It's going to increase the chances of this PR getting merged sooner

**Comment by Max-023** [comment]
Fair enough.

**Pull request merged**
