### PR TITLE
Massive food reorganization

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Does for food what Lumi did for inhands here https://github.com/tgstation/TerraGov-Marine-Corps/pull/12539. This PR reorganizes our giant blob of food icons into several separate .dmi files as well as separating them in the code for easier editing in the future.
Any map edits are solely to make sure that our maps have the updated typepaths.

EDIT: After counting, this PR takes the food.dmi file from 304 icons to ~~109~~ 73, that's less than 1/4th of the original size.

Where appropriate I have also replaced some of our crustier icons with TG versions and added some extra food types as well.
I would strongly recommend TM'ing this for a while, in case some overlooked food icon got broken during the change.

## Why It's Good For The Game

Less insane icon org is good.

## Changelog
:cl:
imageadd: Replaced some crusty food icons with TG versions
code: Reorganized food icons to not be in a single giant file
/:cl:

### CODE REVIEW

**Comment by XElectricX** [comment]
You didn't put lizard.dmi under the food folder, unless that was intentional.

**Comment by RipGrayson** [comment]
> You didn't put lizard.dmi under the food folder, unless that was intentional.

Thanks for pointing that out, both lizard.dmi and moth.dmi are gone now

**Comment by XElectricX** [comment]
> both lizard.dmi and moth.dmi are gone now

:(

**Review by Lumipharon — APPROVED** [review]

**Comment by Lumipharon** [comment]
Amazing

**Comment by Lumipharon** [comment]
image
frosted donuts apparently are broken

**Comment by Lumipharon** [comment]
Pizza boxes are also missing icons

**Pull request merged**
