### PR TITLE
New medical sprites, and chem fixes

### PR DESCRIPTION
**Pull request by goose4429**
## About The Pull Request

- 4 new pill bottles and several new injectors. 
- Existing pbs and injectors have their iconstate changed.
- A lot of fixes for chemmaster code and med sprites

## Injectors

image

image

## Pill Bottles

image

image

image

image

image

## Other

image

## Why It's Good For The Game

Easier to distinguish medicine.
Marines eye have less eyestrain.
You can have LARGE pill bottles for showing off your chem skills.

## Changelog
:cl:
expansion: Some injectors and pill bottles have new sprites
imageadd: Added injector and pill bottle sprites
fix: Fixed a lot of medical sprites
fix: Fixed chemmaster display errors
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Those state names

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Chem bottles have pure black outlines, that looks weird in this server

**Comment by Arctrooper8** [comment]
> > Those state names
> > Also I'm wondering if it would be easier to just greyscale the autoinjector. Outside of a few exceptions they all follow the same bands of colour, so it would make it easier to add more variety, and better yet allow marines to customise the colour like they can with pill bottles.
> 
> Greyscale is bad, don't use it for everything

Greyscale might actually be a good thing in this situation, if only so that injectors can have the same colours as pill bottles.

**Comment by goose4429** [comment]
> Chem bottles have pure black outlines, that looks weird in this server

New bottles have same outlines as both of previous ones.

**Comment by Kuro020** [comment]
> > Chem bottles have pure black outlines, that looks weird in this server
> 
> New bottles have same outlines as both of previous ones.

yes and? if you're gonna change it make it better

**Comment by goose4429** [comment]
> > > Chem bottles have pure black outlines, that looks weird in this server
> > 
> > 
> > New bottles have same outlines as both of previous ones.
> 
> yes and? if you're gonna change it make it better

For some reason it never was a problem, and is now. Lol.

**Comment by Kuro020** [comment]
> > > > Chem bottles have pure black outlines, that looks weird in this server
> > > 
> > > 
> > > New bottles have same outlines as both of previous ones.
> > 
> > 
> > yes and? if you're gonna change it make it better
> 
> For some reason it never was a problem, and is now. Lol.

I mean, new sprites need to be up to standards, just because old sprites of the same type don't adhere to that it doesn't mean I have to approve new ones that don't either, either change the outline of the bottle part to be greyscale or remove the bottles from this pr since I don't have a problem with the injectors

**Comment by goose4429** [comment]
> > > > > Chem bottles have pure black outlines, that looks weird in this server
> > > > 
> > > > 
> > > > New bottles have same outlines as both of previous ones.
> > > 
> > > 
> > > yes and? if you're gonna change it make it better
> > 
> > 
> > For some reason it never was a problem, and is now. Lol.
> 
> I mean, new sprites need to be up to standards, just because old sprites of the same type don't adhere to that it doesn't mean I have to approve new ones that don't either, either change the outline of the bottle part to be greyscale or remove the bottles from this pr since I don't have a problem with the injectors

Alright, I really don't get how it works, but at least now I understand better what you want. Very strange to me, hence the toxicity. But ok. Only outlines?

**Comment by Kuro020** [comment]
> > > > > > Chem bottles have pure black outlines, that looks weird in this server
> > > > > 
> > > > > 
> > > > > New bottles have same outlines as both of previous ones.
> > > > 
> > > > 
> > > > yes and? if you're gonna change it make it better
> > > 
> > > 
> > > For some reason it never was a problem, and is now. Lol.
> > 
> > 
> > I mean, new sprites need to be up to standards, just because old sprites of the same type don't adhere to that it doesn't mean I have to approve new ones that don't either, either change the outline of the bottle part to be greyscale or remove the bottles from this pr since I don't have a problem with the injectors
> 
> Alright, I really don't get how it works, but at least now I understand better what you want. Very strange to me, hence the toxicity. But ok. Only outlines?

yes the outline of the bottles you're adding

**Pull request merged**
