### PR TITLE
Adds auto hide to runner pounce

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Title.

Closes: #6911 

## Why It's Good For The Game

Why would they not always do this?

## Changelog
:cl:
add: Runners automatically hide when pouncing.
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Runner needed that buff

**Comment by lovegreenstuff** [comment]
history will favor my salt ided meme pr

**Comment by Wayland-Smithy** [comment]
just another verse in the tales the bards already sing of my epic merges

**Comment by SplinterGP** [comment]
lol

**Comment by MiniMeatwad** [comment]
Add praetorian corner spray.

**Comment by SilencedMP5A5** [comment]
bad

**Comment by TiviPlus** [comment]
Meme Pr

**Comment by Wayland-Smithy** [comment]
> Meme Pr

Nope. I am removing the incentive to use third party tools to achieve the most effective pounce using available mechanics.
```ahk
RButton:: ;or what ever your use ability hotkey is
Sleep, 20
SendInput, h ;or what ever your hide hotkey is
```

**Comment by MiniMeatwad** [comment]
This takes a feature in the game only available to people abusing third party tools, and makes it usable for everyone. This gives incentive to have it removed, and makes it available to those who do not use third party tools. Although it could just be removed.

**Comment by Wayland-Smithy** [comment]
> only available to people abusing third party tools

Huh? it simply takes a little more effort to press 2 buttons in a row instead of 1. Aside from a little skill curve of learning to bind and press both buttons runners should always be doing this for maximum effect anyway.

Unlike pick-up macros no abuse of custom verbs or the outside automation is even required. It's just QOL.

**Comment by TiviPlus** [comment]
See other pr, hiding should be on a cooldown after a runner pounces

**Pull request closed without merging**
