### PR TITLE
Miners are more durable

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

A 3 second windup is needed to damage miners. This makes them more durable, and way more easy to defend against wraith or fast runners

## Why It's Good For The Game

Miner integrity system was never designed for wraith, so it was stupidly easy to kill miners with it witout taking any risks.

## Changelog
:cl:
balance: Miners now take time to disable
/:cl:

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
3 seconds PER ATTACK?

How about like 5 seconds to completely reset it instead?

**Comment by BraveMole** [comment]
> 3 seconds PER ATTACK?
> 
> How about like 5 seconds to completely reset it instead?

It's 12 seconds, it's fine

**Comment by Wayland-Smithy** [comment]
Fine. I suppose multiple can do it at once to parallelize the task.

**Comment by BraveMole** [comment]
> Fine. I suppose multiple can do it at once to parallelize the task.

No clue, i don't think the do_after is blocking

**Comment by SplinterGP** [comment]
Why not increase health though?

**Comment by BraveMole** [comment]
> Why not increase health though?

would mean changing the code for repairs, for the same effect

**Comment by SplinterGP** [comment]
> 
> 
> > Why not increase health though?
> 
> would mean changing the code for repairs, for the same effect

ah i see

**Pull request merged**
