### PR TITLE
Lets xenos lay eggs anywhere

### PR DESCRIPTION
**Pull request by Pill-U**
## About The Pull Request

Removes the resin and resin building checks for laying eggs, letting them lay you anywhere. This does not let you plant them anywhere, only lay them. There's no real reason for these checks, If someone wanted to grief xenos by giving marines free eggs they could just go carrier, store the eggs, retrieve them and throw them at marines.
## Why It's Good For The Game
Just a QoL thing mainly for defiler and carrier

## Changelog
:cl:
qol: Let xenos lay eggs anywhere
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Why can xeno lay eggs even. Make them plant directly?

**Comment by Walarks** [comment]
Omelette enjoyers rejoice!

**Comment by Pill-U** [comment]
> Why can xeno lay eggs even. Make them plant directly?

because carrier can store them, dunno

**Comment by Walarks** [comment]
Carrier can't lay eggs last I checked.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Yeah honestly this is good qol on it's own so why not, but i'd be more interesting in scrapping laying eggs altogether, and make the ability plant the egg directly.

Do you want to do this or should i merge this pr?

**Comment by Pill-U** [comment]
I considered that. Just copying the egg planting code to the egg laying code is simple enough but since that makes the egg Item pretty redundant, I wanted to remove that too but that's a bit harder to do without breaking other stuff. Give me a day or two to try.

**Comment by Pill-U** [comment]
closing until I do this.

**Pull request closed without merging**
