### PR TITLE
Fixes ravager charge damage bonus not being applied correctly

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Fixes ravager charge not applying bonus damage
## Why It's Good For The Game
Its a bug and coding mistake
## Changelog
:cl:
fix: Ravager charge now applies its damage bonus properly.
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
The value in attack_alien_harm is NOT the damage it causes, its EXTRA damage for the attack, so it does slash damage + 25%, same for the charge

**Comment by RenGusta** [comment]
Xenos have two tier slash damage for a reason. It's sane and consistent for balance. Your change drops ravager to a (theoretical ) peak time to crit of 4.9 down from the current 6.3 seconds. When it's already several seconds faster than other T3's with the slash it already has. 

Yucky.

**Comment by MLGTASTICa** [comment]
> The value in attack_alien_harm is NOT the damage it causes, its EXTRA damage for the attack, so it does slash damage + 25%, same for the charge, and just buffing its damage is a nono.

right , after i looked deeper into how the proc for damage work , you're right, however i noticed that ravager bump used attack_alien , and not alien_attack_harm , so it would lose any bonus.
Ill revert the balance changes for now and make this a fix , considering that i misunderstood how it worked.

**Comment by SplinterGP** [comment]
NP, thats good to make it harm, it'd might cause the xeno to just swap if not in harm intent

**Pull request merged**
