### PR TITLE
Remove razor wire from the game

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Remove razorburn and related from the game

## Why It's Good For The Game

It's been abused for months by one player (thea), no one wants to fix it, admins chose to ignore it (this is a bug abuse and was stated as such for months).

This is slowing down the game to a crawl for the amusment of one player. If admins do not want to inteverne, I will.

If you are not happy with this, feel free to finally fix microdosing (Or maybe, finally warn thea to stop doing bug abusing?)

## Changelog
:cl:
del: Remove razor wire from the game
/:cl:

### CODE REVIEW

**Comment by Pill-U** [comment]
remove metalfoam while you're at it since that would be spammed instead when razorwire gets removed

**Comment by hyper2snyper** [comment]
One person abusing a bug from time to time is not a reason to remove an entire piece of content and a mechanic for marine defense.

**Comment by Derrick2Electricboogaloo** [comment]
> remove metalfoam while you're at it since that would be spammed instead when razorburn gets removed

Metal foam was nerfed by half it is useless, no one uses it. Even I largely gave up using it since primos make it useless more so.

**Comment by MiniMeatwad** [comment]
razor no slash rebound damage?

**Pull request closed without merging**
