### PR TITLE
Adds new chem: Jitterium.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Introducing the all new chem, jitterium. It makes you jitter. That's it.
Recipe: 
image
Can be made in 1 click: 
image
6 pills bottles of them are available in the MedPlus.
## Why It's Good For The Game
image
image
image
It's just for fun, very good for the game. 
## Changelog
:cl:
add: New chem, jitterium. Makes you jittery.
/:cl:

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
i will overdose on this at the start of every round guaranteed

**Comment by FosterGrime-Heymynameslouie** [comment]
VIBRANIUM

**Comment by Losenis** [comment]
inb4 closed due to powergaming

**Comment by FIXTHERADBOXPLEASE** [comment]
Time to take 900 units...

**Comment by Lumipharon** [comment]
Why?

**Comment by Xander3359** [comment]
Because this is a harmless way of bringing some stupid joy to a few people. Oh well.

**Comment by Losenis** [comment]
FUN CONFIRMED ILLEGAL

**Pull request closed without merging**
