### PR TITLE
Clawed Huggers no longer suck

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

Clawed Hugger melee damage increased from 23 to 25.
Clawed Hugger jump timer decreased from 1.5 to 1.2 seconds.

## Why It's Good For The Game

Clawed Huggers are no longer terrible.

## Changelog
:cl:
balance: Clawed Hugger melee damage increased from 23 to 25.
balance: Clawed Hugger jump timer decreased from 1.5 to 1.2 seconds.
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
a bit more than 30%, lets see how it goes

**Comment by SplinterGP** [comment]
way too strong, the hugger speed + damage is way too much at once

**Comment by Surrealaser** [comment]
> way too strong, the hugger speed + damage is way too much at once

Slowed the activation times

**Comment by Al-1ce** [comment]
even with a lower activation time these things are LETHAL against injured people. nice to see carrier becoming useful

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
