### PR TITLE
Makes bwoinks ignore the window flashing preference.

### PR DESCRIPTION
**Pull request by DominikPanic**

### CODE REVIEW

**Comment by spookydonut** [comment]
Nothing worse than making windows flash if you dont want them to

**Comment by DominikPanic** [comment]
> 
> 
> Nothing worse than making windows flash if you dont want them to

This is so people don't get noted for not responding to an admin while AFK. Not all people play with sound, this is something that everyone notices.

**Comment by Rohesie** [comment]
For AdminPMs it makes sense.

**Comment by Pariah919** [comment]
as someone who plays regularly without sound can approve

**Comment by spookydonut** [comment]
If someone sets their client to not flash the client should respect that otherwise you should just remove the preference completely.

**Comment by francinum** [comment]
You do realize this is one of the two places `window_flash` is ever actually used, the other being serverstart init completion.

**Comment by DominikPanic** [comment]
> 
> 
> You do realize this is one of the two places `window_flash` is ever actually used, the other being serverstart init completion.

Psy's #1600 PR changes that. And I assume more will in the future.

**Comment by Rohesie** [comment]
The flash only triggers when the window is not in focus. It is not horribly disturbing. If they are playing the game it won't disturb it. If they are alt+tabbed the window will just be a bit more insistent in that they are getting an admin message, which is kind of important here. They can always close the game if they wish to ignore admins.

In general I'd agree not to bypass preferences, but in this case it makes sense to.

**Pull request merged**
