### PR TITLE
Silo base spawn rate nerf

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Nerf base pool output from .65 to.4

## Why It's Good For The Game

Marines are getting steamrolled. I don't think it's the right solution, but we need a bandaid before balance freeze so this will do

## Changelog
:cl:
balance: Silo output reduced
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -24. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Smudged** [comment]
Knee Jerk PR's just because marines are getting rolled in 1 day are bad, especially before a feature freeze.

**Comment by neohenry** [comment]
> 
> 
> Knee Jerk PR's just because marines are getting rolled in 1 day are bad, especially before a feature freeze.

Technically, BraveMole is the one who made the spawning pool, so it's his project and his work to balance it.

**Comment by Smudged** [comment]
> > Knee Jerk PR's just because marines are getting rolled in 1 day are bad, especially before a feature freeze.
> 
> Technically, BraveMole is the one who made the spawning pool, so it's his project and his work to balance it.

that is a good point, and well, having it test merged wouldn't be a bad idea.

**Comment by Swagile** [comment]
Personally I think pool actually displays many of the weaknesses of marines.

For example, combat engis who's role is supposed to be building frontline FOB's and plugging gaps aren't able to due to a lack of materials so all pushes are "DO OR DIE" pushes because corpsmen can't risk defibbing when there is 125152 flanks all around them and no cover.

Fixing some of these issues with PR's already up should show a steady increase in marine wins when they are able to use all the resources available to them. We already see wins with tadpole ops that rush pools with miner support so that they can fall back and get healing / defibs + spec weapons should xenos dig in (X fuel is a must due to the current meta).

Also, pools show the weaknesses of miners; you can no longer hug miners due to xenos having so many lives and have to actually push.

Im sure there are a few other things im missing since I haven't played every role on marine side during pools, but those are the glaring issues im seeing that pools have exposed as major marine weaknesses.

**Comment by Al-1ce** [comment]
> Personally I think pool actually displays many of the weaknesses of marines.
> For example, combat engis who's role is supposed to be building frontline FOB's and plugging gaps aren't able to due to a lack of materials so all pushes are "DO OR DIE" pushes because corpsmen can't risk defibbing when there is 125152 flanks all around them and no cover.
This is almost entirely performance-dependent, but I agree. I think encouraging Engineers how to set up FOBs through some sort of in-game way (like posters) could help. An easy example is that I've seen more than 10 new engineers who didn't know how to connect plasteel cades and so on.

**Comment by DrCrawler** [comment]
This might be a good one, but work on this pull request. We all need good examples. Also tell us what it is going to be nerfed to. To get this pull actualy merged you need to work on it and get it to be atleast decent-looking.

**Comment by Chaznoodles** [comment]
This doesn't solve the inherent problem with pools which is - marines need to rush or they lose. Instead of it being marines vs xenos, it's marines vs the clock. Xenos don't need to fight to get numbers, whilst marines are under constant pressure to push the silos. They can't use Req well, they can't spend time helping wounded, they can't set up fortifications or secure miners.

This is not a solution or a fix.

**Comment by BraveMole** [comment]
> This doesn't solve the inherent problem with pools which is - marines need to rush or they lose. Instead of it being marines vs xenos, it's marines vs the clock. Xenos don't need to fight to get numbers, whilst marines are under constant pressure to push the silos. They can't use Req well, they can't spend time helping wounded, they can't set up fortifications or secure miners.
> 
> This is not a solution or a fix.

Yeah, marines need to push, rather than cadehugging. The round i saw, they had no issue healing the wounded or getting points, and by pressure, you mean having like a new larva every 6-7 minutes mid game?

**Comment by Chaznoodles** [comment]
> > This doesn't solve the inherent problem with pools which is - marines need to rush or they lose. Instead of it being marines vs xenos, it's marines vs the clock. Xenos don't need to fight to get numbers, whilst marines are under constant pressure to push the silos. They can't use Req well, they can't spend time helping wounded, they can't set up fortifications or secure miners.
> > This is not a solution or a fix.
> 
> Yeah, marines need to push, rather than cadehugging. Shockers i know. The round i saw, they had no issue healing the wounded or getting points, and by pressure, you mean having like a new larva every 6-7 minutes mid game?

And I'd bet they lost that round, or it dragged on endlessly, or both of these. Pools are not conductive to fun and this is a pretty universally-shared opinion.

**Comment by Swagile** [comment]
so the pool nerfs make it so xeno strategy is now to silent hijack for the super pool instead of playing the game normally

marines have adapted and wipe out hives constantly because xenos only have like 0.10 to 0.18 or something larvae PER MINUTE, and it goes up to around 0.25 larvae per MINUTE after 30-45 minutes.

not sure if this is intended behavior, and if it is, xenos stand no chance unless they immediately wipe marines out in the first 10 minutes, cause otherwise they unga rush.

been on both sides (the unga rusher and the unga rushed) and its just not fun as even with good mazes you just get fucked

**Comment by BraveMole** [comment]
> so the pool nerfs make it so xeno strategy is now to silent hijack for the super pool instead of playing the game normally
> 
> marines have adapted and wipe out hives constantly because xenos only have like 0.10 to 0.18 or something larvae PER MINUTE, and it goes up to around 0.25 larvae per MINUTE after 30-45 minutes.
> 
> not sure if this is intended behavior, and if it is, xenos stand no chance unless they immediately wipe marines out in the first 10 minutes, cause otherwise they unga rush.
> 
> been on both sides (the unga rusher and the unga rushed) and its just not fun as even with good mazes you just get fucked

That"s not true. Apart from the ultra-high pop unga ball (50 marines+)  which is still very short and one sided for marines, I've seen plenty of rounds going fairly well.  There's been a bunch of rounds that were 2h+, that went both side.

Also, if the marines attrition keeps being that high, i can't make pools give more output. Xenos will have more larva from psy drain, i think this number of 0.4 is final until marine's respawn get buffed

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-17). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
