### PR TITLE
Nerfs 12 Gauge Slug sunder, gives flechette higher sunder.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Flechette is now 7+5+5 sunder, which is 17.

Slugs of both kinds have halved sunder to 7.5.

## Why It's Good For The Game
12 Gauge Slug sunder is probably overall too high, perhaps 10 is better if it underperforms in the future.

Flechette sunder is too low right now, and I feel the ammo type is underperforming, If it does too much I'll nerf it down to like, 12.

## Changelog
:cl:
balance: 12 Gauge Slugs (Both Incend/Normal) sunder halved to 7.5, flechette upped to 17 max sunder on hit from 8.
/:cl:

### CODE REVIEW

**Comment by srxtreme** [comment]
speedmerghe

**Comment by Al-1ce** [comment]
based

**Comment by Jalopkomit18** [comment]
From stunlock slug juggle to hyperburst flech juggle. I am ready for the new age.

**Comment by DerpiestBruh** [comment]
cruelty squad reference

**Comment by Al-1ce** [comment]
``/datum/ammo/bullet/shotgun/incendiary``
``	sundering = 2 ``
***
``/datum/ammo/bullet/shotgun/flechette``
``	sundering = 3``

I suggest changing incendiary slugs alongside this for consistency.

**Comment by Pariah919** [comment]
> `/datum/ammo/bullet/shotgun/incendiary` ` sundering = 2 `
> 
> `/datum/ammo/bullet/shotgun/flechette` ` sundering = 3`
> 
> I suggest changing incendiary slugs alongside this for consistency.

That'd be a buff for them, rather do it another PR honestly.

**Comment by GravitronBlue** [comment]
>Flechette sunder is too low right now, and I feel the ammo type is underperforming, If it does too much I'll nerf it down to like, 12

Do this, as the problem of sunder spam has simply shifted to flechette with nobody using slugs now.

Frankly I wish this PR had simply nerfed slug sunder and then waited on buffing flechette.

**Pull request merged**
