### PR TITLE
Prae strong acid

### PR DESCRIPTION
**Pull request by Lefunny**
## About The Pull Request

This should give praetorian strong acid.
## Why It's Good For The Game

Praetorian is an spit based tier three so i believe its fitting for it to also have the strongest melting acid available which can also be decently useful at front line with weapon/flares melting. 
## Changelog
:cl:

balance: Gave praetorian strong acid

/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
Uhh i kinda fucked up and made the PR original name 'woo' my bad

**Comment by blackdav123** [comment]
this also increases prae's acid cost from 100 to 200, not sure if you wanted that.

**Comment by Lefunny** [comment]
> this also increases prae's acid cost from 100 to 200, not sure if you wanted that.

Not intended but frankly acceptable given the strength buff

**Comment by Lefunny** [comment]
> Prae is already good enough, we don't need even more sources of max strength acid. Flares melt in like 15-20 seconds with this, reinforced walls are melted in 1.5 minutes, stuff on the ground vanishes extremely quickly and you take massive damage on trying to pick them up to clear the acid.
> 
> We have queen, king, boiler, and primo hivelord for level 3 acid. Prae, spitter, non-primo hivelord, and shrike(?) are level 2. And all xenos with acid get level 3 during prep.

A boiler will barely be in the frontline to melt flares, a hivelord will but has more important things to do, a queen/king is the same, praetorian fits nicely in this spot, burn damage is mostly pain so the 'damage' you think its dealt by picking up stuff is vastly over estimated + praetorian is a lackluster t3.

**Comment by Ragecrabbo** [comment]
I think prae shouldnt have strong acid precisely because of how much use the entire hive would get out of it. Imo strong acid should be reserved for castes that have to make some sort of tradeoff for spending time aciding things. Queen, King and Hivelord all have a million different things they could be spending their time and plasma on ontop of being limited to single one per hive and pop-locked while boiler has to leave its lane to acid things knowing it might get rushed doing so. For a prae it would be very easy to melt any high value items and reinforced walls as the caste naturally spends its time in frontlines where the action is.

**Comment by TiviPlus** [comment]
I dont like this I agree that strong acid should be limited

Your why its good for the game also just says "Its fitting" when this not an insubstantial buff

**Comment by Lefunny** [comment]
> I dont like this I agree that strong acid should be limited
> 
> Your why its good for the game also just says "Its fitting" when this not an insubstantial buff

strong acid is limited, if at most hivelord should lose it at primo. Praetorian is a tier three frontline acid based caste i see no reason for it to not have it

**Comment by Lumipharon** [comment]
agree with tivi

**Comment by Lefunny** [comment]
> agree with tivi

uwaah my pr got closed by a maint that wasn't even talking with me

**Comment by Zangeiti** [comment]
coping that his powercreep pr didnt get in LMAO

> uwaah my pr got closed by a maint that wasn't even talking with me

**Comment by Lefunny** [comment]
> coping that his powercreep pr didnt get in LMAO
> 
> > uwaah my pr got closed by a maint that wasn't even talking with me

anything i dont like is powercreep!!!!!!!!!!!

**Pull request closed without merging**
