### PR TITLE
Revert "Kuro Gun Resprite pt1"

### PR DESCRIPTION
**Pull request by bowlofcereal**
## About The Pull Request
Reverts the gunsprites to the old ones.

## Why It's Good For The Game
The new gunsprites are generally rather poor, the sprites massively clip into both hand slots, and the speedmerge is very controversial in the playerbase, so we should really discuss this instead of speed merging a PR that massively changes the art of the game, considering that a large majority of the playerbase dislike this change. Forcing PRs in that change something to such a large degree should definitely be discussed, not forced in.

## Changelog
:cl:
spriteadd: Reverts the gun sprites to the old ones.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
>evil spriter Kuro inserts satan approved sprites after 3 day speedmerge
>experts call for Kuro to be replaced as art director by the spriter of the old gun sprites, Kuro
>Marines go on strike, fighting only with swords and grenades to protest this injustice, xenos express their support for this action

**Comment by Kapu1178** [comment]
based bowl of cereal. The sprites are straight up inferior to the old ones.

"Consistency" is not a legitimate argument. Don't want mosins? Remove mosins. But again:
Literally who asked for consistency among the weapons? TGMC is goofy. It always has been. It always will be.

**Comment by Skycave1** [comment]
ME WANT ATTACHMENT! ME WANT ATTACHMENT! BOWL LEFT ME FOR DEAD TO WRITE A PR, But I agree with this.

**Comment by Al-1ce** [comment]
I'm starting to realize why Kuro didn't include the inhands sprites of these in his PR. They really do just stand out like a sore thumb. I don't see any reason to appeal to "consistency" when sprites that don't follow conventional rules like #10633 remain speedmerged. The vast majoriety of the community thinks these are a downgrade.

This wouldn't have been merged in first place if the community actually was given a chance to talk about it. Most of the players don't use the github. There are no systems in game like voting panels to decide on these things. So, backlash is only really recieved once the entire community is frustrated.

I think the wider issue here is that most of Kuro's PRs are merged within _less than a day_ of being open. Not because the community agreed on them looking good or anything, but because **_he_** thought that they were fine.


>"_sadly for you I'm art director so my shit taste is what goes_" (kuro comment from #10637)

**Comment by Kuro020** [comment]
The sprite prs are merged without testing because thats what happens to sprite only prs, they dont get TMed (thats what bravemole and tivi told me when I became a memetainer), tho that pr in particular was on github for 2-3 days and me/poofy had posted the sprites on discord quite a bit.

Yes they are quite bad, I'm fixing them, I told mole and tivi that I'll let them decide wheter to merge this revert or not (even though the guns are gonna go back in when the sprites are fixed anyway)

**Comment by Losenis** [comment]
Remember when PRs needed TMC tag and TMing before anyone even thoght about merging?

**Comment by bowlofcereal** [comment]
This is your daily reminder that now is a great time to master the art of the machete. Hell, maybe even get some vali combat in. I personally ain't touching those fuckin' guns with a 10 foot pole, despite my fierce love of the T35. This is literally exactly the same as when they tried to remove armor colors. I will not and never will support changes to such massive parts of the game art style wise when the rest of the freakin' game doesn't look like it. It looks out of place and uncanny. Nobody I have spoken too in game likes these.

Kuro, you seem to have missed the point this PR is making. I don't care about it being "fixed", no one including me wants them in the first place. This is a revert not because they are broken, but because we don't want them.

We have in game stuff for crap like this, like polls. Would it hurt to simply make a poll and ask the 90% of players that don't browse the Github and Discord like it's their house how they feel?

**Comment by Sirsnek15** [comment]
> based bowl of cereal. The sprites are straight up inferior to the old ones.
> 
> "Consistency" is not a legitimate argument. Don't want mosins? Remove mosins. But again: Literally who asked for consistency among the weapons? TGMC is goofy. It always has been. It always will be.

don't you dare use my mosin as a bargaining chip

**Comment by Starfirejordan** [comment]
this is a yes! add it

**Comment by bowlofcereal** [comment]
Interesting that my comment on my own PR which was quite on topic was marked as off-topic.

This is your daily reminder to future coders and maintainers that may see this, including our current ones, that in game polls are a great way to gather opinions from your players who do play the game on what they think of sprites, and not forcing them on to them without them even knowing about them in the first place.
It's clear you really don't like the backlash you're getting since you are going out of your way to censor dissidence. Unfortunate that this devolves into dumb spess politics. I will continue to oppose these sprite changes for as long as they exist and malcontent sits in the player base. 

As we speak I am building up a proper full no-new sprite gun build for those wondering how to play without having to use them.

**Comment by Kapu1178** [comment]
When people are opposing changes THIS HARD, maybe consider that the playerbase doesn't want them?

This is why spriters shouldn't have write access to repos. They put their own self-importance over what people actually want.

**Comment by Losenis** [comment]
Clearly, there is no globally bad feedback.

**Comment by Wotzizname** [comment]
Okay, but can we keep the MG42s sprites? Those look really cool and better than the old halo gun.

**Comment by Naaanii** [comment]
The revolution has begun...

**Comment by TiviPlus** [comment]
The gun sprites are being fixed and will not be reverted

**Pull request closed without merging**
