### PR TITLE
Adding the Barrenquilla Mining Facility (Lava Outpost 3.0)

### PR DESCRIPTION
**Pull request by AyyRobotics**
## About The Pull Request

Updates the old Lava Outpost and replaces it with the new _Barrenquilla_ Mining _Facility._ Also adds some fluff notes and different wall/floor/remain types for an easter egg planned to be added later on, though the map in itself should be playable which is why it's not currently a draft PR. Also comes ready for map rotation.

image
(Updated image.)

## Why It's Good For The Game

More map variety and the revival of a long unused and unloved map. It will somewhat require marines to use their skills and tools like plasma cutters, though I'm fairly sure marines can win without them. The map encourages marines to explore and look around rather than sticking to a specific straight path with different, tactical rewards. As well as encouraging tactical plays like sniping from bridge walkways or locking off certain ones.

Postcard

## Changelog
:cl:
add: Added the Barrenquilla Mining Facility
add: Added some fluff lore and things to be expanded upon later.
del: Removed old Lava Outpost
imageadd: added some sprites for areas and other non-important things.
/:cl:

### CODE REVIEW

**Comment by AyyRobotics** [comment]
AAGH ONE FAILED CHECK

**Comment by AyyRobotics** [comment]
Right I'll fix all this tomorrow alongside some more map fixes

**Comment by Swagile** [comment]
this is level of based unknown to man

👍🏻

**Comment by BraveMole** [comment]
Is it still caves everywhere?

**Comment by AyyRobotics** [comment]
> Is it still caves everywhere?

After checking they're called caves but they have an open roof like regular areas, so OB and CAS and all that should still work.
Just in case though I'll add a base cave area, also since I forgot that ambience exists

**Comment by AyyRobotics** [comment]
By request and potential opportunity to fix errors im gonna close and re-open this

**Comment by AyyRobotics** [comment]
Oh yeah baby checks passed

**Comment by SplinterGP** [comment]
once you make the easter egg, use underlayers to hide the easter egg

**Comment by Wayland-Smithy** [comment]
100% of the entire map is "in the open" including groundside telecoms, also I noticed a space tile near the rubber duck around the center of the map.

**Comment by AyyRobotics** [comment]
> 100% of the entire map is "in the open" including groundside telecoms, also I noticed a space tile near the rubber duck around the center of the map.

Fixed the space tile, though I don't know what you mean by "in the open". If it refers to the areas, I checked and all the building should have outside set to false

**Comment by AyyRobotics** [comment]
Wait did that actually work?

**Comment by AyyRobotics** [comment]
OH SHIT IT WORKED

**Comment by David-Stormwell** [comment]
You're gonna need to remove the cult room north or make it accessible to marines and xenos and remove the DS rifle.
Since you can OB in to kill the door, or wraith in and construct a silo which is unreachable to marines.

**Comment by AyyRobotics** [comment]
> You're gonna need to remove the cult room north or make it accessible to marines and xenos and remove the DS rifle.
> Since you can OB in to kill the door, or wraith in and construct a silo which is unreachable to marines.

Spaced out (literally) the cult room, and lowered the weapon tier to 3 since I do want there to be some reward for marines actually accessing it. Gonna wait on committing it until I can make sure there isn't any other problem I don't know about

**Comment by SplinterGP** [comment]
use underlayers to hide it from the webmap

**Comment by Swagile** [comment]
> 
> 
> You're gonna need to remove the cult room north or make it accessible to marines and xenos and remove the DS rifle.
> Since you can OB in to kill the door, or wraith in and construct a silo which is unreachable to marines.

you can jetpack in, or construct catwalks

**Comment by InterroLouis** [comment]
Queens can still reach that lava blocked spot.

**Comment by AyyRobotics** [comment]
> Queens can still reach that lava blocked spot.

Oh my god why is lava so shit at killing xenos.
Hold on..

**Comment by BraveMole** [comment]
make it limited to 45 pop please

**Comment by TiviPlus** [comment]
> make it limited to 45 pop please

config issue use #policy

**Pull request merged**
