### PR TITLE
Fix the poster bulging downward. As it turns out, there is a weird thing with the direction giving out a pixel offset.

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request

image

Fixes this issue : https://github.com/tgstation/TerraGov-Marine-Corps/issues/7500

## Changelog
:cl:
fix: fixed a misplaced poster.
/:cl:

### CODE REVIEW

**Comment by Ieteihowmee** [comment]
Oh god, will we have to properly fix this in maps as well? These posters on some ships were placed offset due to this bug, now they will all be thrown out of alignment!

**Comment by lbnesquik** [comment]
> 
> 
> Oh god, will we have to properly fix this in maps as well? These posters on some ships were placed offset due to this bug, now they will all be thrown out of alignment!

I have noticed a couple of posters which weren't sticking to walls. That whole 'dir' thing seems to be the reason.

**Review by TiviPlus — APPROVED** [review]

**Comment by Ieteihowmee** [comment]
> > Oh god, will we have to properly fix this in maps as well? These posters on some ships were placed offset due to this bug, now they will all be thrown out of alignment!
> 
> I have noticed a couple of posters which weren't sticking to walls. That whole 'dir' thing seems to be the reason.

So it does not mess with all the maps, there will be no floating posters even after this?

**Comment by lbnesquik** [comment]
> 
> 
> > > Oh god, will we have to properly fix this in maps as well? These posters on some ships were placed offset due to this bug, now they will all be thrown out of alignment!
> > 
> > 
> > I have noticed a couple of posters which weren't sticking to walls. That whole 'dir' thing seems to be the reason.
> 
> So it does not mess with all the maps, there will be no floating posters even after this?

Uhhh, dunno. I fixed this one on the map files, so probably there will be.

**Pull request merged**
