### PR TITLE
Nerfs Hunter Movementspeed

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Hunters now have the movement speed of sentinels.

## Why It's Good For The Game

Hunters have a lot of health, a lot of damage, and a lot of movespeed for what they can do. It's an absolute meme seeing them zip around players like a mouse on cocaine while bump slashing them into oblivion with sneak attack memes. This PR removes the amount of "dodge" they have by nerfing their movespeed to that of a sentinel.

## Changelog
:cl: BurgerBB
balance: Hunters are now slower; they move the same as a sentinel.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
now we need a courageous soul to tackle hunter stealth attack code

**Comment by Rohesie** [comment]
Wait, as slow as the sentinel? That's a ranged caste.

**Comment by BurgerLUA** [comment]
Sentinels are pretty speedy.

**Comment by jroinc** [comment]
Probably for the best, given the stealth capabilities.

**Comment by Isy232** [comment]
Are you sure this isnt too much of a nerf?

Hunters are T2 and nearly as squishy as a runner.

**Comment by BurgerLUA** [comment]
I'm sure, as long as no one nerfs stealth attack.

**Comment by Rohesie** [comment]
I need input from more players here.

**Comment by BurgerLUA** [comment]
> I need input from more players here.
> We should not be keeping stealth attack because the hunter is too slow, we should be addressing the real issue.

The hunter's concept is fine. It having high damage from stealth is fine. It just needs to be slowed to a reasonable amount.

**Comment by AdamElTablawy** [comment]
i don't really see the speed as an issue, given that it's what lets it actually pull off its stealth attacks.

without that, hunter is pretty much relegated to the role of organic landmine, as it's so fragile it can't slash a marine from stealth and escape, thus resulting in it being shot to pieces by any nearby marine

**Pull request closed without merging**
