### PR TITLE
Resurrection of the sacred PR.

### PR DESCRIPTION
**Pull request by BeloneX**
## About The Pull Request
As per title. But it cannot be obtained normally in vendors. It has no protection or camo options compared to the rest of the marine uniforms. Other than that, armors can be worn and so on and so forth. Unless if you want to make it harness-only, be my guest.
 
https://i.imgur.com/CVX6r9R.png

## Why It's Good For The Game
Another variant of marine uniforms for the sake of casual wear. You cannot obtain it normally though, and there's no reason to get this other than losing a minor point of armor.

## Changelog
🆑 Xslayer300 BeloneX
add: Added marine uniform skirts, out of all things.
/🆑

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Mannybrado** [comment]
fuck you

**Comment by David-Stormwell** [comment]
based

**Review by TiviPlus — APPROVED** [review]
Quality content tgmc needs

**Comment by XSlayer300** [comment]
:eyes:

**Comment by Kuro-ai** [comment]
Meme begone,kill this pr bimmer

**Comment by Chaznoodles** [comment]
I'm going to come to your house and armcurl your dog at the bottom of the stairs until you close this

**Comment by BeloneX** [comment]
> I'm going to come to your house and armcurl your dog at the bottom of the stairs until you close this

Good thing I don't have one.

**Comment by TheBimmer231** [comment]
I have more important things to do than play cat and mouse with you, the reason I closed this PR to begin with is very clear, and if you can't wrap your head around it then I'm sorry.

**Pull request closed without merging**
