### PR TITLE
Minor SMG rebalance.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Nerfs T90 akimbo, firedelay upped to 0.15 between shots for both guns and acc debuff.
Buffs T90 gun stats, better wield and aim slowdown overall.
-
T-90

Aim slowdown 0.25->0.2 (Makes it a bit more distinct and shaves a .1 compared to carbine.
Wield delay 0.5->.25 (Makes it have 0.25, most other guns get agrip which allow you for a lower overall level. This is a decent level for it.
Scatter 2->0 (No reason to have 2 degree of angle scatter really.)

T-19

Wield delay 0.4->0.15 (Makes it better at CQC.)
Mag size 30->35 (Makes it have better ammo economy, 40 was too much before, and the burst fire chews through ammo.)

T19 STOCK

Wield delay .1->.2 (Nerf because the base delay was changed, still a bit faster.)
Burst delay -0.1 (Better burst, far better. From .2 to .1)

## Changelog
:cl:
balance: Minor SMG rebalance. T-90 got better gun stats overall, no more scatter angles, faster wield and faster speed. T-19 got a buff, much faster wield delay, and stock gives you a better burst delay at the cost of wield delay, but still faster than before. T-90 akimbo severly nerfed.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
The t90 changes are pretty much what I had in my old pr, but it didn't seem like there was much interest in merging it.

For the T19, burst delay is already 0.1, and I don't think it can go under 0.05.

**Comment by Pariah919** [comment]
```
The t90 changes are pretty much what I had in my old pr, but it didn't seem like there was much interest in merging it.

For the T19, burst delay is already 0.1, and I don't think it can go under 0.05.
```
feels higher than .1 but okay, I'll reblalance it real quick

**Review by BraveMole — CHANGES_REQUESTED** [review]
This obviously wasn't tested.

**Comment by Pariah919** [comment]
image

**Pull request closed without merging**
