### PR TITLE
Powerfist

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

https://streamable.com/kgfqiz
## Why It's Good For The Game

fun

## Changelog
:cl:
add: Powerfist
imageadd: sprite by Daytona 
/:cl:

### CODE REVIEW

**Comment by XSlayer300** [comment]
Finally, a worthy challenge for a melee spec!

Also, should it be undroppable, or make it a toggle to lock on the arm so it cannot be dropped?

**Comment by TiviPlus** [comment]
Toggle created

**Review by TheBimmer231 — CHANGES_REQUESTED** [review]
Ping me.

**Comment by Hughgent** [comment]
If only you solved the sprite 'issues'

_if o n l y_

**Comment by TiviPlus** [comment]
New sprite by daytona

**Review by Hughgent — APPROVED** [review]

**Comment by jroinc** [comment]
Why do ungas have *another* dedicated melee option?

**Comment by Hughgent** [comment]
no bug reports. others may balance as they see fit.

**Pull request merged**
