### PR TITLE
Shutters open at 12:28

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

It's time to shorten prep.

This is only 5 minutes, to see how marines react. 

The goal is probably 12:20 at the end, but this will need some changes first

## Why It's Good For The Game

Prep boring, let's get to fight sooner

## Changelog
:cl:
balance: Shutters open at 12:28
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
reduce the minimum launch time instead, 12:20 is the minimum launch time currently.

**Comment by BraveMole** [comment]
> reduce the minimum launch time instead, 12:20 is the minimum launch time currently. or something like that idk

I did it?

**Comment by KornFlaks** [comment]
> reduce the minimum launch time instead, 12:20 is the minimum launch time currently. or something like that idk

That's not true. I've launched the alamo at 12:18 before. If you see a FC launching at 12:18 and shutters up at 12:20, that's me.

**Comment by SplinterGP** [comment]
> 
> 
> > reduce the minimum launch time instead, 12:20 is the minimum launch time currently. or something like that idk
> 
> That's not true. I've launched the alamo at 12:18 before. If you see a FC launching at 12:18 and shutters up at 12:20, that's me.

oh i dindt know which was the minimum actually, never noticed

**Comment by TiviPlus** [comment]
This wont speed up the game just mount more pressure let marines open when they want

**Pull request closed without merging**
