### PR TITLE
Shotgun Shell Rebalance - Slugs

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request
Brings slugs closer to the other shells in terms of damage, as well as increased sunder at the cost of AP.
## Why It's Good For The Game
Slugs are really bad. They're outperformed at range by flech at every tier of armor except warded crusher due to their low base damage. 

This gives it a niche outside of "pester the enemy xeno with stuns from very far away."
## Changelog
:cl:
balance: increased slug damage and sunder at the cost of AP
/:cl:

### CODE REVIEW

**Review by lbnesquik — APPROVED** [review]

**Comment by OrbisAnima** [comment]
Really excited towards the upgrade! Question though, shouldnt the incendiary slugs get a pass too?

**Comment by Passe2142** [comment]
Slugs my beloved.

**Comment by lovegreenstuff** [comment]
> Really excited towards the upgrade! Question though, shouldnt the incendiary slugs get a pass too?

no incens don't deserve shit
fuck incens

**Comment by lovegreenstuff** [comment]
closing for balance freeze

**Review by TiviPlus — APPROVED** [review]

**Comment by Lefunny** [comment]
marines are with a real lack of damage and stuns being almost always outspeeded by xenos, i hope this chang that.

**Pull request merged**
