### PR TITLE
Optimizes playsound

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

TM before merge, did not profile because i dont have 60 clients on hand i would test with

## Changelog
:cl:
code: optimized sounds
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
You don't need real clients to profile this with. You can lightly modify the code & manually add objects to the spatial grid recursive contents lists nearby.

I think it's unlikely this will be faster than just iterating over all cliented mobs, as spatial grid overhead is not nothing.

**Comment by TiviPlus** [comment]
no but I work on the assumption its faster than 80+ players

**Comment by Barnet2** [comment]
I'll reiterate what I said on Discord;

While this is testmerged I often had instances where audio wouldn't play. Notably, it happened most frequently when I spawned roundstart, when I died and turned into a ghost, and when I spawned in as ERT. They would clear up 15-60 seconds after those instances, where I could hear again. Also saw people in dchat and XOOC talking about it.

**Comment by Lumipharon** [comment]
From when I played this when it was test merged, it seems like an orange_ear is not assigned when a mob spawns, but when I moved far enough from my spawn spot for it to assign a new orange_ear, sound seemed to work fine.

**Pull request closed without merging**
