### PR TITLE
Synth can no longer strap shields.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Synth can't strap shields, and thus can no longer have no drop shields.
## Why It's Good For The Game
Synths can't wear heavy armor for a reason, they already get inherient armor/health boosts by simply existing. I don't think they need shields considering they can't even use firearms. This barely nets a loss for them if they use it.
## Changelog
:cl:
balance: Synths can't use shields anymore.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Shields and firearms are opposites. Defensive options aren't inherently a bad thing and this just seems like a quick salt PR.

Probably out of the scope of this PR but fixing crit for synths would help push this PRs notion as synths are already easily punished as it is.

**Comment by GreatKingWombat** [comment]
> "Your programming restricts operating this strap."

Fuck it, merge because it's funny.

**Comment by Mrrpip** [comment]
...Deployable Shield Ocelot synth?

In other news. For once I'm not affected by a shield nerf. Praise be!

**Comment by Derrick2Electricboogaloo** [comment]
Yes, less defensive options is so terrible. I have to lose a hand to do stuff to use it.

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Can be bypassed via strip menu

**Comment by Pariah919** [comment]
i will wait for #13193

**Pull request closed without merging**
