### PR TITLE
Fixes lasgun pouch having an error sprite

### PR DESCRIPTION
**Pull request by Notamaniac**
## About The Pull Request

Fixes error overlay on lasgun pouches AKA TE Powerpacks

This must've been borked by one of the storage.dmi/ammo.dmi reorganisations. The problem is that I can't find the orignal ammo overlay sprites anywhere, not even in the old versions of those files. Do the orignal overlays still exist? Was there some spaghetti preventing an error overlay from showing? I geninuely do not know. I sprited some new ones instead.
lasgunpouch

## Why It's Good For The Game

A lil less ERROR, a little more knowing how much charge you have at a glance

## Changelog

:cl:
fix: TE powerpacks no longer have an ERROR sprite, and their sprite changes according to how much charge there is left
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Probably the reason why there wasn't any errors, because the standard missing icon was just a blank.

**Comment by Notamaniac** [comment]
> Probably the reason why there wasn't any errors, because the standard missing icon was just a blank.

Oh that makes sense, I assumed that there was always a fallback error sprite

**Comment by Helg2** [comment]
Conflicts

**Comment by Notamaniac** [comment]
bah it's on an icon file so there's no easy way to resolve it

**Comment by Lumipharon** [comment]
@Notamaniac just put the icons in the new file.

**Comment by TiviPlus** [comment]
We also have the dmi conflict resolving script

**Pull request closed without merging**
