### PR TITLE
Reduces color amounts to map variants

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Reduces color availability to only map variant choices.
## Why It's Good For The Game
There are far too many colors in TGMC for marines which causes visual disparity for everyone involved.
## Changelog
:cl:
delete: Deleted about 4/5th of Jaeger colors, only map variant colors remain.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
Xeno nerf, now they can't metatarget the autistic robustos with gradient hair and neon armor

**Comment by zzurge** [comment]
Hell nah

**Comment by docRoboRobert** [comment]
nah man

**Comment by dontob** [comment]
looks like trolling

**Comment by TiviPlus** [comment]
mjp moment

**Pull request closed without merging**
