### PR TITLE
Replaces most pouch sprites

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Replaces the pouches with more in style looking pouches, made by kuro (and some edits by me)
image

## Why It's Good For The Game
They look better and are more in style. And sleek.

## Changelog
:cl:
Pariah919, Kuro
add: Added new pouch sprites.
del: Removed old pouch sprites, git will remember them. Nobody else will.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -60. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by TiviPlus** [comment]
image
Removed the unused ones (red)
B) why are explosive and explosive_large so different (blue)

**Comment by Kuro-ai** [comment]
> image
> Removed the unused ones (red)
> B) why are explosive and explosive_large so different (blue)

Explosive is the grenade pouch,explosive large is the actual explosives pouch

**Comment by Pariah919** [comment]
image
@TiviPlus done

**Review by Hughgent — APPROVED** [review]
LGTM

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-61). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
