### PR TITLE
 reduces buckshot back down to 1+2 projectiles halved damage falloff

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Title
Makes buckshot do 80x3 

## Why It's Good For The Game
Buckshot is really bad right now, it needed a buff

## Changelog
:cl:
balance: Buckshot now does 80x3, and does minorly more slowdown on hit. Halved damage falloff
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -43. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
please god it's so bad

**Review by Hughgent — APPROVED** [review]

**Comment by Hathkar** [comment]
Lowering the number of projectiles seems fine, but increasing the damage is ehhh. It's already extremely strong, enough to destroy most castes in a few shots.

**Comment by Dolth** [comment]
I think I am fine with that. Too much scatter was making it weak as fuck and a total of 240 is still lower than flechette (I think?)

**Comment by Texicos** [comment]
Pariah making a good PR????? Seriously this is needed,

**Comment by MiniMeatwad** [comment]
One shots most t1s and some t2s, and one shots young t3s with burst sawed off.

**Comment by Hathkar** [comment]
Did some testing; buckshot DESTROYS most t1s in two shots, even at ancient. This is without a barrel charger or bayonet attachment.

**Comment by Pariah919** [comment]
> Did some testing; buckshot DESTROYS most t1s in two shots, even at ancient. This is without a barrel charger or bayonet attachment.

this comment is irrelevant since I changed the damage back to what it is the literal milisecond it was done. Ooof.

**Comment by Hathkar** [comment]
> 
> 
> > Did some testing; buckshot DESTROYS most t1s in two shots, even at ancient. This is without a barrel charger or bayonet attachment.
> 
> this comment is irrelevant since I changed the damage back to what it is the literal milisecond it was done. Ooof.

So you tested it then?

**Comment by MiniMeatwad** [comment]
Buckshot still does a lot of damage even at longer ranges. Can still two-shot T3s.

**Comment by MiniMeatwad** [comment]
Kills T3s really easy, and just about everything else. Deals about 235 damage on a PB for a young drone. Can deal anywhere between 20% to 60% of a Young T3's HP in one shot at 3-4 tile distance. For reference, a direct hit from the recoilless rifle does 247 damage to a young drone. Being caught in the explosion does 104 damage to a drone. This means that a rocket launcher is about 44% weaker than all buckshot pellets connecting, or equal damage when a direct hit. This was tested using HE.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Overbuffed, nerf it

**Pull request closed without merging**
