### PR TITLE
revives squad spec

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Revives squad spec in all its glory and some edits to modernize it, like giving it ranks

## Why It's Good For The Game
Marines should have squad specs for early game pushing as it makes their early game far far worse than it needs to be overall, and in general specs are a good idea

## Changelog
:cl:
balance: reenables specs
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
can xenoes permakill them though

**Comment by Jeff-jefferson-jeffery** [comment]
I never thought i could look a man in the eye... and call him based.
But this? This is based.

**Comment by Swagile** [comment]
is this really happening or just a meme PR)

i thought specs was squashed in favor of spec guns in req, and everything was mostly balanced around them not existing at round start (aka weaker screech, crusher charge doing much less damage, etc)

**Comment by Kuro-ai** [comment]
So like, you realize I removed most spec gear sprites from the repo right?

**Comment by TGCMbetcher** [comment]
What if we bring them back but put in the flame thrower, the grenade launcher, the SG and the t127 in their weapon options so its basically just a smart gunner and smart gunners are brought back.

**Comment by SplinterGP** [comment]
Add specs back mixed with SG role, give then a few loadouts like normal SG and Shotgun SG

**Comment by Tupinambis** [comment]
I don't like what specs used to be and I am worried just re-adding them will open up the same problems. They were the overpowered boys with the big toys that made everyone set the role to high and made xenos cry. 

The good part of specs imo was the specialized gear you get, like the grenadiers belt or the scout cloak. The bad part was getting very powerful weapons roundstart, so my recommendation is to give specs more standard marine weapons for the most part.

(TL-127 for snipers, TX-15 for shotgun scout, T-64 for BR scout, TL-84  flamethrower for Flame spec, T-160 Recoilless rifle for Rocket spec, T-70 for nade spec, and T-60 GPMG for heavy spec) and the mod 88 as a sidearm option.

That way spec is more a "I want to have a specialized playstyle" than a "I want to be powerful unga" which led to a lot of bad specs and was a bit unbalanced. I'd rather have the more powerful req weapons exist as options for specs to consider as an upgrade. I imagine most ROs would give specs priority on those req weapons either way since Specs are also second in commands of SLs.

**Comment by TiviPlus** [comment]
Meme Pr

**Pull request closed without merging**
