### PR TITLE
Deletes the entire codebase and replaces it with a png of gayt rouny

### PR DESCRIPTION
**Pull request by Xander3359**
This is what this codebase needs. True Balance.

gayt runner

### CODE REVIEW

**Comment by Pariah919** [comment]
You should lay off the bottle.

**Comment by Xander3359** [comment]
> You should lay off the bottle.

This will end up becoming the most thumb up'd PR on the entire github you just wait and see.
Maintainers will be forced to merge it.

**Review by Lumipharon — APPROVED** [review]

**Comment by Naaanii** [comment]
Man has officially mental boomed.

**Comment by AviiCinders** [comment]
10/10 best thing to ever happen to a tg codebase

**Comment by Licherr** [comment]
what coding an active competitive game's balance looks like:

**Comment by KillerOrcaCora** [comment]
TheRedeemedHumanity

**Comment by Pariah919** [comment]
> > You should lay off the bottle.
> 
> This will end up becoming the most thumb up'd PR on the entire github you just wait and see.
> Maintainers will be forced to merge it.

Alas, Balance fever takes another of weak will..

**Comment by Naaanii** [comment]
> > > You should lay off the bottle.
> > 
> > 
> > This will end up becoming the most thumb up'd PR on the entire github you just wait and see.
> > Maintainers will be forced to merge it.
> 
> Alas, Balance fever takes another of weak will..

Only the strong may survive.

**Comment by XSlayer300** [comment]
👀

**Comment by Lumipharon** [comment]
I would have merged, but 
image

@Xander3359 You're an actual active contributor, so its sad to see you get coped to death. You're welcome back when you get better.

**Comment by MiniMeatwad** [comment]
He got xoped to xeath as the xids say.

**Comment by Derrick2Electricboogaloo** [comment]
Man what have I missed?

**Comment by This1sPanda** [comment]
BRING IT BACK, WE SHOULDA KNOWN, WE ALWAYS SHOULDA KNOWN

**Pull request closed without merging**
