### PR TITLE
Sends all of the Tadpole variants to the adminrealm

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Makes all tadpole variants currently ingame admin only.
## Why It's Good For The Game
Tadpole variants that aren't basically slightly changed standard tad are bad for balance because it can let tad do things it shouldn't like landing in halls and stuff, aswell as dumb stuff such as 3 weapon hardpoints this mainly aims to makes tadpole consistent again in what it can and cannot do.
## Changelog
:cl:
del: All tadpole variants other than standard are admin only now.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
I kinda like fatpole and suspole it feels like normal tadpole but fatter

**Comment by lbnesquik** [comment]
At least keep the fat pole!

**Comment by FIXTHERADBOXPLEASE** [comment]
Like 90% of them are questionable at best, but the sussy wussypole has genuine trade-offs.

**Review by Lumipharon — CHANGES_REQUESTED** [review]
I don't have a problem with big tad or the sustad, or classic tad. They all have tradeoffs due to their large/unusual size.

**Comment by Mannybrado** [comment]
just remove the meme tads please

**Comment by dopamiin0** [comment]
idk i like all the serious tads fine even though i basically always just use the standard one anyways. i do think removing ones like kitchen tad is good though because PO already has a reputation as a grief role and giving them literal grief options does not help

**Comment by Lumipharon** [comment]
@Pariah919 the large tad is fine as well imo, but I'm open if other people think it's unreasonable in some way.

**Pull request closed without merging**
