### PR TITLE
T-64 Battle Rifle Rebalance

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
T-64 now has its own projectile and bullet caliber, 10x26.5mm light marksman bullet. B~~urst amount reduced to **2** with~~ Extra delay of ~~0.25~~ 0.20 seconds. Light marksman bullets deal ~~35~~ 30 damage, ~~7~~ 10 AP, and 1 sunder.

## Why It's Good For The Game
I am beyond caring and now only have supreme apathy. No one has come forward with any changes to tone down the Battle Rifle so it isn't capable of melting just about every xeno within 1 burst to 4 bursts,

## Changelog
:cl:
balance: 10x26.5mm light marksman bullets for the T-64, meaning the T-64 Battle Rifle no longer shares the same caliber or ammo with the T-37 DMR.
balance: extra delay increased to 0.35
imageadd: t-64 ammo packets
/:cl:

### CODE REVIEW

**Comment by KrabSpider** [comment]
Nerfing the burst instead.

**Comment by hyper2snyper** [comment]
First of all, probably should fix the changelog.
Also if you are nerfing the ammo you probably dont need to nerf fire delay

**Comment by KrabSpider** [comment]
Even more changes made.

**Comment by Lumipharon** [comment]
You've reduced the AP and burst amount which already decreases the dps, the extra delay probably isn't required.

**Comment by KrabSpider** [comment]
> You've reduced the AP and burst amount which already decreases the dps, the extra delay probably isn't required.

I'll tack that down in the morning.

**Comment by Xsdew** [comment]
You have introduce a new caliber, the 10x26.5mm light marksman bullet. As such there is no need to reduce the amount of the burst from 3 to 2. As you have given the T64 its own caliber, the performance of the 3 round burst can be adjusted via the characteristics of 10x26.5mm.

**Comment by KrabSpider** [comment]
Burst amount reverted back to 3 after some very careful evaluation.

**Review by Kuro020 — APPROVED** [review]

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
