### PR TITLE
Inventory procs name changes.

### PR DESCRIPTION
**Pull request by Ghommie**
Delivered in a more atomized format as requested.
:cl:
code: renamed several invetory procs naming patterns to match /tg/'s, in preparation of future works.
/ :cl:

### CODE REVIEW

**Comment by spookydonut** [comment]
Simple question, why?

**Comment by Ghommie** [comment]
The inventory procs need some updates. I can't do in one go but I shouldn't implement them in unrelated PRs.

**Comment by DominikPanic** [comment]
Conflicts.

**Comment by Rohesie** [comment]
List the substitutions you've made, please, for easier review.

**Comment by Ghommie** [comment]
> 
> 
> List the substitutions you've made, please, for easier review.

`get_active_hand()` to `get_active_held_item()`
`get_inactive_hand()` to `get_inactive_held_item()`
`drop_inv_item_on_ground()` to `dropItemToGround()`
`drop_held_items()` to `drop_all_held_items()`
`drop_inv_item_to_loc()` to `transferItemToLoc()`
`u_equip()` to `doUnEquip()`
`temp_drop_inv_item()` to `temporarilyRemoveItemFromInventory()`

That should be it. Also time to deal with conflicts.

**Comment by Rohesie** [comment]
Conflicts with your previous PR.

**Pull request merged**
