### PR TITLE
Fixing smoke nades and buffing phosphorus smoke.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Fixing #1549. Also buffing the second most useless smoke subtype, deleting its duplicate.
Done a couple tweaks to make smoke_contact() work on simpler mobs and xenomorphs to an extend. Slighty increasing the cloak nade lifespan too.

## Why It's Good For The Game
Bugfixing, and buffing the severely underpowered phosphorous grenade a little bit even though I assume it will remain fairly useless against xenomorphs.

## Changelog
:cl:
fix: fixed smoke grenades spawning smoke onto the user's location when detonating.
tweak: Extended the smoke effects to simple mobs and xenomorphs a bit.
twek: Raised the smoke layer, now it covers mobs too.
balance: Reworked white phosphorous grenades to not be total trash. Buffed fireloss on contact, added oxyloss, blurring and lung damage if inhaled, now capable of dealing minor damage to alien resin structures and a mild loss of stored plasma in xenomorphs. Also roughly less opaque so to not block FoV and with higher smoke radius. Careful of FF potentials.
balance: Also slighty improved cloaking nades lifespan, though they may need proper improvements later.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
Plasma-draining grenades is a pretty good idea. Increase their duration time, lower their visibility impact and make marines unaffected by it, and you have yourself a situational support tool.

**Comment by Rohesie** [comment]
Merge conflict.

**Comment by Rohesie** [comment]
Merge conflict.
Test this locally after it's fixed and let us know so we can put it for test.

**Comment by Ghommie** [comment]
> 
> Test this locally after it's fixed and let us know so we can put it for test.

Is there a bug I'm unaware of, or is the local run meant to simply verify it works as intended?

**Comment by Rohesie** [comment]
Oh, just to verify. No bug that I know of.

**Comment by DominikPanic** [comment]
has this been tested?

**Comment by Rohesie** [comment]
Let's give it a short test.

**Comment by Ghommie** [comment]
Ok, tested and it works. It just felt very very weak on xenos, so I buffed the effects a bit.

**Comment by psykzz** [comment]
I don't seem to be able to throw a smoke grenade after igniting it, unless i preset throwing before ignition

**Pull request merged**
