### PR TITLE
hivemind tweaks lol

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request
various hivemind related changes
basically, they make hivemind more supportive and less annoying, hopefully
## Why It's Good For The Game
himevind crunge
me get walled off after fling and me salty
ooga booga

Also, in general, I think that hivemind and hivemind players don't deserve nice things.
## Changelog
:cl:
balance: hivemind can no longer manifest inside walls or build at range, shuffle mobs
balance: hivemind built walls now start out weaker, but reach normal health after time
balance: hivemind gets sent back to their core when "killed"
balance: hivemind health increased from 100 to 250, hivemind speed decreased and health regen increased to compensate
/:cl:

### CODE REVIEW

**Comment by Luxyboo** [comment]
BLAST HIVEMIND INTO THE DEPTHS OF HELL

**Comment by vilereaver41** [comment]
Dont touch ranged building lol

**Comment by Mechanelize** [comment]
ranged building NECCESARY

**Comment by lovegreenstuff** [comment]
cope and seethe

**Comment by Ragecrabbo** [comment]
is it possible to increase the speed at which hivemind regains health back? I feel like increasing the health from 100 to 250 is going to be more of a nerf than a buff

**Review by BraveMole — CHANGES_REQUESTED** [review]
Yeah buff the regen as well, and by a good margin. 
Also this will be tm'd before merge to see if hivemind is still viable

**Comment by private-tristan** [comment]
ranged building is practically essential for hiveminds.

**Review by BraveMole — APPROVED** [review]
test first

**Comment by lovegreenstuff** [comment]
you fool
you buffoon
you fell right into my trap

by slapping these two different changes together instead of atomizing wall manifest as a bug fix, i have already enacted the first step of my plan

**Comment by FosterGrime-Heymynameslouie** [comment]
removing ranged building and wall manifest
so we're basically going back to pre 2017 hivemind but worse?

**Comment by Lumipharon** [comment]
This uh, doesn't work. Ranged building still works. On the brightside they're not tanky to the point where it's effectively pointless to try fight them.

**Comment by lovegreenstuff** [comment]
hivemind isnt literally worthless now
time to nerf them into the floor for real this time

**Comment by lovegreenstuff** [comment]
yeah no this has gone too far, i'll clean this shit up later.

**Pull request closed without merging**
