### PR TITLE
Nanotrasen Roomba Racing Stadium Deluxe Squid Games

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
xenos and marines have 4 roombas each that will begin racing to the finish point when the shutters open and when they reach the finish point the losing team explodes

roomba

## Why It's Good For The Game
emergent gameplay, increased excitement, basis for new groundmaps

## Changelog
:cl:
add: Roomba Stadium
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
yes

**Comment by lKiseki** [comment]
pls speedmerg

**Comment by XSlayer300** [comment]
needs more detail tho

**Comment by FosterGrime-Heymynameslouie** [comment]
this is quite possibly the best pr to ever grace the existance of the human race
so good infact that while I was eating my breakfast, scrolling through the github updates, to see the absolute monstrosity of the pr name, has made me choke and nearly die on the food I was chewing.

sppede mrhged

**Comment by Araulius** [comment]
give this man maintainer role. He is a man of the people!

**Review by TiviPlus — APPROVED** [review]
Squid games

**Comment by Alexeivichi** [comment]
this gave me depression, again.

**Review by Pariah919 — APPROVED** [review]
All is balanced in TGMC.

**Review by RipGrayson — APPROVED** [review]
Who needs a maptainer when you have quality like this
fu

**Comment by bowlofcereal** [comment]
This is hilariously based and reminds me of the map I was making for april fools which was just a giant empty black baseplate with "shit yourself" written on it

Make it so xenos and marines can see eachother but they cant actually touch eachother with like invisible walls or unbreakable windows, therefore we can get the most out of this map

**Comment by Starfirejordan** [comment]
what bowl said. just keep the racing track but redo how marines and xeno interact

**Comment by tyeagg** [comment]
Failed experiment, would be good for cm

**Pull request closed without merging**
