### PR TITLE
readd masterkey back to t-25

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

T-25 is getting its plasma pistol, the sorely attachment that let it shoot another type of ammo, removed. Despite it being more flexible than the T-29, T-25 gets less secondary weapons on it than other rifles. Maybe I will add UGL back in T-25, but that's another story.

Masterkey is not as bad as plasma pistol or mini flamethrower. No way in heck shall T-25 get mini flamethrower back. In fact, the masterkey shall syngerize with #9912 to ward off xenomorphs from its lowered RoF.

## Changelog
:cl:
add: readd masterkey back to t-25
balance: readd masterkey back to t-25
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Plasma pistol shouldn't have been an attachment to begin with and plasma pistol got a funny buff to compensate. This seems unnecessary.

**Comment by Arctrooper8** [comment]
Powercreep, if you must add something just give it angled grip which is relatively harmless.

**Review by Pariah919 — COMMENTED** [review]
Unsure, I don't like the T-25 having utility over T-29 outside of pepperball gun in general, I think. Might be better to rebalance them overall to be equal in hard utility attachments, however I'm up to debate this.

**Comment by BraveMole** [comment]
No

**Pull request closed without merging**
