### PR TITLE
More End of Round Deathmatch roles

### PR DESCRIPTION
**Pull request by XSlayer300**
## About The Pull Request
As per title. If anyone needs more EORD roles, please tell me now!

## Why It's Good For The Game
Because WE NEED MORE VARIANTS.

## Changelog
:cl:
add: Added more EORG roles, no deathsquad roles yet though.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
The commando and guardsman leader are pretty unbalanced.
Why not picking more balanced ones?

**Comment by XSlayer300** [comment]
I'll try that.

**Comment by Rohesie** [comment]
```
[00:24:14] Runtime in game_mode.dm, line 521: Cannot execute null.assign equip().
proc name: end of round deathmatch (/datum/game_mode/proc/end_of_round_deathmatch)
src: Crash (/datum/game_mode/crash)
call stack:
Crash (/datum/game_mode/crash): end of round deathmatch()
Crash (/datum/game_mode/crash): declare completion(1)
Crash (/datum/game_mode/crash): declare completion(1)
Ticker (/datum/controller/subsystem/ticker): fire(0)
Ticker (/datum/controller/subsystem/ticker): ignite(0)
```

In short, you are using outfits instead of jobs. That gives an error.

**Comment by XSlayer300** [comment]
> ```
> [00:24:14] Runtime in game_mode.dm, line 521: Cannot execute null.assign equip().
> proc name: end of round deathmatch (/datum/game_mode/proc/end_of_round_deathmatch)
> src: Crash (/datum/game_mode/crash)
> call stack:
> Crash (/datum/game_mode/crash): end of round deathmatch()
> Crash (/datum/game_mode/crash): declare completion(1)
> Crash (/datum/game_mode/crash): declare completion(1)
> Ticker (/datum/controller/subsystem/ticker): fire(0)
> Ticker (/datum/controller/subsystem/ticker): ignite(0)
> ```
> 
> In short, you are using outfits instead of jobs. That gives an error.

Fixed it.

**Comment by InterroLouis** [comment]
Can you remove the CLF standard one? It's actually the pits. The worst. Has no helmet or anything, and a terrible gun.

**Pull request merged**
