### PR TITLE
adds a marine spear

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image
adds a marine spear so people don't have to make glass spears
sprite by me

## Why It's Good For The Game
if someone is gonna get one they might as well not have to go through the hoops to get one

## Changelog
:cl:
expansion: adds marine spear in vendors
/:cl:

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
does this mean we can also have my cool e-sabers?

**Comment by AnCopper** [comment]
MJP removing everything he doesn't like by claiming it's LRP but then adds a 'Marine Spear'

**Comment by vilereaver41** [comment]
harpoon gun or nop

**Comment by David-Stormwell** [comment]
commit unlife on pr

**Review by TiviPlus — APPROVED** [review]
Tactical spear
Camo sold seperately

**Pull request merged**
