### PR TITLE
Quikdeploy HvH Cades

### PR DESCRIPTION
**Pull request by XSlayer300**
## About The Pull Request
image

## Why It's Good For The Game
image

ok

## Changelog
:cl:
add: Quikdeploy cades for HvH has been added for admins.
/:cl:

### CODE REVIEW

**Comment by AbsoluteJerry** [comment]
Gimme gimme

**Comment by Chaznoodles** [comment]
Make their sprite the already-existing ballistic barricade, to reflect them being for that purpose?

**Comment by AbsoluteJerry** [comment]
I would prefer already existing. Mostly just to get this PR TMed quicker

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Needs sprites

**Comment by TiviPlus** [comment]
Also why isnt this a buff of normal caves noone shoots cades usually anywa

**Comment by XSlayer300** [comment]
i mean, they use explosives on cades

**Comment by XSlayer300** [comment]
I have no plans to update this anytime soon, sorry Jerry.

**Pull request closed without merging**
