### PR TITLE
underbarreled flashlights

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
flashlights that fit on your underbarrel slot
literally it, no difference to rail flashlight
## Why It's Good For The Game
People wanted this I suppose, makes sense to me considering you're giving up other stuff in exchange for light range.
## Changelog
:cl:
add: Underbarreled flashlight attachment.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
Based. Remind me how far the light attachment reached compared to baldur?

**Comment by MereWalker** [comment]
Is this a second option? Or are we forced into a underbarrel flashlight.

**Comment by Losenis** [comment]
Wait does having both rail and under lights stack

**Comment by Pariah919** [comment]
> Wait does having both rail and under lights stack

no

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
