### PR TITLE
update pilot visuals

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
New armor and uniform for pilots
image
## Why It's Good For The Game
looks good
## Changelog
:cl:
add: new armor for pilot
imageadd: new pilot armor
imageadd: new pilot uniform
imageadd: new pilot helmet
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Isn't that suit using som colors?

**Comment by Gregormack** [comment]
> Isn't that suit using som colors?

There is no such thing as SOM colors. Don't worry, SOM would be superior anyway

**Comment by lbnesquik** [comment]
I'll be honest, the side helmet prespective looks a little weird.

**Review by Wirpy — APPROVED** [review]
sprite approval

**Comment by Looking4bros** [comment]
I don't understand how the Orange line in the center of the helmet is seen at all on the east and west sprites, as they're depicted at the same elevation as the surrounding blues on the north and south sprite. are the west and east sprites angled south west west and south east east?

**Comment by Lumipharon** [comment]
> > Isn't that suit using som colors?
> 
> isnt the som color orange

this is the exact som armour colour palette

**Pull request merged**
