### PR TITLE
VARIANCE BEGONE

### PR DESCRIPTION
**Pull request by Metroidlover**
## About The Pull Request

Removes any and all melee variance from the code

## Why It's Good For The Game

RNG isn't fun nor fair, and when dealing with damage calculations can change wildly form doing nothing to actually killing things
## Changelog
:cl: MetroidLover
balance: All Melee attacks no longer have a random variance and always do the same damage
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
Spike damage begone!!!

**Comment by Rohesie** [comment]
The principle of the change is good, but the values should be either the average or the lower ones.

**Comment by Metroidlover** [comment]
There, every value that had a Vary of more than 5 originally now has been averaged for the most part, every other caste either needs to have damage higher than it's low or is such a small difference it doesn't matter.

**Comment by Rohesie** [comment]
There's several straight buffs here.
Please use the lower value if you don't want to average it.

If you want to buff certain attacks, state which and why.

**Comment by Metroidlover** [comment]
You know what, after doing the math I agree that everything should use it's average, I'll go change that, my bad

**Pull request merged**
