### PR TITLE
Brig Overhaul

### PR DESCRIPTION
**Pull request by Jimminian95**
:cl: Jimminian95
add: Swaps the brig and the OB room, with the OB as an extension of the hangar and the Brig in front of CIC. Moves all bunks, including the SO and XO bunks, the CL office and the Officer's mess into the CIC ring. Expands CIC armoury while adding engi/medical equipment, adding a hallway surrounding the CIC itself. 
add: Remapped the brig from scratch into a Panopticon design. Adds a large permabrig (complete with hydro, basketball, bedrooms, and food to keep prisoners busy), conference and interrogation rooms, open reception area (Any crew can get into the brig's main hall), MP bunks and an observation bubble complete with buttons to lock down the brig and flash various areas.
/:cl:
Adds white fire extinguishers and megaphones around the map; TCs and POs get their own weapons vendors.
Every button available is accessible in the CMP's office, including one to open the MP armoury;
the MP armoury is now activated separately from the rest of the ship's armouries.
Added fax machines to each department.

### CODE REVIEW

**Comment by Alterist** [comment]
also use more multi_tile airlocks in your bridge area

**Comment by Jimminian95** [comment]
That's because I committed to the same branch as the last PR (the one that swapped the Brig/OB).
While it's bad practice, I got some errors when trying to delete and create a new branch, so I kept it to avoid taking risks.
This PR focuses solely on brig changes (aside from adding faxes to research and CIC)

**Comment by DominikPanic** [comment]
Power was still broken during all of yesterday.

**Comment by Alterist** [comment]
Seems like a mapdiffbot error, close and reopen the commit when you get the chance

**Comment by Alterist** [comment]
Still, put the description made into this pr

**Comment by Alterist** [comment]
Issues: 
Upper floor - Wires passing through walls amd crisscrossing each other, extra wires in intersections
Lower floor - outside hull is incomplete

**Pull request merged**
