### PR TITLE
You can see how many burrowed there are from lobby.

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Stop burrowed larva count from being hidden in lobby

## Why It's Good For The Game

This is just a terrible feature IMO. I added a warning, but knowing that xeno really have a ton of burrowed would probably incentivize players to go even more to xeno whenit's really needed

## Changelog
:cl:
qol: You can see how many burrowed there are from lobby
/:cl:

### CODE REVIEW

**Comment by EvilMelonTheSecond** [comment]
This is much better for measuring xeno/marine balance compared to the "pwease pway beno" pop up. I won't feel like I'm getting baited to play xeno if I can see they have like 7 unclaimed burrowed.

**Comment by SplinterGP** [comment]
Admin input on this because concerns metagaming blablablabla

**Comment by lKiseki** [comment]
Fine by me.

**Comment by Wayland-Smithy** [comment]
I don't think marines who click past the imbalanced teams dialog will see this anyway sadly.

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
Sure <I guess

**Review by TiviPlus — APPROVED** [review]

**Comment by KornFlaks** [comment]
Honestly, when I see 6+ burrowed slots as xeno, it gives me less incentive to play xeno than just the ??.
Then again, I just observe and check hive status before this PR. Still do actually to check the names and how bald the hive is. 

This at least makes my decision easier to go marine and skip the 15 min wait time (missing the first alamo drop if the loadout vendor somehow lost my presets) if I see that many burrowed. 

Is it metagaming? Definitely. But is saves me from suffering though yet another marine stomp from lack of xeno players. And the initial bioscan tells everyone the quantity of xenos anyways.

**Comment by SplinterGP** [comment]
> 
> 
> Honestly, when I see 6+ burrowed slots as xeno, it gives me less incentive to play xeno than just the ??.
> Then again, I just observe and check hive status before this PR. Still do actually to check the names and how bald the hive is.
> 
> This at least makes my decision easier to go marine and skip the 15 min wait time (missing the first alamo drop if the loadout vendor somehow lost my presets) if I see that many burrowed.
> 
> Is it metagaming? Definitely. But is saves me from suffering though yet another marine stomp from lack of xeno players. And the initial bioscan tells everyone the quantity of xenos anyways.

it rather makes the other for me, if i know theres alot of free xeno slots i go play xeno rather than marine, playing just to stomp win aint fun as you basically most times dont need to do anything either

**Review by SplinterGP — APPROVED** [review]

**Comment by SplinterGP** [comment]
worked properly, emrging

**Pull request merged**
