### PR TITLE
Adds some holopads around the Theseus

### PR DESCRIPTION
**Pull request by grinkgo**
## About The Pull Request

Self-explanatory

## Why It's Good For The Game

AI can actually use their holograms yay

## Changelog
:cl:
add: Added some holopads around the Theseus.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by grinkgo** [comment]
> You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

eat poo

**Comment by ondrej008** [comment]
> 
> 
> You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

die

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-3). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
