### PR TITLE
Big Red V2.1 - Big additions.

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

Adds more buildings and some features to big red.

## Why It's Good For The Game

This gives marines a reason to explore the map to access new storage of supplies in LZ1 as well as to access an underground Nanotrasen facility. This gives a nice RP addition to it and hopefully won't just mean marines rush Xenos. Xenos gains access quickly via lambda to this underground facility or at least most of it as only marines can access the other entrance without Xeno interruption. the underground facility allows Xenos a silo/hive spot that makes more sense but at the same time, they have less freedom to flee or run so it needs to be protected well. 

I think the players will really enjoy the process and cosmetic feel of the new additions. Both entrances cannot be camped as the main marine one has a large hangar door that won't allow Xenos access inside. though it should prove a challenge to combat a prepared smart hive.

Also, an issue we currently have is that most of the big maps are not used, I hope to change that slowly but surely so we all have more fun. I do plan to continue adding changes to Big Red as I learn how to code better for instance a third underground chamber and a revamp of how the facility is accessed.

## Changelog
:cl:
fix: weird blue and green cargo container glitch

add: a small miner building in north caves

add: supply chamber in lz1 that can't be accessed until button in eta lab directors office is activated

add: button in eta lab directors office that can only be used by field commander or higher via their id card

add: a building that leads to an underground facility that cannot easily be accessed by marines until the button in eta lab director's office is activated. though a good enough marine squad can use the lambda Xeno entrance that is always open.

add: medium size underground facility

add: lambda entrance to the underground facility
/:cl:

images

Theta lab

### CODE REVIEW

**Comment by rusher210** [comment]
loving the changes to big red, the underground section looks very cool

**Comment by vilereaver41** [comment]
> loving the changes to big red, the underground section looks very cool

Thanks took 2 days to do lol.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
About the use of ladders, what stops this from becoming like CM ice where everyone camps ladders for literally hours in a huge stalemate?

**Comment by vilereaver41** [comment]
> About the use of ladders, what stops this from becoming like CM ice where everyone camps ladders for literally hours in a huge stalemate?

all fixed

**Comment by KornFlaks** [comment]
Woah woah. What's with that plat miner in the north next to FOB.

No. A miner there is fine but not a plat miner. Please, make it phoron.

**Comment by SpaceLoveSs13** [comment]
So I just found out that there is a space tile around[or maybe right here] 25 X, 203 Y, 2 Z. NE of the LZ1 Alamo Landing Pad. Wanted to let you know.

**Comment by vilereaver41** [comment]
> So I just found out that there is a space tile around[or maybe right here] 25 X, 203 Y, 2 Z. NE of the LZ1 Alamo Landing Pad. Wanted to let you know.[ Annotation 2021-08-17 100748 ](url)

il check it out ty

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
