### PR TITLE
Valk buff

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds a check for stabilized limbs when adding pain to a human.
## Why It's Good For The Game
Bugfix
## Changelog
:cl:
balance: Stabilized limbs no longer give un-splinted amounts of pain
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
The one drawback I can find as a xeno against valkyrie is precisely stacking fractures and the pain they give, because otherwise there is no reward for excessive damage on a valkyrie user. This is most certainly an unnecessary buff to the module and I'd rather it stayed as-is.

**Comment by Lumipharon** [comment]
its not a bug fix, its a deliberate thing, and a fairly reasonable/minor tradeoff for not needing splints imo.

**Comment by Xander3359** [comment]
> its not a bug fix, its a deliberate thing, and a fairly reasonable/minor tradeoff for not needing splints imo.

Everything else checks for stabilized limbs except for this here, that's what makes me think this is something that was forgotten.
But I'll go ahead and change the label to balance

**Comment by novaepee** [comment]
I would be genuinely surprised if this gets merged.

**Comment by ivanmixo** [comment]
No thanks

**Pull request closed without merging**
