### PR TITLE
Buff: Reduce required sheet to upgrade metal barricade from 2 to 1

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

image

Tivi said it was okay after 3 hours of engineer balance in #dev-general

## Changelog
:cl:
balance: Reduce required sheet to upgrade metal barricade from 2 to 1
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
Make it 1.5

**Comment by Wayland-Smithy** [comment]
Does this have any meaningful impact in terms of the amount of mats leftover from destruction and break the metal eco?

**Comment by Derrick2Electricboogaloo** [comment]
> Does this have any meaningful impact in terms of the amount of mats leftover from destruction and break the metal eco?

It already does not, I can not image reducing the cost affects it.

**Comment by Derrick2Electricboogaloo** [comment]
Good step in the right direction, now we need to adjust the values for upgrades so they are still less of a joke. This just helps make it less painful in terms of resource consumption.

**Review by Pariah919 — APPROVED** [review]
Makes sense, saves you a cade per every four upgrades. I like this.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
