### PR TITLE
Bumps the nuke up a few layers

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

The nuke is now above beds. Alternative and preferable solution is to have beds be saner with their layers but this is the immediate fix.

## Why It's Good For The Game

Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3524

## Changelog
:cl:
fix: The nuke can no longer be hidden under beds.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
This probably looks weird when the Ravager is south of it, but as said before, sprites over 32 pixels tall are kind of an issue.

**Comment by nemvar** [comment]
It's still below mob layer so it probably looks fine.

**Comment by nemvar** [comment]
yeahfine

**Comment by Rohesie** [comment]
No concerns then, nice.

**Pull request merged**
