### PR TITLE
Replaces AK sprites, add SoM AK. Deltes AK carbine.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
base ak sprite made by kuro, edited by me and ocelot
inhands by kuro with some edits by me.
deletes the mar30/old ak sprites
deletes the pointless ak carbine and replaces it with an SoM carbine
AK now has basic attachment slots.
This is done.

## Why It's Good For The Game
The AK is kind of bad because it has virtually no attachment slots, and the ak carbine is literally pointless.
The old mar sprite sucked
the new ak looks decent

## Changelog
:cl:
add: Added new SoM AK. Added New AK sprite.
del: Removed old AK sprites and mar sprites. Git will remember them. Nobody else will.
tweak: AK can now take some basic attachments
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SilencedMP5A5** [comment]
better firesound too pls

**Review by Hughgent — APPROVED** [review]
Code is good.

Post some pictures of the sprites spawned in game please.

**Comment by Pariah919** [comment]
@Hughgent 
image

**Comment by SilencedMP5A5** [comment]
reee why'd you remove the bolt

**Comment by TheBimmer231** [comment]
Uhh, no? DM me.

**Pull request closed without merging**
