### PR TITLE
Reduces Behemoth's Ability Damage Against Vehicles

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Reduces Behemoth's ability damage against vehicles to a 1.8 multiplier, down from a 10 multiplier.
## Why It's Good For The Game
Behemoth is doing an absurd amount of damage against tanks and apcs right now, doing over 800 damage if he charges his rocks into a vehicle, or around 350 if he stomps in the middle of a vehicle. This pr changes it so each charged rock hit will do about 50 damage, totaling 150 damage, and stomp doing 63 damage. Primal wrath's earth pillars do the equivilant of 3 charged rocks.
## Changelog
:cl:
balance: Reduced the damage multiplier of behemoth's abilities against vehicles from 10 to 1.8
/:cl:

### CODE REVIEW

**Comment by Wisemonster** [comment]
As a side note, behemoth rocks currently will do 0 damage if the rock is launched through click-dragging.

**Review by Lumipharon — CHANGES_REQUESTED** [review]
this change nerfs all vehicle damage, not just multitile vehicle damage. THis was presumably set very high with mechs in mind.

**Comment by Wisemonster** [comment]
Ok, what I could do is add a specific check to see if the target is a mech before calculating damage.

**Comment by Lumipharon** [comment]
ye, see what I did with warlock for reference

**Comment by Wisemonster** [comment]
Alright, added a mech check

**Review by Lumipharon — APPROVED** [review]
this is kind of a cursed way to do it but eh.

**Pull request merged**
