### PR TITLE
Hypospray belt and glass bottle rework

### PR DESCRIPTION
**Pull request by Losenis**
## About The Pull Request
Draft while working on this. Increases bottles to 240u to match capacity of pill bottles and reworks the hypobelt to be centered around reagent bottles than pill bottles and kits. This should be safe to work with given that marines are currently chemlocked, so they can't use the reagent bottles anyway since you can't even sip from them.

# Idea:
Separates the hypobelt from lifesaver belt to fulfill a different playstyle rather than overlapping and becoming either a flat upgrade or flat downgrade. Now the hypobelt (probably renaming it to reagent belt) will store only reagent bottles, healthscanner, and hypospray.

Using hypospray with pill bottles means you're dunking 15u of reagents into a hypospray that unless you're using on like 10 people, will end up being wasteful if you're healing a guy with 40 brute damage with 15u of bicaridine. That is, if you're even using the hypospray rather than feeding him the pill directly. This is where the reagent belt will come in: It'll allow for a different more logistic-oriented playstyle that allows you to control how many reagents you give the marine so as to lengthen your supply of reagents. The marine with 25 brute damage can be given only 5u of bicaridine rather than wasting a full pill, and so on with all other factors.

The downside of this is that the corpsman will have to focus on a marine more since he'll have to do math in his head to figure out the amount of reagents to use if he doesn't just magdump the whole hypospray into him. Inevitably, this is the strength of the lifesaver belt for corpsmen that have to treat 20 marines asap. Another downside will be that given that you're only going to carry reagent bottles, you need to dedicate other slots to splints and kits, or cannibalize the splints from other marines before reapplying them; this coincides with the playstyle of making your supply last as long as possible, in any case.

## Why It's Good For The Game
Different playstyles good

## Changelog

:cl:
add: Corpsman Reagent belt, replaces hypospray belt. Focuses entirely on reagent bottles and skips everything else.
balance: Reagent bottles up to 240u, same storage efficiency as pill bottles, different usage. No, that doesn't include meraderm bottles.
qol: Reagent bottles now (mostly) have overlay text.
/:cl:

### CODE REVIEW

**Comment by BlueHNT** [comment]
This is painful.

**Comment by Losenis** [comment]
>Bottles 60 -> 240 is too much

You can refill hyposprays from a pill bottle. There's really no reason to use bottles given it kills your total supply so much.

**Comment by BlueHNT** [comment]
> You can refill hyposprays from a pill bottle. There's no reason to use bottles given it kills your total supply.

I mean it makes sense to some degree.

You can't properly use Hypos if you're not a medic, reagent bottles are only handy to chemistry and Vali guy.
It is however stronger for medics than pill bottles at this rate since you can carry the same amount with an instant injection at hand, it will probably also be better for the single fact you can keep 2 for which 1 will be combat drugs and the other for everything else... 3 if you want a dedicated one for inaprov/rr

**Comment by GreatKingWombat** [comment]
> > Bottles 60 -> 240 is too much
> 
> You can refill hyposprays from a pill bottle. There's really no reason to use bottles given it kills your total supply so much.

Pill bottles can't be used as beakers though. This would put regular ass reagent bottles somewhere between large beakers and bluespace beakers.

**Comment by BlueHNT** [comment]
How about this, remake the PR to make the bottles be unique ones to the reagent belt independent and not deleting my beloved hypobelt. 

That way you can keep the normal 60u in the vendors while having unique 240u ones usable SOLELY for the belt.

**Comment by Losenis** [comment]
>Pill bottles can't be used as beakers though.

Marines got chemlocked already. The only thing this'd do is make the bluespace beakers being stolen by some valitard less of a pain in the ass to deal with.

**Comment by Lumipharon** [comment]
I am confused as to the point of this. As mentioned above, pills go into hypos, so you're just reinventing pill bottles but only in liquid form, which is all good and well but a medic can just vend the pill bottles anyway

**Comment by Losenis** [comment]
You can grab specific amounts of reagent in the hypospray from a glass bottle, be it 1u or 10u or any number under 15. You can't do that with pill bottles, it's the full pill whether you like it or not. It starts making a difference in the long run for whoever wants to run that playstyle.

Otherwise there's no real gimmick to run hypobelt with other than powergaming the 120u hypos and looting a lifesaver for the same benefit.

**Comment by BlueHNT** [comment]
>powergaming hypobelt
are you hearing yourself? Sure let me powergame by being completely useless for 20 minutes after I use up my 120u of bicaridine..
or let me replace all of the meds with combat meds making me an overglorified combat stimmer.

I would agree if there were some combos you could only do with Hypos, BUT THERE ARENT ANY. It's just a more annoying lifesaver belt and a gimmick Mr powergamer

**Comment by BlueHNT** [comment]
> But I'm repeating what you just said here.

I actually use the hypobelt cuz its my kinda niche, but it's pretty much just cool shiny double sized hypos..

**Comment by Xsdew** [comment]
Optimization and precision are not needed when the chemicals are all provided to you in large quantities, and in some cases infinite. Precise dosage has gone extinct as that was traditionally done with bottles and syringe (so when this code base was bay circa 2014)

For there to be a meaningful choices in how you administer chemicals, the pill bottle must die. That way you can have a variation of ways to disperse chemicals. Which mainly would be a delay in ingestion (pill) versus quick inject (Hypo)

**Comment by Losenis** [comment]
>Optimization and precision are not needed when the chemicals are all provided to you in large quantities, and in some cases infinite
mf try being one of the corpsmen here and come back to me, infinite will start becoming finite stupidly fast

image

**Comment by Xsdew** [comment]
> 

You are under the assumption that marines don't carry their own medication. As a corpsman you are mainly focusing on defibbing the unga and kitting the unga. With auxiliary responsibility of apply splints and dealing with permanent damage when it comes up.

All basic supplies are infinite. With req it can be delivered anywhere.

**Comment by Losenis** [comment]
>You are under the assumption that marines don't carry their own medication

There's a big number that don't, funnily enough. Some don't even realize they need medication, and with the sudden influx of rookies there hasn't been a round I haven't seen a marine walking around wth 50 organ damage on his chest due to a frac he doesn't even know about.

**Comment by Xsdew** [comment]
> 
> And whether that is true or not, it doesn't fix the issue of hypobelt being a flat downgrade to lifesaver belt. Power to people who use them, it's just a game after all, but they're not going to tell me it does anything lifesaver can't do better.

The Hypo belt shouldn't really exist. You can use a Medkit pouch, with seven slots, to carry the big hypo and 6 other pill bottles. And you keep the belt slot open for a medrig or life saver.

The Medical Rig Belt and Life Saver belt compete on the quantity and size of the items each can hold. The hypo belt is for one use case than can be done similarly with a pouch slot. It does not complete for the belt slot.

**Comment by Losenis** [comment]
>The Hypo belt shouldn't really exist

Well, this PR is replacing it. You could consider it skipping the deletion pr and addition pr straight into the replacement.

**Comment by Xsdew** [comment]
> > The Hypo belt shouldn't really exist
> 
> Well, this PR is replacing it. You could consider it skipping the deletion pr and addition pr straight into the replacement.

test

The only thing that will change with this PR is that bottles are now the same quantity as pill bottles at 240units. And can you still ignore the hypo belt.

**Comment by Losenis** [comment]
>The only thing that will change with this PR is that bottles are now the same quantity as pill bottles at 240units. And can you still ignore the hypo belt.

Yes that's, that's kind of the intended change. This isn't a massive groundbreaking rework. You could argue the same thing about putting 240u pill bottles in there and the same argument would apply vs the lifesaver. Hell you actually can right now, it's my standard loadout by shoving combat injectors into pill bottles in a medkit pouch with a hypo and a scanner.

If it's not your playstyle, then I'm sorry but you're not really the target demographic of the pr, just keep using the lifesaver belt.

**Comment by Mrrpip** [comment]
Okie-dokie, here's my questions as it's no longer a draft.

Do you think this will affect vali at-all in the long run? (Though I think it's unlikely as they can just pill - into beaker/bottle - into vali)

But more importantly, I believe syringe cases spawn mapside/in certain first aid kits. Is it alright to let smort ungas potentially put 720u of chems in a small sized syringe case that can fit in their webbing or bag?

**Comment by BlueHNT** [comment]
I've never seen someone shut down a project this fast

**Comment by Losenis** [comment]
>Do you think this will affect vali at-all in the long run?

I've seen a good bunch of them actually steal the bluespace beakers. I don't think there's a rule against it given that even when I ahelped the two beakers stolen, there wasn't a replacement. If anything it only makes the impact of vali stealing said beakers less impactful, since even though the beaker is 300u, you still only need 240u for doing chem. I believe hypos also work for vali so they can just go pill bottle hypo as you said.

>But more importantly, I believe syringe cases spawn mapside/in certain first aid kits. Is it alright to let smort ungas potentially put 720u of chems in a small sized syringe case that can fit in their webbing or bag?

Syringe cases were removed from lifesaver kit, and if it turns into an issue it can be removed from other things. I don't think syringe cases are widely available enough to be an issue regardless, since I haven't come across them in normal gameplay as squad marine.

**Comment by LeAntek** [comment]
Bad change in my opinion.

I've always felt the actual advantage of hypobelt over the other belts is the instant application speed. This was due to the many hyposprays available which allowed pre-made mixes to be applied instantly. (Seriously who the fuck walks around with an empty hypospray)
This forces the player to either run a general-purpose mix of literally everything or spend time preparing mix for every marine (thus nullifying hypo's advantage).
If anything this change would barely change anything.

Perhaps this could be alleviated by adding a second or third hypospray slot? Not even a free one just some more slots so I can keep a spare BKTT hypo to mindlessly inject into marines.

**Comment by Losenis** [comment]
>Perhaps this could be alleviated by adding a second or third hypospray slot?

Hypo slots aren't limited, that's only the starting content. You can ditch bottles you don't want and put more hypos in. Given hypos are in vendor unlike the big ones, and glass bottles will also be in vendors, I'm confident you can rearrange the belt to your liking with different hypos and bottles and then save it to a loadout to have as soon as you start a round.

**Comment by Arctrooper8** [comment]
The name change and sprite change don't really make much sense. Why make it have the same sprite as lifesaver when you could just keep using the unique hypospray belt model. And why change the name when it's still just a hypospray focused healing method?

**Comment by Lumipharon** [comment]
other pr got merged

**Comment by Losenis** [comment]
>other pr got merged

Relevancy? The PR is just "I gave it another hypo".

**Pull request closed without merging**
