### PR TITLE
Silo less collapse gone

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

A lot of people are asking for this, so let's try it out. 

Definitly needs a feedback vote, and a TM. Probably after balance freeze?

Killing all silo no longer proc a timer for the defeat.

To compensate, and probably because it will cause xeno to put silo a bit more, reduce the silo output from 0.5 to 0.45

## Why It's Good For The Game

Pros: Make silo destruction less critical. Xenos can now leave the silo without it being an automatic failiure. IMO, this is just a psychological effect, silo less collapse can be easily managed with putting small silo, but most players don't think like that.

Cons: Xenos will probably be more careless when putting them, leading to stupid silos being killed in no time.
Marines will no longer have that objective formally stated, so they'll probably look for silo less which will be their downfall
Admin will have to end up delay again manually

## Changelog
:cl:
balance: Silo less collapse no longer exist. An hive is dead after all its member are dead or hive rulers are dead for 5 minutes
balance: Output of silo changed from 0.5 to 0.45 , to account for xeno probably putting them more often
/:cl:

### CODE REVIEW

**Comment by Dolth** [comment]
Cool.

**Comment by Losenis** [comment]
>Be SL
>Deploy
>Shutters open
>No silos, cap first miner and tell everyone to chill and just stay in fob till xenos place pools
>The ones that came to play a game rather than alt tab in fob after alt tabbing in alamo after prepping run out, can't tard wrangle them
>The others are just alt tabbing in fob
>RO is buying 104 points of crayons
>Xenos and us are now in an arms race of boring each other out to see who suicides first

Alternatively

>Manage to kill all silos
>Xenos don't give a single shit and just go around cocooning/psydraining till they can afford more silos even if it takes 2 hours of merry go round

If the other psydrain pr goes through, pools will simply be another loss condition for marines compared to old silos. Given marines will be absolutely split on those who want to push and those who want to cadehug there'll be little reason to delay pool placement as much as possible to have that number push out rather than everyone at once with a sense of direction. You might as well remove pools entirely if it'll be that minuscule a thing to the round as a whole. Biggest impact pools have is lengthening fobsiege because suddenly xenos don't have to care for the xenos suiciding at the cades while still having zero sieging tools other than boilers and hoping for no TLs.

**Comment by BraveMole** [comment]
> > Be SL
> > Deploy
> > Shutters open
> > No silos, cap first miner and tell everyone to chill and just stay in fob till xenos place pools
> > The ones that came to play a game rather than alt tab in fob after alt tabbing in alamo after prepping run out, can't tard wrangle them
> > The others are just alt tabbing in fob
> > RO is buying 104 points of crayons
> > Xenos and us are now in an arms race of boring each other out to see who suicides first

If marines are cadehugging, pop silo. Simple as that

> > Manage to kill all silos
> > Xenos don't give a single shit and just go around cocooning/psydraining till they can afford more silos even if it takes 2 hours of merry go round

One psy drain gives 1/8th of a xeno (siloing gave 1/4th roughly), and 60 psy points (40 later). That's at best 1/20th of a silo.

So they'll be able to go around less than in old distress, without silos

**Comment by Swagile** [comment]
while lose's points are exaggerated, yeah

this is making pools more and more like old silo; bandaids upon bandaids

now its just a punishment for marines because we get the same issue as old silos; xenos constantly running and never engaging marines till marines get bored, split, die, rinse and repeat because the only objective we have (kill pools) is gone

its already an issue with small pools; xenos just place small pools as a strategy now to lure out bored ungas and if they don't push, they just afk waiting for them to push

this just makes cadehug tadpole near a plat miner the only viable strategy to force xenos to place all pools, because otherwise your stuck with xenos who never ever want to engage till they can full wipe you when marines get bored

🤷🏻‍♂️

**Pull request closed without merging**
