### PR TITLE
Removes the false illusion that the FC has a special headband

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

image
See that FC headband option? It's fake, it gives you a basic red headband that doesn't have any more armor or even look cool.

## Why It's Good For The Game

Clears up confusion about the FC having a specific headband similar to their beret. And no other class has their vendor give out headbands.

## Changelog
:cl:
delete: FC loadout vendor no longer offers the false promise of a headband specially for FC.
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
Child of: https://github.com/tgstation/TerraGov-Marine-Corps/pull/9755

**Review by TiviPlus — APPROVED** [review]
code ok @Kuro020 pr

**Comment by Arctrooper8** [comment]
> code ok @Kuro020 pr

This is just the black headband sprite, it's already in the game I just gave it more armor.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
image
Project lead has spoken, you can't use the sprite for this

**Comment by Arctrooper8** [comment]
> image Project lead has spoken, you can't use the sprite for this

How bothersome, I wish people gave reasons as to why.

**Comment by Arctrooper8** [comment]
David says no FC headband until I add catgirls and I still haven't used MJP's cursed helmet mod sprite to make a motion detector cat ear helmet mod. One day, one day

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
