### PR TITLE
attack_hulk

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
Moves all hulk attacks in attack_hulk, further iteration will come with obj take_damage

### CODE REVIEW

**Comment by Rohesie** [comment]
Is this taking the component route?

**Comment by spookydonut** [comment]
> 
> 
> Is this taking the component route?

sort of but not really

**Comment by Rohesie** [comment]
Set testing label once conflict is resolved.

**Comment by spookydonut** [comment]
obsolete

**Pull request closed without merging**
