### PR TITLE
Reqtorio Expansion V 1.0

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Adds more stuff that can be constructed via Reqtorio.

List is as:
Minigun Powerpacks
Razorburn nades (small)
All AMR ammo
All Howitzer shell ammo
## Why It's Good For The Game
Expands and gives more options for Reqtorio.
## Changelog
:cl:
add: Added more recipes for Reqtorio (Minigun ammo, Razornades, All AMR ammo, All Howie Shells)
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
Powerpacks are pointless, they are very cheap for the amount of ammo, mass production of them is just inconvenient and inneficient, as all the powerpacks wont get used.
Also, fear the razorwire spam.

**Comment by Derrick2Electricboogaloo** [comment]
> Powerpacks are pointless, they are very cheap for the amount of ammo, mass production of them is just inconvenient and inneficient, as all the powerpacks wont get used. Also, fear the razorwire spam.

Same could be said about all the ammo you can buy, it is all cheap, it is about mass production and getting more. Incentive to building the factory is that you can make a shit tone more than you can buy. I could just buy 5 SG drums or bins for 25 points, but I would rather build a factory and buy the components for the same price and get double the amount.

**Comment by Lumipharon** [comment]
Not sure if making razor easier to spam is a good idea.

**Comment by Losenis** [comment]
Should probably present the math on how many points total a razornade would cost given that if it's the one I'm thinking of, it'd be the equivalent of 5x3 metal sheets to craft manually. With a full stack of metal giving 16 razorwire (with 2 metal leftover) at 10 points per stack, each nade would need to be less than 3 points to break even on whether it's better to make that factory or just order more metal sheets.

Not just that, metal sheets can be used for a lot of other things while razornades have a tendency of wasting razorwire if it doesn't land on a + tile pattern that isn't completely clear.

**Comment by Oscari-pog** [comment]
> > Powerpacks are pointless, they are very cheap for the amount of ammo, mass production of them is just inconvenient and inneficient, as all the powerpacks wont get used. Also, fear the razorwire spam.
> 
> Same could be said about all the ammo you can buy, it is all cheap, it is about mass production and getting more. Incentive to building the factory is that you can make a shit tone more than you can buy. I could just buy 5 SG drums or bins for 25 points, but I would rather build a factory and buy the components for the same price and get double the amount.

SG ammo is used by all SGs and burns through quickly.
Powerpacks are used by a gun that already has a investment cost, so youll have 1-3 people using it at most. With 500 bullets per pack, and 5 points for a powerpack, you have 100 bullets for one point. Mass producing these is just pointless. You arent gonna burn through so much ammo.

**Comment by Losenis** [comment]
Also you can't carry multiple powerpacks easily, while you can shove more bins into your backpack. The bottleneck in terms of ammo for minigun isn't how much there can be, it's how much can be reasonably carried.

**Comment by Naaanii** [comment]
> Not sure if making razor easier to spam is a good idea.

It's not as easy with the high base cost.

**Comment by Naaanii** [comment]
> Should probably present the math on how many points total a razornade would cost given that if it's the one I'm thinking of, it'd be the equivalent of 5x3 metal sheets to craft manually. With a full stack of metal giving 16 razorwire (with 2 metal leftover) at 10 points per stack, each nade would need to be less than 3 points to break even on whether it's better to make that factory or just order more metal sheets.
> 
> Not just that, metal sheets can be used for a lot of other things while razornades have a tendency of wasting razorwire if it doesn't land on a + tile pattern that isn't completely clear.

20 points for 50 metal via req.

50 points for a razornade box with 20 nades.

50 points for the razornade refill that will make 30 razornades, not including the cost of the factory parts.

**Comment by Losenis** [comment]
Oh right it was 20. Yeah that should be good given razornades need all open spaces to not waste razorwire.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
