### PR TITLE
Xenos targeting removed

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Xenos can't chose which limb they target anymore, it's random. For the record, it was previously a 70% chance of hitting the targeted limb, or it was a random body part that was hit

## Why It's Good For The Game

Remove the need to balance each limbs, which is a hot subject among maintainers. The "target right arm" is a meme, and not really balanced IMO. This makes marines a little bit tankier (no more right arm that's broke or cut off in 4 secs), which is I think a good thing for balance

## Changelog
:cl:
remove: Xenos can't target a specific limb. They will hit a random body part
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -24. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Chaznoodles** [comment]
"You can now no longer tactically approach combat regarding people wearing berets or harnesses"

Removes xenos choice in where they're attacking, turning them effectively into simplemobs that have no real choice in where they hit. No.

**Comment by Smudged** [comment]
I agree with Chaz, this simply removes xeno choice and if the damage is really "random" you just have a mixed bag of random slashes on a random assortment on limbs that may or may not contribute to actual damage. Instead of being able to choose chest, which has a very high-armour value and choosing to attack it to create organ damage, or a hunter choosing to hit arm so the marine drops their weapon, this just creates an RNG game for xeno's which disregards choice or options.

**Comment by BeloneX** [comment]
> "You can now no longer tactically approach combat regarding people wearing berets or harnesses and are crippled in terms of personal choice as a melee-based xenos"
> 
> Removes xenos choice in where they're attacking, turning them effectively into simplemobs that have no real choice in where they hit. No.

Dismemberment is not good game design, having a mechanic that instantly kills you or prevents you from properly playing the game **is not good game design**

**Comment by Chaznoodles** [comment]
> Dismemberment is not good game design, having a mechanic that instantly kills you or prevents you from properly playing the game for about 15 minutes **is not good game design**

Noooo you can't just approach situations tactically and change from chest which can cause organ damage via broken bones to the arm to stop them using their weapon effectively but not causing DOT via organ damage or to the head if they're a snowflake and must be punished noooo dismemberment and player choice bad

**Comment by SplinterGP** [comment]
This makes no sense whatsoever, if aiming right arm is way too good you nerf it, or make only targetting chest available, this literally combines both problem making it not better in any sense as the xeno will literally hit any random limb and probably kill the marine before any bone even breaks, half of what the targetting system was, double the problem of the targetting system and of removing it.

**Comment by DrCrawler** [comment]
I disagree, this does not contribute to the game in ANY way accept to just buff the marines you are probably maining. You can just nerf it by making the targeting more simplistic. Example: You can only target the body, the head or a whole limb (Leg+foot or Arm+hand) where it is a 50/50 chanse to damage one of the parts. If you want to cripple one of the sides, you will not do it in such an easy way. This pull request serves no purpose and i do not want this to get somehow merged.

**Comment by BeloneX** [comment]
> Removing player choice is not good game design. Removing it in such a way that the chance of causing long term damage to a marine is miniscule even worse. The knock-on effects of this PR were not thought about in the slightest.

Dismemberment is not good game design, having a mechanic that instantly kills you or prevents you from properly playing the game for about 15 minutes is not good game design.

**Review by BeloneX — APPROVED** [review]

**Comment by TiviPlus** [comment]
I see no reason to remove xeno player choice for an arbitrary balance strawman

**Pull request closed without merging**
