### PR TITLE
Valhalla Update

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Adds few unadded things to valhalla req vendor. Anything I missed can also be added. (Im not touching sentries or sentry code.)

Railgun ammo
HvH nades
Suicide vest
Foam, WP, impact and training nades
Xenohud

Seasonal Vendor
Regular DB
Sawn off
SVD
SOM laser weapons
PMC weapons

Reqtorio gear

## Why It's Good For The Game
Updated valhalla good.
## Changelog
:cl:
add: Added stuff to valhalla.
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
While you are at it, would it be possible to add guns that are just entirely unavailable to the seasonal/req vendor too? Like the PMC guns and volkite weapons.

**Comment by Luxyboo** [comment]
think you could add a normal marine vendor and make it so xenonauten comes from the loadout vendor?

**Comment by Zangeiti** [comment]
would it be possible to be a combat robot when spawning into valhalla?

**Comment by chizzy376** [comment]
Still no real req platform to try reqtorio with :(

**Comment by Naaanii** [comment]
> think you could add a normal marine vendor and make it so xenonauten comes from the loadout vendor?

> would it be possible to be a combat robot when spawning into valhalla?

Not in this PR unfortunately

**Comment by Naaanii** [comment]
> Still no real req platform / req factories / req refills to try reqtorio with :(

Added

**Comment by Lumipharon** [comment]
Why do we need reqtorio in valhalla? conveyors cause lag, there really shouldn't be any reason to have them there.

**Comment by Naaanii** [comment]
> While you are at it, would it be possible to add guns that are just entirely unavailable to the seasonal/req vendor too? Like the PMC guns and volkite weapons.

Added

**Comment by Naaanii** [comment]
> Why do we need reqtorio in valhalla? conveyors cause lag, there really shouldn't be any reason to have them there.

There is already a lot of clutter in valhalla itself, not to mention an autolathe and conveyors already there. If people wanted to lag the server, they could tbh. I don't think allowing for reqtorio sandbox to find interesting combinations would be a massive issue.

**Comment by RipGrayson** [comment]
> Why do we need reqtorio in valhalla? conveyors cause lag, there really shouldn't be any reason to have them there.

Reqtorio was a highly requested feature for Valhalla while it was being mapped, I have nothing against removing it if you think it's causing problems

**Comment by Lumipharon** [comment]
If you think its fine, that's alright

**Pull request merged**
