### PR TITLE
powerfists are now bulky

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
unsurprisingly a big fist is unsurprisingly a bulky item

## Why It's Good For The Game
powerfists shouldn't go in bags

## Changelog
:cl:
balance: powerfists are bulky items
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -163. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by BeloneX** [comment]
They're slightly bigger than a human fist, they absolutely can fit into bags.

**Comment by Tennessee116** [comment]
> You currently have a negative Fix/Feature pull request delta of -163. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

~~h o w~~

> ## About The Pull Request
> unsurprisingly a big fist is unsurprisingly a bulky item
> 
> ## Why It's Good For The Game
> powerfists shouldn't go in bags

Depends, the average human fist is relatively small compared to a bag. So how _big_ of a fist are we talking? From what I can tell, based on the sprite work, I don't see a problem with it fitting in a bag.

**Comment by Pariah919** [comment]
well game balance wise it shouldn't fit in bags otherwise you can just ignore the entire charge mechanic

**Comment by BeloneX** [comment]
> well game balance wise it shouldn't fit in bags otherwise you can just ignore the entire charge mechanic

People just put the powerfist onto their belt slot so this will change nothing balance wise.

**Comment by BraveMole** [comment]
> People just put the powerfist onto their belt slot so this will change nothing balance wise.

What do you mean? If they fit it on their belt spot then they don't have a belt anymore, how is that not a balance change?

**Comment by BeloneX** [comment]
> > People just put the powerfist onto their belt slot so this will change nothing balance wise.
> 
> What do you mean? If they fit it on their belt spot then they don't have a belt anymore, how is that not a balance change?

Nobody uses the powerfist with rifles.

**Comment by fernandos13** [comment]
_coughs!_
i kinda. like to use it as my last resort gun as corpsman. more of a utility thing and i CANNOT give away my belt slot. so i'd say yes people use it inside their backpacks. but i think those who do see it more of a utility save weapon than a damaging and pratical combat weapon. 

i feel like i personally cannot say much about it. since i can only use it due to the fact it FITS in the backpack. and if it didn't i wouldn't ever touch it

but id say if this changes passes please. make it at least fit the SUIT storage too

**Comment by AndroidMK2** [comment]
I would stop using powerfists forever then, they are created to give at least a slight probability of escape when you ran out of ammo or lose your gun entirely. Giving up a belt slot to have it is not good for basically any role other than regular marines but even then there are better stuff to put there.

**Comment by TiviPlus** [comment]
Powerfist size is fine

**Pull request closed without merging**
