### PR TITLE
ADD BOXING RINGS TO ALL EORD ARENA

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

title

## Why It's Good For The Game

becuase i want to box more in eord

ooc: novaepee: boxing fight rn

## Changelog

:cl:
add: ADD BOXING RINGS TO ALL EORD ARENA
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
Make EORD-only boxing gloves that give 200 armor to everything but melee

**Comment by novaepee** [comment]
> Make EORD-only boxing gloves that give 200 armor to everything but melee

I make that a thing when you can spawn in as a boxer.

**Comment by Al-1ce** [comment]
> I make that a thing when you can spawn in as an EORD boxer.


The ability to select which faction/loadout in EORD would be really, really cool. No idea how to code that though.

**Review by TiviPlus — APPROVED** [review]

**Review by RipGrayson — CHANGES_REQUESTED** [review]
I don't like how the boxing ring here is just randomly in the middle of the shuttle crash site
van14

Please move it somewhere here, or north of this area
van15

**Pull request merged**
