### PR TITLE
Auto-punctuation.

### PR DESCRIPTION
**Pull request by BeloneX**
image
image

Ports:
https://github.com/BeeStation/BeeStation-Hornet/pull/156
https://github.com/BeeStation/BeeStation-Hornet/pull/236
## Changelog
:cl: CthulhuOnIce, BeloneX
add: Added automatic-punctuation.
/:cl:

### CODE REVIEW

**Review by Hughgent — APPROVED** [review]
LGTM.

Feature freeze though?

**Comment by BeloneX** [comment]
> LGTM.
> 
> Feature freeze though?

This is such a minor "Feature" honestly.

**Comment by TiviPlus** [comment]
@Hughgent  its on balance changing content not QOL

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-7). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
