### PR TITLE
Adds rappel to tadpole (again)

### PR DESCRIPTION
**Pull request by breadhunt**
## About The Pull Request

I completely fucked my branch; continued version of https://github.com/tgstation/TerraGov-Marine-Corps/pull/15943

Don't merge until I figure out what to replace the firearms skillcheck with but should be fully ready for TM. Still **very** open for walance concerns because this hasn't been tested since before the Kuro coup
## Why It's Good For The Game

See https://github.com/tgstation/TerraGov-Marine-Corps/pull/15943
## Changelog
:cl:
add: Adds rappel system, turning POs into glorified elevators once more.
add: Adds the spare rappel cord box. Required to repair the rappel system.
imageadd: rappel system sprite, rappel cord box
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
God I hope this gets merged, otherwise TAD continues to collect dust, with noobs occasionally trying it out

**Comment by Apple-107** [comment]
please stop marines from shuffling on/off the rappel as that stops the marines already winding up the rappel down

its just jank, if marines want to rappel fast they will either A) climb onto the rappel or B) put a dense object on the rappel to stop you from going on said tile

**Comment by FosterGrime-Heymynameslouie** [comment]
image
this is a really good addition, doing tactical drops with marines and sometimes rsr, and I think this should get merhged instantly

but also some suggestions for improvements would be tacmap icon and maybe a way to make the rope go up on its own on command by the PO? I am unsure if its already a feature and im just stupid, and also I dont know if this is a feature but the rope seems to go up on its own when marines use it from groundside, maybe a way for marines to climb up wtithout rope undeploying? really cool pr thats 2 years old by now, speedmerhg!

**Comment by Autisem** [comment]
add the ability for 1 marine to rapple up some one else, like a body. would make medical rescues really cool

**Comment by breadhunt** [comment]
> please stop marines from shuffling on/off the rappel as that stops the marines already winding up the rappel down
> 
> its just jank, if marines want to rappel fast they will either A) climb onto the rappel or B) put a dense object on the rappel to stop you from going on said tile

yea I designed it wanting marines to HAVE to take turns or get fucked but literally everyone is saying it's jank so ok
bested by the indomitable unga spirit yet again

tacmap icon and cams are cool, dropping flares and nades down is cas territory

> add the ability for 1 marine to rapple up some one else, like a body. would make medical rescues really cool

no, clear an LZ and land tadpole for this, it's even cooler (and also not ass for xenos)

**Comment by Mantlecrawler** [comment]
If this allows marines to rappel down before shutters open, make sure it also disables quickbuild via the appropriate signal in resinshaping.dm

**Comment by breadhunt** [comment]
> If this allows marines to rappel down before shutters open, make sure it also disables quickbuild via the appropriate signal in resinshaping.dm

afaik tadpole launching whatsoever disables quickbuild

**Review by Kuro020 — APPROVED** [review]

**Pull request merged**
