### PR TITLE
NTmed pill bottles revert

### PR DESCRIPTION
**Pull request by goose4429**
## About The Pull Request

#10321 #10466 removed a lot of roundstart-available basic pill bottles, as well as decreased their amounts in NTMed+. This PR restores their number to values closer to pre-PRs. These PRs are good, but decrease in roundstart pills just forces people to rush chem. This concerns only the medic vendor, not the Marine Med.

## Why It's Good For The Game

Rush chem bad.
Restore balance good.

##Notes

Q: HACKINGNHGH
A: It was an option before, it is an option now. Just before more pills were in kits and belts.

Q: POWERCREEP
A: You can literally go to chem, take pill bottles, and move pills from packets to pill bottles

## Changelog
:cl:
balance: more basic pill bottles to NTMed+
/:cl:

### CODE REVIEW

**Comment by Dolth** [comment]
> > Are pill bottles from marine med gonna be infinite or finite like before?
> 
> MM has only pill packets, as intended. This only concerns the medic vendor. Last PRs decreased amount roundstart from approx 25 to 6, which is meh

Oh in that case have my upvote. But I am still convinced locking pill bottles for marines would save the hassle because you can just make an empty pill bottle and empty packets into them or just hack the vendor.

**Comment by goose4429** [comment]
> Oh in that case have my upvote. But I am still convinced locking pill bottles for marines would save the hassle because you can just make an empty pill bottle and empty packets into them or just hack the vendor.

Exactly. Hard to solve this problem, but I'll try!

**Comment by Nanu308** [comment]
Put Ckey next to the CL at the top, so people can see who added it ingame.

**Review by TiviPlus — APPROVED** [review]

**Review by Pariah919 — APPROVED** [review]
Seems good to me, pill bottles themselves are their own argument for another day.

**Pull request merged**
