### PR TITLE
Add auto climbing

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Bumping into a climbable structure will make you climb automatically

## Why It's Good For The Game

Gotcha CM

## Changelog
:cl:
qol: Add auto climbing
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
WINDOWFRAME GAMING

**Comment by Lumipharon** [comment]
Probably too much to ask, but is there a way to make this only work if you hold down the movement key?

Not a huge deal, but I imagine there will be the occasional funny when someone bumps a cade or whatever without realising, and vaults over and dies

**Comment by novaepee** [comment]
The obstacle course that is the Crucible is near

**Comment by BraveMole** [comment]
> Probably too much to ask, but is there a way to make this only work if you hold down the movement key?
> 
> Not a huge deal, but I imagine there will be the occasional funny when someone bumps a cade or whatever without realising, and vaults over and dies

No, not possible

**Comment by Losenis** [comment]
>Merged without even a TM
>Breaks shit

Sasuga bluenames

**Pull request merged**
