### PR TITLE
Moves Optical Meson Scanner to Engineer Clothing Vendor

### PR DESCRIPTION
**Pull request by Three333Digit**
## About The Pull Request
Title.
Removes Optical Meson Scanner from EngiVend and Welding Goggles from Essential Engineer Kit, making them a choice in the engineer clothing vendor instead.

## Why It's Good For The Game
Why not? It's in the EngiVend meaning only Engineers have access to it and I've only ever seen Squad Engineers use this. Plus, this makes the optical meson scanner loadout friendly.

## Changelog
:cl:
del: removes optical meson scanner from engivend
del: removes welding goggles from essential engineer kit
balance: moves them to engineer clothing vendor instead
balance: meson or healthhud choice in synth vendor
/:cl:

### CODE REVIEW

**Comment by InterroLouis** [comment]
The engivend is public access.

**Comment by Naaanii** [comment]
There's no real reason to make this engineer exclusive.

**Comment by Naaanii** [comment]
> > There's no real reason to make this engineer exclusive.
> 
> Why would non engie use it? Are you talking about CE or synth?

CSE, ST and Synths, yeah. Sometimes use it on PO too if there are no points for imagers in req.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Maybe give mesons to CSE, ST and synth as well

**Review by BraveMole — APPROVED** [review]

**Comment by Araulius** [comment]
> > There's no real reason to make this engineer exclusive.
> 
> Why would non engie use it? Are you talking about CE or synth?

well, as a marine, I use it to help determine where to fire my tl-84, and how deep. when dealing with resin.

**Pull request merged**
