### PR TITLE
nerfs tanglefoot/drain gas avaliablity substansiaually and ups the detonation time

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
reduces the grenades from 25 to 5 per req vendor so its 5+5+25 means 35 on average, which is more fine than 100 grenades of a grenade that does soft denial on an area

Nerfs the detonation time to 6 seconds, its too strong at 2 handheld, use a GL to fire this.

## Why It's Good For The Game
You get too much of this stuff. Its too easy to use without specialized equipment.
Its this or making the cl

## Changelog
:cl:
balance: tanglefoot gas amounts reduced substantially, reduced to 5+5+25, and nerfed detonation time to 6 seconds rather than 2 hand thrown
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -69. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SplinterGP** [comment]
SL should probably be able to buy them as a SL option

**Comment by neohenry** [comment]
> 
> 
> SL should probably be able to buy them as a SL option

Would also force marines to purchase grenades from req after using the grenade boxes OR use the M40 HEDP grenade more.

Keep in mind that for each Automated Weapons Racks, there are 30 M40 HEDP grenades.

I actually wonder if this reduce in grenade is a gateway to reducing ammo that marines get in the beginning.

**Comment by jroinc** [comment]
There are 100 of every grenade available roundstart (except the HEDP, which has... about 500?). This grenade does NO DAMAGE, and is not purchasable.

NO DAMAGE.

ZERO. DAMAGE.

Poorly thought out change, like every change from this guy~

**Comment by davidchan13** [comment]
> There are 100 of every grenade available roundstart (except the HEDP, which has... about 500?). This grenade does NO DAMAGE, and is not purchasable.
> 
> NO DAMAGE.
> 
> ZERO. DAMAGE.
> 
> Poorly thought out change, like every change from this guy~

This grenade detonates faster than xenos can react, meaning shrike can't fling it back.
This grenade does significant plasma drain, turning off pheros and effectively blocking abilities.
This grenade has a radius roughly 3 times the size of the boiler's bombards, with 0 downtime.
This grenade has effectively no downside to marines in the smoke that a single pill can't fix.

Marines can and have used dozens of these grenades to make their FOBs and SD defences untouchable for 10 minutes at a time, the smoke is so detrimental to smoke it's actually dumber to run into the smoke to attack marines than it would be to run across lava to escape marines.

And marines get 100+ of these stupid things for free.

**Review by Hughgent — APPROVED** [review]
variable changes

**Comment by Pariah919** [comment]
>There are 100 of every grenade available roundstart (except the HEDP, which has... about 500?). This grenade does NO DAMAGE, and is not purchasable.
>
HEDP is just the default grenade.
M15s you get 15 or 25 of if I remember right
smoke/cloak grenades aren't very useful
You don't get phosphy unless you order it or get it in crates iirc.

It should be buyable and the fact it isn't shows you get way too many in the first place.


>NO DAMAGE.
>ZERO. DAMAGE.
>
It doesn't matter that it does zero damage, it's effectively 10-15 second soft deinal that's screenwide where literally no benogorph can go into without losing all their plasma, which would be fair if you had to buy it or use it smartly but you also get effectively an infinite amount of grenades with no point cost round start for free and it can be used without specialized tools for effectively free.

>Poorly thought out change, like every change from this guy~
>
yeah sure

**Comment by Hughgent** [comment]
TM'd Since:
Commander TGMC
BOT
11/21/2020
REPO: Updating origin branch...
REPO: Merging PRs #5261, #5223, #5252, #5258, #5299...
DM: Compiling...
DM: Compile complete! Server will update on reboot.

TGMC Statbus
Winrate (Xenomorph to Marine)
46.15%
View Raw
http://statbus.psykzz.com:8080/api/winrate?delta=2

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-72). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
