### PR TITLE
PFC paygrades based on playtime

### PR DESCRIPTION
**Pull request by psykzz**
## About The Pull Request
Squad marine playtime ranks

## Why It's Good For The Game
Recognition for your playtime

## Changelog
:cl:
add: Squad marines now rank up from E1 to E3 based on playtime
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
You know what I'd love to see? Semi-persistent playtime, where the playtime the ranks come from resets if you are dead at roundend.

So if ungas win and you live, you keep it, but if they lose and you don't evac, right back to the lowest rank.

**Comment by psykzz** [comment]
I like that, ill try and think of a way to incorperate it long term.

**Comment by Chaznoodles** [comment]
how do rank up?? through time or kills??

**Comment by Mouseofthecake** [comment]
It seems to take playtime in minutes for rank-ups. Whether this means playtime is already tracked and all regulars will get E3 on testmerge, I dunno.

**Comment by psykzz** [comment]
Playtime is already tracked in minutes, very few people already have more than 10,000 minutes and those are people that have played for over a year, so im happy with it.

**Comment by psykzz** [comment]
that said right now its bugged and reading the wrong role so everyone is a PVT.

**Comment by Pariah919** [comment]
i think you should be able to go up to e3, then make going up to e4 or something based off round end

**Comment by Mouseofthecake** [comment]
so, SGs, corpsmen, and engis are E4s, SL is E5. could bump up the "utility specialists" to E5, make the SL an E6 like in CM, and make E4 based off of round-end wins/loses.
also 10k minutes is like 7 days of continuous playtime, sounds good to me.

**Comment by TiviPlus** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/4710 should fix everyone being PVT issues

**Review by TiviPlus — APPROVED** [review]
Fix worked as expected

**Pull request merged**
