### PR TITLE
Nerfs arm aiming.

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
Recently arm has been very much aimed by most people and this nerfs it, my consideration for buffing the arm its that it has same armor as chest with alot of debuffs once broken/removed, unlike leg, so i've buffed its health to 125, needing more 25 damage for delimbing, also robolimbs suck they need buffs.

## Why It's Good For The Game
Makes arm aiming not alot way superior than the other limbs, its now harder to delimb.

## Changelog
:cl:
balance: arm is now harder to delimb, max damage raised to 125
/:cl:

### CODE REVIEW

**Comment by neohenry** [comment]
oh no, that would make HvH in EORD harder so sad

**Comment by David-Stormwell** [comment]
Only 25 more damage.
Not too bad since you can get that damage in only a few slashes

**Comment by bowlofcereal** [comment]
i do not enjoy getting pounced, and then in 3 slashes my arm being broken

**Comment by InterroLouis** [comment]
> i do not enjoy getting pounced, and then in 3 slashes my arm being broken

But you do know this won't change that, right? It's just delimb threshold, not bone break damage amount.

**Comment by Losenis** [comment]
This will not do anything to help with xenos just targetting right arm exclusively and speedrunning bonebreaks on top of splints coming off in like one hit. Arm delimb isn't the crux of the issue problem, it's a symptom of xenos targetting a limb exclusively to focus all the damage. I'd sooner add inaccuracy to have hits also land on other bodyparts, and frac forcing weapon unwield/drop only helps the xenos to keep hitting you while you can't fight back properly resulting in said delimb.

**Comment by SplinterGP** [comment]
> 
> 
> This will not do anything to help with xenos just targetting right arm exclusively and speedrunning bonebreaks on top of splints coming off in like one hit. Arm delimb isn't the crux of the issue, it's a symptom of xenos targetting a limb exclusively to focus all the damage. I'd sooner add inaccuracy to have hits also land on other bodyparts, and frac forcing weapon unwield/drop only helps the xenos to keep hitting you while you can't fight back properly resulting in said delimb.

xenos all target chest otherwise though, still targetting all same limb, there's no problem on that and its the default game balance

**Comment by ThelastArchiver** [comment]
gotta be honest due to marine healing xenos need to cconcentrate on one limb to get the chance to do significant lasting damage else marines are just gonna be full live with no drwabacks 10 seconds later

**Comment by SplinterGP** [comment]
All aiming one limb aint any issue from game, xenos aim chest by default all of them when they spawn, its a placebo effect what happens on arm that much due to alot of debuffs it gives to marines, althought its HP is too low for what it does i think and delimbs arent that funny on an arm

**Comment by Losenis** [comment]
Not necessarily. It was split on some xenos targetting chest and others targetting right arm, but as more and more xenos learn about targetting right arm the damage is no longer split between the two and instead concentrated on one. Some rounds are milder since xenos are not that coordinated but it's over the damage actually being split due to those two types of players rather than there being a unified consensus in the round. If everyone targeted chest exclusively you'd still have a shitton of popped lungs.

**Comment by SplinterGP** [comment]
> 
> 
> Not necessarily. It was split on some xenos targetting chest and others targetting right arm, but as more and more xenos learn about targetting right arm the damage is no longer split between the two and instead concentrated on one. Some rounds are milder since xenos are not that coordinated but it's over the damage actually being split due to those two types of players rather than there being a unified consensus in the round. If everyone targeted chest exclusively you'd still have a shitton of popped lungs.

eh not really, people dindt always target arm, just people started more recently.

**Comment by Chaznoodles** [comment]
> eh not really, people dindt always target arm, just people started more recently.

People have been consistently aiming arm since I buffed glove armour a while back. I'm entirely content with arms being harder to remove.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
