### PR TITLE
Retired ERT adjustments

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Lowers probability of it spawning, gives the grunts shoes and makes them all augmented instead of being in wheelchairs.
## Why It's Good For The Game

Bounty requested. Apparently it was spawning too much and them being in a wheelchair made them weak. Leader still is in the minigun chair and legless however.
## Changelog
:cl:
balance: Retired ERT spawns less often, but can now walk (minus the leader)
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
I wonder if there's a way to apply something like no_drop to things you're buckled to.

**Comment by TiviPlus** [comment]
non grunts get wheelchair still just fyi

**Comment by hivemuscle** [comment]
isn't this just a joke ert?

**Comment by ivanmixo** [comment]
> non grunts get wheelchair still just fyi

there is only a leader and the regular grunt type so

**Comment by Araulius** [comment]
but... that robs the joke ert of the joke...

**Comment by hivemuscle** [comment]
> but... that robs the joke ert of the joke...

that is probably called powercreep

**Comment by ivanmixo** [comment]
They're glorified dudes with slightly better versions of a T12, compared to the other ERTs I think it'll be fine on the powercreep front lol

**Pull request merged**
