### PR TITLE
Boiler Damage Improvement vs Vehicles/Structures

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl: by Surrealistik
tweak: Boiler acid globs will now do 2x damage to most structures (barricades, sentries, etc) and 3x damage to vehicles
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
We have to refactor how damage is processed, and yet more snowflake checks just add coder debt.
Also the effect here is very minor because it only applies to boiler direct hits.
Make it so the projectile covers what was hit in acid if applicable or something like that instead, but stop adding snowflake checks.

**Comment by DominikPanic** [comment]
Agreed with Rohesie here. We can't afford to keep tacking on these changes forever.

**Comment by Rohesie** [comment]
Why are we testing it then?

**Comment by DominikPanic** [comment]
> 
> 
> Why are we testing it then?

Test-merges are temporary and undone with a single tick, we can still observe how badly coded damage tweak affects balance without polluting the codebase.

**Comment by Rohesie** [comment]
Closed for now until a solution that doesn't add coder debt presents itself.

**Pull request closed without merging**
