### PR TITLE
Vali modules removed from standard vendors, added to requisitions

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Removes vali modules from standard vendors, and adds them to requisitions as a purchasable option.
This order is worth 150 points, and includes the module, one of all vali weapons, and the manual itself.

## Why It's Good For The Game
Boasting high healing power and survivability, Vali has started to become a major issue. Its weaponry allows marines to outdo xenos in what is allegedly supposed to be their specialty, and the sheer healing lets you survive a lot more than what I personally consider healthy for balance. I tried to nerf Vali's regeneration in #14060, but after Ivanmixo turned it down, I decided to rethink my options.

So, here we are! If nerfing its healing isn't an option, then making it more limited is my next try.

## Changelog
:cl: Lewdcifer
add: Adds purchaseable Vali kits in requisitions. It is worth 150 points, and includes the module, one of all weapons, and the manual.
balance: Vali modules removed from standard vendors.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
From a design standpoint I tgink valI should be nuked.

This kinda does it, though as locking a entire playstyle at this point behind req is gonna stifle new blood into it massively.

**Comment by lKiseki** [comment]
> why does this include weapons in the req box but also leave the weapons within the basic vendor? I feel like it would make much more sense to have them be exclusive to this crate.
> 
> Not just saying this because I want my teammates to stop bringing vali weapons and blocking shots while failing to get kills xoxoxo

A part of me wanted to be a bit kind by leaving the Vali weapons in standard vendors so that the occasional melee dude can still have fun without needing reqs. I suppose I can do that, too, but I'll hold off on that for a bit.

**Comment by lKiseki** [comment]
> From a design standpoint I tgink valI should be nuked.
> 
> This kinda does it, though as locking a entire playstyle at this point behind req is gonna stifle new blood into it massively.

I kinda agree, honestly! I don't like Vali much but removing things in this game is some major taboo.

**Comment by Wirpy** [comment]
If ur gonna remove vali module, could you make a normal vendable module thats only purpose is to give a health display ;_;?

**Comment by Mrrpip** [comment]
Between this PR and the jetpack one.

I think you're building up to another Optical Scanner esque problem. Regardless, it should be interesting to see IMO.

**Comment by ivanmixo** [comment]
This doesn't address any of the issues you have with vali, you're just throwing it in req and hoping people don't bother (believe it or not, this isn't a solution)

For a start I'd suggest lowering the amount of green blood you get from attacks (and maybe lowering the suits capacity for it), should help deal with the heal being spammable.

**Comment by EvilMelonTheSecond** [comment]
Vali is a bit too high complexity for it to be reasonably sent to req hell, it'll be only used by the people already familiar with it and others will rarely try and experiment at the cost of req points. 

If vali is becoming a problem it should be balanced or removed. Req hell doesn't sound like a good idea imo.

**Comment by FosterGrime-Heymynameslouie** [comment]
> If ur gonna remove vali module, could you make a normal vendable module thats only purpose is to give a health display ;_;?

this ngl

having a module thats entirely just a health scanner would be pretty cool

**Comment by imsxz** [comment]
IMO vali is fine if jetpack is axed, tho the current jetpack PR doesn’t really address the issues with jetpack. Vali without jetpack usually gets bodyblocked and killed very easily if it tries to play in maze

**Comment by Sirsnek15** [comment]
"So, here we are! If nerfing its healing isn't an option, then making it more limited is my next try." Please stop using github PRs to nerf random marine equipment after a bad round. The recent PRs to RR and Vali have been completely unreasonable from a starting point and people still try to find a middle point between that and something that doesn't require change, however...

All the xenos really need gone is the jetpack. Boom, you've just nerfed the actually bad part of vali/shotguns without hurting vali at all and its still useable and free. And funny. And fun. And a marine hazard. And a xeno hazard.

**Comment by lKiseki** [comment]
Closed in favor of #14171.

**Pull request closed without merging**
