### PR TITLE
Armor Update 3.0

### PR DESCRIPTION
**Pull request by Kuro-ai**
## About The Pull Request

Does the changes

## Why It's Good For The Game

damn speed merges

## Changelog
:cl:
add: added prison variant clothes
tweak: gas mask and heavy helmet don't have tint anymore/armor sprites changes
balance: heavy helmet accuracy debuff from 10% to 15%
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by spookydonut** [comment]
@Kuro-ai are the item sprites meant to be the same as the on-mob sprite? it'll look weird maybe with the slightly larger sprites when they're on the floor.

**Comment by Kuro-ai** [comment]
they are,the mob sprite is big enough that using it as the obj sprite isn't a problem

**Comment by Alterist** [comment]
I recommend removing the pants section of uniforms to use as obj sprites

**Comment by psykzz** [comment]
@Kuro-ai the point being made is they might be too large.

**Comment by Kuro-ai** [comment]
> There are failing sprites
> image

fixed

**Comment by Kuro-ai** [comment]
> @Kuro-ai the point being made is they might be too large.

that was fixed on one of my commits,I deleted the leg part

**Comment by Alterist** [comment]
`marine_jumpsuit(unnused)`
👀

**Comment by Kuro-ai** [comment]
> `marine_jumpsuit(unnused)`

Variants broke too much stuff,for now I'll let them sit in the back of the truck

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-8). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
