### PR TITLE
Ammo belt can no longer hold eggs

### PR DESCRIPTION
**Pull request by jonash07**
## About The Pull Request

... and other bizzare things

egg

## Why It's Good For The Game

I don't like my butter knife being stuck in ammo storage for some reason

## Changelog

:cl:
fix: changed ammo belt storage to be more sane
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
This is a balance change - Removing the ability to carry grenades, mines, and knives isn't a fix, even if it's inefficient to do so storage wise.

**Comment by Looking4bros** [comment]
I've always found it weirder that grenades didn't fit in ammo pouches nor regular webbing instead of them fitting in the ammo belt.

**Comment by Lumipharon** [comment]
Someone please ban this egg hater

**Comment by jonash07** [comment]
downvoted into oblivion

**Pull request closed without merging**
