### PR TITLE
Removes Plasma Pistols as an attachable option

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Removes the plasma pistol as an attachable underbarrel option. Revival of #9673.

## Why It's Good For The Game
This should have never been a thing in the first place. It's a viable alternative to the UBF, which was removed from various weapons for balance reasons, mind you, yet the plasma pistol continues to exist on weapons that can't have the UBF. It's not healthy for balance, nor is it every gun having access to fire.

## Changelog
:cl: Lewdcifer
balance: Plasma pistols can no longer be used as an underbarrel attachment.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Death.

**Comment by KrabSpider** [comment]
Finally, a reason to load incendiary slugs into my masterkey. Thank you Daddy Lewdicifer.

**Review by Pariah919 — APPROVED** [review]
Cool idea that should've never made it into the real came, approved from me.

**Comment by Pariah919** [comment]
image

Underbarreled plasma pistol, you were a great weapon, you broke all balance with underbarreled attachment balance by sheer force of existing and securign kills, I used you several times and got some good assists, I will remember you. I drink water in your honor. You should've never even made it into the game.

**Comment by BonkaiB** [comment]
time for the funky under barrel to hardly be touched by anyone once again

**Comment by TiviPlus** [comment]
See bravemole pr

**Pull request closed without merging**
