### PR TITLE
Vending visual retouch & cleanup

### PR DESCRIPTION
**Pull request by Blundir**
## About The Pull Request

Retouch of about half of the vendor sprites to some degree, fixing some visual issues on some and for other making them more in line with general TGMC visual line.

## Why It's Good For The Game

Here is an example: (i've retouched a lot more)
Before -
dreamseeker_1KmZycYkcz
After - 
dreamseeker_doVjFFSm1G

Also added tons of new sprites for deny and vend icon states, here is a med vendor vend icon for example: 
dreamseeker_b2zykThuPq

Additionally fixes some typos and mistakes, which resulted in a lot of sprites not being used properly, also fixed the funny blinking vendors.
Before - 
dreamseeker_5HSo9l8HQy
After - 
dreamseeker_7xtGdiQ82R

Also reorganized unused TG sprites, now it's harder to confuse them with the sprites that are actually used.

## Changelog

:cl:
add: tons of deny and vend icon states for vendors
fix: fixed some incorrect vendor sprites and typos
imageadd: a lot of retouched vendor sprites and its states
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
the medvendor opening is so cool wtf

**Review by RipGrayson — CHANGES_REQUESTED** [review]
I'd rather you not remove the (currently) unused TG vendor icons we have. They have potential to be used for mapping flavor and if Delta is merged they'll just get added to the code again anyway.

Rest of changes are good though

**Comment by Blundir** [comment]
> I'd rather you not remove the (currently) unused TG vendor icons we have. They have potential to be used for mapping flavor and if Delta is merged they'll just get added to the code again anyway.
> 
> Rest of changes are good though

Then i'm gonna move them down to the bottom, for them to not raise confusion

**Comment by Blundir** [comment]
Done, also i didn't really give any additional touch to the unused sprites, i will if they'd find some usage in the future

**Comment by novaepee** [comment]
> the medvendor opening is so cool wtf

INSPIRATION FOR THE CONTRIBUTOR SPRITES

**Comment by novaepee** [comment]
image

also my bad on this; got lazy to fix this

**Review by RipGrayson — APPROVED** [review]

**Pull request merged**
