### PR TITLE
Removes ability to weld floor tiles into metal

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Title.

## Why It's Good For The Game

This was being abused, so off it goes.
nofungrayson

## Changelog
:cl:
balance: Welding floor tiles no longer generate metal
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Literally what is the problem with allowing marines to, of their own free will, make their own ship look like shit?
Has anyone ever even complained about the ship looking like shit because people tore up the floor tiles?

That isn't even your real reason. This is a balance change disguised as a fucking style thing in your why it's good for the game

**Comment by Derrick2Electricboogaloo** [comment]
> Literally what is the problem with allowing marines to, of their own free will, make their own ship look like shit? Has anyone ever even complained about the ship looking like shit because people tore up the floor tiles?
> 
> edit: didn't see the cl, whoops

If it is bad for beans it is bad for everyone apparently.

**Comment by iforgotmeword** [comment]
cool there goes my second way to get mats as PO how the hell I'm going to get them oh right I'm just going to steal them from FOB

**Comment by chizzy376** [comment]
Was this really an issue? It takes around 10 minutes to get 50 metal

**Comment by Aporhtonoma** [comment]
instead of straight up removing an emergency metal generation for engies which usually is also very costly since not many carry welding packs on their backs why not just remove the ability to generate metal from the shipside floortiles.Like we did with chairs and tables

**Comment by Tonklaatech** [comment]
how do we get rid of shipside xeno in vents if not the pipes

**Comment by technicianman** [comment]
"this game mechanic was being used and thats bad for some reason so im removing it" the cost of making tiles into metal is called TIME

**Comment by RipGrayson** [comment]
> instead of straight up removing an emergency metal generation for engies which usually is also very costly since not many carry welding packs on their backs why not just remove the ability to generate metal from the shipside floortiles.Like we did with chairs and tables
> 
> also what if an engie missclicks the option between rods and tiles for example do they just sit and cry cause 20 of their most possibly 50 metal is now send to the shadowrealm?

This is what the change is. It prevents welding 4 floor tiles into a metal sheet, it doesn't remove crowbarring or anything else.

**Comment by RipGrayson** [comment]
> how do we get rid of shipside xeno in vents if not the pipes

This change only prevents welding floor tiles into metal sheets, it doesn't touch pipes or vents.

**Comment by RipGrayson** [comment]
> cool there goes my second way to get mats as PO 

This sounds like a problem unrelated to this change (namely that PO's don't have metal for tad), you should probably make a PR adding a stack of metal to each tadpole.

**Review by Lumipharon — APPROVED** [review]

**Comment by Joe13413** [comment]
> cool there goes my second way to get mats as PO how the hell I'm going to get them oh right I'm just going to steal them from FOB

literally just order it like god intended

**Pull request merged**
