### PR TITLE
autoinjectors for the pill machine.

### PR DESCRIPTION
**Pull request by Hughgent**
:cl: Hughgent
balance: Pills now hold a max of 15u.
add: The pill machine can now create 30u volume autoinjectors.
add: The pill machine can now create pill bottles in many exciting colors.
refactor: redid the autoinjector icon code.
balance: first-aid pouches can now hold all types of autoinjectors.
/:cl:

[why]: It could do Pills, and bottles, now it can also do Autoinjectors.

technically no new sprites, just had to rename a bunch(all) of them.

### CODE REVIEW

**Comment by Hughgent** [comment]
**getting some fresh meds all ready.**
pill machine window
**out comes the autoinjector, fancy new(old) sprite too.**
freshjector
**stings a bit going in.**
injection results
**bit of a mess left behind.**
expended

**Comment by Hughgent** [comment]
image
**Would you look at that, pill bottles, now in color!**

**Comment by Rohesie** [comment]
60 units autoinjector? Make that 15.

**Comment by Hughgent** [comment]
> 60 units autoinjector? Make that 15.

I love making 60u pills, InaOxyTram 30 20 10 is my goto personal painkiller pill. But the actual pills I make regularly for medics are much less in unit size.
- BicaMera 7.5 7.5
- KeloDerm 7.5 7.5
- IRON 15
- Oxycodone 15
- ImiAlky 11 4
- TriBica 15 15 (old news I tell ya.)

With this in mind, I propose that pill size (by this machine) be reduced to 30u at max and make Autoinjectors (still at 60u) the new, bulky, super chem option for doctors. I say 30u only because the basic Dylovene pill is 25u.

**Comment by Ghommie** [comment]
I'm conflicted between simply suggesting to lower down the maximum capacity to 15 u or completely opt for syringes instead. 
I'm not against weaponized chemical injections, but the autoinjects go through any clothing protection and are instant, and 60u capacity makes them way too efficient (against humans without MP level police skill).

**Comment by Hughgent** [comment]
Making syringes would basically negate the feature entirely in my opinion. The point of the autoinjector is for doctors to make something special for marines in a form that they can use normally. If a doctor wanted to use syringes, they would make the liquid bottle and grab any number of syringes from the vendors or the box of syringes.

I feel that an antag doctor would just go around killing via pills and trust rather than relying on the click skill that is afforded by Autoinjectors. 15u Chloral Hydrate knocks a person out and down just as fast as 30, just as fast as 10.

**Comment by Ghommie** [comment]
It's not just a matter of chem cycles, 60u is plenty of space to shove in many junk chemicals in sufficient amounts, plus a handful of them have rather immediate effects, though generally harder to come by as of now.
This may be be considered BS in the future, but I won't impose myself further.

**Comment by TobiNerd** [comment]
Tried it out. It's a cool way to get researchers to make something really special. And I think it's fine having it possible to make 60u autoinjectors this way, just gives more of a reason to use the feature. 

Plus, this gives you an easy way to test large dosages of medicine on monkeys, since they can't eat pills.

**Comment by spookydonut** [comment]
Letting you put anything in an auto injector bypasses the restrictions syringes have on a timer to inject people

**Comment by Rohesie** [comment]
A general nerf in here would be positive. Cut down a bit the chems powercreep.

15u would be fair as a cap for pills and autoinjectors both, same as it is for syringes. Though I agree there should be differentiation between syringes (currently useless), pills and autoinjectors.

Arguably autoinjectors being unable to be refilled (unlike syringes) and being bulkier than pills could bypass this some, perhaps to 30u.

Or do you feel 30u to be too small an amount?

Also dylo has 25u because in the past it could me mixed in the body with inaprov to make tricord, and that was an indirect nerf they made. It can be changed back to 15u without issues.

**Comment by TobiNerd** [comment]
In regards to the balancing of the different ways chems can be administered, as Rohesie suggested opinions on.

**Pill** 
_Pros:_ They're compact, fits 16 in a pill bottle. Easy to mass produce in the chemmaster.
_Cons:_ Delay for giving the pill. Takes a bit to metabolize the pill before the chems enter your system. 
_Opinions:_ Lower the cap for the pills to 15 units and increase how long it takes for the chems to metabolize and enter your system even further. Just lowering the pill cap won't change much alone as pills are rarely made in higher dosages anyway. They're the slowest way of administering medicine, but it's not slow enough for people to give it a second thought. 

**Advanced Hypospray**
_Pros:_ Refillable (by pills too), decent capacity. Can be used on multiple people. Can change transfer amount.
_Cons:_ Low in supply and can't be made.
_Opinions:_ Either give hyposprays a delay again, lower their capacity or lower the max transfer amount to 5 or 10u

**Hypospray**
_Pros:_  Refillable, decent capacity. Can be used on multiple people
_Cons:_ Doesn't inject much at a time. Low in supply and can't be made.
_Opinions:_ Same as above, but should still be worse than the advanced version

**Autoinjector**
_Pros:_ No injection delay. Can inject a lot at a time as compared to hyposprays and syringes. High in supply, but slower to make custom ones as compared to pills (as by this PR)
_Cons:_ Not refillable after use. Can only be used on one person. The least space efficient option.
_Opinions:_ Keep the capacity high, 30u or even 60u for custom injectors. It should be atleast as high as the highest transfer amount of the advanced hypospray, if not higher. Otherwise they'll be obsolete. Don't think they should get bulkier, as they're the least storage efficient already and can't be refilled. They should probably be the same size as syringes even, due to how inefficient they are

**Syringe**
_Pros:_ High in supply. Paired with bottles they're fairly efficient in storage. Only way to take blood samples
_Cons:_ Slow to fill. Has delay when using
_Opinions:_ They're meant for doctors, not medics. They're something any doctor should carry to identify overdoses that can't be scanned. Make doctors specifically able to use syringes without delay, otherwise they'll be obsolete as compared to hyposprays.

**Comment by Hughgent** [comment]
as a small bit of clarification.
pills _w_class = 1_ but fits in the pill bottles _w_class = 2_
Autoinjectors _w_class = 1_ has a dedicated 7 (14?) slot pouch
Syringe _w_class = 1_ has a dedicated 7 slot pouch that shouldn't be used.
Hyposprays  _w_class = 2_ fits in the medical pouch.

I agree with everything here, the autoinjectors that are made by the pill machine are very much so single use. They cannot be "restocked" in the same way as the basic ones are.

**Pull request merged**
