### PR TITLE
Martini Nitro Express Sunder Rounds

### PR DESCRIPTION
**Pull request by Cowbin**
## About The Pull Request
This pull request adds in the ammo for the martini Nitro Express Crude Heavy Sniper Bullet, an armor sundering round with a red tip.  
SVD round:
	damage = 75
	penetration = 35
	sundering = 15
Normal Martini Round:
	damage = 120
	penetration = 20
	sundering = 10
Nitro Express Martini Round:
	damage = 60
	penetration = 20
	sundering = 35

## Why It's Good For The Game
Currently there are no rounds focused on sundering xenos that are available for standard weapons.  The martini is honestly fairly bad as is, and a specialty round would make it more interesting.  This PR currently does not make the round available in Req or standard vendors.  However I would like for it to be unlimited in standard vendors.

## Changelog
:cl:
add: Martini Nitro Express Rounds, sunder focused rounds
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Huge sunder is rare for a reason, it's fucking suffering for xenos to deal with. Most xenos simply can't fight effectively while heavily sundered, and it's slow to regenerate.
All very high sunder options are either limited and/or req.

**Comment by FosterGrime-Heymynameslouie** [comment]
I agree with lumi
high sunder equipment is rare for a reason, but if you REALLY want to get this in I suggest completely slashing its damage again or something so coupled with the fact that its the martini, an already terrible weapon, it dosent punish anyone much damage wise.

This might sound good in my head but it might completely doo doo in practice

**Comment by Cowbin** [comment]
> I agree with lumi high sunder equipment is rare for a reason, but if you REALLY want to get this in I suggest completely slashing its damage again or something so coupled with the fact that its the martini, an already terrible weapon, it dosent punish anyone much damage wise.
> 
> This might sound good in my head but it might completely doo doo in practice

So would you be okay if I dropped the damage by 15 and 5 sunder off?  Also what kind of availability were you thinking for this round?  I was thinking limited/unlimited standard vendors

**Comment by FosterGrime-Heymynameslouie** [comment]
> > I agree with lumi high sunder equipment is rare for a reason, but if you REALLY want to get this in I suggest completely slashing its damage again or something so coupled with the fact that its the martini, an already terrible weapon, it dosent punish anyone much damage wise.
> > This might sound good in my head but it might completely doo doo in practice
> 
> So would you be okay if I dropped the damage by 15 and 5 sunder off? Also what kind of availability were you thinking for this round? I was thinking limited/unlimited standard vendors

the damage and sunder reduction would probably be more acceptable to xenos, and the availability I think should be limited, like how the moving machine gun is. Limited ammo in vendor and more can be bought in from req?
then again, I dont have final say whether this pr gets through or not, its up to maintainers for that.

I hope this pr gets through though in some form, the martini having another niche is cool

**Comment by Al-1ce** [comment]
Limiting the ammo of a gun isn't a solution. It's hardly even a bandage. The problem of the ammo being too powerful is snuffed out when you can just buy more.

If the damage is lowered as it already seems, I don't see why adding a limit is needed.

**Comment by DerpiestBruh** [comment]
I mean, considering Martini has no IFF, takes a long wield time, is outclassed by slugs, etc. I don't see much issue with sunder rounds if they're limited to Requisitions.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Ignoring whether this is a good idea, this is not even available in the game and we arent in the habit of adding dead code, you need to decide how this should be available

**Comment by Losenis** [comment]
>it's fucking suffering for xenos to deal with

Can be said about a lot of things like bonefracs, IB, random organ damage, etc.

**Comment by RikuTheKiller** [comment]
I don't see the point in having this if it's going to be infinite. Make it req (Doesn't have to be an insane cost, though.) and you've got a nice PR imo.

**Comment by Weedmaster77** [comment]
> I don't see the point in having this if it's going to be infinite. Make it req (Doesn't have to be an insane cost, though.) 

I agree seem like making it a REQ ammo will make it something that could work.

**Comment by BraveMole** [comment]
I am closing this :

New ammo generaly adds nothing to the game, you are not playing differently with a sunder ammo or a normal one.
Sunder is a slow to heal wound and having a shit ton from a single shot feels really unfair.

And I am ignoring if this is balanced or not. It is just not the type of content that is merged here ; if you want to add something new it should be a bit "exotic" gameplay wise

**Pull request closed without merging**
