### PR TITLE
Disables mech pilot from being picked, deletes mech vendors from ships.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Disables mech pilot from being picked, and deletes the mech vendors+automated vendors. Puts cobwebs in the mech room.
## Why It's Good For The Game
Mech is entirely unfinished in its current state, the design is poor and unfinished. It requires an entire rework and the person who was doing the rework and decided to leave the current one in as a stopgap (Kuro) decided that he didn't have the time to work on it in general right now due to being busy.
So it should be disabled until that is finished, I would delete the job but people have playtime on it, so deleting it entirely would be pretty cringe, in vein of that I replaced the vendors with cobwebs.
## Changelog
:cl:
del: Mech pilot has been disabled, you cannot pick the job anymore. You may try it out in vallhalla still, however.
/:cl:

### CODE REVIEW

**Comment by Kuro020** [comment]
I suggest tivi to seriously consider this, because mech rn is pretty meh and since I wont be working on it anymore it will probably be forever meh

**Comment by Zangeiti** [comment]
you forgot to add King removal in this pr too

**Comment by XElectricX** [comment]
Delete the inferior mechs and replace with glorious [helicopters](https://github.com/tgstation/TerraGov-Marine-Corps/pull/11783).

**Comment by Pariah919** [comment]
Better alternative might be to make MP like, only appear on super super highpop if people want it to stay as a uncommonly seen thing.

**Comment by RipGrayson** [comment]
At this point all proposed mech reworks are dead, and the mech might be dragging our player numbers down.
I'm not saying I want mechs removed or anything. But I think there's a fundamental issue with one player getting a powerful role that the other team can't easily contest (yes I'm talking about King too).

I'm not sure if it's our implementation of the concept or something inherent to our gameplay, but Tank didn't work out for us or CM and it was the same kind of problem. Two players get a powerful piece of hardware and the other guys just have to deal with it.

I don't want Tivi/Kuro to waste their work on something ultimately shelved, but if we don't have a server because mechs killed our playerbase, is it really worth keeping when we don't have any alternatives?

**Comment by Barnet2** [comment]
It might happen, tgmcbros. The era of mech may come to a close.

**Comment by zzurge** [comment]
Im gonna miss the big rockem sockem robot,but as long as king takes the L ill begrudgingly say goodbye to the big hunk of metal

**Comment by RipGrayson** [comment]
> you forgot to add King removal in this pr too

If this goes through I'll make a separate PR attempting to remove King

**Comment by FosterGrime-Heymynameslouie** [comment]
> Delete the inferior mechs and replace with glorious [helicopters](https://github.com/tgstation/TerraGov-Marine-Corps/pull/11783).

this but unironically 
I love yo electirc

**Comment by RaidarV** [comment]
Very nice PR, mech is pretty mid in its state right now.

But can you remove free King too now ?

**Comment by maikilangiolo** [comment]
You just know king won't be removed if mech will.

**Comment by Zangeiti** [comment]
> You just know king won't be removed if mech will.

the xeno cabal refuses to let go of its one and only crutch (that and minions)

**Comment by lKiseki** [comment]
Finally. This was a long time coming.

**Comment by Joe13413** [comment]
ya know i feel like mech can be fun at times but the cancer that comes with it far outweighs that. good pr, hate to see it go but it's really for the better

**Comment by chizzy376** [comment]
LET'S FUCKING GOOOOOOOOOOOOOOOOOOOOOOOOOOOOO MJP YOU KNOW WHAT TO DO NEXT 
rogan

**Comment by Coastfront** [comment]
And at last, battered and seeded with little more than woe, did the scorned and the scornful alike turn teary gazes sunward, for a dawning curtain swept away a ruthless gripping night from the land.

At once did every petal of joy bloom through a faint, scorched yet cool winter, as each gently warming ember spurred once more into their soothing candle light.

An eye of boundless hate at last dimmed, as its veiling sheet met its longful close.
The beast was slain, and further again could the shilling voice of electric mention helicopters.


mjp i detest nearly every pr you have made but this one is not one of them.

**Comment by Pariah919** [comment]
>mjp i detest nearly every pr you have made but this one is not one of them.
>
ok

**Comment by TheUSSWatercooler** [comment]
End this hell. 
Remove mech, revert king.

**Comment by Mannybrado** [comment]
wtf i love mjp now

**Comment by MiniMeatwad** [comment]
Considering people are complaining about the role being unbalanced, just make it weak as fuck. Can't be overpowered if it's weaker than a standard marine. Then you have the option of having multiple mech pilots when the mech is weak shit.

**Comment by Derrick2Electricboogaloo** [comment]
That was a sick drift.

**Comment by chizzy376** [comment]
MULTI-TRACK DRIFTING

**Pull request closed without merging**
