### PR TITLE
Implements Rohesie's smoothing system, creates/ports a number of new wall sprites.

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

First of all massive disclaimer, I didn't write 99% of this code, Rohesie created the smoothing system here https://github.com/tgstation/TerraGov-Marine-Corps/pull/4462 but left before it could be implemented.
I'm bringing it back mainly because our current smoothing system is utterly ancient and got in the way of respriting cave walls.

This PR implements a new smoothing system and uses it to support an original re-sprite of mineral walls on LV, Chigusa, and Magmoor. While I was at it, I also ported cult walls and jungle walls from CM and one generic set of walls from Eris because the current one dimensional walls look horrible next to cave walls with 3/4ths perspective on them (once again, Rohesie had already converted the CM walls to the new system, I'm responsible only for bug testing them for missing icon states).

## Why It's Good For The Game

The current smoothing system is ancient and gets in the way of better sprites for our maps, it's time it was replaced. New sprites might also be good, players won't have to pretend that a one dimensional plane represents a cave wall anymore.

## Changelog
:cl:
add: Implemented Rohesie's smoothing system.
imageadd: Created new cave wall sprites.
imageadd: Ported jungle wall sprites from CM.
imageadd: Ported cult wall sprites from CM.
imageadd: Ported a set of wall sprites from Eris to replace old Sulaco walls.
imagedel: Deleted old Sulaco wall graphics.
/:cl:

### CODE REVIEW

**Comment by vilereaver41** [comment]
Got any screenshot comparisons?

**Review by Kuro020 — CHANGES_REQUESTED** [review]
post screenshots comparing maps before and after this pr, it might make things look whack on some places since this perspective doenst apply to all the walls we have

**Comment by RipGrayson** [comment]
> Got any screenshot comparisons?

> post screenshots comparing maps before and after this pr, it might make things look whack on some places since this perspective doenst apply to all the walls we have

I'll do that soon, I need to grab actual screenshots from a local test, the map preview isn't a good indication of what the new walls look like during play.

> it might make things look whack on some places since this perspective doenst apply to all the walls we have

This change (primarily) effects three maps, LV, Chigusa and Magmoor. None of them have terrain without perspective, in fact that was the reason I needed to port cult and jungle walls, they looked terrible and flat when placed near the new cave sprites.

**Comment by RipGrayson** [comment]
crashedshipbeforeandafter
beforeaftercave

**Comment by RipGrayson** [comment]
newoldjungle
beforeafternarsie

**Comment by vilereaver41** [comment]
Nice

**Comment by MiniMeatwad** [comment]
looks significantly better

**Review by Kuro020 — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]

**Comment by Derrick2Electricboogaloo** [comment]
Amazing, good work!

**Comment by yyzsong** [comment]
Holy shit these are pretty. Nice
one problem maybe is that it loses the distinction between PC-able walls and un-PC-able walls

**Comment by Walarks** [comment]
I think jungle and cave walls are too thin north and seem like identical black squares.

**Pull request merged**
