### PR TITLE
spits go over barricades

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Spits go over barricades again.

## Why It's Good For The Game
Makes barricades a bit less effective, but they're faster overall to make now so I don't think this is needed anymore, and lets you make the engineer stop doing stuff for a bit.

## Changelog
:cl:
balance: spits go over barricades once again
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Not bad, though will this affect the boiler glob or is that not included?

**Comment by InterroLouis** [comment]
This will affect everything, bullets too.

**Comment by Naaanii** [comment]
Might want to make it only for spits and allow nades to be fired over from range maybe.

**Comment by DerrickChamberlain** [comment]
Pop some kalo and keep on trucking :)

**Comment by SplinterGP** [comment]
FF BBEHIND CADES WOOOOO FF UPGRADED

**Comment by SpaceLoveSs13** [comment]
Bad pr doesn't solve fobbitting problems instead create more imbalance for rest of the cadings where mini fob is applicable. Spitter spam is also possible in just one line or turret. Extremely imbalanced pr imo.

**Comment by Hydrinator** [comment]
This seems like a bad idea for several reasons, one of which is encouraging flimsy ranged xenomorphs to run up face-first into barricades in order to try and spit at people instead of melting said barricades.

**Comment by TiviPlus** [comment]
Basically what people said this doesn't fix anything

**Pull request closed without merging**
