### PR TITLE
Buffs Combat Floodlights

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
The following changes have been made to Combat Floodlights:
- Fixed a typepath issue.
- No longer acidable, but can now be damaged by slashes.
  - Floodlights have a maximum integrity of 500.
  - Can now be repaired using welders. Each welder use will restore 100 integrity.
  - Remaining integrity is visible by examining the floodlight.
- Reduced their cost in requisitions from 100 to 30 points.

## Why It's Good For The Game
Further enhances marine visibility and makes Combat Floodlights worth a damn.
As discussed with @TiviPlus, floodlights should be complicated to deal with, but scarce in amount.

## Changelog
:cl: Lewdcifer
balance: Combat Floodlights are no longer acidable, but can now be damaged by slashes.
balance: Combat Floodlights can now be repaired using welders. Examine the Floodlight to see its remaining integrity.
balance: Combat Floodlights have had their cost in requisitions reduced from 100 to 30.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Now make them powerable by laser gun mags 🗿

**Comment by QualityVan** [comment]
Doesn't the battery have like ten thousand charge? I'm not sure them running out of battery was at all an issue.

**Comment by lKiseki** [comment]
> Doesn't the battery have like ten thousand charge? I'm not sure them running out of battery was at all an issue.

The normal cell has 1,000 charge, not 10,000.

**Comment by Derrick2Electricboogaloo** [comment]
> Doesn't the battery have like ten thousand charge? I'm not sure them running out of battery was at all an issue.

10,000 charge does not last that long, 15 minutes if I recall. And it spawns with the shitty 1,000 charge battery which lasts 2-3 minutes.

**Comment by Derrick2Electricboogaloo** [comment]
> > Doesn't the battery have like ten thousand charge? I'm not sure them running out of battery was at all an issue.
> 
> The normal cell has 1,000 charge, not 10,000. You certainly have the option of inputting better cells, though, so it might be unneeded. I'll go ahead and revert that bit.

So you got it to take spawn with the high cap battery now? Good shit. I tried that and it broke the damn flood light.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
