### PR TITLE
Makes thrown objects actually make sound when they hit something living.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds throw_impact to obj/item and adds playsound hitsound
## Why It's Good For The Game
Have you ever been hit by a throwing knife, a spear or a sword and received 0 feedback that you are taking damage? Well fear not, because now whenever you get hit by something being thrown at you, you will get an auditory response. WHY IS IT NOT LIKE THIS ALREADY?
## Changelog
:cl:
add: Getting hit by something being thrown at you (like knives) now plays a sound.
/:cl:

### CODE REVIEW

**Comment by Joe13413** [comment]
can you make it something rather silly such as explosion sound effect or that metal pipe thing please i beg you

image

**Comment by Joe13413** [comment]
on another note
image

**Comment by Xander3359** [comment]
> can you make it something rather silly such as explosion sound effect or that metal pipe thing please i beg you

You can add any sound to any item by just adding the .ogg to the var/hitsound. Yes, I am saying wyci, specific sounds are outside the scope of this PR, this PR is just to make the sounds that are currently in the game function in the first place.

**Comment by Lumipharon** [comment]
You need to just pull from master 4head, not manually duplicate the fix.

**Comment by Xander3359** [comment]
I think I pulled master now, should work now I think? Please merge?

**Review by Lumipharon — APPROVED** [review]

**Comment by Joe13413** [comment]
> > can you make it something rather silly such as explosion sound effect or that metal pipe thing please i beg you
> 
> You can add any sound to any item by just adding the .ogg to the var/hitsound. Yes, I am saying wyci, specific sounds are outside the scope of this PR, this PR is just to make the sounds that are currently in the game function in the first place.

wait a sec do you mean i can mod my game to add new sounds? based??

**Comment by Xander3359** [comment]
> > > can you make it something rather silly such as explosion sound effect or that metal pipe thing please i beg you
> > 
> > 
> > You can add any sound to any item by just adding the .ogg to the var/hitsound. Yes, I am saying wyci, specific sounds are outside the scope of this PR, this PR is just to make the sounds that are currently in the game function in the first place.
> 
> wait a sec do you mean i can mod my game to add new sounds? based?? or am i just retarded and dont get what the hell code is

I dont think you can mod your game, what I mean is, the game is open source, crack open vscode, add the sounds you want to add and then PR it like the rest of us.

**Comment by Joe13413** [comment]
agh

**Pull request merged**
