### PR TITLE
Merry Christmas from Ocelot!

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request
The Absolute Madman Ocelot has re-sprited nearly all the standard guns for Christmas. 

image

## Why It's Good For The Game
These are some sick looking sprites from Ocelot himself.

## Changelog
:cl: Ocelot
imageadd: Resprites nearly all the standard weapons.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
legendary

**Comment by AnCopper** [comment]
12 shots, this time, I've got 12 shots.

**Comment by Araulius** [comment]
incredibly based. where's his paypal so i can compensate him for his effort?

**Comment by Mrrpip** [comment]
TP-44 red edition

**Comment by Kuro020** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 3 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

shut up I was in vacation

**Pull request merged**
