### PR TITLE
Maximum marines alive requirement for hijack

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Per title, Lewd, pette also are in support of this

## Why It's Good For The Game
Stealthjack is not good for the xenos who get killed, or the marines that now have to rush shipside because they left a cade open for the last xeno to sneak into fob and prolong the round

## Changelog
:cl:
balance: Added a maximum marines alive requirement for hijack
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
wait, im pretty sure that was a thing already ?

**Comment by Lefunny** [comment]
just close the cade.

**Comment by Derrick2Electricboogaloo** [comment]
> wait, im pretty sure that was a thing already ?

It was. Until it was removed for some reason.

**Comment by vilereaver41** [comment]
U ruin all my fun tivi

**Review by BraveMole — CHANGES_REQUESTED** [review]
Your system allow 5 dudes on a tadpole, in lockers, in a tarp, etc. to prevent hijack ; this is just allowing marines to delay at a maximum, and i know this will be used by some marine.

I'd rather have a system where the ratio of marines to xeno matter. If you have 15 xeno and 5 marines on the ground, it's not stealthjack

**Comment by TiviPlus** [comment]
@BraveMole This is the exact same system that capture uses and we haven't had issues with that

**Comment by GradusNL** [comment]
> 
> 
> @BraveMole This is the exact same system that capture uses and we haven't had issues with that

Haven't had issues with that _**yet**_. What's wrong with future proofing by using a ratio instead of a hard number?

**Comment by EgorDinamit** [comment]
Ho boy, here we go again, delaying rounds for 3 hours with tadpole shenanigans.

On a more serious note, what's the issue with xenos getting a victory/marine minor in case someone is dumb enough to leave FOB open with no defenses? I think they deserve it.
Stealthjack isn't even an issue, unless xenos managed to destroy tadpole, in which case they deserve to win even more.

**Comment by Nerolostshor** [comment]
Tivi ... why are you sanctioning a team for the error of the other one ? why kill the strategy ? its a valid option if you hard lock we will have 5 marines camping in the tadpole in the middle of the river for ages ... it will only force capture or give time for a respawn wave for marines / xeno. Honestly i see it come for a good feelling but you may need to give it more thouths on how it will be abused.

**Comment by EgorDinamit** [comment]
Okay, suggestion.
Make it demand 50% of the hive on Alamo so if you have 5 xenos out of 9 you can still hijack.

**Comment by David-Stormwell** [comment]
As much as I enjoy this stat, it does fuck over balance in the long run, and ruins the time for people who may or may not have worked hard for their win/the marine team.
"But I deserve to punish Marines for letting their FOB go unguarded"
I'll support any PR which adds a way for Xenos to temp stall the Alamo if they can't fully hijack, yes Hijack already also stalls it, but the new stalling in theory would be shorter.
And a reminder, the ability to melt the FOB down and kill turrets before Marines can react is already a huge thing that can be done, and can cripple marines logistic wise temporally Unless req gets their shit in order that is.

Consider this approved.

**Comment by EgorDinamit** [comment]
There should be a difference between "1 xeno hijacks alone, ditching 4 other xenos and 40 marines" and "8 xenos out of 10 hijack, leaving 20 marines behind".
I think this PR should consider the xeno:marine ratio, not the amount of living marines.

**Comment by BraveMole** [comment]
I'm not interested in this if you're not doing either of the changes i asked.

This allows theoritical infinite delay, which is bad.

You can fix the insta stealth xeno by adding a timer between the moment they take control of the ship, and the moment they can launch it.

You can fix shrike meming and killing all the hive by checking if a majority of xenos is in alamo.

You can fix solo shrike meming 30 marines by stealth hijacking by adding a ratio check.

**Pull request closed without merging**
