### PR TITLE
Halving kevlar-weave infused bulletproof windows' max integrity.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
The walls around these windows are said to be more than twice as easy to destroy compared to the windows themselves. Premising this is true, halving the windows health still retains them being sturdier than walls by an edge, which is acceptable given their scope.

## Why It's Good For The Game
Making them not as ridicolous.

## Changelog
:cl:
tweak: halved kevlar-weave infused bulletproof windows maximum integrity.
/:cl:

### CODE REVIEW

**Comment by DominikPanic** [comment]
Something to note: You can't attack the walls with a machete/melee weapons, you can the windows.

**Comment by Ghommie** [comment]
Agreeable. If armor datums were appliable by now, It'd be easier to tweak this out.

**Comment by psykzz** [comment]
Why not increase walls to match instead of reducing windows?

**Comment by Ghommie** [comment]
Mapping freeze, main reason.

**Comment by Rohesie** [comment]
The current health is a bit insane. This is positive.

**Pull request merged**
