### PR TITLE
Reworks the martini from a D-tier support weapon to a support/wildcard weapon

### PR DESCRIPTION
**Pull request by ClosetedSkeletonGH**
## About The Pull Request
Note: balanced around the fact that the fastest I could fire from full wield to reloading and firing from full wield again being 3.43 seconds, I doubt that many people could get too much faster than this

Reworks the martini from a D-tier Support weapon with its shatter property (the previous martini PR completely gutted its usability, with shatter failing to provide its support niche because the martini fires once ~every 3 seconds

Major changes:

- Martini shots can now pierce mobs (human or xeno), losing 8 tiles per mob pierce with a max range of 28 (12 less than previously + other snipers, max T-47 scope + 4)

- Martini shots now have a 3 second stagger stun if it hits a human in anywhere of its range :3 (only applies to human and human derivatives (robots, vatborns))

- Martini shots now has a 50% shrap chance (I am sorry my child, but the idea of 2 marines getting shot by 1 shot and both getting shrap is too funny to me)

- Shatter status removed

- Martini can only fire while wielded now (why couldnt it before, its literally known for being huge and unwieldy)

Stat changes:

- Damage changed from 120 -> 105 (this can be shifted back at a later date if its too low, since its spread out DPS is around 28 or so rn)
- accurate min range changed to 3
- sundering set to 12.5 (so it can be a support weapon again)
- fire delay set from 1 -> 1.5 (no effect)
- increased unwielded recoil from 4 -> 5
- aim slowdown increased from 1 -> 1.5 (you shouldnt be moving while firing this gun, its literally a martini henry)
- movement innac penalty increased from 5 -> 8 (see above)

also resprited it, here are the sprites:

image

## Why It's Good For The Game

Last PR turned the martini from a D-tier meme weapon to a D-tier support weapon. this PR hopes to change it into something that can actually be used as a fun weapon with a defined niche of wildcard/support that nothing else currently fills. 

I think this would be pretty fun to use and for people with the gimmick builds for it, also makes it a meme again
## Changelog
:cl:
balance: Rebalances the martini
/:cl:

### CODE REVIEW

**Review by Kuro020 — CHANGES_REQUESTED** [review]
image
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by ClosetedSkeletonGH** [comment]
> image uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

wuh oh

**Comment by Strayed-Raven** [comment]
I foresee this getting closed

**Comment by ClosetedSkeletonGH** [comment]
I have no clue whats going on with gun64.dmi, I redid my gun64.dmi from one with the repo then I sprite import my 4 martini sprites from a .dmi with only my martini sprites

**Comment by Lumipharon** [comment]
its an issue with the diffbot, I had the same issue. The trouble is that means we can't see if there are ACTUAL issues with the icons.

Also holy fuck please just kill the memetini. Replace it with a gun that isn't from the 19th century, this is literally a railgun made out of wood.

**Comment by ClosetedSkeletonGH** [comment]
> its an issue with the diffbot, I had the same issue. The trouble is that means we can't see if there are ACTUAL issues with the icons.
> 
> Also holy fuck please just kill the memetini. Replace it with a gun that isn't from the 19th century, this is literally a railgun made out of wood.

martini funni

**Comment by Joe13413** [comment]
> its an issue with the diffbot, I had the same issue. The trouble is that means we can't see if there are ACTUAL issues with the icons.
> 
> Also holy fuck please just kill the memetini. Replace it with a gun that isn't from the 19th century, this is literally a railgun made out of wood.

musket

**Comment by Zangeiti** [comment]
this changed from niche railgun-wannabe to the ultimate marine grief tool

**Pull request closed without merging**
