### PR TITLE
Adds an Art Maintainer role in OOC color code

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title. Uses Maintainer OOC coloring.

## Why It's Good For The Game
Kuro wanted it, I deliver.

## Changelog
:cl: Lewdcifer
add: Art Maintainer role, has same OOC color as Maintainers
/:cl:

### CODE REVIEW

**Comment by neohenry** [comment]
But does the art maintainer approve of color? HMMM

**Comment by lKiseki** [comment]
he doesn't get a choice :^)

**Comment by Kuro020** [comment]
This is my favorite pr on github

**Comment by BraveMole** [comment]
But kuro doesn't play????

**Comment by lKiseki** [comment]
tru

**Comment by TiviPlus** [comment]
Kuro bald?!

**Pull request merged**
