### PR TITLE
vgrip makes you faster in aimed mode

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
.2 instead of .5 like a gyro, should hopefully make the vgrip a more viable choice in peoples loadouts.

## Why It's Good For The Game
hopefully will give people a reason to run this over agrip, and if rds buff is merged will lead to more variable loadouts.

## Changelog
:cl:
balance: vgrpi helps you move moderately faster in aim mode, not as much as a gyro, however.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
Make vgrip reduce wield slowdown

**Comment by Ieteihowmee** [comment]
> Make vgrip reduce wield slowdown

That is what agrip does, even though I am pretty sure it was nerfed a while ago.

**Comment by Ieteihowmee** [comment]
I support this.

**Comment by Losenis** [comment]
> That is what agrip does, even though I am pretty sure it was nerfed a while ago.

No I mean the speed you walk while you're wielding, not the actual wielding speed

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
