### PR TITLE
Adds an EORD roomba

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Adds a roomba that sucks up both dead bodies and items to keep EORD tidy.
## Why It's Good For The Game

Should help with EORD being swamped with bodies and random items.
## Changelog
:cl:
add: Added an EORD roomba
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Salt PR?

**Comment by mc-oofert** [comment]
doesnt this suck up the guns eord starts with

**Comment by Loldaddy5676** [comment]
> doesnt this suck up the guns eord starts with

best grab them quick then

**Comment by Joe13413** [comment]
powercreep pr

**Review by TiviPlus — APPROVED** [review]

**Comment by RipGrayson** [comment]
EORD maps are created on game load. If a game goes on for 2 hours, that's two hours that the EORD roomba has to suck up all weapons. Even if the roomba gets bad RNG, it still has the time to remove all weaponry before the players get to the arena.

**Comment by ivanmixo** [comment]
Just map them to be on a table or rack if you care ig.

**Review by RipGrayson — APPROVED** [review]
I don't care enough to demand changes here, concept is fine.

**Comment by chizzy376** [comment]
Doesn't the roomba vacuum up things into the same cryo computer as shipside roombas do?

**Comment by ivanmixo** [comment]
Specifically made it delete, look at the code.

**Comment by chizzy376** [comment]
Just checked in valhalla myself, good thinking yeah

**Comment by ivanmixo** [comment]
I want to scoop up corpses too and have it be indestructable so no

**Review by Lumipharon — CHANGES_REQUESTED** [review]
Either this only spawns after round, or kill. Although really this only seems like an issue when you're 4 hours into eord or something.

**Comment by ivanmixo** [comment]
:hampter:

**Comment by Lumipharon** [comment]
I am illogically terrified of map conflicts that will scare and confuse my platform pr.

**Pull request merged**
