### PR TITLE
baldur is no longer free, costs more in req

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Baldur is equivalent to free NVGs and makes flares and literally everything else essentially pointless, it shouldn't have ever been a free module.
It is no longer free and costs 10 points in req.

## Why It's Good For The Game
Returns the light game again rather than making it entirely pointless.

## Changelog
:cl:
balance: Baldur lights are no longer free in vendors. Baldur now costs 10 points in req and is only 1 per module like the other modules.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -40. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Review by TiviPlus — APPROVED** [review]

**Comment by sunofang** [comment]
You currently have a negative Fix/Feature pull request delta of -40000. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Anyways, Seems good for balance. Just make sure marines dont cry too much about it

**Comment by TiviPlus** [comment]
going 42

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-42). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
