### PR TITLE
jaeger has helmet storage now

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
helmet storage, same as the other stuff.
I've tested everything and everything still works the same, nothing broken.

## Why It's Good For The Game
Jaeger and PAS should have generally the same capablities.

## Changelog
:cl:
tweak: jaeger helmets can now hold stuff
/:cl:

### CODE REVIEW

**Comment by QualityVan** [comment]
Jaeger gets a module, m10 gets storage. Why would jaeger get a module and storage?

**Comment by Sebbe9123** [comment]
Finally I can squirrel away a tricord and an oxy injector as my emergency stash.

**Comment by David-Stormwell** [comment]
consider this approved

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Your code isnt even tested because even the linter knows its bugged so fix it and test it

**Comment by Pariah919** [comment]
eh

**Pull request closed without merging**
