### PR TITLE
Carrier can now Vent Crawl

### PR DESCRIPTION
**Pull request by Naaanii**
Gives Carriers the ability to vent crawl.

## About The Pull Request

Gives Carriers the ability to vent crawl.

## Why It's Good For The Game

Adds a more dynamic playstyle to the Carrier, enabling them to stealth and try trapping behind enemy lines or use their newfound mobility to get to areas slightly faster and lets them set up a bit better.
## Changelog
:cl:
balance: Carrier can now vent crawl
/:cl:

### CODE REVIEW

**Comment by Tennessee116** [comment]
I am gonna do you a solid and say that this should probably come with a sprite replacement. The carrier is the sprite size of the _queen_.

**Comment by Chaznoodles** [comment]
I sentence you to death

**Comment by BeloneX** [comment]
Meme PR?

**Comment by neohenry** [comment]
CRINGE PR; GO BACK TO THE SHADOW REALM FROM WHENCE YOU CAME!

**Comment by neohenry** [comment]
> 
> 
> I am gonna do you a solid and say that this should probably come with a sprite replacement. The carrier is the sprite size of the _queen_.

Old sprite remains due to past vote. I've asked before.

image

**Comment by Texicos** [comment]
Unironically buff the useless xeno

**Comment by saprasam** [comment]
my face when strolling in group of 3 and then carrier pops out of vents and hugs us all
fun & intuitive gameplay

**Comment by AtlasRules** [comment]
hmm today i will buff my main

**Comment by TiviPlus** [comment]
Meme PR or not carrier doesnt need this
Maybe when people stop abusing carriers

**Pull request closed without merging**
