### PR TITLE
updates the sprites of some of the berets, adds a red and snow beret

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
adds a red beret to marine loadout that isn't the MP one, and a snow beret
updates the beret sprites to not have blackholes of blackness
image

## Why It's Good For The Game
they look better to me at least

## Changelog
:cl:
add: Added new red beret
del:normal tgmc beret no longer has map variation
tweak: tweaked beret sprites
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -60. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Review by Hughgent — APPROVED** [review]
Code is fine.

**Comment by SilencedMP5A5** [comment]
can we just have this already

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-68). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
