### PR TITLE
Times the cost of all weapons by 1.5x and increases supply point increase and exports by 1.5c.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Increases the amount you get from corpses, miners and passive points by 1.5x.
Increases all gun costs by 1.5x.

## Why It's Good For The Game
We NEED to decompress req weapon costs, and generally I think the price of everything else can be done on case by case after this PR.

## Changelog
:cl:
costs, all point gains are increased by 1.5x, all req weapons are increased by 1.5x and to be decreased/increased on a case by case basis.
/:cl:

### CODE REVIEW

**Comment by Walarks** [comment]
> all point gains are increased by 1.5x

Update researcher credits export rewards

**Comment by novaepee** [comment]
inflation in tgmc is here

**Comment by AGasCanister** [comment]
THIS IS WHAT HAPPENS WHEN YOU SPAM THE SANCTION BUTTON

**Comment by goose4429** [comment]
I'm not sure you consider each of these a "weapon", so also consider changing:
- Stationary weaponry (mortars)
- Turrets
- CAS voucher (which gives CAS points)

**Comment by Pariah919** [comment]
I got my feedback Ill reopen this when its ready

**Pull request closed without merging**
