### PR TITLE
Drowsiness sleep chance changed to only activate after a certain stack threshold

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Hey! You! Yes, you. Come on over, let me show you something really funny...

So I noticed that Boiler globs have a var called `hit_drowsyness`, which is the amount of drowsiness stacks applied on a direct hit. A normal acid glob applied one stack of drowsiness. A lance acid glob, applied 18. A neuro lance glob applied 2.

So what does drowsiness do, you wonder? I am so glad you asked...
Every tick, if you have a stack of drowsiness, it'll blur your eyes and you'll lose a stack. However, _**it also has a 5% chance to make you fall asleep and unconscious**_. This was taken from `/mob/living/carbon/handle_status_effects()`:
image

What does this mean for a poor, poor marine? After being hit directly by a Boiler glob, there's a 5% chance they'll just fall asleep and unconscious as long as they have drowsiness stacks. Fun and emergent gameplay.

This also applied to other sources of drowsiness, like beer.

## Why It's Good For The Game
Why in god's name can a Boiler glob make you fall asleep and unconscious at a 5% chance? That's just unfun.
This also extended to other sources of drowsiness, so I've changed that. One sip of beer is probably not gonna make you fall asleep instantly.

## Changelog
:cl: Lewdcifer
balance: Drowsiness sleep chance will only activate after a certain stack threshold.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
drowsiness also causes slowdown. So to preserve that behavior without the funni sleep, you should probs sub the drowsiness with actual slowdown.

Alternatively, make change drowsiness itself so you can't fall asleep under a certain stack threshold, as afaik you can have a sip of beer and just fall asleep as well.

**Comment by Naaanii** [comment]
While you're at it, would be nicer to also remove the random % chance of globs flying over marines since direct hits are getting their rng debuffs removed too.

**Comment by Ragecrabbo** [comment]
YET ANOTHER Xeno nerf becuse salty marin mains cant simply dodge boiler gmob (wchich btw travels way slower than TAT even though their both offscreen). Please unsubscibe to this guy.

Also agreed the globs should probably get slowdown to preserve their former behavior.

**Comment by Losenis** [comment]
I FUCKING KNEW THEY PUT YOU TO SLEEP

I WAS CALLED CRAZY BUT I WAS RIGHT ALL ALONG

**Comment by Losenis** [comment]
>becuse salty marin mains cant simply dodge boiler gmob

At high TD a boiler glob can hit you even if it hits the first of three cadelines you sit behind

**Comment by lKiseki** [comment]
> drowsiness also causes slowdown. So to preserve that behavior without the funni sleep, you should probs sub the drowsiness with actual slowdown.
> 
> Alternatively, make change drowsiness itself so you can't fall asleep under a certain stack threshold, as afaik you can have a sip of beer and just fall asleep as well.

Donezo.

**Comment by bowlofcereal** [comment]
ive known this for years @Losenis  and anyone who assumes you were crazy is suffering a skill issue, clearly

this mechanic of random rng "you are now asleep have fun lol" will not be missed on my end

**Comment by ilikesaying** [comment]
I, a combat robot, was sleeped by it

**Comment by FIXTHERADBOXPLEASE** [comment]
Seems like a salt PR. Xenos don't need more nerfs than they already have, and getting direct hit by a boiler should be punishing.

**Review by Lumipharon — APPROVED** [review]
Side note: This should probs be an actual status effect

**Comment by Naaanii** [comment]
> > becuse salty marin mains cant simply dodge boiler gmob
> 
> At high TD a boiler glob can hit you even if it hits the first of three cadelines you sit behind

At high TD you can actually just walk around globs and bullets which is kind of funny.

**Comment by KrabSpider** [comment]
> Seems like a salt PR. Xenos don't need more nerfs than they already have, and getting direct hit by a boiler should be punishing.

It's not a "punishment" to be hit by something you didn't know was coming. That's just abuse and you should have your Marines taken away from you.

**Review by TiviPlus — APPROVED** [review]
#makeitastatuseffect

**Comment by FIXTHERADBOXPLEASE** [comment]
> > Seems like a salt PR. Xenos don't need more nerfs than they already have, and getting direct hit by a boiler should be punishing.
> 
> It's not a "punishment" to be hit by something you didn't know was coming. That's just abuse and you should have your Marines taken away from you.

If you can't dodge a boiler glob, that's your problem. They're easily one of the slowest projectiles in the game.

**Pull request merged**
