### PR TITLE
Tweaks ravager endure duration and cooldown

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request

Lowers endure duration, decreases cooldown somewhat.

## Why It's Good For The Game

Ravs can use endure at the start of a fight and can end with enough time left to escape while still doing sizable damage.
Doing this forces ravs to be smarter about their endure timing. Or just die, that is also a possibility.

## Changelog
:cl:
balance: decreased endure duration, with lowered cooldown to somewhat compensate it.
/:cl:

### CODE REVIEW

**Comment by lovegreenstuff** [comment]
very much a salt pr, by the way.

**Comment by Passe2142** [comment]
Yeah, we seen this as the invis button , stats wise is fine cause its meant to be a quick frontline slasher. And ignore pain is no more which iirc was better? but had no visual queue and lacked the stagger protection.

**Comment by Hekzder** [comment]
I think this is a step in the right direction but I would suggest either a further decrease in cooldown in the realm of 40-30 seconds _OR_ less of a decrease in duration in the realm of 6-7.5 seconds. As is right now I feel this is far too strong of a nerf, especially potentially factoring in a damage decrease from #7773.

**Comment by Pariah919** [comment]
remember the cd starts instantly, so this is effectively 40 seconds
overall I'd like to see the damage decrease brew for a day or three before we take a look at endure again, but this is a step in the right direction at making it not literally invinciblity for an entire engagement, though rage might need a rework

**Comment by Surrealaser** [comment]
Ah yes, so, we have a big melee damage nerf in the works (which I'm certain will pass seeing as Evasion's plasma cost was ramped to ridiculous levels that de facto kills chaining which was already challenging), Endure is now only good for covering an escape, and tapping into negative HP rage has gone from very difficult to borderline impossible.

**Comment by Surrealaser** [comment]
> remember the cd starts instantly, so this is effectively 40 seconds
> overall I'd like to see the damage decrease brew for a day or three before we take a look at endure again, but this is a step in the right direction at making it not literally invinciblity for an entire engagement, though rage might need a rework

Ridiculous. Literally invincibility? Lol. Absurd hyperbole. It's literally +50 crit HP, and you don't KO on crit.

**Comment by Passe2142** [comment]
> as E

Stats wise ravey is fine, i think this one is the main thingy to do, the other PR is a bit bananas.

**Comment by Passe2142** [comment]
> 
> 
> remember the cd starts instantly, so this is effectively 40 seconds
> overall I'd like to see the damage decrease brew for a day or three before we take a look at endure again, but this is a step in the right direction at making it not literally invinciblity for an entire engagement, though rage might need a rework

Rage is fine it was nice rework and a much needed one. Still niche and high risk high reward. Stats wise Ravs are fine its supposed to be the main slasher.

**Comment by usnpeepoo** [comment]
honestly' i'd rather see an endurenerf than a slash damage nerf.

**Comment by lovegreenstuff** [comment]
#7773 
If this PR gets merged, I'm closin' this one.

**Comment by lovegreenstuff** [comment]
I'm a moron, wrong button.

**Comment by lovegreenstuff** [comment]
that's weird, it worked locally with no problems.

**Comment by lovegreenstuff** [comment]
cheese burger burger town burger
number 15 burger ki-

**Pull request closed without merging**
