### PR TITLE
Demons

### PR DESCRIPTION
**Pull request by Tennessee116**
## About The Pull Request

It adds demons.

## Why It's Good For The Game

Well, it's a server about DOOM.

## Changelog
:cl:
add: Demons
:cl:

### CODE REVIEW

**Comment by Tennessee116** [comment]
SHIT, my bad, wrong fork.

**Comment by psykzz** [comment]
Wait what if we want the demons kek

**Comment by jroinc** [comment]
too late speedmerge it

**Comment by TiviPlus** [comment]
wait come bck

**Comment by Tennessee116** [comment]
> Wait what if we want the demons kek

reee



> too late speedmerge it

REEEEEEEEE



> wait come bck

REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by David-Stormwell** [comment]
Gib this so we can have mob bloat and more antags k ty

**Pull request closed without merging**
