### PR TITLE
Removes GL54 razorwire grenades

### PR DESCRIPTION
**Pull request by DeltaFire15**
## About The Pull Request
Currently, the TX54 and TX55 can have extreme suppression capabilities through the use of these razorburst grenades.
Not only can they instantly deploy razorsmoke at range without as much as a grenade throw / launch, each shot can also cover more ground than a normal razorwire grenade. (around 12-16 tiles or more (I counted 20 before) depending on rng spread with good distribution, as opposed to the 3x3 star pattern of a normal razor)
This, combined with its nightvision scope, and large magazine size, enables suppressing just about any push or breached defensive parameter, as even castes designed around countering razorwire will fail against the sheer amount of it you can produce.
Its cost? 96 req points per magazine, which covers more ground than a razorwire grenade box, is more convenient to use, and cost wise is one fifth of a normal razor grenade box. (To put this into numbers, on average, a **single** magazine of razorburst grenades can cover ~112 tiles or more)

Honestly, the entire arsenal of the GL54 has its problems, however this ammunition type in particular creates the usual "no fun for either side" situation razor spam tends to generate, and therefore is the culprit I would like to address here today.
## Why It's Good For The Game
Don't you love playing during rounds that have the map looking like this?

grafik
grafik

Sure, it's not every *single* round, but it has become a very common occurance for individuals to just go razorburn GL54 and remove an entire area from play. Maybe.. about 1/3rd.. lets say 1/4th of rounds.
Note that there are also many many rounds where it is used a lot, but there aren't screens that are quite as expressive as these since it's "just" used to make a particular breach virtually inaccessible (across various locations), or many other spread out variations, which I include in my approximation of usage rates.
## Changelog
:cl:
balance: Marines no longer have access to razor airburst grenades
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
Long overdue, I dunno why these were even added in the first place.

**Comment by Mannybrado** [comment]
Blessed.

**Comment by Lumipharon** [comment]
just take them out of marine access, there's other stuff they'll be used for later.

**Comment by DeltaFire15** [comment]
> just take them out of marine access, there's other stuff they'll be used for later.

I keep being told dead code is bad code. If somebody wants to use them for something less harmful to game flow at a later point, they can simply look at this commit / PR.

**Comment by Derrick2Electricboogaloo** [comment]
Holy xopium batman.

**Comment by Lumipharon** [comment]
> > just take them out of marine access, there's other stuff they'll be used for later.
> 
> I keep being told dead code is bad code. If somebody wants to use them for something less harmful to game flow at a later point, they can simply look at this commit / PR.

I am actively working on a pr that uses them lol, so please don't take them out, that just becomes inconvenient for me.

**Comment by Aporhtonoma** [comment]
ugl is already hella strong the razor nades are the cherry on top overall YES PLEASE

**Comment by ivanmixo** [comment]
Lumi its like one git command guh... really stupid reason to delay this PR

**Comment by DeltaFire15** [comment]
> I am actively working on a pr that uses them lol, so please don't take them out, that just becomes inconvenient for me.

Guh, fiiine.

**Comment by Weedmaster77** [comment]
Just make them cost more or make them only obtainable though the factory or something so there a bit more of a pain to get your hands on.

**Comment by Jackal-boop** [comment]
marines have alot of gear, alot of their gear is over tuned. losing this wont mean much for them so i think its fine

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
