### PR TITLE
Deletes some unused sounds.

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull Request
Deletes a bunch of unused sounds.
## Why It's Good For The Game
Organisation is nice.
## Changelog
:cl:
sounddel: removed a bunch of unused sounds.
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
Not so sure about this one chief.
We don't really have a place where these would be stored in the event that someone is looking for any of these sounds.

**Comment by Helg2** [comment]
I doubt someone will ever be scrolling over all these sounds in attempt to find the one without proper knowledge where to look.
And if someone knows where to look, he probably won't have any problem with finding those in other repos, branches or internet.

**Comment by Ragecrabbo** [comment]
Seeing the unused 5 and 10 minute long AI audio clips hurts my soul, im glad to see them gone.

**Comment by lbnesquik** [comment]
> I doubt someone will ever be scrolling over all these sounds in attempt to find the one without proper knowledge where to look. And if someone knows where to look, he probably won't have any problem with finding those in other repos, branches or internet.

Well if everyone prunes sounds, then we don't have any repos with them, so that's moot. All of deleted files weight is in KB, but finding good sounds can take like, 30 minutes or more. Their removal wont have a meaningful impact on load times or download time, but it absolutely could save time for contributors. I personally looked through unused sounds and used them before, and I'm sure I'm not the only one too.

**Comment by Helg2** [comment]
Well, looking through the sounds would still take a bunch of time, and half of the sounds i want to delete are just leftovers from station build, memec or etc.
But i'll revert the deleting of sounds that may seem actually usefull, as your point makes sense.

**Comment by lbnesquik** [comment]
> Looking through the sounds would still take a bunch of time, and half of the sounds i want to delete are just leftovers from station build, memec or etc. But i'll revert the deleting of sounds that may seem actually usefull, as your point makes sense.

How about this : We make an unused folder for sounds. That way, we have a very portable, fast sound repository that's ready to use for devs. It's easy to maintain, it's tracked by git, and we don't have to wonder if it is something taken from somewhere else with a bad license.

**Comment by Helg2** [comment]
I'll reopen later with better implementation

**Pull request closed without merging**
