### PR TITLE
Updates ST Uniform

### PR DESCRIPTION
**Pull request by Chaznoodles**
## About The Pull Request

Updates the Ship Technician uniform, on request of Jeff.

## Why It's Good For The Game

I don't know, ask Jeff.

## Changelog
:cl:
add: Through the use of innovative new techniques, we've managed to add sleeves to the Ship Technician jumpsuits. No more oil stains on your smooth skin!
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -14. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Jeff-jefferson-jeffery** [comment]
JEFF HERE
THIS IS GOOD FOR THE GAME BECAUSE THE OLD ST UNIFORM IS WACKY CM JANK
THIS NEW ONE IS BASICALLY THE SAME THING BUT MORE INLINE WITH THE REST OF THE SHIPSIDE STUFF AND THE MARINE UNIFORMS
IF THE SPRITE OFFSET IS FUCKED BLAME CHAZ FOR NOT TESTING IT

**Comment by Chaznoodles** [comment]
Blame Jeff for sending me offset sprites, and whoever changed instrument sounds for throwing me 100+ errors when compiling

**Comment by Jeff-jefferson-jeffery** [comment]
OH YEAH THIS IS A COMPARISON BETWEEN THE TWO
https://imgur.com/a/PWVvhlq

**Comment by Jeff-jefferson-jeffery** [comment]
FUCK ME THE OTHER LINK DOESN'T WORK AND GITHUB WON'T LET ME DELETE THIS
THIS SHOULD WORK https://i.imgur.com/0ZhYqXOh.jpg

**Comment by Chaznoodles** [comment]
> OH YEAH THIS IS A COMPARISON BETWEEN THE TWO
> https://imgur.com/a/PWVvhlq

image

God I hate you

**Review by TiviPlus — APPROVED** [review]
Code approval

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-24). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
