### PR TITLE
Removes unnecessary pouches, adds medkit pouch and changes it.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Removes a few useless pouches (medium/small of general/mag pouch) and medical pouch
Reworks medkit pouch to just be a medkit pouch

## Why It's Good For The Game
Makes medkit pouches less clunky, less noobtraps in general.

## Changelog
:cl:
add: Added new medkit pouch sprites.
del: Removed the useless medical pouch, removed useless small/medium pouches.
tweak: Tweaked how medkit pouch works to literally be a medkit in your pocket.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -46. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by ilikesaying** [comment]
so you're just removing the normal mag pouch, not the large mag pouch, right?

**Comment by davidchan13** [comment]
Am I reading this code wrong or does the new medkit pouch not hold bruise packs and ointment?

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-48). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by davidchan13** [comment]
GHMME Vendors (PFC/Job Vendors) still produce old 2/3 slot mag/pistol mag pouches.

**Pull request merged**
