### PR TITLE
Mines

### PR DESCRIPTION
**Pull request by HolisticDelight**
## About The Pull Request
Changed amount of mines in mines box. Changed price of mines box in req and engi vendor
## Why It's Good For The Game
Mines were too expensive to buy/use, now not
## Changelog
:cl:
tweak: Mine box requisiton price changed, mine box price in field engineer changed.
balance: More mines in mines box, changed size of mines.
/:cl:

### CODE REVIEW

**Comment by KrabSpider** [comment]
Mine boxes now contain 15 mines from 5 and are now tiny from small. Just an FYI for anyone curious as to what the exact changes are.

**Comment by KrabSpider** [comment]
Also uh... 
I agree that mines were super expensive for the amount that's being paid for, but like...getting THREE TIMES as many mines for 15 points and having them practically be a must-have for any monkey with a basic skill in firearms is just overkill.

**Comment by Chaznoodles** [comment]
15 mines is way too many, considering how powerful displacing enemies is as well as the stagger explosions cause. The price is also 15, so that's 1 point per mine.

7 mines at most for that price.

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
