### PR TITLE
Sulaco changes 

### PR DESCRIPTION
**Pull request by Timmeye**
Updates the Sulaco so that it can actually be played.  ****THERE WAS A PR FOR THIS BUT I DELETED IT IN AN ATTEMPT TO FIX ERRORS****
🆑
add: The Sulaco has had massive changes to make it actually playable. NOTE: the sulaco is ment to be a high pop map.
/🆑

### CODE REVIEW

**Comment by Timmeye** [comment]
I think somethings wrong with my version of python, I can't mapmerge.

**Comment by Timmeye** [comment]
Thanks to  Hughgent I managed to get this actually working

**Comment by Timmeye** [comment]
You can probably test merge this

**Comment by KwinOriginal** [comment]
What's that empty bulge at the lower deck? Is it supposed to be empty or should something get placed there in the future?

**Comment by Timmeye** [comment]
TRAVIS IS GAY

**Comment by KwinOriginal** [comment]
Excellent, I'm happy to see it in action!

**Comment by psykzz** [comment]
Getting a lot of reports that the vendors have not beeen updated with the current content.
Both ingame and discord
https://discordapp.com/channels/498569646014857217/500801682058379265/703358012647276685

**Comment by Jergobob** [comment]
Some issues. First you can have more then one of the same kit (just had a round with two sniper kits)
Second based of how tgmc calculates spec slots (which is not tied to the map tho I may be wrong) any spec slot after the 4th one can't get a spec kit. Because Sulaco uses spec tokens which only one spawns per vendor.

**Comment by Timmeye** [comment]
the problem with the spec venders was there was 2 types of them. The old ones (the broken ones) are under the parent of vender while the normal versions of the /vending/ are under the parent of /marine_selector/

**Comment by Pariah919** [comment]
DO NOT MERGE THIS THERE'S NO DRONE CONSOLE IN THE HANGAR

**Comment by Timmeye** [comment]
ooh yeah the drone console

**Pull request merged**
