### PR TITLE
Queen speed buff

### PR DESCRIPTION
**Pull request by Kuro-ai**
## About The Pull Request

Buffs queen speed

## Why It's Good For The Game

Makes queen not slow

## Changelog
:cl:
balance:Queen speed buffed
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -4. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
ignore the downvotes they're trolling,the nerds

**Comment by David-Stormwell** [comment]
Why would we want to powercreep queen to becoming a combat caste, or better yet a delayalien caste.
It needs more support options instead, and at the very least can someone add drone healing to it.

**Comment by Kuro-ai** [comment]
what you mean powercreep?I just made the queen praetorian levels of speed,this isn't powercreep it's making it PLAYABLE

**Comment by spookydonut** [comment]
if queen/shrike can move faster than marines its impossible to kill them

**Comment by Kuro-ai** [comment]
there's another PR that does the same changes + some,closing this

**Pull request closed without merging**
