### PR TITLE
Insane buffs for the medical storage armor module

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
It can now hold more things inside, like stasis bags, roller beds and so on. 

## Why It's Good For The Game
It just makes sense. 

## Changelog

:cl:
add: Medical armor storage can now hold more things relevant to corpsmen duties
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
Seems pretty storagecrepe to me.

**Comment by Xander3359** [comment]
Pretty sure I already tried this and Lumi (or QV I dont remember) said no.

**Comment by lbnesquik** [comment]
I would at LEAST want stasis bags to fit in there.

**Review by ivanmixo — APPROVED** [review]
I don't think this is a big deal at all, who cares

**Comment by Pariah919** [comment]
> I don't think this is a big deal at all, who cares

armor storage is roughly equivalent to pouches and medkit pouches can't hold any of these items, its a big buff to medical storage overall.

**Comment by ivanmixo** [comment]
I'd sooner compare armor storage to a webbing if anything. And the webbing *can* hold these.

**Comment by Lumipharon** [comment]
webbings are better in (almost) all cases compared to armour storage.

**Review by QualityVan — APPROVED** [review]
Syringe cases are fine (although they're themselves at an awkward point), bodybags are fine. Rollers and medevacs I'm more leery about, but rollers aren't actually useful in bulk and medevacs are more limited by price. I'm wondering about bumping them up to normal size (or even bulky with weight ignores on relevant pieces) and figuring out storage options from there, but that's outside of this particular PR. In terms of just matching webbing, I'm not too concerned. If there's anything in particular it would enable I'm not seeing it, maybe something with holster webbings?

All the above being said, what's up with explicit max storage space 30 on something with 5 storage slots and max weight small?

**Pull request merged**
