### PR TITLE
Gives hivemind queen-level psychic cure instead of shrike-level psychic cure

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request
Title
## Why It's Good For The Game
give hivemind the more available version of psychic cure for a more flexible heal with less cooldown time
## Changelog
:cl:
balance: hiveminds now have the queen's version of psychic cure
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
Correct me if I'm wrong but isn't the shrike version actually the stronger version?

**Comment by coldironwarrior** [comment]
ah, you'd be right. :+)
the idea was to give hivemind the more available version of psychic cure for a more flexible heal with less cooldown time. i've updated the PR to reflect that.

**Comment by Lumipharon** [comment]
Stop using that as "why it's good for the game" or you'll just get your prs closed

**Comment by coldironwarrior** [comment]
> Stop using that as "why it's good for the game" or you'll just get your prs closed

i was asked to make balance changes by someone who was unable to do it. i don't have a stake in these PRs, i did them as a courtesy for someone. i can update the reasoning for this with what i put in the other comment but for the other PR, i have no interest in trying to argue why X balance thing is good for the game

**Comment by Victor239** [comment]
Whilst we're on the topic, also give Queen heal beam instead. She's got shit to do, not sit there and nurse beans back to health.

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
