### PR TITLE
Requisition Overwatch, and how Req is Big Brother

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title

## Why It's Good For The Game

RO hates doing cardio to CIC to watch marines and not get freaking bored looking at nothing, so TerraGov Marine Corps installs a dedicated requisition overwatch in requisition! RO can now watch miners being fixed, locate the FREAKING ASRS bluespace, see marines die, and get MORE MONEEEEEEEEEEEEEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.

Requisition overwatch is not able to change aSL or shoot OB. RO has to haul ass for that.

ST doesn't have access, but they technically don't need to watch marines. Keep getting neglected, STs.

## Changelog
:cl:
add: Give requisition overwatch!
qol: RO doesn't have to run to CIC anymore
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
Sprites for req overwatch.

https://user-images.githubusercontent.com/6610922/147378777-8612c3d7-0906-4b07-baec-e16dac242862.mp4

**Comment by Araulius** [comment]
finally i can do something when req is broke as an RO

**Review by BraveMole — CHANGES_REQUESTED** [review]
real meh. If it's only a camera, why not, but a full overwatch should only be in cic imo

**Comment by novaepee** [comment]
> real meh. If it's only a camera, why not, but a full overwatch should only be in cic imo

The only function req overwatch is jumping to marine's camera. There is no OB function nor changing aSL.

Maybe I should add that in description.

https://cdn.discordapp.com/attachments/500801682058379265/924126523345215508/2021-12-24_18-28-12.mp4

**Pull request merged**
