### PR TITLE
reinforced wall change

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
rwalls have 75 armor, 5000 hp
## Why It's Good For The Game
Makes Rwalls tougher to normal bullets.
## Changelog
:cl:
balance: Reinforced Walls have 75 laser/bullet armor and 5000 HP.
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]

**Comment by yyzsong** [comment]
image

**Comment by exdal** [comment]
image

**Comment by coldironwarrior** [comment]
this wouldnt affect devastating explosions destroying walls, yes? does that just qdel the wall?

**Comment by Ragecrabbo** [comment]
Almost double wall hp and 75% armor? I see no issues that could arise from this

**Comment by Kapu1178** [comment]
> this wouldnt affect devastating explosions destroying walls, yes? does that just qdel the wall?

Explosions don't deal damage to the wall, they use a switch statement based on 3 power values (light heavy devastating) to do work. That's a long way of saying it qdels the wall.

**Comment by coldironwarrior** [comment]
> Explosions don't deal damage to the wall, they use a switch statement based on 3 power values (light heavy devastating) to do work. That's a long way of saying it qdels the wall.
ty!!! explains a ton. that understood now, i think fixing what belltop pointed out about crusher maybe RNG deleting a wall would be good. otherwise, i dont think this would be a bad change for the game. maybe not the most relevant or exciting one. but considering most (sane) rounds, walls are being flattened with explosions for the most part anyways, this all seems okay.

**Comment by Helg2** [comment]
> Explosions don't deal damage to the wall, they use a switch statement based on 3 power values (light heavy devastating) to do work. That's a long way of saying it qdels the wall.

Bruh, yes they do
`/turf/closed/wall/ex_act(severity)
	if(resistance_flags & INDESTRUCTIBLE)
		return
	switch(severity)
		if(EXPLODE_DEVASTATE)
			dismantle_wall(FALSE, TRUE)
		if(EXPLODE_HEAVY)
			if(prob(75))
				take_damage(rand(150, 250), BRUTE, BOMB)
			else
				dismantle_wall(TRUE, TRUE)
		if(EXPLODE_LIGHT)
			take_damage(rand(0, 250), BRUTE, BOMB)
		if(EXPLODE_WEAK)
			take_damage(rand(0, 50), BRUTE, BOMB)`

**Comment by shelteredfreak** [comment]
How will this affect the Crusher ecology...

**Comment by zzurge** [comment]
Hey if xeno walls get stronger to bullets why cant rwalls too?

**Pull request merged**
