### PR TITLE
Warrior Grapple toss distance is 4 tiles with a 0.5s stun.

### PR DESCRIPTION
**Pull request by Passe2142**
## About The Pull Request

Changes the distance for grapple toss to 4 tiles and halves the stun duration to 0.5s.

## Why It's Good For The Game

Warrior is no longer is the fisher machine it was, but grapple toss should have some use instead of a 3 tiles displacement. With 4 tiles it would have more utility but will give the marine a chance with a mini stun. Warrior is mostly a playmaker, not an easy fisher like cursher or shrike.

## Changelog
:cl:
Balance: Grapple toss distance from 3 tiles to 4 with 0.5 seconds of stun from 1s.
/:cl:

### CODE REVIEW

**Comment by bobmancer343** [comment]
Good pr, gives marine enough time to react without a long stun and makes fishing semi-viable without fling

**Review by BraveMole — APPROVED** [review]
I like this

**Comment by David-Stormwell** [comment]
Seems good enough, a extra tile for a minor stun reduction.

**Review by BraveMole — APPROVED** [review]
David said yes

**Pull request merged**
