### PR TITLE
Adds Retrograde Sentinel Strain

### PR DESCRIPTION
**Pull request by Notamaniac**
## About The Pull Request

Readds the (not quite) OG Sentinel, with their gloriously underpowered 22 damage IFF acid spit, 40 stam damage 4u neurospit, and slightly useless neurotox sting.

## Why It's Good For The Game

It probably isn't, but A : I wanna see how old Sentinel stacks up in the new meta, B : If it's any stronger than current Sent, C : This was just an experiment to see if I could get strains working

## Changelog
:cl:
add: Adds Retrograde Sentinel Strain, which has the Sentinels old neurospit, acid spit and neurotox sting. Primo is replaced with a neurogas grenade (which is transparent)
/:cl:

### CODE REVIEW

**Comment by Araulius** [comment]
fellow old bundles of sticks, we are so back

**Comment by Kuro020** [comment]
is this using regular sentinel wounded sprites? cant see on icon diff

**Comment by Notamaniac** [comment]
yes it's using the same wounded overlay sprites as standard sent

**Comment by Notamaniac** [comment]
forgot I need to handle how primo works

**Comment by Barnet2** [comment]
It's peak

**Comment by Lauwma** [comment]
Would be more thematic if it was full neuro instead of acid and neuro. + acid iff is really a bruh thing litteraly no castes has that now

**Comment by Notamaniac** [comment]
> Would be more thematic if it was full neuro instead of acid and neuro. + acid iff is really a bruh thing litteraly no castes has that now

Uh the theme was that it was old sent, and old sent had acid spit. (Unless you meant the CM OG Sentinel, which had hard stun spit). Also the IFF acid spittle is the same one used by scorpions.

**Review by Kuro020 — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]
code ok

**Comment by bestpartui** [comment]
Stray pixel in the top right of the resting sprite

image

**Comment by Notamaniac** [comment]
woops

**Comment by Wisemonster** [comment]
So is this on par with a T2? Cause currently, you have to wait for you're evo timer to finish before you can even evolve to this strain, meaning you can either strain swap, or evo to T2. And if it's not on par with a T2, then swapping to another T1 isn't really worth waiting the entire evo timer.

**Comment by Notamaniac** [comment]
> So is this on par with a T2? Cause currently, you have to wait for you're evo timer to finish before you can even evolve to this strain, meaning you can either strain swap, or evo to T2. And if it's not on par with a T2, then swapping to another T1 isn't really worth waiting the entire evo timer.

It's not meant to be on par with a T2, but I'm not exactly sure if waiting out the evo timer is meant to be intended or not

**Comment by Notamaniac** [comment]
There's currently a bug that causes the server to crash when attempting to strain swap over 420 upgrade. Trying to look into it, but since even my local server locks up completely I can't get logs

**Comment by Notamaniac** [comment]
Okay, seems like it was the wrong upgrade define on /mob/living/carbon/xenomorph/sentinel/retrograde. There may be deeper spaghetti to solve (i.e. not causing the entire server to lockup on getting the wrong upgrade define), but that's currently out of scope.

**Comment by Wisemonster** [comment]
Currently, there's a bug where sentinel and retro sentinel cannot regress to larva, but rather can "regress" to another T1.

**Comment by Notamaniac** [comment]
adding CASTE_TRAIT_SWAP in caste traits causes the problem, which implies that it has to be added somewhere else (i.e. when the caste trait swap verb button is pushed)

**Comment by Notamaniac** [comment]
womp womp

**Comment by Notamaniac** [comment]
@TiviPlus remove stale and tm pls

**Comment by Notamaniac** [comment]
Display named changed to Sentinel on request, so you don't get Prime Primordial Retrograde Sentinel as a name. Bloating Hive status currently an issue out of scope.

**Pull request merged**
