### PR TITLE
Medical Scanners are now infinite in the MarineMed

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
The HF2 health analyzer is now infinite in the marine vendor, just like basic injectors, splints or basic meds, or syringes.

## Why It's Good For The Game
There's really no reason for marines to ever run out of those, given they are in every medical medikit, starter sets of equipment and such. So, there's no reason to restrict their supply either. 

## Changelog
:cl:
add: Medical Scanners are now infinite in the MarineMed
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
balance freeze

**Comment by lbnesquik** [comment]
I will be back

**Comment by RipGrayson** [comment]
Going to reopen this at the request of lbnesquik since balance freeze is over. Maints can close it again if needed.

**Comment by ju45he** [comment]
Fuck you, making me have to change every single one of my loadout's bags to include yet another item.

**Comment by lbnesquik** [comment]
cope

**Comment by Kuro020** [comment]
theres a module called vali that gives infinite health scans, overall dont feel like this is necessary

**Comment by Xander3359** [comment]
+ You can always ask a medic to right click-scan you as per https://github.com/tgstation/TerraGov-Marine-Corps/pull/12467

**Pull request closed without merging**
