### PR TITLE
Improving medical storages and tool pouch.

### PR DESCRIPTION
**Pull request by HolisticDelight**
## About The Pull Request
Surgery kit now have tools in it, no more field surgeons suffering.
Medical belts now have dexalin, alkysine and imidazoline pill bottles in it.
Corpsman webbing, medical storage for jaeger, and medkit/medpouch can hold health analyser, evac roller beds, bodybags for corpses.
Tool pouch now have welder in it.

## Why It's Good For The Game
Yes.

## Changelog
:cl: HolisticDelight
tweak: Lifesaver belt and medical rig now have pill bottles with: dexalin, alkysine, imidazoline. Medical storage of jaeger may now hold health analyser, bodybags, rollerbeds. Surgery webbing now have surgery tools in it. Tool pouch now holds welder.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
Tool pouch was at max capacity with its tool storage, as far as I remember. Did the blowtorch replace another tool, or was the capacity increased by 1 to fit it?

**Comment by TiviPlus** [comment]
powercreep

**Comment by SplinterGP** [comment]
toolbelt exists for a reason lol

**Comment by Losenis** [comment]
Toolbelts exist to remind us that coders didn't clean up and removed them yet

**Pull request closed without merging**
