### PR TITLE
Buffs Selling Xenomorph corpses

### PR DESCRIPTION
**Pull request by Spyroshark**
Increases the points given for selling xeno corpses in requisitions. Also makes the defiler's body sellable.

Why: right now selling xeno bodies aren't worth selling at all, you'd need to sell 3 drones or a T3 just to buy a regular ammo crate.

:cl:
tweak: Xenomorph corpses now sell for more in requisitions.
fix: You can sell Defiler, Shrike, and Larva corpses now.
/:cl:

### CODE REVIEW

**Comment by factoryman942** [comment]
add shrike too

**Comment by Spyroshark** [comment]
shrike added

**Comment by Rushnagar** [comment]
Can you change the changelog a bit?

>fix: You can sell Defiler, Shrike and Larva corpses now.

Its a small step but it'll help discourage Carrier hugger wars. Each surgery will give a Marine req points now. I like it.

**Comment by Spyroshark** [comment]
added that to the changelog, i forgot they gave no points before.

**Comment by spookydonut** [comment]
What even is this code, @spookydonut go rewrite these export datums for xenos

**Comment by psykzz** [comment]
Do you plan to add selling xeno eggs too?

**Pull request merged**
