### PR TITLE
removes var/ from proc params

### PR DESCRIPTION
**Pull request by spookydonut**
applies #2046

### CODE REVIEW

**Comment by psykzz** [comment]
The not opposed to this but the reason i did it in changed files only was to enforce this over time, instead of the sweeping change like this.

If we do want to do this ill update my PR to enforce it on every file instead.

**Comment by DominikPanic** [comment]
> 
> 
> The not opposed to this but the reason i did it in changed files only was to enforce this over time, instead of the sweeping change like this.
> 
> If we do want to do this ill update my PR to enforce it on every file instead.

If your PR was merged travis would not compile until this was fixed

**Comment by Rohesie** [comment]
Travis check.

**Comment by spookydonut** [comment]
this is separate from #2046, this just brings the current code into compliance with what that will enforce

**Comment by psykzz** [comment]
> If your PR was merged travis would not compile until this was fixed 

Why not @DominikPanic ?

**Comment by DominikPanic** [comment]
> 
> 
> > If your PR was merged travis would not compile until this was fixed
> 
> Why not @DominikPanic ?

if you add a check to make something fail without fixing the stuff that makes it fail travis wouldn't be happy

**Pull request merged**
