### PR TITLE
Add alternative Peri+ Hypo

### PR DESCRIPTION
**Pull request by Fallouttec**
## About The Pull Request

Adds in an alternative Large Hypo with Peri+ that has less Peri than the original but comes premixed with Dylovene in quantity to counter the toxin buildup of Peri+.

## Why It's Good For The Game

Currently, new Corpsman may not realize how toxic Peri+ is when using it for healing organs, and they can forget to give Dylovene to help counter the toxin buildup. This version of the Peri+ Hypo is a large version with 10u Peri+ and 110u Dylovene at 12u inject. thus only 10 uses rather than the original 20 uses of the old small hypo. You get less peri than the original but in such a format that its just inject and go rather than needing to double up on the meds, but the old one stays the same to encourage using it for more advanced cocktails of chems. Autoinjectors are not affected.

## Changelog

:cl:
add: New Large Peri+ Hypospray which uses a different chemical mix to the original, does not require anti-toxin to be administered separately but has less uses compared to the original.
/:cl:

### CODE REVIEW

**Comment by Wisemonster** [comment]
Doesn't Dylo affect stamina regen? So now if I take peri+, I can't be on the front until I either purge the dylo, or wait for it to run out, else I risk running out of stamina while chasing/being chased. It might be better to either give hyrolin a weaker toxin purge similar to dylovene, or just increase the amount in the injectors.

**Comment by Fallouttec** [comment]
Upon review of the code; having Dylovene in your system simply Adds -0.5 to stam regen while it exists in your body, it will not negatively drain stamina and only increases time it takes to regain stamina by cutting regen rate in half. Assuming no other chemicals are present

**Comment by jroinc** [comment]
This was originally intended: the goal was to minimize one-click cure-alls from vendors and to preserve a role for chemistry/reward taking the time to make a custom injector.

If you made a custom mix, you get the single-click; if you did *not*, you had to give a pill/10u inject of dylo: this also meant that you had to actually slow down and remain near the medic rather than unga-sprinting off.

**Comment by jroinc** [comment]
-editing the title might also be reasonable; this is not "removing one chemical"; it's a full rework of the injector and **halving** the amount of Peri+ medics can acquire from a purchase.

**Comment by Wisemonster** [comment]
I should also add, tricordrazine already heals the damage from toxin without the downside dylo has, and is easy for marines to access. Not to mention, the damage from toxin is slow. This pr effectively nerfs peri+ injectors.

**Comment by jroinc** [comment]
> I should also add, tricordrazine already heals the damage from toxin without the downside dylo has, and is easy for marines to access. Not to mention, the damage from toxin is slow. This pr effectively nerfs peri+ injectors.

Tricord doesn't purge the toxin, and a single peri+ inject adds 50u of toxin. The damage per tick is minimal, but it _does_ take 500 ticks to leave your system (~7 tricord pills).

**Comment by Fallouttec** [comment]
Really I felt the Hyrolin did basically next to nothing other than act as filler, as its healing barely really did much of any to the toxin reagents added by Peri which can be substantial. Dylovene inherently has the purge toxin tag so it would auto purge out toxins as they built up, as right now if I'm Corpsman I just hit both Peri and Dylovene together, I understand that the original intent was to reward players for creative and their own special mixes, but with newer corpsman it might be best to give them meds they can only Overdose marines on if they aren't careful rather than accidentally giving someone who is low Peri+ because you saw Heart damage and now he is in crit with building toxin damage.

**Comment by Lumipharon** [comment]
Peri+ doesn't need to be safer.
As well as the smelly injector creep, good medics simply use hyper afterwards to rapidly purge the toxin, to minimize downside.

**Comment by Looking4bros** [comment]
1u Peridaxon+ creates 50u of toxin reagent that metabolises at a rate of 0.1u per tick. As mentioned above it's not actually that dangerous, but the idea that you're going to just run off after getting a peri injection is already a dumb idea, as it damages stamina itself. You only need 9.2u of Dylovene per unit of Peri+ (9u dylo purges 45u of toxin, and the toxin will metabolise 4.5u in that time, hence the 0.2u addition, but not needed due to how weak toxin is) Toxin is in fact so weak that it's honestly an afterthought and only becomes problematic when it damages the kidney from sitting around in their system for so long. I use Hyronalin to PwrGame Neuraline, but there are other sources.

Hypering after peri doesn't purge all the toxins either, Toxin(reagent) really is that weak. (one pill only purges 15u)

An alternative would be to use Rye, but Rye gets purged by Bicaridine, Kelotane, and Tricordrazine, which is normally used, so wouldn't fit the bill on most people. But if you are one of those people, you'd only need 1u! as it purges at a rate of 5u, the same as it is being introduced. (more like, half a unit because it metabolizes so slowly, but whatever.)

**Comment by Looking4bros** [comment]
Wait, do people actually buy the Peri+ or QC+ hypos? lmao. Just get the Autoinjector pouches.

**Comment by Ldip999** [comment]
> An alternative would be to use Rye, but Rye gets purged by Bicaridine, Kelotane, and Tricordrazine, which is normally used, so wouldn't fit the bill on most people. But if you are one of those people, you'd only need 1u! as it purges at a rate of 5u, the same as it is being introduced. (more like, half a unit because it metabolizes so slowly, but whatever.)

500 chemrettes neurokillers

**Comment by Looking4bros** [comment]
> 500 chemrettes neurokillers

I LOVE NEUROKILLER!!!!!!!! I USED TO RUN A GENERAL POUCH OF JUST NEUROKILLER!!!!!!!!!!! RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!!!!!!!!

But seriously, don't smoke Neurokiller before the Peri+ has all metabolised, which is ten ticks(~twenty seconds), as Neurokiller has water in it and will purge the Peri+ before it does it's job and just gives them cloneloss, lmao.

**Comment by Fallouttec** [comment]
Really theres about a half dozen or so ways to go about it, and like said it seems that the way its designed was intentional to get Corpsmen to go to chem and mix up their own custom batches rather than rely on the stuff the vendors give. Hyrolain may seem weird but it is a nice by product of the injector pouches you get as a corpsman and it is useful in custom mixes. So really i feel this doesn’t really serve any purpose anymore but was a fun discussion regardless.

**Comment by Fallouttec** [comment]
> Wait, do people actually buy the Peri+ or QC+ hypos? lmao. Just get the Autoinjector pouches.

Yeah… i did.

**Comment by Fallouttec** [comment]
> Peri+ doesn't need to be safer. As well as the smelly injector creep, good medics simply use hyper afterwards to rapidly purge the toxin, to minimize downside.

I just hit with dylovene since it purges toxins and heals tox damage at the same time, plus its free.

**Comment by Looking4bros** [comment]
>Yeah... i did.

Weeeeeelll, the Peri+ Hypospray *IS* the best way to kill the deathsquad, as they don't have injection protection and it kills people in like ten seconds or something. Good talk, i like having them. o7

**Comment by Fallouttec** [comment]
> 1u Peridaxon+ creates 50u of toxin reagent that metabolises at a rate of 0.1u per tick. As mentioned above it's not actually that dangerous, but the idea that you're going to just run off after getting a peri injection is already a dumb idea, as it damages stamina itself. You only need 9.2u of Dylovene per unit of Peri+ (9u dylo purges 45u of toxin, and the toxin will metabolise 4.5u in that time, hence the 0.2u addition, but not needed due to how weak toxin is) Toxin is in fact so weak that it's honestly an afterthought and only becomes problematic when it damages the kidney from sitting around in their system for so long. I use Hyronalin to PwrGame Neuraline, but there are other sources.
> 
> Hypering after peri doesn't purge all the toxins either, Toxin(reagent) really is that weak. (one pill only purges 15u)
> 
> An alternative would be to use Rye, but Rye gets purged by Bicaridine, Kelotane, and Tricordrazine, which is normally used, so wouldn't fit the bill on most people. But if you are one of those people, you'd only need 1u! as it purges at a rate of 5u, the same as it is being introduced. (more like, half a unit because it metabolizes so slowly, but whatever.)

Honestly i feel Hypervene is really weak-sauce in terms of purgative, since a 3u dose pill only purges 15u. When the dam CL Od’s himself on 500u of tramadol your only hope is the sleeper pod anyhow.

**Comment by Fallouttec** [comment]
> > Yeah... i did.
> 
> Weeeeeelll, the Peri+ Hypospray _IS_ the best way to kill the deathsquad, as they don't have injection protection and it kills people in like ten seconds or something. Good talk, i like having them. o7

You have given me forbidden knowledge, i wonder if Peri+ hypo could be obtained in Campaign…

**Pull request closed without merging**
