### PR TITLE
Fixes areas that should be buildable pre shutter open in Big red

### PR DESCRIPTION
**Pull request by vilereaver41**
## About The Pull Request

Some areas where xenos should be allowed to build weren't buildable

## Why It's Good For The Game

Cause fix barance

## Changelog
:cl:
balance: No build zone fixes 
/:cl:

bigred2

### CODE REVIEW

**Comment by RipGrayson** [comment]
I'm not entirely sure what you're trying to do here. Could you justify the changes a little bit more in your own words?

**Review by TiviPlus — APPROVED** [review]
Grayson pr

**Comment by vilereaver41** [comment]
> I'm not entirely sure what you're trying to do here. Could you justify the changes a little bit more in your own words?

The areas inside the green sqaures should be buildable to xenos, they currently arent.

**Comment by RipGrayson** [comment]
> > I'm not entirely sure what you're trying to do here. Could you justify the changes a little bit more in your own words?
> 
> The areas inside the green sqaures should be buildable to xenos, they currently arent.

What I mean is, I would like a little more justification for why these areas should be buildable pre-shutter opening. "Cause fix barance" isn't particularly descriptive and doesn't tell me why the area needs changed.

**Pull request closed without merging**
