### PR TITLE
conveyor belts n switches on the op vendor

### PR DESCRIPTION
**Pull request by FosterGrime-Heymynameslouie**
## About The Pull Request

Conveyor belts and switches on the vendor to smoothen out the experience of reqtorio without having to shove metal and wait for it to print in the autolahte. You can already print effectively infinite conveyors and switches in the autolathe, this PR attempts to streamline it.

## Why It's Good For The Game

smoother reqtorio experience

## Changelog
:cl:

add: conveyors and conveyor switches to op vendor

/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
You can get infinite metal from this

**Comment by FosterGrime-Heymynameslouie** [comment]
> You can get infinite metal from this

you could also get infinite metal from shoving mass amounts of infinite guns into lathe
only limited by the fact that a single gun gives 30 materials and a single metal piece costs something absurd like 5000+

**Comment by chizzy376** [comment]
> > You can get infinite metal from this
> 
> you could also get infinite metal from shoving mass amounts of infinite guns into lathe only limited by the fact that youd die of starvation before printing 10 metal (ive tried before, it took 22 minutes), a single gun gives 30 materials and a single metal piece costs something absurd like 5000+

Conveyors are very easily duped, 12 metal per batch. Takes 3 mins for 12 metal.

**Comment by chizzy376** [comment]
To be more specific: Right now, you can go to an autolathe. Print 30 conveyor stack for 52 (autolathe) metal. You get a stack of 30. Put that back into the autolathe. You get 1500 (autolathe) metal. A real sheet costs 4000 (autolathe) metal. Thanks to this PR, you'll be able to print infinite conveyors at vendor, put them in one of your patented mass produced crates (A PR which I also found to be unnecessary), drag it over to the autolathe and spam infinite metal. By my calculations you'll be able to get 50 metal sheets in less than 5 mins.

**Pull request closed without merging**
