### PR TITLE
Makes larva able to ride crushers

### PR DESCRIPTION
**Pull request by iLikeMemes**
## About The Pull Request

Larva could not ride crushers before, with this PR they can.

croosh1
croosh3
croosh4

https://imgur.com/a/ltI9BR6 (low quality imgur gif)

## Why It's Good For The Game

Larva on da crusher, what he gonna do?

## Changelog
:cl:
expansion: Xeno larva are now able to ride crushers.

/:cl:

### CODE REVIEW

**Comment by iLikeMemes** [comment]
ill add a couple of pictures/video in a bit of how it looks, file size fucking me over

**Comment by FIXTHERADBOXPLEASE** [comment]
Any chance you can evolve on the crusher so as to have the Queen ride her noble steed into battle?

**Comment by iLikeMemes** [comment]
> Any chance you can evolve on the crusher so as to have the Queen ride her noble steed into battle?

might be possible, havent checked, gonna take a closer look at that interaction and see if nothing breaks. (until then dont merge)

**Comment by iLikeMemes** [comment]
Evolving whilst on the back of a crusher will in fact just unbuckle you. Also not going to add queen being able to ride crushers because queen would litteraly crush the crusher due to her sheer size

anyway PR ready for merge.

**Review by BraveMole — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]
This will ruin the walance

**Comment by UltraBigRat** [comment]
tactical larba

**Pull request merged**
