### PR TITLE
Removes Spaceship Orbits

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title. See [#14548](https://github.com/tgstation/TerraGov-Marine-Corps/pull/14548#issuecomment-1828722959) for context.
Changes based on contents of #3434, #5371, and #5983. 

## Why It's Good For The Game
I admittedly only wanted to hit CAS's ordnance travelling speeds at first, but as per Lumi's words, I've instead decided to take out this mechanic. I don't think it is a good thing to have in the present, nor does it help with the various issues related to requisitions point gains, CAS ordnance travel times, and more.

## Changelog
:cl: Lewdcifer
balance: Removed spaceship orbits and all related mechanics.
/:cl:

### CODE REVIEW

**Comment by coldironwarrior** [comment]
i like the risk of going low orbit for better hits but less prep time for shipside :(
also low orbiting for nuke to evac everyone and get them to the ship for round end so they arent stuck on the aylamo forever

**Comment by DeltaFire15** [comment]
Nerfs pasive Req income, the biggest nonissue. Nerfs marine prep time on hijack. Nerfs CAS by removing both its specialized options. Removes every single tactical layer created by having multiple orbits. Whats up with PRs lately.

**Comment by Strayed-Raven** [comment]
Cannot be connected with reducing req points right?

**Comment by novaepee** [comment]
Spaceship orbit is one of the few features that I will remember Hughgent fondly for. Personal bias, I don't want to see spaceship orbit dying.

**Comment by dopamiin0** [comment]
"I don't think it's a good thing to have" isn't really a valid reason to flat-out remove a mechanic. Orbit creates some base levels of decision making and things to do that command sorely lacks.

**Comment by MiniMeatwad** [comment]
CAS goes on a wild ride from orbit 1-5 between instant death omnipresent around marines, mostly useless at default, to a negative to the team as a FF machine at high orbit.

Just balance CAS statically.

**Comment by Strayed-Raven** [comment]
Now that I 

> CAS goes on a wild ride from orbit 1-5 between instant death omnipresent around marines, mostly useless at default, to a negative to the team as a FF machine at high orbit.
> 
> Just balance CAS statically.

This sounds much better. Maybe give CAS the baseline of orbit three speeds. but you can choose to go orbit one speeds at much greater fuel consumption?

**Comment by SimplySmiley123** [comment]
> Now that I
> 
> > CAS goes on a wild ride from orbit 1-5 between instant death omnipresent around marines, mostly useless at default, to a negative to the team as a FF machine at high orbit.
> > Just balance CAS statically.
> 
> This sounds much better. Maybe give CAS the baseline of orbit three speeds. but you can choose to go orbit one speeds at much greater fuel consumption?

Honestly that does sound awesome, would give something for a Condor pilot to think about with trade-offs for how useful they wanna be.

Because, yeah, CAS on lower orbit actually works and hits anything, while on default and higher orbits you'll barely hit anything from what I seen and experienced on both sides, while often times not even really functioning well as a detterent for xenomorph pushes and more of a liability to your own marines trying to move around or chase anything.

**Comment by lbnesquik** [comment]
> Now that I
> 
> > CAS goes on a wild ride from orbit 1-5 between instant death omnipresent around marines, mostly useless at default, to a negative to the team as a FF machine at high orbit.
> > Just balance CAS statically.
> 
> This sounds much better. Maybe give CAS the baseline of orbit three speeds. but you can choose to go orbit one speeds at much greater fuel consumption?

That sounds like a much more fun idea.

**Comment by chizzy376** [comment]
nop, closed

**Pull request closed without merging**
