### PR TITLE
Fix ravage

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
very ez fix
## Changelog
:cl:
fix: fixed ravage not working on humans
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
But why is it good for the game? kek

**Comment by DerpiestBruh** [comment]
rav mains go home

**Review by BraveMole — CHANGES_REQUESTED** [review]
What about xenos from other hives

**Comment by TiviPlus** [comment]
> What about xenos from other hives

Can we have someone else do this I dont feel like doing it and it didnt work before either

**Pull request merged**
