### PR TITLE
Reduces CAS Weapon Prices, Rebalances CAS Ammo Prices, Miners Give Dropship Points

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Miners now produce dropship points. Tad pilots rejoice! 15 points for phoron miners, 30 for platinum miners (1/10th of regular point generation, in parity with intel points)

Reduces GAU cannon price 400 -> 100 (People rarely even install the spares let alone print them, they do not need to be that expensive)
Reduces rocket minipod price 600 -> 150 (People can't experiment with prices this prohibitive)
Reduces rocket pod price 600 -> 150 (same as above)

Reduces incendiary minirocket price 200 -> 150 (Really not worth 200 points)

Reduces Keeper II rocket price 300 -> 175 (A bit overpriced for what it is atm)
Reduces Napalm rocket price 200 -> 150 (Strong area denial weapon, but not really worth 200)

Also changes some descriptions to be more helpful.

## Why It's Good For The Game

CAS suffers from poor return on investment on a fair few of its weapons, and punishing experimentation pretty severely. Hopefully much cheaper guns and a price reduction in some of the least used and valuable options will give CAS pilots a bit more to play with.

Also CAS (and the tad to an extent) should get some form of reward for helping to secure miners without asking req, especially when the tad is often used for securing miners. 

## Changelog

:cl: Tupina
add: Miners now generate dropship points as well as requisition points. POs get a reward for tadpolling, hooray!
balance: Reduces roundstart CAS weapon print prices by 1/4th the original cost.
balance: Incendiary minirocket cost 200 -> 150
balance: Keeper II rocket price 300 -> 175
balance: Napalm rocket price 200 -> 150
/:cl:

### CODE REVIEW

**Comment by Luxyboo** [comment]
holy shit

**Comment by UsernameIs-UnAvailable** [comment]
Fucking why. CAS is bad enough to play against due to spam with no counter play, why make it worse.

**Comment by Zar000** [comment]
I can agree that CAS has to basically min-max and there is very little room for experimentation and trial & error. But this is not the way lmao.

If you want these prices I would consider also looking at inaccuracy modifiers, travel time. Maybe giving rockets more depth like a fuze time , example

Incendiary minirocket fuze time = -1 , It will explode before hitting ground and thus the fire will be larger but last less.
Incendiary minirocket fuze time = 1, it will explode after 1 second of hitting the ground. Small area of effect but lasts way longer. 

This would give CAS more control of their armaments & element of surprise for xenos & fun & variety without making CAS able to shit out metric tons of everything due to price reductions

**Comment by Al-1ce** [comment]
As it stands, the Condor is not very fun to play - namely due to the lack of options. Most things are so ridiculously expensive that you'll be stuck with the default equipment for **most** of the round. Having to wait half an hour (or more) to be able to buy a _SINGLE_ lasergun and battery is ridiculous. 


> Fucking why. CAS is bad enough to play against due to spam with no counter play, why make it worse.


Spam is inefficient and rarely will POs waste their munitions, because of how goddamn expensive they are. I admit this gives _some_ leeway if you're into that, - but it isn't the main takeaway and doing so will still **rapidly** chew through your funds.

What we should all keep in mind here is that the equipment itself is __not__ being changed. Merely the prices. Everything this PR touches is already usable by CAS - and generally underwhelming or stupid easy to avoid.

The PO will still have to manually reload every rocket, magazine, laser and whatever. They will still have to sit around and beg for a flare. They will still have to constantly refuel and wait for the rare opportunity where they can be genuinely useful.

I've got around 112 hours on PO - having flown the Condor for about half that - I can say without a doubt that this change is a good stepping stone into making CAS more fun and overall intuitive as a whole.

+1 imo

**Comment by Naaanii** [comment]
Reducing weapon type price is good. Reducing ammo price not so much. 

The ammo prices are high because of how effective they were in the past and without actually nerfing their effectiveness like with Tfoot minirockets or the laser, they don't really require a price reduction.

**Comment by Tupinambis** [comment]
> Reducing weapon type price is good. Reducing ammo price not so much.
> 
> The ammo prices are high because of how effective they were in the past and without actually nerfing their effectiveness like with Tfoot minirockets or the laser, they don't really require a price reduction.

Tfoot I was thinking of reverting regardless, and I might lower the weapon prices a bit more.

I'd like an idea of how to balance the ammo because it still feels too high as it stands. Should I reduce how much of a reduction I give things? Any standout issues besides tfoot?

It's important to keep in mind that CAS used to use one laser for everything when the prices were set, and the fact it no longer does, telling the xenos exactly what's coming, significantly changes the dynamic.

**Comment by Naaanii** [comment]
> > Reducing weapon type price is good. Reducing ammo price not so much.
> > The ammo prices are high because of how effective they were in the past and without actually nerfing their effectiveness like with Tfoot minirockets or the laser, they don't really require a price reduction.
> 
> Tfoot I was thinking of reverting regardless, and I might lower the weapon prices a bit more.
> 
> I'd like an idea of how to balance the ammo because it still feels too high as it stands. Should I reduce how much of a reduction I give things? Any standout issues besides tfoot?
> 
> It's important to keep in mind that CAS used to use one laser for everything when the prices were set, and the fact it no longer does, telling the xenos exactly what's coming, significantly changes the dynamic.

Like I said, reducing the effectiveness would be better to gauge and justify the cost reduction. While Xenos can see the Tfoot coming, its still a very good suppressive tool. Keeper rewards direct hits really well while banshee has a large aoe which makes it easier to hit but the damage itself isn't great.

Increasing point gen or giving dropship vouchers (yet another) buff seems better because you're actually spending on it. I feel the cost as of now is okay because it punishes spam heavy CAS and unless they're racking up corpses, they won't be able to replenish it that easily. I do however agree Keeper should be lowered to at least 200 as it is underwhelming compared to FATTY, which since its revert is the best missle out of all in my opinion. Napalm also feels very underwhelming and I agree with the cost reduction.

On a side note if miners could also contribute to dropship points, it would be <s>funny</s> and pretty cool ngl.

**Comment by Tupinambis** [comment]
> > > Reducing weapon type price is good. Reducing ammo price not so much.
> > > The ammo prices are high because of how effective they were in the past and without actually nerfing their effectiveness like with Tfoot minirockets or the laser, they don't really require a price reduction.
> > 
> > 
> > Tfoot I was thinking of reverting regardless, and I might lower the weapon prices a bit more.
> > I'd like an idea of how to balance the ammo because it still feels too high as it stands. Should I reduce how much of a reduction I give things? Any standout issues besides tfoot?
> > It's important to keep in mind that CAS used to use one laser for everything when the prices were set, and the fact it no longer does, telling the xenos exactly what's coming, significantly changes the dynamic.
> 
> Like I said, reducing the effectiveness would be better to gauge and justify the cost reduction. While Xenos can see the Tfoot coming, its still a very good suppressive tool. Keeper rewards direct hits really well while banshee has a large aoe which makes it easier to hit but the damage itself isn't great.
> 
> Increasing point gen or giving dropship vouchers (yet another) buff seems better because you're actually spending on it. I feel the cost as of now is okay because it punishes spam heavy CAS and unless they're racking up corpses, they won't be able to replenish it that easily. I do however agree Keeper should be lowered to at least 200 as it is underwhelming compared to FATTY, which since its revert is the best missle out of all in my opinion. Napalm also feels very underwhelming and I agree with the cost reduction.
> 
> On a side note if miners could also contribute to dropship points, it would be funny and pretty cool ngl.

The funny has been completed.

**Comment by Naaanii** [comment]
> > > > Reducing weapon type price is good. Reducing ammo price not so much.
> > > > The ammo prices are high because of how effective they were in the past and without actually nerfing their effectiveness like with Tfoot minirockets or the laser, they don't really require a price reduction.
> > > 
> > > 
> > > Tfoot I was thinking of reverting regardless, and I might lower the weapon prices a bit more.
> > > I'd like an idea of how to balance the ammo because it still feels too high as it stands. Should I reduce how much of a reduction I give things? Any standout issues besides tfoot?
> > > It's important to keep in mind that CAS used to use one laser for everything when the prices were set, and the fact it no longer does, telling the xenos exactly what's coming, significantly changes the dynamic.
> > 
> > 
> > Like I said, reducing the effectiveness would be better to gauge and justify the cost reduction. While Xenos can see the Tfoot coming, its still a very good suppressive tool. Keeper rewards direct hits really well while banshee has a large aoe which makes it easier to hit but the damage itself isn't great.
> > Increasing point gen or giving dropship vouchers (yet another) buff seems better because you're actually spending on it. I feel the cost as of now is okay because it punishes spam heavy CAS and unless they're racking up corpses, they won't be able to replenish it that easily. I do however agree Keeper should be lowered to at least 200 as it is underwhelming compared to FATTY, which since its revert is the best missle out of all in my opinion. Napalm also feels very underwhelming and I agree with the cost reduction.
> > On a side note if miners could also contribute to dropship points, it would be funny and pretty cool ngl.
> 
> The funny has been completed.

Based af

**Comment by chizzy376** [comment]
The uncounterable spam gets spammier.. why?

**Comment by Araulius** [comment]
maybe instead of doing this, buff the dropship fabricator voucher from req?

**Comment by Redrover1760** [comment]
> The uncounterable spam gets spammier.. why?

Have you tried dodging

**Comment by Pariah919** [comment]
CAS should probably get split into high impact expensive weaponry that's very devastating to be hit by and SPAM weaponry that's dead cheap and mostly for area denial in a noticeable way honestly

**Pull request closed without merging**
