### PR TITLE
Adds moan sound to the emote.

### PR DESCRIPTION
**Pull request by Sebbe9123**
## About The Pull Request
Slightly meme pr but...
Requested by Spacelove first in OOC, volunteered to do it and got a ping for an update. It's also funny.
https://i.imgur.com/IVQ4sLi.png
https://i.imgur.com/TaMQxND.png
This PR adds a soundfile to both the male and the female *moan emote, Should not be overtly sexual in any way on their own.
Not sure how to put in the sound files here for people to hear them, think both were posted on discord.

## Why It's Good For The Game
Good question, I guess it moves towards standardizing all emote to have a sound attached to them.

## Changelog
:cl:
soundadd: adds sound to both male and female *moan
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
i'm sorry **_W H A T_**

**Comment by BraveMole** [comment]
how bout no?

**Comment by SpaceLoveSs13** [comment]
Yes absolutely. Sounds should be added. The moans are not sexualized and actual human voice adds bit of sense into the game. So please.

**Comment by SplinterGP** [comment]
The *scream are almost a moan already so i think its fine, i havent heard the moans already though

**Comment by Sebbe9123** [comment]
> The *scream are almost a moan already so i think its fine, i havent heard the moans already though

The audio channel is archived so I can't post it there, but I'll shove the two files into #dev-general.

**Comment by sunofang** [comment]
Make it a pained moan instead of a pleasured moan. Make it sound like a death rattle.

**Comment by lbnesquik** [comment]
Bit too suggestive, also it will get spammed to an annoying degree for sure

**Comment by bowlofcereal** [comment]
No.

**Comment by jroinc** [comment]
> 
> 
> Yes absolutely. Sounds should be added. The moans are not sexualized and actual human voice adds bit of sense into the game. So please.

Every morning I wonder, "what will spacelove do today that's borderline ERP?"
Today, I know earlier than most days.

No. This is a meme that's just gonna be used to spam *moan* on the dropship. It has no purpose besides enabling fetish ERP behavior.

**Comment by SpaceLoveSs13** [comment]
After extensive research, discussion among admin team. And my own extremely great observation, I have came to the conclusion, this will be a breach of rule 8. And i withdraw my previous opinions. I am sorry.

**Comment by Al-1ce** [comment]
this is the only good PR on the entire github

**Comment by David-Stormwell** [comment]
I swear to god

**Comment by spookydonut** [comment]
lmao

**Pull request closed without merging**
