### PR TITLE
Adds a Valhalla surgery area, modifies the marine spawner xeno button.

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Title, adds a surgery area in valhalla, and modifies the xeno caves buttons to be usable by marines.
Change Me - Pillar of Spring 6_30_2024 4_33_30 AM
## Why It's Good For The Game
The first part is so that it let's new players practice surgery without putting some helpless soul in perma-sleep. The second part is so I didn't make another button solely with the ability that marines can use it to spawn humans.
## Changelog
:cl:
add: Added a surgery practice area to marine Valhalla.
code: Modified the marine spawner buttons in xeno Valhalla to be usable by marines.
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
Does this let you spawn people that are injured in any way?

**Comment by Wisemonster** [comment]
No, however you are next to a firing range, so injuring them yourself would be rather easy.

**Comment by Arctrooper8** [comment]
> No, however you are next to a firing range, so injuring them yourself would be rather easy.

Fair, but it could still be a pain or impossible to create certain surgeries such as organ damage, larval infection, etc etc, plus it'd just be easier especially for newer players if they didn't have to create the damages themselves.

Also does anybody but the synth have surgery skills?

**Comment by Wisemonster** [comment]
FC and corpsman has a surgery skill of 1 and 2 respectively.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
