### PR TITLE
Fixes AI double spawning

### PR DESCRIPTION
**Pull request by Ldip999**
## About The Pull Request

Fixes AI being spawned twice

## Why It's Good For The Game

Makes it so that AI only gets spawned once, so that it doesn't send two announcements, the first one with incorrect name, instead only the second one with correct information.

## Changelog
:cl:
fix: Fixed AI double spawning
/:cl:

### CODE REVIEW

**Review by Lumipharon — CHANGES_REQUESTED** [review]
don't just comment out dead code.

**Comment by Ldip999** [comment]
Gone

**Comment by Lumipharon** [comment]
actually doesn't that entire if statement just need to go?

**Comment by Ldip999** [comment]
I have no idea what the rest of the statement does and I'm scared to touch it

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
it does nothing probably but w/e

**Pull request merged**
