### PR TITLE
Nerfs B18 Slightly

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Decreases B18 Melee defense slightly.

## Why It's Good For The Game

B18's seem to solo kill half the hive every third round. I get that the xenos made mistakes causing this situation but still its too strong for a single marine.

## Changelog
:cl:
balance: B18 Melee defense 80 => 60
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
Stop nerfing the b18 because of salt ffs

**Comment by ma44** [comment]
If you don't want b18 to kill entire hives by itself, slow it down while it's using it's damm minigun

>slightly reduced is a 25% reduction

**Comment by Max-023** [comment]
80 melee armor is literally the standard for gloves. You are just flat out trying to make the B18 unusable, dude.

**Comment by sunofang** [comment]
https://www.youtube.com/watch?v=NjoKUHq6NdM

**Comment by Isy232** [comment]
Okay, you know what I agree with you mostly.

Damage values are too high and making a specialist easier to kill shouldn't be the answer.

I'll be looking at the minigun instead.

**Pull request closed without merging**
