### PR TITLE
Give shotgun aimode

### PR DESCRIPTION
**Pull request by Lefunny**
## About The Pull Request

PR made to give aimode to shotguns, actually doest work with the tx shotgun and additional bullets

## Why It's Good For The Game

Shotguns kill more marines with FF than xenos. This PR is made with the idea of making it less punishable for marines who get hitted by shotguns (but still deal damage with secondary bullets)).

## Changelog
:cl:

give shotguns aimode 
shotgun aimode dont fully work with secondary bullets ((a fully made feature))
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
I'm gonna be honest, I have no idea what you typed there.

**Review by BraveMole — CHANGES_REQUESTED** [review]
I don't think shotguns should have aim mode

**Comment by Tristan63** [comment]
Try it with the TX-15 maybe. Otherwise its a massive skill issue.

**Comment by TiviPlus** [comment]
Shotguns should not have aim mode especially when it doesnt even work completely

**Pull request closed without merging**
