### PR TITLE
Maximum shield integrity reduced from 400 to 300

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title.

## Why It's Good For The Game
Currently, shields make you way too tanky. The armor's not necessarily in a bad spot, so I want to tackle reducing its maximum integrity first and see how that goes before I decide on nerfing it some more.

## Changelog
:cl: Lewdcifer
balance: Maximum shield integrity reduced from 400 to 300.
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
xenos have defender marines have imortal shield, sounds balanced to me.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Maybe out of scope, but it's even more important if the shield has less health. A "damaged" icon state (not broken, but at half hp) would be really neat

**Comment by Oscari-pog** [comment]
> 
> 
> xenos have defender marines have imortal shield, sounds balanced to me

You mean the one that cant move when fortified? While a marine can run around with a shield?

**Comment by Oscari-pog** [comment]
Oops, misread that, void my reply.

**Pull request closed without merging**
