### PR TITLE
MP-19 akimbo tweak

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Muh akimbo.

This PR is dependant on #11012 
Increased akimbo penalty for the MP-19, so that the delay between bursts in 0.25 when akimbo'd. Still likely to be deadly as all fuck, but a little bit less rediculous.

## Changelog
:cl:
balance: Increased MP-19 akimbo penalties
/:cl:

### CODE REVIEW

**Comment by Strayed-Raven** [comment]
Is the delay 0.25 or 0.5?

**Comment by Lumipharon** [comment]
the modifier is 0.5, the result is 0.25.

**Comment by Strayed-Raven** [comment]
> the modifier is 0.5, the result is 0.25.

Ah, alright then.

**Comment by MLGTASTICa** [comment]
i don't see why the strategy should be nerfed. Even as a xeno that had to play against it , it is not OP in any shape. The mag capacity on the MP-19 is a measly 30 , and the only thing that makes it remotely good is the speed it can be used to leash out, but the inaccuracy debuffs are way too great to make it meaningfull for anything other than CQC.
(It  also serves to reduce marine burst-ability against xeno-stuns , which are the only thing making any caste good right now)

**Comment by RikuTheKiller** [comment]
I'm a xeno player and going from 600 health as gorger (t3 tank, was ancient) to 0 in less than a second because of one guy who abuses this is total fucking bullshit. All the maturity and whatever the fuck else I got to get to that point gone in less than a second by a single guy with no effort. Like, come on. I understand dying to focused fire or a constant SG barrage, but like, a single guy with akimbo? Hell no.

**Comment by Strayed-Raven** [comment]
> i don't see why the strategy should be nerfed. Even as a xeno that had to play against it , it is not OP in any shape. The mag capacity on the MP-19 is a measly 30 , and the only thing that makes it remotely good is the speed it can be used to leash out, but the inaccuracy debuffs are way too great to make it meaningfull for anything other than CQC. (It also serves to reduce marine burst-ability against xeno-stuns , which are the only thing making any caste good right now)

someone just felt like it should not be that way and asked for the change. I told them it was because of the funny V21 AutoBurst behavior. But alas did not believe me. 

> I'm a xeno player and going from 600 health as gorger (t3 tank, was ancient) to 0 in less than a second because of one guy who abuses this is total fucking bullshit. All the maturity and whatever the fuck else I got to get to that point gone in less than a second by a single guy with no effort. Like, come on. I understand dying to focused fire or a constant SG barrage, but like, a single guy with akimbo? Hell no. Even something like a spear or harvester has way less DPS than this.

Just drink blood. You have the ability to have them on the ground and drain them. There are times I specifically wait for xenos to use an ability that keeps them in place to kill them because unless im hugging you it has terrible accuracy.

**Comment by Al-1ce** [comment]
Salt PR.

**Comment by private-tristan** [comment]
> Just drink blood. You have the ability to have them on the ground and drain them. There are times I specifically wait for xenos to use an ability that keeps them in place to kill them because unless im hugging you it has terrible accuracy.

actually using carnage and walking into someone when you have 50% or more blood doesn't stun them, many a gorgers have lost their life trying to use their stun ability only for it to fail and get bursted down in 1/5th of a second as the intended 'tank' xeno

yaknow Im starting to feel that this whole 'shoot 2 guns at the same time for a accuracy penalty' thing shouldn't have existed in the first place 🤔 but im just a coping xeno main that spent 30 minutes in deadchat and watched a akimbo SMG marine kill 4 xenos in 15 minutes (although you can argue it was skill issue tbh)

**Comment by Strayed-Raven** [comment]
> > Just drink blood. You have the ability to have them on the ground and drain them. There are times I specifically wait for xenos to use an ability that keeps them in place to kill them because unless im hugging you it has terrible accuracy.
> 
> actually using carnage (That's it's name, right?) and walking into someone when you have 50% or more blood doesn't stun them, many a gorgers have lost their life trying to use their stun ability only for it to fail and get bursted down in 1/5th of a second as the intended 'tank' xeno
> 
> yaknow Im starting to feel that this whole 'shoot 2 guns at the same time for a accuracy penalty' thing shouldn't have existed in the first place 🤔 but im just a coping xeno main that spent 30 minutes in deadchat and watched a akimbo SMG marine kill 4 xenos in 15 minutes (although you can argue it was skill issue tbh)

Just yesterday me and another marine kept shooting a gorger at medbay who had his buffs, think his handle was Jaliff or something, and even with me shooting and the other marines it took a good bit to crit them. Do not even know why he did not run away because he would have lived if they did. Akimbo is all about risks and rewards. You have no aim mode, and similar range as shotties. Anyone that says it has more range is forgetting not all shots spray to the sides. You have to frontline the same as the others. The only positive is smg bullets do not hit as hard as buck on FF.

**Comment by BraveMole** [comment]
@Pariah919 hello, opinion ?

**Review by Pariah919 — APPROVED** [review]
Fixes akimbo deleting while keeping normal T19 fine.

**Pull request merged**
