### PR TITLE
Flamer nerf

### PR DESCRIPTION
**Pull request by Zar000**
## About The Pull Request

Prevents normal muzzle from penetrating further than 3* tiles into resin walls
image

Prevents spray muzzle from penetrating as much
image

## Why It's Good For The Game
Currently spray nozzles are dominating xeno mazes, the justification that I recieved was that flamers need to clear mazes effectively.
This allows you to still clear mazes without the insane spread of fire behind 5 layers of mazes.

## Changelog
:cl:
balance: nerfed standard and wide flamer nozzle
code: Made it possible to set flamer penetration on resin walls
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Wide nozzle already has to flame twice to destroy resin walls, so is already horribly fuel inefficient.

**Comment by maikilangiolo** [comment]
Looks fine, as a flamer main. Maybe make the normal flamer 3 tiles as well? It's underwhelming compared to extended and spray.

**Comment by Zar000** [comment]
> Looks fine, as a flamer main. Maybe make the normal flamer 3 tiles as well? It's underwhelming compared to extended and spray.

Done

**Comment by Zar000** [comment]
Buffed up spray nozzle a little bit
image

**Comment by revelation-8468** [comment]
PC? nerfed
flamers? nerfed

wowzer i cant wait to hit resin walls with a bayonet gun for 10 hours instead of playing the game!

**Comment by Otterwatch** [comment]
Are you nerfing miniflamers (ubf) as well? This pr is fine I guess for the spray nozzle considering that it's pretty effective at clearing mazes even if not much else, but the normal nozzle is just a worse version of the current underbarrel flamer. It would be neater to give it some other function or just apply this change to a weapon that isn't purely dedicated to a single function with barely any other upsides. Fire barely effects xenos and there are a couple of counters for it. Flamers also aren't completely dominating the battlefield so I'm not sure I see the reason for this nerf. Mazes are extremely easy to rebuild and you can see this anytime an ob hits one. There is the start of a maze being revived immediately and can be done in about 2 minutes depending on the amount of builder castes. Now, this pr won't even change the effect on mazes because every popular pattern up to this point is 3 or less tiles of wall except for making a straight line in a long corridor. Changing normal nozzles does nothing but makes it slightly more time consuming to destroy a long line of walls that xenos occasionally do to make hallways 1-2 tiles and make wall spamming at disks and other important areas even more effective of a strategy due to the amount of time it will take to burn a 10 width wall or so. All in all, it would be nice to see why this change is necessary.

**Comment by Zar000** [comment]
> Are you nerfing miniflamers (ubf) as well? This pr is fine I guess for the spray nozzle considering that it's pretty effective at clearing mazes even if not much else, but the normal nozzle is just a worse version of the current underbarrel flamer. It would be neater to give it some other function or just apply this change to a weapon that isn't purely dedicated to a single function with barely any other upsides. Fire barely effects xenos and there are a couple of counters for it. Flamers also aren't completely dominating the battlefield so I'm not sure I see the reason for this nerf. Mazes are extremely easy to rebuild and you can see this anytime an ob hits one. The maze will start to be revived immediately and can be done in about 2 minutes depending on the amount of builder castes. Now, this pr won't even change the effect on mazes because every popular pattern up to this point is 3 or less tiles of wall except for making a straight line in a long corridor. Changing normal nozzles does nothing but makes it slightly more time consuming to destroy a long line of walls that xenos occasionally do to make hallways 1-2 tiles and make wall spamming at disks and other important areas even more effective of a strategy due to the amount of time it will take to burn a 10 width wall or so. All in all, it would be nice to see why this change is necessary.

This change is necessary for these reasons IMO:
1. Roundstart massive area denial, even if my nerf has reduced it, this image should prove that it will be far from useless.
2. It seems to not require more than one spray to actually destroy resin walls, I don't know where this belief stems from as the image below should show ( I sprayed once )
image
3. Mazing is easy if you have builder castes, yes. But it's a very painful process ( currently ) and with OB / Wide Flamer / Minigun, I don't think marines are lacking in the destroy maze department, this will also be most apparent underground, where only wide flamer will be a useful maze clearing tool.
4. Due to how I've coded this, it can very easily be adjusted / balanced out. Standard flamer can be made to pen 4, 5, 1, etc.

**Comment by Lumipharon** [comment]
> > Are you nerfing miniflamers (ubf) as well? This pr is fine I guess for the spray nozzle considering that it's pretty effective at clearing mazes even if not much else, but the normal nozzle is just a worse version of the current underbarrel flamer. It would be neater to give it some other function or just apply this change to a weapon that isn't purely dedicated to a single function with barely any other upsides. Fire barely effects xenos and there are a couple of counters for it. Flamers also aren't completely dominating the battlefield so I'm not sure I see the reason for this nerf. Mazes are extremely easy to rebuild and you can see this anytime an ob hits one. The maze will start to be revived immediately and can be done in about 2 minutes depending on the amount of builder castes. Now, this pr won't even change the effect on mazes because every popular pattern up to this point is 3 or less tiles of wall except for making a straight line in a long corridor. Changing normal nozzles does nothing but makes it slightly more time consuming to destroy a long line of walls that xenos occasionally do to make hallways 1-2 tiles and make wall spamming at disks and other important areas even more effective of a strategy due to the amount of time it will take to burn a 10 width wall or so. All in all, it would be nice to see why this change is necessary.
> 
> This change is necessary for these reasons IMO:
> 
>     1. Roundstart massive area denial, even if my nerf has reduced it, this image should prove that it will be far from useless.
> 
>     2. It seems to not require more than one spray to actually destroy resin walls, I don't know where this belief stems from as the image below should show ( I sprayed once )
>        image
> 
>     3. Mazing is easy if you have builder castes, yes. But it's a very painful process ( currently ) and with OB / Wide Flamer / Minigun, I don't think marines are lacking in the destroy maze department, the one situation where marines will be impacted is underground, where only wide flamer will be a useful maze clearing tool.
> 
>     4. Due to how I've coded this, it can very easily be adjusted / balanced out. Standard flamer can be made to pen 4, 5, 1, etc.

You're using walls that aren't at full health. Walls take time before they reach full health to limit combat building.

**Comment by Zar000** [comment]
> > 2. It seems to not require more than one spray to actually destroy resin walls, I don't know where this belief stems from as
> 
> You're using walls that aren't at full health. Walls take time before they reach full health to limit combat building.

So it's rather strong when it comes to preventing a rebuild of OB'd locations as it doesn't take two bursts to break freshly palced resin walls.

**Comment by Strayed-Raven** [comment]
The whole point of OB is to get in there and take a xeno fort maze. I feel the tug of war between gaining and losing ground is getting muddled with all these tweaks, but the only way to see how things go is to test merge to test opinions on why it does or does not work as intended. Otherwise engi's are gonna have to really step up their game.

**Comment by usnpeepoo** [comment]
> > > 3\. It seems to not require more than one spray to actually destroy resin walls, I don't know where this belief stems from as
> > 
> > 
> > You're using walls that aren't at full health. Walls take time before they reach full health to limit combat building.
> 
> So it's rather strong when it comes to preventing a rebuild of OB'd locations as it doesn't take two bursts to break freshly placed resin walls.

You shouldn’t be able to instsntly cuck rebuilded walls after an OB, this PR is a great balance for flamers shitting on mazes currently.

**Comment by Lumipharon** [comment]
> > > 2. It seems to not require more than one spray to actually destroy resin walls, I don't know where this belief stems from as
> > 
> > 
> > You're using walls that aren't at full health. Walls take time before they reach full health to limit combat building.
> 
> So it's rather strong when it comes to preventing a rebuild of OB'd locations as it doesn't take two bursts to break freshly placed resin walls.

That is why walls don't start at full health, yes.

**Comment by MereWalker** [comment]
At this point I may as well forget about being a flamer main ever again. No point to flamer it seems. Just go ahead and take it out of the list of things to get since flamers are working. *angry prop noises*

**Comment by Zar000** [comment]
> At this point I may as well forget about being a flamer main ever again. No point to flamer it seems. Just go ahead and take it out of the list of things to get since flamers are working. *angry pyro noises*

The change can be easily adjusted

**Comment by thenoob699** [comment]
Can't wait to be the only guy hitting resin walls with my bayonet again.

**Comment by Zar000** [comment]
> Given you nerf the effectiveness, did you lower the ammo usage too? Or is that already taken into account by the code? 

Will check

**Review by Pariah919 — COMMENTED** [review]
Flamers are strong team weapons and I'm against nerfing them considering they're the only real way to break through mazes with any speediness, and they aren't exactly the best at direct combat.

This is best tested, but I'm not sure if its a great change without a test.

**Comment by Zar000** [comment]
> Given you nerf the effectiveness, did you lower the ammo usage too? Or is that already taken into account by the code?

It was already taken into account by code. It only removes ammo once it actually ignites a tile

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 97bb57b1283bcd96910a866f9b257d4422f807e6
Pull Request: 1a6e685230d8b1221f8f8f29fe88e282cdba0bd8
Server: 55af5738f09e4f32af093c8b6b6aba41f6390460
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: c1d51908261666015798601def9aec4333609250
Pull Request: 1a6e685230d8b1221f8f8f29fe88e282cdba0bd8
Server: 568d2aff76b2c7ed883b6e6dfeedd8de00c4c4b1

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by Al-1ce** [comment]
I've had enough time with this to change my mind. The nerfs to flamer here are pretty rough and there isn't much to compensate for the losses. I think removing the damage given to flamers by the Surt module would make things fair.

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 4836928d30d2a5e28694d9c1ab705e56bfe4a3f0
Pull Request: 1a6e685230d8b1221f8f8f29fe88e282cdba0bd8
Server: 1d2c6c0233f162c9f43a26214749e40edf56ebe6

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 2968255260c476ffe21a73032b3618818c8c9a3a
Pull Request: 1a6e685230d8b1221f8f8f29fe88e282cdba0bd8
Server: 6c70c2d724f76aebfcc1e0d62b88b004f74c4359

##### Comment

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 6aea506e5d51321aff9be738b1801a71deaa7673
Pull Request: 1a6e685230d8b1221f8f8f29fe88e282cdba0bd8
Server: ce3040c5092889586ff1b0d7b9932cee5804dc07

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Comment by Sirsnek15** [comment]
I found a weird bug, or maybe it was always this way, but I could have sworn that marines were able to control how far the spread nozzle goes, like they can with the standard nozzle. I no longer have the ability to do this with spray nozzle but can still do this with the standard. 

I remember aiming for different distances with the spray nozzle changed the shape of the spray rather than just adding tiles. As someone who doesn't know anything about code, my guess is that some error has occured here with the spray shapes vs the sprays being cut off at 3 tiles long into a resin wall.

**Pull request merged**
