### PR TITLE
Simplify Orbits

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
there are now only 3 orbits: high orbit, standard, and low orbit also lowers the time it takes to change orbit and the time it takes to change orbit when the round starts

## Why It's Good For The Game
the marine orbit retreat win is gone. now takes way less time for you to change orbit to max or lowest orbit

## Changelog
:cl:
balance: orbit system simplified to only have 3 orbits
balance: time it takes for orbit to change to 3 minutes
balance: time it takes to change orbit at roundstart from 30 minutes to 10 minutes

/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
how will this affect req and cas point generation?
I believe the higher you are the faster they generate and vice versa
do they get the highest possible point gen (orbit 5) when the ship is on max orbit and lowest point gen (orbit 1) on the low orbit mode?

very col pr

**Comment by tyeagg** [comment]
> how will this affect req and cas point generation? I believe the higher you are the faster they generate and vice versa do they get the highest possible point gen (orbit 5) when the ship is on max orbit and lowest point gen (orbit 1) on the low orbit mode?
> 
> very col pr

yes

**Comment by Naaanii** [comment]
> how will this affect req and cas point generation? I believe the higher you are the faster they generate and vice versa do they get the highest possible point gen (orbit 5) when the ship is on max orbit and lowest point gen (orbit 1) on the low orbit mode?
> 
> very col pr

It's the same except no middle orbits now.

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
Felse

**Comment by Derrick2Electricboogaloo** [comment]
Marine orbit win was always GONE. I want it back.

**Comment by Derrick2Electricboogaloo** [comment]
Err.. Retreat.

**Pull request merged**
