### PR TITLE
New PAS sprite, removing old sprites

### PR DESCRIPTION
**Pull request by Kuro-ai**
## About The Pull Request

Replaces the current PAS sprite and removes some old sprites I don't want used anymore

## Why It's Good For The Game

New sprites good, old sprites bad

## Changelog
:cl:
add:new PAS sprites
del:some old unused armor sprites
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
The sprite
![image](https://user-images.githubusercontent.com/52428261/108549826-78c4f280-72cc-11eb-9f77-0f531af73586.pn

**Comment by Kuro-ai** [comment]
image

**Review by TiviPlus — APPROVED** [review]
bimmer

**Review by SplinterGP — APPROVED** [review]

**Comment by Kuro-ai** [comment]
waiting for bimmer to revive from his grave to merge this

**Pull request merged**
