### PR TITLE
Expansion of PoS: Req change 2.0, Bigger Bar, 2x1 maint doors, medbay remap, maint hall in bow, and Condor's hazard signs

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

PoS has additional changes. Mapper self wants to continue to improve map.

PoS is symmetrical in profile.
PoS

PoS's req has been flip. This is so that belt is closer to Alamo if anyone running req wants to deliver it to Alamo.

image

PoS' bar increases. Also, boxing ring is near bar in case if anyone wants to fight the old fashion way.

Radically change medbay to integrate bar better. Also, two cryotubes.
image

PoS's Condor landing zone has hazard tiles to indicate where it lands.

image

PoS now has 2x1 maint doors.

PoS has maint in its bow.

image

PoS has more generators.

image

## Why It's Good For The Game

For req, it makes it easier to move stuff to Alamo.

For medbay, it is to make traffic easier and fix the issues with current medbay.

For bar and boxing, they exist for RP purposes.

For Condor landing zone, I have done it for Alamo, so why not for Condor?

For 2x1 maint doors, it's to not make marines and xenos choke on 1 tile.

For the bow maint hall, it's to deal with camping in tadpole landing zone. I know who you are.

For generators, more power is good.

Hydro increases for space.

## Changelog
:cl:
add: more generators in PoS
add: maint hall in PoS' bow
balance: PoS now has two cryotubes
balance: PoS now has more surgical trays
expansion: PoS's req has been flip. This is so that belt is closer to Alamo if anyone running req wants to deliver it to Alamo.
expansion: PoS' bar increases. Also, boxing ring is near bar in case if anyone wants to fight the old fashion way.
expansion: PoS' medbay has been remapped for the greater good
add: PoS's Condor landing zone has hazard tiles to indicate where it lands.
/:cl:

### CODE REVIEW

**Comment by Alexeivichi** [comment]
I was promised more alcohol with this change so I support this for a speedmerge.

**Comment by RipGrayson** [comment]
Apparently the last revision of PoS broke power in medbay, please fix it.
unknown

**Comment by RipGrayson** [comment]
I don't know what's going on with this area, but it has two APCs.
spacetiles10

Tiny nitpick, please replace the tile here with a white one.
spacetiles11

Please put a node here so the maintenance AI node can connect.
spacetiles12

**Comment by Al-1ce** [comment]
Allow POS bar to be public access. Same with Theseus if you can.

**Comment by RipGrayson** [comment]
Double lights here
chem3

The air alarm here seems to be stuck in the wall
chem6

Please put an AI node here
chem2

Please connect AI nodes in maint to prep room here
chem4

Please connect the AI nodes here
chem5

This area doesn't have an APC
chem1

**Review by RipGrayson — APPROVED** [review]
This looks good, there's nothing more that needs done here.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
image
??????

**Pull request merged**
