### PR TITLE
marine satchel belt disentegrated

### PR DESCRIPTION
**Pull request by zerosexualpartners**
Marine satchel now doesn't enclosing the view on the armor, improving aesthetics of it.

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
the best pr of all time

**Comment by Tupinambis** [comment]
Did you intend to merge 500 commits with a total of 1200 file changes?

**Comment by Blundir** [comment]
Bruh

**Comment by Blundir** [comment]
Why did he push the entire RU tgmc repository here

**Comment by Alexeivichi** [comment]
Jesus christ this is amazing to see.

**Comment by ThelastArchiver** [comment]
based speed merge

**Comment by ClosetedSkeletonGH** [comment]
youre failing a check

image

please fix this

**Comment by Aporhtonoma** [comment]
some well needed changes indeed

**Comment by Tailiik** [comment]
Where screamshots

**Comment by ilikesaying** [comment]
RUTGMC moment

**Comment by zerosexualpartners** [comment]
Hell how to delete that I did pr on the rutgmc only and somehow it materialized here

**Comment by chizzy376** [comment]
Nah this looks fine, a test merge should be in order

**Pull request closed without merging**
