### PR TITLE
Adds Crossbow

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Adds a Crossbow with 4 ammo variants

Regular Arrows (high damage, vanilla)
Sticky arrows (sticky nades but hopefully better)
Flare arrows (illuminate Xenos with a funny light exhibiting arrow)
Ice <s>don't know a better name</s> arrows (Minimum damage, maximum slowdown)

Also adds new belt for storing arrows.
Sprites courtesy of [https://github.com/aGhostCoder](url)

image

## Why It's Good For The Game
New gun cool

## Changelog

:cl:
add: Adds crossbow, arrows and pouches.
/:cl:

### CODE REVIEW

**Comment by docRoboRobert** [comment]
the sprites look goofy but this is a good pr as an idea

**Comment by Mrrpip** [comment]
We've got the glock, we've got the MP5, now we have the crossbow. Crowbar buff when?

**Comment by carlarctg** [comment]
wtf is this the crossbow looks like a mix of a g11 and a wa2000 !!!! also use overlays for the colors don't fill the dmi with identical stuff smh!!!!!

**Comment by ilikesaying** [comment]
Does anyone remember the other moff, sibg

**Comment by Al-1ce** [comment]
You could rebrand the ice-arrows to "chase" or "tracking" since that'd be the main purpose of using them.

**Comment by Oscari-pog** [comment]
I am sorry but surely we can manage a better sprite

**Comment by Naaanii** [comment]
Sprites are WIP but I'll see what I can do.

image

**Comment by Mannybrado** [comment]
we love powercreep

**Review by Kuro020 — CHANGES_REQUESTED** [review]
better sprites pls

**Comment by Joe13413** [comment]
if this doesnt shoot the explosive bolts from call of duty, im gonna be very disappointed

**Comment by Beepinex** [comment]
i'm bad at reading code but is that a heavy explosion on the sticky arrow??🤢

**Pull request closed without merging**
