### PR TITLE
Miners now produce dropship points

### PR DESCRIPTION
**Pull request by Al-1ce**
## About The Pull Request

Miners now produce dropship points. 15 points for phoron miners, 30 for platinum miners (1/10th of regular point generation, in parity with intel points)

## Why It's Good For The Game

CAS is expensive. Many of the rockets and systems can cost upwards of 300-600 fabpoints, which takes quite a while to generate. Having to wait 26 minutes for a single-use rocket that doesn’t do a whole lot isn’t very fun.

This allows a symbiosis of sorts, letting miners passively add to the pool of points for both the tadpole and the condor, without being oppressive or too powerful so that spamming is easy. (15 points for a shipment is not much when a single rack of ammo costs 250 or more)

Things will still be expensive but overall less CBT, also encourages engineers to setup miners more.

## Changelog

:cl:
add: Miners now generate dropship points.
balance: Dropship fabricators now earn 30 and 15 points from respective miners.
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
Powercreep.

**Comment by Al-1ce** [comment]
> Powercreep.

I wouldn't say so. These points will mean very little unless a dozen miners are operating, and at that point it's a skill issue on the xeno side of things.

I can lower the variables even further if need be. I'd like for this to be TM'd at the very least.

**Comment by Pariah919** [comment]
Honestly good change, CAS is painfully point inefficent for some reason.
Though it could be that the vendor point balance needs a balance pass honestly..

**Comment by ivanmixo** [comment]
> Powercreep.

Have you played cas and realised how shitty and slow the point gen actually is? You can't even spam out the most basic, cheapest ammo and keep that going all round without running out of points. Super bad for actual variety in cas play since everything is so damn expensive.

**Comment by Al-1ce** [comment]
> Honestly good change, CAS is painfully point inefficent for some reason. Though it could be that the vendor point balance needs a balance pass honestly..

The vendor has been buffed a dozen times; incrementally over the years. I've enough experience as PO to know that this isn't the way to fix things. Buffing the vendor isn't dynamic and is a very lazy way to alleviate oversights with the role.

Allowing the Condor to become reliant on miners for surplus points is a better alternative, because it encourages xeno counterplay and adds a direct counter to CAS - while not being overpowered so that the pilot will be able to drop dozens of rockets in a matter of minutes.

**Comment by Derrick2Electricboogaloo** [comment]
Finally. CAS needed this.

**Comment by Lumipharon** [comment]
This was denied like, a month ago.

You can spend req points on CAS, this is just double dipping and serves to make cas hugely spammable.

**Comment by ivanmixo** [comment]
The req voulcher is a huge ripoff. 400 req points isn't equal to 150 dropship points at all.

**Comment by ClosetedSkeletonGH** [comment]
Mfw two 150mm boxes cost a whole T2

**Comment by Al-1ce** [comment]
> You can spend req points on CAS, this is just double dipping and serves to make cas hugely spammable.


I.. explained in the PR why this _wasn't_ spammable and even offered to lower the variable if this felt like too much. Braindead.

**Comment by Al-1ce** [comment]
> You can spend req points on CAS, this is just double dipping and serves to make cas hugely spammable.

I.. explained in the PR why this wouldn't be spammable and even offered to lower the variable if this felt like too much. I can't tell if you're illiterate or just don't care. Probably the latter.

**Pull request closed without merging**
