### PR TITLE
Makes Big Red rock walls 3/4ths compliant, reorganizes and fixes some things. [MDB ignore]

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

The current walls for Big Red are flat and clash with everything else we have, this PR replaces them.
In the process I have moved the other modern mineral walls to a new typepath so they aren't scattered everywhere, and gave the our current rock walls their own icon file like the rest of the "smooth walls."
~~I also fixed a single crash site for LV which could cause the game to be unwinnable for marines~~

## Why It's Good For The Game

The current Big Red wall sprites are bad and outdated, I promised to replace them and I have.

## Changelog
:cl:
fix: The Canterbury can no longer land on the red disk generator in LV.
imageadd: Created new wall sprites for Big Red.
code: Changed typepaths for smooth mineral walls so they aren't scattered across the multiple areas.
/:cl:

### CODE REVIEW

**Comment by RipGrayson** [comment]
Here's a comparison of our current cave graphics set and the one I'm replacing it with.
dreamseeker_Ty3sNwyGgE
dreamseeker_XjpO47wgNc2

**Comment by Lumipharon** [comment]
The sharp edges look a bit funny for caves.

**Comment by novaepee** [comment]
image

**Comment by RipGrayson** [comment]
> The sharp edges look a bit funny for caves.

There's a bit of a tradeoff here, if you make the edges less sharp then it becomes very hard to tell where the faces are and the whole thing reads very badly. 

There's ways around this, I pulled some of them when making the earlier LV cave walls, but I couldn't keep the rocky red texture of the cave walls *and* keep the corners from looking sharp. Anyone with more artistic talent than me is welcome to succeed where I failed.

This is just a drop-in replacement for the current 1 dimensional walls until somebody does a better sprite.

**Comment by Al-1ce** [comment]
I.. just don't like this. I think plenty others can agree. Big Red is already a confusing map with a crapload of dead-ends. It doesn't need headache inducing parallax or high-depth walls.

**Comment by Al-1ce** [comment]
I.. just don't understand how you can look at this change and think of it as an improvement. I'm not trying to be rude or anything but this just doesn't fit in. It adds more depth and confusing parallax to an already fucky map with a shitload of dead ends.

I think a lot of others can agree. This doesn't look like an improvement.

**Comment by Al-1ce** [comment]
I.. just don't understand how you can look at this change and think of it as an improvement. I'm not trying to be rude or anything but this just doesn't fit in. It adds more depth and confusing parallax to an already fucky map with a shitload of dead ends.

I think a lot of others can agree. This looks more headache inducing than anything else.


>Canterbury change

A good thing. But you really should've included that in a seperate PR.

**Review by BraveMole — CHANGES_REQUESTED** [review]
I'm not kuro but the sprites need some work.

**Comment by RipGrayson** [comment]
Well there is a consensus the sprites are bad, I'm going to bend to public opinion here and close this. Maybe in the future either I or someone else can do better.

**Comment by RipGrayson** [comment]
Actually, I'm going to keep this open for 24 hours before closing for the sake of feedback.

**Comment by RipGrayson** [comment]
> an already fucky map with a shitload of dead ends.

 I would encourage you to expand on this, in as much detail as you can, preferably on Discord or pastebin where I can view it.

**Comment by Al-1ce** [comment]
> I would encourage you to expand on this, in as much detail as you can, preferably on Discord or pastebin where I can view it.

https://imgur.com/a/THcxsWk

Hope this helps.

**Review by Kuro020 — APPROVED** [review]
nobody on this server sprites turfs so cope with it.
I consider these new ones better than the old ones soooo

**Comment by RipGrayson** [comment]
In light of Kuro's approval and the second revision (which looks a lot better than the first imo) I've decided not to close this PR.

**Comment by Al-1ce** [comment]
> I consider these new ones better than the old ones soooo

I think you have shit taste.

**Comment by RipGrayson** [comment]
This is the final revision, I have no plans to adjust it anymore unless Kuro or other maintainers want changes applied.
dreamseeker_7mQbjn6Z0D
dreamseeker_BQ6nMsHhfr
dreamseeker_JcWxyVldJP
dreamseeker_9rLiHrB2kz

**Comment by Kuro020** [comment]
> > I consider these new ones better than the old ones soooo
> 
> I think you have shit taste.

sadly for you I'm art director so my shit taste is what goes

**Comment by Al-1ce** [comment]
>I'm art director so my shit taste is what goes

I ker. Neekothing has better wall sprites.

**Pull request merged**
