### PR TITLE
Update pain hud

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

add ratio to pain hud. Stamina and pain count less, so the perception of human health by xeno will be more accurate

## Why It's Good For The Game

The current pain hud is outdated, pain and stamina are no longer that important

## Changelog
:cl:
balance: Update pain hud (what xeno see on humans) to be more reliable. Pain and stamina have way less impact on it.
/:cl:

### CODE REVIEW

**Comment by DerrickChamberlain** [comment]
So how is this different then the other PR you just closed? What does it show then? What is more reliable? I think we are just word playing here.

**Comment by BraveMole** [comment]
> So how is this different then the other PR you just closed? What does it show then? What is more reliable? I think we are just word playing here.

again, unless you played xeno, why do you even care?

**Comment by korokorokke** [comment]
Personally, the fact that the HUD reflected pain rather than actual health was news to me at all, and explains a lot of my confusion.

The fact that much of a marine's pain state lies in a vague, blinking red meter is incredibly confusing. It could definitely stand to be made more granular for the sake of readability - whether as a corpsman or a xeno - though as previously mentioned, I am uncertain whether or not that is really the intention here.

**Comment by EgorDinamit** [comment]
So that's why marines "in crit" were nowhere near actual crit, huh.

**Review by SplinterGP — APPROVED** [review]

**Comment by SplinterGP** [comment]
give more info in PR desc please

**Pull request merged**
