### PR TITLE
Synthetics can now get their blood back via nanopaste

### LINKED ISSUE #4338: Blood/Nutrition Loss as Synth
## Testmerges:
#4308: 'Makes the M56D smartgun into a whole deployable item' by MacBlaze1 at commit 36124fb928
#4309: 'Add gesture based callouts for humans' by psykzz at commit 2f3ea272a7
#4277: 'Adds self serve requisitions to the Theseus ship' by XElectricX at commit 2b07602c14
#4305: 'Experimental mob processing smoothing' by spookydonut at commit 07b900d728
#4301: 'Adds pill packets, and tricordazine pill packets to the first aid kit pouch.' by Pariah919 at commit 26df452f15
#4270: 'Adds directional slashing and removes bump slashing from xenomorphs' by MacBlaze1 at commit 71fe4460b8
#4328: 'Fixes instant take over of deleted xenos' by psykzz at commit 9e3b8448e6
#4327: 'Nerf T1 Xenos on crash' by psykzz at commit befa855825
#4269: 'More balance changes to cargo orders, better stuff available to order' by XElectricX at commit 70db303350

## Reproduction:

Synthetics don't seem to have a way to restore their blood normally, and their blood loss leads to hunger, like a normal human.

Scanners don't show their blood type, making it a guessing game when trying to transfuse unless you check their Variables.

Also, synths can have their organs damaged. Not sure if that's intentional as well.

### PR DESCRIPTION
**Pull request by Hughgent**
## About The Pull Request

Fixes #4338 

Organ damage and bloodloss are still things that happen to synthetics

## Why It's Good For The Game

Synthetics, when they take a lot of bleeding or damage, can now get their blood back whenever they are touched by nanopaste in the course of repairing their limbs.

## Changelog
:cl: Hughgent
fix: Synthetics can get their blood back with nanopaste
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Move this to where limb healing happens instead

**Comment by Hughgent** [comment]
But the synth could have their limbs healed via other means.

**Comment by TiviPlus** [comment]
If its being repaired then it should regen blood but otherwise itdd just be wierd

**Comment by Hughgent** [comment]
On the contrary. it's just stabbing the synth in the neck.

My point being that if they are at full health because they got 'regular' repairs, then there would not be a way of replenishing their blood unless you hurt them again. and THAT would be weird.

however, do you think it should use up a charge of the nanopaste to do this or should it just be an ancillary benefit.

**Comment by TiviPlus** [comment]
You can just add it before the damage check though

**Pull request merged**
