### PR TITLE
Deletes the longtad

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title

## Why It's Good For The Game

Park this tad in the right spot and mount 3 hsgs and you can hold an area forever. Not even gas can help out with this even if they don't wear mirmir, because they can just spam into the smoke to instakill any xeno that tries to get close, nevermind the fact even if it doesn't kill you it'll heavily chunk your sunder. 

This tad's mounted weapons are better than regular tad due to the complete lack of walls which gives you a full 360 around the tad and epic free plasteel cades that just let you trap charging crushers for free.

Not maintainable, not worth keeping around as admin only, therefore death.

## Changelog
:cl:
del: Removed longtad
/:cl:

### CODE REVIEW

**Comment by SimplySmiley123** [comment]
Bruh it's useless when anything with gas exist or whenever ungas want to use tad as a tad and not a mobile cade.

**Comment by Tonklaatech** [comment]
The long tad is specifically made to be wielded as a mobile cadeline. It sacrifices the versatility of the original tadpole that is able to land in any spot. In return it receives multiple hull point as a means of increasing its viability.

**Comment by ivanmixo** [comment]
If it was made with that in mind then it's a flawed concept. More than one mounting point is a balance issue and this tad demonstrates it.

**Comment by SimplySmiley123** [comment]
> If it was made with that in mind then it's a flawed concept. More than one mounting point is a balance issue and this tad demonstrates it.

Then give it something else instead, come on, do it now, show what you would do to make it actuall viable without those 3 hardpoints.

**Comment by Barnet2** [comment]
Longtad is extremely toxic because it can fit in 3 tile hallways, alongside being able to use 2 of the _free_ roundstart HSG's that also have additional ammo capacity. It is less effected by gas because it is well, long.

**Comment by SimplySmiley123** [comment]
> Longtad is extremely toxic because it can fit in 3 tile hallways, alongside being able to use 2 of the _free_ roundstart HSG's that also have additional ammo capacity. It is less effected by gas because it is well, long.

I'm going to say something I never thought I would say, but.

Have you ever fucking played on the long tad? 
9 out of 10 times that tad gets bombarded by gas be it from defilers blindly charging past, guaranteed banelings suicide bombing you every time they respawn, boilers existing, and then there's all sorts of spitters constantly whittling down your one singular later of plasteel cades.
The only factors saving the long tad from complete obscurity are that it is 3 tiles wide and can fit in more places thanks to that, and tha it has 3 mounting spots as a trade off for how unsafe it is to be inside of, how little the number of marines that can safely fit inside is if you also use all those 3 mounting spots (if you're sitting right on the cade you are a prime target for any warriors wanting tto fish out some marines for dinner).

**Comment by chizzy376** [comment]
It's the only reason the longtad exists, might as well outright remove it.
Source: I know a thing or two about tads.

**Comment by Loafin34** [comment]
Why the fuck are you removing longtad's mounting points? the whole purpose of it is to **be a firing line.** You don't get to have sentries or gas protection or healbus, you are all combat, all the time.

**Comment by JoeHammad1844** [comment]
because flanking doesnt exist

**Comment by Yttriums** [comment]
why would you not go to 2 mounting points? just remove it if you're going to gut it

**Comment by timothymtorres** [comment]
Looks pretty balanced to me:

dreamseeker_iQ370pgxXT

**Pull request merged**
