### PR TITLE
boiler gets acid spit i guess

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
why did it never have this
spits have a max range anyway so you can't snipe

## Why It's Good For The Game
boiler has learnt to spit acid again

## Changelog
:cl:
balance: boiler spits acid
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -228. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by BeloneX** [comment]
>why did it never have this

Probably to discourage frontline Boilers.

**Comment by TGCMbetcher** [comment]
Fair enough, now boilers will try to fight me as I slug them 7 times instead of just running. Xenos dont relize in an acid vs bullet war the only part they win at is heal rate. Unless theyre the queen and do 60 damage per spit.

**Review by SplinterGP — APPROVED** [review]

**Comment by TiviPlus** [comment]
I will trust splinter

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-289). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
