### PR TITLE
Removes an egregious object fling trap in Slumbridge

### PR DESCRIPTION
**Pull request by chizzy376**
## About The Pull Request
Yeah no, this is not a good thing and needs to be quickly removed
Replaced it with this:
slumbridge

## Why It's Good For The Game
* Less unfair deaths
* This shouldn't happen anymore

https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/e28af98d-8b04-4aeb-8391-e4daa281bb38

## Changelog
:cl:
fix: fixes a object fling trap in Slumbridge engineering
/:cl:

### CODE REVIEW

**Comment by chizzy376** [comment]
wat

**Comment by Helg2** [comment]
Or just make it jumpable.

**Comment by blackdav123** [comment]
riptide has this same prop issue, jumpable is probably the way.

**Comment by chizzy376** [comment]
>  jumpable is probably the way.

I have no idea how to do that

**Comment by Helg2** [comment]
Iirc it is made through pass_flags and one them is used for low structures. Also you could look up how its made in the pr that made bike jumpable.

**Comment by XElectricX** [comment]
This is a code issue not a mapping one. They should be dense on all tiles, like tanks or multi tile doors.

**Comment by chizzy376** [comment]
> This is a code issue not a mapping one. They should be dense on all tiles, like tanks or multi tile doors.

it's my map but go off

**Comment by XElectricX** [comment]
> it's my map but go off

It's going to happen wherever those props are used, but ok. You're just working around the issue.

**Pull request merged**
