### PR TITLE
Inspection on the little smoke runtime.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
A debate with Rohesie brought up it would be better to search up the cause of nullspace smokes rather than silencing them. The processing runtime can only date back to the subsystem ignite(), testmerging this should possibly ease the hunt.

## Why It's Good For The Game
Bug hunting season.

### CODE REVIEW

**Comment by DominikPanic** [comment]
This has produced zero output (just searched all the logs)

**Comment by Rohesie** [comment]
We haven't been testing much since then, truth be told, but yea. So far the elusive runtime hasn't happened.

**Comment by Ghommie** [comment]
Well, a shame, I guess we'll catch it up someday, but not now. It's indeed a very rare runtime apparently.
Go ahead and tell me if you want me to close it.

**Comment by Rohesie** [comment]
Guess both PRs can be closed. If it sneakily happens again we can re-open this one.

**Pull request closed without merging**
