### PR TITLE
Marine speed, armor and medical rebalance

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
**Test Merge**
Decreases marine armor by 15 melee and 10 acid across the board
Increases shoe movement speed from -1.0 to -2.0 (NEED TESTS ON THIS, MOVESPEED IS CONFIG AAAA)
Splint HP increased majorly (might need a clamp for higher ones?), delay decreased for those unskilled in medical
Removes RNG organ damage on slash
## Why It's Good For The Game
**THIS IS A TEST**
Kuro wanted to see what would happen if we made less tanky but faster marines. This has a good chance of completely blowing up.
## Changelog
:cl:
balance: Decreases marine armor by 15 melee and 10 acid across the board
balance: Increases shoe movement speed from -1.0 to -2.0
balance: Splint HP increased majorly, delay decreased for those unskilled in medical
balance: Removes RNG organ damage on slash
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]
this is a TEST maintainers, dont ping me 5000 times about it

**Comment by Naaanii** [comment]
Infinite stamina would be based.

**Comment by Lumipharon** [comment]
> this is a TEST maintainers, dont ping me 5000 times about it

@Kuro020 
@Kuro020 
@Kuro020 
@Kuro020 
@Kuro020

**Comment by Barnet2** [comment]
Rest in pieces, you were open for an hour before death.

**Comment by Looking4bros** [comment]
woulda made heart and lung damage even more important, as they combined i think they do +1 to +4 slowdown. depending on how damaged they are.

**Pull request closed without merging**
