### PR TITLE
Buffs the marine shield

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
10 more force
45 melee from 40, 50 bullet from 5, 35 acid from 0

## Why It's Good For The Game
Shields suck for using your entire hand slot and are removed when you're stunned, they need something to make them better.

## Changelog
:cl:
balance: Marine shields now protect you far more, and deal a bit more melee damage.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -49. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Review by TiviPlus — APPROVED** [review]
Why dont we just give them toggleable nodrop

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-51). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Denthamos** [comment]
Playing around with the shield for a bit leads me to believe somewhat that its not so much an issue with the shield (though the acid  defense buff does help with this), but the fact that of all the weapons available none really pairs well with it for the one hand requirement, and the two hand reload requirement further expands on this issue.  

You could say the revolver works well with it but the awkward reloading mechanic for it makes it unadvisable to use with the shield, you can no longer one hand a shotgun to use with it, and the machine pistol is almost like shooting BB's out.  The only two weapons I see pairing well with it is the mateba which you need to buy from req or be a leadership role to have and melee options like a machete/FC sword which puts you at even more risk than normal.

**Comment by Dolth** [comment]
Wielding a heavy armor, an ancient warrior slashes you for 19 brute, 3 brute if you have your shield. I think that's already enormously powerful.
Although, I'll side with what Tivi said. If the shield can't be dropped, it actually has a use, don't forget that is has durability and will still get obliterated regardless after a couple of slashes.

**Pull request merged**
