### PR TITLE
infinite reqtorio machines in op vendor

### PR DESCRIPTION
**Pull request by FosterGrime-Heymynameslouie**
## About The Pull Request

Adds infinite supply of reqtorio machines into op vendor
smoothens out and expands the reqtorio experience as you dont have to buy the parts anymore

## Why It's Good For The Game

streamlines reqtorio process

## Changelog
:cl:

balance: infinite reqtorio machines on op vendor

/:cl:

### CODE REVIEW

**Comment by Beepinex** [comment]
"so you dont have to buy the parts anymore"
creepin'

**Comment by XElectricX** [comment]
People that don't like this PR should be forced to make a factory first. It's time consuming and costly.

**Comment by Naaanii** [comment]
Even the free machines weren't meant to be free in the first place. This creeps it even further.

**Comment by Aporhtonoma** [comment]
brother thats unbalanced as fuck

**Review by TiviPlus — CHANGES_REQUESTED** [review]
This demonstrates an extreme lack of understanding of how reqtorio is intended to be (high fixed costs low variable costs) is there any reasonign beyond powercreep for this change

**Comment by XElectricX** [comment]
> This demonstrates an extreme lack of understanding of how reqtorio is intended to be (high fixed costs low variable costs) is there any reasonign beyond powercreep for this change

Reqtorio is a bad system then.

**Comment by novaepee** [comment]
> > This demonstrates an extreme lack of understanding of how reqtorio is intended to be (high fixed costs low variable costs) is there any reasonign beyond powercreep for this change
> 
> Reqtorio is a bad system then.

False. Tivi intended for this design, though the compromise between req players, MJP, and Tivi was giving only one free set so that ROs have a taste of reqtorio to allow them to get more since previously reqtorio was barely seen. I'm surprised this PR hasn't been closed yet.

**Comment by chizzy376** [comment]
The reason you even begin with machines in the first place is to allow you to build the low tier reqtorio recipes, and if you like the system you shill out for the advanced machines. If it was up to me I'd do the opposite AND INCREASE the cost, as right now you can make a factory at 150 cost, buy a 600 cost item and print items that cost 1500, saving you 900 per batch. (Modules).

**Comment by FosterGrime-Heymynameslouie** [comment]
> This demonstrates an extreme lack of understanding of how reqtorio is intended to be (high fixed costs low variable costs) is there any reasonign beyond powercreep for this change

this was mainly intended to be a way to smoothen out the req experience
I understand now that making all machinery might be a bit too much yeah 
what about making all basic machinery free instead? maybe double the price of the rest of the machinery while at it

mostly made this pr because of frustration in buyin extra req machinery and electric asking me to do so

**Comment by Naaanii** [comment]
> > This demonstrates an extreme lack of understanding of how reqtorio is intended to be (high fixed costs low variable costs) is there any reasonign beyond powercreep for this change
> 
> this was mainly intended to be a way to smoothen out the req experience I understand now that making all machinery might be a bit too much yeah what about making all basic machinery free instead? maybe double the price of the rest of the machinery while at it
> 
> mostly made this pr because of frustration in buyin extra req machinery and electric asking me to do so

But the whole point is buying the machinery.
You'd have a better chance of removing the free machinery <s>which isn't supposed to be free in the first place</s>

**Comment by TiviPlus** [comment]
Okay I see you understabnd why this pr is not a good idea then

**Pull request closed without merging**
