### PR TITLE
Nerf MG-27, HMG, and HSG's scope to slightly less than mini scope

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

image

Supreme Leader Kurt's Will,

"We're removing offscreen gameplay since its uninteractive and heavily stacked for marines, mounted weapons are also culprits of off screening tho less so than the other stuff that is getting a nerf, since boiler is having his range reduced I don't think mounted weapons need mini scope range anymore"

## Changelog

:cl:
balance: Nerf MG-27, HMG, and HSG's scope to slightly less than mini scope
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
Hey, that's not a good 'Why is it good for the game'. They still have to explain themselves.

**Comment by maikilangiolo** [comment]
> boiler is having his range reduced I don't think mounted weapons need mini scope range anymore

That's not why they have the scope. They have it because they're borderline unusable without it, being to slow to deploy/move and too vulnerable. Same for the TAT and AGLS. Due to the giant AOE, they cannot function without a scope so you don't have to shoot inside the marine ball.

A 5 tile scope on slow mounted guns is hardly a balance concern

**Comment by Wisemonster** [comment]
If they are genuinely unusable without the scopes, then it sounds like they need to be reworked, rather than "Keep this bad mechanic cause otherwise the weapon is bad"

**Comment by SimplySmiley123** [comment]
> If they are genuinely unusable without the scopes, then it sounds like they need to be reworked, rather than "Keep this bad mechanic cause otherwise the weapon is bad"

Yeah so how about doing that as well.

**Comment by Lauwma** [comment]
Just give them miniscope tbh

**Comment by maikilangiolo** [comment]
> If they are genuinely unusable without the scopes, then it sounds like they need to be reworked

I indeed tried to do it a long while back, with a very in depth plan to improve them. But lumi shot down every idea I had

**Comment by FosterGrime-Heymynameslouie** [comment]
this sucks ass

mg60 literally not having the reddot and I think its only attachment is the tacsensor is already terrible completely butchering every other machine gunner scopes is beyond ass like cmon, the thing designed to lay supressive fire cant do its supressive fire gimmick any good no more

also terrible why its good for the game, having pseudo art meme stuff to bypass reasoning under a thinly veiled attempt in humor is not something youll see in every other pr

**Comment by Kuro020** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/16038

**Pull request closed without merging**
