### PR TITLE
Salvage dead xenos is gone

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Drone and hivelord cannot recycle bodies anymore

## Why It's Good For The Game

No longer really needed with the maturity buff. And it's pretty lame to prevent marines from selling them that easily, they deserve a reward from killing xenos. We could even prevent xenos from dragging dead xenos bodies, maybe?

## Changelog
:cl:
del: Salvage biomass xeno ability removed.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
good pr
don't reward people for dying

**Comment by Pinkufeck** [comment]
> don't reward people for dying

It gives nothing noticable though.

**Comment by davidchan13** [comment]
So whats the difference here between marines dragging off xeno corpses for req points instead of having only the option to fulton them in the field and xenos being able to drag off corpses and cocooning them where as now they can only cocoon them where the body drops?

**Comment by Glcbitj** [comment]
> > don't reward people for dying
> 
> It gives nothing noticable though.

Doesn't that mean removing it isn't noticeable too?

**Comment by EvilMelonTheSecond** [comment]
> 
> 
> > > don't reward people for dying
> > 
> > 
> > It gives nothing noticable though.
> 
> Doesn't that mean removing it isn't noticeable too?

Removing it won't be noticable for xenos. Marines on the other hand miss out on like 30 req points per body at minimum.

**Review by SplinterGP — CHANGES_REQUESTED** [review]
need keybinds removed

**Review by SplinterGP — APPROVED** [review]
nvm removing keybinds is uh wellelelelelele

**Comment by Al-1ce** [comment]
> Removing it won't be noticable for xenos. Marines on the other hand miss out on like 30 req points per body at minimum.

That's the entire point. It's noticeable for Xenos because it means fewer req points for marines, so it makes it easier on their part of they try to recover bodies.

**Pull request merged**
