### PR TITLE
Willpower (marines nerf of the year)

### PR DESCRIPTION
**Pull request by Dgeen**
## About The Pull Request

 The Marines have a new stat - willpower.
Each psydraining/cocoon will decrease this stat by 1. Upon reaching 0, the victim's mind will be completely destroyed and resurrection will be impossible.

By default:

- Civilians get 4; 
- Marines - 5; 
- Command (sl and above) - 6.

In addition, death now punishes Marines. 
Every second spent on the other side leads to the degradation of the body:

- For the first 75 ticks (~2.5 minutes, half of the time before DNR) the maximum stamina and critical health are reduced by 0.1 
- In the remaining time the degradation rate increases to 0.5

<details>
  <summary>Outdated</summary>
  
 The Marines have a new stat - willpower.
With each death (exception: if you died without leaving crit after resurrection), it will drop by 1, reaching zero, the marine loses the desire to fight and cannot be resurrected after. 
In addition, now every death irreversibly worsens the physical performance of a marine, namely:
- Reduces maximum stamina of a marine;
- Reduces crit threshold health. 

By default:

- Civilians get 4; 
- Marines - 5; 
- Command (sl and above) - 6.

Synthetics and zombies are not affected by this stat
  
  
</details>

## Why It's Good For The Game

**Marines Major**
**34 Marines participated in the landing.**
**Total Marines died - 135**
**Marines survived - 33**
**Congratulations!**

## Changelog
:cl:
add: New marine stats - willpower,
balance: Psydraining/cocoon now brings irreversible death closer
balance: The dead body is now degrading

/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
your morale is low

**Comment by Eskjjlj** [comment]
It's very silly indeed how marines can suicide charge knowing that they will be healed to full in 2 minutes.

With your changes the new funny strat would be to camp medics and kill marines just after they get defibbed...

**Comment by EvilMelonTheSecond** [comment]
Can we have shipside crayon breaks to restore willpower?

**Comment by srxtreme** [comment]
Don't forget about brain damage, though. It reduces all skills I think

**Comment by chizzy376** [comment]
Is the willpower loss permanent? This change is a massive xeno buff during sieges, I'd prefer to have willpower passively regen.

**Comment by Naaanii** [comment]
Headbite with extra steps. Very interesting.

**Comment by KerbalCitizen** [comment]
Boiler acid globs a marine right after they get defibbed. Low hp, no armor, can't move. Even if other marines try to drag the corpse away, it's hard to see a body when it's covered in acid smoke and revived marine will probably die. Before someone tells me to just revive where boiler can't glob, go play corpsman and try to do that. There will almost always be a path that a glob could travel to you. It doesn't take a massive amount of skill to just flank as a boiler and glob medics, or more importantly, the newly revived marines.

**Comment by Dawson1917** [comment]
Will definitely need something to make it not apply immediately after revival. Like not applying for 1-2 minutes after you get revived. 
Worth testmerging since right now marine deaths only matter if xenos sit and guard the body for 5 minutes.

**Comment by Losenis** [comment]
>Get FFd to death by an ivanov cosplayer
>LCPL Baldilocks revives in the middle of combat instead of dragging behind cades
>Permanent debuff

This'd be viable if bald marines didn't have the ability to wipe their own team harder than any xeno ever could. This only makes the retarded bunch of marines even worse to deal with given sometimes they actually cause the whole push to get wiped with how bad they can fuck up. It's going to turn into HvH the moment marines spot the usual suspects and try to kill them faster than they'll kill everyone else.

**Comment by zzurge** [comment]
Lol,Lmao even

**Comment by Guidesu** [comment]
And combat robots?
They... don't need willpower they are machines they literally have no emotions and literally fight until death

**Comment by Pariah919** [comment]
This requires you to rebalance how death works entirely.

**Comment by Dawson1917** [comment]
>>Get FFd to death by an ivanov cosplayer
>>LCPL Baldilocks revives in the middle of combat instead of dragging behind cades
>>Permanent debuff

>This'd be viable if bald marines didn't have the ability to wipe their own team harder than any xeno ever could. This only makes the retarded bunch of marines even worse to deal with given sometimes they actually cause the whole push to get wiped with how bad they can fuck up. It's going to turn into HvH the moment marines spot the usual suspects and try to kill them faster than they'll kill everyone else.

The friendly fire is meant to be the balancing factor of those weapons. It's not fun getting killed or potentially even round-removed (or also having your stats debuffed with this PR) because of friendly fire, but right now FF is so meaningless that shooting rockets/grenade/explosives/fire/etc at marines is heavily encouraged just for the *chance* to get the kill on a xeno, regardless of tier. Even *if* a marine dies to the FF, they can be revived immediately and often don't even have a broken bone or any form of lasting damage from it. 
This PR isn't the only way to make FF more meaningful/less effective at killing xenos, of course, but I don't see any others up.

**Comment by Losenis** [comment]
>This PR isn't the only way to make FF more meaningful/less effective at killing xenos, of course, but I don't see any others up.

Skill issues should punish the one who lacks them, not the guys around him for not immediately deliberatedly FFing him to death him as soon as they caught whiff of his baldness. We already have enough of it with nadetards going hlin and wiping half the marine push while they're fucking around at full health.

**Comment by chizzy376** [comment]
> And combat robots? They... don't need willpower they are machines they literally have no emotions and literally fight until death

V1 from ultrakill, make them regen health by gathering blood. Do it. Make it real

**Comment by Ragecrabbo** [comment]
give this to cocoon/psydrain instead of every death and we're golden

**Comment by Zar000** [comment]
double it and give it to the next person

**Comment by Lumipharon** [comment]
perfection

**Comment by SilencedMP5A5** [comment]
hahahahahahahaha

**Comment by TheUSSWatercooler** [comment]
IMO willpower shouldn't go down if you die within say... a minute or two of being revived.
Maybe add a way to bring willpower up, maybe spending time shipside, or as a reward for objectives. But that's just me throwing ideas out. 
On the side of just not doing this, marines don't actually get revived that much individually. It's rare that I have to revive someone specific twice or thrice in a round.

**Comment by KillerOrcaCora** [comment]
Idk what's with these comments about willpower not going down if you die, If you see your friend die your morale should go down, if you are told by the doctors that you died your willpower should go down, if you got your ass whooped in a maze and didnt kill a single xeno but left crit your will power should go down, if you are surrounded by the bleak nothingness of the dark void and a xeno decides to hiss near you, your will power should go down, If you breathe the toxic fumes of xeno gas walfare your willpower should go down, if King is in your sights your willpower should go down, if your not with your team your will power should go down, If you just so happen to SEE a T4 xeno your will power should go down, if you enter caves your will power should go down, You even landing on this planet should automatically make you lose willpower Just for the dramatic effect and nice appatizer for the clear preview of all the will power your about to lose because your nothing more then fodder and that fact alone should make your will power go down.

**Comment by Losenis** [comment]
>If you see your friend die your will power should go down, if you are told by the doctors that you died your willpower should go down

My brother in Ra if we're applying logic and reason to TGMC, we'd start by deploying during the day

**Comment by Strayed-Raven** [comment]
Now add Resolve. Getting stunned multiple times in a short time frame by xenos fills a Resolve Bar and the marine cannot be stunned again for 6-8 seconds.

**Comment by XElectricX** [comment]
This is just a worse cloneloss. Better to go back to the old system of being unable to revive a marine at 20 heart damage.

**Comment by Naaanii** [comment]
> Idk what's with these comments about willpower not going down if you die, If you see your friend die your will power should go down, if you are told by the doctors that you died your willpower should go down, if you got your ass whooped in a maze and didnt kill a single xeno but left crit your will power should go down, if you are surrounded by the bleak nothingness of the dark void and a xeno decides to hiss near you, your will power should go down, If you breathe the toxic fumes of xeno gas walfare your willpower should go down, if King is in your sights your willpower should go down, if your not with your team your will power should go down, If you just so happen to SEE a T4 xeno your will power should go down, if you enter caves your will power should go down, You even landing on this planet should automatically make you lose willpower Just for the dramatic effect and nice appatizer for the clear preview of all the will power your about to lose because your nothing more then fodder and that fact alone should make your will power go down.

With this logic, Xenos should lose the moment the first Queen dies as Xenos cannot function without one.
Reminder that King isn't a real Xeno.

Also most of our marines are protagonists that don't care about death making the argument even more redundant because of Mary Sues without the plot armour. Willpower or the lack thereof only exists in the minds of those brave enough to make a salt PR (like this one).

Realism arguments do not help adding unliked mechanics in a TDM.

**Comment by FIXTHERADBOXPLEASE** [comment]
As the representative of the TGMC Xenomain Cabal, this should honestly only apply to marines that get Psy-Drained or Cocooned. It's just too punishing if it fucks over Marines who got FFed or killed during revive. 

Psy-Drains can also be defended against for more Emergent Gameplay.
Plus, it'd give Xenos a better reward for landing Psy-Drains.

**Comment by Al-1ce** [comment]
Meth should remove the effects of morale. :^)

**Comment by chizzy376** [comment]
Don't forget if you die of tox groundside and your corpsman is bald you'll go dnr like 5 mins in. Puts dylovene in you, defibs, ignores 25u of defiler chems in your blood, you die of oxyloss shortly after. Defib removes oxyloss, you get revived, die of oxyloss 4 seconds after. Repeat until all your willpower is farmed.

**Comment by Oscari-pog** [comment]
Because Marines trained to fight xenomorphs, fully aware or the threat, would definitely not be mentally resilient or desentisized

**Comment by MiniMeatwad** [comment]
Base it on being psy drained, which is once per death, and lets corpsmen revive in peace. Also something something lore, psy drain is you losing your soul, which has to be morale draining.

**Comment by Kuro020** [comment]
As approved by spooky, I sentence this pr to the cringe realm of bad ideas.

**Pull request closed without merging**
