### PR TITLE
Revert "Synthetics can have hair again"

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
I got headmin permission to delete synth hair again
image

## Why It's Good For The Game
Synthetics should be distinct from humans and from a lore standpoint synthetic hair is very expensive, so a random military ship can't have synthetics with hair, I believe.
 think these changes would benefit the game. If you can't justify it in words, it might not be worth adding. -->

## Changelog
:cl:
del: Synths can no longer have hair again.
/:cl:

<!-- You can use multiple of the same prefix (they're only used for the icon ingame) and delete the unneeded ones. Despite some of the tags, changelogs shou

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Nanotransen finance departament at it again.. cutting NECESARRY funds from the marines.

**Comment by Losenis** [comment]
metagrudging bowl with necrotizing surgery

**Comment by Kuro020** [comment]
you're bald irl

**Comment by novaepee** [comment]
MJP going schizo again

**Pull request closed without merging**
