### PR TITLE
Adds side grates to alamo

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request
Adds grates to the sides of Alamo to ease transportation. I could try to add railings to it if there is concern about marines going to space or being able to be retrieved from space.

Capture

## Why It's Good For The Game
Using the side grates would be easier to load and unload the Alamo because you wouldn't be dealing with marines moving around or have to open the Alamo doors a lot.

## Changelog
:cl: Susbot
qol: add side grates to Alamo for loading stuff
/:cl:

### CODE REVIEW

**Comment by Pill-U** [comment]
can marines survive on those side grates?

**Comment by Walarks** [comment]
> can marines survive on those side grates? also do they crush stuff on landing and do the "landing bubbles" properly show up for them?

 Yes on all.

**Comment by AnCopper** [comment]
Uhh... what?

**Comment by bowlofcereal** [comment]
cant you just breathe in that fresh space air boys

**Comment by AnCopper** [comment]
If you want to add more space to the Alamo you should just widen it by one tile in each direction the lower half, and remove the middle walls, because this is an awful idea.

**Comment by novaepee** [comment]
> If you want to add more space to the Alamo you should just widen it by one tile in each direction at the lower half, and remove the middle walls, because this is an awful idea.

image

If widen the other half, then engine aesthetics is going to get screwed over. Middle wall exists for consistency of chairs being on walls and as Bravemole said in #dev-general, "[If you remove the middle wall,] it makes shit (his words, not mine) easier for xeno though".

**Comment by novaepee** [comment]
If you are suggesting this, then Bravemole and David Stormwell said no to this already: 
image

**Comment by SplinterGP** [comment]
you could add handrails outside to complement the visuals
image

**Comment by SplinterGP** [comment]
image
image
image
image

sprites for it

**Review by BraveMole — CHANGES_REQUESTED** [review]
the idea is cool, but you should not be able to move onto them. I'd rather have a system where you can attach crates on the sides. And the sprite gave by splinter looks better

**Comment by Walarks** [comment]
Was hoping I could do it without coding in a new feature. Maybe someone more dedicated can pick it up.

**Pull request closed without merging**
