### PR TITLE
Ovi removal and abilities rework

### LINKED ISSUE #2976: Queen Ovipositor bug
## Testmerges:
As a Queen, if currently in an Ovipositor, if you mature it will change your icons around and you are unable to remove the ovipositor. Round ID: 1077

## Reproduction:
Become a queen, grow an ovipositor, mature yourself, then watch as your icons disappear.

### PR DESCRIPTION
**Pull request by Rohesie**
Fixes #2976 

:cl:
del: Queen Ovi is no more.
balance: Queens can zoom out at any time, and can overwatch xenos as if they were in ovi mode, either by selecting the ability, selecting a xeno from the hive status list, or using ctrl + middle click. The ability stacks with the zoom, so they can provide more effective overwatch support and guidance. The leader pheromone bonus is kept even as the Queen moves.
/:cl:

### CODE REVIEW

**Comment by factoryman942** [comment]
@Rohesie "Fixes: #2976"

**Comment by spookydonut** [comment]
@Rohesie let me know when you're finished working on this

**Comment by spookydonut** [comment]
@Rohesie let me know

**Comment by Rohesie** [comment]
This is ready.

**Comment by Tupinambis** [comment]
I strongly disagree with this change. It removes a pretty significant part of what made queen unique and interesting to play as and against. It also changes how xenos fundamentally play. There is no longer a reason to make a massive nest complex for the marines to charge into, there is no longer that horror aspect of an egg laying queen, there is no longer logistics in transporting the eggs.

With this change, there is no point in creating anything more than small bits of cover and a nest or two for when you happen to get a capture. Playing drone or hivelord is significantly cheapened because there isn't really a point in building a cool hive. Tunnels are generally waste of time now, because if the xenos are constantly migrating across the map, they rarely will ever be near the static tunnels in order to use.

This removes all of the logistics and construction that made xeno quite a bit more interesting to play. Without a nest to attack and tear through, marines don't have much of an objective besides chase xenos around the map until they die. Xenos don't even have much of an objective now besides kill marines until they can get onto the alamo. 

Making a hive fun, having to make choices of where to nest and when to ovi as queen was fun. Storming and bombing a xeno nest was fun. This removes a lot of that, and just makes distress more of a cat and mouse game than it already is.

**Comment by Rohesie** [comment]
This does revert to the old behavior of having a more mobile hive.

Xenos are not really well balanced towards being static. But you can still build big hives, because you still need a place to hold hosts hostage, a place to retreat when under heavy fire, and chokepoints to halt marine advance.

Ovi queen didn't really add but a point of weakness and diminished the ability of the hive to relocate if overrun. Forcing a player to ovi in one place was often not the best playing experience.

**Comment by Tupinambis** [comment]
But ovi queen could easily de-ovi and bring the fight to the marines if things got hairy. If ovi took too long and had too long a cooldown, that can be fixed. If xenos aren't balanced to be in a static location, that can be fixed with better defenses. You CAN build a big hive, but there is very little incentive to do so.

**Pull request merged**
