### PR TITLE
Adds spec scaling

### PR DESCRIPTION
**Pull request by DominikPanic**
:cl: LaKiller8
balance: The amount of specialists is now scaled and depends on the amount of ready players.
/:cl:

### CODE REVIEW

**Comment by Mr-Worth** [comment]
Does the value in marines.dm not need to be touched? When I was trying this the total_positions value was what stumped me. Would this break the admin job slot control since it does not touch that?

**Comment by DominikPanic** [comment]
> 
> 
> Does the value in marines.dm not need to be touched? When I was trying this the total_positions value was what stumped me. Would this break the admin job slot control since it does not touch that?

Technically not since assigning a job will fail if there's not a place in the squad. Though syncing them would prevent one check.

**Comment by Rohesie** [comment]
Could you extend this to smartgunners?

**Comment by Rohesie** [comment]
This will prioritize squads by alphabetic name. Quite an interesting change in the meta.

**Comment by DominikPanic** [comment]
Should I randomize it?

**Comment by Rohesie** [comment]
No real need. Predictable is good.

**Pull request merged**
