### PR TITLE
Removes Russian Red from standard access in HvX

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title. HvH and ERTs unaffected.

## Why It's Good For The Game
Maintainers **_seem_** more open to the idea, so I figured I'd throw this PR up again to see how it goes. If this is not the case, feel free to close it.

## Changelog
:cl: Lewdcifer
del: Removed Russian Red from standard access in HvX.
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
My 2.5 toxin healing! nooooooooo!

**Comment by zzurge** [comment]
> My 2.5 toxin healing! nooooooooo!

Cant even do that,rye was removed in favor of oxy as i recall

**Comment by Looking4bros** [comment]
> 
> Cant even do that,rye was removed in favor of oxy as i recall

Rye doesn't heal Toxin damage, it just purges toxins. Why do people think rye heals toxins! is it that way in another server?

**Review by ivanmixo — APPROVED** [review]

**Comment by Mrrpip** [comment]
Hold on, no. Why are we approving this if #14871 fixes the whole problem of RR to begin with? It's already been nerfed a few times prior.

**Comment by ivanmixo** [comment]
I dont know if you've been following the discord but I've said this batch of PRs is basically mutually exclusive with that PR in my eyes

**Comment by Tommy-211** [comment]
pomni-stare

Time to pretend to be extremely angry when in reality I'm just disappointed 
please stop. Who hurt you mister lewdcifer?

**Comment by Dolth** [comment]
This shit is literally almost free neuraline, it should never have existed and needs to be nuked.
Everyone is complaining about chemicals and marine tankiness nowadays BECAUSE OF THIS, not because of meds.
Holy shit 50 pain reduction and barely 2 hp per _second****_ from BKTT which is what the majority does is NOT what makes marine tanky. This is.

**Comment by Lumipharon** [comment]
RR only serves to do the funny meme with.
The logic of "long term draw back of cloneloss vs high heal" just doesn't make sense considering the tradeoff is actually "cloneloss instead of dying AND cloneloss"

**Comment by novaepee** [comment]
russian red was sacrificed for these to get closed
image

**Pull request merged**
