### PR TITLE
renables survivor

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
survivor readd

## Why It's Good For The Game
gives the pregame some minor tension again for xenomorphs considering maturity has been massively buffed i don't see the issue with giga survivors and t1s/2s have gotten buffed consistently since addition and tbh most hives that got wiped by a survivor sucked ass, and the pregame for xenomorphs needs to be something other than weed the entire map

i can nerf the armor if that's a huge issue to have slowdown but i doubt that survivors will be good outside of major examples like david which mostly wiped because back then you had one handed shotguns and insane memes like runner being complete trash at 1v1, and now evasion is a thing

## Changelog
:cl:
add: survivor is back
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
This will be shit, everyone will cry and most hives are going to be wiped ((at least if survs are really that op as most people say)) but this will be funny as fucking hell, add it please.

**Comment by Jeff-jefferson-jeffery** [comment]
Hello? Based department?
Looks like we're back in business. I've waited a long time for this.

**Comment by Otterwatch** [comment]
Survivors were only op with their zero slowdown armor and the good weapons scattered around on maps. Nerfing the armor is probably a good idea if xenos are still getting wiped after all this time. (I'm excited to see how much has changed for survivor if anything)

**Comment by Derrick2Electricboogaloo** [comment]
> This will be shit, everyone will cry and most hives are going to be wiped ((at least if survs are really that op as most people say)) but this will be funny as fucking hell, add it please.

Let them cry. It is free entertainment.

**Review by BraveMole — CHANGES_REQUESTED** [review]
I'm fine with readding survivors, but i have some requests:

Kill the island on magmoor, this was just pain for xenomorph
Kill shutters on lv secure storage.

Either add slowdown on survivor, or do like CM is doing and randomize loadouts/jobs for survivors

**Comment by SplinterGP** [comment]
Why do survivors even need slowdown in first place, theyre usually on 10:1 or 5:1 disadvantages with shit weapons with no attachments at all, they even need to salvage map for supplies like medicine and materials which xenos can just camp and pre-melt, not counting very limited ammo. Xenos in the other hand not only have infinite resources to heal from and all but they also get Xray which lets them see survs from behind walls and not die to them by just keeping far away, xenos are not any fair match to survs

**Comment by SplinterGP** [comment]
> 
> 
> This will be shit, everyone will cry and most hives are going to be wiped ((at least if survs are really that op as most people say)) but this will be funny as fucking hell, add it please.

survs are not OP at all, they get shit weapons with shit everything, the only thing ever good they got is armor.

**Comment by SplinterGP** [comment]
>  or do like CM is doing and randomize loadouts/jobs for survivors
 they already have random loadout with random weapons, and no, adding that would just make it not playable at all and would turn in the shit CM has that cant do anything, even banning players from playing it because they managed to somehow kill xenos with their NO GUNS LOADOUT

**Comment by BraveMole** [comment]
Survs should not have better armor than marines. Rambo armor is 50 melee with zero slowdown

**Comment by Dolth** [comment]
> > This will be shit, everyone will cry and most hives are going to be wiped ((at least if survs are really that op as most people say)) but this will be funny as fucking hell, add it please.
> 
> survs are not OP at all, they get shit weapons with shit everything, the only thing ever good they got is armor.

AK and M16 are more than viable, 50% resistance armor is good, no slowdown is good. It's not OP but it's a really good fighting loadout to fight youngs and matures first tiers.

**Comment by Nirvan4** [comment]
Good thing, with the xenos changes and turrets being a thing bald xenos really need to put efforts in losing

**Comment by TiviPlus** [comment]
Mantainerbus is discussing this

**Comment by AndroidMK2** [comment]
I really hope to see them back also the only thing that made them op is the ultra-instinct marine mains that mastered every button to muscle memory.

**Comment by TiviPlus** [comment]
Maintainers have unanimously decided on the following:
```
a surv pr should have:
 - something to prevent rush
 - no gamer gear (see the 0 slowdown armor)
 - no noob traps (shutters, magmoor island)
 - a non killing xeno objectives, other than surviving. Can be defend a place, grabbing that many items, whatever, they are free to look for resources but there must be a mechanic to soft forbid rushing
```
As this PR does not change any of these and just aims to be a direct revert Like previous PR's it will be closed but you can feel free to open a new PR following the above guidelines

**Comment by Jeff-jefferson-jeffery** [comment]
lol have any of you ever played surv holy shit lmfao

**Comment by SilencedMP5A5** [comment]
maintainers have unanimously decided on the following:
- survs should not be allowed to have fun

**Comment by mathis650** [comment]
> maintainers have unanimously decided on the following:
> 
> * survs should not be allowed to have fun

maintainer moment

**Comment by rusher210** [comment]
>  - a non killing xeno objectives, other than surviving. Can be defend a place, grabbing that many items, whatever, they are free to look for resources but there must be a mechanic to soft forbid rushing
> ```
> 
> As this PR does not change any of these and just aims to be a direct revert Like previous PR's it will be closed but you can feel free to open a new PR following the above guidelines

im no coder nor i understand game balance and such important things. Regardless i find survivors really fun and i wish to share some thoughts on the last point.
on lv: what if survivors have to power an area to extract intel before the hive descends upon them, if the surv succeed they have to quickly reach the (this is where the crashed ship was) reverse drop pod to secure a "survivor escaped" "win" condition.
Marines, in this particular case should be hostile to avoid marines drop podding round start to help survs on their little objective. Lore wise they were sent by TGMC to wipe out every life form to leave no evidence of catastrophic TGMC security protocol failure.
surv idea for big red:
there are no survivors, only a few SOM operatives (basically civilians that sabotaged the colony so no SOM operative equipment other than a armband/cosmetic); their objective should be retrieving an intact alien embrio from the labs. (maybe give a random SOM operative 1 c4 idk im shit at balance Ren guide us).
SOM can extract should they repair a crude inverse drop pod (or rudimentary ship) with components found on the map. If they leave with the embrio they get a SOM victory; without embrio a defeat; wiped major SOM defeat.

i'd love to see more ideas regarding bringing back surv

**Comment by Otterwatch** [comment]
> Marines, in this particular case should be hostile to avoid marines drop podding round start to help survs on their little objective. Lore wise they were sent by TGMC to wipe out every life form to leave no evidence of catastrophic TGMC security protocol failure.

Marines have to wait until ds is groundside to drop pod and the alamo can only cycle at 12:18 which is the same as tadpole. Survivors probably wouldn't still be alive without achieving that objective at that point.

**Comment by BraveMole** [comment]
Please don't necro.

If you want, ask me to open a thread on balance about survs

**Pull request closed without merging**
