### PR TITLE
Adds In-Game Notification on How To Replace Sentry Batteries

### PR DESCRIPTION
**Pull request by KornFlaks**
## About The Pull Request

Adds a short blurb to hitting a sentry with a battery in hand that already has a battery on how to remove. Alt-click.

## Why It's Good For The Game

Everything in game requires a simple click on either an obvious button or directly on a sprite. Alt click to remove a battery from a sentry is incredibly niche and very unlikely to be stumbled upon by a bald engineer hitting a sentry with a battery to replace.

This short message will give the bald engineer (e.g. me) an indication on what to do.

## Changelog
:cl:
add: Adds text blurb on a sentry for an engineer to alt-click to remove battery to replace.
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
Or actually why not put this on examine()

**Comment by KornFlaks** [comment]
Why not both?

**Comment by KornFlaks** [comment]
I'll deal with the MC when im done with this game...

**Comment by KornFlaks** [comment]
Done

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
