### PR TITLE
oxy purges tramadol

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
rate of 5 for oxy purging tramadol
## Why It's Good For The Game
I mean, painkiller stacking is pretty cringe, I would make it poison you but oxy is an emergency chem right now so.
## Changelog
:cl:
balance: Oxy purges tramadol at a rate of 5 per tick.
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
* Stacking painkillers is increasingly inefficient & unsafe
* Oxycodone is not a typical chemical for marines to carry around.
* You didn't actually explain **_why_** this is bad. Just that you thought it was.

PK stacking is more often used by corpsmen trying to get marines back into the field/wean them off the initial slowdown from being revived. I can't fathom a reason why that's supposed to be a bad thing.

**Comment by Strayed-Raven** [comment]
If marines were not supposed to carry around oxycodone then why can you vend injectors for it? The main benefit im seeing here is Oxycodone was buffed to 100 pain reduction. And now all of a sudden its the problem with tram but then why was oxycodone buff PR accepted for if now its said to be a problem? The logic is a figure eight or nobody cares to think that far ahead. Pain is a crappy mechanic imo when even healed to full you still get spammed with the pain. Most marines that know whats up are constantly on tram. The ones that need oxy too are the ones that actually FIGHT. Is this combo so bad for balance that xenos cant manage or was it just an oversight?

**Comment by Coastfront** [comment]
And how defiler, as indirectly as a flower trampled 'neath a stampede was indirectly nerfed again.

Does painkiller stacking let you tank an obscene amount of pain? Yes.
Does it cause you to approach the chem limit faster? Yes.

Most importantly, does it add yet further armor piercing damage if a defiler is attacking you? Yes.
Speaking of defiler, if for whatever purpose the effervescent gleam of 200 toxin damage gentle caressing your unwinding mortal coil does not tickle your fancy, get fucked.
If you consume the holy quadrinity and then take oxycodone, IIRC you are then at the chem limit and cant have ANY more medicine, or you will get druggy. oxy aswell, while its tox can be sustained by tricordrazine, further toxin can't then be outmatched.
If you don't want to get torn to shreds by toxin damage from neuro, literally every defiler chem in the game, etc. You either have to accept chem limit druggy vision + confusion, or microdose 3u dylovene, which iirc still actually triggers the limit for a few seconds. 
Along with this, most people either A: Don't care enough to setup dylo microdosing 
Or B: Don't exactly want to or have time to unwield their gun, pull out their 3u pill/injector, into then using it on themselves and re-wielding while actively having their attention and actions demanded elsewhere (being killed.)

It is plate armor with a flaring gap. Oxy+the quadrinity of chems is a shield against pain and generic damage types, but renders you more vulnerable to toxins in exchange due to being at the cap for chemicals-before-your-eyes-blur

**Comment by Lumipharon** [comment]
Don't need this right now.

**Pull request closed without merging**
