### PR TITLE
enables hunter animation sprite that was already in files

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
Enables hunter running and walking animation, looks nice, maybe funny, if not wanna accept it just testmerge for a few rounds maybe, so we can laugh a bit at hunter walking while all xenos are moveless sprites.
[https://cdn.discordapp.com/attachments/498569646014857221/762546657442136095/hunter_shitpost.mp4](url)

## Why It's Good For The Game
looks good and is nice, also some different thing.

## Changelog
:cl:
imageadd: turns Hunter animation sprite on.
/:cl:

### CODE REVIEW

**Comment by neohenry** [comment]
Can't wait for other xenos to get walking animation ha ha

**Comment by TiviPlus** [comment]
funny walk

**Comment by SplinterGP** [comment]
also why the heck did it add 35kb, byond are you saying me that deletting two words is 35KB ? JESUS

**Review by Hughgent — APPROVED** [review]
magic

**Pull request merged**
