### PR TITLE
Remove Magmoor from TGMC

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

I can assure you that people vote Magmoor just to troll other players who didn't vote (or who did). In my survivor time, I make it a living Hell for xenomorphs to get to me by rushing medbay for meds, running to volcano land, waiting for 30 minutes, and walking to marines. Any sane players put Magmoor as one of the worse maps. I even have statistics just to prove it.

image

image

I didn't want to do this since I knew the admin that made this, but no one wanted to maintain this map, and a map that remained unmaintained is a bad map.

## Changelog
:cl:
del: Magmoor from TGMC
/:cl:

### CODE REVIEW

**Review by RipGrayson — APPROVED** [review]
I'm going to preemptively approve this, but I would like discussion before I merge. Any other maintainer can intervene and close this if they strongly feel Magmoor should stay.

**Comment by Lumipharon** [comment]
But without magmoor I won't be able to watch pitboss without fail sneak onto the ship every time :(

**Comment by FosterGrime-Heymynameslouie** [comment]
reject magmoor
embrace barrenquilla

**Comment by GravitronBlue** [comment]
> But without magmoor I won't be able to watch pitboss without fail sneak onto the ship every time :(

That was mostly guaranteed back when wraiths could phase through the rock around the LZ and just camp by the vents for an opening in complete safety.

Having such high liability vents that xenos can flank into FOB undetected to skip playing the map at all is at least an indicator that magmoor isn't liked and is in need of either removal by this PR or more changes.

Otherwise to just list some of the issues with magmoor:

- Random lag that I suspect is simply caused by lava lighting
- Plat miners that tadpole/drop pods can reach immediately
- Shallow and unconnected cave systems (the southwest part of magmoor has never been touched by xenos to my knowledge except in the rarest of cases)
-The entire map being segmented into continents by tiny lava rivers that favor ranged combat, something marines are better geared towards. This ends up turning rounds into long slogs when xenos try to match marines at this using boilers.

**Comment by lKiseki** [comment]
Probably unnecessary to remove the map. You can just remove it from rotation via the server box.

**Comment by Lumipharon** [comment]
Leaving the map in implies it's going to be maintained in a usable state though.

**Comment by Dzhimax** [comment]
автор долбоёб, пошёл на хуй. Fix prison station, fix LV, fix magmoor, fix icarus. DON`T DELETE, CLOWN, FIX THE SHIT YOU DID Prison has zones for OB and Droppod landing in cave zones, where silo can be plased, only two places for silo. LV is shit, fucking green grass that you can't put alien weed on it. A fucking river on a third of the map, on which you also can't put alien weeds and build resin. Hideous shaped caves that look more like intestines, which are hard to defend and there is no place for silo. LV - map for marines only. 

Two-thirds of the card is not used on Magmoor. Just one place for silo, too little lava to throw Marines into it. There are no computers for 60 supply points very few initial alien weeds. 

Ikarus is a map for xenomorphs with flaws like the lack of walls near space. Solid labyrinths in which you can not build anything, it will be very difficult for the Marines to move anyway. At the same time, there is a disgusting fog that interferes with construction and, oddly enough, there is no normal place for silo.

Fix, monkey, don`t delete

**Comment by Weedmaster77** [comment]
> I can assure you that people vote Magmoor just to troll other players who didn't vote (or who did).

 Trolling with map voting seems to be based on with side is on a wining streak or a disadvantage based on which side has more mains or higher pop on, or doesn't.  Feel like this is with all maps so to single Magmoor out is unfair.

> In my survivor time, I make it a living Hell for xenomorphs to get to me by rushing medbay for meds, running to volcano land, waiting for 30 minutes, and walking to marines. 
 
To use this as a any reasoning makes no sense since survivors isn't even a mode anymore, accept for when the admins once in awhile making it a event. 

I don't think it should be removed just because its not maintained, I could be wrong but it seems like Chigusa has been the same for as long as its been in rotation. Even if Chigusa doesn't get played as much or doesn't have as many glaring problems as Magmoor. Magmoor doesn't get played as much compared to the other maps that do get maintaining work which are played multiple times in a row or in a short amount of time giving them more focuses for people to care that there are problems shouldn't  make Magmoor bad enough for removal. I think Magmoor is just a nice change in pace and should be played different if you want to win compared to other maps regardless of what side your on its nice because its something different. Sad that is doesn't get maintained since I like the map and would hope that it doesn't get taken out.

**Comment by Al-1ce** [comment]
Magmoor sucks for a multitude of reasons, the largest being that 3/4ths of the map is considered underground, rendering tac-binos completely useless outside of the exterior-FOB area.

**Comment by Al-1ce** [comment]
Magmoor sucks for a multitude of reasons, the largest being that 3/4ths of the map is considered underground, rendering tac-binos/other artillery completely useless.

> I don't think it should be removed just because its not maintained

The game is always changing. So, the maps need to change with it. Not being maintained = into the trash, always.

**Review by BraveMole — COMMENTED** [review]
Neutral on the matter

**Comment by TiviPlus** [comment]
:((

**Comment by RipGrayson** [comment]
After a bit of discussion this map has been config disabled, the decision to delete the map entirely can be revisited in the future if needed.

**Pull request closed without merging**
