### PR TITLE
Undoes the chemistry lock, chem is open for everyone (also oxy is no longer a free refill from vendors)

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request
Title! Brings chem restrictions back to pre #12170. With the addition of making the doors free access for everyone (no more window smashing) and making oxy not a free refill from the vendor (since you can mix it now)
## Why It's Good For The Game
With the current state of the game this should no longer be necessary considering most of the gamer mixes are lemolocked anyways.
## Changelog
:cl:
balance: The chemistry machines are no longer offlimits to marines (fumble still applies)
balance: The chemistry door is no longer access locked
balance: You can no longer refill partially used up oxycodone injectors
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
Holy based, also, if you're removing EZ oxycodone, the Corpsmen med vendor currently has Oxycodone bottles that you can get free refills from, so you may want to look at that.

**Comment by Barnet2** [comment]
I've been waiting a year and a half for this. Prayers!

**Comment by Naaanii** [comment]
Holy shit, we're so back.

**Comment by Aporhtonoma** [comment]
please for the love of god no more MY RP let me be the chemnerd and make my super mixes

**Comment by Lauwma** [comment]
YESSSSSSSSSSSSSSSSSSSSS YESSSSSSSSSSSSSSSSSS PETTE WE ARE SO BACK PETTE WE ARE SOOOOOO BACK

**Comment by Looking4bros** [comment]
JoeRoganSweating

**Comment by DrAmazing343** [comment]
Oxycodone is still functionally infinite, you just have to brew it yourself now. This has created dumbass busywork for me, and it just kinda is ass. Letting every marine off chemlock is one thing but making Oxycodone "limited" has done nothing but create frustration.

**Comment by ivanmixo** [comment]
It's a tier 2 painkiller, I wouldn't be complaining about getting it for free for pressing 3 buttons

**Pull request merged**
