### PR TITLE
LV624: LZ2 revamp plus minor cave adjustments

### PR DESCRIPTION
**Pull request by RipGrayson**
Revamps and moves LZ2 farther west, swapping its position with the metal cargo box area. Adds a small tunnel above LZ2 allowing for marines to directly enter southwestern caves. Adjusts a sign near hydro tunnel so it doesn't float in mid air.

LZ2 is widely considered to be the worst LZ by general opinion. Most LZ's are built around having 2-3 fixed points for sieging, LZ2 on the other hand can be sieged from almost anywhere in a 180 degree due to all of its walls being breakable with acid. Additionally, due to the setup of LZ2, only one exit of its three exits is viable for pushing, meaning that xenos can freely concentrate their forces and stifle any attempt at breakout. 
It's not uncommon for marine forces to never make out of FOB, let alone make it across the river.

By revamping and moving the LZ we can reduce those problems while adding additional interesting options to the marine forces.
Marines can now venture from LZ2 into southwest caves directly, at the cost of entering unfriendly terrain easily contested by hostile forces, or fight east into the colony to flank medical and hydro from an odd angle.
Multiple exits viable for pushing means that marines are less likely to get into a stalemate against hostile forces, while still offering many ways for xenos to siege LZ2 if that push fails.
Additionally, moving the LZ should reduce the amount of monotony over battling for the same positions multiple rounds in a row, since LZ1 and 2 offer entirely different routes and encourage different attacking directions.

## Changelog
:cl:
balance: LV624: LZ2 has been rebalanced and moved.
balance: LV624: Western cargo storage has been moved to LZ2's old spot.
fix: LV624: Fixed a disconnected engineering sign near hydro bridge.
/:cl:

### CODE REVIEW

**Comment by RipGrayson** [comment]
Here's a comparison between the LZ2 pre and post revision.
beforeafterlz2

**Comment by Oscari-pog** [comment]
It might get some use now
very gud

**Comment by KornFlaks** [comment]
Can you post a screenshot of north and south LZ2? How does it look until the river? What does south flank look like?

Also dont forget the "can not build until shutters" zone. Current LZ2 lacks it which compounds the fact that it's worthless in it's current state. But dont extend it too far please.

Easy access to caves is a double edge sword. Especially if xenos wait to silo until the FOB drone appears to know where marines are landing. LV is infamous for marines unga'ing into caves only to die in a maze 9 screens deep and un-OB'able due to deep underground.

I like what I'm seeing. Some variety from the usual Nexus landing is always good.

**Comment by SplinterGP** [comment]
i'd say move it over the dome on its right as it was before the new rework, so it aint too much on the extreme of the map, it seems way too much on the edge now

**Comment by GradusNL** [comment]
> 
> 
> i'd say move it over the dome on its right as it was before the new rework, so it aint too much on the extreme of the map, it seems way too much on the edge now
It's just the old LZ2 spot with an added northern entrance. I didn't see why LZ2 had to be moved. Reverting back to the old one is good. LZ1 is also on the extreme of the map, but the opposite one. Not seeing anyone complaining about LZ1.

**Comment by RipGrayson** [comment]
> Can you post a screenshot of north and south LZ2? How does it look until the river? What does south flank look like?
> 
As requested, an extended view of both north and south LZ2.
nslz2
North LZ2 goes into southwest caves, the area is fairly unfriendly to marines, they'll likely have a difficult fight on their hands even before they hit the main caverns. As a side note the northern cave opening is somewhat necessary for crushers and boilers to siege the north LZ2 effectively.
South LZ2 is likely to be less monitored and thus vulnerable to a stealthjack, but a counter push could seriously hurt xenos if the marines get their shit together.
> Also dont forget the "can not build until shutters" zone. Current LZ2 lacks it which compounds the fact that it's worthless in it's current state. But dont extend it too far please.
> 
Sadly there's no fine control over the "can not build until shutters" range, if a shutter is in an area it makes that area unable to be built in. Old LZ2 had its shutters entirely within the LZ2 area, essentially meaning that there was no exclusion zone.

**Comment by RipGrayson** [comment]
Barring maintainer requests this PR is ready.

**Comment by SplinterGP** [comment]
i think honestly it could be moved to its older position with then it going from there, i feel like the path is WAAAY too straight line to the caves from the top entrance, plus i think its too much closed and on the border of the map, could be made more acessible to xenos and have paths around it

The things from this PR coupled with some of those would be good in my view.
image

**Comment by RipGrayson** [comment]
> i think honestly it could be moved to its older position with then it going from there, i feel like the path is WAAAY too straight line to the caves from the top entrance, plus i think its too much closed and on the border of the map, could be made more acessible to xenos and have paths around it
> 
> The things from this PR coupled with some of this would be good in my view, and i prefer the passage from that one in the pic too since its less straight forward and a view from FOB, alongside a more extensive jungle. PR in question:
> #6455

I appreciate your feedback but it seems the reception to the LZ2 changes in that PR wasn't particularly positive, in fact some were outright acidic towards said changes. I will look into your suggestion about the path being too direct and your suggestion about alternate routes on the western side. 

All that being said and with all due respect, I don't feel like there's a consensus LZ2 needs moved east. If there's an official maintainer requirement to that effect or more feedback to that effect, I will do my best to compromise and incorporate that suggestion.

I actually just recently learned that my adjustment is extremely similar to the one put forward in #4570, I actually didn't know of its existence or the old LZ2 position until _after_ I finished making these map changes. Small world I guess.

**Comment by SplinterGP** [comment]
> I appreciate your feedback but it seems the reception to the LZ2 changes in that PR wasn't particularly positive, in fact some were outright acidic towards said changes. I will look into your suggestion about the path being too direct and your suggestion about alternate routes on the western side.

that's why i said between a mix of both, seeing  how there were some mistakes on the old one, but the new building on river is way better than what we currently have and makes it a bit less CBT for xenos over there, while on yours is a straight path from marine FOB into it that they can unleash suppressive fire 

image

**Comment by SplinterGP** [comment]
> All that being said and with all due respect, I don't feel like there's a consensus LZ2 needs moved east. If there's an official maintainer requirement to that effect or more feedback to that effect, I will do my best to compromise and incorporate that suggestion.

i mean its a good thing it not being way too close to the border of the map, you can easily remove one  of the dome close to put it more east (like it did before) and give some more space for xenos to move around the LZ

**Comment by Ieteihowmee** [comment]
Looks less ass. Nice, maybe we can get more than one LZ use.

**Comment by Al-1ce** [comment]
I really like the new LZ2 design you've got going here, especially since it's familiar and resembles the old-old one. I'm not sure who mapped LZ2 as it is before this PR is merged but it is absolutely fuckin' disgusting.

**Comment by Al-1ce** [comment]
This looks really nice! I'm not sure who mapped LZ2 before this TM but it was functionally terrible and looks pretty gross.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
