### PR TITLE
Adds the "Toggle Seethrough" component from TGStation to xenos

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Ported from TG https://github.com/tgstation/tgstation/pull/77361

Adds a component that grants the ability "Toggle Seethrough"
This allows you to make your sprite translucent, allowing you to click through your own mob.
By default I'm adding this component to xenos.

https://github.com/tgstation/TerraGov-Marine-Corps/assets/66163761/f4d3e409-18c5-464b-b5d9-cb4a3b2c5340

Do note, this doesn't interfere with anyone elses clicks but your own since the invis sprite is client-side:

https://github.com/tgstation/TerraGov-Marine-Corps/assets/66163761/5ee7fe50-7b2c-49a4-b3e0-c94f4699a1d9
## Why It's Good For The Game
Gives xenos some well deserved QOL, allowing them to actually slash marines who are standing to the tile above them.
## Changelog
:cl:
qol: Gives xenos "Toggle Seethrough" ability, making their sprite translucent, allowing you to click through yourself
/:cl:

### CODE REVIEW

**Comment by efzapa** [comment]
basado

**Comment by yyzsong** [comment]
I could kiss you

**Comment by Aporhtonoma** [comment]
Bro is starting the year with a BANG

**Comment by Xander3359** [comment]
> Bro is starting the year with a BANG

I spent a week on this. Learning planes is some wizard shit

**Review by TiviPlus — COMMENTED** [review]
looks ok from skimming, what are we missing that tg has except set_plane?

**Comment by Xander3359** [comment]
> looks ok from skimming, what are we missing that tg has except set_plane?

We're missing the rest of the plane refactor (which I wanted to port after this)
See https://github.com/tgstation/tgstation/pull/69115/
Keeping in mind that I don't plan to port a single PR, but rather just update our code to TG current.

**Comment by TiviPlus** [comment]
> > looks ok from skimming, what are we missing that tg has except set_plane?
> 
> We're missing the rest of the plane refactor (which I wanted to port after this) 


excellent

**Review by TiviPlus — APPROVED** [review]

**Comment by Lumipharon** [comment]
Apparently allows you to just toggle invisibility.

**Comment by Arturlang** [comment]
Please make it a verb, not a action button, we have way too many action buttons

**Comment by usnpeepoo** [comment]
A few xenos have their sprites shifted slightly (or severely) when using the toggle seethru ability, here's a link showing which ones (Drone, sent, hunter, and behemoth).
https://imgur.com/a/7UpMCuV
I also don't know if it's intended but when you pounce a marine with the toggle-seethru active you will become invisible for a second which is visible to other players, here's a clip of it happening in valhalla: https://streamable.com/wxfkwj

**Comment by TiviPlus** [comment]
No verbs, but it maybe should be a pref

**Pull request merged**
