### PR TITLE
Removes Overeat Slowdown

### PR DESCRIPTION
**Pull request by Ben10083**
## About The Pull Request
Removes slowdown you get when you overeat

## Why It's Good For The Game
image

## Changelog
:cl:
del: Overeating no longer causes slowdown penalty.
refactor: Fat shaming removed from server.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Speedmerhe

**Comment by Lumipharon** [comment]
Muh immersion. I think bigboy slowdown is fine, but if you want to get rid of it the lines above are also redundant. For that matter overfed might as well not exist at that point.

**Comment by QualityVan** [comment]
Just don't overeat. Also simplifies treating low blood, which makes avoiding that less important in the first place.

**Comment by XSlayer300** [comment]
If you're overfed, might as well remove the indicator that you're overfed since people will complain and newbies will question about it.

**Comment by Losenis** [comment]
Wouldn't this have balance concerns on intentionally overeating to not get the slowdown over bloodloss tanking your nourishment?

**Comment by FosterGrime-Heymynameslouie** [comment]
just add a fat removal machine in medbay if fatness slowdown is a concern
this enables intentionally being obese to by pass bloodloss as said earlier and I believe a machine that removes fat already exists in tg code I think

**Comment by Al-1ce** [comment]
No thanks.

**Comment by Ragecrabbo** [comment]
Time to inject myself with 300u of corn syrup

**Comment by DerpiestBruh** [comment]
This cheeses low blood lol

**Comment by Lumipharon** [comment]
This affects various other things, and I don't see how this is good for the game. Just don't over eat yo.

**Pull request closed without merging**
