### PR TITLE
Rebalance minions

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Mantis and beetle will no longer flee.
Since they stick in the fight, nerf their hp so their overall usefulness stay the same.
Plus see CL for other changes

## Why It's Good For The Game

Close combat minions manage to flee only 5% of the time, because they are stupid. This feature only meant that marines had to shoot it longer, even when they constituate no danger; i think that's lame.

Minions will with this update generate as much damage as previously, but will eat less bullets

## Changelog
:cl:
balance: Mantis and beetle no longer flee from fights when low health
balance: Beetle hp from 400 to 260
balance: Mantis hp from 200 to 150
balance: Beetle forward charge only stuns for 2 seconds, 30 seconds of cooldown (it was 4 seconds, 10 seconds before)
balance: Mantis ravage cooldown upped from 6 seconds to 30 seconds
balance: Scorpion spit deal less damage, and the firerate is reduced
balance: Minions spawn rate divided by two. Minions maxium mob by spawner divided by two
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
RIP chad beetle.

Should they still try flee if there are no marines around? Like if they get set on fire, it's a bit silly they will still charge off 50 meters away and burn to death.

**Comment by ThelastArchiver** [comment]
140 is a bit much thats almost half its health maybe make 100 less for now?

**Comment by Tristan63** [comment]
Perhaps make more spawn

**Comment by Luxyboo** [comment]
remove AI its literally just a crutch

**Comment by novaepee** [comment]
Scorpon and mantis are faster than runners.

Marines are seething about minions tanking, but I'm going to count that as skill issue. We could make minions less of a bullet sponge if possible.

**Pull request merged**
