### PR TITLE
Attachment position adjustment for br 64, ar 18 and pr 11

### PR DESCRIPTION
**Pull request by Aquilar**
## About The Pull Request

This adjusts the underbarrel attachment point on the BR-64 so it's no longer just floating. This position is chosen mostly for aesthetic reasons, the BR 64 has a fairly large foregrip that fits the underbarrel GL nicely and makes the two grips look more integrated, 
And and adjusts the muzzle attachment point on the AR-18 so it's on the barrel and not below it.

edit: adjusted the PR-11s stock by one pixel.

Before
daerror

After
daafter

## Changelog
:cl:
fix: adjusts the positioning of the attachments on the BR-64, AR-18 and PR-11
/:cl:

### CODE REVIEW

**Comment by Xsdew** [comment]
The grenade launchers are supposed to be below the weapon. Not inside the weapon. Of which only the BR64 needs the fix.

**Comment by XSlayer300** [comment]
stock adjustment for the PR11 is also slightly off.

**Comment by TiviPlus** [comment]
Please fix the issues people pointed out

**Comment by Aquilar** [comment]
done

**Pull request merged**
