### PR TITLE
xeno sprite files reorganization

### PR DESCRIPTION
**Pull request by Blundir**
## About The Pull Request

Makes it so xeno files are placed in their own files, instead of three gigantic files for wound overlays and xeno sprites.

## Why It's Good For The Game

Has good chance to lower lag due to a lot lighter load on asset loader. 

## Changelog
:cl:
refactor: reorganized xenomorph sprites folder
/:cl:

### CODE REVIEW

**Comment by Blundir** [comment]
What? I don't have such errors, gonna rerun checks later

**Comment by Lumipharon** [comment]
> What? I don't have such errors, gonna rerun checks later

image

**Comment by Blundir** [comment]
Gonna do some additional stuff

**Comment by Blundir** [comment]
As usual

**Pull request closed without merging**
