### PR TITLE
Engineer gear rebalance (attempt 2: the kitting)

### PR DESCRIPTION
**Pull request by Aquilar**
## About The Pull Request

~~woo second attempt~~

This PR makes a set of changes to engineer gear, putting all the strong gear into specialised kits which sit in their own category called "Engineer Specialisation" away from the engineer supplies category. They get one point to use to pick a kit.
The general intention is reduce the amount of strong gear engineers can bring at spawn and instead push them toward more specialisation in battlefield roles.
The pricing of the M20 mine boxes were reduced to make them slightly more appealing. 

image

Breakdown of the new kits:
- the logistical engineering kit contains the teleports and dispenser.
- the forward support kit contains the radio backpack along with 2 fultons and tactical binoculars.
- the breacher kit contains the plasma cutter along with 2 C4, 4 detpacks and a signaller.
- the Construction kit is a generic resource bundle with 100 metals, 50 plasteel, 20 barbed wire and a hi cap welder.

edit: added construction kit and tweak the original kits slightly.

## Why It's Good For The Game

A core issue of engineer is the amount of strong gear they can bring to the field at spawn, no amount of fiddling with numbers, tweaking point values or removals is going to fix this problem with engineer role's gearing, this solution lets engineers keep their strong toys while also limiting which ones and how much they can bring.

## Changelog
:cl:
add: new category added to gear vendors called "Engineer specialisation", engineer role gets 1 point to use in this category. 
balance: Engineer gear points reduced from 75 to 50
balance: following items been moved Engineer specialisation category; Liguana, ST-580
balance: engineer's teleporters, dispenser, radio backpack and plasma cutter options have been rolled into new specialization kits in Engineer specialisation category.
balance: points cost of M20 mine box reduced from 18 to 15 and Large M20 mine box reduce from 35 to 30
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
hoyl shit

already thought the original pr was good
this makes it better

speded merhg

**Comment by Losenis** [comment]
>PC nerfed even more by making it mutually exclusive with other shit that overshadow the everliving shit out of it

image

**Comment by Arctrooper8** [comment]
I wouldn't use boxes. Using boxes makes it so that you can't save them in a loadout and can be annoying.

Also having the breacher kit be the PC and four c4s feels lackluster. You should move it back to engineering supplies (you can always adjust the price of PC) or at least give the kit more oomph.

**Comment by Aquilar** [comment]
@Arctrooper8 
yeah the breacher box lacks a bit of oomph but I kept it minimal for now, could put some det packs too or more C4, so you have any recommendations?

for the forward support kit, engineer just doesn't get a free radio back pack anymore. I was real tempted to add the full tac binos to it and then thought better of that.

as for the box thing, it was recommended I do it this way, making loadout work with it was too much of a hassle due to how loadout handles everything, which is a rabbit hole I do NOT want to wander down again.

**Comment by Losenis** [comment]
Wait, you locked radiopack behind a kit too? What the fuck dude

**Comment by Autisem** [comment]
I dont get this point of engineers having to many strong items, the really strong items are locked behind super high point requirement and everything else is powerfull utility at best. the teleporter is extremely powerfull but its powerfull at being support utilitry, same for the dispencer and backpack. which is there jobs

**Comment by Arctrooper8** [comment]
> @Arctrooper8 yeah the breacher box lacks a bit of oomph but I kept it minimal for now, could put some det packs too or more C4, so you have any recommendations?

It might be fun to buff the plasma cutter itself actually, maybe make it an effective melee weapon or better stats in some way, but that's beyond the scope of this PR. For now I'd replace the C4 with detpacks, they still fit the breacher role but are also more versatile and fun to use.

> for the forward support kit, engineer just doesn't get a free radio back pack anymore. I was real tempted to add the full tac binos to it and then thought better of that.

I notice that now, my bad.

**Comment by Starfirejordan** [comment]
where mortar kit and flamer kit from last PR. those looks cool to allow engi to get em 

~~Then again all engi's being able to to get a bunch of mortar might be broken~~

**Comment by iLikeMemes** [comment]
The logistical engineering kit has both dispenser and teleporter both of which you often put on your back, might be a bit counterproductive to put them in the same kit. You’d have to leave the dispenser in the FOB and use the teleporter to retrieve it. I would either focus on dispenser or teleporter, not both.

**Comment by Aquilar** [comment]
@iLikeMemes would you like to know you can store the teleporter pads in the dispenser.

**Comment by iLikeMemes** [comment]
@Aquilar i did in fact not know that dispensers could store teleporters, in that case its most certainly fine.

**Comment by zzurge** [comment]
Hell nawl

**Comment by Mechswordsman** [comment]
The PC kit would only really work out for them if it was the old PC with changeable batteries.  This also doesn't fix the problem mentioned, it just takes away more player choice and makes it worse to play.

**Pull request closed without merging**
