### PR TITLE
Removes T-47 railscope, Limits mini-scope attachments in the vendor

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Removes the T-47 railscope, replacing them on weapons that had it with a miniscope. Also limits the mini-scope to 1 per 8 marines.
## Why It's Good For The Game
Off-screen weapons are currently really annoying to deal with, being unable to see them until you get shot, and fighting them requires diving far into the marine ball, something few, if any, castes can do without dying. While this pr won't remove this, it'll certainly limit it to make it less frequent.
## Changelog
:cl:
del: Replaced scopes with more range than a mini-scope on most weapons with a miniscope (exceptions are mounted weapons, anti-material rifle, and autosniper)
balance: Limited the miniscope attachments in the marine weapon vendor to 1 per 8 marines.
/:cl:

### CODE REVIEW

**Comment by Wisemonster** [comment]
If this is considered still too many or too little, let me know and I'll change the numbers around.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
DMR and BR shouldnt really be limited considering their falloff stats are closer to normal rifles

**Comment by Wisemonster** [comment]
Alright, unlimited them

**Review by Kuro020 — APPROVED** [review]

**Comment by Kuro020** [comment]
Should wait for barnet to do this boiler pr to TM both at the same time

**Comment by LohnRan** [comment]
Well, can you add the weapons you are limiting to req then?

**Comment by Wisemonster** [comment]
Already, I've been suggested with just straight up killing railscope except on amr/autosniper, so I'll try that

**Comment by Wisemonster** [comment]
Ok, I changed most non-mounted guns that aren't the autosniper/amr to use miniscopes instead of the rail scope. I'm not sure how this may affect campaign. If this mass removal of rail scopes is too much, let me know and I'll go back to simply limiting snipers/scope attachments.

**Comment by Lauwma** [comment]
> Ok, I changed most non-mounted guns that aren't the autosniper/amr to use miniscopes instead of the rail scope. I'm not sure how this may affect campaign. If this mass removal of rail scopes is too much, let me know and I'll go back to simply limiting snipers/scope attachments.

Campaign doesn't use scopes

**Comment by SimplySmiley123** [comment]
Does SR-127 still use a regular scope or nah?

**Comment by 00ze-cyclone** [comment]
> Does SR-127 still use a regular scope or nah?

Miniscope

You limited the amount of miniscopes on the vendor but the unlimited guns still start with miniscopes on them so it’s moot since you can detach them

**Comment by Lauwma** [comment]
Also make it scale with pop

**Comment by revelation-8468** [comment]
The martini being limited the same way as the TL127 is confused me a bit - the Martini is hardly a "sniper rifle", I see it used more often as a frontline gun. I don't think limiting that is neccesary.

**Comment by BoltedAirlock** [comment]
if the scopes that allow for sniping are going what is the purpose in limiting how many marksman rifles are available? If it's because "they come with a miniscope and side-step the limit" then just have them _not_ vend with a scope already attached surely

**Comment by SimplySmiley123** [comment]
> The martini being limited the same way as the TL127 is confused me a bit - the Martini is hardly a "sniper rifle", I see it used more often as a frontline gun. I don't think limiting that is neccesary.

Plus martini isn't even remotely good to consider limiting it anyway.

**Comment by Wisemonster** [comment]
Alright, I unlimited the marksman weapons, but took off the generic miniscopes from them to prevent infinite miniscopes

**Comment by chizzy376** [comment]
Snipers aka "offscreens" aren't the problem. It's the lack of a sunder dmg drop off. You merge this and the skill ceiling for both teams will lower for no good reason. Heavy ided vibes and a bad solution to a whole different problem. Don't merge this lol.

**Comment by SimplySmiley123** [comment]
> > Does SR-127 still use a regular scope or nah?
> 
> Miniscope
> 
> You limited the amount of miniscopes on the vendor but the unlimited guns still start with miniscopes on them so it’s moot since you can detach them

It... Kinda defeats the point of SR-127 then, it's meant for long ranges.

**Comment by Wisemonster** [comment]
Alright, I think I got it so that the mini scope scales with pop. I also unlimited some markmen weapons I missed earlier

**Comment by CoastalCookie** [comment]
I find it important to ask... What do we do against **Boiler** then? Boiler is a offscreen caste and requires a sniper rifle with a sniper scope otherwise you can't hit it do you just need to binoc module spam now?

**Comment by CVSthePharmacy** [comment]
pr reeks of bad ideas. Removing the rail scope, which is the ONLY way to spot boilers before they hit you with a neuro ball, is an incredibly bad idea, if you got offscreened then you were most likely not in the maze or you tried to fuck with cades on your own. Also back to boiler, their only counter is just... rail scoped weapons... and the counter to people using rail scopes is just, not going out in the open??? like... why???

**Comment by Kuro020** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/16038

**Pull request closed without merging**
