### PR TITLE
Allow many non-combat essential objects to be slashed at all or faster by xenos

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

See changelog.

Part 1 of X.

## Why It's Good For The Game

Closets (including coffins and toggleable crates) probably should not be immune from slash destruction, and opening one should not trigger attack cooldown.
Wooden crates, barrels, cases, plastic flaps, beer kegs, ore boxes hydro trays etc.. take a long time to destroy especially with acid which is even slower than slashing which the majority of overlooked movement blocking objects lack the resistance flag for.

## Changelog
:cl:
balance: Reduced the max_integrity of: coffins, large crates (the kind that must be broken or opened with a crowbar), cases, barrels, ore boxes, plastic flaps, hydro trays, mop buckets, janitorial carts, filing cabinets, and reagent dispensers.
fix: Added the xeno damageable flag to: janitorial carts, filing cabinets and reagent dispensers (beer keg, boozeomat, etc..)
fix: Removed useless train vehicle attack_alien override preventing damage. 
fix: Fixed xenos not being able to open wrapped large parcels i.e. wrapped lockers.
fix: Opening gracefully, not smashing, closets does not put xeno attack on cooldown.
fix: Fixed closets not taking damage from slashes even though the animation played and informed the xeno they "smashed" the object.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Don't nerf integrity into the ground, it's especially relevant for shooting. 40 integ is like 2 bullets/slashes/spits.

**Comment by Wayland-Smithy** [comment]
~2 slashes is the goal. Keep in mind these are mostly for fluff and have not been touched for a long time while slash damage has only been going down.

**Comment by Wayland-Smithy** [comment]
> When has slash damage changed?

#4436 #6562 I'm sure there are others, and you are free to dive the blames or just ask MJP I bet, these are just the ones I remember. 

I still think there is some confusion here about what exactly is being reduced to 2/3 slashes to break. Practically nothing shipside as the useful "toggleable crates" are children of closets whose integrity remains unchanged.

Hydro trays in particular give the same effect as unwired cades and should have 50 more integrity than metal cades, and as a side effect take forever to clear out. Same goes for the other objects effected. Please pick something else to take issue with and stop shitting on what is really a QOL change.

**Comment by Naaanii** [comment]
Is janitor cart and mop bucket included in this too? Sometimes run into them on Prison Station.

**Comment by Wayland-Smithy** [comment]
mop bucket could already be slashed, but was 500 integ, janitor cart needed both treatments

that is the last addition to this PR
more will have to wait for part 2

**Pull request merged**
