### PR TITLE
Queen Screech Buff

### PR DESCRIPTION
**Pull request by Swagile**
## About The Pull Request

With the constant nerfs to queen's primary unga ball handling tool, I thought its time to at least buff it in terms of CD; Queen screech CD is lowered by almost half from 100 seconds to 60 seconds.

## Why It's Good For The Game

Queen screech used to be really, REALLY powerful; but has since had constant nerfs. From the actual stun removed and made a drop stun (something done ages ago), to removal of the stam crit, queen screech now is just there to setting up team plays as the stun is momentary. It isn't good at doing that, however, because the CD for queen screech is almost the same as its had since the start yet is overall weaker. This should let queens who know what they are doing setup plays much better against good marine players.

## Changelog
:cl:
balance: Queen screech CD from 100 seconds to 60 seconds.
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Based

**Comment by David-Stormwell** [comment]
I still don't see a reason on why this is needed, it's still a very good tool for softening up Marines and killing them.

**Comment by Swagile** [comment]
> 
> 
> I still don't see a reason on why this is needed, it's still a very good tool for softening up Marines and killing them.

because its had constant nerfs with no other buffs to it, making it a shit tool against marines with any IQ since it takes so long to recharge

**Comment by DerrickChamberlain** [comment]
I guess I will see in time if this will bust my bussy

**Comment by Naaanii** [comment]
Too low of a cd for a screen wide disruption that also goes through walls.

**Comment by David-Stormwell** [comment]
> 
> 
> > I still don't see a reason on why this is needed, it's still a very good tool for softening up Marines and killing them.
> 
> because its had constant nerfs with no other buffs to it, making it a shit tool against marines with any IQ since it takes so long to recharge

Not really, even the best of players will always attempt to avoid a screech, it's not something you can simply dodge.

**Comment by Swagile** [comment]
> 
> 
> Too low of a cd for a screen wide disruption that also goes through walls.

not really, its weak when it goes through walls, and its a light stun at best

> 
> 
> > > I still don't see a reason on why this is needed, it's still a very good tool for softening up Marines and killing them.
> > 
> > 
> > because its had constant nerfs with no other buffs to it, making it a shit tool against marines with any IQ since it takes so long to recharge
> 
> Not really, even the best of players will always attempt to avoid a screech, it's not something you can simply dodge.

yeah and the effect isn't even that good compared to most abilities because of the low CD; at best it halts a push for a few seconds, at worst it takes out a group who are already heavily wounded and woulda died in a few minutes anyway. it needs a lower CD to help deal with unga swarms and aim mode; it won't completely counter both but it will give xenos more options to deal with it

**Comment by SplinterGP** [comment]
I mean it stops marines from running by reducing their stamina

**Comment by InterroLouis** [comment]
It's supposed to be weak when it goes through walls.

**Comment by Swagile** [comment]
> 
> 
> I mean it stops marines from running by reducing their stamina, its not a tool to stop a push but to push and kill

Drops marines to the floor (which drops their guns), disables aimmode, and makes them unable to run very well. All of these are needed to stop a coordinated push to do some damage then retreat; otherwise marines are able to do free damage while xenos do little in return.

Thats what I meant when I said this would help setup more team plays against good marines; right now there isn't much counter to marines with IQ (since abilities like screech are on such high CD's with shit effects due to their nerfs). Thats the point of this PR; giving xenos more reliable tools.

**Comment by TiviPlus** [comment]
Why is this buff needed

**Comment by Swagile** [comment]
> 
> 
> Why is this buff needed

read the PR?

constant nerfs to queen screech while CD stays the same

its long stun removed (long ago), now its stam crit removed (recent), yet the CD remains the same

can at least TM it to test if this is too OP or not, much like the TM of queen charge / tailswipe

or we can just keep gimping queen's only stun and then outright remove it

**Comment by BraveMole** [comment]
> > Why is this buff needed
> 
> read the PR?
> 
> constant nerfs to queen screech while CD stays the same
> 
> its long stun removed (long ago), now its stam crit removed (recent), yet the CD remains the same
> 
> can at least TM it to test if this is too OP or not, much like the TM of queen charge / tailswipe
> 
> or we can just keep gimping queen's only stun and then outright remove it

Something being nerfed in the past doesn't mean it has to be buffed? You've stated no reason to buff it

**Comment by Swagile** [comment]
> 
> 
> > > Why is this buff needed
> > 
> > 
> > read the PR?
> > constant nerfs to queen screech while CD stays the same
> > its long stun removed (long ago), now its stam crit removed (recent), yet the CD remains the same
> > can at least TM it to test if this is too OP or not, much like the TM of queen charge / tailswipe
> > or we can just keep gimping queen's only stun and then outright remove it
> 
> Something being nerfed in the past doesn't mean it has to be buffed? You've stated no reason to buff it

to help create more teamplay against huge ungaswarm tactics, since queen's screech is the only reliable AoE stun xenos currently have. it used to be more potent in return for its high CD, but with its constant nerfs, its not as scary anymore to marines that know what they are doing. lowering CD allows for stopping huge aim mode / shotgun pushes from being as scary

**Comment by Hydrinator** [comment]
Xenos already have a ridiculous amounts of stuns & disarms and it is not solely the queens job to stop "unga balls". Utilize mazes to physically force them to split. Boiler spam also works wonders.

And if you're so inclined for aoe stuns, Praetorian sprays still exist and got buffed recently. Furthermore, if the CD is lowered so drastically, "good marines" will start to bring earmuffs into their kits when doing offensive pushes.

**Comment by Smudged** [comment]
> Xenos already have a ridiculous amounts of stuns & disarms and it is not solely the queens job to stop "unga balls". Utilize mazes to physically force them to split. Boiler spam also works wonders.
> 
> And if you're so inclined for aoe stuns, Praetorian sprays still exist and got buffed recently. Furthermore, if the CD is lowered so drastically, "good marines" will start to bring earmuffs into their kits when doing offensive pushes.

that praetorian "buff" actually made it so pratoerians couldn't spit around corners, and also you can still walk into the cone to skip it

**Comment by Ace2142** [comment]
Maybe a middle ground , like 80 or 75s? A screech per minute sounds like an hysterical queeny.

**Comment by Hydrinator** [comment]
> that praetorian "buff" actually made it so pratoerians couldn't spit around corners, and also you can still walk into the cone to skip it

The spit around corners meme was quite clearly a bug, as is the walk into it shit that already has a PR to get fixed.

**Comment by Swagile** [comment]
> 
> 
> Xenos already have a ridiculous amounts of stuns & disarms and it is not solely the queens job to stop "unga balls". Utilize mazes to physically force them to split. Boiler spam also works wonders.
> 
> And if you're so inclined for aoe stuns, Praetorian sprays still exist and got buffed recently. Furthermore, if the CD is lowered so drastically, "good marines" will start to bring earmuffs into their kits when doing offensive pushes.

all of these are really situational based and have huge drawbacks; ones that marines can punish easily. there is a reason queen screech is used to setup big plays; because it doesn't have as MUCH drawbacks

let me go down the lost of all these "ridiculous amount of disarms", shall we?

Shrike: Punt and Force. Force is arguably one of the best stuns and relocation abilities xenos have as it can be used on multiple targets, but its weakness is having to run past marines (who might shotgun you as shrike is not immune to stuns) and in big unga balls this is death as shrike can't take that much punishment. Punt is the same but faster CD and only singular use, and only really good combo'd with force.

Warrior: Same deal as Shrike; to juggle someone back you have to lunge infront of multiple marines and sit there for a second or two then use the ability, and your still a bit slow after the ability; this is, again, a death sentence against half decent marines in a big push.

Prae: The AoE stun doesn't always work, and it slows the Prae to a halt, making it an easy target to run down even when praes use warding at Elder. Only really good because you see it combo'd with queen screech.

Defiler: A single TX slug, revolver, or T35 slug stops you, and flechette shreds you because defiler has low HP compared to other T3's, so if your caught by a single PB then chased by a shotgun flech, revolver, or a regular rifle unga while they shoot into the smoke you are most likely dead. Worse still if a SG supports the push; smoking a unga ball is just not viable without a screech in unless you want to play with the luck roulette and hope you don't get burst damaged by SG / aim mode weapons or rushed by shotties.

Rav: Lol.

Boiler: Useless till Ancient, basically. And only really there to obscure vision at best, because you can run through neuro with a hypervene injector set to 3u, or kelotane if acid cloud and not suffer that much if any damage. Only direct hits are scary but those are rare after the first shot because most marines know your there and watch for blobs.

can't be bothered to list more, but you get the gist of it; all of them are incredibly situational AoE tools that have medium to high drawbacks that essentially require queen screech to combo with them in order to not instantly die to marines with any level of IQ

thats the only reason queen screech is feared; its ability to be combo'd with other abilities. screech itself has been constantly nerfed that it really isn't that big of a deal.

**Comment by Swagile** [comment]
well after playing the game for a couple of days and seeing the absolute state of some of the shit xenos pull, im just gunna close this.

no point buffing xenos as now they just abuse surr's neuro buffs to make the game absolutely unfun, and buffing queen screech in this meta would make that even worse.

i want this buff but its just not gunna go through anyway

**Pull request closed without merging**
