### PR TITLE
Infinite Ammo for Operations Vendor in Req

### PR DESCRIPTION
**Pull request by FosterGrime-Heymynameslouie**
## About The Pull Request

essentially #11950 but on a new pr, I refformated my PC and I have no idea how to make edits on this branch no more

"Infinite Ammo for Operations Vendor in Req. This PR aims for carpel tunnel rates among RO players to go down.

I understand that specailized ammo boxes hold more ammo than ammo boxes, but granted that the RO has a stack of cardboard at req at the start of the round and can make more, they virtually have infinite specialized ammo boxes. I also do not believe that balancing out usage through obscurity is a good idea.

To the people who vend all ammo during prep then shove them on a nearby crate so they can drag them to alamo, their is an ammo crate that does the loading alamo with ammo process nearby most reqs.

Also hurray for my very first PR. Id like to thank lumi, a potted plant and being ignored in dev chat that bought me here today!

This PR is meant to be the sister PR of: https://github.com/tgstation/TerraGov-Marine-Corps/pull/11951"
## Why It's Good For The Game

I believe spam clicking on weapons vendor for ammo as RO whenever someone asks for ammo should be avoided as much as possible, this PR aims to streamline the supply process while also cutting down on carpel tunnel development rates.
## Changelog
:cl:
qol: infinite pre filled ammo boxes in op vendor
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
just buy surplus ammo box
skill issue + salt pr + no xitches + powercreep + reqpilled

**Comment by FIXTHERADBOXPLEASE** [comment]
Powercreeps the Surplus Ammo req purchase out of existence.

**Comment by Xander3359** [comment]
Hey FYI, I think this is a good PR, but it won't get looked at until it passes checks. The fault is not on your end, all you have to do to pass checks is to pull from master.

**Comment by FosterGrime-Heymynameslouie** [comment]
bless yo kuro

**Comment by FosterGrime-Heymynameslouie** [comment]
> Hey FYI, I think this is a good PR, but it won't get looked at until it passes checks. The fault is not on your end, all you have to do to pass checks is to pull from master.

done and done

**Pull request merged**
