### PR TITLE
Prevent restocking of infinite supplies

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Restocking an item with an infinite supply will no longer make the amount of item increment.

This does not fix the stock showing even for negative stocks, as it is working fine on local serb?

## Changelog
:cl:
fix: No longer can break infinite supplies by restocking
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
Does this mean I can vend a billion things into a pile that crashes someone if they left-click, and can't be easily fixed cause it's on a vendor tile?

**Review by TiviPlus — APPROVED** [review]

**Comment by Losenis** [comment]
That'd probably require admeme roomba regardless given restocking a billion things one by one would be nuts in the first place

**Comment by BraveMole** [comment]
> Does this mean I can vend a billion things into a pile that crashes someone if they left-click, and can't be easily fixed cause it's on a vendor tile?

You could always do that? 
There was 10k ammo in the vendor, if you manage to buy 2 per seconds, it's 1h20 of clicking lel

**Comment by jroinc** [comment]
This appears to prevent all restocking.

**Comment by Losenis** [comment]
This kills medvendor restocking, which is kind of an immense blow to medical and healing

**Pull request merged**
