### PR TITLE
Rocinante Base

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
Please merge this pr before tming this for less suffering since platforms are rather common on this map
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10318
converted to draft since not done
new map,a research and military base of the som med pop
thanks to cm devs for platform, crystal, surveyor, measurer, and the 64x32 science machine sprites

## Why It's Good For The Game
more cool maps so people dont get bored 

## Changelog
:cl:
add: Rocinante Base
fix: horizontal container sprite having off pixels
imageadd: rocinante base sign
imageadd: som cas ship
imageadd: som mech prop
imageadd: rock platform
imageadd: icy rock platform
imageadd: purple platform
imageadd: metal platform
imageadd: crystals
imageadd: crystal mounds
imageadd: crystal crates
imageadd: science machines
imageadd: surveyor
imageadd: measurer
imageadd: bed sheets to bunkbeds
/:cl:

wip image
e

### CODE REVIEW

**Comment by Lumipharon** [comment]
Awesome

**Comment by Al-1ce** [comment]
Looks good. A few parallels to LV but that's to be expected. I dislike how small Engineering is though - being a majorly contested spot on all maps it shouldn't be remotely this small.
image
I'd suggest converting the cargo area into Engineering, but aside from that this seems to be very well done.

**Comment by Licherr** [comment]
finally some good fucking food

**Comment by RipGrayson** [comment]
Hey, I'm just posting here to say I haven't forgotten this map, it's just large and I've been busy lately. I'll try to make a point of leaving a review in less than 24 hours.

**Comment by RipGrayson** [comment]
>less than 24 hours.

Well here we are 96 hours later but anyway...

The generator room should be enlarged a little, also wouldn't hurt to add a door on the eastern side.
engi2


The lockdown buttons initialize to a certain tile position based on their direction. Both of these buttons are inside rock and should be probably rotated to be flush with the wall. 
button1
button2

NanoMeds should also hang off the wall like APCs
nanomed1

tun1

There are a lot of one small buildings here with one tile passages, as a general rule of thumb when building for larger map populations you should consolidate, which means a few large complexes are better than a bunch of cramped disconnected buildings.
build1
build3
build2


Space tiles here
spacetiles

Two tile straights are bad in general, they promote stalemates and the longer the straight the worse the potential stalemate.
Yes, I know that you could break the windows to make it less constricted but we have to assume whoever is getting backed into the corridor won't have the time.
curtain1
tun2

"But Gray", I hear you say, "Doesn't Prison have tons of narrow straights?, What's the difference?"
First of all Prison is currently considered to be a bad map and secondly whoever designed it usually gives little outlet rooms whenever they wanted to do straight corridors.
pr1
  
Also try not to do this with long straight bridges that are only two tiles wide.
bridge1 

Alright time for some more mapping theory
bridge2
Both ends of a bridge spanning water should either 
A. Have a defensible position some distance away (like the xenos have a cave north on LV and marines have Hydro)
B. Have a large open area on one end to allow marines or xenos to setup defenses.

The buildings here are too small for A. and the area is too crowded for B. 
bridge3
bridge4

Honestly turning this whole area into a (potentially flooded) security complex might help a lot, provided players have enough space to move around in.
bridge5

I'm somewhat worried about attrition here, the more roundabouts (circular cave rock groups) in cave territory the more opportunity the hive has to break contact and avoid being crushed or to initiate a flanking maneuver . Typically this leads to a lot more delays and attrition for marine forces.
A really bad case would be something like old LV where xenos would routinely dodge around cave formations for 3+ hours.
caves1

**Comment by RipGrayson** [comment]
I have some doubts here but I think this map deserves a TM first to collect feedback.

**Comment by henriquekill9576** [comment]
bugs so far: Xenos are spawning shipside and the button won't open the shutters

**Comment by Al-1ce** [comment]
### Looks good, but..

1. There is an excessive amount of turf that cannot be weeded. Namely, the unremovable snow and grass. 
This normally wouldn't be much of a problem, but the sheer excess you can find here is abominable. You can't take more than a couple steps before finding six or seven of these tiles that can't be weeded. This combined with the tight, long and open corridors makes it hell for attempting to build any sort of defenses before the marines invade.

### A comparison..
This is the way LV-246 is designed. While there _are_ unweedable sections in the outskirts, the main road is still easy able to be mazed. This encourages xenomorphs to build and defend.
image

Whereas, this is the way Polar Colony is designed. Much of the narrow passageway is covered in unweedable turfs, with a plethora of awkward turns that make it feel pointless to try and build up, maze, or defend. This **_heavily_** discourages xenomorphs. 
### Example A
image

This really wouldn't be that big of an issue if this **_wasn't the way the entire map is designed,_** but it is. Each turn leads to another narrow, undefendable and unweedable corridor that somehow has _EVEN MORE_ dead-ends than the caves. You will seldom find a section of this map, however small that feels marginally defendable, or isn't a narrow corridor waiting to be turned into a firing line. Don't get me wrong, the map _looks_ great, but the overall game design seems to be completely lacking. 

### Example B
image
I really, _really_ can't stress enough how damaging this is to xenomorph gameplay. There are far more unweedable and undestroyable turfs than there are not. It feels hopeless attempting to defend any piece of this map because of this. The design here, while looking pretty cool, is not conducive to good gameplay. It just isn't. The river, the grass tiles, - it all combines into a massive shitstorm of frankly bad map design that feels awkward and unfair for both sides, marine and xenomorph alike.

image
I'd like to make another comparison to LV-246 to give some perspective on what I'm going on about here. While there is water, or otherwise unbuildable turf, the surrounding area is completely weedable. This is prudent, and what Polar Colony lacks entirely.

In the current state, this map feels more like the incest baby of LV246 and Ice Colony than it does something unique or interesting itself. I didn't bother touching on the caves since they're at least one of the few somewhat well-designed things here.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
I'm afraid my initial impressions of this map were correct. The entire colony section needs to be redone, I'm entirely open to providing specifics in Discord as to what needs done.

If anyone wants to disagree with me I'm open to hearing it, but my actual experience with the way the map flows hasn't been good.

**Comment by 2kajowsmol** [comment]
Yo. I'm just a marine player so this is just my perspective of having played it twice, but like most of the map is just way too cramped. No, I don't have any specific examples and I ain't gonna go find any. That's just my two cents.

**Comment by MiniMeatwad** [comment]
You should try adding some landmarks like resin doors throughout the caves, resin walls near dead ends in the caves, and there's light sticks as in ice colony for paths you want to be taken, this should help people get used to the map.

**Comment by RipGrayson** [comment]
This PR isn't stale, tye is working on revamping the colony and it's just taking a while.

**Pull request closed without merging**
