### PR TITLE
Pistol Sunder Nerf

### PR DESCRIPTION
**Pull request by InterroLouis**
## About The Pull Request

Here's your akimbo nerf. Reason it's so strong is because of the massive sunder wrecking xeno armor. So here. A big fat sunder nerf. Squash bullets are keeping the 2 sunder, TP-14 is reduced to 0.8 from 2, and TP-23 is 1.2 from 2 in keeping with having it at the same values per magazine as TP-14. 

## Why It's Good For The Game

Akimbo pistols won't shred armor as much anymore. 

## Changelog
:cl:
balance: TP-14 Sunder reduced. 
balance: TP-23 Sunder reduced. 
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
Why not nerfing akimbo pistol, like someone david is trying to do? No need to nerf single pistol, it's already balanced

**Comment by RenGusta** [comment]
If you think 42 sunder a mag and like 20+ a second is balanced per pistol, I don't know what's up.

**Comment by spookydonut** [comment]
image

**Comment by SplinterGP** [comment]
give the Tp14 just 1 and the tp23 you can leave as is in my opinion, it fires considerably slower

**Comment by TiviPlus** [comment]
This does not fix akimbo it just nerfs pistols

**Comment by InterroLouis** [comment]
I disagree, and I'm not backing down on this, I don't care if the other ones get done too. Pistols have too much sunder.

**Comment by SplinterGP** [comment]
> 
> 
> This does not fix akimbo it just nerfs pistols

pistols are good overall not only akimbo

**Comment by RenGusta** [comment]
Not realising the main reason pistol akimbo is so fucking strong is the massive sunder output 💯

**Pull request closed without merging**
