### PR TITLE
removes xeno probing

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request

title. barring a true Researcher Rework, i've opted to just removing xeno probing dead corpses. you can still play gacha with digsite materials.

changes out the sprite for the xeno analyzer with the implant case/pad sprite, since the analyzer is still used in interactions with newt (why were we hitting newt with a saw); additionally puts a limit on the number of analyzers vendable from the nanomed because it's serving a different purpose now and 12 people fighting to have newt follow *them* seems like it'd be a headache.

**THE MATHS**
totally optional and not mandatory to keep, but given that this whole thing would provide a nerf to marine incomes, i've opted to also go ahead and re-balance the point values per xeno corpse sold to be a bit more generous, while still (roughly) preserving the ratios from #14118. stuff i took into account for this is namely that each corpse probed guarantees the generation of a 50-credit coin at minimum, and that pushing t4s to 1200 makes them equivalent to some of the really critical req gear. i didn't change the t1 value for reasons of #ratios.

T1 - 150 points (no change)
T2 - 350 points (+50)
T3 - 600 points (+100) [includes shrike]
T4 - 1100 points (+100 points)

ratios
image

## Why It's Good For The Game

people seem to think this assists in req snowballing and i much prefer to fix up this aspect of the game versus trying to power scale either team in response to the req snowball

## Changelog

:cl:
add: removes xeno probing
balance: point adjustments to xeno caste values for req exports
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Well, wouldn't it be better reworking and removing in the same pr?

**Comment by Wisemonster** [comment]
One thing this pr would do is encourage the researcher to actually go out and search for the dig spots, rather than hug the tad and wait for injured marines and dead xenos to come to them.

**Comment by SimplySmiley123** [comment]
> One thing this pr would do is encourage the researcher to actually go out and search for the dig spots, rather than hug the tad and wait for injured marines and dead xenos to come to them.

Thing is that searching for those dig spots isn't worth all the risk involved of getting bumrushed by a random ravager for a guaranteed free kill.
Unless the unga ball is moving through a dig spot or settles down right next to it, or when xenomorphs go braindead and are getting wiped (at which point req does not matter anymore, you won at this point), you're better of not going off to the dig spots.

**Comment by SimplySmiley123** [comment]
> > One thing this pr would do is encourage the researcher to actually go out and search for the dig spots, rather than hug the tad and wait for injured marines and dead xenos to come to them.
> 
> Thing is that searching for those dig spots isn't worth all the risk involved of getting bumrushed by a random ravager for a guaranteed free kill. Unless the unga ball is moving through a dig spot or settles down right next to it, or when xenomorphs go braindead and are getting wiped (at which point req does not matter anymore, you won at this point), you're better of not going off to the dig spots. Which doesn't happen a lot in the former cases and in the latter it genuinely doesn't matter if the researcher is looking for dig sites, proving corpses or if there's any point generation happening.

**Comment by coldironwarrior** [comment]
> Well, wouldn't it be better reworking and removing in the same pr?

you're welcome to try it instead if you have the time and the talent to do it, which i, so sadly, don't. so this is the best you get from me.

**Comment by Loafin34** [comment]
The problem with these fun "do or die" digsite gimmicks is that a singular t1 will fuck you over so badly as a medical researcher on your own that most people are gonna stop playing. It's like if PO had a change that made them unable to shoot inside roofed buildings, it would just drop all and any CAS and force POs into one funnel of how to "play" the game. If you feel like req snowballing happens a ton, nerf xenomorph analyzer, but buff digsites to the point that it's possible to even excavate them. Going through xeno territory without the ungaball is more torturous than feeding reqtorio. Especially since the changes to the tankiness of marines have been merged.

**Comment by SimplySmiley123** [comment]
> The problem with these fun "do or die" digsite gimmicks is that a singular t1 will fuck you over so badly as a medical researcher on your own that most people are gonna stop playing. It's like if PO had a change that made them unable to shoot inside roofed buildings, it would just drop all and any CAS and force POs into one funnel of how to "play" the game. If you feel like req snowballing happens a ton, nerf xenomorph analyzer, but buff digsites to the point that it's possible to even excavate them. Going through xeno territory without the ungaball is more torturous than feeding reqtorio. Especially since the changes to the tankiness of marines have been merged.

This and frankly you genuinely don't make a difference via digsites most of the time.
You either die or at best get 1 or 2 done if xeno team ain't loosing horribly, or the xeno team is wiping without your help and getting the digsites doesn't matter anymore.

**Comment by yyzsong** [comment]
Based pr. The initial researcher pr was a """""Content"""" PR that did nothing but serve as blatant powercreep. I've had my issues with it for a while and I'm surprised it took this long for someone to actually make a PR about it. Speedmerge.

**Review by Kuro020 — APPROVED** [review]

**Review by ivanmixo — APPROVED** [review]

**Comment by SimplySmiley123** [comment]
What the hell..........

**Comment by chizzy376** [comment]
This codebase is a joke and you are the circus

**Pull request merged**
