### PR TITLE
XenoSpit to 8

### PR DESCRIPTION
**Pull request by Hughgent**
## About The Pull Request

EOL changes are evil.

## Why It's Good For The Game
Xenos don't need to be perfectly on tile accurate, they can just click in line with their target.

## Changelog
:cl:
tweak: Xeno Spit is range based now. you can click in line with your target.
/:cl:

### CODE REVIEW

**Comment by factoryman942** [comment]
still a bandaid fix but it's better without eol changes i guess

**Comment by Spyroshark** [comment]
spit ending where you click is not a fun change anyway, imo this is better

**Comment by Rohesie** [comment]
Deprecated by #3079 ?

**Comment by Hughgent** [comment]
If ya say so.

**Pull request closed without merging**
