### PR TITLE
Adds a skirt to the Synth vendor.

### PR DESCRIPTION
**Pull request by BeloneX**
## About The Pull Request

Adds the MP skirt as a item to the Synth vendor under uniforms.

## Why It's Good For The Game

More customization, why not?

https://cdn.discordapp.com/attachments/500801682058379265/789336901097881620/unknown.png

## Changelog
:cl:
add: Added a MP skirt to the synth vendor.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
stuff like this is how servers become nrp meme leet fests, it goes under the guise of "customization" and "it won't hurt anything" but only people it appeals to is people who think its funny or think its funny
deny this

**Comment by Pariah919** [comment]
image
case in point

**Comment by BeloneX** [comment]
> stuff like this is how servers become nrp meme leet fests, it goes under the guise of "customization" and "it won't hurt anything" but only people it appeals to is people who think its funny or think its funny, and generally detracts from the game
> deny this

Wew, calm down there crusader.

**Comment by Kuro-ai** [comment]
Put a pic of the sprite up on the PR

**Comment by BeloneX** [comment]
> Put a pic of the sprite up on the PR

unknown-1

**Comment by TheBimmer231** [comment]
No.

**Comment by TiviPlus** [comment]
The sprite director and it's consequences have been a disaster for the tgmc

**Pull request closed without merging**
