### PR TITLE
Arrowhead Rebalance

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
~~Removes arrowhead from Marine venders and moves it to req.~~ 
~~Increases arrowhead slowdown to 0.3 from 0.2.~~
**Arrowhead now has negative armor and has an increased recharge rate of 10.**

## Why It's Good For The Game
Because let's be serious, there are no pronounced downsides to arrowhead aside from lacking the exclusive benefits of other modules. In theory, it's balanced and "fair". In reality, the module is overpowered in the fact that xenos **cannot** do enough damage to not only overload the shield but also **injure the marine using said shield** before they're forced to retreat. It also does not help that there really is, *nothing* stopping you from picking it outside of personal preference. You can slot the module into any build and you would arguably be fine because **you have 40 more effective health. You are the guy xenos DO NOT want to deal with.**

The armor values aren't final and are subject to change. 

## Changelog
:cl:
balance: Arrowhead now has negative armor.
balance: Increases arrowhead recharge to 10 from 8. 
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
I believe this has already been talked about here
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10535
image

**Comment by KrabSpider** [comment]
> edit: but I do agree now that it has to receive some nerf because its wayy too easy to use, annoying to counter (for hit and run xenos), but just it being banished to req seems too much.

I

**Comment by Losenis** [comment]
Wouldn't a more interesting way to nerf it be adding negative armor to it like an opposite tyr, so that even though you can tank one or two slashes you'll be worse off in long engagements? It'd have it as an interesting choice for a pure backliner specialization that'd be punished for frontlining or getting ganked.

**Comment by KrabSpider** [comment]
> Wouldn't a more interesting way to nerf it be adding negative armor to it like an opposite tyr, so that even though you can tank one or two slashes you'll be worse off in long engagements? It'd have it as an interesting choice for a pure backliner specialization that'd be punished for frontlining or getting ganked.

🙂 Y'all are killing me. Sure.

**Comment by FosterGrime-Heymynameslouie** [comment]
> > Wouldn't a more interesting way to nerf it be adding negative armor to it like an opposite tyr, so that even though you can tank one or two slashes you'll be worse off in long engagements? It'd have it as an interesting choice for a pure backliner specialization that'd be punished for frontlining or getting ganked.
> 
> 🙂 Y'all are killing me. Sure.

truly he has taken the mantle of the ultimate sacrifice to his mental health (coding)
Godspeed

**Comment by Al-1ce** [comment]
> Wouldn't a more interesting way to nerf it be adding negative armor to it like an opposite tyr, so that even though you can tank one or two slashes you'll be worse off in long engagements? It'd have it as an interesting choice for a pure backliner specialization that'd be punished for frontlining or getting ganked.


This sounds like a perfect downside.

**Comment by Liznerd** [comment]
Maybe the req part was too far, but i agree on it being the supreme choice hands down with no reason to not use it, a bit of slow should do be enough, otherwise cheap attacks like spits or runner / hunter pounces would be incredibly good

**Review by BraveMole — CHANGES_REQUESTED** [review]
Was this tested ?

**Comment by KrabSpider** [comment]
> Was this tested ?

 **Surface-level** testing but yes.

**Pull request merged**
