### PR TITLE
adds RU shotgun, again

### PR DESCRIPTION
**Pull request by SomrNetwork**
## About The Pull Request
refer to the title
## Why It's Good For The Game
I don't really play on RU, I haven't seen this shotgun before but judging on playtests. It MIGHT be a good mediator
	fire_delay = 3 //one shot every 0.3 seconds.
	accuracy_mult = 1.05
	scatter = 3
	damage_mult = 0.4  //60% less damage.
	recoil = 0.5
	wield_delay = 0.6 SECONDS
	aim_slowdown = 0.2
might literally just be pepperball with damage
## Changelog
:cl:
add:ru shotgun
soundadd:shotgun
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
that cl sucks

**Comment by SomrNetwork** [comment]
> that cl sucks

suffer

**Comment by ivanmixo** [comment]
I could also just close the PR if you don't make the PR body better. Some random permabanned person's opinion doesn't really answer why it's good for the game.

**Comment by AusarAtkin** [comment]
Why wouldn't you just fill it with your own opinion on the PR, and then feel free to add how cvs co-authored it. Its that easy.

**Comment by ivanmixo** [comment]
CL still sucks

**Comment by Kuro020** [comment]
image

**Pull request closed without merging**
