### PR TITLE
Adds the maid uniform to the clothing vendor.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
PR'D ON BEHALF OF @KillerOrcaCora 
Adds the maid uniform:
image
image
image
image
image
image

## Why It's Good For The Game
More clothing options.

## Changelog

:cl:
add: Maid uniform is available in the clothing vendor.
imageadd: Adds maid uniform sprites.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
oh_hell_no-3762791409

**Comment by lKiseki** [comment]
Don't do it. I don't trust our admins to keep it in check.

**Review by Kuro020 — APPROVED** [review]
the funny cat

**Comment by bowlofcereal** [comment]
Do I need to stress the problem here or is it too late and the world has gone upside down? What the fuck is this?

**Comment by KillerOrcaCora** [comment]
Touhou 600 1471112

**Comment by XElectricX** [comment]
Speed merge.

**Comment by Kuro020** [comment]
The cabal has instructed me to destroy this

**Comment by Naaanii** [comment]
Didn't even TM it for the 1st smh smh

**Pull request closed without merging**
