### PR TITLE
Nerfs queen speed

### PR DESCRIPTION
**Pull request by Kuro-ai**
## About The Pull Request

Nerfs queen speed

## Why It's Good For The Game

Queen is fast as fuck boi,and it honestly looks silly and is too strong,so this is a nerf to her speed,she'll still be faster than before rework but not as much
## Changelog
:cl:
balance: nerfed queen speed
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Isy232** [comment]
Yeah, I kinda agree with you here, I think maybe this will make it a bit too slow but yakety sax queen running away forever is annoying to watch or play against.

Perhaps other things can be buffed in the future if after this queen is deemed weak.

**Comment by Rohesie** [comment]
What about the Shrike?

**Comment by Kuro-ai** [comment]
> What about the Shrike?

idk,nobody in balance said anything about shrike when I was doing this,also it needs to be another pr,atomization and all that

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-7). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
