### PR TITLE
Adds a skill lock to pill bottles.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds a skill lock to pill bottles.
## Why It's Good For The Game
Marines are not meant to use pill bottles, they are meant for medics and doctors.
This prevents marines from using them.
## Changelog
:cl:
balance: Those with no med skill can no longer open pill bottles.
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
NOOOO WHAT HAVE YOU DONEEEEEEEEEEEEEEE

**Comment by Xander3359** [comment]
> NOOOO WHAT HAVE YOU DONEEEEEEEEEEEEEEE

Nerf contributor upset about nerfs?

**Comment by AgentMA1** [comment]
best PR i've ever seen speedmerge

**Comment by ilikesaying** [comment]
CM

**Comment by EvilMelonTheSecond** [comment]
Finally its time to remove the "no feature hardlocked behind roles like CM lmao" boasting we had going for years. 
Next update we can also add MP.

**Comment by spookydonut** [comment]
lmao

**Pull request closed without merging**
