### PR TITLE
Slightly lower the chance of sectoids being called.

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
They are weird ass aliens. Maybe seeing them basically every game is a bit much ?

## Why It's Good For The Game
Muh immersion.

## Changelog
:cl:
balance: Slightly lowered the pickrate for sectoids ert's
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Just add more ERTs tbh. Completely out of scope, but yeah, there are only 5 ERTs.

**Comment by lbnesquik** [comment]
> Just add more ERTs tbh. Completely out of scope, but yeah, there are only 5 ERTs.

Might just turn on the CLF ngl

**Comment by Al-1ce** [comment]
> > Just add more ERTs tbh. Completely out of scope, but yeah, there are only 5 ERTs.
> Might just turn on the CLF ngl

It's about time we have rogue borg ERT.

**Comment by BraveMole** [comment]
This increase the chance of having PMC, so ew.

Please make another ERT before this, a neutral one, you already have a ton that just need some refreshment on the repo

**Comment by lbnesquik** [comment]
> 
> 
> This increase the chance of having PMC, so ew.
> 
> Please make another ERT before this, a neutral one, you already have a ton that just need some refreshment on the repo

I'll try my hand at this in a bit. Takes longer to make than this PR and i might be out of town for a bit.

**Comment by SplinterGP** [comment]
this is not needed and other ERT's will have more chance of spawning due to this, which might not be desirable

**Pull request closed without merging**
