### PR TITLE
Implements FOOC (faction OOC)

### PR DESCRIPTION
**Pull request by DominikPanic**
Death to brackets

:cl: LaKiller8
FOOC (Faction OOC) has been added.
/:cl:

### CODE REVIEW

**Comment by factoryman942** [comment]
tfw two brands of ooc aren't enough so you need a third one

**Comment by DominikPanic** [comment]
> 
> 
> tfw two brands of ooc aren't enough so you need a third one

Pepsi, Coke, Dr Pepper

**Comment by factoryman942** [comment]
under what circumstances would using fooc be preferable to using looc
and under what circumstances would using looc be preferable to using fooc

**Comment by Rohesie** [comment]
When you need to interject about a recent game mechanics change, for example. Like about the Shrike, without telling all the marines the player is struggling with its mechanics.

**Comment by psykzz** [comment]
I agree 3 is quite a lot, with FOOC, LOOC doesn't make as much sense, i only see it used to talk with others when you die "How much hp did you have left before you got me down?"

**Comment by Spyroshark** [comment]
we already have LOOC. The only servers that use FOOC is highrp servers that have team antags trying to do gimmicks and whatnot together. There's absolutely zero reason to add it here it's just going to be shitpost central and whining about xenos

**Comment by DominikPanic** [comment]
I also disagree with this PR (which is a bit ironic), but I'm picking the lesser of the two evils (FOOC vs brackets in IC chat)

**Comment by psykzz** [comment]
Why do you need one or the other in the first place.

**Comment by DominikPanic** [comment]
I don't want either, It's Rohesie's decision (see #policy for a LOT of reeeing)

**Comment by spookydonut** [comment]
This is a feature PR with a config option, discussions about if the actual server should use it shouldn't influence the fate of this PR.

**Comment by DominikPanic** [comment]
> 
> 
> This is a feature PR with a config option, discussions about if the actual server should use it shouldn't influence the fate of this PR.

I'd rather close it than let a config decide if it gets merged or not. My philosophy here is a little different.

**Comment by Rohesie** [comment]
I'll be closing this PR due to the current rejection.

**Pull request closed without merging**
