### PR TITLE
Unfucks LZ1 ice.

### PR DESCRIPTION
**Pull request by BeloneX**
## About The Pull Request

image

## Why It's Good For The Game

It makes LZ1 on Ice Colony not result in absolutely cancer CBT rounds.

## Changelog
:cl:
tweak: tweaked the area outside of LZ1 ice to be more open.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by TiviPlus** [comment]
image
Red area needs a smoother transition 
Is blue snow or what is that?

**Review by TiviPlus — CHANGES_REQUESTED** [review]
.

**Comment by BeloneX** [comment]
> .

OK, updated.

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-10). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
