### PR TITLE
Makes Quick-Clot Plus craftable again

### PR DESCRIPTION
**Pull request by Franky2025**
## About The Pull Request
Makes Quick-Clot Plus craftable

The recipe for it as follows:
2 part Quick-Clot
2 parts Lemoline
2 parts Iron
## Why It's Good For The Game
The amount of QC+ needed for treatment seems never enough of what is available, the recipe creates 1 unit of QC+ out of 6 units of the recipe. Not enough medics already bother with chems to care anyways.

## Changelog
:cl: Kait
expansion: Added a recipe for QC+, making it craftable. The recipe for 1 unit is: 2 parts Lemo, 2 parts Iron, 2 parts Quick-Clot.
/:cl:

### CODE REVIEW

**Review by BraveMole — CHANGES_REQUESTED** [review]
should us lemoline at the minimum.

**Comment by Losenis** [comment]
Phoron already competes with Peri+ and who even uses lemoline anything anyway

**Comment by Franky2025** [comment]
i thought its better to unite peri+ and qc+ with phoron but yeah lemoline makes more sense + another use for lemo.

**Comment by Losenis** [comment]
Watch it never get crafted until some dunga spends req money on lemoline as fob gets sieged

**Comment by Franky2025** [comment]
also, how do you add comments to the changelog?

**Comment by Franky2025** [comment]
> Watch it never get crafted until some dunga spends req money on lemoline as fob gets sieged
chem is already niche, but with more MD mains such as myself i see people start to utilize them more, maybe it'll slowly become more common. Also if i play MD and we have other MDs then join i go down FOB with my custom mixes and all and feel good about myself

**Comment by Franky2025** [comment]
Oh wait the thing after the expansion is the comment itself oops

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
