### PR TITLE
Punch and Forward charge no longer knock down sentries

### PR DESCRIPTION
**Pull request by Canohaaaaaaa**
## About The Pull Request

Warrior punch no longer knocks down sentries, instead doing X4 its damage like it does on regular machinery.
Defender charge no longer knocks down sentries either.

## Why It's Good For The Game

Sentries have it a bit hard and warriors aren't supposed to shine during sieges but in 1 on 1 combat.
Defender is a T1 and already very good at crowd control, that's too much utility.

## Changelog
:cl:
balance: Warrior : punch no longer knocks down sentries
balance: Defender : forward charge no longer knocks down sentries
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
If a warrior gets close enough to a sentry he quite deaerves it, please marines mains remember to let sentrys behind cades and well safe

**Comment by Canohaaaaaaa** [comment]
Not in my opinion, if the sentry isn't on radial you can still obliterate it with punch for a whopping 92 out of 200 integrity by punching it from behind.

**Comment by Lefunny** [comment]
> Not in my opinion, if the sentry isn't on radial you can still obliterate it with punch for a whopping 92 out of 200 integrity by punching it from behind.

Cades can prevent that as i said before, if the xeno get 1 tile range of it he deserveds that

**Comment by Pill-U** [comment]
This seems like a spite PR.
Why should warrior in particular have this removed, but defenders forward charge or it taking too much damage at once still be able to knock over  turrets?

**Comment by Luxyboo** [comment]
i agree with everyone here so far that a cafe can help if your sentry is knocked down, plus you can pick it up and run if you need to.

**Comment by Canohaaaaaaa** [comment]
This is not a spite PR, you have my word on it.
I was going to remove it from defender too but I first wanted to gather opinions on why warrior in particular deserved such a mechanic.
Once again, the "if a xeno gets in melee of a sentry it deserves to vanish" doesn't feel right to me because it's not something engies get an infinite supply of. They're still incredibly vulnerable if you do manage to get behind them, it will still be a threat to xenos trying to breach but given the xenos behind manage to take it down in a timely fashion (and with 200 hp it's not hard at all) then the breach will be complete. I want taking down sentries to take more thinking and time than simply instantly disabling them with 2 very common castes.
If they're on radial and well defended then tough luck, you're gonna have to bring one of the 2 castes designed to take down sieges, namely boiler and crusher (or even king). Which in my opinion is also fair given that the hive should adapt its composition to the situation at hand.

**Comment by Canohaaaaaaa** [comment]
> This seems like a spite PR. Why should warrior in particular have this removed, but defenders forward charge or it taking too much damage at once still be able to knock over turrets?

You're right, i'm escalating this change to defender aswell.

**Comment by usnpeepoo** [comment]
Warriors are supposed to shine in sieges by getting fishes, punching cades, and the occasional sentry punch. Warriors punching sentries is not common and takes a lot of work (read breaching cades, razor wire, going thru marine and sentry fire, to get into melee range to disable it. Once it is disabled the warrior still has to destroy it or with another xeno which at that point is game over already. This PR is nerfing an not always used mechanic simply because sentries have it hard (they don’t, you can buy them from req lol).

**Comment by usnpeepoo** [comment]
> > Warriors are supposed to </ cut>
> 
> source?

Me. I played warrior.

**Pull request merged**
