### PR TITLE
Removes randomized starting nutrition for Marines/SOM

### PR DESCRIPTION
**Pull request by AzonStarfall**
## About The Pull Request

Eliminates the random hunger system from marine spawning, starting marines and SOM at full nutrition levels.

## Why It's Good For The Game

I don't believe that anyone actually likes dealing with decreased spawning nutrition. It's a hinderance for exactly 20 seconds until you can make it to the marine food vendor and eat two nutrition bars, which is already an obstruction to round-start procedure - something you'll have to do, every single round, adding nothing but tedium.

Low starting nutrition is only noticeable if you _forget_ to manage it, and potentially debilitating if you do. Personally, I don't believe that possibility adds anything positive to the gameplay experience.

## Changelog
:cl:
qol: Marines and SOM no longer have randomized hunger on spawn
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Nutricorp assassins have been sent to your house, please stay where you are.

**Comment by FosterGrime-Heymynameslouie** [comment]
doing the funny by casuing as much distruption as people scramble to eat nutri bars my beloved will now be erased, from existance, forever. this is so sad

speede mergh

**Comment by XSlayer300** [comment]
IMO though, having lower hunger allows to teach new players to pack food or eat food to know that having full nutrition allows you to move faster and to have their blood regenerate faster. But I don't mind the change either way.

**Comment by Losenis** [comment]
Preparing to laugh my arse off at muscle memory making 3/4 of the server fat as fuck after munching two protein bars while already full

>IMO though, having lower hunger allows to teach new players to pack food

MREs are already standard issue. New players would sooner pack everything the thing gave them, and if they skip on that and start starving, that's an actual skill issue.

**Comment by DerpiestBruh** [comment]
soulless pr

**Comment by siegluck** [comment]
I like eating. If you delete starting nutrition, I have to overeating for good bars taste. And overeating is bad for game coz after it I should go to chem and make some lipozine or idk or walking very slow coz overeating. Very bad for game. Eat some bars faster them make some lipozine. And you always can save bars in your loadout. But you can't save lipozine in your loadout. Very bad for game. Pls do not depress fat ass marines like me. Nice to meet you. Have a nice day.

**Comment by MrSerpentarius** [comment]
I am hungry and i want to eat nutrition bars.
Nutrition bars so juicy and tasty when you think about it.
Just imagine slurping up and down a warm nutrition bar as a vendor bigger than you gives you one more and calls you a good boy.
I'm entirely straight. Just have a nutrition bar fetish.

**Comment by AzonStarfall** [comment]
> I am hungry and i want to eat nutrition bars. Nutrition bars so juicy and tasty when you think about it. Just imagine slurping up and down a warm nutrition bar as a vendor bigger than you gives you one more and calls you a good boy. I'm entirely straight. Just have a nutrition bar fetish.

How much is Nutricorp paying you?

**Comment by AzonStarfall** [comment]
> 

Why not remove the respawned bars as well? The exclusively exist to mediate the low hunger on spawning, and with this added they're no longer necessary. Keeping them around only exists to keep roundstart clutter.

**Pull request merged**
