### PR TITLE
Changes to LV LZ's, around of LZ's and some other parts

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request

Changes some quite few stuff on LV, mostly on LZ and other few stuff around the map like river and all, most of it has been made by Shiryu but i've editted a bit  to my liking(mostly LZ1)

if you want to see map go on checks and mapdiffbot

## Why It's Good For The Game
I think LV needs a few changes mostly a bit to how it used to be+ how it is now, hopefully this makes LZ2 more siegeable and less of a safe pick and LZ1 more picked

## Changelog
:cl: Shiryu, SplinterGP
balance: LV LZ's have been reworked all around.
balance: LV Rivers now has more bridges
/:cl:

### CODE REVIEW

**Comment by fernandos13** [comment]
can we get a print?

**Comment by Alterist** [comment]
so both LZ1 and LZ2 is bad now, ok

**Comment by Alterist** [comment]
after
also here

**Comment by TheOneAndMightyRed** [comment]
In all, i think LZ2 is getting more viable than how it was before.
LZ2 has a bit less to defend south eastish and more to defend north which looks good to me, but you just made LZ1 not a viable option anymore since you actually have to defend all 4 sides all the time. Too many places to defend against xenos at LZ1 that not even 4 turrets can cover. One random drone can just scoot by and melt at least one defense line if noone is looking for like 5 seconds. This is gonna be desert outpost LZ all over again.

[Please](https://i.imgur.com/TpVaKZ1.png)
[In the walls](https://i.imgur.com/35UB710.png)
[console area not over console and random effect/elevator](https://i.imgur.com/ZJGzLoV.png)

Can ya ples fix the wires, atmospipes and the random floating APC?

Also i just discovered [this](https://i.imgur.com/dWNsGVt.png) as well you could also fix.


Also APC NW of LZ2 is missing a wire under the double door.

**Comment by Swagile** [comment]
yeah this is just making LV an even worse map

on the bright side of this gets merged no marine will care if command turns it into a meme op like a pod op, or tad op, cause the LZ's are terrible so landing on them is an instant loss unless xenos are really bad

**Comment by Alterist** [comment]
The wires and pipes might be fixed by the recent pr, update to that and check

**Comment by Glcbitj** [comment]
So we're either back to LZ1 FoB Box or just doing Meme Ops with Tadpole/Drop Pods on LV rounds, nice.

**Comment by SplinterGP** [comment]
> 
> 
> In all, i think LZ2 is getting more viable than how it was before.
> LZ2 has a bit less to defend south eastish and more to defend north which looks good to me, but you just made LZ1 not a viable option anymore since you actually have to defend all 4 sides all the time. Too many places to defend against xenos at LZ1 that not even 4 turrets can cover. One random drone can just scoot by and melt at least one defense line if noone is looking for like 5 seconds. This is gonna be desert outpost LZ all over again.
> 
> [Please](https://i.imgur.com/TpVaKZ1.png)
> [In the walls](https://i.imgur.com/35UB710.png)
> [console area not over console and random effect/elevator](https://i.imgur.com/ZJGzLoV.png)
> [Line up the sand to indicate doors](https://i.imgur.com/Bo7Mtao.png)
> 
> Can ya ples fix the wires, atmospipes and the random floating APC?
> 
> Also i just discovered [this](https://i.imgur.com/dWNsGVt.png) as well you could also fix.
> 
> Also APC NW of LZ2 is missing a wire under the double door.

or make a smaller FOB, the open area is a good thing for marines if you consider only a few parts of outside the LZ has weedable areas

**Comment by Chaznoodles** [comment]
Remember and get webmap updated if this goes through

**Comment by davidchan13** [comment]
This might be one of the worst remaps I've ever seen. LZ2 in particular emphasizes all of the problems.
Grass is everywhere around the LZ preventing marines from spreading out with cades on those routes as well as xenos from making weeds and traps to the west and south.
There is clear lines of sight less than 18 tiles from north LZ doors to the caves. Marines can not only snipe across the river with impunity, they can do it from the safety of the LZ.
Why even have metal walls on the north east corner of the LZ when you have dense jungle walls under the shutters? Xenos can't even breach through the room unless an engineer does a dumb and clears the dense jungle with cutters.

If your intention was to make LZ2 a worse pick you failed, xenos have a hard enough time getting foothold to the north and marines can just charge across the river or snipe xenos that try, not to mention just putting an HSG on the eastern north door to punish xenos for using the river. If marine have their shit together and pick LZ2 it's an immediate cave fight.

**Comment by mrhugo13** [comment]
I'm gonna be honest, LZ1 does not look like it will achieve your goal of having it more oftenly picked here, unless you do what any person would now with this:

firefox_2021-04-19_18-35-05

Lock down the southern and eastern parts of the alamo and have a bit of FOB around western part where everything will be concentrated, as it requires way too much to keep all other exits checked, i know this because the last PR which changed the LZ's on LV624 made it impossible to use LZ1 because of how easily the xenos could get a breach because nobody could possibly keep everything in check, mind you that this will be even harder now that wraiths are a thing and can just teleport in and slash any turrets locking down the area as nobody will be around to notice them.

If i were to have any recommendations, it would be to scrap the outer parts (outside of that northern fence) and move one of the previous parts inwards as to make it more interesting and which i believe would help you out in getting your goal of having LZ1 safer than LZ2 while making it so that LZ1 isn't gonna be super-bunkered, like this:

firefox_2021-04-19_18-41-35

Maybe not directly like that but work somewhere along those lines as, once again, i do believe this would get closer to what you wish to achieve.

**Comment by SplinterGP** [comment]
too much trouble not up to maintaining this

**Pull request closed without merging**
