### PR TITLE
Choose your own adventure: Nuke edition

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
So mechanically there is nothing stopping you from detonating the nuke off planet.

This PR makes doing so actually change the game result.

Nuking the ship is a xeno major.
Nuking transit and irradiating the planet below is a xeno minor.
## Why It's Good For The Game
Unga gonna unga.
## Changelog
:cl:
fix: Detonating the groundside nuke shipside no longer results in a marine victory
/:cl:

### CODE REVIEW

**Comment by Tonklaatech** [comment]
What If unga nuke ship while xeno hijack

**Comment by novaepee** [comment]
image

**Comment by Lumipharon** [comment]
> What If unga nuke ship while xeno hijack. Draw like SD?

hijack actually disables the nuke, afaik

**Comment by GreatKingWombat** [comment]
Xope

**Comment by chizzy376** [comment]
What if we nuke both?

**Pull request merged**
