### PR TITLE
Removes mini scope from RL-152

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title.

## Why It's Good For The Game
Instakill from offscreen is quite unfun.

## Changelog
:cl: Lewdcifer
balance: RL-152 no longer accepts mini scopes.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
Eh, SADARs cost 120 points, but I guess I can understand people's frustration with this one, the RR one is just what, though.

**Comment by Naaanii** [comment]
Seems fine but removing it from both is better consistency.

**Comment by Lumipharon** [comment]
Is this really that much an issue? It gets a tiny increase in view distance, but needs a clear LOS unlike TAT with aim mode and much longer range.

**Comment by Araulius** [comment]
if this goes through, adjustments to the HE shell need to be made. such as, less radius, but more damage within it.

**Comment by Lauwma** [comment]
it's a rocket launcher, not a close quarter combat weapon

**Comment by Wayland-Smithy** [comment]
> Eh, SADARs cost 120 points,

The "req items do not need to be wallenced" argument is getting really old when points are all but free if you put BAS and normal sentries on 1 miner next to FOB or there is a researcher making 100s or any effort is put to selling never decaying corpses.

Xenos can not be revived and dying offscreen no matter the myriad of requirements, no IFF, needs LOS, etc.. is not fun gameplay.

**Comment by TiviPlus** [comment]
If its too weak people can lower the price

**Pull request merged**
