### PR TITLE
Ship Supplies Rebalance

### PR DESCRIPTION
**Pull request by Hathkar**
## About The Pull Request

Each of the three main ships now contain ~260 metal, and 60 plasteel.
200 metal and 60 plasteel is located on a rack near the FOB Drone Computer, along with a boxed sentry.
The other 60 metal is located in either engineering (Sulaco), CIC (Pillar), or CIC Armory (Thesesus).
Each ship also has their number of ColMarTech Engineer System Vendors (The things you get mortars and sentries from) reduced to 1. For the Theseus and Sulaco, said vendors have been moved to the self serve req area.
Moved the self-serve req area on the Pillar of Spring to where the Pilot's quarters used to be.
All ships have an equal number of Automated Armaments, Automated Munitions, and Armat Systems Attachments Vendors (2 of each).
Added some welder packs to the Sulaco.
Added in some hand labelers outside of each req area for general use.
Fixed some walls on the Sulaco being unmeltable.

## Why It's Good For The Game

Each ship had a wildly different amount of materials. For example, on the Sulaco, you could easily build a 6 layer FOB on Prison Station.

Having multiple ColMarTech Engineer System Vendors also meant 4 free mortars + shells, and a mix of 4 Mounted MGs or sentries.

Also some QoL changes for the Sulaco in the form of hand labelers and welding packs.

With these changes, balance will be less dependent on what ship the marines are using.

## Changelog
:cl:
add: More req vendors on the Pillar of Spring
add: One boxed sentry in req for each ship
add: Welder packs on the Sulaco
add: More hand labelers on the Sulaco
del: Moved said vendors to the area the Pilot's quarters used to be
del: Metal and plasteel on Thesus and Sulaco
del: Spec Prep on the Sulaco
del: ColMarTech Engineer System Vendors on ships that had more than 1
del: Several metal barrels on the Theseus, as they gave 10 metal each
balance: Each ship should have ~200 metal and 60 plasteel
/:cl:

Previews of Req on each ship:
https://i.imgur.com/cf3QelB.png

https://i.imgur.com/QTgL5VX.png

https://i.imgur.com/mrFVCZm.png

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by RenGusta** [comment]
Combined with the req changes you've been pushing, I don't quite like the idea of a 75% defensive tool reduction. 

2 on each map is probably reasonable, but that's maybe not just me.
We'll have to see as this PR continues.

**Comment by MacBlaze1** [comment]
It should be 2 on each map, otherwise this is a massive nerf

**Comment by Hathkar** [comment]
Added one sentry crate in each ship's req area.

**Comment by Chaznoodles** [comment]
Reminder that this is due to me calling him out in msay for deleting building supplies with admin buttons on the Sulaco, which would've gone unnoticed if I hadn't spotted it 👀

**Comment by Hathkar** [comment]
I was going to do this anyway. Your whining spurred me to finally do it.

**Comment by Hathkar** [comment]
Moved the sink in the south operating room to actually be inside the room.

**Comment by Hathkar** [comment]
Did another pass, 260 metal 60 plasteel on each ship.
Each FOB Drone Computer now has a rack next to it holding 200 metal and 60 plasteel, along with a boxed sentry.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
