### PR TITLE
Fire and Snow interactions

### PR DESCRIPTION
**Pull request by psykzz**
## About The Pull Request
Fire and Snow interactions

## Changelog
:cl:
add: you can now instantly put out fires by resisting on snow
add: fire melts snow
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
This doesn't really make much sense if it's a flamethrower direct hit-
Napalm doesn't really get off things that easily. Same with LZ river interaction.

**Comment by psykzz** [comment]
This is one of those times i'd go for gameplay over realism as you just roll on the floor to deal with it why not make the snow  more effective?

**Comment by Pariah919** [comment]
This makes flamethrowers even worse than they already are though against beans on maps like ice and icy caves. I disagree with this change.

**Comment by Rohesie** [comment]
I like the concept.

What does this make flamethrower bad at?

**Pull request merged**
