### PR TITLE
Combat shotgun can fire one handed again

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Juggling is dead. One handed combat shotgun is back.
## Why It's Good For The Game
Juggling is dead, and the TGMC bought better stocks for the combat shotguns again.
## Changelog
:cl:
balance: You can now fire combat shotguns one handed again.
/:cl:

### CODE REVIEW

**Comment by QualityVan** [comment]
The component ignores any dual-wielded guns.

**Comment by shelteredfreak** [comment]
Honestly, this sounds mad funny enough that it should be merged.

**Comment by ivanmixo** [comment]
> The component ignores any dual-wielded guns.

Akimbo delay still applies

**Comment by 1kajowsmol** [comment]
Oh yes baby please one handed t39 is back

**Review by TiviPlus — APPROVED** [review]
why did we remove this again

**Comment by ivanmixo** [comment]
> why did we remove this again

To deal with juggling lol

**Comment by ClosetedSkeletonGH** [comment]
It just looks ugly with the non wielded in hand sprites

**Pull request merged**
