### PR TITLE
Attacking a resin wall channels the next attack

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Attacking a resin wall channels the next attack

https://github.com/tgstation/TerraGov-Marine-Corps/assets/66163761/93222a0d-5299-432e-8ec1-1ed801aa0bf0
## Why It's Good For The Game
QOL to help against spam clicking
## Changelog
:cl:
qol: Meleeing a resin wall channels the next attack
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
finally no more carpel tunnel

**Review by TiviPlus — APPROVED** [review]

**Comment by 00ze-cyclone** [comment]
so uh there's no check for distance, so you tap a wall once then telekinetically channel the following hits from kilometers away

**Comment by Fawcksy** [comment]
Beautiful PR but uhhhhh please fix this thanks https://cdn.discordapp.com/attachments/504094319075131402/1211819414572240896/Feb-Mon-26_17-29-49.mp4?ex=65ef95c6&is=65dd20c6&hm=5bc83ccffde58b9a97db20c5c0cf696b150beefbf88768e028753cb691b2ee5d&

**Comment by Lumipharon** [comment]
Fix the funny

**Comment by Lumipharon** [comment]
This creates some very funky behavior. I can channel an attack on a while and shoot xenos full auto at the same time.
On the other hand if I get stunned by a xeno and accidentally click a wall instead of the xeno, I am now stuck unable to attack the xeno (assuming I'm pinned in) and I can't even wield my gun if it wasn't wielded at the time.

**Comment by coldironwarrior** [comment]
it's SO over

**Pull request closed without merging**
