### PR TITLE
Surt Changes

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

Decrease Surt slowdown from a pretty hefty 0.4 to 0.3, matching the highest slowdown of other Mk2 req modules like Tyr Mk2. 

## Why It's Good For The Game

Surt has really crippling slowdown currently for being a paid module.This brings it down to the realm of the Tyr Mk2 in terms of slowdown.

## Changelog
:cl:

balance: Surt has 0.25 slowdown, down from 0.4.

/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
>and applies meds

[Laughs in critdrag and corpsmen tircord ODing]
Tyr2 also gets memed by head aiming and once the bonefrac happens it's obsolete by how what'll kill you is the one-click splint removal followed by organ damage. If xenos are aiming head, you're effectively getting a slowdown for free. Dunno why the tyr2 head module didn't get merged.

**Comment by Hekzder** [comment]
> > and applies meds
> 
> [Laughs in critdrag and corpsmen tircord ODing]
> Tyr2 also gets memed by head aiming and once the bonefrac happens it's obsolete by how what'll kill you is the one-click splint removal followed by organ damage. If xenos are aiming head, you're effectively getting a slowdown for free. Dunno why the tyr2 head module didn't get merged.

Head aiming is incredibly uncommon and would basically only be good against Tyr + Heavy users since helmets otherwise give better protection than body armor. Like I mentioned, Valk _can_ be a doubled edged sword but ultimately I think it's at least on the level of Tyr 2 and Surt in terms of balancing around slowdown.

**Comment by february-ops** [comment]
> > > and applies meds
> > 
> > 
> > [Laughs in critdrag and corpsmen tircord ODing]
> > Tyr2 also gets memed by head aiming and once the bonefrac happens it's obsolete by how what'll kill you is the one-click splint removal followed by organ damage. If xenos are aiming head, you're effectively getting a slowdown for free. Dunno why the tyr2 head module didn't get merged.
> 
> Head aiming is incredibly uncommon and would basically only be good against Tyr + Heavy users since helmets otherwise give better protection than body armor. Like I mentioned, Valk _can_ be a doubled edged sword but ultimately I think it's at least on the level of Tyr 2 and Surt in terms of balancing around slowdown.

Head is the meta now btw

**Comment by Hekzder** [comment]
> > > > and applies meds
> > > 
> > > 
> > > [Laughs in critdrag and corpsmen tircord ODing]
> > > Tyr2 also gets memed by head aiming and once the bonefrac happens it's obsolete by how what'll kill you is the one-click splint removal followed by organ damage. If xenos are aiming head, you're effectively getting a slowdown for free. Dunno why the tyr2 head module didn't get merged.
> > 
> > 
> > Head aiming is incredibly uncommon and would basically only be good against Tyr + Heavy users since helmets otherwise give better protection than body armor. Like I mentioned, Valk _can_ be a doubled edged sword but ultimately I think it's at least on the level of Tyr 2 and Surt in terms of balancing around slowdown.
> 
> Head is the meta now btw

Fairly certain groin is the meta unless I'm out of touch from playing Xeno slightly less the past few days.

**Comment by Losenis** [comment]
Groin's a meta for shits n giggles, but head still happens pretty dang often to the point the one time I decided to try tyr2 again I got headfrac almost immediately rendering the module a 0.3 slowdown deathtrap. Jaeger armor doesn't affect helmet armor, regardless of going light or heavy. Head organ damage, even just a bit, starts causing force rests that not even peridaxon can stop and needs imialky not everyone packs, and will also blind you if you don't splint it causing a direct hindrance at fighting benos rather than just "haha more damage".

A guy going tyr2 with heavy jaeger (tbh why would you go anything but heavy if you're going tyr2) gets invalidated by any xeno aiming head because it'll still be hitting a 50 armor bodypart rather than something like 65 armor. It's only somewhat worthwhile when you can get the SL helmet to compensate for the weak head armor, but when the frac happens, you're just running a slowdown module that'll survive enough to die from organ damage anyway.

**Comment by Hekzder** [comment]
I mean regardless of all this, the balance of Tyr and where Xenos aim is irrelevant to _this_ PR. I'm not suggesting that Tyr be increased or decreased in cost, frankly I think it's fine where it is. But I think Surt is too expensive for what it does and that Valk could use a very slight slowdown increase. 

I might look into a Tyr helmet mod as a completely separate PR, probably bundled with Tyr 2 for like 15 points total to prevent it being free and just having everyone run it regardless of Tyr or not. 

But ignoring all of this, back on the topic, the argument I'm trying to make is that I believe Valk, Tyr 2, and Surt are at about the same level of benefit. Automedical system, hefty body armor, and fireproof all having about the same slowdown shouldn't be too crazy. I don't think any of them are particularly over or underpowered as it stands now, but this just makes them a bit more uniform in terms of power level and to have a bit less tradeoff for Surt and slightly more tradeoff for Valk.

**Comment by Hekzder** [comment]
> I mean regardless of all this, the balance of Tyr and where Xenos aim is irrelevant to _this_ PR. I'm not suggesting that Tyr be increased or decreased in cost, frankly I think it's fine where it is. But I think Surt has too much slowdown for what it does and that Valk could use a very slight slowdown increase.
> 
> I might look into a Tyr helmet mod as a completely separate PR, probably bundled with Tyr 2 for like 15 points total to prevent it being free and just having everyone run it regardless of Tyr or not.
> 
> But ignoring all of this, back on the topic, the argument I'm trying to make is that I believe Valk, Tyr 2, and Surt are at about the same level of benefit. Automedical system, hefty body armor, and fireproof all having about the same slowdown shouldn't be too crazy. I don't think any of them are particularly over or underpowered as it stands now, but this just makes them a bit more uniform in terms of power level and to have a bit less tradeoff for Surt and slightly more tradeoff for Valk.

**Comment by Losenis** [comment]
>I mean regardless of all this, the balance of Tyr and where Xenos aim is irrelevant to this PR

It... kind of is? You mentioned the Tyr2 as reasoning for lowering/increasing the other modules on slowdown but tyr2 is just busted, so I wouldn't consider its slowdown as what it should be. 3 is too high without head protection, so you shouldn't look at it when considering the other modules in terms of slowdown. I'd see surt lowered to 0.25 given it's only stopping your own fire but it might be too much of a change to see it merged.

**Comment by Hekzder** [comment]
Fair, though I guess what I really meant was that changing Tyr is probably out of the scope of this PR. Though like I said I might fuck around with a separate PR to add a Tyr head module for Tyr 2 so that it isn't cucked so hard by head aim. 

Lowering Surt to 0.25 is probably a bit much like you mentioned. I'll probably leave out the Valk change when I make a commit later. I realized it makes this PR not super atomized and I'm not sure if the double edged nature of Valk is really worth the slowdown increase. Maybe after Tyr gets touched up and changed, if I get around to it.

**Comment by Hekzder** [comment]
Yeah this PR is just the Surt change now, don't care enough about the Valk change to potentially prevent this getting merged.

**Comment by SplinterGP** [comment]
@Hekzder helmet has same armor accross all marines so you get more consistency on kills AND head is a easier to break and has more issues when broken bone.

**Comment by SplinterGP** [comment]
id say keep flashlight debuff and reduce a bit more the slowdown and thats good.

**Comment by Hekzder** [comment]
> id say keep flashlight debuff and reduce a bit more the slowdown and thats good.

Done, this is just a slowdown reduction to 0.25 from 0.4 now.

**Comment by TiviPlus** [comment]
@SplinterGP I dont like this talk to me in disc about it

**Comment by TiviPlus** [comment]
Surt does not need this buff it is already decent as is

**Pull request closed without merging**
