### PR TITLE
New lighting with shadows and shapes

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
Taking from https://github.com/BeeStation/BeeStation-Hornet/pull/3742  , new lighting with shadows
A lot of code has been changed to make this a parallel to static and movable as alternatives, and render performance has been drastically improved (at least ~2-3 times), hopefully enough to not lag people anymore.
Layering has been changed, to not opress small lights as much
Directional lights are also possible now
Ported tg dview

## ToDo
- [ ] Check on live that this performs adequately
- [ ] Consider completely removing static if above works
- [ ] Possibly change maps for funny corners or change pixel depending on dir
- [ ] Finish writing that .md about lighting systems lol
- [ ] Maybe change spinny lights to animate instead of icon

## Changelog
:cl:
refactor: New prettier lighting system
code: Static lighting has been fully renamed to static lighting
qol: Fire now flickers when it burns
qol: SD now has alarm sirens (sprite by Ciel)
qol: Powerloaders now have Hazard lights
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
nice

**Comment by DerrickChamberlain** [comment]
Will this fix the bug of light tubes just breaking when you flip them on and off? And also making it so you can not just replace lights on a dead APC area?

**Comment by BraveMole** [comment]
> Will this fix the bug of light tubes just breaking when you flip them on and off? And also making it so you can not just replace lights on a dead APC area?

no

**Comment by TiviPlus** [comment]
Pending investigation into unusually high Populate List render function cost

**Comment by spookydonut** [comment]
Good job

**Comment by SplinterGP** [comment]
Do not merge until lag issue is solved(on clients)

**Comment by DerrickChamberlain** [comment]
> > Will this fix the bug of light tubes just breaking when you flip them on and off? And also making it so you can not just replace lights on a dead APC area?
> 
> no

Frick

**Comment by optimumtact** [comment]
>Ported tg dview

don't do it

**Comment by PowerfulBacon** [comment]
If you pull off a miracle and get this to not lag clients when not using static lighting on machinery/light and other widely used lights, I will be impressed. I tried for way too many hours, but something like this is insanely difficult without full control over the engine's internals.

**Comment by TiviPlus** [comment]
> If you pull off a miracle and get this to not lag clients when not using static lighting on machinery/light and other widely used lights, I will be impressed. I tried for way too many hours, but something like this is insanely difficult without full control over the engine's internals.

Found two sources, one I squashed one, other lummox claimed to be possibly fixed by next release so waiting on him to do that

**Comment by Qustinnus** [comment]
> > If you pull off a miracle and get this to not lag clients when not using static lighting on machinery/light and other widely used lights, I will be impressed. I tried for way too many hours, but something like this is insanely difficult without full control over the engine's internals.
> 
> Found two sources, one I squashed, other lummox claimed to be possibly fixed by next release when I asked him to look into it for me so waiting on him to do that

wtf lummox does that????

**Comment by PowerfulBacon** [comment]
Instead of using overlays, replace the mutable appearance with
```
filters += filter(type="layer", icon = icon(LIGHTING_ICON_BIG, "triangle"), color = "#000", transform = M)
```

**Comment by TiviPlus** [comment]
Filters make the game hang when you try to go near them *shrug

**Pull request closed without merging**
