### PR TITLE
move Big Red's ETA APC closer to disk

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Remove these two APCs in Big Red's ETA.

image

image

Replace those two APCs in Big Red's ETA to an APC closer to disk.

image

## Why It's Good For The Game

Big Red's APCs are known to be visually near disks so that engineers can keep their sanity when dealing with APC.

This is the only disk I know in Big Red that force marines to be far from APC.
image

## Changelog

:cl:
balance: move Big Red's ETA APC closer to disk
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
just build a new one 4head

**Comment by chizzy376** [comment]
What do you mean far away? It's 8 tiles away, within screen view. I don't think this counts as "far away"

**Comment by Helg2** [comment]
You can just blow up the wall tho?

**Comment by ivanmixo** [comment]
Making a map where the marines already have a very easy time if they commit to disks even easier is very meh in my opinion, especially considering this disk has a high likelyhood of being unflankable due to the way big red modulars work.

**Comment by Yttriums** [comment]
doesn't this also double the area you power by getting the one APC? thats real bad

**Pull request closed without merging**
