### PR TITLE
Mesons obscure vision partly when used

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

image

why mesons are currently bwoinkers is explained here : https://github.com/tgstation/TerraGov-Marine-Corps/pull/7199

## Why It's Good For The Game

Getting 1-2-3 night vision range for an item that is orignally designed for engineers is bwoinkers.

This solution allow engineers to still use mesons for legit uses, so PC. It is also possibly useable by flamers, but with a fair compromise

## Changelog
:cl:
balance: Mesons obscure vision partly when used
/:cl:

### CODE REVIEW

**Comment by EvilMelonTheSecond** [comment]
Not even engineers will take it. If this gets merged I'm almost sure people will use this to justify marines getting night vision. 

Do not nuke a popular option please. Limit it with req(or something similar) or add its functionality to something else.

**Comment by Ieteihowmee** [comment]
Mesons on suicide watch. Damn that is a TINY view window. Evilmelonthesecond is right, engineers would not even take this. Compromises vision too much. If I wanted to see barely anything I would never raise up my welder goggles. Not nearly as bad as the nuclear option.

**Comment by Wayland-Smithy** [comment]
> If I wanted to see barely anything I would never raise up my welder goggles.

And just like welding goggles these should have specific use cases, like when you want to see what is on the other side of a wall to know how much to fortify. Once you are done your engi tasks take them off not that hard. They should have only limited hyper specific usefulness and not general purpose unga usability.

**Comment by David-Stormwell** [comment]
Mesons on suicide watch, just like revolvers such is life.

**Comment by jroinc** [comment]
Liiitle too much nerf range. Looks to be 3 tiles of blackout and 2 of tint.

Maybe 1 tile of blackout and 3 of tint instead? That way it won't feel like I put on a blindfold instead of goggles. I like the idea, though, and they do need a nerf.

**Comment by SplinterGP** [comment]
#7307

**Pull request closed without merging**
