### PR TITLE
The Healthbarening

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request
 
Addresses feedback unresolved by the author of the "Berry Bar" mechanic.
## Why It's Good For The Game

Health Bar > Berry Bar
## Changelog
:cl:
add: Health Bars
del: Berry Bars
/:cl:

### CODE REVIEW

**Comment by Sirsnek15** [comment]
shitpost

**Comment by imsxz** [comment]
It has to be done

**Comment by zzurge** [comment]
based

**Comment by Al-1ce** [comment]
I don’t get it.

**Comment by LeAntek** [comment]
good pr speedmerge

**Comment by TiviPlus** [comment]
I dont get it either

**Pull request closed without merging**
