### PR TITLE
Stun changes part 6- queen

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
PART 6-
Queen

NERFS
Screech now deals stamina damage instead of haloss.

Compensation (If any)
Queen now has a hivelord level heal

## Why It's Good For The Game
queen is more of a chess king than a queen, and should probably have more support abilities than direct combat abilities in general

## Changelog
:cl:
balance: queen screech now deals stamina damage, she has gained healing in return
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by MLGTASTICa** [comment]
I feel like this stun should stay , its rarely employed and the queen should still be a powerfull support  xeno.

**Comment by Pariah919** [comment]
the stun top stun was nerfed, which is literally right next to queen, in general its a total buff other than haloss being nerfed so uhh ok

**Comment by Max-023** [comment]
This stun isn't even substantial in any capacity. All it does is allow the queen to setup pushes, which still helps it fill its role of a support caste.

**Comment by Chaznoodles** [comment]
The madman

**Comment by MiniMeatwad** [comment]
ncer

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Id rather you just change the haloss to be stamina damage, hivelord heal can stay I suppose

**Comment by Pariah919** [comment]
@TiviPlus screech deals stamina now

**Comment by jroinc** [comment]
> Id rather you just change the haloss to be stamina damage, hivelord heal can stay I suppose
> @TiviPlus screech deals stamina now

That's a MASSIVE buff to marines, given as the screech can't drop wounded guys for longer now (given the differences between stamina and halloss mechanics).

**Comment by SplinterGP** [comment]
i mean hurt dudes have less stamina ? but dunno *shrug*

**Review by TiviPlus — APPROVED** [review]

**Review by Hughgent — APPROVED** [review]
variable changes

**Comment by Hughgent** [comment]
TM'd Since:
Commander TGMC
BOT
11/21/2020
REPO: Updating origin branch...
REPO: Merging PRs #5261, #5223, #5252, #5258, #5299...
DM: Compiling...
DM: Compile complete! Server will update on reboot.

TGMC Statbus
Winrate (Xenomorph to Marine)
46.15%
View Raw
http://statbus.psykzz.com:8080/api/winrate?delta=2

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-71). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
