### PR TITLE
Adds Rudimentary Tank Breech Animations

### PR DESCRIPTION
**Pull request by JackTheJackhammer**
## About The Pull Request

Adds basic breech animations of the breech moving in and out when the tank fires

## Why It's Good For The Game

Gives the breech a good animation and gives the loader another way to tell that the tank fired

## Changelog

:cl:
add: Added tank firing animations to tank breech

/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]
i like it

**Comment by TiviPlus** [comment]
@Kuro020

**Comment by Kuro020** [comment]
merge conflict

**Comment by lbnesquik** [comment]
Alas, poor staled PR. Hopefully it comes back after the merge conflict is done. I liked it!

**Pull request closed without merging**
