### PR TITLE
Makes buckshot a bit more effective mid range

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
increases the buckshot accurate range to 5 and reduces falloff by 1

## Why It's Good For The Game
Buckshot is kinda weird in a way that it is very good(only against low armor classes) at PB and trash at everything else, its supposed to be bad as range goes on but, not only it spreads, hitting less pellets due to it, but it also loses a lot of damage and misses alot after 3 tiles, now this maxes it hit more at a higher range but it will still hit 1 or 2 pellets due to spread anyway

## Changelog
:cl:
balance: buckshot has less falloff
balance: buckshot accurate range(not spread) has been increased to 5 tiles.
/:cl:

### CODE REVIEW

**Comment by RenGusta** [comment]
So it loses 15 instead of 20 damage a tile? Still not great, but hey. We'll see if someone likes it soon.

**Comment by Lefunny** [comment]
Making a buckshot ((weapon that is good used as meele)) being able to be used now as middle range sounds like a amazing idea for me, surely most people with shotguns cant handle meele fight agaist most t1s this should help with letting shotungs being more ranged, good chang!

**Comment by EvilMelonTheSecond** [comment]
Still worse than flechette in 99% of situations. The 1% is somehow PBing a runner which MIGHT kill it.

**Comment by Pariah919** [comment]
it still loses 15 damage per tile which effectively means all this does is make it slightly better when you pb on something with knockback
reduce the spread a bit and reduce the falloff by 3 rather than 1.

**Comment by lovegreenstuff** [comment]
buck is still going to have absolutely garbage damage potential past 1 tile due to scatter
you're gonna go from doing 32 damage at most to 34 every two seconds

**Comment by Pariah919** [comment]
> Making a buckshot ((weapon that is good used as meele)) being able to be used now as middle range sounds like a amazing idea for me, surely most people with shotguns cant handle meele fight agaist most t1s this should help with letting shotungs being more ranged, good chang!
>
i haven't seen a past pb tile buckshot kill since i got a 6 tile on a hivelord.. With a unnerfed ZX.
Which means it was like, a year and a half ago?

**Comment by lovegreenstuff** [comment]
even less falloff wow.
i still have 17.5 dps at 5 tile range. a whopping 7.5 dps bonus woo.

**Review by BraveMole — APPROVED** [review]
Ok let's try that

**Pull request merged**
