### PR TITLE
Boxers in EORD

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Add boxers in EORD!

Their pants PROTECT them from ANY projectiles, whether it be BULLETS, GRENADES, ROCKETS, OR PLASMA! FACE YOUR OPPONENT WITH YOUR BARE FIST!

https://user-images.githubusercontent.com/6610922/212527474-b441d151-44eb-408d-8b71-13b2a90aa5a6.mp4

https://user-images.githubusercontent.com/6610922/212527477-c53e14e2-ea1f-49d8-bd31-3cf420e6bc6f.mp4

https://user-images.githubusercontent.com/6610922/212527480-b6340fa2-a212-4b67-9507-08734bd9140e.mp4

## Why It's Good For The Game

The best time to box others is in EORD, BABYYYYYYYYYYYYYYYYYYY!

## Changelog

:cl:
add: Boxers in EORD!
/:cl:

### CODE REVIEW

**Comment by XSlayer300** [comment]
Make sure you cannot take them off to prevent any sort of abuse.

**Comment by FosterGrime-Heymynameslouie** [comment]
very cool pr

but can an eord person take them, wear them then leave the ring to be effectively immortal?

**Comment by Tailiik** [comment]
Neat but stupid if they knock people down

**Comment by novaepee** [comment]
> Make sure you cannot take them off to prevent any sort of abuse.

> very cool pr
> 
> but can an eord person take them, wear them then leave the ring to be effectively immortal?

your boxing pants will show to the world that you can get speared so i'm not too worried about that

**Comment by novaepee** [comment]
> Neat but stupid if they knock people down
skill-issue

**Comment by novaepee** [comment]
Lumi brought up two points:

1) People don't wanna respawn as boxers
2) Boxers with semi-deathsquad armor can pick up gun and annihilate people.

Solution for this is have a different EORD respawn verb dedicated for boxers and have boxers unable to hold guns. Those are BYOND my abilities, so I will close this PR.

**Pull request closed without merging**
