### PR TITLE
TX15 slug buff

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Adds stagger to the autoshottie slug.
## Why It's Good For The Game
Flech superiorly outperforms slugs with the autoshottie.
This buff should help keep it in line with flech without being too oppressive and fulfill the soft cc role of slugs vs flech with cc vs raw damage.
## Changelog
:cl:
balance: Autoshottie slugs now have stagger.
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
The slug was also out performed by the lever action (which also has stagger). Seems like a good PR, time to see it not get merged

**Comment by Lumipharon** [comment]
This makes it perma stagger which is pretty cringe.

**Comment by EvilMelonTheSecond** [comment]
> This makes it perma stagger which is pretty cringe.

I believe T39 with slug already has that but with better stats.

**Comment by Naaanii** [comment]
> This makes it perma stagger which is pretty cringe.

Issue addressed.

**Comment by Ragecrabbo** [comment]
> The slug was also out performed by the lever action (which also has stagger). Seems like a good PR, time to see it not get merged

> I believe T39 with slug already has that but with better stats.

Unlike both of these guns autoshotty lets you use underbarrel attachments like miniflamer or grenade launcher (which already makes it better than either of these imo) along with many other attachments. Additionally T39 has a -30% damage and twice the drop-off of autoshotgun while lever action is lever action. Giving autoshotgun slugs stagger would make it easily the best option of these three in every situation i can think of.

**Comment by Naaanii** [comment]
> > The slug was also out performed by the lever action (which also has stagger). Seems like a good PR, time to see it not get merged
> 
> > I believe T39 with slug already has that but with better stats.
> 
> Unlike both of these guns autoshotty lets you use underbarrel attachments like miniflamer or grenade launcher (which already makes it better than either of these imo) along with many other attachments. Additionally T39 has a -30% damage and twice the drop-off of autoshotgun while lever action is lever action. Giving autoshotgun slugs stagger would make it easily the best option of these three in every situation i can think of.

Autoshottie slugs are half the damage.

**Comment by Al-1ce** [comment]
> The slug was also out performed by the lever action (which also has stagger). Seems like a good PR, time to see it not get merged 

This gun was added _years_ before the lever action was. Slugs still preform better.

**Pull request closed without merging**
