### PR TITLE
New automedical sounds

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
B18/Valk have new sounds.
source: Me, filter added from Lich.
## Why It's Good For The Game
More unique and original sounds, with their own cool filter.

## Changelog
:cl:
sound: B18 and Valkyrie automedical modules have new sounds.
/:cl:

### CODE REVIEW

**Comment by Kuro020** [comment]
PLEASE, WE NEED THIS

**Comment by Barnet2** [comment]
This is the next step forward in TGMC history. Truly.

**Comment by Lumipharon** [comment]
Post audio so I don't need to download the files to hear your cringeass

**Comment by Lumipharon** [comment]
I prefer the existing ones tbh.

**Comment by BonkaiB** [comment]
what if more robotic

**Comment by Lumipharon** [comment]
Kuro you nerd, this is honestly worse.

**Pull request closed without merging**
