### PR TITLE
New RR shell for Combat Patrol

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Edit: Made a new shell instead of changing the light shell.

Added the low impact shell, similar to the light explosive shell.

Reduced pen from 50 to 15, so it has less ggnore potential.
Reduced blind range from 5 to 3, for less AOE ggnore potential.

Additionally changed the RR loadout in Combat Patrol to only contain low impact RR shells... to remove the ggnore potential of HE shells.

Also just cleaned up some duplicate vars.

## Why It's Good For The Game
Less ggnore

## Changelog
:cl:
add: Added a low impact shell for the RR, with less direct hit damage and blind range
balance: Combat Patrol: RR loadout only has low impact RR shells
/:cl:

### CODE REVIEW

**Comment by MereWalker** [comment]
This will only affect RR in combat? Not normal xeno rounds? ALSO  if marines still keep a rocket which is deadly for som and their holds. Can som get a loadout equivalent so they can break holds?

**Comment by Lumipharon** [comment]
> This will only affect RR in combat? Not normal xeno rounds? ALSO if marines still keep a rocket which is deadly for som and their holds. Can som get a loadout equivalent so they can break holds?

This is changing the contents of the RR bag only in combat patrol, but is changing the stats of light shells in general.

**Comment by Al-1ce** [comment]
This effects the light shelo in-and-of-itself: meaning that it'll be weaker when used on xenos as well.

Not a fan. At all.

**Comment by Lumipharon** [comment]
> This affects the light shell in-and-of-itself: meaning that it'll be weaker when used on xenos as well.
> 
> Not a fan of this at all. The RR has been nerfed to hell as it is.

It hasn't been nerfed, I heavily buffed it by making the RR fit in it's own ammo bag.

**Comment by Naaanii** [comment]
Just remove RR for HvH.

**Comment by Losenis** [comment]
This nerf reaches farther than its intended scope. Maybe remove RR from CP, given it was a weird choice to have the actual rocket part of rocket tag in said mode where the opponent also doesn't have xray to spot you.

**Comment by Serxule** [comment]
> 



> > This affects the light shell in-and-of-itself: meaning that it'll be weaker when used on xenos as well.
> > Not a fan of this at all. The RR has been nerfed to hell as it is.
> 
> It hasn't been nerfed, I heavily buffed it by making the RR fit in it's own ammo bag.

a rocket on your back is "heavily buffed" ???? if you made it so rockets one shot xenos, _then_  it would be heavily buffed, this is just a nerf for a gamemode no one likes

**Comment by Strayed-Raven** [comment]
Why in the world would you tweak a weapon across the game modes just for CP? Just make a new shell just for CP that fits balance better for anti-personnel. And really ggnore? How about less overreach on a change. Or give an actual reasoning beyond ggnore. SMH.

**Comment by DerpiestBruh** [comment]
I dont think we should balance weapon stats around HvH

**Comment by FIXTHERADBOXPLEASE** [comment]
Not a coder but wouldn't it be a better solution to make a yellow tippeed "Anti-personnel" shell for the Combat Patrol loadouts? Balancing weapons around HvH sounds wack.

**Comment by Al-1ce** [comment]
> It hasn't been nerfed, I heavily buffed it by making the RR fit in it's own ammo bag.

Entirely unrelated to this PR and the changes inside it.

**Comment by Lumipharon** [comment]
Updated with a new shell type.

**Comment by Al-1ce** [comment]
Anti-Personel shell seems like an interesting concept. Still, I think most of the playerbase doesn't enjoy the nature of a 1-shot weapon. Especially if it can reach beyond screen-view.

**Comment by Lumipharon** [comment]
> Anti-Personel shell seems like an interesting concept. Still, I think most of the playerbase doesn't enjoy the nature of a 1-shot weapon. Especially if it can reach beyond screen-view.

The direct damage is going to be like, 35 or some shit now. It'll hurt, but not nearless as deadly as normal shells. And not having the explosive flag (same as LE shells) means if you miss a person, you'll likely COMPLETELY miss them since it will just fly past, unlike HE shells or sadar.

**Comment by Naaanii** [comment]
> > Anti-Personel shell seems like an interesting concept. Still, I think most of the playerbase doesn't enjoy the nature of a 1-shot weapon. Especially if it can reach beyond screen-view.
> 
> The direct damage is going to be like, 35 or some shit now. It'll hurt, but not nearless as deadly as normal shells. And not having the explosive flag (same as LE shells) means if you miss a person, you'll likely COMPLETELY miss them since it will just fly past, unlike HE shells or sadar.

But it's not like humans have the ability to dash or react to it either way, so any competent player that knows how to click sprites with a RR will be getting kills.

**Comment by Lumipharon** [comment]
> > > Anti-Personel shell seems like an interesting concept. Still, I think most of the playerbase doesn't enjoy the nature of a 1-shot weapon. Especially if it can reach beyond screen-view.
> > 
> > 
> > The direct damage is going to be like, 35 or some shit now. It'll hurt, but not nearless as deadly as normal shells. And not having the explosive flag (same as LE shells) means if you miss a person, you'll likely COMPLETELY miss them since it will just fly past, unlike HE shells or sadar.
> 
> But it's not like humans have the ability to dash or react to it either way, so any competent player that knows how to click sprites with a RR will be getting kills.

That's the point of this PR though, making it not ggnore. Also these actually travel slower than bullets, so especially if someone is trying to screen edge snipe you, strafing will actually make it miss quite often.

**Comment by MereWalker** [comment]
I look forward to using this as a marine on the poor som when they see me line up the kill shot. Just don't make it too slow! With love.

**Comment by Al-1ce** [comment]
With some reconsideration, and having been domed by this thing, it seems relatively balanced.

**Pull request merged**
