### PR TITLE
Silo output buff

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Silos are a bit weak compared to king and such, this makes a more interesting choice.

## Why It's Good For The Game

Long game are started to become too marine favored, this balance late game a bit. 

## Changelog
:cl:
balance: Silo produces 18% more
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
Wheres the code for marine respawns giving larvas btw

**Review by TiviPlus — APPROVED** [review]

**Review by SplinterGP — CHANGES_REQUESTED** [review]
How does long games make marine more favored? Please explain better

**Comment by Ragecrabbo** [comment]
> 
> 
> How does long games make marine more favored? Please explain better

Marines get free 30min respawn each, Xeno respawn relies on silos and kills. You need to have 6 cocoons survive for 5 minutes for a SINGLE larva (atleast last time i checked) or however long it takes for a silo to cook up one or the combination of the two while marines can just wait 30 minutes. Combine that with miners and selling xeno bodies for req toys and sooner or later marines will outnumber and outgun xenos in a stalemate unless they have been literally pushed into the FOB and cant secure any kills to sell for points.

**Comment by GradusNL** [comment]
> Marines get free 30min respawn each

This should be changed honestly. Rework clones instead of giving marines free respawns. I agree with your comments on current lategame by the way. The only thing that xeno's have going for them is king lategame and that doesn't weigh up to miners/requisitions and free respawns/new players. By the time you can get a king marines will have already started respawning.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Unrevert respawn change

**Comment by BraveMole** [comment]
image
 Reach a consensus please

**Review by SplinterGP — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]
Splinter why are you like this

**Pull request merged**
