### PR TITLE
Nutrition drains from kit regen

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
The passive regeneration that happens on limbs after they've been kitted drains nutrition relative to the damage healed.
Nutrition drain from having low blood is removed.
Hunger slowdown ramps from 0 rather than starting at 0.5 at the yellow hunger threshold.
Health scanners show a warning if patient nutrition is low.
## Why It's Good For The Game
Moves nutrition further into being a resource that you use via specific actions (kitting and running) instead of it being a knock-on effect of a knock-on effect (low blood).
The slow rescaling is mostly caprice but it seems weird for an otherwise smooth slope to start at not zero.
This does make continuous low blood somewhat less annoying but it still causes unconsciousness and death, so it'll be fine for now.
## Changelog
:cl:
qol: Health scanner shows low nutrition
balance: Hunger slowdown ramps slower
balance: Low blood doesn't drain nutrition
balance: Kitted limbs passively regenerating drains nutrition
/:cl:

### CODE REVIEW

**Comment by ClosetedSkeletonGH** [comment]
The starting at 0.5 was clearly so that people don't have to constantly be eating/risking making themselves fat with every bite in order to not have a constant slowdown of some kind. 

Removing that just seems to be trying to make the system 10x more micro-managy and annoying

**Comment by InterroLouis** [comment]
Can we do something about fat slowdown too?

**Comment by novaepee** [comment]
> Can we do something about fat slowdown too?

Maintainers say not to eat too much. Simple

**Comment by Pariah919** [comment]
As someone who uses kits pretty often, I use them to prevent bloodloss mainly. Does this just hardnerf it if you kit within any reasonable timeframe by math?

**Comment by Lumipharon** [comment]
Thinking about this again, I'm a bit concerned this will be another source of "fuck medics", if they kit someone up and curse them with slowdown because they have no food.

**Comment by maikilangiolo** [comment]
>kit to stop bleeding from five (5) damage punch
>don't lose blood, go hungry

>don't kit to stop bleeding from 5 (five) damage punch 
>lose blood, don't go hungry

And let's not talk about how healing burn damage makes you go hungry too.
Welp, back to pills it is. I'm glad even bandages and ointment are getting nerfed so I don't have to carry them. Good thing isotonic is infinite so I can regen the lost blood, and I can carry 8 pills in the same space I can carry a single MRE or protein bar.

**Comment by EvilMelonTheSecond** [comment]
This turns kit from reliable healing to background resource ticking away to get you slowdown. This is just an annoying nerf to force people back to pills after they get hungry a couple times from kitting. Why would anybody want to deal with managing both the food and medical supplies?

**Comment by Barnet2** [comment]
Pretty bad change, you can game the system as well. Kitting limbs isn't worth it anymore because of scaling slowdown, and you risk the chance of becoming fat since it is not a threshold anymore. This honestly would be fine if slowdown didn't scale.

**Comment by Aporhtonoma** [comment]
why punish kitting out of all things its the only part of the rine that actively requires them to stop for a bit.plus it make no sense for a bandage to soak up all your carbs.tone down heal chems or straight up place that to med chems (maybe a toned down version) but on medkits its honestly uneeded

**Comment by Naaanii** [comment]
I love CBT mechanics for the sake of existing.

**Comment by chizzy376** [comment]
I like how it's labelled QoL because of a stitched on addition
Please atomize your PR's

**Comment by srxtreme** [comment]
I nominate this for the worst PR of the week.

**Comment by ClosetedSkeletonGH** [comment]
your "why its good for the game" doesnt explain why its good for the game at all, just explains what the PR does

**Comment by FosterGrime-Heymynameslouie** [comment]
> your "why its good for the game" doesnt explain why its good for the game at all, just explains what the PR does

yeah it kinda dosent say anyhting about why its good for the game, strange

**Comment by KM-Catman** [comment]
Personally I feel like adding this would just make medics never use kits. Especially if you've kitted a dead marine, when they get back up they'll be drained to starving instantly. If this was something added back when Isotonic still gave Nutriment, then I'd understand it, but with how infrequently marines ever actually bring their MREs, this just feels like a massive nerf without proper justification.

**Comment by KM-Catman** [comment]
This PR also DOESN'T affect specifically kits; it affects the Bandaged and Salved limb status, meaning anything else that salves or bandages would ALSO be affected like Gauze and Ointment. This PR is, as srxtreme said, the worst of the week.

**Comment by Joe13413** [comment]
> > Can we do something about fat slowdown too?
> 
> Maintainers say not to eat too much. Simple

me when i eat an extra protein bar and have to resort to the ancient technique of fucking BLOODLETTING to lose weight 
tgmc is the only server on hub where bloodletting is a viable medical treatment

**Comment by ivanmixo** [comment]
Don't know why this isn't dying of stale but I don't want it and no other maintainer wants to touch this with a 10 foot pole judging from the lack of reviews.

**Pull request closed without merging**
