### PR TITLE
TAT is now Acidable. All Mortars (artillery) can be slashed.

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title.
## Why It's Good For The Game
<s>Seems like an oversight that TAT couldn't be acided but slashed and vice versa for the Mortars. Better consistency.</s>
Artillery and hard hitting weapons should be defended better.
## Changelog
:cl:
balance: TAT can be acided.
balance: Mortars can be slashed.
/:cl:

### CODE REVIEW

**Review by Lumipharon — CHANGES_REQUESTED** [review]
TAT is not acidable because it can't be picked up.

**Comment by FIXTHERADBOXPLEASE** [comment]
> TAT is not acidable because it can't be picked up.

You can't take the acid off of autodocs or consoles either, and they're still acidable. If you let your AT gun be exposed long enough to get acided, you should be punished.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Your why it is good for the game is not acceptable.

Objects having different features and perks is NOT a problem

**Comment by Naaanii** [comment]
> TAT is not acidable because it can't be picked up.

I could increase the time it takes to be acided.

**Comment by TiviPlus** [comment]
Your pr body does not explain why it is good for the game

**Comment by Naaanii** [comment]
> Artillery and hard hitting weapons should be defended better.

**Comment by Lumipharon** [comment]
> > TAT is not acidable because it can't be picked up.
> 
> I could increase the time it takes to be acided.

I'd be fine with this. The main thing is just making sure benos can't do a stun or two/screech and acid it before running away.

**Comment by Naaanii** [comment]
I will, fix this soon.

**Pull request closed without merging**
