### PR TITLE
SMALL ARMS rejoice!!  ((this needs to be TM before being merged and after the freeze))

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
this balances the small arms
smgs
machinepistols
pistols
revolvers

in many different and small improvements "revolver received a nerf to ROF and a BUFF to dmg" most of pitols got some level of buff tho not all T90 got a nerf per say. its relative in most cases come and see the code closer"

## Why It's Good For The Game
will finally set a standard for small arms. tunning them around the overall balance.

## Changelog
:cl:
balance: small arms (pistols. smgs. machine pistols. revolver)
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -14. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Walarks** [comment]
You should list the changes you've made to the guns to make reviewing and commenting on them easier, which increases the change of some/all changes to be merged.

Only looking at code and getting an idea of what has been changed and why is a bit too clunky.

**Comment by fernandos13** [comment]
i mean to be fair its lot of small changes... overall 
image
this will list most of them
also making STANDARD pistols and smgs have no recoil one  handed
at least 90% accuracy
and a max damage per magazine of 420 "MAX DAMAGE" 
a MAX dps of 180 DPS

"execpt for revolver with 450 damage with FULL MAG"

also making the TP23 and TP14 the SAME dps but different ways about it

**Comment by fernandos13** [comment]
also TBH the code is pretty clear.... in this guns.. 
rate of fire.. is.. rate of fire
accuracy is the guns accurary
unwielded means one handed
scatter is the "wide spray"
aim slowdown "how slow you are when holding with 2 hands"
mag size.. is.. mag size...
no changes to aim mode

**Comment by BraveMole** [comment]
You need to describe in the changelog the changes, description in PR is not enough

**Comment by fernandos13** [comment]
well i'm out of time as of now.. i'll make this HUGE changelog somewhere between later today and maybe end of next week.

**Comment by fernandos13** [comment]
well did it!

**Comment by fernandos13** [comment]
made it more human friendly

**Comment by fernandos13** [comment]
made it even more friendly cmon now its readable!!

**Pull request closed without merging**
