### PR TITLE
Add Kilt

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title

kilt

## Why It's Good For The Game

KILT. LET ME TELL YOU HOW MUCH I'VE COME TO WANT KILT SINCE I BEGAN TO PLAY TGMC IN APRIL 2020. THERE ARE 100 BILLONS OF NEURON IN MY MONKEY AND UNGA BRAIN. IF YOU OPEN UP MY CRANIUM, THE WORD KILT RESIDE ON EACH SOMA OF THOSE HUNDREDS OF MILLIONS OF NEURON WOULD NOT EQUAL ONE ONE-BILLIONTH OF THE NEED I HAVE FOR KILT. KILT. KILT.

## Changelog

:cl:
add: kilt; use facepaint on kama to choose kilt in the variety tab
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
still have some issues, so gotta fix that before undraft

**Comment by Wer6** [comment]
does this present marines with the oportunity to show xenos whos boss?

**Comment by BonkaiB** [comment]
Based

**Comment by Pariah919** [comment]
i don't want to deal with all the shitty memes I'll have to deal with as an admin if this gets in

**Comment by chizzy376** [comment]
we already have a vendable kilt from synth, bother him for one

**Comment by ThelastArchiver** [comment]
SCOTLAND FOREVERRRR!

**Review by hyper2snyper — COMMENTED** [review]
There can only be one.

**Review by Kuro020 — APPROVED** [review]
Im sorry mjp

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
