### PR TITLE
Hard Corps Theme Added to Lobby Music

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl: Surrealistik
add: Hard Corps Theme added to Lobby Music
/:cl:

### CODE REVIEW

**Comment by DominikPanic** [comment]
>4.16 MB
Geez, compress your files.

**Comment by Surrealaser** [comment]
> > 4.16 MB
> > Geez, compress your files.

That's the price of quality

**Comment by Rohesie** [comment]
When we get goonchat a are able to port the /tg/ music system.

**Comment by DominikPanic** [comment]
> 
> 
> > > 4.16 MB
> > > Geez, compress your files.
> 
> That's the price of quality

All other music besides space hero that is 2MB and also needs trimming is 600kb. You should get it to around the same size preferably.

**Comment by DominikPanic** [comment]
Goonchat and "Play Internet Sound" is in, if you want to add more music you should do it properly, this way we can use anything without having to host it and bloating the .rsc and repo.

**Pull request closed without merging**
