### PR TITLE
[DNM] Adds SKS - Mosins long lost cousin.

### PR DESCRIPTION
**Pull request by DeadliestDesire**
Adds Gun, own magazine,  sprites for both.

Colour palette and inspiration were taken from Mosin by the "Revolver go NYOM" Ocelot.

!!!!It did have wielded sprite problem (but so did mosin at the time) so I simply ask for an adult to review my mess and guide me!!!!
Please dont beat me with sticks, beat me with suggestions. Thanks.
## About The Pull Request
It's just a new gun, uses already existing ammo, so no crazy damage or sunder.
10 round detachable mag. Semiauto.

## Why It's Good For The Game

Marksman guns are a good balance between spray-n-pray and heavy "artillery"
Kinda Stylish gun many people love and think is cool.
## Changelog
:cl:
add: New Gun, magazine, spitework.

/:cl:

### CODE REVIEW

**Comment by KrabSpider** [comment]
This is pretty much the T-64 without burstfire and an even higher burst :|

**Comment by DeadliestDesire** [comment]
> This is pretty much the T-21 except its been built like its a marksman rifle.
> 
> 😐

Yep, pretty much. Its decent at any range, good at medium and long. Hits decently hard but not overkill.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
you modified all gun sprites in the dmi
image

**Comment by Kuro020** [comment]
also this should be a seasonal, I dont want more old meme guns in the standard vendor

**Comment by DeadliestDesire** [comment]
> you modified all gun sprites in the dmi image

@Kuro020  I have zero idea how I managed to do that. Maybe cause I had quite an outdated build, I wasn't working on it for a while.

**Pull request closed without merging**
