### PR TITLE
Tadpole no longer considered MARINE_BASE

### PR DESCRIPTION
**Pull request by Runian**
## About The Pull Request
The Tadpole no longer has the area tag of MARINE_BASE. The effects of this is that:
- AI can directly rail gun on it (as long it is still ground side).
- Ranged weeding abilities can be used on it.
- Wraith can place portals on it.

Wraith portals are deleted if they change z-levels.

## Why It's Good For The Game
I've noticed that everything valuable imaginable is always left on the floor of the TAD and believes that nothing bad can happen to it outside of a marine stealing or placing it on the very edge where an xeno can acid it. Dead xenos, stacks of building metals, unplaced turrets, grenade boxes full of razorwire, and even the occasional SADAR or ZX. Even Corpsmen prefer to revive people on the TAD ontop of billions of items instead one tile away at a clean spot when they see a Wraith. I think that these marines should put a little more thought into where they leave their items instead of dropping all of their valuable garbage on the floor.

## Changelog
:cl:
balance: Tadpole is no longer considered as MARINE_BASE. This means: the AI can directly railgun it, Wraiths can portal onto it, and the Hivemind's ranged weed ability to be used on it.
balance: Wraith portals are automatically destroyed if they change z-levels.
fix: Placing a new portal as a Wraith after your portals were exploded no longer gives an error message.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Wraith can already drag blink items and marines out of tad.

Don't think spoon-feeding an already good caste is the way to go.

Hivemind and wraith portals aren't meant to be placed on tad because of how boring the gameplay loop of cheesing it is. It's almost as if these restrictions were made for a reason...

**Comment by Arturlang** [comment]
To be honest wraith being unable to portal into FOB makes it unable to assist in FOB attacks at all and completely gimps it in that situation, TAD's are not so bad since you can just make a portal right outside

**Comment by Runian** [comment]
> Wraith can already drag blink items and marines out of tad.
Grabs are effectively canceled if they take even one point of damage, every TAD has at least one sentry, and many marines are now packing shotguns (due to the free 1-tile aim mode) which can chain-stagger a Wraith to death. I doubt a Wraith can pull that off unless someone fell asleep at their computer.

> Hivemind and Wraith portals aren't meant to be placed on tad because of how boring the gameplay loop of cheesing it is. It's almost as if these restrictions were made for a reason...
That was the given reason for why FOB is anti-Hivemind/Wraith, not the TAD. The reason why the Wraith was disallowed from placing their portals on the TAD/Alamo was because the portals could link from the ground side to ship side. This PR prevents that.

**Comment by Naaanii** [comment]
> > Wraith can already drag blink items and marines out of tad.
> 
> Grabs are effectively canceled if they take even one point of damage, every TAD has at least one sentry, and many marines are now packing shotguns (due to the free 1-tile aim mode) which can chain-stagger a Wraith to death. I doubt a Wraith can pull that off unless someone fell asleep at their computer.
> 
Timeshift and allowing portals on tad makes it pretty much risk free. A single marine (The TO) can easily be banished and sentries are mainly on the front which wraiths can blink past. Its only counter is to nade the portal on the tad which a wraith can quite easily use to make marines nade the tad itself.
> > Hivemind and Wraith portals aren't meant to be placed on tad because of how boring the gameplay loop of cheesing it is. It's almost as if these restrictions were made for a reason...
> 
> That was the given reason for why FOB is anti-Hivemind/Wraith, not the TAD. The reason why the Wraith was disallowed from placing their portals on the TAD/Alamo was because the portals could link from the ground side to ship side. This PR prevents that.
 
Tad inherits it from the Canterbury and not Alamo so again it's not really to prevent Z level portalling but to prevent the very sort of mechanics you're trying to promote and given that tad isn't meant to have any sort of cades or viable defences outside of a sentry and defences places **outside** the tad, makes it even more unfair to allow portalling onto it.

And again, allowing hive mind to just spam weed and wall onto the tad promotes even more uninteresting or frustrating gameplay loops which is why there are unweedable zones to begin with.

**Comment by iforgotmeword** [comment]
Know what? Sure just sure I don't see how this could make tad more unusable then it already is

**Comment by Mannybrado** [comment]
It's worth testing. Will make the standard tad much more appealing compared to the big one but whatever.

**Comment by SimplySmiley123** [comment]
> It's worth testing. Will make the standard tad much more appealing compared to the big one but whatever.
> 
> I don't think it will have as much impact as people are saying. Well, that is, once someone in here eventually stops explicitly playing wraith to banish items on the tad to bring attention to the pr and then never play wraith again.

You already have no reasons to pick bigger tads.
There is no incentive already to pick the bigger tads.

**Comment by Mannybrado** [comment]
> > It's worth testing. Will make the standard tad much more appealing compared to the big one but whatever.
> > I don't think it will have as much impact as people are saying. Well, that is, once someone in here eventually stops explicitly playing wraith to banish items on the tad to bring attention to the pr and then never play wraith again.
> 
> You already have no reasons to pick bigger tads. There is no incentive already to pick the bigger tads.

When I mean big one I mean the outrider, which is good for vehicles as an alternative in the case you want to put a bunch of sentries on the tad, as otherwise there isnt any space. Also it can be used as an indestructible wall which is insanely powerful on some maps, letting you hold spots you otherwise would never be able to due to crushers.

The other models are always worse, though. They are too big and too exposed at the same time.

**Comment by Kuro020** [comment]
Unecessary nerf to tad, when it already has received the only nerfs I thought it needed, no from me

**Pull request closed without merging**
