### PR TITLE
Halloween Present: Add Dashe armor to UNITE THE REALMS

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Sprites made by Fitz

linkueihd

Kuro approves

image

## Why It's Good For The Game

https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/af3eae4c-29d9-4ef4-8557-edbad1494fd2

also, good costume for halloween when people can't buy funny costume

## Changelog

:cl: novaepee, Fitz
add: new armor called Dashe for marines to use; find it in the Style line tab in surplus armor vendor
/:cl:

### CODE REVIEW

**Comment by thatguythere03** [comment]
My name is Fitz Sholl and I approve this message.

**Comment by ilikesaying** [comment]
### **_GLORY TO THE LIN KUEI_**

**Review by TiviPlus — APPROVED** [review]
I thought this was gonna be mlp when I saw the title

**Comment by Mrrpip** [comment]
### **_GLORY TO THE LIN KUEI_**

**Comment by Kuro020** [comment]
my campaign to make the milsim crowd xope continues

**Pull request merged**
