### PR TITLE
Akimbo refactor

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

When in akimbo, you'll shoot guns in your hand alternatively. This cause akimbo to give a ~150% dps increase rather than the current 200%. This dps increase % is changeable by gun, for maximum balancing possibilities. 

Does happens when in automatic fire mode.

Remove storage limitation on guns (max 3 pistol per storage) because akimbo might be 

Also remove akimbo accuracy maluses because T90 akimbo is fun

## Why It's Good For The Game

Pistol akimbo maybe balanced

## Changelog
:cl:
balance: Akimbo refactor, you shoot guns alternatively
balance; Akimbo accuracy maluses removed
balance: Remove storage limitation on guns
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
do you actually shoot one after the another or is it just same as shooting one ? if so its same as just not akimboing

**Comment by BrandonSmith6** [comment]
What's the fire rate gonna be like if you have 2 revolvers and you spam them? How much lower rpm total?

**Comment by Lumipharon** [comment]
Yeah this is really, really bad.
The akimbo modifiers meant you had massive scatter, so actually landing shots outside of pointblank was... unreliable. removing this gives you a huge DPS buff, with no drawbacks. You run faster due to not wielding, and your scatter stays low so you can just spam full auto. Marines can pretty much outrun benos as it is.

**Comment by UntoldTactics** [comment]
This is shit. Simple and plain, dual akimbo should be a funny gimmick that MIGHT be good if your good. At the moment its game breaking easy to melt any xeno without them being able to do shit about it unless they're a runner. Anything else will die after they use their stun, you'd melt a rav after they ravage you, you'd melt a shrike or whatnot and you'd certainly melt a hunter.

**Comment by BraveMole** [comment]
This is an akimbo pistol NERF. 

I don't know what you are smoking people

**Pull request merged**
