### PR TITLE
Restats the slash damage of nearly every caste in the game.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Redoes almost every castes damage to fit the homogenized armor in #4434. 
Every caste has 2 tiers of damage they have, 1 at young and 1 at elder.
Most of this is done assuming 50% armor.
tm with #4434 

## Why It's Good For The Game
Better balance.

## Changelog
:cl:
balance: Every caste has their slash damage redone to fit the new homogenized armor. Slash damage now has two tiers, one at young and one at elder.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -23. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by RenGusta** [comment]
He did literally double the values stated in the document, do not test merge

**Comment by davidchan13** [comment]
These are some pretty heavy nerfs and most marines are capable of getting 60+ melee armor.

**Comment by Hathkar** [comment]
This needs some fixing. Multiple xenos lose damage going from elder to ancient, and some have a large jump up in damage, like sentinel. 17 damage at elder, 27 at ancient.

**Comment by Pariah919** [comment]
done

**Comment by davidchan13** [comment]
Imagine nerfing marine armor and claiming you'll nerf xeno slash to compensate, then not touching xeno stam tackles.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-26). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Hathkar** [comment]
Stamina damage from tackles probably could use another passover as well, since armor was changed.

**Pull request merged**
