### PR TITLE
Turns Ice Caves into their own areas on Ice colony , Gives them the deep underground flag.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
(unsure if this counts as a rebalance or fix )
Makes 3 new areas , South-eastern ice caves , Western ice caves and north western ice caves.

## Why It's Good For The Game

Misleading for the player to be in a cave visually ,but still be capable of being OB'ed , also fixes tadpole landing in unintended spots.

## Changelog
:cl:
add:  Turned Ice Caves on Ice Colony into their own areas and they are now considered deep caves.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by XSlayer300** [comment]
image

**Comment by Wayland-Smithy** [comment]
Tags wrong, CL should say fix: and not add: @XSlayer300

**Comment by SkeletalElite** [comment]
Even if you consider it a feature/balance change it should probably get an exception because this being the only way to reach the tadpole and a miner is really just not good.

chadpole fort

**Review by Hughgent — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-13). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
