### PR TITLE
Makes lay egg plant the egg directly.

### PR DESCRIPTION
**Pull request by Pill-U**
Remove the retrieve egg ability. Rewrite lay egg to plant eggs.

## About The Pull Request
Using the lay egg ability now plants the egg directly on the ground ass BraveMole requested.
Removes carriers retrieve egg ability as it's useless with this PR.
Removes the egg item.

## Why It's Good For The Game
Having to pick up and plant and egg after laying it is just extra work.

## Changelog
:cl:
del: Remove carriers retrieve egg ability
del: Remove egg item.
qol: Lay egg now plants the egg on the ground
/:cl:

### CODE REVIEW

**Comment by Pill-U** [comment]
4 unsuccessful checks off to a great start, eh?

**Comment by Pill-U** [comment]
Let me know if 
/obj/item/xeno_egg/get_xeno_hivenumber() from hive_datum.dm
is a bad idea cause I have no idea

**Review by BraveMole — APPROVED** [review]

**Comment by SilencedMP5A5** [comment]
rip corrupted xenos

**Comment by bowlofcereal** [comment]
well there goes corrupted being able to be gotten legit, at the very least researchers now have a legitimate job these days besides crying in their office

**Pull request merged**
