### PR TITLE
Get rid of AS macro

### PR DESCRIPTION
**Pull request by vvvv-vvvv**
## About The Pull Request

This macro stopped being relevant a long time ago. MIN_COMPILER_BUILD is 1584 but AS checks for <1540
Used `git grep -l 'AS' code | xargs sed -i 's/\bAS\b/as anything/g`

## Changelog

:cl:
code: AS macro is removed
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Doesn't hurt to have it, plus its less typing than typing out `as anything`

**Comment by Lumipharon** [comment]
We'll keep AS, it's convenient and frequently used shorthand tbh

**Comment by ivanmixo** [comment]
> It causes inconsistencies. If you want to keep it it should be moved out of byond_version_compat.dm

How come? It's still technically compatibility and it doesn't cost us a thing to keep it so.

**Comment by TiviPlus** [comment]
> We'll keep AS, it's convenient and frequently used shorthand tbh

Agree

**Comment by Joe13413** [comment]
heehee ass macro

**Pull request closed without merging**
