### PR TITLE
Arrowhead no longer has slowdown.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Removes the slowdown off Arrowhead, the energy shield module.

## Why It's Good For The Game
Its currently pretty bad, it drops you down 2 armor levels and has slowdown making it difficult to use at all other than tanking spits and mimir is better at that.

## Changelog
:cl:
balance: Arrowhead no longer has slowdown.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
get rid of the funny pointless negative bullet armour.

**Comment by Losenis** [comment]
The funny pointless negative bullet armor was put in place due to it having free health regen that everyone and their mother would pick back in the day for a free module to invalidate any caste that couldn't just land more than 2 or 3 hits on your without having to run.

Which is every caste if you're surrounded by ungas on aim mode.

**Comment by Lumipharon** [comment]
Xenos don't shoot bullets

**Comment by Al-1ce** [comment]
> Xenos don't shoot bullets

But SOM does.

**Comment by Lumipharon** [comment]
> > Xenos don't shoot bullets
> 
> But SOM does.

Yes, and I added it to combat patrol prenerf, so it was a guh change and wasn't intended from my perspective.

**Comment by Losenis** [comment]
> Xenos don't shoot bullets

lmao I missed the bullet part, my bad

~~inb4 preemptive gun xeno buff~~

**Comment by FosterGrime-Heymynameslouie** [comment]
I think this would make shield better at its intended role (back line support)

with its negative armor on literally everything encouraging you to do backline activities instead of sticking around too long at front for an extended period of time making you not as slow as a snail kinda makes sense for scout/backline support roles it's now intended to have.

spedeb merhred

**Comment by Al-1ce** [comment]
Agree ^

**Pull request merged**
