### PR TITLE
Bluesummers Wreck Site [NEW MAP]

### PR DESCRIPTION
**Pull request by blackdav123**
## About The Pull Request
The HMS Bluesummers was once a high-end spacecraft set to colonize new stars. The wreckage now lies scattered across a desert planet.
bluesummers

StrongDMM-2024-09-22 00 27 32

<details>
  <summary>Experience The Bluesummers!</summary>
Skip the boring parts of spacetravel with our state-of-the-art cryosleep facility!
cyropods

Eat foods prepared by our crew of talented chefs!
kitchen

Utilize our full-sized nature simulation dome!
recdome

Enjoy all the luxuries of home with our industrial fabrication wing!
industrialwing

Travel without any worries, only on the HMS Bluesummers!
cryolab
</details>

## Why It's Good For The Game
New map hooray!
## Changelog
:cl:
add: Added Bluesummers Wreck Site, a new map.
add: Added broken and bloodied tube props.
add: Added an uncommon (25%) motorbike spawner.
add: Added paper map and album props.
add: Added free access engi door variants.
add: Added a chestbursted SOM corpse.
add: Greenglow no longer deletes itself, and now glows green.
add: Added bluegreen lights.
fix: drought/cave/deep now use the correct sprite.
fix: Fixed and added centerfuge sprites.
fix: Centered the Joshua Tree sprite.
fix: Glass engi airlocks are no longer opaque.
fix: Fixed autosmooth mainship window frame sprites.
fix: Vialboxes now update sprite properly.
fix: Fixed broken disposal pipe sprite.
fix: Cryofeeds will now layer under objects.
spellcheck: Edited prison station paper names.
spellcheck: Edited mining car description and names.
remove: Kutjevo is no longer a crash map.
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
didn't make it that far, but from the tiny portion of the map that was seen it seems fine.

**Comment by ivanmixo** [comment]
This map is insanely xeno sided, I'd argue even moreso than even prison was. Marines have no wide open areas for breathing room, every disk is an enclosed building surrounded by tight streets which gives xenos an insane amount of skirmish/harrass options from all angles at all times. 

The disks are also very awkwardly placed in relation to nuke, you have to run across the entire map when doing disks because they're in a triangle pattern with nuke being at the top. You cannot do disks in any sort of serial order, your only option is doing the middle disk last if you want to have a realistic chance of getting to the nuke after doing the last disk (which as I said requires you to do the disks on opposite sides of the map first).

The northern disk is a nightmare by itself and I think it's probably the most marine hostile disk I've ever seen on any map, not even prisons northeast disk was this hostile to being pushed (and you cannot OB it because it is in caves).

**Comment by Looking4bros** [comment]
Bluesummers cade invisibility

Liking the map so far, But in the Cyrosleep area with the central disk, north west of engineering has an issue with it's... alpha i think. It hides Barricades. see attached.

**Comment by Pariah919** [comment]
More or less agree with ivan here. You're kind of fucked as marine in every moment to moment movement on this map. Even with how scuffed map flow is right now you're more or less fighting against the map at every moment while xenos are feasting on you. Needs more open space and probably a new disk loadout else I can see this going to the bottom of the map pool.

**Pull request merged**
