### PR TITLE
Hivemind open resin doors with alt click

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Title

## Why It's Good For The Game

Mostly fluff, i don't see why hivemind should not be able to do that. Goes will with the other door rebanlance. Can maybe lead to funny turret resin door trap

## Changelog
:cl:
add: Hivemind open resin doors with alt click
/:cl:

### CODE REVIEW

**Comment by BlueHNT** [comment]
That would make for very funny trap option and assists of xeno to the hivemind. I'm all for it

**Review by TiviPlus — APPROVED** [review]

**Review by SplinterGP — CHANGES_REQUESTED** [review]
sounds like very frustrating to play against and hivemind doens't need to open doors to walk around, state a better reason more than "might be good/funny"

**Comment by SplinterGP** [comment]
Okay, just make it have a cooldown

**Review by TiviPlus — APPROVED** [review]

**Comment by DerrickChamberlain** [comment]
When will we have a AI, Hivemind battle!

**Pull request merged**
