### PR TITLE
droppods have coolsprites

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image
these are off center by a pixel so have fun

## Why It's Good For The Game
cool stuff

## Changelog
:cl: Daytona
add: Added new dropped sprites
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -117. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Chaznoodles** [comment]
image

**Comment by ilikesaying** [comment]
11P

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-127). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
