### PR TITLE
 removed PCs ability to cut most terrain

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Removes Plasmacutter's ability to qelete terrain.

Doubles PC charge so it can focus on dealing with resin walls.
Interaction with metal and rwalls untouched.
## Why It's Good For The Game
Fixes the real issues with plasmacutters and helps them focus on dealing with Xeno structures instead of terrain in general.
## Changelog
:cl:
balance: removed PCs ability to cut most terrain
balance: doubled base PC charge
/:cl:

### CODE REVIEW

**Comment by MiniMeatwad** [comment]
Yes, now it can be properly balanced for destroying resin walls, instead of an indestructible terrain clearer

**Comment by Mechswordsman** [comment]
Widen more bullshit chokes, or remove the roof on them then. IT'll make some maps have spots that cannot be pushed, ever.

**Comment by Naaanii** [comment]
> Widen more bullshit chokes, or remove the roof on them then. IT'll make some maps have spots that cannot be pushed, ever.

Would be a mapper issue but yeah, they're working on removing death chokes or badly made terrain.

(Ironically learned that some CAS missles can destroy terrain even PC can't)

**Comment by XElectricX** [comment]
Instead of removing functionality and strategy, let Drone and Hivelord dig through rock as well. Balance.

**Comment by Al-1ce** [comment]
> Instead of removing functionality and strategy, let Drone and Hivelord dig through rock as well. Balance.

100% this.

**Comment by lbnesquik** [comment]
Hm. Hefty balance change. Not sure what I think on this, besides that this isn't light.

**Comment by Aporhtonoma** [comment]
i mean we already got terain that cannot be cut with pcs so just update map accordingly

**Comment by carlarctg** [comment]
..why not split it into two? a drill to pierce through terrain, and the plasma cutter for breaking down resin walls? this way both can be balanced appropiately

you could also have the plasma cutter have 'terrain' and 'resin' modes, and the terrain mode would draw from a hard-to-obtain battery, this would let it keep that feature and have it be balanced differently without impacting resin wall clearing

**Comment by SiegeB0t** [comment]
I'm not a fan of this change unless c4 gets a decent buff and req point reduction. It is weird to remove a common strategy for dealing with chokes and place the responsibility of making gameplay fun to mapping.

**Comment by bowlofcereal** [comment]
Breaking_Bad_Ozymandias

**Comment by Naaanii** [comment]
> Breaking_Bad_Ozymandias

sandbox is dead

**Comment by Redrover1760** [comment]
Literally 1984

**Comment by Loldaddy5676** [comment]
just allow xenos to break terrain as well.

**Comment by FosterGrime-Heymynameslouie** [comment]
uniornically allowing xenos to dig through walls with hivelord and maybe drone n queen would be more fun for both sides

**Comment by Oscari-pog** [comment]
stealth reopen

**Comment by Derrick2Electricboogaloo** [comment]
This is still grunge as fuck

**Comment by Coastfront** [comment]
Oh how the echoes of a choir deaf to their tone further still bring only contempt along an audience.

This was bad when it was closed and its still bad now that its reopened.

**Comment by Mannybrado** [comment]
now that mechs are a thing this PR is a lot better. you can push a choke with a mech without a problem, if they're being supported. deleting 90% of the map isn't fun... neither is fighting mechs, but at least mechs are cooler.

**Comment by Derrick2Electricboogaloo** [comment]
Yeah github bot. Close this nonsense. Good bot.

**Pull request closed without merging**
