### PR TITLE
Synthetic spawns with high-capacity industrial blowtorch

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

As promised in https://github.com/tgstation/TerraGov-Marine-Corps/pull/8892, I shall give synthetics the high-capacity industrial blowtorch in spawn so that they have QoL and show that contributors observe. Engineers have to buy one for 15 points, but since synthetic is dedicated support role, they need all the help they need. No sane synthetic would give away the high-capacity industrial blowtorch to any engineer.

## Changelog
:cl:
qol: Synthetic spawns with high-capacity industrial blowtorch
/:cl:

### CODE REVIEW

**Review by BraveMole — APPROVED** [review]

**Comment by Losenis** [comment]
Based

**Comment by Pill-U** [comment]
ok good now spawn me with janitorial supplies so I can fully immerse myself and RP as an unpaid janny

**Comment by novaepee** [comment]
> ok good now spawn me with janitorial supplies so I can fully immerse myself and RP as an unpaid janny

HMMM

**Comment by BraveMole** [comment]
@TiviPlus @David-Stormwell  can i get your opinion on this ?

**Comment by David-Stormwell** [comment]
There shouldn't be much of a problem since you can get this item if you want it from just a out any map, as long as it has a engineering room or autolathe.

**Pull request merged**
