### PR TITLE
Lets marine use bump attacks.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request

Gives marines the same bump attacks that xenos can use . Only works if you are carrying a gun and yes it will PB.
## Why It's Good For The Game

1. Fixes runners being unhittable to some degree
2. Same to the hunter

 Still got to add custom marine sprites for the button..
## Changelog
:cl:
add: Marines now have the reflexes enchanced , and now can PB by simply bumping into xenos.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -18. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Jeff-jefferson-jeffery** [comment]
Oh god.

**Comment by lKiseki** [comment]
This is, in fact, a nerf to rounies and hunters, because it means you can just WASD dance with them and not have to sit there taking like 10 slashes per Evasion use. This also makes point blanking much easier (especially with how mobile xenos can be), and although it's my own opinion on this one, using WASD to melee is quite fun! Gimme gimme gimme.

In the future, assuming this is approved, it could also be implemented to melee weapons such as machetes, powerfists, and so on...

**Comment by Pariah919** [comment]
finally i can nerf shotguns

But also, god no please no

**Comment by SilencedMP5A5** [comment]
LOL

**Comment by AdamElTablawy** [comment]
awful idea

**Comment by ilikesaying** [comment]
please no movespam combat

**Comment by AbsoluteJerry** [comment]
This shit is gonna be fucking awesome.

The FF logs! The Ahelps! I will cry of joy and sadness

**Comment by ondrej008** [comment]
speedmerge this

**Comment by Chaznoodles** [comment]
Just end this hell and turn us all into simplemobs who can only bump attack

**Comment by Losenis** [comment]
At first I thought this was melee only and would give a nice incentive to pick bayonets, but PB? Damn son, tadpole will be 60% casualties before it even touches the planet.

**Comment by MLGTASTICa** [comment]
Just so you all know , you cannot trigger the bump attack on friendlies.

**Comment by TiviPlus** [comment]
Funny, but balance wise and FF wise too much to handle

**Pull request closed without merging**
