### PR TITLE
Flares are now infinite.

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request
makes flares infinite

## Why It's Good For The Game
because i want significantly more flares. there are not enough flares for my tastes.

## Changelog
:cl:
balance: infinite flares.
/:cl:

### CODE REVIEW

**Comment by vilereaver41** [comment]
Hurp derp

**Comment by usnpeepoo** [comment]
this is dumb, and the reasoning makes no sense

**Comment by Pariah919** [comment]
i mean like 200 is already pretty much infinite flares

**Comment by BraveMole** [comment]
Dis was already denied by tivi. Good luck

**Comment by godspeedfunnyman** [comment]
Test merge it for one round

**Comment by TiviPlus** [comment]
> Dis was already denied by tivi. Good luck

**Pull request closed without merging**
