### PR TITLE
CMO buff

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Gives the CMO master surgery skill.
Increases all Max Surgery step durations by 20.
Lowers all Min Surgery step durations by 20.
## Why It's Good For The Game
The chief should be the best at his art. (Would also be funny to see master level surgery implemented.)
## Changelog
:cl:
balance: CMO now has master level medical and surgery.
balance: Increases all Max Surgery step durations by 20.
balance: Lowers all Min Surgery step durations by 20.
edit: Updates some codex stuff to be more accurate.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
> Does this do literally anything at all, given a good few skill checks were based on fumbling if under a certain level rather than buffing if over a threshold?

It's slightly slower lol.

**Comment by Losenis** [comment]
>It's slightly slower lol.

Wait it's a nerf then?

**Comment by Naaanii** [comment]
> > It's slightly slower lol.
> 
> Wait it's a nerf then?

Yes 

> > It's slightly slower lol.
> 
> Wait it's a nerf then?

Wait, wrong PR lol.

This is a buff, it makes surgery quite fast. <s>Probably instant</s>

**Comment by Naaanii** [comment]
> > > It's slightly slower lol.
> > 
> > 
> > Wait it's a nerf then?
> 
> Yes
> 
> > > It's slightly slower lol.
> > 
> > 
> > Wait it's a nerf then?
> 
> Wait, wrong PR lol.
> 
> This is a buff, it makes surgery quite fast. Probably instant

After testing, it's not instant but slightly faster.

**Comment by yyzsong** [comment]
CMO players stay winning

**Review by TiviPlus — APPROVED** [review]

**Comment by Naaanii** [comment]
> I don't really see the point in buffing CMO, and I really don't see the point in increasing the delay variance by 4 seconds for everything.

Better consistency.

CSE is by far the best engineer. FC/Captain as leaders. CMO should be the best at surgery by a certain margin, along with synth too I suppose.

>  Also there are undocumented changes in this pr.

I made this alongside the MR PR guhh. I'll document the rest.

**Comment by QualityVan** [comment]
That doesn't change how much better 3 skill is than 2 though. Scale up the skill time reduction (optionally with a default duration increase) or add other effects to it if your goal is increased disparity.

**Comment by Losenis** [comment]
>Buff
>But also nerfs other things

bruh

**Comment by Naaanii** [comment]
Made a simpler PR #12505

**Pull request closed without merging**
