### PR TITLE
deletes flavor text and its safe files

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
flavor text is a pointless thing that nobody will ever use seriously, and the server is vastly better off with it being removed so I stop having to read about peoples waifu when examing them while i loot their decapitated corpse after they got fragged for being bad

## Why It's Good For The Game
nobody has ever used this seriously

## Changelog
:cl:
del: Removed character description
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -221. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by ilikesaying** [comment]
cassie

**Comment by davidchan13** [comment]
> B-but muh snowflake!!

Just kidding, good riddance, and begone.

**Comment by BeloneX** [comment]
Pariah: Screams about how it would be LRP to add skirts and how they would lead to the server becoming an NRP shithole.
Also Pariah: Deletes one of the few roleplay mechanics on TGMC.

**Comment by XSlayer300** [comment]
Either that or just simply cover it up by one simple "[Character Description]" button.

**Comment by David-Stormwell** [comment]
I'm gonna miss seeing some of these crazy discs

**Comment by bowlofcereal** [comment]
no

**Comment by TG-Eris** [comment]
Does it really hurt anything having it in?  We already have basically no RP on the server, I don't really see the harm in keeping it unless we're getting some benefit.  Why not just add a maximum character limit that's fairly low to prevent the kind of things that _ilikesaying_ sent an image of.  If you can't describe your character's physical appearance satisfactorily with a line or two then you're probably overcomplicating things.

**Comment by TiviPlus** [comment]
Admins not checking flavortext is a policy issue

**Pull request closed without merging**
