### PR TITLE
Losing armor grants speed

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Adds a movespeed modifier, for Tier 3+ xenos only, that represents -0.4 * % of armor sundered to `adjust_sunder` and `set_sunder` procs.

## Why It's Good For The Game

Sunder should have sticking power so I hear, but it's pretty unfun to deal with as a slow top tier xeno that can actually accumulate it unless there is an attentive hivelord or pack of drones supporting you. This makes the mechanic more engaging for both sides and much easier to still have fun with while not making it any less effective for punching through high armor.

Also I think it just makes sense that as their "chitinous armor plating" is whittled down by sunder the xenos can then move a little quicker until it regenerates.

## Changelog
:cl:
balance: Sunder inversely grants move speed to Tier 3+ xenos up to -0.4 at 100%, the default weed speed mod.
/:cl:

### CODE REVIEW

**Comment by David-Stormwell** [comment]
Nerf to most higher sundering weapons, Lasers, RRs any DMR bullet guns possibly more.

**Comment by Skycave1** [comment]
Dude, Xenos lost three rounds today. The queen isn't going to go out with you.

**Comment by BraveMole** [comment]
Eh, this is bold. 

It could be interesting

**Comment by BraveMole** [comment]
Eh, this is bold. 

It could be interesting

**Comment by davidchan13** [comment]
Ravs and rounies angrily shrieking at the hivelord for healbeaming them. This could be funny.

**Comment by Wayland-Smithy** [comment]
> shrieking at the hivelord for healbeaming them

image

Rav? I very much doubt that. Runners maybe since they have crap armor to start with (10 at mature) so they potentially get the best returns if they an manage to "farm" sunder without getting killed.

If need be I'll restrict to Tier 3+ or even to specific tanky castes whos armor is supposed to make up for their lack of speed.

**Comment by Pariah919** [comment]
this is almost as silly as run stamina
tm it

**Comment by Wayland-Smithy** [comment]
Most of the slow tank xenos I really want to be affected by this are T3 or above anyway, sorry defender.

**Comment by Al-1ce** [comment]
> Nerf to most higher sundering weapons, Lasers, RRs any DMR bullet guns possibly more.


How, exactly? The sunder is still applied, and the speed buff is incredibly minor & only applied to T3s.

**Comment by Al-1ce** [comment]
> Most of the slow tank xenos I really want to be affected by this are T3 or above anyway, sorry defender.

Would Bull be an exception?

**Comment by Wayland-Smithy** [comment]
I think bull is fast and low armor enough to be excluded here like the rest. It being able to be staggerd and knocked back (even when charging?) is something I am looking at which is out of scope for this PR.

**Comment by SolarMacharius** [comment]
As long as the speed boost is not to high, it could be an ok idea. I just hope it doesn't encourage xenos to play recklessly with busted armor. Also it makes the railgun even more useless.

**Comment by Ieteihowmee** [comment]
Xenos already fast as fuck, time to make them super sonic speed.

**Comment by Ieteihowmee** [comment]
More time for them to F-off, and not get punished for being stupid or greedy. Shame,

**Comment by Wayland-Smithy** [comment]
> super sonic speed.

Once again it is just weed speed, and only full weed speed at ZERO ARMOR

**Comment by SilencedMP5A5** [comment]
making xenos unkillable in essence

xenos being faster than marines with no armor, sprinting, means they can effectively never die if they just
y'know

leave

bad pr

**Comment by Wayland-Smithy** [comment]
> making xenos unkillable in essence

Omegalul, for the umpteenth time it's only for T3, only weed speed, and **only with 100% sunder** because it is **scaling.**

**Comment by Al-1ce** [comment]
> making xenos unkillable in essence


Are..are you serious? You do realize that in the vast majority of circumstances most xenos will be DEAD or very close to being dead by the time they actually get weed speed in terms of damage.


>xenos being faster than marines with no armor, sprinting, means they can effectively never die if they just


Marines can outspeed the vast majority of castes. I'm not trying to be rude but you should shut up if you have no idea what you're talking about.

**Comment by SplinterGP** [comment]
> Marines can outspeed the vast majority of castes. I'm not trying to be rude but you shouldn't slap a dislike if you have no idea what you're talking about. The marine speed TM was fine though, right?

not true except if youre running, and then depending of your armor might not as well

**Comment by SplinterGP** [comment]
dont really think this does anything to be noticeable enough by both sides so, i dont know how to check if this is actually balanced or not, i dont see much reasoning behind it since sunder is something to punish xenos.

**Comment by Wayland-Smithy** [comment]
I believe it's having the intended effect, from my own play as well as watching other T3+ xenos. Perhaps the max speed modifier should be 2x weed speed but also unable to stack with weeds. If you really want to come up with an excuse not to merge it even though anecdotally you think it does nothing and thus can not be a bad change I can't stop you.

**Comment by SplinterGP** [comment]
> 
> 
> I believe it's having the intended effect, from my own play as well as watching other T3+ xenos. Also I think it's still too early to tell. Stam buff was TM for what like 2 weeks?
> 
> Perhaps the max speed modifier should be 2x weed speed but also unable to stack with weeds. If you really want to come up with an excuse not to merge it even though anecdotally you think it does nothing and thus can not be a bad change I can't stop you.

i mean it DOES something but what i mean its hard to notice it ingame for both sides.

**Comment by SplinterGP** [comment]
i don't see much the point of this, T3 are really not needing buffs right now and move speed doenst seem like a right thing, unless tivi wants this i won't be mergeing it.

**Comment by Wayland-Smithy** [comment]
> T3

You mean Rav right? I can blacklist it.

**Comment by Wayland-Smithy** [comment]
Xeno buff? Not in my TGMC.

**Pull request closed without merging**
