### PR TITLE
Hivelord ability balancing

### PR DESCRIPTION
**Pull request by XElectricX**
## About The Pull Request

Sow (ability for making plants) becomes a base ability for the Hivelord. Healing Infusion becomes a primordial ability. Sow cooldown increased from 45 to 60. Tunneling ability cooldown is slashed from 120 to 60 seconds.

## Why It's Good For The Game

Sow is a really fantastic ability that fits Hivelord's theme, yet is locked to primordial. It rewards planning and playing for the long term, yet you cannot use it until mid or late game. Or never, if you don't get to the point of getting primordial'ed. Healing Infusion is also a great ability but makes more sense to keep that as a primordial. It's an ability that grants a powerful heal every 12 seconds. Primordial abilities tend to be major changes in how you can play a caste, which the Healing Infusion does.

Also the tunnel ability was on an incredibly long cooldown which makes it pretty bad for setting up large tunnel networks and using it on the fly.

## Changelog
:cl:
balance: Hivelord Dig Tunnel ability decreased from 120 to 60 secon cooldown.
balance: Hivelord Sow moved from primordial ability to base ability. Cooldown increased from 45 to 60 seconds.
balance: Hivelord Healing Infusion moved from base ability to primordial ability.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
> Healing beam neutered to primo
> Sow to 60 so that you can forget about it even more and miss the cooldowns

YOU FUCKING ANIMAL

**Comment by yyzsong** [comment]
>Hivelord gets to heal once every sixty seconds 
get out.

**Comment by zee11zee** [comment]
No stoop please, don't do this. Hive lord's current abilities don't need to change, its the balanced support class.

**Comment by bowlofcereal** [comment]
What fucking crack are you using, can I have some of that? What's the purpose in making a T2 worse than a T1?

The TGMC Github and its consequences have been an absolute disaster for the unga race, holy shit

**Comment by Al-1ce** [comment]
Are you sure this is the right repo, dude?

**Comment by Pariah919** [comment]
Hivelord has insanely bloated utility out of the box but this ain't the way to fix it chief.

**Comment by KillerOrcaCora** [comment]
The swap of the primo part is not really sticking with me and this consequently makes drone better then hivelord…

**Comment by FosterGrime-Heymynameslouie** [comment]
60 seems too much

maybe this pr would be okay if instead the plant ability was buffed to be something like 15 - 10 seconds or something

**Comment by XElectricX** [comment]
Fruit planting fits better than the dumb heal beam. If it's that big of an issue, it can always be buffed. Sow is a more interesting ability and rewards planning.

**Comment by Losenis** [comment]
"Fruit planting fits better than the dumb heal beam" Fruit planting wasn't a thing for 99% of the hivelord's existence

**Comment by Mannybrado** [comment]
I honestly like the idea behind this change. But 60 second CD? Bruh? No no no. This would honestly be a nerf in game. Like, where it matters.
A significantly more appropriate change would be something like this:
Instead of starting with Healing Infusion, Hivelord starts with Healing Salve. Hiverlord's primordial switches Healing Salve with Healing Infusion.
Hivelord starts with Sow, as this PR does. 60 second CD is appropriate if Hivelord keeps some for of healing as a supplement to Healing Infusion. If they didn't have it, it would be dogshit, which is why nobody likes this PR. I think a lot more people would if something like this suggestion was considered.

**Comment by Losenis** [comment]
Honestly, I'm having second thoughts about this because it means I'll be able to just maze the entire map before shutters open due to the free infinite plasma plants. But that'd be fucking cancerous to deal with as a marine if there's 2 or 3 hivelords with infinite plasma walling off the whole map.

**Comment by Coastfront** [comment]
The year is 2023
My eyes wearily are cast upon a field of wretched purple, as the look of nightshade paints the landscapes now marred visage

I take 3 steps from the shutters, the clatter of my tools the wardrums to my step, and 7 invisible warriors fracture my every limb
As my spirit looks along past every boundary, I stare in horror as I count the plasma plants, the armor restores, the healing plants.
And I can muster only but one word

"electric pr"

**Comment by Lumipharon** [comment]
I don't really get the reasoning behind the PR.
>Primordial abilities tend to be major changes in how you can play a caste, which the Healing Infusion does.

You can say the exact same thing about planting, but heal beam is fundamentally a much more key part of what a hivelord does.
Also you can be t2 primo before shutters even drop, go ree at your local queen.

**Pull request closed without merging**
