### PR TITLE
A new model for robot

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

https://user-images.githubusercontent.com/6610922/212421038-27dcde0a-b71e-42bd-a8a4-4860be0b92e8.mp4

Works with medhud and meson.

https://user-images.githubusercontent.com/6610922/212422037-9d0ec9b2-f931-49f2-849d-15c7588cb403.mp4

## Why It's Good For The Game

Adding a new model was inspirited by a spriter that we used to have in TGMC long ago named Jackie. I want to make sure that his vision of having another model for robot fulfilled.

## Changelog

:cl:
add: A new model for robot
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
~~fembot pr :)~~

**Comment by Helg2** [comment]
kek

**Comment by FosterGrime-Heymynameslouie** [comment]
womaen bot

**Comment by coldironwarrior** [comment]
please stop trying to put fetish content in the game

**Comment by Kuro020** [comment]
Cease and desist

**Comment by novaepee** [comment]
so sad

**Pull request closed without merging**
