### PR TITLE
SOM food [MDB ignore]

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
The most important PR I have ever made, speed merge pls.

Adds SOM specific food, with SOM flavors, in SOM food vendors, and replacing UPP snacks in loadouts.

image

Also makes it easier to change theme for vendors, if needed.

## Why It's Good For The Game
SOM brand food for SOM brand marines.

## Changelog
:cl:
add: The SOM have begun domestic food production to replace imported UPP rations
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
mapbot go home, you're drunk.

**Comment by bruhman8ghughug** [comment]
this changes everything

**Comment by Lumipharon** [comment]
99% sure mapbot is failing due to master code still having a name var without quotation marks, this pr should fix that.

**Comment by Al-1ce** [comment]
I dream of a world where every ERT faction will have their own MREs.

**Review by RipGrayson — APPROVED** [review]
There's nothing wrong with the mapping changes, mapdiffbot is just being dumb. Ignore it and pretend like the PR passed all checks (which it would have).

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
