### PR TITLE
No more Build-a-Sentry magnum

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

This build-a-sentry magnum is too good. Maintainer Lumi approves.

Sorry, gamer engineers, next time. Try a build-a-sentry flamethrower or tesla.

## Changelog

:cl:
del: remove the capability to have Build-a-Sentry magnum
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
GUH MY PR GOT COMBAT ROBOT NOISE AS WELL

**Comment by SilencedMP5A5** [comment]
it may be heresy to vouch for a revolver nerf but this is sadly necessary

but you know what else is cracked OP?

ravager :)

**Comment by Al-1ce** [comment]
> ravager is OP

maybe try not wearing a beret and the lightest armor possible o__o

**Comment by Oscari-pog** [comment]
Engineers should maybe instead Build-some-Bitches

**Review by Lumipharon — APPROVED** [review]

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Your changelog is illegible

**Comment by SilencedMP5A5** [comment]
> > ravager is OP
> 
> maybe try _not_ wearing a beret and the lightest armor possible o__o

the extra three seconds of being alive is surely worth the incredible slowdown i'm sure

**Comment by Al-1ce** [comment]
> the extra three seconds of being alive is surely worth the incredible slowdown i'm sure


Those extra three seconds are critical if you have allies to help you. But you're right. That's not exactly useful with a playstyle where you charge solo into the hive and get swarmed right away. 

Maybe reconsider your strategy?

**Pull request merged**
