### PR TITLE
Revert "Fixes Aim Mode fire rate debuff bypass."

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request
Reverts tgstation/TerraGov-Marine-Corps#5544

## Why It's Good For The Game
uhhhh

## Changelog
:cl:
balance: reverted unable to fire while wielding
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -25. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Review by SplinterGP — APPROVED** [review]
i'm okay with this because the changes that are being reverted(removes a very hard to do bypass that needs you to waste ammo to do) and then bugs weapons wielding causing them to not be able to shoot mid them, a proper fix on autofire and stuff would be good later

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Fix the bug

**Comment by SplinterGP** [comment]
> Fix the bug

wyci

**Comment by TiviPlus** [comment]
You will fix the bug without balance changes

**Comment by SplinterGP** [comment]
> You will fix the bug without balance changes



> You will fix the bug without balance changes

the bug made a balance change you nerd

**Comment by TiviPlus** [comment]
See merged doafter Pr and discord for correct fix

**Pull request closed without merging**
