### PR TITLE
bayoknife two-shots weeds

### PR DESCRIPTION
**Pull request by cheapcents**
## About The Pull Request

Bayoknives now deal as much damage as the combat knife, enough to destroy weed nodes in two hits

Combat knives can no longer be made into attachments using cable coil, but now fit inside your helmet. Because it is a small (not tiny) item, placing it in your helmet will occupy all storage slots in it and prevent you from putting anything else inside

## Why It's Good For The Game
image
This post was made before the sprites were changed, but the point still stands that some people just prefer some sprites over others, especially now that they look so different

This PR justifies both knives existing by giving them a specific characteristic over the other without taking away the core advantage that makes any knife even worth using, **killing the damned weed nodes**

Will you sacrifice space for potentially life saving hyper/dylo shots so that you can fit an MRE in your boot, will you use the bayoknife so you can change attachments on the fly, or are you just using one because you think it looks better? Doesn't matter, because both can be just as efficient as the other

## Changelog
:cl:
balance: combat knive now fits into your helmet, and can no longer be made into an attachment
balance: bayoknife now deals enough dmg to kill weed nodes in two hits
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Uhh no, we aren't making it a straight upgrade

**Comment by cheapcents** [comment]
> Uhh no, we aren't making it a straight upgrade

Currently, the combat knife is superior to any other knife in the game. It's the only one capable of two-shotting weeds, and its only disadvantage is that you need to use 5 cable coil pieces to turn it into an attachment. There is absolutely no reason to use any other knife if you intend to keep it in your boot.

This straight upgrade certainly isn't making it any better than what the combat knife already is.

**Comment by Lumipharon** [comment]
If you put cable on the combat knife, the damage goes down.
If you're carrying spare cable in case you want to turn a combat knife into a bayo, I uh, have no idea why you don't just have a bayo.
If you have a bayo on a gun, you two shot weeds already.

I'm not sure what the point of this is. Combat knife is basically just to 2 shot weeds where you can't/don't want to have a bayo on your gun.

**Comment by cheapcents** [comment]
> If you put cable on the combat knife, the damage goes down.
If you're carrying spare cable in case you want to turn a combat knife into a bayo, I uh, have no idea why you don't just have a bayo.
If you have a bayo on a gun, you two shot weeds already.

I agree. Why even have the bayo attachie and the bayoknife be different items, then? Why make an item specifically only to be held in your boots when you could just detach the bayoknife?

It's pointless, but this PR makes it a little less so. And even then, it barely affects balance while giving people the chance to choose their knives' "skin".

> I'm not sure what the point of this is.

What about the "Why It's Good For The Game" doesn't make what I think clear?

**Comment by Strayed-Raven** [comment]
Ahh once again a simple change causes so much controversy. Reminds me of the shoulder holster webbing being changed. Otherwise maybe agree that having the CM leftovers is bad and should just homogenize the melee options instead of grasping straws over keeping a difference between. Upvote from me

**Comment by Lumipharon** [comment]
Yeah I still don't see the point of this.

One is a item specifically meant to be used as a weapon, the other is meant to be an attachment that can also be used as a weapon. This is just buffing the bayo knife because ??

**Pull request closed without merging**
