### PR TITLE
replaces whatever the fp2000 masquarades as with a FAMAS

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Replaces the FP2000 with a FAMAS sprite from cold war (thanks Bimmer)
Gives it to freelancer medics and maybe Freelancer standards laster idk
It fires at a rate of 0.15 fire delay but only has 24 round magazines.
Replaced the one instance of an fp2000 with a famas on big red.

## Why It's Good For The Game
Guns more in style good, guns that are weird bad, guns are cool.
image

## Changelog
:cl:
add: Added new cool FAMAS.
del: Removed FP-2000, git will remember it. Nobody else will
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -55. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
need #5129 merged.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Whats the sprite licenced under

**Comment by Pariah919** [comment]
discussed the license issue on discord

**Comment by davidchan13** [comment]
FP2000 is based on the FN F2000, which is mostly, but not entirely, a P90 upscaled to 5.56 and the parallel magazine replaced with a more traditional bullpup style.

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-61). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
