### PR TITLE
Deletes Baneling.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Gets rid of Baneling.
## Why It's Good For The Game
This caste is absolutely awful to play against from a design perspective you cannot play against it in almost any form and if you have beat it you've likely already won or they placed their pod in an absolutely awful spot., if you care about my full 2 paragraph rant look below.

<details>

## The Bane of Lings

To preface why I'm removing Baneling from a design perspective, the caste breaks almost all precedence when it comes to gas, all the gas castes (save sent primo) have to highly risk themselves inorder to gas. Boiler has to root, Defiler has to fart and run up to marines.

Baneling? Baneling can just run in. If you die, you waste 2 minutes. Just run back! It doesn't matter that you die considering most rest cycles take equally if not longer under bad/decent conditions, and your pod is likely in the middle of the hive anyway!

This all leads to baneling being pretty much unbeatable from a marine perspective, if you shoot it it explodes, it comes back, it blows up again. If you shoot it far away it just comes back, you shoot it, it comes back again. It can be stacked infinitely and there's nothing you can do about it!

## Why

Why should it be removed? Why not leave it in for someone to rework it? Now we get into subjectiveness.

You can say this, but I disagree on the principle that other castes arguably in this limbo-like Bull and old!Sent aren't quite as game health breaking, primo bull was utterly busted but once it was fixed the caste faded back into the "waiting for rework" bin, but you can't do the same thing with baneling unless you make the caste literally unplayable like I am because the entire design is rotten from the very core due to being incredibly low risk in a game about risk/reward management due to its inherient nature as a PvP game.
</details>

## Changelog
:cl:
del: Removed the Baneling xeno caste.
/:cl:

### CODE REVIEW

**Comment by veterath** [comment]
god came down from the heavens to give us this pr

**Comment by bowlofcereal** [comment]
image

**Comment by Barnet2** [comment]
I KNEEL FOR MJP
Uh, on a serious note, I literally do not see any way to fix this caste from a fundamental standpoint. Even some maintainers have mentioned that it simply uh, it's not fun for _either side._

**Comment by KillerOrcaCora** [comment]
This Xeno was designed so you could watch youtube shorts during your TGMC games 10/10

**Comment by efzapa** [comment]
> I KNEEL FOR MJP
> Uh, on a serious note, I literally do not see any way to fix this caste from a fundamental standpoint. Even some maintainers have mentioned that it simply uh, it's not fun for _either side._

literally boiler but zero risk and you have to wait an hour between bursts

**Comment by Strayed-Raven** [comment]
Baneling is a good xeno caste. Give it some TLC and love and everything will work out just fine. Baneling fits into the cohesion for xenos to make the most out of Warlock and same with Behemoth. Just figure out how it will all come together with other multitude of xenos and you got one good xeno hive comp. JUST DO IT

**Comment by bowlofcereal** [comment]
> Baneling is a good xeno caste. Give it some TLC and love and everything will work out just fine. Baneling fits into the cohesion for xenos to make the most out of Warlock and same with Behemoth. Just figure out how it will all come together with other multitude of xenos and you got one good xeno hive comp. JUST DO IT

just rework it bro just rework it!!

bro how? its literally just a suicide bomb

**Comment by Strayed-Raven** [comment]
> > Baneling is a good xeno caste. Give it some TLC and love and everything will work out just fine. Baneling fits into the cohesion for xenos to make the most out of Warlock and same with Behemoth. Just figure out how it will all come together with other multitude of xenos and you got one good xeno hive comp. JUST DO IT
> 
> just rework it bro just rework it!!
> 
> bro how? its literally just a suicide bomb

Simple. With the same passion as Zaro. You just gotta find someone that has good Baneling sense like his Widow sense. Seriously i do not see why it should be removed. A way to deal damage to marines that does not involve putting yourself at risk is a good siege breaker. Am I the only one who understands the complexities of this ambitious gameplay masterpiece?

**Comment by AlexCrimson** [comment]
>just rework it bro just rework it!!
>
>bro how? its literally just a suicide bomb

Just make it a shitty Defiler. No AoE gas, no respawns, just melee injects Defiler toxins, and abilities that enable it to do so.

**Comment by yyzsong** [comment]
> Simple. With the same passion as Zaro. You just gotta find someone that has good Baneling sense like his Widow sense. Seriously i do not see why it should be removed. A way to deal damage to marines that does not involve putting yourself at risk is a good siege breaker. Am I the only one who understands the complexities of this ambitious gameplay masterpiece?

"Just rework it bro just rework it!!"
"How?"
"Very carefully"

lol. If you wanna advocate for keeping baneling in the game bring up an idea (a good one) or make the PR yourself. As it is right now, baneling is *objectively* a shitty caste to play against and "Removal" essentially just removes its ability to be evolved to. The code will still exist in the records of the github for anyone to pick up and use later, but you're acting like we're tossing out the concept as a whole and barring anyone from readding it, ever.

**Comment by Mrrpip** [comment]
So uh...Where's the two paragraph rant? I wanted to see it. ):

**Comment by Strayed-Raven** [comment]
> > Simple. With the same passion as Zaro. You just gotta find someone that has good Baneling sense like his Widow sense. Seriously i do not see why it should be removed. A way to deal damage to marines that does not involve putting yourself at risk is a good siege breaker. Am I the only one who understands the complexities of this ambitious gameplay masterpiece?
> 
> "Just rework it bro just rework it!!" "How?" "Very carefully"
> 
> lol. If you wanna advocate for keeping baneling in the game bring up an idea (a good one) or make the PR yourself. As it is right now, baneling is _objectively_ a shitty caste to play against and "Removal" essentially just removes its ability to be evolved to. The code will still exist in the records of the github for anyone to pick up and use later, but you're acting like we're tossing out the concept as a whole and barring anyone from readding it, ever.

Remember Mech. Technically speaking it's code is not gone either but you do not see anyone picking that up. We do not make shitty castes you know that right? The real answer is to rework it, not remove. improve, not some simple single line change. If you do not act now it will be consigned to a hellish limbo. Can you really accept that?

**Comment by Zar000** [comment]
:-(

**Comment by ilikesaying** [comment]
> > > Simple. With the same passion as Zaro. You just gotta find someone that has good Baneling sense like his Widow sense. Seriously i do not see why it should be removed. A way to deal damage to marines that does not involve putting yourself at risk is a good siege breaker. Am I the only one who understands the complexities of this ambitious gameplay masterpiece?
> > 
> > 
> > "Just rework it bro just rework it!!" "How?" "Very carefully"
> > lol. If you wanna advocate for keeping baneling in the game bring up an idea (a good one) or make the PR yourself. As it is right now, baneling is _objectively_ a shitty caste to play against and "Removal" essentially just removes its ability to be evolved to. The code will still exist in the records of the github for anyone to pick up and use later, but you're acting like we're tossing out the concept as a whole and barring anyone from readding it, ever.
> 
> Remember Mech. Technically speaking it's code is not gone either but you do not see anyone picking that up. We do not make shitty castes you know that right? The real answer is to rework it, not remove. improve, not some simple single line change. If you do not act now it will be consigned to a hellish limbo. Can you really accept that?

Mech Pilot is not picked up because it requires 80 Marine Pop Points for a slot to open up, alongside this is the common usage of Mechs in Lumipharon's Campaign gamemode.

Mech was shifted up to very rare on highpop due to how hard it is to balance, due to being a power-role that either dies very fast or prevents xenos from snowballing properly.

Baneling however, is a T1 caste whose gimmick is being a gas-filled rolling suicide bomb, and has the unique ability of respawning after a long-to-short delay instead of permanently dying once its killed, as long as its pod is intact, alongside its effective health pool being high enough to allow it to run into a Marine push and explode in the middle of it. The only way to counter this is to hope the Baneling's pod is somewhere near the skirmish zone in a accessible location, instead of next to a tunnel far away, otherwise Marines can only helplessly watch as the same baneling explodes in their face again and again and again.

**Comment by Oscari-pog** [comment]
Marines experience what its like to have your opponent die and come over repeatedly

**Comment by UncleBourbon** [comment]
i like how the two gas xenos, defiler and boiler are t3's and both have inherent downsides and risks tied to them while also taking up a slot for the power of gas spam and obscuring marines vision.
then baneling is stackable on high pop rounds, is easier to use, more versatile, and 10x the less risk

only way to make it less cbt for marines is to make the gas smaller and make it leave a corpse if marines successfully shoot it and disarm it. That way it at least punishes brainlets that just runs up to cades or apc's and slash it until they get lit up then marines can squeeze req points out of it

**Comment by ju45he** [comment]
Idea: Remove the baneling respawning, stop it from exploding on death, have it release gas and then be unable to move for 5 seconds. Encourages teamwork and stuff. Also consider making the reworked baneling into a Tier 2. Also make a fairly large cooldown for releasing gas.

Now it's a high-risk high-reward, and marines can do something about it by shooting harder.

**Comment by AlexCrimson** [comment]
That is just death. You release gas in a group of Marines, then get stunned for 5 seconds? Yeah, death.

Again, just remove the gas, remove the respawn and make it a melee caste that directly injects Defiler toxin. The main issues with the caste are gone, and it still gets to mess up marines with toxins. It could work with Defilers to make better use of the toxin stacking system, so the element of teamwork is still there.

**Comment by Tommy-211** [comment]
> > just rework it bro just rework it!!
> > bro how? its literally just a suicide bomb
> 
> Just make it a shitty Defiler. No AoE gas, no respawns, just melee injects Defiler toxins, and abilities that enable it to do so.

doesn't this literally invalidate it's existence?
"Fix it by making it more shit and unfun for xenos"

**Comment by Tommy-211** [comment]
> Idea: Remove the baneling respawning, stop it from exploding on death, have it release gas and then be unable to move for 5 seconds. Encourages teamwork and stuff. Also consider making the reworked baneling into a Tier 2. Also make a fairly large cooldown for releasing gas.
> 
> Now it's a high-risk high-reward, and marines can do something about it by shooting harder.

btw that means marines will have 5 whole seconds to collectively magdump a low HP caste
it takes like 2 seconds to kill a baneling with a shotgun

**Comment by Tommy-211** [comment]
I'm all for removing this dogshit caste

**Comment by AlexCrimson** [comment]
>doesn't this literally invalidate it's existence?
>"Fix it by making it more shit and unfun for xenos"

Well its already shit. Ive only played it from the Xeno side, but waiting 120 seconds to respawn is rather boring. Then when alive, your only job is to blow yourself up. Literally nothing else you can do. Attacking is annoying because you need to force-walk yourself to do it.

As for making it a melee caste, who said it would be shit? A T1 caste that injects Defiler toxins would be too much, if anything. Depends on its abilities. The point is that it no longer has the frustrating respawn or gas mechanics that Marine & Xeno players dislike about the caste.

**Comment by coldironwarrior** [comment]
i find it a lot of fun, i think it has a unique niche, but to be real, i think there's not only balance concerns, but also bug concerns that need to be hammered out (and balance-bug concerns?)

**Comment by lKiseki** [comment]
one minute of gameplay
two minutes of YouTube

**Comment by Tommy-211** [comment]
> > doesn't this literally invalidate it's existence?
> > "Fix it by making it more shit and unfun for xenos"
> 
> Well its already shit. Ive only played it from the Xeno side, but waiting 120 seconds to respawn is rather boring. Then when alive, your only job is to blow yourself up. Literally nothing else you can do. Attacking is annoying because you need to force-walk yourself to do it.
> 
> As for making it a melee caste, who said it would be shit? A T1 caste that injects Defiler toxins would be too much, if anything. Depends on its abilities. The point is that it no longer has the frustrating respawn or gas mechanics that Marine & Xeno players dislike about the caste.

The respawn cooldown is there for balance, this caste literally cant be fixed that much without just making it something else entirely, so i dont see much point in its existence, as well as this it goes against the normalities of gas castes, its braindead.

**Comment by yyzsong** [comment]
> Can you really accept that?

"Can you really accept bad features being removed if nobody wants to make them good?"
Yes.

**Comment by chemistrymain2** [comment]
> > > Simple. With the same passion as Zaro. You just gotta find someone that has good Baneling sense like his Widow sense. Seriously i do not see why it should be removed. A way to deal damage to marines that does not involve putting yourself at risk is a good siege breaker. Am I the only one who understands the complexities of this ambitious gameplay masterpiece?
> > 
> > 
> > "Just rework it bro just rework it!!" "How?" "Very carefully"
> > lol. If you wanna advocate for keeping baneling in the game bring up an idea (a good one) or make the PR yourself. As it is right now, baneling is _objectively_ a shitty caste to play against and "Removal" essentially just removes its ability to be evolved to. The code will still exist in the records of the github for anyone to pick up and use later, but you're acting like we're tossing out the concept as a whole and barring anyone from readding it, ever.
> 
> Remember Mech. Technically speaking it's code is not gone either but you do not see anyone picking that up. We do not make shitty castes you know that right? The real answer is to rework it, not remove. improve, not some simple single line change. If you do not act now it will be consigned to a hellish limbo. Can you really accept that?

You have to have an idea to suggest improving it.

**Comment by Strayed-Raven** [comment]
> > > > Simple. With the same passion as Zaro. You just gotta find someone that has good Baneling sense like his Widow sense. Seriously i do not see why it should be removed. A way to deal damage to marines that does not involve putting yourself at risk is a good siege breaker. Am I the only one who understands the complexities of this ambitious gameplay masterpiece?
> > > 
> > > 
> > > "Just rework it bro just rework it!!" "How?" "Very carefully"
> > > lol. If you wanna advocate for keeping baneling in the game bring up an idea (a good one) or make the PR yourself. As it is right now, baneling is _objectively_ a shitty caste to play against and "Removal" essentially just removes its ability to be evolved to. The code will still exist in the records of the github for anyone to pick up and use later, but you're acting like we're tossing out the concept as a whole and barring anyone from readding it, ever.
> > 
> > 
> > Remember Mech. Technically speaking it's code is not gone either but you do not see anyone picking that up. We do not make shitty castes you know that right? The real answer is to rework it, not remove. improve, not some simple single line change. If you do not act now it will be consigned to a hellish limbo. Can you really accept that?
> 
> You have to have an idea to suggest improving it.

Nah. If the powers that be wanna kill it. That is the travesty for TGMC to bear.

**Comment by Joe13413** [comment]
> > just rework it bro just rework it!!
> > bro how? its literally just a suicide bomb
> 
> Just make it a shitty Defiler. No AoE gas, no respawns, just melee injects Defiler toxins, and abilities that enable it to do so.

i don't think that any castes in this game should be a 'shitty version of X'
every caste should have a clear niche that it excels at

Baneling shouldn't be a shitty defiler, it should either be a good (and fun to play as/against) suicide bomber, or not exist at all. shitty versions of xenos should only exist as minions.

**Comment by Pariah919** [comment]
> Am I the only one who understands the complexities of this ambitious gameplay masterpiece?

everything going as planned maintainers are truly behind everything and I have control over the deathweb (hi ofnir)

>Idea: Remove the baneling respawning, stop it from exploding on death, have it release gas and then be unable to move for 5 seconds. Encourages teamwork and stuff. Also consider making the reworked baneling into a Tier 2. Also make a fairly large cooldown for releasing gas.

Now it's a high-risk high-reward, and marines can do something about it by shooting harder.
>

Isn't this just.. A T2 Defiler? Why?

>Marines experience what its like to have your opponent die and come back repeatedly
>

I shouldn't be humoring this- But this is an asymmetrical game sir, there's a reason marine death is easier to come back from than xeno death. One has a slightly deeper system and slowly lose capablity as they take damage, the other one is binary "I am above crit, in crit or dead.".


>That is just death. You release gas in a group of Marines, then get stunned for 5 seconds? Yeah, death.

Again, just remove the gas, remove the respawn and make it a melee caste that directly injects Defiler toxin. The main issues with the caste are gone, and it still gets to mess up marines with toxins. It could work with Defilers to make better use of the toxin stacking system, so the element of teamwork is still there.
>

We already tried a caste kinda like this, afflictor didn't work out. I doubt it would work out in modern TGMC. The concept simply will just be "Defiler but lower tier and melee".

**Comment by chizzy376** [comment]
The sentient acid glob is too powerful for a t1 (in my opinion).

**Comment by Tommy-211** [comment]
> > Am I the only one who understands the complexities of this ambitious gameplay masterpiece?
> 
> everything going as planned maintainers are truly behind everything and I have control over the deathweb (hi ofnir)
> 
> > Idea: Remove the baneling respawning, stop it from exploding on death, have it release gas and then be unable to move for 5 seconds. Encourages teamwork and stuff. Also consider making the reworked baneling into a Tier 2. Also make a fairly large cooldown for releasing gas.
> 
> Now it's a high-risk high-reward, and marines can do something about it by shooting harder.
> 
> > 
> 
> Isn't this just.. A T2 Defiler? Why?
> 
> > Marines experience what its like to have your opponent die and come back repeatedly
> 
> I shouldn't be humoring this- But this is an asymmetrical game sir, there's a reason marine death is easier to come back from than xeno death. One has a slightly deeper system and slowly lose capablity as they take damage, the other one is binary "I am above crit, in crit or dead.".
> 
> > That is just death. You release gas in a group of Marines, then get stunned for 5 seconds? Yeah, death.
> 
> Again, just remove the gas, remove the respawn and make it a melee caste that directly injects Defiler toxin. The main issues with the caste are gone, and it still gets to mess up marines with toxins. It could work with Defilers to make better use of the toxin stacking system, so the element of teamwork is still there.
>
>
>
> We already tried a caste kinda like this, afflictor didn't work out. I doubt it would work out in modern TGMC. The concept simply will just be "Defiler but lower tier and melee".

You replace a defective part in your car. The next day you do the same thing with another part and then do so each day until you have replaced every part with a new one. Is what you have at the end of this process the same car with new parts or is it a new car? And if it is different when did it become so?

If you replace a shitty part in your caste. the next day you stealth merge and do the same thing with another part of the caste and then do so each day until you have replaced every feature with a new one. Is what you have at the end of this process the same caste with new parts or is it a new caste? And if it is different when did it become so?

**Comment by Mannybrado** [comment]
Bless you MJP! I love MJP!!!!!!!!

**Comment by AlexCrimson** [comment]
>Then, when you play marine, you are punished for shooting it. You see, if you kill it, it explodes--but if you don't kill it... it can still attack you. So, if it gets close, you're just... fucked. There are no options, you're just fucked. Incredibly unfun.

Shoot it into crit then move away from it? Not exactly complicated.

**Comment by lKiseki** [comment]
This is gonna get staled to death, mark my words...

**Comment by Tommy-211** [comment]
stop procrastinating and kill banelings already

**Comment by zzurge** [comment]
> Marines experience what its like to have your opponent die and come back repeatedly

Imagine if marines had a free suicide vest every time they were revived and didnt lose all their limbs when it exploded

**Comment by Carnage068** [comment]
Make it so that it only releases gas when it blows up, and that it only respawns when blowing up. That way marines killing it actually does something meaningful. Wouldn't singlehandedly fix the caste but it would probably alleviate the issue.

**Comment by ZeWaka** [comment]
> Make it so that it only releases gas when it blows up, and that it only respawns when blowing up. That way marines killing it actually does something meaningful. Wouldn't singlehandedly fix the caste but it would probably alleviate the issue.

Honestly... not the worst idea, better than outright removal. Would suck to die within 5min to a shotgun but whatever I can do that as a rouny too.

**Comment by Tommy-211** [comment]
> Make it so that it only releases gas when it blows up, and that it only respawns when blowing up. That way marines killing it actually does something meaningful. Wouldn't singlehandedly fix the caste but it would probably alleviate the issue.

This is the only intelligent thing that has been said in this thread

**Comment by Kuro020** [comment]
> This is gonna get staled to death, mark my words...

alright bet

**Comment by Kuro020** [comment]
it was a prank bro

**Pull request closed without merging**
