### PR TITLE
Reduced miner slash time

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Now you can no longer bypass the while loop, slashing miners takes notably longer.
Halves the time to make it a bit quicker, also in particular means its possible to do hit and run attacks on miners to chip it down.
## Why It's Good For The Game
walance
## Changelog
:cl:
balance: Miner slash time reduced to 1.5 seconds per cycle
/:cl:

### CODE REVIEW

**Comment by ClosetedSkeletonGH** [comment]
shooting xenos while they slash doesnt even interrupt them

**Comment by Naaanii** [comment]
> shooting xenos while they slash doesnt even interrupt them

This should probably be included.

**Comment by chizzy376** [comment]
I'd rather have it be as it is now. This just makes annoying drive-by's impossible to react to.

https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/e36d8094-c2c9-433c-adae-fa925ceb866d

**Comment by imsxz** [comment]
i dont mind how it is currently, getting the 1st slash is all that really matters even in driveby slashes

**Comment by Aporhtonoma** [comment]
i mean when you are slashing a miner you are exposed to everything if you wanna stop the beno grab a shotty and stagger it.

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
