### PR TITLE
OB cannon impact is now animated

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

https://cdn.discordapp.com/attachments/500801682058379265/1103265616330244106/Change_Me_-_Debugdalus_2023-05-03_11-29-45.mp4
## Changelog
:cl:
qol: OB cannon impact now has a visual animation
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
kaeboom

**Comment by MLGTASTICa** [comment]
Imagine if the explosion itself also gave off large smoke particles.

**Comment by Losenis** [comment]
make it a 1% chance for the sprite to be a clown plsssss

**Comment by XSlayer300** [comment]
Make it possible to have a trail? And to have some angle akin to droppods from tg?

**Review by Lumipharon — APPROVED** [review]
This is some looney tunes anvil drop thing lol. If Kuro is happy with it tho.

**Pull request merged**
