### PR TITLE
Terra Experimental Rework

### PR DESCRIPTION
**Pull request by ClosetedSkeletonGH**
## About The Pull Request

_**Weapon changes:**_

**Terra Experimental Carbine:**

Fire modes:

- The standard automatic fire mode was removed, leaving it with the two modes: burst fire and scatter.

The reason why is because the standard auto fire was noob bait as it is worse than the burst fire mode in every way. While burst fire made the weapon viable, the auto fire was just plain garbage. If someone wants straight auto fire they could use the basic Terra Rifle which has a viable auto fire mode. This also opens up someone making a new carbine mode in the future.

- Scatter shot audio was made much louder

It was weirdly quiet before, with how fast the lasers go away, it was often hard to tell if you were even firing in cases where other people were firing at the same time.

------

**Terra Experimental Pistol:**

Fire modes:

- Standard mode now fires in 24 lasers in 4 burst shots. 20 damage with 5 AP, so it burns through its ammo quickly but it is a decent backup weapon to pull out now

- Disable mode now fires 10 significantly faster shots that can drain xeno plasma similar to pepperballs, although at a significantly weaker rate when compared to the pepperballs. The pepperball gun is much better to swap to for dedicated plasma drain, but this mode now serves as utility when the time is right

- Heat mode now fires 10 shots at a somewhat faster rate, meaning that this mode is viable now for its niche of setting xenos on fire, but still very. It had its base damage reduced from 20 to 10 so it is now a utility firing mode than a dedicated damage dealer.

-------

**Terra Experimental Sniper:**

General:

-New sprite
Before:
image
After:
image
Inhand example:
image

- Unweilded scatter has been increased from 10 to 15 although this may be increased more.

Fire modes:

- Standard mode now fires 8 shots of 65 dmg, 45 AP, 5 sunder shots instead of 12 shots of 60 dmg, 30 AP, 4 sunder shots. Rate of fire has also been slightly reduced.

The Standard sniper mode was absolutely awful and outclassed by the terra rifle on overcharge with a scope or literally any other sniper in every way. This is hopefully enough to give it a buff to be viable, although it may need future tweaking in order to get it into viability

- Heat mode now fires 6 shots instead of four, and has 30 AP instead of 0 AP. Its rate of fire has also been more notably decreased.

- New overcharge mode: Has a total of 3 shots per cell, with a 1.5 second windup and 3 seconds cooldown inbetween firing. It does 130 damage, 65 AP, 10 sunder. and an accurate min range of 6. These numbers may need to be increased based on feedback.

Windup audio: https://discord.com/channels/498569646014857217/528230141546201120/1068669943668801637
Firing audio: https://discord.com/channels/498569646014857217/528230141546201120/1068669957065420861

------

**Terra Experimental Machine gun**

Fire modes:

- Standard mode has had its damage buffed from 15 to 16 and AP buffed from 15 to 22.5, now it is more inline with other MG's in its damage output capabilities. Ammo decreased from 150 to 120.

- Efficiency mode has had its fire rate increased significantly, its damage buffed by 8.5 to 12.5, and AP upped from 0 to 5.

This firing mode was arguably the most useless weapon in the loadouts available to marines at round start, as it only provided 50 extra ammo for losing all damage capabilities (0 AP) and almost half the lasers damage (15 -> 8.5). This change now provides an adequate niche for the firing mode as a suppression option that can deal damage and has very little drop off, while also having no IFF as its trade off.

--------

### Why It's Good For The Game

I have most justifications for the changes under the respective changes, but overall, so many of the laser weapons were either entirely useless, or had entirely useless modes. This PR is an attempt to turn every mode into something that atleast has times in which it could be used, along with adding in some cool new features to the terra experimentals that makes them feel a bit more, experimental.

## Changelog
:cl:
Add: new overcharge mode the TE-S
Balance: Terra Cells are now small weight class
Balance: Significantly changes dmg, AP, and firing rate of TE-M's efficiency mode and slightly on the standard mode
Balance: Significantly changes dmg, AP, firing rate, and ammo values of TE-S's standard mode and heat mode
Balance: Significantly changes all dmg, AP, firing rate, and ammo values TE-P's modes. Disable mode now drains plasma
Removal: Removes the standard auto firing mode from the TE-C
imageadd: New TE-S sprites
/:cl:

### CODE REVIEW

**Comment by Guidesu** [comment]
Can you add IFF to the laser rifle?
Seriously it won't be used due to it lack of utility

**Comment by Starfirejordan** [comment]
> Can you add IFF to the laser rifle? Seriously it won't be used due to it lack of utility

the only way he could give it IFF and it not be spammed to shit by anyone and everyone with everyone carrying them in mass and basically volly firing xenos with IFF is to make it a limited item and force it to be ordered from req if you want more.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
The current laser gun sprites are good as they are, no need for a change, also that sprite is a downgrade in quality

**Comment by Lumipharon** [comment]
For reference I have some doubt about the balance changes, but was posted in discord.

**Comment by Autisem** [comment]
im not sure how I feel about machine gun being buffed, it was weak before but the fact is that for atleast engineers you can trivialy recharge it. you can bassicly fire it infintly

**Comment by Al-1ce** [comment]
> The current laser gun sprites are good as they are, no need for a change, also that sprite is a downgrade in quality

hilarious coming from you of all people
remember the kuro gun pr
do not forgive
do not forget

**Comment by zzurge** [comment]
call me crazy but that resprite reminds me of the morita railgun somewhat. i dig it

**Comment by WEWLAD2222** [comment]
Ah hell, I was really looking forward to this.

**Pull request closed without merging**
