### PR TITLE
Loadouts can be reorganized.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request

https://user-images.githubusercontent.com/66163761/231069688-4825fb9b-13fb-4406-85b2-b47897bbf4dd.mp4
## Why It's Good For The Game
Better UI
## Changelog
:cl:
qol: Loadouts are re-organizable.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Based af

**Comment by FosterGrime-Heymynameslouie** [comment]
SPPPEEEEEEDDDDDDDMERGHEEDDDDDDDDDDDDDD

**Comment by Lumipharon** [comment]
BTW if you did this with the draw order, people would love you for it.

**Comment by Strayed-Raven** [comment]
Xander out here showing the devs how to dev. Based af

**Pull request merged**
