### PR TITLE
Off-hand shooting

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Have thing in active hand.
Have gun in off hand.

Right click to shoot offhand gun.
## Why It's Good For The Game
Sword and pistol lets go
## Changelog
:cl:
add: Guns can be fired offhand with right click
/:cl:

### CODE REVIEW

**Comment by Zangeiti** [comment]
finally vali sword serves a purpose

**Comment by JackTheJackhammer** [comment]
finally, i can be a british officer with my sabre and revolver and die in peace

**Comment by Xander3359** [comment]
Holy shit bros we're becoming burgerstation LETS GOOOOOO

**Comment by Gregormack** [comment]
Fucking finally! Bless Lumi!

**Review by TiviPlus — APPROVED** [review]

**Review by Kuro020 — APPROVED** [review]

**Comment by Zangeiti** [comment]
this breaks turning on deployables

**Comment by Yttriums** [comment]
This is already possible using obscure high-apm techniques and making it easier will make me less special personally.

**Comment by Lauwma** [comment]
"High-apm" 
Hold left click then swap hand :clueless:

**Comment by Ragecrabbo** [comment]
This lets you ignore melee cooldown if you click a xeno with left mouse button and then right mouse button, pls fix

**Comment by Lumipharon** [comment]
> This lets you ignore melee cooldown if you click a xeno with left mouse button and then right mouse button, pls fix

That has nothing to do with this pr.

**Pull request merged**
