### PR TITLE
widow can emmit pheromones

### PR DESCRIPTION
**Pull request by Aporhtonoma**
## About The Pull Request
Widow becomes a true spider mother that emits her own pheromones.
importand edit: 
image

I asked 
## Why It's Good For The Game
Since widow can build their own mazes they should be the true queens of their mazes by emitting (weak) pheromones. Also I find it kind of odd poor widow does not have better support abilities for her fellow flankers.
## Changelog
:cl:
balance: Widow can now emit drone level pheromones
/:cl:

### CODE REVIEW

**Comment by LohnRan** [comment]
powercreep, widow is suppose to be a maze fighter, giving the caste the ability to weed and build walls is in the caste specialty. It was never meant to be a full on support caste with phero.

**Comment by SimplySmiley123** [comment]
Does Widow really need even more shit piled onto the caste?

**Comment by FunkyMonke47** [comment]
power creep of the shitty t3 that no one plays, oh nooooooo

**Comment by Runian** [comment]
Sure, I guess. I suppose Widow is the final caste of the Drone --> Hivelord --> Widow line even though Widow doesn't really have much relation to them besides making walls and caring about maze.

**Comment by Naaanii** [comment]
Good for consistency as it's the only weed (and wall) caste without pheros.

**Review by Kuro020 — APPROVED** [review]

**Pull request merged**
