### PR TITLE
Stun changes part 5 - Ravager

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
PART 5-
Ravager

NERFS
Eviscerating charge now has 20 second cooldown
Ravage stuns for less time

Compensation (If any)
Ravager now has ignore pain on 40 second cooldown, and has to choose between being able to survive for more time incombat or the ability to stun again, the higher plasma allows you to recover faster as you have more spare plasma overall

## Why It's Good For The Game
Stuns bad, ravager might need another button after this though.

## Changelog
:cl:
balance: eviscerating charge nerfed to 20 seconds, ravage stun nerfed, can use 2 of the three abilities at any time before running out of plasma at any level, ignore pain reduced to 40 seconds
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by MiniMeatwad** [comment]
bal

**Comment by Surrealaser** [comment]
Ah yes, let us cripple the weakest T3 by both doubling its Eviscerate cooldown *and* killing its stuns while giving it a pittance in exchange.

**Comment by MLGTASTICa** [comment]
Ravagers stuns are barely effective.  Ignore pain is barely usefull since rage was removed. You should either keep the stun or allow the ravager to use both eviscerating charge and ravage one after each other.

**Comment by Pariah919** [comment]
>Ravagers stuns are barely effective. Ignore pain is barely usefull since rage was removed. You should either keep the stun or allow the ravager to use both eviscerating charge and ravage one after each other.
>
it never even had ignore pain during the rage era, that was second wind?

**Comment by Surrealaser** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/5269

You see this?

Wait on this to get merged, and then replace most of the stun duration with a greater duration of stagger and slow stacks.

And also eliminate the crippling changes to cooldowns that have nothing to do with stuns, and that aren't a problem after you've already nuked stun times, like doubling the cooldown on the Rav charge.

**Review by Hughgent — APPROVED** [review]
variable changes

**Comment by Hughgent** [comment]
```
Commander TGMC BOT
11/24/2020
REPO: Updating origin branch...
REPO: Merging PRs #5254, #5257, #5263, #5267, #5223, #5235...
```
```
DuccBot BOT
Today at 7:29 PM
TGMC Statbus
Winrate (Xenomorph to Marine)
64.52%
View Raw
http://statbus.psykzz.com:8080/api/winrate?delta=3
```
Reasonable balance

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-89). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
