### PR TITLE
Adds Medical and Surgery skill to Pilots

### PR DESCRIPTION
**Pull request by KAAITTT**
## About The Pull Request
Gives basic medical and surgical skills to pilots:

	medical = SKILL_MEDICAL_PRACTICED
	surgery = SKILL_SURGERY_AMATEUR

## Why It's Good For The Game
It makes sense for a pilot to have simple knowledge of medicine, even IRL pilots do indeed train in cases of emergencies. As a member of command, it makes sense too. Running Tad/Alamo, you can be a little bit more useful if someone needs first aid.

## Changelog
:cl: Kait
balance: Pilots now have basic Medical And Surgical skill
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
Don't they have Pilot access so they *don't* need these things?

Like, can't they just use their magic buttons to teleport to within ten tiles of medbay? And can't they do most of this anyway, just moderately slower? Seems like skill creep to me.

**Comment by Verlurk** [comment]
Definitely creep.

**Comment by KrabSpider** [comment]
there's a difference between knowing first aid and knowing how to perform a surgical operation on a dying patient. This doesn't make sense. This is just stretching logic just so your changes make sense.

**Comment by novaepee** [comment]
Don't make PO be flight surgeons. Be synthetic if you want PO access and surgery skills.

**Comment by Moggram** [comment]
medical maybe, surgery no.

**Comment by Losenis** [comment]
Give synth the ability to use guns to balance it out, they're going to be underpowered vs pilots in the inevitable deathmatch for who gets to run a healbus

**Comment by BraveMole** [comment]
nop

**Pull request closed without merging**
