### PR TITLE
Xeno armor/health rebalance

### PR DESCRIPTION
**Pull request by Kuro-ai**
## About The Pull Request

Nerfs all castes fire resist (aside from queen),changes most castes armor and health values,nerfs shrike speed

## Why It's Good For The Game

Marines are losing their ap ammo with the new guns,being as it is most xenos can tank a lot of damage and deal a lot of damage/be really fast,this buffs the actual frontliners and nerfs everyone else with the fact that ap mags are being sent to the bone zone in mind

## Changelog
:cl:
balance: various xeno value changes
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -9. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
defender should probably scale by 240/250/260/270. 10 per evo level.

**Comment by Kuro-ai** [comment]
> defender should probably scale by 240/250/260/270. 10 per evo level.

that is a really bad scalling for a xeno that is supposed to be taking the damage

**Comment by Pariah919** [comment]
warrior doesn't need bomb resist. It was the only way to kill a warrior who's any good.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-6). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
