### PR TITLE
Adds a fumble to baseline pill bottles.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Add pill bottles to the MarineMed
Adds a fumble to pill bottles if you lack medical skill
For now I only added pill bottles that have a packet variant.

## Why It's Good For The Game
Gives marines access to the desired pill bottles, but they now have draw delay for pfcs.
It's basically the satchel/backpack equivalent.
If you want quick access to pills, use packets, which have 8 pills and are instant.
If you want more total pills, you can use pill bottles, but the downside is that they have a draw delay to take pills out.
## Changelog
:cl:
add: Unlimited Pill bottles to the MarineMed
bal: Pill bottles have a fumble
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
Might as well make it a medical skill check in normal pill bottles rather than a new pill bottle, in my opinion.

**Comment by Xander3359** [comment]
> Might as well make it a medical skill check in normal pill bottles rather than a new pill bottle, in my opinion.

That PR was already denied

**Comment by BonkaiB** [comment]
Bro really adding one of the fucking accursed thick plastic squeeze caps to a pill bottle

**Comment by KerbalCitizen** [comment]
If you want to change the system, I think you're better off starting from the ground up than trying to make specific changes. The pill bottles in medplus vendor only run out when marine team is stacked, easy win for them anyways and the limited quantity not really relevant. Or anyone with medskill 2 or higher can just make 30 empty pill bottles (ones with no draw delay) very quickly and let people fill them up via pill packets, then again this is considered "teamwork" under TGMC standards. Also would need to make sure stuff like hyposprays dissolving the pills doesn't bypass the draw delay. 

And likely unintended feature of making it very easy to have a backpack full of pill bottles to restock from, where the draw delay won't matter much. 

I don't think this is a good change design wise.

**Comment by ivanmixo** [comment]
This is bloat and also shit

**Comment by ivanmixo** [comment]
You were told no.

**Comment by Xander3359** [comment]
I wasn't told no by anyone?

**Comment by ivanmixo** [comment]
unmortis

**Comment by Otterwatch** [comment]
This is a semi fair exchange, though I would've liked to see some of the other med+ vendor bottles as well such as inap, QC, head meds (imid and alky). They aren't exactly powergamey. Inaprovaline is perhaps the closest to that and you can only apply it to other people for the crit heal so it is simply promoting "teamwork." If this pr gets merged in tandem with the locked med+ vendor pr, then it would be nice to see free versions of most of the meds there with the exception of maybe RR.

**Comment by BonkaiB** [comment]
changed since last looked at, This seems like such a non issue, infact more of a reach than anything. More so this just seems to make marine side more tedious. If this is going for preventing indepth pre-meds, longer fighting healing this will do next to nothing as a few extra seconds when properly pre-medding is basically nothing, this isn't going to inhibit much and just seems to be a nerf PR for the majority of marines just for the sake of it.

**Comment by Pariah919** [comment]
This just seems like a desperate attempt to acquire the legendary storage creep that is the 10 set of pill bottles that are gone every round.
At this point, storage has been crept far too much (i'm to blame for that lel tho) by stuff like packets, ammo boxes, etc.
Pill packets are a comprimise to let people have pills without having pill bottle level storage for every single marine, they're intentionally inferior in about nearly every way. The only thing I never finished was making them come in boxes so people could dump them in FOB to have pills for everyone, but after how ammo boxes simplified logi to a degree I dislike I decided against doing that.
But, more subjectively I suppose you give people an inch and they demand a mile. I don't think this PR is a good idea, we should all just accept pill bottles shouldn't be the standard , they're the upgrade.

**Comment by iforgotmeword** [comment]
If you’re going to add this change make the bottles unlimited because the bottles aren’t an upgrade anymore now are they? They are a sizegrade

**Comment by Xander3359** [comment]
> If you’re going to add this change make the bottles unlimited because the bottles aren’t an upgrade anymore now are they? They are a sidegrade

image

**Comment by iforgotmeword** [comment]
> > If you’re going to add this change make the bottles unlimited because the bottles aren’t an upgrade anymore now are they? They are a sidegrade
> 
> image

does it say "makes pill bottles unlimited"?
or "Add pill bottles to the MarineMed"

**Comment by InterroLouis** [comment]
Aren't pill packets children of pill bottles?

**Review by ivanmixo — APPROVED** [review]

**Comment by ivanmixo** [comment]
Seems nobody else wants to touch this with a 10ft pole so bite me

**Comment by BonkaiB** [comment]
hmmm yes no one touching it. badly rated PR. lets merge it. Omega brain

**Comment by Tommy-211** [comment]
What is wrong with you, are you retarded?
Can you not open pill bottles irl without medical personnel to help you?
Do you need to see a psychiatrist?

**Comment by Nuker555** [comment]
overwhelmingly negative time to stealthmerge guys

**Comment by TheUSSWatercooler** [comment]
more fuel to the PFC+ corpsman fire

**Comment by SzkieletorNutric** [comment]
oh mah gawd

**Comment by ilikesaying** [comment]
deargod

**Comment by docRoboRobert** [comment]
Github try not to merge a dogshit pr that everyone dislikes challenge.

**Comment by spookydonut** [comment]
@Xander3359 I told you not to do this

**Comment by Tommy-211** [comment]
ding dong the wicked witch is dead

**Comment by Fawcksy** [comment]
Pill bottle skill cringe was literally why I transitioned from CM to TGMC, and now TGMC is adding pill bottle skill cringe. AND it was a stealth merge cause they knew nobody would fucking like it and they're shooting down any reverts instantly

_**F u c k o f f**_

**Comment by TheUSSWatercooler** [comment]
More fuel to the PFC+ fire that plagues corpsman.

**Pull request merged**
