### PR TITLE
Adds more screams

### PR DESCRIPTION
**Pull request by Spyroshark**
:cl:
soundadd: Added two new screams and two new pain sounds for humans.
/:cl:

All of the sounds are from Half Life 1.
_Why do we all have to wear these ridiculous ties?_

### CODE REVIEW

**Comment by Rohesie** [comment]
I'm not really convinced by the meme set of screams we've gathered.
The TF spy one is specially bad.

**Comment by DominikPanic** [comment]
Agreed, this is too memey.

**Comment by Spyroshark** [comment]
i mean we already had a wilhelm scream from CM

**Comment by Spyroshark** [comment]
I'm going to make a new PR, because 1: rohsie said he'd be ok with the half life screams as long as they're made more rare and 2: because drawsstuff has sent me a LARGE collection of screams and xeno sounds from the same game our current ones are ripped from.

**Pull request closed without merging**
