### PR TITLE
Burst fire balance 2.0

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Do what #9699 couldn't.

## Why It's Good For The Game

Make burst fire tuned.

## Changelog
:cl: 
balance: T18, T12, and Tx11 burst firerates have all been nerfed with burst fire delay of 0.05 seconds. Don't worry, slap on BFA, and you're good. MJP will balance BFA to make sure you have your funny brr
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Better than nothing, but in reality I doubt people click fast enough/time it perfectly enough for this to actually mean anything.

**Comment by lovegreenstuff** [comment]
the only way to make an actual difference in anything is through radical change
and this is the complete opposite of radical change. this does literally nothing
your willingness to collude with foreign powers blinds you to the truth of powercreep.

**Comment by TiviPlus** [comment]
Fix your changelog

**Comment by Braun1719** [comment]
Nerf your brain and with xeno acid spam on the queen. What the stupid xeno-PR accepted?

**Comment by novaepee** [comment]
image

David approves.

**Pull request merged**
