### PR TITLE
squad marines get 2 consturction skill

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
~~they've learnt to play minecraft~~ squad marines get 2 construction skill to allow engineers room to breathe and not have to entirely be dependant on the marine force to be able to make literally anything resembling a fob and frontal cades.

## Why It's Good For The Game
Let's engineers have more breathing room and makes the marine force not entirely dependant on engineers to do any buuilding at all

## Changelog
:cl:
balance: squad marines get 2 construction skill
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
can't wait for the insta close

**Comment by bobmancer343** [comment]
lol

**Comment by Kuro-ai** [comment]
image
*what?*

**Comment by David-Stormwell** [comment]
yea sure insta merge this.
-tgmc pl
_totes not sarcastic or anything._

**Comment by TiviPlus** [comment]
> yea sure insta merge this.
> -tgmc pl
roger that

**Comment by TiviPlus** [comment]
misclick

**Comment by Kuro-ai** [comment]
bring back gbp bot so we can watch mjp reach -1000,kay thx

**Pull request closed without merging**
