### PR TITLE
Partial Ravager Rework - New Ravager Rage Ability

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request
1. Ravager gains the Rage ability:

**Rage
Duration:** 10 seconds
**Cooldown:** 2 Minutes
**Effect:** The Ravager bellows a demoralizing, earth shaking roar, regains plasma and gains extra speed, armor and slash damage in proportion to the % of its missing HP for the duration as well as slow, stagger and stun immunity. Plasma and Sunder are likewise restored. These benefits are further increased for each negative HP the Ravager has. The roar imposes 1-3 slow and stagger stacks (3 * Rage Power) on each non-allied living creature within range and earshot scaling in range with Rage strength (tile radius = 6 * Rage Power). 

**Details:**

Rage Power is calculated as 50% of the % difference between the Ravager's current and maximum hit points: (1 - (X / 350) ) * 0.5

So base Rage Power is 0.5 when the Ravager is at 0 HP, 0.64 when it's at -100 HP and 0.93 when it's at -300 HP.

Rage Power is further increased by 0.005 per point of negative HP, and is capped at 1.

Slash damage is increased by a % = to Rage Power.

Armor is increased by 40 * Rage Power

Speed is increased by 50% of Rage Power.

Plasma regained is a % = to Rage Power.

Sunder regained is equal to 50 * Rage Power (min 12.5, max 50)

2. Ignore Pain renamed to Endure, and its duration has been increased to 15 seconds up from 10, and cooldown increased from 40 seconds to 60 seconds, and plasma cost increased from 175 to 200. It now has an aura SFX and additional notifications. Ignore Pain grants immunity to the staggerslow effect from staggering munitions for its duration, and immunity to the stagger status in general. Instead of granting effective immortality, Endure lets the Ravager take up to 350 damage while at crit health before instantly dying. If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal.

3. Added a xeno melee damage modifier var, allowing for global modification of slash damage for individual xenos.

4. Added statistics support for the Ravager abilities.

5. Charge cost decreased from 600 (lol) to 450. It still is impossible to combo Endure, Ravage and Charge all at once.

6. Ravage now also attacks structures and machinery in its area.

## Why It's Good For The Game

Adds an interesting high risk, high reward option to the Ravager that synergizes strongly with its existing kit, particularly Endure/Ignore Pain, and adds much needed depth to its kit.

Allows Ravage to target things other than humans only; it can now be used against hostile xenos, structures and machinery.

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/5465

## Changelog
:cl:
add: Rage ability added.
balance: Ignore Pain renamed to Endure and its duration was increased from 10 to 20 seconds, cooldown increased from 40 seconds to 60 seconds, and plasma cost increased from 175 to 200; this also grants stagger immunity for its duration.
balance: Charge plasma cost decreased from 600 to 450.
refactor: Added statistics support to Ravager abilities. Added support for per xeno slash damage modification. Minor other refactors.
tweak: Ravage now targets all non-friendly living creatures as well as machinery and structures.
fix: Fixes Ignore Pain (now Endure) granting immortality. Instead the Ravager can take up to 350 damage while at crit health before instantly dying. If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal.
/:cl:

### CODE REVIEW

**Comment by Dolth** [comment]
No.
Seriously Surr wtf.

1. You're making ravagers able to combo all three ability. Debatable but alright why not.
2. Giving ANOTHER ability ontop of endure that gives health/armor/regen/HP/plasma/whatever else.
3. It also slows down everyone in a 6 tiles radius?

Surr that's literally 3 different type of buff to a caste that is already pretty strong.
I suggest you only keep one of these 3.

**Comment by Chaznoodles** [comment]
"If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal."

"Ignore Pain grants immunity to the staggerslow effect from staggering munitions for its duration, and immunity to the stagger status in general."

Get out of jail free card that can be combo'd with charge due to you dropping the cost to 450, meaning there is absolutely no punishment for overextending - not to mention adding Rage on top of that, which refills a % of your plasma, meaning you probably _can_ combo Ravage, Charge and Endure despite what you're saying. AND it regains sunder? AND Ravage will damage structures?

This isn't a rework, it's a buff to a caste that doesn't need it.

**Comment by SkeletalElite** [comment]
> "If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal."
> 
> "Ignore Pain grants immunity to the staggerslow effect from staggering munitions for its duration, and immunity to the stagger status in general."

Honestly this is a nerf to ignore pain, right now if you use ignore pain you literally can't be killed for 10 seconds.
This new ignore pain you can still die

**Comment by Dolth** [comment]
> > "If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal."
> > "Ignore Pain grants immunity to the staggerslow effect from staggering munitions for its duration, and immunity to the stagger status in general."
> 
> Honestly this is a nerf to ignore pain, right now if you use ignore pain you literally can't be killed for 10 seconds.
> This new ignore pain you can still die

You die if you take damage that would have normally killed you. Now it gives you 350 HP before instantly dying so technically you get a bigger HP pool than before. Not really a nerf, a tweak that I still considere a buff.

**Comment by Chaznoodles** [comment]
> Honestly this is a nerf to ignore pain, right now if you use ignore pain you literally can't be killed for 10 seconds.
> This new ignore pain you can still die

You die if you take damage that would normally kill you, all the while being able to run about until you hit that threshold with no stagger or the like, making this a get out of jail free card that lasts _twenty seconds_. If you don't hit said threshold, you heal right back out of it into a nonlethal state - which I assume means standing up and not crit.

Not dying in Ignore Pain was a bug that has gone unfixed. That wasn't a feature.

**Comment by SkeletalElite** [comment]
> You die if you take damage that would normally kill you, all the while being able to run about until you hit that threshold with no stagger or the like, making this a get out of jail free card that lasts _twenty seconds_. If you don't hit said threshold, you heal right back out of it into a nonlethal state - which I assume means standing up and not crit, making all the damage sustained worth absolutely nothing.

By being returned to a non lethal state they mean it just heals enough damage to make you not instantly die on the spot from damage sustained, after the ability ends you will still be in crit, so you'll only survive in a safe place. 

Also I'm like 90% certain ignore pain immortality is not fixed, I've been direct hit with AP sadars at 0 health and survived with ignore pain up. This PR fixes it

**Comment by Dolth** [comment]
Okay I did read it wrong altho it's not a nerf but rather a fix lol. Regarding endure.

**Comment by Pariah919** [comment]
agree with chaz here

also making plasma not real again, silly as usual

**Comment by TiviPlus** [comment]
```
Effect: The Ravager bellows a demoralizing, earth shaking roar, regains plasma and gains extra speed, armor and slash damage in proportion to the % of its missing HP for the duration as well as slow, stagger and stun immunity. Plasma and Sunder are likewise restored. These benefits are further increased for each negative HP the Ravager has. The roar imposes 1-3 slow and stagger stacks (3 * Rage Power) on each non-allied living creature within range and earshot scaling in range with Rage strength (tile radius = 6 * Rage Power).
```
This does way too much for one ability, try restricting it to damage-only or similar

```
Ignore Pain renamed to Endure, and its duration has been increased to 15 seconds up from 10, and cooldown increased from 40 seconds to 60 seconds, and plasma cost increased from 175 to 200. It now has an aura SFX and additional notifications. Ignore Pain grants immunity to the staggerslow effect from staggering munitions for its duration, and immunity to the stagger status in general. Instead of granting effective immortality, Endure lets the Ravager take up to 350 damage while at crit health before instantly dying. If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal.
```
But why?
```
Charge cost decreased from 600 (lol) to 450. It still is impossible to combo Endure, Ravage and Charge all at once.
```
Can you explain this?
```
Ravage now also attacks structures and machinery in its area.
```
Why?

**Comment by Smudged** [comment]
> ```
> Effect: The Ravager bellows a demoralizing, earth shaking roar, regains plasma and gains extra speed, armor and slash damage in proportion to the % of its missing HP for the duration as well as slow, stagger and stun immunity. Plasma and Sunder are likewise restored. These benefits are further increased for each negative HP the Ravager has. The roar imposes 1-3 slow and stagger stacks (3 * Rage Power) on each non-allied living creature within range and earshot scaling in range with Rage strength (tile radius = 6 * Rage Power).
> ```
> 
> This does way too much for one ability, try restricting it to damage-only or similar
> 
> ```
> Ignore Pain renamed to Endure, and its duration has been increased to 15 seconds up from 10, and cooldown increased from 40 seconds to 60 seconds, and plasma cost increased from 175 to 200. It now has an aura SFX and additional notifications. Ignore Pain grants immunity to the staggerslow effect from staggering munitions for its duration, and immunity to the stagger status in general. Instead of granting effective immortality, Endure lets the Ravager take up to 350 damage while at crit health before instantly dying. If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal.
> ```
> 
> But why?
> 
> ```
> Charge cost decreased from 600 (lol) to 450. It still is impossible to combo Endure, Ravage and Charge all at once.
> ```
> 
> Can you explain this?
> 
> ```
> Ravage now also attacks structures and machinery in its area.
> ```
> 
> Why?

I agree with Tivi, This is hardly *just* a rework, but a full on buff for Ravager.
A little too crazy

**Comment by Naaanii** [comment]
> > Honestly this is a nerf to ignore pain, right now if you use ignore pain you literally can't be killed for 10 seconds.
> > This new ignore pain you can still die
> 
> You die if you take damage that would normally kill you, all the while being able to run about until you hit that threshold with no stagger or the like, making this a get out of jail free card that lasts _twenty seconds_. If you don't hit said threshold, you heal right back out of it into a nonlethal state - which I assume means standing up and not crit, making all the damage sustained worth absolutely nothing.
> 
> Not dying in Ignore Pain was a bug that has gone unfixed. That wasn't a feature.
> 
> This is sounding more and more like Evasion+...

You do now die in ignore pain at least.

Tested it myself while tanking an OB and then getting gibbed once the duration ended, though yeah it is wonky at times.

**Comment by Naaanii** [comment]
I do like the synergy of rage with ignore pain but imo the plasma costs should not be lowered so that Ravs still require a pocket drone or hivelord to be a very dangerous threat.

The AOE slow is not needed at all, considering the massive boosts Rav gets with Rage and even moreso when its used as intended. It should either buff Rav or debuff enemies, not both.

**Comment by Surrealaser** [comment]
> > > Honestly this is a nerf to ignore pain, right now if you use ignore pain you literally can't be killed for 10 seconds.
> > > This new ignore pain you can still die
> > 
> > 
> > You die if you take damage that would normally kill you, all the while being able to run about until you hit that threshold with no stagger or the like, making this a get out of jail free card that lasts _twenty seconds_. If you don't hit said threshold, you heal right back out of it into a nonlethal state - which I assume means standing up and not crit, making all the damage sustained worth absolutely nothing.
> > Not dying in Ignore Pain was a bug that has gone unfixed. That wasn't a feature.
> > This is sounding more and more like Evasion+...
> 
> You do now die in ignore pain at least.
> 
> Tested it myself while tanking an OB and then getting gibbed once the duration ended, though yeah it is wonky at times.

Ignore Pain is still broken; it is immortality.

Just end the duration on weeds.

**Comment by Surrealaser** [comment]
> ```
> Effect: The Ravager bellows a demoralizing, earth shaking roar, regains plasma and gains extra speed, armor and slash damage in proportion to the % of its missing HP for the duration as well as slow, stagger and stun immunity. Plasma and Sunder are likewise restored. These benefits are further increased for each negative HP the Ravager has. The roar imposes 1-3 slow and stagger stacks (3 * Rage Power) on each non-allied living creature within range and earshot scaling in range with Rage strength (tile radius = 6 * Rage Power).
> ```
> 
> This does way too much for one ability, try restricting it to damage-only or similar
> 
> ```
> Ignore Pain renamed to Endure, and its duration has been increased to 15 seconds up from 10, and cooldown increased from 40 seconds to 60 seconds, and plasma cost increased from 175 to 200. It now has an aura SFX and additional notifications. Ignore Pain grants immunity to the staggerslow effect from staggering munitions for its duration, and immunity to the stagger status in general. Instead of granting effective immortality, Endure lets the Ravager take up to 350 damage while at crit health before instantly dying. If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal.
> ```
> 
> But why?
> 
> ```
> Charge cost decreased from 600 (lol) to 450. It still is impossible to combo Endure, Ravage and Charge all at once.
> ```
> 
> Can you explain this?
> 
> ```
> Ravage now also attacks structures and machinery in its area.
> ```
> 
> Why?

#1: Since Ignore Pain has been fixed such that it's not immortality, Rage needs to make the Ravager more resistant to damage when it is used at negative HP, otherwise the risk/reward ratio is unacceptably skewed in the former's favour. The AoE debuffs could be removed, but beyond that, given the plasma cost of Endure, I think the rest are fine to stay.

#2:  Because Ignore Pain is literally broken. It is de facto immortality atm given how it's been coded, and it would be broken asf when paired with Rage as is.

#3: What's to explain? Check the plasma costs.

#4: Because it's needlessly arbitrary that it only hits living targets in its area.

**Comment by TiviPlus** [comment]
> 1: Since Ignore Pain has been fixed such that it's not immortality, Rage needs to make the Ravager more resistant to damage when it is used at negative HP, otherwise the risk/reward ratio is unacceptably skewed in the former's favour, since the Ravager can now actually be killed while Endure/IP is active. The AoE debuffs could be removed, but beyond that, given the plasma cost of Endure, I think the rest are fine to stay. It should also be noted that Rage itself has a 2 minute cooldown.
> 
> 2: Because Ignore Pain is literally broken. It is de facto immortality atm given how it's been coded, and it would be broken asf when paired with Rage as is.
> 
> 3: What's to explain? Check the plasma costs.
> 
> 4: Because it's needlessly arbitrary that it only hits living targets in its area.

The issue is it does too MUCH for ONE ability, just keep it to strictly damage so its effects are both good to understand and to keep it balanced easier

But you're buffing it I dont see how this helps that?

I mean why you did this change, it seems very arbitrary / possibly powercreepy

This means that ravager is now much more effective against FOB, which frankly is not it's role to play as a damage-dealing oriented caste

**Comment by Surrealaser** [comment]
> > 1: Since Ignore Pain has been fixed such that it's not immortality, Rage needs to make the Ravager more resistant to damage when it is used at negative HP, otherwise the risk/reward ratio is unacceptably skewed in the former's favour, since the Ravager can now actually be killed while Endure/IP is active. The AoE debuffs could be removed, but beyond that, given the plasma cost of Endure, I think the rest are fine to stay. It should also be noted that Rage itself has a 2 minute cooldown.
> > 2: Because Ignore Pain is literally broken. It is de facto immortality atm given how it's been coded, and it would be broken asf when paired with Rage as is.
> > 3: What's to explain? Check the plasma costs.
> > 4: Because it's needlessly arbitrary that it only hits living targets in its area.
> 
> The issue is it does too MUCH for ONE ability, just keep it to strictly damage so its effects are both good to understand and to keep it balanced easier
> 
> But you're buffing it I dont see how this helps that?
> 
> I mean why you did this change, it seems very arbitrary / possibly powercreepy
> 
> This means that ravager is now much more effective against FOB, which frankly is not it's role to play as a damage-dealing oriented caste

1. It must shore up the Ravager's resilience when it is used at negative HP otherwise it will punish the player for using Rage as intended and when it should be optimal. Remember, the Ravager can actually die now while Ignore Pain/Endure is active.

2. I'm not buffing it; I actually made it much less powerful because you can actually die while Endure/Ignore Pain is active.

3. The plasma costs are too high; personally I don't care too much about this though.

4. I very much doubt whether slashing (and taking the barbed wire damage) from 3 barricades on Ravager's plasma cost and cooldown is gonna make it 'much more effective' vs FOBs.

**Comment by lKiseki** [comment]
Lots of balance changes, really not sure about some of these, but to offer my honest feedback based on the description of this PR:

> Sunder regained is equal to 50 * Rage Power (min 12.5, max 50)

I am not sure I understand. Maximum of 50, but it's already 50 multiplied by some value? I'll go ahead and assume you put an incorrect value, but regardless; the sunder regeneration on Rage is, frankly, quite a lot. I'd suggest the minimum and maximum amount of sunder you can regenerate both get reduced, something like min. 10 and max. 30.

> Ignore Pain renamed to Endure, and its duration has been increased to 15 seconds up from 10, and cooldown increased from 40 seconds to 60 seconds, and plasma cost increased from 175 to 200. It now has an aura SFX and additional notifications. Ignore Pain grants immunity to the staggerslow effect from staggering munitions for its duration, and immunity to the stagger status in general. Instead of granting effective immortality, Endure lets the Ravager take up to 350 damage while at crit health before instantly dying. If Endure ends while the Ravager has normally lethal damage, its damage is reduced to barely non-lethal.

Big change. I _feel_ this will be somewhat broken, but I'd be interested in testing out how it performs first before suggesting anything. If I had to say anything from speculation alone, however? I feel a duration of 15 seconds and 350 effective health may be a bit too much.

> Charge cost decreased from 600 (lol) to 450. It still is impossible to combo Endure, Ravage and Charge all at once.

Eviscerating Charge should keep an increased cost so it can't be more easily comboed into after a Ravage. However, given Rage rewards the player with some plasma, you could just let Rage reward proper usage by granting some more leniency to Eviscerating Charge rather than reducing its plasma cost. I'd be interested in seeing how this change performs, as well.

> Ravage now also attacks structures and machinery in its area.

**_Yes_**. This grants Ravager a much needed change for the purposes of sieging, since as it is currently, Ravager has little to no presence in FOB sieging.

Overall, lots of stuff I'd be interested to confirm in action. I'd suggest a few balance changes, maybe do what Tivi said in #dev-general and split up some of these changes so we can test each one individually.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
This PR is too much to take in, please split it up

**Pull request closed without merging**
