### PR TITLE
Combat robots can speak machine

### PR DESCRIPTION
**Pull request by Three333Digit**
## About The Pull Request
Combat robots can speak machine

## Why It's Good For The Game
Combat robots (synths and AI too) have their own sikrit language now.

## Changelog
:cl:
add: Combat robots can speak machine
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
_Happy robot noises_

**Comment by chesse20** [comment]
can you have it so that the chief ship engineer can speak it too that'd be cool

**Comment by Al-1ce** [comment]
Just to clarify: This IS the **local** language, right? Not the reserved synth/AI channel? The latter should remain exclusive for those roles.

**Comment by Lumipharon** [comment]
https://www.youtube.com/watch?v=CTjolEUj00g

**Comment by Al-1ce** [comment]
> I think he means the funny combat robot scream/warcry sound effects and the text in chat being in the different font than human speak

Local languages for mobs function like you would expect, i.e. - you can only hear them when nearby. `#define MODE_KEY_BINARY "n"` however acts as a hivemind channel for synthetics and the AI, and should be solely reserved for those roles. 

Looking at the code it seems to be regular robotspeak, which is good.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
To be clear is this the pseudo radio channel one where you can talk at range or just a language

**Comment by Three333Digit** [comment]
> To be clear is this the pseudo radio channel one where you can talk at range or just a language

Just the language. The point is to add funny fluff.

**Review by Lumipharon — APPROVED** [review]

**Comment by Lumipharon** [comment]
I know this will just lead to robots shit talking behind their human master's backs but eh.

**Pull request merged**
