### PR TITLE
Outrider tad tweaks

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
Removes the un-crushable spot on the outrider tad.
image
The red square is the tile that used to be immune to crusher charges, with the yellow arrows being the lanes that this PR opens up.
A positive of this is that vehicles can now enter/exit from the side entrance, as well as there being 2 new tiles of extra space.
## Why It's Good For The Game
Outrider tad is currently objectively the best tad on the majority of the maps in the game due to its indestructible back wall and very easily defendable choke entrances. It still is, but this makes it slightly less oppressive in spots where it would otherwise be nearly unkillable.
## Changelog
:cl:
balance: uncrushable tile in the outrider tad has been opened (side door made 3 tiles, windows extended to include north side walls)
/:cl:

### CODE REVIEW

**Comment by YehnBeep** [comment]
So, I want to provide a little background here.

When I started using this tad model, many people told me they'd never seen it before. Since I've been using it so much (and personally I don't know anyone that plays TO as frequently as I do, though there's probably been some others), this has mostly faded now. Though selecting it can still cause friction and anger from marines who are dead set on the idea that I should use the mini tad.

Of course, that the Crusher exists is one of the driving reasons that I select it. But I also feel the Crusher itself is balanced problematically - it's only real counter being that it has to run into wire in perfect condition, that can't be easily compared and the Crusher having such huge amounts of armor and HP it can often run in, left click wire itself, and then retreat and charge even while tanking weapons fire.

The size of fat tads is already a significant drawback, restricting landing sites, especially on many maps with areas that look like they should be landable - and groundside marines often assume they are, which leads to anger when they want a tad to land somewhere - but the areas aren't valid.

I feel that there should be a tad model that's harder for the Crusher to attack. I think that there is an option to (slightly) counter the Crusher is a good thing, not a bad thing.

Nerfing the only fat tad that is sometimes accepted as viable just puts us back to minitad only, and I don't consider that a good thing.

**Comment by Mannybrado** [comment]
> I feel that there should be a tad model that's harder for the Crusher to attack. I think that there is an option to (slightly) counter the Crusher is a good thing, not a bad thing.

Yep. This is still that. There are multiple angles where a crusher simply cannot attack from, including one side which is capable of completely blocking off 7 tiles of... anything, and that isn't including the corners on the other sides. With boiler having significantly reduced range, the only thing that can reliably attack the tad without instantly dying does happen to be the crusher, so there being an option which keeps a relatively open layout for marine movement but is also effective at stopping crushers offers literally no counterplay for xenos in certain situations. You land, and the xenos cannot do anything in this area until you leave or they dedicate their entire force to killing you, in which you can simply leave and go somewhere else.

You can still do this. It's just less oppressive for the other team. 

If you can't see the value of having an indestructible wall I don't know what else to tell you.

**Comment by Mannybrado** [comment]
> The outrider is not the only tad model with this, yet it's the only non-minitad that's started to become less-than-completely rejected.

It is the only tad model to have one side completely impassible. All of the other modules have at least one point where you can get inside, from every side.

> Making it "worse than minitad" (which it already is to most) by taking away the strength that makes it, sometimes and to some people, worth all the drawbacks...

You said it yourself. I don't personally believe it is worse than minitad on most maps, however the maps that the big tads(including outrider) are bad on are because of the map, not the tad. Again, blocking off areas of attack is so much better than being open on all sides, especially since tad does not have cades on it. It is much easier to defend the outrider than it is to defend the standard on many more positions. If you block off the side entrance by landing against the wall, you've got 1 entrance in and out, which is very easy to cade and wire.

> the Crusher itself is so thoroughly oppressive that

It isn't. Use wire. If a crusher is solo smashing into your lanes so effectively that your wire isn't catching them and they're able to slash them down without being punished it's a compounding skill issue of the entire marine team, or you landed in a bad position and you need to move.

> I feel it not getting a free pass on one tad model that already has very big drawbacks isn't a negative thing at all.

As previously stated, the only major drawback of the outrider is that it is hard to land on certain maps. Any other "drawback" is something all of the different models share.

**Comment by YehnBeep** [comment]
I mean, you're getting lost in a lot of minutiae that I don't really think is necessarily accurate, but there's also not much point to arguing it.

I don't think it's good to go back to minitad only, which we haven't even escaped much. Maps contribute, but even on maps that are "friendly" to fat tads, that vast majority would still pick the minitad, would still see it as the best option. It's not a single factor, but a contribution of many things.

We have exactly one alternative to the minitad that has gained only very tenuous traction as a sometimes-accepted alternative.

Please don't put us thoroughly back into the world of "minitad only".

**Comment by Arturlang** [comment]
Honestly the TAD should be vulnerable when it's landed without a couple marines protecting it, often you can also just land in spots where a crusher or xenos can't do a damn thing because of the positioning and indestructible walls, or is nicely in the open and in the perfect spot for the TAD to become a veritable mini-fob with it's sentries and HMG.

**Comment by DrAmazing343** [comment]
Crushers who are experienced are basically unstoppable in the sense that their direct counter (razorwire in perfect condition) only takes a few seconds of prep or a single reaction to deal with when they have a lane. I think it's okay to have one (1) tile that's immune to Crushing on this Tadpole. It's just too damn big otherwise, and it barely justifies anything by the whole "two sides blocked off" sorta logic— those are marine blind spots, and frequently taken advantage of, anyway!

**Comment by YehnBeep** [comment]
> Honestly the TAD should be vulnerable when it's landed without a couple marines protecting it, often you can also just land in spots where a crusher or xenos can't do a damn thing because of the positioning and indestructible walls, or is nicely in the open and in the perfect spot for the TAD to become a veritable mini-fob with it's sentries and HMG.

It is vulnerable.

Having a single tile the crusher can't get to doesn't mean the outrider is invulnerable. If you're a lone marine on it, all it takes is one baneling/defiler/etc and 1 warrior, or some other combination that does the same thing, and it's dead.

The HSG also isn't really viable with the outrider. The mini tad is actually the better option to give a wide area coverage with up to 6 turrets (+ HSG with clear firing lines) due to its openness and the much smaller size means it's much easier and cheaper to fortify than other models. It's one of the bigger advantages that the mini maintains. And of course, 6 turrets + potentially an HSG can pretty well shred any xeno or group that gets near and detected. And it has many more locations to pick from.

The outrider is much worse at providing wide area turret coverage, it's strength is in other areas, such as providing a bit more shelter from ranged attacks (but that very thing makes the HSG bad for it and turrets very limited for outside coverage).

But being a mobile highly-turreted kill zone is the minitad's game. If you dislike that... this PR is only pushing to have that option used more.

**Comment by Mannybrado** [comment]
> only takes a few seconds of prep or a single reaction to deal with when they have a lane

This is your fault. Don't land in spots that expose you to a wide open area that a crusher can attack from. You have full vision over 80% of the map, if you are unable to find one you should play a different role or you're being cucked by the map, in which case you'll have to choose between facing your back wall against the xenos to make yourself immune to crusher charges at the cost of said blindspot(which is not a thing for most of the other tad models), or you can land in less impactful but safer locations.

> those are marine blind spots

If you land in a bad position. Once again, you have full control over it.

**Comment by YehnBeep** [comment]
> If you land in a bad position. Once again, you have full control over it.

You... don't. That's been one of the bigger points of these last discussions.

Fat tads have very limited choices for landing spots and often can't even choose their orientation to squeeze into somewhere. You can call it "mapping issue" but it's not really feasible to remap nearly every map.

**Comment by DrAmazing343** [comment]
> > only takes a few seconds of prep or a single reaction to deal with when they have a lane
> 
> This is your fault. Don't land in spots that expose you to a wide open area that a crusher can attack from. You have full vision over 80% of the map, if you are unable to find one you should play a different role or you're being cucked by the map. In that case you'll have to choose between facing your back wall against the xenos to make yourself immune to crusher charges at the cost of said blindspot(which is not a thing for most of the other tad models), or you can land in less impactful but safer locations.

"It's your fault that you have crusher lanes existing at all" okay dude. You want to tweak the TAD to make it more susceptible to Crushers, then I bring up that Crushers cannot really be countered with their traditional counters over time, and now you're saying that you shouldn't land in spots that a Crusher can attack from? On your own PR, which makes a TAD more susceptible to Crusher attacks? Are you seeing the fallacy I see here? Because it doesn't look very nice.

**Review by Lumipharon — APPROVED** [review]
This tad model being seemingly purpose built to be hard to attack/have dead spots explicitly goes against the intention of the tadpole NOT being a fortress.

**Comment by YehnBeep** [comment]
Long live the minitad, the once, present, and future king...

**Pull request merged**
