### PR TITLE
Fixes synthetic blind and deafness issues

### PR DESCRIPTION
**Pull request by DominikPanic**
FIxes: #2384

### CODE REVIEW

**Comment by DominikPanic** [comment]
> 
> 
> Use issynth

Issynth is more wasteful, these are already human and using the bitflag is more universal.

**Comment by Rohesie** [comment]
But by using `issynth(H)` we can modify how the whole thing works more easily. It's a define after all.

**Comment by DominikPanic** [comment]
> 
> 
> But by using `issynth(H)` we can modify how the whole thing works more easily. It's a define after all.

issynth is used for when you have mob that you aren't sure is a human, here we are 100% sure it's a human since it's defined on the human path, also this is more efficient. That define has other purposes, this is not it.

**Comment by Rohesie** [comment]
I'm not sure about it. What's the basis of your request, @spookydonut ?

**Comment by spookydonut** [comment]
issynth is used plenty of places already where you already know its a human how is this any different, its more readable and easier to change the behaviour of it without hard coding behaviour like in this pr.

**Comment by DominikPanic** [comment]
Just because it's already used in those places doesn't mean it's ideal. You have to agree that the performance impact of issynth is much worse than a bitflag comparison on the species.

**Comment by spookydonut** [comment]
> 
> 
> Just because it's already used in those places doesn't mean it's ideal. You have to agree that the performance impact of issynth is much worse than a bitflag comparison on the species.

OH NO NOT AN EXTRA ISTYPE CHECK IN INFREQUENTLY CALLED CODE THINK OF THE CHILDREN.

its more maintainable, its more readable, this code isnt performance critical.

**Comment by DominikPanic** [comment]
For the readbility and maintainability argument, a second macro could be created.

**Comment by Rohesie** [comment]
A second macro would be a good compromise.

**Pull request merged**
