### PR TITLE
viking boat chadpole

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

adds this, real gamers only

_viking

## Why It's Good For The Game

Shuttle variety is good and this should allow for more combat gimmicks

## Changelog
:cl:
add: viking boat tadpole
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
needs to be speedmerghed instantly

**Comment by chizzy376** [comment]
speedmermeghed

**Comment by RipGrayson** [comment]
I'm of the opinion that the sandbags should probably come pre-wired and the ship should have some guns, otherwise it will be used as a grief pick.

**Comment by chizzy376** [comment]
20 pounder cannon with grape shot confirmed

**Comment by mc-oofert** [comment]
> I'm of the opinion that the sandbags should probably come pre-wired and the ship should have some guns, otherwise it will be used as a grief pick.

20 aimmode marines are your guns

**Comment by blackdav123** [comment]
give it two weapon attachment points so we can broadside xenos

**Pull request closed without merging**
