### PR TITLE
lol

### PR DESCRIPTION
**Pull request by Zar000**
## About The Pull Request
bugfix good
## Why It's Good For The Game
bugfix good
## Changelog
:cl:
fix: ?
code: ?
/:cl:

### CODE REVIEW

**Comment by srxtreme** [comment]
Salt PR?

**Comment by lKiseki** [comment]
Salt PR?

**Comment by DeltaFire15** [comment]
What is calling that proc? That seems like something incorrectly using get_hard_armor() without a limb argument, which means something right now is likely ignoring hard armor if it exists (since it runtimes) and will continue to if this gets merged without resolving what is actually triggering that improper call.

**Comment by Zar000** [comment]
> omething right now is likely ignoring hard armor if it exists (since it runtimes) and will continue to if this gets merged without resolving what is actually triggering that improper call.

Spawn alien
Spawn human
Attack human as alien
viola

**Comment by FIXTHERADBOXPLEASE** [comment]
We sure this isn't an elaborate salt PR?

**Comment by Derrick2Electricboogaloo** [comment]
What even is this PR? something about hard armor or?

**Pull request closed without merging**
