### PR TITLE
lets boilers make bombs whenever they're not zoomed

### PR DESCRIPTION
**Pull request by terranaut1**
## About The Pull Request

as title

## Why It's Good For The Game

boilers can use their abilities

## Changelog
:cl:
fix: fixes boilers being unable to make bombs
/:cl:

### CODE REVIEW

**Comment by Hughgent** [comment]
This is not a fix, it is a balance change.

**Comment by terranaut1** [comment]
there is literally no way to create bombs with this, the way you told me in the discord doesn't work for me and the player who reported this to me via ticket.

**Comment by psykzz** [comment]
still a fix to the issue, but does have balance concerns

**Comment by XElectricX** [comment]
I never played Boiler so I didn't know that was a thing. Sounds pretty bad. Beno buffs are in short supply.

**Pull request merged**
