### PR TITLE
Adds a boot knife to basic marine sets.

### PR DESCRIPTION
**Pull request by grinkgo**
## About The Pull Request

Boot knives now come with marine essential sets.

## Why It's Good For The Game

It makes everyone's life easier.

## Changelog
:cl:
add: Marine essential clothing sets now come with a boot knife included.
/:cl:

### CODE REVIEW

**Comment by DominikPanic** [comment]
This kind of bloats the loadout further and makes the vendor even more worthless. Not sure I like this change.

**Comment by psykzz** [comment]
Is it time to migrate vendors to Nano and improve the UI to allow selectable sections?

**Comment by DominikPanic** [comment]
They are already nano and already allow selectable sections

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
