### PR TITLE
Access rework

### PR DESCRIPTION
**Pull request by Rohesie**
* Removed `req_access_txt` and `req_one_access_txt`, we use lists and defines now.

* Refactored the way the lists are stored, so we make use of dictionaries for unique combinations. After the huge var-edit cleanup we'd still have 1014 unique access lists on Pillar + Prison. This system reduces this to just 2 directory lists, plus 25  unique `req_access` and 19 `req_one_access` lists. Not a huge gain, but it's something.

* Since I really don't love myself, removed a ton of var-edits, cleaning up the maps quite a bit.

* Ice Colony and to a lesser degree Prison Station had several access locks. Both were removed, following the standard of other patterns, to avoid having the station be powered be against the marines.

### CODE REVIEW

**Comment by spookydonut** [comment]
They're for mapping to reduce number of compiled in types, i'm not sure what the trade off is for like memory usage, rsc size etc, might pay to check what the before/after on a bunch of things is with this.

**Comment by Rohesie** [comment]
rsc (on disk) before the PR: `63.0 MB (66,088,960 bytes)`
rsc (on disk) after the PR: `63.0 MB (66,088,960 bytes)`

Memory by Dream Daemon on roundstart before the PR: `330.9 MB`
Memory by Dream Daemon on roundstart after the PR: `331.2 MB`

No significant difference that can be separated from random variance.

**Comment by spookydonut** [comment]
> 
> 
> rsc (on disk) before the PR: `63.0 MB (66,088,960 bytes)`
> rsc (on disk) after the PR: `63.0 MB (66,088,960 bytes)`
> 
> Memory by Dream Daemon on roundstart before the PR: `330.9 MB`
> Memory by Dream Daemon on roundstart after the PR: `331.2 MB`
> 
> No significant difference that can be separated from random variance.
> 
> This fixes a ton of access issues that'd be more clear if we didn't use this var-edit standard, which is quite unmaintainable.

sweet!

**Comment by Rohesie** [comment]
Any issues found?

**Comment by psykzz** [comment]
No complaints so far

**Comment by Rohesie** [comment]
I'd say it's ready for merge. I can fix eventual issues that open up, but I don't think there will be any, and if there are, it will be minor stuff.

**Pull request merged**
