### PR TITLE
Adds a "Smartguns/IFF" to the valhalla vendor

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds a "Smartguns/IFF" to the valhalla vendor
Includes:
Smartguns (29, 85, 62, pistols)
BR-8
AMR/Autosniper

(Not the PMC Sniper since that's not available in req)
## Why It's Good For The Game
Good for valhalla
## Changelog
:cl:
qol: Adds a "Smartguns/IFF" to the valhalla vendor
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
You can get these all in Valhalla already?

**Comment by Al-1ce** [comment]
> Not the PMC Sniper since that's not available in req


There are lots of other things in Vallhalla that are otherwise unobtainable. Probably wouldn't hurt to include the AT rifle.

**Comment by Xander3359** [comment]
> You can get these all in Valhalla already?

The only way to get more SG62 stuff is by respawning as a SG in valhalla, since it wasn't added anywhere vendable.
I moved the IFF stuff from the "Weapons" category to the "IFF" category. 
I just think it's more appropriate.

**Comment by Xander3359** [comment]
It also debloats the 1 category slightly
image

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
