### PR TITLE
removes barrel charger from req vendor

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
it shouldn't be there in the first place, its not a decently designed attachment

## Why It's Good For The Game
bc bad, bc die

## Changelog
:cl:
del: Removed barrel charger
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
So why not rebalance it ?

**Comment by Kuro-ai** [comment]
> So why not rebalance it ?

because damage mults should not be a thing on attachments,unless someone adds a AP value for attachments BC should be shadowrealmed

**Comment by SkeletalElite** [comment]
could rework it to increase sunder instead of damage.

**Comment by SplinterGP** [comment]
This is good, BC is awfull and shoulnd't be acquirable, also causes people to question and ask of its existence.

**Review by SplinterGP — APPROVED** [review]

**Comment by Swagile** [comment]
> 
> 
> could rework it to increase sunder instead of damage.

too many weapons already have sunder, increasing that number to literally every weapon is not good game design; you might as well remove armor in that case then since people will find ways to game BC with other attachments to absolutely shred armor (see: RDS, LS, BC on a T42, cringe moment)

**Pull request merged**
