### PR TITLE
Remove reagent ids and use typepaths where applicable.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Roughly does what https://github.com/tgstation/tgstation/pull/44166 did.

## Why It's Good For The Game
Keeping things up to date. Code improvement.

## Changelog
:cl: Ghommie (Original PR by Naksu)
code: reagent IDs have been removed in favor using reagent typepaths where applicable.
/:cl:

Still a draft, Gotta still end searching up for more leftover reagent ids and nuke them.
And make defines for the typepath strings to make things easier and prettiers once I'm done with the main task.
EDIT: on second thought, I don't think the defines are really necessary.

### CODE REVIEW

**Comment by Hughgent** [comment]
In theory, once this is done, the codex should update itself with automatic recipes for every chemical.
see `code\modules\codex\categories\category_reagents.dm` for that code in particular.

**Comment by Rohesie** [comment]
very nice.

**Comment by DominikPanic** [comment]
Do you still plan to work on this?

**Comment by Ghommie** [comment]
Yes. I just forgot about it for a moment until now.

**Pull request closed without merging**
