### PR TITLE
plasma SMG tweaks

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Minor increase to plasma smg scatter.
Reduced damage of bouncy mode after each bounce.
Increased heat gen of standard fire by 10%.
## Why It's Good For The Game
Slightly overtuned at range.

The heat gen was a bit TOO manageable on standard mode. Combined with its very low slowdown (and one handedness) plus bouncy, makes it particularly good at chasing nerds down.
## Changelog
:cl:
balance: Plasma SMG scatter increased slightly
balance: Plasma SMG bouncy mode damage decreases slightly for each bounce
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
Why does the plasma SMG of all things need a nerf?

I've added it to the DPS calculator page provided to me, I dont believe any of the numbers entered are incorrect.
image
Given a xenomorph with 50 armour at a range of 4 tiles the plasma SMG has a DPS of 76.

Comparably the other ballistic weapons offer simiar DPS amounts 
image
Notably the AR18 reaches 78 DPS with a similar slowdown to the plasma SMG.
This is using the same example target with 50 armour at 4 tiles.

The Plasma SMG has notable improvements over the AR18, especially with magazine capacity being 75, limited to being able to fire only 60 of those if holding down the trigger due to overheating. which is higher than AR18's 36, however tactical reloading by a skilled marine can somewhat negate this.

At the cost of 400 requisitions points, the plasma SMG seems like a rather mediocre option which I see as in no way needing a nerf.

**Comment by Isy232** [comment]
I no longer have any objections to you nerfing the plasma SMG due to overperformance in HvH, we can adjust the requisitons price downwards to compensate for HvX.

**Review by Kuro020 — APPROVED** [review]

**Comment by TiviPlus** [comment]
Shouldn't have added it to req I warned you

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Actually as good time as any to correct previous errors see above comment

**Comment by Lumipharon** [comment]
I don't have a problem with it being in req (although I really don't care either way) as its not particularly powerful for its cost in HvX.

Up to Kuro though.

**Pull request merged**
