### PR TITLE
Plasma cutter now has the ability to nodrop toggle.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Works like shield and powerfist
image

## Why It's Good For The Game
Makes plasma cutter more reliable in the age of xeno drag and makes sense anyway considering its a high value item.

## Changelog
:cl:
balance: Plasma cutter now has togggleable nodrop.
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
just give it higher drag delay

**Comment by Aquilar** [comment]
wouldn't this be an indirect buff to synths?

**Comment by Losenis** [comment]
SPEEDMERGE HOLY SHIT LETS FUCKING GOOOOOOOOOOOOOOOOOOOOOOOO

image

**Comment by MereWalker** [comment]
If your lose your fun stick that is on you imo.

**Comment by Losenis** [comment]
Posted while wraith banishes and runs into the maze with it

**Comment by Losenis** [comment]
Xenos have enough ways to force knockdown and displacement that can only be countered with 「Future Vision」 given while you're stunned or tiles away another xeno can drag the PC. In practice a PC will be used to aid a push, which is going to be defended by multiple xenos rather than one.

Examples are wraith banishing you, warrior tossing you elsewhere and god forbid it's a maze, shrike doing the same, crusher displacement + tanking, defiler gas right after a knockdown, so on and so forth in any combination and any number given that there's no reason why there can't be even 10+ xenos in one given place. For the sake of the argument we'll also ignore the hundred million ways the marines themselves will help you lose your PC, like getting slugged in the back in the head since you need to be in melee range to use the PC anyway.  The ability to pull items of which plasma cutter is not going to be blacklisted on the list of ended up a probably unintended nerf on top of all the other nerfs like map removal, synth removal, inability to change cells, damage reduction, and so on. I'd like to bring emphasis to the most recent damage reduction that already preemptively dealt with memelords going shield + PC going overboard.

**Comment by FIXTHERADBOXPLEASE** [comment]
For context I always see Losenis go shield + PC engineer and kill/cryo himself if his cutter ever gets melted. Not slander just a relevant observation.

**Comment by Losenis** [comment]
>shield + PC engineer

The only times I go shield is when I go t90 tyr2, and in those times I go PFC+ engi so I spend 60 points on 3 PCs so I don't kill/cryo myself if I lose one. Are you confusing me for someone else?

**Pull request closed without merging**
