### PR TITLE
attachment changes and some new sprites

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
new sprites for attachments
some changes to some attachments, specifically the barrel charger which is now too good because of the accuracy changes. i halved the damage bonus and make it more inaccurate and gave it more spread.

## Why It's Good For The Game
New sprites.
Supressor is just bad. It doesn't need to be this bad.
Barrel charger was buffed too hard unintentionally. It was too much free damage. Supre

## Changelog MJP Kuro
:cl:
add: Added new attachment sprites
del: Removed old attachment sprites
balance: BC now gives you only 10% more damage, has worse accuracy penalties and spread penalties. Suppressor has no damage penalty.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -40. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Marmio64** [comment]
make suppressor not have a downside. Barrel attachments (im pretty sure) already make you unable to mount your bayonet on the gun, and having a quiet gun is near useless since xenos have x-ray and thermal vision anyhow.

**Comment by ilikesaying** [comment]
> make suppressor not have a downside. Barrel attachments (im pretty sure) already make you unable to mount your bayonet on the gun, and having a quiet gun is near useless since xenos have x-ray and thermal vision anyhow.

bayonet is a barrel attachment
suppressor is literally useless if you're not going full on stealth mode

**Comment by Pariah919** [comment]
pepperoni one minute

**Pull request closed without merging**
