### PR TITLE
CM windows + map fixes

### LINKED ISSUE #4398: Sulaco pipenet incorrect
Sulaco Atmos isn't piped correctly.
Throws runtimes

## Reproduction:

```
[22:49:23] Runtime in components_base.dm, line 89: list index out of bounds
proc name: setPipenet (/obj/machinery/atmospherics/components/setPipenet)
src: the connector port (/obj/machinery/atmospherics/components/unary/portables_connector)
src.loc: the floor (155,62,3) (/turf/open/floor/tile/dark)
call stack:
the connector port (/obj/machinery/atmospherics/components/unary/portables_connector): setPipenet(/datum/pipeline (/datum/pipeline), the pipe (/obj/machinery/atmospherics/pipe/simple/cyan/hidden))
/datum/pipeline (/datum/pipeline): build pipeline(the pipe (/obj/machinery/atmospherics/pipe/simple/cyan/hidden))
the pipe (/obj/machinery/atmospherics/pipe/simple/cyan/hidden): build network()
Atmospherics (/datum/controller/subsystem/air): setup pipenets()
Atmospherics (/datum/controller/subsystem/air): Initialize(821633)
Master (/datum/controller/master): Initialize(10, 0, 1)
```
image

### PR DESCRIPTION
**Pull request by Rohesie**
Ports the CM-SS13 windows, shared by Neth.

## Changelog
:cl:
imageadd: Windows replaced with 3/4 directional ones, courtesy of the CM dev team. Old ones are kept as short versions, and put in places where the new ones don't fit well due to the perspective.
/:cl:

* Includes two minor icon fixes, one of plasma windows, the other of a gorg prison wall.
* Removes frosted windows, which were old legacy.
* Refactored windoor and windoor assembly code to allow for the two versions.
* Deleted a duplicate and unused icon file.
* Made a few map changes to better fit the perspective.
* Fixed atmos pipe errors, cabling and directional wall things while adjusting things to fit the perspective.
* Closes #4398

### CODE REVIEW

**Comment by Pariah919** [comment]
I don't like these windows.
They look off.

**Comment by spookydonut** [comment]
Who's the sprite artist?

**Comment by spookydonut** [comment]
Needs artist attribution and explicit permission from the artist for us to use them, it's the least we can/should do.

**Comment by Pariah919** [comment]
These should be made into their own turf.

**Comment by spookydonut** [comment]
@psykzz without any author information/permission I feel we should close this, #4462 and any further PRs opened with ported sprites without attribution.

**Comment by Hughgent** [comment]
I tend to agree. nice as they are I'm sure. a few commented lines saying 'with thanks from so and so' in or around the object would be beneficial.

**Comment by Rohesie** [comment]
> 
> 
> I tend to agree. nice as they are I'm sure. a few commented lines saying 'with thanks from so and so' in or around the object would be beneficial.

Check the PR body and changelog. Credit is being given, in fact there's more credit here than on most sprite PRs around.
Per the CM contribution guidelines the sprites are owned and administered by the active CM development team.
Neth, as their head dev, decided to release them and gave us permission to use them.
Credit is not lacking here.

**Comment by psykzz** [comment]
I had poked Neth on discord to double check, so from what i can tell, this is fine to continue https://discordapp.com/channels/498569646014857217/500801682058379265/730132759565041744

**Comment by spookydonut** [comment]
@Rohesie @psykzz Neth isn't sole head dev anymore.
The CM sprites are contributed to their repo as GPLv3.
Neth is claiming to release them as CC-BY-SA-NC which is an illegal re-licensing of the sprites.
Morally I disagree with using sprites to which it is unclear who the actual the artist was (the cm repo is closed-source and we can't see who committed them like we can with sprites from open source code bases).
I also strongly disagree with using CM's sprites when as a project we are aiming to differentiate ourselves from CM, which is a goal @Rohesie themselves set and believed strongly in.

**Comment by Rohesie** [comment]
> 
> 
> this feature requires some mapping changes to work properly.

Re-added the old windows for where they fit better, chiefly as vendors separators.

Fixed a ton of issues, including bad item references in maps and duplicated atmos pipes. Altered the wire network to follow the usual standard of going as little as possible through walls and other paths that are hard to replace, and aligned APCs to get proper cabling and pixel offset.
What other issues are left, @TheBimmer231 ?

**Comment by AndriiYukhymchak** [comment]
Only aliens and predators are NC and they were not and will not be shared

**Comment by AndriiYukhymchak** [comment]
Sprites are from Nicboon's archive for CM

**Comment by spookydonut** [comment]
> 
> 
> Sprites are from Nicboon's archive for CM

Then we can't use them, nicboone explicitly stated his sprites were only for CM.

**Comment by NethIafin** [comment]
> > Sprites are from Nicboon's archive for CM
> 
> Then we can't use them, nicboone explicitly stated his sprites were only for CM.

Give me few days

**Comment by NethIafin** [comment]
Nicboon authorized use of his sprites (not lobby art) to (quote) "but just consider my request that any work ive done should if at all possible, be limited to well moderated servers".

Lobby art is big nono

**Comment by spookydonut** [comment]
> 
> 
> Nicboon authorized use of his sprites (not lobby art) to (quote) "but just consider my request that any work ive done should if at all possible, be limited to well moderated servers".
> 
> Lobby art is big nono
> 
> Psykzz has screencap of my PM convo with Nicboon of anyone needs to confirm

maybe start posting this evidence in the pr rather than having it secret?

**Comment by spookydonut** [comment]
Update changelog entry and pr desc with artist info please

**Comment by NethIafin** [comment]
> > Nicboon authorized use of his sprites (not lobby art) to (quote) "but just consider my request that any work ive done should if at all possible, be limited to well moderated servers".
> > Lobby art is big nono
> > Psykzz has screencap of my PM convo with Nicboon of anyone needs to confirm
> 
> maybe start posting this evidence in the pr rather than having it secret?

I've sent it to Psykzz already, what do you want from me?

**Pull request closed without merging**
