### PR TITLE
Theseus improvements.

### PR DESCRIPTION
**Pull request by topkek1**
/:cl: RomanZC
Tweak: The Theseus was improved! The AI room is much bigger, and it's the new synthetic spawn. The maints connected to the ERT maints are wider, so that it's not a wide 1 tile corridor shitfest fight. The SD room now has 2 mini-rooms in the sides of the SD entrance, to see your local serial killer xenos screench at you in rage! 

:cl:

### CODE REVIEW

**Comment by Alterist** [comment]
Obvious Issues: 
Area of the corridor is wrong
There's now 3 possible spawn points for synths, with your 2 lacking the equipment at spawn for them
the shape of the ship on the upper floor and lower floor doesn't match

Personal Concerns:
What's the purpose of the expanded AI room? it doesn't seem like a place the marines would choose to hold
I don't understand the point of having the Synths spawn inside the AI chamber, along with hypersleep chambers they don't use
Why is there a crate of M16s and m16 mags on the port ERT shuttle maint tunnel? this change is undocumented and unwanted. There's is no reason for unsecured antiquated to be lying around on the maintenance corridors of a TGMC ship.

**Comment by Alterist** [comment]
> Maints are more symethrical, the M16 crate is removed, there's proper equipament on the AI synth room. The old synth room is now abandoned.
Literally none of that is true

**Comment by topkek1** [comment]
Didn't you notice the tool locker, cyborg recharging station and all the items that were on table of the synth room now on the rack?

**Comment by topkek1** [comment]
Also, the M16 crate WAS removed, so it must be a problem with git.

**Comment by Alterist** [comment]
the code here states otherwise

**Comment by topkek1** [comment]
Code? what the hell then how you are checking the maints symethery using the DMM code?

**Comment by Alterist** [comment]
I'm doing both, checking the code and loading the map, the point is, the code that was committed has none of the changes.

**Comment by topkek1** [comment]
Maybe open the map? Can be a DMM only issue

**Pull request closed without merging**
