### PR TITLE
Change stale autoclose from 7 days to 3

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Contributors have 7 days befofe label + 3 days after
## Why It's Good For The Game

Less dead prs in the tracker

## Changelog
Github

### CODE REVIEW

**Comment by BraveMole** [comment]
Eh, do we have enough maintainers for that? I had a ton of prs going stale and then saved by a maintainer, because they were too busy at the time or whatever

**Comment by TiviPlus** [comment]
Sometimes maintainers just dont have interest in seeing a pr through and theres no point letting it clog up the tracker if the two of us dont want to review it

**Review by SplinterGP — APPROVED** [review]
Good for me, i think spooky has nothing against it but ill take some little while to merge before it

**Comment by SplinterGP** [comment]
Nvm

**Pull request merged**
