### PR TITLE
Xeno progression rework

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Adds a proper xeno hive progression.

Hive starts at tier 1. To progress to the next tier, xenos must collect some amount of psypoints (250 > 500 > 750 > 1000).
At hive tier 1, xenos only have access to T0, T1 and T4 xenos.
At hive tier 2, xenos get access to T2 xenos.
At hive tier 3, xenos get access to T3 xenos and primo.

Each hive tier allows to build 1 more silo.
Each silo allows to build more structures (1 evotower, 1 psychictower, 2 pherotowers, 1 spawner, 4 turrets per silo)
Each silo grants 5% bonus to xeno health and damage for a total of 25% bonus.

Keep in mind that all numbers and balance is TBD.

In an attempt of nerfing roundstart marine push potential:
Plasmacutters and flamethrowers were removed from vendors. You can only get them from req now.
Xeno acid turret buffed to create acid smoke on shooting.

## Why It's Good For The Game

Better xeno lategame progression. Increased incentive to complete secondary objectives.

## Changelog
:cl:
add: Xeno progression rework
/:cl:

### CODE REVIEW

**Comment by RuneQuesteER** [comment]
T1's are far, far too weak to hold the early-game and secure kills against a full strength marine rush for this to be even remotely fair

**Comment by RuneQuesteER** [comment]
> Xeno damage can't be raised since our medical system is dumb and giving xenos +1 slash damage can be the difference between them just doing damage and them inflicting IB/organ damage with their slashes

Not sure what the context of this but I assume its against this PR

**Comment by usnpeepoo** [comment]
this pr would necessitate a complete rework of xeno strength early game and I personally don't see the need for i

**Comment by Luxyboo** [comment]
Removing plasma cutter and flamer is just unnecessary.

**Comment by imsxz** [comment]
marines dont even need plasmacutter or flamers to push. if 2 marines dedicate themselves to shooting down resin and carrying their own ammo box, they replace the need for them entirely. if all 5 mg27's were used to mazeclear+shoot down some rwalls, if even 2 or 3 mg27's are used to mazeclear its already extremely oppressive.

Marines also get to fire MANY ob's for free, can at least fire 5 before needing to buy more fuel from req. 

The only counter to marines slowpushing is gas spam with defiler or boiler(baneling isnt enough gas on its own). Xenos probably wont even be able to get enough psy to reach tier 3 before marines control all 3 disks unless marines are super bald.

Some maps have gens in spots where thyere easily rushed from fob(LV, ice colony) which xenos rely heavily on if marines arent feeding psy.

**Comment by Pariah919** [comment]
Not the unmentioned changes in a pr bruv

Other than that this would require a rework of basically all progression ingame and giving bonus slash damage would definitely break all the slash numbers

**Comment by bowlofcereal** [comment]
"xeno progression rework"

*sneakily adds in the removal of two items and buffs acid turrets*

huh????

**Comment by Joe13413** [comment]
erm what the fuck?? what the actual fuck is this???
not many PRs manage to make me bewildered but this is one of them
lay off the gah damn crackpipe holy shit

**Comment by Waselon** [comment]
Сlosing as the PR was poorly received by the community

**Pull request closed without merging**
