### PR TITLE
Adds 3 new imagers to req.

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Adds 3 new imagers to req. (Sprites by Jackie Burgdorf )

Thermal imagers that give people the ability to see mobs through terrain but not turfs. (1k points)
NVG imagers that give people the ability to see in darkness but they cannot see mobs behind turfs and vision can be blocked. (1k points)
X-ray imagers which give both of the above, basically the ultimate set of imagers (2k points)

<https://cdn.discordapp.com/attachments/498576438908420106/1061018884234293328/Imagers.mp4>

these do not light up tiles like SG goggles or Xeno X-ray.
## Why It's Good For The Game
More expensive and worthwhile upgrades to imagers giving a decent vision power boost to marines. They don't come cheap however. 
## Changelog
:cl:
add: Added 3 new imagers to req. Thermal Imagers, NVG imagers and X-Ray imagers.
/:cl:

### CODE REVIEW

**Comment by 567Turtle** [comment]
1. How much more effective are the NVGs from the Optical Imagers?

2. The thermal goggles kind of make the motion detector obsolete, maybe give them a range that's not your full screen, raise the price or make it so it's pulses and isnt just a steady stream of bug-o-vision, or raise the price a bit. These are just some ideas I came up with, it's your call.

3. The X-Ray goggles should deffinently be more expensive, maybe 3k, 3.5k

**Comment by Strayed-Raven** [comment]
No one is gonna waste the points

**Comment by Derrick2Electricboogaloo** [comment]
So we will see this ONE time? Maybe? Also.. Why NVGs? We have imagers, what is the main difference? I could not see any noticeable deviation.

**Comment by yyzsong** [comment]
These are literally worth the more than a minigun for the first two, and the third is worth more than an actual b18. There's not much reason to buy these aside from trying to kill xenos with X-ray rifles- buying a ZX or whatever and walking at xenos is probably more efficient.

**Comment by TiviPlus** [comment]
Will either be completely useless or imagers-but-powercrept, not interested sorry

**Pull request closed without merging**
