### PR TITLE
Adds "bullet grenades" and the lasburster grenade

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
Adds functionality to enable shooting in a circle either rotating clockwise or just immediately 

using this adds the lasburster grenade, sprites by kuro, "balance" by mjp

https://github.com/tgstation/TerraGov-Marine-Corps/assets/57223640/4064fccc-f36b-4539-b3e6-70aa4c343585

## Why It's Good For The Game
More funny grenade variety

## Changelog
:cl:
add: Added new "lasburster" grenade
code: added the ability to shoot bullets in a circle
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
HEFA but hitscan yes yes

**Comment by WinterDarkraven** [comment]
Finally, fragmentation grenades can fragment.

**Review by Lumipharon — APPROVED** [review]
Surely nothing bad can happen when you throw one of these under a mob and pb them with 800 damage worth of lasers.

**Comment by gryffinp** [comment]
lmao this should probably deal damage to the tile that it's on.
or the marine holding it.

**Pull request merged**
