### PR TITLE
alien embryos now hatch slowly in stasis bags instead of being completely stopped

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

instead of stasis bags completely stopping alien hatching, they now make it 5 times longer

## Why It's Good For The Game

it takes a literal 20 minutes for one host to get to stage 5, in which he can just run back to the base and pop in a stasis bag and hes gonna be fine no matter what, getting hugged should be not an annoyance, especially when theres roles who can resist 6 huggers, and even if they get hugged they can just pop a stasis bag to be fine

## Changelog
:cl:
balance: embryos now hatch slowly in stasis bags instead of being completely stopped
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
there's only a single helmet with anti hug. The B18 helmet. Unless someone somehow added several to all maps.

**Comment by Rohesie** [comment]
This is a controversial PR. Get feedback from the balance folk.

**Comment by jroinc** [comment]
+1 to me. It's too hard to make people pop if they're free. Having the stasis bag stop growth makes it near-impossible.

**Comment by Rohesie** [comment]
Conflicting with #3322

**Comment by Fikou** [comment]
@Rohesie fixed

**Comment by InterroLouis** [comment]
This is unnecessary. Being in a stasis bag means you can't fight at all, and getting out of the stasis bag has a stun associated with it much like getting out of a locker.

**Comment by psykzz** [comment]
I approve in terms of code, but should be checked balance wise.

**Comment by jroinc** [comment]
Balance-wise, I don't think it's needed anymore.

The doubling of larva passive growth speed makes free bursts actually possible if people unga constantly, and the stasis bag being a hard counter to larva's actually fine.

Plus, being in a stasis bag is effectively being in crit for marine combat purposes, so there's that.

**Comment by Fikou** [comment]
what does this revert

**Comment by Rohesie** [comment]
Spooky is signaling that stasis bags used to work in this way and they were changed. So this is a revert to old behavior.

**Comment by psykzz** [comment]
@Fikou can you address @jroinc's comment.
With the latest master, is this still needed?

**Comment by jroinc** [comment]
I mean, it can't hurt, I just don't think it's needed.

People get autodoc'd blindingly fast on crash, and pretty fast on distress.

I suppose it might make a difference if you were nested and it was down to the wire, but I'm not seeing this make more than a 10 progress difference in the course of a normal round.

**Comment by spookydonut** [comment]
I plan to close this in a week due to lack of balance discussion.

**Comment by spookydonut** [comment]
Contact a maintainer if you want to keep working on this.

**Comment by Hathkar** [comment]
I feel this should be reopened, especially with with the surgery table attachment being added as an option for the Alamo.

**Pull request closed without merging**
