### PR TITLE
oxycodone now gives 100 pain resistance over 50.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Oxy has 100 pain resist over 50.

## Why It's Good For The Game
Oxycodone is super mediocre, and barely worth carrying in its current state, it doesn't give you enough pain resist to wobble away from whatever just beat the crap out of you unless you double dose on tramadol as well.

## Changelog
:cl:
balance: Oxycodone gives 100 pain resistance instead of 50 now.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
200 please.

**Comment by Al-1ce** [comment]
> 200 please.

Not even going to explain why that's a stupid idea. No. Just, no.

**Comment by Lumipharon** [comment]
In what situation are you not going to also have tram though?

**Comment by Al-1ce** [comment]
> In what situation are you not going to also have tram though?

Tram gives 50. Neuraline gives 100. I think stacking painkillers should give diminished returns somewhat to begin with but I think somewhere around 85-75 would be better.

**Comment by Jalopkomit18** [comment]
I thought oxycodone always had higher pain resistance than tramadol. If this wasn't the case, then what was the point of using oxycodone over tramadol besides stam on inject and long pain?

**Comment by Al-1ce** [comment]
> I thought oxycodone always had higher pain resistance than tramadol. If this wasn't the case, then what was the point of using oxycodone over tramadol besides stam on inject and long pain?

Those were exactly the reasons. Also because you can mix it with tramadol for any "oh shit" moments. It seems to be good at 100.

**Comment by adamkad1** [comment]
Fun.

**Pull request merged**
