### PR TITLE
Repeater Nerf (lazy edition)

### PR DESCRIPTION
**Pull request by KrabSpider**
Ammo cap to 9 from 13.
Slowdown from 2 to 1.

## About The Pull Request
Ammo cap to 9 from 13.
Slowdown from 2 to 1.
Screenshake removed.

## Why It's Good For The Game
Remember that stuff I said about the repeater being a "self-defense gun" when I reworked it to using its own ammo? Yeah. I'm stupid like that. Anyway, it still procs staggerstun on mobs within a 3 tile range, you won't be chaining it on slower xenos through the slowdown though. I also felt like it had far too much ammo it had no business having. 

## Changelog
:cl:
del: Repeater screenshake (it did nothing)
balance: Repeater holds 9 (10) rounds from 13. 
balance: Repeater slowdown reduced to 1 from 2. 
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Seems like decent comprimises.

**Review by Pariah919 — COMMENTED** [review]
Why are you nerfing the size to 9 from 13? Just remove shake and slowdown, it'll be fine that way.

**Comment by Naaanii** [comment]
Maybe add extra rounds and let it have 15 to compensate as the gun isn't all that overpowered honestly.

**Comment by KrabSpider** [comment]
> Why are you nerfing the size to 9 from 13? Just remove shake and slowdown, it'll be fine that way.
 
To spite Zaha.

**Comment by Dzhimax** [comment]
It`s bad for the game. Автор долбоёб. Ебанат, понерфи револьверы и дробовики, а не репитер

**Comment by TiviPlus** [comment]
Your justification is "to spite people" so im gonna say to go come back with proper changes pls

**Pull request closed without merging**
