### PR TITLE
Replaces the jumpsuit for cmo/RO/MOs get with new sprites

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image
image
image
Updates the jumpsuit sprites on these 3 to be a bit more modern, made by J*ff.

## Why It's Good For The Game
Makes them more modern and they look better than the old ones in my opinion.

## Changelog
:cl:
Jeff Pariah919
add: Added new green scrub sprites and cmo scrub sprites, new RO sprites for his jumpsuit and new Cargo tech sprites by Jeff.
del:Old jumpsuit sprites for RO/CMO/CT. Git will remember them. Nobody else will.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -53. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by neohenry** [comment]
The more we get rid of CM stuff, the better.

**Review by Kuro-ai — APPROVED** [review]
our art mantainer is dead,so I'm giving my approval in his place for whatever it's worth,the sprites are good 👍

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-55). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
