### PR TITLE
water buff

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
has infinte cycles after 6 to 10, less stamina loss recvoery (-0.15 from 0.5) but same limb health

## Why It's Good For The Game
makes water have a bit more utility as a budget paracematol that purges chems you don't like

## Changelog
:cl:
balance: after the initital rush of effects are over, water still has an effect on you. Heals minor stamina loss and health damage.
/:cl:

### CODE REVIEW

**Comment by Ieteihowmee** [comment]
Good. Can we make it so we can fill up bottles from water tanks? That would be nice.

**Comment by davidchan13** [comment]
> Good. Can we make it so we can fill up bottles from water tanks? That would be nice.

This is default behavior, you can already do this.

**Review by TiviPlus — APPROVED** [review]
stay hydrated

**Comment by Tristan63** [comment]
sergeant major says:

stay hydrated you dumbfuck!

**Comment by davidchan13** [comment]
someone code canteen waterbottles that spawn in standard kit.
MARINES WILL DRINK 4-8 CANTEENS OF WATER EVERY OP, NOT TO EXCEED 8 CANTEENS. HYDRATE, FUCKBAGS!

**Pull request merged**
