### PR TITLE
Hyperscales Guns: Take 3

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request
WE BACK! THIRD TIMES THE CHARM BABY!
Hyperscales a handful of gun furniture.
T12, T18, T81, T42, T21, T35, TP14, TP23, TP44, TX11, TX15
Also hyperscales the vgrip and agrip.

image
image
image
image
image
image
image
image
image

## Why It's Good For The Game
Colorable guns.

## Changelog

:cl:
add: Hyperscales T12, T18, T81, T42, T21, T35, TP14, TP23, TP44, TX11, TX15
add: Hyperscales the agrip and vgrip.
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
worst pr I've ever seen
merge immediately.

**Comment by Aporhtonoma** [comment]
INTRODUCING THE HELLO KITTY T14

**Comment by efzapa** [comment]
speedmerge
speedmerge

**Comment by zee11zee** [comment]
Can you pretty please add R76, I understand if not. But awsome work tho!

**Comment by FosterGrime-Heymynameslouie** [comment]
third times the charm

**Review by TiviPlus — APPROVED** [review]

**Review by Kuro020 — APPROVED** [review]
Surely byond wont shit itself this time

**Comment by TiviPlus** [comment]
It did not 🎉

**Pull request merged**
