### PR TITLE
(APRIL FOOLS) Alternative Ammo Types

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
Adds 5 different ammos to 10x24 guns (AR-12, AR-18, MG-42)

https://github.com/tgstation/TerraGov-Marine-Corps/assets/20828943/ded9f73f-9106-4020-89c7-a0aab7bc18e0
## Why It's Good For The Game
Kuro wanted variety in ammo from the success in Squash Head on the SMG-45.
## Changelog
:cl:
add: Specialized Ammo: 5 new ammo types for AR-12, AR-18 and MG-42! Find them in the "Specialized Ammo" section of the Weapons Vendor!
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
image
dear god

**Comment by FosterGrime-Heymynameslouie** [comment]
mmmmmm raingbow

**Comment by Dolth** [comment]
Removing 10 damage from a 25 (and hardly any AP) damage bullet is way too big. Magdump stuff and it hardly kills.
Too weak.

**Comment by FosterGrime-Heymynameslouie** [comment]
I didnt realize this was april fools at first and thought it was a geunine additiion to req or something

still would be pretty cool if after april fools cryo bullets or something got in req/req factorio

**Comment by zzurge** [comment]
Im ngl cryo or depleted uranium ammo would be hawt to have as a non april fools thing...

**Comment by FosterGrime-Heymynameslouie** [comment]
salute

**Pull request closed without merging**
