### PR TITLE
Freedom of Movement buff, and xeno sticky weed buff

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Humans no longer use stamina on running. Human stamina buffer reduced to 30, robots, synths and the like that can't run currently still cannot run. Humans below 0 stamina cannot run still.

Sticky weed cost reduced by 1 whole multiplier. It is now x2 normal cost rather than x3 to compensate for increased marine movement.
## Why It's Good For The Game
TGMC is too slow paced a game ever since stamina, in my years and years of attempts to speed the game up to encourage wonton aggression my number one enemy has forever been stamina, I seek to lay to rest this haphazardlly made in 5 minutes by Rohesie mechanic to rest forever and return running to its rightful place as the normal form of movement.
## Changelog
:cl:
balance: Humans no longer use stamina on run.
balance: Sticky weed cost reduced due to human mobs no longer using stamina on run.
/:cl:

### CODE REVIEW

**Comment by Autisem** [comment]
This is a horrible idea, running human can outrun many of the xenos and this will make sure there is NO counterplay for these casts

**Comment by RipGrayson** [comment]
You want to break map balance, allow marines to rush across the map in under 30 seconds without stopping

**Comment by Beepinex** [comment]
give up 20 stamina for infinite sprint? in exchange sticky weeds become mandatory to slow marines? tg ss13 is like what you propose, and people there ONLY walk so they dont slip! i'd love to hear why this is good for the game from a xeno pov

**Comment by Losenis** [comment]
The problem with sticky resin isn't the cost, it's that it's something you have to build on a per-tile basis so it's extremely time consuming even if you're a hivelord doped on power fruit. If you want to buff sticky resin, change the sticky spit ability to throw something similar to a resin hugger on impact that covers a 3x3 space, then change the cost and cooldown accordingly.

**Comment by InterroLouis** [comment]
> The problem with sticky resin isn't the cost, it's that it's something you have to build on a per-tile basis so it's extremely time consuming even if you're a hivelord doped on power fruit. If you want to buff sticky resin, change the sticky spit ability to throw something similar to a resin hugger on impact that covers a 3x3 space, then change the cost and cooldown accordingly.
> 
> Also infinite stamina was already tested and rejected.

Losenis this is sticky WEEDS not sticky RESIN.

**Comment by Kuro020** [comment]
hey look, its the yearly "no stamina" mjp pr

**Comment by Joe13413** [comment]
ya know i feel like speeding up the game and making it more fast paced would be a welcome addition
but this PR just seems half baked. in the games current state, giving marines infinite sprint would totally fuck balance. im down to get PRs that make the game faster, but this would just screw xenos so hard. give this a little more thought than "make xenos place sticky weeds"

**Comment by Losenis** [comment]
>Losenis this is sticky WEEDS not sticky RESIN.

oh shit lmao my b

**Comment by Al-1ce** [comment]
>Humans no longer use stamina on running

About last time when this was tried and TM'd, it killed the fucking server. We had regular <30 pop because NOBODY wants to play xeno against this.

TGMC is not slow paced. You are insane.
-1

**Comment by Al-1ce** [comment]
>Humans no longer use stamina on running

This was TM'd last year. And the year before that. Both times, it ended up obliterating the server population. We've went from a consistient 60-80 to a 20-30 average (at peak hours) whenever someone has tried this.

TGMC is not slow paced. You are insane. Stop trying to impliment this retarded PR. It's never going to get merged. Never.

**Comment by Passe2142** [comment]
You could try buffing certain chems and reward certain players that take some time to prep instead of giving for free _the chase_. Marines are by no means slow, this will bring back high burrowed numbers as it did back then.

**Comment by Losenis** [comment]
>reward certain players that take some time to prep

If you spend even a second doing anything in prep other than waiting in alamo it'll be called powergaming and will be nerfed to extinction at the earlier convenience. See: putting roundstart-available PFC accessible chems into pill bottles for convenience, IE the chem machine.

**Comment by Passe2142** [comment]
> If you spend even a second doing anything in prep other than waiting in alamo it'll be called powergaming and will be nerfed to extinction at the earlier convenience. See: putting roundstart-available PFC accessible chems into pill bottles for convenience, IE the chem machine.
They could buff water, or certain basics pills. Even making req synap avaible or some sort of stam drug with some drawback. Not saying they should all be able to run but naked to chem dispenser as if it was a valk order. This PR is not needed and will break the game as it did back then.

**Comment by InterroLouis** [comment]
We played for a long time with running as the default and it was perfectly fine, but back then regular weeds slowed marines. I suppose maybe if all weeds had an amount of slowdown with sticky weeds just having more slowdown than the rest? The xeno cabal will never let this pass anyways. Running forever is a xeno exclusive power.

**Comment by bowlofcereal** [comment]
hasn't this been tried 3-4 times in the past and everytime it was tm'd it killed the xeno population because we outran every single caste? like i recall not even bothering to leave the FOB because it killed any entertainment in frontlining from how superpowerful it made us

**Comment by Lumipharon** [comment]
I uh, think this is not a good idea.

**Pull request closed without merging**
