### PR TITLE
Nerf plasma regen

### PR DESCRIPTION
**Pull request by psykzz**
## About The Pull Request
Nerfs plasma regen but making it unaffected by pheroes

## Why It's Good For The Game
Plasma should be important and this will increase the impact of large plasma pools vs just using abilities and resting quickly

## Changelog
:cl:
balance: plasma regen is no longer affected by recovery pheroes
/:cl:

### CODE REVIEW

**Comment by psykzz** [comment]
I think by itself this is too much for xenos, we'd likely need to pair it with armour or the other health buff, but we'll see.

**Comment by Pariah919** [comment]
pair with https://github.com/tgstation/TerraGov-Marine-Corps/pull/4583.

**Comment by TiviPlus** [comment]
Make sure to change the changelog

**Comment by psykzz** [comment]
Updated

**Pull request merged**
