### PR TITLE
Pillar of Spring Fall Renovation: MP Edition [MDB ignore]

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request
Expand PoS by 3 tiles north!
PoS

Expand and shuffle medbay around to permit maint hall and tighter medbay. Medbay also has a loadout vendor for researchers and vatborns to use. MDs now have a dedicated shower room!
image

Researcher landmark updated!
image

Move memorial from prep to south of medical.
image

Decrease PO's bunk because of how incompetent they are, and they don't deserve fluff.
image

Prepare MP's room. He just needs funny computer now.
image

Change marine's prep to FORCE THEM to live in bunk beds. WITNESS THE TRUE MARINE EXPERIENCE! THEY ARE NOT GOING TO PASS BARRACK INSPECTION!
image

Change marine's prep in light of new traffic. Also add more loadout vendors for easy access.
image

Shuffle SL prep with smartgunner. Also give SL prep more bling.
image

Add bathrooms.
image
image

Add some vendors near Alamo in case if marines forget something!
image

Expand briefing!
image

Pretty AI core.
image

Shuffle around engineering in light of AI core changes
image

Elimination of engineering storage room permits PACMAN to be near Alamo.
image

Move starboard ERT landing zone to SD, and speaking of SD, making SD easier to defend.
image

Dark room simulation! Practice how bright your lights are in a dark environment, realistic to when you are dealing with xenomorphs.
https://user-images.githubusercontent.com/6610922/192429251-586194cc-c7e8-40ed-8519-579d6c302cff.mp4
image

CIC gets more vendors, yay
image

## Why It's Good For The Game

POS is the most popular shipside map, and with the incoming MP, it's time to update POS to have MORE bling.

## Changelog
:cl:
expansion: Pillar of Spring map!
expansion: POS medical. Also, connect a maint hall to medical.
expansion: AI core
add: MP room
add: bathrooms
expansion: Change marine's prep to FORCE THEM to live in bunk beds.
expansion: Dark room simulation! Practice how bright your lights are in a dark environment, realistic to when you are dealing with xenomorphs. Go to the PoS's firing range and check it out!
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Make the cardboard stack next to the autolathe 50 instead of a single piece of cardboard like every other map as well, please.

**Comment by FosterGrime-Heymynameslouie** [comment]
>Decrease PO's bunk because of how incompetent they are, and they don't deserve fluff.
):

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Space tiles here
tile1
tile2
tile4

On the subject of this door, I don't think doctors have researcher access, which would block them from accessing the morgue.
tile5


This area is strange, wall usually don't offset like this.
tile3

It might be nitpicky, but this area also just looks odd. It could be because it's a tight corridor in what is otherwise a fairly open medbay.
tile6

**Comment by Starfirejordan** [comment]
feedback: un-needed taking away of fluff and un-needed forced fluff 

Just add mech dudes room next to POs and be done with it

**Comment by Edelor68** [comment]
Does this fix #11055 ?

**Comment by novaepee** [comment]
> Does this fix #11055 ?

yes

**Comment by novaepee** [comment]
> feedback: un-needed taking away of fluff and un-needed forced fluff
> 
> Just add mech dudes room next to POs and be done with it

lel literally have mech dudes next to po

**Comment by Jalopkomit18** [comment]
The NanotrasenMed Plus vendors don't share an inventory; they each have their own individual inventory. This means I can vend 45 pill bottles of each med total from the three vendors.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
This carpet is just floating around in the CL lounge
tile16
This decal under the hypersleep computer is just sitting there, unconnected
tile26
This decal is just sitting there unconnected to anything
tile24
Pipe network problems from the corruption
tile17
tile25
tile18
tile19
tile21
tile22
tile23

This wall has been totaled by corruption
tile20

**Comment by FosterGrime-Heymynameslouie** [comment]
wouldn't ERT landing spot being right next to SD be a bit iffy given how if it was an xrt or som ERT SD force gets obliterated instantly instead of the ERT first trying to make its way to SD and potentially coming across the xenos?

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: f672f018d98fbc3542ada38d6260f37d4c50d0e3
Pull Request: 31dfa2bba4472d9176eb9311f8d9d9482c944b6a
Server: 0f2e13d46370ed4b71632488688e40bdd3acef2e

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Review by Kuro020 — APPROVED** [review]

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 244e28c96322ec39d06af2ab8d05ce6051299714
Pull Request: 31dfa2bba4472d9176eb9311f8d9d9482c944b6a
Server: b22fb77831c1f2dbc2222fb125416ba2220e64c4

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 244e28c96322ec39d06af2ab8d05ce6051299714
Pull Request: 31dfa2bba4472d9176eb9311f8d9d9482c944b6a
Server: 08424fe2de96d50e0d4e6739f9184a5fd165907b

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 3398322f1f506d5ac8ae36ca492d3fb015506b02
Pull Request: 31dfa2bba4472d9176eb9311f8d9d9482c944b6a
Server: 8a3c8b025777ba377bb061b61a5c7ec23f61e9af

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Review by RipGrayson — CHANGES_REQUESTED** [review]
tile26
tile27
You can escape into space, these walls aren't hull or invincible.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
The shutters here are both breakable, please fix this
tile28

**Review by RipGrayson — CHANGES_REQUESTED** [review]
I'm not really fond of the dropship being blocked like this, it looks weird.
blocked

**Comment by Edelor68** [comment]
There is a wall in the door that leads from the medical researcher room into the morgue

**Comment by Losenis** [comment]
Ok but why though

image

**Comment by RipGrayson** [comment]
> Ok but why though
> 
> image

This has actually been addressed already, the TM just hasn't updated serverside.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Camera coverage issues

Floating camera


Engineering should probably be one area to avoid situations like this


Missing firelock & wire


Floating light

**Review by RipGrayson — APPROVED** [review]
Merging in 24 hours, leave your feedback in that timeframe or not at all.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
unknown
Fix this and I'll merge

**Comment by zzurge** [comment]
I quite welcome the QOL additions,my only reservation if you can call it that is why touch up brief? we have long since done away with briefings traditionally

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
GAME\tiviplus

##### Revision
Origin: 97bb57b1283bcd96910a866f9b257d4422f807e6
Pull Request: 0e10b29f38c3955b6b462ad8e5b322237b90aff8
Server: 55af5738f09e4f32af093c8b6b6aba41f6390460

##### Comment
No comment set - Fast Add
[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Pull request merged**
