### PR TITLE
Fixes minerva mech stairs being uggli

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
image

image

## Why It's Good For The Game
Stair

## Changelog

:cl:
fix: Fixed Minerva Mech Bay stairs being of the wrong type
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
why do you have extra corner pieces?

**Comment by lbnesquik** [comment]
> why do you have extra corner pieces?

I think it looks good!

**Comment by Lumipharon** [comment]
Your pic had 4 corners instead of 2, is what I meant
image

**Comment by lbnesquik** [comment]
> Your pic had 4 corners instead of 2, is what I meant image

Yes this is on purpose, like the staircases in many of the houses I lived in.

**Review by ivanmixo — APPROVED** [review]
Looks fine imo

**Review by Lumipharon — CHANGES_REQUESTED** [review]
the extra bits crop, you literally can't see them. Look at it in game instead of the editor.

**Comment by Lumipharon** [comment]
Bruh, why'd you get rid of the corners lol? the original had the correct 2 corners. I was saying you added 2 MORE corners 4noraisin.

**Comment by AzonStarfall** [comment]
Minerva removed in #13988.

**Comment by ivanmixo** [comment]
Death

**Pull request closed without merging**
