### PR TITLE
replaces the old belt sprites with new ones 

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
replaces the old marine belt sprites with new ones

## Why It's Good For The Game
new belt better than old

## Changelog
:cl:
add: Added new belt sprites by kuro
del: Removed old belt sprites, git will remember them. Nobody else will
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -68. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
image
everything here is by kuro but the shotgun belt

**Review by TiviPlus — CHANGES_REQUESTED** [review]
The ammo one doesnt look like an ammo belt

**Comment by Pariah919** [comment]
@TiviPlus its this now 
image

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-70). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
