### PR TITLE
Mecha and pilot minimap fix

### PR DESCRIPTION
**Pull request by tanker4390**
## About The Pull Request
Mechas and their pilots will now properly display their minimap icons, with icons for occupied and unoccupied mechas (previously the pilot's icon would remain at the location where they entered the mecha until they exited it).

Screenshot_20230129_084227

Might still be buggy.
## Why It's Good For The Game
Bug fix.
## Changelog
:cl: Tanker
fix: Mechas and their pilots will now properly display their minimap icons
/:cl:

### CODE REVIEW

**Comment by Starfirejordan** [comment]
will the In mech icon move with mech, or will mech have an icon for itself?

**Comment by tanker4390** [comment]
> will the In mech icon move with mech, or will mech have an icon for itself?

The mech will have an icon, which changes depending on whether it's occupied.

**Comment by Lumipharon** [comment]
Does this remove the minimap button for the MP when in a mech?

**Comment by tanker4390** [comment]
> Does this remove the minimap button for the MP when in a mech?

Hmm. I didn't think of that being a side effect of calling `remove_minimap`. I'll see if I can fix that.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
This really feel like a hack instead of fixing the core issue which is that minimap registers to Move() of the user and not the mech

**Pull request closed without merging**
