### PR TITLE
Refactor udders to a component

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/58910/files

you can milk anything shitcode free 
## Changelog
:cl:
refactor: refactored udders
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
What? Why?

**Comment by Pariah919** [comment]
this is cursed

**Comment by jroinc** [comment]
*sluuurp* time?

**Comment by ilikesaying** [comment]
FC udders

**Comment by David-Stormwell** [comment]
what in the fuck

**Comment by ilikesaying** [comment]
### **FC Udders**

**Review by SplinterGP — COMMENTED** [review]
give it to hivelord to milk hivelord jelly

**Review by SplinterGP — APPROVED** [review]

**Comment by SolarMacharius** [comment]
Speed Merge this

**Comment by jroinc** [comment]
> 
> ### **FC Udders**

I can do this now

**Pull request merged**
