### PR TITLE
Vali Tweaks

### PR DESCRIPTION
**Pull request by RikuTheKiller**
## About The Pull Request

Changes the wording in multiple balloon messages, for example replacing "resource" with "green blood" since that's what the suit description says.

Oh, I also removed a redundant check for the volume amount since the checks happen on the same frame regardless of whether or not it's at the end of the checks or at the beginning. (Perhaps someone forgot to remove it?)

The pull request was, at first, aimed to fix a bug regarding the degeneration overlay, but somehow a person had fixed it in the time span of me discovering the bug a day earlier and then trying to fix it like, yesterday. So uh, yeah, the change I THOUGHT had fixed it has been reverted. (Tested in-game on dream daemon, bug was still gone even after moving it back.)

## Why It's Good For The Game

Having better wording on messages is good for obvious reasons and not having inconsistent mentions of "resource" and "green blood" clears up some things and makes vali easier to understand for people who didn't look at the wiki or ask others for help.

## Changelog
:cl:
del: removed useless vali messages
del: removed redundant check for volume amount
spellcheck: changed the exact wording on some of the vali balloon messages
/:cl:

### CODE REVIEW

**Comment by RikuTheKiller** [comment]
For the maintainer that reviews this, please remove the "Fix" label as the "Fix" portion of the PR had already been done earlier within a day of me figuring out the bug. How that happened is beyond me. (The PR still contains the wording changes and the removal of useless checks and messages.)

**Review by BraveMole — APPROVED** [review]
Ballon alerts sentences do not take any period at the end.

Rest is good

**Comment by RikuTheKiller** [comment]
> 

I see the periods in game, though?

Or do you mean that they shouldn't have periods whatsoever.

**Comment by RikuTheKiller** [comment]
Fixed.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
