### PR TITLE
Makes somolent little bit less useless

### PR DESCRIPTION
**Pull request by Franky2025**
## About The Pull Request
-Somolent changed to start working from 25th cycle.
-Clone damage healing slightly increased
-Added a message indicating the medicine started working.
-Starting from 25th cycle, has a chance to deal stamina damage based. on how long it has been in the patient

## Why It's Good For The Game
Somolent is useless as of now, and is the only way to heal cloneloss outside of shipside medbay. Its specific usage and creation makes it never used. This might change that, and allow for some medics that are willing to go out of their way a unique ability to heal clone and additionally heal critical patients quickly in safe conditions on ground.

## Changelog
:cl: kait
balance: rebalanced somolent
/:cl:

### CODE REVIEW

**Comment by Franky2025** [comment]
i hate dm

**Review by BraveMole — APPROVED** [review]

**Comment by BraveMole** [comment]
What this tested?

**Comment by Franky2025** [comment]
> What this tested?

if youre asking if this was tested, i have tested it yes

**Comment by Franky2025** [comment]
okay i really dont like dm give me a sec

**Comment by Franky2025** [comment]
what is the issue here even lol

**Pull request merged**
