### PR TITLE
New Shrike strain: Squall

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
hi
it's me again
i've made a questionably balanced strain for shrike that everyone will hate
do you guys remember #10418
no?
ok cool

# The Squall
the squall as a strain is meant to be a more offensive version of the shrike; trading most of its supportive abilities/capabilities for extra damage, effectively turning them into more of a frontliner role capable of dishing out considerable damage, especially in enclosed spaces

### removals
- loses cocooning
- loses egg laying
- loses ozelomelyn sting
- loses psychic cure
- loses transfer plasma

### psychic fling
- cooldown reduced from 12s to 6s
- plasma cost reduced from 100 to 50
- stun duration reduced from 2s to 0.2s (effectively just a disarm)
- will now deal additional damage if the target is flung against the wall, works exactly like warrior fling

### unrelenting force
- cooldown reduced from 50s to 25s
- plasma cost reduced from 300 to 150
- stun duration reduced from 2s to 1s
- weakness duration reduced from 2s to 1s
- also has a wall bang effect, same as described above

### stat changes
- melee damaged reduced from 25 to 23
- speed increased from -0.4 to -0.8 (now goes zoom)
- maximum health reduced from 500 to 450

### literally everything else
- minor refactor of shrike abilities to account for strain changes
- knockback proc now accepts spin as a var

## Why It's Good For The Game
more content good, caste variety with strains also good, this is also fun and more fitting with current xeno balance compared to how it was before

## Parting thoughts
i was originally gonna make a unique primo but i got lazy and decided i'd rather not
instead i release the product as is since it was mostly finished besides that
enjoy

## Changelog
:cl:
add: new shrike strain: squall
del: loses some abilities in exchange for buffs on others: cocooning, egg laying, ozelomelyn sting, psychic cure, transfer plasma
balance: psychic fling; cooldown 12s > 6s, plasma cost 100 > 50, stun duration 2s > 0.2s (effectively a disarm), wall bang effect a la warrior
balance: unrelenting force; cooldown 50s > 25s, plasma cost 300 > 150s, stun duration 2s > 1s, weakness duration 2s > 1s, wall bang effect a la warrior
balance: stat changes; melee damage 25 > 23, speed -0.4 > -0.8 (much faster), maximum health 500 > 450
refactor: minor refactor of shrike abilities to account for strain variations
code: knockback proc now accepts spin as a var
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
do you think anyone will listen if i tell them balance is hard and that i'll probably tweak numbers after testmerges

**Comment by blackdav123** [comment]
its peak

**Comment by Barnet2** [comment]
Neat, I really disliked to play Tanya shrike so the fact I can choose between the two is nice

**Comment by yyzsong** [comment]
not bird named 2/10

**Comment by lKiseki** [comment]
> not bird named 2/10

give me a cool bird name and i'll do it

**Comment by Pariah919** [comment]
> do you think anyone will listen if i tell them balance is hard and that i'll probably tweak numbers after testmerges

no
i don't really like increasing the speed and only... removing 50 hp, especially if it spam stutterstuns so consistently. Though in general I think most strains should straddle around the same level of speed.

**Comment by Ragecrabbo** [comment]
Losing pretty much all abilities, the heal especially in exchange for shorter cooldown and lower cost but no stun flings does not seem like a good trade. Not sure what -0.8 is in terms of speed but im guessing its somewhere in runner-tier. 
This will be either incredibly useful or incredibly bad but either way it will be interesting to see 👍

**Comment by yyzsong** [comment]
> > not bird named 2/10
> 
> give me a cool bird name and i'll do it

~~boobie~~ ~~tit~~ Lark or Thrush. There's even a bird called the "Shrikethrush" which will make the part where we put the strain name before the caste name less awkward (unless tivi did that differently) (even then it will be out of order)

Alternatively you can go with Kingfisher

**Comment by Wisemonster** [comment]
Ok, minor issue, currently this would let there be 2 shrikes active in the hive if the first shrike strain swaps to squall. Doesn't appear to be an issue with your pr, but rather how strains was coded. This should probably be fixed before this is tmed, else there's gonna be up to 4 T4s running around, 2 of which don't require timers for someone to evolve to.

**Comment by SimplySmiley123** [comment]
> > do you think anyone will listen if i tell them balance is hard and that i'll probably tweak numbers after testmerges
> 
> no i don't really like increasing the speed and only... removing 50 hp, especially if it spam stutterstuns so consistently. Though in general I think most strains should straddle around the same level of speed.

The only thing I hate about this, is that it would allow to just spam the stagger/stun/displacement abilities even more.
And nobody likes playing against those.

**Comment by yyzsong** [comment]
> Really needs a sprite you can differentiate from base shrike, like all strains should.

slight red tint (because it's faster)

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Screenshot_20240701_094906_Discord

**Comment by Ragecrabbo** [comment]
Give it the psychic choke from OG shrike but make it require LoS :trollface:

**Comment by lKiseki** [comment]
> Screenshot_20240701_094906_Discord

i'm too lazy to make new abilities and finding new sprites is lol so

**Comment by Naaanii** [comment]
Noooooooooooooooooooooooo

**Pull request closed without merging**
