### PR TITLE
Remove rocket sledge from req

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

See title.

## Why It's Good For The Game

MJP said so.

## Changelog
:cl:
del: Removed rocket sledge from req.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
Silly, considering the entire gimmick of the sledge in the first place.

**Comment by Wayland-Smithy** [comment]
Then why does it not effect queen? I think because the creator knew it would be silly so why is it okay for other big slow mobs?

**Comment by private-tristan** [comment]
Gorgers' existences no longer hard countered by a 60 point req item? cool

**Comment by Pariah919** [comment]
>Then why does it not effect queen? I think because the creator knew it would be silly so why is it okay for other big slow mobs?
>
IIRC, people got mad at it stunlocking queen, since she's pretty slow compared to all the other T3s and "Large" xenos.
I don't really see a reason for it to exist in the first place if your'e gonna extend the immunity, anyway, just delete it.

**Comment by Wayland-Smithy** [comment]
If full removal will be accepted more readily then sure. I prefer this change since removing content is no fun and this way how it effects targets is also more predictable. The majority of any healthy hive is not even "large" so the overall *impact* of this is being blown out of proportion I feel.

**Review by BraveMole — CHANGES_REQUESTED** [review]
IDK, as MJP said that's the whole hammer gimmick. 

Queen got a pass because people mald at the hammer, but I don't think she deserved that special treatment either

**Comment by Wayland-Smithy** [comment]
As per MJP suggestion I have removed it from req altogether, but left it in code elsewhere for Valhalla and special events.

**Comment by BraveMole** [comment]
Hammer is fine and doesn't need to be killed

**Comment by Wayland-Smithy** [comment]
Okay Mole what ever you say. Just don't be surprised when this and the almost as cheap AMR come out then xenos SSD from the BS.

**Pull request closed without merging**
