### PR TITLE
Removes View Crew Manifest from the Lobby.

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
Better compromise to revealing both teams.
## Changelog
:cl:
del: Removes View Crew Manifest from lobby.
/:cl:

### CODE REVIEW

**Comment by BettaSplendid** [comment]
Revealing both teams?

**Comment by Luxyboo** [comment]
> Revealing both teams?

the last PR they made was to show hive status but they opted for this one for some reason

**Comment by KerbalCitizen** [comment]
I use view crew manifest to decide to join or not pretty often. Good people in roles like medical or RO make me want to play instead of just calling it for the day. 

 I don't really see there being much of a balance concern about information asymmetry here. If you want to play xeno, you can just observe, look at orbit menu, then join larva queue. I do it once a while when deciding if I want to play xeno. You could use it when joining as marine too, but you'd either wait for respawn or could just ahelp to be sent back to lobby. Besides, alive xenos can just look at the marines in FOB before shutters open to know who is on marine team, granted you can't tell who is shipside via this. 

I just don't really see the point in this PR.

**Comment by shelteredfreak** [comment]
You sly devil, were you looking at the Discord when we were talking about the other PR?

Anyhow, this actually surprised me considering that you've talked about just joining the team with the better players, which is what some like to do. This being a negative thing because it often leads to one side being stacked against the other because all the players flocked to one side that had better people on it.

I like this, it promotes players to pick the team they want to play instead of picking the team that's going to win. Afterall, this is a game, not a competition. The goal is to win but the journey is to have fun, no?

**Comment by Losenis** [comment]
Bad change. If you want to play xeno you can already just obs then check both xeno and marine compositions to decide if you're going xeno, continue obsing, or playing another game. As marine the only pre-join information you can get is crew manifest and whatever role you're unable to pick due to being full, latter of which isn't a good indication of anything since you can't tell if that role was taken by either MSGT Autismus Maximus or PVT Shitfuck, something ghosts can not only fully see while obsing before entering larva queue but also whatever said marines might be doing or not doing, like forgetting to build fob.

**Comment by Naaanii** [comment]
> I use view crew manifest to decide to join or not pretty often. Good people in roles like medical or RO make me want to play instead of just calling it for the day.
> 
> I don't really see there being much of a balance concern about information asymmetry here. If you want to play xeno, you can just observe, look at orbit menu, then join larva queue. I do it once a while when deciding if I want to play xeno. You could use it when joining as marine too, but you'd either wait for respawn or could just ahelp to be sent back to lobby. Besides, alive xenos can just look at the marines in FOB before shutters open to know who is on marine team, granted you can't tell who is shipside via this.
> 
> I just don't really see the point in this PR.

This will reduce the meta aspect. Players shouldn't be joining teams just because X player is on it. People can already coordinate via Discord or whatnot but this reduces it.

**Comment by KerbalCitizen** [comment]
> You sly devil, were you looking at the Discord when we were talking about the other PR?
> 
> Anyhow, this actually surprised me considering that you've talked about just joining the team with the better players, which is what some like to do. This being a negative thing because it often leads to one side being stacked against the other because all the players flocked to one side that had better people on it.
> 
> I like this, it promotes players to pick the team they want to play instead of picking the team that's going to win. Afterall, this is a game, not a competition. The goal is to win but the journey is to have fun, no?

Sometimes I just don't want to play with no one/ bald people in important roles. If I'm relying on req like I do as smartgunner or engi, then someone like Zaha as RO is definitely going to make me want to play. If it's just some random name that I don't recognize, I'm less inclined to go for that loadout/ playstyle. I often focus on getting those sweet req points, carrying xeno analyzer and fulton in my backpack. It's amazing when a good RO sends me the shit I need on time and at the right place when I got those points, it's also kinda miserable when I never get my order because RO is overwhelmed/ nonexistant. 

>This will reduce the meta aspect. Players shouldn't be joining teams just because X player is on it. People can already coordinate via Discord or whatnot but this reduces it.

I just do not enjoy playing rounds where I know marines lack good players in important roles. So many rounds where marines just have no (good) medical roles so despite good fights, marines just end up whittled down because of no medics. Or when there's no one that wants to build FOB and has access to do so, I just do not find it fun to be there.

**Comment by Goblinu** [comment]
> Sometimes I just don't want to play with no one/ bald people in important roles. If I'm relying on req like I do as smartgunner or engi, then someone like Zaha as RO is definitely going to make me want to play. If it's just some random name that I don't recognize, I'm less inclined to go for that loadout/ playstyle.

ITT: People should stop hyper minmaxing WR and try to enjoy the game instead of using meta knowledge so they know it their meta buddy will give them their req points for their cool loadout.tm

**Comment by KerbalCitizen** [comment]
>ITT: People should stop hyper minmaxing WR and try to enjoy the game instead of using meta knowledge so they know it their meta buddy will give them their req points for their cool loadout.tm

Smartgunners just become normal marines when they run out of SG ammo, assuming you either carry, find, or get RO to send down a normal weapon with ammo. Req is a hard job when you have multiple people ordering shopping lists, but some ROs are good enough to handle it and still do stuff like reqtorio or overwatch. Analyzing and fultoning a few xenos then asking for ammo multiple times to never receive any is just not fun. 

Engineer is kinda varied in how req point dependent they are. Fortifying disks or miners will cost quite a bit. Sometimes engis use the drone (aka UV, or iguana) or man artillery, which need req points to work. 

Not being able to play the game because of a shit RO that doesn't fulfill any orders (not just mine) and not because of a lack of req points (which is completely understandable) is just not fun to me. Especially if I sent a lot of req points, it just sucks.

**Comment by FIXTHERADBOXPLEASE** [comment]
Yeah, TGMC has a huge problem with good players only joining the team that has the most good statics on, which leads to lopsided rounds. This doesn't make it totally impossible to check, but it's still a great change.

You can just turn around cryo if it turns out your metafriend isn't playing RO to personally give you all your gamer gear. Or ask them on discord. 
I'm not sure why people are complaining about that, you don't HAVE to check the RO from the lobby.

And aside from that, honestly, Cargo Techs should be readded to help pick up the slack for nooby ROs. Call it a bloat role, but it's stupid to have the entirety of req hinge on one guy, in a server where req is arguably MORE important. Even the best ROs will still have to go SSD occasionally. None of this is a problem with this PR. It exists with or without it merged.
(Yes, Captains and Ship Techs can help with req too, but they have a dozen other expectations. I'm talking about as a dedicated role.)

**Comment by Al-1ce** [comment]
This is stupid as fuck.

**Comment by Naaanii** [comment]
> Edit: Had another thought right after I finished this. If I want to play xeno, I can just observe and see hive status. If I like the xeno players, I can join larva queue and pre shutters has no/ short time to wait. If I don't like the xeno players, then I can just close the game and do something else. Assuming this PR gets merged, then marines just have to spawn in and pray, while xenos can actually decide.

Marines can cryo as well. No one is being forced to play the game.

**Comment by Losenis** [comment]
> ITT: People should stop hyper minmaxing WR and try to enjoy the game instead of using meta knowledge so they know it their meta buddy will give them their req points for their cool loadout.tm

Today I learned wanting playing with people you know is hyper minmaxing WR

**Comment by Losenis** [comment]
And tbh yeah you can just spawn as marine, check the crew manifest from inside, then suicide if there's nobody you know. It's better to suicide because you know either bald people or funny suicide vesters grab SSD mob and just take the clone down groundside to die and get psydrained, unless you're a gamer that will deliberatedly suicide it after joining at 40m to have it cocooned/psydrained for more larva points to join as xeno.

This change can have unintended consequences. Better to just add hive status to lobby screen so that both sides get info. Crew manifest is already inaccurate past 30mins because it will not show you who's dead, who SSD'd, who's doing what where with what loadout, etc.

**Comment by KerbalCitizen** [comment]
> Marines can cryo as well. No one is being forced to play the game.

My understanding is that cryo doesn't remove the larva points that you generate from spawning. So you are making it slightly harder for marines/ slightly easier for xenos. Meanwhile there is no effect from someone observing, deciding to not join larva queue, and then just closing the game.

**Comment by Naaanii** [comment]
> > Marines can cryo as well. No one is being forced to play the game.
> 
> My understanding is that cryo doesn't remove the larva points that you generate from spawning. So you are making it slightly harder for marines/ slightly easier for xenos. Meanwhile there is no effect from someone observing, deciding to not join larva queue, and then just closing the game.

There is, 10 burrowed rounds are not uncommon. If people don't join, they don't join. If they enter larva queue, they're playing regardless of who's on the team.

**Comment by Naaanii** [comment]
> Why, you still see how many players are in each job when joining

Yes, but you will no longer see who is in each role etc.

**Pull request closed without merging**
