### PR TITLE
Removes ion storm random event

### PR DESCRIPTION
**Pull request by jonash07**
## About The Pull Request

Pretty much the title

## Why It's Good For The Game

One side being severly crippled just because of pure rng chance is really not good for a team pvp game

## Changelog

:cl:
balance: ion storm (communication blackout) has been removed as a random event
/:cl:

### CODE REVIEW

**Comment by Aporhtonoma** [comment]
personally I feels since marines get straight up positive random events they should get some straight up negatives good example is req points event where its free money and this which is disruption of comms

**Comment by Isy232** [comment]
The free requisitions points events could be removed as well, but the impact of them is far less than taking communications down for long periods of time.

**Comment by Naaanii** [comment]
Don't Xenos get only positive events as well? In terms of extra pay points for draining X marine. They also get 0 negatives for it too so it's kind of completely unfair even if the sides are not 1:1 symmetrical.

> personally I feel since marines already get straight up positive random events they should get some straight up negatives good example is req points event where its free money and this which is disruption of comms

**Comment by iforgotmeword** [comment]
Personally I think this should be reused as a xenos  ability but I'm in favor of just removing it

**Review by ivanmixo — APPROVED** [review]
This reeks!

**Pull request merged**
