### PR TITLE
TGUI updates

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
tm b4 merge

## Why It's Good For The Game
https://github.com/tgstation/tgstation/pull/64331/files
https://github.com/tgstation/tgstation/pull/65054/files
https://github.com/tgstation/tgstation/pull/64227/files
+ adds a missed new component
## Changelog
:cl:
code: updated tgui
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
Broke the 'Try to take SSD mob' option.

**Comment by BraveMole** [comment]
Still breaking ssd mobs it seems tivi

**Comment by BraveMole** [comment]
Still some issues with big prompt box, like the one you get when choosing a silo as a xeno.

Also swaping yes and no would be nice

**Comment by TiviPlus** [comment]
> Still some issues with big prompt box, like the one you get when choosing a silo as a xeno.

pain

> Also swaping yes and no would be nice

its a pref

**Comment by BraveMole** [comment]
Why is it not classic default then. Checkmate atheist

**Comment by MiniMeatwad** [comment]
Might be breaking the game-preferences window, can't access the game preferences through the preferences tab > game-preferences verb, gonna test by untestmerging

**Pull request merged**
