### PR TITLE
edits to human sprites

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request

brushes up the human sprites by gregormn

there's a lot of really little things going on that don't really impact much but just make the sprites a bit nicer; the biggest change is that the female body variant sprites are slightly edited to be wider. it's only noticeable prior to putting on undersuits and armors.

underclothes have been adjusted as needed to fit the edited sprites, as have the chunked torso sprites and groin sprites.

image

other misc things that aren't of particular note:
every sprite (and the various chunked sprites) have had their hand highlighting edited a bit for more defined fingers.
male and chunked sprites now have the same feet as the female sprites since the shading wasn't as harsh on those.

## Why It's Good For The Game

i think they look a little nicer.

less weird clipping issues for back-worn things and stuff.

bonus is that standardization of body sprite size and feet/hand sprites for the chunks might mean that in the future there could be just one set of those sprites for both male and female variants, so there's a potential for some file size reduction. which is nice for maintainability later on.

## Changelog

:cl:
imageadd: edited human sprites
/:cl:

### CODE REVIEW

**Comment by Gregormack** [comment]
Well, good work, i guess? Too little presentation, what has changed?

**Comment by coldironwarrior** [comment]
namely this 
image

**Comment by Lumipharon** [comment]
The seggs update.

image

We had different shaped female sprites in the past and you either A: couldn't tell 99.99% of the time due to stuff ontop.
Or B: produced weird cropping issues when it was actually visible.

If clothes actually wrapped about the mob shape then great, otherwise I'm not a fan.

**Comment by coldironwarrior** [comment]
sorry, i guess i didnt make it apparent, but to be clear: this sprite is equal to the male variant one in terms of the silhouette (one pixel less on the groin on front-facing and two less on the groin and bottom of arms on back-facing; both of these areas, i didnt add anything).

so if the outfits and back-worns for other jumpsuits or guns are cut correctly for the current male sprites, then assuming there is no gender-specific mask applied to clip the sprites (which i was specifically told by you there was not when i asked), any worn sprites should work on this body type sprite. it'd look exactly the same as it does for anyone with a male sprite variant.

**Comment by Lumipharon** [comment]
Some sprites in general have issues but yes, having less pixels means EVERYTHING will have ugly gaps. We specifically changed away from the shape of your sprite, with the latest resprite because of this. Up to Kuro though I guess.

**Comment by coldironwarrior** [comment]
apologies, i think i'm missing the uhhhhhh idea, so bear with me. the sprites i did are the slightly wider ones. less pixels = ugly gaps. current sprites have less pixels and the ones i have in this PR have more pixels and the potential for fewer ugly gaps.

i dont really understand; the latest resprite changed away from the sort that i have where it is wider, but has fewer clipping issues?

**Comment by Lumipharon** [comment]
Oh I'm just brain damaged then.

**Comment by coldironwarrior** [comment]
no, is okay :pensive: i didn't help either by not labelling which sprite was which. im also the person that puts the "after" photo before the "before" photo

**Comment by Kuro020** [comment]
I like gregors sprite more

**Pull request closed without merging**
