### PR TITLE
Revert "Campaign gamemode"

### PR DESCRIPTION
**Pull request by TiviPlus**
Reverts tgstation/TerraGov-Marine-Corps#13990

CI is broke for everyone now

### CODE REVIEW

**Comment by yyzsong** [comment]
real

**Comment by Blundir** [comment]
what

**Comment by Lumipharon** [comment]
will merge if we can't sort out the hard del

**Comment by spookydonut** [comment]
see #14017

**Comment by Lumipharon** [comment]
hard del fixed

**Pull request closed without merging**
