### PR TITLE
Valhalla fix

### PR DESCRIPTION
**Pull request by goose4429**
## About The Pull Request

Fixes missing equipment in Valhalla. Ammo boxes, medical stuff.

## Why It's Good For The Game

Fix good, loadout easy

## Changelog
:cl:
fix: Added missing equipment to Valhalla vendors
/:cl:

### CODE REVIEW

**Comment by goose4429** [comment]
I go sleep, so you have few hours to delete your meme comments before I see them

**Review by TiviPlus — APPROVED** [review]
Fix your cl being add instead of fix and note that the prefix is for the image not the text

**Comment by goose4429** [comment]
> Fix your cl being add instead of fix and note that the prefix is for the image not the text

Done

**Comment by TiviPlus** [comment]
Not fully I did it for you

**Pull request merged**
