### PR TITLE
remove supply manifest

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
removes supply manifest paper from orders
## Why It's Good For The Game
useless since computer already logs purchases, and is clutter
## Changelog
:cl:
del: removed supply manifest from orders
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
Zased.....

**Comment by MereWalker** [comment]
Anti paper(please)/time dilation/document pouch pr.

**Review by TiviPlus — APPROVED** [review]

**Comment by ThelastArchiver** [comment]
noooo the cargo manifesto

**Comment by chizzy376** [comment]
Rip soul ☹

**Pull request merged**
