### PR TITLE
Adds death sounds to humans and robots

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Adds a death sound effect to humans, like sectoids and xenos.
Applies to humans and both kinds of vatborn.

https://user-images.githubusercontent.com/7869430/194202235-dc1d480e-36c6-4da6-bdeb-5475bd5117ce.mp4

Edit: now also includes death sounds for combat robots.

https://user-images.githubusercontent.com/7869430/194290215-b3141e01-bedb-46b5-8f58-3f3b9300514d.mp4

## Why It's Good For The Game
More sounds good, audio cues good.

## Changelog
:cl:
soundadd: Humans and combat robots now have death sounds
/:cl:

### CODE REVIEW

**Comment by tyeagg** [comment]
can you give them the half life combine death flatline sound thing

**Comment by Lumipharon** [comment]
> can you give them the half life combine death flatline sound thing

That would be cool. I wonder if I could set that up as a faction specific thing...

**Comment by DerpiestBruh** [comment]
> Copyright?

Using valve sfx is fine aslong as it's non commercial, IIRC.

**Comment by Starfirejordan** [comment]
taking though a radio sound meh

**Comment by helper-2** [comment]
The only reason for implementing death sounds is increasing "realism" when you kill somebody and those screams are to odd to do that

**Comment by lbnesquik** [comment]
I like the idea! Just not a fan of the sounds for the robots.

**Comment by Losenis** [comment]
These are jarring in contrast to say the least and don't really feel any different from a pain sound in terms of what it conveys.

**Comment by DerpiestBruh** [comment]
😭

**Pull request closed without merging**
