### PR TITLE
Xeno turret rebalance

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Xeno turret damage from 20 to 30, price from 150 to 100. Health went from 1500 to 800, health at start will be only 250 rather than 750, fire will do more damage in percentage of health, explosion damage will stay the same.
The turrets will no longer shoot marines that are unconcious

Takes 10 seconds to build rather than 15

## Why It's Good For The Game

Marines are now really good to counter turrets, and they became only minor inconvenience. This makes the turrets both more deadly (so xenos can use them more), but also easier to deal with alone. You will have more trouble to tank it, but shooting it will be twice as fast.

It also doesn't kill marines anymore, just burn them until unconcious. This allow the turrets to focus on other marines, while healing a down marines way easier

Xeno turrets took 15 seconds to build, because i wanted to make it impossible to build combat turret.
Since the health when spawning is now really weak, this is not longer such an issue, and we can lower the building time

## Changelog
:cl:
balance: Xeno turret damage from 20 to 30, price from 150 to 100. Health went from 1500 to 800, fire will do more damage in percentage of health, explosion damage will be more efficient.
balance: The turrets will no longer shoot unconcious marines, but will rather try to find another target
fix: Fix green arrow sprite
balance: The xeno turrets alert cooldown is upped, but it stays longer on screen (so less spam)
balance: It takes 10 seconds to build a turret rather than 15
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
now.... buff warrior.

**Comment by Losenis** [comment]
50% more damage with a buy 2 get one free price reduction? Turrets are absolute hell on earth when they're actually used with xenos to stunthrow marines into them, given they do pure burn damage which has 1.2 pain per point of damage compared to brute that only has 1. Of course they're gonna be an annoyance if left alone. If they're deadlier it'll just make shrikes and warriors camping by a turret that much more hellish to deal with, especially in spots grenades can't reliably get into like diagonal cave walls or mazes where you take so much time the entire hive drops in soon enough.

**Comment by Chaznoodles** [comment]
This is a buff, not a rebalance. 30 burn damage every 0.5 seconds that has no human miss error, and you now get more for less. Health is meaningless because the only way turrets ever die anyway is if someone sets them on fire and hides, or they die from offscreen. This is also still more health than fully matured walls.

"easier to deal with alone" doesn't stand on it's own two feet with the buffs noted above.

**Comment by BraveMole** [comment]
> This is a buff, not a rebalance. 30 burn damage every 0.5 seconds that has no human miss error, and you now get more for less. 

Have you ever played once against the turret? No human miss error? When you can literally shoot it while running it around without getting any damage?

> Health is meaningless because the only way turrets ever die anyway is if someone sets them on fire and hides, or they die from offscreen. This is also still more health than fully matured walls.

The only way turrets ever die? Wait you actually never played against them. 2 or 3 marines can shoot it to oblivion in 5 seconds top by concentrating fire. Halving the health make it way easier to shoot it, even at close range

**Comment by SilencedMP5A5** [comment]
time for the stun throw into two turrets meta

**Comment by Chaznoodles** [comment]
> > This is a buff, not a rebalance. 30 burn damage every 0.5 seconds that has no human miss error, and you now get more for less.
> 
> Have you ever played once against the turret? No human miss error? When you can literally shoot it while running it around without getting any damage?
> 
> > Health is meaningless because the only way turrets ever die anyway is if someone sets them on fire and hides, or they die from offscreen. This is also still more health than fully matured walls.
> 
> The only way turrets ever die? Wait you actually never played against them. 2 or 3 marines can shoot it to oblivion in 5 seconds top by concentrating fire. Halving the health make it way easier to shoot it, even at close range

Weird arguments that try and say I don't play instead of refuting the points, wacky

**Comment by Losenis** [comment]
> The only way turrets ever die? Wait you actually never played against them. 2 or 3 marines can shoot it to oblivion in 5 seconds top by concentrating fire. Halving the health make it way easier to shoot it, even at close range

Excuse me what? If xenos are bald enough to put them out in the open to get shot from so far out that the travel distance of the projectile is slower than the movement speed of the mob, it's either baldness or it had been mazed enough to delay marines clearing the entire mess up. Actual good turret placement in mazes in caves in very tight spaces that makes them start shooting without the human reaction time delaying it is pure hell on earth to work with because you get shot and pain already starts slowing you down, on top of the acid staying on the ground for bonus damage. And this is if the turrets are left alone, you already have shrikes and warriors throwing people into turrets and xenos stunning them for free damage, which this will buff since turret health isn't going to be something so important in that instance until you get rid of the xenos first to actually be able to sit down and hold click.

**Comment by ThelastArchiver** [comment]
lets be honest grenade spam counters turrets and no rebalance will ever change that this wil make grenade spam just more effective.

**Comment by BraveMole** [comment]
> > The only way turrets ever die? Wait you actually never played against them. 2 or 3 marines can shoot it to oblivion in 5 seconds top by concentrating fire. Halving the health make it way easier to shoot it, even at close range
> 
> Excuse me what? If xenos are bald enough to put them out in the open to get shot from so far out that the travel distance of the projectile is slower than the movement speed of the mob, it's either baldness or it had been mazed enough to delay marines clearing the entire mess up. Actual good turret placement in mazes in caves in very tight spaces that makes them start shooting without the human reaction time delaying it is pure hell on earth to work with because you get shot and pain already starts slowing you down, on top of the acid staying on the ground for bonus damage. And this is if the turrets are left alone, you already have shrikes and warriors throwing people into turrets and xenos stunning them for free damage, which this will buff since turret health isn't going to be something so important in that instance until you get rid of the xenos first to actually be able to sit down and hold click.

That was hardly nerf since i removed IFF from turrets. Frankly right now you have no issue to tank turrets

**Comment by Losenis** [comment]
I've had an easier time with IFF turrets since they wouldn't destroy their own walls when I found a good angle to shoot at a turret from behind a resin wall, now they're unintentionally smart enough to remove the wall allowing the marine to shoot with impunity.

**Comment by Chaznoodles** [comment]
image

undocumented change that lets you drop turrets at will go brr

**Comment by BraveMole** [comment]
> image
> 
> undocumented change that lets you drop turrets at will go brr

Eh, true, forgot that

**Comment by Losenis** [comment]
Yeah listen I don't think this pr got thought through well enough
image

**Comment by Chaznoodles** [comment]
> Yeah listen I don't think this pr got thought through well enough
> image

This was me, I retract everything, 100 point turrets that place in 5 seconds and cause 30 burn damage per shot is a perfect game design

There was someone in B18 in the CIC. Instead of fighting them, I just stood there placing turrets at lightspeed that tore right through their armour.

image

**Comment by Tupinambis** [comment]
Turrets are already pretty strong if used properly and this buffs them regardless of the health decrease. With how quickly a turret can melt through a marine a 50% damage increase would more than make up for any health loss.

**Review by SplinterGP — CHANGES_REQUESTED** [review]
make fire or grenades have special interaction with them rather than being literally, "i have this, turret no existoroni", stops things from being 8/80 with it and a excuse for them being strong because 1(2) things hard counter it, which in my opinion very hard counters with everything else is shit against, are bad game design

**Comment by Pariah919** [comment]
Turrets are not balanced with this PR, and arguably weren't before.

**Comment by Chaznoodles** [comment]
image

Making a bad thing less bad doesn't make it good. The previous points still stand.

**Comment by AyyRobotics** [comment]
So... Turrets that build faster, cost less, and do 33% more damage at the cost of around half health.
Just like the stuff mentioned above all I can imagine is insane turretspam. You can get 3 turrets dealing 90 Burn damage every 0.5 seconds for the same price here as you could with 2 turrets dealing 40 Burn damage every 0.5 seconds.

Turrets are strong, they're irritating, and they are in no way a minor inconvenience from what I've seen. Turrets stop pushes in their tracks, they're the ultimate backup for any xeno hold, and they're infuriating to deal with in the state they are now, which I will say is _probably_ balanced. This'll just make turrets something xenos don't think twice about spamming the hell out of and slow marine pushes to a crawl as they have to meticulously peek or blast or burn turrets repeatedly just to get through even an abandoned xeno hold. Not to mention how this would make SILOS 3x more difficult to deal with since turrets usually get put around them.

The only actual weakness here is being able to focus fire on separate turrets with less health which requires marines to focus on spreading out their fire, debatably possible, all the while being shot at with likely multiple turrets at different angles. And we can't forget that two of the turrets will have more overall health than a regular turret, costs only 50 more than one regular turret, and do triple the damage of one. All the while marines are PROBABLY also being attacked by xenos.

This is the utter definition of an insane buff. Defensively they'll become almost impossible to deal with if backed up by xenos in places CAS can't reach, and offensively they'll be difficult to push through, even if you hit them with a mortar or CAS since xenos can just place another one there.

**Comment by BraveMole** [comment]
> So... Turrets that build faster, cost less, and do 33% more damage at the cost of around half health.
> Just like the stuff mentioned above all I can imagine is insane turretspam. You can get 3 turrets dealing 90 Burn damage every 0.5 seconds for the same price here as you could with 2 turrets dealing 40 Burn damage every 0.5 seconds.
> 
> Turrets are strong, they're irritating, and they are in no way a minor inconvenience from what I've seen. Turrets stop pushes in their tracks, they're the ultimate backup for any xeno hold, and they're infuriating to deal with in the state they are now, which I will say is _probably_ balanced. This'll just make turrets something xenos don't think twice about spamming the hell out of and slow marine pushes to a crawl as they have to meticulously peek or blast or burn turrets repeatedly just to get through even an abandoned xeno hold. Not to mention how this would make SILOS 3x more difficult to deal with since turrets usually get put around them.
> 
> The only actual weakness here is being able to focus fire on separate turrets with less health which requires marines to focus on spreading out their fire, debatably possible, all the while being shot at with likely multiple turrets at different angles. And we can't forget that two of the turrets will have more overall health than a regular turret, costs only 50 more than one regular turret, and do triple the damage of one. All the while marines are PROBABLY also being attacked by xenos.
> 
> This is the utter definition of an insane buff. Defensively they'll become almost impossible to deal with if backed up by xenos in places CAS can't reach, and offensively they'll be difficult to push through, even if you hit them with a mortar or CAS since xenos can just place another one there.

This was PR'd with better stats, spammed one round and killed a bunch of marines that were ungaing.
Next round, marines were carefull, and they rekt all turrets on their way out.
The rounds after, turrets stopped being placed

**Review by SplinterGP — CHANGES_REQUESTED** [review]
i don't like the approach of turrets themselves, even more considering they're pretty strong in damage wise and with this, spammy, as with marine sentries once happened to be nerfed down due to fighting them being annoying, same happens on this, i'd rather we'd focus on player controlled or atleast managed to a extent stuff rather than like, having stuff that is a standstill structure that does damage and actually has barely any management or any involvent gameplay around it whatsoever, at this point AI xenos would be a better thing IMO, as they can also be used against FOB, things which turrets are probably barely able to and follows more into infinite stalemate pit

**Comment by AyyRobotics** [comment]
> > So... Turrets that build faster, cost less, and do 33% more damage at the cost of around half health.
> > Just like the stuff mentioned above all I can imagine is insane turretspam. You can get 3 turrets dealing 90 Burn damage every 0.5 seconds for the same price here as you could with 2 turrets dealing 40 Burn damage every 0.5 seconds.
> > Turrets are strong, they're irritating, and they are in no way a minor inconvenience from what I've seen. Turrets stop pushes in their tracks, they're the ultimate backup for any xeno hold, and they're infuriating to deal with in the state they are now, which I will say is _probably_ balanced. This'll just make turrets something xenos don't think twice about spamming the hell out of and slow marine pushes to a crawl as they have to meticulously peek or blast or burn turrets repeatedly just to get through even an abandoned xeno hold. Not to mention how this would make SILOS 3x more difficult to deal with since turrets usually get put around them.
> > The only actual weakness here is being able to focus fire on separate turrets with less health which requires marines to focus on spreading out their fire, debatably possible, all the while being shot at with likely multiple turrets at different angles. And we can't forget that two of the turrets will have more overall health than a regular turret, costs only 50 more than one regular turret, and do triple the damage of one. All the while marines are PROBABLY also being attacked by xenos.
> > This is the utter definition of an insane buff. Defensively they'll become almost impossible to deal with if backed up by xenos in places CAS can't reach, and offensively they'll be difficult to push through, even if you hit them with a mortar or CAS since xenos can just place another one there.
> 
> This was PR'd with better stats, spammed one round and killed a bunch of marines that were ungaing.
> Next round, marines were carefull, and they rekt all turrets on their way out.
> The rounds after, turrets stopped being placed

I think we both know that we can't consistently rely on marines being competent. If marines were constantly competent and didn't unga then balance would be thrown out the window.

> It's 12th the price of a silo, can be shot down faster than a wall at full health. You can kill them in three he, with an incend, with cas strike, with ob strike, with railgun, shoot it from afar.

CAS and OB's can be worked around by xenos, namely in caves. Building them around corners can pretty much negate shooting them from afar, and for everything else they're likely backed up by other xenos. And if it goes down they can just build another one. 12th the price still seems fairly cheap to me, considering how often I've seen them at their current price.

> If you don't have any of this tool, and you only have let's say a t12 (so a terrible gun to deal with it compared to a gpmg), you can kill it in 34 bullets.
> 
> That's less than a fucking mag, and you just took 100 points from the xeno. For the record, you need 48 bullets of that gun to kill a wall, but the wall is fucking free and built in one second.
>

I'm not denying that the turrets are weak, but they are most certainly spammable, and putting yourself in a position to actually shoot the damn thing is also risky. Assuming it's backed up, which they usually are, a grenadier would be at risk of getting tossed by the shrike or pounced or tossed by warriors, etc.

> All it does is burn damage, which you can heal up in one kelo and one tram pill. So litteraly something you will brush off in one minute
> 

???
That's like saying xenos can be brushed off because they only do brute damage that you can heal up with one bic and one tram pill. All damage can be repaired, what matters is how fast and how much is done. These turrets, ESPECIALLY if spammed will do a lot of damage very, very quickly. Not even to mention how more often than not marines will have burn damage before even facing a turret due to how many burn options xenos have already.

> "Turrets stop pushes in their tracks, they're the ultimate backup for any xeno hold"
> 
> Good. Xeno have still on this day ZERO way of stopping an unga ball;
> 

Boilers, Defilers, Queens, and to an extent Praetorians and Shrikes can stop a push, they just can't do it on their own. It's not JUST the turret, it's the turret WITH its backup that becomes the problem. A turret on its own is easily overrun, but not so much when there are multiple turrets and multiple xenos defending them. And of course we can't expect xenos to be consistently competent, but spamming gas down a chokepoint or hitting one button followed by a counterpush doesn't really need competence. I will agree that current turrets do aid in this when they're not available or good, but saying they have no options isn't very true from what I've seen myself.

> Everyday that passes on, xeno are capable to do less and less permanent damage to a marine. This count the lack of perma kill, but also the neuro that was hard nerfed, the arm health that was buffed, the pain slowing down marines less, the tweezers that removes the need of surgery for shrap, the GPMG and T42 buff that allowed ungas to never run out of ammunitation, the augmentation of mats for engineer, and so on and so on
> 

I'll concede on this, however being unable to deal permanent damage isn't uniquely a problem for xenos. I won't get into that though since that's off-topic.  Though I will say that the buffs do make sense. the arm health thing was mainly because hunters kept lobbing arms off easily and that just forced everyone to go back to the ship (same thing with huggers and you see how hard it is for carriers to get that done), tweezers only come with medics, and considering the low frequency of medics from what I've seen I wouldn't say it's a major problem. I _think_ Psydrain lowers the death timer, so that sort-of helps in that way, and doing that/cocooning just gives you more xenos even if the guy is revived. Nothing to say on the other points.

> All of this is making stopping a unga ball even harder than it was. Giving xeno a moment of rest, or even a slight fucking obstacle on the way of marines is just needed
> 

Exactly. Turrets are already that solution and in my opinion do a good job at it. They don't need something to make them stronger than they already are.

> Turrets were not balanced at all, cause xeno had absolutely no incentive to use them other than as early alerts. Every other turrets was a waste of points. This makes them useful in other ways.

Xenos have perfect incentive to use them. I've seen myself how much a turret can stall or even just completely negate a push when placed right. To my knowledge these weren't test-merge rounds. And how weren't they balanced? Of course on their own they're weak and can be overrun, assuming marines are okay with taking some burn damage to do it, but decent placement and moderate amounts of teamwork can make turrets a pain to deal with as xenos can repeatedly run in and out of a fight with marines being punished for chasing.

Or hell maybe all the more recent times I've been in test-merge rounds and I'm arguing in favor of yours, I don't really know, but that would be funny.

**Comment by AyyRobotics** [comment]
>AI Xenos
I like that actually. Assuming we don't pull a Whiskey Outpost and have hordes of ravagers charging the FOB I could see it being balanced enough.

**Pull request closed without merging**
