### PR TITLE
ERT Shuttles Have Plasteel Cades By Their Doors

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Adds opened plasteel cades to the entrances to the ERT shuttles
Change Me - Debugdalus 2_21_2024 4_51_43 PM
## Why It's Good For The Game
Currently, if ERT shows up in the middle of a hijack after the xenos land, they are immediately swarmed by the xenos and killed, unless the ERT is ridiculously strong like PMC. This helps to at least give ERT a little bit of time and breathing room before being ganked to death. Note I also did this for the alien ERT ship, though not sure if it clashes with the ERT's theme.
## Changelog
:cl:
balance: ERT ships will now have plasteel cades protecting their doors.
code: Added a plasteel child that spawns in closed
/:cl:

### CODE REVIEW

**Comment by Wisemonster** [comment]
Note, I didn't add cades to the big ERT ship cause I didn't think it appears in normal gameplay, and the thing is effectively a smaller FOB as is.

**Comment by Wisemonster** [comment]
Second Note, none of the cades have razorwire on them.

**Comment by yyzsong** [comment]
ERTs dont deserve anything

**Comment by lbnesquik** [comment]
Honestly this seems like a good idea, because ERT's tend to either die instantly or get enough time / have enough bodies to win either way.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
No varediting density or closed state on the barricades. If you really need it I'll make you a map helper.

**Comment by Wisemonster** [comment]
I could simply make a child that is already open.

**Comment by Wisemonster** [comment]
Alright, gonna wait till the map helper pr is merged, then use those in the maps.

**Comment by Wisemonster** [comment]
Alright, it's using closed helpers now

**Pull request merged**
