### PR TITLE
Floodlight Rework

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
combat floodlights are now deployable and has a normal weight class
combat floodlights no longer need cells and last forever
5 free at round start 2 points in engi vendor
## Why It's Good For The Game
combat floodlights at its current state is unusable, they are hard to transport and you have to baby sit them because they run out of cell power fast.
## Changelog
:cl:
add: deployable floodlight
balance: combat floodlights are now deployables
balance: combat floodlights now last forever not needing cells
imageadd: deployable floodlight item sprite
/:cl:

### CODE REVIEW

**Comment by bowlofcereal** [comment]
> ive been seeing allot of flare spam

isn't that the whole point of flares is to be used as a mass produced light source

> xenos cant really do too much against them if spammed

image

**Comment by ivanmixo** [comment]
image

lol

**Comment by zuneshine** [comment]
god's least unatomic PR

**Comment by Strayed-Raven** [comment]
I want the drugs you got. To think we gave up Imagers for this timeline

**Comment by Derrick2Electricboogaloo** [comment]
When one see a problem that is not even a problem, put the words: "spam" and it somehow becomes valid.

**Comment by Losenis** [comment]
>Coders: Remove imagers
>Marines: Spam flares
>Coders:

image

**Comment by Aporhtonoma** [comment]
im gonna upvote this for diversity and because someone told me not to

**Comment by BlueHNT** [comment]
This sounds funny, let's have this added. To begin with, having these around for more than 10 minutes when they are "mass-produced" sounds stupid. 

Each marine can carry a package with, or without sacrificing a pouch and the slotting is easy more often than you come up to an area that the marines went through several minutes ago and all those flares are still everywhere scattered and lit.

Being able to see is a huge merit and demerit so it's up to the balancers in the end, but it could be a good change.

**Comment by Al-1ce** [comment]
Flares suck but they're a necessary evil. 

Floodlights are meme items and worthless.

-1

**Comment by ForeverNumbered** [comment]
You can still spam your flares all you want, you just can't keep . This is a great change, 16 minutes is ridiculous

**Comment by blackdav123** [comment]
why are flares needed to be involved in this change? if floodlights are now a nigh permanent light source then people will use those regardless of how good or bad flares are. these things are not competing for usage.

**Comment by Araulius** [comment]
mf's would rather nerf flare than buff acid melt speed

**Comment by tyeagg** [comment]
> image
> 
> lol

isajoke

**Comment by tyeagg** [comment]
> Flares suck but they're a necessary evil. 
> 
> Floodlights are meme items and worthless.
> 
> -1

they were meme items and worthless

**Comment by tyeagg** [comment]
> why are flares needed to be involved in this change? if floodlights are now a nigh permanent light source then people will use those regardless of how good or bad flares are. these things are not competing for usage.

it compensates for eachother  flare nerf marines now need a better lighting option but one thats not too spammable so deployable floodlights are that

**Comment by Losenis** [comment]
Atomize so that the flare nerf can be closed and floodlight rework merged

**Comment by tyeagg** [comment]
> why are flares needed to be involved in this change? if floodlights are now a nigh permanent light source then people will use those regardless of how good or bad flares are. these things are not competing for usage.

Whats the point of using floodlights if you can just get 14 flares in a pack or allot in a flare pouch which can last for 16 minutes and once their out of action its easily replaceable

**Comment by blackdav123** [comment]
> > why are flares needed to be involved in this change? if floodlights are now a nigh permanent light source then people will use those regardless of how good or bad flares are. these things are not competing for usage.
> 
> Whats the point of using floodlights if you can just get 14 flares in a pack or allot in a flare pouch which can last for 16 minutes and once their out of action its easily replaceable

floodlights have massive range and no blindspots and are therefore great for putting at disks and other bases while flares are better for the spaces inbetween where you dont need 100% coverage

if the floodlight buff is merged without the flare nerf you'll still see both being used

**Comment by tyeagg** [comment]
> > > why are flares needed to be involved in this change? if floodlights are now a nigh permanent light source then people will use those regardless of how good or bad flares are. these things are not competing for usage.
> > 
> > Whats the point of using floodlights if you can just get 14 flares in a pack or allot in a flare pouch which can last for 16 minutes and once their out of action its easily replaceable
> 
> floodlights have massive range and no blindspots and are therefore great for putting at disks and other bases while flares are better for the spaces inbetween where you dont need 100% coverage
> 
> if the floodlight buff is merged without the flare nerf you'll still see both being used

yea but the whole point of this pr is to reduce effectiveness of flares since you can easily spam with the storage space and have a long lasting light, the floodlight buff is just to compensate for the loss of long lasting area lighting

**Comment by Losenis** [comment]
>since you can easily spam with the storage space

You are aware that was the intended state given the amount of flares in the vendors and how there's an actual crate of flares marines bring down, right? You know that the only thing that stopped marines from filling a backpack with flares and throwing it along the way back in the day was pure laziness and bystander effect rather than space limits, right?

If anything flares already got nerfed by the ability of xenos to move them around, so of course you're going to see them spammed en masse when the times they're thrown once or twice they're quickly moved out of the way even by castes that can't acid them. Textbook causation =/= correlation.

**Comment by tyeagg** [comment]
> > since you can easily spam with the storage space
> 
> You are aware that was the intended state given the amount of flares in the vendors and how there's an actual crate of flares marines bring down, right? You know that the only thing that stopped marines from filling a backpack with flares and throwing it along the way back in the day was pure laziness and bystander effect rather than space limits, right?
> 
> If anything flares already got nerfed by the ability of xenos to move them around, so of course you're going to see them spammed en masse when the times they're thrown once or twice they're quickly moved out of the way even by castes that can't acid them. Textbook causation =/= correlation.
> 
> I'd sooner suggest lowering the acid cost on flares in specific because as boiler it's an actual pain in the ass to melt 3 and have to rest like I didn't just spit at a glowing stick instead of aciding down an entire wall. They're already acided faster, I'm sure there's a way to code in a plasma multiplier in there somewhere.

is it a good state no and explain how you start seeing flares actually being used post storage space buff before you couldnt really carry much flares so it wasnt really useful to bring in a loadout when you can just bring other stuff instead of a small flare pack or a small amount of flares in a flare pouch post storage buff you actually have a good amount

**Comment by Losenis** [comment]
>is it a good state no

That's just, like, your opinion, man.

>explain how you start seeing flares actually being used post storage space buff

Because suddenly it's viable to skip a pouch slot that'd carry more pill bottles, or more mags, etc for simply flares rather than a pisspoor amount of them that'd actually fit a webbing slot due to the flare box counting as a small item. I'd sooner return the question back at you and ask you why you think people started going flare pouch when it also existed back then and nobody grabbed it. This line of thinking of yours will lock you into thinking that anything that is made viable is too powerful and needs to get nerfed down to being skipped by 99% of the server due to it not being worth it.

And nothing stopped people from shoving 12 flare packs into a backpack to throw around and then drop the backpack once it's over -- Nothing other than not being arsed to do it. What you see now of "spam" is maybe like 10 or so marines carrying flares and throwing them rather than in the past where maybe 1 or 2 carried them en masse to cover for the entire team of 50+.

You wanna know real spam? Count the flaresin one flare pouch, then in 4 flare packs in webbing slot, then maybe add 4 more packs in backpack, and then multiply that for every single marine in the server. I can guarantee you the current amount you see right now doesn't even reach a tenth of that number.

Again, make aciding flares be cheaper in plasma cost. It's that easy. Let xenos actually be able to handle it rather than trying to nerf it to the point you don't have to face it ingame.

**Comment by tyeagg** [comment]
> > is it a good state no
> 
> That's just, like, your opinion, man.
> 
> > explain how you start seeing flares actually being used post storage space buff
> 
> Because suddenly it's viable to skip a pouch slot that'd carry more pill bottles, or more mags, etc for simply flares rather than a pisspoor amount of them that'd actually fit a webbing slot due to the flare box counting as a small item. I'd sooner return the question back at you and ask you why you think people started going flare pouch when it also existed back then and nobody grabbed it. This line of thinking of yours will lock you into thinking that anything that is made viable is too powerful and needs to get nerfed down to being skipped by 99% of the server due to it not being worth it.
> 
> And nothing stopped people from shoving 12 flare packs into a backpack back in the day to throw around and then drop the backpack once it's over -- Nothing other than not being arsed to do it. What you see now of "spam" is maybe like 10 or so marines carrying actually carrying a sensible amount flares and throwing them rather than in the past where maybe 1 or 2 carried them en masse in backpacks to cover for the entire team of 50+.
> 
> You wanna know real spam? Count the flaresin one flare pouch, then in 4 flare packs in webbing slot, then maybe add 4 more packs in backpack, and then multiply that for every single marine in the server. I can guarantee you the current amount you see right now doesn't even reach a tenth of that number.
> 
> Again, make aciding flares be cheaper in plasma cost. It's that easy. Let xenos actually be able to handle it rather than trying to nerf it to the point you don't have to face it ingame.

nerfing flares to 5 minutes will still make flares worth it it still has a large quantity and it still provides good illumination you just need to restock it more and your forgetting requisitions exists which allows for easy restocking of flares

**Comment by Losenis** [comment]
Or just make it cheaper to acid them

SERIOUSLY I JUST HAD A BOILER ROUND AND IM COPING RN MAKE IT CHEAPER TO ACID JFC I DONT CARE IF THEY LAST 5 MINUTES IF I TAKE 30 MINUTES TO ACID JUST 10 OF THEM INBETWEEN ALL THE RESTING AAAAAAAAAAAAAAAA

**Comment by tyeagg** [comment]
> Or just make it cheaper to acid them
> 
> SERIOUSLY I JUST HAD A BOILER ROUND AND IM COPING RN MAKE IT CHEAPER TO ACID JFC I DONT CARE IF THEY LAST 5 MINUTES IF I TAKE 30 MINUTES TO ACID JUST 10 OF THEM INBETWEEN ALL THE RESTING AAAAAAAAAAAAAAAA

Buffing acid against flares could be a potential solution to make it easier and more effective to melt them. This would involve increasing the effectiveness of acid against flares so that it takes less time and resources to melt them.

However, it's important to carefully consider the potential impact of this change on the overall gameplay and balance of the game. For example, if acid becomes too effective against flares, it could potentially make them obsolete and decrease their usefulness in certain situations. This could have unintended consequences on gameplay and balance, and may require additional adjustments to other game mechanics.

In general, any changes to game mechanics should be made with careful consideration and testing to ensure that they align with the overall vision and goals for the game, and that they don't negatively impact other aspects of gameplay or balance. Additionally, it's important to communicate any proposed changes with the community and gather feedback before implementing them to ensure that everyone is on the same page and that the changes are well-received.

**Comment by Losenis** [comment]
>suddenly capitalized and punctuated

My brother in Ra you can stop using AI, I'm watching your shitposts with gpt in discord already

**Comment by Al-1ce** [comment]
> In general, any changes to game mechanics should be made with careful consideration and testing to ensure that they align with the overall vision and goals for the game, and that they don't negatively impact other aspects of gameplay or balance. Additionally, it's important to communicate any proposed changes with the community and gather feedback before implementing them to ensure that everyone is on the same page and that the changes are well-received.

actually using chatgtp
I raise you,
-2
fuck this PR

**Comment by Oscari-pog** [comment]
Based chatgpt user
Cope
+20

**Comment by zuneshine** [comment]
If you're going to be so deathly unserious to the extent of unironically using chatGPT to respond to criticism and feedback I don't think you should be submitting PRs to this repo out of principle.

**Comment by FosterGrime-Heymynameslouie** [comment]
kinda absurd how flares light up till 16 minutes now that you mention its exact run time, honestly felt like it shouldve be like 10 or something, six is kinda hmmmmmmmmmmmmmmmmmmm

also based flooglith change 10/10

**Comment by tyeagg** [comment]
> If you're going to be so deathly unserious to the extent of unironically using chatGPT to respond to criticism and feedback I don't think you should be submitting PRs to this repo out of principle.

I apologize if my use of ChatGPT has caused any frustration or discomfort. I understand that it's important to work collaboratively and respectfully with other contributors to reach a consensus on the best course of action for the project. I would be happy to engage in open and constructive discussion with you and other team members to find a solution that works for everyone. Please let me know if there's anything specific you would like to discuss or address.

**Comment by Jalopkomit18** [comment]
I was wondering when someone would use chatgpt to make arguments for their pr. It's perfect for this.

**Comment by bowlofcereal** [comment]
> > If you're going to be so deathly unserious to the extent of unironically using chatGPT to respond to criticism and feedback I don't think you should be submitting PRs to this repo out of principle.
> 
> I apologize if my use of ChatGPT has caused any frustration or discomfort. I understand that it's important to work collaboratively and respectfully with other contributors to reach a consensus on the best course of action for the project. I would be happy to engage in open and constructive discussion with you and other team members to find a solution that works for everyone. Please let me know if there's anything specific you would like to discuss or address.

Are you for real.

**Comment by BlueHNT** [comment]
I mean, it's a simple way to have your criticism have weight. It's there and you can use it. Now you should fight back with chatgpt too

**Comment by TiviPlus** [comment]
no flare nerf

**Comment by Al-1ce** [comment]
1984

**Comment by tyeagg** [comment]
> Member

ok hopefully that acid flare nerf will solve it

**Comment by Dickff** [comment]
I would just open a new PR for floodlight rework, this one has been downvoted to hell and the comments are a mess.

**Comment by FosterGrime-Heymynameslouie** [comment]
10/10 pr actually made floodligts useful after 2 billiong years

**Comment by Lumipharon** [comment]
this is conflicting with others tm'd forever, was there really anything that actually still needed to be tested with this though?

**Review by Kuro020 — APPROVED** [review]

**Review by QualityVan — COMMENTED** [review]
I'm not sold on cutting the cell entirely rather than just reducing the charge rate, but also I'm late on it and that can be changed in the future anyway. 400 also seems like a lot of integrity for a folding lamp pole.

**Pull request merged**
