### PR TITLE
Heads can always reattach

### LINKED ISSUE #11732: Decap synth is stuck unable to leave body
### Description

Apparently getting decapped lets you still talk and you're stuck as the head. Unfortunately this is literally worse than dying because now you're now stuck forever unable to obs or anything at all without even radio unless you ghost, which DNRs you regardless of having no defib timer.

### Test Merges

[#11637: 'Adds TGUI Say aka. new chatbox for text' by SplinterGP at commit d22e060a09](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11637)
[#11697: 'Sentinel Redesigned' by lKiseki at commit 8e0268c78b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/11697)

### Reproduction Steps

Step 1 die

### Screenshots

image

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
Removes the restrictions from non-robots. Everything just got decap immunity slapped on anyway, so whatever.
You can only reattach a head to the body it came from, so no bypassing going cold with this.
Synths and robots will stay 'alive' in the head after it gets removed, able to talk and not do much else. They can ghost out and return later, but it'll kill them (preventing non-dead chat) so you can't be a spooky scouting skull.
## Why It's Good For The Game
Fixes #11732 
## Changelog
:cl:
balance: Humans can have their heads stuck back on and revived, long as you have the right body
fix: Synths are no longer stuck in a living purgatory when they lose their head, unable to truly die
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
I think if you get decapped, even when "Everything just got decap immunity slapped on anyway, so whatever." you probably deserved to get decapped 

but the part where synths and droids still being technically alive and being able to talk in head form is insanely funny please keep that

spededmehgr instantly

**Comment by Xander3359** [comment]
If a doctor is robust enough to recover your head, and your dead body in under 5 minutes, they should be able to re-attach the head and defib.

**Comment by Naaanii** [comment]
Next we add heads to the printer but keep them bald so its a perma debuff in terms of appearance.

**Comment by Lumipharon** [comment]
Why though? If you wanna go drip with a headband or whatever, then deal with the decap. On the same token I think adding decap protection to a bunch of snowflake stuff was dumb to begin with, but eh.

**Comment by Losenis** [comment]
>is insanely funny please keep that

It'll stop being funny when it happens to you and your options are alt-tabbing for an indefinite amount of time for no guarantee of actually getting someone who knows to also drag your head or ghosting into a DNR due to having literally no way to see anything in the round, as your radio also gets unequipped.

On that matter, is the decapped head xenodrag-immune?

**Comment by Derrick2Electricboogaloo** [comment]
Nice. This is a good one! Yes from me!

**Comment by QualityVan** [comment]
> Why though? If you wanna go drip with a headband or whatever, then deal with the decap.
#9657
With this pr you'd still get decapped without protection, die instantly, and need someone to recover both your body and head and fix it all within the time limit. That seems like a decent amount of 'dealing with'.

**Comment by Shootnik01** [comment]
Wow, another clown PR about decapitation. We can repeat once again about punishing marines, who doesn't wear armor (helmet here), but I just ask the maintainers to close this.

At least about re-attaching human heads, bobot part sounds funny.

**Comment by FIXTHERADBOXPLEASE** [comment]
What's with all the marine salt PRs about dying/being damaged recently?

**Comment by Luxyboo** [comment]
> What's with all the marine salt PRs about dying/being damaged recently?
37% Winrate

**Comment by FosterGrime-Heymynameslouie** [comment]
> > is insanely funny please keep that
> 
> It'll stop being funny when it happens to you and your options are alt-tabbing for an indefinite amount of time for no guarantee of actually getting someone who knows to also drag your head or ghosting into a DNR due to having literally no way to see anything in the round, as your radio also gets unequipped.
> 
> On that matter, is the decapped head xenodrag-immune?

"They can ghost out and return later, but it'll kill them (preventing non-dead chat) so you can't be a spooky scouting skull"

did you not read litetslly the paragraph below that

**Comment by novaepee** [comment]
if this gets merged, xenos will drag marine head and melt it lel

**Comment by Derrick2Electricboogaloo** [comment]
> if this gets merged, xenos will drag marine head and melt it lel

Shocking they do not already for synths dumb enough to not use helmets.

**Comment by Losenis** [comment]
I mean if a synth is dumb enough to not use a helmet, it's not like it was doing anything of value while alive to stop a revive

**Comment by chizzy376** [comment]
> I mean if a synth is dumb enough to not use a helmet, it's not like it was doing anything of value while alive to stop a revive

You misunderstand. This will make me purposefully NOT wear a helmet so I can chat with the hive after my death.

**Pull request closed without merging**
