### PR TITLE
[DO NOT TM/MERGE UNTIL AIM MODE] Removes marine squad smartgunners from the game

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Sends smartgunners to the shadowrealm. Lets anyone use the smartmachinegun, it is now a req only weapon, which I personally believe is fair.

TODO 
Decide on req cost balance, probably. I think 40 points is fair but it might be TOO fair.

## Why It's Good For The Game
Smartgunner fails at what it tries to do, or reduce marine friendly fire, #5242 is a much fairer balance viewpoint PR. In return for aim mode smartgunners are gone. Sent to the shadowrealm as they should've been ages ago.

## Changelog
:cl:
del: Removed smartgunners, nobody will remember them but those with 200 hours in them. Praise aim mode.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SilencedMP5A5** [comment]
40 points for a smartgun is fair imo considering the cost of feeding them and their questionable effectiveness used by the typical unga

**Comment by Jeff-jefferson-jeffery** [comment]
speedmerge this

**Comment by Kindadread** [comment]
What

**Comment by MLGTASTICa** [comment]
Smartgunners do not fail at what they are supposed to do . A competent smartguner will do their job extremly effective , preventing xenos from rushing at all.

**Comment by Kesserline** [comment]
I would agree, but Req would need to start with a couple of these in the cargonia vendors.

Otherwise, that would be removing SGs from roundstart, and probably for the game. Marines don't always have req.

**Comment by Pariah919** [comment]
> would agree, but Req would need to start with a couple of these in the cargonia vendors.

Otherwise, that would be removing SGs from roundstart, and probably for the game. Marines don't always have req.
> 
that's the entire point.

**Comment by MLGTASTICa** [comment]
> > would agree, but Req would need to start with a couple of these in the cargonia vendors.
> 
> > Otherwise, that would be removing SGs from roundstart, and probably for the game. Marines don't always have req.
> 
> that's the entire point.
> you're not getting smartguns for free, if I do that its either in a future pr or once i spilt the req and special gear vendors again

Why should we keep removing round-start roles ? requisitions as it is is not used that frequently to get guns , and 40 points seems extremly overpriced if all guns would have IFF by being in aim mode.

**Comment by Walarks** [comment]
> > > would agree, but Req would need to start with a couple of these in the cargonia vendors.
> > 
> > 
> > > Otherwise, that would be removing SGs from roundstart, and probably for the game. Marines don't always have req.
> > 
> > 
> > that's the entire point.
> > you're not getting smartguns for free, if I do that its either in a future pr or once i spilt the req and special gear vendors again
> 
> Why should we keep removing round-start roles ? requisitions as it is is not used that frequently to get guns , and 40 points seems extremly overpriced if all guns would have IFF by being in aim mode.

I think that smartguns are ok to be in requisitions since if aim mode happens, it is not supposed to make every gun nearly as strong as smartguns when IFF is active. This way marines will also have another noticeable upgrade option through points.

**Comment by Pariah919** [comment]
Aim mode has tmc.
It begins.

**Comment by Pariah919** [comment]
Aim mode has tmc.
It begins.

**Comment by Drevenshek** [comment]
aim mode more like cadehug mode can we please rework it before we start getting rid of smartgunners

**Comment by Pariah919** [comment]
>This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself
>
nice

**Comment by TiviPlus** [comment]
I see no reason to go through with this change

**Pull request closed without merging**
