### PR TITLE
Rest of the resin

### PR DESCRIPTION
**Pull request by Arachnidnexus**
:cl: Arachnidnexus
imageadd: replacing resin walls, doors, and window overlays
/:cl:

Done:
- resin walls
- thick resin walls
- unused resin membranes
- resin doors
~~ui icons in actions.dmi~~
- weed overlays for windows

Removing more CM stuff per request.

### CODE REVIEW

**Comment by Arachnidnexus** [comment]
No idea what Map Diff Renders is all about.

**Comment by Arachnidnexus** [comment]
Gonna fix the UI in another PR I guess because I have no idea why Map Diff Renders tells me there are map issues when I edit actions.dmi.

**Comment by Alterist** [comment]
Everything seems good here

**Comment by Alterist** [comment]
Everything checks out here

**Pull request merged**
