### PR TITLE
Some Pillar things.

### PR DESCRIPTION
**Pull request by grinkgo**
## About The Pull Request

1. The Pillar needed some holopads. And an extra camera in the hangar.
2. Finally added a tool closet southeast of req.

## Why It's Good For The Game

1. We have working AI and working holopads. Let's use em.
2. With access to tools marines are (hopefully) less likely to use brute force to get into req.

## Changelog
:cl:
add: Several more holopads around the Pillar of Spring
add: Finally added a tool closet outside of requisitions. You're welcome, David.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by grinkgo** [comment]
> You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Hello, old friend. It's nice to see you again.

**Comment by Rohesie** [comment]
Needs mapmerge.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-4). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
