### PR TITLE
Pillar of Spring's Remapping: Changing Req, PO, Hanger, and Medical, then adding bar and memorial

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

PoS's req has been expanded to fit in reqtorio.

Hanger changed for QoL and in light of req's expansion

image

Add memorial

image

PoS's PO bunks have been changed to let req expand.

Remove props.

PoS's medbay has been changed to make room for a BAR.

Add in bar in PoS.

image
Bar and medbay

Hanger, PO's bunk, and req
image

## Why It's Good For The Game

Two fundamental take away:

1) Req needs room ~~TO GROW THE FACTORY~~ for reqtorio. It demands a radical change to starboard side of the ship, especially for PO. The dedicated room for Alamo console is dead. At least PO has a bigger room. Due to req, hanger needs changing.

2) Bar is added for RP and a place to rest after deployment. Since the lounge area near req is detached from req due to my previous remapping, I decide to put R&R near medbay and Alamo. Medbay has to change to make room for bar. Since bar is added for a place to rest, the prep area's mess hall has been replaced with a memorial.

## Changelog
:cl:
add: PoS's req has been expanded to fit in reqtorio.
add: PoS's hanger has been changed in light of this
add: PoS's PO bunks have been changed to let req expand.
del: Remove PoS's gun props.
add: PoS's medbay has been changed to make room for a BAR.
add: Add in bar in PoS.
add: PoS's memorial
/:cl:

### CODE REVIEW

**Comment by RipGrayson** [comment]
Just a heads up, there seems to be some space tiles in the new PO bunks, rest looks solid.
tile3

**Comment by novaepee** [comment]
**AAAAAAAAAA**

**Comment by MrHorizons** [comment]
I think it'd be better to just have the bar and medbay's walls overlap than the weird double-wall there currently is. More room that way, too.

Speaking of double-walls, the PO room _definitely_ doesn't need it down there.

**Comment by Arctrooper8** [comment]
Add a second cryo tube so it matches most of the other ship medbays.

**Comment by RipGrayson** [comment]
These two AI nodes are completely disconnected, only adjacent AI nodes connect
tile4

Please don't put nodes in solid objects, it confuses the AI.
tile5

Stacked AI nodes shouldn't be a thing, please move one of them to the left or right so they connect diagonally instead. 
tile6
tile9
tile10

Why is the middle node needed in these cases? AI nodes connect at distances of 15 or less, and there's certainly less than 15 squares between the two nodes here.
tile7
tile8

**Comment by novaepee** [comment]
> Why is the middle node needed in these cases? AI nodes connect at distances of 15 or less, and there's certainly less than 15 squares between the two nodes here. tile8

image

For the landing zone, this is the path.

**Comment by RipGrayson** [comment]
The circled nodes are useless, please remove them
nod14
nod13
nod15

The rest looks fine

**Review by RipGrayson — APPROVED** [review]
Yeah this looks good, I don't see anymore problems here

**Pull request merged**
