### PR TITLE
Long and spread nozzle are gone from acquisition.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
See title. They're still in valhalla/hvh
## Why It's Good For The Game
This was literally pure flamer powercreep the day it was introduced, I have no idea why it took so long for anyone including me to decide to nuke this from orbit.
## Changelog
:cl:
del: You can no loner acquire long or wide nozzle in HvX.
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
image

**Comment by Tonklaatech** [comment]
If this PR were to be merged the spray will never see the light of day. As for 100 points more one can buy a x fuel back tank which Is far more effective and versatile

**Comment by Oscari-pog** [comment]
I fucking despise the spray nozzle but 500 is a insane amount

**Comment by TellyLsc** [comment]
Ah yes spray nozzle, the nozzle that uses literally 20-25 fuel per shot because it flames tiles you don't need to burn (non resin node weeds) on top of having half intensity flames.

**Comment by srxtreme** [comment]
500 points spray nozzle MJP what are you doing

**Comment by Woker2004** [comment]
Alright, the spray nozzle gets countered by Rav, ranged caste, and generally any xeno not afraid of a little damage, this is not power creep as you actually have to be close to the damn target to spray

**Comment by SimplySmiley123** [comment]
> The people who hate the spray nuzzle don't use it, it's actually pretty bad. The extended nuzzle is cracked, though. Flamers needing to be vulnerable and get close to walls to remove them is good. If anything, the extended nuzzle should be req.

at the same time extended means you're fucked if quick area denial is needed

this PR sucks either way but extended nozzle is fine the way it is as well

**Comment by SzkieletorNutric** [comment]
lmfao how is that remotely powercreep when each of the nozzles have their own defined drawbacks and strengths MJP please I always thought better of you :skull:

**Comment by Woker2004** [comment]
> lmfao how is that remotely powercreep when each of the nozzles have their own defined drawbacks and strengths MJP please I always thought better of you 💀

He play basically 10 hour at most a week, rest on warthunder

But now onto the actual topic on hand, most framers will grab all modules to switch them out on the go, which is reasonable, also the sprayer has generally weaker damage due to having to flame multiple times in the same spot tp get it to full strength

**Comment by ivanmixo** [comment]
Id keep to just deleting extendo attachie if you want a shot at this going through. Do ask kurt tho

**Comment by Pariah919** [comment]
> Id keep to just deleting extendo attachie if you want a shot at this going through. Do ask kurt tho

What shot? Me and him already discussed this. And we'll spread is being nuked too.

**Comment by DaTruRiZZoB** [comment]
so what's the actual reasoning behind the removal, because just saying "powercreep" doesn't exactly explain much. why is it powercreep?

**Comment by SimplySmiley123** [comment]
> so what's the actual reasoning behind the removal, because just saying "powercreep" doesn't exactly explain much. why is it powercreep?

To be honest no damn idea considering the spray nozzle is a straight up downgrade to the default nozzle flamers get. While extended is more of a sidegrade to default then anything (you get more ammo efficiency at high precision for clearing walls in SECURED areas but during pushes it's a pain in the ass without penetration on top of being even worse at dealing with xenos).
You do get better area coverage which, doesn't matter for anything a flamer is good at. And for that you trade higher fuel cost for each shot and lower damage to xenos unless you waste even more fuel to fire a second time at the same spot, on top of wasting a lot of fuel for the main purpose of clearing walls.
The only time it's even remotely good is with xfuel which is costly on it's own on top of, again, high fuel usage from the spray nozzle meaning you gotta hog req for it if you use it more then once in a blue moon.

**Comment by aarrisu** [comment]
:(

**Comment by breadhunt** [comment]
opportunity cost my ass, they're literally attachments, can't you swap between them in like 2 seconds?

**Comment by QualityVan** [comment]
I don't like this. Nozzles add some variation to flamers that otherwise doesn't exist since there's only the one main gun. If the one bonus range on extended is so overwhelming, just remove that and see how it stands.

**Comment by ivanmixo** [comment]
The point is flamer should have to get close or suffer some bad fuel inefficiency, extendo lets you avoid both

**Comment by TellyLsc** [comment]
> The point is flamer should have to get close or suffer some bad fuel inefficiency, extendo lets you avoid both

Oh sure, let's nerf marines by making them more reliant on supplies because every round relying on the RO actually being decent is very fun for both the RO and the marine players.

**Comment by TellyLsc** [comment]
> opportunity cost my ass, they're literally attachments, can't you swap between them in like 2 seconds? it's not a sidegrade when the sidegrade is a small item that can be fitted/unfitted whenever to give you all the benefits whenever you want them

A flamer marine usually can only carry like what? 30 free weight (after medical items+flamer tank satchel/backtank assuming no second gun) Carrying two nozzles reduces that by 4, if you carry a a second weapon then you only have like 12 free weight after that, and if you want to carry utility items like binos, tac sensor, miniextinguisher for self extinguish, MRE, crowbar, then that's it, you can't strap more stuff.

**Comment by Kuro020** [comment]
bye bye

**Pull request merged**
