### PR TITLE
Adds a new Tadpole for the Drop ship Picker, Introducing Umbilical

### PR DESCRIPTION
**Pull request by chizzy376**
## About The Pull Request
Adds a new tadpole shuttle with its own useful niches.
### UPDATED TO NO LONGER RESEMBLE THE AMOGUS SHAPE. May you rest in peace suspole.
_umbilical

## Why It's Good For The Game
Giving Pilot Officers more options while making use of modularized tadpole code.
## Changelog
:cl:
add: Added a new tadpole, Umbilical.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
the
the tadpole with the built in chokepoint

**Comment by chizzy376** [comment]
> the the tadpole with the built in chokepoint
> 
> edit: any reason why this is like this btw? image

It's so the only entrance to the tad isn't exclusively from a far out side

**Comment by FosterGrime-Heymynameslouie** [comment]
> > edit: any reason why this is like this btw?
> 
> It's so the only entrance to the tad isn't exclusively from a far out side
> 
> I can change it if enough people complain

oh no not a complaint, I just found it very strange, das a good reason for them to exists although I do reccomend removing the inner walls and door next to the plasteel cade because 1x1 spaces is generally not approved off (atleast thats what I remember from gregor and their stance on 1x1 spaces)

image


personally would make it so that the only entrance and exit is the 2 plasteel cade line opening because it would be highyl funny

cool pr spedemgh

**Comment by chizzy376** [comment]
> personally would make it so that the only entrance and exit is the 2 plasteel cade line opening because it would be highyl funny


What if 
what if

**Comment by chizzy376** [comment]
> personally would make it so that the only entrance and exit is the 2 plasteel cade line opening because it would be highyl funny

What if
what if

**Review by RipGrayson — APPROVED** [review]
Very suspicious asymmetry here

**Review by RipGrayson — APPROVED** [review]
New design approved

**Comment by mc-oofert** [comment]
i think the design 2 was fine and kinda better if you consider TGMC at its core is a silly spessman TDM game where we pose as "MRP" while jetstream samuel and astolfo with thighhigh juggle DBs and shred the queen before being killed by FF so i dont see why silly designs arent good

**Comment by FosterGrime-Heymynameslouie** [comment]
new design looks fantastic I love you sus looking tadpole sspedmerhg instantly

**Comment by mc-oofert** [comment]
> now what i think would make it better is to lose the 3 wide and make it 2

actual nerd please go touch grass

**Comment by iforgotmeword** [comment]
Untitled

**Comment by mc-oofert** [comment]
> Untitled

looks bad

**Comment by iforgotmeword** [comment]
mean yea i used paint im just trying to show you what i mean

**Comment by iforgotmeword** [comment]
mean if you keep it the same size it's just going to be a weaker cargo

**Comment by chizzy376** [comment]
> Untitled

Making it a wide makes it look much worse and perform worse, while also making the mounted spot in the middle be obstructed topleft.
Right now the tad is made to be a great backlining tool, and if you bust the windows out you get an even greater (But much, much riskier) frontliner

**Pull request merged**
