### PR TITLE
The AI wants YOU to get revived

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

Replaces the marine defib sound with the new AI VOX system saying "Revival imminent" followed by the TG station defib warble. All credit goes to RipGrayson for making the sound for me, warble included, all I really did was make it slightly shorter.
RipGrayson gave me a ton of sounds (Thanks again!), you should check the discord for the download if you think this isn't a good replacement.

https://user-images.githubusercontent.com/95723150/157558659-bdf28ed3-9e06-4f45-873d-8012a3715807.mp4

## Why It's Good For The Game

Right now the defib sound is the same bwoink used for admin pings. This not only scares the shit out of some people but also wrongfully uses an important sound. The bwoink should stay restricted to an admin only sound. gladosmarinerevive is a better option because it is distinct and recognizable. It outright tells you that you are ready to revive, then it is followed by the defib sound from TG.

## Changelog
:cl: Arctrooper8/RipGrayson
soundadd: New marine defib sound: AI voice telling you to revive followed by defib warble.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
I like the bwoink though, I completely ignore the vote sound effect. But maybe that's just me.

**Comment by Mechanelize** [comment]
hah

**Comment by EvilMelonTheSecond** [comment]
Even if it means my death I will ignore all map votes, not to send a message but because I don't care which map is picked.

Please pick a different sound.

Sidenote: Larva queue sound is also bugged and does not play at all

**Comment by Losenis** [comment]
Votestart is already ignored by most players since 90% of the time nobody really cares enough to vote other than those that don't want distress, and even then not everyone since some like crash too. Given that votes can happen midgame, this'll only make defib accidentally ignorable since at the start nobody is going to pick up on votestart.ogg actually being defib without reading github. I'd propose making it the end sound for defib just as placeholder if you REALLY want to not have it be a bwoink, but given how critical it is it should have a just as critical sound.

**Comment by Arctrooper8** [comment]
> Even if it means my death I will ignore all map votes, not to send a message but because I don't care which map is picked.
> 
> Please pick a different sound.
> 
> Sidenote: Larva queue sound is also bugged and does not play at all

I have heard the larva queue before and there was even a PR that fixed the bug: https://github.com/tgstation/TerraGov-Marine-Corps/pull/9461
Silo already uses the drumbeat and this isn't really about making votes more important. It's about keeping the admin sound for admin things. I chose votestart.ogg because it's already used with the silos and hoped this would help it ease into it's new role as "time to play again sound" for both teams.

**Comment by Arctrooper8** [comment]
> Votestart is already ignored by most players since 90% of the time nobody really cares enough to vote other than those that don't want distress, and even then not everyone since some like crash too. Given that votes can happen midgame, this'll only make defib accidentally ignorable since at the start nobody is going to pick up on votestart.ogg actually being defib without reading github. I'd propose making it the end sound for defib just as placeholder if you REALLY want to not have it be a bwoink, but given how critical it is it should have a just as critical sound.

Those are some good points. It might be best to find a new "respawn" sound for both sides, do you have any suggestions?

**Comment by RipGrayson** [comment]
> Those are some good points. It might be best to find a new "respawn" sound for both sides, do you have any suggestions?

If you want I can make a new sound effect using our current vox announcer saying something along the lines of "You are ready revive".

**Comment by Lumipharon** [comment]
Will this spam if multiple people are defibbing?

**Comment by Arctrooper8** [comment]
> Will this spam if multiple people are defibbing?
I didn't touch any code and I've never heard the bwoink get spammed with multiple defibbers.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Find a different sound, this is too long and reveille has real life applications

**Comment by Arctrooper8** [comment]
> Find a different sound, this is too long and reveille has real life applications

Will do

**Comment by Firefox13** [comment]
Use what /tg/station has for this sound, `genetics.ogg` (in their github)

https://user-images.githubusercontent.com/57810301/157429079-7ef6f04d-3147-4377-8bcb-a8b6d2411108.mov

**Comment by novaepee** [comment]
> Use what /tg/station has for this sound, `genetics.ogg` (in their github)

We are now slowly turning to TG.

**Pull request merged**
