### PR TITLE
Removes rad armor

### PR DESCRIPTION
**Pull request by TiviPlus**
bai bai

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
What

**Comment by RipGrayson** [comment]
> What

We don't have a source of radiation, and radiation was kinda a bad mechanic anyway. No sense in keeping radiation armor around when we literally won't ever use it.

**Comment by ivanmixo** [comment]
Me downvoting a PR removing an unused feature because removal bad.

**Comment by bluezorua** [comment]
im geniunely surprised radiation armour even got merged in the first place

**Comment by FIXTHERADBOXPLEASE** [comment]
Uhhhh aren't there radioactive SoM grenades and rockets now

**Comment by Starfirejordan** [comment]
> Uhhhh aren't there radioactive SoM grenades and rockets now

Tivi yelled at Lumi for trying to use rad armor and told them to make it a status effect instead of actual radiation

**Comment by Lumipharon** [comment]
> Uhhhh aren't there radioactive SoM grenades and rockets now

It uses bio armour

**Comment by TiviPlus** [comment]
1984

**Comment by Derrick2Electricboogaloo** [comment]
Literal 1984, holy shit the comments. :)

**Comment by Derrick2Electricboogaloo** [comment]
> > What
> 
> We don't have a source of radiation, and radiation was kinda a bad mechanic anyway. No sense in keeping radiation armor around when we literally won't ever use it.

FEATURE

**Pull request merged**
