### PR TITLE
Cool buff to SG minigun

### PR DESCRIPTION
**Pull request by goose4429**
## About The Pull Request

Quick shooting is fun, so now the minigun fires even faster! Without damage, pure fun.

## Why It's Good For The Game

Quick shooting very fun.
Benos lag, benos cry, is good.

## Changelog
:cl:
balance: SG now shoots 100x as fast, at 0 damage
/:cl:

image

### CODE REVIEW

**Comment by isotope436** [comment]
i support it

**Comment by Arctrooper8** [comment]
Firerate only works in intervals of .5 it will round up or down depending on which is closer

**Comment by goose4429** [comment]
Okay, Arctrooper didn't get the meme. 
Closing so that Mole doesn't merge this on accident

**Comment by Arctrooper8** [comment]
> Okay, Arctrooper didn't get the meme. Closing so that Mole doesn't merge this on accident

Obviously you've never heard of the straight man in comedy.

**Pull request closed without merging**
