### PR TITLE
Powerfist balancing

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request
Revives #5639 
- Power fist can now only use lasgun power cells
- Energy consumption is 50*power level. This is 20 uses at power 1, 10 at power 2 and 6 at power 3.
- Hitting a MOB_SIZE_BIG does double damage, knocks you back and staggers the xeno similarly to buckshot instead of knocking them back.
- Takes 6 hits at charge 3 to crit an elder crusher and 5 hits to crit a young runner. For reference, harvester takes 4 hits to down a runner and doesn't require batteries, but much more to down a high-armored xeno because it doesn't ignore armor, while powerfist does.

## Why It's Good For The Game
It makes powerfist's crowd control more restrained as getting hit by it while being a slow xeno can be a death sentence, while it doesn't matter much for fast xenos. This also opens room for the powerfist to have its damage improved so that it is still good for pushing xenos, but can also be used for damage.

## Changelog
:cl:
balance: powerfist now has less uses, but deals more damage. If you hit a big xeno, you get pushed back instead and deal additional damage
/:cl:

### CODE REVIEW

**Comment by InterroLouis** [comment]
The power use increase was excessive before and it's excessive now.

**Comment by Naaanii** [comment]
Based. Maybe lower the max setting changes a bit.

**Comment by Walarks** [comment]
> The power use increase was excessive before and it's excessive now.

> Based. Maybe lower the max setting changes a bit.

Changed stuff.

**Comment by Swagile** [comment]
maybe if it didn't require a screwdriver to remove battery so you can switch on the go this would be more viable

otherwise this breaks a lot of builds, because you needed the power of high cap to be able to punch more than a few times

plus big mob xenos knocking you back when you hit them is really dumb; remove that and keep the stagger instead. stagger without the knockback of powerfist is already a big enough nerf to powerfist, no need to literally punish people for playing the game by punching them AWAY from xenos (when its already hard to get close to xenos in the first place)

**Comment by Walarks** [comment]
> maybe if it didn't require a screwdriver to remove battery so you can switch on the go this would be more viable
> 
> otherwise this breaks a lot of builds, because you needed the power of high cap to be able to punch more than a few times
> 
> plus big mob xenos knocking you back when you hit them is really dumb; remove that and keep the stagger instead. stagger without the knockback of powerfist is already a big enough nerf to powerfist, no need to literally punish people for playing the game by punching them AWAY from xenos (when its already hard to get close to xenos in the first place)

I think we can test both since you being pushed away can also be a positive since you stun the xeno for a bit and are brought to safety. If you don't get pushed away, the repeated stunning could also be overwhelming.

**Comment by InterroLouis** [comment]
I mean, it doesn't actually stun. It applies a single stack each of weaken and stagger, plus a small slowdown.

**Comment by SilencedMP5A5** [comment]
power fist is fine 

just surround the user when they overextend and automatically win

**Comment by fernandos13** [comment]
THE GOOD THING ABOUT THE POWER FIST IS THE USE.. people take machete and vali for damage the POWERFIST thing IS the utility

**Comment by SilencedMP5A5** [comment]
ngl i take power fist because i'm bad at clicking on xenos and it's satisfying to chain multiple hits and send them careening off into the sunset

**Pull request closed without merging**
