### PR TITLE
Lower xeno ratio

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
To go with #16557

Larva points required in Nuke War changed from 8 to 10 (same as crash currently).

Changes the optimal xeno/marine ratio from 1:2.46 to 1:3. (The above change does this roughly, but I simply made it an exact number for convenience of tweaking.
## Why It's Good For The Game
Balance for our brave new world.
## Changelog
:cl:
balance: Larva points required per xeno in Nuke War increased from 8 to 10
balance: Xeno to Marine ratio in Nuke War changed from 1:2.46 to 1:3
/:cl:

### CODE REVIEW

**Review by Kuro020 — APPROVED** [review]

**Comment by Breadeagle** [comment]
Does this affect larva point generation from drains and silo? If so is that intended? 

If only going for ratio on spawns, could change the amount of larva each marine spawn is worth.

**Comment by Looking4bros** [comment]
I don't really like the idea of less xenos, as every time there's a dip in the xeno population, it means boring marine stomps and more HvH. I genuinely think that marines need to get good, it's just like when Quickbuild was introduced and every round was a FoB siege because nobody would take Flamers, Plasma cutters, or anything of the like.

**Comment by Lumipharon** [comment]
Marked DNM for now since it may likely need adjustments. Feel free to TM though.

**Review by ivanmixo — APPROVED** [review]

**Comment by Victor239** [comment]
This is a pretty significant jump and feels like too quick a reaction to marines just needing to adjust to https://github.com/tgstation/TerraGov-Marine-Corps/pull/16557 for a while first. Why not something more reasonable like 2.7?

**Comment by ivanmixo** [comment]
> I don't really like the idea of less xenos, as every time there's a dip in the xeno population, it means boring marine stomps and more HvH. I genuinely think that marines need to get good, it's just like when Quickbuild was introduced and every round was a FoB siege because nobody would take Flamers, Plasma cutters, or anything of the like.

And quickbuild has since been heavily adjusted from 600 walls per xeno to a shared pool, it hasn't stayed the same and the marines have not adapted to it, it just got brought down to a more reasonable level. 

The goal with touching the ratio instead of stats is to keep xenos able to 1v1 marines reliably while also trying to not have an overwhelming amount of xenos where marines have to play very optimally to have a shot at winning.

**Comment by Looking4bros** [comment]
>And quickbuild has since been heavily adjusted from 600 walls per xeno to a shared pool, it hasn't stayed the same and the marines have not adapted to it, it just got brought down to a more reasonable level.

Marines not adapting is either a gameplay loop problem, or a skill issue. Either they don't like, and thus refuse to bring the required tools to counter, or they can't wrap their heads around how to do it.


When a marine respawns, they effectively add whatever job they respawned as into the Ratio counter right? What if we buffed marines respawn timer with this? Playing RUTGMC (as utterly broken as it is) their 15 minute respawn timer for marines does let people who perma get back into the game in a timely manner, 10 minutes instead of 25.

**Comment by PibeCantina** [comment]
I feel like this is slightly too big a nerf, i think it needs a small buff

**Comment by FunkyMonke47** [comment]
eh, since this has been tmed it feels like there's been a lot more actual games, where neither side really stomps the other, (at least really quickly), and xenos are still winning a lot, so yeah. This does not decrease the actual amount of xeno players who wanna play, just the numerical amount that can be there at one time. (big burrowed rounds would happen regardless of this change due to other factors)

**Comment by Victor239** [comment]
10-7 wins to marines since the server started being hosted earlier, I think this PR can be closed now that marines have adapted successfully.

**Comment by Isy232** [comment]
I believe we should maybe look at alternate strategic changes such as #16587 which make fortifications more useful to give marines some of their power back instead of decreasing xeno numbers.

I also second Victor in that marines may be able to adapt to different strategies that may be more or similarily effective, practically a forced meta shift.

Given my current understanding I'm strongly against merging this currently.
I am very willing to see this continue to be TM'ed to see if the current high marine winrates with this change remain consistent.

**Comment by Isy232** [comment]
In my own experience I've found Marine winrates to be somewhat higher than I think they should be with this test merged.
The winrate stats bot is dead so we're stuck with subjective analysis.

Given this has been test merged for a week, I'd suggest removing the test merge for a week to see what aim mode removal is like with previous xeno numbers for a decent amount of time.

**Comment by Mannybrado** [comment]
> In my own experience I've found Marine winrates to be somewhat higher than I think they should be with this test merged. The winrate stats bot is dead so we're stuck with subjective analysis.
> 
> Given this has been test merged for a week, I'd suggest removing the test merge for a week to see what aim mode removal is like with previous xeno numbers for a decent amount of time.

agree

perhaps try out some of the alternatives 
(つ ͡ꈍ ͜ʖ̫ ͡ꈍ )

**Comment by Looking4bros** [comment]
Alternative balance PRs TMd when?

**Comment by Zangeiti** [comment]
speedmerge NOW

**Pull request merged**
