### PR TITLE
Revert "Revert "Triples damage from guns/acid spit and xeno melee""

### PR DESCRIPTION
**Pull request by BraveMole**
It was good pr

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
Wow, that damage buff.

**Comment by Ragecrabbo** [comment]
Finally some runner nerfs

**Comment by Losenis** [comment]
Warrior lunge punch with 120 damage lets GOOOOOOOOOOOOOOO

**Comment by TiviPlus** [comment]
1984

**Pull request closed without merging**
