### PR TITLE
Removes jones the cat.

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
Removes jones the cat, very very bad cat

## Why It's Good For The Game
removes bad cat

## Changelog
:cl:
fix: replaces jones with ian
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
GIT BAN THAT MAN NOW

**Comment by TiviPlus** [comment]
JONES IS A GOOD BOY LEAVE HIM ALONE

**Comment by SplinterGP** [comment]
replacing jones by Ian, stinky grumpy cat

**Comment by spookydonut** [comment]
lazy webedit pr

**Pull request closed without merging**
