### PR TITLE
Seperates PO into Condor Pilot and Tadpole Pilot

### PR DESCRIPTION
**Pull request by ClosetedSkeletonGH**
## About The Pull Request

Splits PO into Condor Pilot and Tadpole Pilot. 

Adds relevant mapspawn stuff/job selection/skill stuff for them, doesn't change them or their balance in any way.

Tadpole Pilot can pilot the condor, Condor Pilot can pilot the tadpole. The change is in name only

## Why It's Good For The Game

Having two very separate jobs under the same title is pretty awful game design especially if you're joining in late and cant see what is already taken.

This is why we get so many SSD PO's, because they get forced into a job they dont want to do because someone already called dibs on the job they wanted to do. This PR will solve this issue

Also since there are 0 skill/access changes, they can just swap if they both want to

## Changelog

:cl:
add: Condor Pilot and Tadpole Pilot role
del: PO role
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
Hooray, the PR that everyone wanted but were too lazy to code!

**Comment by ClosetedSkeletonGH** [comment]
> Hooray, the PR that everyone wanted but were too lazy to code!
> 
> Also, instead of tadpole pilot why not call it dropship pilot? Especially with all the new dropships coming soon.

They are all Tadpoles aren't they? Dropship pilot makes it sound like theyre also obligated to pilot the Alamo

**Comment by Arctrooper8** [comment]
> > Hooray, the PR that everyone wanted but were too lazy to code!
> > Also, instead of tadpole pilot why not call it dropship pilot? Especially with all the new dropships coming soon.
> 
> They are all Tadpoles aren't they? Dropship pilot makes it sound like theyre also obligated to pilot the Alamo

Well yeah, but the other fellow is called the CAS pilot and not the Condor pilot. So it'd make sense to call it the Dropship pilot instead of the Tadpole pilot. You could also the do the opposite and swap CAS pilot for Condor pilot. It's more about consistency of having the vehicle name or the vehicle type I guess. But overall very good PR!

**Comment by ClosetedSkeletonGH** [comment]
> 

Its already called Condor pilot ahahaha, Its Tadpole Pilot and Condor Pilot (but the code is tadpilot and caspilot just for brevity)

**Comment by Arctrooper8** [comment]
> Its already called Condor pilot ahahaha, Its Tadpole Pilot and Condor Pilot (but the code is tadpilot and caspilot just for brevity)

Ah okay my bad lol, that's what I get for only reading code paths. And yeah you're right even the new dropships are called Tadpoles.

**Comment by FosterGrime-Heymynameslouie** [comment]
cool change spedmegher

**Comment by Al-1ce** [comment]
Three years in the making, and about damn time.

I love this pr.
+1

**Comment by Deroh-Ra** [comment]
Job bloat.

**Comment by Coastfront** [comment]
> Job bloat.

And yet it is bloat as gilded as the hollow space in boats.

PO is the, singular fucking job in the game, where you are in no way guaranteed to fufill the role of the job that you wanted to play, at all.

An equivilent would be spawning in as a squad leader and getting instantly demoted for somebody else to promote, and its why, as the pr stated, there are endless seas of SSD po's or suicided PO's because they joined and the other po got tad when they wanted to tad or condor when they wanted to cas.

Only the tongue of the blind would declare this as any greater than dirt obscuring a flower. it is, so, egregiously fucking dumb that you can pick PO, and then just not get to play the job you wanted despite having the role.

**Comment by TiviPlus** [comment]
This will not be merged while the job system relies on the name due to how persistence works
Instead you should add something like a task assigning while keeping these as one job

**Review by TiviPlus — CHANGES_REQUESTED** [review]
.

**Comment by ClosetedSkeletonGH** [comment]
> 

yeah thats a lot of work for something thats just as simple as making two entirely different jobs into two different things, way more than im invested in ever trying out the new tadpole.

Sorry but thats above my level of coding and motivation

**Comment by Al-1ce** [comment]
instead of allowing a half-decent bandaid they close the PR and let the problem persist

incredible

**Comment by pilotmans** [comment]
As someone whom wants play as an alamo pilot, this is tragic.

**Pull request closed without merging**
