### PR TITLE
Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request
If a Defender is fortified and has 100+ bullet armor, bullets will reflect off of it.
This only counts for projectiles that do brute damage.

Defender is still hit by the projectiles so sunder and ap will still be applied.
Sadar shots de-fortify on hit and thus cannot be reflected.

## Why It's Good For The Game
This can only be achieved through ancient defender with very strong warding pheros.
I figure this will be a funny interaction that will not cause too much problems balance wise.

## Changelog
:cl:
add: If a Defender is fortified and has 100+ bullet armor, bullets will reflect off of it.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
The following xenomorphs can help ancient defender have 100+ armor due to very strong warding pheros:

- Elder prae and older with ancient prae having aura_strength of 4.5
- Mature queen and older with ancient queen having aura_strength of 5
- Young king and older with ancient king having aura_strength of 6

I won't be surprised if defender starts camping with these xenomorphs.

**Review by BraveMole — APPROVED** [review]

**Comment by Losenis** [comment]
As hyped as I was this turned out to be an awful idea, getting fracs off marine FF alone with zero of said deflections being my own shots. Sentries can FF you, and their own bullets can hit cades effectively invalidating them altogether. Defender can also pop the ability to heal its sunder and suddenly it can deflect even more. I've seen marines literally kill themselves on deflections alone.

image

**Comment by Lumipharon** [comment]
This seems like a poor idea because marines have no visual indication that a beno they want to shoot can or can't reflect bullets back into their face.
Helps laser master race though.

**Comment by private-tristan** [comment]
perhaps give it a outline, maybe in yellow or red to show that the defender is able to reflect bullets?

**Comment by SpaceLoveSs13** [comment]
Terrible balancing as I can tell from normal playing experience. This is not TM worthy yet.

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
