### PR TITLE
Change the snowstorm sprite

### PR DESCRIPTION
**Pull request by botPurple**
## About The Pull Request

Yeah, I just changed one sprite that's hurting my eyes a lot.
image
[Before/After gif](https://imgur.com/a/ohSGNGu)

## Why It's Good For The Game

No more unwatchable milk on the screen in winter maps.

## Changelog
:cl:
imageadd: Changed snow_storm sprite
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by XSlayer300** [comment]
sorry ;w;

**Comment by Lumipharon** [comment]
Psst, no one show them the old snow sprites.

**Comment by QualityVan** [comment]
Isn't the point of snowstorms to kill visibility? Is there anything else the weather does?

**Comment by Serxule** [comment]
> Isn't the point of snowstorms to kill visibility? Is there anything else the weather does?

it used to do damage if you didnt have a mask but i think that was removed

**Pull request merged**
