### PR TITLE
Marine armour now prevents delimbs

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
Delimbs only serve to be a permanent form of attrition and mostly removal from combat or even a permastun in some scenarios as they also heal giving the opportunity to remove another limb. It's a mechanic only fun for one side. With the removal of capture gameplay marines can still be attritioned through fractures, and RNG organ damage and IB.

Armorless personnel can still be delimbed. (Medics will have to be a bit more careful during the defib process)
## Changelog
:cl:
add: Marine armor now prevents delimbing
balance: Most marine armor now prevents delimbing
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
F For our ravager, runners and other castes that do not have that great of spammable stuns , and rely on delimbs to get rid of gamer-marines.
(Only super-heavy armor should get no delimb in my opinion)

**Comment by psykzz** [comment]
I'd agree, make delimbs an upgrade to existing armour or something that comes later, or perhaps reduces the chance, but not flat our removing delimbs.

**Comment by srxtreme** [comment]
Delimbs are one of the only ways you can actually put down a marine (for a while anyways). While they are frustrating to be the target of, IB,fractures, and organ damage are rather marginal/easily treated (valk + qc says hello). Additionally delimbs serve as a mechanic to discourage excessive premedding.

**Comment by Naaanii** [comment]
> Delimbs are one of the only ways you can actually put down a marine (for a while anyways). While they are frustrating to be the target of, IB,fractures, and organ damage are rather marginal/easily treated (valk + qc says hello). Additionally delimbs serve as a mechanic to discourage excessive premedding.

Delimbs remove a marine out of combat till treated. IB, fractures and Organ damage only add to the further attrition not to mention cumulative pain from the latter 2.
Cloneloss also exists as another form of attrition and while can be slept off or cryo celled, only adds further downtime to actually heal to full.
Premedding is already discouraged in the form of corpsedrag which maintainers are fine with as its punishing but a corpse can't be dragged infinitely.

**Comment by FIXTHERADBOXPLEASE** [comment]
Salt PR?

**Comment by Naaanii** [comment]
> F For our ravager, runners and other castes that do not have that great of spammable stuns , and rely on delimbs and melle to get rid of gamer-marines. (Only super-heavy armor should get no delimb in my opinion)

No caste relies on delimbs. TTK is lower when just aiming chest. Delimb just acts as a mechanic of perma removal until treated almost like a permanent Sunder mechanic until a specific treatment is provided.

**Comment by Naaanii** [comment]
> I'd agree, make delimbs an upgrade to existing armour or something that comes later, or perhaps reduces the chance, but not flat our removing delimbs.

Organ Damage, IB and not to mention Xeno slashing itself is probability based and kind of a gacha mechanic. I don't really want to make it even more probability based.

Armour upgrades would make more sense but as a mechanic it's still unfun and lower armours already have their ups and downsides via speed/eHP values.

**Comment by Lumipharon** [comment]
Your 'why is this good for the game' is basically why I think leaving it in is good for the game.

**Comment by EvilMelonTheSecond** [comment]
delimbing being absolutely permanent sucks, you can't even drag your arm/leg back to get it reattached. Prosthetics force you to bring repair tools and makes chip damage a nightmare to heal.

I don't see these as something that adds anything to gameplay for either side, xenos don't ever notice the marine healing processes and marines are forced to play more cowardly in case xeno are targeting limbs which is semi RNG and hard to notice during combat.

I don't understand why xeno complain huggers are too weak to be useful but consider delimbing to be an amazing feature that forces marines to go shipside while in practice both are almost identical for their use for them.

**Comment by Xsdew** [comment]
Fractures, Internal Bleeding, and Organ Damage can be mitigated ground side with surgery (Ground Side), equipment, and chemicals. So they apply no real form of attrition. The only thing that can cause attrition is de-limbing, and that is if the doctors didn't bring any spare limbs. So you have to go into the autodoc / limb printer shipside to get fixed.

Additionally we still have Medical Doctor, and the only action they get is any Ship Side Medical Evacuations. Or they head ground side to the FoB to compete with the Synth and Corpsman. Shipside Engineering is already dead, lets not add shipside medical when 95% of everything can be fixed with the correct personnel and tools groundside.

**Comment by Naaanii** [comment]
> Fractures, Internal Bleeding, and Organ Damage can be mitigated ground side with surgery (Ground Side), equipment, and chemicals. So they apply no real form of attrition. The only thing that can cause attrition is de-limbing, and that is if the doctors didn't bring any spare limbs. So you have to go into the autodoc / limb printer shipside to get fixed.
> 
> Additionally we still have Medical Doctor, and the only action they get is any Ship Side Medical Evacuations. Or they head ground side to the FoB to compete with the Synth and Corpsman. Shipside Engineering is already dead, lets not add shipside medical when 95% of everything can be fixed with the correct personnel and tools groundside.

Killing shipside medical further and making it easier to be done groundside is actually more of a win. Making cryo tubes and autodocs moveable/buildable would be nice but probably more suited for another PR.

Allowing doctors to deploy within the FOB and let their medical skill heal for more or make splints worthwhile would still keep them relevant if not make them even more relevant.

Needing surgery for anything is still downtime spent needed to heal. Mechanics that are uninteractive and who's only purpose serve to be 'complicated' as a means of gameplay make little sense in the TDM nature of this game.

**Comment by Losenis** [comment]
Delimb is gay anyway. For guns that require 2 hands and for smartgunner as a role it's literally worse than death because you can't use your gun and need to pray for a medevac to go shipside and then suffer the CBT of changing your loadout for a robolimb that is bugged and fumbles welder repairs. Delimb being straight up worse than fucking **DYING** is already insane in concept let alone in practice with warrior ignoring armor or every xeno targetting one limb in specific, which was already a problem that led to limbs getting bonus HP in the past. And that's if delimb works in the xeno's favor, because marines get healed by getting delimbed and get back up to shoot them if they're using a T90 of another 1handing-friendly gun.

**Comment by SpiderPsycho** [comment]
RNG organ damage and IB is not enough to actually make dying an issue. The reason xenos go for delimbs is exactly because marines can shrug off everything else. Replacing limbs actually takes time and means that they're out of the fight for however long. Unless you intend to make IB and organ damage more consistent, then this is ridiculous.

**Comment by bluezorua** [comment]
light armor should not prevent delimbs tbh, and with jaeger the actual arm protection should be the ones that prevent delimb not the base

**Comment by Naaanii** [comment]
> RNG organ damage and IB is not enough to actually make dying an issue. The reason xenos go for delimbs is exactly because marines can shrug off everything else. Replacing limbs actually takes time and means that they're out of the fight for however long. Unless you intend to make IB and organ damage more consistent, then this is ridiculous.

Xenos don't like sunder either because of the downtime spent healing it. IB, Both sides rely on attrition, Xenos more so but that doesn't make being unable to do anything any more fun nor a good mechanic to keep especially with the long since removal of capture gameplay where delimbs helped secure caps even better. Organ damage, fracs and cloneloss all result in pain and downside effects when alive but also require a certain amount of downtime to heal. In general, it is not fun waiting to fight at full strength, attrition for marines or sunder for Xenos. I'd be down for making IB, Organ and fracs more punishable in combat with bigger downsides till healed.

**Comment by Redrover1760** [comment]
In my opinion, I like delimbs. Its thematically cool that you lost your arm or leg fighting the xenos and have to get it replaced with a robotic limb.

If you find its an issue, I'd much prefer a rework of some kind. Also, it does pretty much kill shipside medbay, not that limb replacement even a long surgery, so you aren't even out of the fight that long, even. 

Also, another counterargument: Delimbs have actually saved me from death before, as such a high amount of damage on a limb was removed from me, put me out of crit and let me run away.

I think the only potential problem is that delimbs could be a way to force someone shipside, although only high damage xenos can actually try this. Still, when I play Corpsmen, the amount of delimbs aren't very high, and we easily medevac them all to shipside to get a 30 second surgery done (if the medical doctor is competent) so they can come back down via drop pod in like another 30 ish seconds and suddenly its like they never got delimbed. I carry a soldering tool or at least welder and cable as Corpsmen to heal robots anyways so its not a huge deal.

**Comment by Derrick2Electricboogaloo** [comment]
Could not spin IB, so now we are removing delimbs. Okay.

**Comment by bowlofcereal** [comment]
would it be theoretically possible to make the machines that make robotic limbs actually make organic limbs like they supposedly are supposed to be able to do but cannot for some stupid reason as it would add back a reason to not throw people into the autodoc when missing limbs and therefore trivializing the whole concept that would cause this PR to even be a thought or be brought up

**Comment by Xsdew** [comment]
> Killing shipside medical further and making it easier to be done groundside is actually more of a win. Making cryo tubes and autodocs moveable/buildable would be nice but probably more suited for another PR.

 The only distinction between Medical Doctor and Corpsman are their mechanical skills, and for flavor purpose the amount of education and backgrounds they have. Medical Doctors ship side deal with serious injuries while the Corpsman fix the boo boo is ideally how it goes. But is not the case currently. This is only a win for people who want the optimal treatment, with little to no downside (Medical Doctor Skill Level treatment without going to the Ship). Which already happens with Synth / FoB MD.

Cryo and Autodocs are not buildable because they are elements of map balance. Securing groundside medbay for quicker treatment times. That is an interactive element to the game that both marines and xenos can fight over.

> Allowing doctors to deploy within the FOB and let their medical skill heal for more or make splints worthwhile would still keep them relevant if not make them even more relevant.

Better numbers does not make a role. The classification between serious injuries and light injuries is why Medical Doctor and Corpsman exist as two separate roles. The concept of Triage is how the Medical Systems works. If everything can be treated at the LZ, only one role is needed. And in practice generally everything is treated at the LZ already.

> Needing surgery for anything is still downtime spent needed to heal. Mechanics that are uninteractive and who's only purpose serve to be 'complicated' as a means of gameplay make little sense in the TDM nature of this game.

Healing as a marine is done mainly passively. This is done by chemicals, and it is probably the weakest part of baymed because that just means 1 pill = X amount of damage. Or a skill check of good inventory preparation. Popping Pills / Injectors at the rear of the front lines isn't downtime, it is just prevention of more serious injuries. Which is by the way how to avoid de limbing. And if you do need some surgeries, there is very little downtime as a marine, thanks to the teleporting evac beds and drop pods you can be back into the fight as fast as the auto doc / cryo / Shipside MD can work. Or just bug whoever can do it at the LZ.

**Comment by RyderFive** [comment]
Delimbs would be ok if we had robolimbs reworked or changed with a normal limb option as well. Currently they're just a god awful CM holdover even with the RNG being reduced before. Not to mention all the problems and permanent round crippling they can bring.

**Comment by Losenis** [comment]
People are really putting a lot of weight on delimbs doing what they think it's doing when I've run field surgery and replaced limbs on people before they even realize they lost them. A backpack can already fit two of every limb, you don't even have to go shipside for it. Delimb is only there to make the game unfun enough for the marine to consider not playing anymore, because it still is like, what, 2 minutes for a marine to get medevacced, jump into autodoc/get surgery replacement which is EVEN FASTER, run to pod, and pod down with webmap coords? A marine gets more downtime from waiting on req if they decide to pay it a visit in the meantime.

Not to mention that with the xeno drag changes some people are hit the most like engineers losing their insulated gloves because apparently when you lose your arm it's good habit to deliberatedly remove the glove of your other hand too. Now you're fucked because you can't actually replace them if you need to fix an APC or anything else involving electrics.

**Comment by Shootnik01** [comment]
Dude, any fracture - is 5 seconds of medic time. I strongly disapprove this pr, as huge nerf for damage castes of benoses

**Comment by zee11zee** [comment]
Don't delimbs only happen when you are caught alone? I thought rav was the only xeno that could get a delimb with a large group of marines.

**Comment by Xsdew** [comment]
> Don't delimbs only happen when you are caught alone? I thought rav was the only xeno that could get a delimb with a large group of marines.

It is dependent on Brute damage already taken, from there it is random. For Delmibs if you pace your damage with healing you will not be delimbed.

**Comment by Luxyboo** [comment]
i like this PR :)

**Comment by Lumipharon** [comment]
*comes up behind you and delimbs your PR*

**Comment by Naaanii** [comment]
PR killed in shorter time than average shipside treatment. Oh the misery.

**Comment by Losenis** [comment]
>Don't delimbs only happen when you are caught alone?

It does but not for the reasons one would think. Getting caught alone probably means getting caught by one xeno backlining whilch leads to all your brute damage being from one xeno doing all brute to one aimed limb. Because of this getting ganked by 10 xenos is actually less likely to delimb as they all spread brute and even add burn damage around to kill you before you actually get delimbed.

Delimb is so fucking stupid that you're in more danger when fighting one xeno than 20+ xenos alone.

**Comment by Derrick2Electricboogaloo** [comment]
> 

We should allow the ability to reattach organic arms or be able to print them and attach them.

**Comment by David-Stormwell** [comment]
closed but I'm still calling u a stupidhead

**Comment by Shootnik01** [comment]
image

**Pull request closed without merging**
