### PR TITLE
0.8% chance for the shrike's roar to be a familiar coder screaming

### PR DESCRIPTION
**Pull request by Neocloudy**
## About The Pull Request
0.8% chance for the shrike's roar to be a familiar coder screaming. i know that the shrike's unrelenting force ability is used every round multiple times, so that's why it's really low. i might make it lower (or higher?)

...

it's just xander dying in lethal company
### volume warning
https://github.com/user-attachments/assets/62c530cc-cd59-4c90-a8ba-601d73baf8fd
## Why It's Good For The Game
it's not, but we have had goofy shit like this in the game before, such as dolls referencing other games/player references/etc. i think this is rare enough and goofy enough to stay in the game
## Changelog
:cl:
soundadd: ridiculously low chance for the shrike's unrelenting force roar to be something... different. good luck.
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
Based as fuck. Speedmerge this

**Review by RipGrayson — APPROVED** [review]
clearly what the codebase needs to be its best self

**Comment by Isy232** [comment]
You have my utmost support and respect for this.

Do Queen Screech next.

**Comment by Technical-l** [comment]
powercreep pr

**Comment by Lumipharon** [comment]
Bruh.

**Comment by Neocloudy** [comment]
IMG_2286

**Comment by TiviPlus** [comment]
make it an april fools pr lmao

**Pull request closed without merging**
