### PR TITLE
Trouble in terrorist town

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

New gamemode, can be fun for a quick event.

Based on nuclear war, cenos can only evolve into to castes, drones and hunter. There's a twist: these two classes have access to disguise ability, and they can mark marines ....

On top of that, disguise plasma cost is removed, drones have access to blessing menu and every class can hijack the ship.

Disguised xeno will produce lights if their marked target has lights.
Xeno speaks common
Minimap is disabled in TTT
Marine HUD is disabled in TTT

## Why It's Good For The Game

Probably will be a broken mess, if people like it I'll improve 

## Changelog
:cl:
add: Trouble in terrorist town added
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
what stops marines from aim-mode shooting suspicious players? what about smartgunners? the minimap?

**Comment by turnop** [comment]
finally some good fucking food

**Comment by ilikesaying** [comment]
also, shotgun vulnerability

**Review by TiviPlus — APPROVED** [review]
Among is in tgmc

**Comment by Autisem** [comment]
Gonnna make a long comment with cheese stuff that needs removing

I like the idea alot but you may be better off just giving transform ability to humans to make it easier on yourself(maby throw some extra powers in)

Any single point of target damage will instantly remove your disguise, which can include
literly random bullets
IFF ammo
punching
aim mode

Its trivial to check who is and who is not xeno based of this

As disquised xeno, you will perform ALL animations that your target does. so if you randomly pull out a gun or something similair youd have to dynamicly bullshit around that which is sometimes impossible

Xenos cannot open cades, which is pretty obviouse red flag

During disquise you still get the xeno bloody overlay, so if you disquise while hurt they will see floating green splatters.

If you disquise as a corpse marines can still pump into you and be blocked

Reportly medhud is a dead giveaway, and this propably goes for most other huds

Examing an aged xeno still gives the text of "he looks mature and dangerous"(or what ever it is)

**Comment by henriquekill9576** [comment]
Adding to above, haven't seen it myself but tac sensor attachie might be a dead giveaway and it's hard to VV them out of all vendors

**Comment by zzurge** [comment]
lovely idea,always a champion of game mode variety

**Pull request closed without merging**
