### PR TITLE
disables being able to pick synth

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
you can't pick synth ~~0 effort~~

## Why It's Good For The Game
synth is a bad role that has nearly no tradeoffs if you realize that most shipside roles don't shoot in most rounds anyway, and makes most shipside roles pointless to pick since a synth is usually just better

## Changelog
:cl:
del: Removed synth
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -61. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SpaceLoveSs13** [comment]
Synth is role forbothground and ship. Bad pr. 

- Synthetic Rosana.

**Comment by Hughgent** [comment]
`Maintainers may close this PR at will.`

**Comment by Texicos** [comment]
remove more content, what do you mean I have to have more reason than it can do more than one job?

**Pull request closed without merging**
