### PR TITLE
Fixes xeno_action's add_cooldown() sanity check to prevent 0 length timers

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Adds a check for 0 length cooldowns to `add_cooldown()`

## Why It's Good For The Game

Fix good.

## Changelog
:cl:
fix: Fixed a timer error with 0 length cooldown xeno actions.
/:cl:

### CODE REVIEW

**Comment by Hughgent** [comment]
why there and not in `xeno_action` ? is it not runtiming for other things like it?

**Comment by Wayland-Smithy** [comment]
I'll check @Hughgent, but I am thinking they are probably not calling `add_cooldown()` if they have not set the `cooldown_timer`

**Comment by Hughgent** [comment]
Well, this would be a kind of 'future proofing' such that if anyone else adds an ability.

**Comment by Wayland-Smithy** [comment]
Can't argue with that, but again it'd only matter if they use `add_cooldown()` by mistake, like from doing some copy pasta which is probably more than likely actually 🤔

Yeah I'll just move it to the base datum.

**Comment by Hughgent** [comment]
Stack trace is still calling 0 length timer with your PR merged locally. please solve

**Comment by Wayland-Smithy** [comment]
With the PR branch checked out or merged into master at the time of writing I am unable to cause a 0 timer stack trace with Plant Weeds. 

Can you please share the log and repro steps?

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
