### PR TITLE
Several small fixes and improvements

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
- Fix the autopsy scanner not having an icon. I took the one from old polaris, or old bay. 
- The hand labeler now goes in and out to signify if it is open or not.

image

- Increased the AI holopad notification noise
- Renamed the OB laser typepath to not have capitals
That might solve the AI notifications thinking all OB lasers are actually railgun ones.

- Fixed the AI carp holopad choice being called holo4

## Why It's Good For The Game
Fixes and small-ish improvements.

## Changelog

:cl:
qol: Increased the AI holopad notification noise
qol: The hand labeler now goes in and out to signify if it is open or not.
fix: Fixed the AI carp holopad choice being called holo4
fix: Fix the autopsy scanner not having an icon. I took the one from old polaris, or old bay. 
fix: Fixed Asphalt  being called aasphalt
code: Renamed the OB laser typepath to not have capitals
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
These could be atomized with better PR names

**Comment by lbnesquik** [comment]
Would be the case if they weren't fixes and QoL. There's no real reason any of those should be refused.

**Comment by Xander3359** [comment]
> Would be the case if they weren't fixes and QoL. There's no real reason any of those should be refused.

Yes that's true, but the title is very non-descriptive. It would make it harder to find this PR in the future but it's whatever, all small fixes.

**Comment by RipGrayson** [comment]
If you're doing small fixes, I would appreciate it if you would fix my typo in /turf/open/floor/plating/ground/desertdam/asphalt/autosmooth/alt.

**Comment by lbnesquik** [comment]
> plating/ground/desertdam/asphalt/autosmooth/a

Done

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
