### PR TITLE
Remove monkey cubes from shipside

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

I have been asked to do this at the behest of admins due to an entitled attitude when it comes to obtaining corrupted xenos as the new groundside eggs make it easier to get a monkey infected

## Changelog
:cl:
del: Removed monkey cubes from shipside
/:cl:

### CODE REVIEW

**Comment by adamkad1** [comment]
Bruh

**Comment by EvilMelonTheSecond** [comment]
Local researchers kill monki population by forceful impregnation of their entire stock.

**Comment by Ieteihowmee** [comment]
I have to ask, removing monkey cubes solves this how? Admins DO not have to make them corrupted, I have heard a few say they will not unless it is done properly. Why not just remove corrupted at this point without monkey cubes how are researchers expected to produce them? In another note, why even have researcher at this point?

**Comment by lbnesquik** [comment]
We are missing the discussion here, but to me, it seems like the problem is more with researchers having nothing to do rather than monkey cubes.

**Comment by gazzmaz4** [comment]
just give the medical researcher a job?

**Comment by EvilMelonTheSecond** [comment]
The problem as far as I understand is newbie researchers reading the wiki or hearing about corrupt xeno and then demanding it from admemes via ahelp rather than *pray. Surely a few ain't problematic but ss13 isn't easy to learn/understand and arguing with every new comer as to why they can't have the gimmick their role was "promised" sounds tedious.

**Comment by Ragecrabbo** [comment]
Might aswell remove researcher

**Comment by BraveMole** [comment]
> just give the medical researcher a job?

lel lel

**Comment by Naaanii** [comment]
Time to add CL on the chopping block too.

**Review by SplinterGP — CHANGES_REQUESTED** [review]
i want a headmin input on this please.

**Comment by lKiseki** [comment]
Yes. The idea is for players to adminhelp when they get eggs so that an admin may be aware that they're growing xenos shipside and so that they can keep an eye on it, since these are considered mini events for administration purposes.

**Comment by TiviPlus** [comment]
https://discordapp.com/channels/498569646014857217/500801682058379265/874360690398347294 @SplinterGP

**Comment by Ieteihowmee** [comment]
> Might aswell remove researcher

Agreed. Why even have it at this point. We all know it serves no other purpose at the moment since it lacks content.

**Comment by Ieteihowmee** [comment]
You know I had a thought, if using groundside eggs was the problem, why not just REMOVE them. What is the point of them we no longer have cap. Still mind boggling.

**Pull request merged**
