### PR TITLE
Module Name Changes

### PR DESCRIPTION
**Pull request by 567Turtle**
## About The Pull Request

Changes all instances of Arrowhead in the code (Besides changelogs) to Svalinn, does the same thing with Artemis but changes all instances of it to Heimdall.

## Why It's Good For The Game

Norse god modules are cool.

Svalinn blocked the sun with her shield, blocking part of its heat and keeping the world from burning.

Freyr was the god of summer... So like... This implies light... Warmth.. Uhh... Light sees dark... See through flashbang, I dunno somebody already took Heimdall

## Changelog
:cl:
add: Changed Arrowhead to Svalinn
add: Changed Artemis to Freyr
/:cl:

### CODE REVIEW

**Review by Lumipharon — APPROVED** [review]

**Comment by Al-1ce** [comment]
viking larping 
-1
cringe

**Comment by 567Turtle** [comment]
> viking larping -1 cringe

Tyr was the god of war 
Baldur the god of light 
Hodr the god of night who was tricked into shooting his brother Baldur with an arrow 
Mimir the god of knowledge who was a decapitated head
Valkyries were the angels who guided brave souls who died in battle to Valhalla
Surtr was the leader of the Fire Jotuns
Hlin was the goddess protection
Last but not least, Vali was the god of fertility, sun and rain.

You've been viking larping this ENTIRE time

**Comment by Joe13413** [comment]
powercreep!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Joe13413** [comment]
also theres another module stealing the name heimdall i think, its the flare launcher currently being PR'd

**Comment by 567Turtle** [comment]
FUCK uhh let me come up with something that isnt heimdall

**Comment by 567Turtle** [comment]
Alright I made Heimdall into Freyr because Heimdall was already in use by #12477

**Comment by hyper2snyper** [comment]
Leave typepaths alone, otherwise it'll break loadouts and such.

**Comment by Xander3359** [comment]
It's gonna break fucking loadouts AGAIN.

**Comment by 567Turtle** [comment]
> Leave typepaths alone, otherwise it'll break loadouts and such.

Sure, I don't see why not

**Comment by 567Turtle** [comment]
> It's gonna break fucking loadouts AGAIN.

Shouldn't break loadouts now that I've reverted the typepath changes

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
