### PR TITLE
Juicer, chem dispenser, chem master sprites port.

### PR DESCRIPTION
**Pull request by Blundir**
## About The Pull Request

Ports grinder sprite from [Yogstation](https://github.com/yogstation13/Yogstation/pull/9182) and chem master and chem dispenser (chem dispenser sprite was edited by me) from [Eris](https://github.com/discordia-space/CEV-Eris/issues/20).

## Why It's Good For The Game

Adds more visual consistency to other tg/bay like sprites, general refreshment from CM sprites.
dreamseeker_QPAA0w62cL
dreamseeker_OGMAmjFQ9W

Comparison of old ones and new ones.

## Changelog

:cl:
imageadd: ported chem master, chem dispenser, grinder sprites
imagedel: deleted old CM chemistry machines sprites
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
I don't think a booze dispenser and arcade machine look better than what we already have. Grinder is good though.

**Review by RipGrayson — CHANGES_REQUESTED** [review]
As mapper I'm in charge of both maintaining a coherent art style and making sure mapping sprites are distinct and easily identifiable at a glance.

The new chem dispenser here looks exactly like a soda dispenser.
delta7
Please change it, rest are fine.

**Comment by Al-1ce** [comment]
I think the new chem dispenser sprite should replace the soda dispenser sprite.

**Review by RipGrayson — APPROVED** [review]

**Comment by Blundir** [comment]
Gonna add some sprite non related changes, so gonna close it for now and redo the pr later.

**Pull request closed without merging**
