### PR TITLE
Robot hud port from RUTGMC

### PR DESCRIPTION
**Pull request by Blundir**
## About The Pull Request

Gives robots a distinct hud icon to differentiate it from humans.

dreamseeker_DTsC0VNtcW

Entire pr is a port of my autistic ideas from RUTGMC.

## Why It's Good For The Game

Firstly, it's extremely annoying to not understand what is in front you for a xenomorph, being castes like: defiler, carrier, praetorian is very annoying when you can't differentiate between robot and a human (especially when they look so alike after the armor resprite, in combat its hard to see a difference).

## Changelog

:cl:
add: healthud now has a robot icon for robots
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Robo indicator is nice because yeah, they function differently from humans but visually look extremely similar now.

The loss of health bar is a significant nerf to xenos for no particular reason though. Its purely a gameplay thing.

**Comment by ivanmixo** [comment]
Has to be visible to xenos or no bueno. Robots are already painful enough to fight.

**Comment by Aporhtonoma** [comment]
why is it not merged already?

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Blocking the xeno seeing hp change

**Comment by ClosetedSkeletonGH** [comment]
Robot health being unable to be seen by xeno’s is a massive balance change, it’s a large part of why AI droids and Iggy’s are still very powerful, it allows health bluffing and makes xeno’s have to risk dying for EVERY robo-kill due to lack of knowledge

this also doesn’t account for robo’s visual damage being able to be seen less on certain body types (ie brute damage is near invisible on blue, and burn damage is near invisible on yellow) and certain armors show robo damage more than others

**Comment by Pixelknightly** [comment]
Xenos should probably be able to see robot health.

**Review by spookydonut — CHANGES_REQUESTED** [review]
Same was what tivi said

**Review by ivanmixo — APPROVED** [review]

**Comment by Lumipharon** [comment]
on a semi related note, robot health should really reflect the closeness to death, as their lack of crit threshold means they are on flashing red for ages.

**Pull request merged**
