### PR TITLE
 shrike HP nerfed, shrike no longer has a 100 hp jump

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Shrike HP jumps to 425 for some reason, making it incredibly tanky. Not sure why. Could be a bug or a typing accident.

## Why It's Good For The Game
It's either a mistake or a huge weird jump.

## Changelog
:cl:
balance: Shrike now has 350 hp at ancient, rather than jumping from 350 to 450.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -4. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
Queen? Tanky?

lol

~but yeah, pull that shrike HP~

**Comment by Kuro-ai** [comment]
Agreeon the shrike change,it shouldnt be that tanky,the queen however should remain at 450 hp

**Comment by Max-023** [comment]
I disagree with the queen nerf as well. The shrike nerf is fine, but the queen is not really justified at all.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
