### PR TITLE
Adds CLF specialist to CLF ERT, and 2 guns for it.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Adds a CLF Heavy with 2 loadouts, one being the DPM machinegun, the other is the CLF heavy rifle which is a deployable anti armor rifle.

https://github.com/tgstation/TerraGov-Marine-Corps/assets/46353991/8803cfe9-dacf-4552-a7cc-073278686af0

https://github.com/tgstation/TerraGov-Marine-Corps/assets/46353991/e9437ed7-1aa2-40f6-975b-b066e56f3729
## Why It's Good For The Game
New CLF stuff. Though, they really still need a clothing redesign or whatever.
## Changelog
:cl:
add: Added new CLF heavy roles, and two new guns for it, which are the PTR anti tank rifle and the DP 'RP' machine gun.
/:cl:

### CODE REVIEW

**Comment by AnotherNobodie** [comment]
What about the LMG the SL gets? Could you give that to the CLF spec?

**Review by TiviPlus — APPROVED** [review]
kuro

**Comment by Joe13413** [comment]
holy based deployable anti armor rifle is based as fuck, i'd almost say i'd like to see that given to marines but i know the cancer that'd be

**Comment by yyzsong** [comment]
Add them to valhalla while you're at it.

**Pull request merged**
