### PR TITLE
Removes pouches, satchel from synth outfit

### PR DESCRIPTION
**Pull request by Neocloudy**
## About The Pull Request

Self explanatory, makes synthetics no longer spawn with pouches or a satchel on their character. The medium pouches they previously spawned with are now a vendor item and their toolbelt is a vendor item.
## Why It's Good For The Game

Many times synths will just throw these items away in favor of more useful items. As well, these items were already available in the synth vendor [or for the pouches are made available with this PR].
## Changelog
:cl:
del: Synthetics no longer spawn in with pouches or a satchel on their character. Their medium general pouch and tool belt are instead available in the synthetic vendor.
qol: The toolbelt and medium general pouch are now in the synthetic vendor.
/:cl:

### CODE REVIEW

**Comment by grinkgo** [comment]
just fyi the tool pouch does not include cable coil so if a synth doesn't loot it from their toolbelt they gotta get it elsewhere. Just a minor convenience issue.

**Comment by Neocloudy** [comment]
normally that wouldnt be much issue but if coil cant be found for some reason it _might_ need some looking into

**Comment by Al-1ce** [comment]
> normally that wouldnt be much issue but if coil cant be found for some reason it _might_ need some looking into

You can literally get infinite coil from the tool pouches dispensed by vending machines.
And you can use this to get an infinite amount of metal if you have an autolathe.
Just food for thought.

**Comment by Coastfront** [comment]
> > normally that wouldnt be much issue but if coil cant be found for some reason it _might_ need some looking into
> 
> You can literally get infinite coil from the tool pouches dispensed by vending machines. And you can use this to get an infinite amount of metal if you have an autolathe. Just food for thought.

Aren't there also iirc unlimited cable coils from the engineering vendor aswell?

**Comment by Losenis** [comment]
I'd argue against toolbelt removal because sometimes you can latejoin and immediately need to do something, IE fix power or replace medbay cell, with enough urgency that you don't really have time to gear up. This is rare but it does happen a few times.

**Comment by Neocloudy** [comment]
I'm bad at deciding so belt is just gonna get kept because of the rare situation where synth spawns in during hijack or skeleton shipside

**Comment by Lumipharon** [comment]
I'm not really sure what the point of this is. ALl non unga roles spawn fully equipped. If you don't want to use something just dump it. Otherwise as said if you need to do stuff as soon as spawning (or you don't particularly need any specific stuff) you're good to go.

**Comment by Neocloudy** [comment]
closed because I actually forgot why I made this pr

**Pull request closed without merging**
