### PR TITLE
Skill adjustments and additions

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Some skill changes, mainly in the backend.

1. Removed the funny MP cqc meme abilities (such as stunning people injecting them)
2. Made the melee skill (which only buffs melee with a WEAPON) give 15% per level instead of an insane 30%. Also a define instead of a magic number in 4 places or whatever.
3. Made specific gun skills (i.e. rifle/pistol/etc) give a 5% damage mod per level (above zero, it won't scale down). This is only available on a few ert roles like PMC and sectoids.
4. Added a stamina skill. This skill effects the time delay between using stamina and being able regen it again. It also effects the rate at which you recover stamina. Unused in this pr, but will pop up in campaign in the near future.
5. Captain no longer has Main Character skills in every single field.
6. Sectoids being small weak little grey men no longer have monsterous melee skills.

Plus some minor code tidyup.
## Why It's Good For The Game
Setting up skills to be more usable for upcoming changes.
## Changelog
:cl:
add: Added a stamina skill to boost stamina regen and stamina regen delay time. Currently not available to normal roles
balance: high weapon skills as seen on PMC and the like now provide a 5% damage boost per level with the appropriate weaponry
balance: Melee skill now adds +15% damage instead of 30% with melee weapons
balance: Removed some old MP CQC interactions
balance: Captain no longer has elite skills in basically every category
balance: Sectoids are no longer melee masters
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
nerfing cap skill is very stinky

**Comment by Lumipharon** [comment]
> nerfing cap skill is very stinky

cap being the head officers and having med skills of a doctor, engie skills of an engineer and weapon skills better than anyone in the game is what's stinky.

This basically just puts them in line with FO.

**Comment by Dikozda** [comment]
i mean the cap skills are good when you have a lack of other shipside roles, would be sad to see em go, weapons skills on cap tho are not needed

**Comment by DeltaFire15** [comment]
> cap being the head officer and having med skills of a doctor, engie skills of an engineer and weapon skills better than anyone in the game is what's stinky.
> 
> This basically just puts them in line with FO.

Captain is basically what shipside synth is except with the actual rules telling them they cannot deploy and even more limited in slots (always 1 as opposed to more 2 or more on high (40-60) - higherpop).
Captain should be able to effectively operate in roles that are not present, as this is already detrimental to groundside (no remote level 4 buffs & yelling) without them having to suffer with the penalties (or lower advantages of skill), already being limited in surgery skill (which can be very painful when *something* breaks the autodoc.

On the topic of gun skill, this only applies during either xenos stealthing to shipside via burst / alamo, or on hijack, during which the captain should be able to fulfil their, again, mandated order of going down with the ship, with whatever firepower is available.

Like, I do not get what this is supposed to achieve in the first place. Are captains stealing the work of CMO / MD? No, they are manning medbays completely lacking staff or having to supplement baldies in there. Are captains stealing the work of engineers? No, because the engineering work is either groundside, or they are helping reinforce SD because the engineers are dead or worse, and the synth's head is missing. Are they ungabungaing groundside? No, because they cannot deploy in the first place.
Are they a terragov army knife of a role? Yes. Does that make it a problem? Not really.

**Comment by Barnet2** [comment]
Nerfing captain skill is pretty questionable.

**Comment by coldironwarrior** [comment]
nerfing cap is not good; rest seems fine.
removing their SG skills or whatever, i don't particularly care about, but removing their pistol skill when they literally get a pistol as their personal weapon is really goofy. 

one question related to melee skills: with synth having a melee damage malus added more recently and if their skills were further halved with this, would that affect the amount of clicks it takes to do stuff like break weeds? the melee malus made that from a one-hit job with a machete to a two-hit job, and it's tedious and unintuitive. don't care about damage bonuses on mobs though. just am not sure if those damages are kept separate or not.

**Comment by ivanmixo** [comment]
> > nerfing cap skill is very stinky
> 
> cap being the head officer and having med skills of a doctor, engie skills of an engineer and weapon skills better than anyone in the game is what's stinky.
> 
> This basically just puts them in line with FO.

Thing is captain is supposed to be able to manage shipside by himself, unlike RO

**Comment by bowlofcereal** [comment]
the captain needs that skill to solo shipside since 90% of the time theres only an RO besides him shipside and maybe one MO, he has to normally solo the CIC, help RO and MO if they get bogged down, and load OB. cutting his skill is gonna make shipside tasks a nightmare because its not gonna stop the captain from trying to do it since he has too, its just gonna make me afk while im fumbling to do something

**Comment by Lumipharon** [comment]
He can still do all these things? I didn't remove the skills, its just not as super high anymore.

**Comment by ivanmixo** [comment]
This is gonna die if you don't atomise the captain change

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
