### PR TITLE
Priority change in shuffling

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

As a xeno: if you are on help intent, you will never be blocked by another xeno

## Why It's Good For The Game

No more body blocking. Maybe more shuffling hell, i think it's a fair price to pay

## Changelog
:cl:
qol: As a xeno: if you are on help intent, you will never be blocked by another xeno
/:cl:

### CODE REVIEW

**Comment by SkeletalElite** [comment]
The marine one seems like it will create a lot of FF issues since you can't avoid getting shuffled by ungas who dont know not to be on help intent in the fight.

**Review by SplinterGP — CHANGES_REQUESTED** [review]
the marine one is scuffed and will cause alot of FF

**Comment by turnop** [comment]
Note that this will also remove pushdragging entirely and make it much harder to secure kills as a result.

**Comment by BraveMole** [comment]
> Note that this will also remove pushdragging entirely and make it much harder to secure kills as a result.

No, this just ask the two xenos to be in harm intent rather than only one

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
