### PR TITLE
Various requisition supply additions

### PR DESCRIPTION
**Pull request by KaleRobe**
## About The Pull Request

Adds a corrupted xeno egg item and sprite, as well as the following changes to the supplypacks.dm;
-moved the straw hat to the clothing tab
-added a research crate, with a corrupted egg, monkeycube box and extinguisher, to the medical tab for 40 points
-renamed the supplies tab to the miscellaneous tab
-added a plush crate with one of each of the non-therapy plushies to the miscellaneous tab for 1 point
-added a roomba crate with 5 roomba's to the miscellaneous tab for 20 points
-added a pizza crate with one of each to the miscellaneous tab for 4 points
-added a supply tablet crate with one asrs tablet to the operations tab for 5 points

## Why It's Good For The Game

The research crate provides MR's with the ability to create a corrupted xenomorph hive without pestering admins. The Supply tablet crate allows for multiple players such as bored SO's or ST's to assist the RO while not having to run to to req anytime it is flooded with requests. The plush and pizza crates promote morale and nourishment levels in marines and ship personnel. Lastly the roomba crate is to ensure a safe and clean combat preparations area after the marines have deployed.

## Changelog
:cl:
expansion: Added a corrupted xenomorph egg
imageadd: Created a recolored xeno egg sprite for corrupted eggs.
code: Created a corrupted xenomorph egg
code: Duplicated and modified portions of egg.dm for the corrupted eggs.
code: Added ASRS tablets to the requisitions list.
code: Added pizzas to the requisitions list.
code: Added Roombas to the requisitions list.
code: Added Research crate to the requisitions list.
code: Added plush crate to the requisitions list.
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
this is cool.

**Review by BraveMole — CHANGES_REQUESTED** [review]
The game is not made for XvX, so it's a big no from me.

And please atomise this PR anyway, no reason to add a hat and XvX in the same PR

**Comment by KaleRobe** [comment]
Both straw hats and corrupted xenomorphs are aready part of the game, all I created was a means for medical researchers to be more than knock off doctors without having to annoy the admins.

**Comment by BraveMole** [comment]
They are not part of the game, they are admin only BECAUSE the game is not made for this.

That's why almost all of the time, admins accepting corrupted xenos are limiting the number, or making it shipside only

**Pull request closed without merging**
