### PR TITLE
Vali can load from pills

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
Applies to both harvester weapons and the armor module. The full pill is always consumed, even when there's only space for part of it.
## Why It's Good For The Game
Restricting chem gear from using the chem form marines are generally supplied with the most is kinda weird.
## Changelog
:cl:
balance: Vali armor and weapons can load reagents from pills
/:cl:

### CODE REVIEW

**Comment by bowlofcereal** [comment]
this is a good idea so vali doesnt have to spend an extra 10-15 minutes grinding pills in the grinder since its impossible to use the chem dispenser

**Comment by Arctrooper8** [comment]
Make it so vali can print pills too then pleas. Because otherwise you'd still need bottles to replicate more chems for the suit and sword.

**Comment by FosterGrime-Heymynameslouie** [comment]
> > this is a good idea so vali doesnt have to spend an extra 10-15 minutes grinding pills in the grinder since its impossible to use the chem dispenser
> 
> The general way to due it right now is have a canteen filled with tram and just drop pills in to dissolve in the canteen. Carrying tram in liquid form is.......... suffering

dropping pills into canteen dissolves it
WHAT, SINCE WHEN???

**Comment by KrabSpider** [comment]
> > > this is a good idea so vali doesnt have to spend an extra 10-15 minutes grinding pills in the grinder since its impossible to use the chem dispenser
> > 
> > 
> > The general way to due it right now is have a canteen filled with tram and just drop pills in to dissolve in the canteen. Carrying tram in liquid form is.......... suffering
> 
> dropping pills into canteen dissolves it WHAT, SINCE WHEN???

Always.

**Comment by Aporhtonoma** [comment]
ya all know you can use the advanced hypo to disolve pills (and load them without skill issue) right?(no need for fluids too)

**Comment by Arctrooper8** [comment]
> > Make it so vali can print pills too then pleas. Because otherwise you'd still need bottles to replicate more chems for the suit and sword.
> 
> What do you mean? You can get pill packets from the marine med vendor in unlimited quantities. 1 packet (small item) = 8 pills = 120u = 24 chem-charged attacks with a harvester weapon.

With bottles you can deposit green blood into them and if they mix with any of the three basic chems used by the sword it'll replicate more chems. I know pills are basically as prevalent as air on the ship and you can carry a small pharmacy amount on you, but it'd still be nice to have pills be equivalent to bottles in terms of functionality.

**Comment by Lumipharon** [comment]
> > > this is a good idea so vali doesnt have to spend an extra 10-15 minutes grinding pills in the grinder since its impossible to use the chem dispenser
> > 
> > 
> > The general way to due it right now is have a canteen filled with tram and just drop pills in to dissolve in the canteen. Carrying tram in liquid form is.......... suffering
> 
> dropping pills into canteen dissolves it WHAT, SINCE WHEN???

for the past like, 12 years of ss13 baymed lol

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
