### PR TITLE
Adds more reqtorio ammo production for req gear.

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
Adds Mateba speedloaders, railgun magazines, and standard scout rifle magazines to the list of producable ammo types that req factory can create.

**PR created for Araulius**

## Why It's Good For The Game
Gives req more to do. has a high buy in cost to set up, but produces more ammo cheaper, than it would be to just buy the ammo, once the production line is set up. Marines would probably use the fancy shmancy toys more, if the ammo was available. Costs for production line refills are up for debate. the idea is that it costs at least 50% less to produce, than it is to buy in bulk. rewarding factorio RO players for investing in the high buy in cost to set them up.

## Changelog
:cl:
add: Mateba speedloaders, scout rifle magazines, and railgun magazine factorio refills are now available through cargo. Please don't blow anything up. 
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
You have to replace spaces indentations by tab

**Comment by Araulius** [comment]
I balanced the pricing on the refills, and the amount they refill based on cost of individual items of ammo that currently exist.

Current prices for individual ammo:
Mateba speedloader = 3
Railgun Mag = 3
Scout rifle = 5

the refill stats are:
mateba refill costs 20, and produces 30 speedloaders. (because they are 6 shots per, and not really high impact for the amount they cost individually.
Railgun Mag refill costs 20, and produces 20. 3*20 = 60. so you get 3 times point efficiency if you set up production instead.
scout rifle refill costs 50, and produces 20. 5*20=100. so you get double point efficiency, assuming you set up the buy in costs for production.

**Review by hyper2snyper — APPROVED** [review]
The factory must GROW.

**Pull request merged**
