### PR TITLE
Added Automag Attachments

### PR DESCRIPTION
**Pull request by AvalonHunter**
Highpower Automag (9mm) can now take all default pistol attachments

:cl: 

tweak: Made Highpower Automag(9mm) able to take every attachment a standard M4A3 can take

/:cl:

[why]: Enabling of attachments should allow more usability of Highpowers looted planetside. Will potentially assist survivors if they can find an armory that has attachments, but mostly will benefit Marines dissatisfied with standard sidearm options.

### CODE REVIEW

**Comment by Rohesie** [comment]
Have you tested this for sprites? How do they look?

**Comment by AvalonHunter** [comment]
https://i.gyazo.com/1082837a4e5e00093e43ac46d6cf2737.png
https://i.gyazo.com/c61d45278d0e6f3fae921b57a5746ac7.png
Rail and barrel attachments seem to be fine, but underbarrel attachments are maybe shifted slightly too far left. BFA is alright, but the laser in particular looks a little bad.

**Comment by Rohesie** [comment]
Tweak the `attachable_offset` to make it look good, and leave out any attachment that is not aesthetically compatible.

**Comment by AvalonHunter** [comment]
Adjusted the underbarrel offset forward 2 pixels (16 to 18) and I'm pretty comfortable now with how both the BFA and laser look. 
https://i.gyazo.com/145ee648b2ee9c5ad6200b54eac9ce79.png
https://i.gyazo.com/a9b44a924891b98711b49710ea0fb165.png

Did not change any of other offsets, as those all seemed fine as is

**Pull request merged**
