### PR TITLE
new crosshair 

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
new mouse pointer stuff

https://github.com/tgstation/TerraGov-Marine-Corps/assets/98577688/cbd610ac-ac78-49a8-9616-2ba0484709e7
## Why It's Good For The Game
simpler and easier to read
## Changelog
:cl:
qol: different gun types have different crosshairs
fix: semi auto guns have crosshair when clicked now
imageadd: new crosshairs
code: use update mouse pointer proc instead of initial
/:cl:

### CODE REVIEW

**Comment by theta891** [comment]
can you make a setting that allow us to change its color? i fine green chrosshairs better then white

**Comment by Losenis** [comment]
I'd rather have it be a triangle like the normal cursor on normal usage because there's a good chunk of things you have to pixelhunt, like tactreloading or just grabbing something out of a pile of 20 objects in the same tile.

**Comment by Losenis** [comment]
Wait is it even CENTERED AT ALL?
image

**Comment by Strayed-Raven** [comment]
personally I do not mind the crosshairs when you are shooting a gun on full auto or something. That old one needed to be done better than what we currently have. But for regular mouse clicking and dragging I am just gonna override that.

**Comment by iLikeMemes** [comment]
This should probably be something that can be enabled/disabled in the options.

**Comment by chizzy376** [comment]
Why not let us color it? This is extremely bad for visibility

**Comment by Pinkufeck** [comment]
make it be a preference option and i don't care.

**Comment by novaepee** [comment]
> make it be a preference option and i don't care.

already is

image

**Comment by Kapu1178** [comment]
I really dislike this and I think it actively worsens the new player experience.

**Comment by Burger1998** [comment]
make this off by default

**Comment by MisterBomb7** [comment]
I like the crosshair appearing while using guns, but the dot should not replace the cursor outside of lobby.

**Comment by Lumipharon** [comment]
Even when I turn off the new cursor, it causes constant cursor flicking for whatever reason.

**Comment by novaepee** [comment]
Now people can't disable custom cursor.

**Comment by Strayed-Raven** [comment]
After trying this out. It is superior to completely cut it out to make it back to normal. Will continue to do this until this is made a preference because a users OWN CUSTOM cursors are far superior to this.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
when you're shooting the gun its fine, but the white dot instad of a normal cursor is really not, its hard to see when theres a lot going on and its too small, just put the normal cursor back in in non shooty mode

**Comment by tyeagg** [comment]
> when you're shooting the gun its fine, but the white dot instad of a normal cursor is really not, its hard to see when theres a lot going on and its too small, just put the normal cursor back in in non shooty mode

thats been removed decades ago

**Comment by chizzy376** [comment]
Even when you disable the custom cursor (Like it should be), the new aiming cursor remains which is a bug

**Review by Kuro020 — APPROVED** [review]

**Comment by Lumipharon** [comment]
@tyeagg what's happening with this?

**Pull request closed without merging**
