### PR TITLE
LV map update by shiryu

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request
Updates LV map with some stuff, making LZ1 better by making it more open on the other sides, allowing Marines to go out and flank xenos attacking and etc. reducing ability of FOBCamp, while also making LZ1 easier to breach if marines are losing, brings back more usability of MINIFob's or no entire FOB on it, changes to LZ2 and some map jungle-ishness brought back, Will ask Shiryu to post images here.

## Why It's Good For The Game
updates the map 

## Changelog
:cl: SplinterGP, Shiryu.
tweak: LZ1, LZ2 and other stuff changed on LV
/:cl:

### CODE REVIEW

**Comment by Nigkgro99** [comment]
I'm not a big fan of the floodlight spam. I also don't like the pointless bloat room that just has two useless vendors and a table in it. Remove that and I think it'll be okay.

**Comment by EvilMelonTheSecond** [comment]
LZ2 is unusable. Breach points in all directions, west is literally undefendable with its proximity to the alamo and north is suffering from the same. Give me the space Big Red LZ's have if you want to have this many breach points.

**Comment by SpaceLoveSs13** [comment]
We just had a playtest round with new LV map on LZ2. I found few issues that I feel like should be noted:

1. Way too many flanks. It overall makes people sit in FOB making cadehug more forceable. Plus it is hard to manage that many flanks when Alamo is at the center and there are narrow paths to go to other sides.
2. Why is there a west flank through jungle/dense jungle? It makes no sense.
3. North east rooms needs update. They look too much of a maze.

**Comment by Losenis** [comment]
"allowing Marines to go out and flank xenos attacking", be aware that the marines have a harder time flanking than xenos by needing more numbers, so this is the inverse, IE xenos having more flanking opportunities than marines due to the openings. Most times I've seen marines attempt to go there to flank, it resulted in inevitable death where their bodies were not recovered because it'd be suicide to try save them while getting dragged away in crit. With a boiler or defiler gas, it's even more suicidal to enter a chokepoint xenos can shuffle you in.

**Comment by David-Stormwell** [comment]
God please remove this, I don't wanna vote for LV anymore if I'm a Marine.
Problem is how as said before most likely is how it actually does the opposite of what you want, more FOB camping. There's more places that need to be guarded and thus more flanks xenos can breach from.

**Comment by SplinterGP** [comment]
update incoming

**Comment by TiviPlus** [comment]
Closing as stale

**Pull request closed without merging**
