### PR TITLE
harnesses and harness type stuff have 6 light range

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Harness (and thus stuff like cowboy jacket) has 6 light range.
## Why It's Good For The Game
You have 0 armor. This is basically baldur range so.
## Changelog
:cl:
balance: harness and unarmored leather jackets have 6 light range.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Hear me out. Give it to the boomvest as well.

**Comment by novaepee** [comment]
> Hear me out. Give it to the boomvest as well.

Boomvest inherits from harness, therefore boomvest will get buff as well.

image

image

**Comment by Lumipharon** [comment]
Same light as normal armour, not better.

**Comment by Losenis** [comment]
>Same light as normal armour, not better.

It'd have identical stats to jaeger exoskeleton without armor plates + baldur, though. Remember that baldur is essentially a free module given it has 0 slowdown.

**Comment by SilencedMP5A5** [comment]
baldur actually gives 9 light range iirc

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
