### PR TITLE
Research rework (Marine Psionics)

### PR DESCRIPTION
**Pull request by SiegeB0t**
## About The Pull Request

This PR copies over protolathe code to allow researcher to produce the items they want on ship using psionic materials extracted from xeno autopsies and refined in the research tube. The xeno material will still be sellable on asrs, but the value will be nerfed to encourage research item production.

Going with the theme of psionics, this PR will add two items. One is a translator module which will allow a marine to talk to xenos. The other is a levitator item which makes crates easy to pull.

My take on marine psionics is that they should be less powerful than those of the xenos, but they should be more fine tuned. A marine should not be able to create a massive knockback push like a shrike but they should be able to move a crate faster. In the future I would like to add a pyromancy helmet module and a psionic shade helmet module that allows a marine to teleport like an adept from starcraft2.

**Input on balance is appreciated.**

###Progress
- [x] add protolathe to ships
- [x] refactor current research code to produce psionic precursor materials with the BEPIS toob
- [x] allow protolathe to store psi points and green blood
- [x] move item production to protolathe
- [ ] create tgui for protolathe
- [ ] create universal translator helmet module
- [ ] create crate levitator item
## Why It's Good For The Game

Research right now is not particularly rewarding and is rarely done. Only 50% of games use the research tube, and even fewer actually see the items generated by the tube used. The biggest problem is the randomness of the item rewards. The only item that can be reliably generated is the blood implanter which is nearly useless when marines have isotonic pills and nanoblood.

Research would be better if items are produced deterministically.
## Changelog
:cl:
balance: Makes research item production deterministic.
balance: Moves research item production to ship.
balance: Nerfs research credit production.
add: Adds protolathe to ship that can produce items based on xeno psionics and blood.
add: Adds a translator helmet module to research recipes.
add: Adds a crate levitation item to research recipes.
/:cl:

### CODE REVIEW

**Comment by MereWalker** [comment]
You just made my admin nightmare... draws via negotiation. Time to revise the rules I suppose. That is if you keep the translator.

**Comment by ThelastArchiver** [comment]
> 

this would be incredibly cool

**Comment by FIXTHERADBOXPLEASE** [comment]
Psychic RO telepathically levitating all crates across req buff? The future is here.

**Comment by Derrick2Electricboogaloo** [comment]
Okay,  now this is a neat idea. I always though we should use the protolathe for something research related.

**Comment by Losenis** [comment]
>Teleporting marines
As if jetpack and wraiths weren't cancer enough

**Comment by SiegeB0t** [comment]
> As if jetpack and wraiths weren't cancer enough

This style of teleport is not defensive since the user is stationary while casting the projection. It only adds mobility to get to flanks faster. However if you are the only marine teleporting, you just brazilled yourself making this kind of teleport punishable.

I'll figure out the balance when I get to it.

**Comment by KerbalCitizen** [comment]
Translator and levitator just don't seem very useful imo. Synths or AI can speak with xenos already, but I rarely see it used. Levitator might be useful if it applies to things other than just crates, like xeno corpses or marines, We already have bike which lets you drag stuff quickly, but it doesn't get used that often, although you could blame it on its fuel usage, possibility of breaking, and being a dense object (blocking other marines). You can powerfist dead xenos to move them quickly, but I've only seen this once. 

Overall, I just feel like these psionic items won't be that useful or seen that often. Not enough details about the pyromancy or teleportation for me to say much about them.

**Comment by SilencedMP5A5** [comment]
do we get to raise permadead marines as weak zombies like sectoids in xcom2

**Comment by SiegeB0t** [comment]
I think someone should build a xeno caste that reanimates perma dead first. It would be decent compensation for loss of cap gameplay.

**Comment by Aporhtonoma** [comment]
*psychically levitates while propaganda from jojo battle tendecy can softly be heard on the air*

**Comment by Losenis** [comment]
image

**Comment by Lumipharon** [comment]
> I think someone should build a xeno caste that reanimates perma dead first. It would be decent compensation for loss of cap gameplay.

Pay someone to make a new xeno sprite and I'll code it. I was already thinking about a necro caste.

**Comment by Derrick2Electricboogaloo** [comment]
> I think someone should build a xeno caste that reanimates perma dead first. It would be decent compensation for loss of cap gameplay.

That was a thing a long time ago. I think Hivemind or something could/would turn dead bodies into husks.

**Comment by Derrick2Electricboogaloo** [comment]
Sad, hope this PR gets re-visited.

**Pull request closed without merging**
