### PR TITLE
Buffs Marksman bullet by 5 damage

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

Literally the title. Mostly intended as a buff for BR, but after talking with Splinter this was agreed upon instead. 

## Why It's Good For The Game

Both DMR and BR are not super strong, BR especially. This should help them slightly be a bit more impactful for being such slow firing weapons. 

## Changelog
:cl:

balance: Marksman bullets do 5 more damage, mostly impacting the Battle Rifle and DMR

/:cl:

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
hol up

battlerifle not strong? 

nah dog the DMR and BR are the best raw DPS RIFLES marines have, you just need to hit your shots

**Comment by RenGusta** [comment]
BR stinky due to shared falloff, reduce damage malus by like 5-10% to compensate for lower base damage

**Comment by Hekzder** [comment]
> BR stinky due to shared falloff, reduce damage malus by like 5-10% to compensate for lower base damage

I'm not opposed to this, it's what I originally wanted to do. Kind of just depends what maintainers say. I was thinking an increase of damage mult from 50% to 60%, resulting in a net +12 damage to the BR combined with the overall damage buff, from 30 to 42. 

But really my biggest concern is the BR, I think the DMR is _generally_ fine where it is. Splinter just suggested this and I believe any buff for the BR is better than no buff. I am a bit wary of a potential 12 damage increase.

**Comment by TiviPlus** [comment]
I approve of what ocelot said

**Comment by SplinterGP** [comment]
i mean what ocelot said is actually not true, the most raw DPS one is the T-12 with 125 DPS, the T-64 only has 90 DPS

**Pull request closed without merging**
