### PR TITLE
dmr/br nerf

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
nerfs the dmrs and BRs damage minorly.

## Why It's Good For The Game
marine man win lots. DMR strong. MJP nerf DMR/BR. 
BR gets nerfed because its theoretically pretty stronk.
DMR gets nerfed because its literally the best marine gun lol

## Changelog
:cl:
balance: dmr does 2 sundering and 65 damage from 70. BR does 32.5 from 35
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -21. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by David-Stormwell** [comment]
I will make marines suffer before sunder

**Comment by Kuro-ai** [comment]
Necessary sacrifices

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-25). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
