### PR TITLE
Adds handholding.

### PR DESCRIPTION
**Pull request by DominikPanic**
The slipper slope just keeps getting worse and worse...

If you and your target are both human and you have hands selected when you start pulling them, it will give you a "X has grabbed Y by their hands!" instead of "passively!"

### CODE REVIEW

**Comment by MoXuT0** [comment]
Cursed

**Comment by Ketrai** [comment]
Perish

**Comment by factoryman942** [comment]
image

**Comment by Arachnidnexus** [comment]
🤔

**Pull request merged**
