### PR TITLE
turrets have less max health and 100 less health on spawn

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
1500->1250
should be one less grenade to kill and 1 t-12 magazine to kill at point blank range at full health rather than one and a half.

## Why It's Good For The Game
Turrets are a bit too resistant to everything right now, in the opinion of me and several other people, so I think this is fair.

## Changelog
:cl:
balance: resin turrets have 1250 max hp from 1500, 500 on spawn rather than 600
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
Make it allow limited amounts on the alamo/crash phase instead

**Comment by SilencedMP5A5** [comment]
reopen this

**Comment by Al-1ce** [comment]
keep it closed

**Comment by SpaceLoveSs13** [comment]
Keep this closed. "Others agree with this opinion" is not a valid reason. Regardless, turrets can still be very easily killed, especially when marines are not there. So turrets should have good HP to protect an area until marines reach there.

**Comment by SplinterGP** [comment]
> 
> 
> Keep this closed. "Others agree with this opinion" is not a valid reason. Regardless, turrets can still be very easily killed, especially when marines are not there. So turrets should have good HP to protect an area until marines reach there.

those are xeno turrets not marines

**Pull request closed without merging**
