### PR TITLE
Sow for all

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Adds Sow (xeno flowers) ability for every **builder** caste as their **primo** ability.
Hivemind gets it as a base ability since he has no primo rank.

## Why It's Good For The Game

I believe that Sow is very well designed and perfectly balanced ability. Adding it to more castes as a primo ability expands building complexity and adds more gameplay options while not contributing towards powercreep.

## Changelog
:cl:
add: Added Sow as primo for Drone, Queen, Shrike. Added Sow as a base ability for Hivemind.
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
Ah yes the instant blood/rage refill , sunder full heal and regular full heal fruit available roundstart with hivemind.
Also that make the hivelord primo be just strong acid which is very underwhelming even accounting for the fact that hivelord kit is goated.
Anyway speedmerge that PR it’ll be funny.

**Comment by blackdav123** [comment]
> Ah yes the instant blood/rage refill , sunder full heal and regular full heal fruit available roundstart

ravagers cant use the plasma plants, the sunder fruit only heals 30%, and the heal fruit only heals 50%.
if gorgers are able to use the plasma plant then that is an oversight and nobody would object to fixing it

**Comment by Joe13413** [comment]
yo dude uh aren't the point of primos to be unique abilities available to castes who've survived a long time? adding this ability to EVERY builder caste as their primo completely breaks the idea of primos. basically, PR is dumb and stupid and i HATE IT!!! ujghfisujngfiudsgnsf

**Comment by Jackal-boop** [comment]
i like this

**Comment by bowlofcereal** [comment]
why are you giving multiple castes a primo when the idea of primo is that they are unique to a caste

**Comment by Waselon** [comment]
> why are you giving multiple castes a primo when the idea of primo is that they are unique to a caste

Nothing stops us from expanding and/or modifying the original idea if that makes the game better

**Comment by TiviPlus** [comment]
What bowl said, come back when you have a replacement primo

**Comment by Victor239** [comment]
Maybe give each builder **one** flower but it be a slightly enhanced version, whereas the original primo allows all three but it is normal strength. Also perhaps a frenzy plant for Hivemind.

**Pull request closed without merging**
