### PR TITLE
Adds the Heat lens to the M43 lasgun

### PR DESCRIPTION
**Pull request by Hughgent**
## About The Pull Request

This is another lens attachment for the lasgun. sets things on fire.

## Why It's Good For The Game

Adds some versitility to the lasgun in that it can set xenos on fire on overcharge mode.

## Changelog
:cl: Hughgent, Kuro
add: M43 Heat Lens is now available for the lasgun. Set your foes ablaze!
/:cl:

image

### CODE REVIEW

**Comment by Pariah919** [comment]
The attachment description should state it has less penetration than the regular shot aswell.

**Comment by Hughgent** [comment]
image

**Comment by Rohesie** [comment]
No fire delay reduction?

**Comment by Hughgent** [comment]
Do you mean on top of the 1/second fire rate of overcharge in general?

**Comment by Rohesie** [comment]
Alright, we'll test this for balance.

**Pull request merged**
