### PR TITLE
New Map: Gelida IV [MDB ignore]

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Ports and modifies the LV522 map currently being tested by CM. Approximately 2/3rds of this map was made by a talented mapper [spartanbobby](https://github.com/spartanbobby) with contributions from the rest of the CM team.

Continuing a tradition from the last CM map I ported, I'm going to preemptively answer some questions that I'm sure you'll have.

**Q**. Can we do this?
**A**. Yes. This map actually uses only a handful of CM graphics, which is why it's been re-themed. As a bonus it's not in the Alien™ universe owned by Disney so we're less likely to get sued. As a courtesy, I will not have this map merged until the CM map this map is based on has also been merged for about a week.
**Q**. Gelida IV is a dumb name can it be *insert cool spess name here* instead?
 **A**. Yes, propose a new better name and I'll rename it if it's better.
**Q**. I want to play survivor, it's what the CM LV522 is all about, can I do that here?
**A**. Not unless you're willing to recode the survivors to meet maintainer standards.
**Q**. How many ports of CM maps do you plan to do? This is your 3rd one, and the other 2 weren't all that great anyway.
**A**. As many CM maps as can be feasibly ported without giving me a headache. This one is the simplest map I've ported so far, with the simplest flow, that means adjusting it is far simpler than say Chigusa.
**Q**. What's the size of this thing?
**A**. 175 * 220, which is the same size as LV624, but flipped on its side. In the event it's still too large I'll probably take a crack at reducing it further. Compared to other ports, shrinking it should be quite a bit simpler.

maze2

## Why It's Good For The Game

More maps and more variety good.

## Changelog
:cl:
add: Added Gelida IV, a new map based off of CM's WIP LV522 map.
imageadd: Created some new icons for use in Gelida IV.
imageadd: Ported a handful of new icons for use in Gelida IV, mostly from CM.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Neat

**Comment by FosterGrime-Heymynameslouie** [comment]
I refuse to believe this is the same size as LV
this is l a r ghe

spede mrhge

**Comment by BraveMole** [comment]
Link to orig PR ?

**Comment by RipGrayson** [comment]
> Link to orig PR ? 

https://github.com/cmss13-devs/cmss13/pull/797

>Looks neat, map name is ew.

Map name is changeable, would like suggestions though.

**Comment by Weedmaster77** [comment]
I like the look and has no river that cut it in half that's a plus. Also tons of buildings instead of open land, which I think is cool and something different.

**Comment by Edelor68** [comment]
Name suggestions:
Corporate/Nanotransen Rim/Forward Base/Colony/Outpost
Pick and chose as you like.

**Comment by TiviPlus** [comment]
Added to config

**Comment by Al-1ce** [comment]
Comms don't seem to work at roundstart.

**Comment by Lumipharon** [comment]
TM'd at the moment, apparently the comm relay was missing or melted?

**Comment by MLGTASTICa** [comment]
Was TM'ed , there is no bluespace relay mapped in . Also the randomly bolted/welded doors round-start are a massive headache for xenos.
As for a better name , could be named Icestorm facility 2

**Pull request merged**
