### PR TITLE
Replaces the HE rockets in the seasonal operations recoilless rocket bag with LE rockets

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Replaces the HE shells in the seasonal recoilless rifle bag with LE shells.
## Why It's Good For The Game
Currently, the seasonals give the recoilless rifle 10 HE shells. Considering this can easily take down a queen in 2 shots, this seems rather excessive, especially for free. This effectively reduces the total amount of HE shells to 4, and the LE shells to 10 for the seasonals.
## Changelog
:cl:
balance: Replaced the HE shells in the seasonal recoilless rifle bag with LE shells. Non-seasonal variants untouched.
/:cl:

### CODE REVIEW

**Comment by AwkwardStereo** [comment]
LE rockets do more damage than HE.

**Comment by Wisemonster** [comment]
In what way? Cause I tested this in valhalla, LE rockets do 1/3rd of a queens health, meanwhile HE slightly less than 1/2

**Comment by ivanmixo** [comment]
This is pure kneejerk, these rockets are literally fine. Sure two of them can one shot a queen but have you considered how fast they can be fired at all? Come on.

**Comment by AwkwardStereo** [comment]
> In what way? Cause I tested this in valhalla, LE rockets do 1/3rd of a queens health, meanwhile HE slightly less than 1/2

i am rarted and wrong, its quite shrimple

**Comment by Mrrpip** [comment]
> This is pure kneejerk, these rockets are literally fine. Sure two of them can one shot a queen but have you considered how fast they can be fired at all? Come on.

> Two of them can one shot a queen.

**Comment by yyzsong** [comment]
> > This is pure kneejerk, these rockets are literally fine. Sure two of them can one shot a queen but have you considered how fast they can be fired at all? Come on.
> 
> > Two of them can one shot a queen.

dodge.

**Comment by Wisemonster** [comment]
> This is pure kneejerk, these rockets are literally fine. Sure two of them can one shot a queen but have you considered how fast they can be fired at all? Come on.

I was more focused on the fact that there's 2 of em roundstart, and that this get's especially bad in the narrowier parts of maps.

**Comment by Lumipharon** [comment]
I don't see the issue. If TWO people that both have RR's, both hit  you at the same time with rockets uh, thats great. One person isn't 360 noscoping a queen with two rockets themselves.

**Pull request closed without merging**
