### PR TITLE
Rise of the Ubermensch

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Updates human sprites from flat potatomen to gigchads. Thanks to GregorMN for the amazing new sprites.
image

Some comparison shots of the old sprites vs the new:
image

image

Resprites of clothing to come, but here's a preview of what you can expect.
image
## Why It's Good For The Game
Remove weedy manlets, welcome ubermensch
## Changelog
:cl:
imageadd: Human mob sprites have been brought into the future
/:cl:

### CODE REVIEW

**Comment by Strayed-Raven** [comment]
These look like XCOM 199X sprites. I had to say it.

**Comment by AGasCanister** [comment]
>TGMC marines more muscular than CM ones
CM has fallen, the winner is clear

**Comment by Losenis** [comment]
The final piece in the full sundowner build
image

**Review by Kuro020 — APPROVED** [review]
should've made the female boobs bigger tbh

**Comment by Al-1ce** [comment]
These new sprites are great.

**Comment by David-Stormwell** [comment]
> should've made the female boobs bigger tbh

my thoughts exactly

**Comment by FosterGrime-Heymynameslouie** [comment]
GREGOR AT IT AGAIN

BLESS HIS EXISTANCE

**Comment by Oscari-pog** [comment]
Add customizable boobs

**Comment by FIXTHERADBOXPLEASE** [comment]
They look like my X-Com dudes. 10/10.

**Comment by RaidarV** [comment]
KVNV VND SVVL

NVW VDD BVVB SLVDVRS !!

**Comment by chizzy376** [comment]
crotch and boob size sliders?

**Review by TiviPlus — APPROVED** [review]

**Comment by novaepee** [comment]
Next week, I will work on rolled uniform so that marines could see their chiseled body.

image

**Comment by Al-1ce** [comment]
> Next week, I will work on rolled uniform so that marines could see their chiseled body if this PR gets merged.


You... do realize this is already a feature, right? If you enable right click and RMB on a jumpsuit, you'll be given the ability to roll it down.

**Pull request merged**
