### PR TITLE
Allow rclick to immediately draw from storage

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request
title

## Changelog
:cl:
qol: Right click can now be used on storage items to immediately draw the topmost item
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
i honestly wished it'd just open the storage independent of item on hand, theres already alt click to pull from storage

**Comment by TiviPlus** [comment]
alt click sucks to use

**Comment by Dolth** [comment]
Can middle mouse work too?

**Comment by David-Stormwell** [comment]
> Can middle mouse work too?

^
If middle click could work as well it'd be a beautiful qol

**Pull request merged**
