### PR TITLE
Heisennaught

### PR DESCRIPTION
**Pull request by MsSeraph**
## About The Pull Request

Basically adds a massive warship as a shipside map. So that wins a few awards, including but not limited to: First 3 z level map, First water shipside map, First map with coloured lightning. First shipmap map with exterior exposed areas

## Why It's Good For The Game

Adds more variety and such, there's not too many shipside maps.

## Changelog
:cl:
add: Added Heisennaught, TGMC's naval vessel
add: Added the decorative props that came with it
/:cl:

### CODE REVIEW

**Comment by MsSeraph** [comment]
Temporarily closing as im DUM DUM who forgot the briefing shutters were to be open from the sgart

**Comment by sunofang** [comment]
Needs ALOT of tweaking and polish. But its a funny idea!

(Cant wait to see powergamers die to space)

**Comment by jroinc** [comment]
You know space *or* lack of pressure instakills currently, right?

Move into a depressurized tile and you instadie.

**Comment by Ragecrabbo** [comment]
More ship variety good
Still needs more work and testing though and im personally not a fan of the piss colored lights in the lower deck but would love to see this eventually played around with many people

**Comment by sunofang** [comment]
> 
> 
> You know space _or_ lack of pressure instakills currently, right?
> 
> Move into a depressurized tile and you instadie.

Only areas marked as space. As the atmos system is fully removed.

**Comment by SpaceLoveSs13** [comment]
Some issue I have noticed.

1. Way too many railguns
2. Way too many fuel and Ob shells.
3.  Requistion needs to be on the same level as OB/railgun.
4. Needs more ladders.
5. Open hull ship can end up really bad and a headche for us admins as people will repeatedly walk into SPACE tiles accidentally or unknowingly and it's not good design to allow that.
6. How are marines supposed to access requistion at the east from west when the entirety of the area is closed off by SD shutters?

**Comment by MsSeraph** [comment]
piss lights piss lights piss lights!
Now its on sea, which means its on a planet, which means its got an atmosphere. This ship is close and headed for the operation location (the ground map), which has a habitable atmosphere, thus the atmosphere around the ship is habitable too

**Comment by MsSeraph** [comment]
> Some issues I have noticed.
> 
> 1. Way too many railguns
> 2. Way too many fuel and Ob shells.
> 3. Requistion needs to be on the same level as OB/railgun.
> 4. Needs more ladders.
> 5. Open hull ship can end up really bad and a headche for us admins as people will repeatedly walk into SPACE tiles accidentally or unknowingly and it's not good design to allow that.
> 6. How are marines supposed to access requistion at the east from west when the entirety of the area is closed off by SD shutters?

1: those were swapped for decorational thingies
2: they are the same as POS. You see, POS stacks more than one thing per rack, while my map stacks 2 at most. I personally counted all fuel tanks and they were perfectly the same as POS
3: dam u rite
4: same as 3
5: there's guard rails to stop this on the upper deck, and you'd have to have 4 second input lag to fall off in command deck. Falling into space is also meant to be part of command deck fighting on this map
6: forced briefing. Basically, marines have to pass by briefing to get to req or hangar, allowing for a briefing to be held since otherwise you only have 3 out of 40 people show up. These shutters are open shift start tho, but i placed SOs closer to the button than marines

**Comment by AnCopper** [comment]
Areas exposed to space are a terrible idea and I wouldn't be surprised if it against mapping guidelines, any mob that steps onto a space tile will instantly die and become unrevivable, and atmos is disabled so it just looks weird.

**Comment by MsSeraph** [comment]
Specifically for this map i wanted to add a chance for the high risk thing of space combat
Then i swapped space combat for water combat
Basically there's sea tiles, so the place is infact on a planet, thus pressurized hence why you can walk around, but sea tiles kill you via drowning you in the weight of your gear

**Comment by lbnesquik** [comment]
I hope it works out, i'd love another ship map

**Comment by Tristan63** [comment]
If its a big ship map, what if the entire op takes place on the ship itself!

**Comment by MsSeraph** [comment]
Its as long as theseus but not as wide tho, so

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Please adress or fix the following:
1)Snaking corridor on bottom floor
2) Excessive space and gun props on the second floor
3) giant seperating shutter wall on the bottom floor?
4) water
5) accessible space on the top floor
6) top floor halway of death at the ladders
7) drop pod bay is far away from other drop possibilities?
8) Possibly prefillable sandbags on the obstacle course on the bottom floor
9) Prespawned turrets on he hull of the ship are not ok unless those are props

**Comment by MsSeraph** [comment]
1: pretty sure that's maintenance
2: should i fill it with stuff?
3: that's on purpose to force marines to go to briefing or be unable to use the dropship or req
4: its meant so because its meant to be a boat
5: that's also meant to be like that for the map's gimmick
6: there's several other ladders to take that aren't as exposed
7: its meant to be the only way to get groundside if the briefing shutters are down, that way griefers can't infinitely delay drops
8: oof u right
9: makes sense, i'll turn them into props

**Comment by TiviPlus** [comment]
1) it is maintennce but it's horrible the south one is much better
2) You should probably make it much smaller if I'm honest
3) I'm not sure that is a good idea
4) We are in space
5)Space instantly kills you
6)I only see the hallway ones and one space ladder
7) we will see

Also consider adding a default value for popcaps for when this is tm ready

**Comment by SplinterGP** [comment]
I think it being on water is okay since the planets can have water or rivers but dont make the water acessible in anyway possible please, and make them killtiles

**Comment by TiviPlus** [comment]
We have maps in space why is there water in space @SplinterGP

**Comment by SplinterGP** [comment]
> We have maps in space why is there water in space @SplinterGP 

Why cant it not be in space ?

**Comment by TiviPlus** [comment]
Because its a  space ship its in the name

**Comment by MsSeraph** [comment]
Alright i forgot about the gunprops and the maintenance i'll fix em

**Comment by TiviPlus** [comment]
As discussed in discord you need to fix the middle floor having too much easily defensible space and CIC being ladder camp hell at the very least, as well as fix space accesablility, and the sandbags as well

**Review by Kuro020 — APPROVED** [review]

**Pull request closed without merging**
