### PR TITLE
Gives supply beacons on the minimap the req background colour and a red tip

### PR DESCRIPTION
**Pull request by Ldip999**
## About The Pull Request

Makes the background of the supply beacons a "requsitionesq" brown on the map.

## Why It's Good For The Game

Supply beacons are currently hard to find as they are easily confused since they look like rotated sentries, and otherwise have a plain, dark grey background, which helps them blend into the background. This PR attempts to remedy it by making them stand out more by giving them a brown background and a red flashing tip on the minimap

Before:
image
After:
image
(Sentries added to futher illustrate my point of how easily these get lost nearby other markers)

## Changelog
:cl:
qol: Supply beacons on the maps now have a brown background and a red flashing tip, hopefully making them easier to see.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
absolute king shit ur a hero to dirty reqqies like me

**Comment by Wisemonster** [comment]
An image comparing the new sprite to the old sprite would be nice

**Comment by Ldip999** [comment]
> An image comparing the new sprite to the old sprite would be nice

Done

**Review by TiviPlus — APPROVED** [review]

**Comment by grinkgo** [comment]
is this the way i find out req beacons had a mini-map icon...

**Comment by Ldip999** [comment]
> is this the way i find out req beacons had a mini-map icon...

That makes two 😀
At first I thought they were just rotated sentries, hence my initial confusion. When I first set out with this PR, I wanted to ADD a supply beacon to the minimap only to find out halfway it was already a thing that got lost in the sea of other stuff

**Comment by lbnesquik** [comment]
Now, I am not asking Ldip999 to do it for us, but I think at some point, we'll need some minimap options, because we honestly are starting to get a little too cluttered in terms of icons, especially with Tad, APC, Tank, Leaders and all the other stuff.

**Pull request merged**
