### PR TITLE
Removes Eyeblur from Blink

### PR DESCRIPTION
**Pull request by KrabSpider**
eyeblur removed

## About The Pull Request
Per title. 

## Why It's Good For The Game
Annoying and next to worthless status effect that does nothing but induce motion sickness while the Wraith is perfectly safe and comfy in godmode. 50% damage reduction and heavy slowdown are enough. 

## Changelog
:cl:
bal: Eyeblur removed from blink.
/:cl:

### CODE REVIEW

**Comment by Lefunny** [comment]
Removes blink itself :trollface:

**Review by TiviPlus — APPROVED** [review]

**Comment by breadhunt** [comment]
^ alternative PR
doesn't blink also apply screenshake? If eyeblur causes motion sickness, camera shake is 10x worse

**Comment by KrabSpider** [comment]
> ^ alternative PR doesn't blink also apply screenshake? If eyeblur causes motion sickness, camera shake is 10x worse

Removed as well.

**Comment by Starfirejordan** [comment]
this PR is bad for the game
reason: wraith is support and backline harassment being able to blind player is able to throw of there aim and use it to evade and escape is a big part of player wraith. this just seems as a MAJOR nerf

**Pull request merged**
