### PR TITLE
Plasma cutter can one hit resin walls again

### LINKED ISSUE #11103: plasma cutter damage nerf killed plasma cutter
### Description

plasma cutter nerf (https://github.com/tgstation/TerraGov-Marine-Corps/pull/10902) was to reduce melee damage against xeno coz it powerful tool and do not need powerful melee damage, but melee damage nerf is very buggy and bad coded. It kill all meaning of use plasma cutter coz now you need to punch a xeno wall TWICE. And now plasma cutter is not TOOL or WEAPON. And it do not worth its points. Or slots that it occupies. 

### Test Merges

(https://github.com/tgstation/TerraGov-Marine-Corps/pull/10902

### Reproduction Steps

Take plasma cutter
Punch xeno wall once (you dont destroy it)
Wait for cutter delay (very long)
Punch xeno wall once more (only now you destroy it)

### Screenshots

image
image

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Increased the resin damage multiplier so PC can cut full health resin walls in one hit again.

The recent change to nerf melee damage brought it's damage against resin walls down to 280, not enough to one hit them, and so a pretty huge nerf consider the extra charge and hit delay.

Fixes #11103 

## Why It's Good For The Game
PC being good for it's intended role is good.

## Changelog
:cl:
balance: Plasma cutters once again one hit resin walls
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
I'd personally increase it to 3 or even 5 purely for the redundancy safety. it doesn't really use that for anything but resin walls that should be 1hit regardless, does it?

**Comment by Lumipharon** [comment]
> I'd personally increase it to 3 or even 5 purely for the redundancy safety. it doesn't really use that for anything but resin walls that should be 1hit regardless, does it?

All resin structures, so silos and shit, so that's probably not a great idea.

**Comment by novaepee** [comment]
on god

**Comment by Losenis** [comment]
It doesn't actually trigger on silos, and as far as I've seen neither on things like towers and jelly pods.

**Comment by Lumipharon** [comment]
> It doesn't actually trigger on silos, and as far as I've seen neither on things like towers and jelly pods.

Not silos sorry, turrets.

**Comment by FosterGrime-Heymynameslouie** [comment]
for some reason I cannot emote with a thumbs up on my phone so have this comment instead

I can finally pc without have a knife on the other hand to whack the wall which apparently was already cut down by the pc

spedde megher

**Comment by Losenis** [comment]
>Not silos sorry, turrets.

Fair enough

**Comment by Al-1ce** [comment]
This sounds fair. Especially considering plasma cutters have a huge timer in between usage once the battery dries.

**Comment by Losenis** [comment]
Also should probably change it from balance to fix since the reduction was unintended and the original pr had no mention of wanting to do such a thing

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
