### PR TITLE
T-81 AutoSniper no longer has NVG

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title. The gun has also been given access to normal scope attachments to compensate, and will now start with a T-47 rail scope attached by default.

## Why It's Good For The Game
T-81 is way too good at what it does. This should make it so it doesn't have that much of an edge, while keeping it as a better sniper rifle.

## Changelog
:cl: Lewdcifer
balance: T-81 Autosniper no longer has a NVG scope, now starts with a T-47 rail scope.
/:cl:

### CODE REVIEW

**Comment by Pariah919** [comment]
image

~~sniper rifle can't even snipe, this is so sad~~

But seriously, the T-81 probably should just get a fire rate reduction to DMR levels of fire speed (0.65) rather than old old BR levels of 0.55, this would really solve the issue of the CQC sniping it has.

Or someone can code the aim delay changing when you zoom in, that'd be cool.

**Comment by SpaceLoveSs13** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/9327 Price of the rifle has already been increased. If this nerf of a kit is necessary or the rifle itself, then decrease its price again in the pr significantly. Otherwise this is an unnecessary cut down.

**Comment by lKiseki** [comment]
> #9327 Price of the rifle has already been increased. If this nerf of a kit is necessary or the rifle itself, then decrease its price again in the pr significantly. Otherwise this is an unnecessary cut down.

Its stats are already really good and I'm not touching them, they should very well keep it worth the purchase.

**Review by BraveMole — CHANGES_REQUESTED** [review]
the price was just bumped to 50, does it need another nerf?

**Comment by OpsCoretango** [comment]
Remember, 81 costs 50, Magazines! every each its 30  pts
=80 pts, just head blow up.
I pay for king of DMRs, not for SVD chambered in 8.6

**Comment by hyper2snyper** [comment]
and now.. the sniper is never bought and succesfully qdeled

**Comment by Lumipharon** [comment]
It was just nerfed, give it some time to see if it actually needs more changes.

**Comment by BraveMole** [comment]
Nah, at least not for now

**Pull request closed without merging**
