### PR TITLE
Nerfs ravager health to 350 and buffs endure to -150HP

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
This nerfs the ravager health to it's original 350 and doubles endure's critical health.

## Why It's Good For The Game
Currently ravager's endure is a joke, and marines have a lot of weapons that let you do 100+ damage in one shot, shotguns, snipers, repeaters, vali, and it's not simply possible to account for it if you want to make use of the critical health for raging, meaning that endure/rage is mostly left as a escape tool and that goes against the entire philosophy of Ravager as a whole

## Changelog

:cl:
balance: Ravagers maxhealth is now 350, decreased from 400
balance: Ravagers endure health is now -200, increased from 100
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Numbers can be changed around based on discussion if need be, mostly the keypoint is that endure HP needs to be some amount higher

**Comment by Runian** [comment]
Will they drop dead if Endure ends when their health is under -100?

**Comment by Arturlang** [comment]
> Will they drop dead if Endure ends when their health is under -100?
This doesn't change other endure functionality, but I've been hoping to see if I can make that just drop them into deepcrit instead

**Comment by Lumipharon** [comment]
I look forward to the funny rav buffwith 300 crit hp.

**Comment by iforgotmeword** [comment]
the only problem i see with this is that it's going to be even more annoying with stagger bots (cough cough) 

and endure being a even stronger run away tool then it already is

**Comment by Arturlang** [comment]
> I look forward to the funny rav buffwith 300 crit hp.

Yea if you make use of the rage feature that buffs crit HP that is kinda really hard to use right now given how close to death you need to be

**Comment by Arturlang** [comment]
> the only problem i see with this is that it's going to be even more annoying with stagger bots (cough cough)
> 
> and endure being a even stronger run away tool then it already is

Endure does prevent stagger, and the intent is to make endure useful enough that it's possible to use it to make full usage of rage so commiting is not literally suicidal

**Comment by Technical-l** [comment]
> Endure does prevent stagger, and the intent is to make endure useful enough that it's possible to use it to make full usage of rage so commiting is not literally suicidal

BASED................... RAV MAINS RISE UP

**Comment by blackdav123** [comment]
rav _should_ die in one hit from all those things

**Comment by despong** [comment]
no more atropos mk ultra we're so back xenoheads

**Comment by Barnet2** [comment]
> I look forward to the funny rav buff with 300 crit hp.

Yeah uh, Super Rage is supposed to be risky. This is just a straight up bad idea, as a MK Ultra rav player myself it really isn't hard to calculate damage in small groups, just a learned skill.

**Comment by Arturlang** [comment]
@Barnet2 
Currently, trying to do super rage is pure luck if you even manage to survive, it's near impossible to manage 100 damage when a single quick burst will just off you out of nowhere, a endure hp of 100 damage is jack shit, let's see, buckshot does 40 for the main shell + 40 damage  for each bonus projectile, which there are 5 of, slugs do 100 straight damage with 20 ap, repeater does 70 damage per hit with 20AP, snipers do 90 damage per hit with 50 AP, yes, not all of these will instantly crit you, but you need to consider the easy of burst damage for marines, and that even dipping within any amount of endure health opens up you to literal instadeath.

**Comment by Arturlang** [comment]
Oh yea, vali spear, 60 force wielded, claymore is 90, that's not including the extra 0.6 times damage, spear:60+36=96, claymore: 90+54=144

**Comment by Lauwma** [comment]
Rav doesn't really need a buddy to be honest. Screen shake removal + kuro sweep + removal of aimmode put it in a very very good spot where you can reliably super rage. Maybe only buff the crit health by 50 so it's a lighter buff, it'll make super raging more forgiving

**Comment by Arturlang** [comment]
I think 200 endure HP is reasonable given how little armor it has compared to other castes, considering also it has to melee marines to deal damage, and taking damage is a core mechanic of ravager.

**Comment by Lumipharon** [comment]
currently super rage endure limit is 150, not 100. This pr buffs it to 300. This is an exceedingly bad idea, and simply allows rav to be even more aggressive, with far less risk, when enjoying its largest buffs.

**Comment by Pariah919** [comment]
This... is just a straight buff posing as a trade off.

**Comment by Arturlang** [comment]
Alright, reduces endure HP to -150, but some amount of a buff is neccesary to make max-raging some amount of practical instead of a mostly-suicidal move

**Comment by DrAmazing343** [comment]
I've seen a lot of extraordinarily good Ravagers who utilize super rage without dying very consistently. Nascar and Atropos very easily reach this, in my mind, and while we shouldn't necessarily curve buffs and nerfs around individual players, it's not skill that's one player in the entire field level. A buff like this will allow a lot of intermediate Ravagers to make expert-level plays for no good reason.

I stopped myself from commenting ided because I did that on another PR and felt bad about it, but please do take note of the level that others play at when considering whether to buff or nerf a caste because that same buff that makes a caste playable to you will make another player practically invincible.

**Comment by FunkyMonke47** [comment]
So this is just a ravager nerf now, amazing

**Review by TiviPlus — APPROVED** [review]
code ok

**Comment by Arturlang** [comment]
@FunkyMonke47 People said this was a straight buff earlier, and said that 200 was too much, if people can agree to readd the removed health i am willing to, and i have used super rage effectively but it is so damn on the edge that its just not fun to risk instant death

**Comment by Lauwma** [comment]
> So this is just a ravager nerf now unless you take advantage of super rage, an optional mechanic, amazing 

You don't need to use super rage to make use of that change ? It makes so you can stay in endure much longer and not get instant deleted by a shotgun or rocket launcher

**Comment by FunkyMonke47** [comment]
> You don't need to use super rage to make use of that change ? It makes so you can stay in endure much longer and not get instant deleted by a shotgun or rocket launcher
 
If you take 50 health from the normal health pool, and give 50 to endure, you're left with the same health as before if you're not super raging

**Comment by Lumipharon** [comment]
This is still really stinky, kuro can fight me if they disagree.

**Pull request closed without merging**
