### PR TITLE
Buffs Barricades

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
To go with https://github.com/tgstation/TerraGov-Marine-Corps/pull/16557.
Buffs most barricade types. Changes are as follows:

> **Barbed Wire Upgrade**
> Damage: 10 -> 15

Meant to compensate for xeno health and armor buffs slightly. Still worse than before.

> **Metal Barricade**
> Health: 200 -> 250(300 with barbed wire)
> Concussive Upgrade: 40 bomb armor -> 80 
> Ballistic Upgrade: 30 bullet/laser/energy armor -> 50(80 with base armor)
> Acid Upgrade: 20 acid armor -> 35(75 with base armor)

My thoughts here are that metal cades are laughably weak in all aspects and their upgrades do not help this feeling. This is probably the biggest buff here, and I am willing to tone it down a bit or perhaps increase the cost to build them to 5 to compensate. 
Firstly, acid cades are the big one: a single ranged caste being able to whittle down marine defenses so effectively is the main problem and is what I wish to nuke. 
Secondly, I honestly believe that the explosive upgrade should grant total explosion immunity to the cade, but this is fine enough. 
Lastly, the ballistic upgrade should simply be very good at stopping guns. It currently isn't, as every marine or sommie can blast through them like paper in hvh. I don't believe melee castes should be punished any more than the health buff, so the +30 melee armor remains the same as previous for this upgrade.
>**Plasteel Barricade**
> Heath: 500 -> 550(600 with barbed wire)
> Acid Armor: 40 -> 50

Health and acid armor buff are meant to also decrease the effectiveness of ranged caste spam, however I don't believe it needs anything else.
> **Sandbags**
> Health: 300 -> 325(375 with barbed wire)

I want sandbags to keep their health advantage over metal barricades so that un-upgraded metal cades are somewhat worse than sandbags, while upgraded metal cades are much better than sandbags. To be honest, this is still the case without the +25 health, but I included it because I wanted to.
> **Deployable Shield**
> Health 300 -> 325

Mostly same as above.
## Why It's Good For The Game
Currently, marine defense is laughably bad due to xeno health buffs, removal of aim mode, and general powercreep/balance shifts in the game since a few years ago. This changes is poised at generally buffing marine defense and specifically lowering the effectiveness of ranged xeno attacks against cades, as currently, it is incredibly easy for a single ranged caste to whittle down a cade line unless marines *leave* their cades to chase it away. 

I do not believe this will completely destroy xeno's balance, as marines tend to get complacent when they sit behind good defenses for too long and are much more likely to make mistakes that xenos can capitalize on; marines sitting behind a cade line doing a disk just slows their momentum, which they need if they want to get all of the disks.

Numbers are not final by any means, and if any of them are too much I will gladly nerf it. However, I think this is a good starting point. 
## Changelog
:cl:
Balance: Increased health of most barricade types(Metal+50, Plasteel+50, Sandbags+25, Deployable+25)
Balance: Doubles armor values of most metal barricade upgrade types with the exception of ballistic armor's melee value
Balance: Increased acid armor value of plasteel barricade(40 -> 50)
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
making sandbags cheaper would be really funny

cool pr spepderhgm

**Comment by Looking4bros** [comment]
Actually being able to defend something would be nice, yeah. I stopped bringing mats as engineer when i realized how crappy they had become. Always enough scrap lying around to build an APC frame if i need to, and that's about all i need mats for right now.

**Comment by Breadeagle** [comment]
Its important we understand the numbers here: By changing acid armor of caustic cades, we're doubling the EHP vs acid. Adding that with the 20% HP increase and its probably an over adjustment. Xenos don't actually have strong siege when a field is cleared, since pretty much all their off screen options have been removed. There's a few areas on maps that can just be blown off and become unassailable. 

Sandbags are also strong enough as is and meet the breakpoint to survive crusher charges. Plasteel changes here make it about 25% bulkier to acid.

Its also worth noting that increasing stats do not mirror how much more useful they'll become - plasteel cades are significantly more useful than metal options on average because their increased bulk lets them be repaired by welder MUCH more often, compared to metal. I do agree that metal cades need to be buffed, but the caustic number change is probably too much. It's already the most generally useful upgrade. Concussive is fine since explosion armour is super niche regardless.

I think we should be very careful to not adjust marine defenses to be too strong, since it usually just ends up in horrible gameplay with fob sieges, miner holds and stuff feeling completely impossible to overcome at times. That said, metal cades are definitely underpowered. They usually struggle to hold up to all the strengths of sandbags right now lol.

**Comment by Pariah919** [comment]
Honestly should consider making it so crusher doesn't need to slash a razor once to deny it from stopping charges.

**Comment by Mannybrado** [comment]
> Its important we understand the numbers here: By changing acid armor of caustic cades, we're doubling the EHP vs acid. Adding that with the 20% HP increase and its probably an over adjustment. Xenos don't actually have strong siege when a field is cleared, since pretty much all their off screen options have been removed. There's a few areas on maps that can just be blown off and become unassailable.

I'd be willing to change the acid cade buff to instead be +20 to cades as a part of their base armor, meaning its 60 with the acid cade upgrade. I really believe that acid cades should completely fuck ranged castes as otherwise there is no counterplay to ranged castes besides spamming explosives, babysitting with a welder the entire time you're under attack, or leaving your cades to make them run away.

The rest I believe are fine as they are. Maybe the plasteel one could just be the health increase, but keeping the rest of the cades in line with the buffed metal cades seems appropriate to me.

**Comment by Lumipharon** [comment]
This really ignores the fact you can already make autism miner forts, where this is going to buff them through the roof.

**Comment by EEASAS** [comment]
idea: bring back tad barricades

**Comment by Looking4bros** [comment]
> This really ignores the fact you can already make autism miner forts, where this is going to buff them through the roof.

I've only had good luck with Reinforced walls Miner forts, i've seen one or two forts that survived for a good while, but it definetly seems like a team composition problem, or if xenos can't peel off and organize an attack on the miner. Perhaps lower caste swapping timer :clueless:

**Comment by Arturlang** [comment]
Cades do kinda suck and crumble way too easily, especially metal ones, even just in HVH they get destroyed way too fast because they're simply that fragile.

**Comment by Isy232** [comment]
> This really ignores the fact you can already make autism miner forts, where this is going to buff them through the roof.

Miner forts are trivial to crumble with high skilled xenos on certain castes.
If no Sentry, have wraith banish the Marine and slash the miner.
If sentry have Warlock reflect the bullets to destroy the barricades and sentries.
Adding a second xeno willing to take out the miner fort such as Praetorian or Crusher make it even less likely the fort will last.

With multiple sentries and multiple marines the miner fort has a far better chance, but that is a decent investment from the marine side and requires some degree of teamwork so should ideally be rewarded.

I'd argue that if the stronger barricades prove to make miner forts far too strong we could revert or nerf this, but as is miner forts are relatively weak in the current meta and could probably use a buff.

**Comment by SimplySmiley123** [comment]
> > This really ignores the fact you can already make autism miner forts, where this is going to buff them through the roof.
> 
> Miner forts are trivial to crumble with high skilled xenos on certain castes. If no Sentry, have wraith banish the Marine and slash the miner. If sentry have Warlock reflect the bullets to destroy the barricades and sentries. Adding a second xeno willing to take out the miner fort such as Praetorian or Crusher make it even less likely the fort will last.
> 
> With multiple sentries and multiple marines the miner fort has a far better chance, but that is a decent investment from the marine side and requires some degree of teamwork so should ideally be rewarded.
> 
> I'd argue that if the stronger barricades prove to make miner forts far too strong we could revert or nerf this, but as is miner forts are relatively weak in the current meta and could probably use a buff.

To be honest every autismo miner fort lives on borrowed time.
It's not an if they die, they absolutely will, but how long it takes tier 3s and the 3 tier 4s to notice the free kill sitting off to the side surrounded by paper mache metal.

**Comment by Mannybrado** [comment]
Furthermore a point was raised that this buffs the activity known as sitting on a miner with the entire marine team, PCing the walls around the miner and creating an open death zone.

Sure. This is still something that is completely un-counterable by xenos currently. Personally I believe that miners in their current state are bad for the game in the long run in the same way that aim mode was: they encourage gameplay that isn't fun for either side. I would personally either return the ore crate mechanic to force the use of asrs pads as a way to increase the cost of this, or simply remove miners and replace it with a singular objective that is much harder to hold, akin to sensor towers in hvh gamemodes. 

Either way it's not a problem with marine barricades, its a problem with marine off-screens. What a joke it is that the only xeno off-screen was nerfed while all of the marine off-screens remain exactly the same.

**Comment by Lauwma** [comment]
The problem with your PR is not miner forts, the problem with your PR is simply that it doesn't encourage a good round flow. We don't want barricades to be too durable and too permanent simply because marines are not supposed to stay in once place for too long. Also increasing effective hp also increases how long you can wield a barricade under heavy attacks, making the xeno commitment enormous since they'll have to be slashing your cade for too long to make it go down. 

If you want to buff cades this is not the way, the only thing I'd keep is the explosive cade buff. Maybe instead consider making tools to build line of cades more quickly or lowering the build time.

**Comment by SimplySmiley123** [comment]
> The problem with your PR is not miner forts, the problem with your PR is simply that it doesn't encourage a good round flow. We don't want barricades to be too durable and too permanent simply because marines are not supposed to stay in once place for too long. Also increasing effective hp also increases how long you can wield a barricade under heavy attacks, making the xeno commitment enormous since they'll have to be slashing your cade for too long to make it go down.
> 
> If you want to buff cades this is not the way, the only thing I'd keep is the explosive cade buff. Maybe instead consider making tools to build line of cades more quickly or lowering the build time.

Then make the cades easier and faster to disassemble, or cheap as dirt to keep abandoning them.

**Comment by Mannybrado** [comment]
> > The problem with your PR is not miner forts, the problem with your PR is simply that it doesn't encourage a good round flow.

Hmmm... That's worth trying actually.

**Comment by Mannybrado** [comment]
> > > Then make the cades easier and faster to disassemble, or cheap as dirt to keep abandoning them.
> 
> Hmmm... That's worth trying actually.

Ehhh... I dunno actually. Will probably slopify the game more as it'll just encourage xenos to use spitter castes more often to counter the increased cade spam, at least in the case of decreasing the cost, and I don't feel like lowering build time will do anything.

Significantly decreasing the time it takes to deconstruct to only need one tool or something might be interesting, but I still prefer this over that. If someone was to make that pr and it got approved over this, I would accept that.

**Comment by Mannybrado** [comment]
After TM I'll consider removing the health buff, or decreasing it or whatever, but I want to see how it plays with both increased armor and health.

**Comment by Kuro020** [comment]
Tm this first to see how it goes

**Comment by Barnet2** [comment]
Just an observation, not going to argue for or against the PR at this point. All I will say is assuming barbed.
Changing armor values  does change EHP quite drastically. For example, Acid Cades have gone from 18 spits to take down to 35.
Plasteel cades - 26 to 35. Those are the numbers, I don't think the other buffs were much relevant (bullet + laser armor only takes into account I think warlock, their beam and reflecting marine ammos).

**Comment by Lumipharon** [comment]
1200ehp on an acid cade. This is more ehp than the APC, as a comparison.

**Comment by FunkyMonke47** [comment]
It's honestly impressive how poorly balanced this pr is

**Comment by Looking4bros** [comment]
> 1200ehp on an acid cade. This is more ehp than the APC, as a comparison.

Now what's the ehp against a crusher charge?

> Acid Cades have gone from 18 spits to take down to 35.

The unacidable cade is now much less viable to acid from afar. :thinking:

It was never an acid caste that i recall being a menace to engineering forts. Crushers and Warlocks come to mind as they tend to force openings faster than you can do much about. Both T3s, and i suppose Primo queen. Boilers gas can be a nuisance as well, but that's more suppression than anything else. Spitters kinda do stuff, but it's not something that comes to mind very often.

**Comment by SimplySmiley123** [comment]
> It was never an acid caste that i recall being a menace to engineering forts. Crushers and Warlocks come to mind as they tend to force openings faster than you can do much about. Both T3s, and i suppose Primo queen. Boilers gas can be a nuisance as well, but that's more suppression than anything else. Spitters kinda do stuff, but it's not something that comes to mind very often.

Acid castes ain't gonna burst down a barricade but they sure do consistent, repeating damage from a distance that rarely ever gets dealt with by marines. Though they sure as hell don't care much at all wether the cade is the acid resistance one or any other.

**Review by TiviPlus — APPROVED** [review]

**Comment by TiviPlus** [comment]
@Kuro020 ?

**Comment by SauceCat9** [comment]
This change feels great to play with, there's actually a point to upgrading cades now.

**Comment by Lauwma** [comment]
> @Kuro020 ?

image

**Comment by Mannybrado** [comment]
me when i ask for it to be reopened and it isnt reopened

**Pull request merged**
