### PR TITLE
Deletes the derringer and all the associated icons.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Deletes the derringer. Deletes the derringer sprites.
## Why It's Good For The Game
image
If a gun only exists to be a shittier version of another gun, maybe it's not meant to be in the game.
Improves the game by reducing vendor bloat and reducing the amount of noob traps.
## Changelog
:cl:
del: Deletes Derringer.
imagedel: Deletes Derringer sprites.
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Salt PR?

**Comment by chizzy376** [comment]
This nerfs redcoats vs bluecoats, close

**Comment by Oscari-pog** [comment]
Maybe make it a seasonal?

**Comment by FIXTHERADBOXPLEASE** [comment]
This PR destroys at least half of George Washington RP.

**Comment by RaidarV** [comment]
This PR destroyed my life. It kicked in my door, fucked my wife, broke my kid's spine, tucked me into the bed while giving me a good night kiss and pissed on my dog on it's way out.

**Comment by Xander3359** [comment]
> Salt PR?

Yes, I'm salty from maintainers.

**Comment by Lumipharon** [comment]
This seems like a fair and reasonable response for not getting your buffs merged.

**Pull request closed without merging**
