### PR TITLE
The Purge: Part I

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
TM before merging.

Purged a whole bunch of suits and hats (both code and sprites) that were entirely unused. Part 1 of probably many, as we have a huge amount of legacy garbage that just sits there unused.

This is all ancient CM or bay era stuff, although a few were left in because a few shipside roles still use them. I repathed them for my own sanity however (someone please resprite them as well).

This also purges various related code such as various boxes, and preloaded marine outfits (we have quickload vendors now).

Additionally updated various suit and helmet sprites with more modern TG versions.
## Why It's Good For The Game
Purging unused stuff good.
## Changelog
:cl:
code: Removed various items from the codebase that are entirely unused
imageadd: Ported TG sprites for various very old suits and hats
/:cl:

### CODE REVIEW

**Comment by QualityVan** [comment]
Aren't preequip marine outfits used for admin menu stuff? Dunno offhand if that comes up with any real frequency.

**Comment by Lumipharon** [comment]
> Aren't preequip marine outfits used for admin menu stuff? Dunno offhand if that comes up with any real frequency.

You can just drop a quickload vendor these days, and actually have some options.

**Comment by Autisem** [comment]
> > Aren't preequip marine outfits used for admin menu stuff? Dunno offhand if that comes up with any real frequency.
> 
> You can just drop a quickload vendor these days, and actually have some options.

not much point IMO removing a few outfit datums that can be useful for admins. I doubt it will make a noticeable impact on performance

**Comment by XElectricX** [comment]
I get removing old CM stuff but why SS13 content? If anything more clothes would be nice to have available.

**Comment by RipGrayson** [comment]
I'm fine with removing most of this content, but I'm less certain about removing standard ss13 items/gear/clothing in the future. A lot of those have use as mapper flavor, and it would be a pain to readd them if deleted.

**Comment by Lumipharon** [comment]
Put the space suits back in, but updated them with more modern TG sprites. Also unfugged some code/removed some spacesuit breach code that is unused.

**Pull request merged**
