### PR TITLE
Synthetics can now be scanned

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

This allows synthetics to now scan themselves with the health analyzer

## Why It's Good For The Game

Extremely minor change that just makes it slightly easier for Synthetics to self repair or be repaired by others. It's honestly not even balance with how stupidly minor it is.

## Changelog
:cl:
qol: Synthetics now show on the health analyzer
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
FUCKING

FINALLY

**Comment by InterroLouis** [comment]
What about combat robots?

**Comment by Losenis** [comment]
They always could

**Comment by InterroLouis** [comment]
Combat robots also have the NO_SCAN flag, though.

**Comment by Arctrooper8** [comment]
> Combat robots also have the NO_SCAN flag, though.

This, funnily enough, does nothing; because, the health analyzer actually only checks if you're A. not a carbon, and B. not a synthetic.

**Comment by Arctrooper8** [comment]
Tivi has declared that Synthetics shall not be scannable

**Pull request closed without merging**
