### PR TITLE
Among us Crewmate emojis

### PR DESCRIPTION
**Pull request by SplinterGP**
## About The Pull Request 
Adds among us crewmate emojis
image

## Why It's Good For The Game
Emojis are nice and they are on OOC, plus everyone likes among us

## Changelog
:cl:
imageadd: added among us emojis to ooc, red, yellow blue, green, orange and purple, use :colorsus: for it.
/:cl:

### CODE REVIEW

**Comment by David-Stormwell** [comment]
no

**Comment by SplinterGP** [comment]
> 
> 
> no
> -tgmc PL

why not, state reason or i'll make the plague seem like a trivial thing close to what im gonna do to you

**Comment by Jeff-jefferson-jeffery** [comment]
idk man this seems kinda sus

**Comment by Tennessee116** [comment]
I (unironically) don't think these would fit well **_among_** the other emojis.

**Comment by David-Stormwell** [comment]
> > no
> > -tgmc PL
> 
> why not, state reason or i'll make the plague seem like a trivial thing close to what im gonna do to you

No.

**Comment by lKiseki** [comment]
> 
> 
> no
> -tgmc PL

based

**Comment by TiviPlus** [comment]
I voted david

**Comment by Swagile** [comment]
i vote tivi

begin the process

**Comment by Smudged** [comment]
based

**Comment by Walarks** [comment]
amogus good

**Comment by Kuro-ai** [comment]
merge amogus or I'll hack into tivi's computer and delete the cat pics

**Comment by TiviPlus** [comment]
Splinter was not the imposter

**Comment by TheBimmer231** [comment]
No u

**Comment by Kuro-ai** [comment]
based and spriter pilled

**Pull request merged**
