### PR TITLE
Removes TerraGovTech Engineer Vendor, Changes Automated Weapons vendor.

### PR DESCRIPTION
**Pull request by Arctrooper8**
## About The Pull Request

Removes the TerraGovTech Engineer Vendor
removes TL-102 and sentry boxes
Adds three round start sentries to fob drone
Moves the remaining TerraGovTech inventory to Automated Weapons vendor
Reorganized Automated Weapons vendor to a minor degree
Creates a crash specific Automated Weapons vendor
Updates Valhalla and HvH weapons vendor (copy paste)

## Why It's Good For The Game

TerraGovTech Engineer Vendor has increasingly become irrelevant and even annoying in recent times. It hardly holds any actual engineering equipment except for the sentries which don't actually require any skills or tools to set up. However as time has progressed more heavy duty equipment meant for all marines has been locked away in the vendor leaving marines begging engis to vend them. 
Completely removing the vendor and adding it to automated storage solves this issue. To avoid these heavier weapons being used in crash a crash specific vendor has been created. 
3of the 4 sentries are now in the fob drone by default, their excess ammo and the 4th sentry is in the automated vendor. This ensures that there will always be some sentries for the FOB whilst still allowing Tadpole for example to take one if it pleases. 

Sentry/TL-102 boxes were removed and buying them from req now gives only the weapon (prices has been adjusted to account for lost ammo). This is because most of the time you'll still have spare ammo, but the weapon itself will be destroyed.

Pictures:

image
Melee
image
Specialized
image
Deployables (Not available on crash vendor)
image

## Changelog
:cl:
del: TerraGovTech Engineer Vendor.
qol: TerraGovTech Engineer Vendor products have been moved to Automated Weapons Vendor.
balance: Crash specific version of Automated Weapons Vendor added, it lacks certain powerful weaponry.
balance: Sentry/HSG-102 crate removed, you now buy just the sentry/HSG itself.
imagedel: TerraGovTech Engineer Vendor.
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
yes, finally, sentries inside fob drone itself.
can it be ejected though? some engie's give their spare sentries to PO

also crash specific vendor was a long time coming. im glad this pr finally does that

also hsg being removed is kinda strange, but I guess its understandable.

**Comment by Lumipharon** [comment]
Sentries shouldn't be in the drone unless people without engie access can get them out, so honestly it's better to just not put them in at all. Just stack them all next to the fob console like there used to be one, then engies or PO's can take them depending on whether they choose to fob or tadop, or whatever else they do.

The HSG and sentry boxes are actually kinda useful since you can fit the actual gun/sentry itself inside along with it's ammo. This is not possible otherwise, except for a technician bag. (hsg and sentry ammo are both bulky items). So if you actually need to move them, their boxes are the best method to do so outside of dragging a crate around.

**Comment by Glcbitj** [comment]
The sentries begining roundstart inside the FoBdrone is kinda bad, non-engineering access marines can't use them, losing their boxes also sucks in case you want to move the sentry + ammo around. Just let 3 roundstart sentry crates besides the drone console and make them insertable in the FoBdrone if possible, and make sure the sentries auto eject from the drone if the Alamo launches, just like metal does.

**Comment by Arctrooper8** [comment]
I'm working on being able to eject sentries however for atomization (and the fact I haven't been able to get it to work yet) I've got three sentries in the drone and one in the vendor. I believe that's pretty fair considering most of the sentries should be going to FOB anyway.

**Comment by Arctrooper8** [comment]
> Will conflict with #10498 as noted in PR.
> 
> Sentry in FOB drone is not a good investment since if you remove the sentry boxes, then you nerf the ammo.
> 
> Sentry voucher were never used since the convenience of putting sentry in FOB drone lose the ammo drum. At the time, you can either buy the sentry voucher or sentry box, which is long pass.
> 
> If you want sentry in FOB drone, you need to consider the ammo that spawn inside the sentry boxes.

The ammo I already have placed in the vendor? Please read the PR next time.

**Review by Pariah919 — APPROVED** [review]
Seems unatomized? That's up to the code maintainers, not me anyway.

Changes seem alright to me, even if I dislike the removal of boxes for logistical reasons and moving shit around once ordered.

Crash vendor is good for balance.

**Review by BraveMole — CHANGES_REQUESTED** [review]
Sentries shouldn't be in fob drone, because sometime you don't make a fob.

This PR has a million thing and I don't feel like reviewing the rest

**Comment by Arctrooper8** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10544

**Pull request closed without merging**
