### PR TITLE
Disallows AI railgun to target FOB

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
What it says on the tin.
## Why It's Good For The Game
Literally only used to delay the round by 30 seconds to a minute when xenos want to hijack and there is no way to stop it.
## Changelog
:cl:
balance: Disallows AI railgun to target FOB
/:cl:

### CODE REVIEW

**Comment by Wisemonster** [comment]
Don't the xenos usually have to wait for the alamo to recharge anyways when they call it down? Also this will prevent the AI from providing covering fire during a retreat to the alamo.

**Comment by Helg2** [comment]
As wisemonster said, AI can provide assist with railgun if fob is sieged.

Proper fix to it would probably be to make fob cameras not invisible? So xenos can just slash them, and if they don't its their fault.

**Comment by Notamaniac** [comment]
Disallow the railgun to be fired without sufficent marines on the ground

**Review by Kuro020 — APPROVED** [review]

**Comment by TiviPlus** [comment]
> Disallow the railgun to be fired without sufficent marines on the ground

Disallow the railgun to be fired

**Pull request merged**
