### PR TITLE
Female Combat Robots

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

https://user-images.githubusercontent.com/6610922/212421038-27dcde0a-b71e-42bd-a8a4-4860be0b92e8.mp4

Works with medhud and meson.

https://user-images.githubusercontent.com/6610922/212422037-9d0ec9b2-f931-49f2-849d-15c7588cb403.mp4

Thanks to Jack(ie) Burgdorf who gave us sprites!

## Why It's Good For The Game

Synthetic can be female, so why not combat robot? Before these sprites, combat robot female sprites were just male. Sometimes, I chuckled to myself when I hear a combat robot using the female *medic.

## Changelog

:cl: novaepee, Jack(ie) Burgdorf
imageadd: Female Combat Robots
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
Wall-E and watsername in TGMC

**Comment by ilikesaying** [comment]
ohno

**Comment by grinkgo** [comment]
What is the point of gendering robots? At least for synthetics they are made to imitate humans but this isn't the case for robots, whose frames would be built and designed solely for practical purposes. 

> Before these sprites, combat robot female sprites were just male.

What does this even mean. Why are they "male" sprites when they are just robots. What distinguishes a male and female robot? Robot breasts?

**Comment by XSlayer300** [comment]
I think they can just be different models of combat robot.

**Comment by MereWalker** [comment]
Please don't use the robots as toys. They are killing apparatuses.- HC 
In all honesty I don't see a reason to gender them since they are not living. Just add a different model make. Just my opinion don't care to much.

**Comment by FosterGrime-Heymynameslouie** [comment]
atomic heart

**Comment by David-Stormwell** [comment]
im going to put myself in a eternal sleep for life

**Comment by Lumipharon** [comment]
Why do we need fembots? They're expendable killbots.

**Comment by helper-2** [comment]
Its almost the same model but more silver with thicker chestplate and one cheek. And de fucking mask. Mask is the worst design choice here. First it looks shit. Second it catch too much attention than it needed and looks out of place.

I think, it would be interesting alternative sprite (don't know why its female sprite), but PLEASE remove mask, its just awful

**Comment by RaidarV** [comment]
> Why do we need fembots? They're expendable killbots.

"I NEED TO SUCK MAD ROBO TITTIES RN! OR ELSE I DIE! DONT LET ME DIE!! LET ME SUCK SOME ROBO TITTIES!! HELP ME!!"

                                         - Elsa, probably

On a more seriouser note on uhhhh female robots, there isn't really any meaning to them outside of coomerbait I feels like.

**Comment by Coastfront** [comment]
Synthetics are gendered because they're given a human design to create an artifical, superior human being. They are expensive and built to have personalities.
IIRC, combat robots, are intended as a killing machine first, living creature second. 
Therein, what would be the logic in creating a female design for one?
For what purpose flows this effort, and for this effort is what fruit bore?
The real answer is to just remove pronouns from combat robots and assign them "it/that" given that they are genderless objects.
Each stone of a river is without distinction despite their shape, for there is no point defining them.

also this would just be inefficient for a factory line having a portion of the production lines making a differently shaped product for no reason and would forever be a plot hole muh lore

**Comment by Pariah919** [comment]
No

**Comment by grinkgo** [comment]
> The real answer is to just remove pronouns from combat robots and assign them "it/that" given that they are genderless objects. 

This is the correct answer

**Comment by Naaanii** [comment]
Add the sprites and kill the gender for robots.

**Comment by Starfirejordan** [comment]
image
I think this is fine

**Comment by Starfirejordan** [comment]
> I think they can just be different models of combat robot.

that basically what they are, but anyone can argue that it gendered robots since it uses F/M selection to chose the sprite used
so no matter how you really word it, it still gonna be "female and male robots"

**Comment by lbnesquik** [comment]
A little silly. I'm very neutral on this, because while this isn't catgirls tier, there isn't much reason to have it.

**Comment by aGhostCoder** [comment]
> Synthetics are gendered because they're given a human design to create an artifical, superior human being. They are expensive and built to have personalities. IIRC, combat robots, are intended as a killing machine first, living creature second. Therein, what would be the logic in creating a female design for one? For what purpose flows this effort, and for this effort is what fruit bore? The real answer is to just remove pronouns from combat robots and assign them "it/that" given that they are genderless objects. Each stone of a river is without distinction despite their shape, for there is no point defining them.
> 
> also this would just be inefficient for a factory line having a portion of the production lines making a differently shaped product for no reason and would forever be a plot hole muh lore
Hi I'm the artist, and first of all thank you for giving your feedback. I understand your concern, though disagree with it.
First of all the sprite already existed, I was just adding a visual difference. Will it matter? Probably not, because it'll be covered by a helmet anyways. 

I'll answer your questions, and some other's in the comments, by asking my own, because at the end of the day that really seems to be the focus: It's why.

**_Why do we need gynoids?_**
Why do we have female vat born soldiers? For what purpose? We don't need them, but we have them already.
For that matter why do we have different styles of vat born? Wouldn't they all be the same person?
All I know is that people argued it's because their primary focus is medical work, and/or work best in unison.

Asking the question of why can just lead into more questions of why, because robots don't exist yet. I can respond with: "Why are they humanoid, and not using motors to move?"
 
**_Well what if there's a plot hole in the lore?_**
We are an open-source community that actively makes bullshit up on the fly, our lore has constantly changed but here.
The lore reason I made up: Designed primary for medical and civilian work they were designed to look softer, though the only difference is that they're just smoother. They're just as effective, and usually the same, though some swear they're less impact resistant -- though such a fact is merely a rumor based on early prototype building. Some might why, but I just ask they made the original killing machine human-like to begin with. 

Also to lessen your worry those aren't meant to be breasts, it's meant to be smooth.
That's literally the difference. One is smooth, the other isn't.

**_But coomer bait_**
I tried everything in my power to avoid it being outright coomerbait: I used men as loose references, _which for TGMC might have been a mistake_, and attempted to focus only the smoothing the object itself.

**_What side am I on_**
Mecha is always cooler.

Anyways. Thank you all for your feedback, the reception has been divided though surprisingly more-so positive and while I think some of you are making mountains out of ant hills: I still appreciate you taking your time to interact and communicate.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Why is the robot's face white? make it the same color as the normal robot

**Comment by RaidarV** [comment]
It's okay I guess. I just don't want TGMC to go down the pipeline it has been going down for SO long.

**Comment by maikilangiolo** [comment]
> Why do we have female vat born soldiers?

because they are humans, and if they are clone soldiers, they are cloned from women. This is absolutely no stretch to think of, and the only issue (women are physically weaker and less fit for warfare) literally doesnt matter in a scifi universe where you got tech to bridge the gap.

Robots, on the other hand, are robots. Combat robots, to be specific, whose only reason to exist is combat. My turn to ask, "Why do we have female robot soldiers?" What is a female robot, is it a robot that has female human anatomy? It looks like it isn't. Is it a robot that has a different voice? It is a text-based game, so it can't be that either. Is it just the regular robot sprite but with a white mask, sloped torso to hint at breasts (south facing sprite) and a lighter shade of gray? 
So what's the purpose? I am not saying this will somehow harm the codebase, but it has no point in existing, or at least existing as a "female robot".

**Comment by aGhostCoder** [comment]
> -- scifi universe where you got tech to bridge the gap.
But that's exactly my point: Why bother? Why put in the effort? That's the issue with asking why that, or this, it's at the end of day just asking why when everything in a sci-fi universe could make you ask the same thing.
It was already in the code, I just made it look different. So outside of the loose lore reason I gave: There is no reason, beyond the outside fact someone might like it and someone might appreciate the fact it's not just literal copy paste anymore.

Also I changed the head, so no more white face.
png

**Comment by Coastfront** [comment]
> I find it funny how no matter what your opinion on these sprites are, you will never actually see them unless someone decides to be naked
Otherwise known as each and every single time you spawn in the round at the start and see every other marine naked until they vend loadouts, so extremely often.

**Comment by bluezorua** [comment]
> > I find it funny how no matter what your opinion on these sprites are, you will never actually see them unless someone decides to be naked
> 
> Otherwise known as each and every single time you spawn in the round at the start and see every other marine naked until they vend loadouts, so extremely often.

most people will rush to the loadout vendor and get fully equipped in less than a 45 seconds, this PR is just a joke and you will probably only notice these sprites unless you look out for them

**Comment by Licherr** [comment]
> I think they can just be different models of combat robot.

This should just be an alternate model, not female or male, just make them different models of robot.

**Comment by shelteredfreak** [comment]
The liberals are turning our robots effeminate! First the corpsman, now this!

In all seriousness, this is a net positive addition so I approve

**Comment by Licherr** [comment]
Outright you shouldn't have put the 'Female' or Gynoid world for it, you could've ignored all of this if you had just say "alternate" model. Then we would've all gotten this speedmerged without any opposition.

**Comment by ZahaSanko** [comment]
More controversial that stealth merge of imager deletion

**Comment by lKiseki** [comment]
image

**Comment by ilikesaying** [comment]
image

**Comment by Luxyboo** [comment]
aint no way yall actually up in arms about this

**Comment by revelation-8468** [comment]
image

**Comment by ClosetedSkeletonGH** [comment]
It really doesn't even look good, it just feels like needless sexualization, especially with the constant trope in sci-fi to make 'sex-bots'/'fem-bots' in order to translate women into tools for men to use. 

It just feels kinda nasty for  **robots that had a very non-binary, objectish human design to get assigned the male gender, and then ontop of that we get a "same robot but with booby so its woman".**

Part of the theme'ing of Combat Robots is that they are reduced into the basics of what one needs for war, two legs to move, two arms to shoot, and a head to see out of. If TGMC needed less they would have less. 

I would love for robots to get different models, but if the only change is just gendering robots, it doesnt feel good at all. Robots were NB and not male before, they do not need gender, they are tools of war.

**Comment by ClosetedSkeletonGH** [comment]
> . Why do we have female vat born soldiers? For what purpose? We don't need them, but we have them already. For that matter why do we have different styles of vat born? Wouldn't they all be the same person?

Again, female vat born soldiers are clones of human women. We have human character representation, pretty much anything you want, and women are in the military plenty.

There is no clone soldier lore, they could all be of one person, or they could be the DNA of any number of people just given some random smucks body.

**Comment by aGhostCoder** [comment]
> I would love for robots to get different models, but if the only change is just gendering robots, it doesnt feel good at all. Robots were NB and not male before, they do not need gender, they are tools of war.

Okay, just to clarify and hopefully prevent future comments like this. You do realize you can already gender your robots right now? That literally all this does is replace the pre-existing f_states for head, torso, and groin. That's it. It's just a re-sprite.
Should robots have genders? _I don't care_, but they exist already. That's it.

**Comment by bowlofcereal** [comment]
61vdh8

**Comment by Tupinambis** [comment]
Not a fan of the sprites tbh. The idea isn't bad per se but this isn't the best execution.

**Comment by Davidththird** [comment]
titan fall 2 all over again

**Comment by Starfirejordan** [comment]
sad

**Comment by Pariah919** [comment]
To be actually serious, this shouldn't happen from a setting perspective. Cheap combat robots having gender makes little sense as well as synth gender which also makes little sense, but is doubtful to change unless someone goes out of their way to do it.
Female robits make no sense, and shouldn't probably happen. As funny as this PR is it shouldn't be merged.

**Comment by helper-2** [comment]
I have some idea why female robots isn't that much absurd implementation. While we don't have any lore related to robots specifically, we do know that their numbers are pretty much low. Like, they are beraly 8% of total amount marines in round. That implies, that demand in combat robots don't matchup with it production speed.
Two possible things can explain that. First, combat robots is a newest product, which is only start to implement in TGMC, (that's not explain why robots required to be at least 18 old). Second, robots wasn't build for combat, they had been converted, because war with xeno start going off the rails too much and that's mean, that previously they were civilian utility robots and some of them were specifically designed to be female like carcass. So having female robot in TGMC isn't much absurd, because previously she was female law enforcer robot, or i don't, some different job wich required being 18 old 😏

**Comment by chizzy376** [comment]
Why do we need to give robots genders? It hasn't been an issue up until now and it still isn't.

**Comment by Al-1ce** [comment]
>synth gender which also makes little sense, but is doubtful to change unless someone goes out of their way to do it.


Unlike regular machines, synths are **designed** to appear more human/less freaky. Combat robots are the direct opposite.

**Comment by TiviPlus** [comment]
but why

**Comment by ilikesaying** [comment]
> I have some idea why female robots isn't that much absurd implementation. While we don't have any lore related to robots specifically, we do know that their numbers are pretty much low. Like, they are beraly 8% of total amount marines in round. That implies, that demand in combat robots don't matchup with it production speed.
> Two possible things can explain that. First, combat robots is a newest product, which is only start to implement in TGMC, (that's not explain why robots required to be at least 18 old). Second, robots wasn't build for combat, they had been converted, because war with xeno start going off the rails too much and that's mean, that previously they were civilian utility robots and some of them were specifically designed to be female like carcass. So having female robot in TGMC isn't much absurd, because previously she was female law enforcer robot, or i don't, some different job wich required being 18 old 😏

Girls Frontline Lore

**Comment by aGhostCoder** [comment]
> To be actually serious, this shouldn't happen from a setting perspective. Cheap combat robots having gender makes little sense as well as synth gender which also makes little sense, but is doubtful to change unless someone goes out of their way to do it. Female robits make no sense, and shouldn't probably happen. As funny as this PR is it shouldn't be merged.

You are the lore master, so I won't be upset if this gets declined by Kuro.
I will admit it's impressive this is currently the third most commented pr, and even funnier when you realize it's incredibly pointless.

**Comment by Licherr** [comment]
Just ditch gender based robot modules, reuse and make new models of the robots just like how we have normal synths and early synths.

-  As some has said already, there is **no need or overwhelming desire** to have the robots gendered or "sexualized". Ghost already said that the intent was to add an alternative, but knowing the devious ss13 players the addition of a gynoid is a fucking double-edged sword. 
- Elsa really did a number when he decided to name the pr as an **"Female" Combat Robot** instead of a simple **Alternate Combat Robot Model** . Truly the biggest blunder of all the PRs this year.

**Comment by ilikesaying** [comment]
103D1345-4093-4C99-A0B9-7AC16F96739C

**Comment by srxtreme** [comment]
Salt PR?

**Comment by Kuro020** [comment]
We have arrived, and it is now that we perform our charge. In fealty to the God-Maintainer, our undying Coder, and by the grace of the Github Throne, I declare Exterminatus upon the Female robots. I hereby sign the death warrant of an entire PR, and consign a million fembots to oblivion. May Maintainer Justice account in all balance. The Head coder Protects.

**Comment by Kuro020** [comment]
In all seriousness, I would've merged this since when I resprite robot armor the base sprite wont ever be seen again, but I cant trust you lot to not make me regret merging female robots so I condmen it to oblivion

**Comment by Licherr** [comment]
warhammer-40k

**Comment by AtlasRules** [comment]
Some may question your right to destroy ten hundred fembots. Those who understand know that you have no right to let them get merged.

**Comment by aGhostCoder** [comment]
I cannot trust TGMC players to not make me regret merging female robots, I would've merged it if not for the heretic. - Kuro

This fucking pr was a wild ride, and I'm glad it's over.

**Comment by ClosetedSkeletonGH** [comment]
> > I would love for robots to get different models, but if the only change is just gendering robots, it doesnt feel good at all. Robots were NB and not male before, they do not need gender, they are tools of war.
> 
> Okay, just to clarify and hopefully prevent future comments like this. You do realize you can already gender your robots right now? That's literally all this does, it replaces the pre-existing f_states for head, torso, and groin. That's it. It's just a re-sprite. Should robots have genders? _I don't care_, but they exist already. That's it.
> 
> edit: Would I like to add an additional line? Sure. Would I like to add additional armor-sets for robots, once again yes. But unfortunately that requires code, code that would be redundant, and permission. I wanted to add more accessories for combats robots but currently that's not possible from what I understand. So I used what we already had to create another line on something that was a literal same sprite.
> 
> I appreciate your concern, and thank you for giving us your opinion.

This is some of the easiest stuff there is to code, I’ll code literally any new armor PR for you

**Pull request closed without merging**
