### PR TITLE
Flamethrower Rework

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
reworks the flamethrower to be like a proper flamethrower, fire burn time significantly decreased so if you want area denial your gonna need to constantly expend ammo deletes nozzles and flamethrower code also reworks the mech flamethrower to also be like this deletes x fuel and replaced with new flamethrower that fires x fuel but uses normal flamethrower tanks

todo: make bounce projectiles actually work, get a new flamethrower sound and finish my overheat mechanics pr to apply it here

https://user-images.githubusercontent.com/98577688/203898713-7ae7d7a3-64ba-427e-b57e-4ac300425652.mp4

https://user-images.githubusercontent.com/98577688/203898734-d2a8fe60-b3b7-4d20-b912-165c8493d140.mp4

## Why It's Good For The Game
more fun flamethrower gameplay, flamethrower will require more ammo management

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
This is cool and all, but you're burning extremely fast through your fuel in these videos. I'd recommend increasing the maximum amount of fuel contained in the available fuel container options.

**Comment by novaepee** [comment]
IT'S HERE
IT'S FINALLY HERE

WE CONTINUE TO BEAT CM IN GAME DESIGN AND MECHANICS

**Comment by MereWalker** [comment]
Hrrrrng. I love my flamer. I'd love to keep an eye on this development. Maybe it will resurrect my old flamer ways.... Maybe.

**Comment by maikilangiolo** [comment]
The damage against resin walls needs to be adjusted if you lower the burn time.

**Comment by Al-1ce** [comment]
Removing area denial from flamers completely is bad.

**Comment by Coastfront** [comment]
My criticism of this: 
These arent flamethrowers, these are just incendiary firearms.

I acknowledge that current flamethrowers need to be reeled in: though I do not believe this is through removing their current role.
The lingering flames are a nonfactor, unless if they have CONSTANT application they last effectively no time at all.

My 2 cents on the flamethrower issue is still that seemingly most of the current problem became exemplified with the fuckin wide nozzle, which turned the flamethrowers from "it takes a few shots to cover a maze" to "Instantly fucking destroys everything infront of it in one shot".
I feel the main issue lays not in the fact of how lingering flames work, but that it is currently too easy to apply them en masse.

**Comment by Skatuk** [comment]
Everything looks good but I don't like the fact that the flames bounce of objects maybe remove that and then it will act like a flamethrower.

**Comment by Strayed-Raven** [comment]
fire damage isnt that critical. This is just about the walls huh?

**Comment by xarsak** [comment]
this looks sick

**Comment by Serxule** [comment]
ok, here's the thing, there's GAS flamethrowers, and LIQUID flamethrowers, almost all of our current ones are LIQUID flamethrowers, hence area denial.

**Comment by SplinterGP** [comment]
just add more flamethrowers instead of reworking old ones, then its based, also do a flamethrower that penetrates targets but fires slowly.

**Comment by Al-1ce** [comment]
### Area Denial
As a flamer you are a _VERY_  high-priority target. By sacrificing gunplay for efficiency, you are easily overwhelmed. Putting distance between you and the xenos is **critical** to long-term survival. Period.

### Damage
Flamers are meant to be offensive weapons. That's a given. So, when we look at why flame causes xenos to bounce back, you need to understand something: It has less to do with the actual damage produced, <sub>(of which is very minimal)</sub> and more to do with discouraging xenos to push any further.

Flamethrowers are not offensive weapons because of their damage outout. The primary function, outside of removing resin structures, is area denial. It is the most efficient way to poke and harass the hive while giving the rest of your team an edge when it comes to mazes.

### So?

I like this. I like the idea of this. I think an incendiary type weapon with a larger focus on raw damage is a great idea. But removing the base flamers - which are one of the only ways to effectively clear a maze is beyond silly. You said it yourself - if you intend to clear mazes with these, you'll need to constantly expend ammo.

I'm not sure if you took the time to consider that this might buff xenos considerably. Mowing down mazes can be a chore. There really is no need to make it next-to-impossible outside of wasting OBs/bayoneting until your mouse implodes.

### Because of this...
I think it would be a good idea to impliment these seldom as a sort of unique alternative to the current ones we have, rather than deleting the latter entirely. ~~Might be noteworthy to throw in that it would make a really cool item for engineers, too.~~

**Comment by FosterGrime-Heymynameslouie** [comment]
https://user-images.githubusercontent.com/59080633/204764071-4a825497-bc43-4ba4-be60-f70a2a5813bb.mp4

aylmao isolation flamethrower my beloved

**Pull request closed without merging**
