### PR TITLE
Broken Man but Fixed (Greyscale Hair!)

### PR DESCRIPTION
**Pull request by Wirpy**
## About The Pull Request

Adds greyscale functionality for hairs and beards as a means to fix the broken man beard we imported from TG which was imported without the eye part due the importer not knowing how to go about doing it. 
With the usage of greyscale I have managed to make it so the eye part is uncolorable while the beard remains colorable. 

These additions and changes adds a base and makes it substansially easier for anyone wishing to contribute in the future to the greyscale functionality for any hairstyles or beards they may so desire to make. 

I have also left the old broken man sprite so everyone can remain happy with the addition of the correct ''new'' one. 
It has been re-named to rough man.

Thanks to Lumi for telling me about greyscale and to hyper for helping me make the code and all. 

## Why It's Good For The Game

-Fixes a sprite so it's the way It's intended to be
-Keeps the old one so now we have two beards for the price of one!
-Greyscale functionality for hair and beards is coded in this PR so It'll be very straightforward and easy for anyone else who wishes to utilize greyscale for a hair or beard. (Thanks to hyper!) 
-Epic new cool unibrow and in greyscale colours wow!

1b484c1450b62920b2db14e2e8813e54
733f3c12d9ef0a18893d5a6d1ca589fd
db036f4b24bfaa6f4dfb1e28d2aaaffd
36b95c0f31bda1ede2aad5e1a1ee121f

## Changelog
:cl: wirpy
fix: broken man sprite
imageadd: Broken man greyscale sprite + seperate uncolorable eye part
add: re-named old broken man sprite to ---> rough man
config: broken man and general hair section added to greyscale config
add: greyscale json for broken man
add: greyscale functionality to hair & beards in update_icons.dm
add: broken man & rough man to sprite_accessories.dm 
add: greyscale var to  sprite_accessories.dm 
/:cl:

### CODE REVIEW

**Comment by hyper2snyper** [comment]
0/10, unbalanced af. did you even test this. i hate coders who never play the game ruining balance.

**Review by hyper2snyper — APPROVED** [review]

**Comment by Wirpy** [comment]
> 0/10, unbalanced af. did you even test this. i hate coders who never play the game ruining balance.



Im worse, I'm a jannie

**Review by Kuro020 — APPROVED** [review]

**Comment by ivanmixo** [comment]
Kinda weird you only did it for just this one hairstyle

**Comment by Wirpy** [comment]
> Kinda weird you only did it for just this one hairstyle

Well I wanted to fix the broken man beard so I did, if someone else wants a hairstyle to use greyscale now the framework is all there and ready to be used for it. I just wanted the funny unibrow and no one else will fix it. 

If someone wants a hairstyle to use greyscale now It's as easy as replacing the old sprite+adding it to the greyscale config and a json.

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
