### PR TITLE
Mp holster in clothing vensor, smg25 holster in seasonal

### PR DESCRIPTION
**Pull request by maikilangiolo**
## About The Pull Request
Adds the two holsters for the mp and seasonal smg

## Why It's Good For The Game
Drip, i guess, and in the case of the smg25 something to carry it and make it worth it over the p90, which is generally better all around.

## Changelog
:cl:
add: added holsters for the mp19 and smg-25
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
unsure as to how this would go down with people who get dunked on constantly by the machine peestol people but having unusued guns finally be used, and having the SMG section finally not only being comprised by p90 (the machine pistol dosent count) is cool

**Comment by maikilangiolo** [comment]
> unsure as to how this would go down with people who get dunked on constantly by the machine peestol people

actually changes nothing. the MP is only good when dual wielded, and this would only let you carry one without any ammo to boot. If someone choose to carry a single one, and likely with a stock since they wont dual it, this holster is a valid choice, if only for the drip.

**Comment by Lumipharon** [comment]
MP19 fits in the belt slot already, the holster is purely decorative, and for the whoosh sound.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
No SMG-25/holster for it we have seasonals for it already

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
