### PR TITLE
Stun changes part 4 - warrior

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Stuns bad, time to kill some CC

PART 4-
Warrior

NERFS
Fling stun time halved

Compensation (If any)
Warrior is fine as it is, it has decent stats and decent overall stuff. I could give it more health I guess, but run makes it incredibly safe.

## Why It's Good For The Game
Stuns bad, death to the stuns.
Read compensaton.

## Changelog
:cl:
balance: Warrior fling time halved
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -66. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by joookschad** [comment]
>Warrior is fine as it is,
Maybe fix lunge code first.

**Comment by MiniMeatwad** [comment]
er

**Comment by SplinterGP** [comment]
> > Warrior is fine as it is,
> 
> Maybe fix lunge code first.

wyci.

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-69). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
