### PR TITLE
TL127 can now fit magnetic harness and motion sensor. Scope moved to barrel attachment.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
image
image
TL-127 now can fit Magh and Tac sensor.
Technically, the scope is now a "barrel attachement" and by doing this PR I discovered barrel attachments don't fit on anything, not even the *Mateba* which was the last thing to use them. I might just remove snubnose Mateba.
## Why It's Good For The Game
Makes TL-127 more useable overall, in my opinion and gives it a gimmick, considering its bad in CQC, this makes sense as a change.
## Changelog
:cl:
balance: SR-127 can now fit a magnetic harness and motion detector.
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
oh my god MJP

**Comment by Al-1ce** [comment]
Uhhh.. what?

**Comment by Lumipharon** [comment]
??

**Comment by Naaanii** [comment]
Just no, lol.

**Comment by Losenis** [comment]
"Makes it more usable" makes scope mutually exclusive with extended barrel and barrel charger

my brother in christ if you want a funny melee range sniper just give mosin magharn since it can already fit rds and bayo anyway

**Comment by Etrnlmelancholy** [comment]
Why when we have DMR?

**Comment by Losenis** [comment]
Also doesn't the 127 have atrocious minimum range that makes it the one gun you absolutely don't want to use at ranges that'd make you swap the scope for magh/sensor?

**Comment by Naaanii** [comment]
> Also doesn't the 127 have atrocious minimum range that makes it the one gun you absolutely don't want to use at ranges that'd make you even consider magh/sensor?

Yes.

**Comment by Jordanstolethepreciousslam** [comment]
MJP what are you on

**Comment by Pariah919** [comment]
> "Makes it more usable" makes scope mutually exclusive with extended barrel and barrel charger
> 
> my brother in christ if you want a funny melee range sniper just give mosin magharn since it can already fit rds and bayo anyway

This isn't even correct in any way, barrel attachments are different from that slot.

**Comment by Losenis** [comment]
If it's actually a different slot then ignore what I said, my bad. Point still stands, mosin would probably be better to give magharn to for a sniper.

**Comment by KrabSpider** [comment]
C300A20D-7C52-4CF3-A13A-B5FCC9BDDB79

**Comment by Araulius** [comment]
what universe are you living in, where you need a mag harn for your rifle that shoots two screens away? If you are getting bonked with this gun, you deserve it. position yourself better.

**Comment by usnpeepoo** [comment]
What the hell is this title”scope moved to barrel slot”
Bro what

**Comment by TiviPlus** [comment]
The bullet goes through the scope and the magnifier makes it bigger its that easy people come on

**Comment by Al-1ce** [comment]
MJP logic strikes again it seems

**Comment by Pariah919** [comment]
> What the hell is this title”scope moved to barrel slot” Bro what

barrel slot is literally right there and making an entire scope attachment slot for the tl127 seems redundant when this accomplishes the same goal

**Comment by Lumipharon** [comment]
> > What the hell is this title”scope moved to barrel slot” Bro what
> 
> barrel slot is literally right there and making an entire scope attachment slot for the tl127 seems redundant when this accomplishes the same goal

Why does it need it though? This is an actual sniper rifle, and you're giving it attachments to help it at close range.

**Comment by Al-1ce** [comment]
> barrel slot is literally right there and making an entire scope attachment slot for the tl127 seems redundant when this accomplishes the same goal

I think you fail to see the purpose of a sniper rifle.

**Comment by Notamaniac** [comment]
> what universe are you living in, where you need a mag harn for your rifle that shoots two screens away? If you are getting bonked with this gun, you deserve it. position yourself better.

I mean there is a universe where this exists. Sometimes you'll get pounced on the back lines, and sometimes the front line gets pushed back simulatenously, meaning you don't have an opportunity to grab your gun before xenoes are all over it. 

Though I agree, that situation doesn't happen often and most of the other times you're getting bonked for poor positioning. I think that should be a weakness of the sniper rifle, and that you bring another weapon/side arm to compensate for it.

The tac sensor being essentially a free addon without any stat downsides might also be an issue since the tac sensor might sub as a ghetto optical scanner to see xenoes in the dark, though the delay between pings and the inability to see turfs might be enough of a tradeoff. Especially since I can't remember if the tac sensor is limited by range, or what you can currently see on the screen.

**Comment by KrabSpider** [comment]
> The tac sensor being essentially a free addon without any stat downsides might also be an issue since the tac sensor might sub as a ghetto optical scanner to see xenoes in the dark, though the delay between pings and the inability to see turfs might be enough of a tradeoff.

It has a range of 16 tiles IIRC.

**Comment by Pariah919** [comment]
interest doesn't seem to be here, honestly

**Pull request closed without merging**
