### PR TITLE
Reduces the healing effectiveness of Russian Red

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title.

## Why It's Good For The Game
I am going to be very honest with you, I tire of writing the exact same thing in different words and dealing with balance in general so just refer to "Why it's good for the game" in PRs #14170 and #14061.

## Changelog
:cl: Lewdcifer
balance: Halves the healing effectiveness of Russian Red.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Wuh, this is just the same as doubling the cloneloss, only now its also twice as dose inefficient.

**Comment by Derrick2Electricboogaloo** [comment]
When he remakes the same PR but with different wording.

**Comment by Al-1ce** [comment]
Xope.

**Comment by efzapa** [comment]
mfw xope PR 
kept the CL the same too, this literally probably makes a min-maxed BKTT mix better lmao

**Comment by technicianman** [comment]
halve the cl gain aswell then otherwise this is the same pr as the cl increase one

**Comment by ivanmixo** [comment]
Think 30% less heals would be more fair with the limb heal thingy PR.

Reasoning being xenos have a 30% chance to hit a limb other than the one they're aiming for, so it should probably even out.

**Comment by lKiseki** [comment]
> Think 30% less heals would be more fair with the limb heal thingy PR.
> 
> Reasoning being xenos have a 30% chance to hit a limb other than the one they're aiming for, so it should probably even out.

Donezo.

**Comment by zzurge** [comment]
Xopium

**Review by ivanmixo — APPROVED** [review]

**Comment by Lumipharon** [comment]
The cloneless should be scaled down as well. But really this is just indicative of RR being extremely plentiful and accessible.

**Comment by TiviPlus** [comment]
lumi why is this dnm

**Comment by yyzsong** [comment]
Change CL stinky

**Pull request closed without merging**
