### PR TITLE
Inventory defines changes.

### PR DESCRIPTION
**Pull request by Ghommie**
Delivered in a more atomized version as requested.

### CODE REVIEW

**Comment by spookydonut** [comment]
Please explain why, is this code quality or just renaming for the sake of it?

**Comment by Ghommie** [comment]
I'm renaming the defines to /tg/station's, reason being this is of the same repo group.
Plus the naming pattern is more consistent and those other minor quality bitflags improvements.

**Comment by DominikPanic** [comment]
Conflicts.

**Comment by DominikPanic** [comment]
Conflicts.

**Pull request merged**
