### PR TITLE
nerf combat droid speed

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

title

## Why It's Good For The Game

mjp mood

It can run faster than a combat robot, which I find amusing. Since xenomorphs cannot stun a speedy machine like this and it is for free for AI players to use, something free like this shouldn't be a better combat robot.

## Changelog

:cl:
balance: nerf combat droid speed
/:cl:

### CODE REVIEW

**Comment by Starfirejordan** [comment]
at first i was gonna say salt PR because of how easy it is to kill the droid, then I saw it in action when used proper... yea i saw a speed nerf would be good

**Comment by Lumipharon** [comment]
I'd rather you make it vulnerable to CC first in some respect.

**Comment by Coastfront** [comment]
I feel like adding damage slowdown + vulnerability to crowd control would conserve its ability to get to the front lines quickly, while also making it less egregiously overpowered.

**Comment by srxtreme** [comment]
Salt PR?

**Comment by Tupinambis** [comment]
I agree with adding stunnability but that might be hard to code in so this works too.

**Comment by ZahaSanko** [comment]
give it the Liguana treatment. Overnerf and forget it exist, you know the classic

**Comment by Ragecrabbo** [comment]
Salt PR, also how did it take THIS long for a droid nerf?

**Comment by Zambie-Tron** [comment]
salt PR

**Comment by FosterGrime-Heymynameslouie** [comment]
this came into fruition entirely because of jasmine lol

**Comment by yyzsong** [comment]
salt PR

please merge this immediately.

**Comment by Beepinex** [comment]
"salt pr"
signed, 95% alive time squad marine

**Comment by Strayed-Raven** [comment]
And here we go again

**Comment by Xander3359** [comment]
Salt PR
Please merge :)

**Comment by chizzy376** [comment]
Thank the heavens, the speed is way too high.

**Comment by novaepee** [comment]
lumi wants more than this, and i'm not a capable contributor to add those features

**Pull request closed without merging**
