### PR TITLE
Adds widescreen.

### PR DESCRIPTION
**Pull request by BeloneX**
## About The Pull Request

Adds widescreen mode.

## Why It's Good For The Game

Most servers have this nowadays, so I'd say it's better to get rid of the scoliosis inducing head tilt of 15x15, I added a preference for anyone that wishes to remain at 15x15

## Changelog
:cl:
add: Added widescreen mode.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by SplinterGP** [comment]
cursed, affects balance

**Comment by Hughgent** [comment]
a screenshot of it working please.

**Comment by BeloneX** [comment]
> a screenshot of it working please.

https://streamable.com/lj9q3s

**Comment by Hughgent** [comment]
Nice in theory, but as I'm told, the increased mapTick lag from the additional tiles will be a big performance hit.

Keep this in your back pocket though, maybe things will improve in the future.

**Comment by TiviPlus** [comment]
Unfortunately I'm going to have to deny this
The reasons being:
A) Balance: Marines get a bump in vision range, which puts xenos at a disadvantage
B) Gameplay: Left to right fighting is now vastly preferable which means xenos are advantaged NS and marines are advantaged EW which gets wonky fast
C) Performance: Maptick is a thing, and increasing vision range makes it laggier

---aaand hugh closed it

**Pull request closed without merging**
