### PR TITLE
Delete clown paraphernalia from maps

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Players should not be getting ahold of meme equipment without admin intervention

## Changelog
:cl:
del: Delete clown paraphernalia from maps
/:cl:

### CODE REVIEW

**Comment by Walarks** [comment]
I feel like this reduces RP potential and immersion as, while rare, such items are usually present in the facilities where most of the battles take place. This would make it seem like there were no actual humans at the artificial facilities on the maps, despite the corpses laying around, thus hurting the atmosphere that enables engaging roleplay.

**Comment by Ragecrabbo** [comment]
Literally 1984

**Comment by BraveMole** [comment]
This PR violates github rules

**Comment by bowlofcereal** [comment]
No

**Comment by Licherr** [comment]
f4b

**Comment by turnop** [comment]
1984

**Comment by Texicos** [comment]
The people don't want it but it will probably get merged cause we can't have fun. It's MRP not HRP

**Comment by SplinterGP** [comment]
~~1984~~

**Pull request merged**
