### PR TITLE
Changes most shipside chairs and tables to not drop metal when deconstructed

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Title.
I'm mostly doing it on behalf of Elsa, I don't care much one way or another personally.

## Why It's Good For The Game

On some ships you can get 300+ metal by deconstructing chairs and tables, I know because I've done it on occasion myself. This probably shouldn't be a thing that happens and it makes balancing based on metal availability harder.

## Changelog
:cl:
balance: Most shipside chairs and tables no longer drop metal on deconstruct
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
image

**Comment by Derrick2Electricboogaloo** [comment]
It is a no from me >:(

**Comment by Durbles** [comment]
It's potentially a lot of metal, but it's extremely tedious to gather, takes a long time and then you still need to find a way to get it groundside where it can be used.

Me no like proposed change.

**Comment by RipGrayson** [comment]
There's about 20 minutes before the Alamo can leave for the planet. Why should marines bother with req or buying metal from their vendors when they can get just as much from deconstructing chairs and tables?

Yesterday, I have it on good authority that in **less than 30 minutes** the chairs on the Minerva were all gone, deconstructed and sent groundside. 

> It's potentially a lot of metal, but it's extremely tedious to gather, takes a long time and then you still need to find a way to get it groundside where it can be used.

The logistics of gathering and getting metal groundside aren't difficult, just stuff it into a crate and have req send it down. Alternatively, use the time before Alamo leaves, stuff it into a crate and send it down with the ship.

**Review by BraveMole — APPROVED** [review]

**Comment by BraveMole** [comment]
> It's potentially a lot of metal, but it's extremely tedious to gather, takes a long time

So a shitty mechanic then ?

**Comment by Derrick2Electricboogaloo** [comment]
> There's about 20 minutes before the Alamo can leave for the planet. Why should marines bother with req or buying metal from their vendors when they can get just as much from deconstructing chairs and tables?
> 
> Yesterday, I have it on good authority that in **less than 30 minutes** the chairs on the Minerva were all gone, deconstructed and sent groundside.
> 
> > It's potentially a lot of metal, but it's extremely tedious to gather, takes a long time and then you still need to find a way to get it groundside where it can be used.
> 
> The logistics of gathering and getting metal groundside aren't difficult, just stuff it into a crate and have req send it down. Alternatively, use the time before Alamo leaves, stuff it into a crate and send it down with the ship.

They do not. It usually is ONE st, or CSE, or one engineer. I have never seen this so called collective effort from marines to gather metal in the beginning.

**Comment by Derrick2Electricboogaloo** [comment]
LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAME

**Pull request merged**
