### PR TITLE
Gives the AI proper access to the chem master

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
The wiki describes the AI as being able to use pretty much any machines. 

## Why It's Good For The Game
This PR makes the AI closer to being able to use any machines.
Balance is minimal given you still lack hands to put things in, so humans are still needed.

## Changelog
:cl:
qol: made the AI able to use the chem master. or at least, access it.
/:cl:

### CODE REVIEW

**Comment by GradusNL** [comment]
> Balance is minimal given you still lack hands to put things in, so humans are still needed.

I wouldn't call it minimal, since this allows those without the proper skills to bypass the delay introduced by #7821.
This is the third balance PR you introduced during the balance freeze. (See #7944 and #7945)
They might all have QoL elements, but despite that they do affect balance and should get the balance label.

**Comment by lbnesquik** [comment]
> 
> 
> > Balance is minimal given you still lack hands to put things in, so humans are still needed.
> 
> I wouldn't call it minimal, since this allows those without the proper skills to bypass the delay introduced by #7821.

In practice, it is not going to affect balance. At all. In all of my play time of AI, i haven't had anyone ask me to use the chem master once. And even with access, it is still clunky as fuck to use this with another player compared to simply getting access. 

> This is the third balance PR you introduced during the balance freeze. (See #7944 and #7945)

Well i put the PR's whenever i want. What's the big deal? They'll get to it afterward. 

> They might all have QoL elements, but despite that they do affect balance and should get the balance label.

Minimally for each of them.

**Comment by Losenis** [comment]
>this allows those without the proper skills to bypass the delay introduced by #7821

That'd take such a stupidly high level of coordination for the average TGMC unga that it might as well be its own reward.

**Comment by GradusNL** [comment]
> 
> 
> > this allows those without the proper skills to bypass the delay introduced by #7821
> 
> That'd take such a stupidly high level of coordination for the average TGMC unga that it might as well be its own reward.

I agree, but using such a word as reward means that this is a balance PR, not a QoL PR. I didn't comment on **how** balanced this PR is, only that it **is** balance.

**Comment by Losenis** [comment]
"but using such a word as reward"

Bro are you gonna argue semantics for a word I put there for lack of a better one

**Review by David-Stormwell — APPROVED** [review]
Approved from a balance standpoint.
Not like the AI can do much anyways, and if it wants to help Marines in low-pop to avoid the slowdown that's fine.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
