### PR TITLE
Fixes missing area on big red office.

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull Request
Fixes this:
image
## Changelog
:cl:
fix: [Big Red] One of the office variants now doesn't have a hole in the roof.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
does the area that tile is currently in have another apc? this seems like an intentional (if somewhat dumb) workaround to have an apc for outside be... inside.

**Comment by Barnet2** [comment]
This was intentional by Grayson to have the outside lights be controlled by an indoor APC. I would recommend you talk to him on Discord about it, since there are multiple of these, not just the office one.

**Comment by Lumipharon** [comment]
The current solution is also frankly not good, and is very hacky. There should really be a coded solution to hard set an apc to a particular area thats its not physically in.

**Comment by Helg2** [comment]
Oh well, kek

**Pull request closed without merging**
