### PR TITLE
Buffs builder caste door build speed

### PR DESCRIPTION
**Pull request by Sebbe9123**
## About The Pull Request

This PR aims to buff the build speeds of doors a slight bit as myself and others have found that building as a xeno is pretty tedious and not fun, to the point where (I at least) try to avoid doing it.
[https://i.imgur.com/kZoobRh.gif](url) NEW SPEED

[https://i.imgur.com/y7O2bn2.gif](url) OLD SPEED

## Why It's Good For The Game
Makes building slightly less tedious so drones and hivelords can go on and do other duties like healing damaged benos.

## Changelog
:cl:
qol: Xeno caste that can build can now build doors at 33% faster.
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
It's to prevent door spam before shutters open. I'm not convinced by the pr, the building time doesn't matter much if you are not actually spamming doors

**Comment by Sebbe9123** [comment]
> It's to prevent door spam before shutters open. I'm not convinced by the pr, the building time doesn't matter much if you are not actually spamming doors

The end goal is to make building less unfun for the average player, not the drone or hivelord mains. When I asked on discord it was doors that was mostly brought up. I'm totally open for suggestions if you got any!

**Comment by BraveMole** [comment]
> > It's to prevent door spam before shutters open. I'm not convinced by the pr, the building time doesn't matter much if you are not actually spamming doors
> 
> The end goal is to make building less unfun for the average player, not the drone or hivelord mains. When I asked on discord it was doors that was mostly brought up. I'm totally open for suggestions if you got any!

make doors faster to build, more expensive in plasma?

**Comment by Sebbe9123** [comment]
> > > It's to prevent door spam before shutters open. I'm not convinced by the pr, the building time doesn't matter much if you are not actually spamming doors
> > 
> > 
> > The end goal is to make building less unfun for the average player, not the drone or hivelord mains. When I asked on discord it was doors that was mostly brought up. I'm totally open for suggestions if you got any!
> 
> make doors faster to build, more expensive in plasma?

They already cost 3x the base amount anything else costs, which I belieeeve is 225 since base amount is 75, this can be seen on line 319-320 of the same file I edit in this PR.

**Comment by lbnesquik** [comment]
I approve of this PR.
 Doors are weaker than walls, which themselves aren't THAT sturdy. Even with the whole 'can open' part, they still take too long to buikd

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
