### PR TITLE
Lights no burn robot hands

### PR DESCRIPTION
**Pull request by grinkgo**
## About The Pull Request

Robots and robot limb users can remove powered light tubes.

## Why It's Good For The Game

Robot cannot wear glove, but why robot get burn from light bulb when hands made of metal?

## Changelog
:cl:
qol: A revolutionary heat-dispelling steel alloy now allow combat robots and those with prosthetic limbs to remove powered light bulbs without fear of burning their hands!
/:cl:

### CODE REVIEW

**Comment by QualityVan** [comment]
Could make this a check on whether the active hand is robotic rather than the mob as a whole so it works with prosthetics.

**Comment by grinkgo** [comment]
> 

Amazing that such an oversight has existed this long. I will look into that

**Comment by Lumipharon** [comment]
> Could make this a check on whether the active hand is robotic rather than the mob as a whole so it works with prosthetics.

Do this.

**Comment by Al-1ce** [comment]
Another game-destroying balance wrecking buff that will surely turn the tides of winrate.

<sub> I approve. </sub>

**Comment by grinkgo** [comment]
> > Could make this a check on whether the active hand is robotic rather than the mob as a whole so it works with prosthetics.
> 
> Do this.
I am actually unsure how to check for robo limb

**Comment by GreatKingWombat** [comment]
> > > Could make this a check on whether the active hand is robotic rather than the mob as a whole so it works with prosthetics.
> > 
> > 
> > Do this.
> 
> I am actually unsure how to check for robo limb

I think that would have to be handled roughly the same way the code checks if you're wearing gloves a few lines up.

**Comment by grinkgo** [comment]
I'm not sure if I'm doing it correctly, but it's tested to work and even behaves different if you use a non-prosthetic limb. PLEASE tell me if I'm doing something wrong

**Comment by QualityVan** [comment]
Looks good to me.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
