### PR TITLE
Survivor armor now has bio protection

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Whoever made this forgot to add bio protection to it for some reason.

## Why It's Good For The Game
survivor man never had bio armor for some reason. He should now.

## Changelog
:cl:
balance: Survivor armor has bio protection now.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -11. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
> You currently have a negative Fix/Feature pull request delta of -12. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
>
nice

**Comment by psykzz** [comment]
Was intentional kek https://github.com/tgstation/TerraGov-Marine-Corps/pull/3290/files#diff-1449b9cadfbf0b181a5640e4cf2a36f0

**Comment by Pariah919** [comment]
it probably wasn't, as sentinel spit damage was buffed later on I think, and sent spit is balanced around being armored against a bit.
Even then if we are keeping survivors we should probably give them bio armor unless were gonna just yeet them out of the game

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-13). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
