### PR TITLE
Tweak Corpsman Uniform

### PR DESCRIPTION
**Pull request by Sulaboy**
## About The Pull Request

Removes striping for a single armband. Armband "Cross" color changed from red to green because red cross is for non combatants and for war crime memes we need to pretend to be civil. Also fixes TGMC Uniforms letting you see your shins when rolling up your sleeves and facing sideways.

## Why It's Good For The Game

Pictures are pretty.
Armo Medic Uniform
No Armor Medic Uniform
## Changelog
:cl:
tweak: 
imageadd: Tweaked existing TGMC Uniform Sprites
/:cl:

### CODE REVIEW

**Comment by RenGusta** [comment]
That's a pretty lame forearm band. Should see how far up you can make it. 

Most servers do fairly high up, or cuff trim.

This is inferior to either option :(

**Review by TiviPlus — APPROVED** [review]

**Comment by Sulaboy** [comment]
> That's a pretty lame forearm band. Should see how far up you can make it.
> 
> Most servers do fairly high up, or cuff trim.
> 
> This is inferior to either option :(

It's in the same place as the previous medical uniform sprite. All I changed was the color of the single dot cross, and removed the bands on the opposite arm, and legs. I was trying to stay with the status quo. I'll make it two pixels tall to see what it looks like.

**Comment by Sulaboy** [comment]
Larger Armband
Thicker armband.

**Comment by Sulaboy** [comment]
I really hope there's a better way to make sprites than in dream maker because it's making me sad.

**Comment by TiviPlus** [comment]
Most spriters use asesprite

**Comment by Sulaboy** [comment]
> Most spriters use asesprite

I will look that up. I tried using gimp, but gimp was causing me more problems than it fixed. Thank you.

**Comment by Kuro-ai** [comment]
This is a downgrade from the current sprite,I would ask you to keep both leg details on the corpsman sprite at least

**Comment by Sulaboy** [comment]
I’m going to work on the sprite some more when I have time. I like the idea of a standard uniform with an armband as a corpsman uniform because of the uniformity between the two. Also the white changing direction when you do looks cool.

**Pull request closed without merging**
