### PR TITLE
slug damage bgiger

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
120 from eighty

## Why It's Good For The Game
slug bad buff slug

## Changelog
:cl:
balance: slugs deal 120 damage, so they deal fourty more
/:cl:

### CODE REVIEW

**Comment by Jeff-jefferson-jeffery** [comment]
thank you MJP i can finally bully tier 2s
at long last

**Comment by Walarks** [comment]
Wouldn't the other shotguns need buffs to compensate as well?

**Comment by Losenis** [comment]
God, the FF

**Comment by TGCMbetcher** [comment]
Cant wait to DB slugs

**Comment by TGCMbetcher** [comment]
I just played a round with slug. They dont need this buff. They are in a very very good spot if you can hit every shot. They are the bane of spitters and defenders.

**Comment by TiviPlus** [comment]
Slug doesnt need direct buffs right now

**Pull request closed without merging**
