### PR TITLE
makes rail flashlight a underbarreled flashlight

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title

## Why It's Good For The Game
People asked for it

## Changelog
:cl:
balance:  rail flashlights now go underbarreled
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -53. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
I don't want this.

I like using the UGL or the underbarrel flamer, and I don't like how you're trying to enable the "magharness+raillight" meta.

Especially now that the pickup macros that you *swear you don't use* are getting yeeted.

**Comment by TheGandalf85** [comment]
Yeah, we really shouldn't be making one-line PR changes that are purely balance changes when **there's absolutely no explanation by the contributor** other then "people asked for it." Please tell us specifically why "people are asking for it" and how this would affect balance both positively and negatively, and pull up discussion instead of nothing.

**Comment by Pariah919** [comment]
not a good idea anyway, just showing it can be done easily

**Comment by Denthamos** [comment]
Why remove the current railight and not just add a new attachment for underbarrel light.

**Pull request closed without merging**
