### PR TITLE
Xeno Maw

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

WIP needs testing
and sprites:
- 1x hugger launching sprite
- 1x hugger radial selection sprite
- ?x can add more gases if i get more variants of campaign radial sprites for smoke since im piggy backing campaign radial sprites
- ideally minimap icons for both as well

Buy maw with points click it as hive ruler to open radial menu after selecting bombardment type click on minimap to fire

Acid Jaws: costs 600 tac points, cannot be in caves
Fire:
5 minute CD, 4 turf radius of basically a pyrogen fireball, 6 sec cd

Hugger: 3 minute cd, 6 sec impact, drops 30 random huggers in a 8 tile radius 

Smoke: Shoots neuro smoke 6 second impact, 1 sec lasting, radius 4 (can easily shoot more if I get radial sprites for it), cooldown 4 min

Acid Maw: 1600 strategic points, can be in caves, fires 10 tile radius acid gas bombardments that last 2 sec every 10 minutes, shots are announced, impact time 6 seconds

## Why It's Good For The Game

Xeno indirect fire be like

## Changelog
:cl:
add: Added the new acid maw and acid jaws xeno structures
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
image

the ALASKAN BULL WORM

**Comment by Wisemonster** [comment]
Finally I can play Mortar Drone in the Xob

**Comment by ju45he** [comment]
Can't wait for xenos to get their own hive ship and come down to planetside in their xlamo to construct xob before opening the xhutters and loading their xuke xisks so they can xuke the human hive. Maybe even a xadop or a xodop.

**Comment by Tonklaatech** [comment]
Headcrab Canister from Half Life 2????? REAL???!!!!

**Comment by Wisemonster** [comment]
This would give hivemind more use, as it could easily teleport to the jaw/maw, making it the quickest caste for getting to these structures.

**Comment by SimplySmiley123** [comment]
> This would give hivemind more use, as it could easily teleport to the jaw/maw, making it the quickest caste for getting to these structures.

As if hivemind isn't already an extreme annoyance.

**Comment by JackTheJackhammer** [comment]
I for one am extremely excited for artillery duels and fire-and-move maneuvers with xenos

**Comment by SimplySmiley123** [comment]
I for one don't look with excitement to the "30 huggers spawning from the aether" one, rest seem perfectly fine I guess.

**Comment by Wisemonster** [comment]
> I for one don't look with excitement to the "30 huggers spawning from the aether" one, rest seem perfectly fine I guess.

Yea, would probably be a good idea restricting that to the maw, considering that's the one that sends the marines an announcement when it launches. That or give that one in particular an announcement on the jaw.

**Comment by Wisemonster** [comment]
That or remove larva huggers from the payload, considering those are stuns, unlike all the other larvas being some form of damage.

**Comment by Arturlang** [comment]
2 second lasting 10 radius gas for 1600 points doesn't seem worth it, should last a bit longer.

**Comment by blackdav123** [comment]
i dont think the jaws should use 600 tac points as psy points are meant to be saved and used on big expensive buys while tac points are meant to be used by anyone on small things should an opportunity present itself. adding something to save tac points for invalidates whole purpose of splitting the two.

**Comment by Kuro020** [comment]
Bad bot

**Pull request closed without merging**
