### PR TITLE
Medical, optical imager, meson sunglasses and eyepatches

### PR DESCRIPTION
**Pull request by Blundir**
## About The Pull Request

Adds five more craftable hud eyewear. Sunglasses are crafted from the fake ones.

dreamseeker_E3bpuMg4BG

## Why It's Good For The Game

Drip is always good.

## Changelog

:cl:
add: Meson eyepatch and its crafting recipe
add: Meson sunglasses and its crafting recipe
add: Medhud sunglasses and its crafting recipe
add: Optical imager sunglasses and its crafting recipe
add: Optical imager eyepatch and its crafting recipe
/:cl:

### CODE REVIEW

**Comment by ZahaSanko** [comment]
all we need now is Imager balistic goggles

**Comment by ZahaSanko** [comment]
> dreammaker_eTHn4kd4uH They kinda exist for a long time

maybe in codebase, not aviable in game as far as I know, also it looks kinda bad

**Comment by Blundir** [comment]
I've literally seen em like a round ago, seen em numerous times before

**Comment by Lumipharon** [comment]
The meson animation is very fast, looks a little wack.

**Comment by Blundir** [comment]
it's due to gif timings, animation has 1:1 identical timings to medhud eyepatch in dmi file

**Comment by AzonStarfall** [comment]
> maybe in codebase, not aviable in game as far as I know, also it looks kinda bad

They're available in-game. Click on Goggles while holding Imagers, same as with MedHuds.

**Review by TiviPlus — APPROVED** [review]

**Comment by AzonStarfall** [comment]
> it's due to gif timings, animation has 1:1 identical timings to medhud eyepatch in dmi file

You could resolve this by adding duplicate frames to slow the cycle down, like with the OB cannon.

**Comment by Blundir** [comment]
> > it's due to gif timings, animation has 1:1 identical timings to medhud eyepatch in dmi file
> 
> You could resolve this by adding duplicate frames to slow the cycle down, like with the OB cannon.

I'm aware, but there is no issue, tha frames are consistent with other patches/glasses that are in game already, here is a comparison with a medpactch hud for example.
dreammaker_eNOA1gUyfD
dreammaker_GBv4x0KXOr

**Comment by Autisem** [comment]
> > > it's due to gif timings, animation has 1:1 identical timings to medhud eyepatch in dmi file
> > 
> > 
> > You could resolve this by adding duplicate frames to slow the cycle down, like with the OB cannon.
> 
> I'm aware, but there is no issue, the frames are consistent with other patches/glasses that are in game already, here is a comparison with a medpactch hud for example. dreammaker_eNOA1gUyfD dreammaker_GBv4x0KXOr

you can change the delay between frames, maby crick that up to like half a second?

**Comment by Blundir** [comment]
> > > > it's due to gif timings, animation has 1:1 identical timings to medhud eyepatch in dmi file
> > > 
> > > 
> > > You could resolve this by adding duplicate frames to slow the cycle down, like with the OB cannon.
> > 
> > 
> > I'm aware, but there is no issue, the frames are consistent with other patches/glasses that are in game already, here is a comparison with a medpactch hud for example. dreammaker_eNOA1gUyfD dreammaker_GBv4x0KXOr
> 
> you can change the delay between frames, maby crick that up to like half a second?

well, it's a general issue of these eyepatches then, i can ofc, but should i?

**Comment by Lumipharon** [comment]
Yeah if the existing ones are wack, change all of them.

**Pull request merged**
