### PR TITLE
Allows minions to ride crushers

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title.

## Why It's Good For The Game
I think it's a fun change! Gives minions more potential if they work together with crushers, too.

## Changelog
:cl: Lewdcifer
add: Xeno minions can now ride crushers.
/:cl:

### CODE REVIEW

**Comment by Zangeiti** [comment]
powercreep af

**Comment by yyzsong** [comment]
No. No fun allowed.

**Comment by TiviPlus** [comment]
Does this need unique offsets or does it look fine?

**Comment by Looking4bros** [comment]
Mfw nymph and baneling gets ignored. :C

**Comment by lKiseki** [comment]
> Does this need unique offsets or does it look fine?

I checked offsets and they looked fine!

**Pull request merged**
