### PR TITLE
(Re) adds MP

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

As per title
## Why It's Good For The Game

The headmins have said they'd like to see MP in the game

## Changelog
:cl:
add: Added MP role
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
waht

**Comment by Xsdew** [comment]
I sure do love MPs. They get a big Mech to be Stompy.

**Comment by BraveMole** [comment]
Good pr

**Comment by Kuro020** [comment]
awesome pr, I love MPs

**Comment by DerpiestBruh** [comment]
how

**Comment by Naaanii** [comment]
1. The Maintainer PRs, and its consequences have been a disaster, for my sanity. They have greatly increased the consistent-expectancy of those who play in “advanced” servers, but they have destabilized the soul of the very game they try to improve. They have made games unfulfilling, have subjected players to overly zealous admins, have led to widespread psychological suffering and have inflicted severe damage on SS13 landscape. The continued development of code will only worsen the situation. It will certainly subject players to greater indignities and inflict greater damage onto servers. It will lead to greater social divide, and psychological suffering, and it may lead to schizophrenic rants, and even autistic ones, even in “advanced” servers.

**Comment by BraveMole** [comment]
Stop whining the debate is closed mps are here

**Pull request merged**
