### PR TITLE
LTB tank cannon rebalancing

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Rebalances the LTB tank cannon round, with it being a net nerf.
Projectile damage reduced from 200 to 85.
Price in Requisitions increased from 10 to 30.
Sundering increased from 20 to 50.
Heavy impact range increased from 2 to 3.
Removes gibbing of non-xeno targets.

## Why It's Good For The Game
As it stands right now, the tank is basically a death sentence most of the times, and can solo a vast majority of the xeno castes. I believe it is healthier for the tank to require more support, instead of being able to just instantly crit everything that dares challenge it. Considering I'm pushing it in that direction, I figured I'd compensate by adding more sunder, explosion range, and outright removing gibbing; if it's meant to be more supportive, then this should enable that.

Double also, gibbing permanently removes people from rounds and that's very stinky.

## Changelog
:cl: Lewdcifer
balance: LTB tank cannon round rebalanced;
del: Projectile damage reduced from 200 to 85.
del: Requisitions price increased from 10 to 30.
del: No longer gibs non-xeno targets.
add: Sundering increased from 20 to 50.
add: Heavy impact range increased from 2 to 3.
/:cl:

### CODE REVIEW

**Comment by Breadeagle** [comment]
Recommending the price get changed so we don't run into the issue of people simply spamming 10 cost shots to clear walls and weeds with 0 risk - something people already probably should/could be doing but will be made worse once its power is concentrated into explosion size rather than direct hits.

**Comment by yyzsong** [comment]
Mom, they're trying to remove LTB gibbing again

**Comment by Looking4bros** [comment]
If Tanks don't strike fear into the marines hearts, it's not a real Tank.

**Comment by MLGTASTICa** [comment]
lmao the tank getting turned from a proper vehicle to a obese AMR with serious movement and mobility issues.

**Comment by Breadeagle** [comment]
> lmao the tank getting turned from a proper vehicle to a obese AMR with serious movement and mobility issues.

Vehicles shouldn't require 1 shot doom guns that you have to camp 95% hp (or pre sunder nerf, not show at all) to even be on same screen lol. Even with this, if price isn't changed, tank is still a wall shredding, explosive spamming monster. Mobility problems sure but right now its basically the unstoppable slowpush cancer which will always trade with xenos at the very least if fighting (and thats unlikely without t3 or t4 primo)

**Comment by chizzy376** [comment]
the req price alone is a pretty good change overall, rn you can either get 1 railgun mag or 3 gib tank shells, hope this makes it less spammy

**Comment by Araulius** [comment]
tad died for tank and apc, only for tank and apc to get nerfed into the ground

**Comment by chizzy376** [comment]
> tad died for tank and apc, only for tank and apc to get nerfed into the ground

I really don't understand how people can defend the current state of the tank. Try playing xeno and getting oneshot when you're supposed to be a tank caste by a 10 req point shell

**Comment by Isy232** [comment]
First thing I think to bring up:

> if it's meant to be more supportive, then this should enable that.

Tank with Cannon is typically supposed to be leading the charge at the very front of the marine force. It is in no way practical to use as a support due to the explosion killing or now damaging marines. What the tank is supposed to need is marines to support it from getting flanked and slashed to death or sniped repeatedly by warlocks and unable to repair.

200 => 85 is far too large a change to consider reasonable. Consider 200 => 150.

Another nerf idea would be to nerf the turrets turn speed, or provide a stabilization delay such that the tank has a second wait after rotating the turret before it could fire. As is the tank can instantly rotate left or right (not behind) and shoot making it very risky to flank.

**Comment by SimplySmiley123** [comment]
> First thing I think to bring up:
> 
> > if it's meant to be more supportive, then this should enable that.
> 
> Tank with Cannon is typically supposed to be leading the charge at the very front of the marine force. It is in no way practical to use as a support due to the explosion killing or now damaging marines. What the tank is supposed to need is marines to support it from getting flanked and slashed to death or sniped repeatedly by warlocks and unable to repair.
> 
> 200 => 85 is far too large a change to consider reasonable. Consider 200 => 150.
> 
> Another nerf idea would be to nerf the turrets turn speed, or provide a stabilization delay such that the tank has a second wait after rotating the turret before it could fire. As is the tank can instantly rotate left or right (not behind) and shoot making it very risky to flank.

The cannon has no IFF, has wonky aiming as ss13 always had to be honest, and it will gib any unfortunate marine it smacks in the face no matter their armour. And in fact, it gibs more marines then it kills xenos or really doing anything of significance at the moment most of the rounds. 
Without the cannon providing big damage to scare off the squishier castes, it can't really hold itself at the front where the cannon is usable at all, as any xeno caste can and will otherwise jump on the tank without an issue (and as a bonus, the fact aiming can be used to shoot over the tank is not widely known, so can't rely on marines helping you deal with that).
_Without the cannon, the tank is just a bigger, slower, metal smartgunner._

Plus, tankier castes can indeed tank a tank shell, then a second, and have the health to run away or straight up hop onto the tank and deal some damage that way. They're not gonna solo it, they _shouldn't_ solo it nor expect to solo an experienced tank crew and the marines near it, but it does enable other xenos to go in and help deal with it, it's a _team_ game.

It would need a way to get IFF if it's damage gets nerfed, otherwise the cannon tank's not gonna be living long in positions that the cannon encourages due to the gib mechanic.

**Comment by Pariah919** [comment]
Tank cannons meme is nuking people from the face of the universe. If you want to have the ezmode support experience the minigun is sitting right there. The probable just cause is to just give it several more ammo types as that *should* be the advantage a tank cannon has over a multifeed machinegun.

**Comment by Breadeagle** [comment]
Anyone thinking the damage reduction is too high remember that more sunder = more explosion damage since its applied after sunder (hence why old tank was auto gib at 100 sunder -> devastation)

Side note I always preferred it to have devastation rather than this straight gib call since marines can at least do funny memes with heavy hlin or b17 to live through accidents.

**Pull request closed without merging**
