### PR TITLE
Add a new floor (industrial

### PR DESCRIPTION
**Pull request by Danaleja2005**
Just add a new floor (industrial)

image

## Changelog
:cl:
add: add a new floor (industrial)
imageadd: icon of floor 
/:cl:

### CODE REVIEW

**Comment by psykzz** [comment]
I used the turfs in bedred as the cargo area there just has plating and could use the industrial sprites.

This is just SDMM, but curious your thoughts on how it turned out?

image

For me it's a little too hard, and might make things hard to see on the floor.

**Comment by Danaleja2005** [comment]
well huh what you want? more brightness?

**Comment by Chaznoodles** [comment]
It doesn't quite fit in with the other turfs. Maybe make matching walls/rwalls?

**Comment by Danaleja2005** [comment]
image

i did it better @psykzz

**Review by TheBimmer231 — APPROVED** [review]
A lot better with the fix, approved.

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
