### PR TITLE
Queen Rework WIP

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Been struggling with this PR, need it out there with more eyes so I can finish out with what I think is a pretty strong start. Goal is to turn queen into more of a frontline leader and "psychic warrior" caste.

- [X] Psychic Barrier
- [X] Psychic Discharge
- [X] Queen Heal Update (3 Charges)
- [X] Give Plasma Update (3 Charges)
- [X] Queen Always Has Charge
- [X] Queen Zoom not breaking when moving.
- [ ] Psychic Whisper 
- [ ] Acid/Resin Scatter Spit
- [ ] Queen Primo Ability (not sure what yet)
- [ ] Screech Removal (Partially Done)
- [ ] Old Spit Removal
- [ ] Sting Removal
- [ ] Additional Ability Updates and Improvements TBD
- [ ] Balancing (Most values are currently placeholder)
- [ ] Polish

## Why It's Good For The Game

Queen isn't exactly a fan favorite among people most people don't like playing it despite it being a very important caste, so I hope to improve the fun factor.

## Changelog

:cl: Tupina
add: Reminder to do this
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
Truly the golden age of xenomorph content is here.

**Comment by chizzy376** [comment]
What's in plan to be the replacement for her screech?

**Comment by FIXTHERADBOXPLEASE** [comment]
She gets the crusher mode since the start now? Thank you my friend... the best PR this year.

**Comment by Lumipharon** [comment]
Not sure if I like turning queen into a frontline monster when it's always been the support core for the entire hive. There's a reason people say not dying is the main job of queen.

**Comment by SilencedMP5A5** [comment]
queen does not need to be king 2.0

king is already impossible to deal with without a massive coordinated effort by the marines using all of the overpowered BS they have

**Comment by Tupinambis** [comment]
I hate to do this again, but after some discussion this probably isn't a good direction for queen, and these new abilities would fit better on a separate caste altogether. That said I still plan on bringing some stuff over.

**Comment by Joe13413** [comment]
i feel like a big, big problem with queen is the fact that they don't really have a lot of impact on the game other than using their queen screech, preventing hive collapse and giving out good pheros. All of those things are real fuckin' boring to play as, so im gonna take a few shots in the dark here and suggest some changes here.
Maybe you can reinforce the queens position as a sort of "push enabler". Xenos love to push when queen screeches, and maybe there can be a few more abilities to reinforce this?

I was thinking adding a sort of battle cry to the queen to replace the screech, one you can cycle through to either buff xenos, or debuff marines
maybe a small damage boost to xenos (+2 slash?), along with extra speed and maybe a bonus to max plasma (10-20%?) that buffs xenos in your battlecry range for 15-20 seconds maybe?
or you can choose a debuff for marines that makes them move slower, set stamina to 40 if above 40 stam, increase scatter, decrease accuracy, and maybe even increase wield times for weapons?

Also adding fun combat abilities to queen would help to compensate for the lack of fun combat queen has. Maybe adding a buffed version of defenders tail swipe (higher radius than tail swipe, but still higher cooldown than swipe), and maybe give queen a finisher move where you can spit acid at a downed marine for massive burn damage?

The way im thinking here is that you can buff xenos if you're attacking the marines, or debuff marines if you're being chased/defending. And you also have a weaker, but lower cooldown AOE stun so you can be in combat more often, and the acid finisher can be used if you get help from another xenos stun (defenders charge, ravagers ravage, spitter/prae acid spray) could probably help to make queen into a more fun caste

Some more things to reinforce the queens "push enabler" identity would be cool to have
also do keep in mind that i don't know much about game design, this is just an idea i had, and hopefully these changes wouldn't make queen too overpowered/underpowered while improving the amount of fun you can have playing as queen.

**Pull request closed without merging**
