### PR TITLE
King Cost Significantly Reduced

### PR DESCRIPTION
**Pull request by Ben10083**
## About The Pull Request
King psypoint cost reduced from 1800 to 800.
## Why It's Good For The Game
While according to Tivi a king rework will come someday, until that day comes, having the current king be at a cost that better reflects its value is a good measure to do to make king less of a meme pick.

MJP approved! 
image
## Changelog
:cl:
balance: King psypoint cost reduced to 800
/:cl:

### CODE REVIEW

**Comment by zzurge** [comment]
this should be interesting

**Comment by helper-2** [comment]
You can make him free at this point. In RuTGMC he costs 1200 points. That doesn't make him stronger.

**Comment by Strayed-Raven** [comment]
It's another source of free *whatever req points a queen gives*

**Comment by BraveMole** [comment]
King should not be made more available until it is significantly improved in quality

**Comment by Skatuk** [comment]
Cringe

**Pull request closed without merging**
