### PR TITLE
Slight nerfs to the TX11

### PR DESCRIPTION
**Pull request by Kuro020**
## About The Pull Request

Nerfs the TX11's sunder

## Why It's Good For The Game

TX11 right now outpaces the rest of the guns, while that's the niche it has due to sacrificing attachments, it does it a little bit too well, this should put it more in line

## Changelog

:cl:
balance: TX11 Sunder reduced
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
Supreme Leader Kurt's will
image

**Comment by Isy232** [comment]
AKSHUALLY...

Checking the DPS equations at 6 tiles AR11 and AR18 are equivalent while BR64 slightly outperforms both.

AR11 is relatively in line with the other weapons, especially given that it can't have any of the good underbarrel attachments.

If you want to merge this anyways because you think the gun is overused, meh.

AR11 with 15 AP would match the DPS of the AR12 at 6 tiles, given that AR12 is a clear underperformer.

**Comment by Kuro020** [comment]
this is completely ignoring lower burst delay that makes it easier to hit all the shots and the fact that it has more ammo than both the ar12 and ar18

**Comment by Isy232** [comment]
Fair points, it has its upsides too

If you think those other upsides are worth it having AR12 DPS instead of AR18/BR64 DPS then sure

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
