### PR TITLE
Nerfs machinepistol fire rate to 0.2 from 0.15

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
This lowers the rpm by 100 basically.
0.15->0.2

## Why It's Good For The Game
The machine pistol is too good compared to all the other secondaries, this should be a good nerf considering it has 30 rounds and assault rifle fire speed, and good one-handed performance.

## Changelog
:cl:
balance: machine pistol fire speed reduced to 0.2 from 0.15, aka 100 rpm less
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -137. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by MLGTASTICa** [comment]
What ? what about the revolvers that can instantly put a T3 to under half health ? machine pistol is a pea shooter.

**Comment by davidchan13** [comment]
TP-14 and TP-44 both outperform the machine pistol whether they are stock or full attachments.

**Comment by SilencedMP5A5** [comment]
the T19 can do serious damage extremely fast if you dual wield it and xenos facetank you

i once gibbed a runner from full health in like 2 seconds

**Comment by SplinterGP** [comment]
> What ? what about the revolvers that can instantly put a T3 to under half health ? machine pistol is a pea shooter.

6 shots, long reload

**Comment by SplinterGP** [comment]
i think this is far from whats wrong with the T-19, it got broken stats all over, its not only the ROF, you can see how fucked it is from when the gun is worse when wielded than onehanded.

**Comment by davidchan13** [comment]
> the T19 can do serious damage extremely fast if you dual wield it and xenos facetank you
> 
> i once gibbed a runner from full health in like 2 seconds

Hows this any different from any pistol when dual wielding and the xeno face tanks? A revolver wouldn't need that long and neither would the TP14, I'm pretty sure even the MOD88 does more damage in that scenario.

**Review by TiviPlus — APPROVED** [review]

**Comment by fernandos13** [comment]
one should remember we are treating the T19 as a SMG in most of the code. its weird to compare it to other pistols... honestly its a very middle ground id say
but for medic. i feel like its the only gun i can consistently one hand it. """i dont care that much for the ROF personally" but im afraid of it being nerfed like the PPSh. and leaving me with only the P90 as smg that can be used without pb benos. 

also.. a beno should not face tank. someone with a SMG.. so.. if it didn't damage benos at FACE TANK.. when would it.. 
"T44 can halv benos from afar"
T18 and T12 can fair VERY well at medium range even to moving benos
PPSh "MELTS em even MORE when up close and with those 70 shots.. DUDE that thing is strong PB.. only PB due to scatter. but nonetheless" 

i think the T19 is good indeed. and one never wants its most used thing to be nerfed so i assure you i might have some bias.. but thats only cause i tried to use T90 PPSh and even the TP 14 and MOD 88 for one handling around. and no gun fits the same niche as T19 """and dont call it a side arm.. you cant even fit in the pistol holsters anymore, you can say that it needs a nerf. but its DEFINETLY not a sidearm"""

**Comment by SplinterGP** [comment]
the T-19 far from needs a nerf on firerate, it needs to be tweaked around other stuff that the gun has 0 in it, without counting the fucked up stats it has, making it have 0 trouble shooting one handed but has scatter and shit wielded (?????????????????????????)

**Comment by davidchan13** [comment]
> the T-19 far from needs a nerf on firerate, it needs to be tweaked around other stuff that the gun has 0 in it, without counting the fucked up stats it has, making it have 0 trouble shooting one handed but has scatter and shit wielded (?????????????????????????)

It's only controllable firing onehanded if you have very specific mods on the weapon. With a vanilla/bare T-19 only about 1 in 3 bullets actually travel the direction you're aiming. And wielding the weapon actually lowers it's accuracy, it was specifically designed to be use one handed.

**Comment by SplinterGP** [comment]
> > the T-19 far from needs a nerf on firerate, it needs to be tweaked around other stuff that the gun has 0 in it, without counting the fucked up stats it has, making it have 0 trouble shooting one handed but has scatter and shit wielded (?????????????????????????)
> 
> It's only controllable firing onehanded if you have very specific mods on the weapon. With a vanilla/bare T-19 only about 1 in 3 bullets actually travel the direction you're aiming. And wielding the weapon actually lowers it's accuracy, it was specifically designed to be use one handed.

actually the T-19 has no scatter, something like moving and pain might be affecting it.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-153). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by TiviPlus** [comment]
If you want niche make it

**Pull request merged**
