### PR TITLE
revolvers get aim mode

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
revolvers get aim mode
0.75 slow 0.25 fire delay

## Why It's Good For The Game
marines are gunning
every normal gun should really get aim mode

## Changelog
:cl:
balance: revolvers get aim mode
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -145. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by BeloneX** [comment]
12 shots.

**Comment by Tennessee116** [comment]
What's a normal gun in TGMC context? Just anything that shoots regular boolets?

**Comment by Swagile** [comment]
yes

lets give marines the ability to stagger stun behind other marines

there's a reason why shotguns don't have aim mode

unless you remove the stagger stun from revolvers when in aim mode this is gunna be hilariously OP

**Comment by TGCMbetcher** [comment]
So the best damage dealing weapon in the game, capable of doing 350 damage as fast as you can pull the trigger, can now be done behind meatwalls

**Comment by SplinterGP** [comment]
Seems fine for me, it needs to wield to be aimmed so reloading and doing that looks troublesome and hard to do, not mentioning aimmode activation delay.

**Review by SplinterGP — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-179). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Swagile** [comment]
you actually fucking merged this?

clown town

**Pull request merged**
