### PR TITLE
M40 stickies no longer acquireable in marine vendors, renamed to M41. Added to req as buyable item.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
M40 stickies renamed to M41. Added sticky box.
M41 sticky grenades removed from roundstart vendor, they are now 500 for 25 grenades.
## Why It's Good For The Game
Stickies are way too powerful as they are, I'd argue impact grenades were more balanced than these things since they were super limited and expensive advanced grenades. These things are literally roundstart and break all grenade balance for the downside of slightly less explosive range.
## Changelog
:cl:
grammar: M40 adhesive grenade renamed to M41.
balance: M41 adhesive grenade no longer spawns in marine vendors roundstart. You can instead acquire them for 500 points in req.
/:cl:

### CODE REVIEW

**Comment by 567Turtle** [comment]
cringe salt PR, stickies ain't even that good you just got sticked as a drone and blew up

**Comment by Lumipharon** [comment]
I've already got a pr for stickies, when tivi gets around to looking at it.

**Comment by Tupinambis** [comment]
Stickies are fine

**Comment by FIXTHERADBOXPLEASE** [comment]
Erm why change the name to M41? That's the one thing I don't understand.

**Comment by Strayed-Raven** [comment]
Show me on the character doll where the sticky hit you

**Comment by Beepinex** [comment]
i think the issue with stickies could be a lot of castes having ZERO bomb armor? from my test they deal about 150 damage if they stick to a 0 bomb armor caste. thats a lot of damage for hitting one right click. can anything else do that?

**Comment by Lumipharon** [comment]
Sticky delay pr was merged, this isn't needed right now

**Comment by pilotmans** [comment]
This is actual cope, just add like a 20% damage reduction?

**Pull request closed without merging**
