### PR TITLE
Modernizes CLF

### PR DESCRIPTION
**Pull request by hyper2snyper**
Note: This is dependent on the Freelancer PR. Dont review until that one is merged.

## About The Pull Request
Modernizes the CLF for current gameplay. This is to make them not such a joke and to be more on par with the Freelancers.

CLF armors now have lights, and their guns now have mag harnesses and bayonets.

Leader:
leader

Leader now carries a Sadar. Sadar only has WP ammo and does not have a mag harness.
Leader has regular meds now.
He now has a pistol belt.
His binocs are now of the Tactical type.

New Class: Grenadier: 
Grenadier
Wears a suicide vest.
Has a belt of WP grenades.
Carries various miscellaneous grenades.

The Grenadier carries a belt of WP grenades as well as a handful of other grenades

Medic:
Medic

Now has a beret.
Carries the standard medical equipment now.
Now has the same weapon as the rest of the CLF.

Standard:
Standard

Now carries two Uzis
Has much more ammo.
Now has decent meds and two more bottles of zoom pills.

## Why It's Good For The Game
CLF is currently a joke. Given the medics and the standards dont have decap protection or even lights on their armor.
I means seriously no lights.
Their guns are pitiful and bad and they dont have any meds to be sustainable in any way.

This aims to bring them to the same level as Freelancers in effect on xeno.
This however makes them fit into the role of glass cannon. And for the new class, Grenadiers, to have fun.
Ultimately this aims to buff CLF in a way that makes them distinct from freelancers, but about as powerful.

## Changelog
:cl:
balance: CLF Leader now has a Sadar with WP. He has been given Surt as well.
balance: New CLF Class: The Grenadier. Equiped with a belt of WP grenades and a suicide vest, they are sure to be an explosive addition.
balance: CLF Medic now has adequate supplies to keep his suicidal comrades alive.
balance: CLF Standard kits now have two smgs and some decent meds.
balance: CLF buffed to be more or less equal to Freelancers in power, yet different in niche. They are now the suicidal glass cannons of erts.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Unga bunga

**Comment by Araulius** [comment]
give them the CM bomb lance. do it. D O I T. long wield time, require wield in order to detonate. detonation would be mutually assured gibbing.

**Comment by yyzsong** [comment]
what the fuck based bird???

**Comment by XSlayer300** [comment]
we need those claymore spears from CM

**Comment by Pill-U** [comment]
why WP though? spawning in a cloud of WP is just unfun

**Comment by Moggram** [comment]
Grenadier is nightmare fuel.

**Comment by Naaanii** [comment]
Agree with the WP comment. Double WP is decent consistency but slight variety wouldn't hurt. Would much prefer HE rockets and WP nades.

Would also like to suggest just scratching the medic class in favour for a more robusto class with akimbo, light weapons like SMGs, pistols or revolvers along with meds (for themselves) for CLF in particular.

**Comment by Lumipharon** [comment]
nothing wrong with extra zoom pills but 3 bottles seems excessive, I'd be impressed if someone legitimately went through that many.

**Comment by bowlofcereal** [comment]
modernizing the clf is something badly needed but that is a LOT of white phosphorus

**Comment by Pariah919** [comment]
give them the sadar

**Comment by Rexdyer1** [comment]
The zoom bottles offer a cool buff to the standard, however I am quite sure that zoom causes oxy damage in massive amounts, and I don't see any dex+ in the loadout, you may want to add that.

**Review by BraveMole — CHANGES_REQUESTED** [review]
No sadar

**Comment by BraveMole** [comment]
stale

**Pull request closed without merging**
