### PR TITLE
Medical Storage Changes

### PR DESCRIPTION
**Pull request by Arctrooper8**
### Changes medical storage/vending to a large degree.

Deleted: First aid pouch, Hypospray pouch, Syringe pouch, injector case.
Changed the contents of all rig and lifesaver belt. (Hypo will be a different PR)
Pill packets are free and infinite in marine med.
Pill bottles are in the NT med vendor and available to medics and doctors.
Tricord is now consistently white (Pill bottle, packet, reagent bottle)
Basic chem and some empty hypos in NT med.
Surgical webbing has a new sprite and can be found in the NT med, alongside the new surgery pouch.
Brute kit has been replaced with a specialized surgery tool in surgical usage/storage. 

#### Rig Medic/MO spawn:
image
Bicard, Kelo, Trama, Tricord, Dylo, ina, dex, spaceacillin, alky, imi, quickclot, hypervene, stasis bag, roller bed, defib, health analyzer.

#### Rig Researcher spawn:
image
Bicard, Kelo, Trama, Tricord, Dylo, ina, dex, spaceacillin, alky, imi, quickclot, hypervene, defib, excavator, xeno saw, health analyzer.

#### Lifesaver:
image
Bicard, Kelo, Trama, Tricord, Dylo, ina, dex, spaceacillin, alky, imi, quickclot, hypervene, 2 splints, 3 burn kits, 3 brute kits, health analyzer.

#### First aid:
image
Bicard, Kelo, Trama, Tricord, Dylo, splint, ina injector

#### First aid injectors:
image
Bicard, Kelo, Trama, Tricord, dylo, ina, synapt, russian red

#### Medic pouch:
image
3 burn kits, 3 brute kits, 1 meraderm hypo

#### Medic injectors:
image
3 advanced combat injectors, 1 dex plus injector, 2 qc+ injectors, 2 peri+ injectors

### Ground sprites:
image
image

## Why It's Good For The Game (NOT DONE)

Medical storage has been weird for quite a while. For example: the first aid pouch only had 6 slots, yet the medkit pouch which was free and infinite had 7 slots. So why would you ever not take a medkit pouch? Same thing with the two injector pouches. And medical belts in particular can be awful, often times missing vital chems that medics should have with them or just having useless stuff. 

Pills:
Pills have always been a contentious thing when it comes to medical. Specifically the massive amounts that marines could carry with them. By making pills harder to get and pushing pill packets to the forefront should help with the walking pharmacy complaint.

Belts:
Each belt now has generally at least one of every chem type (There's no peri in any of them because I fully expect Brave's organ change to pass before this PR) 
Hypospray belt in particular now uses big hypos and only one bottle (The previous design had 240 chems when the trade off is supposed to be less chems for faster application)

Pouches:
Pouches were weirdly inconsistent, especially the pre loaded injector pouch which was never updated in light of the autoinjector changes. The first aid pouch had 6 slots but medkit had 7, punishing newer players who didn't understand this. The same thing was true for combat injector pouch (from loadout) vs injector pouch.
Both first aid type full pouches now have all the basic chems (Bicard, kelo, trama, dylo, tricord) alongside some other stuff (medkit pouch has splints and an ina injector, while auto injector has the emergency injector, an ina injector, and a single synapt injector).
All ERTs now use the injector pouches due to the faster paced scenarios they often find themselves in (Hijack and EORD)

## Changelog
:cl:
add: Surgery pouch 
add: brute kits in surgical usage have been replaced with a new tool, surgical membrane.
del: First aid pouch, Hypospray pouch, Syringe pouch, injector case.
del: Medical belts in medbay storage rooms.
balance: Lifesaver belt now has every pill type alongside 6 kits, two splints, and a health analyzer.
balance: Rig belt now has every pill type.
balance: full lolly pouches are now free and infinite from the vendor.
balance: pill packet are free and infinite from MarineMed.
balance: pill bottles have been moved to nanotrasen medical vendor.
balance: moved stuff such as defib from nanotrasen medical vendor to MarineMed.
balance: ERT/EORD spawns now use injector pouches.
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
Fails ci

**Comment by Naaanii** [comment]
I don't see the need for surgery pouch when vests exist as most pouches can carry a lot more than regular webbing.

**Comment by Arctrooper8** [comment]
> I don't see the need for surgery pouch when vests exist as most pouches can carry a lot more than regular webbing.

A couple of reasons:
1. You cannot spawn someone with webbing, by making it a pouch we can spawn doctors with their tools instead of having them duke it out for webbing.
2. As you point out pouches are a lot more useful, therefore making it a surgery pouch forces a FOB doctor to choose between using a tray or always having their tools on them.
3. I like the look of it.

**Comment by Lumipharon** [comment]
You can spawn people with webbing though.

**Review by Kuro020 — APPROVED** [review]

**Comment by Arctrooper8** [comment]
> You can spawn people with webbing though.

Then why couldn't I find any examples in the code? And why does every ERT not spawn with webbing?

**Comment by Lumipharon** [comment]
> > You can spawn people with webbing though.
> 
> Then why couldn't I find any examples in the code? And why does every ERT not spawn with webbing?

Ert does spawn with webbing. All freelancers and SOM have webbing.

**Comment by Arctrooper8** [comment]
> > > You can spawn people with webbing though.
> > 
> > 
> > Then why couldn't I find any examples in the code? And why does every ERT not spawn with webbing?
> 
> Ert does spawn with webbing. All freelancers and SOM have webbing.
> 
> Edit: Also slightly confused on what is happening exactly. You mention removing first aid pouch but then it's lists in your screens hots.

That's because it is the first aid stuff you get from loadout vendor, but it is in a medkit pouch now.

**Comment by Lumipharon** [comment]
> > > > You can spawn people with webbing though.
> > > 
> > > 
> > > Then why couldn't I find any examples in the code? And why does every ERT not spawn with webbing?
> > 
> > 
> > Ert does spawn with webbing. All freelancers and SOM have webbing.
> > Edit: Also slightly confused on what is happening exactly. You mention removing first aid pouch but then it's lists in your screens hots.
> 
> That's because it is the first aid stuff you get from loadout vendor, but it is in a medkit pouch now.

OK, you should probs label it as medkit pouch in the pr body. Also atomization is good, but tbh in this case your pouch rebalance pr is directly related to what you're doing here, and I think it would make more sense to have a single PR.

And if you're confused about webbing, like all attachments it has to be specified on the parent item, exactly like guns.

**Comment by Al-1ce** [comment]
> You can spawn people with webbing though.

Doesn't seem to work. At least not with surgical supplies? As far as MDs have existed, they've never spawned with surgical webbing. They have to get it from a locker.

**Comment by Lumipharon** [comment]
> > You can spawn people with webbing though.
> 
> Doesn't seem to work. At least not with surgical supplies? As far as MDs have existed, they've never spawned with surgical webbing. They have to get it from a locker.

It 100% works, doctors just either don't have webbings in their job loadout, or it's been added incorrectly. There's like 3 layers of ass to adding populated attachments to clothing, pm me in discord if you wanted me to show you.
image

**Comment by Naaanii** [comment]
Yeah, spawning with webbing sounds better and it'd be better to just get a vest from lockers rather than waste pouches especially with how much better they are.

**Comment by Al-1ce** [comment]
> It 100% works, doctors just either don't have webbings in their job loadout, or it's been added incorrectly. There's like 3 layers of ass to adding populated attachments to clothing, pm me in discord if you wanted me to show you.
> image
> 


Great. Think you can make MDs spawn with surg-kits while you're at it?

**Comment by FosterGrime-Heymynameslouie** [comment]
this is a cool pr and does alot for unifying med storage but..

now that pill packets are free and stuff,
whats stopping marines from just, vending them, taking the pills, and placing them on a pill bottle?

**Comment by Autisem** [comment]
the medical suit storage also seems a bit wierd, cant fit medical stuff that does fit in webbing which I found odd(defibs, roller beds, stasis bags, evac beds, etc)

**Comment by Arctrooper8** [comment]
> the medical suit storage also seems a bit wierd, cant fit medical stuff that does fit in webbing which I found odd(roller beds, stasis bags) and few other things id expect them to fit(evac beds,defibs , etc)

The differences between what webbing vs pouches/armor module can hold while odd is probably best put in another PR. Due to how much is already in this single PR.

**Comment by Arctrooper8** [comment]
> this is a cool pr and does alot for unifying med storage but..
> 
> now that pill packets are free and stuff, whats stopping marines from just, vending them, taking the pills, and placing them on a pill bottle?

Realistically nothing, however you can already do stuff such as that with say autoinjectors. In fact it's more convenient to dump a bunch of injectors into a beaker then use the chem machine to make pills which come in a pill bottle too. But, if marines want to take out 16 pills from two bicard packets one at a time and then place them in a bottle they're free to go ahead.

**Comment by Arctrooper8** [comment]
> Edit: And can I be an ass? If you're planning to nerf medkit pouch storage and remove firstaid pouch, why don't you just increase first aid pouch storage to 6, and remove the medkit pouch from marine vendors? the 7 slot pouch gets used a lot for ert and other junk, and apparently some medics use it as well (it can stay in their gimmie/medic vendor). I also selfishly don't want you to change it because I'm using it in a new gamemode, so it's pain to then have to make a medkit+ pouch.

????
First aid pouch is already at 6 slots while medkit pouch has 7. This pr is removing first aid pouch and replacing it with medkit pouch in all scenarios. Same for the combat injector (7 slots) vs injector pouch (8 slots). 
If anything this is a slight buff in terms of storage/ pre filled pouches for marines (even corpsmen).

**Comment by Arctrooper8** [comment]
> > > You can spawn people with webbing though.
> > 
> > 
> > Doesn't seem to work. At least not with surgical supplies? As far as MDs have existed, they've never spawned with surgical webbing. They have to get it from a locker.
> 
> It 100% works, doctors just either don't have webbings in their job loadout, or it's been added incorrectly. There's like 3 layers of ass to adding populated attachments to clothing, pm me in discord if you wanted me to show you. image

I still believe that adding it as a pouch is the better option for a variety of reasons.

1. It's more obvious, especially for newer doctors. The idea of the jumpsuit having storage isn't a common one when it comes to the majority of SS13 servers, and that's where most people are gonna be coming from. The pouch itself is also much more noticeable, having it's own pouch slot and a white colour scheme that stands out from other marine pouches.

2. While I probably didn't look hard enough for webbing code. I have still never seen an ERT or EORD spawn with webbing, and I've been freelancers and SoM a fair bit.

3. As Naani pointed out, pouches are more useful. And being able to carry an entire set of surgery tool (alongside a pair of tweezers) sounds pretty useful. A doctor could always carry a tray with them, but I feel that if they want to constantly have their tools on them they should be forced to give something up.

**Comment by QualityVan** [comment]
Realized that MD spawn with a couple of important tools in their rig, which means they won't get them if you replace it with lifesaver. Defib's the core one, although there's usually spares available. Just something to double check on.

**Comment by Arctrooper8** [comment]
> Realized that MD spawn with a couple of important tools in their rig, which means they won't get them if you replace it with lifesaver. Defib's the core one, although there's usually spares available. Just something to double check on.

I'll put a defib and a roller in their spawn backpack. Thanks for point it out!

**Comment by Lumipharon** [comment]
I must be brain damagedon the slot thing. I still really wouldn't remove the item though. You're removing a unique item, including the unique SOM first aid pouch, which means I'm going to have to just readd them later which is ass. You're also replacing them on SOM with a poop pouch which doubles up on items they have stored elsewhere.
If you don't want marines to access first aid pouch because it's a noob trap, just remove their access to it, don't remove the item entirely.

On the surgical vest, it's a bad argument to say people don't know about webbings, so we shouldn't have it. Every human player should have a webbing, there is zero reason not to. If you're entirely bald and trying to be a doctor without knowing the basics of the game, that's a literal skill issue. If you want to add a surgery pouch in addtion to the webbing, I mean I guess, but certain webbings and pouches have different storage efficiencies.

And again, many ERT spawn with webbings, you can literally see it on the uniform sprites. They should really add something to the examine description though.
image
image

**Comment by Arctrooper8** [comment]
>You're removing a unique item, including the unique SOM first aid pouch

It's somewhat obscure but the PR desc says that all ERTs now use the prefilled injector pouch. SOM pouch is just a reskin of the injector pouch now (it was previously a reskin of first aid pouch)

>On the surgical vest, it's a bad argument to say people don't know about webbings, so we shouldn't have it.

That was only half my reasoning, as I have demonstrated it can be entirely possible to not notice webbing when you spawn with it. Therefore, I still think that a pouch is a better solution. It also forces MDs to choose between having surgery tool always on them, or using a surgical tray and taking another pouch.

>I must be brain damagedon the slot thing. I still really wouldn't remove the item though. You're removing a unique item, including the unique SOM first aid pouch, which means I'm going to have to just readd them later which is ass. You're also replacing them on SOM with a poop pouch which doubles up on items they have stored elsewhere.

I'm consolidating med pouches for the main gamemode Xenos vs Marines. The item itself is hardly unique, being a medkit pouch with one less slot. The only unique thing about the first aid pouch is that in terms of the loadout vendor it spawns with stuff inside it. Keeping the first aid pouch for one mode that isn't even in the game yet feels silly. If you'd like I'll add a SOM reskin version of the new medkit basic med prefilled pouch.

**Comment by novaepee** [comment]
Corpsman webbing sprites broke.

**Comment by Weedmaster77** [comment]
I like the idea of the lifesaver belt having more bottles good change, but please don't remove the surgical vest for the surgical pouch the pouch is a nice if someone wants to use webbing but why not both or atleast get to pick one or the other. Also please don't take all the Tricord Hyposprays out of the Nanomed vendors 6 was a bit much but making it so medical staff has to order them from Req if they want one is kinda a bit much. Make it so Req can order empty 60u  hyposprays that are not only the big ones (120u) for like 6 points so medical staff can still get 60u ones and not be force to use pills and injectors for thing they use often. Also medical staff not starting with a defib, statis bag and roller bed is painful but more so the researcher, still think it hurt all medical staff and not being able to put them in a lifesaver belt forcing you to put them in a satchel if you want one on you its hard on anyone wanting to go ground and be fob doctor.

**Comment by QualityVan** [comment]
Wait, you're removing surgical vests entirely? I dunno about that one.

**Comment by Al-1ce** [comment]
Adjusting the sizes of certain pouches is one thing. Completely altering and changing the entire loadout of a role is another. MDs having their items shifted and thrown around into a random order for no apparent reason isn't conducive to a smooth experience. 

There is no difference in having the surgical webbing or the surgical pouch, except that you are now down on an entire container of injectors and now have an empty webbing slot. For.. reasons, apparently?

To clarify, this change would've been fine in my book if the loadout of MDs and the CMO hadn't been messed with. Additionally, spawning with an entire hypo of MeraDerm is a bit cheese. I'm surprised nobody else has mentioned this.

With that said, ..I've asked around. There's about five other MDs who aren't a fan of this, and one synth. Muscle memory is critical when it comes to quickly preforming a medics duties and tending to multiple patients quickly. Making seemingly pointless changes that more or less just put one thing in a completely different area is... well, pointless.

**Comment by Losenis** [comment]
>deleted surgery webbing

Excuse me I fucking use that all the time, why is this removed

**Comment by Al-1ce** [comment]
> It 100% works, doctors just either don't have webbings in their job loadout, or it's been added incorrectly. There's like 3 layers of ass to adding populated attachments to clothing.

Surgical Webbing does not save in the oufit vendor. For shipside staff, it never has..

> 1. It's more obvious, especially for newer doctors. The idea of the jumpsuit having storage isn't a common one when it comes to the majority of SS13 servers, and that's where most people are gonna be coming from. The pouch itself is also much more noticeable, having it's own pouch slot and a white colour scheme that stands out from other marine pouches.

You mightve had a point here if MDs/CMO _didn't have to manually equip the webbing from a locker._ Which they do. 

> 2. While I probably didn't look hard enough for webbing code. I have still never seen an ERT or EORD spawn with webbing, and I've been freelancers and SoM a fair bit.

This was adressed above.

> 3. As Naani pointed out, pouches are more useful. And being able to carry an entire set of surgery tool (alongside a pair of tweezers) sounds pretty useful. A doctor could always carry a tray with them, but I feel that if they want to constantly have their tools on them they should be forced to give something up.

Pouches are more useful.. how, exactly? You can say that, sure, but without actually explaining how it's meaningless. If tweezers are an issue then add them into the webbing. Most doctors already replace the trauma kit in their webbing for tweezers anyways.

Moving the surgical webbing to a pouch does nothing but waste space. It isn't any more useful. It is however disruptive to the flow/muscle memory of shipside staff. The webbing is utilitarian, takes up no space, and allows for two seperate pouches to be equiped at once. If your main concern is visibility, change the color.

They don't even spawn with them. It's not like someone is going to unlock the locker, put the webbing on and forget it exists. In regards to adjusting the Lifesaver/other medical belt, it is also completely unessicarry. I'd much rather have my defib in the belt than in the backpack. If you feel the need to move such a critical tool out of the pouch it was designed for maybe it'd be better to question the reasoning and purpose of what you are actually doing.

I also noticed the 60u of free MeraDerm. That's just cheese, plainly put.

**Comment by Arctrooper8** [comment]
Comments have been taken into account. I have updated PR dec and CL to reflect this.
If I missed anything please notify me.

**Comment by breadhunt** [comment]
I'm pretty sure you stealth removed the lemoline bottle (at least for rsr)

Why not just add webbing roundstart anyway - letting you keep the old loadouts without fucking wuth everything. The pouch sounds nice, that can literally just be added to MD lockers though

**Comment by Arctrooper8** [comment]
> I'm pretty sure you stealth removed the lemoline bottle (at least for rsr)
> 
> Why not just add webbing roundstart anyway - letting you keep the old loadouts without fucking wuth everything. The pouch sounds nice, that can literally just be added to MD lockers though

RSR doesn't have a lemoline bottle on master right now, I believe that was changed when MOs/CMOs got them.

Webbing and pouches have been added to NT med now.

**Comment by Al-1ce** [comment]
> RSR doesn't have a lemoline bottle on master right now, I believe that was changed when MOs/CMOs got them.

Lemoline spawns for MDs as 30u, in 60u containers, whereas req-ordered lemoline spawns in the same containers with _only_ 10u. There does seem to be more inconsistiency.

> Webbing and pouches have been added to NT med now.

Great. I hope my criticism didn't come off as harshness earlier.

**Comment by Arctrooper8** [comment]
> Lemoline spawns for MDs as 30u, in 60u containers, whereas req-ordered lemoline spawns in the same containers with _only_ 10u. There does seem to be more inconsistiency.

Here's the PR which changed it that I alluded to in my previous comment: https://github.com/tgstation/TerraGov-Marine-Corps/pull/10136
The 30u amount is intentional and the 60u bottle is just the default bottle size
I'm not sure when researcher lost lemoline however, since they don't have it by the time of this PR.

> Great. I hope my criticism didn't come off as harshness earlier.

Not at all, I'm glad people are giving feedback. And I'm more than happy to listen.

**Comment by thebestcodertoevercode** [comment]
> Deleted: First aid pouch, Hypospray pouch, Syringe pouch, injector case, bottle case.
give me these back and I'll be happy

**Comment by Arctrooper8** [comment]
> > Deleted: First aid pouch, Hypospray pouch, Syringe pouch, injector case, bottle case.
> 
> give me these back and I'll be happy

All of those are redundant

First aid pouch is exactly the same as medkit pouch (which is free and infinite) except it has 6 instead of 7 slots.
Hypospray pouch is also completely outclassed by medkit pouch, it has 4 slots which can only hold injectors and hypos. Medkit has 7 slots which can hold hypos, injectors, and more.
Syringe pouch can literally only hold syringes.
Injector case doesn't make much sense. Medics/Doctors have hyposprays so giving them an injector case is silly.
Bottle case is outdated, I'll update CL.

**Comment by Weedmaster77** [comment]
I like the surgical webbing only thing is that it has less slots then the pouch which in my mind they should have the same since the webbing is more for ground and the pouch I like for shipside. Glad you added back hyposprays to the vendor and more types that's a plus.  Both MD and RSR seem to not have tweezers and Lemoline bottle in there spawn loadout which seem like they should since they had them before. Also the RSR gets there xeno saw and the excavator in there medbelt instead of there bag in spawn loadout. I don't like that since it take out there roller bed and stais bag so I think that needs to go back to the way it was. The Surgical membrane is a nice idea so its not something that runs out like a trauma kit that's a plus. So over all I like the changes just needs a little more work and its will be golden in my book.

**Comment by Arctrooper8** [comment]
> I like the surgical webbing only thing is that it has less slots then the pouch which in my mind they should have the same since the webbing is more for ground and the pouch I like for shipside. Glad you added back hyposprays to the vendor and more types that's a plus. Both MD and RSR seem to not have tweezers and Lemoline bottle in there spawn loadout which seem like they should since they had them before. Also the RSR gets there xeno saw and the excavator in there medbelt instead of there bag in spawn loadout. I don't like that since it take out there roller bed and stais bag so I think that needs to go back to the way it was. The Surgical membrane is a nice idea so its not something that runs out like a trauma kit that's a plus. So over all I like the changes just needs a little more work and its will be golden in my book.

Webbing and pouch not being the same is a mistake, I'll fix it.

Tweezers/ bottles is also a mistake. However, RSR hasn't spawned with Lemoline for a while it seems. https://github.com/tgstation/TerraGov-Marine-Corps/pull/10136 The PR which gave MDs lemoline shows the RSR as not having any. 

The researcher spawning with their tools in their belt is meant to show researcher that it can hold tools. You should be able to get stasis bags easily from marine med, I'll double check that rollers can be gotten somehow too.

Thanks for the feedback!

**Comment by Weedmaster77** [comment]
> However, RSR hasn't spawned with Lemoline for a while it seems. https://github.com/tgstation/TerraGov-Marine-Corps/pull/10136 The PR which gave MDs lemoline shows the RSR as not having any. 

This is odd since I just saw the RSR have the Lemoline bottle before the most recent TM for this PR. I will say its was only a 10u bottle not a 30u which was fine but it makes it harder to make chems like Somolent which I use alot on RSR when doing ground surgery, so even having the 10u bottle was nice but if that not from this PR its fine.

**Comment by Al-1ce** [comment]
> Injector case doesn't make much sense. Medics/Doctors have hyposprays so giving them an injector case is silly.

These are used by marines and corpsmen. Removing them because MDs do not use them is silly.

**Comment by Arctrooper8** [comment]
> > Injector case doesn't make much sense. Medics/Doctors have hyposprays so giving them an injector case is silly.
> 
> These are used by marines and corpsmen. Removing them because MDs do not use them is silly.

Medic means corpsmen, my point is that a hypospray is simply better than an injector case. The only people who would reasonably use injector cases would be squad marines, who don't even have access to the vendor.

**Comment by Lumipharon** [comment]
I use cases as both medic and normal unga. You can fit not just injectors in them, but bottles. I know vali people do the same.

**Comment by Arctrooper8** [comment]
> I use cases as both medic and normal unga. You can fit not just injectors in them, but bottles. I know vali people do the same.

Syringe/bottle cases are still in. I removed the Injector cases.

**Comment by ilikesaying** [comment]
tricord pill packets hold 2 less pills than the rest, can ya up that number?

**Comment by Arctrooper8** [comment]
> tricord pill packets hold 2 less pills than the rest, can ya up that number?

It's been that way forever.

**Comment by breadhunt** [comment]
> I'm not sure when researcher lost lemoline however, since they don't have it by the time of this PR.

The.. fuck? When this PR un-TM'd I got the bottle back playing researcher. Are you sure

**Comment by Lumipharon** [comment]
The files for this pr straight up show Lemoline being taken from researcher pocket, along with the rest of their post equip going.

Also what the fuck is an injector case, in that case? Because the case that takes bottles also takes injectors. Some have injectors in them, others have bottles but they're the same thing.

**Comment by Weedmaster77** [comment]
> The files for this pr straight up show Lemoline being taken from researcher pocket, along with the rest of their post equip going. 

I though so kinda think that the 10u bottle should be give back to the RSR. Not sure why it was  taken in the first place being that all the RSRs that I talked to including myself don't make  Dermaline or Meralyne which seem to be the reasoning that was given for taking it out so that makes no sense . And most  RSR use it as a Catalyst in chems like Somolent and Neuraline which to be honest I think a RSR has more grounds to make Experimental chems then a Regular Doctor. CMO on the other hand makes sense to have Lemoline in a large amount.

**Comment by Arctrooper8** [comment]
> The files for this pr straight up show Lemoline being taken from researcher pocket, along with the rest of their post equip going.
> 
> Also what the fuck is an injector case, in that case? Because the case that takes bottles also takes injectors. Some have injectors in them, others have bottles but they're the same thing.
> 
> Edit: oh I see. You removed the combat injectors case, but thats not actually an injectors case (it's not a child of that type), it just happens to have injectors in it.

Oh it was in the pocket. Guh, okay I can't read. I'll fix the lemoline now.

**Comment by Panzerkampfwaggen** [comment]
MOs and Rsr don't spawn with tweezers, is it unintended?

**Pull request merged**
