### PR TITLE
Spawners are no longer purchasable

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
Minion spam attributes to an amount of lag and are generally unfun and don't provide any engaging combat.
AI Xenos function perfectly no matter the dilation and players suffer instead.
King works around any pathfinding issues but just summoning them.
(There's a separate server that caters to players that desire this sort of gameplay.)
## Changelog
:cl:
balance: Xenos may no longer purchase Spawners or Smart minions.
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
Salt PR?

**Comment by RaidarV** [comment]
salt pr...

REAL !!

**Comment by Tailiik** [comment]
Maybe just limit it to one or two instead of outright delete

**Comment by ClosetedSkeletonGH** [comment]
> Maybe just limit it to one or two instead of outright delete

The only time they’re useful is when they can basically be used as wave type cannon fodder, but that only happens when there is a shit ton.

even then, they tend to lose significantly more rounds than they have ever helped win, and are just kinda noob bait

**Comment by Losenis** [comment]
The round didn't even end yet lmfao

**Comment by aGhostCoder** [comment]
Salt PR, but I agree and it should be removed. Please end this nightmare already.

**Comment by Coastfront** [comment]
Either remove it, cap the amount of minions that can active at once, or cap the amount of spawners to 2.
As comedic it is to witness an endless river, carrying with it the ferry to time skipping its beat as an insect for each grain in its floods the world as locusts, it is fucking horrendously stupid that queens can just decide to bootleg ddos the server with the magic of minion spam.

**Comment by Barnet2** [comment]
Minions are legit the most sleeper gameplay when I play xeno or marine. God bless they might be limited to silos now. Speed merge

**Comment by ThelastArchiver** [comment]
counterargumewnt ai xenos work badly their pathfidnign is bad to say the least if they dont provide engagign combat just buff them so they do but this is just a salt pr

**Comment by Coastfront** [comment]
> counterargumewnt ai xenos work badly their pathfidnign is bad to say the least if they dont provide engagign combat just buff them so they do but this is just a salt pr


THAT IS NOT THE MAIN ISSUE.
THE MAIN ISSUE IS THE FACT THAT THEY'RE BEING USED TO FUCKING CAUSE 50% TD.

**Comment by Redrover1760** [comment]
Salt PR

**Comment by Ragecrabbo** [comment]
Salt PR

**Comment by Naaanii** [comment]
> Maybe just limit it to one or two instead of outright delete

Code is still available if anyone wants to make it better.
Silos can still spawn minions.

Otherwise, PVE TGMC exists.

**Comment by Naaanii** [comment]
> counterargumewnt ai xenos work badly their pathfidnign is bad to say the least if they dont provide engagign combat just buff them so they do but this is just a salt pr

As mentioned King negates the shitty pathfinding, so it's not an issue. The 'engaging' combat is the minions are better than majority of players because they don't miss a slash or spit when the server lags to shit. They only attritbute to stalling out rounds and forcing marines to FOB hug, spam conveyors and get req shit which turns the round on its head and now it's an unfun slog for Xenos so no one is having fun.

**Comment by Luxyboo** [comment]
i agree that this is a salt PR but minions have been in the game way longer than they should have

**Comment by AtlasRules** [comment]
for that last round alone minions should get the cut

**Comment by srxtreme** [comment]
Salt PR. Leave HWL alone you monsters

**Comment by Aporhtonoma** [comment]
salt pr please speedmerge

**Comment by wezsel11** [comment]
I'm sorry hivers, but I got to do this. 
CUT MY SILO INTO PIECES, THIS IS MY LAST RESORT. SUFFOCATION, NO BREATHING, DON'T GIVE A FRICK I CUT MY ARM BLEED'N. 

DO YOU EVEN CARE IF I DIE BLEEDING? WOULD IT BE WRONG? WOULD IT BE RIGHT? IF I TOOK MY UNGA TONIGHT?
CHANCES ARE THAT I MIGHT. MUTILATION OUT OF SIGHT, AND I'M CONTEMPLATING UNGACIDE.

/me teleports behind the xenomorph, pushing
 his katana into the exoskeleton with such a force that the air surrounding the xeno is pushed away. He pulls his katana out of the skeleton of the xeno taking the 2nd heart with it. Vergilli grabs the 2nd heart of the xeno and takes a bite out of it. He then gives a slight bow and tips his hair back saying: "Nothing personel". He then runs away with lighting speed, ready for his next strike.

https://user-images.githubusercontent.com/33401862/212567556-e885728a-1ea0-4893-95c6-b118cec039cb.mp4

**Comment by Zangeiti** [comment]
for the love of tgmc please speedmerge

**Comment by Strayed-Raven** [comment]
Rework minions into something else if you can. Keep it for HWLs legacy. i like them

**Comment by Al-1ce** [comment]
Salt PR. Bite a .44.

**Comment by Al-1ce** [comment]
Saltiest PR in the entire repo.

**Comment by Losenis** [comment]
rip WO gaming
image

**Comment by vilereaver41** [comment]
I'm gona support this, i was never a fan of minions anyway as i believe player skill should be the only thing to make a difference, i also do believe minions affect frame drops.

**Comment by FIXTHERADBOXPLEASE** [comment]
Extremely pre-emptive salt PR. 
If Xenos continue to use this strategy(as they have before), then literally just give marines a day or two to adapt to it and win (as they have before.)

**Comment by TiviPlus** [comment]
Clearly salt pr

**Comment by RaidarV** [comment]
> Extremely pre-emptive salt PR. If Xenos continue to use this strategy(as they have before), then literally just give marines a day or two to adapt to it and win (as they have before.)

DID YOU PLAY IN THE 50% TD ROUND ?

DID YOU ? DID YOU SEE PLAYERS AND ADMINS REE'ING AT EACHOTHER IN OOC ?

HOLY SHIT, YOU XENOMAINS. ITS NOT ABOUT BALANCE ITS ABOUT SERVER NOT SHITTING ITSELF !!!

**Comment by Losenis** [comment]
"Salt pr" they say about the round marines won by stacking an octodecillion bullets in the same tile like whisky outpost

Yeah mfs are salty about winning amirite

**Comment by FIXTHERADBOXPLEASE** [comment]
Wow that's even worse. So marines won and STILL malded this hard? Hilarious.

**Comment by Naaanii** [comment]
> Wow that's even worse. So marines won and STILL malded this hard? Hilarious.

You're missing the point that it's still not fun to play a laggy around against NPCs. No one really cares about winning or whether it's a viable strategy or not. We don't have a ranked system here, only 5% of our players actually care about winning while the rest just want to have fun.

**Comment by Losenis** [comment]
Nobody likes playing turn-based combat tbh

**Comment by Al-1ce** [comment]
> Nobody likes playing turn-based combat tbh

Probably should change platforms then. We are BYOND this.

**Pull request closed without merging**
