### PR TITLE
Removes legs and the orbital cannon from the game

### PR DESCRIPTION
**Pull request by TJatPBnJ**
## About The Pull Request
The orbital cannon and legs have been removed from the game. 

## Why It's Good For The Game
Raises awareness for people with leg disabilities, also I think the orbital cannon is OP. If this gets merged I'll add wheelchairs to the maps as a balance patch.

## Changelog
:cl:
del: Removed legs from the game
del: Removed the orbital cannon from the game
/:cl:

### CODE REVIEW

**Review by XSlayer300 — CHANGES_REQUESTED** [review]
I am a marine main, and I do not approve this.

**Comment by TJatPBnJ** [comment]
i do not need your approval

**Comment by XSlayer300** [comment]
Yeah, but you need the maintainer's approval too.

**Comment by TJatPBnJ** [comment]
whath's a maintainer

**Comment by TJatPBnJ** [comment]
nevermind, i figured it out

**Comment by TJatPBnJ** [comment]
should i have made this into two prs

**Comment by David-Stormwell** [comment]
Nice.

**Comment by TJatPBnJ** [comment]
ill make this 2 prs tomorrow im kinda tired right now

**Comment by Gooboi** [comment]
This is an excellent PR, why didn't I think of this?

**Comment by AtlasRules** [comment]
all personnel I am detecting a CLASS 9 XENOS MAD moment, I repeat,  a CLASS 9 XENOS MAD moment

**Comment by SilencedMP5A5** [comment]
imagine dying to the OB

-- this post made by people with eyes and ears

**Comment by Hughgent** [comment]
is good joke

**Comment by DinkleNH** [comment]
remove the ob and remove legs? thats badass re open this

**Pull request closed without merging**
