### PR TITLE
Removes barrel charger as an attatchment option for MG-27

### PR DESCRIPTION
**Pull request by ClosetedSkeletonGH**
## About The Pull Request

removes barrel charger from MG-28

## Why It's Good For The Game

With next to 0 aimmode slowdown encouraging mini-scope usage, this will make the gun a bit worse for being entirely used as an offscreen aimmode weapon

## Changelog

:cl:
balance: Removes barrel charger from MG-27
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
This makes it worse than the mg60 when deployed.

**Comment by Lumipharon** [comment]
RDS alone does nothing for the MG27 aim ROF due to byond ticks. The MG60 has the same dps as the MG27 if both are deployed.
MG27 is better when not on aim mode (which this doesn't touch) or when compared when using miniscopes.

This also makes it hilariously worse than prebuff.

**Comment by Lumipharon** [comment]
I removed the dnm, but honestly the more useful nerf would be to remove the BC. As stated, at closer range the T60 is already just as good, so this pr will make it worse. However with miniscopes (and so at further range) the MMG is considerably better than the T60.

**Comment by iforgotmeword** [comment]
"MMG is considerably better than the T60."
isn't that point? you're being forced TO STAY still and have a deployment time 
it's like nerfing the the rocket launchers because they are considerably better than recoilless launchers

**Comment by Xander3359** [comment]
image
Checks are failing because you removed /obj/item/attachable/heavy_barrel from attachable_allowed, however, you did not remove it from the gun that some loadouts have it on at line 413.

image

**Review by Lumipharon — APPROVED** [review]

**Review by Xander3359 — APPROVED** [review]

**Comment by antropod** [comment]
This PR made the gun useless, xenos are just outrunning bullets now

**Pull request merged**
