### PR TITLE
deletes evolution paths, every xenomorph can evo into the next tier

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
t1s can evo into all t2s and all t2s into all t3s, the exception is drone since i have no clue how to that so only drone can become shrike/queen for now

## Why It's Good For The Game
evo paths are awful mechanics, they shouldn't exist anymore

## Changelog
:cl:
balance: every xenomorph can evo into their next tier with no restrictions, evo paths are gone
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -83. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Texicos** [comment]
but why?

**Comment by Wayland-Smithy** [comment]
How come queen and shrike stay locked to drone? The very 2 castes you must evolve to for preventing hivemind collapse when time most precious must be spent devolving and waiting for larva/drone evo progress.

**Comment by neohenry** [comment]
> 
> 
> How come queen and shrike stay locked to drone? The very 2 castes you must evolve to for preventing hivemind collapse when time most precious must be spent devolving and waiting for larva/drone evo progress.

We could add to devolve to any tiers you want.

**Comment by Wayland-Smithy** [comment]
> We could add to devolve to any tiers you want.

A likewise change so that regression can happen to any caste of any lower tier and not just the immediate next tier could work. I also remembered Drones ignore evolution points for Queen and Shrike so if it's only 2 steps, one regress and one evolution, from any caste that would be great. Health and Plasma requirements would still apply.

**Comment by Surrealaser** [comment]
I would allow any caste to evolve to Queen/Shrike as well, so the poor workhorses don't have involuntary leader duty added to their obligations alongside weeding and hiving.

**Comment by Chaznoodles** [comment]
Based

**Comment by Walarks** [comment]
1st step to making all xenos available at t1.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Do it by changing how evo is done not whatever this is supposed to be

**Comment by Pariah919** [comment]
oh boy

**Pull request closed without merging**
