### PR TITLE
Baneling Removal

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
image
Basically a revival of #14415
## Why It's Good For The Game
I agree with most of MJP's points on #14415 that you can read, but for me tldr; this caste is a net negative to the game, and goes against any sort of risk/reward that may be in the game. Even the castes designed to be omega safe (warlock/boiler) are both T3 and are not **completely** risk free. Turning baneling into a minion doesn't solve that issue either; gas is a very powerful tool and should be relegated to higher castes with even just slightly more risk. A caste needing a complete rework right out of the box isn't good for TGMC, I wager.
## Changelog
:cl:
del: Removed Baneling
/:cl:

### CODE REVIEW

**Comment by coldironwarrior** [comment]
yes but you gotta delay until i hit prime, bro

**Comment by efzapa** [comment]
I was gonna minion it since that's what kuro said he specifically wanted done but maint moment

**Comment by AusarAtkin** [comment]
Just move it to buyable Pods, and make it a minion, its a neat caste with its own situational use, would be a shame to have it be yeeted completely.

**Comment by Kuro020** [comment]
> I was gonna minion it since that's what kuro said he specifically wanted done but maint moment

took too long

**Review by Kuro020 — APPROVED** [review]

**Comment by efzapa** [comment]
> > I was gonna minion it since that's what kuro said he specifically wanted done but maint moment
> 
> took too long

joever 

could have just told me removing it was fine from the start gug

**Comment by Yttriums** [comment]
RIP baneling. someday you will return as the seasonal caste we deserve

**Comment by SimplySmiley123** [comment]
Thank fuck, risk free addition to the gas spam wasn't nice.

**Comment by lbnesquik** [comment]
> RIP baneling. someday you will return as the seasonal caste we deserve. Also banes countered nade spam, which is still somehow unaffected by any recent balancing, so rip

How did it counter nade spam? People didn't fire nades at it.

**Comment by ju45he** [comment]
Huge nerf idea: Make it need to stay within range of its pod in order to revive, I don't know what a great number for it is so baneling players can make suggestions. This way marines can push towards the hive and potentially stumble across a pod for an easy kill. Maybe even make it a T2 or be trackable with a xeno location pinpointer or something.
Maybe even make it so explosion is based on plasma amount, and give it a constant plasma drain when off of weeds.
Please nerf it into the ground instead of removing it, I fucking hate going T3 just for me to be forced to pick between a gas caste or losing the round.

**Review by Lumipharon — APPROVED** [review]

**Comment by Lumipharon** [comment]
rip cutie, I will miss your waddle

**Pull request merged**
