### PR TITLE
Makes the AI unable to interact with dropship doors.

### PR DESCRIPTION
**Pull request by DominikPanic**
Fixes: #1802

### CODE REVIEW

**Comment by spookydonut** [comment]
what if you pulse the wires

**Comment by DominikPanic** [comment]
> 
> 
> what if you pulse the wires

no_panel = you cannot unscrew it to mess with the wires.

**Comment by spookydonut** [comment]
> 
> 
> > what if you pulse the wires
> 
> no_panel = you cannot unscrew it to mess with the wires.

no_panel should probably be a flag as should this ai controllable thing

**Comment by DominikPanic** [comment]
Feel free to make it one, /tg/ doesn't do it so I'm not going to do it for compatibility reasons.

**Pull request merged**
