### PR TITLE
Decreases slug sunder and pen

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
What is says on the tin. 

This isn't specifically to solve currently funny shotgun issues, it's just a general issue that slugs got buffed a year ago to have considerably higher damage, very high pen and absurdly high sunder, all on a stagger/slow/weaken platform, and it's more readily apparent now you see them get spammed. Getting your armour shredded to nothing by huge sunder for 10 minutes is guh.

Nerfs sunder to 5 from 15(!).
AP changed to 15 from 20 for slugs, and 10 from 15 for incend slugs.

## Why It's Good For The Game
Slugs being good at literally everything is bad funni not good funni

## Changelog
:cl:
balance: reduced the sunder and AP of shotgun slugs
/:cl:

### CODE REVIEW

**Review by Pariah919 — CHANGES_REQUESTED** [review]
No from me, slugs have high sunder specifically to offset the downsides of using them which is less overall damage, and I don't see why you're even nerfing incend slugs in the same PR.

**Comment by Lumipharon** [comment]
flech specifically had superior sunder, and it still does on the tx15. It's inconsistant and was powercrept to begin with.

**Comment by Losenis** [comment]
Cutting sunder by over half feels like a sledgehammer approach given it's still ammo that needs to be loaded with handfuls and spamclicking a specific amount (prepare to get fucked if you accidentally click one more time than the handful, that's taking one slug out). Even the autoshotty still just uses normal magazines that can even be tacloaded without unwielding at all, something you just can't do with the shotguns that use this ammo.

**Comment by Serxule** [comment]
> it's still ammo that needs to be loaded with handfuls and spamclicking a specific amount (prepare to get fucked if you accidentally click one more time than the handful, that's taking one slug out)

this is actually a skill issue, i have absolutely no problems with loading shotguns in combat

**Comment by Al-1ce** [comment]
> (prepare to get fucked if you accidentally click one more time than the handful, that's taking one slug out)

I've never once had this happen. As for the PR itself, I think slugs are fine where they're at

**Comment by Naaanii** [comment]
Slugs are fine overall and this doesn't really solve any existing issues with slugs.

Incen nerf also seems unnecessary.

**Comment by KrabSpider** [comment]
Slugs are mechanically stacked and I'm all for knocking them down.

**Comment by BraveMole** [comment]
MJP said no

**Comment by Serxule** [comment]
> MJP said no

who asked

**Comment by Naaanii** [comment]
The issue really lies with shotguns being spammable and juggleable and not slugs in particular.

**Pull request closed without merging**
