### PR TITLE
Fixes Aim Mode fire rate debuff bypass.

### LINKED ISSUE #5542: Aim Mode fire rate debuff not applying during automatic fire
## Testmerges:

not relevant

## Reproduction:

1. Wield a gun with aim mode and automatic fire.
2. Turn on the channelling for aim mode
3. Start auto-firing before the bar fills up
4. You have IFF with the pre-aim mode fire rate as long as you don't stop firing.

### PR DESCRIPTION
**Pull request by Walarks**
## About The Pull Request

Fixes being able to fire with pre-aim mode fire rate while retaining the IFF.

Fixes #5542

## Changelog
:cl:Slotbot
fix: fixes #5542 by adding a busy check at able_to_fire proc
/:cl:

### CODE REVIEW

**Comment by Hughgent** [comment]
Don't have the `fixes XXX` in the CL itself.

**Review by Hughgent — APPROVED** [review]
LGTM

**Review by TiviPlus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is now above zero (2). Feel free to make Feature/Tweak/Balance PRs.

**Comment by SplinterGP** [comment]
this makes gun not able to shoot in middle of wielding...

**Pull request merged**
