### PR TITLE
Xeno fade in on spawn and evolution

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Adds fade in type fullscreen overlay on xeno spawn and evolution

## Why It's Good For The Game

Adds immersion

## Changelog
:cl:
add: Added fade in type fullscreen overlay on xeno spawn and evolution
/:cl:

### CODE REVIEW

**Comment by dopamiin0** [comment]
FIRST HIT LAG FIX REAL!????????

**Comment by TiviPlus** [comment]
> yes this is confirmed that loading this overlay file causes lag

Where citation

**Comment by yyzsong** [comment]
post an animation of it

**Comment by Waselon** [comment]
> > yes this is confirmed that loading this overlay file causes lag
> 
> Where citation

I tried adding an overlay on spawn on RUTGMC and xenos reported less lags. When fix was removed, game started to freeze-on-first-hit once again. Adding and removing the fix showed strong correlation with lags presence.

**Comment by Waselon** [comment]
> post an animation of it

same animation a marine would see when waking up from the cryosleep

**Comment by TiviPlus** [comment]
Because it doesnt bloody work, and people gaslight themselves that it does thats why

If this was a working fix then marines would not have hit lag (they already have this same visual as even indicated by the author), I asked multiple people who serially complain about it and they said it happens on marine. The PRs "fix" is just confirmation bias which is why I do NOT TM any of these "fixes" unless they have a technically sound background.

Im removing all references to fixing anything but the actual effect is fine

**Review by TiviPlus — APPROVED** [review]

**Comment by breadhunt** [comment]
> If this was a working fix then marines would not have hit lag (they already have this same visual as even indicated by the author)
Not necessarily. The xeno hit lag (although infamous foe first hit deaths) does return after a while of not being attacked, possibly BYOND unloads it? If this fixes it as a byproduct then awesome though.
..come to think of it, I don't think I've ever had hit lag pre drop.

> The PRs "fix" is just confirmation bias

A 20 second freeze --> instant death is pretty noticeable but I do get your point. I could provide recordings if you want to see the difference

**Comment by Lumipharon** [comment]
fade in when you evo is kinda weird but eh.

**Pull request merged**
