### PR TITLE
Remove delimb points from campaign

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
After scenes that would go straight to the UN warcrimes tribunal, I've decided its better to simply remove points gain from delimbs entirely.
## Why It's Good For The Game
Chopping up the dead and dying for fun and profit is not ideal.
## Changelog
:cl:
balance: Campaign: Delimbing no longer provides additional credits
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
Why not make it count delimbs only if the victim is living?

**Comment by Lumipharon** [comment]
because then they're just going to do it to living people instead of dead people, which is only marginally better (or worse, depending on your perspective)

**Comment by Technical-l** [comment]
you know getting delimbed in hvh kinda sucks, beheading is funny tho. Just hate to see it when my SL has no arm so no epic SoM beheadings is a fair price to pay

**Comment by Looking4bros** [comment]
Delimbing is like securing the kill, it's its own reward.

**Comment by lbnesquik** [comment]
Not a full 24h

**Pull request merged**
