### PR TITLE
Fix's CSE and STs ID's not having access to engineerprep and RO locker

### PR DESCRIPTION
**Pull request by Derrick2Electricboogaloo**
## About The Pull Request

Small bug that has been around for a while, STs and CSEs can use the ASRS tablet but not get access to it. This corrects that finally. Also allows CSE and ST access engineer prep.

## Why It's Good For The Game

Bug fix good, smashing locker bad

## Changelog
:cl:
qol: CSE and ST can now open RO locker instead of smashing it open.
qol: CSE and ST now can walk into marine engineering
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
I am thinking I should give them marine engineer prep access, no idea why not?

**Review by TiviPlus — CHANGES_REQUESTED** [review]
What exactly is bugged here

**Comment by Derrick2Electricboogaloo** [comment]
> What exactly is bugged here

So the ST and CSE ID could not open the RO locker without outright breaking it open, but they could use the ASRS tablet. Just makes it easier for ST and CSE to fulfill their aRO role if the need arises. They have normal cargo access, they should have access to the RO locker.

**Comment by TiviPlus** [comment]
That doesnt explain what they need to be doing and it debatable if they should have tablet access in the first place

**Comment by Derrick2Electricboogaloo** [comment]
> Member

Seriously? They naturally fit aRO roles, and I say engineer prep access because there is discarded equipment they can use/take to req.

**Comment by Derrick2Electricboogaloo** [comment]
Maybe I should fix the labels to QOL, since this is more of a quality of life thing.

**Comment by Derrick2Electricboogaloo** [comment]
> What exactly is bugged here

Okay I think I was misunderstanding the 'fix', so I relabeled it QOL given that, that is actually how it is.

**Comment by FIXTHERADBOXPLEASE** [comment]
> That doesnt explain what they need to be doing in prep and it is debatable if they should have tablet access in the first place

Don't they have access because STs are just cargo techs that can engineer?

**Comment by Derrick2Electricboogaloo** [comment]
> 

They do not, they have access to the requsitions locker, but the ASRS is in the RO locker which has the different access ID. For what ever reason. Pretty sure just an oversight, but this PR corrects it.

**Comment by Derrick2Electricboogaloo** [comment]
> What exactly is bugged here

Can you remove the fix tag, and change it to QOL? I was hoping draft conversation and reopening it would relabel it. As I realize it is not a bug, and rather, quality of life improvement.

**Review by Derrick2Electricboogaloo — COMMENTED** [review]
Just QOL, not a bug fix.

**Pull request closed without merging**
