### PR TITLE
uniforms are bulky

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
why are these normal sized lmao

## Why It's Good For The Game
image

## Changelog
:cl:
fix: uniforms are bulky now
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
In 500 years, humanity will have forgotten how to fold clothes.

**Comment by Ieteihowmee** [comment]
> In 500 years, humanity will have forgotten how to fold clothes.

Apparently.

**Comment by Al-1ce** [comment]
> > In 500 years, humanity will have forgotten how to fold clothes.


Clothes folding PR?

**Comment by SplinterGP** [comment]
i'd say make webbing increase clothes size ?

**Review by TiviPlus — APPROVED** [review]

**Pull request merged**
