### PR TITLE
No more sharpened sharpened shovel

### PR DESCRIPTION
**Pull request by goose4429**
## About The Pull Request

Adds checks on shovel to not be sharpened while it's being sharpened. Doesn't affect anything except the name. 
image

## Why It's Good For The Game

Bugfix. If you really want to have super sharp shovel just drop it on the ground and call some friends. Didn't fix that yet.

## Changelog
:cl:
fix: Shovel can't be sharpened more than once
/:cl:

### CODE REVIEW

**Comment by Derrick2Electricboogaloo** [comment]
Wait does this actually make digging instant?

**Comment by private-tristan** [comment]
> Wait does this actually make digging instant?

it's purely cosmetic and makes the name bigger so whenever I look at chat I'll see 
"Unga  Bunga throws the Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened entrenching tool"

**Comment by Derrick2Electricboogaloo** [comment]
> > Wait does this actually make digging instant?
> 
> it's purely cosmetic and makes the name bigger so whenever I look at chat I'll see "Unga Bunga throws the Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened Sharpened entrenching tool"

That is funny.

**Review by TiviPlus — APPROVED** [review]
_sharpens your code_

**Pull request merged**
