### PR TITLE
Mech minigun buff

### PR DESCRIPTION
**Pull request by Kuro020**
## About The Pull Request

Buff mech minigun damage, nerfs AP

## Why It's Good For The Game

I might have made the minigun just straight up worse than the LMG in the last nerf pr, oops

## Changelog

:cl:
balance: Mech minigun damage buffed to 30, AP nerfed to 10
/:cl:

### CODE REVIEW

**Comment by maikilangiolo** [comment]
Why nerf the AP a second time?

**Comment by Kuro020** [comment]
> Why nerf the AP a second time?

It wasnt nerfed on the first pr, this is basically reverting the damage nerf and nerfing ap instead to differentiate the minigun from the lmg a bit more

**Comment by maikilangiolo** [comment]
Makes sense. Lmg still triumph with same rof, more ammo, accuracy, less slowdown...
I think giving the minigun a higher sunder would be good. It becomes a harder hitting gun where you can chip away, like I assume it's supposed to be.

**Comment by Serxule** [comment]
> I think giving the minigun a higher sunder would be good. It becomes a harder hitting gun where you can chip away, like I assume it's supposed to be.

with something like this, i dont think you could do noticeably higher sunder without it being OP

**Pull request merged**
