### PR TITLE
Puppeters puppets can have pheros

### PR DESCRIPTION
**Pull request by Aporhtonoma**
## About The Pull Request
Puppeters pheros can now benefit from pheromones that other xenos near them emit .
importand edit:
image
I asked 
## Why It's Good For The Game
Puppeter puppets feel like they could use the extra oomph as even for minions they feel lack luster for their price . With pheros they should heal in a more timely fashion and not fall completely behind puppeter in battle.
## Changelog
:cl:
balance: puppeters puppets benefit from pheromones other xeno emit.
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
Didnt Zaro explicitly make it so they couldnt, and also can his Widow-phero-only idea

**Comment by Aporhtonoma** [comment]
> Didnt Bowl explicitly make it so they couldnt, and also can his puppet-phero-only idea

I always assumed it was a balance stand point because they only recieved pheros if he was lead but Ill ask bowl in case it was a design choise

**Comment by FunkyMonke47** [comment]
Balancing a caste around tedium is not fun, having to wait super long for your puppets health to Regen when the caste wants you to bless them and keep them alive is painful.

**Review by Kuro020 — APPROVED** [review]

**Comment by SimplySmiley123** [comment]
>caste falls behind in battle
>can still melt marines it gets it's puppets to

**Pull request merged**
