### PR TITLE
new valk sprite overlay for xenonauten

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

https://user-images.githubusercontent.com/6610922/210475984-0352b211-27ba-4168-920c-104609b4a203.mp4

## Why It's Good For The Game

I can ensure you that many people like the xenonauten modules overlay with the sheer exception of valk. Sprites intended to convey that their limbs are protected, though the aesthetics is disgusting at best. Even Kuro agreed that he wanted something else, so I went out of my way to make it better.

With the advent of Jaegar's end, this PR is a step toward improving what we got, Xenonauten.

Animation resembles heartbeat since valk is always listening.

Also, special effect was due to Lumi being concerned about visual balance, and I hate myself for wanting to pull this off.

## Changelog

:cl:
imageadd: new valk sprite overlay for xenonauten
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
what if the cross was red instead? the red aesthetic of valk before was pretty kewl
or maybe that would be hard to see once hte marine is covered in blood?

**Comment by Lumipharon** [comment]
This is harder to see than the old one, and the chest can be obscured by storage attachments and stuff.

**Comment by novaepee** [comment]
> what if the cross was red instead? the red aesthetic of valk before was pretty kewl or maybe that would be hard to see once hte marine is covered in blood?

We can't do red because American Red Cross will DDoS us faster than a Putin sympathizer.

**Comment by Lumipharon** [comment]
> > what if the cross was red instead? the red aesthetic of valk before was pretty kewl or maybe that would be hard to see once hte marine is covered in blood?
> 
> We can't do red because American Red Cross will DDoS us faster than a Putin sympathizer.

The Red Cross logo is specifically a red cross on a white background. If it's just the cross itself, it's just a cross that happens to be red. People still seem to shy away from it though.

**Comment by Redrover1760** [comment]
Making it red would help separate it from Mimir.

**Comment by Kuro020** [comment]
> This is harder to see than the old one, and the chest can be obscured by storage attachments and stuff.

but I mean, the current one can be hidden too, idk how elsa would fix this

**Review by Kuro020 — APPROVED** [review]

**Comment by Derrick2Electricboogaloo** [comment]
Current valk on Xenonaut is perfect. No changes needed.

**Comment by Coastfront** [comment]
> Current valk on Xenonaut is perfect. No changes needed.

Perfectly abhorrent

**Comment by Derrick2Electricboogaloo** [comment]
> > Current valk on Xenonaut is perfect. No changes needed.
> 
> Perfectly abhorrent

WRONG

**Pull request merged**
