### PR TITLE
Modularizes Standard armor + headgear

### PR DESCRIPTION
**Pull request by hyper2snyper**
## About The Pull Request
All suit slot armor available in the standard vendors can take jaeger modules.
Also modularizes robot armor. It no longer has internal storage but can take the storage modules.
Berets can now take helmet modules.

And I fixed the hlin attached icon that was broken and fixed the researcher labcoat being offset 1 pixel to the right.

## Why It's Good For The Game
This adds some viability to things like marine harness and armored labcoat. It wont effect balance in the slightest since the little bonus for storage modules or health modules will not make these items comparable to regular armor in any sense. this adds cosmetic and utility to the less conventional armor choices.

If you want to have a marine harness and surt. You can.
If you want a armored labcoat and mimir. You can.
If you want tyr on your beret. You can.
If you want binocs on your beret. You can.

image

## Changelog
:cl:
add: All tgmc suits can now take jaeger modules. All berets can now take helmet modules.
add: Robot armor is now modular. It no longer has internal storage but can take the storage modules.
fix: fixed the hlin sprite not appearing.
fix: fixed the armored labcoat being one pixel too far to the right.
/:cl:

### CODE REVIEW

**Comment by DarkWolfKai** [comment]
modules for robots kinda sound... ehh... weird? dunno how valk will react with them, like, dunno, something? self-repairs ANYTHING...?

**Comment by Alexeivichi** [comment]
BIRD YOU BROKE EVERYTHING PLEASE FIX AHHHHHHHH

finally, berets.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
robots shouldnt have modules, its ass sprite wise (because robot mob sprites have a different perspective from humans) and they were balanced around not having modules

**Comment by ilikesaying** [comment]
Bird’s gaining power!

**Comment by vilereaver41** [comment]
So basically iron man

**Comment by ThelastArchiver** [comment]
just imagine robots walking around with tyr mk2 they would basiclly take no brute damage anymore and then add 3 shields to the equation that would be madness.

**Comment by Licherr** [comment]
the the layering hurt hurties my eyes, owwies

**Comment by ilikesaying** [comment]
> A robot with heavy armor and mimir mk2 gets 85% acid resist.

~~time to readd the 30% less brute and more 30% burn damage~~

**Comment by Lumipharon** [comment]
Please no robo buffs.

Also does this mean rambo man with beret and harness can have mk.II Mimir and be chem immune? That's pretty funny.

**Comment by AndroidMK2** [comment]
Combat robot armor is quite dog poop so making it modularizable is good, berets with modules? Kinda weird.

**Comment by AndroidMK2** [comment]
Robots don't have the 30% brute decrease and 30% burn increase, they are just worse humans so  I don't see the reason not to buff them in some way

**Review by Kuro020 — APPROVED** [review]
approved but if something looks whack we're gonna have to change it

**Review by BraveMole — CHANGES_REQUESTED** [review]
Didn't david said no to modular robot?

**Review by BraveMole — CHANGES_REQUESTED** [review]
This removes any kind of plausibility that armor still have. 

A magharness with surt is stupid enough, but a rice hat with a tyr just complety break the principle that an object has the same function as its appearance.

It is my understanding that david wants to be able to chose between decap or no decap ; fine, then do a neckguard that can be added to headgear, and that will fill this purpose.

By modularising everything you are just making every piece of equipment a cosmetic choice only; this just leads to more visual clutter than we have right now. 

Like magharness had a clear cut role: low armor no module high speed. What is the difference between a magharness and a light jaeger now?

**Comment by hyper2snyper** [comment]
> This removes any kind of plausibility that armor still have.
> 
> A magharness with surt is stupid enough, but a rice hat with a tyr just complety break the principle that an object has the same function as its appearance.
> 
> It is my understanding that david wants to be able to chose between decap or no decap ; fine, then do a neckguard that can be added to headgear, and that will fill this purpose.
> 
> By modularising everything you are just making every piece of equipment a cosmetic choice only; this just leads to more visual clutter than we have right now.
> 
> Like magharness had a clear cut role: low armor no module high speed. What is the difference between a magharness and a light jaeger now?

Ok so first. Most actual armor is armor. Berets/marine harness/whatever else has very little armor if any. Adding one tyr will grant it some, but nowhere near enough that it will remove the concept of armor to the point where its just cosmetic choice.
Boonie hat tyr is so what because its obviously completely inferior to an actual helmet.

Also, marine harness =/= light jaeger
Light jaeger slows down and has armor, marine harness doesnt slowdown and has no armor.
Furthermore, surt marine harness will not cause any problems because sure, you can walk through fire, but you will die in a slash or two. 
At the end of this. Armor will still be completely plausible and laughably superior to the other items because a marine harness isnt going to protect the use from much even if you give it tyr. 0 + 10  of marine harness + tyr =/= 40 + 10 of light armor + tyr. Armor will be just as relevant.

**Comment by BraveMole** [comment]
"Armor will be just as relevant." No it's not, the whole goal of this pr is to make every other piece of head clothing more relevant.

I have explained multiple time in discord and on this pr why i don't want this. You haven't provided any proper why it's good for the game either. "This adds some viability to things like marine harness and armored labcoat."

You're saying david wants this but no, David wants neck guards (which are absolutly fine IMO).

**Review by BraveMole — APPROVED** [review]
Blame david for this

**Comment by ilikesaying** [comment]
what is this sequence of actions bruh

**Pull request merged**
