### PR TITLE
magnetic harness slows you down when you wield with it on, has unwielded scatter

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
magnetic harness slows you down when you wield a gun, has unwielded scatter negatives so you can't get past this negative.

## Why It's Good For The Game
magnetic harness is way too good compared to the alternatives, rds gives you.. 10% accuracy. Compared to the MG which denies you dropping or losing your gun, ever.

## Changelog
:cl:
balance: magnetic harness slows you down when you wield with it on, has unwielded high scatter negatives aswell
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
image

**Comment by Alexeivichi** [comment]
This is the worst part of TGMC's lore.

**Comment by ZahaSanko** [comment]
MJP and the PRs of  chaos

**Comment by Losenis** [comment]
More like every other attachment is shit when they open you up to losing your gun in exchange for nothing in practice

>0.3 slowdown
That's a fucking tyr1 worth of slowdown

image
Nice undocumented nerf bro

**Comment by Pariah919** [comment]
> Nice undocumented nerf bro
i was going to update the pr with this, and just did

**Comment by lKiseki** [comment]
But why? Literally nobody complains about magharness ever, why do you want to nerf it at all?

**Comment by DerrickChamberlain** [comment]
Holy shit, can we stop with all these changes? You want mag harness to be fucking useless? Why not actually make other attachments more viable. CM levels of nerfing marine gear. Mag Harness has never been a problem and a lot of guns while fired one handed are inaccurate as fuck.

**Comment by MLGTASTICa** [comment]
Finnaly , a downside for a upside.

**Comment by Knuff-les** [comment]
Mfw I get beat to death by stun and displacement combat and now I get punished for not wanting to lose my gun

> Finnaly , a downside for a upside.

upside, or necessary part of the game for marine players....

**Comment by ilikesaying** [comment]
Mag Harness getting the old Barrel Charger nerf

**Comment by MLGTASTICa** [comment]
> Mfw I get beat to death by stun and displacement combat and now I get punished for not wanting to lose my gun
> 
> > Finnaly , a downside for a upside.
> 
> upside, or necessary part of the game for marine players....

arghghghgghg , what am i gonna do if i can't wield my GPMG back without infernal slowdown, aaa, side-arms and pockets for them are non-existant.

**Comment by Knuff-les** [comment]
> > Mfw I get beat to death by stun and displacement combat and now I get punished for not wanting to lose my gun
> > > Finnaly , a downside for a upside.
> > 
> > 
> > upside, or necessary part of the game for marine players....
> 
> arghghghgghg , what am i gonna do if i can't wield my GPMG back without infernal slowdown, aaa, side-arms and pockets for them are non-existant.

“yeah, I think ill go without my mag harness and take a pistol instead, this’ll surely be better”

who says this lmao

**Comment by DerrickChamberlain** [comment]
> Mfw I get beat to death by stun and displacement combat and now I get punished for not wanting to lose my gun
> 
> > Finnaly , a downside for a upside.
> 
> upside, or necessary part of the game for marine players....

Man it has been balance change after balance change, and marines getting cucked lots of times.

**Comment by Pariah919** [comment]
pizzapizzapizza

**Pull request closed without merging**
