### PR TITLE
Makes plasma cutters cut plasma

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
Do plasma cutters need this? Probably not. Is it going to matter with any frequency? Probably not. Am I making this PR anyway? Yes. 20% of the caste's max regenable plasma drained per hit.
Also conjugates plasma cutter's attack verbs, since they were showing up weird.

## Why It's Good For The Game
Fixes an inaccurate tool name.

## Changelog
:cl:
add: Plasma cutters now cut plasma, 20% per hit.
/:cl:

### CODE REVIEW

**Comment by novaepee** [comment]
melee spec 2.0

**Comment by goose4429** [comment]
Very based 12/10 love it

**Comment by Arctrooper8** [comment]
Does this drain blood and rage too? If so you should try and avoid that due to them being separate resources thematically.

**Comment by Al-1ce** [comment]
As mentioned above, this draining blood and rage is definitely concerning for balance.

**Pull request merged**
