### PR TITLE
Changes xenomorph rank from prime to primal

### PR DESCRIPTION
**Pull request by Mantlecrawler**
## About The Pull Request
Changes the rank of prime to be primal

## Why It's Good For The Game
Sounds cooler

## Changelog
:cl: Cheese
add: Prime xenomorph rank has been renamed to Primal.
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
Primal Primordial Ravager (Primal)

**Comment by ivanmixo** [comment]
Player reference??

On a serious note this also makes way less sense, lol. Doesn't really go along with the others in terms of it having to be a continuation of the advancement in the xenos' skill.

**Comment by Mantlecrawler** [comment]
> Player reference??
> 
> On a serious note this also makes way less sense, lol. Doesn't really go along with the others in terms of it having to be a continuation of the advancement in the xenos' skill.

Given that its mature -> elder - ancient, ranks denote a xenos time, but tbh "prime" doesn't make much sense in that way, you could argue that prime refers to "prime time" etc, but the usual assumption with prime is earlier in life, when a person is physically in the prime of their health.

**Comment by Lauwma** [comment]
How about primordial so you can get primordial primordial ravager lol

**Comment by Arturlang** [comment]
> Primal Primordial Ravager (Primal)

This is going to ruin my xeno name so bad

**Comment by Lumipharon** [comment]
stinky

**Pull request closed without merging**
