### PR TITLE
cheap barbed wire

### PR DESCRIPTION
**Pull request by tyeagg**
## About The Pull Request
barbed wire now costs 1 metal from 2
## Why It's Good For The Game
metal is expensive and limited and barbed wire is essential for a cade line. if your planning to make a good amount of cades its gonna take a good amount of metal just for the barbed wire so this solves that problem
## Changelog
:cl:
balance: barbed wire now costs 1 metal
/:cl:

### CODE REVIEW

**Comment by Shootnik01** [comment]
> metal is expensive and limited

And that is why it cost 2 not 1. Not only it makes xenos lose their hp,trying to break it, it also adds additional hp to cads.

**Comment by Losenis** [comment]
This'd also reduce the metal cost of razorwire from 3 to 2 since you can craft it with metal rods and barbed wire. This change affects way more than just barbed wire.

**Comment by Derrick2Electricboogaloo** [comment]
Blessed PR, make it happen!

**Comment by chizzy376** [comment]
Creepin'

**Comment by Tailiik** [comment]
Sittin and shittin on cades marines love it. Having a massive fob should be costly

**Comment by Naaanii** [comment]
Just order more metal or make it easier to get/salvage.

**Comment by chizzy376** [comment]
If you'd want more metal, I'd suggest instead PRing a reversal of decon mats. Like now, you only get 1 metal sheet and 1 metal rod from manually deconning an rwall, a time costly endeavor. Pry up some floor tiles instead and in the same time you get over 20-30 sheets using an autolathe. The balance is all over the place, yeah.

**Comment by Lumipharon** [comment]
Something being very good isn't a reason to make it cheap.

**Pull request closed without merging**
