### PR TITLE
Riot gear and stuff

### PR DESCRIPTION
**Pull request by Mrrpip**
## About The Pull Request

Well, It's raining and so I have nothing better to do, so I decided to muck about with coding and sprites.

This gives some changes to the riot gear crate: That 30 point 'SUCKER' sign.

It improves the riot gear crate in several methods.

-1: It's cheaper.

-2: The main armor has a light, updated armor values consisting of:
     -Standardized bio/fire/etc armor.
     -Tyr 2 esque improvements. (Tyr 1 bomb armor, Tyr 2 melee) and free ballistic plating!
     -Even slower than the normal riot gear.
     -It's weapon slot can hold anything a normal jaegar/xenonauten can.
     -Slightly different paintjob for distinguishability.

-3: The helmet also gets an update, don't worry, you can still find the old one groundside!
     -Lowered/standardized armor (Melee is equivalent to the free Tyr helmet)
     -A crummy paint job by yours truly, atleast xenos can distinguish it.
     -Ballistic head plating. Incase you hate baldies.
     -Still crummy acid armor, slightly improved though, yay!

Here is an image of the armor. Yeah, It's a bit orange, I've noticed.

https://cdn.discordapp.com/attachments/792079667494125591/956238778236797009/unknown.png

Note: This riot gear set cannot be used during Civil War, as it is unpurchaseable in that case and groundside riot gear uses a different variant

## Why It's Good For The Game

Well, it's more of a boredom thing because of it raining and being unable to go out with my mates. Because it's raining.

Buuuut: It fills a niche of having a ballistic helmet, for whoever hates getting shot in the head by allies and it you get a neat riot gear set with it!

As for the pricing: I have decided to go with 12 points because I believe it's an alternative variant to Tyr/modular armor with it's own benefits and drawbacks.

## Changelog
:cl:
add: Added the marine riot helmet, with a poorly made orange paintjob.
balance: Changed the pricing of the Riot Gear Set and their armor values.
/:cl:

### CODE REVIEW

**Comment by Mrrpip** [comment]
...In hindsight, probably should've used a better name for the PR.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
why do we need more marine available armor

We only have the main sets for a reason

**Comment by Mrrpip** [comment]
> why do we need more marine available armor
> 
> We only have the main sets for a reason

Because 1: It was a 30 point waste of space that could be found groundside. I would've been just fine tossing it out completely, but we may as-well try something with it first.

Because 2: The flak jacket was just fine being added to the main modular sets despite being objectively worse except for synth creep.

3: Armor balancing is frankly rather non-uniform anyhow.  The Xenonauten can take any uniform unlike the Jaegar, which is minor but can give advantages roundstart, such as nurse fatigues for +10 bio armor.

The SL helmet which is free can protect more than the B18's with Tyr, The flak jacket can be used with modules and synth, etc.

**Review by TiviPlus — APPROVED** [review]
nvm just realized that was valhalla vendor

**Review by Pariah919 — APPROVED** [review]
Has a gimmick, good for me. Someone might pick this now.

**Pull request merged**
