### PR TITLE
reduces shield durablity to 300

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
thing stuff title thing

## Why It's Good For The Game
mjp bad ban mjp
shield no longer effectively invcinible

## Changelog
:cl:
balance: drastically reduced shield health
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -57. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Review by Hughgent — APPROVED** [review]
variable change

**Comment by Denthamos** [comment]
Instead of reducing the durability for the shield it really should just not have no drop at all.  No drop on a defensive item like the shield is pretty insane.  A mag harness effect, sure.  I can see that.  But not no drop.

An overall durability decrease means that a melee oriented build which is already gimped by the fact you are going to be melee'ing mobs that can stun you and move faster than you, and you are giving up the back and belt/suit slot in order to go full melee could pretty much kill it.

**Comment by Pariah919** [comment]
>An overall durability decrease means that a melee oriented build which is already gimped by the fact you are going to be melee'ing mobs that can stun you and move faster than you, and you are giving up the back and belt/suit slot in order to go full melee could pretty much kill it.
>
uhh marines aren't balanced around melee the heck

**Comment by Hughgent** [comment]
"Conflicts" with #5138

**Review by TiviPlus — APPROVED** [review]

**Comment by neohenry** [comment]
> An overall durability decrease means that a melee oriented build which is already gimped by the fact you are going to be melee'ing mobs that can stun you and move faster than you, and you are giving up the back and belt/suit slot in order to go full melee could pretty much kill it.

If a marine doesn't check the durability of their shield and not repair it, then that is the fault of the marine to not fixing it. It's easy to get a blowtorch and welder helmet mod to fix the shield, not to mention that lately marines start to bring fuel tanks from shipside to planetside OR ask an engineer to refuel OR fix.

It is true that a shield user is facing against faster and stronger xenomorphs, but the shield user can withstand multiple punishments from xenomorphs without any issues. When the shield user reaches has at least half their health (assuming that the shield user has a healthHUB) OR the pain damage is starting to slow down the shield user, it's a better choice to recover the health than to pursue xenomorphs since (1) the shield user is slower than optimal, especially when dealing with xenomorphs, and (2) xenomorphs will punish a moderately wounded shield user.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-59). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
