### PR TITLE
Removes nightvision from amr and autosniper

### PR DESCRIPTION
**Pull request by Wisemonster**
## About The Pull Request
Title
## Why It's Good For The Game
Meant to be part of the reduction of scopes, keeping nightvision on these will make it impossible for boiler to exist if these are in play.
## Changelog
:cl:
balance: Removed night vision traits from the autosniper and anti-material rifle
/:cl:

### CODE REVIEW

**Comment by lbnesquik** [comment]
If the scopes are reduced in amount, how would AMR and Autosnipers keeping their scopes make it impossible for boilers to exist? They already have night vision., and with less scopes, surely boiler would already be better off than before.

**Comment by iforgotmeword** [comment]
make them give SG vision? this change makes sense but also removing their main perks of needing no light to work is odd

**Comment by chizzy376** [comment]
> keeping nightvision on these will make it impossible for boiler to exist if these are in play.

This is an obvious lie. Boilers depend on teamwork to function, ergo a defender for example. Counters exist for a reason, and removing the only "reliable" "counter" to a boiler (that can counter the counter by having some tanky caste stand in front) is not what should be done.

**Comment by Kuro020** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/16038

**Pull request closed without merging**
