### PR TITLE
adds a lolipop pouch to marine venders

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
adds a cool new lolipop pouch with TEN lolipops with ALL cool medical effects

## Why It's Good For The Game
more options for the game is cool

## Changelog
:cl:
add: Added new lolipop pouch with cool lolipops that heal you and stuff. As an equivalent to the marine medical pouches.
spriteadd: new boxes for lolipops
/:cl:

### CODE REVIEW

**Comment by mrhugo13** [comment]
You know what would make this ten times better?


Turn the lolipops into crayons.

**Comment by Al-1ce** [comment]
Lollipop is spelled with two L's.

**Comment by davidchan13** [comment]
> Lollipop is spelled with two L's.

Maybe he's going for the forbidden kind of lol

In all seriousness, this needs to be merged ASAP, and a follow-up PR needs to be made so that the Chem Master can produce Custom Lollipops.

**Review by TiviPlus — APPROVED** [review]
Are you going to fix the conflicts or no

**Comment by SplinterGP** [comment]
^

**Review by SplinterGP — APPROVED** [review]

**Comment by davidchan13** [comment]
Tried to buy one of these as a Smartgunner. Got an empty medical pouch and no lollipops. Admeme taunted me. 0/10.

**Pull request merged**
