### PR TITLE
map: metnal mining operation

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request

~~lava map 2~~
adds a new map: metnal mining operation
tacmap view kinda outdated; full-size is updated
metnal2
metnal
StrongDMM-2024-01-22 03 11 00

re-enables ash storms from lava outpost for this one but i changed the weighting so that they're not as often since lava is also an ever-present map hazard.

if anyone wants to go through the work of validating the nuke disk sets, uhhhhhhh, that would be cool, i really struggled with that.

## Why It's Good For The Game

~~lava map TWO~~
something about variety, also we pruned a lot of maps recently so hopefully this fills something in our rotation

## odds and ends
(sorry rip) i dont have a ton of time to maintain this (and won't for the foreseeable future). open to doing fixes and changes, but if there's anything of magnitude to be addressed that is critical to the map, i just cant get to it right now and understand if this has to be tabled for that reason.

biggest of thanks to closetedskeleton for helping me extensively with the iconcutter
also big thanks to elsa for a crash course and for teaching me about ai nodes which i've never worked with until now

## Changelog
:cl:
add: metnal mining outpost
/:cl:

### CODE REVIEW

**Comment by coldironwarrior** [comment]
i've conflicted with my own PR for adding the exact same item this is so sad

**Comment by novaepee** [comment]
Metnal's FOB is different in that it has multiple breach points, which entail having more cades than the average FOB.

**Comment by coldironwarrior** [comment]
> Metnal's FOB is different in that it has multiple breach points, which entail having more cades than the average FOB.

it has 4 like big red

**Comment by novaepee** [comment]
> > Metnal's FOB is different in that it has multiple breach points, which entail having more cades than the average FOB.
> 
> it has 4 like big red
> 
> image

mfw the shutters hid funny rocks

**Comment by DeltaFire15** [comment]
>if anyone wants to go through the work of validating the nuke disk sets

Disk set stuff looks like it's setup correctly.

**Comment by yyzsong** [comment]
BARRENQUILLA 2 LETS GO

**Comment by novaepee** [comment]
AI nodes need to be in cardinal direction in order to link up. If you want AI to move diagonal, the AI nodes need to be diagionally next to each other.

image

**Comment by coldironwarrior** [comment]
what did they mean by this:
Run yogstation13/DreamAnnotate@v[2](https://github.com/tgstation/TerraGov-Marine-Corps/actions/runs/7603003473/job/20704213330?pr=14870#step:7:2)
  with:
    outputFile: output-annotations.txt
Error: ENOENT: no such file or directory, open 'output-annotations.txt'

**Comment by RipGrayson** [comment]
> what did they mean by this: Run yogstation13/DreamAnnotate@v[2](https://github.com/tgstation/TerraGov-Marine-Corps/actions/runs/7603003473/job/20704213330?pr=14870#step:7:2) with: outputFile: output-annotations.txt Error: ENOENT: no such file or directory, open 'output-annotations.txt'

You have a number of double cables, as well as a few icon_state varedits on some airlocks and the linters are failing you.

**Comment by coldironwarrior** [comment]
> > what did they mean by this: Run yogstation13/DreamAnnotate@v[2](https://github.com/tgstation/TerraGov-Marine-Corps/actions/runs/7603003473/job/20704213330?pr=14870#step:7:2) with: outputFile: output-annotations.txt Error: ENOENT: no such file or directory, open 'output-annotations.txt'
> 
> You have a number of double cables, as well as a few icon_state varedits on some airlocks and the linters are failing you.

ic ic

**Comment by RipGrayson** [comment]
This PR is waiting to be added to the config, once that happens I'll give it a TM.

**Comment by blackdav123** [comment]
the fob should be made of rwalls instead of regular walls like every other map

**Comment by Barnet2** [comment]
Tadpole can't land on the basalt tiles, basically closing off the map to it entirely

**Comment by MiniMeatwad** [comment]
175 metal in engineering

Supposedly can't build in the middle of the map, but can build on some areas directly adjacent to LZ

**Comment by blackdav123** [comment]
Xenos need more places to retake disks from. Most of the disks are lone buildings surrounded by open fields and touching caves, which makes it just 20 minutes of marines shooting into cave entrances while xenos have no good spot to flank from. Adding more buildings as xeno healing spots especially for the southeast disks will make it less of a snoozefest doing disks

**Comment by spwoah** [comment]
Opinions from first round (FC pov):
- Very very very didactic. Colony had a lot of open spaces which will likely be abused to hold miners and impossible for xenos to fight in; caves was incredibly enclosed and impossible to push. (Think Lawanka first TM - since nuke is so fucking hard to push, it's not realistically going to be pushable in a "close" game. It is most likely more effective to silo rush at full strength instead of holding disks for 2 hours only to find that nuke is completely unpushable.)
^ Both xenos and marines moping about it being a biased map kind of reflects how this map literally punishes everyone, ever, and completely restricts options for BOTH sides. That's not really fun. What the fuck are xenos supposed to do in colony? What the fuck are marines supposed to do in caves? There is no tactics or decision to be made when the map itself punishes any action other than "die in open" "walk in one direction and shoot beno, then die"
- For the first round we played around with making catwalk bridges to cross lava; this was doable due to the fact that we had like 6 engineers, but there's not always 6 engineers. I imagine the map would be a lot more hellish without it.
- Little flagging on minimap for what is tadpole-able and what is not. We had a lot of confusion because tadpole can't land on basalt; this caused some really big issues.
- Very... empty. Not a lot of key/landmark locations. Big map but just felt like a whole lot of nothing.

Also why is the ENTIRE FOB REGULAR WALLS WHAT THE FUCK YOU GAVE MY ENGINEERS AN ACTUAL COLLECTIVE HEART ATTACK LMAOOOOO
6.5/10, cool ideas, balance is scuffed though, content is always appreciated 👍

**Comment by coldironwarrior** [comment]
> * Little flagging on minimap for what is tadpole-able and what is not. We had a lot of confusion because tadpole can't land on basalt; this caused some really big issues.

yea, i didnt exactly realize the basalt is locked like that, sorry.

this map is pretty disliked by both sides and i don't have the chops to rework it from the ground up, so off to the trash bin it goes.

**Comment by Ragecrabbo** [comment]
> this map is pretty disliked by both sides and i don't have the chops to rework it from the ground up, so off to the trash bin it goes.

I actually really enjoyed the map and despite its flaws its probably one of my favourite lava maps due to its unique structure. Unfortunate to hear you wont be working on it.

**Comment by MiniMeatwad** [comment]
> > * Little flagging on minimap for what is tadpole-able and what is not. We had a lot of confusion because tadpole can't land on basalt; this caused some really big issues.
> 
> yea, i didnt exactly realize the basalt is locked like that, sorry.
> 
> this map is pretty disliked by both sides and i don't have the chops to rework it from the ground up, so off to the trash bin it goes.

Deadchat salt is deadchat salt

**Comment by MiniMeatwad** [comment]
### As for ideas for changes:

* It could simply be more closed. You could throw some occasional walls here and there, in the shape of ruins or what have you, like some damaged buildings, fences, and maybe a rock wall against the lava streams.

* Remove the one tile lava sprinkled around.

* Add a few more flanks to areas like the medical/research building southwest of security sticking into caves. Research has no real flank around it without building a tunnel or making catwalks. The one tile flank on the south of research is also a deadman's land for both sides.

* The map needs more bridges or ways around, and experimenting with removing them over adding them if you want less.

### As for what looks like bugs:

* A lot of the windows on the map look like reinforced windows, but are plain windows, which have less health.

* There is a fireaxe cabinet in the engineering racks that should be moved near a wall and have displacement to appear as if it's on the wall.

* Make a new turf type for basalt that doesn't prevent tadpole landing, if that's an issue.

**Pull request closed without merging**
