### PR TITLE
neuraline now purges mera/dermaline at a incredibly fast rate

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
i was either going to do this or make them turn into toxin, but i think this is more fairer to the player than toxin probably, i can swap it to just make toxin anyway

## Why It's Good For The Game
stops ungajuice combos that heal you for incredible amounts of health a tick.

## Changelog
:cl:
balance: neuraline now purges dermaline/meralyne
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -61. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Dolth** [comment]
You're literally making a PR to nerf 5 players despite their actions not being an issue to balance.
This PR is just ruining fun for the sake of nothing.

**Comment by Pariah919** [comment]
>You're literally making a PR to nerf 5 players despite their actions not being an issue to balance.
This PR is just ruining fun for the sake of nothing.
> 
I'm removing the ability to heal literally 10 damage a tick, which is hilariously overpowered no two ways you look at it and nerfs your epic ungajuice combos (Which were nerfed a lot for a reason, they made marines heal hilariously fast in short amounts of time).

**Comment by Dolth** [comment]
Yes, a very strong chemical juice at the cost of using all your medical points into it and having literally just 3 uses per round.
And even though it does NOT make you immortal, you can still.
You're removing the ability for medics to instead have a ton of healing chems for their hypospray, to have 3 injectors per round that doesn't guarantee survival either then some chemicals leftovers which you are already going to nerf with the previous increase of neuraline cost.
Removing every bits of customization is the best way to lead this to CM and you're doing a marvellous job at it.

**Comment by MLGTASTICa** [comment]
Good PR , neuraline is way too powerfull when combined with advanced healing chems.

**Comment by Pariah919** [comment]
>Yes, a very strong chemical juice at the cost of using all your medical points into it and having literally just 3 uses per round.
And even though it does NOT make you immortal, you can still.
You're removing the ability for medics to instead have a ton of healing chems for their hypospray, to have 3 injectors per round that doesn't guarantee survival either then some chemicals leftovers which you are already going to nerf with the previous increase of neuraline cost.
Removing every bits of customization is the best way to lead this to CM and you're doing a marvellous job at it.
>
I mean I'm literally just increasing the point cost by 1 to add levels of customization, there's literally more actual thought put into the choice than just picking 2 meraderm+1 neuraline most of the time unless you want MOAR neuraline. 

This is just to stop super powergaming setups where you're basically invincible for effectively 30 seconds. That's pretty dumb.

**Comment by MiniMeatwad** [comment]
Neuraline is highly limited in availability, and a good xeno player (One that uses any stun ability properly) can still easily kill you with neurameraderm. Or just run away for a bit if alone and you have your neuraline wasted. You just don't get killed by really bad xenos (Those who never use any abilities). It's a good surprise tool that lasts 12 seconds maybe, but I wouldn't use it to run into the xeno hive or something ridiculous. It's not a magic tool that makes you unbeatable, you're just not falling over instantly because 4 xenos held down a movement key towards you and slashed you two times. You're still dead after the third though, and it always has to be injected right before or during combat and that means you're either defenseless during that period, or have less time to use the neuraline. Neurogas, neurotoxin, and larval accelerant make it even worse, it lasts maybe 4 seconds tops? I haven't checked because it's only a surprise tool that works on the unsuspecting, and even then it doesn't do anything against xenos with any teamwork or insight.

**Comment by Pariah919** [comment]
>Neuraline is highly limited in availability, and a good xeno player (One that uses any stun ability properly) can still easily kill you with neurameraderm. Or just run away for a bit if alone and you have your neuraline wasted. You just don't get killed by really bad xenos (Those who never use any abilities). It's a good surprise tool that lasts 12 seconds maybe, but I wouldn't use it to run into the xeno hive or something ridiculous. It's not a magic tool that makes you unbeatable, you're just not falling over instantly because 4 xenos held down a movement key towards you and slashed you two times. You're still dead after the third though, and it always has to be injected right before or during combat and that means you're either defenseless during that period, or have less time to use the neuraline. Neurogas, neurotoxin, and larval accelerant make it even worse, it lasts maybe 4 seconds tops? I haven't checked because it's only a surprise tool that works on the unsuspecting, and even then it doesn't do anything against xenos with any teamwork or insight.
>
Neuraline is infact an emergency chem, which is fine. But it shouldn't be stackable with t2 healing chemicals because else it heals way too fast.

**Comment by Dolth** [comment]
That's exactly my point, you're stacking 2 rare chems into 1 usage (out of 3 in total per round).
Having the whole mix is VERY costly. It's 12 seconds of healing, even if it's fast you can't outheal multiple xenos slashing at you.
And keep in mind bica/tricord/kelo/neura is still 9.3 per tick. Not much a big difference.

**Review by Hughgent — APPROVED** [review]
Code is fine

**Comment by Dolth** [comment]
Ah and as MiniMeatWad stated, you're still vulnerable to one-click larval growth injection from drones that will purge your shit, and yet again, it's 12 seconds.

**Review by TiviPlus — CHANGES_REQUESTED** [review]
Xeno larval is basically never used in combat by xenos that I see
Id rather have them make toxin when mixed together so it ha to be bundled with dylovenes downsides than a straight purge

**Comment by Dolth** [comment]
> Xeno larval is basically never used in combat by xenos that I see
> Id rather have them make toxin when mixed together so it ha to be bundled with dylovenes downsides than a straight purge

Neuraline already has 3.75 toxin per tick, if you turn meraderm into toxin then  you literally have no gain to counter it (beside using arith/hyronaline which will make a huge amount of brute).

Nah, this is just a silly nerf again.

**Comment by Pariah919** [comment]
>Xeno larval is basically never used in combat by xenos that I see
Id rather have them make toxin when mixed together so it ha to be bundled with dylovenes downsides than a straight purge
>
iirc i don't remember how toxin mixing in the body functions but wouldn't this basically cause the same thing but give you toxin unless you microdose

**Comment by TiviPlus** [comment]
With the other neuraline nerfs I dont see the point of this PR anymore as neuraline is fine as is so ill go ahead and close it

**Pull request closed without merging**
