### PR TITLE
Pillar of Spring 2023 Remodeling Part 1: Medbay Edition

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Medbay got remodeled to use more of the empty space, direct traffic, and expanded!

image

Boxing ring is near Alamo now.

image

Some addition in prep in light of medbay remodeling.

image

Don't get me started in disposial piping.

## Why It's Good For The Game

After observing closely to medbay flow from my recent work on it, I disliked how there was only a designated trauma bay with almost no RP life to it. 

image

Also, marines having access to med storage were not intentional. Sorry, but no go.

before
image

after
image

The PoS is the only shipside map of both CM and TGMC to ulitize the rear side of the Alamo, and the PoS trauma bay ought to get marines heal up ASAP.

image

I also compressed medbay a bit as a callback to old medbay.

image

This is vastly different compared to CM where it takes a while to get to the trauma bay.

image

Note that the reception area is optional unless you're getting something from the MarineMed

image

I also noticed that prep deserve some MarineMed since Theseus has MarineMed in prep. It's good practice so that marines prepping may choose to go to medbay.

image

I anticipate that corpsmen and MD want MEDEVAC beacon here.

image

also, my symmetry

Stay tune for more on starboard . . .

image

And possibly medical Overwatch . . .

image

## Changelog

:cl:
add: POS' medbay got remodeled to use more of the empty space, direct traffic, and expanded!
add: PoS' Boxing ring is near Alamo now.
add: Some addition in PoS prep in light of medbay remodeling.
/:cl:

### CODE REVIEW

**Comment by psykzz** [comment]
Are these not blocking the doors?
image

**Review by RipGrayson — CHANGES_REQUESTED** [review]
Space tiles here
van2
van3

These objects are in the way of the doors, please move them somewhere else.
van4
van5

**Comment by Barnet2** [comment]
> Are these not blocking the doors? image

You can walk through RSR consoles.

**Comment by psykzz** [comment]
Aesthetically though it doesn't look good

**Pull request merged**
