### PR TITLE
huggers stun you for 2s from 6s

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
title, literally

## Why It's Good For The Game
stun bad, die stun

## Changelog
:cl:
balance: huggers stun for 2 seconds from 6
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -315. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by InterroLouis** [comment]
It still stamcrits tho

**Comment by revelation-8468** [comment]
NO.

You do know right that we can pull facehuggers off in around about 2 seconds?

So, do the math. If it's a two second stun down from 6 how are we supposed to remove a facehugger?

This is a carrier buff disguised as a nerf.

**Comment by BeloneX** [comment]
> NO.
> 
> You do know right that we can pull facehuggers off in around about 2 seconds?
> 
> So, do the math. If it's a two second stun down from 6 how are we supposed to remove a facehugger?
> 
> This is a carrier buff disguised as a nerf.

Go actually look at the file changes instead of shouting random claims that aren't even true.

**Comment by TGCMbetcher** [comment]
Have you tried this and made sure that people cant just rip the hugger off their face when they get up? Or is this just for like swat masks and removed huggers and if you have the hugger on you youre still stunned?

**Comment by TiviPlus** [comment]
I'd prefer the carrier rework be balanced properly

**Pull request closed without merging**
