### PR TITLE
Gasmask Sprite Change

### PR DESCRIPTION
**Pull request by Suicidalpickles**
changes the default gasmask to the current /tg/ version

capture

(still keeps the tint, just a ghost screenshot)

### CODE REVIEW

**Comment by Alterist** [comment]
I don't see any reason to change the look of the gasmask, is it an Nic sprite?

**Comment by Suicidalpickles** [comment]
don't believe so, though I could always just add it in as an alt variant instead.

**Comment by Arachnidnexus** [comment]
Having both would be nice.

**Comment by Suicidalpickles** [comment]
alright I'll close it for now until I tweak that

**Pull request closed without merging**
