### PR TITLE
Makes the nuke call death() and deal more damage

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Please don't be dumb like me and be too lazy to test your 1 liner PR.
Makes the nuke call death so you *definetely* cannot survive the nuke
## Why It's Good For The Game
How does one revive from a literal nuclear explosion, or simply survive it's blast with one's mortal body?
## Changelog
:cl:
fix: The nuclear explosion will actually, properly, goddamn, kill you, instead of just singing you slightly
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
rip surivivng a literal nuclear blast it was funny while it lasted

**Review by spookydonut — APPROVED** [review]

**Comment by Pariah919** [comment]
wouldn't this break eord

**Comment by Arturlang** [comment]
> wouldn't this break eord

do_nuke_z_level only blows the people on the z_level in arguments, which should be the z-level that the nuke is on

**Comment by Strayed-Raven** [comment]
This is peak Xeno main PR

**Comment by MiniMeatwad** [comment]
Needs nuke lore, where's the 50 paragraphs explaining how to make a nuclear bomb?

**Comment by InterroLouis** [comment]
Doesn't seem super necessary to me. The round is about to end anyways, why not let someone have a little bit of fun by doing whatever it is they do to be not dead in the last few minutes of said round?

**Comment by Arturlang** [comment]
> Doesn't seem super necessary to me. The round is about to end anyways, why not let someone have a little bit of fun by doing whatever it is they do to be not dead in the last few minutes of said round?

Isn't that the main purpose of EORD?

**Comment by Arturlang** [comment]
As a counterpoint then, I could make the nuke simply deal no damage, what about that? @Strayed-Raven

**Comment by Luxyboo** [comment]
i rejuve people when nuke goes off so...

**Comment by chizzy376** [comment]
> Isn't that the main purpose of EORD? If you don't want to be dead, don't stay in the nuclear explosion radius, currently marines just ignore escaping the nuke often, many not even bothering to retreat since they'll probably survive the nuke anyways

Sounds like excuses
All this does is remove fun, not even a fix
Also marines will never run from nuke. Round ends anyways, why does it matter if you survive. Let people have fun.

**Comment by FIXTHERADBOXPLEASE** [comment]
Does the fridge still let you survive though?

**Comment by Strayed-Raven** [comment]
> As a counterpoint then, I could make the nuke simply deal no damage, what about that? @Strayed-Raven And even if you don't like marines dying from nuke, EORD will just revive them and put them in the arena
You...do realize people have EORD turned off. right?

**Comment by KrabSpider** [comment]
> > > As a counterpoint then, I could make the nuke simply deal no damage, what about that? @Strayed-Raven And even if you don't like marines dying from nuke, EORD will just revive them and put them in the arena
>>
>> You...do realize people have EORD turned off. right?

> has EORD turned off
> six minutes to evacuate the via transport beacon, the alamo, or tadpole
> complains when the nuke they had six minutes to flee from kills them (they wanted to RP with their fellow dead marines)

**Review by Lumipharon — APPROVED** [review]

**Comment by chizzy376** [comment]
> > complains when the nuke they had six minutes to flee from kills them (they wanted to RP with their fellow dead marines)

Yes because I do love being stuck inside of a 10x10 flying cube for the rest of the round instead of hanging out groundside where I was for most the op.
When is this getting reverted?

**Comment by Arturlang** [comment]
@chizzy376 Is the tadpole unable to land back on the ship after the nuke has exploded?

**Comment by chizzy376** [comment]
> @chizzy376 Is the tadpole unable to land back on the ship after the nuke has exploded?

Yes, all ships (including req platform) get frozen after round end.

**Comment by Arturlang** [comment]
Sounds like all shuttles should be recalled on nuke detonation or somewhat before.

**Pull request merged**
