### PR TITLE
Better disk spawns

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

This PR changes the locations of the nuke and the nuke disk generator of all playable maps to be easier to reach and reasonable to defend.

(Screenshots of the specifics coming in 14 hours, it's 2am and I need to sleep.

## Why It's Good For The Game

Most, if not all, of the maps are absolutely really bad on Crash because all the nuke disks or nukes are in hard to reach locations that are sometimes directly next to xeno spawnpoints or past them. This PR fixes that by relocating nuke stuff so it's easier to come across and defend.

## Changelog
:cl: BurgerBB
balance: All maps now have different nuke and nuke generator map spawns.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by BurgerLUA** [comment]
> You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Implying that balance fixes aren't issues that need to be fixed and aren't just as bad or worse than any bug that can get reported.

**Comment by Rohesie** [comment]
Part of the idea of the sites were to make more use of the map.
Are you removing parts of the map from the game?
Could you list the new locations?

**Comment by BurgerLUA** [comment]
> Part of the idea of the sites were to make more use of the map.
> Are you removing parts of the map from the game?
> Could you list the new locations?

The disks generators themselves are in locations that are closer together but are still spread out in major parts of the map.

**Comment by Rohesie** [comment]
In Big Red, for example, the classic hive locations were Lambda, ETA, and for suicidal ones Virology. That's where the disk generators were located.

And deep caves, also a traditional distress hive location, for the nuke.

**Comment by spookydonut** [comment]
> 
> 
> > You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> 
> Implying that balance fixes from map edits that literally every single player wants aren't fixes.
> Implying that balance/logic fixes from map edits that the map makers themselves admitted are issues that needed to be fixed aren't fixes.
> Implying that somehow me making 1 more balance PR than 1 more fix PR means that maintainers can close this PR at will because for some reason they need another excuse to close PRs they don't like.
> 
> I mean if you want me to stop making PRs and stop contributing to an open source project, I can. Alternatively I can add "Fixes another dev's bullshit because everyone else is too lazy to do map edits that take more than an hour." to my changelog because that's kind of what I'm doing here.

this is a bot that autoposts, we dont control it you'd need to take it up with TG maint team

**Comment by jroinc** [comment]
Thoughts on dropping the number of resin silos to something reasonable, like 1-2, so that marines can cut off ayy reinforcements if they push, and ayys have a home-base to defend if they want those sweet unlimited respawns?

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
