### PR TITLE
Bricks the brick

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Original pr wasn't meant to be merged.

Fixed some code guh, and brick is no longer comically strong. Bricks no longer magically transmute into stone.
## Why It's Good For The Game
You're lucky I didn't just revert it.
## Changelog
:cl:
balance: Reduced brick damage somewhat
/:cl:

### CODE REVIEW

**Comment by Windryn** [comment]
keep the brick as is. Save the brick,.

Stop restricting brick specifications

What are you the government?

What comes next our semi-automatic bricks?

**Comment by SELFHELL** [comment]
Alexa, why is my brick not turning on?

**Comment by 74delta** [comment]
🧱 squad is no more.....

**Comment by UncleBourbon** [comment]
brick yourself

**Comment by CVSthePharmacy** [comment]
next person, add the damage back to revert this change

**Comment by thatguythere03** [comment]
If you somehow manage to get killed by a brick as a Xeno, immense fucking skill issue.

**Review by ivanmixo — APPROVED** [review]
joe biden

**Pull request merged**
