### PR TITLE
Smartgunners get helmets in their boxes

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request

Title.

## Why It's Good For The Game
newbies no longer die horribly, and they no longer die horrifically

## Changelog
:cl:
fix: Readded helmets to SG box
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
Why not add it to the basic gear package in the vendor?

**Comment by davidchan13** [comment]
Just give them the option of helmet or heavy helmet in their uniform vendor.

**Comment by grinkgo** [comment]
> Why not add it to the basic gear package in the vendor?
> 
> ~do both. double helmet SG~

agreed here. Don't add it to their box, add it to their basics kit.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is now above zero (1). Feel free to make Feature/Tweak/Balance PRs.

**Pull request merged**
