### PR TITLE
Resprites/ports firedoor sprites, removes more flat icons

### PR DESCRIPTION
**Pull request by RipGrayson**
## About The Pull Request

Currently our firedoor sprites are flat and contrast with the rest of our art style, I ported a replacement sprite from Baystation and did some respriting so it fits here. 
I also ported a small number of icons from CM and fixed some invalid icon states in Thunderdome as well as adjusting some door icon_state paths to our existing modern door sprites.

Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/10529

## Why It's Good For The Game
Sprites like this
court3
court4
court5
offend me and I want to get rid of all of them, this PR is yet another step towards that goal.

## Changelog
:cl:
fix: Fixed a couple bad AI nodes
imageadd: Ported some icons from CM.
imageadd: Ported and resprited a firedoor icon from Baystation.
imagedel: Removed old fire door icon from game.
imagedel: Removed old exterior airlock icon from game.
spellcheck: fixed a few typos
code: Added a couple table and earmuff variants to the game.
/:cl:

### CODE REVIEW

**Comment by RedBaronFlyer** [comment]
Do you have some before and after pictures?

**Comment by RipGrayson** [comment]
> Do you have some before and after pictures?

court4
court6
Here's a before and after of the exit airlocks, albeit in game the doors are rotated so they look more like this
court8

**Comment by RipGrayson** [comment]
Here's the current fire doors on the ground
court9
and here's the resprited doors, undeployed
court10

**Review by Kuro020 — APPROVED** [review]

**Review by TiviPlus — APPROVED** [review]
omg changing file names to snake case love it

**Pull request merged**
