### PR TITLE
Rocket Sledgehammer Fix

### PR DESCRIPTION
**Pull request by Waselon**
## About The Pull Request

Apparently it has been broken since some rework that changed stun values.
Also updated description to inform the user that they can change attack modes.

## Why It's Good For The Game

fix

## Changelog
:cl:
fix: fixed rocket sledgehammer having incorrect stun values
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
What does this fix exactly. Can you be more descriptive?

**Comment by Waselon** [comment]
> What does this fix exactly. Can you be more descriptive?

it has wrong stun/weaken values until attack mode is switched at least once

**Comment by lbnesquik** [comment]
In practice, does it change the values for in-game?

**Comment by Waselon** [comment]
> In practice, does it change the values for in-game?

no, they are the same they were supposed to be

**Review by Lumipharon — APPROVED** [review]
probably better as defines than vars but eh

**Pull request merged**
