### PR TITLE
Construction pouches hold one unfolded shovel

### PR DESCRIPTION
**Pull request by QualityVan**
## About The Pull Request
Construction pouch max weight was increased so shovels can now fit inside while unfolded, but each pouch can only hold one.
Also lets you carry one on your back if you so wish.

## Why It's Good For The Game
The shovel is a critical tool to any marine operation, even though it's called an entrenching tool and trenches don't exist. Also this gives ways for engineers to actually carry a sharpened one without sacrificing their toolbelt.

## Changelog
:cl:
add: Top TGMC engineers have figured out how to get the hook on construction pouches to hold an e-tool while it's unfolded.
add: They also discovered a way to carry them on your back.
/:cl:

### CODE REVIEW

**Comment by BraveMole** [comment]
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7317

**Comment by EvilMelonTheSecond** [comment]
I've been meaning to make this one myself. Makes sandbags viable for frontline engineers AND isn't storage creep for other mats. Considering shovel itself is useless and sandbags got nerfed (many times) this is simply QoL.

**Comment by davidchan13** [comment]
wouldn't it just have been easier to allow e tools to fold after they have been sharpened?

**Comment by Ieteihowmee** [comment]
Folded shovels could have always been held in construction pouches before the slot increase. We should instead make it so you can attach the E-tool to your backpack or armor or something.

**Pull request closed without merging**
