### PR TITLE
Adds Imi,Alky and tricord pill bottles to marinemed

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Adds Imi and Alky and tricord pill bottles to marine med
## Why It's Good For The Game
Medics already get them, don't really see the need for these to be chem/medic only.
## Changelog
:cl:
balance: Added imi/alky/tricord pill bottles to marine med
/:cl:

### CODE REVIEW

**Comment by spookydonut** [comment]
increase peri to 3 bottles too?

**Comment by Hughgent** [comment]
On a somewhat related note, the Alkysine pills in the pillbottle are 10u each, which will heal 250 points of brain damage on a single pill. 

This is total and complete overkill. But I'll leave it up to you whether or not to change the dosage.

**Comment by drawsstuff** [comment]
my eye hurting juice: countered forever

**Comment by XElectricX** [comment]
Not too OP since they are pills, which cannot be refilled. Good addition for the MOs and CMOs to use.

**Comment by jroinc** [comment]
Can you please remove these 3 from being buyable in the medic's vendor as well?

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
