### PR TITLE
Riot Armor Nerf

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Riot Armor with security jumpsuit provides 90 melee armor, this is higher than B18 and riot armor can be found groundside on most maps.

So I reduced it to the same armor as heavy armor is.

## Why It's Good For The Game

Removes an overpowered item.

## Changelog
:cl:
balance: Nerfs Riot Armor
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Kuro-ai** [comment]
riot armor is very heavy slowdown,has no armor stats aside from melee,has no light,doesn't cover hands or feet,I don't see the reason for such a nerf,just reduce it to 80 melee

**Comment by Kuro-ai** [comment]
to top it off,you admited in discord you are nerfing this because you died to someone using it,nerfing out of salt is not a thing we should be doing

**Comment by Isy232** [comment]
Nerfing out of salt is bad, getting annoyed at something, looking at the numbers, realizing its a combo for 90 melee armor then deciding on nerfing it is totally rational.

**Comment by Kuro-ai** [comment]
Except it has no numbers on other armor types and the melee armor can be 100% ignored by targetting feet/hands/head

**Comment by Isy232** [comment]
Its too hard on xenos to have to, in combat, identify the armor worn then target which part of the body to attack and changing it depending on the marine your attacking. 

Its a level of robustness that should not be balanced around as I doubt 90% of the population could pull that off.

**Comment by Kuro-ai** [comment]
Xenos already do that,hand targetting meta was a thing

**Comment by Rohesie** [comment]
It having week hands/feet/head looks more like an oversight than a good balance implementation.

Can you fix this instead of just nerfing it, to make the armor useful in some way? Maybe make it something like a slow armor designed against rioters/humans (melee and bullet protection), but weak against other xeno stuff?

**Comment by Rohesie** [comment]
Closing due to staleness.

**Pull request closed without merging**
