### PR TITLE
Maturity tower provides 25% less bonus than before.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
25% less bonus, .2 to .15.

## Why It's Good For The Game
Maturity tower currently does far too much in its current state. Considering you can basically just place it in a corner of the map and never lose it.

## Changelog
:cl:
balance: Maturity tower nerfed by 25%.
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
> Maturity tower currently does far too much in its current state.


I'm fully convinced you've never actually seen a maturity tower in action before. Even several do little more than make a **mild at best** impact on the hives overall maturity, which already feels slow enough as it is, especially for latejoined xenomorphs who have to deal with an awkward "afk" phase if they'd rather not die at mature. 


>Considering you can basically just place it in a corner of the map and never lose it.


This is ..intended. It's not meant to be a high-value target like a silo, because it isn't. And yet, despite taking a fairly large amount of points to make, a single maturity tower will barely make a dent in the overall gameplay. It acts as little more than QOL to ease the waiting by a minute or two.

Salt PR. Simple as.

**Comment by Walarks** [comment]
I think maturity tower should do much more and be restricted to more vulnerable spots.

**Comment by private-tristan** [comment]
sitting in a corner until you hit mature/elder is good gameplay :)

**Comment by BraveMole** [comment]
Ok for changes to maturity tower, but a simple number balance won't cut it here.

**Pull request closed without merging**
