### PR TITLE
Give Warlock psychic whisper

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

title

## Why It's Good For The Game

WARLOCK'S BRAIN IS SO BIG HE CAN TELEPATHICALLY TALK TO MARINES AND TELL THEM, "COPE AND SEETH!" WHEN WARLOCK BLASTS THEM WITH ITS MIND! BEAT MARINES WITH PSYCHIC POWER?! MORE LIKE CRUSH MARINES THROUGH PSYCHOLOGICAL OPERATION!!

Due to how psychic whisper bypasses admin's oversight, I gave admins the ability to see what kind of message the xenomorph is sending to a marine.

## Changelog

:cl:
add: Give Warlock psychic whisper
add: admins can now read psychic whisper
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
the curse of ra

**Comment by MereWalker** [comment]
Make sure it logs for admins. Don't want a repeat of xenos sending erp over that with no way to log it.

**Comment by Al-1ce** [comment]
>Don't want a repeat of xenos sending erp over that with no way to log it.


my mind refuses to accept this was real

**Review by Lumipharon — APPROVED** [review]

**Comment by Derrick2Electricboogaloo** [comment]
> Make sure it logs for admins. Don't want a repeat of xenos sending erp over that with no way to log it.

Unironically?

**Pull request merged**
