### PR TITLE
Nerfs B18 Armor A Bit

### PR DESCRIPTION
**Pull request by Isy232**
## This PR is meant to be merged with other de-escalation PR's.
Also if in testing this is too much of nerf we can undo it, just see what these numbers get us too.

## About The Pull Request

I set the B18 armor to be about 70 across the board and nerfed the helmet slightly to just above the armor.

I also put the bullet resist down to a reasonable level.

## Why It's Good For The Game

In its current state the B18 is quite hard to kill but if xenos damage goes down and B18 armor does not go down I assume B18's will be nearly unkillable. I am not the only one who thinks this.

Nerf B18 Reason

## Changelog
:cl:
balance: B18 armor and helmet nerfed slightly.
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
+1, assuming the other damage de-escalation PR gets in.

It's either this or remove the automedic.

**Comment by davidchan13** [comment]
> In its current state the B18 is quite hard to kill but if xenos damage goes down and B18 armor does not go down I assume B18's will be nearly unkillable. I am not the only one who thinks this.
> 
> Nerf B18 Reason

If the driving force or intent of this PR is reducing B18 so Xeno damage can be reduced by a simliar amount, that should be coupled with this PR. Not some after thought that may or may not go through later.

**Comment by jroinc** [comment]
agree 100%

**Comment by Isy232** [comment]
I put the first message to be "This PR is meant to be merged with other de-escalation PR's." for a reason. B18 is fine enough with current damage values, if they go down B18 should go down too.

**Comment by Pariah919** [comment]
70+5 puts it at edge armor level which makes edge better to run in most cases due to premed being better than in battle med if you remember-
I think 75+5 is better personally if your nerfing b18 than the current 80+5

**Comment by Kuro-ai** [comment]
+1 to Pariah919 comment,that should be the nerf otherwise it's just better to run edge armor

**Comment by spookydonut** [comment]
@Isy232 merge conflict

**Comment by Isy232** [comment]
Fixed that, only 2 days late...

**Comment by Rohesie** [comment]
This hasn't significantly weakened the B18. It goes in.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by adamkad1** [comment]
useless time incoming

**Comment by adamkad1** [comment]
> This hasn't significantly weakened the B18. It goes in.

yunno, i see it getting soloed by shrikes every time now...

**Pull request merged**
