### PR TITLE
Makes the M56D smartgun into a whole deployable item

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

This PR makes the M56 not require construction and just makes it deployable after a timer

## Why It's Good For The Game

Ren told me to do this, and Ren is a smart boy, this is reduce strain on engineers who built                      

## Changelog
:cl:
tweak: the M56D is now deployable like the minisentry, just take it out and press z, it will be placed in front of your direction
tweak: M56D no longer requires tools to manage or deploy, or undeploy, just drag it to your person to undeploy it. 
tweak: M56D can now rotate, bringing you and your person with it, and can immediately fire
tweak: You can now examine and also point while using the M56D
tweak: You can now shoot critical condition mobs (xenos) with the M56D
tweak: Only people directly behind the gun can dissassemble it, this is to prevent griefing
balance: reduced the damage to 40, penetration to 40, and sundering to 5
balance: You can now buy the crate from the Combat Engineer Nexus for a massive 35 points, have fun with no metal or plasteel.
tweak: You can now repair both the handheld piece, and the deployed mounted SG with a welder
sound: adds new M56D sound
sprites: adds new M56D sprites
/:cl:

### CODE REVIEW

**Comment by MacBlaze1** [comment]
> Um.
> 
> So I can carry 2 sentries in each hand and set up a forward position in ~3.5 seconds (cause I can do both at once), or SEVEN seconds if I want to move around a bit? Compared to the ~12 seconds to set up a normal sentry?
> 
> Why have the point-defense sentry at this point? This just makes regular sentry a better point defense sentry.

Ren told me to do this so he could balance better or something, I believe the point sentry is still viable because it is weaker and the normal sentry is limited in number

**Comment by MacBlaze1** [comment]
FUCK IM RETARDED AAAAAAAAA

**Comment by MacBlaze1** [comment]
@jroinc please remove the reddit downvote thanks

**Comment by jroinc** [comment]
M56d placement speed WAY too fast. Double it (it'll still be less than before.)

Same with the retrieval speed.

Also, if you retrieve and re-deploy a gun, it heals it to full.

**Comment by Hathkar** [comment]
Just some general observations.

- It deploys and unpacks far too quickly, making it far too easy to move around, considering it's stopping power.

- Perfect accuracy, even with burst fire.

- 3 round burst, 75 damage, 75 armor penetration, 20 sundering seems a bit high, coupled with the accuracy.

**Comment by MacBlaze1** [comment]
> Just some general observations.
> 
> * It deploys and unpacks far too quickly, making it far too easy to move around, considering it's stopping power.
> * Perfect accuracy, even with burst fire.
> * 3 round burst, 75 damage, 75 armor penetration, 20 sundering seems a bit high, coupled with the accuracy.

The damage, pen, and sunder have all been cut to shreds, deploy time has increased to 3 seconds

**Comment by Hughgent** [comment]
If this doesn't have any direct bugs found within the next 24 hours, it will be merged.

Speak your piece for balance issues.

**Comment by Hathkar** [comment]
The new firing sound is VERY loud. Please save my eardrums.

**Pull request merged**
