### PR TITLE
Allows the AI to have interactions across Z levels.

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
This allows the AI to interact with groundside electronics. Just like on the ship basically. 
Some people asked for a test merge, especially so the AI has something to do groundside. 

## Changelog
:cl:
balance: Allows the AI to interface with groundside equipment
/:cl:

### CODE REVIEW

**Comment by jroinc** [comment]
This was pulled for a reason in an earlier PR.

AI can shock-bolt doors open and closed, and ayys can't destroy open doors without aciding them and waiting forever. This meant that once power was up, the AI could in practice trap ayys in many places as they tried to retreat.

**Comment by lbnesquik** [comment]
> 
> 
> This was pulled for a reason in an earlier PR.
> 
> #2401
> #2402
> 
> AI can shock-bolt doors open and closed, and ayys can't destroy open doors without aciding them and waiting forever. This meant that once power was up, the AI could in practice trap ayys in many places as they tried to retreat.

The AI cannot shock doors anymore. As for closing doors and trapping xenos, that might be a little harder with zero cameras down there. 

This is mostly for having a test merge to see how it actually plays out, given that this other PR is two years old.

**Comment by jroinc** [comment]
> 
> 
> > This was pulled for a reason in an earlier PR.
> > #2401
> > #2402
> > AI can shock-bolt doors open and closed, and ayys can't destroy open doors without aciding them and waiting forever. This meant that once power was up, the AI could in practice trap ayys in many places as they tried to retreat.
> 
> The AI cannot shock doors anymore. As for closing doors and trapping xenos, that might be a little harder with zero cameras down there.
> 
> This is mostly for having a test merge to see how it actually plays out, given that this other PR is two years old.

I have no comments on desirability or balance, I'm just noting that this has happened before.

**Comment by Wayland-Smithy** [comment]
> zero cameras down there.

Except for all the mairnes and cas flares lol. I think one of a few things needs to also happen for this change to make sense:

1. Disable AI control on all goundside doors, via code in a non-repairable way
2. Remove AI door bolting ability period.
2. Make xenos able to open powered doors without a `do_after()` wait and/or able to slash them down in as much time it takes to shoot resin doors.

**Comment by BraveMole** [comment]
I agree with wayland, i think this is only possible if AI is unable to interact with doors.

**Comment by SkeletalElite** [comment]
Or just make APCs spawn broken so marines have to go through some effort for AI to be able trap groundside xenos

**Comment by TiviPlus** [comment]
> > zero cameras down there.
> 
> Except for all the mairnes and cas flares lol. I think one of a few things needs to also happen for this change to make sense:
> 
> 1. Disable AI control on all goundside doors, via code in a non-repairable way
> 2. Remove AI door bolting ability period.
> 3. Make xenos able to open powered doors without a `do_after()` wait and/or able to slash them down in as much time it takes to shoot resin doors.

Do this

**Comment by lbnesquik** [comment]
> 
> 
> Or just make APCs spawn broken so marines have to go through some effort for AI to be able trap groundside xenos

Seems like the easiest and fairest way. Xenos do not have to slash APC's everywhere every round, and marines need to bring power modules/cells to fix their APC's. Which is like, maybe 6 APC's per engineer if they dedicated themselves to this. 

And it wouldn't allow aggressive bolting of doors.

**Comment by Wayland-Smithy** [comment]
I think modifying this proc to simply compare airlock and user z coords would be the easiest.

https://github.com/tgstation/TerraGov-Marine-Corps/blob/0b779360279362562416f70a041a3d486c25334d/code/game/objects/machinery/doors/airlock.dm#L71-L72

**Comment by InterroLouis** [comment]
Could also make it so APCs groundside have AI control off by default, it's already a function of APCs.

**Comment by Wayland-Smithy** [comment]
I don't think the APC AI control wire affects the doors as they have their own wires.

**Comment by lbnesquik** [comment]
I've implemented the solution from Wayland and it works. No control over doors, but other machinery works.

**Comment by Al-1ce** [comment]
This..doesn't really do anything if the AI can't open doors but still very cool.

**Comment by lbnesquik** [comment]
> 
> 
> This..doesn't really do anything if the AI can't open doors but still very cool.

Generators, turrets, locking alamo doors, APC's, vendors, shutters... There is a fair bit of things you can interact with.

**Pull request merged**
