### PR TITLE
Reduces xeno rank playtime requirements

### PR DESCRIPTION
**Pull request by Barnet2**
## About The Pull Request
Young - 10 hours (the same)
Mature - 25 hours (instead of 50)
Elder - 70 hours (instead of 100)
Ancient - 175+ (instead of 300)
## Why It's Good For The Game
Apparently they were too long, and the people nagging at me for it were probably right since it is a per caste thing, and people change caste around alot during a game. This is a copy from CM's xeno ranks outside of name.
## Changelog
:cl:
qol: Reduced xeno rank playtime requirements
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
I thought thats how it already was what the fuck 💀
Yeah merge this, its WAY harder to rack hours as a xeno (because you need to switch dynamically)

**Comment by yyzsong** [comment]
Coward

**Comment by Lumipharon** [comment]
I feel like this is a mistake. People have thousands of xeno hours, they'll get those ranks sooner rather than later.

**Comment by Barnet2** [comment]
> I feel like this is a mistake. People have thousands of xeno hours, they'll get those ranks sooner rather than later.

Reminder it is per caste. In TGMC, xenos often (or should) try to adapt to the circumstances around them by changing castes. While ranks are very cool, a Marine can play Marine Rifleman and become a sniper, a rifleman, a flamer, etc while still getting hours on them. People like their ranks; they shoudn't feel guilty for switching to another caste because "muh rank".

**Comment by TheWiznard** [comment]
> I feel like this is a mistake. People have thousands of xeno hours, they'll get those ranks sooner rather than later.

marine ranks right now
10 25 100 125 

xeno ranks right now
10 50 150 300

xeno ranks after
10 25 70 175

**Comment by Lumipharon** [comment]
ogey.

**Review by Lumipharon — APPROVED** [review]

**Pull request merged**
