### PR TITLE
Fixes FS key giving command channel

### PR DESCRIPTION
**Pull request by fernandos13**
## About The Pull Request
fixes the FS key allowing Command comms

## Why It's Good For The Game
fixes the FS key allowing Command comms (now FS key will only give FS channel)

## Changelog
:cl:
fix: Fire Support key. no longer gives the command channel
/:cl:

### CODE REVIEW

**Comment by fernandos13** [comment]
AHA!

**Review by TiviPlus — CHANGES_REQUESTED** [review]
you're deleting a random yaml file

**Comment by fernandos13** [comment]
FINNALY i couldn't find the original thing. heck thanks git kraken for the rever option cause idk where does one even get that file

**Comment by usnpeepoo** [comment]
:(

**Review by SplinterGP — APPROVED** [review]

**Pull request merged**
