### PR TITLE
Adds a new male scream

### PR DESCRIPTION
**Pull request by 567Turtle**
## About The Pull Request

Adds a new scream made for my dear friend Herman, it is a very good noise and I think it will add much needed variety to the pool of male screams.

https://voca.ro/1fdkS8aGfYQU

## Why It's Good For The Game

This will please my dear friend Herman, who I seek approval from constantly as well as the afformentioned variety needed for the pool of possible screams done by males. It sha'll instill fear in xenos heart surely.

Thank you dearly to my good friend Jack Kelly, Frogkicker29, Kellogg and Hyperkid5 for contributing their voices to the sound.

## Changelog
:cl:
add: New male scream
/:cl:

### CODE REVIEW

**Comment by SexmasterWasTaken** [comment]
What a great addition to the game

**Comment by frogkicker29** [comment]
Thats me you cant do this

**Comment by 567Turtle** [comment]
> Thats me you cant do this

I own your voice

**Comment by wezsel11** [comment]
Is this the next 'good hits' mp3?

**Comment by 567Turtle** [comment]
> Is this the next 'good hits' mp3?

minor scrape

**Comment by Lumipharon** [comment]
Don't shitpost.

**Comment by 567Turtle** [comment]
george orwell 1984

**Comment by Joe13413** [comment]
1984

**Pull request closed without merging**
