### PR TITLE
Adds aim to lasrifle

### PR DESCRIPTION
**Pull request by BlueHNT**
## About The Pull Request
Adds aiming option to lasrifle mk2

## Why It's Good For The Game
Currently lasrifle is one of the most neglected and special snowflake weapons that you see once or twice a month so adding aim to it would make it much more less FF-worthy and actually usable in the field.

## Changelog
:cl:
balance: rebalanced something
/:cl:

### CODE REVIEW

**Comment by Swagile** [comment]
my body is ready

its time

for the lasrifle aim mode blob

epic sunder time

**Comment by neohenry** [comment]
Lasgun's FF isn't bad compared to other weapons, so it's justified, by some balancers, that lasgun is frontline. I would take a pump shotgun with flech instead of a lasgun, but that's just me.

**Comment by BlueHNT** [comment]
> Lasgun's FF isn't bad compared to other weapons, so it's justified, by some balancers, that lasgun is frontline. I would take a pump shotgun with flech instead of a lasgun, but that's just me.

At it's current state it's almost as if it's a support weapon unless explicitly used one hand with shield and is one of the few sundering weapons. I made this based on my experience with the gun and witnessing others not knowing what to do with it or picking it purely out of interest before leaving it on ship for what I believe is due to either aim or it's clunky choice mechanic.

**Comment by davidchan13** [comment]
Lasgun lacking aim mode and tactical reloads does severely limit it's usefulness despite being a supposed weapon for every situation.

**Comment by usnpeepoo** [comment]
crusher players are gonna go on suicide watch if this gets merged

**Comment by Tennessee116** [comment]
I thought it was already determined the lasrfile _wasn't_ going to get aim-mode.

**Comment by Naaanii** [comment]
Not needed. Lasrifle is already useable and the FF isn't even crippling.

**Comment by Glcbitj** [comment]
How the fuck is "FF not as bad as other weapons" a valid argument? Go ahead and give SADAR aim mode too then, since it's FF is obliterating.

The gun is almosy useless, it's only use is sundering, and you dont wanna frontline with a no damage gun. You almost always wanna frontline with either shotguns or miniguns (if you ever get them), hence why the gun is not used. Besides, healing Sunder is piss easy nowadays with Drones and Hivelords.

If you genuinelly think the gun is good why the heck you think absolutely no one uses the gun for anything other than shooting through windows in Crash or CIC? If shit was good people would use it.

**Comment by Tokanova** [comment]
just have a lasrifle mode that has IFF but does less damage..

**Comment by neohenry** [comment]
hitscan lasgun when

**Comment by SpaceLoveSs13** [comment]
If this gets merged, you will jist cripple lasgun more because sooner or later there will be a pr to remove one hand use of lasgun. Lasgun FF is no way near to get aimmode.

**Comment by Chaznoodles** [comment]
Lasgun doesn't have aim mode on purpose.

**Comment by Walarks** [comment]
> I thought it was already determined the lasrfile _wasn't_ going to get aim-mode. Don't remember why, might be wrong.

It hasn't been set in stone or anything. Lasrifle didn't have aim mode PR made before because no one wanted to bother going all the way to add aim mode only to specific modes. Thought this PR just adds it to the whole gun.

> If this gets merged, you will just cripple lasgun more because sooner or later there will be a pr to remove one hand use of lasgun. Lasgun FF is no way near to get aimmode.

You can't aim mode without wielding the gun anyways.

**Comment by Losenis** [comment]
>unless explicitly used one hand with shield

Yeah listen I tried that and uhhhhh
image

**Comment by BlueHNT** [comment]
> > unless explicitly used one hand with shield
> 
> Yeah listen I tried that and uhhhhh
> image

Seems about right

**Comment by TiviPlus** [comment]
The lasgun is versatile and usable as-is so I dont believe this is necessary

**Comment by davidchan13** [comment]
> The lasgun is versatile and usable as-is so I dont believe this is necessary

If by versatile you mean has exactly one loadout/use that makes it usable, sure. Every other function on the gun that isn't spread is worthless.

**Pull request closed without merging**
