### PR TITLE
Repairing shipside gens and removing fuel cells now scales with engi skill

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title
## Why It's Good For The Game
CSE and STs are the masters of engineering and the masters of ship maintenance. Makes sense for them to do the job more efficiently. Synth too but that's if they're shipside.
## Changelog
:cl:
qol: Makes repairing shipside gens and removing fuel cells scale with engineering skill.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Probs just make it scale with skill level instead of just a flat bonus for master level.

**Comment by Naaanii** [comment]
> Probs just make it scale with skill level instead of just a flat bonus for master level.

Done

**Comment by Derrick2Electricboogaloo** [comment]
Nevermind this is not for repairing.

**Comment by zzurge** [comment]
BASED

**Comment by Derrick2Electricboogaloo** [comment]
To be fair, should just be all gen types. There is only 1 ship that has busted ship gens right off the bat, I have never seen them breakdown anymore.

**Comment by Naaanii** [comment]
> To be fair, should just be all gen types. There is only 1 ship that has busted ship gens right off the bat, I have never seen them breakdown anymore.

I'll address groundside in another PR.

**Pull request merged**
