### PR TITLE
My Anger is As Hot as These Incendiary Slugs

### PR DESCRIPTION
**Pull request by KrabSpider**
## About The Pull Request
Fixes @hyper2snyper's goof. Do this again and I will instill my wrath upon your DM's. 

## Why It's Good For The Game
FIxing incendiary slugs awful stats. 

## Changelog
:cl:
balance: Incendiary slugs, yet again, no longer have airburst and do normal damage. Again.
/:cl:

### CODE REVIEW

**Comment by hyper2snyper** [comment]
should change the pr title too

**Comment by Derrick2Electricboogaloo** [comment]
Nice. Always good to have ammo be viable!

**Review by hyper2snyper — APPROVED** [review]
fixing my stupid mistakes. nice

**Comment by Lumipharon** [comment]
Considering how good setting xenos on fire is (continued DOT, which they can't mitigage until death or leaving combat unless they can acid well), buffing the damage that high seems pretty powerful.

**Comment by ilikesaying** [comment]
> Considering how good setting xenos on fire is (continued DOT, which they can't mitigage until death or leaving combat unless they can acid well), buffing the damage that high seems pretty powerful.

don't forget disabling pheromone effects

**Comment by KrabSpider** [comment]
> Considering how good setting xenos on fire is (continued DOT, which they can't mitigage until death or leaving combat unless they can acid well), buffing the damage that high seems pretty powerful.

The same effect can achieved with a plasma pistol as an under barrel attachment, so I dont see much of a difference to be real with you. Beyond that, Im just fixing a screw up **someone** made.

**Pull request merged**
