### PR TITLE
Lowers Claymore deploy time

### PR DESCRIPTION
**Pull request by CCorvet**
## About The Pull Request

Changes Claymore deploy time from 4 secs, to 1s.
Removes the M21 APRDS Minelayer from engie gear vendor, leaves it in otherwise.

## Why It's Good For The Game

Makes Claymores more viable, as they don't take the better part of your twilight years to deploy.
Removes an extremely rarely used device from the vendor, especially in light of this PR, but keeps in it code for purpose of electrics future mine rework.
As for why approve this when rework is in progress? This is an interim balance/qol change, as to my knowledge, the rework will take a while due to its scope.

## Changelog

:cl:
balance: Claymores now take 1 secs to deploy, instead of 4s
/:cl:

### CODE REVIEW

**Comment by Autisem** [comment]
#12495 is reworking how mines work

**Comment by CCorvet** [comment]
> #12495 is reworking how mines work

Yes i am aware, i even addressed it in the original post

**Comment by XElectricX** [comment]
Yeah my PR is still a bit of a while away so meh. Minelayer is pretty bad anyways since claymores are not as good right now.

**Comment by zzurge** [comment]
Based

**Comment by Lumipharon** [comment]
The minelayer exists to make deploying mines in mass faster, so I unno why you're removing it.

**Pull request merged**
