### PR TITLE
Github my beloathed (PC gains charge on hit)

### PR DESCRIPTION
**Pull request by Arctrooper8**
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10105

## Changelog
:cl:
expansion: PC now gains 200 charge when it hits a living creature
del: Removed PC emp act
balance: PC cell size from 8500 to 7500
/:cl:

### CODE REVIEW

**Review by TiviPlus — APPROVED** [review]

**Comment by Naaanii** [comment]
This is pretty dumb and feels like the PC is getting nerfed even more. A tool shouldn't be getting any combat benefits other than just melee, or energy damage because of what the PC is and the 1k charge nerf for something that will barely happen feels a bit much.

**Comment by Losenis** [comment]
Now give synth the PC again so that I can actually do anything with a PC

**Comment by Al-1ce** [comment]
This is just silly. Go ahead and hit a xeno with a charger.

**Comment by Derrick2Electricboogaloo** [comment]
PC just can not catch a break.

**Comment by Pariah919** [comment]
But why?

**Comment by WoodenTucker** [comment]
PC gains 200 charge when it hits a living creature 
i am going to beat ian to death

**Comment by breadhunt** [comment]
this is fucking awesome what are you guys on

haha energy go BRRRRRRR

**Pull request merged**
