### PR TITLE
add milk in soda dispenser

### PR DESCRIPTION
**Pull request by novaepee**
## About The Pull Request

Title.

## Why It's Good For The Game

Bihexajuline is a chemical that causes extreme pain and fixes bones at cryogenic temperatures. It's the juice that provide the SNAP CRACKLE POP in cryotube.

Milk is required to make this. I'm not sure why, but it does. Maybe bone likes cold milk, not room-temperature milk. Only Sulaco and Theseus have /obj/item/reagent_containers/food/drinks/milk , which hinder PoS and Minerva from producing bihexajuline.

Can also add this in chem dispenser.

## Changelog
:cl:
add: add milk in soda dispenser
balance: marines have access to milk; JUICE UP, BOYS AND GIRLS!
qol: you can finally make Bihexajuline in all shipside maps; if there isn't a soda dispenser nearby medical, I will change that in another PR.
/:cl:

### CODE REVIEW

**Comment by QualityVan** [comment]
You can use cream instead, which is in booze-o-mats.

**Comment by bluezorua** [comment]
this is just a stealthy pr that makes pilk easier to make

**Comment by Licherr** [comment]
this is clearly an excuse to make cum

**Comment by novaepee** [comment]
> You can use cream instead, which is in booze-o-mats.

True, though (1) soda dispenser is near almost all medbay, so doctors, researchers, and corpsmen use this to extract particular regeants and (2) booze-o-mat takes more time to access to compared to soda dispenser. See #9255 .

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
