### PR TITLE
Deathsquad equippment and role refresh

### PR DESCRIPTION
**Pull request by disappointedButNotSuprised**
## About The Pull Request

Deathsquad has now a new loadout. The fist-aid-kit has been replaced with a full custom medkit including a new elite auto-injector 15/15 RR/rezadone. DS commando armor has a build in autodoc like the B18. The commando backpack has got the opening delay removed and is essentaily equal to the light combat backpack, its contents has also been updated. 

Additionally a new DS job has been added - Deathsquad Gunner, to keep up with other ERT's like the PMC. Equipped with a smartgun and a new pouch able to hold a single SG or minigun drum.

## Why It's Good For The Game

Deathsquad is deployed very rarely and is usually expected to complete it's mission. After one of it's failed deployments some players pointed that the DS gear is outdated in comparison to other ERTs. This PR tries to refresh the loadouts and add some custom stuff and a new role to make DS the absolute killer ERT.
The loadout is obviously overpowered but taking into accout what the role of DS is, it seems appropriate.

## Changelog
:cl:
balance: Refresh Deathsquad equippment - proper meds and buffs for armor and backpack
add: New Deathsquad role - Gunner
/:cl:

### CODE REVIEW

**Comment by SplinterGP** [comment]
DS is not in normal loop so is fine

**Comment by SpaceLoveSs13** [comment]
I approve of DS refreshment as an admin. Helps in events, thanks!

**Comment by SpaceLoveSs13** [comment]
Make sure the DS SG kills evwryrhing that is not DS, even PMCs.

**Comment by disappointedButNotSuprised** [comment]
Oh, I forgott about the IFF settings. Will adjust this shortly

**Comment by ilikesaying** [comment]
don't care, still flammable

**Comment by BraveMole** [comment]
Maybe give the guns magnetic attachement, cause it's really easy to stun lock them as a xeno

**Comment by disappointedButNotSuprised** [comment]
> 
> 
> Maybe give the guns magnetic attachement, cause it's really easy to stun lock them as a xeno

Both the standard and SG troopers already got magnets on their weapons. The M57A4 launcher wielded by the leadear cannot be fittet with one (It should probably stay that way, unless I it wouldbe a good idea to make a special DS version that can).

**Review by SplinterGP — APPROVED** [review]

**Pull request merged**
