### PR TITLE
Metal barricades can now be upgraded

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Explosive, acid and bullet/slash armor featuring cool radial menus
## Why It's Good For The Game

engineer content

## Changelog
:cl:
add: Metal barricades can now be upgraded with acid, ballistic, or explosive armor
/:cl:

### CODE REVIEW

**Comment by SpaceLoveSs13** [comment]
Finally something useful for HvH. DIE SOMS!

**Comment by AtlasRules** [comment]
buildin' a level 3 cade

**Comment by ilikesaying** [comment]
Engineer Gaming

**Review by Hughgent — APPROVED** [review]

**Comment by AbsoluteJerry** [comment]
What do I use to upgrade it?

**Comment by TiviPlus** [comment]
Click on cade with metal

**Review by Hughgent — APPROVED** [review]

**Pull request merged**
