### PR TITLE
Removes hyperzine,thermite and roullettiums recipe

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Removes the chems from being makeable, or acquirable by most normal means I know of. Keeps them in there for admins for to adminbus.

## Why It's Good For The Game
They're unfunny memes.
Roullettium gives you a conscious chance of just dying, so it's equivalent to berserker suicide. Which we want to get away from.
Thermite is a solid kek.
Hyperzine, even if it exists and drains your stamina per tick is still best used as a berserker chem to go harness suicide rush, it's not a funny meme after the first time. And the only reason it's still in is because "nobody uses it"
Thermite is probably a nice tool for adminbus events, I have no lie how you'd use roulletium in an admin event but I'll leave it there, hyperzine aswell.

## Changelog
:cl:
del: Recipes of hyperzine,thermite and roulletium removed. Removed from medic vendors.
balance: You can no longer make hyperzine,thermite and roulletium. Medics can no longer acquire them.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
Put hyperzine back, please. Also, please add a bottle with thermite to the game items, it's obnoxious to spawn.

**Comment by AdamElTablawy** [comment]
Why remove hyperzine and thermite?

**Comment by psykzz** [comment]
Thermite is old and can be added back in later properly.

Im removing thermite fully in https://github.com/tgstation/TerraGov-Marine-Corps/pull/3954

**Comment by spookydonut** [comment]
This is not a proper removal.

idk who added roulletium but it looks like a grade-a grief chem

**Comment by jroinc** [comment]
> This is not a proper removal.
> idk who added roulletium but it looks like a grade-a grief chem

I added it. It was left reachable by players through a convoluted recipe to give the RSR something to do to entertain themselves. It can kill you, true, but we have logging for that, and it's very obvious what did it. If you inject someone with it and they didn't consent to it, I'll treat it like I would any other assault.

**Comment by spookydonut** [comment]
> 
> 
> > This is not a proper removal.
> > idk who added roulletium but it looks like a grade-a grief chem
> 
> I added it. It was left reachable by players through a convoluted recipe to give the RSR something to do to entertain themselves. It can kill you, true, but we have logging for that, and it's very obvious what did it. If you inject someone with it and they didn't consent to it, I'll treat it like I would any other assault.

tgmc policy is to where possible reduce admin workload not increase it

**Comment by jroinc** [comment]
> This is not a proper removal.
> idk who added roulletium but it looks like a grade-a grief chem
> 
> I added it. It was left reachable by players through a convoluted recipe to give the RSR something to do to entertain themselves. It can kill you, true, but we have logging for that, and it's very obvious what did it. If you inject someone with it and they didn't consent to it, I'll treat it like I would any other assault.
> 
> tgmc policy is to where possible reduce admin workload not increase it

Again, this doesn't change much. I can pop 30u of synaptizine in an autoinjector and make something that kills people. Or Russian Red. Or lexorin or any of the poisons, really. I can make one-click deathmixes so bad they aren't counterable and can't be revived from without surgery.

2 people have done that in the last 6 months. We banned them.

Also, I thought TGMC policy was to keep things IC when possible?

**Comment by Pariah919** [comment]
@spookydonut i specifically only deleted the recipes, though I can delete the scheme if you want me to.

**Comment by jroinc** [comment]
Upon looking at the current speedboosts possible and testing them out ingame, go ahead and remove hyperzine. I'll add it back in a more balanced form. As-is, hyperzine's strong, ultrazine lets you move at normal unarmored running pace in B-18, and combo-ing both lets you move at lightspeed in B-18.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
