### PR TITLE
Remove ST from the game

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

Title

## Why It's Good For The Game

Completly useless role.
If you want to be useless shipside or at fob, play CSE. We do not need more than one CSE like role.

If you want to do req, go RO
If you want to be swiss knife shipside, go cap or so

## Changelog
:cl:
remove: Remove ST from the game
/:cl:

### CODE REVIEW

**Comment by revelation-8468** [comment]
i grinded 100 hours for the mythical CPO rank and now it just gets removed

smh my head

**Comment by Lumipharon** [comment]
I don't see the issue with keeping it. It's especially nice if someone wants to learn shipside stuff, while leaving space open for someone actually competent to take the main role(s).

**Comment by FosterGrime-Heymynameslouie** [comment]
> I don't see the issue with keeping it. It's especially nice if someone wants to learn shipside stuff, while leaving space open for someone actually competent to take the main role(s).

this

people need to get used to shipside before taking up the mantle of nigh important command roles
the last thing we need is the increased number of braindead ro's, cse's, and SO's and caps

**Comment by Starfirejordan** [comment]
> > I don't see the issue with keeping it. It's especially nice if someone wants to learn shipside stuff, while leaving space open for someone actually competent to take the main role(s).
> 
> this
> 
> people need to get used to shipside before taking up the mantle of nigh important command roles the last thing we need is the increased number of braindead ro's, cse's, and SO's and caps

this, it might be a "useless" role in the sense that it doesn't do anything much other then being a shipside role, but there no valid reason to remove it other then that

**Comment by Losenis** [comment]
"If you want to be useless shipside or at fob, play CSE."

Can't, someone already took CSE.

**Comment by DerpiestBruh** [comment]
soulless pr

**Comment by Calyxman** [comment]
This is quite possibly the worst PR ever made to TGMC's repository

**Comment by Weedmaster77** [comment]
Brave please for the good of TGMC stop taking thinks out that don't hurt anyone maybe push of more ranks rather then take whole roles away when there is no reason to!

**Comment by Serxule** [comment]
> Completly useless role. If you want to be useless shipside or at fob, play CSE. We do not need more than one CSE like role.
> 
> If you want to do req, go RO If you want to be swiss knife shipside, go cap or so

this completely fucks over lowpop since STs usually have to do those jobs because no one else will actually pick them, and "oh but why not just go that role" because its boring as shit doing 1 thing for an entire round

**Comment by Derrick2Electricboogaloo** [comment]
Big 'Ol Negative from me. Allow us to have a Fobbit team. Okay thanks.

**Comment by Derrick2Electricboogaloo** [comment]
What if RO dies, and captain dies, and CSE dies, guess we get no more req, if we have no AI, and even if we have AI. No arms or legs to move stuff.

**Comment by Dikozda** [comment]
I usually take st when i want to help out with shipside stuff like gens, reloading OB and even once or twice helping CAS refuel and rearm, but not wanting to play a command role.

without the st i feel like i won't have this as an option anymore.

**Comment by Losenis** [comment]
Globally bad feedback

**Comment by Strayed-Raven** [comment]
Just vibe on ST a bit. Might be a good experience playing?

**Comment by MathiasOrtega** [comment]
This does less than a Ship Tech does.

**Comment by Otterwatch** [comment]
This pr has few good reasons to remove ST. There are actual uses for the role and sometimes you won't have your CSE because it's a single person and they might cryo (which doesn't open slots anymore) or die. ST isn't a one trick pony either. It can take care of Req, OB, power for the ship, engineering problems on ship, fob defenses, miner, and presumably tad op stuff.
      Spec was removed for the good reasons of not limiting super good and fun weapons to a single person on the battlefield. It opened up more stuff to marines and made tgmc for the better. Survivors were removed because they didn't serve a purpose besides killing new young xenos and then giving the beno team xeno returns considering that maturity is a huge limiting factor. Smartgunner was removed for evidently flawed reasoning, but I suppose it was thought that aim mode invalidated the role of SG and that it was just unga+ at that point. ST is none of these things. ST has an actual role that isn't entirely filled by anyone else besides CSE and Synth who don't have time to take care of the ship and req and groundside and loading ob. You gain nothing other than one less option to pick in the already short job menu.
      If you want to remove an absolutely useless role, then go for SO. They literally do nothing that someone else, not including Synth, can't. Not to mention the learning opportunities you gain by keeping this role. I've legitimately spent rounds where I saw a new ST and decided to teach them by going CSE and it was great. The tiniest bit of roleplay I've ever eeked out of tgmc while still helping someone as a mentor at the time. Also, you already showed the flaw in removing it. Each different role you mentioned can't do everything a ST can except for CSE.

**Comment by Starfirejordan** [comment]
image

**Comment by MiniMeatwad** [comment]
Next up is removing the Corporate Liaison, we sold his soul already, lets sell his organs too.

**Comment by TiviPlus** [comment]
Forgot this was open

**Comment by TiviPlus** [comment]
Now shush please

**Comment by Losenis** [comment]
wtf i love maintainers now

**Pull request closed without merging**
