### PR TITLE
Increase the AI cargo droid movespeed

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
Reduces the AI cargo droid movespeed delay. 
## Why It's Good For The Game
The AI drone is actually painfully slow to use. This thing moves as slow as a ripley with a PVT using it, without as much functionnality. It just makes sense that something with less capacity moves faster. 
## Changelog
:cl:
qol: Reduced the AI droid movespeed delay
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Everyone moves at the same speed in a ripley, so this is just buffing AI to be a better ripley.

**Review by TiviPlus — APPROVED** [review]
code ok

**Comment by TiviPlus** [comment]
Also yea what lumi says this feels like creep

**Comment by lbnesquik** [comment]
> Everyone moves at the same speed in a ripley, so this is just buffing AI to be a better ripley.

That would be true if it could do everything a ripley can. If we could move OB shells, sentries, pods or dropship gear, I'd totally be fine to have that speed. But given you can't do that, I don't feel like it's really that comparable.

**Comment by Kuro020** [comment]
> > Everyone moves at the same speed in a ripley, so this is just buffing AI to be a better ripley.
> 
> That would be true if it could do everything a ripley can. If we could move OB shells, sentries, pods or dropship gear, I would absolutely be fine staying at the current movement speed. But given you can't do that, I don't feel like it's really that comparable.
> 
> I would also add that a lot of the AI features over the years are straight buffs and QoL because it started out in such a deep pit of being boring / broken, so creep is one word for it. We are generally moving towards less obstacles for everything, and less tedium, with quick build, less medical fumble, now generators being preset... Not moving at a snail pace when trying to play with a feature seems fine to me.

then make it able to do those things, this is creep

**Pull request closed without merging**
