### PR TITLE
Adds the cement protein bar

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
cement

## Why It's Good For The Game
mmm... cement...

## Changelog
:cl: Lewdcifer
add: Cement protein bar. Mmm... cement...
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Mmm... cement...

**Comment by novaepee** [comment]
request a crayon protein bar made out of crayon colored by the rainbow

**Comment by Lumipharon** [comment]
>no harden up joke
Kill this man

**Comment by bluezorua** [comment]
he was forced to eat cement flavored protein bars at age 6

**Comment by Pariah919** [comment]
cinco de diez

**Comment by veterath** [comment]
holy based, speedmerge...

**Pull request merged**
