### PR TITLE
Adds organ damage to embryo growth

### PR DESCRIPTION
**Pull request by RikuTheKiller**
## About The Pull Request

So, we have a problem with people just plain ignoring embryos. Even with call of younger, there are still cases where for example the carrier dies or the victim simply relocates to an area where the carrier isn't present. In these cases the victim just keeps fighting as if they don't have an embryo eating their insides.

This PR intends to change that by inflicting organ damage over time. As long as you stay at stage 0, you will get no organ damage. Stage 1 deals very minor organ damage. By the time you reach stage 4, you'll be collapsing on the floor due to pain from organ damage and gasping for air due to heart and lung damage.

This also serves to make reviving people who have burst harder since it used to be a permadeath but marine cope removed that so I'm now soft-readding it by making revival more difficult. (The minor organ damage it causes right now really isn't that bad, this pretty much breaks all of the victim's organs without any intervention.)

This PR also increases the significance of larvaway, not only making it halve the embryo's growth speed once more instead of reducing it by 40% (the comment next to the line still said it reduced it by half, which it wasn't doing by the looks of things), but also by making it reduce the overall organ damage caused during the course of the embryo's growth to be reduced by 60% on top of slowing it down by half.
## Why It's Good For The Game

Larva bursting not being significant simply doesn't seem healthy to the game. Burst rates are already very low as evidenced by round end reports since people have gotten really good at removing them, so they aren't as much of a threat anymore.

This PR serves to reintroduce some of that threat and prevent marines from simply walking it off, albeit they can still do that if they prepare with larvaway or a questionable amount of painkillers. Corpsmen can also mitigate it with peridaxon plus or by simply using a stasis bag like a normal person, so there's definitely ways of dealing with it.

Call of younger is a neat addition and fixes part of the problem, but it doesn't provide that constant nuisance that having an embryo should really give you. Not to mention, it needs to get nutrition somehow, so this makes sense. If call of younger didn't exist, I would've probably tried to readd the permadeath, but that seems excessive now.
## Changelog
:cl:
add: Embryos now deal organ damage over time. This is affected by things that affect growth, however taking larvaway provides an additional 60% bonus reduction to the overall damage.
fix: Larvaway halves embryo growth speed once more! Turns out it was reduced to 40% at some point, likely silently.
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Larvals do not need a buff, go away.

**Comment by Derrick2Electricboogaloo** [comment]
Not even that bad of an idea honestly.

**Comment by Oscari-pog** [comment]
This is the 7th week in a row youve shown a Carrier buff in class

**Comment by chizzy376** [comment]
STOP BUFFING CARRIER IT'S A STRONG CASTE ALREADY

**Comment by bowlofcereal** [comment]
didnt we come to the consensus that this wasnt a good idea like 2 days ago tho

**Comment by maikilangiolo** [comment]
Xenos can't stop buffing carrier and rav like they were bad castes

**Comment by RikuTheKiller** [comment]
> didnt we come to the consensus that this wasnt a good idea like 2 days ago tho

I don't remember agreeing that it was a bad idea, I simply remember the counter arguments being that it's strong already with call of younger. I'd like to do some additional balancing to get this implemented, I just don't know what. (This would end up being more balanced overall IMO.)

**Comment by Losenis** [comment]
>So, we have a problem with people just plain ignoring embryos.

Yeah because anyone getting medevacced tends to burst shipside and suddenly you have half the fucking ship acided, comms gone, and prep's 50 SSD mobs cocooned. You're literally better off letting it straight up kill you and give you 11 fracs and 80 points of IB with a free larva for xenos than actually treating the embryo shipside should the worst happen. It does not need a buff.

**Comment by AlexCrimson** [comment]
> Yeah because anyone getting medevacced tends to burst shipside and suddenly you have half the fucking ship acided, comms gone, and prep's 50 SSD mobs cocooned. You're literally better off letting it straight up kill you and give you 11 fracs and 80 points of IB with a free larva for xenos than actually treating the embryo shipside should the worst happen. It does not need a buff.

I think you are exaggerating a fair bit. Even with 15-20 successful huggers its still incredibly rare for a marine to ever burst. Then you need a competent xeno to get the larva, and escape before getting killed. Their only real option is Drone, and that thing cannot solo anyone with even a modicum of skill.

Larval huggers perform incredibly bad if your goal is getting people to burst. However, in my irrelevant opinion, they are balanced fine right now, because they still force the marine to eventually go get it removed, and provide a mini-stun when you hug someone.

At most, i think the crazy idea instead is to remove larval huggers, or their ability to burst, and just have these organ damage huggers instead. They implant a parasite that causes organ damage over time, eventually killing the host unless its removed. No bursting at all.

**Comment by RikuTheKiller** [comment]
> > Yeah because anyone getting medevacced tends to burst shipside and suddenly you have half the fucking ship acided, comms gone, and prep's 50 SSD mobs cocooned. You're literally better off letting it straight up kill you and give you 11 fracs and 80 points of IB with a free larva for xenos than actually treating the embryo shipside should the worst happen. It does not need a buff.
> 
> I think you are exaggerating a fair bit. Even with 15-20 successful huggers its still incredibly rare for a marine to ever burst. Then you need a competent xeno to get the larva, and escape before getting killed. Their only real option is Drone, and that thing cannot solo anyone with even a modicum of skill.
> 
> Larval huggers perform incredibly bad if your goal is getting people to burst. However, in my irrelevant opinion, they are balanced fine right now, because they still force the marine to eventually go get it removed, and provide a mini-stun when you hug someone.
> 
> At most, i think the crazy idea instead is to remove larval huggers, or their ability to burst, and just have these organ damage huggers instead. They implant a parasite that causes organ damage over time, eventually killing the host unless its removed. No bursting at all.

Yeah, bursting is rare as hell, that's why this PR exists.

But, yeah, removing the larba entirely would be rather funny.

**Comment by Araulius** [comment]
instead of that, give defilers larval accelerant again

**Comment by Losenis** [comment]
> I think you are exaggerating a fair bit.

Second round I played after that comment. No, I am in fact not exaggerating this a fair bit.
image

**Comment by Joe13413** [comment]
> > Yeah because anyone getting medevacced tends to burst shipside and suddenly you have half the fucking ship acided, comms gone, and prep's 50 SSD mobs cocooned. You're literally better off letting it straight up kill you and give you 11 fracs and 80 points of IB with a free larva for xenos than actually treating the embryo shipside should the worst happen. It does not need a buff.
> 
> I think you are exaggerating a fair bit. Even with 15-20 successful huggers its still incredibly rare for a marine to ever burst. Then you need a competent xeno to get the larva, and escape before getting killed. Their only real option is Drone, and that thing cannot solo anyone with even a modicum of skill.

nahhh dude xenos can run away REAL easy, it's not that hard to just run past marines in maints as xeno. considering that most of the time, you'd have maybe a few marines + shipside roles chasing the xeno, you can easily evade capture and sabotage lotta shit

**Comment by Lumipharon** [comment]
I don't think huggers need this sort of buff.

**Comment by AlexCrimson** [comment]
>Second round I played after that comment. No, I am in fact not exaggerating this a fair bit.

Its still very anecdotal evidence. Not sure if admins/devs can easily access the logs, but if they could pull the end-round stats of the last 100 rounds, purely looking at the larval hugger infection & burst rates, there would be hundreds of infections, and way less bursts. Of those bursts, its impossible to know how many lead to successful ship sabotage, but i would wager the number is tiny.

In my personal experience, and i do not sit on this game all day, but since commenting, i have not seen a single burst on the ship. Even in a round that had 3 Carriers over the course of the game.

**Comment by Losenis** [comment]
I don't think anecdotal evidence means what you think it means

**Comment by AlexCrimson** [comment]
>I don't think anecdotal evidence means what you think it means

Evidence gathered through personal observation, no? Generally unreliable to prove anything. Which is why i mention that the statistics gathered at round-end would be the better way to look at things.

In their personal experience, they witnessed a larva burst on the ship after 2 rounds, so therefore it must happen often? Not a good basis for a debate.

**Pull request closed without merging**
