### PR TITLE
Small silo linked with pop

### PR DESCRIPTION
**Pull request by BraveMole**
## About The Pull Request

You can no longer build small silos if the active pop of the server is superior to 30

## Why It's Good For The Game

The full small silo start for xenos is too good, and more important, it is actively discouraging marines to push. 
I'm keeping small silos cause they are nice to have in small pop

## Changelog
:cl:
balance: Can no longer place small silos in medium-high pop
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
But why, why dont you just make pools automatially generate like small silos on lower pop

**Comment by BraveMole** [comment]
Why removing the ability to do big silo in small pop? If they prefer to have all their defences in the same spot?

**Comment by Wayland-Smithy** [comment]
Can the marines not afford to go on longer silo raids where they can cut a whole path through the xenos backlines cleaning up the silo spam when there are more of them?

If with no silos they have a problem, and too many silos is also a problem then maybe silo construction is a flawed mechanic to begin with.

**Review by TiviPlus — APPROVED** [review]
Id rather not have small silos at all but this is fine for now

**Pull request merged**
