### PR TITLE
Guns part1 redux

### PR DESCRIPTION
**Pull request by Xsdew**
## About The Pull Request

Updates a few of the new sprites added to the game for firearms. The AR12, AR18, SMG90, and SH35 got a bit of touch up by Kuro.

## Why It's Good For The Game

Further refinement of new sprites introduced.

## Changelog
:cl:

imageadd: Further refinements to the AR12, AR18, SMG90, and SH35 sprites.

/:cl:

### CODE REVIEW

**Comment by Xsdew** [comment]
pr
From Top to Bottom:
AR-12
AR-18
SMG-90
SH-35

**Comment by FosterGrime-Heymynameslouie** [comment]
spped merhg

**Comment by Kuro020** [comment]
> spped merhg

24 hour rule

**Comment by Alexeivichi** [comment]
i hate that rule. speedmerge rn

**Comment by Kuro020** [comment]
> i hate that rule. speedmerge rn

maintainer cabal would kill me

**Comment by Weedmaster77** [comment]
I still like the old removed ones more but these are looking a lot better then the first pass ill give you that kuro

**Comment by Kuro020** [comment]
No point in TMing something that fixes something that is already in, for the next part I'll do a TM first to get feedback

**Pull request merged**
