### PR TITLE
Disallows the masterkey shotgun as an attachment for the TX-15 Auto Shotgun

### PR DESCRIPTION
**Pull request by lKiseki**
## About The Pull Request
Per title.

## Why It's Good For The Game
The fact that you can have a secondary shotgun, on a shotgun, is already weird enough. You can also fire both _simultaneously_ for some god forsaken reason. You can mix and match flechette, buckshot, and slugs for the imbalanced combination of your choice. All things considered, it's nowhere near balanced and arguably something that shouldn't be allowed.

## Changelog
:cl: Lewdcifer
balance: TX-15 autoshotgun no longer accepts masterkey shotguns.
/:cl:

### CODE REVIEW

**Comment by Viniwizi** [comment]
TX-15 is garbage even with the masterkey, not worth it over the T35 or the paladin.

**Comment by lKiseki** [comment]
> TX-15 is garbage even with the masterkey, not worth it over the T35 or the paladin. This attempt of a nerf is literally kicking a dead dog.

Clearly you haven't seen the multiple marines abusing the TX-15 + masterkey shotgun every round, then. If you're not content with the TX-15's current balance, you can change that, but it's ultimately not a reason to promote keeping something that is clearly broken.

**Comment by BonkaiB** [comment]
I've been using it quite a bit and i can tell you without a doubt when the masterkey when combo'd with another shotgun it just deletes

I shouldn't be able to kill an ancient gorger within a matter of 4 - 5 clicks in a few seconds or instantly crit a runner no matter how funny it is when it happens

Truly a broken combo

**Comment by Luxyboo** [comment]
hate this because i use this combo and it is OP but why are you removing it just because it is OP and because i use it. you should not remove this because i like it and it is good :((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((

**Comment by Viniwizi** [comment]
> > TX-15 is garbage even with the masterkey, not worth it over the T35 or the paladin. This attempt of a nerf is literally kicking a dead dog.
> 
> You haven't seen the multiple marines abusing the TX-15 + masterkey shotgun every round, then. If you're not content with the TX-15's current balance, you can change that, but it's ultimately not a reason to promote keeping something that is clearly broken.

Nevermind, just played as a runner and that shit instantly crits rounies, since you can load slugs on the masterkey. Truly broken meta. Completely forgot about slugs when making the comment

**Comment by ilikesaying** [comment]
16g flech and 12g incend slug truly is a funny combo

**Comment by novaepee** [comment]
For more hard evidence for this PR:

https://www.youtube.com/watch?v=ayndNNDvHrE

**Review by BraveMole — APPROVED** [review]

**Pull request merged**
