### PR TITLE
Sentry Health Buff

### PR DESCRIPTION
**Pull request by InterroLouis**
## About The Pull Request

Sentries are, well, to put it simply excessively easy to kill. Cheese them, they die in a scant few acid spits. So, here's a health buff and some armor. 

## Why It's Good For The Game

Sentries won't die in like, a handful of acid spits. 

## Changelog
:cl:
balance: Sentry health buffed, given armor
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jroinc** [comment]
Tbh, up the HP even more to double the original value(they're fragile as all hell), but make it easier to knock them over to temporarily disable them (when's the last time you've seen one knocked over?).

**Comment by Chaznoodles** [comment]
This doesn't solve anything. If you're in a position where sentries are being damaged by spit, then the spitcastes will happily just spend a little longer spitting. This just makes it harder for the melee castes to do anything against a turret on Radial.

**Comment by psykzz** [comment]
This gives marines more time to react, melee castes should never be able to deal with a turret on radial honestly.

**Comment by XElectricX** [comment]
Turrets are in a balanced state, barricades are not. Fix the source of the problem, not the symptom. If barricades can block spit, turrets are not as threatened.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
