### PR TITLE
Adds the TA-40L Rocket Artillery system and some ammo datum fixes for artillery rounds.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
45 points for the system. ~~1 point for 2 warheads.~~ Rockets come in packs of eight now after feedback, 3 points for eight rockets. That's half a reload.

Fires large salvos of 16 rockets in a area of around 5 tiles, they are ~~3~~ 4 light explosion each.

Holds 32 Rockets, and has a .25 reload time between each rocket. Get teammates to help you out.

Has a cooloff of 3 minutes to prevent constant use, could reduce down to one minute to accommodate for reload time.

Credit to Kuro for the sprite.

## Why It's Good For The Game
Interesting, new and cool artillery option for marines if they want to saturate an area with volume of fire rather than quality of fire.

## Changelog
:cl:
add: TA-40L Multiple Launch Rocket System has been added, it is 45 points in Requisitions and fires large salvos of small 60mm rockets at foes in an indirect arc.
tweak: Some ammo datum names for shells have been renamed, unnoticeable from a player perspective, they now specify they are shells instead of just "120mm"
/:cl:

### CODE REVIEW

**Review by Kuro020 — CHANGES_REQUESTED** [review]
Get a sprite loser

**Comment by ilikesaying** [comment]
Hwacha

**Comment by DerpiestBruh** [comment]
Spriteless

**Comment by Goblinu** [comment]
Great, another long range AoE explosion weaponry, like the xenos deosnt have enough of those to deal with already

**Comment by Losenis** [comment]
>Fires large salvos of 16 rockets in a area of around 5 tiles, they are 3 light explosion each.

Mortar and howi ff was bad enough, I picture these things being push wipers

**Comment by MereWalker** [comment]
I love the toys we get for fob defense. Look forward to firing these too close to fob and obliterating the front line.

**Comment by bowlofcereal** [comment]
something of this explosive caliber can destroy entire marine regiments

i hope it has logs to indicate who fired it because i can already see what's gonna happen

**Comment by Lumipharon** [comment]
buying multiple of these and linking them together for a super barrage is going to be true hell.

**Comment by Al-1ce** [comment]
If the sprites are inspired by Foxhole I will cream

**Comment by UsernameIs-UnAvailable** [comment]
Fucking why, marines already have the mortar, the howi ,CAS and the OB. They do not need a fifth offscreen fire support system.

**Comment by Pariah919** [comment]
Okay, sprites acquired

**Review by Kuro020 — APPROVED** [review]

**Comment by Kuro020** [comment]
> Fucking why, marines already have the mortar, the howi, the railgun, CAS and the OB. They do not need a sixth offscreen fire support system.

not enoug, we need MORE

**Comment by Kuro020** [comment]
> > Fucking why, marines already have the mortar, the howi, the railgun, CAS and the OB. They do not need a sixth offscreen fire support system.
> 
> not enough, we need MORE

**Comment by Thegreatspidernonbinary** [comment]
mortar is mid tbh and this would be funny

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 1a7897fb75c0bc591fc470eeb19602cedd44f913
Pull Request: 1603fe3b3bcedc0e88b5d6370eb8617a26856c38
Server: 39862f7d553c85a605709fa41bd5380a2f39c840

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Updated

##### Server Instance
TGMC

##### Merged By
Lewdcifer

##### Revision
Origin: 48bb57ab23241cd1fe25e1c80ec1cfa43da71592
Pull Request: 326990f5c5bcf10f57b6e04ad161c41dc96a4f8e
Server: 9eda513e79e9a6a25c9ef0ba9b659d01bc276131

##### Comment

[GitHub Deployments](https://github.com/tgstation/TerraGov-Marine-Corps/deployments/activity_log?environment=TGS%3A%20TGMC)

**Comment by comfyorange** [comment]
#### Test Merge Removed

**Comment by comfyorange** [comment]
#### Test Merge Deployed

##### Server Instance
TGMC

##### Merged By
Tiviplus

##### Revision
Origin: 48bb57ab23241cd1fe25e1c80ec1cfa43da71592
Pull Request: 326990f5c5bcf10f57b6e04ad161c41dc96a4f8e
Server: fa36ab454b4d3585ace1d08747ae259292dba298

**Comment by tyeagg** [comment]
in its current state really sucks buff the cooldown by allot

**Comment by Dolth** [comment]
45 points?

**Comment by Ducky-Momo** [comment]
spotters have said that it's...really, really weak

**Comment by Losenis** [comment]
My very first interaction with this was learning that it got TMd due to getting FF'd days ago. It was an extremely forgiving FF at that, so I don't know if it's able to do anything at all to xenos. Feels more like a way to clear the weeds from a maze, honestly.

**Comment by DemonOfHatred** [comment]
Do this but for xenos instead so xenos have artillery

**Pull request merged**
