### PR TITLE
Port more AI core displays & holograms

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
I stole AI cores from Polaris, and it's downstream.
Also stole the carp hologram.

## Why It's Good For The Game
More options are good. 

## Changelog
:cl:
add: Added 3 new AI cores from polaris
add: Added 1 new AI hologram
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
Box fort doesnt even fit out perspective

**Comment by lbnesquik** [comment]
I don't think it fits any perspective.

**Review by Kuro020 — CHANGES_REQUESTED** [review]
the box is a no, the other ones, sure

**Comment by lbnesquik** [comment]
I'll bring in the version Greyson gave me

**Comment by lbnesquik** [comment]
I removed the cardboard box. It doesn't really fit, and the sprites just don't quite blend with the others.

**Pull request merged**
