### PR TITLE
deletes cat ears

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
cat ears are a bad meme item that will never be used seriously by admins and only contribute to giving specific players meme items because they prayed for them

## Why It's Good For The Game
i too hate bad meme items

## Changelog
:cl:
del: Removed catgirl ears
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -69. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Pariah919** [comment]
> You currently have a negative Fix/Feature pull request delta of -69.
> 
Nice

**Comment by Hughgent** [comment]
Gotta get All the things your deleting from all files

ctrl+shift+f is your friend

**Review by Hughgent — APPROVED** [review]

**Comment by Pariah919** [comment]
small victories

**Comment by ondrej008** [comment]
huge losses

**Comment by AtlasRules** [comment]
Win!

**Comment by David-Stormwell** [comment]
o7

**Pull request merged**
