### PR TITLE
adds fc ghmme to valhalla

### LINKED ISSUE #14446: No FC GHMME Vendor in Valhalla
### Description

There is a FC Point vendor but no GHMME, likely someone simply forgot about it.

### Test Merges

```#14258: 'Reverts Hyperscale 3' by lKiseki at commit f1eedc1e4a
#14393: 'Flare Rebalance: Removes infinite flares and adds a flare crate to req' by KrabSpider at commit 0bf22a2d60
#14378: 'Bump rust-g to 3.0.0' by vvvv-vvvv at commit d01a959374
#14261: 'Adds Beginner loadouts.' by Xander3359 at commit a98df94476
#14389: 'Gorger Feast is AOE + lower cooldown' by Xander3359 at commit 22ada19c83```

### Reproduction Steps

Go to Valhalla. 
No GHMME vendor for FC. 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by coldironwarrior**
## About The Pull Request
title. took two tiles from the moth room to accomplish this, may moff have mercy on my soul
image

also fixes two things that had no areas

## Why It's Good For The Game

fixes #14446

## Changelog

:cl:
add: FC ghmme is added to valhalla
/:cl:

### CODE REVIEW

**Comment by Looking4bros** [comment]
Have to take one whole step to access both unique vendors, it's Joever.

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Map merger is required, please use strongdmm for map changes. There's no way moving a couple walls causes 7.2k changes.

**Comment by coldironwarrior** [comment]
it was indeed a mistake. deleting and making new branch for this one. rebase didn't clean it up ???

**Comment by ivanmixo** [comment]
Holy god never rebase PR branches for the love of god. This is also easily undoable with `git reset 12ac552 --hard` followed by `git push -f` though

**Pull request closed without merging**
