### PR TITLE
Injector Jaeger Module

### PR DESCRIPTION
**Pull request by goose4429**
## About The Pull Request

Add module similar to medical one. Holds injectors only.
Sprite credits: The Lord (Saro)

## Why It's Good For The Game

Injectors take only 1 weight/space, but most slotted items do not allow you to utilize this. Only backpack and injector pouches, which are smaller. Also makes pouch/module distribution more uniform.
Taking pills into medical module is still more space-efficient, but at least it's somewhat better.

(Sprite is little different in actual game)

image

 

## Changelog
:cl:
add: added Injector Jaeger module
/:cl:

### CODE REVIEW

**Comment by FosterGrime-Heymynameslouie** [comment]
based pr spede merhg

**Review by Kuro020 — CHANGES_REQUESTED** [review]
This is a copy paste sprite from the medical module.
Make a original sprite for it.

**Comment by goose4429** [comment]
> This is a copy paste sprite from the medical module. Make a original sprite for it.

It is. Do we really need new sprites? It's still medical by its purpose.

**Comment by Kuro020** [comment]
> > This is a copy paste sprite from the medical module. Make a original sprite for it.
> 
> It is. Do we really need new sprites? It's still medical by its purpose.

yes we do

**Comment by goose4429** [comment]
> > > This is a copy paste sprite from the medical module. Make a original sprite for it.
> > 
> > 
> > It is. Do we really need new sprites? It's still medical by its purpose.
> 
> yes we do

Ok, will do I guess

**Review by TiviPlus — APPROVED** [review]

**Comment by David-Stormwell** [comment]
crying, opened this PR thinking someone else was creative and had the will to code it but alas, simply a storage crepe pr

**Pull request merged**
