### PR TITLE
Desant fix

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
Fixes razor, sticky and fire effecting desants when they shouldn't really.
## Why It's Good For The Game
Less strange interactions on top of a tank
## Changelog
:cl:
fix: fixed tank desants being effected by razor, sticky and fire the vehicle crosses
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
Do we not have a flag we can use here that they get when riding?

**Comment by Lumipharon** [comment]
This is good to merge, all 3 already check for flags, but we want desants explicitly to be immune even without the flags.

**Comment by Lumipharon** [comment]
@TiviPlus pls

**Review by TiviPlus — COMMENTED** [review]
I hope you realize thsi code is disgusting

**Pull request merged**
