### PR TITLE
Style hats have helmet-level armor

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
I was told to atomize this into parts, so style hats have helmet armor now.
## Why It's Good For The Game
Suffering for your drip is sadge, and style in general is about form and function.
## Changelog
:cl:
balance: Style hats now have helmet-level armor.
/:cl:

### CODE REVIEW

**Comment by Barnet2** [comment]
Good PR. "Muh realism" isn't exactly applicable when anti-decap exists, even more so with equalizer modules.

**Comment by chizzy376** [comment]
Based

**Comment by Al-1ce** [comment]
> Suffering for your drip is sadge, and style in general is about form and function.

Copecode.

**Comment by Lumipharon** [comment]
> Good PR. "Muh realism" isn't exactly applicable when anti-decap exists, even more so with equalizer modules.

I can remove anti decap if you'd like

**Comment by Dawson1917** [comment]
I already said this in the last PR but xenos should be able to notice and change how they attack to take advantage of weaknesses in a marine's equipment. We already have too many stupid ways to hide what armor class you're wearing, have multiple weapons for multiple roles equipped at once, and ways to have the gear to do the job of multiple marine roles at once. 
Seeing a marine not wearing armor on a bodypart should signal to xenos that they should target that part when fighting that marine, just like seeing a shotgun should tell you not to stick around in close range. Giving magical armor to people who want to dress as civilians or anime characters is hugboxing and takes away options in combat.

**Comment by Barnet2** [comment]
> I can remove anti decap if you'd like

Even then, you cannot tell me this game is trying to portray realism. If you want the hard mode, we still have the old sprite and armor values in a surplus.

**Comment by FosterGrime-Heymynameslouie** [comment]
to quote previous comment on [#12201](https://github.com/tgstation/TerraGov-Marine-Corps/pull/12201)

> These should have way less armor than actual combat helmets. If people want to wear fashion gear, they should open themselves up to being taken advantage of by a player that switches their limb targeting to take advantage of the marine wearing a piece of cloth on their head in a warzone.
> There's already so much cosmetic bloat that even telling if a marine is wearing light/medium/heavy is a challenge (especially if they hide their armor under a cloak). Giving clothing that by all reasoning should have none or massively less armor than a combat helmet the same armor and magical decap protection flushes the entire idea of adapting your approach to what marines have equipped down the toilet.
> 
 I agree with this as an average slouch hat user, you trade protection for drip and thats what makes it fun, knowing your decision has consequences makes the decision even more meaningful!
 
giving cosmetic stuff armor similar to normal armor is pretty stinky with less risk, less impact, meaningless DRIP also makes the cosmetics itself a spineless decision, which is kinda shame since they look good
 
 should atleast make them be able to be decappable by xenos




> who cares cosmetics are cool

baby proof cosmetics lol

**Comment by Joe13413** [comment]
berets and bandanas and shit are only cool because the people who wear them are risking a lot imo. If style hats get the same amount of armor that helmets do, then you'll see a lot of people with these armored berets and hats and they stop having a meaning. People who wear berets are willing to sacrifice protection to look cool, but if this is merged then it'd actually be even BETTER to wear style line helmets compared to regular helmets, as im pretty sure they hide modules. Removing the risk from berets just means that there isn't much reason NOT to use them, and we'll be oversaturated with berets and campaign hats.

**Comment by MiniMeatwad** [comment]
> > Good PR. "Muh realism" isn't exactly applicable when anti-decap exists, even more so with equalizer modules.
> 
> I can remove anti decap if you'd like

Do it now, hat wearers have no rights

**Comment by MiniMeatwad** [comment]
> Remove all decap protection from vanity hats, even though I wear vanity hats. I will suffer and cope for my drip, but I will look cool as fuck dying.

As it should be, the only right a hat wearer should get is the right to die badass.

**Comment by breadhunt** [comment]
Drip is cool because it's a sacrifice, the mark of a true marine. That's what makes it cool. Having a big sign over your head screaming "I'M A BADASS"  and if you want to look like american war hero John Rambo you've got to earn the title.

**Comment by isotope436** [comment]
even though this was merged i like the idea that xeno players still pretend like they aim anywhere but right arm and hand lmao

**Pull request merged**
