### PR TITLE
jaeger helmet hides hair

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
hair breaks on most of the jaeger helmets
this fixes that

## Why It's Good For The Game
image
image

## Changelog
:cl:
fix:jaeger helmets hide hair 
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -288. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by David-Stormwell** [comment]
based

**Comment by SplinterGP** [comment]
it doens't break any jaeger helmet but this one, because it is too small, lol

**Comment by Smudged** [comment]
No, not like this

**Comment by Kuro-ai** [comment]
that's a little extreme don't you think

**Comment by neohenry** [comment]
NOOOOOOOOOOOOO I NEED MY HAIR TO GET META-TARGETTED

**Comment by TG-Eris** [comment]
Elsa, Kooters, and the other high-ponytail crowd screamed out in agony.

**Comment by SpaceLoveSs13** [comment]
Nooooooo my white hair meta!!! Get a better fix.

**Pull request closed without merging**
