### PR TITLE
Kills rocket spam

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
All rocket launchers now require full wielding to be fired.

Rockets are typically extremely accurate (and most explode on click), additionally rockets like disposable's and even the RR can easily be juggled to spam multiple rockets with almost no delay, which is cringe.
## Why It's Good For The Game
Rocket juggling is bad.
## Changelog
:cl:
balance: All rocket launchers require full wielding to be fired
/:cl:

### CODE REVIEW

**Comment by Naaanii** [comment]
This was left on the RR because it isn't as oppressive as SADAR for the one tap memory. Is this another certified salt PR?

**Comment by Lumipharon** [comment]
> This was left on the RR because it isn't as oppressive as SADAR for the one tap memory. Is this another certified salt PR?

honk, edited your message instead of replied.

You can juggle RR's roundstart by taking both of them. If someone wants to tweak the wield time that's another conversation, but right now it functionally means nothing.

**Comment by Oscari-pog** [comment]
Would call this a salt PR but I too have experienced the fucking instakill that is the RR juggle

**Comment by Naaanii** [comment]
> > This was left on the RR because it isn't as oppressive as SADAR for the one tap memory. Is this another certified salt PR?
> 
> honk, edited your message instead of replied.
> 
> You can juggle RR's roundstart by taking both of them. If someone wants to tweak the wield time that's another conversation, but right now it functionally means nothing.

Ohh lmao. Should probably make disposables not as good too but needs another PR.

**Comment by ivanmixo** [comment]
Not addressing the spamability which is the bigger issue with them?

**Comment by Lumipharon** [comment]
> Not addressing the spamability which is the bigger issue with them?

Its a separate issue, for a separate pr.

**Comment by ScheveningenZonn** [comment]
I wasn't even aware this was the case, since I always full wielded rockets before firing. Looks good to me.

**Pull request merged**
