### PR TITLE
Removes dupe TGMC uniform from Clothing vendor

### PR DESCRIPTION
**Pull request by Naaanii**
## About The Pull Request
Title.
image
## Why It's Good For The Game
Less bloat.
## Changelog
:cl:
del: Removed dupe of TGMC uniform.
/:cl:

### CODE REVIEW

**Comment by revelation-8468** [comment]
have you tested that this won't absolutely fuck over loadouts that use the second TGMC uniform

**Comment by Naaanii** [comment]
> have you tested that this won't absolutely fuck over loadouts that use the second TGMC uniform

It probably will for people using the former
image
But I think they can just remake their loadouts and at most just need to get the uniform.

**Comment by ivanmixo** [comment]
Its better to fix is as soon as possible rather than let the problem with people making loadouts with it get even worse

**Comment by Arctrooper8** [comment]
This has been proposed before but maints shot it down due to it messing with loadouts.

**Pull request merged**
