### PR TITLE
Adds ammo counters to most spec weapons and launchers

### PR DESCRIPTION
**Pull request by MoXuT0**
## About The Pull Request

Like every gun now has ammo counter, cmon.

## Changelog

:cl:
tweak: Added ammo counter to most spec weapons and grenade launchers.
/:cl:

### CODE REVIEW

**Comment by DominikPanic** [comment]
Have you tested this on all the weapons you are adding it for? Some may be missing sprites.

**Comment by MoXuT0** [comment]
I'm pretty sure ammo hud has sprites for every bullet, even some predator ones.

**Comment by DominikPanic** [comment]
Of course it's unlikely to cause major issues, but still you should test your PRs anyway.

**Comment by Rohesie** [comment]
Use `add` or `tweak`. This is not really a balance change, more of a QoL one.

**Pull request merged**
