### PR TITLE
Human head compression

### PR DESCRIPTION
**Pull request by Lumipharon**
## About The Pull Request
All ungas are to undergo mandatory head molding.

TGMC has bizarre head sprites that are this strange egg shape when looking south or north, making their heads notably taller compared to facing west or east.

This PR brings their head shape back in line with the side view, and the shape of other servers as well.
Incidentally the majority of head related items were made for the correct head shape, so currently have cropping issues that are only not apparent due to hair and headwear usually hiding it.

Edited the sprites of various tgmc specific items to fit the correct headsize, such as masks. Helmets are supposed to be larger than the head so they're unchanged, although this does make it far easier to have smaller (compared to jaeger/SOM) helmets than it is currently.

## Why It's Good For The Game
Changing egg size is bad

## Changelog
:cl:
imageadd: Human head shape is now consistant
/:cl:

### CODE REVIEW

**Comment by lKiseki** [comment]
mmm... egg...

**Comment by XSlayer300** [comment]
eg

**Comment by ilikesaying** [comment]
hard boiled

**Comment by TiviPlus** [comment]
merge from master to fix the map edit

**Comment by Lumipharon** [comment]
> merge from master to fix the map edit

Done, that really messed my vsc around, truly cursed.

**Comment by ivanmixo** [comment]
Doesnt provide screenshots..

**Comment by Lumipharon** [comment]
> Doesnt provide screenshots..

Lazy. Just look at the icondiff.

It's changing it to the same head shape as every other server.

**Pull request merged**
