### PR TITLE
New, More distinct B18 sprite

### PR DESCRIPTION
**Pull request by Metroidlover**
## About The Pull Request

B18 squad

## Why It's Good For The Game

Makes the B18 more distinct from the other armors and it looks cool

## Changelog
:cl: Compadre Sonoliento(sprites) Kuro(Idea) MetroidLover(Editing and recoloring sprites)
imageadd: New B18 sprites with a darker look and glowing colored visor
/:cl:

### CODE REVIEW

**Comment by Kuro-ai** [comment]
It looks cool and **E D G Y** so we need definetely need it in the game

**Comment by Metroidlover** [comment]
The eyes may get changed to orange

**Comment by sleepyretard** [comment]
I'd suggest changing the eyes to the glass visors I had sent Kuro. Coloured visors end up looking like hot doo-doo balls, and IMO only the intent eyes would end up looking 'ok'.

167, 194, 182 RGB w/ 126 alpha is the pyrotech's enclosed visor, for reference, and it looks pretty good.

**Comment by Metroidlover** [comment]
Eyes are now orange and it no longer looks like the armor exposes the arms

**Comment by Rohesie** [comment]
Any chance to color the `_m` and `_s` variants?

**Comment by Metroidlover** [comment]
I can attempt to do so, but I can not promise amazing quality

**Comment by DominikPanic** [comment]
Did you touch stuff like the dutch cap? The diffbot shows it's modified

**Comment by Rohesie** [comment]
Conflicting PR is merged. Solve the conflicts and we can test this.

**Comment by Rohesie** [comment]
Still conflicting.

**Comment by Metroidlover** [comment]
Don't merge give me a moment

**Comment by Metroidlover** [comment]
Okay now it should be good

**Comment by Metroidlover** [comment]
Oh nevermind, some things got changed on accident, god I hate this

**Comment by Metroidlover** [comment]
There we go, no conflicts and only my intended changes

**Pull request merged**
