### PR TITLE
Fixes evil emote runtime

### PR DESCRIPTION
**Pull request by DominikPanic**
Fixes: #1560
Fixes: #1570

### CODE REVIEW

**Comment by Rohesie** [comment]
Is this for corgis to use `/datum/emote/living/carbon/human/run_emote()`?

**Comment by DominikPanic** [comment]
> 
> 
> Is this for corgis to use `/datum/emote/living/carbon/human/run_emote()`?

the base run_emote runs can_run_emote, before that this was running it before checking if you were allowed to

**Comment by Rohesie** [comment]
Why is `get_paygrade()` being defined at a mob level, though, if it's only checked in `/datum/emote/living/carbon/human/run_emote()`? Is something non-human calling that proc?

**Comment by DominikPanic** [comment]
> 
> 
> Why is `get_paygrade()` being defined at a mob level, though, if it's only checked in `/datum/emote/living/carbon/human/run_emote()`? Is something non-human calling that proc?
> 
> Maybe try a rubber duck method here, explaining your change.

````
/datum/emote/proc/run_emote(mob/user, params, type_override, intentional = FALSE, prefix)
	. = TRUE
	if(!can_run_emote(user, TRUE, intentional))
		return FALSE
```
If I overwrite that proc
```
/datum/emote/living/carbon/human/run_emote(mob/living/carbon/human/user, params, type_override, intentional = FALSE, prefix)
	var/paygrade = user.get_paygrade()
	if(paygrade)
		prefix = "<b>[paygrade]</b> "
	return ..()
```
I have to ensure I either check if it can be ran, or define get_paygrade at the mob level.

**Pull request merged**
